### ISSUE TITLE
How do deal the error: 'module' has no attribut 'get_start_method'?

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#100]
when using tools/dist_train.sh to train the model, an error happens like:

Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
    main()
  File "./tools/train.py", line 57, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/usr/local/lib/python2.7/dist-packages/mmdet-0.5.2+3f5df4f-py2.7.egg/mmdet/apis/env.py", line 13, in init_dist
    if mp.get_start_method(allow_none=True) is None:
AttributeError: 'module' object has no attribute 'get_start_method'

how to deal with it? anyone has some solutions? Thank you!

**Comment by hellock** [comment]
mmdetection does not support python 2, you need to use python 3 instead.
