### ISSUE TITLE
[Reimplementation] 

### ISSUE THREAD

**Issue by naiyuhh** [open-mmlab/mmdetection#10009]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I used dino to train the crowdhuman dataset, load the crowdhuman odgt annotation file to report an error, and only modify data_type=‘CrowdHumanDataset’

Traceback (most recent call last):
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "c:\users\cao\mmdetection\mmdet\datasets\base_det_dataset.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\dataset\base_dataset.py", line 247, in __init__
    self.full_init()
  File "c:\users\cao\mmdetection\mmdet\datasets\base_det_dataset.py", line 58, in full_init
    self.data_list = self.load_data_list()
  File "c:\users\cao\mmdetection\mmdet\datasets\coco.py", line 64, in load_data_list
    self.coco = self.COCOAPI(local_path)
  File "c:\users\cao\mmdetection\mmdet\datasets\api_wrappers\coco_api.py", line 25, in __init__
    super().__init__(annotation_file=annotation_file)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\pycocotools\coco.py", line 82, in __init__
    dataset = json.load(f)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 1379)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\runner\loops.py", line 43, in __init__
    super().__init__(runner, dataloader)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\runner\base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\runner\runner.py", line 1333, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main()
  File "tools/train.py", line 122, in main
    runner.train()
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\runner\runner.py", line 1656, in train
    self._train_loop = self.build_train_loop(
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\runner\runner.py", line 1448, in build_train_loop
    loop = LOOPS.build(
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\CAO\.conda\envs\mm3.0\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: __init__() missing 2 required positional arguments: 'doc' and 'pos'

### Environment

python 3.8
PyTorch: 1.7.1+cu101
mmdetection 3.0.0rc6

**Comment by hhaAndroid** [comment]
@naiyuhh Please provide complete configuration information

**Comment by naiyuhh** [comment]
_base_ = [
    '../dino/dino-4scale_r50_8xb2-12e_coco.py'
]
model = dict(
    as_two_stage=True,

    #backbone = dict(
    #    frozen_stages = 1,
    #),
    bbox_head = dict(
        num_classes=1,
))


dataset_type = 'CrowdHumanDataset'
data_root = 'myCH/crowedHuman/coco/'

train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        data_root=data_root,
        ann_file='annotation_train.odgt',
        data_prefix=dict(img='CrowdHuman_train/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=32)))
val_dataloader = dict(
    batch_size=2,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotation_val.odgt',
        data_prefix=dict(img='CrowdHuman_val/'),
        test_mode=True))
test_dataloader = val_dataloader

optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(
        type='AdamW',
        lr=0.000005,  # 0.0002 for DeformDETR  #原始0.0001 
        weight_decay=0.000002),
    clip_grad=dict(max_norm=0.1, norm_type=2),
    paramwise_cfg=dict(custom_keys={'backbone': dict(lr_mult=0.1)})
)

val_evaluator = dict(
    type='CrowdHumanMetric',
    ann_file=data_root + 'annotation_val.odgt',)
test_evaluator = val_evaluator

work_dir = 'G:/LCY/源码/mmdetection-dev-3.x/work_dirs/dinoCHdata'
