### ISSUE TITLE
Random crop segmentation

### ISSUE THREAD

**Issue by Monica2511** [open-mmlab/mmdetection#1001]
i get the error when augmentation data by random crop ?

> Traceback (most recent call last):
File "tools/train.py", line 97, in 
main()
File "tools/train.py", line 93, in main
logger=logger)
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/apis/train.py", line 65, in train_detector
_non_dist_train(model, dataset, cfg, validate=validate)
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/apis/train.py", line 228, in _non_dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/anhtran/instance_segmentation/mmcv/mmcv/runner/runner.py", line 358, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/anhtran/instance_segmentation/mmcv/mmcv/runner/runner.py", line 260, in train
for i, data_batch in enumerate(data_loader):
File "/home/anhtran/.conda/envs/project/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 582, in next
return self._process_next_batch(batch)
File "/home/anhtran/.conda/envs/project/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
File "/home/anhtran/.conda/envs/project/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/anhtran/.conda/envs/project/lib/python3.5/site-packages/torch/utils/data/_utils/worker.py", line 99, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/datasets/custom.py", line 193, in getitem
data = self.prepare_train_img(idx)
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/datasets/custom.py", line 272, in prepare_train_img
scale_factor, flip)
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/datasets/transforms.py", line 118, in call
mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
File "/home/anhtran/instance_segmentation/mmdetection/mmdet/datasets/transforms.py", line 118, in 
mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
File "/home/anhtran/instance_segmentation/mmcv/mmcv/image/transforms/geometry.py", line 184, in impad
assert shape[i] >= img.shape[i]
AssertionError

**Comment by hellock** [comment]
It does not support mask cropping currently. You may need to implement it by yourself.
