### ISSUE TITLE
Is there no supports for building custom dataset in 3.x?

### ISSUE THREAD

**Issue by DableUTeeF** [open-mmlab/mmdetection#10055]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

I've been using earlier version of mmdet with these imports with a lot of nice results.
```
from mmdet.datasets.custom import CustomDataset
from mmdet.datasets.builder import DATASETS
```
However I wanted to try the new mmyolo but it requires mmdet>v3.x. And when I install those I found out that I physically can't build a new `Dataset` object, let alone a custom one.

All documentations I found are simply telling me to use COCO and nothing else.

The reason I don't use COCO because it often has problems when file names aren't integer + .png and after a quick check I got this error.
```
Traceback (most recent call last):
  File "/media/palm/BiggerData/conda/yolo6/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/media/palm/BiggerData/mmyolo/mmyolo/datasets/yolov5_coco.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/media/palm/BiggerData/conda/yolo6/lib/python3.8/site-packages/mmdet/datasets/base_det_dataset.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "/media/palm/BiggerData/conda/yolo6/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 250, in __init__
    self.full_init()
  File "/media/palm/BiggerData/mmyolo/mmyolo/datasets/yolov5_coco.py", line 43, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/media/palm/BiggerData/conda/yolo6/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 772, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```
I have some ideas about how it happened but if possible I'd rather use custom dataset.

### Reproduces the problem - code sample

test.py

```python
from mmdet.datasets.custom import CustomDataset
from mmdet.datasets.builder import DATASETS
```

### Reproduces the problem - command or script

```
python test.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/palm/PycharmProjects/parasite_yolo/train.py", line 1, in <module>
    from mmdet.datasets.custom import CustomDataset
ModuleNotFoundError: No module named 'mmdet.datasets.custom'
```

**Comment by DableUTeeF** [comment]
I thought I was kinda clear in my question but apparently not.

The files [here](https://github.com/open-mmlab/mmdetection/tree/3.x/mmdet/datasets) are missing `custom.py` and `builder.py` which were essential for building list-based custom dataset in 2.x and below. The master branch has those file yes, but not 3.x.

**Comment by Chop1** [comment]
I believe custom is replaced by base_det_dataset

**Comment by Asaad-Nasrallah** [comment]
try this
