### ISSUE TITLE
Error reported by the inference model in running benchmark. py

### ISSUE THREAD

**Issue by Lucky-zi-lin** [open-mmlab/mmdetection#10124]
When testing FPS using the benchmark. py script 'inference' model, it was shown that the model did not test_ step method.
Test code is mask_ rcnn

Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 133, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 129, in main
    benchmark.run(args.repeat_num)
  File "/media/a408/DATA/xia/project/mmdetection-3.0/mmdet/utils/benchmark.py", line 100, in run
    results.append(self.run_once())
  File "/media/a408/DATA/xia/project/mmdetection-3.0/mmdet/utils/benchmark.py", line 215, in run_once
    self.model.test_step(data)
  File "/home/a408/anaconda3/envs/mmdet_3.0_torch1.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'test_step'

**Comment by TheGreatTreatsby** [comment]
i got the same problem，but i wonder does the dataset mode result contains the inference mode results？

**Comment by okt7760** [comment]
i got the same problem
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 133, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 129, in main
    benchmark.run(args.repeat_num)
  File "e:\git\mmdetection\mmdet\utils\benchmark.py", line 109, in run
    results.append(self.run_once())
  File "e:\git\mmdetection\mmdet\utils\benchmark.py", line 224, in run_once
    self.model.test_step(data)
  File "C:\Users\5oo\.conda\envs\mmlabv3\lib\site-packages\torch\nn\modules\module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(

**Comment by Yuxinyi-Qiyu** [comment]
i met the same problem, and solved this by replacing the line222 at https://github.com/open-mmlab/mmdetection/blob/main/mmdet/utils/benchmark.py#L222  with 'self.model.module.test_step(data)'.


i think this is a bug in the code, cause DistributedDataParallel doesn't have 'test_step', only using DistributedDataParallel.module could make the code run 😢, but I'm not sure whether this will effect the speed of model.

**Comment by lijoe123** [comment]
I got the same problem. And can you tell me about the difference about `ms/img `and` ms/batch`?

**Comment by gabby647** [comment]
i got the same problem.my solutions is use dataset instead of inference in --task place.
