### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test_dataloader'

### ISSUE THREAD

**Issue by schneizelvibritannia** [open-mmlab/mmdetection#10127]
**Environment:**
torch==1.12.1 
mmcv==2.0.0
mmdet==3.0.0

I have a model which I am trying to inference using CPU. 

this is my code

```
from PIL import Image
import cv2
import numpy as np
import pandas as pd 
import cv2
import os
from mmdet.models.detectors import BaseDetector
from mmdet.apis import init_detector, inference_detector
import mmcv
from numpy import array, float32



config_file = 'models/table-identification/faster_rcnn_r50_fpn_1x_voc0712/faster_rcnn_r50_fpn_1x_voc0712.py'
checkpoint_file = "models/table-identification/faster_rcnn_r50_fpn_1x_voc0712/epoch_15.pth"
model = init_detector(config_file, checkpoint_file, device='cpu')
```

when I run the file I keep getting this error

```
Traceback (most recent call last):
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/mmengine/config/config.py", line 51, in __getattr__
    value = super().__getattr__(name)
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/mmengine/config/config.py", line 47, in __missing__
    raise KeyError(name)
KeyError: 'test_dataloader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 16, in <module>
    model = init_detector(config_file, checkpoint_file, device='cpu')
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/mmdet/apis/inference.py", line 94, in init_detector
    test_dataset_cfg = copy.deepcopy(config.test_dataloader.dataset)
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/mmengine/config/config.py", line 894, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/user829/Warehouse/Projects/colab_envv/env/lib/python3.8/site-packages/mmengine/config/config.py", line 53, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'test_dataloader'
```

config_file: [config_file](https://drive.google.com/file/d/1v81Uv5N9OvVPNoorlDnwr3jZybZ_t00y/view?usp=share_link)

checkpoint: [check_point](https://drive.google.com/file/d/1tojTPLVAFmSsjHMlTMy9lzOGQN6zsZxY/view?usp=share_link)

**Comment by Extra-rich** [comment]
hello, have you solved this problem?

**Comment by jacoverster** [comment]
I noticed that there has been a major update recently, I found this guide in die docs: https://mmdetection.readthedocs.io/en/v3.0.0/migration/config_migration.html

**Comment by Extra-rich** [comment]
How do you fix this problem？

**Comment by LeungKalan** [comment]
> > How do you fix this problem？
> 
> Hi, you need to update your old config file to match the new format as described in the link above. The specific part causing the above error is under https://mmdetection.readthedocs.io/en/v3.0.0/migration/config_migration.html#dataloader-and-dataset-configuration
I still haven't found a solution after querying the migration configuration file. Can you give me a clear indication?


> > How do you fix this problem？
> 
> Hi, you need to update your old config file to match the new format as described in the link above. The specific part causing the above error is under https://mmdetection.readthedocs.io/en/v3.0.0/migration/config_migration.html#dataloader-and-dataset-configuration

Hi. I still haven't found a solution after querying the config migration file. Could you give me some clear indication?

**Comment by willcray** [comment]
@LeungKalan this issue occurred for me when trying to run a mmdet 2.x version model and config on a server that was running mmdet 3.x. The issue was resolved once I trained a model using mmdet 3.x and used a 3.x compatible model config.

**Comment by bshakya77** [comment]
Hello @LeungKalan,

I am trying to evaluate SAHI with TOOD model. I get the same issue. I am using mmdet 3.3.0 but the current configuration is 2.x. Could you please provide me with 3.x compatible model config your used?

Thank you.

Regards,
Bijay
