### ISSUE TITLE
about crowddet 

### ISSUE THREAD

**Issue by XianHYe** [open-mmlab/mmdetection#10137]
`Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 120, in main
    runner.train()
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\runner\runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\runner\loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\runner\loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "D:\anaconda3\envs\det3\lib\site-packages\mmengine\model\base_model\base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "D:\anaconda3\envs\det3\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\mmdet3\mmdet\models\detectors\base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "e:\mmdet3\mmdet\models\detectors\two_stage.py", line 190, in loss
    roi_losses = self.roi_head.loss(x, rpn_results_list,
  File "e:\mmdet3\mmdet\models\roi_heads\multi_instance_roi_head.py", line 159, in loss
    bbox_results = self.bbox_loss(x, sampling_results)
  File "e:\mmdet3\mmdet\models\roi_heads\multi_instance_roi_head.py", line 110, in bbox_loss
    bbox_loss_and_target = self.bbox_head.loss_and_target(
  File "e:\mmdet3\mmdet\models\roi_heads\bbox_heads\bbox_head.py", line 323, in loss_and_target
    losses = self.loss(
  File "e:\mmdet3\mmdet\models\roi_heads\bbox_heads\multi_instance_bbox_head.py", line 415, in loss
    loss_0 = self.emd_loss(bbox_pred[:, 0:4], cls_score[:, 0:2],
  File "e:\mmdet3\mmdet\models\roi_heads\bbox_heads\multi_instance_bbox_head.py", line 475, in emd_loss
    bbox_pred = bbox_pred.reshape(-1, self.num_classes, 4)
RuntimeError: shape '[-1, 10, 4]' is invalid for input of size 8192`

Does crowddet support multiple classes detection？
I tried to train crowddet on my own dataset which consists of 10 classes and this error occurred

**Comment by GolvenDong** [comment]
I also meet the same problem when i trained on my multiple classes dataset
