### ISSUE TITLE
ValueError: matrix contains invalid numeric entries

### ISSUE THREAD

**Issue by WinnerMeat** [open-mmlab/mmdetection#10141]
Thanks for reporting the unexpected results and we appreciate it a lot.

Checklist

I have searched related issues but cannot get the expected help.
I have read the [FAQ documentation](https://mmcv.readthedocs.io/en/latest/trouble_shooting.html) but cannot get the expected help.
The unexpected results still exist in the latest version.
Describe the Issue
In my use '.. The following error occurs when training a custom dataset (coco format) with a configuration file for /configs/detr/detr_r50_8xb2-150e_coco.py'

Reproduction

Did you make any modifications on the code? Did you understand what you have modified?
I modified some hyperparameters in the config file
Environment

Please run python -c "from mmcv.utils import collect_env; print(collect_env())" to collect necessary environment information and paste it here.
OrderedDict([('sys.platform', 'win32'), ('Python', '3.8.16 | packaged by conda-forge | (default, Feb 1 2023, 15:53:35) [MSC v.1929 64 bit (AMD64)]'), ('CUDA available', True), ('numpy_ra
ndom_seed', 2147483648), ('GPU 0,1', 'NVIDIA GeForce RTX 3090'), ('CUDA_HOME', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3'), ('NVCC', 'Cuda compilation tools, release 1
1.3, V11.3.109'), ('MSVC', '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.29.30148 版'), ('GCC', 'n/a'), ('PyTorch', '1.13.0+cu116'), ('PyTorch compiling details', 'PyTorch built with:\n
C++ Version: 199711\n - MSVC 192829337\n - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n - Intel(R) MKL-DNN v2.6.0
(Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n - OpenMP 2019\n - LAPACK is enabled (usually provided by MKL)\n - CPU capability usage: AVX2\n - CUDA Runtime 11.6\n - NVCC arc
hitecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,c
ode=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n - CuDNN 8.3.2 (built aga
inst CUDA 11.5)\n - Magma 2.5.4\n - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/build
er/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/i
nclude -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=
1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK
=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n'), ('TorchVision', '0.14.0+cu116'), ('OpenCV', '4.7.0'), ('MMEngine', '0.7.2'), ('MMCV', '2.0.0'), ('MMCV Compiler', 'MSVC 192829924'), ('MMCV CUDA C
ompiler', '11.6')])
![image](https://user-images.githubusercontent.com/53172668/231527590-a7f3086e-334d-4f8d-b846-2e5788ed82a5.png)

Traceback (most recent call last):
File "D:/userDocument/mmdetection/tools/train_detr_insulator.py", line 102, in
runner.train()
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1706, in train
model = self.train_loop.run() # type: ignore
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 96, in run
self.run_epoch()
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 112, in run_epoch
self.run_iter(idx, data_batch)
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 128, in run_iter
outputs = self.runner.model.train_step(
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 114, in train_step
losses = self._run_forward(data, mode='loss') # type: ignore
File "D:\userDocument\Anaconda\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 326, in _run_forward
results = self(**data, mode=mode)
File "D:\userDocument1\Anaconda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
return forward_call(*input, **kwargs)
File "d:\userdocument\mmdetection\mmdet\models\detectors\base.py", line 92, in forward
return self.loss(inputs, data_samples)
File "d:\userdocument\mmdetection\mmdet\models\detectors\base_detr.py", line 101, in loss
losses = self.bbox_head.loss(
File "d:\userdocument\mmdetection\mmdet\models\dense_heads\detr_head.py", line 186, in loss
losses = self.loss_by_feat(*loss_inputs)
File "d:\userdocument\mmdetection\mmdet\models\dense_heads\detr_head.py", line 227, in loss_by_feat
losses_cls, losses_bbox, losses_iou = multi_apply(
File "d:\userdocument\mmdetection\mmdet\models\utils\misc.py", line 219, in multi_apply
return tuple(map(list, zip(*map_results)))
File "d:\userdocument\mmdetection\mmdet\models\dense_heads\detr_head.py", line 274, in loss_by_feat_single
cls_reg_targets = self.get_targets(cls_scores_list, bbox_preds_list,
File "d:\userdocument\mmdetection\mmdet\models\dense_heads\detr_head.py", line 360, in get_targets
neg_inds_list) = multi_apply(self._get_targets_single,
File "d:\userdocument\mmdetection\mmdet\models\utils\misc.py", line 219, in multi_apply
return tuple(map(list, zip(*map_results)))
File "d:\userdocument\mmdetection\mmdet\models\dense_heads\detr_head.py", line 406, in _get_targets_single
assign_result = self.assigner.assign(
File "d:\userdocument\mmdetection\mmdet\models\task_modules\assigners\hungarian_assigner.py", line 131, in assign
matched_row_inds, matched_col_inds = linear_sum_assignment(cost)
ValueError: matrix contains invalid numeric entries

**Comment by WinnerMeat** [comment]
The problem has been solved, when the AMP mode is enabled, the data format of storing giou is float16, which is easy to overflow. Turn off AMP mode

**Comment by guangqianzhang** [comment]
but,how to  turn off AMP mode ,could you have some description??thanks!!

**Comment by mchaniotakis** [comment]
Dont use AmpOptimWrapper and dont do --amp as an argument on train.py . I also faced this issue with query inst. Is there a way to fix this issue or go arount it to be able to train with fp16? I can confirm training with fp32 solves the issue.

**Comment by airainday** [comment]
首先python train时没有加--amp参数是默认不开启混合精度训练的。可以检查以下你的配置文件，看看有没有optim_wrapper，有的话替换为下面的即可，
optim_wrapper = dict(
    clip_grad=dict(max_norm=0.1, norm_type=2),
    #loss_scale='dynamic',
    optimizer=dict(lr=0.0001, type='AdamW', weight_decay=0.0001),
    paramwise_cfg=dict(custom_keys=dict(backbone=dict(lr_mult=0.1))),
    #type='AmpOptimWrapper'
    )

**Comment by underlmao** [comment]
> but,how to turn off AMP mode , could you have some description?? Thanks!!

Hi, you should find your config file to change the AMP to False. For me, it is in there as I am using Mask2Former based model. Best!

**Comment by WhatRui** [comment]
我也遇到了同样的问题，请问如何解决的
