### ISSUE TITLE
Please, make the package PyTorch Nightly compatible for M1 Macs

### ISSUE THREAD

**Issue by fablau** [open-mmlab/mmdetection#10142]
Allowing training on MSP device besides CUDA and CPU.

**Motivation**
Since the introduction of PyTorch Nightly, it is now possible to use tell PyTorch to use the embedded GPU of the new M1 chips on Mac. This allows both training and inference to be completed much faster (3x-5x faster, accordingly to my tests)

**Related resources**
[If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/)

**Additional context**
I tried to initiate training with mmdetection on a conda environment with PyTorch Nightly installed on a M1 Max Mac, and I got the following error:

```
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/detectors/two_stage.py", line 174, in loss
    rpn_losses, rpn_results_list = self.rpn_head.loss_and_predict(
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 167, in loss_and_predict
    predictions = self.predict_by_feat(
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 233, in _predict_by_feat_single
    return self._bbox_post_process(
  File "/Users/fabrizio/Documents/Working Documents (to backup)/Programmazione PHP:Perl:Java/Python/Music OCR/mmdetection/MacOS/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 284, in _bbox_post_process
    det_bboxes, keep_idxs = batched_nms(bboxes, results.scores,
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmcv/ops/nms.py", line 302, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmengine/utils/misc.py", line 354, in new_func
    output = old_func(*args, **kwargs)
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmcv/ops/nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/fabrizio/anaconda3/envs/openmmlabNIGHTLY/lib/python3.8/site-packages/mmcv/ops/nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device mps:0 not found.
```

It is clear that mmdetection isn't compatible with Nightly and the availability of mps as alternative device besides CUDA and CPU.

**Comment by volkov-maxim** [comment]
Up!

**Comment by YijieLiao** [comment]
So, is that means we can not solve this problem now?RuntimeError: nms_impl: implementation for device mps:0 not found.

**Comment by yrik** [comment]
Or at least any hints on how to implement it. Can make a PR.

**Comment by YijieLiao** [comment]
I have worked done with that, thanks!lol

**Comment by yrik** [comment]
btw, all works for me, I just had to set `%env PYTORCH_ENABLE_MPS_FALLBACK=1` and specify device='mps',

e.g. `model.train(data='runs/coco2yolov5/exp2/data.yaml', epochs=20, imgsz=640, device='mps')`

I have successful trained model using my mac m1.

**Comment by ShiDunKai** [comment]
> I have worked done with that, thanks!lol

how do you do ? thanks

**Comment by bekassyl7** [comment]
Up!

**Comment by insung3511** [comment]
UP AGAIN!

**Comment by smileWCX** [comment]
请问现在mmdetection还不支持mps，RuntimeError: nms_impl: implementation for device mps:0 not found.

**Comment by FiReTiTi** [comment]
There is a workaround [here](https://github.com/open-mmlab/mmdetection/issues/11437).

However, I later get the error: `RuntimeError: roi_align_forward_impl: implementation for device mps:0 not found.`
And the workaround for `nms` does not work for `roi_align`

**Comment by asamiKA** [comment]
> And the workaround for nms does not work for roi_align

I made the following changes to  MMCV's nms.py and roi_align.py.

[mmcv/ops/nms.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/nms.py#L28)

before
```
inds = ext_module.nms(
     bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
```
after
```
 inds = ext_module.nms(
     bboxes.cpu(), scores.cpu(), iou_threshold=float(iou_threshold), offset=offset)
 inds.to(bboxes.device)
 ```

[mmcv/ops/roi_align.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/roi_align.py#L62)

before
```
        output = input.new_zeros(output_shape)
        if ctx.pool_mode == 0:
            argmax_y = input.new_zeros(output_shape)
            argmax_x = input.new_zeros(output_shape)
        else:
            argmax_y = input.new_zeros(0)
            argmax_x = input.new_zeros(0)

        ext_module.roi_align_forward(
            input,
            rois,
            output,
            argmax_y,
            argmax_x,
            aligned_height=ctx.output_size[0],
            aligned_width=ctx.output_size[1],
            spatial_scale=ctx.spatial_scale,
            sampling_ratio=ctx.sampling_ratio,
            pool_mode=ctx.pool_mode,
            aligned=ctx.aligned)

        ctx.save_for_backward(rois, argmax_y, argmax_x)
        return output
```
after
```
        output = input.new_zeros(output_shape, device=torch.device('cpu'))
        if ctx.pool_mode == 0:
            argmax_y = input.new_zeros(output_shape, device=torch.device('cpu'))
            argmax_x = input.new_zeros(output_shape, device=torch.device('cpu'))
        else:
            argmax_y = input.new_zeros(0, device=torch.device('cpu'))
            argmax_x = input.new_zeros(0, device=torch.device('cpu'))

        ext_module.roi_align_forward(
            input.cpu(),
            rois.cpu(),
            output,
            argmax_y,
            argmax_x,
            aligned_height=ctx.output_size[0],
            aligned_width=ctx.output_size[1],
            spatial_scale=ctx.spatial_scale,
            sampling_ratio=ctx.sampling_ratio,
            pool_mode=ctx.pool_mode,
            aligned=ctx.aligned)

        ctx.save_for_backward(rois, argmax_y, argmax_x)
        return output.to(input.device)
```

and

before
```
    def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
        rois, argmax_y, argmax_x = ctx.saved_tensors
        grad_input = grad_output.new_zeros(ctx.input_shape)
        # complex head architecture may cause grad_output uncontiguous.
        grad_output = grad_output.contiguous()
        ext_module.roi_align_backward(
            grad_output,
            rois,
            argmax_y,
            argmax_x,
            grad_input,
            aligned_height=ctx.output_size[0],
            aligned_width=ctx.output_size[1],
            spatial_scale=ctx.spatial_scale,
            sampling_ratio=ctx.sampling_ratio,
            pool_mode=ctx.pool_mode,
            aligned=ctx.aligned)
        return grad_input, None, None, None, None, None, None
```
after
```
    def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
        rois, argmax_y, argmax_x = map(lambda x: x.cpu() ,ctx.saved_tensors)
        grad_input = grad_output.new_zeros(ctx.input_shape, device=torch.device('cpu'))
        # complex head architecture may cause grad_output uncontiguous.
        grad_output = grad_output.contiguous()
        ext_module.roi_align_backward(
            grad_output.cpu(),
            rois,
            argmax_y,
            argmax_x,
            grad_input,
            aligned_height=ctx.output_size[0],
            aligned_width=ctx.output_size[1],
            spatial_scale=ctx.spatial_scale,
            sampling_ratio=ctx.sampling_ratio,
            pool_mode=ctx.pool_mode,
            aligned=ctx.aligned)
        return grad_input.to(grad_output.device), None, None, None, None, None, None
```

**Comment by anujndoshi** [comment]
> > And the workaround for nms does not work for roi_align
> 
> I made the following changes to MMCV's nms.py and roi_align.py.
> 
> [mmcv/ops/nms.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/nms.py#L28)
> 
> before
> 
> ```
> inds = ext_module.nms(
>      bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
> ```
> 
> after
> 
> ```
>  inds = ext_module.nms(
>      bboxes.cpu(), scores.cpu(), iou_threshold=float(iou_threshold), offset=offset)
>  inds.to(bboxes.device)
> ```
> 
> [mmcv/ops/roi_align.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/roi_align.py#L62)
> 
> before
> 
> ```
>         output = input.new_zeros(output_shape)
>         if ctx.pool_mode == 0:
>             argmax_y = input.new_zeros(output_shape)
>             argmax_x = input.new_zeros(output_shape)
>         else:
>             argmax_y = input.new_zeros(0)
>             argmax_x = input.new_zeros(0)
> 
>         ext_module.roi_align_forward(
>             input,
>             rois,
>             output,
>             argmax_y,
>             argmax_x,
>             aligned_height=ctx.output_size[0],
>             aligned_width=ctx.output_size[1],
>             spatial_scale=ctx.spatial_scale,
>             sampling_ratio=ctx.sampling_ratio,
>             pool_mode=ctx.pool_mode,
>             aligned=ctx.aligned)
> 
>         ctx.save_for_backward(rois, argmax_y, argmax_x)
>         return output
> ```
> 
> after
> 
> ```
>         output = input.new_zeros(output_shape, device=torch.device('cpu'))
>         if ctx.pool_mode == 0:
>             argmax_y = input.new_zeros(output_shape, device=torch.device('cpu'))
>             argmax_x = input.new_zeros(output_shape, device=torch.device('cpu'))
>         else:
>             argmax_y = input.new_zeros(0, device=torch.device('cpu'))
>             argmax_x = input.new_zeros(0, device=torch.device('cpu'))
> 
>         ext_module.roi_align_forward(
>             input.cpu(),
>             rois.cpu(),
>             output,
>             argmax_y,
>             argmax_x,
>             aligned_height=ctx.output_size[0],
>             aligned_width=ctx.output_size[1],
>             spatial_scale=ctx.spatial_scale,
>             sampling_ratio=ctx.sampling_ratio,
>             pool_mode=ctx.pool_mode,
>             aligned=ctx.aligned)
> 
>         ctx.save_for_backward(rois, argmax_y, argmax_x)
>         return output.to(input.device)
> ```
> 
> and
> 
> before
> 
> ```
>     def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
>         rois, argmax_y, argmax_x = ctx.saved_tensors
>         grad_input = grad_output.new_zeros(ctx.input_shape)
>         # complex head architecture may cause grad_output uncontiguous.
>         grad_output = grad_output.contiguous()
>         ext_module.roi_align_backward(
>             grad_output,
>             rois,
>             argmax_y,
>             argmax_x,
>             grad_input,
>             aligned_height=ctx.output_size[0],
>             aligned_width=ctx.output_size[1],
>             spatial_scale=ctx.spatial_scale,
>             sampling_ratio=ctx.sampling_ratio,
>             pool_mode=ctx.pool_mode,
>             aligned=ctx.aligned)
>         return grad_input, None, None, None, None, None, None
> ```
> 
> after
> 
> ```
>     def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
>         rois, argmax_y, argmax_x = map(lambda x: x.cpu() ,ctx.saved_tensors)
>         grad_input = grad_output.new_zeros(ctx.input_shape, device=torch.device('cpu'))
>         # complex head architecture may cause grad_output uncontiguous.
>         grad_output = grad_output.contiguous()
>         ext_module.roi_align_backward(
>             grad_output.cpu(),
>             rois,
>             argmax_y,
>             argmax_x,
>             grad_input,
>             aligned_height=ctx.output_size[0],
>             aligned_width=ctx.output_size[1],
>             spatial_scale=ctx.spatial_scale,
>             sampling_ratio=ctx.sampling_ratio,
>             pool_mode=ctx.pool_mode,
>             aligned=ctx.aligned)
>         return grad_input.to(grad_output.device), None, None, None, None, None, None
> ```

This works for mmaction ~ mps as well! Thanks!

**Comment by henryrobbins** [comment]
The above changes worked for me too -- thanks! Here's my [patch](https://github.com/henryrobbins/mmcv/tree/mmdetection-mps) off `v2.1.0` of mmcv (mmdetection requires <2.2). When I built mmcv from source with `pip install -e .` alone, I got errors about missing the `mmcv._ext` module. Running `python setup.py develop` in the mmcv repo before pip installing solved it for me. Thanks ChatGPT... 😅

**Comment by zhn6818** [comment]
> > > And the workaround for nms does not work for roi_align并且 nms 的解决方法不适用于 roi_align
> > 
> > 
> > I made the following changes to MMCV's nms.py and roi_align.py.我对 MMCV 的 nms.py 和 roi_align.py 做了以下更改。
> > [mmcv/ops/nms.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/nms.py#L28)
> > before  前
> > ```
> > inds = ext_module.nms(
> >      bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after  后
> > ```
> >  inds = ext_module.nms(
> >      bboxes.cpu(), scores.cpu(), iou_threshold=float(iou_threshold), offset=offset)
> >  inds.to(bboxes.device)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [mmcv/ops/roi_align.py](https://github.com/open-mmlab/mmcv/blob/5916fbd8789f9578cff4d325b1ffe0bc710b4534/mmcv/ops/roi_align.py#L62)
> > before  前
> > ```
> >         output = input.new_zeros(output_shape)
> >         if ctx.pool_mode == 0:
> >             argmax_y = input.new_zeros(output_shape)
> >             argmax_x = input.new_zeros(output_shape)
> >         else:
> >             argmax_y = input.new_zeros(0)
> >             argmax_x = input.new_zeros(0)
> > 
> >         ext_module.roi_align_forward(
> >             input,
> >             rois,
> >             output,
> >             argmax_y,
> >             argmax_x,
> >             aligned_height=ctx.output_size[0],
> >             aligned_width=ctx.output_size[1],
> >             spatial_scale=ctx.spatial_scale,
> >             sampling_ratio=ctx.sampling_ratio,
> >             pool_mode=ctx.pool_mode,
> >             aligned=ctx.aligned)
> > 
> >         ctx.save_for_backward(rois, argmax_y, argmax_x)
> >         return output
> > ```
> > 
> > 
> >     
> >   
> > after  后
> > ```
> >         output = input.new_zeros(output_shape, device=torch.device('cpu'))
> >         if ctx.pool_mode == 0:
> >             argmax_y = input.new_zeros(output_shape, device=torch.device('cpu'))
> >             argmax_x = input.new_zeros(output_shape, device=torch.device('cpu'))
> >         else:
> >             argmax_y = input.new_zeros(0, device=torch.device('cpu'))
> >             argmax_x = input.new_zeros(0, device=torch.device('cpu'))
> > 
> >         ext_module.roi_align_forward(
> >             input.cpu(),
> >             rois.cpu(),
> >             output,
> >             argmax_y,
> >             argmax_x,
> >             aligned_height=ctx.output_size[0],
> >             aligned_width=ctx.output_size[1],
> >             spatial_scale=ctx.spatial_scale,
> >             sampling_ratio=ctx.sampling_ratio,
> >             pool_mode=ctx.pool_mode,
> >             aligned=ctx.aligned)
> > 
> >         ctx.save_for_backward(rois, argmax_y, argmax_x)
> >         return output.to(input.device)
> > ```
> > 
> > 
> >     
> >   
> > and  和
> > before  前
> > ```
> >     def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
> >         rois, argmax_y, argmax_x = ctx.saved_tensors
> >         grad_input = grad_output.new_zeros(ctx.input_shape)
> >         # complex head architecture may cause grad_output uncontiguous.
> >         grad_output = grad_output.contiguous()
> >         ext_module.roi_align_backward(
> >             grad_output,
> >             rois,
> >             argmax_y,
> >             argmax_x,
> >             grad_input,
> >             aligned_height=ctx.output_size[0],
> >             aligned_width=ctx.output_size[1],
> >             spatial_scale=ctx.spatial_scale,
> >             sampling_ratio=ctx.sampling_ratio,
> >             pool_mode=ctx.pool_mode,
> >             aligned=ctx.aligned)
> >         return grad_input, None, None, None, None, None, None
> > ```
> > 
> > 
> >     
> >   
> > after  后
> > ```
> >     def backward(ctx: Any, grad_output: torch.Tensor) -> tuple:
> >         rois, argmax_y, argmax_x = map(lambda x: x.cpu() ,ctx.saved_tensors)
> >         grad_input = grad_output.new_zeros(ctx.input_shape, device=torch.device('cpu'))
> >         # complex head architecture may cause grad_output uncontiguous.
> >         grad_output = grad_output.contiguous()
> >         ext_module.roi_align_backward(
> >             grad_output.cpu(),
> >             rois,
> >             argmax_y,
> >             argmax_x,
> >             grad_input,
> >             aligned_height=ctx.output_size[0],
> >             aligned_width=ctx.output_size[1],
> >             spatial_scale=ctx.spatial_scale,
> >             sampling_ratio=ctx.sampling_ratio,
> >             pool_mode=ctx.pool_mode,
> >             aligned=ctx.aligned)
> >         return grad_input.to(grad_output.device), None, None, None, None, None, None
> > ```
> 
> This works for mmaction ~ mps as well! Thanks!这也适用于 mmaction ~ mps！谢谢！



This is works for M4 pro,Thanks a lot
