### ISSUE TITLE
Any plan support RT-DETR? 

### ISSUE THREAD

**Issue by zugofn** [open-mmlab/mmdetection#10186]
**Describe the feature**

**Motivation**
There is a recent paper https://arxiv.org/abs/2304.08069 which is very helpful for Object Detection in DETR style.
The proposed RT-DETR-L achieves 53.0% AP on COCO val2017 and 114 FPS on T4 GPU, while RT-DETR-X achieves 54.8% AP and 74 FPS, outperforming all YOLO detectors of the same scale in both speed and accuracy.  

**Related resources**
The official code release.
https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rtdetr

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by IuliuNovac** [comment]
+1

**Comment by MINGtoMING** [comment]
+1 for this

**Comment by glenn-jocher** [comment]
We've implemented RT-DETR now in `ultralytics`. Here's a usage example:

## Install

```bash
pip install ultralytics
```

## Run Inference

```python
from ultralytics import RTDETR

model = RTDETR("rtdetr-l.pt")
model.predict("path/to/image.jpg")
```

For details see https://docs.ultralytics.com/models/rtdetr

**Comment by MINGtoMING** [comment]
@glenn-jocher Thanks, amazing speed, too curly!

**Comment by MINGtoMING** [comment]
@glenn-jocher Does it already support training, or does it currently support inference?

**Comment by AyushExel** [comment]
It supports prediction and validation currently. We'll work on supporting training soon

**Comment by nijkah** [comment]
https://github.com/open-mmlab/mmdetection/pull/10498
Stay tuned please 😄

**Comment by op-newman** [comment]
im waitingggggg

**Comment by Zunon** [comment]
@nijkah @hhaAndroid is there an ETA regarding this?
I tried to clone the branch in which your pull request is merging, however when I try to run tools/test.py on the config and model, I get the following error: 

```sh
Traceback (most recent call last):
  File "C:\<omitted>\mmrtdetr\tools\test.py", line 149, in <module>
    main()
  File "C:\<omitted>\mmrtdetr\tools\test.py", line 131, in main
    runner = Runner.from_cfg(cfg)
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\runner\runner.py", line 439, in from_cfg
    runner = cls(
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\runner\runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\runner\runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\registry\registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\registry\build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\<omitted>\mmrtdetr\venv\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'RTDETR is not in the model registry. Please check whether the value of `RTDETR` is correct or it was registered 
as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by nijkah** [comment]
Hi @Zunon , did you run `pip install -e .` in the cloned branch? The model registry should work if you installed it correctly. I tested now.

**Comment by lyuwenyu** [comment]
I provided a clean code version for RT-DETR that you can try if you are interested, including benchmark (tensorrt inference), rtdetr_paddle, rtdetr_pytorch. 

For details see https://github.com/lyuwenyu/RT-DETR

**Comment by lyuwenyu** [comment]
Release pytorch rtdetr, try it in https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch

**Comment by op-newman** [comment]
> [发布pytorch rtdetr，在https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch](https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch)中尝试一下[](https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch)

thank you! the next work is train in cocodataset.

**Comment by HaoLiuHust** [comment]
any progress?

**Comment by dhddxdhd** [comment]
mm系列会更新rt-detr吗，非常期待

**Comment by GGD777** [comment]
> 嗨，你在克隆的分支中跑了吗？如果正确安装，模型注册表应该可以正常工作。我现在测试了。`pip install -e .`
![Uploading 736a474fce8350c6ef82ad52ea58305.png…]()  Could you tell me how to register?
