### ISSUE TITLE
When training RTMDet

### ISSUE THREAD

**Issue by pd162** [open-mmlab/mmdetection#10184]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by pd162** [comment]
```
Traceback (most recent call last):
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/site-packages/mmengine/optim/optimizer/optimizer_wrapper.py", line 351, in optim_context
    yield
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ljh/mmdetection3/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/data/ljh/mmdetection3/mmdet/models/detectors/single_stage.py", line 77, in loss
    x = self.extract_feat(batch_inputs)
  File "/data/ljh/mmdetection3/mmdet/models/detectors/single_stage.py", line 148, in extract_feat
    x = self.neck(x)
  File "/data/ljh/anaconda3/envs/open-mmlab-new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/ljh/mmdetection3/mmdet/models/necks/cspnext_pafpn.py", line 153, in forward
    torch.cat([upsample_feat, feat_low], 1))
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 104 but got size 103 for tensor number 1 in the list.
```

**Comment by GeorgePearse** [comment]
What size image are you trying to train on? 

I hit this when I try to train on 1920x1080 but not 950x540

**Comment by wbudd** [comment]
In my case too, this error occurred when I accidentally used an image with a `shape` outside of the `img_scales` range I had defined in my model config file (while taking `scale_factor` into account). Checking image sizes/shapes beforehand solved the problem. (Batch size doesn't seem to be relevant.)

**Comment by GeorgePearse** [comment]
@wbudd out of curiousity, what size image are you training on?

**Comment by wbudd** [comment]
@GeorgePearse 

Sorry, upon closer inspection the cause I suggested above was inaccurate.

The direct/common cause of the error is deviant image (tensor) dimensions with regard to the 640x640 input layer, but in my case the reason that this image wasn't modified properly during preprocessing was simply because I forgot to include a `'Pad'` step in my data pipeline—`test_dataloader.dataset.pipeline` in my case, but the same principle applies to the pipelines in `train_dataloader` and `val_dataloader`.

I was working with square images mostly, fow which the `dict(type = 'Resize', scale = (640, 640), keep_ratio = True)` step in that pipeline resizes any original size just fine, but obviously `keep_ratio = True` means that non-square images need padding added to the shorter dimension.

I imagine there are numerous other ways this error can occur, other than my simple padding facepalm here: but the takeaway nonetheless seems to be to make 100% sure that the `pipeline`s in the config file (that determine the preprocessing that the MMDetection framework applies) do exactly what you assume they do—combing through the MMDetection source code if necessary.

**Comment by wbudd** [comment]
@GeorgePearse 

BTW, to respond more directly to your performance-related concerns: I wasn't aware of any RTMDet hard upper bounds; but as you've noticed, downscaling of large images with RTMDet (and many other object detection architectures) does seem to cause a rather major performance penalty, especially if the bounding boxes you're interested in have a small surface area.

Luckily there is a good solution which I can strongly recommend: [SAHI](https://github.com/obss/sahi). SAHI has support for the MMDetection framewoek (a PR for v3 support just landed a few days ago), and takes care of all the tile overlap edge cases via NMS, so you don't have to worry about it. For HD+ image sizes, RTMDet+SAHI resulted in a significant performance boost versus RTMDet alone.
