### ISSUE TITLE
No module named 'petrel_client'

### ISSUE THREAD

**Issue by Toto-Alfredo** [open-mmlab/mmdetection#10199]
/Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
我跑mask2former时报错没有petrel_client模块，其他数据集跑目标检测是没有问题的。
**Reproduction**

1. What command or script did you run?

python tools/train.py configs/mask2former/mask2former_r50_8xb2-lsj-50e_coco.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
没有
3. What dataset did you use?
自己实例分割coco数据集
报错为
Traceback (most recent call last):
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/fileio/backends/petrel_backend.py", line 46, in __init__
    from petrel_client import client
ModuleNotFoundError: No module named 'petrel_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/hipeson/mmdetection_whl/mmdet/datasets/base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 250, in __init__
    self.full_init()
  File "/home/hipeson/mmdetection_whl/mmdet/datasets/base_det_dataset.py", line 65, in full_init
    self.data_list = self.load_data_list()
  File "/home/hipeson/mmdetection_whl/mmdet/datasets/coco.py", line 34, in load_data_list
    with get_local_path(
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/fileio/io.py", line 398, in get_local_path
    backend = get_file_backend(
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/fileio/io.py", line 152, in get_file_backend
    backend = _get_file_backend(prefix, backend_args)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/fileio/io.py", line 99, in _get_file_backend
    backend = prefix_to_backends[prefix](**backend_args)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/fileio/backends/petrel_backend.py", line 48, in __init__
    raise ImportError('Please install petrel_client to enable '
ImportError: Please install petrel_client to enable PetrelBackend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
ImportError: class `CocoDataset` in mmdet/datasets/coco.py: Please install petrel_client to enable PetrelBackend.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1672, in train
    self._train_loop = self.build_train_loop(
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1464, in build_train_loop
    loop = LOOPS.build(
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/hipeson/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-11.7/
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.0
OpenCV: 4.7.0
MMEngine: 0.7.2
MMDetection: 3.0.0+

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
![Snipaste_2023-04-21_20-24-35](https://user-images.githubusercontent.com/46951881/233643587-f468f92d-cfa1-4360-9c06-5ea20e6e3776.png)

**Comment by zwhus** [comment]
Sorry, i will fix this issue now

**Comment by SuGoe-Young** [comment]
Hi, I have same error with you, I can't understand #10213 to fix this error..., can you porvide your config, or teach me how do you solve this question to train your own instance segmentation dataset

**Comment by bushilingluan** [comment]
> Hi, I have same error with you, I can't understand #10213 to fix this error..., can you porvide your config, or teach me how do you solve this question to train your own instance segmentation dataset

![image](https://github.com/open-mmlab/mmdetection/assets/67639851/60e84c9a-a6a3-4045-8d52-de1914fa0728)
Find that config file，just make the same changes (comment out the ninth line in a coco_panoptic.py file to make the third line of code effective).
