### ISSUE TITLE
how to convert .pth model to .onnx model in mmdetection?

### ISSUE THREAD

**Issue by linssswww** [open-mmlab/mmdetection#1023]
This is my code
def main():
    args = parse_args()
    cfg = mmcv.Config.fromfile(args.config)
    model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
    model.load_state_dict(checkpoint['state_dict'])
    import torch
    dummy_input = torch.randn(1, 64, 512, 256)
    torch.onnx.export(model, dummy_input, "onnx_model_name.onnx")

args.config = checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth
args.checkpoint = configs/faster_rcnn_r50_fpn_1x.py

When I run the script, it call the error:
unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer4.0.downsample.1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer2.3.bn1.num_batches_tracked, bn1.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer4.0.bn2.num_batches_tracked

Traceback (most recent call last):
  File "/home/dl6/pycharm-community-2018.1.3/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/dl6/pycharm-community-2018.1.3/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/dl6/pycharm-community-2018.1.3/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/dl6/pycharm-community-2018.1.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/dl6/ljn_workplace/mmdetection-master/tools/test.py", line 140, in <module>
    main()
  File "/home/dl6/ljn_workplace/mmdetection-master/tools/test.py", line 136, in main
    torch.onnx.export(model, dummy_input, "onnx_model_name.onnx")
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 266, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 231, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 294, in forward
    out = self.inner(*trace_inputs)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/dl6/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_meta'

what should I do?  thanks!!

**Comment by ujsyehao** [comment]
I encounter the problem too.

**Comment by hellock** [comment]
#1082

**Comment by yyfhaku** [comment]
问题解决了吗？

**Comment by loveunk** [comment]
any update?

**Comment by hudingding** [comment]
这个你修改下model.foward = model.foward_dumpy，但是后面会报错，有些算子会无法转换

**Comment by xvjiarui** [comment]
Please check out `tools/pytorch2onnx.py` in the latest mmdetection. Currently, customize operators are not supported. 
Note: Please use English or English & Chinese in issues.

**Comment by RunningLeon** [comment]
Please try with the latest `mmcv` and `mmdetection` if you still have problems.
