### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

### ISSUE THREAD

**Issue by LiamNinetyNine** [open-mmlab/mmdetection#10243]
Using mmdetection 3.0.0 with cuda 11.3, pytorch 1.12.1 and mmcv 2.0.0rc4
```
_base_ = '/home/lunet/fylr3/mmdetection/configs/faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(type='Shared2FCBBoxHead', num_classes=4)))

dataset_type = 'CocoDataset'
classes = ('Apple','Banana','Orange','Watermelon')
data_root = '/home/lunet/fylr3/mmdetection/train_data/'
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    dataset=dict(
        type=dataset_type,
        metainfo=dict(classes=classes),
        data_root=data_root,
        ann_file='train/result.json',
        data_prefix=dict(img='train/images')
        )
    )

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    dataset=dict(
        type=dataset_type,
        test_mode=True,
        # explicitly add your class names to the field `metainfo`
        metainfo=dict(classes=classes),
        data_root=data_root,
        ann_file='test/result_test.json',
        data_prefix=dict(img='test/images')
        )
    )

test_dataloader = val_dataloader
load_from = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'

work_dir = '/home/lunet/fylr3/mmdetection/work_dirs/faster_rcnn_lr'

lr_config = dict(
    by_epoch=True,
    policy='step',
    warmup='linear',
    warmup_iters=10,  # same as burn-in in darknet
    warmup_ratio=0.1,
    warmup_by_epoch=True,
    step=[290, 298])

evaluation = dict(interval=1, metric=['bbox'])

#checkpoint_config = dict(interval=10)

runner = dict(type='EpochBasedRunner', max_epochs=300)

num_workers = 0

workflow = [('train', 1)]`
```
After running python tools/train.py configs/custom_config3.py i get the following error
 
```
Traceback (most recent call last):
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/lunet/fylr3/mmdetection/mmdet/evaluation/metrics/coco_metric.py", line 126, in __init__
    self._coco_api = COCO(local_path)
  File "/home/lunet/fylr3/mmdetection/mmdet/datasets/api_wrappers/coco_api.py", line 25, in __init__
    super().__init__(annotation_file=annotation_file)
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 338, in __init__
    self.evaluator = runner.build_evaluator(evaluator)  # type: ignore
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1294, in build_evaluator
    return Evaluator(evaluator)  # type: ignore
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/evaluator/evaluator.py", line 25, in __init__
    self.metrics.append(METRICS.build(metric))
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `CocoMetric` in mmdet/evaluation/metrics/coco_metric.py: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    self._val_loop = self.build_val_loop(
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1506, in build_val_loop
    loop = LOOPS.build(
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/lunet/fylr3/.conda/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
FileNotFoundError: class `ValLoop` in mmengine/runner/loops.py: class `CocoMetric` in mmdet/evaluation/metrics/coco_metric.py: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'
```

**Comment by aliwaqas333** [comment]
How did you solve this?

**Comment by liebeslied** [comment]
I would also be curious, @LiamNinetyNine! Thanks!

**Comment by liebeslied** [comment]
Actually I solved this by adding the `val_evaluator` and `test_evaluator` to my config with the correct `ann_file` params following https://mmdetection.readthedocs.io/en/latest/user_guides/config.html
