### ISSUE TITLE
HTC alwasy requires segmentation information?

### ISSUE THREAD

**Issue by mosheliv** [open-mmlab/mmdetection#1024]
It looks like HTC can't be used on datasets that do not contain segmentation information. Is this correct?

**Comment by cizhenshi** [comment]
There is config file name htc_without_segmentation in ./configs/htc dir.

**Comment by mosheliv** [comment]
Thank you. Will same changes work on all HTC models? including X-101-64x4d-FPN? (assuming I can train it with any success on single v100)

**Comment by hellock** [comment]
Yes, it is irrelevant to the backbone models.

**Comment by mosheliv** [comment]
I have tried running it but I get error on mask:
```
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 62, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 223, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/mmdetection/mmdet/datasets/custom.py", line 171, in __getitem__
    data = self.prepare_train_img(idx)
  File "/mmdetection/mmdet/datasets/custom.py", line 241, in prepare_train_img
    gt_masks = self.mask_transform(ann['masks'], pad_shape,
KeyError: 'masks'
```
if i change "with_mask" to false, i get:
```
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 62, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 223, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/htc.py", line 254, in forward_train
    semantic_feat)
  File "/mmdetection/mmdet/models/detectors/htc.py", line 108, in _mask_forward_train
    rcnn_train_cfg)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 109, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 10, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
```
this is using the htc_without_semantic_r50_fpn_1x

Is there any way of using HTC on dataset that does not contain mask or semantic segmentation?

**Comment by hellock** [comment]
Semantic segmentation annotation is optional, but the instance masks are required.

**Comment by mosheliv** [comment]
Thank you for clarifying this.

**Comment by jc56968** [comment]
> I have tried running it but I get error on mask:
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 98, in <module>
>     main()
>   File "tools/train.py", line 94, in main
>     logger=logger)
>   File "/mmdetection/mmdet/apis/train.py", line 62, in train_detector
>     _non_dist_train(model, dataset, cfg, validate=validate)
>   File "/mmdetection/mmdet/apis/train.py", line 223, in _non_dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 260, in train
>     for i, data_batch in enumerate(data_loader):
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
>     return self._process_next_batch(batch)
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
>     raise Exception("KeyError:" + batch.exc_msg)
> Exception: KeyError:Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/mmdetection/mmdet/datasets/custom.py", line 171, in __getitem__
>     data = self.prepare_train_img(idx)
>   File "/mmdetection/mmdet/datasets/custom.py", line 241, in prepare_train_img
>     gt_masks = self.mask_transform(ann['masks'], pad_shape,
> KeyError: 'masks'
> ```
> 
> if i change "with_mask" to false, i get:
> 
> ```
>   File "tools/train.py", line 98, in <module>
>     main()
>   File "tools/train.py", line 94, in main
>     logger=logger)
>   File "/mmdetection/mmdet/apis/train.py", line 62, in train_detector
>     _non_dist_train(model, dataset, cfg, validate=validate)
>   File "/mmdetection/mmdet/apis/train.py", line 223, in _non_dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 264, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
>     losses = model(**data)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
>     return old_func(*args, **kwargs)
>   File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
>     return self.forward_train(img, img_meta, **kwargs)
>   File "/mmdetection/mmdet/models/detectors/htc.py", line 254, in forward_train
>     semantic_feat)
>   File "/mmdetection/mmdet/models/detectors/htc.py", line 108, in _mask_forward_train
>     rcnn_train_cfg)
>   File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 109, in get_target
>     gt_masks, rcnn_train_cfg)
>   File "/mmdetection/mmdet/core/mask/mask_target.py", line 10, in mask_target
>     pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
> TypeError: 'NoneType' object is not iterable
> ```
> 
> this is using the htc_without_semantic_r50_fpn_1x
> 
> Is there any way of using HTC on dataset that does not contain mask or semantic segmentation?

i have a same problem as this  "TypeError: 'NoneType' object is not iterable"  when  i train htc_without_semantic_r50_fpn_1x.config , so  how  to solve it
