### ISSUE TITLE
mmdetection  AttributeError: 'ConfigDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by Yu1802** [open-mmlab/mmdetection#10287]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
我在mmdetection v2.28版本下，运行官网上更新的centernet_r50-caffe_fpn_ms-1x_coco.py以及centernet-update_r50_fpn_8xb8-amp-lsj-200e_coco.py，并在common文件夹中添加 lsj-coco-detecton的100e及200e文件。报错信息为
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 135, in main
    setup_multi_processes(cfg)
  File "/home/mmdetection/mmdet/utils/setup_env.py", line 30, in setup_multi_processes
    workers_per_gpu = cfg.data.get('workers_per_gpu', 1)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

**Reproduction**

I ran  python tools/train.py configs/centernet/centernet-update_r50_fpn_8xb8-amp-lsj-200e_coco.py --work-dir work-dir/centernet-update_r50_fpn_8xb8-amp-lsj-200e_coco.py  on coco dataset.

**Environment**

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: :/usr/local/cuda-11.3:/usr/local/cuda-11.3
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.0+56e42e7

**Comment by tojimahammatov** [comment]
Hi, I guess the issue is related to mmcv version. Latest mmdetection uses `train_dataloader` keyword in configs instead of `data` keyword. Thus mmcv can't find `data`. Compare [this](https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/configs/_base_/datasets/coco_detection.py#L37) and [this.](https://github.com/open-mmlab/mmdetection/blob/2.x/configs/_base_/datasets/coco_detection.py#L31) You may notice that there are more differences. Perhaps upgrading mmcv to version >=2.0 will help. The best way I guess is to build mmdet from scratch following the latest [installation](https://mmdetection.readthedocs.io/en/latest/get_started.html) guide.

**Comment by mahilaMoghadami** [comment]
Hello
I have same error while using mmdetection. How you solved that?

**Comment by tojimahammatov** [comment]
@mahilaMoghadami hi, what are the versions you have for mmdet and mmcv. Check my response above. That should be a reason if you have the same error and environments.

**Comment by mahilaMoghadami** [comment]
thanks
yes I did, but Im using repository which is need to install mmcv==0.6.2!!!!
and now, I don't know what should I do

**Comment by nemuwww** [comment]
您好，mmdet3和mmdet2的注册机制好像有点不同，一个是@MODELS.register_module()一个是@HEADS.register_module()，请问你是怎么修改文件让他能成功运行的呢？
