### ISSUE TITLE
failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by htcml** [open-mmlab/mmdetection#10300]
When I did pip install mmdet, I encountered the following error. I also added export TMPDIR=$HOME/tmp and it doesn't work either.
```

  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-d0hn6ggj/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 17, in <module>
          from . import multiarray
        File "/tmp/pip-build-env-d0hn6ggj/overlay/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
          from . import overrides
        File "/tmp/pip-build-env-d0hn6ggj/overlay/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: /tmp/pip-build-env-d0hn6ggj/overlay/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted
```

**Comment by cmarqu** [comment]
It looks like your `TMPDIR=$HOME/tmp` setting doesn't have an effect. Try e.g. creating that directory with `mkdir -p $HOME/tmp`.
