### ISSUE TITLE
BUG: TypeError: EpochBasedRunner: __init__() got an unexpected keyword argument 'max_epoch'

### ISSUE THREAD

**Issue by Sudae827** [open-mmlab/mmdetection#10311]
F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
F:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\utils\setup_env.py:38: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
F:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\utils\setup_env.py:48: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
f:\anaconda\envs\openmmlab\lib\site-packages\mmdet\.mim\tools\train.py:155: UserWarning: `--gpus` is deprecated because we only support single GPU mode in non-distributed training. Use `gpus=1` now.
  warnings.warn('`--gpus` is deprecated because we only support '
2023-05-10 21:25:51,467 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: win32
Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: 
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: 11.7
MMDetection: 2.28.0+unknown
------------------------------------------------------------

2023-05-10 21:25:52,747 - mmdet - INFO - Distributed training: False
2023-05-10 21:25:54,009 - mmdet - INFO - Config:
input_size = 512
model = dict(
    type='SingleStageDetector',
    backbone=dict(
        type='SSDVGG',
        depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_indices=(3, 4),
        out_feature_indices=(22, 34),
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://vgg16_caffe')),
    neck=dict(
        type='SSDNeck',
        in_channels=(512, 1024),
        out_channels=(512, 1024, 512, 256, 256, 256, 256),
        level_strides=(2, 2, 2, 2, 1),
        level_paddings=(1, 1, 1, 1, 1),
        l2_norm_scale=20,
        last_kernel_size=4),
    bbox_head=dict(
        type='SSDHead',
        in_channels=(512, 1024, 512, 256, 256, 256, 256),
        num_classes=2,
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=512,
            basesize_ratio_range=(0.1, 0.9),
            strides=[8, 16, 32, 64, 128, 256, 512],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2])),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.0,
            ignore_iof_thr=-1,
            gt_max_assign_all=False),
        smoothl1_beta=1.0,
        allowed_border=-1,
        pos_weight=-1,
        neg_pos_ratio=3,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        nms=dict(type='nms', iou_threshold=0.45),
        min_bbox_size=0,
        score_thr=0.02,
        max_per_img=200))
cudnn_benchmark = True
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Expand',
        mean=[123.675, 116.28, 103.53],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[1, 1, 1],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[1, 1, 1],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=1,
        dataset=dict(
            type='VOCDataset',
            ann_file='data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt',
            img_prefix='data/VOCdevkit/VOC2007/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    type='Expand',
                    mean=[123.675, 116.28, 103.53],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[1, 1, 1],
                    to_rgb=True),
                dict(type='DefaultFormatBundle'),
                dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
            ])),
    val=dict(
        type='VOCDataset',
        ann_file='data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt',
        img_prefix='data/VOCdevkit/VOC2007/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='VOCDataset',
        ann_file='data/VOCdevkit/VOC2007/ImageSets/Main/test.txt',
        img_prefix='data/VOCdevkit/VOC2007/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[1, 1, 1],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.002, momentum=0.9, weight_decay=0.0005)
optimizer_config = dict()
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 22])
runner = dict(type='EpochBasedRunner', max_epochs=24, max_epoch=10)
checkpoint_config = dict(interval=1)
log_config = dict(interval=10, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='CheckInvalidLossHook', interval=50, priority='VERY_LOW')
]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = 'F:\Detection\mmdetection-2.28.0\mmdetection-2.28.0\checkpoints\ssd512_coco_20210803_022849-0a47a1ca.pth'
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=False, base_batch_size=8)
classes = ('Coal', 'Gangue')
work_dir = './work_dirs\my_ssd512_coco'
auto_resume = False
gpu_ids = range(0, 1)

2023-05-10 21:25:54,010 - mmdet - INFO - Set random seed to 111649425, deterministic: False
2023-05-10 21:25:54,272 - mmcv - INFO - initialize SSDVGG with init_cfg {'type': 'Pretrained', 'checkpoint': 'open-mmlab://vgg16_caffe'}
2023-05-10 21:25:54,272 - mmcv - INFO - load model from: open-mmlab://vgg16_caffe
2023-05-10 21:25:54,273 - mmcv - INFO - load checkpoint from openmmlab path: open-mmlab://vgg16_caffe
2023-05-10 21:25:54,439 - mmcv - INFO - initialize SSDNeck with init_cfg [{'type': 'Xavier', 'distribution': 'uniform', 'layer': 'Conv2d'}, {'type': 'Constant', 'val': 1, 'layer': 'BatchNorm2d'}, {'type': 'Constant', 'val': 20, 'override': {'name': 'l2_norm'}}]
2023-05-10 21:25:54,510 - mmcv - INFO - initialize SSDHead with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform', 'bias': 0}
2023-05-10 21:25:54,538 - mmcv - INFO - 
backbone.features.0.weight - torch.Size([64, 3, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,539 - mmcv - INFO - 
backbone.features.0.bias - torch.Size([64]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,539 - mmcv - INFO - 
backbone.features.2.weight - torch.Size([64, 64, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,539 - mmcv - INFO - 
backbone.features.2.bias - torch.Size([64]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,539 - mmcv - INFO - 
backbone.features.5.weight - torch.Size([128, 64, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,539 - mmcv - INFO - 
backbone.features.5.bias - torch.Size([128]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.7.weight - torch.Size([128, 128, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.7.bias - torch.Size([128]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.10.weight - torch.Size([256, 128, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.10.bias - torch.Size([256]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.12.weight - torch.Size([256, 256, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.12.bias - torch.Size([256]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,540 - mmcv - INFO - 
backbone.features.14.weight - torch.Size([256, 256, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.14.bias - torch.Size([256]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.17.weight - torch.Size([512, 256, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.17.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.19.weight - torch.Size([512, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.19.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.21.weight - torch.Size([512, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,541 - mmcv - INFO - 
backbone.features.21.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.24.weight - torch.Size([512, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.24.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.26.weight - torch.Size([512, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.26.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.28.weight - torch.Size([512, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.28.bias - torch.Size([512]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,542 - mmcv - INFO - 
backbone.features.31.weight - torch.Size([1024, 512, 3, 3]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
backbone.features.31.bias - torch.Size([1024]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
backbone.features.33.weight - torch.Size([1024, 1024, 1, 1]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
backbone.features.33.bias - torch.Size([1024]): 
PretrainedInit: load from open-mmlab://vgg16_caffe 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
neck.l2_norm.weight - torch.Size([512]): 
ConstantInit: val=20, bias=0 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
neck.extra_layers.0.0.conv.weight - torch.Size([256, 1024, 1, 1]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
neck.extra_layers.0.0.conv.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,543 - mmcv - INFO - 
neck.extra_layers.0.1.conv.weight - torch.Size([512, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.0.1.conv.bias - torch.Size([512]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.1.0.conv.weight - torch.Size([128, 512, 1, 1]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.1.0.conv.bias - torch.Size([128]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.1.1.conv.weight - torch.Size([256, 128, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.1.1.conv.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.2.0.conv.weight - torch.Size([128, 256, 1, 1]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,544 - mmcv - INFO - 
neck.extra_layers.2.0.conv.bias - torch.Size([128]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.2.1.conv.weight - torch.Size([256, 128, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.2.1.conv.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.3.0.conv.weight - torch.Size([128, 256, 1, 1]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.3.0.conv.bias - torch.Size([128]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.3.1.conv.weight - torch.Size([256, 128, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,545 - mmcv - INFO - 
neck.extra_layers.3.1.conv.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
neck.extra_layers.4.0.conv.weight - torch.Size([128, 256, 1, 1]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
neck.extra_layers.4.0.conv.bias - torch.Size([128]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
neck.extra_layers.4.1.conv.weight - torch.Size([256, 128, 4, 4]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
neck.extra_layers.4.1.conv.bias - torch.Size([256]): 
The value is the same before and after calling `init_weights` of SingleStageDetector  
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
bbox_head.cls_convs.0.0.weight - torch.Size([12, 512, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
bbox_head.cls_convs.0.0.bias - torch.Size([12]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,546 - mmcv - INFO - 
bbox_head.cls_convs.1.0.weight - torch.Size([18, 1024, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.1.0.bias - torch.Size([18]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.2.0.weight - torch.Size([18, 512, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.2.0.bias - torch.Size([18]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.3.0.weight - torch.Size([18, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.3.0.bias - torch.Size([18]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.4.0.weight - torch.Size([18, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.4.0.bias - torch.Size([18]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,547 - mmcv - INFO - 
bbox_head.cls_convs.5.0.weight - torch.Size([12, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.cls_convs.5.0.bias - torch.Size([12]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.cls_convs.6.0.weight - torch.Size([12, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.cls_convs.6.0.bias - torch.Size([12]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.reg_convs.0.0.weight - torch.Size([16, 512, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.reg_convs.0.0.bias - torch.Size([16]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.reg_convs.1.0.weight - torch.Size([24, 1024, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,548 - mmcv - INFO - 
bbox_head.reg_convs.1.0.bias - torch.Size([24]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.2.0.weight - torch.Size([24, 512, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.2.0.bias - torch.Size([24]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.3.0.weight - torch.Size([24, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.3.0.bias - torch.Size([24]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.4.0.weight - torch.Size([24, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.4.0.bias - torch.Size([24]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,549 - mmcv - INFO - 
bbox_head.reg_convs.5.0.weight - torch.Size([16, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,550 - mmcv - INFO - 
bbox_head.reg_convs.5.0.bias - torch.Size([16]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,550 - mmcv - INFO - 
bbox_head.reg_convs.6.0.weight - torch.Size([16, 256, 3, 3]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:54,550 - mmcv - INFO - 
bbox_head.reg_convs.6.0.bias - torch.Size([16]): 
XavierInit: gain=1, distribution=uniform, bias=0 
 
2023-05-10 21:25:55,110 - mmdet - INFO - Automatic scaling of learning rate (LR) has been disabled.
Traceback (most recent call last):
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'max_epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\anaconda\envs\openmmlab\lib\site-packages\mmdet\.mim\tools\train.py", line 247, in <module>
    main()
  File "f:\anaconda\envs\openmmlab\lib\site-packages\mmdet\.mim\tools\train.py", line 236, in main
    train_detector(
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmdet\apis\train.py", line 169, in train_detector
    runner = build_runner(
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\builder.py", line 24, in build_runner
    runner = runner_constructor()
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\default_constructor.py", line 47, in __call__
    return RUNNERS.build(self.runner_cfg, default_args=self.default_args)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: EpochBasedRunner: __init__() got an unexpected keyword argument 'max_epoch'
Traceback (most recent call last):
  File "F:\Anaconda\envs\openmmlab\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Anaconda\envs\openmmlab\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Anaconda\envs\openmmlab\Scripts\mim.exe\__main__.py", line 7, in <module>
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mim\commands\train.py", line 100, in cli
    is_success, msg = train(
  File "F:\Anaconda\envs\openmmlab\lib\site-packages\mim\commands\train.py", line 261, in train
    ret = subprocess.check_call(
  File "F:\Anaconda\envs\openmmlab\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\Anaconda\\envs\\openmmlab\\python.exe', 'f:\\anaconda\\envs\\openmmlab\\lib\\site-packages\\mmdet\\.mim\\tools\\train.py', 'configs/ssd/my_ssd512_coco.py', '--launcher', 'none', '--gpus', '1']' returned non-zero exit status 1.

**Comment by Sudae827** [comment]
resovled it.
