### ISSUE TITLE
AttributeError: 'TOOD' object has no attribute 'CLASSES'

### ISSUE THREAD

**Issue by hihosilvers** [open-mmlab/mmdetection#10344]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. 
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Not sure if this bug report should go here or on label-studio, but since the guide is hosted here:
https://github.com/open-mmlab/mmdetection/blob/dev-3.x/docs/en/user_guides/label_studio.md
I will make the bug report here first.

When trying to use TOOD as an ml backend for label-studio we get the following error:
```
AttributeError: 'TOOD' object has no attribute 'CLASSES'
```
In the previous version of mmdet we added class labels to data.train | val.classes in the config and there wasn't any error.

I believe now that classes are given in metainfo by the dataloader, perhaps label-studio can't find it? 

**Reproduction**

1. What command or script did you run?
In Windows CMD
```
label-studio-ml start coco-detector --with config_file=../tood_mmdet3config.py checkpoint_file=../labelling_exps/latest.pth device=cuda score_threshold=0.6
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
This is my config file `tood_mmdet3config.py`:
```
_base_ = "mmdetection/configs/tood/tood_r101-dconv-c3-c5_fpn_ms-2x_coco.py"
# Note 2x in the name means 2 GPU's used for training so we should divide the lr by 2

# Modify dataset type and path
data_root = "dataset/"

# modify num classes of the model in box head
model = dict(
    bbox_head=dict(
        num_classes=1,
    )
)

metainfo = {"classes": ("dog")}

train_dataloader = dict(
    batch_size=8,
    num_workers=12,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="train.json",
    ),
)

val_dataloader = dict(
    batch_size=8,
    num_workers=12,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="train.json",
    ),
)

# Modify metric related settings
val_evaluator = dict(ann_file=data_root + "train.json")
test_evaluator = val_evaluator

# If we need to finetune a model based on a pre-trained detector, we need to
# use load_from to set the path of checkpoints.
load_from = "labelling_exps/latest.pth"
work_dir = "./labelling_exps"

# The original learning rate (LR) is set for 2-GPU training.
# We divide it by 2 since we only use one GPU.
optim_wrapper = dict(optimizer=dict(lr=0.005))

# We can set the checkpoint saving interval to reduce the storage cost
default_hooks = dict(
    logger=dict(type="LoggerHook", interval=10), checkpoint=dict(interval=12)
)

# Remove warmup in learning rate
param_scheduler = [
    dict(
        type="MultiStepLR",
        begin=0,
        end=24,
        by_epoch=True,
        milestones=[16, 22],
        gamma=0.1,
    )
]

# We can set the evaluation interval to reduce the evaluation times
train_cfg = dict(val_interval=12)

device = "cuda"
gpu_ids = range(1)
```

4. What dataset did you use?
Custom dataset

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: win32
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
GCC: n/a
PyTorch: 2.0.0+cu118
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 193431937
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.15.1+cu118
OpenCV: 4.7.0
MMEngine: 0.7.3
MMDetection: 3.0.0+ecac3a7
```

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - pip

**Error traceback**
If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "c:\users\...\label-studio-ml-backend\label_studio_ml\exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "c:\users\...\label-studio-ml-backend\label_studio_ml\api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "c:\users\...\label-studio-ml-backend\label_studio_ml\model.py", line 584, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "C:\Users\...\label-studio-ml-backend\coco-detector\mmdetection.py", line 97, in predict
    for bboxes, label in zip(model_results, self.model.CLASSES):
  File "C:\Users\...\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TOOD' object has no attribute 'CLASSES'
```

**Comment by hihosilvers** [comment]
Oh nevermind I needed to update label-studio-ml-backend
