### ISSUE TITLE
How to use TTA in demo/inference_demo.ipynb

### ISSUE THREAD

**Issue by jamiechoi1995** [open-mmlab/mmdetection#10355]
I saw the example using TTA in https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/tools/test.py#L125-L126

However, when I copy the code and place it in demo/inference_demo.ipynb, it does not work.
Here is my code:
```python
config_file = './checkpoints/rtmdet_tiny_8xb32-300e_coco.py'
checkpoint_file = './checkpoints/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'
cfg = Config.fromfile(config_file)
cfg.model = ConfigDict(**cfg.tta_model, module=cfg.model)
cfg.test_dataloader.dataset.pipeline = cfg.tta_pipeline
model = init_detector(cfg, checkpoint_file, device='cuda:0')
```
and I got the error
```sh
Traceback (most recent call last):
  File "infer.py", line 24, in <module>
    model = init_detector(cfg, checkpoint_file, device='cuda:0')  # or device='cpu'
  File "mmdetection-3.0.0/mmdet/apis/inference.py", line 57, in init_detector
    elif 'init_cfg' in config.model.backbone:
  File "/opt/conda/envs/mmdet3/lib/python3.8/site-packages/mmengine/config/config.py", line 54, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'backbone'
```
seems that after `cfg.model = ConfigDict(**cfg.tta_model, module=cfg.model)`, cfg.model no longer have the backbone attribute

**Comment by jamiechoi1995** [comment]
Solution: https://github.com/open-mmlab/mmyolo/blob/dc85144fab20a970341550794857a2f2f9b11564/demo/large_image_demo.py#L109-L129
