### ISSUE TITLE
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

### ISSUE THREAD

**Issue by pengweicug** [open-mmlab/mmdetection#10375]
**Reproduction**

1. What command or script did you run?

python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cpu

**Environment**

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \
      via:conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
      pytorch version 2.0 and cuda version 11.8 
   
**Error traceback**
If applicable, paste the error trackback here.
Traceback (most recent call last):
  File "C:\Users\pengwei\mmdetection\demo\image_demo.py", line 29, in <module>
    from mmdet.apis import DetInferencer
  File "c:\users\pengwei\mmdetection\mmdet\__init__.py", line 2, in <module>
    import mmcv
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\__init__.py", line 4, in <module>
    from .image import *
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\image\__init__.py", line 11, in <module>
    from .photometric import (adjust_brightness, adjust_color, adjust_contrast,
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\image\photometric.py", line 8, in <module>
    from PIL import Image, ImageEnhance
  File "E:\Anaconda3\envs\openmmlab\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by pengweicug** [comment]
i get reason pillow's version not match python's version
