### ISSUE TITLE
Error while installing MMDetection

### ISSUE THREAD

**Issue by ydzat** [open-mmlab/mmdetection#10371]
I follow [GET STARTED](https://mmdetection.readthedocs.io/en/latest/get_started.html#best-practices) to install on my lab computer, the system description of the laboratory is [here](https://doc.zih.tu-dresden.de/quickstart/getting_started/).

There are no problems with the previous steps until:

_Step 1. Install MMDetection.
Case a: If you develop and run mmdet directly, install it from source:_

```
(openmmlab) username@tauruslogin5:~/workspace/mmdetection> pip3 install -v -e .
Using pip 23.0.1 from /home/username/.conda/envs/openmmlab/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/h6/username/workspace/mmdetection
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info
  writing /tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'mmdet/VERSION'
  warning: no files found matching 'mmdet/.mim/model-index.yml'
  warning: no files found matching 'mmdet/.mim/demo/*/*'
  warning: no files found matching '*.py' under directory 'mmdet/.mim/configs'
  warning: no files found matching '*.yml' under directory 'mmdet/.mim/configs'
  warning: no files found matching '*.sh' under directory 'mmdet/.mim/tools'
  warning: no files found matching '*.py' under directory 'mmdet/.mim/tools'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-_nmpijqr/mmdet.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /home/h6/username/.conda/envs/openmmlab/lib/python3.8/site-packages (from mmdet==3.0.0) (3.7.1)
Requirement already satisfied: numpy in /home/h6/username/.conda/envs/openmmlab/lib/python3.8/site-packages (from mmdet==3.0.0) (1.24.3)
Collecting pycocotools
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Running command pip subprocess to install build dependencies
  Collecting cython>=0.27.3
    Using cached Cython-0.29.34-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
  Collecting oldest-supported-numpy
    Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
  Collecting setuptools>=43.0.0
    Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
  Collecting numpy==1.17.3
    Using cached numpy-1.17.3-cp38-cp38-manylinux1_x86_64.whl (20.5 MB)
  Installing collected packages: wheel, setuptools, numpy, cython, oldest-supported-numpy
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  pandas 2.0.1 requires numpy>=1.20.3; python_version < "3.10", but you have numpy 1.17.3 which is incompatible.
  matplotlib 3.7.1 requires numpy>=1.20, but you have numpy 1.17.3 which is incompatible.
  Successfully installed cython-0.29.34 numpy-1.17.3 oldest-supported-numpy-2022.11.19 setuptools-67.8.0 wheel-0.40.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 17, in <module>
      from . import multiarray
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/multiarray.py", line 14, in <module>
      from . import overrides
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: /tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/username/.conda/envs/openmmlab/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/home/username/.conda/envs/openmmlab/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/username/.conda/envs/openmmlab/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 7, in <module>
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/__init__.py", line 142, in <module>
      from . import core
    File "/tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 47, in <module>
      raise ImportError(msg)
  ImportError:

  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

  Importing the numpy c-extensions failed.
  - Try uninstalling and reinstalling numpy.
  - If you have already done that, then:
    1. Check that you expected to use Python3.8 from "/home/username/.conda/envs/openmmlab/bin/python",
       and that you have no directories in your PATH or PYTHONPATH that can
       interfere with the Python and numpy version "1.17.3" you're trying to use.
    2. If (1) looks fine, you can open a new issue at
       https://github.com/numpy/numpy/issues.  Please include details on:
       - how you installed Python
       - how you installed numpy
       - your operating system
       - whether or not you have multiple versions of Python installed
       - if you built from source, your compiler versions and ideally a build log

  - If you're working with a numpy git repository, try `git clean -xdf`
    (removes all files not under version control) and rebuild numpy.

  Note: this error has many possible causes, so please don't comment on
  an existing issue about this - open a new one instead.

  Original error was: /tmp/pip-build-env-_pplywnw/overlay/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/username/.conda/envs/openmmlab/bin/python /home/username/.conda/envs/openmmlab/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp6x9894s7
  cwd: /tmp/pip-install-kjh6x_84/pycocotools_2457bf3011ed4a13ae99c3efaa4f5d42
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Packages installed by pip:

```
Package             Version
------------------- --------
addict              2.4.0
brotlipy            0.7.0
certifi             2023.5.7
cffi                1.15.1
charset-normalizer  2.0.4
click               8.1.3
colorama            0.4.6
contourpy           1.0.7
cryptography        39.0.1
cycler              0.11.0
filelock            3.9.0
fonttools           4.39.4
gmpy2               2.1.2
idna                3.4
importlib-metadata  6.6.0
importlib-resources 5.12.0
Jinja2              3.1.2
kiwisolver          1.4.4
Markdown            3.4.3
markdown-it-py      2.2.0
MarkupSafe          2.1.1
matplotlib          3.7.1
mdurl               0.1.2
mkl-fft             1.3.6
mkl-random          1.2.2
mkl-service         2.4.0
mmcv                2.0.0
mmengine            0.7.3
model-index         0.1.11
mpmath              1.2.1
networkx            2.8.4
numpy               1.24.3
opencv-python       4.7.0.72
openmim             0.3.7
ordered-set         4.1.0
packaging           23.1
pandas              2.0.1
Pillow              9.4.0
pip                 23.0.1
pycparser           2.21
Pygments            2.15.1
pyOpenSSL           23.0.0
pyparsing           3.0.9
PySocks             1.7.1
python-dateutil     2.8.2
pytz                2023.3
PyYAML              6.0
requests            2.29.0
rich                13.3.5
setuptools          67.8.0
six                 1.16.0
sympy               1.11.1
tabulate            0.9.0
termcolor           2.3.0
tomli               2.0.1
torch               2.0.1
torchvision         0.15.2
typing_extensions   4.5.0
tzdata              2023.3
urllib3             1.26.15
wheel               0.38.4
yapf                0.33.0
zipp                3.15.0
```

what have i done? (but no use)

1. Reinstall numpy via pip
2. try different versions of numpy (1.17.3, 1.20.0, 1.20.3, 1.24.3)
3. Manually create a tmp folder in my $HOME directory. 
```
(openmmlab) username@tauruslogin5:~> echo $HOME
/home/username
(openmmlab) username@tauruslogin5:~>mkdir -p $HOME/tmp
```
4. `pip3 install -v -e .` 

What is the problem? What should I do? Please help me!

**Comment by jokulsarlon777** [comment]
I have a same error message when I install previous version of mmdectection like 2.28.2
But I couldn't solve it

**Comment by ydzat** [comment]
> I have a same error message when I install previous version of mmdectection like 2.28.2 But I couldn't solve it

I solved this problem by myself, please refer to the following steps(I don't know which step actually works):
1. Install pycocotools manually, to do this, several of its dependencies need to be installed first:
    `pip install cython numpy`
2. Correct steps to install pycocotools, refer to [this](https://github.com/matterport/Mask_RCNN/issues/6#issuecomment-341623963)
(I didn't add sudo after executing it, it can also)
```
cd coco/PythonAPI
make
sudo make install
sudo python setup.py install
```
Then a few warnings will pop up, don't worry about it. Back to our mmdetection, `pip install -v -e .`, and success!
