### ISSUE TITLE
libgeos_c.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shirwy** [open-mmlab/mmdetection#10383]
Successfully installed mmcv-2.0.0
(pytorch1.8.1) [ma-user work]$python test2.py 
[W OperatorEntry.cpp:133] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::is_pinned(Tensor self, Device? device=None) -> (bool)
    registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: BackendSelect
  previous kernel: registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:606
       new kernel: registered at /usr1/workspace/FPTA_Daily_open_pytorchv1.11.0/CODE/torch_npu/csrc/aten/PinMemory.cpp:42 (function registerKernel)
[W OperatorEntry.cpp:133] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::_pin_memory(Tensor self, Device? device=None) -> (Tensor)
    registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: BackendSelect
  previous kernel: registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:606
       new kernel: registered at /usr1/workspace/FPTA_Daily_open_pytorchv1.11.0/CODE/torch_npu/csrc/aten/PinMemory.cpp:42 (function registerKernel)
[W OperatorEntry.cpp:133] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::empty.memory_format(int[] size, *, int? dtype=None, int? layout=None, Device? device=None, bool? pin_memory=None, int? memory_format=None) -> (Tensor)
    registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: CPU
  previous kernel: registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:606
       new kernel: registered at /usr1/workspace/FPTA_Daily_open_pytorchv1.11.0/CODE/torch_npu/csrc/aten/common/EmptyTensor.cpp:115 (function registerKernel)
[W OperatorEntry.cpp:133] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::empty_strided(int[] size, int[] stride, *, int? dtype=None, int? layout=None, Device? device=None, bool? pin_memory=None) -> (Tensor)
    registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: CPU
  previous kernel: registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:606
       new kernel: registered at /usr1/workspace/FPTA_Daily_open_pytorchv1.11.0/CODE/torch_npu/csrc/aten/common/EmptyTensor.cpp:115 (function registerKernel)
[W OperatorEntry.cpp:133] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::_has_compatible_shallow_copy_type(Tensor self, Tensor from) -> (bool)
    registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: (catch all)
  previous kernel: registered at /usr1/v1.11.0/pytorch/build/aten/src/ATen/RegisterCompositeImplicitAutograd.cpp:10303
       new kernel: registered at /usr1/workspace/FPTA_Daily_open_pytorchv1.11.0/CODE/torch_npu/csrc/aten/ops/HasCompatibleShallowCopyType.cpp:37 (function registerKernel)
Traceback (most recent call last):
  File "test2.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/apis/det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/evaluation/__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/evaluation/metrics/__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/datasets/__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/datasets/utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/datasets/transforms/__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/datasets/transforms/formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/structures/bbox/__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/structures/bbox/base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/mmdet/structures/mask/structures.py", line 10, in <module>
    import shapely.geometry as geometry
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/shapely/geometry/__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/shapely/geometry/base.py", line 20, in <module>
    from shapely.coords import CoordinateSequence
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/shapely/coords.py", line 10, in <module>
    from shapely.geos import lgeos
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/site-packages/shapely/geos.py", line 93, in <module>
    _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
  File "/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/ma-user/anaconda3/envs/pytorch1.8.1/lib/libgeos_c.so: cannot open shared object file: No such file or directory
THPModule_npu_shutdown success.

run ：
from mmdet.apis import init_detector, inference_detector

config_file = 'rtmdet_tiny_8xb32-300e_coco.py'
checkpoint_file = 'rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth'
model = init_detector(config_file, checkpoint_file, device='cpu')  # or device='cuda:0'
inference_detector(model, 'demo/demo.jpg')

**Comment by furh20** [comment]
you can find the libgeos_c.so by 'whereis libgeos_c.so'，and copy it into '/home/ma-user/anaconda3/envs/pytorch1.8.1/lib/'
libgeos_c: /usr/lib64/libgeos_c.so 
cp /usr/lib64/libgeos_c.so /home/ma-user/anaconda3/envs/pytorch1.8.1/lib/

**Comment by congw729** [comment]
I upgraded the `shapely` package from 1.8.x to 2.0.2 and it fixed this Error.  Hope it could help others.

**Comment by smalltoyfox** [comment]
run : conda install geos
