### ISSUE TITLE
KeyError: 'img_prefix'

### ISSUE THREAD

**Issue by mc-lgt** [open-mmlab/mmdetection#10427]
Traceback (most recent call last):
  File "D:\deeplearning\mmdetection_main\tools\train.py", line 136, in <module>
    main()
  File "D:\deeplearning\mmdetection_main\tools\train.py", line 132, in main
    runner.train()
  File "D:\anaconda3\lib\site-packages\mmengine\runner\runner.py", line 1721, in train
    model = self.train_loop.run()  # type: ignore
  File "D:\anaconda3\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "D:\anaconda3\lib\site-packages\mmengine\runner\loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\anaconda3\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 413, in __getitem__
    data = self.prepare_data(idx)
  File "D:\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 797, in prepare_data
    return self.pipeline(data_info)
  File "D:\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 59, in __call__
    data = t(data)
  File "D:\deeplearning\mmdetection_main\mmdet\datasets\transforms\loading.py", line 27, in __call__
    if results['img_prefix'] is not None:
KeyError: 'img_prefix'

Does anyone know what this is about?

**Comment by imadgohar** [comment]
@mc-lgt Have you solved this issue? I am also facing the same issue.
