### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Weizhen-Fang** [open-mmlab/mmdetection#1042]
When i run "python setup.py install" command, it said:

Download error on https://pypi.org/simple/pytest-runner/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    zip_safe=False)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

how to fix it?

**Comment by HuangQinJian** [comment]
> When i run "python setup.py install" command, it said:
> 
> Download error on https://pypi.org/simple/pytest-runner/: [Errno -2] Name or service not known -- Some packages may not be found!
> Couldn't find index page for 'pytest-runner' (maybe misspelled?)
> Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
> No local packages or working download links found for pytest-runner
> Traceback (most recent call last):
> File "setup.py", line 199, in 
> zip_safe=False)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/**init**.py", line 144, in setup
> _install_setup_requires(attrs)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/**init**.py", line 139, in _install_setup_requires
> dist.fetch_build_eggs(dist.setup_requires)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
> replace_conflicting=True,
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/**init**.py", line 782, in resolve
> replace_conflicting=replace_conflicting
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/**init**.py", line 1065, in best_match
> return self.obtain(req, installer)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/**init**.py", line 1077, in obtain
> return installer(requirement)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
> return cmd.easy_install(req)
> File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
> raise DistutilsError(msg)
> distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
> 
> how to fix it?

I also met this error,hou to fix it?Thanks!

**Comment by milleniums** [comment]
请问如何解决的？
