### ISSUE TITLE
Can not train own dataset  use multi-GPU

### ISSUE THREAD

**Issue by Weizhen-Fang** [open-mmlab/mmdetection#1043]
I tried to train my own dataset  use multi-GPU , but it got some errors, here is log:

(open-mmlab) [weizhenfang@gpu mmdetection]$ ./tools/dist_train.sh configs/football_mask_rcnn_x101_64x4d_fpn_1x.py 4
2019-07-23 15:21:15,421 - INFO - Distributed training: True
2019-07-23 15:21:18,200 - INFO - load model from: open-mmlab://resnext101_64x4d
2019-07-23 15:21:22,571 - WARNING - missing keys in source state_dict: layer3.12.bn2.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer1.0.bn3.num_batches_tracked,         layer3.3.bn2.num_batches_tracked, layer3.11.bn1.num_batches_tracked, layer3.17.bn3.num_batches_tracked, layer3.19.bn3.num_batches_tracked, layer2.0.downsample.1.num_batches_t        racked, layer4.0.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer3.22.bn2.num_batches_tracked, layer3.3.bn1.num_batches_trac        ked, layer3.19.bn1.num_batches_tracked, layer3.12.bn3.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, bn1.num_batches_tracked, layer3        .6.bn1.num_batches_tracked, layer3.9.bn2.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.20.bn3.num_batches_tracked, layer3.11.bn2.num_batches_tracked, layer3.6        .bn3.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.0.dow        nsample.1.num_batches_tracked, layer3.17.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.18.bn3.num_batches_tracked, layer3.7.bn1.num_batches_tracked, layer        3.0.bn1.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.20.bn2.num_batches_tracked, layer3.11.bn3.num_batches_tracked, layer3.        7.bn2.num_batches_tracked, layer3.8.bn1.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.8.bn3.num_batches_tracked, layer3.15.bn1.num_batches_tracked, layer3.9.b        n3.num_batches_tracked, layer3.13.bn3.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer1.1.bn2.        num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.9.bn1.num_batches_tracked, layer3.7.bn3.num_batches_tracked, layer2.0.bn3.num_        batches_tracked, layer3.4.bn1.num_batches_tracked, layer3.18.bn2.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.18.bn1.num_ba        tches_tracked, layer3.13.bn2.num_batches_tracked, layer3.10.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.12.bn1.num_bat        ches_tracked, layer3.14.bn1.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer2.0.bn2.num_batche        s_tracked, layer4.0.downsample.1.num_batches_tracked, layer3.19.bn2.num_batches_tracked, layer3.15.bn3.num_batches_tracked, layer3.22.bn3.num_batches_tracked, layer3.21.bn3.n        um_batches_tracked, layer3.1.bn3.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.22.bn1.num_batches_tracked, layer3.16.bn3.num_batches_tracked, layer3.21.bn2.nu        m_batches_tracked, layer3.6.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.10.bn1.num_batches_tracked, layer3.14.bn3.num_batches_tracked, layer3.2.bn2.num_        batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.17.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.21.b        n1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.14.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.16.bn2.num_batches_tracked, layer3.16.bn        1.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.13.bn1.num_batches_tracked, layer3.10.bn2.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.5.bn3.        num_batches_tracked, layer3.8.bn2.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.15.bn2.num_batches_tracked, layer3.20.bn1.nu        m_batches_tracked

loading annotations into memory...
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
Done (t=0.05s)
creating index...
index created!
loading annotations into memory...
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
Done (t=0.05s)
creating index...
index created!
2019-07-23 15:21:23,261 - INFO - Start running, host: weizhenfang@gpu, work_dir: /share/home/weizhenfang/Playground/mmdetection/work_dirs/mask_rcnn_x101_64x4d_fpn_1x
2019-07-23 15:21:23,261 - INFO - workflow: [('train', 1)], max: 50 epochs
Traceback (most recent call last):
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/share/home/weizhenfang/.conda/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/football_mask_rcnn_        x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' died with <Signals.SIGSEGV: 11>.
(open-mmlab) [weizhenfang@gpu mmdetection]$ /share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))
/share/home/weizhenfang/.conda/envs/open-mmlab/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 14 leaked semaphores to clean up at shutdown
  len(cache))

how to fix it?

**Comment by ferranrigual** [comment]
SIGSEGV tells me that you are probably trying to access an array element out of bounds or trying to use too much memory.

Is the memory on your GPU big enough?

**Comment by aaxwaz** [comment]
I am having the exact same error with @Weizhen-Fang  Weizhen-Fang when I tried to train my own dataset with multi-gpu. 

I don't think it is due to GPU memory, as I have enough memory, and I tried to reduce number gpus, number of workers, or images per gpu, but the error was still there. 

Are there any solutions to this?

**Comment by mosheliv** [comment]
Does it work on single gpu? Its easier to debug. Reduce batch size, doesn't
matter.

**Comment by aaxwaz** [comment]
@mosheliv I am having `Segmentation fault` when running single GPU.

**Comment by mosheliv** [comment]
And I guess training on coco is fine?

**Comment by mosheliv** [comment]
If training on coco is fine, most probable cause would be mistakes in the
annotation conversion.

**Comment by aaxwaz** [comment]
Haven't tried on coco yet. I probably would try coco to see if you are right, but I think my conversion script should be ok, as I followed the instruction to implement a subclass from `CustomDataset`, writing the two functions of `load_annotations` and `get_ann_info` to return what's required.

**Comment by Weizhen-Fang** [comment]
@aaxwaz I just fixed this issue by check my own dataset that if the image's height and width labeled in json file matches its real size. When I fixed some mistake in json, it worked~

**Comment by aaxwaz** [comment]
@Weizhen-Fang Thanks but I checked and cleaned the data, leaving only 100 images with correct dimensions just to give a try, and still got the error: 

`Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/ec2-user/anaconda3/envs/pytorch_p36/bin/python3', '-u', './tools/train.py', '--local_rank=0', './configs/my_configs/cascade_rcnn_x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' died with <Signals.SIGSEGV: 11>.
(pytorch_p36) [ec2-user@master mmdetection]$ /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
`

**Comment by Weizhen-Fang** [comment]
@aaxwaz Oh, I remember that, u should check that is your GCC is 4.9 or higher, if not try to update it to a higher version

**Comment by aaxwaz** [comment]
@Weizhen-Fang thanks again! 

But I updated my GCC to new one: 

gcc --version
gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

but unfortunately, I still got the same error ...

**Comment by mosheliv** [comment]
Did you try coco? also, try to do the 100 images with no bboxes, just to be
extra sure its not something in the data.

**Comment by aaxwaz** [comment]
not yet on coco, but I also tried this code - https://github.com/MyLtYkRiTiK/ComputerVision_Tutorials_in_Russian/blob/master/ObjectDetection_TransferLearning_with_mmdetection/object_detection_transfer_learning_mmdetection.ipynb - which basically converts data into coco format. 

I used the same data and conversion script like her, and 

and I got the same error as well.

**Comment by mosheliv** [comment]
Another option to try is the docker image. This will tell you if its an
installation problem or something else

**Comment by aaxwaz** [comment]
@mosheliv ok thanks!
