### ISSUE TITLE
ImportError: cannot import name 'load_checkpoint' from 'mmcv.runner' (unknown location)

### ISSUE THREAD

**Issue by haojun0318** [open-mmlab/mmdetection#10445]
(open-mmlab) xuhj@k8s:/opt/data2/xuhj_projects/xuhj_projects/mmskeleton$ python mmskl.py pose_demo
Traceback (most recent call last):
  File "mmskl.py", line 7, in <module>
    import mmskeleton
  File "/opt/data2/xuhj_projects/xuhj_projects/mmskeleton/mmskeleton/__init__.py", line 1, in <module>
    from . import utils
  File "/opt/data2/xuhj_projects/xuhj_projects/mmskeleton/mmskeleton/utils/__init__.py", line 3, in <module>
    from .checkpoint import load_checkpoint, get_mmskeleton_url, cache_checkpoint
  File "/opt/data2/xuhj_projects/xuhj_projects/mmskeleton/mmskeleton/utils/checkpoint.py", line 1, in <module>
    from mmcv.runner import load_checkpoint as mmcv_load_checkpoint
ImportError: cannot import name 'load_checkpoint' from 'mmcv.runner' (unknown location)

**Comment by Lokesh-26** [comment]
Hi @carlosgomez1987, I am facing the same problem. Did you solve it already?

**Comment by carlosgomez1987** [comment]
Hello @Lokesh-26 I resolved this problem as follows:

1. `!pip install openmim mmengine`
`!mim install mmcv`
`!rm -rf mmdetection`
`!git clone https://github.com/open-mmlab/mmdetection.git`
`%cd mmdetection`
`!pip install -e .` 

2. I shared an example of my configuration 
`import mmcv`
`import mmengine`
`from mmdet.apis import init_detector, inference_detector`
`from mmdet.utils import register_all_modules`

   `config_file = 'checkpoints/pisa_faster_rcnn_r50_fpn_1x_coco.py'`

   `checkpoint_file = 'checkpoints/pisa_faster_rcnn_r50_fpn_1x_coco-dea93523.pth'`

   `register_all_modules()`

   `model = init_detector(config_file, checkpoint_file, device='cuda:0')`

**Comment by HoSiThien137** [comment]
Halo @Lokesh-26 new version mmcv remove mmcv.runner I resolved this problem as follows: 
from mmengine.runner import load_checkpoint as mmcv_load_checkpoint
from mmengine.fileio import get as load_from_uri
import urllib


mmskeleton_model_urls = {
    'st_gcn/kinetics-skeleton': "https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmskeleton/models/st-gcn/st_gcn.kinetics-6fa43f73.pth",
    'st_gcn/ntu-xsub': "https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmskeleton/models/st-gcn/st_gcn.ntu-xsub-300b57d4.pth",
    'st_gcn/ntu-xview': "https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmskeleton/models/st-gcn/st_gcn.ntu-xview-9ba67746.pth",
    'mmdet/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e': 'https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmskeleton/models/mmdet/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e_20190408-0e50669c.pth',
    'pose_estimation/pose_hrnet_w32_256x192': 'https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmskeleton/models/pose_estimation/pose_hrnet_w32_256x192-76ea353b.pth',
    'mmdet/cascade_rcnn_r50_fpn_20e': 'https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r50_fpn_20e_coco/cascade_rcnn_r50_fpn_20e_coco_bbox_mAP-0.41_20200504_175131-e9872a90.pth',
}  # yapf: disable


def load_checkpoint(model, filename, *args, **kwargs):
    try:
        filename = get_mmskeleton_url(filename)
        return mmcv_load_checkpoint(model, filename, *args, **kwargs)
    except (urllib.error.HTTPError, urllib.error.URLError) as e:
        raise Exception(url_error_message.format(filename)) from e


def get_mmskeleton_url(filename):
    if filename.startswith('mmskeleton://'):
        model_name = filename[13:]
        model_url = mmskeleton_model_urls.get(model_name)
        return model_url
    return filename


def cache_checkpoint(filename):
    try:
        filename = get_mmskeleton_url(filename)
        load_from_uri(filename)  # Đã đổi tên hàm để tải từ URL
    except (urllib.error.HTTPError, urllib.error.URLError) as e:
        raise Exception(url_error_message.format(filename)) from e


url_error_message = """

==================================================
MMSkeleton fail to load checkpoint from url: 
    {}
Please check your network connection. Or manually download checkpoints according to the instructor:
    https://github.com/open-mmlab/mmskeleton/blob/master/doc/MODEL_ZOO.md
"""
