### ISSUE TITLE
ValueError: class `ConcatDataset` in mmengine/dataset/dataset_wrapper.py: The meta information of the 2-th dataset does not match meta information of the first dataset

### ISSUE THREAD

**Issue by priya091989** [open-mmlab/mmdetection#10474]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/mmengine/dataset/dataset_wrapper.py", line 77, in __init__
    raise ValueError(
ValueError: The meta information of the 2-th dataset does not match meta information of the first dataset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/mmengine/runner/loops.py", line 219, in __init__
    super().__init__(runner, dataloader)
  File "/usr/local/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/usr/local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1346, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ValueError: class `ConcatDataset` in mmengine/dataset/dataset_wrapper.py: The meta information of the 2-th dataset does not match meta information of the first dataset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/properpay/mmdetection/tools/train.py", line 133, in <module>
    main()
  File "/properpay/mmdetection/tools/train.py", line 129, in main
    runner.train()
  File "/usr/local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1687, in train
    self._train_loop = self.build_train_loop(
  File "/usr/local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1479, in build_train_loop
    loop = LOOPS.build(
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
ValueError: class `IterBasedTrainLoop` in mmengine/runner/loops.py: class `ConcatDataset` in mmengine/dataset/dataset_wrapper.py: The meta information of the 2-th dataset does not match meta information of the first dataset

**Comment by oomq** [comment]
Have you solved the problem?

**Comment by LicharYuan** [comment]
try add  `ignore_keys=['dataset_type']`
as it shows in `configs/_base_/datasets/voc0712`: https://github.com/open-mmlab/mmdetection/blob/main/configs/_base_/datasets/voc0712.py#L51

**Comment by lxysimple** [comment]
```
go to:

"/usr/local/lib/python3.9/site-packages/mmengine/dataset/dataset_wrapper.py", line 77

and then cut out the code:

# if (isinstance(self._metainfo[key], np.ndarray)
#         and not np.array_equal(self._metainfo[key],
#                                dataset.metainfo[key])
#         or (not isinstance(self._metainfo[key], np.ndarray)
#             and self._metainfo[key] != dataset.metainfo[key])):
#     raise ValueError(
#         f'The meta information of the {i}-th dataset does not '
#         'match meta information of the first dataset')

OK.
```
