### ISSUE TITLE
An error occurred while training the VOC dataset with mmdetection

### ISSUE THREAD

**Issue by SZUcby** [open-mmlab/mmdetection#10601]
**Describe the bug**
Traceback (most recent call last):
  File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/voc.py", line 24, in __init__
    super().__init__(**kwargs)
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 30, in __init__
    super().__init__(**kwargs)
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 40, in __init__
    super().__init__(*args, **kwargs)
  File "/home/mmengine-main/mmengine/dataset/base_dataset.py", line 245, in __init__
    self.full_init()
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 65, in full_init
    self.data_list = self.load_data_list()
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 63, in load_data_list
    parsed_data_info = self.parse_data_info(raw_img_info)
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 110, in parse_data_info
    data_info['instances'] = self._parse_instance_info(
  File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 138, in _parse_instance_info
    int(float(bnd_box.find('xmin').text)),
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/mmengine-main/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/home/mmengine-main/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/mmengine-main/mmengine/runner/runner.py", line 1351, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
AttributeError: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/mmengine-main/mmengine/runner/runner.py", line 1701, in train
    self._train_loop = self.build_train_loop(
  File "/home/mmengine-main/mmengine/runner/runner.py", line 1493, in build_train_loop
    loop = LOOPS.build(
  File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
**AttributeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'**

**Environment**
python tools/train.py configs/pascal_voc/faster-rcnn_r50_fpn_1x_voc0712.py --work-dir WORK_DIR --auto-scale-lr 
mmdet3.0
latest mmcv, mmengine
follow  [](https://mmdetection.readthedocs.io/zh_CN/latest/get_started.html)

![1688629251916](https://github.com/open-mmlab/mmdetection/assets/138761865/420919bd-1c30-4dd0-8bb1-5e515afe7e88)
![1688629297398](https://github.com/open-mmlab/mmdetection/assets/138761865/e550a05a-e99b-4dd9-8b96-509b40096273)

please, help me

**Comment by SZUcby** [comment]
follow  [https://mmdetection.readthedocs.io/zh_CN/latest/get_started.html](url)

**Comment by makalsue** [comment]
> **Describe the bug** Traceback (most recent call last): File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/voc.py", line 24, in **init** super().**init**(**kwargs) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 30, in **init** super().**init**(**kwargs) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 40, in **init** super().**init**(*args, **kwargs) File "/home/mmengine-main/mmengine/dataset/base_dataset.py", line 245, in **init** self.full_init() File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 65, in full_init self.data_list = self.load_data_list() File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 63, in load_data_list parsed_data_info = self.parse_data_info(raw_img_info) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 110, in parse_data_info data_info['instances'] = self._parse_instance_info( File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 138, in _parse_instance_info int(float(bnd_box.find('xmin').text)), AttributeError: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/home/mmengine-main/mmengine/runner/loops.py", line 44, in **init** super().**init**(runner, dataloader) File "/home/mmengine-main/mmengine/runner/base_loop.py", line 26, in **init** self.dataloader = runner.build_dataloader( File "/home/mmengine-main/mmengine/runner/runner.py", line 1351, in build_dataloader dataset = DATASETS.build(dataset_cfg) File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg raise type(e)( AttributeError: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "tools/train.py", line 133, in main() File "tools/train.py", line 129, in main runner.train() File "/home/mmengine-main/mmengine/runner/runner.py", line 1701, in train self._train_loop = self.build_train_loop( File "/home/mmengine-main/mmengine/runner/runner.py", line 1493, in build_train_loop loop = LOOPS.build( File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg raise type(e)( **AttributeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'**
> 
> **Environment** python tools/train.py configs/pascal_voc/faster-rcnn_r50_fpn_1x_voc0712.py --work-dir WORK_DIR --auto-scale-lr mmdet3.0 latest mmcv, mmengine follow
> 
> ![1688629251916](https://user-images.githubusercontent.com/138761865/251379720-420919bd-1c30-4dd0-8bb1-5e515afe7e88.png) ![1688629297398](https://user-images.githubusercontent.com/138761865/251379914-e550a05a-e99b-4dd9-8b96-509b40096273.png)
> 
> please, help me

Have you solved the problem yet? Thanks a lot!

**Comment by makalsue** [comment]
> **Describe the bug** Traceback (most recent call last): File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/voc.py", line 24, in **init** super().**init**(**kwargs) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 30, in **init** super().**init**(**kwargs) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 40, in **init** super().**init**(*args, **kwargs) File "/home/mmengine-main/mmengine/dataset/base_dataset.py", line 245, in **init** self.full_init() File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/base_det_dataset.py", line 65, in full_init self.data_list = self.load_data_list() File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 63, in load_data_list parsed_data_info = self.parse_data_info(raw_img_info) File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 110, in parse_data_info data_info['instances'] = self._parse_instance_info( File "/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet-3.0.0-py3.8.egg/mmdet/datasets/xml_style.py", line 138, in _parse_instance_info int(float(bnd_box.find('xmin').text)), AttributeError: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/mmengine-main/mmengine/registry/build_functions.py", line 122, in build_from_cfg obj = obj_cls(**args) # type: ignore File "/home/mmengine-main/mmengine/runner/loops.py", line 44, in **init** super().**init**(runner, dataloader) File "/home/mmengine-main/mmengine/runner/base_loop.py", line 26, in **init** self.dataloader = runner.build_dataloader( File "/home/mmengine-main/mmengine/runner/runner.py", line 1351, in build_dataloader dataset = DATASETS.build(dataset_cfg) File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg raise type(e)( AttributeError: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "tools/train.py", line 133, in main() File "tools/train.py", line 129, in main runner.train() File "/home/mmengine-main/mmengine/runner/runner.py", line 1701, in train self._train_loop = self.build_train_loop( File "/home/mmengine-main/mmengine/runner/runner.py", line 1493, in build_train_loop loop = LOOPS.build( File "/home/mmengine-main/mmengine/registry/registry.py", line 570, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/mmengine-main/mmengine/registry/build_functions.py", line 144, in build_from_cfg raise type(e)( **AttributeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `VOCDataset` in mmdet/datasets/voc.py: 'NoneType' object has no attribute 'text'**
> 
> **Environment** python tools/train.py configs/pascal_voc/faster-rcnn_r50_fpn_1x_voc0712.py --work-dir WORK_DIR --auto-scale-lr mmdet3.0 latest mmcv, mmengine follow
> 
> ![1688629251916](https://user-images.githubusercontent.com/138761865/251379720-420919bd-1c30-4dd0-8bb1-5e515afe7e88.png) ![1688629297398](https://user-images.githubusercontent.com/138761865/251379914-e550a05a-e99b-4dd9-8b96-509b40096273.png)
> 
> please, help me

Have you solved it yet? Please provide me with details and solutions, thanks a lot!
