### ISSUE TITLE
mmengine KeyError: 'PoseLocalVisualizer is not in the visualizer registry.

### ISSUE THREAD

**Issue by seon-creator** [open-mmlab/mmdetection#10600]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?
python tools/train.py /data/home/seondeok/mmpose/configs/body_2d_keypoint/topdown_heatmap/custom_model_coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192.py

```none
A placeholder for the command.
```

# custom model
_base_ = ['../../../_base_/default_runtime.py']

# runtime
train_cfg = dict(max_epochs=300, val_interval=10)   # edit

# optimizer
optim_wrapper = dict(optimizer=dict(
    type='Adam',
    lr=5e-4,
))

# learning policy
param_scheduler = [
    dict(
        type='LinearLR', begin=0, end=500, start_factor=0.001,
        by_epoch=False),  # warm-up
    dict(
        type='MultiStepLR',
        begin=0,
        end=210,
        milestones=[170, 200],
        gamma=0.1,
        by_epoch=True)
]

# automatically scaling LR based on the actual training batch size
auto_scale_lr = dict(base_batch_size=512)

# hooksCocoDataset
default_hooks = dict(checkpoint=dict(save_best='coco/AP', rule='greater'))

# codec settings
codec = dict(
    type='MSRAHeatmap', input_size=(192, 256), heatmap_size=(48, 64), sigma=2)

# model settings
model = dict(
    type='TopdownPoseEstimator',
    data_preprocessor=dict(
        type='PoseDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True),
    backbone=dict(
        type='HRNet',
        in_channels=3,
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(32, 64)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(32, 64, 128)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(32, 64, 128, 256))),
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmpose/'
            'pretrain_models/hrnet_w32-36af842e.pth'),
    ),
    head=dict(
        type='HeatmapHead',
        in_channels=32,
        out_channels=5, # edit : counts of keypoints are five
        deconv_out_channels=None,
        loss=dict(type='KeypointMSELoss', use_target_weight=True),
        decoder=codec),
    test_cfg=dict(
        flip_test=False,    # edit
        flip_mode='heatmap',
        shift_heatmap=True,
    ))

# base dataset settings
dataset_type = 'CocoDataset'
data_mode = 'topdown'
data_root = 'datasets/'     # edit

# pipelines
train_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage'),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=64,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='/data/home/seondeok/mmpose/datasets/segmentation_train/segmentation_train.json',   # edit
        # data_prefix : image folder
        data_prefix=dict(img='/data/home/seondeok/mmpose/datasets/segmentation_train/'),    # edit
        # metainfo : specify data info
        metainfo=dict(from_file='configs/_base_/datasets/coco_arm.py'),
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='/data/home/seondeok/mmpose/datasets/segmentation_val/segmentation_val.json', # edit 
        bbox_file=None, # edit
        data_prefix=dict(img='/data/home/seondeok/mmpose/datasets/segmentation_val/'), # edit 
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file='/data/home/seondeok/mmpose/datasets/segmentation_val/segmentation_val.json') # edit 
test_evaluator = val_evaluator

3. What dataset did you use?
-- coco dataset

**Environment**
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
chumpy                    0.70                     pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
coverage                  7.2.7                    pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.35                  pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
flake8                    6.0.0                    pypi_0    pypi
fonttools                 4.40.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
interrogate               1.5.0                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
json-tricks               3.17.1                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.44.2               h5eee18b_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6d00ec8_46342  
mkl-service               2.4.0            py38h5eee18b_1  
mkl_fft                   1.3.6            py38h417a72b_1  
mkl_random                1.2.2            py38h417a72b_1  
mmcv                      2.0.0                    pypi_0    pypi
mmdet                     3.0.0                    pypi_0    pypi
mmengine                  0.7.4                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
munkres                   1.1.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
numpy                     1.24.3           py38hf6e8229_1  
numpy-base                1.24.3           py38h060ed82_1  
opencv-python             4.7.0.72                 pypi_0    pypi
opendatalab               0.0.9                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.9                h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.2                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
pillow                    9.0.1            py38h22f2fdc_0  
pip                       23.1.2           py38h06a4308_0  
platformdirs              3.8.0                    pypi_0    pypi
pluggy                    1.2.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycryptodome              3.18.0                   pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.1.0                    pypi_0    pypi
pytest                    7.4.0                    pypi_0    pypi
pytest-runner             6.0.0                    pypi_0    pypi
python                    3.8.16               h955ad1f_4  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.10.2          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.8.0           py38h06a4308_0  
shapely                   2.0.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
termcolor                 2.3.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torchvision               0.11.3               py38_cu113    pytorch
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.6.3            py38h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.3                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
xdoctest                  1.1.1                    pypi_0    pypi
xtcocotools               1.13                     pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yapf                      0.40.1                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0 

**Error traceback**
If applicable, paste the error trackback here.
Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 153, in main
    runner = Runner.from_cfg(cfg)
  File "/data/home/seondeok/.conda/envs/mmpose/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/data/home/seondeok/.conda/envs/mmpose/lib/python3.8/site-packages/mmengine/runner/runner.py", line 393, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/data/home/seondeok/.conda/envs/mmpose/lib/python3.8/site-packages/mmengine/runner/runner.py", line 780, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/data/home/seondeok/.conda/envs/mmpose/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/home/seondeok/.conda/envs/mmpose/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PoseLocalVisualizer is not in the visualizer registry. Please check whether the value of `PoseLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by lolbus** [comment]
similar problem with coco wholebody-hand model as pretrained checkpoint

**Comment by lolbus** [comment]
Fixed problem.

To fix this using anaconda environment, open anaconda prompt, activate your environment used to run MMPose, type conda list, make sure mmpose package is successfully listed, if not do these:
![image](https://github.com/open-mmlab/mmdetection/assets/1837762/2c07c0dd-6855-484c-b6f1-1b9f58024f57)

and verify that mmpose package is listed in your python enviornment.

**Comment by lolbus** [comment]
> 你好，我导入了mmpose，还是不行，有其他的解决方法吗

抱歉 没。 
但是建议你用google colab跑一圈 要是能跑那就是你电脑local environment问题。你也能查查看 conda list 有没包含你之前导入的mmpose 和 mmdet。 mmdet 和 mmpose 应该导入在同样的 environment 才能跑mmpose

**Comment by lzx101** [comment]
> > 你好，我导入了mmpose，还是不行，还有其他的解决方法吗？
> 
> 抱歉没。 但是建议你用google colab跑一圈如果能跑那就是你电脑本地环境的问题。你也可以查查看conda列表有没有包含你之前导入的mmpose和mmdet。mmdet和mmpose应该导入在同样的环境才能跑mmpose。我曾在本地磁盘导入了mmpose但是没有安装到conda环境才结果遇到了这个困难。
> 
> 加油

感谢你的回复，我想知道为什么要导入mmpose来解决模型不在注册表的问题

**Comment by sxj731533730** [comment]
05/12 14:55:27 - mmengine - WARNING - Failed to import `None.registry` make sure the registry.py exists in `None` package.
05/12 14:55:27 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "visualizer" registry tree. As a workaround, the current "visualizer" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "tools/train.py", line 160, in <module>
    main()
  File "tools/train.py", line 153, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 416, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 803, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'PoseLocalVisualizer is not in the mmengine::visualizer registry. Please check whether the value of `PoseLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'




我真对mm系列的环境构建 无语
ubuntu@ubuntu:~/mmpose-1.0.0$ pip3 list
Package                       Version              Editable project location
----------------------------- -------------------- -----------------------------------------------
absl-py                       2.2.2
accelerate                    1.0.1
addict                        2.4.0
aiohappyeyeballs              2.4.4
aiohttp                       3.10.11
aiosignal                     1.3.1
albucore                      0.0.17
albumentations                1.4.18
aliyun-python-sdk-core        2.16.0
aliyun-python-sdk-kms         2.16.5
annotated-types               0.7.0
antlr4-python3-runtime        4.7.2
anyio                         4.5.2
apturl                        0.5.2
asttokens                     3.0.0
async-timeout                 5.0.1
attrs                         25.3.0
awscli                        1.38.38
backcall                      0.2.0
bcrypt                        3.1.7
blinker                       1.8.2
boto3                         1.37.38
botocore                      1.37.38
Brlapi                        0.7.0
cachetools                    5.5.2
certifi                       2019.11.28
cffi                          1.17.1
chardet                       3.0.4
charset-normalizer            3.4.1
chumpy                        0.70
click                         8.1.8
colorama                      0.4.3
coloredlogs                   15.0.1
comm                          0.2.2
command-not-found             0.3
ConfigArgParse                1.7
configobj                     5.0.9
contourpy                     1.1.1
coverage                      7.6.1
crcmod                        1.7
cryptography                  44.0.2
cupshelpers                   1.0
cycler                        0.10.0
Cython                        3.0.12
dash                          3.0.4
datasets                      3.1.0
dbus-python                   1.2.16
decorator                     5.2.1
defer                         1.0.6
develop                       0.2.1
dill                          0.3.8
distro                        1.9.0
docopt                        0.6.2
docstring_parser              0.16
docutils                      0.19
duplicity                     0.8.12.0
einops                        0.8.1
entrypoints                   0.3
eval_type_backport            0.2.2
evalscope                     0.15.1
exceptiongroup                1.2.2
executing                     2.2.0
fastapi                       0.115.12
fasteners                     0.14.1
fastjsonschema                2.21.1
filelock                      3.14.0
flake8                        7.1.2
Flask                         3.0.3
flatbuffers                   25.2.10
fonttools                     4.57.0
freetype-py                   2.5.1
frozenlist                    1.5.0
fsspec                        2024.9.0
future                        0.18.2
google-api-core               2.24.2
google-auth                   2.40.0
google-auth-oauthlib          1.0.0
google-cloud-aiplatform       1.90.0
google-cloud-bigquery         3.30.0
google-cloud-core             2.4.3
google-cloud-resource-manager 1.14.2
google-cloud-storage          2.19.0
google-crc32c                 1.6.0.dev2
google-resumable-media        2.7.2
googleapis-common-protos      1.70.0
graphsurgeon                  0.4.6
grpc-google-iam-v1            0.14.2
grpcio                        1.70.0
grpcio-status                 1.70.0
h11                           0.16.0
hf-xet                        1.1.0
httpcore                      1.0.9
httplib2                      0.14.0
httpx                         0.28.1
huggingface-hub               0.31.1
humanfriendly                 10.0
idna                          2.8
imageio                       2.35.1
imagesize                     1.4.1
immutabledict                 4.2.1
importlib_metadata            8.5.0
importlib_resources           6.4.5
iniconfig                     2.1.0
interrogate                   1.7.0
ipython                       8.12.3
ipywidgets                    8.1.7
isort                         4.3.21
itsdangerous                  2.2.0
jedi                          0.19.2
jieba                         0.42.1
Jinja2                        3.1.6
jiter                         0.9.0
jmespath                      0.10.0
joblib                        1.4.2
json-tricks                   3.17.3
jsonlines                     4.0.0
jsonschema                    4.23.0
jsonschema-specifications     2023.12.1
jupyter_core                  5.7.2
jupyterlab_widgets            3.0.15
keyring                       18.0.1
kiwisolver                    1.0.1
labelImg                      1.8.6
labelme                       3.16.7
langdetect                    1.0.9
language-selector             0.1
latex2sympy2                  1.9.1
launchpadlib                  1.10.13
lazr.restfulclient            0.14.2
lazr.uri                      1.0.3
lazy_loader                   0.4
lightning-utilities           0.11.9
litellm                       1.68.1
LLMPerf                       0.1.0                /home/ubuntu/llmperf
lockfile                      0.12.2
louis                         3.12.0
lxml                          5.4.0
macaroonbakery                1.3.1
Mako                          1.1.0
Markdown                      3.7
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.7.5
matplotlib-inline             0.1.7
mccabe                        0.7.0
mdurl                         0.1.2
mmcv-full                     1.6.2
mmdet                         3.3.0
mmengine                      0.10.5
mmpose                        1.3.2                /home/ubuntu/.local/lib/python3.8/site-packages
mock                          3.0.5
model-index                   0.1.11
modelscope                    1.25.0
monotonic                     1.5
motmetrics                    1.4.0
mpmath                        1.3.0
msgpack                       1.1.0
multidict                     6.1.0
multiprocess                  0.70.16
munkres                       1.1.4
narwhals                      1.38.0
nbformat                      5.10.4
nest-asyncio                  1.6.0
netifaces                     0.10.4
networkx                      3.1
nh3                           0.2.21
nltk                          3.9.1
num2words                     0.5.14
numpy                         1.24.4
nvidia-cublas-cu11            11.10.3.66
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu11             8.5.0.96
nvidia-cudnn-cu12             9.1.0.70
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.8.93
nvidia-nvtx-cu12              12.1.105
oauthlib                      3.1.0
olefile                       0.46
omegaconf                     2.3.0
onnx                          1.17.0
onnx-simplifier               0.4.36
onnxruntime                   1.16.3
onnxslim                      0.1.51
open3d                        0.19.0
openai                        1.75.0
opencv-python                 4.11.0.86
opencv-python-headless        4.11.0.86
opendatalab                   0.0.10
openmim                       0.3.9
openxlab                      0.1.2
ordered-set                   4.1.0
oss2                          2.17.0
packaging                     24.2
pandas                        2.0.3
parameterized                 0.9.0
paramiko                      2.6.0
parso                         0.8.4
pbr                           5.4.5
pexpect                       4.6.0
pickleshare                   0.7.5
pillow                        10.4.0
pip                           25.0.1
pkgutil_resolve_name          1.3.10
platformdirs                  4.3.6
plotly                        6.0.1
pluggy                        1.5.0
portalocker                   3.0.0
poseval                       0.1.0
prompt_toolkit                3.0.51
propcache                     0.2.0
proto-plus                    1.26.1
protobuf                      5.29.4
psutil                        7.0.0
pure_eval                     0.2.3
py                            1.11.0
py-cpuinfo                    9.0.0
pyaml                         25.1.0
pyarrow                       17.0.0
pyasn1                        0.6.1
pyasn1_modules                0.4.2
pycairo                       1.16.2
pycocotools                   2.0.7
pycodestyle                   2.12.1
pycparser                     2.22
pycryptodome                  3.22.0
pycuda                        2025.1
pycups                        1.9.73
pydantic                      2.4.2
pydantic_core                 2.10.1
pyflakes                      3.2.0
pyglet                        2.1.6
Pygments                      2.19.1
PyGObject                     3.36.0
PyJWT                         1.7.1
pymacaroons                   0.13.0
PyNaCl                        1.3.0
PyOpenGL                      3.1.0
pyparsing                     2.4.6
PyQt5                         5.14.1
pyquaternion                  0.9.9
pyrender                      0.1.45
pyRFC3339                     1.1
pytest                        8.3.5
pytest-runner                 6.0.1
python-apt                    2.0.1+ubuntu0.20.4.1
python-dateutil               2.9.0.post0
python-debian                 1.0.1
python-dotenv                 1.0.1
python-hglib                  2.6.2
pytools                       2024.1.14
pytorch-lightning             1.9.5
pytz                          2025.2
PyWavelets                    1.4.1
pyxattr                       0.6.1
pyxdg                         0.26
PyYAML                        6.0.2
QtPy                          1.9.0
ray                           2.10.0
readme_renderer               43.0
referencing                   0.35.1
regex                         2024.11.6
repo                          0.3.0
reportlab                     3.5.34
requests                      2.32.3
requests-oauthlib             2.0.0
requests-unixsocket           0.2.0
retrying                      1.3.4
rich                          14.0.0
rouge-chinese                 1.0.3
rouge-score                   0.1.2
rpds-py                       0.20.1
rsa                           4.7.2
ruamel.showoutput             0.1.7
s3transfer                    0.11.5
sacrebleu                     2.5.1
safetensors                   0.5.3
scikit-image                  0.21.0
scikit-learn                  1.3.2
scipy                         1.10.1
screen-resolution-extra       0.0.0
seaborn                       0.13.2
SecretStorage                 2.3.1
setuptools                    69.5.1
shapely                       2.0.7
shellingham                   1.5.4
simplejson                    3.16.0
sip                           4.19.21
six                           1.14.0
smplx                         0.1.28
sniffio                       1.3.1
sortedcontainers              2.4.0
sse-starlette                 2.1.3
stack-data                    0.6.3
starlette                     0.44.0
sympy                         1.13.3
systemd-python                234
tabulate                      0.9.0
tensorboard-data-server       0.7.2
tensorrt                      8.6.1
termcolor                     1.1.0
terminaltables                3.1.10
threadpoolctl                 3.5.0
tifffile                      2023.7.10
tiktoken                      0.7.0
tokenizers                    0.20.3
tomli                         2.2.1
torch                         2.1.1+cu121
torchaudio                    2.1.1+cu121
torchmetrics                  1.5.2
torchvision                   0.16.1+cu121
tqdm                          4.67.1
traitlets                     5.14.3
transformers                  4.46.3
trimesh                       4.6.8
triton                        2.1.0
typer                         0.15.3
typing_extensions             4.13.2
tzdata                        2025.2
ubuntu-advantage-tools        8001
ubuntu-drivers-common         0.0.0
uff                           0.6.9
ufw                           0.36
ultralytics                   8.3.120
ultralytics-thop              2.0.14
unattended-upgrades           0.1
unicorn                       2.1.3
urllib3                       2.2.3
usb-creator                   0.3.7
uvicorn                       0.33.0
wadllib                       1.3.3
wcwidth                       0.2.13
Werkzeug                      3.0.6
wheel                         0.34.2
widgetsnbextension            4.0.14
word2number                   1.1
xdoctest                      1.2.0
xkit                          0.0.0
xmltodict                     0.14.2
xtcocotools                   1.14.3
xxhash                        3.5.0
yapf                          0.43.0
yarl                          1.15.2
youtube-dl                    2020.3.24
zipp                          3.20.2
到底为啥什么 不能用

**Comment by sxj731533730** [comment]
太难了 成功了
(openmmlab) ubuntu@ubuntu:~/mmpose-1.0.0$ pip list
Package                Version
---------------------- ------------
addict                 2.4.0
albucore               0.0.23
albumentations         2.0.0
annotated-types        0.7.0
chumpy                 0.70
contourpy              1.3.0
cycler                 0.12.1
Cython                 3.1.0
eval_type_backport     0.2.2
fonttools              4.58.0
importlib_resources    6.5.2
json-tricks            3.17.3
kiwisolver             1.4.7
markdown-it-py         3.0.0
matplotlib             3.9.4
mdurl                  0.1.2
mmcv                   2.0.0
mmdet                  3.3.0
mmengine               0.10.3
mmpose                 1.1.0
munkres                1.1.4
numpy                  1.26.4
opencv-python          4.11.0.86
opencv-python-headless 4.11.0.86
packaging              25.0
pillow                 11.2.1
pip                    25.1
platformdirs           4.3.8
pycocotools            2.0.8
pydantic               2.11.4
pydantic_core          2.33.2
Pygments               2.19.1
pyparsing              3.2.3
python-dateutil        2.9.0.post0
PyYAML                 6.0.2
rich                   14.0.0
scipy                  1.13.1
setuptools             78.1.1
shapely                2.0.7
simsimd                6.2.1
six                    1.17.0
stringzilla            3.12.5
termcolor              3.1.0
terminaltables         3.1.10
tomli                  2.2.1
torch                  1.10.1+cu111
torchaudio             0.10.1+cu111
torchvision            0.11.2+cu111
tqdm                   4.67.1
typing_extensions      4.13.2
typing-inspection      0.4.0
wheel                  0.45.1
xtcocotools            1.14.3
yapf                   0.43.0
zipp                   3.21.0
代码使用mmpose-1.0.0
可以复制我的环境
[mmpose_environment.zip](https://github.com/user-attachments/files/20263557/mmpose_environment.zip)
