### ISSUE TITLE
KeyError: 'RANK' occered when trained in single gpu

### ISSUE THREAD

**Issue by VariableXX** [open-mmlab/mmdetection#10621]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I try to reference https://mmdetection.readthedocs.io/zh_CN/v2.21.0/2_new_data_model.html began training, but error occurred:

D:\python_code\mmdet_2\mmdetection>python ./tools/train.py
D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\utils\dl_utils\setup_env.py:46: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\utils\dl_utils\setup_env.py:56: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  warnings.warn(
Traceback (most recent call last):
  File "./tools/train.py", line 135, in <module>
    main()
  File "./tools/train.py", line 124, in main
    runner = Runner.from_cfg(cfg)
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\runner\runner.py", line 443, in from_cfg
    runner = cls(
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\runner\runner.py", line 353, in __init__
    self.setup_env(env_cfg)
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\runner\runner.py", line 656, in setup_env
    init_dist(self.launcher, **dist_cfg)
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\dist\utils.py", line 84, in init_dist
    _init_dist_pytorch(backend, init_backend=init_backend, **kwargs)
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\site-packages\mmengine\dist\utils.py", line 101, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "D:\ProgramData\Miniconda3\envs\mmdet_2\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by HEIseYOUmolc** [comment]
do you fix it? in what way?

**Comment by bharanibala** [comment]
Hi,

Did you find the fix?
