### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by Majiawei** [open-mmlab/mmdetection#10620]
When training mmdet3.x using a single machine with multiple gpus,
This distribution error is reported every time after the third epoch of training.
How to solve this problem?

![微信图片_20230711102619](https://github.com/open-mmlab/mmdetection/assets/20382521/8531e6a7-3a0f-44b9-8f30-171444c617d3)

**Comment by nattametee007** [comment]
i have same issue

**Comment by Younger330** [comment]
> i have same issue

I also have the same question, have you solve it?

**Comment by MAMOB** [comment]
i have same issue

**Comment by Abdulmalik0x** [comment]
Me too

**Comment by happybear1015** [comment]
the same error，as follows：

Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
cv2.error: Caught error in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 790, in prepare_data
    return self.pipeline(data_info)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/loading.py", line 107, in transform
    raise e
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/loading.py", line 101, in transform
    img = mmcv.imfrombytes(
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/image/io.py", line 285, in imfrombytes
    img = cv2.imdecode(img_np, flag)
cv2.error: OpenCV(4.8.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:802: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'


WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5478 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5477) of binary: /home/uvtec/miniconda3/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/uvtec/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-10_16:52:17
  host      : uvtec-MS-7B98
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5477)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by RYHSmmc** [comment]
same

**Comment by zhaozhen2333** [comment]
same

**Comment by Bradly-s** [comment]
how to solve it？

**Comment by wfq007** [comment]
I also have the same question, have you solve it?

**Comment by flytocc** [comment]
try https://github.com/pytorch/pytorch/issues/121222

**Comment by wenshinlee** [comment]
related issues:  https://github.com/open-mmlab/mmdetection/issues/6934#issuecomment-1066255179
