### ISSUE TITLE
Error in using mmcv.symlink(filename, linkpath) on cloud docker environment

### ISSUE THREAD

**Issue by soap117** [open-mmlab/mmdetection#1064]
**Describe the bug**
Traceback (most recent call last):
  File "tools/train.py", line 107, in <module>
    main()
  File "tools/train.py", line 103, in main
    logger=logger)
  File "/opt/miniconda/lib/python3.7/site-packages/mmdet-0.6.0+unknown-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 62, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/opt/miniconda/lib/python3.7/site-packages/mmdet-0.6.0+unknown-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 223, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 274, in train
    self.call_hook('after_train_epoch')
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/hooks/checkpoint.py", line 25, in after_train_epoch
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 252, in save_checkpoint
    mmcv.symlink(filename, linkpath)
  File "/opt/miniconda/lib/python3.7/site-packages/mmcv-0.2.10-py3.7-linux-x86_64.egg/mmcv/utils/path.py", line 49, in symlink
    os.symlink(src, dst, **kwargs)
OSError: [Errno 38] Function not implemented: 'epoch_1.pth' -> '/mnt/batch/tasks/shared/LS_root/jobs/kc-ml-westus2/azureml/juluo_rcnn_1564053045_45b3ca31/mounts/workspaceblobstore/juluo/faster-rcnn-r101-fpn-chart/latest.pth'

Does anyone know how to solve this problem? I can't find any similar mistakes. It works fine on local environment.

**Environment**
Ubuntu 16.04.6
Pytroch 1.10
Python 3.7
Azureml Service

**Comment by dmy1997** [comment]
hello, have you solved it?

**Comment by soap117** [comment]
Hi,

I just delete the link part to solve it. Still don’t know the problem.

Best
发件人: dmy1997<mailto:notifications@github.com>
发送时间: 2019年9月11日 22:12
收件人: open-mmlab/mmdetection<mailto:mmdetection@noreply.github.com>
抄送: Junyu Luo<mailto:asbljy@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [open-mmlab/mmdetection] Error in using mmcv.symlink(filename, linkpath) on cloud docker environment (#1064)


hello, have you solved it?

―

**Comment by hellock** [comment]
#1371
