### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by edehino** [open-mmlab/mmdetection#10652]
Hi, I have created a config file for faster-rcnn but I can't seem to run the code. The error is as follow:

`Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 133, in <module>
    main()
  File "mmdetection/tools/train.py", line 122, in main
    runner = Runner.from_cfg(cfg)
  File "...\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 443, in from_cfg
    runner = cls(
  File "...\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 353, in __init__
    self.setup_env(env_cfg)
  File "...\anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 647, in setup_env
    if env_cfg.get('cudnn_benchmark'):
AttributeError: 'NoneType' object has no attribute 'get'`

May I know hot to fix this?
I followed this to setup my environment: https://github.com/open-mmlab/mmdetection/issues/10649#:~:text=Creating%20an%20environment

I also made sure I have cuda in my workstation.

**Comment by Rhett-Lin** [comment]
Do you fix it?

**Comment by edehino** [comment]
> Do you fix it?

@Rhett-Lin I moved on and created a new config file but now I have this same problem:

https://github.com/open-mmlab/mmdetection/issues/10488

**Comment by edehino** [comment]
Hi, I added this line of code in my config file
`env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))`
    
Now I am getting the same error in 

Here's the output error:
`Traceback (most recent call last):
  File "...\mmdetection\tools\train.py", line 135, in <module>
    main()
  File "...\mmdetection\tools\train.py", line 131, in main
    runner.train()
  File "...\anaconda3\envs\mm\Lib\site-packages\mmengine\runner\runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^
  File "...\anaconda3\envs\mm\Lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "...\anaconda3\envs\mm\Lib\site-packages\mmengine\runner\loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "...\anaconda3\envs\mm\Lib\site-packages\mmengine\runner\loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\anaconda3\envs\mm\Lib\site-packages\mmengine\model\base_model\base_model.py", line 113, in train_step
    data = self.data_preprocessor(data, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\anaconda3\envs\mm\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\anaconda3\envs\mm\Lib\site-packages\mmdet\models\data_preprocessors\data_preprocessor.py", line 121, in forward
    batch_pad_shape = self._get_pad_shape(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\anaconda3\envs\mm\Lib\site-packages\mmdet\models\data_preprocessors\data_preprocessor.py", line 156, in _get_pad_shape
    _batch_inputs = data['inputs']
                    ~~~~^^^^^^^^^^
KeyError: 'inputs'`

Same as here https://github.com/open-mmlab/mmdetection/issues/10488

**Comment by somnusyyy** [comment]
I also have this same question, have u solve it?

**Comment by somnusyyy** [comment]
> > Do you fix it?

hello, have you fix this problem?

**Comment by edehino** [comment]
> > > Do you fix it?
> 
> hello, have you fix this problem?

I added this on my config file:
`env_cfg = dict( cudnn_benchmark=False, mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0), dist_cfg=dict(backend='nccl'))`

**Comment by PoTsui99** [comment]
配置文件中继承了 configs/_base_/default_runtime.py 吗?

**Comment by Uquli** [comment]
@edehino i am getting the same error like you:

>      _batch_inputs = data['inputs']
>                     ~~~~^^^^^^^^^^
> KeyError: 'inputs'

I am using the cityscapes mask-rcnn configuration - which is provided from mmdetection -, but it seems, that it dont work. Did you find any solution of your problem? 
@PoTsui99 my configuration file inherits the _bas_/default_runtime.py file

**Comment by THEBEST-cloud** [comment]
add following contents in your config

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
