### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Younger330** [open-mmlab/mmdetection#10669]
I try to run `/home/aaa/anaconda3/envs/openmmlab/bin/python tools/train.py /home/aaa/disk1/mmdetection/configs/_base_/models/retinanet_r50_fpn.py`
but have the following error:

I also occurred this problem when I tried to train the model using a customized dataset in COCO format. But I have already change the coco.py for `METAINFO = {'classes':('label1', 'label2')}
`
I have no idea what is this problem, and i didnt find anyone have this
```
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 122, in main
    runner = Runner.from_cfg(cfg)
  File "/home/aaa/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 444, in from_cfg
    runner = cls(
  File "/home/aaa/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 354, in __init__
    self.setup_env(env_cfg)
  File "/home/aaa/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 648, in setup_env
    if env_cfg.get('cudnn_benchmark'):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by hhaAndroid** [comment]
@Younger330 Please do not modify the code directly, you should modify the configurations.  please refer to https://github.com/open-mmlab/mmyolo/blob/main/docs/en/get_started/15_minutes_object_detection.md#config

**Comment by weiyuelu** [comment]
I meet the same problem when I train the model on my own dataset, and I only change the config.

> Traceback (most recent call last):
  File "../mmdetection/tools/train.py", line 134, in <module>
    main()
  File "../mmdetection/tools/train.py", line 123, in main
    runner = Runner.from_cfg(cfg)
  File "/workdir/weiyuelu/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmengine/runner/runner.py", line 470, in from_cfg
    cfg=cfg,
  File "/workdir/weiyuelu/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmengine/runner/runner.py", line 353, in __init__
    self.setup_env(env_cfg)
  File "/workdir/weiyuelu/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmengine/runner/runner.py", line 647, in setup_env
    if env_cfg.get('cudnn_benchmark'):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by weiyuelu** [comment]
`defvv `

**Comment by Younger330** [comment]
This is mainly a version issue,recommend instll mmcv by:MMCV_WITH_OPS=1 pip install -e .

**Comment by wenxie18** [comment]
I got the same issure for image segmentation, wonder if you revoled it?
