### ISSUE TITLE
DLL load failed while importing _ext during training

### ISSUE THREAD

**Issue by yeungkong** [open-mmlab/mmdetection#10664]
Hi developers from mmdetection. I am encountering an error when training my model. The environment consists of win10, rtx4090, cuda11.8, pytorch2.0.0, mmcv2.0.0 and mmdet3.1.0. When I ran the train command "python tools/train.py test.py". The following error occurs. 

```
(NP) D:\NP\mmdetection>python tools/train.py test.py
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 122, in main
    runner = Runner.from_cfg(cfg)
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\runner\runner.py", line 443, in from_cfg
    runner = cls(
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\runner\runner.py", line 378, in __init__
    self.log_processor = self.build_log_processor(log_processor)
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\runner\runner.py", line 1623, in build_log_processor
    log_processor = LOG_PROCESSORS.build(log_processor_cfg)
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\registry\registry.py", line 451, in get
    self.import_from_location()
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "D:\Programs\Anaconda3\envs\NP\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "d:\np\mmdetection\mmdet\engine\__init__.py", line 2, in <module>
    from .hooks import *  # noqa: F401, F403
  File "d:\np\mmdetection\mmdet\engine\hooks\__init__.py", line 10, in <module>
    from .visualization_hook import DetVisualizationHook, TrackVisualizationHook
  File "d:\np\mmdetection\mmdet\engine\hooks\visualization_hook.py", line 13, in <module>
    from mmdet.datasets.samplers import TrackImgSampler
  File "d:\np\mmdetection\mmdet\datasets\__init__.py", line 26, in <module>
    from .utils import get_loading_pipeline
  File "d:\np\mmdetection\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "d:\np\mmdetection\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import (ImageToTensor, PackDetInputs, PackReIDInputs,
  File "d:\np\mmdetection\mmdet\datasets\transforms\formatting.py", line 11, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "d:\np\mmdetection\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "d:\np\mmdetection\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "d:\np\mmdetection\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "d:\np\mmdetection\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\Programs\Anaconda3\envs\NP\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Programs\Anaconda3\envs\NP\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。
```
Please tell me what to do to solve the problem. Thank you in advance

**Comment by yeungkong** [comment]
Hi developers from mmdetection. I created the virtual python3.8 environment with conda. The following lines show how I created the environment. 

```
conda activate NP

conda install pytorch=2.0.0 torchvision cudatoolkit=11.8 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/ -c pytorch -c conda-forge

conda install pycocotools -c conda-forge

pip install matplotlib-3.7.2-cp38-cp38-win_amd64.whl

pip install imgviz-1.7.2-py3-none-any.whl

pip install PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-none-win_amd64.whl

pip install labelme-5.2.1.tar.gz

pip install Cython-3.0.0-cp38-cp38-win_amd64.whl

conda env config vars set CUDA_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8"

conda activate NP

conda env config vars list

pip install opencv_python-4.5.4.60-cp38-cp38-win_amd64.whl

pip install mmcv==2.0.0 -f https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html

git clone -b v3.1.0 https://github.com/open-mmlab/mmdetection.git

cd mmdetection

python setup.py develop

cd ../

pip install future tensorboard

pip install scipy-1.10.1-cp38-cp38-win_amd64.whl

pip install scikit_image-0.21.0-cp38-cp38-win_amd64.whl
```

Please kindly help me check where went wrong. Thank you very much.

**Comment by YanxingLiu** [comment]
It seems that you have not install mmcv correctly.

**Comment by CastleDream** [comment]
maybe you can download the corresponding mmcv wheel and install directly, 
1. Download: 
In <https://download.openmmlab.com/mmcv/dist/cu118/torch2.0/index.html>, maybe your python version is 3.10?, download `[./torch2.0.0/mmcv-2.0.0-cp310-cp310-win_amd64.whl](https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/mmcv-2.0.0-cp310-cp310-win_amd64.whl)`, make sure your download is **Win**
2. Install 
`pip install XXXX(your download path)/mmcv-2.0.0-cp310-cp310-win_amd64.whl`

**Comment by yeungkong** [comment]
Thank you developers. After many trials, I think the reason for the failure is the incorrect installation of pytorch 2.0.0. For pytorch 2.0.0, the installation command should be

`conda install pytorch=2.0.0 torchvision torchaudio pytorch-cuda=11.8 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/ -c pytorch -c conda-forge -c nvidia`

**Comment by anzr299** [comment]
I am still facing this issue
Pytorch Version:
  Name: torch
  Version: 2.2.1+cu118
MMDet Version:
  Name: mmdet
  Version: 3.3.0
MMCV version:
  Name: mmcv
  Version: 2.1.0

**Comment by GJMY592** [comment]
> I am still facing this issue Pytorch Version: Name: torch Version: 2.2.1+cu118 MMDet Version: Name: mmdet Version: 3.3.0 MMCV version: Name: mmcv Version: 2.1.0

Did you solve it? I had the same problem

**Comment by davidpagnon** [comment]
Same here

**Comment by TtopsBo** [comment]
mmcv 2.0版本不行啊

**Comment by tmzncty** [comment]
I also meet this error.
(kotenocr_cli) PS D:\ndlocr3> pip install https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/mmcv-2.0.0-cp38-cp38-win_amd64.whl
WARNING: Ignoring invalid distribution -orch (d:\miniconda\envs\kotenocr_cli\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting mmcv==2.0.0
  Downloading https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/mmcv-2.0.0-cp38-cp38-win_amd64.whl (35.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.4/35.4 MB 2.2 MB/s eta 0:00:00
Requirement already satisfied: addict in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (2.4.0)
Requirement already satisfied: mmengine>=0.2.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (0.10.5)
Requirement already satisfied: numpy in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (1.22.4)
Requirement already satisfied: packaging in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (24.1)
Requirement already satisfied: Pillow in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (10.3.0)
Requirement already satisfied: pyyaml in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (6.0.1)
Requirement already satisfied: yapf in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (0.40.2)
Requirement already satisfied: opencv-python>=3 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (4.6.0.66)
Requirement already satisfied: regex in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmcv==2.0.0) (2024.9.11)
Requirement already satisfied: matplotlib in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmengine>=0.2.0->mmcv==2.0.0) (3.7.5)
Requirement already satisfied: rich in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmengine>=0.2.0->mmcv==2.0.0) (13.4.2)
Requirement already satisfied: termcolor in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from mmengine>=0.2.0->mmcv==2.0.0) (2.4.0)
Requirement already satisfied: importlib-metadata>=6.6.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from yapf->mmcv==2.0.0) (8.5.0)
Requirement already satisfied: platformdirs>=3.5.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from yapf->mmcv==2.0.0) (4.3.6)
Requirement already satisfied: tomli>=2.0.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from yapf->mmcv==2.0.0) (2.0.1)
Requirement already satisfied: zipp>=3.20 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from importlib-metadata>=6.6.0->yapf->mmcv==2.0.0) (3.20.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (1.1.1)
Requirement already satisfied: cycler>=0.10 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (6.4.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from rich->mmengine>=0.2.0->mmcv==2.0.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from rich->mmengine>=0.2.0->mmcv==2.0.0) (2.18.0)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from rich->mmengine>=0.2.0->mmcv==2.0.0) (4.11.0)
Requirement already satisfied: mdurl~=0.1 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from markdown-it-py>=2.2.0->rich->mmengine>=0.2.0->mmcv==2.0.0) (0.1.2)
Requirement already satisfied: six>=1.5 in d:\miniconda\envs\kotenocr_cli\lib\site-packages (from python-dateutil>=2.7->matplotlib->mmengine>=0.2.0->mmcv==2.0.0) (1.16.0)
WARNING: Ignoring invalid distribution -orch (d:\miniconda\envs\kotenocr_cli\lib\site-packages)
Installing collected packages: mmcv
  Attempting uninstall: mmcv
    Found existing installation: mmcv 2.0.0rc4
    Uninstalling mmcv-2.0.0rc4:
      Successfully uninstalled mmcv-2.0.0rc4
WARNING: Ignoring invalid distribution -orch (d:\miniconda\envs\kotenocr_cli\lib\site-packages)
Successfully installed mmcv-2.0.0
(kotenocr_cli) PS D:\ndlocr3> python.exe d:/ndlocr3/main.py infer "D:/NDLTEST/input" "D:/NDLTEST/output" -s b        
start inference !
input_root : D:/NDLTEST/input
output_root : D:/NDLTEST/output
config_file : D:/ndlocr3/config.yml
add_info : False
Found image files: ['D:/NDLTEST/input\\img\\1.jpg', 'D:/NDLTEST/input\\img\\10.jpg', 'D:/NDLTEST/input\\img\\11.jpg', 'D:/NDLTEST/input\\img\\12.jpg', 'D:/NDLTEST/input\\img\\13.jpg', 'D:/NDLTEST/input\\img\\14.jpg', 'D:/NDLTEST/input\\img\\15.jpg', 'D:/NDLTEST/input\\img\\16.jpg', 'D:/NDLTEST/input\\img\\17.jpg', 'D:/NDLTEST/input\\img\\18.jpg', 'D:/NDLTEST/input\\img\\19.jpg', 'D:/NDLTEST/input\\img\\2.jpg', 'D:/NDLTEST/input\\img\\20.jpg', 'D:/NDLTEST/input\\img\\3.jpg', 'D:/NDLTEST/input\\img\\4.jpg', 'D:/NDLTEST/input\\img\\5.jpg', 'D:/NDLTEST/input\\img\\6.jpg', 'D:/NDLTEST/input\\img\\7.jpg', 'D:/NDLTEST/input\\img\\8.jpg', 'D:/NDLTEST/input\\img\\9.jpg']
{'input_root': 'D:/NDLTEST/input', 'output_root': 'D:/NDLTEST/output', 'config_file': 'D:/ndlocr3/config.yml', 'input_structure': 'b', 'add_info': False}
[WARNING] Directory D:/NDLTEST/output already exist.
[WARNING] Directory is changed to D:/NDLTEST/output_20240925233637.
D:\miniconda\envs\kotenocr_cli\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (2.2.2) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(
D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmengine\optim\optimizer\zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "d:/ndlocr3/main.py", line 101, in <module>
    main()
  File "d:/ndlocr3/main.py", line 97, in main
    cmd(obj={})
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:/ndlocr3/main.py", line 91, in infer
    inferencer = OcrInferencer(infer_cfg)
  File "d:\ndlocr3\cli\core\inference.py", line 58, in __init__
    self.proc_list = self._create_proc_list(cfg)
  File "d:\ndlocr3\cli\core\inference.py", line 325, in _create_proc_list
    proc_list.append(self.full_proc_list[i](cfg, i))
  File "d:\ndlocr3\cli\procs\layout_extraction.py", line 28, in __init__
    from src.ndl_kotenseki_layout.tools.process import InferencerWithCLI
  File "d:\ndlocr3\src\ndl_kotenseki_layout\tools\process.py", line 15, in <module>
    from mmdet.apis import (inference_detector, init_detector)
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\apis\det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\evaluation\__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\evaluation\metrics\__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\datasets\__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\datasets\transforms\formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "D:\miniconda\envs\kotenocr_cli\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\miniconda\envs\kotenocr_cli\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.


In linux I run it well ,but in WIN I cann't run it. I try to build or use the whl to install. It display well ,but print loss some dll.
I make sure all version well.
Can you help me?
GPT tell me this

```markdown
看起来你在运行 `ndlocr3` 的推理过程中遇到了一个导入错误，特别是与 `mmcv` 库中的 DLL 加载失败有关。这个错误通常是由于以下几种原因引起的：

1. **不兼容的库版本**：你的 `mmcv` 或 `mmdet` 版本可能与当前的环境或 PyTorch 版本不兼容。你可以检查当前安装的 `mmcv` 和 `mmdet` 版本，尝试升级或降级它们以确保兼容性。

2. **环境问题**：某些库需要编译和安装特定的二进制文件。如果你的环境不支持这些文件（例如，缺少特定的 C++ 编译工具或 GPU 驱动程序），可能会导致 DLL 加载失败。确保你有安装并正确配置了必要的编译工具和库。

3. **CUDA 和 PyTorch 版本冲突**：如果你的 PyTorch 版本和 CUDA 版本不匹配，可能会导致这种错误。你可以检查 `torch.cuda.is_available()` 是否返回 `True`，以确保 CUDA 正常工作。

你可以尝试以下步骤来解决这个问题：

### 1. 检查 `mmcv` 和 `mmdet` 版本
确保 `mmcv` 和 `mmdet` 版本是最新的或与当前 PyTorch 版本兼容。可以使用以下命令更新：

```bash
pip install --upgrade mmcv-full mmdet
```

### 2. 检查 CUDA 和 PyTorch 版本
使用以下命令检查 CUDA 和 PyTorch 是否正确安装：

```python
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
```

确保你安装的 CUDA 和 PyTorch 版本相互兼容。

### 3. 重装 `mmcv` 和相关依赖
有时重新安装 `mmcv-full` 可以解决 DLL 加载失败的问题。你可以尝试以下命令重新安装 `mmcv`：

```bash
pip uninstall mmcv mmcv-full
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cuXX/torchX.X/index.html
```

确保 `cuXX` 和 `torchX.X` 分别替换为你系统中 CUDA 和 PyTorch 的版本号。

如果问题仍然存在，可以进一步排查是否与 Python 环境配置有关。希望这些建议能帮你解决问题！
```
