### ISSUE TITLE
ValueError: No gt or bboxes

### ISSUE THREAD

**Issue by himsR** [open-mmlab/mmdetection#1067]
I am using my own data  in coco format and running finetuning on a pretrained net (X-101-64x4d-FPN) using load_from option and distributed training. Now afer training for few steps it breaks giving the error ValueError: No gt or bboxes in : https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L74
I tried to print bboxes.shape and it prints:  torch.Size([0, 4]). Which means for some data point the pretrained net is not generating any proposals ?(On debugging it seems that the backbone extractor gives nans after few images) I am posting the stack trace below

**Reproduction**
1. What command or script did you run?
```
./tools/dist_train.sh /media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py 2

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
 - OS: [e.g., Ubuntu 16.04.6]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [e.g., pip, conda, source]
- GPU model [e.g., 1080Ti, V100]
- CUDA and CUDNN version
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
(open-mmlab) himanshu@himanshu:/media/himanshu/himanshu-dsk2/mmdetection$ ./tools/dist_train.sh /media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py 2
2019-07-27 12:21:26,934 - INFO - Distributed training: True
2019-07-27 12:21:28,973 - INFO - load model from: open-mmlab://resnext101_64x4d
2019-07-27 12:21:31,579 - WARNING - missing keys in source state_dict: layer3.4.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.7.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.14.bn1.num_batches_tracked, layer3.13.bn3.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.7.bn2.num_batches_tracked, layer3.17.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.12.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.7.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.9.bn3.num_batches_tracked, layer3.21.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.10.bn1.num_batches_tracked, layer3.6.bn1.num_batches_tracked, layer3.8.bn1.num_batches_tracked, layer3.16.bn1.num_batches_tracked, layer3.11.bn2.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer3.22.bn3.num_batches_tracked, bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.6.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer3.17.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.19.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.21.bn2.num_batches_tracked, layer3.14.bn2.num_batches_tracked, layer3.15.bn2.num_batches_tracked, layer3.11.bn1.num_batches_tracked, layer3.6.bn3.num_batches_tracked, layer3.20.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.20.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.13.bn1.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.12.bn3.num_batches_tracked, layer3.19.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.22.bn2.num_batches_tracked, layer3.9.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.18.bn2.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.10.bn2.num_batches_tracked, layer3.8.bn3.num_batches_tracked, layer3.16.bn2.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.19.bn3.num_batches_tracked, layer3.18.bn3.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.22.bn1.num_batches_tracked, layer3.18.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.20.bn1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.21.bn1.num_batches_tracked, layer3.16.bn3.num_batches_tracked, layer3.11.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.10.bn3.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer3.15.bn1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.14.bn3.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.15.bn3.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.17.bn1.num_batches_tracked, layer3.8.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.13.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.12.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.9.bn1.num_batches_tracked

loading annotations into memory...
loading annotations into memory...
Done (t=11.73s)
creating index...
Done (t=13.34s)
creating index...
index created!
index created!
2019-07-27 12:21:47,767 - INFO - load checkpoint from /media/himanshu/himanshu-dsk2/mmdetection/tools/cascade_rcnn_x101_64x4d_fpn_2x_20181218-5add321e.pth
2019-07-27 12:21:49,691 - INFO - Start running, host: himanshu@himanshu, work_dir: /media/himanshu/himanshu-dsk2/mmdetection/work_dirs/cascade_rcnn_x101_64x4d_fpn_1x
2019-07-27 12:21:49,691 - INFO - workflow: [('train', 1)], max: 24 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 106, in <module>
    main()
  File "./tools/train.py", line 102, in main
    logger=logger)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 189, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
    losses = model(**data)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 195, in refine_bboxes
    img_meta_)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 218, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "./tools/train.py", line 106, in <module>
    main()
  File "./tools/train.py", line 102, in main
    logger=logger)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 189, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
    losses = model(**data)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 165, in forward_train
    gt_labels[j])
  File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 74, in assign
    raise ValueError('No gt or bboxes')
ValueError: No gt or bboxes
Traceback (most recent call last):
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/himanshu/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', '/media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.


```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by liugaolian** [comment]
> I am using my own data in coco format and running finetuning on a pretrained net (X-101-64x4d-FPN) using load_from option and distributed training. Now afer training for few steps it breaks giving the error ValueError: No gt or bboxes in : https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/bbox/assigners/max_iou_assigner.py#L74
> I tried to print bboxes.shape and it prints: torch.Size([0, 4]). Which means for some data point the pretrained net is not generating any proposals ?(On debugging it seems that the backbone extractor gives nans after few images) I am posting the stack trace below
> 
> **Reproduction**
> 
>     1. What command or script did you run?
> 
> 
> ```
> ./tools/dist_train.sh /media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py 2
> ```
> 
>     1. Did you make any modifications on the code or config? Did you understand what you have modified?
> 
>     2. What dataset did you use?
> 
> 
> **Environment**
> 
>     * OS: [e.g., Ubuntu 16.04.6]
> 
>     * GCC [e.g., 5.4.0]
> 
>     * PyTorch version [e.g., 1.1.0]
> 
>     * How you installed PyTorch [e.g., pip, conda, source]
> 
>     * GPU model [e.g., 1080Ti, V100]
> 
>     * CUDA and CUDNN version
> 
>     * [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
> 
> 
> **Error traceback**
> If applicable, paste the error trackback here.
> 
> ```
> (open-mmlab) himanshu@himanshu:/media/himanshu/himanshu-dsk2/mmdetection$ ./tools/dist_train.sh /media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py 2
> 2019-07-27 12:21:26,934 - INFO - Distributed training: True
> 2019-07-27 12:21:28,973 - INFO - load model from: open-mmlab://resnext101_64x4d
> 2019-07-27 12:21:31,579 - WARNING - missing keys in source state_dict: layer3.4.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.7.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.14.bn1.num_batches_tracked, layer3.13.bn3.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.7.bn2.num_batches_tracked, layer3.17.bn3.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.12.bn2.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.7.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.9.bn3.num_batches_tracked, layer3.21.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer3.10.bn1.num_batches_tracked, layer3.6.bn1.num_batches_tracked, layer3.8.bn1.num_batches_tracked, layer3.16.bn1.num_batches_tracked, layer3.11.bn2.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer3.22.bn3.num_batches_tracked, bn1.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.6.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer3.17.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.19.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.21.bn2.num_batches_tracked, layer3.14.bn2.num_batches_tracked, layer3.15.bn2.num_batches_tracked, layer3.11.bn1.num_batches_tracked, layer3.6.bn3.num_batches_tracked, layer3.20.bn3.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.20.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.13.bn1.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.12.bn3.num_batches_tracked, layer3.19.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.22.bn2.num_batches_tracked, layer3.9.bn2.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer3.18.bn2.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.10.bn2.num_batches_tracked, layer3.8.bn3.num_batches_tracked, layer3.16.bn2.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.19.bn3.num_batches_tracked, layer3.18.bn3.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.22.bn1.num_batches_tracked, layer3.18.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.20.bn1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.21.bn1.num_batches_tracked, layer3.16.bn3.num_batches_tracked, layer3.11.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.10.bn3.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer3.15.bn1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.14.bn3.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.15.bn3.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.17.bn1.num_batches_tracked, layer3.8.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.13.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.12.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.9.bn1.num_batches_tracked
> 
> loading annotations into memory...
> loading annotations into memory...
> Done (t=11.73s)
> creating index...
> Done (t=13.34s)
> creating index...
> index created!
> index created!
> 2019-07-27 12:21:47,767 - INFO - load checkpoint from /media/himanshu/himanshu-dsk2/mmdetection/tools/cascade_rcnn_x101_64x4d_fpn_2x_20181218-5add321e.pth
> 2019-07-27 12:21:49,691 - INFO - Start running, host: himanshu@himanshu, work_dir: /media/himanshu/himanshu-dsk2/mmdetection/work_dirs/cascade_rcnn_x101_64x4d_fpn_1x
> 2019-07-27 12:21:49,691 - INFO - workflow: [('train', 1)], max: 24 epochs
> Traceback (most recent call last):
>   File "./tools/train.py", line 106, in <module>
>     main()
>   File "./tools/train.py", line 102, in main
>     logger=logger)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 60, in train_detector
>     _dist_train(model, dataset, cfg, validate=validate)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 189, in _dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
>     losses = model(**data)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
>     return old_func(*args, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
>     return self.forward_train(img, img_meta, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
>     rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
>     return old_func(*args, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 195, in refine_bboxes
>     img_meta_)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
>     return old_func(*args, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 218, in regress_by_class
>     assert rois.size(1) == 4 or rois.size(1) == 5
> IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
> Traceback (most recent call last):
>   File "./tools/train.py", line 106, in <module>
>     main()
>   File "./tools/train.py", line 102, in main
>     logger=logger)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 60, in train_detector
>     _dist_train(model, dataset, cfg, validate=validate)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 189, in _dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/apis/train.py", line 40, in batch_processor
>     losses = model(**data)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
>     return old_func(*args, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
>     return self.forward_train(img, img_meta, **kwargs)
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 165, in forward_train
>     gt_labels[j])
>   File "/media/himanshu/himanshu-dsk2/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 74, in assign
>     raise ValueError('No gt or bboxes')
> ValueError: No gt or bboxes
> Traceback (most recent call last):
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
>     main()
>   File "/home/himanshu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
>     cmd=process.args)
> subprocess.CalledProcessError: Command '['/home/himanshu/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', '/media/himanshu/himanshu-dsk2/mmdetection/configs/cascade_rcnn_x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
> ```
> 
> **Bug fix**
> If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I have the same problem as you When I use my own data in coco format and running finetuning on a pretrained net (X-101-64x4d-FPN) using load_from option and distributed training.

**Comment by czqInNanjing** [comment]
I also have the same problem. At first, I think that some of my data has problem, but when I throw away the data which the program corrupts with, it still crash with other data....

Reproduction

**What command or script did you run?**
./tools/dist_train.sh configs/open_image_cascade_fpn.py 4 --validate

**Did you make any modifications on the code or config?  Did you understand what you have modified?
What dataset did you use?**

I use OpenImage V5 as my dataset.
I only change the config file and use the provided CustomDataset.
The following is how I create the pickle file for Custom dataset input
```
    for index, row in tqdm(box_anno.iterrows(), total=all):
        img = cv2.imread(osp.join(image_prefix, 'train_' + start_char, row[0] + '.jpg'))
        height, width = img.shape[0], img.shape[1]
        bbox = np.asarray([row[2] * width, row[4] * height, (row[3] - row[2]) * width, (row[5] - row[4])*height])
        label = row[1]
        real_label = labels_dict[row[1]]




        filename_dict[filename].append(
            (width, height, bbox, label, real_label)
        )


    for one_file, annos in filename_dict.items():
        annos = list(zip(*annos))
        result_dict.append(
            {
                'filename': one_file,
                'width': annos[0][0],
                'height': annos[1][0],
                'ann': {
                    'bboxes': np.asarray(annos[2]),
                    'labels': np.asarray(annos[3]),
                    'bboxes_ignore': None,
                    'real_label': np.asarray(annos[4])
                }
            }

        )

```




Error traceback
If applicable, paste the error trackback here.

> Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/apis/train.py", line 197, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/chenziqiang/anaconda3/envs/vrd/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/chenziqiang/anaconda3/envs/vrd/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/chenziqiang/anaconda3/envs/vrd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenziqiang/anaconda3/envs/vrd/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/chenziqiang/anaconda3/envs/vrd/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/models/detectors/cascade_rcnn.py", line 238, in forward_train
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/models/bbox_heads/bbox_head.py", line 200, in refine_bboxes
    img_meta_)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/chenziqiang/Development/mmdetection-master/mmdet/models/bbox_heads/bbox_head.py", line 223, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by kaikaizhu** [comment]
I also have the same problem. I am using my own data in VOC format and running finetuning on a pretrained net (X-101-64x4d-FPN) using load_from option and distributed training. Now afer training for few steps it breaks.

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by jiangzhengkai** [comment]
any can have the solution?

**Comment by hellock** [comment]
1. Some images have no gt annotations: #1531 solves it.
2. Some images have no proposals: the model is not trained well so that RPN generates no proposals, in this case you need to check hyper-parameters.
