### ISSUE TITLE
unexpected keyword argument 'data_root'

### ISSUE THREAD

**Issue by fellen88** [open-mmlab/mmdetection#10674]
when i try to train maskrcnn model  using my own dataset with below config:
(refer to https://mmdetection.readthedocs.io/en/latest/user_guides/train.html#train-with-customized-datasets)

_base_ = [
    '../../configs/mask_rcnn/mask-rcnn_r101_fpn_ms-poly-3x_coco.py'
]

# 我们还需要更改 head 中的 num_classes 以匹配数据集中的类别数
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=1), mask_head=dict(num_classes=1)))

# 修改数据集相关配置
data_root = 'data/data_set/test'
metainfo = {
    'classes': ('1', ),
    'palette': [
        (220, 20, 60),
    ]
}
train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='train/annotations.json',
        data_prefix=dict(img='train/')))
val_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='val/annotations.json',
        data_prefix=dict(img='val/')))
test_dataloader = val_dataloader

# 修改评价指标相关配置
val_evaluator = dict(ann_file=data_root + 'val/annotations.json')
test_evaluator = val_evaluator

# 使用预训练的 Mask R-CNN 模型权重来做初始化，可以提高模型性能
load_from = 'data/checkpoints/mask_rcnn/mask_rcnn_r101_fpn_mstrain-poly_3x_coco_20210524_200244-5675c317.pth'

**Environment**
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
    CUDA available: True
    numpy_random_seed: 1205399794
    GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.1, V11.1.105
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.9.0
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.10.0
    OpenCV: 4.7.0
    MMEngine: 0.7.4

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: 1205399794
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1688, in train
    self._train_loop)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1482, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 145, in build_from_cfg
    f'class `{obj_cls.__name__}` in '  # type: ignore
TypeError: class `EpochBasedTrainLoop` in mmengine/runner/loops.py: class `RepeatDataset` in mmengine/dataset/dataset_wrapper.py: __init__() got an unexpected keyword argument 'data_root'
```none
A placeholder for trackback.
```

**Comment by shallweiwei** [comment]
You c an try to use absolute path.

**Comment by XiaofanQue2000** [comment]
I have the same error training RetinaNet. Did you figure out how to solve this?

**Comment by XiaofanQue2000** [comment]
> 

I have tried to use absolute path, but it is not working. I am trying to run RetinaNet on cityscapes dataset.

**Comment by XiaofanQue2000** [comment]
My problem is solved. You should also inherit dataset config from _base_ besides model config

**Comment by fellen88** [comment]
> My problem is solved. You should also inherit dataset config from _base_ besides model config

Think you for your advice.  however I wonder why  is that needed，as the dataset config is already included in model config

**Comment by XiaofanQue2000** [comment]
In my case, I use cityscapes dataset, so the dataset config is different with the default one included in the model config, MS COCO dataset.

**Comment by fellen88** [comment]
> In my case, I use cityscapes dataset, so the dataset config is different with the default one included in the model config, MS COCO dataset.

I am glad your problem was solved. I think my problem is different with you, because the model config "mask-rcnn_r101_fpn_ms-poly-3x_coco.py" is already include dataset config " ../_base_/datasets/coco_instance.py"

**Comment by fellen88** [comment]
my data set is organized as coco format

**Comment by smoothumut** [comment]
hi @fellen88  did you solve the problem?

**Comment by liujianmisaka** [comment]
I noticed that the `train_dataloader` in the ms_3x_coco.py seems to be different:
```python
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file='annotations/instances_train2017.json',
            data_prefix=dict(img='train2017/'),
            filter_cfg=dict(filter_empty_gt=True, min_size=32),
            pipeline=train_pipeline,
            backend_args=backend_args)))
```
The `type` attribute of the dataset is `RepeatDataset`, and the actual `COCODataset` is one of its properties.

**Comment by BarryGUN** [comment]
> I noticed that the `train_dataloader` in the ms_3x_coco.py seems to be different:
> 
> ```python
> train_dataloader = dict(
>     batch_size=2,
>     num_workers=2,
>     persistent_workers=True,
>     sampler=dict(type='DefaultSampler', shuffle=True),
>     batch_sampler=dict(type='AspectRatioBatchSampler'),
>     dataset=dict(
>         type='RepeatDataset',
>         times=3,
>         dataset=dict(
>             type=dataset_type,
>             data_root=data_root,
>             ann_file='annotations/instances_train2017.json',
>             data_prefix=dict(img='train2017/'),
>             filter_cfg=dict(filter_empty_gt=True, min_size=32),
>             pipeline=train_pipeline,
>             backend_args=backend_args)))
> ```
> 
> The `type` attribute of the dataset is `RepeatDataset`, and the actual `COCODataset` is one of its properties.

This answer is right yo need arg 'type' in dateset dict

**Comment by niqbal996** [comment]
Hi all, 
I faced the same issue and found out that I followed the documentation of adding custom dataset a bit too much by the word. My mistake was that in the custom_dataset.py file I added it as below. 
```python
from mmseg.registry import DATASETS
from .basesegdataset import BaseSegDataset

@DATASETS.register_module()
class CustomDataset(BaseSegDataset):
    METAINFO = dict(
        classes=('background', 'crop', 'weed', 'partial_crop', 'partial_weed'),
        palette=[[0, 0, 0], 
                 [0, 255, 0],
                 [0, 0, 255], 
                 [255, 0, 0],
                 [0, 255, 255]
                 ])
    def __init__(self, arg1, arg2):
        pass
```
which was wrong because there was no initialization of super class `BaseSegDataset` even though it was imported and it could not find the `root_dir`. I changed it as below and it started working. 

```python
from mmseg.registry import DATASETS
from .basesegdataset import BaseSegDataset

@DATASETS.register_module()
class CustomDataset(BaseSegDataset):
    METAINFO = dict(
        classes=('background', 'crop', 'weed', 'partial_crop', 'partial_weed'),
        palette=[[0, 0, 0], 
                 [0, 255, 0],
                 [0, 0, 255], 
                 [255, 0, 0],
                 [0, 255, 255]
                 ])
    def __init__(self,
                 img_suffix='.jpg',
                 seg_map_suffix='.png',
                 reduce_zero_label=True,
                 **kwargs) -> None:
        super().__init__(
            img_suffix=img_suffix,
            seg_map_suffix=seg_map_suffix,
            reduce_zero_label=reduce_zero_label,
            **kwargs)
```

Just leaving it here in case someone else makes the same mistake. 
Cheers
