### ISSUE TITLE
 old version of mmdetection :enviornment issue 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#10701]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. yes
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
yes , and i try but i could not reach to a solution. 
3. The bug has not been fixed in the latest version. yes 

**Describe the bug**

**Reproduction**

1. What command or script did you run?

i run normal training function , on a cluster using this 

`bash ./tools/dist_train.sh configs/xxxx.py 3 --work-dir /work/shubbak/coco_train/xxx/`

and try to verify the installation using this 

`python demo/image_demo.py demo/demo.jpg configs/yolo/yolov3_mobilenetv2_320_300e_coco.py checkpoints/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth --device cpu --out-file result.jpg`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No , my model is as yours with only some changing in the loss functions which already tested and worked in another environment 
4. What dataset did you use?
coco dataset.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

`Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 16, in <module>
    for name, val in collect_env().items():
  File "mmdet/utils/collect_env.py", line 10, in collect_env
    env_info = collect_base_env()
  File "/home/ghezal/open_lab/lib/python3.8/site-packages/mmcv/utils/env.py", line 124, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/ghezal/open_lab/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/ghezal/open_lab/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/ghezal/open_lab/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/software/python/3.8.11/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/ghezal/open_lab/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so)
`

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\] pip 
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
   i made a python environment 

**Error traceback**
If applicable, paste the error trackback here.

mentioned above 

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Younger330** [comment]
I recommend using 
`
cd path/to/mmcv  
MMCV_WITH_OPS=1 pip install -e .
`
to install mmcv

**Comment by alaa-shubbak** [comment]
hello , thanks for suggestion .
I try it , but i got some error when run this 

`python mmdet/utils/collect_env.py`

Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 3, in <module>
    from mmcv.utils import get_git_hash
ImportError: cannot import name 'get_git_hash' from 'mmcv.utils' (/home/ghezal/mmdetection-2x/mmcv/mmcv/utils/__init__.py)


as well as when running the verification code like this 

`python demo/image_demo.py demo/demo.jpg configs/yolo/yolov3_mobilenetv2_320_300e_coco.py checkpoints/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth --device cpu --out-file result.jpg`


i got this error 
Traceback (most recent call last):
  File "demo/image_demo.py", line 5, in <module>
    from mmdet.apis import (async_inference_detector, inference_detector,
ModuleNotFoundError: No module named 'mmdet'

when running this 
`python -c 'import mmcv; import mmcv.ops'`

inside the folder of mmdetection , i got this error as well 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ghezal/mmdetection-2x/mmcv/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/ghezal/mmdetection-2x/mmcv/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/ghezal/mmdetection-2x/mmcv/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/software/python/3.8.11/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'


any other suggestion ?

**Comment by alaa-shubbak** [comment]
i did some more modification 
but i got this error 

<img width="479" alt="image" src="https://github.com/open-mmlab/mmdetection/assets/10245810/d2a171e8-1ac0-40c6-b582-c6241196c16e">

**Comment by 15738281321** [comment]
Did you finally solve it? I also have this problem, my environment is
python=3.8
torch                   1.10.2+cu113
mmcv                    2.0.0        /home/fengcui/yolo/mmcv
mmdet                   2.14.0
mmengine                0.10.1
出现的问题就是上面的情况
ImportError: cannot import name 'Registry' from 'mmcv.utils' (/home/fengcui/yolo/mmcv/mmcv/utils/__init__.py)
我给mmcv.utils改成了mmdet.utils,就出现上面问题了
