### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by chinabing** [open-mmlab/mmdetection#10749]
$ python browse_dataset.py 
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
image path: IMG_20211024_223313.jpg
Traceback (most recent call last):
  File "D:\0.Coding\mmdetection\browse_dataset.py", line 32, in <module>
    visualizer.add_datasample(
  File "C:\Users\robin\AppData\Roaming\Python\Python310\site-packages\mmengine\dist\utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "D:\0.Coding\mmdetection\mmdet\visualization\local_visualizer.py", line 506, in add_datasample
    self.add_image(name, drawn_img, step)
  File "C:\Users\robin\AppData\Roaming\Python\Python310\site-packages\mmengine\dist\utils.py", line 401, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\robin\AppData\Roaming\Python\Python310\site-packages\mmengine\visualization\visualizer.py", line 1084, in add_image
    vis_backend.add_image(name, image, step)  # type: ignore
  File "C:\Users\robin\AppData\Roaming\Python\Python310\site-packages\mmengine\visualization\vis_backend.py", line 56, in wrapper
    obj._init_env()  # type: ignore
  File "C:\Users\robin\AppData\Roaming\Python\Python310\site-packages\mmengine\visualization\vis_backend.py", line 213, in _init_env
    if not os.path.exists(self._save_dir):
  File "D:\ProgramData\Anaconda3\envs\gpt\lib\genericpath.py", line 20, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by hhaAndroid** [comment]
@chinabing `not NoneType` is mean the image path is incorrect.

**Comment by chinabing** [comment]
> @chinabing `not NoneType` is mean the image path is incorrect.

I have checked the path and have not found any problem. I can run the training step. Only the visulization step did not work. I guess whether the mmengine version is not suitable.

**Comment by chinabing** [comment]
> ### Set show = True, it can show one image, but also have the "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType"
> visualizer.add_datasample( os.path.basename(img_path), img, data_sample, draw_pred=False, **show=True**) drawed_image=visualizer.get_image()

Set show = True, it can show one image, but also have the "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType"
visualizer.add_datasample(
os.path.basename(img_path),
img,
data_sample,
draw_pred=False,
show=True)
drawed_image=visualizer.get_image()

**Comment by chinabing** [comment]
> @chinabing `not NoneType` is mean the image path is incorrect.

Set show = True, it can show one image, but also have the "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType"
visualizer.add_datasample(
os.path.basename(img_path),
img,
data_sample,
draw_pred=False,
show=True)
drawed_image=visualizer.get_image()

**Comment by qsunyuan** [comment]
same issue, I just ran inference_demo.ipynb

**Comment by batman47steam** [comment]
same issue
