### ISSUE TITLE
I want to train the mask2former_vis with the mot_challenge.py

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#10779]
I want to train the mask2former_vis, and i want to use the `MOTChallengeDataset`. So i change the _base_ = `['./_base_/datasets/youtube_vis.py'] `to` _base_ = ['./_base_/datasets/mot_challenge.py']`. But it occur the problem:
```
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/loops.py", line 278, in run
    self.run_iter(data_batch)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/loops.py", line 301, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/music/mmdetection/mmdet/models/mot/base.py", line 108, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/home/music/mmdetection/mmdet/models/vis/mask2former_vis.py", line 75, in loss
    losses = self.track_head.loss(x, data_samples)
  File "/home/music/mmdetection/mmdet/models/tracking_heads/mask2former_track_head.py", line 613, in loss
    batch_gt_instances = self.preprocess_gt(batch_gt_instances)
  File "/home/music/mmdetection/mmdet/models/tracking_heads/mask2former_track_head.py", line 218, in preprocess_gt
    gt_instances.masks = gt_instances.masks.to_tensor(
AttributeError: 'InstanceData' object has no attribute 'masks'
```
I dont know how to fix this. And i had compare the `/mmdet/datasets/mot_challenge_dataset.py `and `/mmdet/datasets/youtube_vis_dataset.py `,. i can't find the difference. By the way, i can train the vis model with motchallengedataset in the old mmtracking version. I hope you can help me.

**Comment by ryylcc** [comment]
You should check whether the option `with_mask` has been set True in the `config.py`
~~~
train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations',  with_mask=True)]
~~~

**Comment by lijoe123** [comment]
thank you for your reply.  I had add the `with_mask=True`:

<img width="428" alt="截图 2023-08-22 18-05-21" src="https://github.com/open-mmlab/mmdetection/assets/86214036/049ceb75-26bb-40e0-ac06-6874660661ac">
<img width="428" alt="截图 2023-08-22 18-08-05" src="https://github.com/open-mmlab/mmdetection/assets/86214036/106629d4-d5a1-478a-9bbf-e079c7b93495">
<img width="428" alt="截图 2023-08-22 18-08-28" src="https://github.com/open-mmlab/mmdetection/assets/86214036/7bc2c115-7273-42cd-94da-580ae3b2b6ec">


And it still had a error:
```
08/22 17:56:46 - mmengine - INFO - Exp name: mask2former_r50_8xb2-8e_youtubevis2019_20230822_175632
08/22 17:56:46 - mmengine - INFO - Iter(train) [   28/10000]  base_lr: 1.0000e-04 lr: 1.0000e-05  eta: 1:00:22  time: 0.3633  data_time: 0.0121  memory: 10276  grad_norm: 1406.3541  loss: 99.1270  loss_cls: 1.3553  loss_mask: 2.7707  loss_dice: 5.5168  d0.loss_cls: 3.6967  d0.loss_mask: 2.8553  d0.loss_dice: 5.5653  d1.loss_cls: 1.8370  d1.loss_mask: 2.4655  d1.loss_dice: 5.4585  d2.loss_cls: 1.6591  d2.loss_mask: 2.5773  d2.loss_dice: 5.4102  d3.loss_cls: 1.3775  d3.loss_mask: 2.8267  d3.loss_dice: 5.6282  d4.loss_cls: 1.2777  d4.loss_mask: 2.8141  d4.loss_dice: 5.5740  d5.loss_cls: 1.2211  d5.loss_mask: 2.8264  d5.loss_dice: 5.5122  d6.loss_cls: 1.2436  d6.loss_mask: 2.7452  d6.loss_dice: 5.4614  d7.loss_cls: 1.3319  d7.loss_mask: 2.8261  d7.loss_dice: 5.5238  d8.loss_cls: 1.3463  d8.loss_mask: 2.8104  d8.loss_dice: 5.6127
08/22 17:56:46 - mmengine - WARNING - Reach the end of the dataloader, it will be restarted and continue to iterate. It is recommended to use `mmengine.dataset.InfiniteSampler` to enable the dataloader to iterate infinitely.
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1735, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/loops.py", line 277, in run
    data_batch = next(self.dataloader_iterator)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/runner/loops.py", line 164, in __next__
    data = next(self._iterator)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/music/mmdetection/mmdet/datasets/base_video_dataset.py", line 270, in prepare_data
    return self.pipeline(data_info)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 515, in transform
    output_scatters = [
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 516, in <listcomp>
    self._apply_transforms(_input) for _input in input_scatters
  File "/home/music/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 323, in _apply_transforms
    raise ValueError(
ValueError: Transforms wrapped by TransformBroadcaster should not return None.
```
Thank you for your help
