### ISSUE TITLE
KeyError: 'mask'

### ISSUE THREAD

**Issue by QZZZZZYF** [open-mmlab/mmdetection#10825]
I encountered issues when using cascade mask rcnn and training with VOC datasets
```
Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 129, in main
    runner.train()
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 96, in run
    self.run_epoch()
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\runner\loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _process_data
    data.reraise()
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\_utils.py", line 543, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\dataset_wrapper.py", line 278, in __getitem__
    return self.dataset[sample_idx]
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\dataset_wrapper.py", line 159, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 790, in prepare_data
    return self.pipeline(data_info)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\dataset\base_dataset.py", line 58, in __call__
    data = t(data)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmdet-3.1.0-py3.8.egg\mmdet\datasets\transforms\loading.py", line 447, in transform
    self._load_masks(results)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmdet-3.1.0-py3.8.egg\mmdet\datasets\transforms\loading.py", line 386, in _load_masks
    gt_masks = self._process_masks(results)
  File "C:\software\Anaconda3\envs\openmmlab\lib\site-packages\mmdet-3.1.0-py3.8.egg\mmdet\datasets\transforms\loading.py", line 348, in _process_masks
    gt_mask = instance['mask']
KeyError: 'mask'
```

**Comment by hhaAndroid** [comment]
@QZZZZZYF  I think you have configured it incorrectly.

**Comment by QZZZZZYF** [comment]
> @QZZZZZYF I think you have configured it incorrectly.
Thank you for your reply. Here is my configuration. Can you help me check where the problem is?
’‘’
# cascade-mask-rcnn_r50_fpn_1x_coco.py
_base_ = [
    '../_base_/models/cascade-mask-rcnn_r50_fpn.py',
    '../_base_/datasets/voc0712.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
‘’‘

’‘’
# voc0712.py
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/VOCdevkit/'

# Example to use different file client
# Method 1: simply set the data root and let the file I/O module
# automatically Infer from prefix (not support LMDB and Memcache yet)

# data_root = 's3://openmmlab/datasets/detection/segmentation/VOCdevkit/'

# Method 2: Use `backend_args`, `file_client_args` in versions before 3.0.0rc6
# backend_args = dict(
#     backend='petrel',
#     path_mapping=dict({
#         './data/': 's3://openmmlab/datasets/segmentation/',
#         'data/': 's3://openmmlab/datasets/segmentation/'
#     }))
backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', scale=(600, 600), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=(600, 600), keep_ratio=True),
    # avoid bboxes being resized
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor'))
]
train_dataloader = dict(
    batch_size=8,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type='ConcatDataset',
            # VOCDataset will add different `dataset_type` in dataset.metainfo,
            # which will get error if using ConcatDataset. Adding
            # `ignore_keys` can avoid this error.
            ignore_keys=['dataset_type'],
            datasets=[
                dict(
                    type=dataset_type,
                    data_root=data_root,
                    ann_file='VOC2007/ImageSets/Main/trainval.txt',
                    data_prefix=dict(sub_data_root='VOC2007/'),
                    filter_cfg=dict(
                        filter_empty_gt=True, min_size=32, bbox_min_size=32),
                    pipeline=train_pipeline,
                    backend_args=backend_args),
            ])))

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='VOC2007/ImageSets/Main/test.txt',
        data_prefix=dict(sub_data_root='VOC2007/'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args))
test_dataloader = val_dataloader

# Pascal VOC2007 uses `11points` as default evaluate mode, while PASCAL
# VOC2012 defaults to use 'area'.
val_evaluator = dict(type='VOCMetric', metric='mAP', eval_mode='11points')
test_evaluator = val_evaluator

‘’‘
