### ISSUE TITLE
    key, val = kv.split('=', maxsplit=1) ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by sunsmarterjie** [open-mmlab/mmdetection#10836]
I use the mmdetection3.x, mmcv==2.0.0, pytorch==1.8.0, cuda==10.2, meeting the following error  >>>

Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 63, in main
    args = parse_args()
  File "./tools/train.py", line 55, in parse_args
    args = parser.parse_args()
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/site-packages/mmengine/config/config.py", line 1829, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "./tools/train.py", line 133, in <module>
    main()
  File "./tools/train.py", line 63, in main
    args = parse_args()
  File "./tools/train.py", line 55, in parse_args
    args = parser.parse_args()
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/argparse.py", line 1874, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/site-packages/mmengine/config/config.py", line 1829, in __call__
    key, val = kv.split('=', maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
Killing subprocess 15023
Killing subprocess 15024
Traceback (most recent call last):
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/TianYunjie/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/TianYunjie/anaconda3/envs/torch18/bin/python', '-u', './tools/train.py', '--local_rank=1', '--cfg-options', 'config/mask_rcnn/mask-rcnn_r50_fpn_1x_coco.py']' returned non-zero exit status 1.

**Comment by sunsmarterjie** [comment]
I try different configs such as maskrcnn and dino, all the settings meet the error.

**Comment by hhaAndroid** [comment]
@sunsmarterjie Hi, could you please share your training command? I suspect either the command is incorrect, or there may be an issue with your configuration file.

**Comment by sunsmarterjie** [comment]
python -m torch.distributed.launch --nproc_per_node=8 ./tools/train.py  --cfg-options config/mask_rcnn/mask-rcnn_r50_fpn_1x_coco.py

**Comment by sunsmarterjie** [comment]
I do not change the configuration file (only the coco dataset path).

**Comment by hhaAndroid** [comment]
@sunsmarterjie toos/dist_train.sh  config/mask_rcnn/mask-rcnn_r50_fpn_1x_coco.py 8
