### ISSUE TITLE
RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by Markson-Young** [open-mmlab/mmdetection#10841]
**Describe the bug**
Problems encountered when adapting the new configuration file for dino in mmdetection. Errors reported during training, "RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found."
**Reproduction**
script
```none
#!/bin/bash
# 加载 anaconda
module load anaconda/2021.05
# 加载 cuda 11.7
module load cuda/11.7
# 激活 python 虚拟环境
source activate MMEngine
export PYTHONUNBUFFERED=1
# DINO 训练的的命令（此处需要自己依据自己训练的需要进行修改）
python tools/train.py configs/dino_newconfig/dino-4scale_r50_8xb2-12e_coco.py --cfg-options efficient_conv_bn_eval="[backbone]"
```
**Environment**
**I installed MMEngine with mim install mmengine, and compile mmcv and mmdetection from source code.**
sys.platform: linux
Python: 3.9.17 (main, Jul  5 2023, 20:41:20) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4090
CUDA_HOME: None
GCC: gcc (GCC) 7.3.0
PyTorch: 1.13.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2.1  (built against CUDA 11.3)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 
TorchVision: 0.14.0+cu117
OpenCV: 4.8.0
MMEngine: 0.8.4
MMCV: 2.0.1
MMDetection: 3.1.0+
**Error traceback**
```none
Traceback (most recent call last):
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/tools/train.py", line 133, in <module>
    main()
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/tools/train.py", line 129, in main
    runner.train()
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/detectors/base_detr.py", line 99, in loss
head_inputs_dict = self.forward_transformer(img_feats,
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/detectors/dino.py", line 116, in forward_transformer
    encoder_outputs_dict = self.forward_encoder(**encoder_inputs_dict)
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/detectors/deformable_detr.py", line 252, in forward_encoder
    memory = self.encoder(
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/layers/transformer/deformable_detr_layers.py", line 56, in forward
    query = layer(
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/run01/scw6580/DINO/mmdetection-3.1.0/mmdet/models/layers/transformer/detr_layers.py", line 206, in forward
    query = self.self_attn(
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HOME/scw6580/.conda/envs/MMEngine/lib/python3.9/site-packages/mmengine/utils/misc.py", line 395, in new_func
    output = old_func(*args, **kwargs)
  File "/data/run01/scw6580/DINO/mmcv/mmcv/ops/multi_scale_deform_attn.py", line 368, in forward
    output = MultiScaleDeformableAttnFunction.apply(
  File "/data/run01/scw6580/DINO/mmcv/mmcv/ops/multi_scale_deform_attn.py", line 64, in forward
    output = ext_module.ms_deform_attn_forward(
RuntimeError: ms_deform_attn_impl_forward: implementation for device cuda:0 not found.
```

**Comment by hhaAndroid** [comment]
@Markson-Young There is an issue with the mmcv compilation you did yourself. I suspect you compiled mmcv in CPU mode.

**Comment by Markson-Young** [comment]
> @Markson-Young There is an issue with the mmcv compilation you did yourself. I suspect you compiled mmcv in CPU mode.
Thanks for your reply! It's my first time training in BsccCloud, their login node does not have a GPU. So, even I've load cuda/11.7, mmcv still compiled in CPU mode.

**Comment by syf-fgnb** [comment]
Hi @Markson-Young, I met almost the same problem for my case (`their login node does not have a GPU. So, even I've load cuda/11.7, mmcv still compiled in CPU mode`), would you mind sharing your solution?

**Comment by SSongWang** [comment]
> Hi @Markson-Young, I met almost the same problem for my case (`their login node does not have a GPU. So, even I've load cuda/11.7, mmcv still compiled in CPU mode`), would you mind sharing your solution?

Hi, @syf-fgnb , did you solve this problem?

**Comment by snirlugassy-imagry** [comment]
Make sure to set MMCV_WITH_OPS=1

**Comment by ZiweiLin-vv** [comment]
Did you solve this problem?

> > Hi [@Markson-Young](https://github.com/Markson-Young), I met almost the same problem for my case (`their login node does not have a GPU. So, even I've load cuda/11.7, mmcv still compiled in CPU mode`), would you mind sharing your solution?嗨，我在我的案例中遇到了几乎相同的问题 （ `their login node does not have a GPU. So, even I've load cuda/11.7, mmcv still compiled in CPU mode` ），您介意分享您的解决方案吗？
> 
> Hi, [@syf-fgnb](https://github.com/syf-fgnb) , did you solve this problem?您好，您解决了这个问题吗？
