### ISSUE TITLE
RoIAlign is not compiled with GPU support

### ISSUE THREAD

**Issue by APONING** [open-mmlab/mmdetection#10864]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
(oln) PS D:\Project\python\object_localization_network-main> python tools/test.py configs/oln_box/oln_box.py work_dirs/oln_box/latest.pth --eval bbox
loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
Use load_from_local loader
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 190, in main
    args.show_score_thr)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\apis\test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmcv\parallel\data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\torch\nn\parallel\data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\IDE\anconda\envs\oln\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmcv\runner\fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\detectors\base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\detectors\base.py", line 160, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\detectors\two_stage.py", line 199, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\roi_heads\standard_roi_head.py", line 248, in simple_test
    x, img_metas, proposal_list, self.test_cfg, rescale=rescale)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\roi_heads\oln_roi_head.py", line 70, in simple_test_bboxes
    bbox_results = self._bbox_forward(x, rois)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\roi_heads\oln_roi_head.py", line 32, in _bbox_forward
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmcv\runner\fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmdet\models\roi_heads\roi_extractors\single_level_roi_extractor.py", line 93, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmcv\ops\roi_align.py", line 212, in forward
    self.sampling_ratio, self.pool_mode, self.aligned)
  File "D:\IDE\anconda\envs\oln\lib\site-packages\mmcv\ops\roi_align.py", line 102, in forward
    aligned=ctx.aligned)
RuntimeError: RoIAlign is not compiled with GPU support

**Reproduction**

```
The code comes from https://github.com/mcahny/object_localization_network
Run the following code to report an error：python tools/test.py configs/oln_box/oln_box.py work_dirs/oln_box/latest.pth --eval bbox
```

**Environment**
 Python 3.7, PyTorch 1.7.0, Cuda 11.0, and mmcv==1.2.5
RTX4060

**Comment by hhaAndroid** [comment]
@APONING Your mmcv is not installed correctly and is compiled in CPU mode. Please refer to the mmcv documentation for instructions.
