### ISSUE TITLE
Could not build wheels for mmcv, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by rbli-john** [open-mmlab/mmdetection#10873]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

I tried to build mmdet (3.1.0) with the follow command:
mim install mmdet==3.1.0
But it fails and report an error

"Could not build wheels for mmcv, which is required to install pyproject.toml-based projects"

**Reproduction**

1. What command or script did you run?

```none
conda install pytorch torchvision cpuonly -c pytorch  (succeed)
pip install -U openmim (succeed)
mim install mmengine (succeed)
mim install "mmcv-lite>=2.0.0rc1" (succeed)
mim install mmdet==3.1.0 (failed)
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No

3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
      [65/77] c++ -MMD -MF /private/var/folders/dv/wbjrnyb94pv5djk1y4dkb_bc0000gp/T/pip-install-1yjd_y_z/mmcv_f011dc5113964864ae8a79a17590b9c0/build/temp.macosx-10.9-x86_64-3.8/mmcv/ops/csrc/pytorch/roi_pool.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/rongbin/anaconda3/envs/openmmlab/include -arch x86_64 -I/Users/rongbin/anaconda3/envs/openmmlab/include -arch x86_64 -I/private/var/folders/dv/wbjrnyb94pv5djk1y4dkb_bc0000gp/T/pip-install-1yjd_y_z/mmcv_f011dc5113964864ae8a79a17590b9c0/mmcv/ops/csrc/common -I/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include -I/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/TH -I/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/include/THC -I/Users/rongbin/anaconda3/envs/openmmlab/include/python3.8 -c -c /private/var/folders/dv/wbjrnyb94pv5djk1y4dkb_bc0000gp/T/pip-install-1yjd_y_z/mmcv_f011dc5113964864ae8a79a17590b9c0/mmcv/ops/csrc/pytorch/roi_pool.cpp -o /private/var/folders/dv/wbjrnyb94pv5djk1y4dkb_bc0000gp/T/pip-install-1yjd_y_z/mmcv_f011dc5113964864ae8a79a17590b9c0/build/temp.macosx-10.9-x86_64-3.8/mmcv/ops/csrc/pytorch/roi_pool.o -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1905, in _run_ninja_build
          subprocess.run(
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '4']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dv/wbjrnyb94pv5djk1y4dkb_bc0000gp/T/pip-install-1yjd_y_z/mmcv_f011dc5113964864ae8a79a17590b9c0/setup.py", line 437, in <module>
          setup(
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 848, in build_extensions
          build_ext.build_extensions(self)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 663, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/Users/rongbin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1921, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv
  Running setup.py clean for mmcv
Failed to build mmcv
ERROR: Could not build wheels for mmcv, which is required to install pyproject.toml-based projects
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@rbli-john Please go to the mmcv repository and open an issue. This appears to be a mmcv-related problem.
