### ISSUE TITLE
distributed training on two machine gets error when load checkpoint

### ISSUE THREAD

**Issue by twangnh** [open-mmlab/mmdetection#1089]
**Describe the bug**
I'm trying to run distributed training on two machine with 3 gpu cards each, distributed training on single node works fine, but when using the launch utility to distributed training on two machines, I got 
**Reproduction**
run script `tools/dist_train_master.sh` on master node:
```
#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}

CONFIG=$1
GPUS=$2

$PYTHON -m torch.distributed.launch --nproc_per_node=$GPUS --nnodes=2 --node_rank=0 --master_addr="192.168.0.173" \
   --master_port=7008 $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```
run script `tools/dist_train_worker.sh` on worker node:
```
#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}

CONFIG=$1
GPUS=$2

$PYTHON -m torch.distributed.launch --nproc_per_node=$GPUS --nnodes=2 --node_rank=1 --master_addr="192.168.0.173" \
   --master_port=7008 $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}

```
error on master:
```
2019-07-31 09:39:04,485 - INFO - Distributed training: True
2019-07-31 09:39:05,466 - INFO - load model from: modelzoo://resnet50
Traceback (most recent call last):
  File "./tools/train.py", line 106, in <module>
    main()
  File "./tools/train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/mask_rcnn.py", line 31, in __init__
    pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/two_stage.py", line 57, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/two_stage.py", line 65, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/backbones/resnet.py", line 484, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 137, in load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 101, in load_url_dist
    torch.distributed.barrier()
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1358, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error
Traceback (most recent call last):
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/wangtao/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/mask_rcnn_r50_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```
error on worker:
```
Traceback (most recent call last):
  File "./tools/train.py", line 106, in <module>
    main()
  File "./tools/train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/mask_rcnn.py", line 31, in __init__
    pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/two_stage.py", line 57, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/detectors/two_stage.py", line 65, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/wangtao/prj/_mmdetection/mmdetection/mmdet/models/backbones/resnet.py", line 484, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 137, in load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 101, in load_url_dist
    torch.distributed.barrier()
  File "/home/wangtao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1358, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653114079/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO
3. What dataset did you use?
Default COCO dataset
**Environment**
 - OS: Ubuntu 16.04.4 LTS
 - GCC  5.4.0 
 - PyTorch version 1.1.0
- How you installed PyTorch conda install -c pytorch pytorch torchvision -y
- GPU model RTX2080ti
- CUDA and CUDNN version CUDA9.0 cudnn 7.2
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Comment by hellock** [comment]
Thanks for reporting! We will look into that.

**Comment by AloshkaD** [comment]
You may want to check your NCCL.[https://github.com/pytorch/pytorch/issues/17349](url)

**Comment by twangnh** [comment]
Thank you. but the issue seems been removed?

**Comment by yhcao6** [comment]
Have you checked the pytorch version in different nodes, they must be same.

When I install pytorch-nightly in one node and pytorch-1.1.0 in another node, I encounter the same error as yours. However, when I replace pytorch-nightly with pytorch-1.1.0, the program runs successfully.
My nccl version is 2402, you can check it using command `torch.cuda.nccl.version()`.

**Comment by twangnh** [comment]
yes, I'm using the same conda created environment on the two nodes with pytorch 1.1.0, and I'm also using nccl 2402. So it seems it is not caused by different pytorch version. I'm wondering if you use similar script to launch the training on different nodes?

**Comment by yhcao6** [comment]
Yes, this is my scripts. I just change the ip address of master node. I first run the script on master node, wait for some seconds, and then run the scipt on worker node.

On master node:
```
#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}

CONFIG=$1
GPUS=$2

$PYTHON -m torch.distributed.launch --nproc_per_node=$GPUS --nnodes=2 --node_rank=0 --master_addr="10.1.72.25" \
   --master_port=7008 $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```

On worker node:
```
#!/usr/bin/env bash

PYTHON=${PYTHON:-"python"}

CONFIG=$1
GPUS=$2

$PYTHON -m torch.distributed.launch --nproc_per_node=$GPUS --nnodes=2 --node_rank=1 --master_addr="10.1.72.25" \
   --master_port=7008 $(dirname "$0")/train.py $CONFIG --launcher pytorch ${@:3}
```

**Comment by twangnh** [comment]
Thanks for sharing the scripts, I'm wondering do you have same cuda and nvidia-driver version on master and worker nodes? what is their version and GPU model?

**Comment by yhcao6** [comment]
Yes.  nvidia smi Driver Version: 396.24.  nvcc version: 9.0, V9.0.176.  cudnn version: 7.1.1
