### ISSUE TITLE
when I use the get_flops function, it's wrong!

### ISSUE THREAD

**Issue by Ashores** [open-mmlab/mmdetection#10957]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python tools/analysis_tools/get_flops.py configs/crowddet/crowddet-rcnn_r50_fpn_8xb2-30e_crowdhuman.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I did not make any modifications on the code, only change the address of dataset in cinfig. I understand the modified.
3. What dataset did you use?
CrowdHuman dataset.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
  sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA RTX A4000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu116
OpenCV: 4.8.0
MMEngine: 0.8.4
MMDetection: 3.1.0+f78af77
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
   I try some version of torch and torchvision, including pytorch 1.12.0+cuda11.6 and 1.12.1+cuda11.6, the wrong is same.

**Error traceback**
If applicable, paste the error trackback here.

```none
loading CrowdHuman annotation...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 4370/4370, 293.7 task/s, elapsed: 15s, ETA:     0s
Done
/hy-tmp/mmdetection/mmdet/models/task_modules/coders/delta_xywh_bbox_coder.py:325: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  num_bboxes, num_classes = deltas.size(0), deltas.size(1) // 4
Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 139, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 119, in main
    result = inference(args, logger)
  File "tools/analysis_tools/get_flops.py", line 97, in inference
    outputs = get_model_complexity_info(
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/print_helper.py", line 748, in get_model_complexity_info
    flops = flop_handler.total()
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 268, in total
    stats = self._analyze()
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 570, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs,
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 194, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 1175, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/hy-tmp/mmdetection/mmdet/models/detectors/base.py", line 96, in forward
    return self._forward(inputs, data_samples)
  File "/hy-tmp/mmdetection/mmdet/models/detectors/two_stage.py", line 141, in _forward
    roi_outs = self.roi_head.forward(x, rpn_results_list,
  File "/hy-tmp/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 84, in forward
    bbox_results = self._bbox_forward(x, rois)
  File "/hy-tmp/mmdetection/mmdet/models/roi_heads/multi_instance_roi_head.py", line 53, in _bbox_forward
    bbox_feats = self.bbox_roi_extractor(
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/hy-tmp/mmdetection/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py", line 107, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1118, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/roi_align.py", line 198, in forward
    from torchvision.ops import roi_align as tv_roi_align
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import KittiFlow, Sintel, FlyingChairs, FlyingThings3D, HD1K
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from ..io.image import _read_png_16
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/io/__init__.py", line 8, in <module>
    from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/io/_load_gpu_decoder.py", line 1, in <module>
    from ..extension import _load_library
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/extension.py", line 93, in <module>
    _check_cuda_version()
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torchvision/extension.py", line 52, in _check_cuda_version
    _version = torch.ops.torchvision._cuda_version()
  File "/usr/local/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: unsupported output type: int, from operator: torchvision::_cuda_version
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Ashores** [comment]
In addition, I can train and test the model successfully.
