### ISSUE TITLE
GLIP finetune related error: AttributeError: 'DetDataSample' object has no attribute 'text'

### ISSUE THREAD

**Issue by CDchenlin** [open-mmlab/mmdetection#10979]
Hi, I have successfully organized my custom dataset and initiated training using the rtmdet model. However, upon transitioning to the GLIP model using the configuration file `configs/glip/glip_atss_swin-t_fpn_dyhead_pretrain_obj365-goldg-cc3m-sub.py` as base, I encountered the following issues:

```
Traceback (most recent call last):
  File "~/Code/mmdetection-dev-3.x/tools/train.py", line 138, in <module>
    main()
  File "~/Code/mmdetection-dev-3.x/tools/train.py", line 134, in main
    runner.train()
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "~/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/Code/mmdetection-dev-3.x/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "~/Code/mmdetection-dev-3.x/mmdet/models/detectors/glip.py", line 270, in loss
    text_prompts = [
  File "~/Code/mmdetection-dev-3.x/mmdet/models/detectors/glip.py", line 271, in <listcomp>
    data_samples.text for data_samples in batch_data_samples
AttributeError: 'DetDataSample' object has no attribute 'text'
```
I have attempted multiple potential solutions, including transitioning to the official cat dataset referenced in this [notebook](https://nbviewer.org/github/chg0901/openmmlab2-hong/blob/main/Assignment3/mmdet_simple_cats.ipynb). Despite these efforts, the error persists.

I would be immensely grateful for any advice or suggestions you might have regarding this issue.

Thank you very much for your assistance. I apologize if my repeated inquiries have caused any inconvenience.

**Comment by hhaAndroid** [comment]
@CDchenlin 请基于我们 funtune 的配置来做哦，你的配置看起来有错误

**Comment by FengheTan9** [comment]
你解决了嘛，我也有一样的问题，把coco2017放进去就是不行，需要caption

**Comment by stihuangyuan** [comment]
> 你解决了嘛，我也有一样的问题，把coco2017放进去就是不行，需要caption

遇到同样问题，是因为mmengine、mmcv版本问题吗？

**Comment by SoulProficiency** [comment]
> > 你解决了嘛，我也有一样的问题，把coco2017放进去就是不行，需要caption
> 
> 遇到同样问题，是因为mmengine、mmcv版本问题吗？

请问解决了吗？

**Comment by SoulProficiency** [comment]
> @CDchenlin 请基于我们 funtune 的配置来做哦，你的配置看起来有错误

groundDINO用cat的配置文件来训练提示一样的错误，改了load_from，其余没动还是不行

**Comment by tangqh03** [comment]
`pretrain`的配置文件没有设置`train_pipeline`，将其添加上就好了。
