### ISSUE TITLE
KeyError: 'GroundingDINO is not in the mmdet::model registry.

### ISSUE THREAD

**Issue by yaweiWANG94** [open-mmlab/mmdetection#10980]
I try to run demo in 
https://github.com/open-mmlab/mmdetection/tree/dev-3.x/configs/grounding_dino, but got   an error KeyError: 'GroundingDINO is not in the mmdet::model registry.

**Comment by hhaAndroid** [comment]
请问你是咋用的，我用没有问题哦

**Comment by yaweiWANG94** [comment]
> 请问你是咋用的，我用没有问题哦
先按这个https://mmdetection.readthedocs.io/en/latest/get_started.html安装，
然后按照给的说明安装下载，运行demo，
cd $MMDETROOT
# source installation
pip install -r requirements/multimodal.txt
wget https://download.openmmlab.com/mmdetection/v3.0/grounding_dino/groundingdino_swint_ogc_mmdet-822d7e9d.pth

python demo/image_demo.py \
	demo/demo.jpg \
	configs/grounding_dino/grounding_dino_swin-t_pretrain_obj365_goldg_cap4m.py \
	--weights groundingdino_swint_ogc_mmdet-822d7e9d.pth \
	--texts 'bench . car .'

**Comment by yaweiWANG94** [comment]
Loads checkpoint by local backend from path: groundingdino_swint_ogc_mmdet-822d7e9d.pth
Traceback (most recent call last):
  File "demo/image_demo.py", line 136, in <module>
    main()
  File "demo/image_demo.py", line 127, in main
    inferencer = DetInferencer(**init_args)
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py", line 98, in __init__
    super().__init__(
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/infer/infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/infer/infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/SENSETIME/wangyawei/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'GroundingDINO is not in the mmdet::model registry. Please check whether the value of `GroundingDINO` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by FengheTan9** [comment]
Same issue, could you tell me how to solve it !

**Comment by ws1hope** [comment]
+1

**Comment by FengheTan9** [comment]
fix this error by "pip install -v -e ." in mmdetection-dev-3.x

**Comment by FengheTan9** [comment]
> +1

fix this error by "pip install -v -e ." in mmdetection-dev-3.x

**Comment by ws1hope** [comment]
> > +1
> 
> fix this error by `pip install -v -e .` in folder mmdetection-dev-3.x
Thanks, i just solved this problem a moment ago follwed by [mmdetection 报错 KeyError: ‘xxx is not in the models registry‘](https://blog.csdn.net/qq_42897796/article/details/126045017)
