### ISSUE TITLE
ImportError: cannot import name 'build_sampler' from 'mmdet.core.bbox.assign_sampling' 

### ISSUE THREAD

**Issue by huangteng1220** [open-mmlab/mmdetection#1098]
I have successful install the mmdetection by the command "pip install -v -e .". But I have the problem in the test. Would anyone help me ?

(lab) gpuserver@ubuntu:~/ht/labs/mmdetection-master$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmdet.apis import init_detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import inference_detector, init_detector, show_result
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_inside_flags, anchor_target
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import PseudoSampler, assign_and_sample, bbox2delta, build_assigner
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .assign_sampling import assign_and_sample, build_assigner, build_sampler
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/bbox/assign_sampling.py", line 3, in <module>
    from . import assigners, samplers
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/bbox/samplers/__init__.py", line 2, in <module>
    from .combined_sampler import CombinedSampler
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/bbox/samplers/combined_sampler.py", line 1, in <module>
    from ..assign_sampling import build_sampler
ImportError: cannot import name 'build_sampler' from 'mmdet.core.bbox.assign_sampling' (/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/bbox/assign_sampling.py)

**Comment by wrccrwx** [comment]
I encountered the same error today.

**Comment by travishsu** [comment]
same problem here.

**Comment by huangteng1220** [comment]
@hjinlee88 @hellock Thank you . Above  problem has been solved. But I have another problem.

Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-122-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

35 packages can be updated.
16 updates are security updates.

New release '18.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
Last login: Thu Aug  1 16:20:57 2019 from 106.127.226.214
/usr/bin/xauth:  /home/gpuserver/.Xauthority not writable, changes will be ignored
gpuserver@ubuntu:~$ source activate open-mmlab
(open-mmlab) gpuserver@ubuntu:~$ cd ht/labs/mmdetection-master/
(open-mmlab) gpuserver@ubuntu:~/ht/labs/mmdetection-master$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmdet.apis import init_detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import inference_detector, init_detector, show_result
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/gpuserver/ht/labs/mmdetection-master/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: /home/gpuserver/ht/labs/mmdetection-master/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
>>>

**Comment by huangteng1220** [comment]
The another problem has been solved. 
"export CUDA_HOME=$CUDA_HOME:/usr/local/cuda"  modify  to
"export CUDA_HOME=/usr/local/cuda"
, and reinstall the mmdetection.
