### ISSUE TITLE
RVC voice extraction problems

### ISSUE THREAD

**Issue by Erock1959** [open-mmlab/mmdetection#10995]
No matter what I do I keep getting errors; I have python39 installed.

**In step 2b:**
Traceback (most recent call last):
  File "C:\No-Backup\RVC\extract_feature_print.py", line 90, in <module>
    model = model.half()
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
**RuntimeError: The parameter is incorrect.**

**I am not a programmer so no idea what the problem is or whether it is critical.** Rest if process seemed to work fine.
['extract_f0_print.py', 'C:\\No-Backup\\RVC/logs/BLOOZE', '3', 'harvest']
todo-f0-26
f0ing,now-0,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/0_0.wav
todo-f0-26
f0ing,now-0,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/0_2.wav
todo-f0-25
f0ing,now-0,all-25,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/10_0.wav
f0ing,now-5,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/16_2.wav
f0ing,now-5,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/16_0.wav
f0ing,now-5,all-25,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/17_1.wav
f0ing,now-10,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/24_1.wav
f0ing,now-10,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/23_1.wav
f0ing,now-10,all-25,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/25_0.wav
f0ing,now-15,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/30_4.wav
f0ing,now-15,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/30_2.wav
f0ing,now-15,all-25,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/31_0.wav
f0ing,now-20,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/34_2.wav
f0ing,now-20,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/34_1.wav
f0ing,now-20,all-25,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/34_3.wav
f0ing,now-25,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/9_3.wav
f0ing,now-25,all-26,-C:\No-Backup\RVC/logs/BLOOZE/1_16k_wavs/9_1.wav
['extract_feature_print.py', 'privateuseone:0', '1', '0', 'C:\\No-Backup\\RVC/logs/BLOOZE', 'v2']
C:\No-Backup\RVC/logs/BLOOZE
load model(s) from hubert_base.pt
move model to privateuseone:0

**Step 3** One Click Training
Traceback (most recent call last):
  File "C:\No-Backup\RVC\extract_feature_print.py", line 90, in <module>
    model = model.half()
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\torch\nn\modules\module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
**RuntimeError: The parameter is incorrect.**

**Seemingly the same error.** 

**After training completed, NO INDEX FILE.**
Ran step 3 Train Feature Index 
Traceback (most recent call last):
  File "C:\No-Backup\RVC\runtime\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\No-Backup\RVC\runtime\lib\site-packages\gradio\blocks.py", line 1006, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\gradio\blocks.py", line 859, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\No-Backup\RVC\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\No-Backup\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\No-Backup\RVC\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\No-Backup\RVC\runtime\lib\site-packages\gradio\utils.py", line 408, in async_iteration
    return next(iterator)
  File "C:\No-Backup\RVC\infer-web.py", line 1283, in train1key
    big_npy = np.concatenate(npys, 0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

** Another error.** 

I don't think  my training voice folder is excessive, about 30 small mp3 examples.

**Can anyone help?**

**Comment by Erock1959** [comment]
Just to add:
For AMD/Intel GPU users:
https://huggingface.co/lj1995/VoiceConversionWebUI/resolve/main/RVC0813AMD_Intel.7z

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/releases
I have python 3.9 installed as a program. I simply extracted the 7z file and placed contents in a folder "RVC"
I see other updates on this page, so I guess another question would be do I need to modify the code I downloaded with versions below the one I used?

**Comment by Erock1959** [comment]
Closed and completed? What did I miss here?
