### ISSUE TITLE
Co-detr export error

### ISSUE THREAD

**Issue by monsterlyg** [open-mmlab/mmdetection#11011]
Try to export co-detr with mmdeploy
```
from mmdeploy.apis import torch2onnx
from mmdeploy.backend.sdk.export_info import export2SDK

img = 'demo/demo.jpg'
work_dir = 'mmdeploy_models/mmdet/onnx'
save_file = 'end2end.onnx'
deploy_cfg = '../mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py'
model_cfg = 'projects/CO-DETR/configs/codino/co_dino_5scale_r50_lsj_8xb2_1x_coco.py'
model_checkpoint = 'checkpoints/co_dino_5scale_r50_lsj_8xb2_1x_coco-69a72d67.pth'
device = 'cpu'

# 1. convert model to onnx
torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
           model_checkpoint, device)
```
returned traceback:
```
Traceback (most recent call last):
  File "/root/mnt2/lyg/Projects/mmdetection/convert.py", line 13, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/pytorch2onnx.py", line 98, in torch2onnx
    export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/onnx/export.py", line 138, in export
    torch.onnx.export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/mmdeploy/apis/onnx/optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/root/mnt2/lyg/conda/envs/pytorch/lib/python3.9/site-packages/torch/jit/_trace.py", line 121, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables are supported as JIT inputs/outputs. Dictionaries and strings are also accepted, but their usage is not recommended. Here, received an input of unsupported type: DetDataSample
```

**Comment by hhaAndroid** [comment]
@monsterlyg Hello, it is currently not supported. If you have this requirement, you can provide feedback at mmdeploy.

**Comment by monsterlyg** [comment]
I've tried that DINO can be exported successfully as least(did not check whether the result is correct). CO-DETR with dino_head accepts the same input format. Perplexing.

**Comment by hhaAndroid** [comment]
@monsterlyg Please provide feedback at the mmdeploy repository.

**Comment by xinlin-xiao** [comment]
> @monsterlyg Hello, it is currently not supported. If you have this requirement, you can provide feedback at mmdeploy.
Hello，Is co-detr export onnx currently supported ?

**Comment by bibekyess** [comment]
Hi @monsterlyg Did you fix this? I also noticed that I can export DINO models to onnx format but with Co-DINO, I am getting that `JIT` error. The author say that the inference architecture of Co-DINO is same as DINO as the auxiliary heads is not used during inference. So, I was wondering if you figured out any alternative to export it? Thank you!

**Comment by bibekyess** [comment]
Hello, I figured out to solve this error: 
Have a look at this comment, Thank you!
[https://github.com/Sense-X/Co-DETR/issues/26#issuecomment-1884104065](https://github.com/Sense-X/Co-DETR/issues/26#issuecomment-1884104065 )
