### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cls_cost'

### ISSUE THREAD

**Issue by YOOCHANMOON** [open-mmlab/mmdetection#11042]
Traceback (most recent call last):
  File "c:\Users\inference.py", line 89, in <module>
    model = init_detector(config_file, checkpoint_file, device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu'))
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\apis\inference.py", line 66, in init_detector
    model = MODELS.build(config.model)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\models\detectors\sparse_rcnn.py", line 21, in __init__
    super().__init__(
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\models\detectors\two_stage.py", line 61, in __init__
    self.roi_head = MODELS.build(roi_head)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\models\roi_heads\sparse_roi_head.py", line 77, in __init__
    super().__init__(
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\models\roi_heads\cascade_roi_head.py", line 46, in __init__
    super().__init__(
  File "c:\users\mmdetection-main\mmdetection-main\mmdet\models\roi_heads\base_roi_head.py", line 37, in __init__
    self.init_assigner_sampler()
  File "c:\users\lineinference_230509\mmdetection-main\mmdetection-main\mmdet\models\roi_heads\cascade_roi_head.py", line 115, in init_assigner_sampler
    TASK_UTILS.build(rcnn_train_cfg.assigner))
  File "C:\MOON\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\MOON\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'cls_cost'

How can I resolve such an error

**Comment by hhaAndroid** [comment]
@YOOCHANMOON It seems like there is a configuration error. Could you please provide a detailed description?
