### ISSUE TITLE
How to load CO-DETR checkpoint from official code out ?

### ISSUE THREAD

**Issue by monsterlyg** [open-mmlab/mmdetection#11043]
从Sense-X那里的代码训练出来的checkpoint，怎么能在dev-3.x的分支上加载进来。这个[页面](https://github.com/open-mmlab/mmdetection/tree/dev-3.x/projects/CO-DETR)说 "Models labeled * are not trained by us, but from [CO-DETR](https://github.com/Sense-X/Co-DETR) official website." 确实从这里下载的checkpoint是能够顺利地使用dev-3.x的分支去加载的，但是自己训练出来的文件不可以，我看了sense-X在backbone和query-head上的实现与mmdetection这里都有所不同，对应的权重name应该是不同的，所以这边是怎么转过来以使得dev-3.x这个分支能去用的？

**Comment by hhaAndroid** [comment]
@monsterlyg 自己训练的文件不可以吗？我记得没有权重转换脚本的，看下报啥错误？

**Comment by monsterlyg** [comment]
> @monsterlyg 自己训练的文件不可以吗？我记得没有权重转换脚本的，看下报啥错误？

10/13 14:05:24 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/13 14:05:24 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 307, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 140, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 134, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None

**Comment by monsterlyg** [comment]
> @monsterlyg 自己训练的文件不可以吗？我记得没有权重转换脚本的，看下报啥错误？
我已经将配置文件里的SwinTransformerV1改成了SwinTransformer
```
10/13 14:05:24 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/13 14:05:24 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 307, in <module>
    torch2onnx(img, work_dir, save_file, deploy_cfg, model_cfg,
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 140, in torch2onnx
    task_processor = build_task_processor(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/apis/utils/utils.py", line 48, in build_task_processor
    return codebase.build_task_processor(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/base/mmcodebase.py", line 45, in build_task_processor
    return cls.task_registry.build(
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/mmdet/deploy/object_detection.py", line 134, in __init__
    super().__init__(model_cfg, deploy_cfg, device)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/base/task.py", line 53, in __init__
    self.scope = DefaultScope.get_instance(
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/utils/manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/default_scope.py", line 35, in __init__
    assert isinstance(
AssertionError: scope_name should be a string, but got None
```

**Comment by monsterlyg** [comment]
> @monsterlyg 自己训练的文件不可以吗？我记得没有权重转换脚本的，看下报啥错误？
我已经把配置文件里的SwinTransformerV1改成了SwinTransformer；但是很明显这里注册backbone的方式都有不同，Sense-X那里是通过BACKBONE.registry，这里是通过MODELS.registry
```
10/16 14:10:52 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "Codebases" registry tree. As a workaround, the current "Codebases" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
10/16 14:10:52 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "mmdet_tasks" registry tree. As a workaround, the current "mmdet_tasks" registry in "mmdeploy" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
Traceback (most recent call last):
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 304, in <module>
    load_and_run(deploy_cfg, model_cfg, model_checkpoint, [img, img], "cuda:0", run_mode='predict')
  File "/root/mnt2/lyg/Projects/mmdetection/demo/load_torch_model.py", line 202, in load_and_run
    torch_model = task_processor.build_pytorch_model(model_checkpoint)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmdeploy/codebase/base/task.py", line 120, in build_pytorch_model
    model = MODELS.build(model)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/mnt2/lyg/Projects/mmdetection/projects/CO-DETR/codetr/codetr.py", line 44, in __init__
    self.backbone = MODELS.build(backbone)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/ssd2/lyg/conda_pytorch_env/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'depth'
```

**Comment by ywfwyht** [comment]
遇到同样的问题，config注册使用`SwinTransformer`，会出现`TypeError: __init__() got an unexpected keyword argument 'depth'`
