### ISSUE TITLE
GroungdingDINO测试问题

### ISSUE THREAD

**Issue by dpxudong** [open-mmlab/mmdetection#11096]
10/26 11:25:41 - mmengine - INFO - Epoch(val)  [2][3400/3402]    eta: 0:00:00  time: 0.1484  data_time: 0.0018  memory: 3332
10/26 11:27:48 - mmengine - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=27.37s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
[E ProcessGroupNCCL.cpp:828] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800741 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800768 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800777 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800794 milliseconds before timing out.
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
        main()main()

  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    runner.train()
Traceback (most recent call last):
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
model = self.train_loop.run()  # type: ignore  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list

      File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    model = self.train_loop.run()  # type: ignore
self.runner.val_loop.run()  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run

  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    torch_dist.broadcast_object_list(data, src, group)
      File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
        torch_dist.broadcast_object_list(data, src, group)return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda    .return func(*args, **kwargs)OutOfMemoryError
:   File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
CUDA out of memory. Tried to allocate more than 1EB memory.
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
[E ProcessGroupNCCL.cpp:828] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800821 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800833 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800841 milliseconds before timing out.
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
[E ProcessGroupNCCL.cpp:828] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800821 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800833 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=987156, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1800841 milliseconds before timing out.
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate more than 1EB memory.
Traceback (most recent call last):
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 121, in <module>
    main()
  File "/root/xudong/GroundingDINO/mmdetection_1024/tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/runner.py", line 1745, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 102, in run
    self.runner.val_loop.run()
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/runner/loops.py", line 366, in run
    metrics = self.evaluator.evaluate(len(self.dataloader.dataset))
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/evaluator/metric.py", line 144, in evaluate
    broadcast_object_list(metrics)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/mmengine/dist/dist.py", line 519, in broadcast_object_list
    torch_dist.broadcast_object_list(data, src, group)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1436, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/openmmlab/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2246, in broadcast_object_list
    object_tensor = torch.empty(  # type: ignore[call-overload]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1793.05 GiB (GPU 2; 23.69 GiB total capacity; 2.59 GiB already allocated; 19.77 GiB free; 3.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
作者大大我用 GroungDINO 训练不报错在 eval 时报这个错误请问你们有遇到吗？或者看错误信息可以看出是什么问题来吗？

**Comment by hhaAndroid** [comment]
这是 oom ，估计是你显存不够。

**Comment by zhiwenwang20122302** [comment]
我也遇到同样的问题，还不知道怎么解决
