### ISSUE TITLE
为什么跑到多GPU相关的函数上去了？

### ISSUE THREAD

**Issue by shortsonghh** [open-mmlab/mmdetection#11211]
我目前在做一个目标识别的课设，最开始遇到的问题是 base_dataset文件下的datalist为空导致  ‘need at least one array to concatenate’

看网上很多人说是类别设定的问题，但我认为我的配置和数据集都没有问题，配置是根据教程改的；
数据集是从yolo转换过来的，格式与官网对照没有差异，就是缺少info等无关项，但categories、images、annotions是没有问题的。

```python
# 新配置继承了基本配置，并做了必要的修改
_base_ = 'configs/faster_rcnn/faster-rcnn_r101_fpn_1x_coco.py'

# 我们还需要更改 head 中的 num_classes 以匹配数据集中的类别数
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=4)))

# 修改数据集相关配置
data_root = 'dataset_coco/'
metainfo = {
    'classes': ('slagcar', 'excavator', 'bulldozer', 'soilcompactor'),
    'palette': [(220, 20, 60), (119, 11, 32), (0, 0, 142), (0, 0, 230)]
}
train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='annotations/train_an.json',
        data_prefix=dict(img='train/')))
val_dataloader = dict(
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file='annotations/val_an.json',
        data_prefix=dict(img='val/')))
test_dataloader = val_dataloader

# 修改评价指标相关配置
val_evaluator = dict(ann_file=data_root + 'annotations/val_an.json')
test_evaluator = val_evaluator
``` 

![image](https://github.com/open-mmlab/mmdetection/assets/130122649/563f7443-88c3-43ad-8d4b-ed4384e057a3)

之后，按照网上的回答更改coco.py, class_name.py 等文件的classes信息，仍然没有用。

所以我就强行改代码，设定base_dataset文件的datalist为空，则直接输出空的 np.array([])，结果问题就延伸到 ZeroDivisionError: division by zero

```
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 117, in main
    runner.train()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 111, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 350, in __iter__
    self._iterator = self._get_iterator()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 940, in __init__
    self._reset(loader, first_iter=True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 971, in _reset
    self._try_put_index()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1205, in _try_put_index
    index = self._next_index()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 508, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet-3.2.0-py3.8.egg/mmdet/datasets/samplers/batch_sampler.py", line 41, in __iter__
    for idx in self.sampler:
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/sampler.py", line 82, in __iter__
    int(self.total_size / len(indices) + 1))[:self.total_size]
ZeroDivisionError: division by zero
``` 

所以各位有什么想法吗，或者遇到过类似的问题吗？

**Comment by jslok** [comment]
Same issue. Have you solved it?
