### ISSUE TITLE
error on exporting scnet and htc instance-set model to ONNX

### ISSUE THREAD

**Issue by stoneyrh** [open-mmlab/mmdetection#11213]
Traceback (most recent call last):
  File "C:\Users\Stone\.conda\envs\mmlab\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Stone\.conda\envs\mmlab\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\pytorch2onnx.py", line 111, in torch2onnx
    optimize=optimize)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py", line 356, in _wrap
    return self.call_function(func_name_, *args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py", line 326, in call_function
    return self.call_function_local(func_name, *args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py", line 275, in call_function_local
    return pipe_caller(*args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\onnx\export.py", line 141, in export
    verbose=verbose)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 519, in export
    export_modules_as_functions=export_modules_as_functions,
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 1539, in _export
    dynamic_axes=dynamic_axes,
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\onnx\optimizer.py", line 27, in model_to_graph__custom_optimizer
    graph, params_dict, torch_out = ctx.origin_func(*args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\onnx\utils.py", line 896, in _trace_and_get_graph_from_model
    _return_inputs_states=True,
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 132, in forward
    self._force_outplace,
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\jit\_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\onnx\export.py", line 123, in wrapper
    return forward(*arg, **kwargs)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\codebase\mmdet\models\detectors\two_stage.py", line 94, in two_stage_detector__forward
    x, rpn_results_list, data_samples, rescale=False)
  File "C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdet\models\roi_heads\scnet_roi_head.py", line 524, in predict
    rescale=bbox_rescale)
TypeError: cascade_roi_head__predict_bbox() got an unexpected keyword argument 'semantic_feat'
11/27 18:20:46 - mmengine - ERROR - C:\Users\stone\.conda\envs\mmdeploy\lib\site-packages\mmdeploy-1.2.0-py3.7-win-amd64.egg\mmdeploy\apis\core\pipeline_manager.py - pop_mp_output - 81 - `mmdeploy.apis.pytorch2onnx.torch2onnx` with Call id: 0 failed. exit.

**Comment by stoneyrh** [comment]
It seems that scnet_roi_head shoudl reimplement predict_bbox, but actually not. And the return result list does not have the same structure as described in function help block
