### ISSUE TITLE
KeyError: 'FemtoDet is not in the mmengine::model registry. Please check whether the value of `FemtoDet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

### ISSUE THREAD

**Issue by ZS-YANG** [open-mmlab/mmdetection#11255]
我使用的mmdet版本为3.2.0
当我尝试自己运行写一个自己写的模型时，报如下错误
```
Traceback (most recent call last):
  File "E:\code\Det\mmdetection-3.2.0\tools\train.py", line 126, in <module>
    main()
  File "E:\code\Det\mmdetection-3.2.0\tools\train.py", line 115, in main
    runner = Runner.from_cfg(cfg)
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\runner\runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\runner\runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\software\anaconda\envs\femtodet\lib\site-packages\mmengine\registry\build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'FemtoDet is not in the mmengine::model registry. Please check whether the value of `FemtoDet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```
我已经在 mmdet/models/detectors 中注册过该模型了，并且已经将其添加到mmdet/models/detectors/__init__.py中
尝试了很多方法都没有解决这个问题，太令人头疼了

**Comment by ZS-YANG** [comment]
https://github.com/open-mmlab/mmdetection/issues/9719
