### ISSUE TITLE
Adding custom augmentation to a config file 

### ISSUE THREAD

**Issue by armine105** [open-mmlab/mmdetection#11273]
Hello
How are you?
I am going to add other augmentations like random Blur, Brightness, Contrast to a config.
I tried to use Albu for using albumentations library.
Here is my config file.

albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=0,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    dict(type='JpegCompression', quality_lower=70, quality_upper=95, p=0.2),
    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args={{_base_.backend_args}}),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='CachedMosaic', img_scale=(640, 640), pad_val=114.0),
    dict(
        type='RandomResize',
        scale=(1280, 1280),
        ratio_range=(0.1, 2.0),
        keep_ratio=True),
    dict(type='RandomCrop', crop_size=(640, 640)),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', prob=0.5),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        skip_img_without_anno=True),
    dict(type='Pad', size=(640, 640), pad_val=dict(img=(114, 114, 114))),
    dict(
        type='CachedMixUp',
        img_scale=(640, 640),
        ratio_range=(1.0, 1.0),
        max_cached_images=20,
        pad_val=(114, 114, 114)),
    dict(type='PackDetInputs')
]

train_dataloader = dict(
    batch_size=24,
    num_workers=8,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="train/_annotations.coco.json",
        data_prefix=dict(img="train/"),
        pipeline=train_pipeline,
    ),
)

But when I run the train script, I meet the following issue.

KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\admin\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "C:\Users\admin\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 790, in prepare_data
    return self.pipeline(data_info)
  File "C:\Users\admin\anaconda3\lib\site-packages\mmengine\dataset\base_dataset.py", line 58, in __call__
    data = t(data)
  File "C:\Users\admin\anaconda3\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "d:\work\rtmdet\mmdetection\mmdet\structures\bbox\box_type.py", line 267, in wrapper
    return func(self, results)
  File "d:\work\rtmdet\mmdetection\mmdet\datasets\transforms\transforms.py", line 1701, in transform
    results = self._postprocess_results(results, ori_masks)
  File "d:\work\rtmdet\mmdetection\mmdet\datasets\transforms\transforms.py", line 1764, in _postprocess_results
    [results[label][i] for i in results['idx_mapper']])
  File "d:\work\rtmdet\mmdetection\mmdet\datasets\transforms\transforms.py", line 1764, in <listcomp>
    [results[label][i] for i in results['idx_mapper']])
KeyError: 'gt_labels'

**Comment by rewolfiluac** [comment]
Hi @armine105 
The "gt_labels" from the LoadAnnotations class has been removed and changed to "gt_bboxes_labels".

https://github.com/open-mmlab/mmdetection/blob/cfd5d3a985b0249de009b67d04f37263e11cdf3d/mmdet/datasets/transforms/loading.py#L292-L306
