### ISSUE TITLE
Training xdecoder error

### ISSUE THREAD

**Issue by JunDaLee** [open-mmlab/mmdetection#11292]
**Problem**
I want to train the xdecoder model, but there is an error.
```none
Traceback (most recent call last):
  File "./tools/train.py", line 121, in <module>
    main()
  File "./tools/train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/mmdet/mmdetection-3.2.0/projects/XDecoder/xdecoder/xdecoder.py", line 27, in __init__
    self.sem_seg_head = MODELS.build(head_)  # TODO: sem_seg_head -> head
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/mmdet/mmdetection-3.2.0/projects/XDecoder/xdecoder/unified_head.py", line 34, in __init__
    self.predictor = MODELS.build(transformer_decoder_)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmdet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/mmdet/mmdetection-3.2.0/projects/XDecoder/xdecoder/transformer_decoder.py", line 97, in __init__
    self.lang_encoder = LanguageEncoder()
  File "/data/mmdet/mmdetection-3.2.0/projects/XDecoder/xdecoder/language_model.py", line 30, in __init__
    self.lang_encoder = Transformer(max_token_num,
  File "/data/mmdet/mmdetection-3.2.0/projects/XDecoder/xdecoder/language_model.py", line 145, in __init__
    torch.empty(self.context_length, width))
TypeError: empty(): argument 'size' must be tuple of SymInts, but found element of type int at pos 1
```
** Command**
the command I used is 
```none
bash ./tools/dist_train.sh ./projects/XDecoder/configs/xdecoder-tiny_zeroshot_open-vocab-panoptic_coco.py 8
```

**Environment**
```none
Python                   3.8.18
torch                    1.13.0
torchaudio               0.13.0
torchvision              0.14.0
mmcv                     2.1.0
mmdet                    3.2.0 
mmengine                 0.10.1
```

Thank you very much.

**Comment by hhaAndroid** [comment]
@JunDaLee We have mentioned in the readme that training is not supported at the moment.
