### ISSUE TITLE
I got an error when I used video_demo.py to detect the video, but I used image_demo.py and webcam_demo.py to detect the image and camera respectively. Ask the master to answer!!!

### ISSUE THREAD

**Issue by frostsnow777** [open-mmlab/mmdetection#11306]
When I used RTMDet to split the task, I had no problems testing images and cameras using image_demo.py and webcam.py, but I found the following error using video_demo.py:

```
Traceback (most recent call last):
  File "demo/video_demo.py", line 83, in <module>
    main()
  File "demo/video_demo.py", line 60, in main
    for frame in track_iter_progress(video_reader):
  File "C:\Users\911PRO\anaconda3\envs\RTMDet\lib\site-packages\mmengine\utils\progressbar.py", line 240, in track_iter_progress
    raise TypeError(
TypeError: "tasks" must be a tuple object or a sequence object, but got <class 'mmcv.video.io.VideoReader'>
```

I'm sure there's nothing wrong with the command I entered. Sincere request master answer!!!

**Comment by TonikLeung** [comment]
In video_demo.py, line 73, change `    for frame in track_iter_progress(video_reader):` to `    for frame in video_reader:
`

**Comment by frostsnow777** [comment]
> 在 video_demo.py 中，第 73 行，更改` for frame in track_iter_progress(video_reader):`为` for frame in video_reader:`

it works! thanks a lot.^_^

**Comment by PLIclouds** [comment]
This progressbar leads to the bug. I find it and change `for frame in track_iter_progress(video_reader):` to    `for frame in video_reader` too. It needs to be fixed.  Plus, can you add a function about showing the video fps? Thanks a lot.@openmmlab-bot
