### ISSUE TITLE
I can't setup it successfully!

### ISSUE THREAD

**Issue by tunantu** [open-mmlab/mmdetection#11302]
when I use the official document to start my mmdet, I got the error 
"Traceback (most recent call last):
  File "/usr/local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/usr/local/lib/python3.8/dist-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "/usr/local/lib/python3.8/dist-packages/mim/commands/download.py", line 127, in _download_configs
    raise RuntimeError(
RuntimeError: mmdet is not installed. Please install it first."

I promise I follow  your document!

**Comment by tunantu** [comment]
By the way, when I use 'pip list', it didn't display 'mmdet'

**Comment by Matvey123456** [comment]
I have the same problem

**Comment by Jeremy891102** [comment]
Hey, please refer to my solution, it works for me! I am using mmcv==2.1.0
https://github.com/Jeremy891102/mmdetection-easy-setup
