### ISSUE TITLE
AttributeError: 'SSDHead' object has no attribute 'loss_cls'

### ISSUE THREAD

**Issue by RunningLeon** [open-mmlab/mmdetection#11305]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

- ssd failed on `main` and `dev-3.x` branch
`AttributeError: 'SSDHead' object has no attribute 'loss_cls'`

**Reproduction**

1. What command or script did you run?

```shell
python3 demo/image_demo.py demo/demo.jpg configs/ssd/ssd300_coco.py --weights ../mmdeploy_checkpoints/mmdet/ssd/ssd300_coco_20210803_015428-d231a06e.pth  --out-dir ./outs
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
4. What dataset did you use?
None
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "demo/image_demo.py", line 192, in <module>
    main()
  File "demo/image_demo.py", line 184, in main
    inferencer(**call_args)
  File "/root/workspace/mmdetection/mmdet/apis/det_inferencer.py", line 403, in __call__
    preds = self.forward(data, **forward_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/infer/infer.py", line 296, in forward
    return self.model.test_step(inputs)
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/workspace/mmdetection/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/root/workspace/mmdetection/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/root/workspace/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/root/workspace/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/root/workspace/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 376, in _predict_by_feat_single
    if getattr(self.loss_cls, 'custom_cls_channels', False):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SSDHead' object has no attribute 'loss_cls'

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by alexh-deeplite** [comment]
I also encountered this bug with SSD when running `tools/train.py`.

**Bug Fix**
 A simple patch for the bug is to check for the presence of the loss_cls attribute first by replacing the [original code](https://github.com/open-mmlab/mmdetection/blob/44ebd17b145c2372c4b700bfb9cb20dbd28ab64a/mmdet/models/dense_heads/base_dense_head.py#L376) with the following:

Original:
```
if getattr(self.loss_cls, 'custom_cls_channels', False):
```

Patched:
```
if getattr(self, 'loss_cls', None) and getattr(self.loss_cls, 'custom_cls_channels', False):
```

**Comment by wukaijian** [comment]
> I also encountered this bug with SSD when running `tools/train.py` for COCO object detection training
> 
> **Bug Fix** A simple patch for the bug is to check for the presence of the loss_cls attribute first by replacing the [original code](https://github.com/open-mmlab/mmdetection/blob/44ebd17b145c2372c4b700bfb9cb20dbd28ab64a/mmdet/models/dense_heads/base_dense_head.py#L376) with the following:
> 
> Original:
> 
> ```
> if getattr(self.loss_cls, 'custom_cls_channels', False):
> ```
> 
> Patched:
> 
> ```
> if getattr(self, 'loss_cls', None) and getattr(self.loss_cls, 'custom_cls_channels', False):
> ```

Thank for your solution
