### ISSUE TITLE
CO-DETR occured an AssetionError error on my own dataset: assert pred.size() == target.size()

### ISSUE THREAD

**Issue by ykqyzzs** [open-mmlab/mmdetection#11359]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
我想用自己的数据集训练CO-DETR，但是遇到了以下错误：
`Traceback (most recent call last):
  File "tools/train.py", line 134, in <module>
    main()
  File "tools/train.py", line 130, in main
    runner.train()
  File "/mnt/mmengine/mmengine/runner/runner.py", line 1706, in train
    model = self.train_loop.run()  # type: ignore
  File "/mnt/mmengine/mmengine/runner/loops.py", line 96, in run
    self.run_epoch()
  File "/mnt/mmengine/mmengine/runner/loops.py", line 112, in run_epoch
    self.run_iter(idx, data_batch)
  File "/mnt/mmengine/mmengine/runner/loops.py", line 128, in run_iter
    outputs = self.runner.model.train_step(
  File "/mnt/mmengine/mmengine/model/wrappers/distributed.py", line 121, in train_step
    losses = self._run_forward(data, mode='loss')
  File "/mnt/mmengine/mmengine/model/wrappers/distributed.py", line 161, in _run_forward
    results = self(**data, mode=mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/code/mmdet_autolabel/mmdet/models/detectors/base.py", line 92, in forward
    return self.loss(inputs, data_samples)
  File "/root/code/mmdet_autolabel/projects/CO-DETR/codetr/codetr.py", line 171, in loss
    bbox_losses, x = self.query_head.loss(x, batch_data_samples)
  File "/root/code/mmdet_autolabel/projects/CO-DETR/codetr/co_dino_head.py", line 319, in loss
    losses = self.loss_by_feat(*loss_inputs)
  File "/root/code/mmdet_autolabel/mmdet/models/dense_heads/dino_head.py", line 126, in loss_by_feat
    loss_dict = super(DeformableDETRHead, self).loss_by_feat(
  File "/root/code/mmdet_autolabel/mmdet/models/dense_heads/detr_head.py", line 227, in loss_by_feat
    losses_cls, losses_bbox, losses_iou = multi_apply(
  File "/root/code/mmdet_autolabel/mmdet/models/utils/misc.py", line 219, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/root/code/mmdet_autolabel/mmdet/models/dense_heads/detr_head.py", line 293, in loss_by_feat_single
    loss_cls = self.loss_cls(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/code/mmdet_autolabel/mmdet/models/losses/gfocal_loss.py", line 240, in forward
    loss_cls = self.loss_weight * calculate_loss_func(
  File "/root/code/mmdet_autolabel/mmdet/models/losses/utils.py", line 121, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/root/code/mmdet_autolabel/mmdet/models/losses/gfocal_loss.py", line 72, in quality_focal_loss_tensor_target
    assert pred.size() == target.size()
AssertionError`

我的数据集类别是20类，Debug时我注意到，pred的shape是[900, 20]，但是target的shape是[900]，维度无法对齐。
接着我找到detr_head.py中的losses = self.loss_by_feat(*loss_inputs)函数，在这段代码中没有找到将类别标签转换为one hot编码的地方，所以label的维度也是[900]。请问这个问题应该怎么解决呢？

**Reproduction**

1. What command or script did you run?
`bash tools/dist_train.sh projects/CO-DETR/configs/codino/codetr.py 1`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
只修改了配置文件，用于适配自己的数据集。
4. What dataset did you use?
user-defined dataset, transform it to COCO dataset type.

**Environment**
`sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu113
OpenCV: 4.7.0
MMEngine: 0.7.2
MMDetection: 3.0.0+1500735`

**Comment by vishalmogal-coder** [comment]
@ykqyzzs  Did you managed to solved above bug? I have encounter same issue.

**Comment by ChenConnie** [comment]
I have encountered the same issue on my dataset, and I train CO-DETR on the coco val dataset, which meets the same error.

**Comment by ghostgeek6113** [comment]
I encountered the same problem, did you ever solve the problem?
