### ISSUE TITLE
Gettiong error "Torch not compiled with CUDA enabled". Need to run with CUDA on my RTX 5000 laptop.

### ISSUE THREAD

**Issue by ChintanShahDS** [open-mmlab/mmdetection#11381]
Getting error after mmdetection installation and running the first commands for inference. It mentions pytorch not compiled with CUDA but seems pytorch is with CUDA. I want to use my RTX 5000 that I have on my laptop and so do not want to run without GPU. Request help to fix the issue.

**Running command**
python demo/image_demo.py images/animals.png configs/mm_grounding_dino/grounding_dino_swin-t_pretrain_obj365.py  --weights ../models/grounding-dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det_20231204_095047-b448804b.pth --texts "zebra. giraffe" -c

**Getting error:**
Loads checkpoint by local backend from path: ../models/grounding-dino/grounding_dino_swin-t_pretrain_obj365_goldg_grit9m_v3det_20231204_095047-b448804b.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: language_model.language_backbone.body.model.embeddings.position_ids

Traceback (most recent call last):
  File "demo/image_demo.py", line 192, in <module>
    main()
  File "demo/image_demo.py", line 179, in main
    inferencer = DetInferencer(**init_args)
  File "d:\chintan\workspace\imagetotext\mmdetection\mmdet\apis\det_inferencer.py", line 99, in __init__
    super().__init__(
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\infer\infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\infer\infer.py", line 486, in _init_model
    model.to(device)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\mmengine\model\base_model\base_model.py", line 208, in to
    return super().to(*args, **kwargs)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 857, in _apply
    self._buffers[key] = fn(buf)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "D:\Software\Anaconda3\envs\openmmlab\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Output of nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Output of python mmdet/utils/collect_env.py**
sys.platform: win32
Python: 3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:17:17) [MSC v.1929 64 bit (AMD64)]
CUDA available: False
numpy_random_seed: 2147483648
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64
GCC: n/a
PyTorch: 2.1.2
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /bigobj /FS -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /utf-8 /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=OFF, TORCH_VERSION=2.1.2, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.2
OpenCV: 4.9.0
MMEngine: 0.10.2
MMDetection: 3.3.0+44ebd17

**Comment by JackWei01** [comment]
i got the same error when i complete the enviroment installation. I try to run a  inference demo. The command is  "python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth " .I delete the --device=cpui

**Comment by JackWei01** [comment]
I follow the offical doc to install dependency.But I find torch.cuda.is_available() returns False ....
So I use pip instead of conda to install the dependency of pytorch. 
And I try  torch.cuda.is_available()   is True.And the inference demo with GPU return new error like :"RuntimeError: nms_impl: implementation for device cuda:0 not found."

**Comment by JackWei01** [comment]
> I follow the offical doc to install dependency.But I find torch.cuda.is_available() returns False .... So I use pip instead of conda to install the dependency of pytorch. And I try torch.cuda.is_available() is True.And the inference demo with GPU return new error like :"RuntimeError: nms_impl: implementation for device cuda:0 not found."


版本不支持 建议使用pytorch 2.1
参考：https://github.com/open-mmlab/mmdetection/issues/11531
