### ISSUE TITLE
ModuleNotFoundError: No module named 'native_rasterizer'

### ISSUE THREAD

**Issue by theRain0450** [open-mmlab/mmdetection#11386]
控制台报错细节：
Traceback (most recent call last):
  File "C:/PythonProject/e2ec_mmdet-master/demo/test.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\apis\inference.py", line 13, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\datasets\__init__.py", line 13, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\datasets\utils.py", line 11, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\dense_heads\__init__.py", line 17, in <module>
    from .fsaf_head import FSAFHead
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\dense_heads\fsaf_head.py", line 9, in <module>
    from ..losses.accuracy import accuracy
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\losses\__init__.py", line 21, in <module>
    from .contour_loss import DMLoss, MaskRasterizationLoss
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\losses\contour_loss.py", line 8, in <module>
    import native_rasterizer
ModuleNotFoundError: No module named 'native_rasterizer'

Process finished with exit code 1

是模型导入错误，但是这个'native_rasterizer好像无法pip install 这是哪里的模块呢？

**Comment by hhaAndroid** [comment]
你用的并不是 mmdet 官方库，对于你提到的问题我建议你直接去咨询原始 repo

**Comment by Zeitecho** [comment]
我也遇到了这个问题，求教有后续吗
