### ISSUE TITLE
GroundingDino: RuntimeError: _Map_base::at

### ISSUE THREAD

**Issue by dongfeicui** [open-mmlab/mmdetection#11390]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python tools/analysis_tools/get_flops.py configs/grounding_dino/grounding_dino_swin-t_finetune_8xb2_20e_cat.py 
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

```sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100 80GB PCIe
CUDA_HOME: /home/xhu/software/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.1+cu117
OpenCV: 4.9.0
MMEngine: 0.10.2
MMDetection: 3.3.0+44ebd17
```

**Error traceback**
If applicable, paste the error trackback here.

```none
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 147, in <module>
    main()
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 127, in main
    result = inference(args, logger)
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 104, in inference
    outputs = get_model_complexity_info(
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/print_helper.py", line 748, in get_model_complexity_info
    flops = flop_handler.total()
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 268, in total
    stats = self._analyze()
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 570, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs,
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 194, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/base.py", line 96, in forward
    return self._forward(inputs, data_samples)
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/base_detr.py", line 161, in _forward
    img_feats = self.extract_feat(batch_inputs)
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/base_detr.py", line 237, in extract_feat
    x = self.backbone(batch_inputs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xhu/projects/mmdetection/mmdet/models/backbones/swin.py", line 755, in forward
    x, hw_shape, out, out_hw_shape = stage(x, hw_shape)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xhu/projects/mmdetection/mmdet/models/backbones/swin.py", line 458, in forward
    x = block(x, hw_shape)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xhu/projects/mmdetection/mmdet/models/backbones/swin.py", line 375, in forward
    x = cp.checkpoint(_inner_forward, x)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
RuntimeError: _Map_base::at
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by dongfeicui** [comment]
> @dongfeicui It appears that the checkpoint does not support calculating flops. You can configure it by setting `model.backbone.with_cp=False` and `model.encoder.num_cp=-1`.
I add these code in here, but error happens again.
![image](https://github.com/open-mmlab/mmdetection/assets/60336738/3e90a34e-01ef-4713-9259-01686659fa43)

**Comment by dongfeicui** [comment]
Hi @hhaAndroid Thanks your reply!

I want to set the shape value to 800x800, just as the  [documentation](https://mmdetection.readthedocs.io/zh-cn/3.x/user_guides/useful_tools.html#id13) says. However, I'm getting an error

![image](https://github.com/open-mmlab/mmdetection/assets/60336738/c523839b-13a0-47f3-b63e-c07d9252aba8)

**Comment by dongfeicui** [comment]
I tried commenting out this code to proceed, but I still encountered an error.
![image](https://github.com/open-mmlab/mmdetection/assets/60336738/b23878f5-021c-4dcf-ac58-244da342f523)

```
Traceback (most recent call last):
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 169, in <module>
    main()
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 149, in main
    result = inference(args, logger)
  File "/home/xhu/projects/mmdetection/tools/analysis_tools/get_flops.py", line 125, in inference
    outputs = get_model_complexity_info(
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/print_helper.py", line 748, in get_model_complexity_info
    flops = flop_handler.total()
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 268, in total
    stats = self._analyze()
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 570, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs,
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/analysis/jit_analysis.py", line 194, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 1268, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/xhu/software/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/base.py", line 96, in forward
    return self._forward(inputs, data_samples)
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/base_detr.py", line 162, in _forward
    head_inputs_dict = self.forward_transformer(img_feats,
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/grounding_dino.py", line 303, in forward_transformer
    encoder_inputs_dict, decoder_inputs_dict = self.pre_transformer(
  File "/home/xhu/projects/mmdetection/mmdet/models/detectors/deformable_detr.py", line 152, in pre_transformer
    assert batch_data_samples is not None
AssertionError
```

**Comment by hydrochloricacid** [comment]
thank you for your reply,after adding --cfg-options model.backbone.with_cp=False model.encoder.num_cp=-1 ,the _Map_base::at error didnt occur,but another error occured:
assert batch_data_samples is not None
how should I solve thie problem?
