### ISSUE TITLE
SystemExit: 2

### ISSUE THREAD

**Issue by James-S-choi** [open-mmlab/mmdetection#11439]
pip download failed with args: ['mmdet==2.24.0', '-d', '/tmp/tmpqyu6am06', '--no-deps', '--no-binary', ':all:']
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/pip/_internal/commands/download.py", line 142, in run
    requirement_set.warn_legacy_versions_and_specifiers()
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/pip/_internal/req/req_set.py", line 104, in warn_legacy_versions_and_specifiers
    for dep in req.get_dist().iter_dependencies():
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/pip/_internal/metadata/pkg_resources.py", line 221, in iter_dependencies
    return self._dist.requires(extras)
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/mim/commands/install.py", line 207, in patched_requires
    mmdeps_text = get_mmdeps_from_mmpkg(self.project_name,
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/mim/commands/install.py", line 321, in get_mmdeps_from_mmpkg
    mminstall_content = get_mminstall_from_pypi(mmpkg, index_url=index_url)
  File "/opt/conda/envs/cmt/lib/python3.8/site-packages/mim/commands/install.py", line 351, in get_mminstall_from_pypi
    exit(status_code)
  File "/opt/conda/envs/cmt/lib/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 2

你好，我用`mim install mmdet==2.24.0`时，出现了上述的错误，是什么原因呢？

**Comment by GCQi** [comment]
hi, 我也遇到这个问题了，请问是怎么解决的呢？

**Comment by DongmingMMM** [comment]
同问，感谢
