### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by BerhanBilginer** [open-mmlab/mmdetection#11449]
While im trying to do a training on Faster RCNN (faster_rcnn_r50_caffe_fpn_mstrain_3x_coco_20210526_095054-1f77628b.pth) with my own custom dataset which i transformed into COCO format, i receive this error message:

"""Traceback (most recent call last):
  File "/content/mmdetection/tools/train.py", line 121, in <module>
    main()
  File "/content/mmdetection/tools/train.py", line 117, in main
    runner.train()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/mmengine/dataset/dataset_wrapper.py", line 223, in __init__
    self.dataset = DATASETS.build(dataset)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/content/mmdetection/mmdet/datasets/base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/content/mmdetection/mmdet/datasets/base_det_dataset.py", line 89, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/usr/local/lib/python3.10/dist-packages/mmengine/dataset/base_dataset.py", line 769, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate"""

i did a search with same issues on MMDetection GitHub page, but i couldn't find anything for fixing my problem. I will share my configuration file and train, test, val .json files for checking out them. If someone can help me on that issue it would be great.

-----------Configuration File--------------------------
config_PPE = """
auto_scale_lr = dict(base_batch_size=8, enable=False)
backend_args = None
data_root = '/content/mmdetection_dataset/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(interval=5, type='CheckpointHook'),
    logger=dict(interval=5, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(
            checkpoint='open-mmlab://detectron2/resnet50_caffe',
            type='Pretrained'),
        norm_cfg=dict(requires_grad=False, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='caffe',
        type='ResNet'),
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        pad_size_divisor=32,
        std=[
            1.0,
            1.0,
            1.0,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        type='FPN'),
    roi_head=dict(
        bbox_head=dict(
            bbox_coder=dict(
                target_means=[
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                target_stds=[
                    0.1,
                    0.1,
                    0.2,
                    0.2,
                ],
                type='DeltaXYWHBBoxCoder'),
            fc_out_channels=1024,
            in_channels=256,
            loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
            loss_cls=dict(
                loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=False),
            num_classes=2,  # Update to 2 classes for 'vest' and 'helmet'
            reg_class_agnostic=False,
            roi_feat_size=7,
            type='Shared2FCBBoxHead'),
        bbox_roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=7, sampling_ratio=0, type='RoIAlign'),
            type='SingleRoIExtractor'),
        type='StandardRoIHead'),
    rpn_head=dict(
        anchor_generator=dict(
            ratios=[
                0.5,
                1.0,
                2.0,
            ],
            scales=[
                8,
            ],
            strides=[
                4,
                8,
                16,
                32,
                64,
            ],
            type='AnchorGenerator'),
        bbox_coder=dict(
            target_means=[
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            target_stds=[
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            type='DeltaXYWHBBoxCoder'),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
        loss_cls=dict(
            loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=True),
        type='RPNHead'),
    test_cfg=dict(
        rcnn=dict(
            max_per_img=100,
            nms=dict(iou_threshold=0.5, type='nms'),
            score_thr=0.05),
        rpn=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=1000)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=False,
                min_pos_iou=0.5,
                neg_iou_thr=0.5,
                pos_iou_thr=0.5,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=True,
                neg_pos_ub=-1,
                num=512,
                pos_fraction=0.25,
                type='RandomSampler')),
        rpn=dict(
            allowed_border=-1,
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=True,
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.7,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=False,
                neg_pos_ub=-1,
                num=256,
                pos_fraction=0.5,
                type='RandomSampler')),
        rpn_proposal=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=2000)),
    type='FasterRCNN')
optim_wrapper = dict(
    optimizer=dict(lr=0.02, momentum=0.9, type='SGD', weight_decay=0.0001),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=500, start_factor=0.001, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=12,
        gamma=0.1,
        milestones=[
            9,
            11,
        ],
        type='MultiStepLR'),
]

resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='/content/mmdetection_dataset/test/test_coco.json',
        backend_args=None,
        data_prefix=dict(img='/test/images'),
        data_root='/content/mmdetection_dataset',
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='/content/mmdetection_dataset/test/test_coco.json',
    backend_args=None,
    metric='bbox',
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]

train_cfg = dict(max_epochs=12, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=4,
    dataset=dict(
        dataset=dict(
            ann_file='/content/mmdetection_dataset/train/train_coco.json',
            backend_args=None,
            data_prefix=dict(img='/train/images'),
            data_root='/content/mmdetection_dataset',
            filter_cfg=dict(filter_empty_gt=True, min_size=32),
            pipeline=[
                dict(backend_args=None, type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(
                    keep_ratio=True,
                    scale=[
                        (
                            1333,
                            640,
                        ),
                        (
                            1333,
                            800,
                        ),
                    ],
                    type='RandomResize'),
                dict(prob=0.5, type='RandomFlip'),
                dict(type='PackDetInputs'),
            ],
            type='CocoDataset'),
        times=3,
        type='RepeatDataset'),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        keep_ratio=True,
        scale=[
            (
                1333,
                640,
            ),
            (
                1333,
                800,
            ),
        ],
        type='RandomResize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(type='PackDetInputs'),
]

val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='/content/mmdetection_dataset/val/val_coco.json',
        backend_args=None,
        data_prefix=dict(img='/val/images'),
        data_root='/content/mmdetection_dataset',
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='/content/mmdetection_dataset/val/val_coco.json',
    backend_args=None,
    metric='bbox',
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
"""

with open('/content/drive/MyDrive/AVAPP/PPE/Baret-Yelek-Faster_RCNN-17.01.24/train_results/faster-rcnn_r50-caffe_fpn_ms-3x_coco_PPE.py', 'w') as f:
    f.write(config_PPE)

-------------------Sample Of Train JSON File-------------------

  "images": [
    {
      "id": 0,
      "width": 1920,
      "height": 1080,
      "file_name": "2023-07-28_05.56.53.528826.jpg"
    },
    {
      "id": 1,
      "width": 1920,
      "height": 1080,
      "file_name": "2023-07-14_13.42.54.360845.jpg"
    },
    {
      "id": 2,
      "width": 1920,
      "height": 1080,
      "file_name": "2023-07-14_14.03.42.489209.jpg"
    },
    {
      "id": 3,
      "width": 1920,
      "height": 1080,
      "file_name": "2023-07-28_06.18.54.842339.jpg"
    },
    {
      "id": 4,
      "width": 1920,
      "height": 1080,
      "file_name": "2023-07-28_06.20.40.493816.jpg"
    },

"annotations": [
    {
      "id": 1,
      "image_id": 0,
      "category_id": 0,
      "segmentation": [],
      "area": 780,
      "bbox": [
        1887,
        337,
        13,
        60
      ],
      "iscrowd": 0
    },
    {
      "id": 2,
      "image_id": 1,
      "category_id": 0,
      "segmentation": [],
      "area": 10086,
      "bbox": [
        531,
        782,
        82,
        123
      ],
      "iscrowd": 0
    },
    {
      "id": 3,
      "image_id": 1,
      "category_id": 0,
      "segmentation": [],
      "area": 756,
      "bbox": [
        744,
        136,
        21,
        36
      ],
      "iscrowd": 0
    },
    {
      "id": 4,
      "image_id": 1,
      "category_id": 0,
      "segmentation": [],
      "area": 462,
      "bbox": [
        732,
        138,
        14,
        33
      ],
      "iscrowd": 0
    },
    {
      "id": 5,
      "image_id": 2,
      "category_id": 0,
      "segmentation": [],
      "area": 7875,
      "bbox": [
        196,
        870,
        75,
        105
      ],
      "iscrowd": 0
    },
    {
      "id": 6,
      "image_id": 2,
      "category_id": 0,
      "segmentation": [],
      "area": 7446,
      "bbox": [
        132,
        824,
        73,
        102
      ],
      "iscrowd": 0
    },
    {
      "id": 7,
      "image_id": 2,
      "category_id": 0,
      "segmentation": [],
      "area": 6615,
      "bbox": [
        57,
        779,
        63,
        105
      ],
      "iscrowd": 0
    },
    {
      "id": 8,
      "image_id": 2,
      "category_id": 0,
      "segmentation": [],
      "area": 2850,
      "bbox": [
        109,
        910,
        57,
        50
      ],
      "iscrowd": 0
    },
    {
      "id": 9,
      "image_id": 2,
      "category_id": 0,
      "segmentation": [],
      "area": 2925,
      "bbox": [
        105,
        418,
        39,
        75
      ],
      "iscrowd": 0
    },
    {
      "id": 10,
      "image_id": 3,
      "category_id": 0,
      "segmentation": [],
      "area": 13072,
      "bbox": [
        1502,
        812,
        86,
        152
      ],
      "iscrowd": 0
    },
    {
      "id": 11,
      "image_id": 3,
      "category_id": 0,
      "segmentation": [],
      "area": 8460,
      "bbox": [
        1418,
        989,
        94,
        90
      ],
      "iscrowd": 0
    },
    {
      "id": 12,
      "image_id": 3,
      "category_id": 0,
      "segmentation": [],
      "area": 625,
      "bbox": [
        802,
        75,
        25,
        25
      ],
      "iscrowd": 0
    },
    {
      "id": 13,
      "image_id": 4,
      "category_id": 0,
      "segmentation": [],
      "area": 12730,
      "bbox": [
        1498,
        908,
        95,
        134
      ],
      "iscrowd": 0
    },
    {
      "id": 14,
      "image_id": 4,
      "category_id": 0,
      "segmentation": [],
      "area": 12284,
      "bbox": [
        1492,
        807,
        83,
        148
      ],
      "iscrowd": 0
    },
    {
      "id": 15,
      "image_id": 4,
      "category_id": 0,
      "segmentation": [],
      "area": 11473,
      "bbox": [
        1430,
        755,
        77,
        149
      ],
      "iscrowd": 0
    },
    {
      "id": 16,
      "image_id": 5,
      "category_id": 0,
      "segmentation": [],
      "area": 9780,
      "bbox": [
        741,
        671,
        60,
        163
      ],
      "iscrowd": 0
    },
    {
      "id": 17,
      "image_id": 5,
      "category_id": 0,
      "segmentation": [],
      "area": 1647,
      "bbox": [
        418,
        156,
        27,
        61
      ],
      "iscrowd": 0
    },
    {
      "id": 18,
      "image_id": 5,
      "category_id": 0,
      "segmentation": [],
      "area": 6327,
      "bbox": [
        1368,
        446,
        57,
        111
      ],
      "iscrowd": 0
    }

**Comment by tojimahammatov** [comment]
Hi @BerhanBilginer , so your issue is here at `data_bytes = np.concatenate(data_list)`, and error message is probably saying that `data_list` is empty. Maybe you will try to print your `data_list` to ensure it is what you want to have. You can also use pdb to trace for other details. Sharing more details would be helpful.

**Comment by tojimahammatov** [comment]
And have a look at [this issue](https://github.com/open-mmlab/mmdetection/issues/11406). Perhaps it is related to your case.
