### ISSUE TITLE
AssertionError: The length of palette should not be less than `num_classes`.

### ISSUE THREAD

**Issue by meng8407** [open-mmlab/mmdetection#11457]
Thanks for your error report and we appreciate it a lot.

**Checklist**
The length of palette should not be less than `num_classes`.
我的类别数量是40，然而我打印出palette的长度是20，

我运行的代码是：
inferencer = DetInferencer(model=config_file,weights=checkpoint_file,device='cuda:0')
result = inferencer(imgpath,out_dir=out_dir,show=False) 

错误显示是：
palette: 20
classes 40
Traceback (most recent call last):
  File "/home/ai-developer/data/mmdetection-main/inforence_peidian_ceshi.py", line 50, in <module>
    result = inferencer(imgpath,out_dir=out_dir,show=False)#,show=True
  File "/home/ai-developer/data/mmdetection-main/mmdet/apis/det_inferencer.py", line 397, in __call__
    visualization = self.visualize(
  File "/home/ai-developer/data/mmdetection-main/mmdet/apis/det_inferencer.py", line 484, in visualize
    self.visualizer.add_datasample(
  File "/home/ai-developer/anaconda3/envs/nmmdet/lib/python3.10/site-packages/mmengine/dist/utils.py", line 419, in wrapper
    return func(*args, **kwargs)
  File "/home/ai-developer/data/mmdetection-main/mmdet/visualization/local_visualizer.py", line 477, in add_datasample
    pred_img_data = self._draw_instances(image, pred_instances,
  File "/home/ai-developer/data/mmdetection-main/mmdet/visualization/local_visualizer.py", line 138, in _draw_instances
    bbox_palette = get_palette(bbox_color, max_label + 1)
  File "/home/ai-developer/data/mmdetection-main/mmdet/visualization/palette.py", line 65, in get_palette
    assert len(dataset_palette) >= num_classes, \
AssertionError: The length of palette should not be less than `num_classes`.
![错误问题](https://github.com/open-mmlab/mmdetection/assets/69879311/f4fde2a5-3fb5-4d1d-b5a4-50a099e3ff21)

**Comment by hhaAndroid** [comment]
@meng8407 你可以修改 palette 的长度。或者在推理时候直接指定 --palette random

**Comment by meng8407** [comment]
> @meng8407 你可以修改 palette 的长度。或者在推理时候直接指定 --palette random

您好，我想问在哪个代码位置修改palette
我运行的代码是
inferencer = DetInferencer(model=config_file,weights=checkpoint_file,device='cuda:0')
result = inferencer(imgpath,out_dir=out_dir,show=False)

期待您的回答

**Comment by hhaAndroid** [comment]
DetInferencer 在初始化时候是可以传入 palette 参数的，你可以看下

**Comment by meng8407** [comment]
> DetInferencer 在初始化时候是可以传入 palette 参数的，你可以看下

好的，谢谢您
