### ISSUE TITLE
AssertionError: MMCV==1.7.2 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.

### ISSUE THREAD

**Issue by shinparkg** [open-mmlab/mmdetection#11476]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by shinparkg** [comment]
root@autodl-container-f77d11adac-3ed8119f:~/mask/mmdetection-master/mmdet/utils# python collect_env.py
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "collect_env.py", line 5, in <module>
    import mmdet
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
root@autodl-container-f77d11adac-3ed8119f:~/mask/mmdetection-master/mmdet/utils# A placeholder for the command.
i not good at using the github ,could u plz help deal with the problem? i  install the mmcv2.0.0rc4 but still with problems

**Comment by linfeng26** [comment]
![Uploading miminstallmmcv-2.0.0rc4.png…]()
it seems to solve it by update mmcv2.0.0rc4

**Comment by Jeremy891102** [comment]
Hey, 可以參考我整理的安裝方法! 我是使用mmcv==2.1.0
https://github.com/Jeremy891102/mmdetection-easy-setup
