### ISSUE TITLE
FPS testing does not work as described in the documentation

### ISSUE THREAD

**Issue by mau17hzw** [open-mmlab/mmdetection#11478]
Hello everyone,

Firstly, I apologize for my English.

I have a problem: I trained a custom object detector, and for my use case, the Frames Per Second (FPS) is crucial. I used the following command:

!python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py /content/mmdetection/configs/ursa/CustomConfigFasterRcnn50.py /content/mmdetection/work_dirs/faster-rcnn_r50_fpn_2x_coco/epoch_25.pth --launcher pytorch

Unfortunately, the command did not run properly. Instead, an error occurred, and I am unable to fix it. Maybe someone knows where the error is coming from.

/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

warnings.warn(
usage: benchmark.py [-h] [--checkpoint CHECKPOINT] [--task {inference,dataloader,dataset}]
                    [--repeat-num REPEAT_NUM] [--max-iter MAX_ITER] [--log-interval LOG_INTERVAL]
                    [--num-warmup NUM_WARMUP] [--fuse-conv-bn] [--dataset-type {train,val,test}]
                    [--work-dir WORK_DIR] [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                    [--launcher {none,pytorch,slurm,mpi}] [--local_rank LOCAL_RANK]
                    config
benchmark.py: error: unrecognized arguments: --local-rank=0 /content/mmdetection/work_dirs/faster-rcnn_r50_fpn_2x_coco_Vanilladata_Standcofig/epoch_25.pth
[2024-02-18 10:12:19,373] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 40420) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/analysis_tools/benchmark.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-18_10:12:19
  host      : 4c4ef013f9fc
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 40420)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Are these issues already known? 

I really appreciate any help you can provide.

**Comment by jianke000** [comment]
hello,i met the same problem,but anyone can fix it?

**Comment by SkyWay003** [comment]
same problem

**Comment by SkyWay003** [comment]
mmdet3.3 我的改这种形式应该就行了
python  tools/analysis_tools/benchmark.py /content/mmdetection/configs/ursa/CustomConfigFasterRcnn50.py /content/mmdetection/work_dirs/faster-rcnn_r50_fpn_2x_coco/epoch_25.pth
