### ISSUE TITLE
Asking for your help! Test demo is not available

### ISSUE THREAD

**Issue by jinweixia03** [open-mmlab/mmdetection#11474]
(mmdet) alian@ROG07-4090:~/mmdetection$ python demo/image_demo.py demo/demo.jpg ./configs/retinanet/retinanet_r18_fpn_1x_coco.py --weights retinanet_r18_fpn_1x_coco_20220407_171055-614fd399.pth 
Loads checkpoint by local backend from path: retinanet_r18_fpn_1x_coco_20220407_171055-614fd399.pth
02/15 21:35:55 - mmengine - WARNING - Failed to search registry with scope "mmdet" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet" is a correct scope, or whether the registry is initialized.
/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/visualization/visualizer.py:196: UserWarning: Failed to add <class 'mmengine.visualization.vis_backend.LocalVisBackend'>, please provide the `save_dir` argument.
  warnings.warn(f'Failed to add {vis_backend.__class__}, '
<built-in method nms of PyCapsule object at 0x7fa224bfe660>
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
Traceback (most recent call last):
  File "demo/image_demo.py", line 192, in <module>
    main()
  File "demo/image_demo.py", line 184, in main
    inferencer(**call_args)
  File "/home/alian/mmdetection/mmdet/apis/det_inferencer.py", line 403, in __call__
    preds = self.forward(data, **forward_kwargs)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/infer/infer.py", line 296, in forward
    return self.model.test_step(inputs)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/alian/mmdetection/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/home/alian/mmdetection/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/home/alian/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/home/alian/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/home/alian/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 423, in _predict_by_feat_single
    return self._bbox_post_process(
  File "/home/alian/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 485, in _bbox_post_process
    det_bboxes, keep_idxs = batched_nms(bboxes, results.scores,
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/ops/nms.py", line 304, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmengine/utils/misc.py", line 395, in new_func
    output = old_func(*args, **kwargs)
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/ops/nms.py", line 128, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/alian/miniconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/ops/nms.py", line 28, in forward
    inds = ext_module.nms(
RuntimeError: Unknown layout

I've been troubled by it for a long time and haven't found a solution. I hope I can get help. Thanks in advance.

**Comment by Cory-M** [comment]
having the same issue as well. Any updates on this? @ALiAN4011

**Comment by ALiAN4011** [comment]
> having the same issue as well. Any updates on this? @ALiAN4011
Sorry, I haven't solved this problem yet

**Comment by jinweixia03** [comment]
> having the same issue as well. Any updates on this? @ALiAN4011

Sorry, I haven't solved this problem yet

**Comment by Cory-M** [comment]
> > having the same issue as well. Any updates on this? @ALiAN4011
> 
> Sorry, I haven't solved this problem yet

thanks still! will lyk if i manage to fix it

**Comment by jinweixia03** [comment]
> > > having the same issue as well. Any updates on this? @ALiAN4011
> > 
> > 
> > Sorry, I haven't solved this problem yet
> 
> thanks still! will lyk if i manage to fix it

I installed a new system and successfully ran the demo according to the documentation. I still don’t know why the original system went wrong. It may be due to the traces of use of the previous system. I will cherish this new system very much, and the old one will The system is ready for migration.

**Comment by lingdu-xu** [comment]
> > > > having the same issue as well. Any updates on this? @ALiAN4011
> > > 
> > > 
> > > Sorry, I haven't solved this problem yet
> > 
> > 
> > thanks still! will lyk if i manage to fix it
> 
> I installed a new system and successfully ran the demo according to the documentation. I still don’t know why the original system went wrong. It may be due to the traces of use of the previous system. I will cherish this new system very much, and the old one will The system is ready for migration.

may i ask ur system?ubuntu?cuda version,python version,torch vision,,mmcv version,,,?
