### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by fennuya** [open-mmlab/mmdetection#11531]
当我训练，在保存checkpoints时，报错：
03/08 16:40:44 - mmengine - INFO - Exp name: rtmdet-ins_s_8xb32-300e_coco_balloon_20240308_163857
03/08 16:40:44 - mmengine - INFO - Epoch(train)  [10][9/9]  base_lr: 3.5639e-04 lr: 3.5639e-04  eta: 0:41:50  time: 0.6201  data_time: 0.2189  memory: 5347  loss: 2.6011  loss_cls: 0.6292  loss_bbox: 0.9600  loss_mask: 1.0119
03/08 16:40:44 - mmengine - INFO - Saving checkpoint at 10 epochs
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 117, in main
    runner.train()
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\runner\runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\runner\loops.py", line 102, in run
    self.runner.val_loop.run()
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\runner\loops.py", line 371, in run
    self.run_iter(idx, data_batch)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\runner\loops.py", line 391, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\model\base_model\base_model.py", line 133, in val_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\model\base_model\base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "d:\pythoncode\mmdetection-main\mmdet\models\detectors\base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "d:\pythoncode\mmdetection-main\mmdet\models\detectors\single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "d:\pythoncode\mmdetection-main\mmdet\models\dense_heads\base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "d:\pythoncode\mmdetection-main\mmdet\models\dense_heads\rtmdet_ins_head.py", line 256, in predict_by_feat
    results = self._predict_by_feat_single(
  File "d:\pythoncode\mmdetection-main\mmdet\models\dense_heads\rtmdet_ins_head.py", line 417, in _predict_by_feat_single
    return self._bbox_mask_post_process(
  File "d:\pythoncode\mmdetection-main\mmdet\models\dense_heads\rtmdet_ins_head.py", line 485, in _bbox_mask_post_process
    det_bboxes, keep_idxs = batched_nms(bboxes, results.scores,
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmcv\ops\nms.py", line 303, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmengine\utils\misc.py", line 395, in new_func
    output = old_func(*args, **kwargs)
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmcv\ops\nms.py", line 127, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset, score_threshold,
  File "E:\miniconda3\envs\mmdet\lib\site-packages\torch\autograd\function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "E:\miniconda3\envs\mmdet\lib\site-packages\mmcv\ops\nms.py", line 27, in forward
    inds = ext_module.nms(
RuntimeError: nms_impl: implementation for device cuda:0 not found.
我的环境:
sys.platform: win32
Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3060
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.31.31107 版
GCC: n/a
PyTorch: 2.2.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.7
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.0
OpenCV: 4.9.0
MMEngine: 0.10.3
MMDetection: 3.3.0+unknown

**Comment by captainIT** [comment]
你这个是环境问题，可以参考试下https://github.com/open-mmlab/mmdetection/issues/11530#issuecomment-1996359661
