### ISSUE TITLE
Trying to train with HTC, 2 bugs found

### ISSUE THREAD

**Issue by eduramiba** [open-mmlab/mmdetection#1154]
**Describe the bug**

First I get bug #977 Not clear why that line changes the file name. If removed, then I get this exception:

```python
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eduardo/dev/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/eduardo/dev/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/eduardo/dev/mmdetection/mmdet/models/detectors/htc.py", line 189, in forward_train
    loss_seg = self.semantic_head.loss(semantic_pred, gt_semantic_seg)
  File "/home/eduardo/dev/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/eduardo/dev/mmdetection/mmdet/models/mask_heads/fused_semantic_head.py", line 104, in loss
    loss_semantic_seg = self.criterion(mask_pred, labels)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1826, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 100, 128, 3]
```

**Reproduction**
1. What command or script did you run?
```
python tools/train.py cfg/htc_x101_32x4d_fpn_20e.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

Only pointed the configuration to my dataset paths.

3. What dataset did you use?

I am using my own COCO formatted dataset. It worked fine for Retinanet but does not work with HTC (config `htc_x101_32x4d_fpn_20e`).

With Retinanet I didn't provide segmentation. Here it seems mandatory (crashes if not provided), so I fill it with 4 coordinates of the bbox rectangle.

**Environment**
 - OS: Ubuntu 18.04.2
 - GCC 7.4.0
 - PyTorch version 1.2.0 (conda)
- GPU model: 2080 ti
- CUDA 10 and CUDNN 7.6.0

**Comment by eduramiba** [comment]
In config I changed all of these from True to False:
```
with_mask=False
with_crowd=False
with_label=False
with_semantic_seg=False
```

And the new error is:

```
File "/home/eduardo/dev/capilos/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
TypeError: forward_train() missing 1 required positional argument: 'gt_labels
```

Does that make any sense? Reading #1024 it seems that mask is required, how should I provide that for each bbox rectangle?

Sorry if repeated or stupid question, thank you!

**Comment by eduramiba** [comment]
I guess the mask must be the png file and original image jpg?

I have mixed images in my dataset, so should I convert all of them to jpg and provide the mask in png always?

**Comment by hellock** [comment]
HTC is for instance segmentation. Similar to Mask R-CNN, the mask of each instance should be annotated. If your dataset does not provide such annotation, HTC/Mask R-CNN is not proper for usage. Furthermore, HTC can also utilize the semantic segmentation annotation, in the config directory, there are two kind of settings that with or without semantic segmentation annotations.

**Comment by mosheliv** [comment]
As this is the third time I see this question, perhaps it should be in the
readme? A better error message will also be good.

**Comment by eduramiba** [comment]
Thank you for your help.
I was trying to improve my object detection model (now using `retinanet_x101_32x4d_fpn_1x`) with HTC because it seems it would produce a better bounding box precision than retinanet.

If I don't care about the mask, does it make sense if I add simple bbox mask data to my dataset and try?
Or should I use another model instead?

Thanks,
Eduardo

**Comment by hellock** [comment]
If you do not have mask annotations, you may try object detection methods instead of instance segmentation models. There are lots of supported detection methods in mmdetection.

**Comment by eduramiba** [comment]
@hellock Thank you, I am trying other models.
I tried GHM and it worked correctly but didn't get an improvement.

Later I have tried other models such as `cascade_rcnn_x101_32x4d_fpn_1x` and `ga_faster_x101_32x4d_fpn_1x` but I am getting this error:

```python
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/eduardo/dev/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [512, 256, 7, 7]], which is output 0 of IndexPutBackward, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Traceback (most recent call last):
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
```

Any idea of the possible cause?

My env is this:

```
Package          Version
---------------- --------------
absl-py          0.7.1          
addict           2.2.1          
certifi          2019.6.16      
cffi             1.12.3         
chardet          3.0.4          
Click            7.0            
cycler           0.10.0         
Cython           0.29.12        
decorator        4.4.0          
Flask            1.1.1          
Flask-Cors       3.0.8          
grpcio           1.16.1         
gunicorn         19.9.0         
idna             2.8            
imagecorruptions 1.0.0          
imageio          2.5.0          
itsdangerous     1.1.0          
Jinja2           2.10.1         
kiwisolver       1.1.0          
Markdown         3.1.1          
MarkupSafe       1.1.1          
matplotlib       3.1.1          
mkl-fft          1.0.12         
mkl-random       1.0.2          
mmcv             0.2.12         
mmdet            1.0rc0+3180621
networkx         2.3            
numpy            1.16.4         
olefile          0.46           
opencv-python    4.1.0.25       
Pillow           6.1.0          
pip              19.1.1         
protobuf         3.8.0          
pycocotools      2.0.0          
pycparser        2.19           
pyparsing        2.4.2          
python-dateutil  2.8.0          
PyWavelets       1.0.3          
PyYAML           5.1.2          
requests         2.22.0         
scikit-image     0.15.0         
scipy            1.3.0          
setuptools       41.0.1         
six              1.12.0         
tensorboard      1.14.0         
tensorboardX     1.8            
terminaltables   3.1.0          
torch            1.2.0          
torchvision      0.4.0          
urllib3          1.25.3         
Werkzeug         0.15.4         
wheel            0.33.4
```

Thanks,
Eduardo

**Comment by hellock** [comment]
Please refer to #1160 for PyTorch 1.2.

**Comment by eduramiba** [comment]
@hellock Thank you I will try that :)

**Comment by unademo** [comment]
> **Describe the bug**
> 
> First I get bug #977 Not clear why that line changes the file name. If removed, then I get this exception:
> 
> ```python
> Traceback (most recent call last):
>   File "tools/train.py", line 108, in <module>
>     main()
>   File "tools/train.py", line 104, in main
>     logger=logger)
>   File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 60, in train_detector
>     _non_dist_train(model, dataset, cfg, validate=validate)
>   File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
>     runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/mmcv-0.2.12-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 264, in train
>     self.model, data_batch, train_mode=True, **kwargs)
>   File "/home/eduardo/dev/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
>     losses = model(**data)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/eduardo/dev/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/eduardo/dev/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
>     return self.forward_train(img, img_meta, **kwargs)
>   File "/home/eduardo/dev/mmdetection/mmdet/models/detectors/htc.py", line 189, in forward_train
>     loss_seg = self.semantic_head.loss(semantic_pred, gt_semantic_seg)
>   File "/home/eduardo/dev/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/eduardo/dev/mmdetection/mmdet/models/mask_heads/fused_semantic_head.py", line 104, in loss
>     loss_semantic_seg = self.criterion(mask_pred, labels)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 916, in forward
>     ignore_index=self.ignore_index, reduction=self.reduction)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1995, in cross_entropy
>     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
>   File "/home/eduardo/miniconda2/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1826, in nll_loss
>     ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
> RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [1, 100, 128, 3]
> ```
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> ```
> python tools/train.py cfg/htc_x101_32x4d_fpn_20e.py
> ```
> 
> 1. Did you make any modifications on the code or config? Did you understand what you have modified?
> 
> Only pointed the configuration to my dataset paths.
> 
> 1. What dataset did you use?
> 
> I am using my own COCO formatted dataset. It worked fine for Retinanet but does not work with HTC (config `htc_x101_32x4d_fpn_20e`).
> 
> With Retinanet I didn't provide segmentation. Here it seems mandatory (crashes if not provided), so I fill it with 4 coordinates of the bbox rectangle.
> 
> **Environment**
> 
> * OS: Ubuntu 18.04.2
> * GCC 7.4.0
> * PyTorch version 1.2.0 (conda)
> * GPU model: 2080 ti
> * CUDA 10 and CUDNN 7.6.0

Since facing the same problems when training with myself COCO-like datasets and HTC, I finally found that there is [a line of code](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L101) in ```mmdetection/mmdet/datasets/coco.py```, which reads the segmentation maps with "*.png" format on your host disk.
This means it needs not only "segmentation" fields in your coco-like json, but also the ground truth mask images. 
Thus, you may need to write a method to load data into the ```seg_map```.

**Comment by tableter** [comment]
Hi i got the same `RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size` problem but i just use the coco datasets with no modification. and this is my data structure:

- coco
annotations
---instances_{trail,val}2017.json
---stuff_{train,val}2017.json
train2017
---0000.jpg
val2017
---0000.jpg
stuffthingmaps
---train2017
------0000.png
---val2017
------0000.png

can someone help me? thanks in advance.

**Comment by FantasyJXF** [comment]
met the same error here with HTC and coco2017, mmdet2.8.0

```
File "tools/train.py", line 193, in <module>
    main()
  File "tools/train.py", line 189, in main
    meta=meta)
  File "/home/work/JXF/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/work/JXF/mmdetection/mmdet/models/detectors/base.py", line 236, in train_step
    losses = self(**data)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/work/JXF/mmdetection/mmdet/models/detectors/base.py", line 176, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/work/JXF/mmdetection/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/home/work/JXF/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line 256, in forward_train
    loss_seg = self.semantic_head.loss(semantic_pred, gt_semantic_seg)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/work/JXF/mmdetection/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py", line 105, in loss
    loss_semantic_seg = self.criterion(mask_pred, labels)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/torch/nn/functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/torch/nn/functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 100, 144, 3]
```

**Comment by FantasyJXF** [comment]
The error comes from `seg map` label files, the `.png` label files should be read with `PIL.Image`, just like the VOC dataset, these label images are in `palette ` mode.
If we just read it with opencv or mmcv, we will get labels shape like `H,W,3` which should be `H,W`, so the `torch.nn.CrossEntropy` loss function went into error.

**Comment by Rock-L21** [comment]
> The error comes from `seg map` label files, the `.png` label files should be read with `PIL.Image`, just like the VOC dataset, these label images are in `palette ` mode. If we just read it with opencv or mmcv, we will get labels shape like `H,W,3` which should be `H,W`, so the `torch.nn.CrossEntropy` loss function went into error.

Following the explanation you stated, how can I modify in the code?
