### ISSUE TITLE
Endless loop while install mmdet using mim/pip and FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph1rknnpr/tmphgu4r4rf.py'

### ISSUE THREAD

**Issue by Markson-Young** [open-mmlab/mmdetection#11544]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
python tools/train.py ...
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
```none
Nothing
```
4. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```none
fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 4090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1
OpenCV: 4.9.0
MMCV: 1.6.0
MMCV Compiler: GCC 11.4
MMCV CUDA Compiler: 11.7
MMDetection: 2.24.1+
```

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

**Endless loop while installing `mmdet==2.24.1`, seems to be a temporary path problem.**
<img width="260" alt="9ba6a5a964605ffe7ef1dfe887a7391" src="https://github.com/open-mmlab/mmdetection/assets/71065224/07a3329c-b0fc-4d48-9a33-be6c37007dd3">

the command I run `python tools/train.py ...`

```none
Traceback (most recent call last):
  File "/home/ubuntu/mmlab/mmlab/mmcv-1.6.0/mmcv/utils/config.py", line 208, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/ubuntu/miniconda3/envs/mmdet2.24/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/tmph1rknnpr/tmphgu4r4rf.py", line 16, in <module>
AssertionError
python-BaseException
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f79afbc8940>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mmdet2.24/lib/python3.9/tempfile.py", line 445, in __del__
    self.close()
  File "/home/ubuntu/miniconda3/envs/mmdet2.24/lib/python3.9/tempfile.py", line 441, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph1rknnpr/tmphgu4r4rf.py'

Process finished with exit code 1
```
I also referenced some issues and reinstalled mmdet [2827](https://github.com/open-mmlab/mmdetection/issues/2827), [2698](https://github.com/open-mmlab/mmdetection/issues/2698) and [6221](https://github.com/open-mmlab/mmdetection/issues/6221), but nothing worked.

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Markson-Young** [comment]
Hello, is anyone here...

**Comment by Viktor1203** [comment]
Hey, i encountered the same issue while setting up my environment. I ended up installing mmdet with pip instead of mim and that fixed it for me.

**Comment by liushengxin** [comment]
same here

**Comment by Ftoy99** [comment]
Same
