### ISSUE TITLE
Torchserve stopped

### ISSUE THREAD

**Issue by tienduchoang** [open-mmlab/mmdetection#11598]
Hi, Thank for your awesome work.
I am working to deploy the mmdetection model using torch serving.
I am following the [detection serving documentation](https://mmdetection.readthedocs.io/en/latest/user_guides/useful_tools.html#model-serving). The model convertion is woked well. However, i cannot deploy the conveted model to the torch serving

#### Docker version: 
pytorch/torchserve:latest

#### Library versions
```
mmcv                    2.1.0
mmdet                   3.3.0       /ws/mmdetection
mmengine                0.10.3
```

### Step3: Convert the trained model
```
python tools/deployment/mmdet2torchserve.py ${CONFIG_FILE} ${CHECKPOINT_FILE} \
--output-folder ${MODEL_STORE} \
--model-name ${MODEL_NAME}
```
### Step 4: Deploy the converted torch model
```
torchserve --start --ncs \
  --model-store ${MODEL_STORE} \
  --models  ${MODEL_NAME}.mar
``` 

But got the problem below:
```
torchserve --start --ncs --model-store cat_work_dir/ --models cat_model.mar
model-server@tienduchoang-pc:/ws/mmdetection$ WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-03-28T02:56:10,171 [WARN ] main org.pytorch.serve.util.ConfigManager - Your torchserve instance can access any URL to load models. When deploying to production, make sure to limit the set of allowed_urls in config.properties
2024-03-28T02:56:10,172 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2024-03-28T02:56:10,210 [INFO ] main org.pytorch.serve.metrics.configuration.MetricConfiguration - Successfully loaded metrics configuration from /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml
2024-03-28T02:56:10,281 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.10.0
TS Home: /home/venv/lib/python3.9/site-packages
Current directory: /ws/mmdetection
Temp directory: /home/model-server/tmp
Metrics config path: /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 3980 M
Python executable: /home/venv/bin/python
Config file: N/A
Inference address: http://127.0.0.1:8080
Management address: http://127.0.0.1:8081
Metrics address: http://127.0.0.1:8082
Model Store: /ws/mmdetection/cat_work_dir
Initial Models: cat_model.mar
Log dir: /ws/mmdetection/logs
Metrics dir: /ws/mmdetection/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 8
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Enable metrics API: true
Metrics mode: LOG
Disable system metrics: false
Workflow Store: /ws/mmdetection/cat_work_dir
CPP log config: N/A
Model config: N/A
System metrics command: default
2024-03-28T02:56:10,286 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2024-03-28T02:56:10,298 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: cat_model.mar
2024-03-28T02:56:43,063 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
	at org.pytorch.serve.archive.utils.ArchiveUtils.readYamlFile(ArchiveUtils.java:69)
	at org.pytorch.serve.archive.model.ModelArchive.getModelConfig(ModelArchive.java:226)
	at org.pytorch.serve.wlm.Model.<init>(Model.java:90)
	at org.pytorch.serve.wlm.ModelManager.createModel(ModelManager.java:390)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:146)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:261)
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:393)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:120)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:101)

```

**Comment by pengxin233** [comment]
We also want to use torchserve to deploy the mmdetection model, but we encountered the same error. I would like to ask how to solve this problem?

java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')

**Comment by pengxin233** [comment]
torch-model-archiver --model-name louye_v5.2_2 --version 1.0 --model-file config.py --serialized-file best_pascal_voc_mAP_epoch_23.pth --handler mmdet_handler.py -f


I used the command to manually package it into a mar package and it was successful. There may be something wrong with the mmdet2torchserve.py script.

**Comment by tienduchoang** [comment]
Hi @pengxin233, Thank for your advice, maybe the mmdet2torchserve.py has problem. I followed your command and got sucessfull on my convertion.

But i got a bug on torch serving below.
```
2024-03-30T05:45:14,407 [DEBUG] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-cat_serve_1.0 State change null -> WORKER_STARTED
2024-03-30T05:45:14,410 [INFO ] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2024-03-30T05:45:14,414 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2024-03-30T05:45:14,416 [DEBUG] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req.cmd LOAD repeats 1 to backend at: 1711777514416
2024-03-30T05:45:14,418 [INFO ] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - Looping backend response at: 1711777514418
2024-03-30T05:45:14,439 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - model_name: cat_serve, batchSize: 1
2024-03-30T05:45:14,669 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - Enabled tensor cores
2024-03-30T05:45:14,669 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - proceeding without onnxruntime
2024-03-30T05:45:15,375 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - Torch TensorRT enabled
2024-03-30T05:45:16,031 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - NOTE! Installing ujson may make loading annotations faster.
2024-03-30T05:45:16,031 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - Backend worker process died.
2024-03-30T05:45:16,031 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2024-03-30T05:45:16,031 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/ts/model_service_worker.py", line 263, in <module>
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     worker.run_server()
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/ts/model_service_worker.py", line 231, in run_server
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/ts/model_service_worker.py", line 194, in handle_connection
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/ts/model_service_worker.py", line 131, in load_model
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     service = model_loader.load(
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/ts/model_loader.py", line 143, in load
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2024-03-30T05:45:16,032 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/tmp/models/e3328baa4daa4b0680891e1ec9186340/mmdet_handler.py", line 29, in initialize
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     self.model = init_detector(self.config_file, checkpoint, self.device)
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/ws/mmdet/apis/inference.py", line 53, in init_detector
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     config = Config.fromfile(config)
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 458, in fromfile
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     lazy_import is None and not Config._is_lazy_import(filename):
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 1657, in _is_lazy_import
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG -     with open(filename, encoding='utf-8') as f:
2024-03-30T05:45:16,033 [INFO ] W-9000-cat_serve_1.0-stdout MODEL_LOG - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/models/e3328baa4daa4b0680891e1ec9186340/config.py'
2024-03-30T05:45:16,035 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2024-03-30T05:45:16,036 [DEBUG] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2024-03-30T05:45:16,036 [DEBUG] W-9000-cat_serve_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died., responseTimeout:120sec
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:229) [model-server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Have you ever got this problem?

**Comment by pengxin233** [comment]
Yes, I know this error. This is because the name of the model file specified in your handler is config.py. You only need to change the name of your model, or modify the code in the handler --model- fileconfig.py

**Comment by pengxin233** [comment]
self.config_file = os.path.join(model_dir, 'config.py')

**Comment by tienduchoang** [comment]
Yes, I also edited the config file before, but I still encountered more errors, so I decided to give up on it. But thanks to your comment, I continued and fixed the bug.

Your comment was do help me to solve the problem, you save my day.  Thank @pengxin233 so much

**Comment by AP-Kai** [comment]
Thanks

**Comment by JookerLoo** [comment]
> self.config_file = os.path.join(model_dir, 'config.py')

How to do?

**Comment by JookerLoo** [comment]
I found a solution, just change the list in mmdet2torchserver.py
`        args = Namespace(
            **{
                'model_file': f'{tmpdir}/config.py',
                # 'config_file': f'{tmpdir}/config.py',
                'config_file': "",
                'serialized_file': checkpoint_file,
                'handler': f'{Path(__file__).parent}/mmdet_handler.py',
                'model_name': model_name or Path(checkpoint_file).stem,
                'version': model_version,
                'export_path': output_folder,
                'force': force,
                'requirements_file': None,
                'extra_files': None,
                'runtime': 'python',
                'archive_format': 'default'
            })`

**Comment by JookerLoo** [comment]
I found a solution, just change the list in mmdet2torchserver.py
```        args = Namespace(
            **{
                'model_file': f'{tmpdir}/config.py',
                # 'config_file': f'{tmpdir}/config.py',
                'config_file': "",
                'serialized_file': checkpoint_file,
                'handler': f'{Path(__file__).parent}/mmdet_handler.py',
                'model_name': model_name or Path(checkpoint_file).stem,
                'version': model_version,
                'export_path': output_folder,
                'force': force,
                'requirements_file': None,
                'extra_files': None,
                'runtime': 'python',
                'archive_format': 'default'
            })```
