### ISSUE TITLE
Unable to deploy glip model in mmdetection due to not downloading bert, transformer, etc. correctly

### ISSUE THREAD

**Issue by Yu1802** [open-mmlab/mmdetection#11622]
I downloaded the vocab, config and pytorch-model files from the hug website, stored them in a new hub folder in mmdetection and added them to the configs/glip/glip_atss_swin-t_fpn_dyhead_16xb2_ms-2x_funtune Add the following to the _coco.py file，
from transformers import BertConfig, BertModel
from transformers import AutoTokenizer
config = BertConfig.from_pretrained("hub/bert-base-uncased")
model = BertModel.from_pretrained("hub/bert-base-uncased", add_pooling_layer=False, config=config)
tokenizer = AutoTokenizer.from_pretrained("hub/bert-base-uncased")

config.save_pretrained("hub/bert-base-uncased")
model.save_pretrained("hub/bert-base-uncased")
tokenizer.save_pretrained("hub/bert-base-uncased")
lang_model_name = 'hub/bert-base-uncased'

and executes the python training command, but reports an error:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf/pytree/pytree_utils.py", line 113, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 188, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 157, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 230, in addtoken
    return self._addtoken(ilabel, type, value, context)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 313, in _addtoken
    raise ParseError('bad input', type, value, context)
yapf_third_party._ylib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (1, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 198, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf/pytree/pytree_utils.py", line 116, in ParseCodeToTree
    ast.parse(code)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    AutoTokenizer=<class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/config/config.py", line 1477, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 201, in FormatCode
    raise errors.YapfError(errors.FormatErrorMsg(e))
yapf.yapflib.errors.YapfError: <unknown>:1:15: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 403, in __init__
    self._log_env(env_cfg)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 2388, in _log_env
    self.logger.info(f'Config:\n{self.cfg.pretty_text}')
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/config/config.py", line 1482, in pretty_text
    raise SyntaxError('Failed to format the config file, please '
SyntaxError: Failed to format the config file, please check the syntax of: 
AutoTokenizer=<class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
BertConfig=<class 'transformers.models.bert.configuration_bert.BertConfig'>
BertModel=<class 'transformers.models.bert.modeling_bert.BertModel'>
auto_scale_lr=dict(
    base_batch_size=16,
    enable=False)
backend_args=None
config=BertConfig {
      "_name_or_path": "hub/bert-base-uncased",
      "architectures": [
        "BertModel"
      ],
      "attention_probs_dropout_prob": 0.1,
      "classifier_dropout": null,
      "gradient_checkpointing": false,
      "hidden_act": "gelu",
      "hidden_dropout_prob": 0.1,
      "hidden_size": 768,
      "initializer_range": 0.02,
      "intermediate_size": 3072,
      "layer_norm_eps": 1e-12,
      "max_position_embeddings": 512,
      "model_type": "bert",
      "num_attention_heads": 12,
      "num_hidden_layers": 12,
      "pad_token_id": 0,
      "position_embedding_type": "absolute",
      "torch_dtype": "float32",
      "transformers_version": "4.39.3",
      "type_vocab_size": 2,
      "use_cache": true,
      "vocab_size": 30522
    }
    
data_root='data/coco/'
dataset_type='CocoDataset'
default_hooks=dict(
    checkpoint=dict(
        interval=1,
        type='CheckpointHook'),
    logger=dict(
        interval=50,
        type='LoggerHook'),
    param_scheduler=dict(
        type='ParamSchedulerHook'),
    sampler_seed=dict(
        type='DistSamplerSeedHook'),
    timer=dict(
        type='IterTimerHook'),
    visualization=dict(
        type='DetVisualizationHook'))
default_scope='mmdet'
env_cfg=dict(
    cudnn_benchmark=False,
    dist_cfg=dict(
        backend='nccl'),
    mp_cfg=dict(
        mp_start_method='fork',
        opencv_num_threads=0))
lang_model_name='hub/bert-base-uncased'
launcher='none'
load_from='glip_tiny_mmdet-c24ce662.pth'
log_level='INFO'
log_processor=dict(
    by_epoch=True,
    type='LogProcessor',
    window_size=50)
model=dict(
    backbone=dict(
        attn_drop_rate=0.0,
        convert_weights=False,
        depths=[
            2,
            2,
            6,
            2,
            ],
        drop_path_rate=0.2,
        drop_rate=0.0,
        embed_dims=96,
        mlp_ratio=4,
        num_heads=[
            3,
            6,
            12,
            24,
            ],
        out_indices=(
            1,
            2,
            3,
            ),
        patch_norm=True,
        qk_scale=None,
        qkv_bias=True,
        type='SwinTransformer',
        window_size=7,
        with_cp=False),
    bbox_head=dict(
        anchor_generator=dict(
            center_offset=0.5,
            octave_base_scale=8,
            ratios=[
                1.0,
                ],
            scales_per_octave=1,
            strides=[
                8,
                16,
                32,
                64,
                128,
                ],
            type='AnchorGenerator'),
        bbox_coder=dict(
            target_means=[
                0.0,
                0.0,
                0.0,
                0.0,
                ],
            target_stds=[
                0.1,
                0.1,
                0.2,
                0.2,
                ],
            type='DeltaXYWHBBoxCoderForGLIP'),
        early_fuse=True,
        feat_channels=256,
        in_channels=256,
        lang_model_name='bert-base-uncased',
        loss_bbox=dict(
            loss_weight=2.0,
            type='GIoULoss'),
        loss_centerness=dict(
            loss_weight=1.0,
            type='CrossEntropyLoss',
            use_sigmoid=True),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=1.0,
            type='FocalLoss',
            use_sigmoid=True),
        num_classes=80,
        type='ATSSVLFusionHead',
        use_checkpoint=True),
    data_preprocessor=dict(
        bgr_to_rgb=False,
        mean=[
            103.53,
            116.28,
            123.675,
            ],
        pad_size_divisor=32,
        std=[
            57.375,
            57.12,
            58.395,
            ],
        type='DetDataPreprocessor'),
    language_model=dict(
        name='bert-base-uncased',
        type='BertModel'),
    neck=dict(
        add_extra_convs='on_output',
        in_channels=[
            192,
            384,
            768,
            ],
        num_outs=5,
        out_channels=256,
        relu_before_extra_convs=True,
        start_level=0,
        type='FPN_DropBlock'),
    test_cfg=dict(
        max_per_img=100,
        min_bbox_size=0,
        nms=dict(
            iou_threshold=0.6,
            type='nms'),
        nms_pre=1000,
        score_thr=0.05),
    train_cfg=dict(
        allowed_border=-1,
        assigner=dict(
            iou_calculator=dict(
                type='BboxOverlaps2D_GLIP'),
            topk=9,
            type='ATSSAssigner'),
        debug=False,
        pos_weight=-1),
    type='GLIP')
optim_wrapper=dict(
    clip_grad=dict(
        max_norm=1,
        norm_type=2),
    optimizer=dict(
        betas=(
            0.9,
            0.999,
            ),
        lr=1e-05,
        type='AdamW',
        weight_decay=0.05),
    paramwise_cfg=dict(
        custom_keys=dict(
            absolute_pos_embed=dict(
                decay_mult=0.0),
            norm=dict(
                decay_mult=0.0),
            relative_position_bias_table=dict(
                decay_mult=0.0))),
    type='OptimWrapper')
param_scheduler=[
    dict(begin=0,
        by_epoch=False,
        end=500,
        start_factor=0.001,
        type='LinearLR'),
    dict(begin=0,
        by_epoch=True,
        end=12,
        gamma=0.1,
        milestones=[
            8,
            11,
            ],
        type='MultiStepLR'),
    ]
resume=False
test_cfg=dict(
    type='TestLoop')
test_dataloader=dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/instances_val2017.json',
        backend_args=None,
        data_prefix=dict(
            img='val2017/'),
        data_root='data/coco/',
        pipeline=[
            dict(backend_args=None,
                imdecode_backend='pillow',
                type='LoadImageFromFile'),
            dict(backend='pillow',
                keep_ratio=True,
                scale=(
                    800,
                    1333,
                    ),
                type='FixScaleResize'),
            dict(type='LoadAnnotations',
                with_bbox=True),
            dict(meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'text',
                    'custom_entities',
                    ),
                type='PackDetInputs'),
            ],
        return_classes=True,
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(
        shuffle=False,
        type='DefaultSampler'))
test_evaluator=dict(
    ann_file='data/coco/annotations/instances_val2017.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
test_pipeline=[
    dict(backend_args=None,
        imdecode_backend='pillow',
        type='LoadImageFromFile'),
    dict(backend='pillow',
        keep_ratio=True,
        scale=(
            800,
            1333,
            ),
        type='FixScaleResize'),
    dict(type='LoadAnnotations',
        with_bbox=True),
    dict(meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'text',
            'custom_entities',
            ),
        type='PackDetInputs'),
    ]
tokenizer=BertTokenizerFast(name_or_path='hub/bert-base-uncased', vocab_size=30522, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
        0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
    }
train_cfg=dict(
    max_epochs=12,
    type='EpochBasedTrainLoop',
    val_interval=1)
train_dataloader=dict(
    batch_sampler=dict(
        type='AspectRatioBatchSampler'),
    batch_size=2,
    dataset=dict(
        dataset=dict(
            ann_file='annotations/instances_train2017.json',
            backend_args=None,
            data_prefix=dict(
                img='train2017/'),
            data_root='data/coco/',
            filter_cfg=dict(
                filter_empty_gt=True,
                min_size=32),
            pipeline=[
                dict(backend_args=None,
                    imdecode_backend='pillow',
                    type='LoadImageFromFile'),
                dict(type='LoadAnnotations',
                    with_bbox=True),
                dict(type='GTBoxSubOne_GLIP'),
                dict(backend='pillow',
                    keep_ratio=True,
                    resize_type='FixScaleResize',
                    scales=[
                        (
                                1333,
                                480,
                                ),
                        (
                                1333,
                                560,
                                ),
                        (
                                1333,
                                640,
                                ),
                        (
                                1333,
                                720,
                                ),
                        (
                                1333,
                                800,
                                ),
                        ],
                    type='RandomChoiceResize'),
                dict(prob=0.5,
                    type='RandomFlip_GLIP'),
                dict(min_gt_bbox_wh=(
                        1,
                        1,
                        ),
                    type='FilterAnnotations'),
                dict(meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'scale_factor',
                        'flip',
                        'flip_direction',
                        'text',
                        'custom_entities',
                        ),
                    type='PackDetInputs'),
                ],
            return_classes=True,
            type='CocoDataset'),
        times=2,
        type='RepeatDataset'),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(
        shuffle=True,
        type='DefaultSampler'))
train_pipeline=[
    dict(backend_args=None,
        imdecode_backend='pillow',
        type='LoadImageFromFile'),
    dict(type='LoadAnnotations',
        with_bbox=True),
    dict(type='GTBoxSubOne_GLIP'),
    dict(backend='pillow',
        keep_ratio=True,
        resize_type='FixScaleResize',
        scales=[
            (
                    1333,
                    480,
                    ),
            (
                    1333,
                    560,
                    ),
            (
                    1333,
                    640,
                    ),
            (
                    1333,
                    720,
                    ),
            (
                    1333,
                    800,
                    ),
            ],
        type='RandomChoiceResize'),
    dict(prob=0.5,
        type='RandomFlip_GLIP'),
    dict(min_gt_bbox_wh=(
            1,
            1,
            ),
        type='FilterAnnotations'),
    dict(meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'flip',
            'flip_direction',
            'text',
            'custom_entities',
            ),
        type='PackDetInputs'),
    ]
val_cfg=dict(
    type='ValLoop')
val_dataloader=dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/instances_val2017.json',
        backend_args=None,
        data_prefix=dict(
            img='val2017/'),
        data_root='data/coco/',
        pipeline=[
            dict(backend_args=None,
                imdecode_backend='pillow',
                type='LoadImageFromFile'),
            dict(backend='pillow',
                keep_ratio=True,
                scale=(
                    800,
                    1333,
                    ),
                type='FixScaleResize'),
            dict(type='LoadAnnotations',
                with_bbox=True),
            dict(meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'text',
                    'custom_entities',
                    ),
                type='PackDetInputs'),
            ],
        return_classes=True,
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(
        shuffle=False,
        type='DefaultSampler'))
val_evaluator=dict(
    ann_file='data/coco/annotations/instances_val2017.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
vis_backends=[
    dict(type='LocalVisBackend'),
    ]
visualizer=dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
        ])

I have tried to put the bert folder in the cache folder and change the path in the training file and it still reports an error.
Could you help me with the above? Thank you very much.

**Comment by Yu1802** [comment]
I also tried changing the configuration in the training file to，
config = BertConfig.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased", add_pooling_layer=False, config=config)
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
It will report the following error

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f8c03332910>, 'Connection to huggingface.co timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8c03332910>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1238, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1631, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f8c03332910>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 5ba9fb63-3776-4e56-ad2d-34a475ffb842)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1371, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 68, in main
    cfg = Config.fromfile(args.config)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/config/config.py", line 457, in fromfile
    cfg_dict, cfg_text, env_variables = Config._file2dict(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/config/config.py", line 941, in _file2dict
    raise e
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/mmengine/config/config.py", line 919, in _file2dict
    eval(codeobj, global_locals_var, global_locals_var)
  File "/home/zxy/mmdetection/configs/glip/glip_atss_swin-t_fpn_dyhead_16xb2_ms-2x_funtune_coco.py", line 8, in <module>
    config = BertConfig.from_pretrained("bert-base-uncased")
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 602, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/zxy/anaconda3/envs/lab3/lib/python3.8/site-packages/transformers/utils/hub.py", line 441, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by xuans29** [comment]
did you find the solution? I also encountered this problem
