### ISSUE TITLE
Need help pls "AttributeError: module 'mmcv' has no attribute 'jit'"

### ISSUE THREAD

**Issue by PRABS25** [open-mmlab/mmdetection#11630]
I ran this command previously and it worked then i try to ran some other models. when i run this command again i got error. i tried to uninstall and install back the mmcv but no changes pls help

(openmmlab) PS C:\Users\praba\PycharmProjects\mmdetection> python demo/image_demo.py demo/demo.jpg demo/rtmdet_tiny_8xb32-300e_coco.py --weights demo/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cuda --show
Loads checkpoint by local backend from path: demo/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth
c:\users\praba\pycharmprojects\mmdetection\mmdet\mmcv\__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "demo/image_demo.py", line 192, in <module>
    main()
  File "demo/image_demo.py", line 179, in main
    inferencer = DetInferencer(**init_args)
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\apis\det_inferencer.py", line 99, in __init__
    super().__init__(
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\infer\infer.py", line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\infer\infer.py", line 483, in _init_model
    model = MODELS.build(cfg.model)
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 451, in get
    self.import_from_location()
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "C:\Users\praba\anaconda3\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\models\__init__.py", line 4, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\models\dense_heads\__init__.py", line 55, in <module>
    from .reppoints_v2_head import RepPointsV2Head
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\models\dense_heads\reppoints_v2_head.py", line 8, in <module>
    from mmdet.core import (PointGenerator, build_assigner, build_sampler,
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\core\__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\core\bbox\__init__.py", line 4, in <module>
    from .coder import (BaseBBoxCoder, DeltaXYWHBBoxCoder, PseudoBBoxCoder,
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\core\bbox\coder\__init__.py", line 2, in <module>
    from .bucketing_bbox_coder import BucketingBBoxCoder
  File "c:\users\praba\pycharmprojects\mmdetection\mmdet\core\bbox\coder\bucketing_bbox_coder.py", line 94, in <module>
    @mmcv.jit(coderize=True)
AttributeError: module 'mmcv' has no attribute 'jit'

**Comment by wdzwdxy** [comment]
same as u

**Comment by wdzwdxy** [comment]
Traceback (most recent call last):
  File "D:\codae\mmdetection\tools\train.py", line 121, in <module>
    main()
  File "D:\codae\mmdetection\tools\train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
    runner = cls(
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 416, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\runner\runner.py", line 794, in build_visualizer
    return Visualizer.get_instance(**visualizer)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\visualization\visualizer.py", line 1184, in get_instance
    instance = super().get_instance(name, **kwargs)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\utils\manager.py", line 110, in get_instance
    instance = cls(name=name, **kwargs)  # type: ignore
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\visualization\visualizer.py", line 186, in __init__
    vis_backend = VISBACKENDS.build(vis_backend)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\registry\registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\registry\build_functions.py", line 98, in build_from_cfg
    obj_cls = registry.get(obj_type)
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\registry\registry.py", line 451, in get
    self.import_from_location()
  File "C:\Users\gang\.conda\envs\pytorch\lib\site-packages\mmengine\registry\registry.py", line 376, in import_from_location
    import_module(loc)
  File "C:\Users\gang\.conda\envs\pytorch\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\codae\mmdetection\mmdet\visualization\__init__.py", line 2, in <module>
    from .local_visualizer import DetLocalVisualizer, TrackLocalVisualizer
  File "D:\codae\mmdetection\mmdet\visualization\local_visualizer.py", line 17, in <module>
    from ..evaluation import INSTANCE_OFFSET
  File "D:\codae\mmdetection\mmdet\evaluation\__init__.py", line 4, in <module>
    from .metrics import *  # noqa: F401,F403
  File "D:\codae\mmdetection\mmdet\evaluation\metrics\__init__.py", line 5, in <module>
    from .coco_metric import CocoMetric
  File "D:\codae\mmdetection\mmdet\evaluation\metrics\coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval, COCOevalMP
  File "D:\codae\mmdetection\mmdet\datasets\__init__.py", line 38, in <module>
    from .custom import CustomDataset
  File "D:\codae\mmdetection\mmdet\datasets\custom.py", line 11, in <module>
    from mmdet.core import eval_map, eval_recalls
  File "D:\codae\mmdetection\mmdet\core\__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "D:\codae\mmdetection\mmdet\core\bbox\__init__.py", line 4, in <module>
    from .coder import (BaseBBoxCoder, DeltaXYWHBBoxCoder, PseudoBBoxCoder,
  File "D:\codae\mmdetection\mmdet\core\bbox\coder\__init__.py", line 2, in <module>
    from .bucketing_bbox_coder import BucketingBBoxCoder
  File "D:\codae\mmdetection\mmdet\core\bbox\coder\bucketing_bbox_coder.py", line 94, in <module>
    @mmcv.jit(coderize=True)
AttributeError: module 'mmcv' has no attribute 'jit'

**Comment by hlnull** [comment]
It seems that the mmcv 1.7.2 supports `jit` in mmcv while the newer mmcv only supports `jit` in mmcv.utils.

![image](https://github.com/user-attachments/assets/d36244cf-b24a-4109-b90c-01294919af32)
![image](https://github.com/user-attachments/assets/0e81b7f7-bb8b-4902-b80c-83727ca6109e)

Replace `@mmcv.jit` with `@mmcv.utils.jit`.
