### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Davids3498** [open-mmlab/mmdetection#11650]
i getting  the error described here when running the train script.
when i remove the line `filter_cfg=dict(filter_empty_gt=True)` from the config file and running train again i dont get the error, but the dataset seems right and no other exceptions/errors rise.

- [x] I have searched related issues but cannot get the expected help.
- [x] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**
Basically im getting a error 
```
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

when trying to train a simple model for object detection 

**Reproduction**

1. What command or script did you run?

```none
_base_ = [
    '/mmdetection/configs/_base_/models/faster-rcnn_r50_fpn.py',
    '/mmdetection/configs/_base_/schedules/schedule_1x.py',
    '/mmdetection/configs/_base_/default_runtime.py'
]

# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/house_data/'
backend_args = None # Arguments to instantiate the corresponding file backend

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)


train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip',prob=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='ImageToTensor', keys=['img'])
]

train_dataloader=dict(
    batch_size=2,  # Batch size of a single GPU
    num_workers=2,  # Worker to pre-fetch data for each single GPU
    persistent_workers=True,
    sampler=dict(  # training data sampler
        type='DefaultSampler',  # DefaultSampler which supports both distributed and non-distributed training. Refer to https://mmengine.readthedocs.io/en/latest/api/generated/mmengine.dataset.DefaultSampler.html#mmengine.dataset.DefaultSampler
        shuffle=True),
    dataset=dict(  # Train dataset config
        type=dataset_type,
        data_root=data_root,
        ann_file='ann/train.json',  # Path of annotation file
        data_prefix=dict(img='/jpg_Images/'),  # Prefix of image path
        filter_cfg=dict(filter_empty_gt=True),  # Config of filtering images and annotations
        pipeline=train_pipeline,
        backend_args=backend_args)
    )

test_dataloader=dict(
    batch_size=1,  # Batch size of a single GPU
    num_workers=2,  # Worker to pre-fetch data for each single GPU
    persistent_workers=True,
    sampler=dict(  # training data sampler
        type='DefaultSampler',  # DefaultSampler which supports both distributed and non-distributed training. Refer to https://mmengine.readthedocs.io/en/latest/api/generated/mmengine.dataset.DefaultSampler.html#mmengine.dataset.DefaultSampler
        shuffle=False),  # not shuffle during validation and testing
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='ann/val.json',
        data_prefix=dict(img='jpg_Images/'),
        test_mode=True,  # Turn on the test mode of the dataset to avoid filtering annotations or images
        pipeline=test_pipeline,
        backend_args=backend_args)
    )

val_dataloader = test_dataloader

val_evaluator = dict(  # Validation evaluator config
    type='CocoMetric',  # The coco metric used to evaluate AR, AP, and mAP for detection and instance segmentation
    ann_file=data_root + 'ann/val.json',  # Annotation file path
    metric=['bbox'],  # Metrics to be evaluated, `bbox` for detection and `segm` for instance segmentation
    format_only=False,
    backend_args=backend_args)
test_evaluator = val_evaluator 


model = dict(
    type='FasterRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')
    ),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5
    ),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]
        ),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]
        ),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0
        ),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)
    ),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]
        ),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=3,  
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]
            ),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0
            ),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)
        )
    )
)

# optimizer
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

nothing to the rest of the code just made my own configuration

4. What dataset did you use?
im using my own dataset 
```
|-- data
|   `-- house_data
|       |-- Images
|       |-- ann
|       `-- jpg_Images
```
the json file built something like this
```
{
    "images": [
        {
            "id": 1,
            "file_name": "id_4dnohptcwcfp.jpg",
            "width": 1000,
            "height": 1000
        }],
    "annotations": [
        {
            "id": 0,
            "image_id": 1,
            "category_id": 2,
            "bbox": [
                122.0,
                1.0,
                42.0,
                30.0
            ],
            "area": 1260.0,
            "iscrowd": 0,
            "segmentation": []
        }],
    "categories": [
        {
            "id": 1,
            "name": "Other",
            "supercategory":""
        },
        {
            "id": 2,
            "name": "Tin",
            "supercategory":""
        },
        {
            "id": 3,
            "name": "Thatch",
            "supercategory":""
        }
    ]
}
```
**Environment**

```
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.9.0
MMEngine: 0.10.3
MMDetection: 3.3.0+cfd5d3a
```
2. You may add addition that may be helpful for locating the problem, such as
   - im using the docker image provided in this repo
   - i didnt made any changes to env variables

**Error traceback**
```
Traceback (most recent call last):
  File "tools/train.py", line 121, in <module>
    main()
  File "tools/train.py", line 117, in main
    runner.train()
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1729, in train
    self._train_loop)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1523, in build_train_loop
    runner=self, dataloader=self._train_dataloader))
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/base_loop.py", line 27, in __init__
    dataloader, seed=runner.seed, diff_rank_seed=diff_rank_seed)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/mmdetection/mmdet/datasets/base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "/mmdetection/mmdet/datasets/base_det_dataset.py", line 89, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/opt/conda/lib/python3.7/site-packages/mmengine/dataset/base_dataset.py", line 768, in _serialize_data
    data_bytes = np.concatenate(data_list)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by Davids3498** [comment]
i was missing `metainfo=metainfo` inside the `*_dataloader`.
```
metainfo = {
'classes' :('a','b', 'c', ),
    'palette': [
        (220, 20, 60),(96,69, 60),(220,60,100),
    ]
}
```

**Comment by PoplarBoat** [comment]
Hello Davids3498! May I ask how you fix the problem? I met the same problem when training a VFNet.When I removed the Filter in coco_detection.py,the model work normaly but the loss is very low like 0.000x. I guess it is because the annotations were not read correctly.
