### ISSUE TITLE
Multi GPUs training raise an error 

### ISSUE THREAD

**Issue by ZenFSheng** [open-mmlab/mmdetection#1172]
Single GPU training is normal. But multi gpus training will raise an error below.
How can I solve it ?
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/home/dl/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
  File "/home/dl/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
    exitcode = _main(fd)
  File "/home/dl/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
  File "/home/dl/anaconda3/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
MemoryError
MemoryError
Traceback (most recent call last):
  File "/home/dl/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dl/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dl/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/dl/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/dl/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/cascade_rcnn_x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>
```

**Comment by hellock** [comment]
How much memory does your server have?

**Comment by ZenFSheng** [comment]
> How much memory does your server have?
Four GPUs，for each one is  TITAN X  12G

**Comment by hellock** [comment]
Oh I mean CPU memory.

**Comment by ZenFSheng** [comment]
> Oh I mean CPU memory.

Sorry... the CPU memory is 32G

**Comment by hellock** [comment]
The memory is quite tight. You may try reducing the data workers.

**Comment by ZenFSheng** [comment]
> The memory is quite tight. You may try reducing the data workers.
In config:
workers_per_gpu=2 now，I should reduce it to 1, right?

**Comment by ZenFSheng** [comment]
> The memory is quite tight. You may try reducing the data workers.

If I wanna increase my CPU memory, how many is suitable?  Maybe 64G ?

**Comment by hellock** [comment]
80G memory is consumed with 8*2 workers, so 64G may be enough for 4 GPUs. However, if you plan to train on larger datasets, maybe you need even larger memory.
BTW, Fast R-CNN takes more memory than end-to-end Faster R-CNN, sometimes it can eat 200G memory or more.

**Comment by ZenFSheng** [comment]
> 80G memory is consumed with 8*2 workers, so 64G may be enough for 4 GPUs. However, if you plan to train on larger datasets, maybe you need even larger memory.
> BTW, Fast R-CNN takes more memory than end-to-end Faster R-CNN, sometimes it can eat 200G memory or more.

😮 Oh my~
 Thank you for your reply，that really helps a lot.🙂

**Comment by www516717402** [comment]
great help
