### ISSUE TITLE
finetune model error

### ISSUE THREAD

**Issue by DecentMakeover** [open-mmlab/mmdetection#1176]
When trying to fine tune model on custom dataset with 15 classes. I get

	Traceback (most recent call last):
	  File "tools/train.py", line 98, in <module>
	    main()
	  File "tools/train.py", line 78, in main
	    train_dataset = get_dataset(cfg.data.train)
	  File "/media/bubbles/fecf5b15-5a64-477b-8192-f8508a986ffe/ai/ryan/mmdetection/mmdet/datasets/utils.py", line 102, in get_dataset
	    assert len(img_prefixes) == num_dset
	AssertionError

I have changed the model like this and i am doing load_from --

       import torch
	pretrained_weights  = torch.load('checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

	num_class = 15
	pretrained_weights['state_dict']['bbox_head.fc_cls.weight'].resize_(num_class, 1024)
	pretrained_weights['state_dict']['bbox_head.fc_cls.bias'].resize_(num_class)
	pretrained_weights['state_dict']['bbox_head.fc_reg.weight'].resize_(num_class*4, 1024)
	pretrained_weights['state_dict']['bbox_head.fc_reg.bias'].resize_(num_class*4)

	torch.save(pretrained_weights, "checkpoints/faster_rcnn_r50_fpn_1x_%d.pth"%num_class)

**Comment by DecentMakeover** [comment]
Fixed this
