### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'model'

### ISSUE THREAD

**Issue by sivareddy9166** [open-mmlab/mmdetection#11775]
Hi,
I'm trying to run video_demo,py in mmdetections with internimage using command:
```
python demo/video_demo.py Aircraft_Processing_test.mp4 internimage/internimage_h_22kto1k_640.yaml  internimage/internimage_h_22kto1k_640.pth --out Aircraft_Processing_person_output2.mp4 --device cuda:0
```
getting the error :
```(openmmlab) babo@odin:~/sivakondla/mmdetection$ python demo/video_demo.py Aircraft_Processing_test.mp4 internimage/internimage_h_22kto1k_640.yaml  internimage/internimage_h_22kto1k_640.pth --out Aircraft_Processing_person_output2.mp4 --device cuda:0
Traceback (most recent call last):
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 109, in __getattr__
    value = super().__getattr__(name)
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 138, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 105, in __missing__
    raise KeyError(name)
KeyError: 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/video_demo.py", line 84, in <module>
    main()
  File "demo/video_demo.py", line 40, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/babo/sivakondla/mmdetection/mmdet/apis/inference.py", line 59, in init_detector
    elif 'init_cfg' in config.model.backbone:
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 1499, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/babo/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 113, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'model'
```

cfg file : 
```DATA:
  IMG_SIZE: 640
  IMG_ON_MEMORY: True
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0
  REPROB: 0.0
MODEL:
  TYPE: intern_image
  DROP_PATH_RATE: 0.2
  LABEL_SMOOTHING: 0.3
  INTERN_IMAGE:
    CORE_OP: 'DCNv3'
    DEPTHS: [6, 6, 32, 6]
    GROUPS: [10, 20, 40, 80]
    CHANNELS: 320
    DW_KERNEL_SIZE: 5
    LAYER_SCALE: None
    OFFSET_SCALE: 1.0
    MLP_RATIO: 4.0
    POST_NORM: False
    RES_POST_NORM: True
    LEVEL2_POST_NORM: True
    LEVEL2_POST_NORM_BLOCK_IDS: [5, 11, 17, 23, 29]
    CENTER_FEATURE_SCALE: True
    USE_CLIP_PROJECTOR: True
TRAIN:
  EMA:
    ENABLE: true
    DECAY: 0.9999
  EPOCHS: 20
  WARMUP_EPOCHS: 2
  WEIGHT_DECAY: 0.05
  BASE_LR: 2e-05 # 512
  WARMUP_LR: .0
  MIN_LR: .0
  USE_CHECKPOINT: true
  OPTIMIZER:
    USE_ZERO: True
    DCN_LR_MUL: 0.1
AMP_OPT_LEVEL: O0
```

**Comment by wuying-541** [comment]
hello，have you solved this problem，I have the same problem as you

**Comment by scybd** [comment]
hello, have you solved it? I have the problem too. @sivareddy9166 @wuying-541

**Comment by wuying-541** [comment]
没有，重新安装了一下，可以看这个视频 【旋转目标检测mmrotate零基础入门教程】 https://www.bilibili.com/video/BV1N94y1A7DZ/?share_source=copy_web&vd_source=279c39b25c6851e98f90ff6735e9044c

**Comment by wuying-541** [comment]
没有，重新安装了一下，可以看这个视频 【旋转目标检测mmrotate零基础入门教程】 https://www.bilibili.com/video/BV1N94y1A7DZ/?share_source=copy_web&vd_source=279c39b25c6851e98f90ff6735e9044c  @scybd
