### ISSUE TITLE
Assertion Error "assert isinstance(item, IndexType.__args__)" in mmengine in Tutorial

### ISSUE THREAD

**Issue by LucaBernecker** [open-mmlab/mmdetection#11794]
Hej,

I am using

M3 Pro

and have the packages

mmdetection: 3.3.0
mmcv: 2.1.0
mmengine: 0.10.4
torchvision: 0.18.1
torch: 2.3.1

I am running the Tutorial: "MMDet_Tutorial" and in during the training I get an assertion error. I have only changed parts of the tutorial to fit it for CPUs. Does anyone know what I do wrong?

config = "configs/rtmdet/rtmdet_tiny_1xb4-20e_balloon.py"
python_executable = "/Users/lucabernecker/anaconda3/envs/mdetect2/bin/python"
script_path = "tools/train.py"
!{python_executable} "{script_path}" '{config}'

I get the following printout with error:

06/14 13:43:07 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: darwin
    Python: 3.9.19 (main, May  6 2024, 14:39:30) [Clang 14.0.6 ]
    CUDA available: False
    MUSA available: False
    numpy_random_seed: 602692056
    GCC: Apple clang version 15.0.0 (clang-1500.3.9.4)
    PyTorch: 2.3.1
    PyTorch compiling details: PyTorch built with:
  - GCC 4.2
  - C++ Version: 201703
  - clang 14.0.3
  - OpenMP 201811
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, 
Traceback (most recent call last):
  File "/Users/lucabernecker/PHD-UiT/mmdetection/tools/train.py", line 121, in <module>
    main()
  File "/Users/lucabernecker/PHD-UiT/mmdetection/tools/train.py", line 117, in main
    runner.train()
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 103, in run
    self.runner.val_loop.run()
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 373, in run
    self.run_iter(idx, data_batch)
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/runner/loops.py", line 393, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 133, in val_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/detectors/single_stage.py", line 110, in predict
    results_list = self.bbox_head.predict(
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 197, in predict
    predictions = self.predict_by_feat(
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 279, in predict_by_feat
    results = self._predict_by_feat_single(
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 423, in _predict_by_feat_single
    return self._bbox_post_process(
  File "/Users/lucabernecker/PHD-UiT/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 480, in _bbox_post_process
    results = results[valid_mask]
  File "/Users/lucabernecker/anaconda3/envs/mdetect2/lib/python3.9/site-packages/mmengine/structures/instance_data.py", line 175, in __getitem__
    assert isinstance(item, IndexType.__args__)
AssertionError

**Comment by ggcr** [comment]
@LucaBernecker Hi, have you found out the problem? It must be something related with 'mps' as if I run it with 'cpu' it correctly performs inference.

**Comment by LucaBernecker** [comment]
> @LucaBernecker Hi, have you found out the problem? It must be something related with 'mps' as if I run it with 'cpu' it correctly performs inference.

Hej, I tried it with "cpu". I reinstalled it completely and I am fighting with other errors now.

**Comment by asamiKA** [comment]
Same AssertionError occured.

While the type of `valid_mask` is expected to be `torch.BoolTensor` or `torch.cuda.BoolTensor`, this `valid_mask` seems to be `torch.Tensor` when calculated on `mps`.

I commented out this Asserion because the `torch.mps.BoolTensor` type does not exist.

**Comment by albanInE** [comment]
Same AssertionError occured.
how to fix this?

**Comment by ComplexImg** [comment]
I added this code into `/opt/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/structures/instance_data.py` file before assertion and it helped :)

```
    # Find this function where it fails and just cast tensor to CPU 
    def __getitem__(self, item: IndexType) -> 'InstanceData':

        # add this >
        if isinstance(item, torch.Tensor) and item.device != torch.device('cpu'):
            item = item.cpu()

        # Original code - don't change it
        assert isinstance(item, IndexType.__args__)
        if isinstance(item, list):
            item = np.array(item)
```
            
 Or just comment  `assert isinstance(item, IndexType.__args__)` line :)
