### ISSUE TITLE
'ConfigDict' object has no attribute 'model'

### ISSUE THREAD

**Issue by wuying-541** [open-mmlab/mmdetection#11872]
我在配置mmrotate时，运行demo中的image_demo.py时候，遇到了以下的报错：

Traceback (most recent call last):
  File "demo/image_demo.py", line 45, in <module>                                                  
    main(args)                                                                                     
  File "demo/image_demo.py", line 30, in main                                                      
    model = init_detector(args.config, args.checkpoint, device=args.device)                        
  File "d:\mmrotate\mmdetection-2.25.1\mmdet\apis\inference.py", line 39, in init_detector         
    if 'pretrained' in config.model:                                                               
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)                                                           
  File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 50, in __getattr__
    raise ex
**AttributeError: 'ConfigDict' object has no attribute 'model'**

mmdet：v2.25.1
mmrotate：v0.3.3
mmcv-full: v1.6.0

望告知 qaq

**Comment by love-whut** [comment]
> 我在配置mmrotate时，运行demo中的image_demo.py时候，遇到了以下的报错：
> 
> Traceback (most recent call last): File "demo/image_demo.py", line 45, in main(args) File "demo/image_demo.py", line 30, in main model = init_detector(args.config, args.checkpoint, device=args.device) File "d:\mmrotate\mmdetection-2.25.1\mmdet\apis\inference.py", line 39, in init_detector if 'pretrained' in config.model: File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 519, in **getattr** return getattr(self._cfg_dict, name) File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 50, in **getattr** raise ex **AttributeError: 'ConfigDict' object has no attribute 'model'**
> 
> mmdet：v2.25.1 mmrotate：v0.3.3 mmcv-full: v1.6.0
> 
> 望告知 qaq

你好，请问你解决了吗，我报了相同的错误

**Comment by wuying-541** [comment]
> > 我在配置mmrotate时，运行demo中的image_demo.py时候，遇到了以下的报错：
> > Traceback (most recent call last): File "demo/image_demo.py", line 45, in main(args) File "demo/image_demo.py", line 30, in main model = init_detector(args.config, args.checkpoint, device=args.device) File "d:\mmrotate\mmdetection-2.25.1\mmdet\apis\inference.py", line 39, in init_detector if 'pretrained' in config.model: File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 519, in **getattr** return getattr(self._cfg_dict, name) File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 50, in **getattr** raise ex **AttributeError: 'ConfigDict' object has no attribute 'model'**
> > mmdet：v2.25.1 mmrotate：v0.3.3 mmcv-full: v1.6.0
> > 望告知 qaq
> 
> 你好，请问你解决了吗，我报了相同的错误

你好，时间太久应该是解决了 具体我也忘记了 环境的配置我是在b站看的这个视频：
【旋转目标检测mmrotate零基础入门教程】 https://www.bilibili.com/video/BV1N94y1A7DZ/?share_source=copy_web&vd_source=279c39b25c6851e98f90ff6735e9044c
希望对你有帮助

**Comment by love-whut** [comment]
感谢感谢



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 27, 2025 17:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection] 'ConfigDict' object has no attribute'model' (Issue #11872)


 wuying-541 left a comment (open-mmlab/mmdetection#11872)
   
我在配置mmrotate时，运行demo中的image_demo.py时候，遇到了以下的报错：
 Traceback (most recent call last): File "demo/image_demo.py", line 45, in main(args) File "demo/image_demo.py", line 30, in main model = init_detector(args.config, args.checkpoint, device=args.device) File "d:\mmrotate\mmdetection-2.25.1\mmdet\apis\inference.py", line 39, in init_detector if 'pretrained' in config.model: File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 519, in getattr return getattr(self._cfg_dict, name) File "D:\anaconda\envs\mmrotate\lib\site-packages\mmcv\utils\config.py", line 50, in getattr raise ex AttributeError: 'ConfigDict' object has no attribute 'model'
 mmdet：v2.25.1 mmrotate：v0.3.3 mmcv-full: v1.6.0
 望告知 qaq
  
你好，请问你解决了吗，我报了相同的错误
  
你好，时间太久应该是解决了 具体我也忘记了 环境的配置我是在b站看的这个视频：
 【旋转目标检测mmrotate零基础入门教程】 https://www.bilibili.com/video/BV1N94y1A7DZ/?share_source=copy_web&amp;vd_source=279c39b25c6851e98f90ff6735e9044c
 希望对你有帮助
