### ISSUE TITLE
TypeError: forward() missing 2 required positional arguments: 'init_bboxes' and 'init_t'   Diffision DET

### ISSUE THREAD

**Issue by yihaohu0118** [open-mmlab/mmdetection#11889]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by merlinxu-zz** [comment]
I had the same problem when I run "tools/analysis_tools/get_flops.py". Here is the error trackback:

`Traceback (most recent call last):
  File "/workspace/user_code/mmdetection_v3.1.0/tools/analysis_tools/get_flops.py", line 139, in <module>
    main()
  File "/workspace/user_code/mmdetection_v3.1.0/tools/analysis_tools/get_flops.py", line 119, in main
    result = inference(args, logger)
  File "/workspace/user_code/mmdetection_v3.1.0/tools/analysis_tools/get_flops.py", line 97, in inference
    outputs = get_model_complexity_info(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/mmengine/analysis/print_helper.py", line 748, in get_model_complexity_info
    flops = flop_handler.total()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/mmengine/analysis/jit_analysis.py", line 268, in total
    stats = self._analyze()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/mmengine/analysis/jit_analysis.py", line 570, in _analyze
    graph = _get_scoped_trace_graph(self._model, self._inputs,
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/mmengine/analysis/jit_analysis.py", line 194, in _get_scoped_trace_graph
    graph, _ = _get_trace_graph(module, inputs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/workspace/user_code/mmdetection/mmdet/models/detectors/base.py", line 96, in forward
    return self._forward(inputs, data_samples)
  File "/workspace/user_code/mmdetection/mmdet/models/detectors/single_stage.py", line 133, in _forward
    results = self.bbox_head.forward(x)
TypeError: DynamicDiffusionDetHead.forward() missing 2 required positional arguments: 'init_bboxes' and 'init_t'`

**Comment by yihaohu0118** [comment]
the same problem sir
