### ISSUE TITLE
CLASSES in custom dataset

### ISSUE THREAD

**Issue by flyfj** [open-mmlab/mmdetection#1190]
Is there a way to specify classes for custom dataset in config file? 
the current way is to create a new data class inherited from CustomDataset and set CLASSES in the py file to register. This seems to be cumbersome when working with multiple datasets.

**Comment by zzzfinal0** [comment]
Yes,we did it. Just add a custom dataset class and paste it.

**Comment by flyfj** [comment]
yeah, that's what i did, just wondering if can do the same without creating a new dataset class.

**Comment by zzzfinal0** [comment]
@flyfj Yes. 
CLASSES=self.loadclasses(cfg.popup['cfgfile_path'])
def loadclasses:
#your  codes

**Comment by bond9779** [comment]
How to register custom dataset classes?

python3 tools/train.py /mmdetection_train/configs/htc/htc_without_semantic_r50_fpn_1x.py
2019-10-16 18:50:23,132 - INFO - Distributed training: False
2019-10-16 18:50:23,586 - INFO - load model from: torchvision://resnet50
2019-10-16 18:50:23,716 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 86, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/MM_Detection/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/MM_Detection/mmdetection/mmdet/utils/registry.py", line 67, in build_from_cfg
    obj_type, registry.name))
KeyError: 'MyDataset is not in the dataset registry'

**Comment by bond9779** [comment]
@hellock can you please help?
