### ISSUE TITLE
infer bug

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#11905]
I customized a voc dataset and trained it normally：

```
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/RSOD-Dataset/'

classes = ('aircraft', 'oiltank', 'overpass', 'playground')
# Example to use different file client
# Method 1: simply set the data root and let the file I/O module
# automatically Infer from prefix (not support LMDB and Memcache yet)

# data_root = 's3://openmmlab/datasets/detection/segmentation/VOCdevkit/'

# Method 2: Use `backend_args`, `file_client_args` in versions before 3.0.0rc6
# backend_args = dict(
#     backend='petrel',
#     path_mapping=dict({
#         './data/': 's3://openmmlab/datasets/segmentation/',
#         'data/': 's3://openmmlab/datasets/segmentation/'
#     }))
backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=(1000, 600), keep_ratio=True),
    # avoid bboxes being resized
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor'))
]
train_dataloader = dict(
    batch_size=8,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type='ConcatDataset',
            # VOCDataset will add different `dataset_type` in dataset.metainfo,
            # which will get error if using ConcatDataset. Adding
            # `ignore_keys` can avoid this error.
            ignore_keys=['dataset_type'],
            datasets=[
                dict(
                    type=dataset_type,
                    metainfo=dict(classes=classes),
                    data_root=data_root,
                    ann_file='aircraft/train.txt',
                    data_prefix=dict(sub_data_root='aircraft/'),
                    filter_cfg=dict(
                        filter_empty_gt=True, min_size=32, bbox_min_size=32),
                    pipeline=train_pipeline,
                    backend_args=backend_args),
                dict(
                    type=dataset_type,
                    metainfo=dict(classes=classes),
                    data_root=data_root,
                    ann_file='oiltank/train.txt',
                    data_prefix=dict(sub_data_root='oiltank/'),
                    filter_cfg=dict(
                        filter_empty_gt=True, min_size=32, bbox_min_size=32),
                    pipeline=train_pipeline,
                    backend_args=backend_args),
                dict(
                    type=dataset_type,
                    metainfo=dict(classes=classes),
                    data_root=data_root,
                    ann_file='overpass/train.txt',
                    data_prefix=dict(sub_data_root='overpass/'),
                    filter_cfg=dict(
                        filter_empty_gt=True, min_size=32, bbox_min_size=32),
                    pipeline=train_pipeline,
                    backend_args=backend_args),
                dict(
                    type=dataset_type,
                    metainfo=dict(classes=classes),
                    data_root=data_root,
                    ann_file='playground/train.txt',
                    data_prefix=dict(sub_data_root='playground/'),
                    filter_cfg=dict(
                        filter_empty_gt=True, min_size=32, bbox_min_size=32),
                    pipeline=train_pipeline,
                    backend_args=backend_args)
            ])))

val_dataloader = dict(
    batch_size=1,
    num_workers=8,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ConcatDataset',
        # VOCDataset will add different `dataset_type` in dataset.metainfo,
        # which will get error if using ConcatDataset. Adding
        # `ignore_keys` can avoid this error.
        ignore_keys=['dataset_type'],
        datasets=[
            dict(
                type=dataset_type,
                metainfo=dict(classes=classes),
                data_root=data_root,
                ann_file='aircraft/train.txt',
                data_prefix=dict(sub_data_root='aircraft/'),
                test_mode=True,
                pipeline=test_pipeline,
                backend_args=backend_args),
            dict(
                type=dataset_type,
                metainfo=dict(classes=classes),
                data_root=data_root,
                ann_file='oiltank/train.txt',
                data_prefix=dict(sub_data_root='oiltank/'),
                test_mode=True,
                pipeline=test_pipeline,
                backend_args=backend_args),
            dict(
                type=dataset_type,
                metainfo=dict(classes=classes),
                data_root=data_root,
                ann_file='overpass/train.txt',
                data_prefix=dict(sub_data_root='overpass/'),
                test_mode=True,
                pipeline=test_pipeline,
                backend_args=backend_args),
            dict(
                type=dataset_type,
                metainfo=dict(classes=classes),
                data_root=data_root,
                ann_file='playground/train.txt',
                data_prefix=dict(sub_data_root='playground/'),
                test_mode=True,
                pipeline=test_pipeline,
                backend_args=backend_args)
        ]))
test_dataloader = val_dataloader

# Pascal VOC2007 uses `11points` as default evaluate mode, while PASCAL
# VOC2012 defaults to use 'area'.
val_evaluator = dict(type='VOCMetric', metric='mAP', eval_mode='11points')
test_evaluator = val_evaluator

```

But the single reasoning is wrong：

```
python demo/image_demo.py data/RSOD-Dataset/playground/JPEGImages/playground_108.jpg work_dirs/cascade-rcnn_r50_fpn_1x_rsod/cascade-rcnn_r50_fpn_1x_rsod.py --weights work_dirs/cascade-rcnn_r50_fpn_1x_rsod/epoch_12.pth
Loads checkpoint by local backend from path: work_dirs/cascade-rcnn_r50_fpn_1x_rsod/epoch_12.pth
Traceback (most recent call last):
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 109, in __getattr__
    value = super().__getattr__(name)
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 138, in __getitem__
    return self.build_lazy(super().__getitem__(key))
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 105, in __missing__
    raise KeyError(name)
KeyError: 'pipeline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/image_demo.py", line 192, in <module>
    main()
  File "demo/image_demo.py", line 179, in main
    inferencer = DetInferencer(**init_args)
  File "/home/guozebin/work_code/chenzhao/mmdetection/mmdet/apis/det_inferencer.py", line 100, in __init__
    model=model, weights=weights, device=device, scope=scope)
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/infer/infer.py", line 181, in __init__
    self.pipeline = self._init_pipeline(cfg)
  File "/home/guozebin/work_code/chenzhao/mmdetection/mmdet/apis/det_inferencer.py", line 161, in _init_pipeline
    pipeline_cfg = cfg.test_dataloader.dataset.pipeline
  File "/home/guozebin/miniconda3/envs/mmyolo/lib/python3.7/site-packages/mmengine/config/config.py", line 113, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
```

I think this is a bug, can anyone help me?

**Comment by Bin-ze** [comment]
@ZwwWayne Excuse me, could you spare some time to answer this?
