### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'times'

### ISSUE THREAD

**Issue by ArpanGyawali** [open-mmlab/mmdetection#11935]
I am working on LVO detection (A single class detection where dataset have both positive(with 1 to 2 boxes) and negative(without any boxes) sample images. I am using faster rcnn model.
My config is comething like this:
```
model = 'faster-rcnn_r101_fpn_ms'
num_epochs = 30
base_lr = 0.005

config_lvo = f"""
# Inherit and overwrite part of the config based on this config
_base_ = './faster-rcnn_r101_fpn_ms-3x_coco.py'

work_dir = "../../checkpoints/{model}/run1"
data_root = '../../LVO-data'  # dataset root

train_ann_file = 'train/_annotations.coco.json'
train_data_prefix = 'train/'

val_ann_file = 'valid/_annotations.coco.json'
val_data_prefix = 'valid/'

test_ann_file = 'test/_annotations.coco.json'  # Changed from val_ann_file
test_data_prefix = 'test/'  # Changed from val_data_prefix

dataset_type="CocoDataset"
class_name = ("lvo", )
num_classes = 1
max_epochs = {num_epochs}
stage2_num_epochs = max_epochs // 3
base_lr = {base_lr}

metainfo = dict(classes=("lvo", ), palette=[
        (220, 20, 60),
    ])  # Corrected missing parenthesis

# Data related parameters
img_scale = (512, 512)  # width, height
random_resize_ratio_range = (0.8, 1.2)
pad_val = 0.0
mosaic_max_cached_images = 50
train_batch_size_per_gpu = 4
train_num_workers = 2
persistent_workers = True
val_batch_size_per_gpu = 4
val_num_workers = 2

model_test_cfg = dict(
    nms_pre=20,
    score_thr=0.001,  # Threshold to filter out boxes.
    nms=dict(type='nms', iou_threshold=0.65),  # NMS type and threshold
    max_per_img=2)  # Max number of detections of each image

# define data augmentation
albu_train_transforms = [
    dict(
        type='ShiftScaleRotate',
        shift_limit=0,
        scale_limit=0,
        rotate_limit=15,
        interpolation=1,
        p=0.3),
    dict(
        type='OneOf',
        transforms=[
            dict(type='MedianBlur', blur_limit=3, p=0.5),
            dict(type='GaussNoise', var_limit=0.2, p=0.5),
        ],
        p=0.3),
]

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Mosaic',
        img_scale=img_scale,
        use_cached=True,
        max_cached_images=mosaic_max_cached_images,
        pad_val=pad_val),
    dict(
        type='RandomResize',
        scale=img_scale,
        ratio_range=random_resize_ratio_range,
        keep_ratio=True),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_bboxes_labels', 'gt_ignore_flags'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(
            img='image',
            gt_masks='masks',
            gt_bboxes='bboxes'),
        skip_img_without_anno=False),
    dict(type='RandomCrop', crop_size=img_scale),
    dict(type='RandomFlip', direction='horizontal', prob=0.3),
    dict(type='PackDetInputs')
]

train_pipeline_stage2 = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='RandomResize',
        scale=img_scale,
        ratio_range=random_resize_ratio_range,
        keep_ratio=True),
    dict(type='RandomFlip', prob=0.4),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=None),
    dict(
        type='RandomResize',
        scale=img_scale,
        ratio_range=random_resize_ratio_range,
        keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='mmdet.PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'pad_param'))
]

train_dataloader = dict(
    batch_size=train_batch_size_per_gpu,
    num_workers=train_num_workers,
    persistent_workers=True,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        metainfo=metainfo,
        pipeline=train_pipeline,
        data_prefix=dict(img='train/'),
        filter_empty_gt=False,
        ann_file=data_root + '/' + train_ann_file,
        backend_args=None))

val_dataloader = dict(
    batch_size=val_batch_size_per_gpu,
    num_workers=val_num_workers,
    persistent_workers=True,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        metainfo=metainfo,
        pipeline=test_pipeline,
        data_prefix=dict(img='valid/'),
        filter_empty_gt=False,
        ann_file=data_root + '/' + val_ann_file,
        backend_args=None))

test_dataloader = dict(
    batch_size=val_batch_size_per_gpu,
    num_workers=val_num_workers,
    persistent_workers=True,
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        metainfo=metainfo,
        pipeline=test_pipeline,
        data_prefix=dict(img='test/'),
        test_mode=True,  # Added missing comma
        ann_file=data_root + '/' + test_ann_file,
        backend_args=None))

val_evaluator = dict(ann_file=data_root + '/' + val_ann_file)

test_evaluator = dict(ann_file=data_root + '/' + test_ann_file)

model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))

# learning rate
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=1.0e-5,
        by_epoch=False,
        begin=0,
        end=10),
    dict(
        type='CosineAnnealingLR',
        eta_min=base_lr * 0.05,
        begin=max_epochs // 2,
        end=max_epochs,
        T_max=max_epochs // 2,
        by_epoch=True,
        convert_to_iter_based=True),
]

# optimizer
optim_wrapper = dict(
    _delete_=True,
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=base_lr, weight_decay=0.05),
    paramwise_cfg=dict(
        norm_decay_mult=0, bias_decay_mult=0, bypass_duplicate=True))

default_hooks = dict(
    checkpoint=dict(
        interval=5,
        max_keep_ckpts=2,
        save_best='auto'),
    logger=dict(type='LoggerHook', interval=5))

custom_hooks = [
    dict(
        type='PipelineSwitchHook',
        switch_epoch=max_epochs - stage2_num_epochs,
        switch_pipeline=train_pipeline_stage2)
]

# load COCO pre-trained weight
load_from = './checkpoints/faster_rcnn_r101_fpn_mstrain_3x_coco_20210524_110822-4d4d2ca8.pth'

train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=max_epochs, val_interval=1)
visualizer = dict(vis_backends=[dict(type='LocalVisBackend'), dict(type='TensorboardVisBackend')])
"""

config = f"./configs/faster_rcnn/{model}_lvo.py"
with open(config, 'w') as f:
    f.write(config_lvo)

print(config_lvo)
```

But while running train script or even browse_aug script, I am facing this error:
!python tools/train.py {config}
```
Traceback (most recent call last):
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdetection/tools/train.py", line 121, in <module>
    main()
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdetection/tools/train.py", line 117, in main
    runner.train()
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/runner/runner.py", line 1728, in train
    self._train_loop = self.build_train_loop(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/runner/runner.py", line 1520, in build_train_loop
    loop = LOOPS.build(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/runner/runner.py", line 1370, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdet_env/lib64/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/data/gpfs/projects/punim0401/Arpan/LVO_detection/mmDetection/mmdetection/mmdet/datasets/base_det_dataset.py", line 51, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'times'
```

I have checked the previous similar issue but i havent used dataset type as RepeatedDataset and i have not used any times argument in dataloader. I couldnt solve the problem. 

My env:
- torch==2.4.0+cu118
- python==3.9.13
- nvcc --version==11.8
- mmcv==2.1.0
- mmengine==0.10.4
- git+https://github.com/open-mmlab/mmdetection.git@cfd5d3a985b0249de009b67d04f37263e11cdf3d#egg=mmdet

Please help me and if i need to provide more information that i will do that.

Thanks on advance

**Comment by ArpanGyawali** [comment]
@hhaAndroid could you please help?

**Comment by ArpanGyawali** [comment]
I found the mistake

**Comment by saraalemadi** [comment]
Hi @ArpanGyawali,

I am facing the same issue and wondering how did you resolve it?

Thanks.
