### ISSUE TITLE
加载grounding-dino大模型进行推理时，一张图需要30s也太慢了吧

### ISSUE THREAD

**Issue by jamesbondzhou** [open-mmlab/mmdetection#11969]
您好，我使用grounding-dino训练了我自己的烟雾数据（用的是configs/grounding_dino/grounding_dino_swin-t_finetune_16xb2_1x_coco.py），进行推理的时候单张图耗时32s，是不是太慢了啊
推理的时候出现nltk的报错，可是这些包我都已经拉到本地的nltk下了，他还是自己去网上找，请问是不是这里大量耗时了？
[nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno -2] Name or service not known>
noun_phrases: ['smoke']
[nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or
[nltk_data]     service not known>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno -2] Name or service not known>
noun_phrases: ['smoke']
Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
Total inference time cost 3261.86s,Average inference time cost 32.62s

**Comment by xuans29** [comment]
我微调groundingdino的代码总是会报错，请问一下您遇到过如下问题吗？
tools/train，test报的都是这个问题
Traceback (most recent call last):
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf/pytree/pytree_utils.py", line 113, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 188, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 157, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 230, in addtoken
    return self._addtoken(ilabel, type, value, context)
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/parse.py", line 313, in _addtoken
    raise ParseError('bad input', type, value, context)
yapf_third_party._ylib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (1, 14))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 198, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/site-packages/yapf/pytree/pytree_utils.py", line 116, in ParseCodeToTree
    ast.parse(code)
  File "/home/dell/Software/Anaconda3/envs/mmdet/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    AutoTokenizer=<class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
                  ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

**Comment by shelly-angel** [comment]
> 您好，我使用grounding-dino训练了我自己的烟雾数据（用的是configs/grounding_dino/grounding_dino_swin-t_finetune_16xb2_1x_coco.py），进行推理的时候单张图耗时32s，是不是太慢了啊 推理的时候出现nltk的报错，可是这些包我都已经拉到本地的nltk下了，他还是自己去网上找，请问是不是这里大量耗时了？ [nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or [nltk_data] service not known> [nltk_data] Error loading averaged_perceptron_tagger: <urlopen error [nltk_data] [Errno -2] Name or service not known> noun_phrases: ['smoke'] [nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or [nltk_data] service not known> [nltk_data] Error loading averaged_perceptron_tagger: <urlopen error [nltk_data] [Errno -2] Name or service not known> noun_phrases: ['smoke'] Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Total inference time cost 3261.86s,Average inference time cost 32.62s

请问最后有解决吗？我这边用它推理也很慢。

**Comment by shelly-angel** [comment]
> > 您好，我使用grounding-dino训练了我自己的烟雾数据（用的是configs/grounding_dino/grounding_dino_swin-t_finetune_16xb2_1x_coco.py），进行推理的时候单张图耗时32s，是不是太慢了啊 推理的时候出现nltk的报错，可是这些包我都已经拉到本地的nltk下了，他还是自己去网上找，请问是不是这里大量耗时了？ [nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or [nltk_data] service not known> [nltk_data] Error loading averaged_perceptron_tagger: <urlopen error [nltk_data] [Errno -2] Name or service not known> noun_phrases: ['smoke'] [nltk_data] Error loading punkt: <urlopen error [Errno -2] Name or [nltk_data] service not known> [nltk_data] Error loading averaged_perceptron_tagger: <urlopen error [nltk_data] [Errno -2] Name or service not known> noun_phrases: ['smoke'] Inference ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Total inference time cost 3261.86s,Average inference time cost 32.62s
> 
> 请问最后有解决吗？我这边用它推理也很慢。

已解决,推理慢的原因是联网下载那个nltk包。注释掉mmdet/models/detector/glip.py 里面 try: import nltk ...... exception ....那一块，替换为import nltk，即可。
