### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'groups'

### ISSUE THREAD

**Issue by jianpingZhonggit** [open-mmlab/mmdetection#1209]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I train my dataset with faster_rcnn_x101_64x4d_fpn_1x.I got the error:
TypeError: __init__() got an unexpected keyword argument 'groups'.Before that I train my dataset with faster_rcnn_r101_fpn_1x,it works ok.
**Reproduction**
1. What command or script did you run?
python toos/train configs/faster_rcnn_x101_64x4d_fpn_1x.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I have,I change the num_classes and ann_file in the config file,and I have change the class type in mmdet/evalution/class_names.py and mmdet/datasets/voc.py
3. What dataset did you use?
VOCdevkit
**Environment**
 - OS:  Ubuntu 16.04.6
 - GCC:5.4.0
 - PyTorch version:1.1.0
- How you installed PyTorch :pip
- GPU model:RTX2080ti V
- CUDA and CUDNN version:cuda-10.1 cudnn-7.5.4

**Error traceback**
```
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 73, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/detectors/faster_rcnn.py", line 27, in __init__
    pretrained=pretrained)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/detectors/two_stage.py", line 28, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 36, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/backbones/resnext.py", line 222, in __init__
    gcb=gcb)
  File "/home/zhongjianping/桌面/paper/detection_cvpr2019/1901.03278/mmdetection-master/mmdet/models/backbones/resnext.py", line 138, in make_res_layer
    gcb=gcb))
TypeError: __init__() got multiple values for argument 'groups'
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
I cannot reproduce your error. Maybe you just made wrong modifications to the config file.

**Comment by jianpingZhonggit** [comment]
> I cannot reproduce your error. Maybe you just made wrong modifications to the config file.

Thank you very much!I have solved the problem,I found that my version was old,so when I updated my code,It works well.
