### ISSUE TITLE
An error  always occurs when I using faster rcnn ,cascade-rcnn or cascade-maskrcnn...

### ISSUE THREAD

**Issue by JiaquanYe** [open-mmlab/mmdetection#1214]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I want to change my own dataset and it has 20 classes, so I have create mydataset.py and modify some dataset setting according to GET_STARTED.md. 
But I have met a strange situation, I have modify num_class=21 in  faster-rcnn config.py, it raise an error : RuntimeError: copy_if failed to synchronize: device-side assert triggered.
When I change the num_class=81, it is ok and no error.
And I check my json file(my own dataset) in 'data/coco/annotations/instances_train2017.json', the classes is 20.
The most strange is, when I use config file 'retinanet_x101_64x4d_fpn_1x.py' to a retinanet model, and I also change the num classes to 21, it is OK and no error.
So, I think there are maybe some bug in faster-rcnn config?
I have train the model in a single GPU,no server,  RTX2080Ti, CUDA9.0, cudnn 7.3.1.

**Reproduction**
1. What command or script did you run?
python tools/train.py configs/.../faster_rcnn_r50_fpn_1x.py

A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I have only modify the dataset part. I create mydataset.py and inherit 'class CocoDataset' like this:
from .coco import CocoDataset
from .registry import DATASETS

@DATASETS.register_module
class GDDataset(CocoDataset):

    CLASSES = ('1', '2', '3', '4', '5', '6', '7', \
               '8', '9', '10', '11', '12', '13', '14', \
               '15', '16', '17', '18', '19', '20')

and add GDDataset to __all__  of __init__.py.


3. What dataset did you use?
My own dataset with COCO format.


**Environment**
 - OS: [e.g., Ubuntu 18.04]
 - GCC [e.g., 5.5.0]
 - PyTorch version [e.g., 1.2.0]
- How you installed PyTorch [conda]
- GPU model [2080 Ti]
- CUDA and CUDNN version 
CUDA 9.0 and CUDNN 7.3.1
- [optional] Other information that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
2019-08-19 17:11:32,384 - INFO - Distributed training: False
2019-08-19 17:11:32,616 - INFO - load model from: torchvision://resnet50
2019-08-19 17:11:32,744 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
2019-08-19 17:11:35,154 - INFO - Start running, host: lab404@LAB404, work_dir: /home/lab404/mmdetection/work_dirs/tianchi_gd/faster_rcnn_r50_fpn_1x
2019-08-19 17:11:35,154 - INFO - workflow: [('train', 1)], max: 12 epochs
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [512,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home/lab404/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/lab404/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/lab404/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lab404/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/lab404/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/lab404/mmdetection/mmdet/models/detectors/two_stage.py", line 183, in forward_train
    *bbox_targets)
  File "/home/lab404/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/lab404/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 123, in loss
    4)[pos_inds, labels[pos_inds]]
RuntimeError: copy_if failed to synchronize: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1565272271120/work/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fe07b870e37 in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x12e14 (0x7fe07baa8e14 in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x165bf (0x7fe07baac5bf in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x74 (0x7fe07b85bfa4 in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x1bb014 (0x7fe0ac95c014 in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x40142b (0x7fe0acba242b in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x401461 (0x7fe0acba2461 in /home/lab404/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #26: __libc_start_main + 0xe7 (0x7fe0ba61cb97 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

**Comment by qa8306202** [comment]
Hi, how did you solve the problem?I met it too.

**Comment by ccl-1** [comment]
> Hi, how did you solve the problem?I met it too.

I also met this problem.Did you fogure  it out?
