### ISSUE TITLE
Socket error when running train.py from ssh connection

### ISSUE THREAD

**Issue by lee4138** [open-mmlab/mmdetection#1220]
Hi all, 

I am trying to make mmdetection run on a remote server which I conneted to via a ssh connection. Everything worked fine but when I try to run tools/train.py it get stuck at the piint where the checkpoint file is being downloaded with following errors:
(open-mmlab) vlad@ubuntu-16:~/mmdetection$ python tools/train.py /home/vlad/mmdetection/configs/cascade_rcnn_r50_fpn_1x.py 
2019-08-20 13:11:35,226 - INFO - Distributed training: False
2019-08-20 13:11:35,785 - INFO - load model from: torchvision://resnet50
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/vlad/.cache/torch/checkpoints/resnet50-19c8e357.pth
Traceback (most recent call last):
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1406, in connect
    super().connect()
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
**socket.gaierror: [Errno -2] Name or service not known**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 84, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/vlad/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/vlad/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/vlad/mmdetection/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
  File "/home/vlad/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 86, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/vlad/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 94, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/vlad/mmdetection/mmdet/models/backbones/resnet.py", line 482, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 163, in load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 115, in load_url_dist
    checkpoint = model_zoo.load_url(url)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/hub.py", line 462, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/hub.py", line 372, in _download_url_to_file
    u = urlopen(url)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/vlad/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

Seems that the socket connection to that url is not working.
When I copy paste the URL https://download.pytorch.org/models/resnet50-19c8e357.pth to my browser I can download it. 

Thanks for help!

**Comment by hellock** [comment]
You may check if your remote server can access the internet.
