### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by ZenFSheng** [open-mmlab/mmdetection#1253]
OS & Env：
Ubuntu 16.04.6
64G memory
4*GTX1080Ti（10G）
Python 3.7.3
GCC 5.4.0
PyTorch  1.1.0 （install with pip）
CUDA 10.1

Excuse me, I use custom dataset to train.
when I run the command `python tools/train.py configs/cascade_rcnn_r101_fpn_1x.py`  got an error below.
```
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/les/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/les/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/les/.local/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/custom.py", line 145, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/custom.py", line 158, in prepare_train_img
    return self.pipeline(results)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/transforms.py", line 152, in __call__
    self._resize_bboxes(results)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/transforms.py", line 125, in _resize_bboxes
    bboxes = results[key] * results['scale_factor']
TypeError: can't multiply sequence by non-int of type 'float'
```
I think it's because that my annotation is json file, the bboxes and labels are not numpy array. So I modified function `load_annotations` in `custom.py`.
```
    def load_annotations(self, ann_file):
        if ann_file.endswith('.json'):
            print('Using json format annotation.')
            ann = mmcv.load(ann_file)
            for item in ann:
                item['ann']['bboxes'] = np.array(item['ann']['bboxes'], dtype=np.float32)
                item['ann']['labels'] = np.array(item['ann']['labels'], dtype=np.int64)
            return ann
        else:
            print('Using pickle format annotation.')
            return mmcv.load(ann_file) 
```

Then I run command `python tools/train.py configs/cascade_rcnn_r101_fpn_1x.py` again. The error becomes as follows: 

```
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/les/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/les/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/les/.local/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/les/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/custom.py", line 158, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/custom.py", line 171, in prepare_train_img
    return self.pipeline(results)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/transforms.py", line 152, in __call__
    self._resize_bboxes(results)
  File "/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/sheng_zf/mmdetection/mmdet/datasets/pipelines/transforms.py", line 125, in _resize_bboxes
    bboxes = results[key] * results['scale_factor']
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
I paste one slice of my annotations, hope it will be helpful for analysis.

```
   {
      "filename": "000002b66c9c498e.jpg",
      "width": 1024,
      "height": 1024,
      "ann": {
         "bboxes": [
            [
               974.719970703125,
               277.6135559082031,
               1023.3599853515625,
               736.7802734375
            ],
            [
               797.4400024414062,
               280.4951171875,
               935.6799926757812,
               549.4630126953125
            ],
            [
               321.2799987792969,
               94.13836669921875,
               419.8399963378906,
               294.90484619140625
            ],
            [
               456.32000732421875,
               158.49880981445312,
               688.6400146484375,
               205.5679931640625
            ],
            [
               1015.0399780273438,
               178.67161560058594,
               1023.3599853515625,
               199.804931640625
            ],
            [
               580.47998046875,
               66.2814712524414,
               948.47998046875,
               1009.59130859375
            ],
            [
               816.0,
               160.4198455810547,
               974.719970703125,
               210.37158203125
            ],
            [
               807.6799926757812,
               203.64697265625,
               855.0399780273438,
               278.5740661621094
            ],
            [
               712.3200073242188,
               121.03577423095703,
               805.1199951171875,
               304.50994873046875
            ],
            [
               0.0,
               109.50860595703125,
               39.040000915527344,
               223.8197784423828
            ],
            [
               60.15999984741211,
               146.97164916992188,
               230.39999389648438,
               192.11981201171875
            ],
            [
               237.44000244140625,
               145.05062866210938,
               289.9200134277344,
               243.0320587158203
            ],
            [
               21.760000228881836,
               161.38035583496094,
               126.72000122070312,
               324.6827392578125
            ],
            [
               452.4800109863281,
               172.90853881835938,
               478.7200012207031,
               249.75564575195312
            ]
         ],
         "labels": [
            339,
            339,
            327,
            327,
            327,
            199,
            327,
            327,
            327,
            327,
            327,
            327,
            339,
            339
         ],
         "bboxes_ignore": null,
         "labels_ignore": null
      }
   },
```

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by ZenFSheng** [comment]
> Please follow the `Error report` issue template.

Sorry, I've change the content of error report. Hoping that it is clear for your analysis. 
And looking forward for your reply. 🙂

**Comment by hellock** [comment]
What's your config file?

**Comment by ZenFSheng** [comment]
> Please follow the `Error report` issue template.

Sorry to bother you again, just hope that you’ll recheck my issue~ 
The issue has puzzled me for Three days..😂 

> What's your config file?

cascade_rcnn_r101_fpn_1x.py
details are listed below:
```
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='torchvision://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
    ])
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100),
    keep_all_stages=False)
# dataset settings
dataset_type = 'CustomDataset'
data_root = '/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 768), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 768),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'level_1_train_trans.pickle',
        img_prefix=data_root + 'train_all/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/cascade_rcnn_r101_fpn_1x'
load_from = None
resume_from = None
workflow = [('train', 1)]
```

**Comment by ZenFSheng** [comment]
> What's your config file?
cascade_rcnn_r101_fpn_1x.py
```
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='torchvision://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
    ])
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100),
    keep_all_stages=False)
# dataset settings
dataset_type = 'CustomDataset'
data_root = '/media/les/30a40184-b063-4ff9-9cba-6afcca5669b8/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 768), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 768),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'level_1_train_trans.pickle',
        img_prefix=data_root + 'train_all/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/cascade_rcnn_r101_fpn_1x'
load_from = None
resume_from = None
workflow = [('train', 1)]
```

**Comment by artmortal93** [comment]
That's because they intorduce a bug in transforms.py in Resize Transform
 "bboxes = results[key] * results['scale_factor']"
and in LoadAnnotations:
 results['bbox_fields'].extend(['gt_bboxes',gt_bboxes_ignore'])
even bbox_ignore is not provided as None,it still provided as a key to multiply a scale factor
i still finding a way to monkey patching this issue.

**Comment by artmortal93** [comment]
For working around, you could just remove the 'gt_bboxes_ignore'  to see if it helps.

**Comment by hellock** [comment]
@artmortal93 That's it, thanks a lot! Feel free to open a PR to fix it if you would like to.

**Comment by ZenFSheng** [comment]
> For working around, you could just remove the 'gt_bboxes_ignore' to see if it helps.

Thanks for your sharing. Unfortunately, just removing the 'gt_bboxes_ignore' doesn't work. But you reminded me of the bug I hadn't noticed. Thanks anyway, I'll work on it too.

**Comment by artmortal93** [comment]
> @artmortal93 That's it, thanks a lot! Feel free to open a PR to fix it if you would like to.

Keep busying these days, may be you guys could fix it internally?

**Comment by hellock** [comment]
Sure, thanks!

**Comment by zhasulan** [comment]
> > For working around, you could just remove the 'gt_bboxes_ignore' to see if it helps.
> 
> Thanks for your sharing. Unfortunately, just removing the 'gt_bboxes_ignore' doesn't work. But you reminded me of the bug I hadn't noticed. Thanks anyway, I'll work on it too.

What bugs, i have the same problem. May u share solution?

**Comment by tom-melistas** [comment]
I still have the same bug, is there any solution?

**Comment by tom-melistas** [comment]
update: adding _if results[key] is None: continue_ in transforms.py and compose.py (before errors) solved it

**Comment by ZenFSheng** [comment]
> I still have the same bug, is there any solution?

Personal advise~  Using COCO format label is better，it won‘t raise any error.(If the content is correct~)

**Comment by kartikJ-9** [comment]
> update: adding _if results[key] is None: continue_ in transforms.py and compose.py (before errors) solved it

Can you elaborate on this? I am getting the same error. I cant solve this. results[key] is None: continue is already there in transforms.py

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?
