### ISSUE TITLE
Error when testing Cascade Mask R-CNN

### ISSUE THREAD

**Issue by jwwangchn** [open-mmlab/mmdetection#126]
I use the shell looks like `python tools/test.py CONFIG CHECKPOINT --gpus 1 --out PKL --eval bbox segm`.
> loading
 annotations into memory...
Done (t=0.94s)
creating index...
index created!
[                                                  ] 0/6056, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 85, in main
    outputs = single_test(model, data_loader, args.show)
  File "tools/test.py", line 20, in single_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/home/jwwangchn/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jwwangchn/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jwwangchn/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jwwangchn/.local/lib/python3.7/site-packages/mmdet-0.5.3+c9f2c56-py3.7.egg/mmdet/models/detectors/base.py", line 81, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/jwwangchn/.local/lib/python3.7/site-packages/mmdet-0.5.3+c9f2c56-py3.7.egg/mmdet/models/detectors/base.py", line 75, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/home/jwwangchn/.local/lib/python3.7/site-packages/mmdet-0.5.3+c9f2c56-py3.7.egg/mmdet/models/detectors/cascade_rcnn.py", line 306, in aug_test
    raise NotImplementedError
NotImplementedError

**Comment by jwwangchn** [comment]
@hellock Thank for your reply! Yes, I am trying to perform multi-scale testing, look forward your update.

**Comment by chenxu93** [comment]
I want to test my cascade_rcnn_x101_32x4d_fpn_1x model，and set flip=1.0 it has "NotImplementedError" error. so if it is can not do any augmentation in test and validate stage use cascade model?

**Comment by donglee-afar** [comment]
You can view the source code in mmdet/models/detectors/cascade_rcnn.py，and there is empty in the aug_test function. 
look forword somebody update it!

> I want to test my cascade_rcnn_x101_32x4d_fpn_1x model，and set flip=1.0 it has "NotImplementedError" error. so if it is can not do any augmentation in test and validate stage use cascade model?

**Comment by yutao007** [comment]
我也是遇到类似的问题。这个和框架本身封装的原因吗？（我这是用的mmdetection框架改得freeanchor,train没问题，test必须修改flip_ratio=0才可以）
