### ISSUE TITLE
Author, hello, when I ran the training program, there was such aerror.

### ISSUE THREAD

**Issue by DFLyan** [open-mmlab/mmdetection#1260]
(open-mmlab) syb@syb-G1-SNIPER-B7:/media/syb/file/mmdetection-master$ python train.py faster_rcnn_r101_fpn_1x.py 
2019-08-26 16:27:25,689 - INFO - Distributed training: False
2019-08-26 16:27:26,082 - INFO - load model from: torchvision://resnet101
2019-08-26 16:27:26,879 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.90s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 104, in main
    logger=logger)
  File "/media/syb/file/mmdetection-master/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/media/syb/file/mmdetection-master/mmdet/apis/train.py", line 201, in _non_dist_train
    model = MMDataParallel(model, device_ids=range(cfg.gpus)).cuda()
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 311, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/cuda/__init__.py", line 178, in _lazy_init
    _check_driver()
  File "/home/syb/anaconda2/envs/open-mmlab/lib/python3.7/site-packages/torch/cuda/__init__.py", line 108, in _check_driver
    of the CUDA driver.""".format(str(torch._C._cuda_getDriverVersion())))
AssertionError: 
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

**Comment by MPolaris** [comment]
maybe you should update your CUDA Edition
