### ISSUE TITLE
Multi-scales not supported in reppoints? Error when run "configs/reppoints/reppoints_moment_x101_dcn_fpn_2x_mt.py"

### ISSUE THREAD

**Issue by PumayHui** [open-mmlab/mmdetection#1275]
When I run "./tools/dist_train.sh configs/reppoints/reppoints_moment_x101_dcn_fpn_2x.py 2", everything is ok.
So maybe it not support multi-scales training?

**Reproduction**
1. What command or script did you run?
```
./tools/dist_train.sh configs/reppoints/reppoints_moment_x101_dcn_fpn_2x_mt.py 2

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
no
3. What dataset did you use?

**Environment**
 - OS: Ubuntu 18.04
 - GCC 7.3.0
 - PyTorch version 1.2.0
- How you installed PyTorch conda
- GPU model 1080Ti
- CUDA and CUDNN version 10.0

**Error traceback**
If applicable, paste the error trackback here.
```
loading annotations into memory...
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
Done (t=0.26s)
creating index...
index created!
2019-08-27 15:44:56,470 - INFO - Start running, host: dl@DL, work_dir: /home/mmdetection/work_dirs/reppoints_moment_x101_dcn_fpn_2x_mt
2019-08-27 15:44:56,470 - INFO - workflow: [('train', 1)], max: 24 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/anaconda3/envs/0813-open-mmlab/lib/python3.6/site-packages/mmcv-0.2.12-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda3/envs/0813-open-mmlab/lib/python3.6/site-packages/mmcv-0.2.12-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 150, in __call__
    self._random_scale(results)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 98, in _random_scale
    scale, scale_idx = self.random_sample(self.img_scale)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 70, in random_sample
    assert mmcv.is_list_of(img_scales, tuple) and len(img_scales) == 2
AssertionError

Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/home/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home//anaconda3/envs/0813-open-mmlab/lib/python3.6/site-packages/mmcv-0.2.12-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home//anaconda3/envs/0813-open-mmlab/lib/python3.6/site-packages/mmcv-0.2.12-py3.6-linux-x86_64.egg/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home//anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home//anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 150, in __call__
    self._random_scale(results)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 98, in _random_scale
    scale, scale_idx = self.random_sample(self.img_scale)
  File "/home/mmdetection/mmdet/datasets/pipelines/transforms.py", line 70, in random_sample
    assert mmcv.is_list_of(img_scales, tuple) and len(img_scales) == 2
AssertionError

Traceback (most recent call last):
  File "/home/anaconda3/envs/0813-open-mmlab/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/0813-open-mmlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/envs/0813-open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/reppoints/reppoints_moment_x101_dcn_fpn_2x_mt.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by PumayHui** [comment]
Update……
Solved. The img_scale contain 2 size, such as img_scale=[(1333, 1024), (1333, 832)],
but failed with img_scale=[(1333, 1024), (1333, 832), (1333, 608)],
Will modify this? Thanks!

**Comment by hellock** [comment]
You need to set `multiscale_mode='value'`.

**Comment by PumayHui** [comment]
Thanks!

**Comment by VolcanoGao** [comment]
May I know how to set multiscale_mode, thanks very much!

**Comment by PumayHui** [comment]
The original parameter is:
'
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
'

And multiscale_mode is:
‘
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    # dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(
        type='Resize',
        img_scale=[(1333, 1024), (1440, 1440), (1333, 1280), (1333, 608)],
        keep_ratio=True,
        multiscale_mode='value'),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
’

**Comment by VolcanoGao** [comment]
> > May I know how to set multiscale_mode, thanks very much!
> 
> The original parameter is:
> 
> train_pipeline = [
> 
> ```
> dict(type='LoadImageFromFile'),
> 
> dict(type='LoadAnnotations', with_bbox=True),
> 
> dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
> 
> dict(type='RandomFlip', flip_ratio=0.5),
> 
> dict(type='Normalize', **img_norm_cfg),
> 
> dict(type='Pad', size_divisor=32),
> 
> dict(type='DefaultFormatBundle'),
> 
> dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
> ```
> 
> ]
> 
> And multiscale_mode is:
> 
> train_pipeline = [
> 
> ```
> dict(type='LoadImageFromFile'),
> 
> dict(type='LoadAnnotations', with_bbox=True),
> 
> # dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
> 
> dict(
> 
>     type='Resize',
> 
>     img_scale=[(1333, 1024), (1440, 1440), (1333, 1280), (1333, 608)],
> 
>     keep_ratio=True,
> 
>     multiscale_mode='value'),
> 
> dict(type='RandomFlip', flip_ratio=0.5),
> 
> dict(type='Normalize', **img_norm_cfg),
> 
> dict(type='Pad', size_divisor=32),
> 
> dict(type='DefaultFormatBundle'),
> 
> dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
> ```
> 
> ]

Thank you very much!

**Comment by RiyazAina-DeepML** [comment]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=[(1200, 800),(900,600),(1600,1200)], keep_ratio=True,multiscale_mode='value),
    dict(type='RandomFlip', flip_ratio=0.9),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]

but still i am getting assertion error
