### ISSUE TITLE
KeyError: 'filename'

### ISSUE THREAD

**Issue by skyequeen** [open-mmlab/mmdetection#1283]
Hi,I use the inference_demo.ipynb .How to solve this question.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kongchibin/mmdetection/mmdet/apis/inference.py", line 77, in inference_detector
    data = test_pipeline(data)
  File "/home/kongchibin/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/kongchibin/mmdetection/mmdet/datasets/pipelines/test_aug.py", line 25, in __call__
    data = self.transforms(_results)
  File "/home/kongchibin/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/kongchibin/mmdetection/mmdet/datasets/pipelines/formating.py", line 149, in __call__
    img_meta[key] = results[key]
KeyError: 'filename'

Thanks.

**Comment by hellock** [comment]
You may try the latest version. There was a bug in some commit a few days ago.

**Comment by skyequeen** [comment]
thank you very much
