### ISSUE TITLE
Another ONNX conversion error

### ISSUE THREAD

**Issue by slizb** [open-mmlab/mmdetection#1292]
**Describe the bug**
When converting [this HTC model](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_dconv_c3-c5_mstrain_400_1400_x101_64x4d_fpn_20e.py) to ONNX, I followed the example in #1082 With this method, the conversion started, then failed before completion. It produced the following error stack:

```
Traceback (most recent call last):
  File "another_converter.py", line 52, in <module>
    main()
  File "another_converter.py", line 48, in main
    torch.onnx.export(model, dummy_input, args.out, verbose=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible
```

**Environment**
 -Using the Docker environment shipped with mmdetection

Is it possible to convert this model to ONNX?

**Comment by hellock** [comment]
Unfortunately most models (except for simple ones like SSD) do not support ONNX exporting without modifying anything. You may trying following the instructions in the error message `to make things (e.g., kernel size) static if possible`.

**Comment by slizb** [comment]
Okay, thanks for the quick response.

**Comment by jinfagang** [comment]
@hellock Will this PR merging into master branch? https://github.com/open-mmlab/mmdetection/pull/1386

**Comment by RunningLeon** [comment]
Please try with the latest `mmcv` and `mmdetection` if you still have problems.
