### ISSUE TITLE
Multi-GPU training error

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1293]
Hi, Kai,

I'm doing training on four GPUs using the following code: **./tools/dist_train.sh configs/faster_rcnn_r101_fpn_1x.py 4**

However, after the first epoch iteration, the training exit unexpected with the following error:

File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 274, in train
    self.call_hook('after_train_epoch')
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/utils.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/hooks/checkpoint.py", line 25, in after_train_epoch
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 252, in save_checkpoint
    mmcv.symlink(filename, linkpath)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/utils/path.py", line 49, in symlink
    os.symlink(src, dst, **kwargs)
OSError: [Errno 95] Operation not supported: 'epoch_1.pth' -> '/mmdetection/files/trained_model/faster_rcnn_r101_fpn_1x/latest.pth'
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/miniconda/envs/py36/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/faster_rcnn_r101_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

Can you give me some hints on solving it?

Thank you!

**Comment by shanggdlk** [comment]
I think I find the problem. My storage folder is a shared folder which causes the os.symlink error.

**Comment by YYZ-rose** [comment]
> 我想我发现了问题。我的存储文件夹是一个共享文件夹，导致os.symlink错误。
是需要改训练命令吗

**Comment by shanggdlk** [comment]
> > 我想我发现了问题。我的存储文件夹是一个共享文件夹，导致os.symlink错误。
> > 是需要改训练命令吗

存在一个Local FOLDER就好。不用修改训练命令。

**Comment by solauky** [comment]
subprocess.CalledProcessError: Command '['/home/lxx/anaconda3/envs/mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/lxx/mask_rcnn_x101_64x4d_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
Same problem.May I ask what is the meaning of the existence of a Local FOLDER?thank you

**Comment by freedom521jin** [comment]
File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 252, in save_checkpoint

Find the runner.py ,line 252.Comment the code ' # mmcv.symlink(filename, linkpath) '
