### ISSUE TITLE
Where to add PhotoMetricDistortion in new pipeline?

### ISSUE THREAD

**Issue by zhouhang95** [open-mmlab/mmdetection#1301]
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/student/zhouhang/mmdetection/mmdet/datasets/dataset_wrappers.py", line 52, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 85, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/student/zhouhang/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/student/zhouhang/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/student/zhouhang/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/student/zhouhang/mmdetection/mmdet/datasets/pipelines/transforms.py", line 517, in __call__
    img[..., 0] += random.uniform(-self.hue_delta, self.hue_delta)
TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

Traceback (most recent call last):
  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/student/zhouhang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/student/zhouhang/miniconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'cloth/cloth_cascade.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.

**Comment by zhouhang95** [comment]
set it like ssd config
