### ISSUE TITLE
Forcing test_mode=True for the DistEvalHook causes --validate to fail

### ISSUE THREAD

**Issue by dmarnerides** [open-mmlab/mmdetection#1302]
When using --validate, the a DistEvalHook is added to the runner which creates a dataset with
test_mode=True [here](https://github.com/open-mmlab/mmdetection/blob/ff2f1f3c3213dee29ee7d5f08e4e69bf6271995f/mmdet/core/evaluation/eval_hooks.py#L24). This causes the datapoints to be created without 'ann_info' [here](https://github.com/open-mmlab/mmdetection/blob/ff2f1f3c3213dee29ee7d5f08e4e69bf6271995f/mmdet/datasets/custom.py#L145) since prepare_test_img is called and not prepare_train_img. But 'ann_info' is required for validation.

**Comment by fangxu622** [comment]
I had the same problem

```
2020-01-14 00:32:02,834 - INFO - Epoch [1][21/26]	lr: 0.00360, eta: 0:07:04, time: 0.655, data_time: 0.011, memory: 5679, loss_rpn_cls: 0.0267, loss_rpn_bbox: 0.0164, loss_cls: 0.1501, acc: 96.1182, loss_bbox: 0.0933, loss: 0.2865
2020-01-14 00:32:03,489 - INFO - Epoch [1][22/26]	lr: 0.00361, eta: 0:06:59, time: 0.656, data_time: 0.012, memory: 5679, loss_rpn_cls: 0.0247, loss_rpn_bbox: 0.0120, loss_cls: 0.1572, acc: 96.0449, loss_bbox: 0.1054, loss: 0.2992
2020-01-14 00:32:04,138 - INFO - Epoch [1][23/26]	lr: 0.00363, eta: 0:06:54, time: 0.648, data_time: 0.013, memory: 5679, loss_rpn_cls: 0.0193, loss_rpn_bbox: 0.0123, loss_cls: 0.1350, acc: 96.1914, loss_bbox: 0.0918, loss: 0.2584
2020-01-14 00:32:04,790 - INFO - Epoch [1][24/26]	lr: 0.00364, eta: 0:06:50, time: 0.652, data_time: 0.012, memory: 5679, loss_rpn_cls: 0.0221, loss_rpn_bbox: 0.0110, loss_cls: 0.1407, acc: 96.3379, loss_bbox: 0.0852, loss: 0.2591
2020-01-14 00:32:05,385 - INFO - Epoch [1][25/26]	lr: 0.00365, eta: 0:06:44, time: 0.595, data_time: 0.013, memory: 5679, loss_rpn_cls: 0.0225, loss_rpn_bbox: 0.0099, loss_cls: 0.1913, acc: 94.8242, loss_bbox: 0.1214, loss: 0.3451
2020-01-14 00:32:06,025 - INFO - Epoch [1][26/26]	lr: 0.00367, eta: 0:06:40, time: 0.640, data_time: 0.011, memory: 5679, loss_rpn_cls: 0.0421, loss_rpn_bbox: 0.0141, loss_cls: 0.1480, acc: 96.9238, loss_bbox: 0.0787, loss: 0.2829
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 278, in train
    self.call_hook('after_train_epoch')
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 39, in after_train_epoch
    data = self.dataset[idx]
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/custom.py", line 129, in __getitem__
    return self.prepare_test_img(idx)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/custom.py", line 152, in prepare_test_img
    return self.pipeline(results)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/loading.py", line 99, in __call__
    results = self._load_bboxes(results)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/loading.py", line 52, in _load_bboxes
    ann_info = results['ann_info']
KeyError: 'ann_info'
[                                                  ] 0/606, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 278, in train
    self.call_hook('after_train_epoch')
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 39, in after_train_epoch
    data = self.dataset[idx]
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/custom.py", line 129, in __getitem__
    return self.prepare_test_img(idx)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/custom.py", line 152, in prepare_test_img
    return self.pipeline(results)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/loading.py", line 99, in __call__
    results = self._load_bboxes(results)
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/mmdetection/mmdet/datasets/pipelines/loading.py", line 52, in _load_bboxes
    ann_info = results['ann_info']
KeyError: 'ann_info'
Traceback (most recent call last):
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/fangxu/anaconda3/envs/det/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/fangxu/anaconda3/envs/det/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'sewer-det/configs/sewer_faster_rcnn_r50_fpn_1x.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
```

**Comment by fangxu622** [comment]
I got it, It's my problem.

**Comment by haoran1062** [comment]
> I got it, It's my problem.

I had the same problem, how did you fix it? what's the 'ann_info'

**Comment by milleniums** [comment]
你到底说是为什么呀？

**Comment by milleniums** [comment]
怎么解决的？

**Comment by kaikaizhu** [comment]
I had the same problem, how did you fix it? what's the 'ann_info'
@fangxu622 @haoran1062 @dmarnerides @hellock

**Comment by appledora** [comment]
guys, 
any solutions yet?

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?

**Comment by Lg955** [comment]
> I got it, It's my problem.

So how to solve this problem?
