### ISSUE TITLE
Error when train a model in my costom dataset(CoCo format)

### ISSUE THREAD

**Issue by xiao-keeplearning** [open-mmlab/mmdetection#1312]
I want to train a Cascade R-CNN detector to detect 20 categories of objects using my own coco like datasets, and I counter some problems.
Here is an error:
```
2019-08-31 20:19:40,519 - INFO - Distributed training: False
2019-08-31 20:19:42,214 - INFO - load model from: torchvision://resnet50
2019-08-31 20:19:43,894 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
2019-08-31 20:19:59,619 - INFO - Start running, host: xiaoyao@isee415, work_dir: /home2/xiaoyao/project/mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x
2019-08-31 20:19:59,619 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home2/xiaoyao/project/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home2/xiaoyao/project/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 218, in forward_train
    loss_bbox = bbox_head.loss(cls_score, bbox_pred, *bbox_targets)
  File "/home2/xiaoyao/project/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 129, in loss
    reduction_override=reduction_override)
  File "/home2/xiaoyao/anaconda3/envs/pytorch_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/losses/smooth_l1_loss.py", line 44, in forward
    **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/losses/utils.py", line 93, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home2/xiaoyao/project/mmdetection/mmdet/models/losses/smooth_l1_loss.py", line 11, in smooth_l1_loss
    assert pred.size() == target.size() and target.numel() > 0
AssertionError

```
My train process is:
1. create mmdet/datasets/my_data.py and then copy the contents of `coco.py`, modify the class name to MyDataset and finally change the tuple of `CLASSES` to the tuple of my dataset.
CLASSES = ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
           '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')
2. Then introduce my custom dataset in mmdet\datasets\__init__.py
3.copy cascade_rcnn cfg (checkpoints/cascade_rcnn_r50_fpn_1x.py) to a new dir, rename and only change 3 places:
1)in model->bbox_head->numclasses
num_classes=81 => num_classes = 21
2)in dataset setting
dataset_type = 'CocoDataset' => dataset_type = 'MyDataset'
3)in data path config

then train:
python tools/train.py configs/tianchi_cascade_rcnn_r50_fpn_1x.py

So, how I should do to solve it?  Thank you!

**Comment by xiao-keeplearning** [comment]
sloved

**Comment by Shun14** [comment]
Hi, how did you solve the problem?I met it too.

**Comment by ravikantb** [comment]
@Shun14 : I followed the above steps by @xiao-keeplearning (Thanks mate!) and they worked perfectly fine for my training on my custom data. If I were to guess about this error then I think you haven't replaced 'num_classes' by your classes count at all the places in your config file (for e.g. mask-rcnn has it at two places in 'mask_head' and 'box_head'). 
Please note that:
your classes count =  actual classes + 1 (for background)
