### ISSUE TITLE
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mmdetection#1355]
I am running your inference code:
```
model = init_detector("faster_rcnn_r50_fpn_1x.py", "faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth", device='cuda:0')
img = 'intersection_unlabeled/frame0.jpg'
result = inference_detector(model, img)
show_result_pyplot(img, result, model.CLASSES)
```
And I get the error that torch.distributed has no attribute is_initialized. The full error log:
```
Traceback (most recent call last):
  File "C:/Users/sarim/PycharmProjects/thesis/pytorch_learning.py", line 355, in <module>
    test()
  File "C:/Users/sarim/PycharmProjects/thesis/pytorch_learning.py", line 338, in test
    model = init_detector("faster_rcnn_r50_fpn_1x.py", "faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth", device='cuda:0')
  File "C:\Users\sarim\PycharmProjects\thesis\mmdetection\mmdet\apis\inference.py", line 36, in init_detector
    checkpoint = load_checkpoint(model, checkpoint)
  File "c:\users\sarim\appdata\local\programs\python\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 188, in load_checkpoint
    load_state_dict(model, state_dict, strict, logger)
  File "c:\users\sarim\appdata\local\programs\python\python37\lib\site-packages\mmcv\runner\checkpoint.py", line 96, in load_state_dict
    rank, _ = get_dist_info()
  File "c:\users\sarim\appdata\local\programs\python\python37\lib\site-packages\mmcv\runner\utils.py", line 21, in get_dist_info
    initialized = dist.is_initialized()
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```
My pytorch version is 1.1.0

**Comment by Penuoz** [comment]
same issue
have you solved this problem?

**Comment by sarimmehdi** [comment]
distributed training doesn't work on Windows. I commented out the lines and it all started working. Interestingly enough, on Google Colab (where they are running everything on Linux) it is all working just fine

**Comment by joinssmith** [comment]
_python-path_/Lib/site-packages/mmcv/runner/utils.py
`def get_dist_info():
    if torch.__version__ < '1.0':
        initialized = dist._initialized
    else:
        # initialized = dist.is_initialized()         # commented this
        initialized = False                                # be False
    if initialized:
        rank = dist.get_rank()
        world_size = dist.get_world_size()
    else:
        rank = 0
        world_size = 1
    return rank, world_size`
work for me.

**Comment by hellock** [comment]
The latest mmcv has solved this problem.
