### ISSUE TITLE
TypeError: new_zeros() argument after * must be an iterable, not int

### ISSUE THREAD

**Issue by xxliiiii** [open-mmlab/mmdetection#1368]
Train on VOC dataset using deformable pooling function，but raise TypeError: new_zeros() argument after * must be an iterable, not int. How can I solve it.

**Comment by xxliiiii** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/workspace/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/workspace/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/workspace/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/workspace/mmdetection/mmdet/models/detectors/two_stage.py", line 174, in forward_train
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/mmdetection/mmdet/models/roi_extractors/single_level.py", line 98, in forward
    rois.size(0), self.out_channels, *out_size)
TypeError: new_zeros() argument after * must be an iterable, not int

**Comment by yhcao6** [comment]
Thanks for reporting the bug. Please check #1390 and try again.
