### ISSUE TITLE
OSError: [Errno 95] Operation not supported:

### ISSUE THREAD

**Issue by 666xiaohei666** [open-mmlab/mmdetection#1371]
Traceback (most recent call last):
  File "tools/train.py", line 131, in <module>
    main()
  File "tools/train.py", line 127, in main
    logger=logger)
  File "/test/competition/cloth/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/test/competition/cloth/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 274, in train
    self.call_hook('after_train_epoch')
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/utils.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/checkpoint.py", line 25, in after_train_epoch
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 252, in save_checkpoint
    mmcv.symlink(filename, linkpath)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/path.py", line 49, in symlink
    os.symlink(src, dst, **kwargs)
OSError: [Errno 95] Operation not supported: 'epoch_1.pth' -> '/test/competition/cloth/mmdetection/work_dirs/ga_retinanet_x101_32x4d_fpn_1x/latest.pth'

**Comment by dmy1997** [comment]
hi, have you solved the problem?

**Comment by 666xiaohei666** [comment]
> hi, have you solved the problem?

no

**Comment by dmy1997** [comment]
I just comment the 'os.symlink(src, dst, **kwargs)' in  /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/path.py

**Comment by 666xiaohei666** [comment]
> I just comment the 'os.symlink(src, dst, **kwargs)' in /root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/path.py

got it, thank you!

**Comment by JasonStanson** [comment]
you should check your folder's filesystem(by 'df -T folder') which supports softlink or not.

**Comment by yrjhzbh** [comment]
Did this work?

**Comment by freedom521jin** [comment]
File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 252, in save_checkpoint

Find the runner.py ,line 252.Comment the code ' # mmcv.symlink(filename, linkpath) '

**Comment by hellock** [comment]
Some environments do not support `os.symlink` so that you can add an argument in the checkpoint_cfg field in config files, like `checkpoint_cfg=dict(create_symlink=False)`.

**Comment by ChristopherCao** [comment]
I have just figured it out, here is my solution to this problem:
u should add a line of codes in ./configs/_base_/default_runtime.py
"checkpoint_config = dict(create_symlink=False)" after the line of "checkpoint_config = dict(interval=1)"

by using this line of codes, u can successfully save ur checkpoint in the directory of work_dirs
