### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by rurubaobao** [open-mmlab/mmdetection#1379]
hello,when I eval this ,I got this error
root@seg-pkq57:/data/fr/mmdetection# python tools/voc_eval.py eval/result.pkl configs/libra_rcnn/libra_faster_rcnn_x101_64x4d_fpn_1x.py
Traceback (most recent call last):
  File "tools/voc_eval.py", line 62, in <module>
    main()
  File "tools/voc_eval.py", line 58, in main
    voc_eval(args.result, test_dataset, args.iou_thr)
  File "tools/voc_eval.py", line 43, in voc_eval
    print_summary=True)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+df1b904-py3.6-linux-x86_64.egg/mmdet/core/evaluation/mean_ap.py", line 328, in eval_map
    print_map_summary(mean_ap, eval_results, dataset)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+df1b904-py3.6-linux-x86_64.egg/mmdet/core/evaluation/mean_ap.py", line 371, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: tuple index out of range

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by RebornL** [comment]
excuse me! Have you solved this problem?

**Comment by navimelon** [comment]
if you use a different dataset,you should verify the num_classes in bbox_head,the default value is 80.
