### ISSUE TITLE
error when training maskrcnn on dataset without mask field

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#1417]
Hi, I have a general question regarding the maskrcnn. How to close this mask branch? My dataset does not contain the mask field in the annotation.json. So I simply add a segmentation field in it and randomly fill in some numbers like this: **"segmentation": [[12,15,14,17]]**

I check the config file and set the following field as false:

dict(type='LoadAnnotations', **with_bbox=True**, with_mask=False),

    mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=4,
        loss_mask=dict(
            type='CrossEntropyLoss', **use_mask=False**, loss_weight=1.0)))

However, I still get errors when kicking off the training. I thought it is because the code examines the mask, is it?

  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 215, in forward_train
    self.train_cfg.rcnn)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 111, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 11, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 215, in forward_train
    self.train_cfg.rcnn)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 111, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 11, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 215, in forward_train
    self.train_cfg.rcnn)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 111, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 11, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/miniconda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/miniconda/envs/py36/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/mask_rcnn_r50_fpn_1x.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
root@12bb66940b08:/mmdetection# Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)
  File "/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 215, in forward_train
    self.train_cfg.rcnn)
  File "/mmdetection/mmdet/models/mask_heads/fcn_mask_head.py", line 111, in get_target
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 11, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable

Thank you!

**Comment by hellock** [comment]
You can use Faster R-CNN if you just want to ignore the mask branch.
