### ISSUE TITLE
when convert to onnx: RuntimeError: The size of tensor a (167) must match the size of tensor b (168) at non-singleton dimension 2

### ISSUE THREAD

**Issue by sankexin** [open-mmlab/mmdetection#1418]
Traceback (most recent call last):
  File "onnx_export.py", line 54, in <module>
    main()
  File "onnx_export.py", line 50, in main
    torch.onnx.export(model, dummy_input, args.out, verbose=True)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 266, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 50, in set_training
    yield
  File "/usr/local/lib/python3.5/dist-packages/torch/onnx/utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 231, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 294, in forward
    out = self.inner(*trace_inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/home/zhike.chen/mmdetection_makeonnx/mmdetection/mmdet/models/detectors/two_stage.py", line 93, in forward_dummy
    x = self.extract_feat(img)
  File "/data/home/zhike.chen/mmdetection_makeonnx/mmdetection/mmdet/models/detectors/two_stage.py", line 87, in extract_feat
    x = self.neck(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 481, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/data/home/zhike.chen/mmdetection_makeonnx/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/data/home/zhike.chen/mmdetection_makeonnx/mmdetection/mmdet/models/necks/fpn.py", line 113, in forward
    laterals[i], scale_factor=2, mode='nearest')
RuntimeError: The size of tensor a (167) must match the size of tensor b (168) at non-singleton dimension 2

**Comment by RunningLeon** [comment]
Please try with lastest `mmcv` and `mmdetection`.
