### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by gbyy422990** [open-mmlab/mmdetection#142]
Thx for ur excellent work. I am just trying to training cascade-RCNN on my own dataset, but i got "EOFError: Ran out of input" when i am training, i dont know why and how to fix it. The problem is showing below:
```
root@6d7fc6064502:/notebooks/mmdetection# CUDA_VISIBLE_DEVICES=0,1 ./tools/dist_train.sh configs/cascade_rcnn_r101_fpn_1x.py 2 --seed 9527
2018-12-05 03:46:56,845 - INFO - Distributed training: True
2018-12-05 03:46:56,845 - INFO - Set random seed to 9527
2018-12-05 03:46:58,081 - INFO - load model from: /root/.torch/models/resnet101-5d3b4d8f.pth
Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
    main()
  File "./tools/train.py", line 69, in main
    main()
  File "./tools/train.py", line 69, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 57, in build_detector
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 57, in build_detector
    return build(cfg, detectors, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 24, in build
    return build(cfg, detectors, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 24, in build
    return _build_module(cfg, parrent, default_args)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 16, in _build_module
    return _build_module(cfg, parrent, default_args)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/builder.py", line 16, in _build_module
    cfg, parrent, default_args)
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/utils.py", line 72, in obj_from_dict
    cfg, parrent, default_args)
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/utils.py", line 72, in obj_from_dict
    return obj_type(**args)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/detectors/cascade_rcnn.py", line 75, in __init__
    return obj_type(**args)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/detectors/cascade_rcnn.py", line 75, in __init__
    self.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/detectors/cascade_rcnn.py", line 83, in init_weights
    self.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/detectors/cascade_rcnn.py", line 83, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/backbones/resnet.py", line 266, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/site-packages/mmdet-0.5.4+a6ee053-py3.6.egg/mmdet/models/backbones/resnet.py", line 266, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/checkpoint.py", line 91, in load_checkpoint
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/usr/local/lib/python3.6/site-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/checkpoint.py", line 91, in load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

```
I am using Python3.6/torch 0.4.1/CUDA9.1

**Comment by hellock** [comment]
Could you try
```python
import torch
checkpoint = torch.load('/root/.torch/models/resnet101-5d3b4d8f.pth')
```

It seems that the checkpoint file is broken.
