### ISSUE TITLE
The pre-training model cannot be downloaded!

### ISSUE THREAD

**Issue by zihaozhang9** [open-mmlab/mmdetection#1440]
When I tried to train the SSD model using [ssd300_voc.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/ssd300_voc.py#L5), I received some error logs
`Downloading: "https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/vgg16_caffe-292e1171.pth" to /home/nnir712/.cache/torch/checkpoints/vgg16_c$
ffe-292e1171.pth                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/urllib/request.py", line 1317, in do_open                                                           
    encode_chunked=req.has_header('Transfer-encoding'))                                                                                                           
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1244, in request                                                              
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1290, in _send_request                                                        
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                          
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1239, in endheaders                                                           
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                                
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1026, in _send_output                                                         
    self.send(msg)                                                                                                                                                
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 966, in send                                                                  
    self.connect()                                                                                                                                                
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 1406, in connect                                                              
    super().connect()                                                                                                                                             
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/http/client.py", line 938, in connect                                                               
    (self.host,self.port), self.timeout, self.source_address)                                                                                                     
  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/socket.py", line 727, in create_connection
    raise err  File "/home/nnir712/anaconda3/envs/open-mmlab/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
`
Then I used wget to download the file and found that it could be downloaded.
`wget https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/vgg16_caffe-292e1171.pth`
Maybe I am in China and my Internet is not good.

**Comment by lxtGH** [comment]
Yes because you are in China :)

**Comment by kingwpf** [comment]
大兄弟，复制到迅雷下载，实测满速

**Comment by hellock** [comment]
You may also try the Aliyun mirror.

**Comment by xincyu** [comment]
maybe you can downlaod the pthfile cross the GreatWall Fire by using vpn;
and set in config file: load_from = 'path/to/your_pth_file'

Please correct me if I'm wrong
