### ISSUE TITLE
Raise an error in validation with multi GPU training

### ISSUE THREAD

**Issue by ZenFSheng** [open-mmlab/mmdetection#1445]
**Environment**
 - OS: Ubuntu 18.04.1
 - GCC : 7.4.0
 - PyTorch version 1.1.0
- How I installed PyTorch  : pip
- GPU model  TITANX x 4 (GM200) (12G)
- CUDA 10.00

I use the config `cascade_rcnn_dconv_c3-c5_r50_fpn_1x.py`，and I simply modify it to `cascade_rcnn_dconv_c3-c5_r101_fpn_1x.py`. Then I run multi GPU training with the cmd：
`./tools/dist_train.sh configs/dcn/cascade_rcnn_dconv_c3-c5_r101_fpn_1x.py 4 --validate`
When the training epochs over, the validation start to run.And it seems like the error was happened after the validation images loading. I'm not sure if I miss something in the config or etc. Modified config and error details have been listed below. Hoping some help~ Thank you.

Config  cascade_rcnn_dconv_c3-c5_r101_fpn_1x.py:
```
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='torchvision://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch',
        dcn=dict(
            modulated=False, deformable_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, True, True, True)),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=444,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
    ])
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.02, nms=dict(type='nms', iou_thr=0.5), max_per_img=300),
    keep_all_stages=False)
# dataset settings
dataset_type = 'CocoDataset'
data_root = '/home/dl/d/open_image_2019/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/cache_instances_train.json',
        img_prefix=data_root + 'train/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_validation_correct.json',
        img_prefix=data_root + 'validation/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_validation_correct.json',
        img_prefix=data_root + 'validation/',
        pipeline=test_pipeline))
# optimizer # default: 0.02
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    gamma = 0.5,
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[3, 6, 10, 15, 18])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
evaluation = dict(interval=3)
# runtime settings
total_epochs = 1
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/cascade_rcnn_dconv_c3-c5_r101_fpn_1x'
load_from = '/home/dl/d/open_image_2019/sheng_zf/mm_models/cascade_rcnn_dconv_c3-c5_r101_fpn_1x_20190125-aaa877cc.pth'
resume_from = None
workflow = [('train', 1)]
```

Error details：
```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 26380/26377, 14.5 task/s, elapsed: 1825s, ETA:     0s

Traceback (most recent call last):
File "./tools/train.py", line 108, in <module>
main()
File "./tools/train.py", line 104, in main
logger=logger)
File "/home/dl/d/open_image_2019/sheng_zf/mmdetection/mmdet/apis/train.py", line 58, in train_detector
_dist_train(model, dataset, cfg, validate=validate)
File "/home/dl/d/open_image_2019/sheng_zf/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/dl/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/dl/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 274, in train
self.call_hook('after_train_epoch')
File "/home/dl/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
getattr(hook, fn_name)(self)
File "/home/dl/d/open_image_2019/sheng_zf/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 57, in after_train_epoch
dist.barrier()
File "/home/dl/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1365, in barrier
work.wait()
RuntimeError: CUDA error: the launch timed out and was terminated (synchronize at /opt/conda/conda-bld/pytorch_1556653099582/work/torch/lib/c10d/ProcessGroupNCCL.cpp:145)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fb5a3127dc5 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::synchronize() + 0x235 (0x7fb5a6cbceb5 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x6c0032 (0x7fb5a6c37032 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x12ce4a (0x7fb5a66a3e4a in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyCFunction_FastCallDict + 0x154 (0x556f50023744 in /home/dl/anaconda3/bin/python)
frame #5: <unknown function> + 0x19857e (0x556f500aa57e in /home/dl/anaconda3/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #7: <unknown function> + 0x14022b (0x556f5005222b in /home/dl/anaconda3/bin/python)
frame #8: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #9: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #10: <unknown function> + 0x19253b (0x556f500a453b in /home/dl/anaconda3/bin/python)
frame #11: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #12: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #13: <unknown function> + 0x19253b (0x556f500a453b in /home/dl/anaconda3/bin/python)
frame #14: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #16: <unknown function> + 0x1918e4 (0x556f500a38e4 in /home/dl/anaconda3/bin/python)
frame #17: _PyFunction_FastCallDict + 0x3da (0x556f500a4e6a in /home/dl/anaconda3/bin/python)
frame #18: _PyObject_FastCallDict + 0x26f (0x556f50023b0f in /home/dl/anaconda3/bin/python)
frame #19: _PyObject_Call_Prepend + 0x63 (0x556f500286a3 in /home/dl/anaconda3/bin/python)
frame #20: PyObject_Call + 0x3e (0x556f5002354e in /home/dl/anaconda3/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x19ec (0x556f500d0a6c in /home/dl/anaconda3/bin/python)
frame #22: <unknown function> + 0x1918e4 (0x556f500a38e4 in /home/dl/anaconda3/bin/python)
frame #23: <unknown function> + 0x192771 (0x556f500a4771 in /home/dl/anaconda3/bin/python)
frame #24: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #26: <unknown function> + 0x191bfe (0x556f500a3bfe in /home/dl/anaconda3/bin/python)
frame #27: <unknown function> + 0x192771 (0x556f500a4771 in /home/dl/anaconda3/bin/python)
frame #28: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x10c7 (0x556f500d0147 in /home/dl/anaconda3/bin/python)
frame #30: <unknown function> + 0x1918e4 (0x556f500a38e4 in /home/dl/anaconda3/bin/python)
frame #31: <unknown function> + 0x192771 (0x556f500a4771 in /home/dl/anaconda3/bin/python)
frame #32: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x10c7 (0x556f500d0147 in /home/dl/anaconda3/bin/python)
frame #34: <unknown function> + 0x19253b (0x556f500a453b in /home/dl/anaconda3/bin/python)
frame #35: <unknown function> + 0x198505 (0x556f500aa505 in /home/dl/anaconda3/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x30a (0x556f500cf38a in /home/dl/anaconda3/bin/python)
frame #37: PyEval_EvalCodeEx + 0x329 (0x556f500a5289 in /home/dl/anaconda3/bin/python)
frame #38: PyEval_EvalCode + 0x1c (0x556f500a601c in /home/dl/anaconda3/bin/python)
frame #39: <unknown function> + 0x2163c4 (0x556f501283c4 in /home/dl/anaconda3/bin/python)
frame #40: PyRun_FileExFlags + 0xa1 (0x556f501287c1 in /home/dl/anaconda3/bin/python)
frame #41: PyRun_SimpleFileExFlags + 0x1c3 (0x556f501289c3 in /home/dl/anaconda3/bin/python)
frame #42: Py_Main + 0x613 (0x556f5012c4b3 in /home/dl/anaconda3/bin/python)
frame #43: main + 0xee (0x556f4fff502e in /home/dl/anaconda3/bin/python)
frame #44: __libc_start_main + 0xe7 (0x7fb5aaf86b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #45: <unknown function> + 0x1c3e0e (0x556f500d5e0e in /home/dl/anaconda3/bin/python)

terminate called after throwing an instance of 'c10::Error'
what():  CUDA error: the launch timed out and was terminated (insert_events at /opt/conda/conda-bld/pytorch_1556653099582/work/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fb5a3127dc5 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14792 (0x7fb5a2071792 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x50 (0x7fb5a3117640 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x13ff1b (0x7fb5a66b6f1b in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::~WorkNCCL() + 0x4c (0x7fb5a6cbd5cc in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0xa2 (0x7fb5a6693592 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x6b7e4b (0x7fb5a6c2ee4b in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x12bde2 (0x7fb5a66a2de2 in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x12bf5e (0x7fb5a66a2f5e in /home/dl/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xf12b7 (0x556f500032b7 in /home/dl/anaconda3/bin/python)
frame #10: <unknown function> + 0xf1147 (0x556f50003147 in /home/dl/anaconda3/bin/python)
frame #11: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #12: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #13: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #14: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #15: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #16: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #17: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #18: <unknown function> + 0xf115d (0x556f5000315d in /home/dl/anaconda3/bin/python)
frame #19: PyDict_SetItem + 0x3da (0x556f50048e7a in /home/dl/anaconda3/bin/python)
frame #20: PyDict_SetItemString + 0x4f (0x556f5005178f in /home/dl/anaconda3/bin/python)
frame #21: PyImport_Cleanup + 0x99 (0x556f500b5709 in /home/dl/anaconda3/bin/python)
frame #22: Py_FinalizeEx + 0x61 (0x556f501215f1 in /home/dl/anaconda3/bin/python)
frame #23: Py_Main + 0x35e (0x556f5012c1fe in /home/dl/anaconda3/bin/python)
frame #24: main + 0xee (0x556f4fff502e in /home/dl/anaconda3/bin/python)
frame #25: __libc_start_main + 0xe7 (0x7fb5aaf86b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #26: <unknown function> + 0x1c3e0e (0x556f500d5e0e in /home/dl/anaconda3/bin/python)

Traceback (most recent call last):
File "/home/dl/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/dl/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/dl/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
main()
File "/home/dl/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
cmd=process.args)
subprocess.CalledProcessError: Command '['/home/dl/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/Sheng_modified/cascade_rcnn_dconv_c3-c5_r101_fpn_1x.py', '--launcher', 'pytorch', '--validate']' died with <Signals.SIGABRT: 6>.
```

**Comment by XavierCHEN34** [comment]
the same error

**Comment by longzeyilang** [comment]
I got the same question, have you already solved the same problem?

**Comment by changqinyao** [comment]
I got the same problem

**Comment by xy-guo** [comment]
the same problem. Do you guys find the solution? @changqinyao @longzeyilang @ZenFSheng

**Comment by xy-guo** [comment]
I finally find a potential solution for this. Add extra dist.barrier() in the for loop. It seems nccl will issue a timeout error.

**Comment by hhh0578** [comment]
> For `nccl`, this is applicable only if the environment variable `NCCL_BLOCKING_WAIT` or `NCCL_ASYNC_ERROR_HANDLING` is set to 1. 

[https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group](url)
or you can try to add the two environment variables.
