### ISSUE TITLE
question about train ？ help me

### ISSUE THREAD

**Issue by nuist-xinyu** [open-mmlab/mmdetection#1452]
)
loading annotations into memory...
Done (t=18.06s)
creating index...
index created!
2019-09-26 14:19:18,658 - INFO - Start running, host: xinyu@xinyu-MS-7B89, work_dir: /home/xinyu/mmdetection-master/work_dirs/faster_rcnn_r101_fpn_1x
2019-09-26 14:19:18,659 - INFO - workflow: [('train', 1)], max: 12 epochs
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCTensorMathCompareT.cuh line=69 error=59 : device-side assert triggered
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
Traceback (most recent call last):
  File "train.py", line 108, in <module>
    main()
  File "train.py", line 104, in main
    logger=logger)
  File "/home/xinyu/mmdetection-master/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/xinyu/mmdetection-master/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/xinyu/mmdetection-master/mmcv/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xinyu/mmdetection-master/mmcv/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/xinyu/mmdetection-master/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xinyu/mmdetection-master/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/xinyu/mmdetection-master/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/xinyu/mmdetection-master/mmdet/models/detectors/two_stage.py", line 183, in forward_train
    *bbox_targets)
  File "/home/xinyu/mmdetection-master/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/xinyu/mmdetection-master/mmdet/models/bbox_heads/bbox_head.py", line 116, in loss
    losses['acc'] = accuracy(cls_score, labels)
  File "/home/xinyu/mmdetection-master/mmdet/models/losses/accuracy.py", line 15, in accuracy
    correct = pred_label.eq(target.view(1, -1).expand_as(pred_label))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCTensorMathCompareT.cuh:69
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1565272271120/work/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f61f557ce37 in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x12e14 (0x7f61f57b4e14 in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x165bf (0x7f61f57b85bf in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x74 (0x7f61f5567fa4 in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x1bb014 (0x7f6226668014 in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x40142b (0x7f62268ae42b in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x401461 (0x7f62268ae461 in /home/xinyu/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #26: __libc_start_main + 0xf0 (0x7f62347bc830 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)

**Comment by nuist-xinyu** [comment]
@Kai Chen

**Comment by nuist-xinyu** [comment]
@hellock

**Comment by zrl4836** [comment]
我遇到这种情况，可能是内存溢出或者计算损失的标签不对，估计你属于后者

**Comment by JackeyDeng** [comment]
我也遇到这个问题，求解答呀~~~

**Comment by SunNYNO1** [comment]
为什么这个问题关了，请问有解决这个问题的吗，已经卡在这3天了，只能跑faster rcnn，就是跑不了ssd300，求解求解
