### ISSUE TITLE
during training got an error

### ISSUE THREAD

**Issue by RiyazAtar** [open-mmlab/mmdetection#1462]
when i run  python tools/train.py configs/mask_rcnn_r50_fpn_1x.py for instance segmentation with step followed properly for coco datasets.

but i am getting index out of range error , can anyone help why

`

2019-09-28 05:39:13,330 - INFO - Distributed training: False
2019-09-28 05:39:13,871 - INFO - load model from: torchvision://resnet50
2019-09-28 05:39:14,127 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2019-09-28 05:39:16,807 - INFO - Start running, host: root@60236732d75f, work_dir: /content/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x
2019-09-28 05:39:16,807 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 107, in __call__
    results = self._load_masks(results)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 88, in _load_masks
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 88, in <listcomp>
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0rc0+3dc9ddb-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 73, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

`

**Comment by guohaoyuan** [comment]
我也遇到同样问题

**Comment by HiLiuHuan** [comment]
The same. Have you solved it yet?

**Comment by alexandliutao** [comment]
maybe you can decrease learning rate

**Comment by HiLiuHuan** [comment]
> maybe you can decrease learning rate

sorry. I just tried but failes again. The same error.

**Comment by alexandliutao** [comment]
> > maybe you can decrease learning rate
> 
> sorry. I just tried but failes again. The same error.
这个错误我也遇到过，看issue上总结的有两点，一是数据量太小，learning rate 太大，二是你的类别弄错了，你查查数据集的类别数看看

**Comment by HiLiuHuan** [comment]
> > > maybe you can decrease learning rate
> > 
> > 
> > sorry. I just tried but failes again. The same error.
> > 这个错误我也遇到过，看issue上总结的有两点，一是数据量太小，learning rate 太大，二是你的类别弄错了，你查查数据集的类别数看看

感谢回复，我之前跑了faster_rcnn_r50_fpn_1x和cascade_rcnn_r50_fpn_1x都ok，同样的数据集mask_rcnn_r50_fpn_1x报这个错。我刚看了看这两点，我觉得没问题。。。

**Comment by Noah-CV** [comment]
> > > > maybe you can decrease learning rate
> > > 
> > > 
> > > sorry. I just tried but failes again. The same error.
> > > 这个错误我也遇到过，看issue上总结的有两点，一是数据量太小，learning rate 太大，二是你的类别弄错了，你查查数据集的类别数看看
> 
> 感谢回复，我之前跑了faster_rcnn_r50_fpn_1x和cascade_rcnn_r50_fpn_1x都ok，同样的数据集mask_rcnn_r50_fpn_1x报这个错。我刚看了看这两点，我觉得没问题。。。

我也是 SSD和faster rcnn都没问题 就是mask rcnn不行，请问您解决了吗

**Comment by Atul997** [comment]
Have you solved this. i am facing the same error while using cascade_mask_rcnn_hrnetv2p_w32_20e. 
How to resolve this?

**Comment by paulineml** [comment]
Same error here, https://github.com/open-mmlab/mmdetection/issues/3338 did not fix it. Do you have a solution ?

**Comment by 1508224326** [comment]
我也是跑mask_rcnn会报这样的错，其他的都没问题，我发现把mask_rcnn_r50_fpn_1x_coco.py中的coco_instance改成coco_detection 可以运行，但肯定结果不对，其他类似有mask的模型都会报这个错

**Comment by 1508224326** [comment]
我解决了这个问题 问题出在了数据集上 从voc转coco的时候，有的转换方式将最终的json文件的最后：
`"categories": [{"supercategory": "none", "id": 1, "name": "baseball_cap"}, {"supercategory": "none", "id": 2, "name": "bucket_hat"}, {"supercategory": "none", "id": 3, "name": "clothes_cap"}, {"supercategory": "none", "id": 4, "name": "helmet"}, {"supercategory": "none", "id": 5, "name": "knit_cap"}, {"supercategory": "none", "id": 6, "name": "others"}, {"supercategory": "none", "id": 7, "name": "service_cap"}]`
id起始是从1开始，我出问题的数据中的id起始是从0开始，不知道是不是这个问题直接引起的，我除了改变了数据的转换之外，还修改了图片以及xml文件中的命名，之前命名是“PartA_000000001.jpg”  --->"000000001.jpg",以此。但我想应该不是命名的问题。当我训练别的模型的时候是不会报错的，只有在训练包含mask有关的模型才会报这个IndexError: list index out of range。因为你会发现所有包括mask的模型他们的
```
_base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]
```
中都是coco_instance.py 。如果你单纯想跑mask_rcnn_r50_fpn_1x_coco这个模型，你可以把coco_instance.py换成coco_detection.py，是可以成功运行的！希望有帮助！！

**Comment by NEUdeep** [comment]
我这里添加一个新的情况：
我遇到这个问题也是在跑mask系列算法，也尝试了这里的各种说法，但是，最后发现是一个很愚蠢的问题，就是mask系列默认是分割的，而很多人一开始搞不清coco_instance.py和detection配置的区别，而我的数据本身只标定了box，segmentation是null，所以本身数据，或者配置的classes数目都没问题，问题在数据的格式上。
