### ISSUE TITLE
TypeError: loss() got an unexpected keyword argument 'gt_bboxes_ignore'

### ISSUE THREAD

**Issue by jshuzi** [open-mmlab/mmdetection#1510]
while i run the command 
./tools/dist_train.sh configs/ssd300_scratchdet_coco.py 2 --validate, 
i got an error:
Traceback (most recent call last):
File "./tools/train.py", line 108, in
main()
File "./tools/train.py", line 104, in main
logger=logger)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 58, in train_detector
_dist_train(model, dataset, cfg, validate=validate)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 358, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 264, in train
self.model, data_batch, train_mode=True, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
losses = model(**data)
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/home/jshuzi/mmcv/mmcv/parallel/distributed.py", line 50, in forward
return self.module(*inputs[0], **kwargs[0])
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
return old_func(*args, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
return self.forward_train(img, img_meta, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/models/detectors/single_stage.py", line 60, in forward_train
*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
TypeError: loss() got an unexpected keyword argument 'gt_bboxes_ignore'
Traceback (most recent call last):
File "./tools/train.py", line 108, in
main()
File "./tools/train.py", line 104, in main
logger=logger)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 58, in train_detector
_dist_train(model, dataset, cfg, validate=validate)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 186, in _dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 358, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/jshuzi/mmcv/mmcv/runner/runner.py", line 264, in train
self.model, data_batch, train_mode=True, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
losses = model(**data)
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/home/jshuzi/mmcv/mmcv/parallel/distributed.py", line 50, in forward
return self.module(*inputs[0], **kwargs[0])
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
return old_func(*args, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
return self.forward_train(img, img_meta, **kwargs)
File "/home/jshuzi/mmdetection/mmdet/models/detectors/single_stage.py", line 60, in forward_train
*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
**TypeError: loss() got an unexpected keyword argument 'gt_bboxes_ignore'**
Traceback (most recent call last):
File "/home/jshuzi/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/jshuzi/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in
main()
File "/home/jshuzi/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
cmd=process.args)
subprocess.CalledProcessError: Command '['/home/jshuzi/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/ssd300_scratchdet_coco.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
Have anyone met the problem? thank you for reply.

**Comment by PAUPAUPAUL** [comment]
Hi, did you find some solutions?
