### ISSUE TITLE
Error with modeling

### ISSUE THREAD

**Issue by suryakumara** [open-mmlab/mmdetection#1513]
Dear author.. I got some error here.. maybe you can to solve this..
I am quite new in machine learning.. 
Thankyou

Traceback (most recent call last):
  File "/content/drive/My Drive/app/darts-master/cnn/test.py", line 103, in <module>
    main() 
  File "/content/drive/My Drive/app/darts-master/cnn/test.py", line 59, in main
    utils.load(model, args.model_path)
  File "/content/drive/My Drive/app/darts-master/cnn/utils.py", line 99, in load
    model.load_state_dict(torch.load(model_path))
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'EXP/model.pt'

**Comment by ZwwWayne** [comment]
This is because the path is not right. Please check whether the file indeed exists in this path.

This issue is closed, feel free to reopen it if you have any further questions.
