### ISSUE TITLE
RuntimeError: received 0 items of ancdata

### ISSUE THREAD

**Issue by NOSYPIPA** [open-mmlab/mmdetection#1520]
I hadn't changed the source code and run the code: python tools/train.py configs/retinanet_r50_fpn_1x.py --gpus 8 --validate
The following problems occurred when it was within 1000 iterations of the first epoch.

Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home/qinweida/code/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/qinweida/code/mmdetection/mmdet/apis/train.py", line 227, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 284, in rebuild_storage_fd
    fd = df.detach()
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/qinweida/anaconda3/envs/mmdetection/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

**Comment by WangChuanYuan** [comment]
In my case, I solved that problem through reducing works_per_gpu in the config, or adding
` torch.multiprocessing.set_sharing_strategy('file_system')`
in the entry script.

**Comment by BingliangLi** [comment]
For other wandering souls:
In tools/train.py, add the following lines:
First
`import torch`
Then at the line right after `def main():`
`    torch.multiprocessing.set_sharing_strategy('file_system')`
