### ISSUE TITLE
"struct.error: 'i' format requires -2147483648 <= number <= 2147483647"There is anyone can tell me Why? thanks！

### ISSUE THREAD

**Issue by chaozhong2010** [open-mmlab/mmdetection#1544]
/home/uestc/.conda/envs/mmdetection/bin/python3.6 /media/uestc/1C6E4D586E4D2BB8/dataset_dota/mmdetection/train.py
2019-10-14 22:01:01,092 - INFO - Distributed training: False
2019-10-14 22:01:01,365 - INFO - load model from: torchvision://resnet50
2019-10-14 22:01:01,474 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=10.93s)
creating index...
index created!
2019-10-14 22:01:14,558 - INFO - Start running, host: uestc@uestc, work_dir: /media/uestc/1C6E4D586E4D2BB8/dataset_dota/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x_dota
2019-10-14 22:01:14,559 - INFO - workflow: [('train', 1)], max: 12 epochs
2019-10-14 22:01:25,605 - INFO - Epoch [1][50/18528]	lr: 0.00100, eta: 13:38:14, time: 0.221, data_time: 0.049, memory: 4035, loss_rpn_cls: 0.6333, loss_rpn_bbox: 0.1034, loss_cls: 0.6298, acc: 88.9570, loss_bbox: 0.0340, loss_mask: 0.8105, loss: 2.2110
2019-10-14 22:01:35,231 - INFO - Epoch [1][100/18528]	lr: 0.00116, eta: 12:45:33, time: 0.193, data_time: 0.024, memory: 4035, loss_rpn_cls: 0.4587, loss_rpn_bbox: 0.0848, loss_cls: 0.3793, acc: 93.1328, loss_bbox: 0.0516, loss_mask: 0.6859, loss: 1.6603
2019-10-14 22:01:46,115 - INFO - Epoch [1][150/18528]	lr: 0.00133, eta: 12:58:56, time: 0.218, data_time: 0.048, memory: 4974, loss_rpn_cls: 0.3673, loss_rpn_bbox: 0.0768, loss_cls: 0.4284, acc: 92.1289, loss_bbox: 0.0872, loss_mask: 0.6737, loss: 1.6334
2019-10-14 22:01:55,349 - INFO - Epoch [1][200/18528]	lr: 0.00150, eta: 12:34:59, time: 0.185, data_time: 0.014, memory: 4974, loss_rpn_cls: 0.2834, loss_rpn_bbox: 0.0866, loss_cls: 0.4563, acc: 91.4336, loss_bbox: 0.1405, loss_mask: 0.6243, loss: 1.5911
2019-10-14 22:02:04,609 - INFO - Epoch [1][250/18528]	lr: 0.00166, eta: 12:20:57, time: 0.185, data_time: 0.013, memory: 4974, loss_rpn_cls: 0.2654, loss_rpn_bbox: 0.0742, loss_cls: 0.4863, acc: 90.2188, loss_bbox: 0.1831, loss_mask: 0.5970, loss: 1.6060
2019-10-14 22:02:14,149 - INFO - Epoch [1][300/18528]	lr: 0.00183, eta: 12:15:00, time: 0.191, data_time: 0.021, memory: 4974, loss_rpn_cls: 0.2175, loss_rpn_bbox: 0.0754, loss_cls: 0.4477, acc: 90.5352, loss_bbox: 0.1702, loss_mask: 0.6147, loss: 1.5254
2019-10-14 22:02:24,072 - INFO - Epoch [1][350/18528]	lr: 0.00200, eta: 12:14:44, time: 0.198, data_time: 0.024, memory: 4974, loss_rpn_cls: 0.2393, loss_rpn_bbox: 0.1003, loss_cls: 0.4946, acc: 89.0508, loss_bbox: 0.1907, loss_mask: 0.5843, loss: 1.6092
2019-10-14 22:02:35,562 - INFO - Epoch [1][400/18528]	lr: 0.00216, eta: 12:29:00, time: 0.230, data_time: 0.046, memory: 4974, loss_rpn_cls: 0.3123, loss_rpn_bbox: 0.1018, loss_cls: 0.5767, acc: 86.7969, loss_bbox: 0.2117, loss_mask: 0.5491, loss: 1.7517
2019-10-14 22:02:45,397 - INFO - Epoch [1][450/18528]	lr: 0.00233, eta: 12:26:27, time: 0.197, data_time: 0.024, memory: 4974, loss_rpn_cls: 0.2094, loss_rpn_bbox: 0.0737, loss_cls: 0.4938, acc: 89.4492, loss_bbox: 0.1994, loss_mask: 0.5625, loss: 1.5388
2019-10-14 22:02:55,264 - INFO - Epoch [1][500/18528]	lr: 0.00250, eta: 12:24:37, time: 0.197, data_time: 0.023, memory: 4974, loss_rpn_cls: 0.2039, loss_rpn_bbox: 0.0695, loss_cls: 0.5100, acc: 88.9297, loss_bbox: 0.2014, loss_mask: 0.5470, loss: 1.5318
2019-10-14 22:03:05,806 - INFO - Epoch [1][550/18528]	lr: 0.00250, eta: 12:27:37, time: 0.211, data_time: 0.029, memory: 4974, loss_rpn_cls: 0.2369, loss_rpn_bbox: 0.0794, loss_cls: 0.6097, acc: 85.4453, loss_bbox: 0.2642, loss_mask: 0.5355, loss: 1.7258
2019-10-14 22:03:18,044 - INFO - Epoch [1][600/18528]	lr: 0.00250, eta: 12:40:32, time: 0.245, data_time: 0.060, memory: 4974, loss_rpn_cls: 0.1863, loss_rpn_bbox: 0.0708, loss_cls: 0.5435, acc: 85.2305, loss_bbox: 0.2396, loss_mask: 0.4936, loss: 1.5337
2019-10-14 22:03:29,276 - INFO - Epoch [1][650/18528]	lr: 0.00250, eta: 12:45:43, time: 0.225, data_time: 0.046, memory: 4974, loss_rpn_cls: 0.1766, loss_rpn_bbox: 0.0840, loss_cls: 0.5133, acc: 87.8477, loss_bbox: 0.1967, loss_mask: 0.5168, loss: 1.4874
2019-10-14 22:03:39,878 - INFO - Epoch [1][700/18528]	lr: 0.00250, eta: 12:46:49, time: 0.212, data_time: 0.029, memory: 4974, loss_rpn_cls: 0.1739, loss_rpn_bbox: 0.0902, loss_cls: 0.4781, acc: 86.8984, loss_bbox: 0.2212, loss_mask: 0.4907, loss: 1.4541
2019-10-14 22:03:52,096 - INFO - Epoch [1][750/18528]	lr: 0.00250, eta: 12:55:41, time: 0.244, data_time: 0.058, memory: 4974, loss_rpn_cls: 0.1739, loss_rpn_bbox: 0.0902, loss_cls: 0.5094, acc: 85.7578, loss_bbox: 0.2249, loss_mask: 0.4743, loss: 1.4726
2019-10-14 22:04:02,397 - INFO - Epoch [1][800/18528]	lr: 0.00250, eta: 12:54:35, time: 0.206, data_time: 0.029, memory: 4974, loss_rpn_cls: 0.1536, loss_rpn_bbox: 0.0801, loss_cls: 0.4598, acc: 88.3164, loss_bbox: 0.1870, loss_mask: 0.4840, loss: 1.3644
2019-10-14 22:04:14,924 - INFO - Epoch [1][850/18528]	lr: 0.00250, eta: 13:03:15, time: 0.251, data_time: 0.066, memory: 6721, loss_rpn_cls: 0.1802, loss_rpn_bbox: 0.0653, loss_cls: 0.4409, acc: 87.7539, loss_bbox: 0.1840, loss_mask: 0.4786, loss: 1.3490
Traceback (most recent call last):
  File "/home/uestc/.conda/envs/mmdetection/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/home/uestc/.conda/envs/mmdetection/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/uestc/.conda/envs/mmdetection/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by prateek-77** [comment]
**Same Error:**
2020-01-16 21:50:33,471 - INFO - Epoch [1][2950/9264]	lr: 0.00250, eta: 1 day, 19:58:39, time: 0.663, data_time: 0.088, memory: 2922, loss_rpn_cls: 0.1053, loss_rpn_bbox: 0.0535, loss_cls: 0.3013, acc: 90.1621, loss_bbox: 0.1726, loss_mask: 0.3588, loss: 0.9915
2020-01-16 21:51:03,123 - INFO - Epoch [1][3000/9264]	lr: 0.00250, eta: 1 day, 19:59:30, time: 0.593, data_time: 0.076, memory: 2922, loss_rpn_cls: 0.0992, loss_rpn_bbox: 0.0435, loss_cls: 0.2940, acc: 90.4590, loss_bbox: 0.1574, loss_mask: 0.3383, loss: 0.9323
2020-01-16 21:51:33,354 - INFO - Epoch [1][3050/9264]	lr: 0.00250, eta: 1 day, 20:01:10, time: 0.605, data_time: 0.077, memory: 2922, loss_rpn_cls: 0.0892, loss_rpn_bbox: 0.0497, loss_cls: 0.3190, acc: 89.1953, loss_bbox: 0.1958, loss_mask: 0.3475, loss: 1.0013
2020-01-16 21:51:58,362 - INFO - Epoch [1][3100/9264]	lr: 0.00250, eta: 1 day, 19:55:02, time: 0.500, data_time: 0.051, memory: 2922, loss_rpn_cls: 0.0812, loss_rpn_bbox: 0.0456, loss_cls: 0.2711, acc: 90.7227, loss_bbox: 0.1798, loss_mask: 0.3763, loss: 0.9540
2020-01-16 21:52:37,105 - INFO - Epoch [1][3150/9264]	lr: 0.00250, eta: 1 day, 20:09:04, time: 0.775, data_time: 0.140, memory: 2922, loss_rpn_cls: 0.0915, loss_rpn_bbox: 0.0444, loss_cls: 0.2598, acc: 91.0000, loss_bbox: 0.1570, loss_mask: 0.3656, loss: 0.9183
Traceback (most recent call last):
  File "/home/sall/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/sall/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/sall/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647


I have set the **gpu_assign_thr = 1** to use the cpu for large gt bbox numbers.
**Batch Size = 2img/gpu (8gb GPU)
img_scale=(800,800) (for train pipeline)**

Any help is greatly appreciated!
