### ISSUE TITLE
coco dataset mask error

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#1556]
when I run `mmdetection/tools/train.py`, use `mmdetection/configs/mask_rcnn_r50_fpn_1x.py`.
The code report error:
```
2019-10-17 14:17:58,981 - INFO - Start running, host: zgz@node17, work_dir: /data/zgz/code/rcnn/mmdetection/tools/work_dirs/mask_rcnn_r50_fpn_1x
2019-10-17 14:17:58,982 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "/home/zgz/code/rcnn/mmdetection/tools/train.py", line 111, in <module>
    main()
  File "/home/zgz/code/rcnn/mmdetection/tools/train.py", line 107, in main
    logger=logger)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/apis/train.py", line 227, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/pipelines/loading.py", line 107, in __call__
    results = self._load_masks(results)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/pipelines/loading.py", line 88, in _load_masks
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/pipelines/loading.py", line 88, in <listcomp>
    gt_masks = [self._poly2mask(mask, h, w) for mask in gt_masks]
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/pipelines/loading.py", line 74, in _poly2mask
    rle = maskUtils.merge(rles)
  File "pycocotools/_mask.pyx", line 145, in pycocotools._mask.merge (pycocotools/_mask.c:3173)
  File "pycocotools/_mask.pyx", line 122, in pycocotools._mask._frString (pycocotools/_mask.c:2605)
TypeError: Expected bytes, got str
```

**Comment by as754770178** [comment]
I change `mmdetection/configs/mask_rcnn_r50_fpn_1x.py`, as
(1) `dict(type='LoadAnnotations', with_bbox=True, with_mask=True)` to `dict(type='LoadAnnotations', with_bbox=True, with_mask=False)` 
(2) `dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', `gt_mask`])` to `dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])`

The program report error:
```
2019-10-17 14:34:09,921 - INFO - Start running, host: 110482@node17, work_dir: /data/zgz/code/rcnn/mmdetection/tools/work_dirs/mask_rcnn_r50_fpn_1x
2019-10-17 14:34:09,922 - INFO - workflow: [('train', 1)], max: 12 epochs

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by as754770178** [comment]
我检查`rle = maskUtils.merge(rles)`，rles中数据为
```
<class 'dict'>: {'size': [480, 640], 'counts': b'c[b51l>5M3M4L3M6K6I6J6K4K4L3M3N2M4L3N2M3M4L3N2M3M3M2O2M3M2O2M2O2M2O2N2M2O2M2O2M2O2M3N1N3N1O2N0O100000O10O102N2N3M1N101O001O0O2O010O001O100O0010O100O1OO1O100O1001N3N1N3N1O2M2O2M2O2M2O1N3N1N2O2M2O0O100O1000O02O2M2nL[Dg2f;VM^Dg2d;VM`Dh2n;M2O2M2O1N2O1N3N1N01N101N13N2UN`C1L4MCj<0kCNC;OBP>;=L4M3MT`n1'}
```

**Comment by lingchen1991** [comment]
same issue here

**Comment by JKingKong** [comment]
same issue here

**Comment by zhiwenfan** [comment]
annotation_info['segmentation']["counts"] = mask.encode(np.asfortranarray(binary_mask))["counts"].decode("UTF-8")

**Comment by zhiwenfan** [comment]
decode the bytes to UTF-8 using:
annotation_info['segmentation']["counts"] = mask.encode(np.asfortranarray(binary_mask))["counts"].decode("UTF-8")
