### ISSUE TITLE
训练VOC数据集出错

### ISSUE THREAD

**Issue by upupbo** [open-mmlab/mmdetection#1561]
(mmdetection) cb@ceo-pc:~/mmdetection$ python tools/train.py configs/cascade_mask_rcnn_r50_fpn_1x.py
2019-10-19 10:52:50,646 - INFO - Distributed training: False
2019-10-19 10:52:52,295 - INFO - load model from: torchvision://resnet50
2019-10-19 10:52:52,643 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2019-10-19 10:52:58,388 - INFO - Start running, host: cb@ceo-pc, work_dir: /home/cb/mmdetection/work_dirs/cascade_mask_rcnn_r50_fpn_1x
2019-10-19 10:52:58,388 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home/cb/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/cb/mmdetection/mmdet/apis/train.py", line 227, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cb/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cb/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/cb/mmdetection/mmdet/datasets/custom.py", line 141, in prepare_train_img
    return self.pipeline(results)
  File "/home/cb/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/cb/mmdetection/mmdet/datasets/pipelines/loading.py", line 107, in __call__
    results = self._load_masks(results)
  File "/home/cb/mmdetection/mmdet/datasets/pipelines/loading.py", line 86, in _load_masks
    gt_masks = results['ann_info']['masks']
KeyError: 'masks'

cuda90，gcc4.9，pytorch1.1.0

**Comment by b03505036** [comment]
请问你怎么VOC数据集的呢?能分享嘛，感谢!

**Comment by yhcao6** [comment]
1. Please use English or English&Chinese. 
2. Please follow the Error report issue template.

**Comment by lijain** [comment]
Can you tell me how to make MS RCNN data format with label and mask in your own data set

**Comment by WHY95666** [comment]
i have the same problem

**Comment by yhcao6** [comment]
Current we do not support mask related models for VOC dataset. But prs are welcome.
