### ISSUE TITLE
The Distributed training didnt work?   the errors are as follows. i have installed the v0.4.1 torch from source 

### ISSUE THREAD

**Issue by hitlxm** [open-mmlab/mmdetection#158]
(pt41) bryanleoliu@100:~/mmdetection# python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.4.1'
>>> 
[8]+  Stopped                 python
(pt41) bryanleoliu@100:~/mmdetection# CUDA_VISIBLE_DEVICES='0,1,2,3,4,5' tools/dist_train.sh configs/faster_rcnn_r50_fpn_1x.py 6 --work_dir out_model
Traceback (most recent call last):
  File "tools/train.py", line 81, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 81, in <module>
    main()
  File "tools/train.py", line 57, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
    main()
  File "tools/train.py", line 57, in main
    _init_dist_pytorch(backend, **kwargs)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
    init_dist(args.launcher, **cfg.dist_params)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
Traceback (most recent call last):
    dist.init_process_group(backend=backend, **kwargs)
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
  File "tools/train.py", line 81, in <module>
    _init_dist_pytorch(backend, **kwargs)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17
Traceback (most recent call last):
    main()
  File "tools/train.py", line 81, in <module>
  File "tools/train.py", line 57, in main
    group_name, rank)
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17
Traceback (most recent call last):
    init_dist(args.launcher, **cfg.dist_params)
  File "tools/train.py", line 81, in <module>
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
    main()
  File "tools/train.py", line 57, in main
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
Traceback (most recent call last):
    dist.init_process_group(backend=backend, **kwargs)
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
  File "tools/train.py", line 81, in <module>
    init_dist(args.launcher, **cfg.dist_params)
    main()
  File "tools/train.py", line 57, in main
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
    group_name, rank)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17
    init_dist(args.launcher, **cfg.dist_params)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
    dist.init_process_group(backend=backend, **kwargs)
    main()
  File "tools/train.py", line 57, in main
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    _init_dist_pytorch(backend, **kwargs)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
    init_dist(args.launcher, **cfg.dist_params)
    dist.init_process_group(backend=backend, **kwargs)
    group_name, rank)
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 16, in init_dist
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17
    _init_dist_pytorch(backend, **kwargs)
  File "/data1/bryanleoliu/mmdetection/mmdet/apis/env.py", line 30, in _init_dist_pytorch
    group_name, rank)
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17
    dist.init_process_group(backend=backend, **kwargs)
  File "/data1/bryanleoliu/anaconda3/envs/pt41/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /data1/bryanleoliu/pytorch/torch/lib/THD/process_group/General.cpp:17

**Comment by thangvubk** [comment]
It seems that your machine doesnt have nccl installed ``the distributed NCCL backend is not available``
