### ISSUE TITLE
error with env var RANK

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1596]
Traceback (most recent call last):
  File "/snap/pycharm-professional/159/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/snap/pycharm-professional/159/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/159/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/snap/pycharm-professional/159/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/159/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "../mmdetection/tools/train.py", line 108, in <module>
    main()
  File "../mmdetection/tools/train.py", line 72, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/user/repos/mmdetection/mmdet/apis/env.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/user/repos/mmdetection/mmdet/apis/env.py", line 28, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/user/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

Ubuntu 18.04

run by cmd ../mmdetection/tools/train.py configs/mobilenet_ssd512.py --validate --launcher=pytorch  --seed 9527

**Comment by hellock** [comment]
When you are using non-distributed training, you do not need to specify `--launcher=pytorch`, which is expected to be specified in distributed training mode.
When you train models with the `dist_train.sh` script, it will adopt the pytorch launch util to start processes, which set the environment `RANK`.

**Comment by guotong1988** [comment]
Same question. Thank you!

**Comment by FrancescoSaverioZuppichini** [comment]
Same here, trying to train a model on two gpus without any success. I followed the doc but it is unclear to me witch launcher I should use, I set 'pytorch' but I got the above error
