### ISSUE TITLE
error imgs must be a list, but got <class 'torch.Tensor'>  from test.py

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1600]
I try to validate my model with test.py as it been written https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#test-a-dataset

but get some internal not-intuitively clear error

Ubuntu 18, with gpu 2080

/home/user/anaconda3/bin/python ../mmdetection/tools/test.py configs/mobilenet_ssd512.py work_dirs/mobilenet_ssd512/latest.pth --out mobilenet_ssd512_test.pkl --eval bbox --show
```

[                              ] 0/2914, elapsed: 0s, ETA:Traceback (most recent call last):
  File "../mmdetection/tools/test.py", line 224, in <module>
    main()
  File "../mmdetection/tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "../mmdetection/tools/test.py", line 26, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/repos/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/repos/mmdetection/mmdet/models/detectors/base.py", line 88, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/user/repos/mmdetection/mmdet/models/detectors/base.py", line 67, in forward_test
    name, type(var)))
TypeError: imgs must be a list, but got <class 'torch.Tensor'>
```

**Comment by lijain** [comment]
I have the same problem. Please give me some advice

**Comment by korabelnikov** [comment]
Is my PR not enough for you?

**Comment by korabelnikov** [comment]
@lijain did it helped?

**Comment by korabelnikov** [comment]
@lijain and can you reproduce the error?

**Comment by alfialdo** [comment]
I happened to meet this error/problem when I tried to use the test.py script with my own HTC configuration. However, if I use the error doesn't exist if I use the original config from mmdetection library. Is there any follow up regarding this issue?
