### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by liuhe2017** [open-mmlab/mmdetection#1636]
Hi, I tried to run train.py and got the following this error:
Traceback (most recent call last):
  File "/home/lhcoder/mmdetection-pytorch-1.1/tools/train.py", line 108, in <module>
    main()
  File "/home/lhcoder/mmdetection-pytorch-1.1/tools/train.py", line 104, in main
    logger=logger)
  File "/home/lhcoder/mmdetection-pytorch-1.1/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/lhcoder/mmdetection-pytorch-1.1/mmdet/apis/train.py", line 227, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/hooks/optimizer.py", line 17, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lhcoder/anaconda2/envs/py37_torch1/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

My environment:
system ubuntu 16.04
gpu: NVIDIA RTX 2080 Ti
python 3.7.4
cuda 9.0
torch 1.1
nccl2 1.0

**Comment by thomashossler** [comment]
did you try running the code inside the provided docker image? Are you sure that cudnn is installed on your machine?

**Comment by hellock** [comment]
This thread has been inactive for a long time thus I will close it.
