### ISSUE TITLE
encountering mistake 'IndexError: list index out of range' in test stage.

### ISSUE THREAD

**Issue by yelusaleng** [open-mmlab/mmdetection#1637]
recently, I have designed a new loss function for object detection task, and I use coco as test dataset.

In the training stage, there are no problems.

```shell
{"mode": "train", "epoch": 1, "iter": 50, "lr": 0.00399, "time": 2.51918, "data_time": 0.81056, "memory": 4824, "loss_cls": 1.24209, "loss_bbox": 0.50203, "loss": 1.74411}
{"mode": "train", "epoch": 1, "iter": 100, "lr": 0.00465, "time": 1.71576, "data_time": 0.00517, "memory": 4824, "loss_cls": 1.89211, "loss_bbox": 0.53207, "loss": 2.42419}
{"mode": "train", "epoch": 1, "iter": 150, "lr": 0.00532, "time": 1.65303, "data_time": 0.00509, "memory": 4824, "loss_cls": 1.5037, "loss_bbox": 0.51983, "loss": 2.02353}
{"mode": "train", "epoch": 1, "iter": 200, "lr": 0.00599, "time": 1.64268, "data_time": 0.00508, "memory": 4824, "loss_cls": 1.35439, "loss_bbox": 0.54477, "loss": 1.89916}
{"mode": "train", "epoch": 1, "iter": 250, "lr": 0.00665, "time": 1.65721, "data_time": 0.00515, "memory": 4824, "loss_cls": 1.2359, "loss_bbox": 0.48259, "loss": 1.71849}
{"mode": "train", "epoch": 1, "iter": 300, "lr": 0.00732, "time": 1.68257, "data_time": 0.00503, "memory": 4824, "loss_cls": 1.13274, "loss_bbox": 0.58633, "loss": 1.71906}
{"mode": "train", "epoch": 1, "iter": 350, "lr": 0.00799, "time": 1.6704, "data_time": 0.00528, "memory": 4824, "loss_cls": 1.11957, "loss_bbox": 0.53514, "loss": 1.6547}
{"mode": "train", "epoch": 1, "iter": 400, "lr": 0.00865, "time": 1.58609, "data_time": 0.00508, "memory": 4824, "loss_cls": 1.04725, "loss_bbox": 0.51203, "loss": 1.55928}
{"mode": "train", "epoch": 1, "iter": 450, "lr": 0.00932, "time": 1.62442, "data_time": 0.00521, "memory": 4824, "loss_cls": 1.01147, "loss_bbox": 0.51179, "loss": 1.52326}
{"mode": "train", "epoch": 1, "iter": 500, "lr": 0.00999, "time": 1.63957, "data_time": 0.00516, "memory": 4824, "loss_cls": 0.99802, "loss_bbox": 0.53101, "loss": 1.52903}
{"mode": "train", "epoch": 1, "iter": 550, "lr": 0.01, "time": 1.68507, "data_time": 0.00517, "memory": 4824, "loss_cls": 0.98049, "loss_bbox": 0.49828, "loss": 1.47877}
{"mode": "train", "epoch": 1, "iter": 600, "lr": 0.01, "time": 1.6903, "data_time": 0.00533, "memory": 4824, "loss_cls": 1.09401, "loss_bbox": 0.55063, "loss": 1.64464}
{"mode": "train", "epoch": 1, "iter": 650, "lr": 0.01, "time": 1.64446, "data_time": 0.00538, "memory": 4824, "loss_cls": 0.95786, "loss_bbox": 0.50824, "loss": 1.4661}
{"mode": "train", "epoch": 1, "iter": 700, "lr": 0.01, "time": 1.64591, "data_time": 0.00525, "memory": 4824, "loss_cls": 1.07544, "loss_bbox": 0.60573, "loss": 1.68117}
{"mode": "train", "epoch": 1, "iter": 750, "lr": 0.01, "time": 1.6262, "data_time": 0.00526, "memory": 4824, "loss_cls": 1.04016, "loss_bbox": 0.51284, "loss": 1.55301}
{"mode": "train", "epoch": 1, "iter": 800, "lr": 0.01, "time": 1.62241, "data_time": 0.00525, "memory": 4824, "loss_cls": 1.01909, "loss_bbox": 0.49044, "loss": 1.50953}
{"mode": "train", "epoch": 1, "iter": 850, "lr": 0.01, "time": 1.58241, "data_time": 0.00535, "memory": 4824, "loss_cls": 1.07877, "loss_bbox": 0.53542, "loss": 1.61418}
{"mode": "train", "epoch": 1, "iter": 900, "lr": 0.01, "time": 1.61612, "data_time": 0.00531, "memory": 4824, "loss_cls": 1.16556, "loss_bbox": 0.52732, "loss": 1.69288}
{"mode": "train", "epoch": 1, "iter": 950, "lr": 0.01, "time": 1.67163, "data_time": 0.00564, "memory": 4824, "loss_cls": 1.10956, "loss_bbox": 0.52668, "loss": 1.63624}
{"mode": "train", "epoch": 1, "iter": 1000, "lr": 0.01, "time": 1.63832, "data_time": 0.0053, "memory": 4824, "loss_cls": 0.96347, "loss_bbox": 0.50139, "loss": 1.46486}
{"mode": "train", "epoch": 1, "iter": 1050, "lr": 0.01, "time": 1.60166, "data_time": 0.00544, "memory": 4824, "loss_cls": 0.95086, "loss_bbox": 0.49739, "loss": 1.44825}
{"mode": "train", "epoch": 1, "iter": 1100, "lr": 0.01, "time": 1.60944, "data_time": 0.00552, "memory": 4824, "loss_cls": 0.946, "loss_bbox": 0.50504, "loss": 1.45104}
{"mode": "train", "epoch": 1, "iter": 1150, "lr": 0.01, "time": 1.64524, "data_time": 0.00546, "memory": 4824, "loss_cls": 0.86903, "loss_bbox": 0.51401, "loss": 1.38304}
{"mode": "train", "epoch": 1, "iter": 1200, "lr": 0.01, "time": 1.64834, "data_time": 0.00536, "memory": 4824, "loss_cls": 0.90143, "loss_bbox": 0.52757, "loss": 1.429}
{"mode": "train", "epoch": 1, "iter": 1250, "lr": 0.01, "time": 1.66177, "data_time": 0.00546, "memory": 4824, "loss_cls": 0.87427, "loss_bbox": 0.54145, "loss": 1.41572}
...
...
{"mode": "train", "epoch": 2, "iter": 7250, "lr": 0.01, "time": 1.64567, "data_time": 0.00563, "memory": 4824, "loss_cls": 0.39677, "loss_bbox": 0.32976, "loss": 0.72653}
{"mode": "train", "epoch": 2, "iter": 7300, "lr": 0.01, "time": 1.63921, "data_time": 0.00576, "memory": 4824, "loss_cls": 0.39802, "loss_bbox": 0.3541, "loss": 0.75212}
{"mode": "train", "epoch": 2, "iter": 7350, "lr": 0.01, "time": 1.63998, "data_time": 0.00578, "memory": 4824, "loss_cls": 0.3964, "loss_bbox": 0.36769, "loss": 0.76409}
{"mode": "train", "epoch": 2, "iter": 7400, "lr": 0.01, "time": 1.62722, "data_time": 0.0056, "memory": 4824, "loss_cls": 0.39808, "loss_bbox": 0.35222, "loss": 0.75029}
{"mode": "train", "epoch": 2, "iter": 7450, "lr": 0.01, "time": 1.65345, "data_time": 0.00554, "memory": 4824, "loss_cls": 0.39607, "loss_bbox": 0.31247, "loss": 0.70854}
{"mode": "train", "epoch": 2, "iter": 7500, "lr": 0.01, "time": 1.6603, "data_time": 0.00573, "memory": 4824, "loss_cls": 0.39808, "loss_bbox": 0.3486, "loss": 0.74667}
{"mode": "train", "epoch": 2, "iter": 7550, "lr": 0.01, "time": 1.6605, "data_time": 0.00568, "memory": 4824, "loss_cls": 0.39821, "loss_bbox": 0.33742, "loss": 0.73562}
{"mode": "train", "epoch": 2, "iter": 7600, "lr": 0.01, "time": 1.68604, "data_time": 0.00584, "memory": 4824, "loss_cls": 0.39829, "loss_bbox": 0.335, "loss": 0.73329}
{"mode": "train", "epoch": 2, "iter": 7650, "lr": 0.01, "time": 1.68376, "data_time": 0.00585, "memory": 4824, "loss_cls": 0.397, "loss_bbox": 0.32409, "loss": 0.72109}
{"mode": "train", "epoch": 2, "iter": 7700, "lr": 0.01, "time": 1.6591, "data_time": 0.00572, "memory": 4824, "loss_cls": 0.39648, "loss_bbox": 0.33856, "loss": 0.73504}
{"mode": "train", "epoch": 2, "iter": 7750, "lr": 0.01, "time": 1.60765, "data_time": 0.00575, "memory": 4824, "loss_cls": 0.39743, "loss_bbox": 0.37015, "loss": 0.76759}
{"mode": "train", "epoch": 2, "iter": 7800, "lr": 0.01, "time": 1.63731, "data_time": 0.0059, "memory": 4824, "loss_cls": 0.39806, "loss_bbox": 0.36466, "loss": 0.76272}
{"mode": "train", "epoch": 2, "iter": 7850, "lr": 0.01, "time": 1.62429, "data_time": 0.00574, "memory": 4824, "loss_cls": 0.39667, "loss_bbox": 0.34721, "loss": 0.74388}
{"mode": "train", "epoch": 2, "iter": 7900, "lr": 0.01, "time": 1.63246, "data_time": 0.006, "memory": 4824, "loss_cls": 0.39794, "loss_bbox": 0.34429, "loss": 0.74224}
```

but I encounter some a serious problem in the testing period.
```shell
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5000/5000, 10.1 task/s, elapsed: 493s, ETA:     0s
writing results to results.pkl
Starting evaluate bbox
Loading and preparing results...
Traceback (most recent call last):
  File "../mmdetection/tools/test.py", line 190, in <module>
    main()
  File "../mmdetection/tools/test.py", line 179, in main
    coco_eval(result_file, eval_types, dataset.coco)
  File "/media/wy/1ff8baa1-5a97-4b86-bfcf-83bff91477f1/wy/code/GHM_Detection/mmdetection/mmdet/core/evaluation/coco_utils.py", line 26, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/home/wy/anaconda3/envs/ghm/lib/python3.7/site-packages/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
```

i can't understand this mistake.
the loss_cls and loss_bbox of model shouldn't drop if the model is not convergence.

I need your help! it puzzles me for two weeks !!!

**Comment by yelusaleng** [comment]
@hellock

**Comment by hellock** [comment]
You may try step-by-step debugging to see the predictions during inference.

**Comment by loveisp** [comment]
@yelusaleng Have you solved it? I also encounter this problem.

**Comment by loveisp** [comment]
@yelusaleng OK, I solved it. It's caused by the empty list of bbox when evaluating.

**Comment by yelusaleng** [comment]
@loveisp i know it caused by the empty. but how do you solve the empty?

**Comment by loveisp** [comment]
@yelusaleng I added a "if" statement to check whether the list was empty and didn't do evaluation when it's empty.

**Comment by Edgis** [comment]
> @yelusaleng I added a "if" statement to check whether the list was empty and didn't do evaluation when it's empty.
i meet the problem too, can you tell me the detailed code you have made.
Thanks

**Comment by yelusaleng** [comment]
@Edgis i can't figure out it, i give up.

**Comment by loveisp** [comment]
这好像和我那个不完全一样，但只要在 coco_dets = coco.loadRes(result_file) 这行语句前，提前检查下result_file里的列表是否为空，如果为空直接return应该就可以。

**Comment by Edgis** [comment]
> 这好像和我那个不完全一样，但只要在 coco_dets = coco.loadRes(result_file) 这行语句前，提前检查下result_file里的列表是否为空，如果为空直接return应该就可以。@yelusaleng @Edgis

我理解的是这个result_file 是模型的预测值，coco.loadRes(result_file) 这个函数用来计算一些评价指标，比如mAP。但是result_file 为空的原因是什么，看了好几个issue，是模型没有收敛？

**Comment by loveisp** [comment]
> > 这好像和我那个不完全一样，但只要在 coco_dets = coco.loadRes(result_file) 这行语句前，提前检查下result_file里的列表是否为空，如果为空直接return应该就可以。@yelusaleng @Edgis
> 
> 我理解的是这个result_file 是模型的预测值，coco.loadRes(result_file) 这个函数用来计算一些评价指标，比如mAP。但是result_file 为空的原因是什么，看了好几个issue，是模型没有收敛？

应该是，如果样本比较少的话，前几个epoch可能没有任何预测结果，但后面就好了。
