### ISSUE TITLE
Distributed training error

### ISSUE THREAD

**Issue by Curry1201** [open-mmlab/mmdetection#164]
I want to do distributed training on PASCAL VOC2007. When running the code “ PYTHON=python3 ./tools/dist_train.sh configs/mask_rcnn_r50_fpn_1x.py 2 ”,  the training could not be started. How should I do. The error is shown below:

power@ubuntu:~/mmdetection$ PYTHON=python3 ./tools/dist_train.sh configs/mask_rcnn_r50_fpn_1x.py 2
2018-12-10 21:31:02,984 - INFO - Distributed training: True
2018-12-10 21:31:03,493 - INFO - load model from: modelzoo://resnet50
2018-12-10 21:31:03,747 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer3.4.bn1.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer2.2.bn1.num_batches_tracked

2018-12-10 21:31:06,964 - INFO - Start running, host: power@ubuntu, work_dir: /home/power/mmdetection/work_dirs/mask_rcnn_r50_fpn_1x
2018-12-10 21:31:06,964 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
    main()
  File "./tools/train.py", line 77, in main
    logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/apis/train.py", line 92, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/runner.py", line 251, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/datasets/custom.py", line 139, in __getitem__\n    data = self.prepare_train_img(idx)\n  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/datasets/custom.py", line 193, in prepare_train_img\n    gt_masks = self.mask_transform(ann[\'masks\'], pad_shape,\nKeyError: \'masks\'\n'
Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
    main()
  File "./tools/train.py", line 77, in main
    logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/apis/train.py", line 92, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.2.0-py3.6.egg/mmcv/runner/runner.py", line 251, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/power/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/datasets/custom.py", line 139, in __getitem__\n    data = self.prepare_train_img(idx)\n  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.5.4+65a2e5e-py3.6.egg/mmdet/datasets/custom.py", line 193, in prepare_train_img\n    gt_masks = self.mask_transform(ann[\'masks\'], pad_shape,\nKeyError: \'masks\'\n'

**Comment by hellock** [comment]
The converted VOC dataset does not support masks currently. If you'd like to train mask rcnn on VOC, you may use the officially json [annotations](https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip) provided by coco website. In that case, you will use `CocoDataset`.
