### ISSUE TITLE
Error happened in onnx export

### ISSUE THREAD

**Issue by AndrewZhou924** [open-mmlab/mmdetection#1643]
Hi, I encountered an error when I tried to export a mask_rcnn model which is .pth format to ONNX model. The error message is following.

> Traceback (most recent call last):
  File "onnx_export.py", line 61, in <module>
    main()
  File "onnx_export.py", line 56, in main
    torch.onnx.export(model, dummy_input, args.out, verbose=True)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/andrew/.local/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'new_full'

Could you please tell me the reason and solution towards this error? Thank you.

**Comment by zhudd-hub** [comment]
have you solved?I also met it

**Comment by hellock** [comment]
ONNX export is currently not supported. You may check if https://github.com/open-mmlab/mmdetection/pull/1386 can help.

**Comment by drcut** [comment]
> have you solved?I also met it

You can just use new_ones() * scalar instead of new_full, as ONNX does not support new_full
