### ISSUE TITLE
got an unexpected keyword argument 'ann_file'

### ISSUE THREAD

**Issue by Fitz-liu** [open-mmlab/mmdetection#165]
hi,I use my own dataset for training，but i got this error:
Traceback (most recent call last):
  File "tools/train.py", line 82, in <module>
    main()
  File "tools/train.py", line 70, in main
    train_dataset = get_dataset(cfg.data.train)
  File "/home/liuhaoxu/anaconda3/lib/python3.6/site-packages/mmdet-0.5.4+unknown-py3.6.egg/mmdet/datasets/utils.py", line 114, in get_dataset
    dset = obj_from_dict(data_info, datasets)
  File "/home/liuhaoxu/anaconda3/lib/python3.6/site-packages/mmcv-0.2.1-py3.6.egg/mmcv/runner/utils.py", line 72, in obj_from_dict
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'ann_file'

Where did I make a mistake?

**Comment by hellock** [comment]
Could you provide your config file?

**Comment by Fitz-liu** [comment]
![image](https://user-images.githubusercontent.com/24975745/49772862-b9f30c80-fd29-11e8-86cc-7e2b77098d43.png)
This is my config file ,and I rewrote a data loader，like this:
![image](https://user-images.githubusercontent.com/24975745/49772923-fd4d7b00-fd29-11e8-9450-b001ec117a2f.png)

**Comment by hellock** [comment]
You do not need to rewrite the `__init__` method in `YuncongDataset`, just delete the method and it will get right.

**Comment by Fitz-liu** [comment]
It's work ,thank you!

**Comment by Fitz-liu** [comment]
It works,thank you!
