### ISSUE TITLE
how to batch inference images correctly with  inference_detector(model, imgs) 

### ISSUE THREAD

**Issue by xuhuasheng** [open-mmlab/mmdetection#1659]
I want to batch inference images
so I code like this:
`imgs = [img1, img2, img3]`
`result = inference_detector(model, imgs)`
where `imgs` is a list of ndarray
but it can not run 
**I want to know how to batch inference images?**
`Traceback (most recent call last):
  File "/home/watson/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/watson/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/watson/.vscode/extensions/ms-python.python-2019.10.44104/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/watson/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/watson/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/watson/anaconda3/envs/pytorch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/watson/anaconda3/envs/pytorch/mmdetection/cervical_detection2.py", line 182, in <module>
    slidingWindow_inference()
  File "/home/watson/anaconda3/envs/pytorch/mmdetection/cervical_detection2.py", line 113, in slidingWindow_inference
    result = inference_detector(model, all_WinImgs_list)
  File "/home/watson/anaconda3/envs/pytorch/mmdetection/mmdet/apis/inference.py", line 82, in inference_detector
    data = test_pipeline(data)
  File "/home/watson/anaconda3/envs/pytorch/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/watson/anaconda3/envs/pytorch/mmdetection/mmdet/apis/inference.py", line 56, in __call__
    img = mmcv.imread(results['img'])
  File "/home/watson/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmcv/image/io.py", line 44, in imread
    raise TypeError('"img" must be a numpy array or a filename')
TypeError: "img" must be a numpy array or a filename`

**Comment by ZwwWayne** [comment]
You can check the [config](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py#L145). The implementation is in https://github.com/open-mmlab/mmdetection/tree/master/mmdet/datasets.

**Comment by ShineVJiang** [comment]
@xuhuasheng :hi,do you know how to solve this problem? Thanks!

**Comment by xuhuasheng** [comment]
Not yet.
You can see the conversation in this  [issue](https://github.com/open-mmlab/mmdetection/issues/1671)

**Comment by ShineVJiang** [comment]
> Not yet.
> You can see the conversation in this [issue](https://github.com/open-mmlab/mmdetection/issues/1671)

Thanks, it seems is is not supported by official, you can use for-loop instead.
