### ISSUE TITLE
AttributeError: install_layout

### ISSUE THREAD

**Issue by yulubin** [open-mmlab/mmdetection#1665]
I encountered a problem during installation. I can't figure out what caused it.
I follow the step in the INSTALL.md, after I type 'python setup.py develop' in the terminal, the terminal show as follows：

(ylb) scut@scut-PC:~/mmskeleton$ python setup.py develop
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 353, in fetch_build_egg
    cmd = self._egg_fetcher
AttributeError: 'Distribution' object has no attribute '_egg_fetcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    zip_safe=False)
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 378, in fetch_build_egg
    cmd.ensure_finalized()
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 289, in finalize_options
    'install_lib', ('install_dir', 'install_dir')
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 287, in set_undefined_options
    src_cmd_obj.ensure_finalized()
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 17, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/scut/miniconda3/envs/ylb/lib/python3.7/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
