### ISSUE TITLE
RuntimeError: invalid hash value

### ISSUE THREAD

**Issue by russell-li** [open-mmlab/mmdetection#1666]
I face a error when downloading the pretrained model
and I tried the solution of 
mask_rcnn_x101_32x4d_fpn_gn_ws_2x.py？ #615
but it didn't work.
I also tried several times, I can't solve it myself.
Thanks for helping.
```
~/PycharmProjects/cascade-rcnn$ python tools/get_flops.py configs/cascade_rcnn_x101_64x4d_fpn_1x.py --shape 1000 600
Downloading: "https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth" to /home/russell/.cache/torch/checkpoints/resnext101_64x4d-ee2c6f71.pth
 71%|█████████████████████████████████████████████████▍                    | 220M/311M [01:00<00:25, 3.82MB/s]
Traceback (most recent call last):
  File "tools/get_flops.py", line 52, in <module>
    main()
  File "tools/get_flops.py", line 35, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg).cuda()
  File "/home/russell/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/russell/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/russell/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/russell/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 87, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/russell/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 95, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/russell/mmdetection/mmdet/models/backbones/resnet.py", line 499, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 166, in load_checkpoint
    checkpoint = load_url_dist(open_mmlab_model_urls[model_name])
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 115, in load_url_dist
    checkpoint = model_zoo.load_url(url)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 462, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/torch/hub.py", line 406, in _download_url_to_file
    .format(hash_prefix, digest))
RuntimeError: invalid hash value (expected "ee2c6f71", got "d4397db6fac3447aaa3797ceb642e90bb30d5ecb958f0915e26e80b420fccafc")
```

**Comment by russell-li** [comment]
the pretrained model I want to load is resnext101_64x4d-ee2c6f71.pth
Maybe some error in the mmcv?

**Comment by yhcao6** [comment]
The model has not been download completely, the progress bar is in 71%.
When I download `mask_rcnn_x101_32x4d_fpn_gn_ws_2x.py` and the progress bar reach 100%, the same command with you can be executed without any problem.

**Comment by russell-li** [comment]
Can you try the command `get_flops.py configs/cascade_rcnn_x101_64x4d_fpn_1x.py --shape 1000 600`? Maybe the hash value of the pretrained model should be updated in the mmcv https://github.com/open-mmlab/mmcv/blob/c728193f8d1dc62537c54b29748d9ba595184d40/mmcv/runner/checkpoint.py#L18  ... And I finally download it mannually

**Comment by yhcao6** [comment]
Yes, I use the same command with you. And I use the latest mmcv. There is no error occur.

```
python tools/get_flops.py configs/cascade_rcnn_x101_64x4d_fpn_1x.py --shape 1000 600
Downloading: "https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_64x4d-ee2c6f71.pth" to /home/yhcao/.cache/torch/checkpoints/resnext101_64x4d-ee2c6f71.pth
100%|████████████████████████████████████████████████████████████████████████████████| 311M/311M [00:09<00:00, 36.0MB/s]
CascadeRCNN(
  294.936 GMac, 100.000% MACs,
  (backbone): ResNeXt(
```
