### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#1668]
I use `pip install -v -e .` to compile.
report the error:
```
zgz@node17:~/code/mmdetection$ pip install -v -e .
Obtaining file:///data/zgz/code/mmdetection
  Running setup.py (path:/data/zgz/code/mmdetection/setup.py) egg_info for package from file:///data/zgz/code/mmdetection
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/zgz/code/mmdetection/setup.py", line 94
        sources=[os.path.join(*module.split('.'), p) for p in sources],
    SyntaxError: only named arguments may follow *expression
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /data/zgz/code/mmdetection/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 307, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 489, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/site-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /data/zgz/code/mmdetection/
```

**Comment by YilanWang** [comment]
try to use py3.6+ ?

**Comment by hellock** [comment]
Only python 3.5 or higher is supported.
