### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by he010103** [open-mmlab/mmdetection#169]
Hello, I  run the tools/test.py and error occurs. How can I solve it?
Traceback (most recent call last):
  File "tools/test_image.py", line 3, in <module>
    from mmdet.models import build_detector
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/models/__init__.py", line 1, in <module>
    from .detectors import (BaseDetector, TwoStageDetector, RPN, FastRCNN,
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/models/detectors/__init__.py", line 1, in <module>
    from .base import BaseDetector
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/models/detectors/base.py", line 9, in <module>
    from mmdet.core import tensor2imgs, get_classes
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/anchor/__init__.py", line 2, in <module>
    from .anchor_target import anchor_target
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/anchor/anchor_target.py", line 3, in <module>
    from ..bbox import assign_and_sample, build_assigner, PseudoSampler, bbox2delta
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/bbox/__init__.py", line 2, in <module>
    from .assigners import BaseAssigner, MaxIoUAssigner, AssignResult
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/bbox/assigners/__init__.py", line 1, in <module>
    from .base_assigner import BaseAssigner
  File "/mnt/lustre/hezhiqun/experiments/detection/mmdetection/mmdet/core/bbox/assigners/base_assigner.py", line 4
    class BaseAssigner(metaclass=ABCMeta):
                                ^
SyntaxError: invalid syntax

**Comment by hellock** [comment]
What python version are you using?

**Comment by he010103** [comment]
@hellock Python 2.7.15

**Comment by hellock** [comment]
We use some Python 3 features in this project, thus py2 is not supported. You may reinstall it with Python 3.4+.

**Comment by he010103** [comment]
@hellock now I use python3.7 and Pytorch 0.4.1.post2 with the code: 
`cfg = mmcv.Config.fromfile('configs/mask_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None

# construct the model and load checkpoint
model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(model, 'model/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth')

# test a single image
print('loading image...')
img = '/mnt/lustre/hezhiqun/experiments/detection/mmdetection/test.jpg'
print('inferencing image...')
result = inference_detector(model, img, cfg)
print('showing results...')
show_result(img, result)`

But when forwarding, error exists:
`Segmentation fault`

I go to mmdet/apis/inference.py and find that the code in function _inference_single() interrupt the process:
`result = model(return_loss=False, rescale=True, **data)`

**Comment by hellock** [comment]
What's your cluster environment such as GPU, CUDA, CUDNN? How is PyTorch installed, via conda or pip or from source? Are you running the script on the management node or computing node?

**Comment by he010103** [comment]
I install PyTorch via conda and I can run mnist example. My GPU is TITAN Xp, the CUDA version is cuda9.0 and I donot use CUDNN. I have tried to run the script on the management node with failure, and then on computing node with the same error.

**Comment by huxianer** [comment]
@hellock @he010103 The same error,How to deal with it, THKS!
