### ISSUE TITLE
undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by Xuhuanhua** [open-mmlab/mmdetection#1704]
Hi, I am facing a problem in demo.py

>>> from mmdet.apis import show_result
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuhuanhua/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/xuhuanhua/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/xuhuanhua/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/xuhuanhua/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: /home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by Xuhuanhua** [comment]
torch.version.cuda = 10.1.243

**Comment by hellock** [comment]
Please use the `Error report` issue template.

**Comment by Xuhuanhua** [comment]
> Please use the `Error report` issue template.

ok, Please read the ```Error report``` issue what I re-edit.

**Comment by yindong97** [comment]
I have the same problem. Have you solved this problem?
thank you.

**Comment by Xuhuanhua** [comment]
I don't know how to reply you on Github.
You can refer to the solution of the issue#1705.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yindong97"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 下午4:00
收件人:&nbsp;"open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;;
抄送:&nbsp;"徐焕华"<1286514476@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection] undefined symbol: cudaSetupArgument (#1704)




I have the same problem. Have you solved this problem?
 thank you.

**Comment by BiAnHuaKai-007** [comment]
i don't know how to deal with it
