### ISSUE TITLE
undefined symbol: cudaSetupArgument --> ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Xuhuanhua** [open-mmlab/mmdetection#1705]
**Checklist**
1. I have searched related issues but cannot get the expected help.

**Describe the bug**
Bug occurs when I test the demo.py.
ImportError: /home/xu/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Reproduction**
1. What command or script did you run?
```
from mmdet.apis import init_detector
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
NO
```

**Environment**
 - OS: [Ubuntu 16.04]
 - GCC [5.4.0]
 - PyTorch version [1.3.0]
- How you installed PyTorch [conda install torch]
- GPU model [GTX 1080Ti]
- CUDA and CUDNN version [CUDA Version 9.0.176]

**Error traceback**
```
from mmdet.apis import init_detector
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/xuhuanhua/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/xuhuanhua/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/xuhuanhua/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/xuhuanhua/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: /home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument
```

**Bug fix**
```
```

**Comment by Xuhuanhua** [comment]
I try to use ```PyTorch version [1.2.0](pip install)``` based on some recommendations in #1554 .

**Ner Error traceback**
```
>>> from mmdet.apis import init_detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuhuanhua/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/xuhuanhua/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/xuhuanhua/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/xuhuanhua/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/__init__.py", line 4, in <module>
    from .deform_pool import (DeformRoIPooling, DeformRoIPoolingPack,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_pool.py", line 7, in <module>
    from . import deform_pool_cuda
ImportError: /home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_pool_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl28tls_excluded_tensor_type_setEv
```

**Comment by ZwwWayne** [comment]
Hi @Xuhuanhua ,
This might because the CUDA environment you are currently running is different from that for compiling the code. You may check the version using `nvcc -V` and `echo $CUDA_HOME`.

**Comment by Xuhuanhua** [comment]
Hi @ZwwWayne ,
I check the version of CUDA using `nvcc -V`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
while I check the version using `cat /usr/local/cuda/version.txt`:
```
CUDA Version 9.0.176
```
And terminal has no output when I use `echo $CUDA_HOME`.

**Question**
1. Which is CUDA environment I am currently running？
2. Which is CUDA environment for compiling the code？

**Comment by ZwwWayne** [comment]
I do not know either.
But this is indeed the problem, you could make them be the same 9.0 version and try further.

**Comment by Xuhuanhua** [comment]
I use `torch.__version__ = 1.1.0` and `torch.version.cuda = 9.0.176`.
**And then new error occurs: **
```
>>> from mmdet.apis import init_detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xuhuanhua/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/xuhuanhua/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/xuhuanhua/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/xuhuanhua/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/xuhuanhua/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/__init__.py", line 4, in <module>
    from .deform_pool import (DeformRoIPooling, DeformRoIPoolingPack,
  File "/home/xuhuanhua/mmdetection/mmdet/ops/dcn/deform_pool.py", line 7, in <module>
    from . import deform_pool_cuda
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
```

**Comment by ZwwWayne** [comment]
Do you recompile the ops after your change the Cuda version?

**Comment by Xuhuanhua** [comment]
How to recompile the ops or others?

**Comment by ZwwWayne** [comment]
Once you change your Cuda version/environment, always remember to reinstall the MMDet (run the build command) following the [guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md)

**Comment by Xuhuanhua** [comment]
I always reinstall the MMDet following the [guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md) when I change the CUDA version, but it didn't help me.
### My solution
`rm -rf mmdetection`
`conda remove -n open-mmlab --all`
**Finally I reinstall the MMDet following the [guide](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md) .**
Especially，I install PyTorch and mmdetection using:
```
conda install pytorch==1.1.0 torchvision==0.3.0
```
```
pip install -v -e .
```
### My opinion
When we install the mmdetection, it will generate a **_build_** folder and some **_.so_** files.
Therefore, once we change our CUDA version/environment, we maybe need to remove the **_build_** folder and all **_.so_** files, and reinstall the mmdetection.

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/1577
