### ISSUE TITLE
Create a new loss function

### ISSUE THREAD

**Issue by tjzjp** [open-mmlab/mmdetection#1731]
I want to design a new loss function in mmdetection, however I met this problem unfortunately:

Traceback (most recent call last):
  File "../mmdetection/tools/train.py", line 97, in <module>
    main()
  File "../mmdetection/tools/train.py", line 93, in main
    logger=logger)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/models/detectors/single_stage.py", line 55, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 177, in loss
    sampling=self.sampling)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/core/anchor/anchor_target.py", line 116, in anchor_target_single
    anchors, gt_bboxes, gt_bboxes_ignore, None, cfg)
  File "/home/lwj/zjp/GHM_Detection/mmdetection/mmdet/core/bbox/assign_sampling.py", line 28, in assign_and_sample
    bbox_sampler = build_sampler(cfg.sampler)
  File "/home/lwj/anaconda3/envs/ghm/lib/python3.7/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'sampler'

I have created a new python file in mmdet/models/losses called imbalance_loss.py and added my Loss called ImbalanceLoss in __init__.py

What should I do next and how can I fix the problem?
Thank you very much~~

**Comment by ZwwWayne** [comment]
I think the bug information is quite clear, but we are not able to help you because we do not know what config you use and what other modification you have done, so please use the `ERROR Template`.
This is because you write something wrong about the `cfg`, maybe you pass a wrong thing to the function or you do not write the sampler config. You can check the code and your configs.

**Comment by tjzjp** [comment]
@ZwwWayne 
Thanks for your reply. This morning I have fixed this problem~~

However I have another small question.

  def forward(self, cls_score, label, label_weight, *args, **kwargs):
          if self.use_sigmoid:
              loss_cls = self.loss_weight * self.cls_criterion(
                  cls_score,
                  label,
                  label_weight,
                  gamma=self.gamma,
                  alpha=self.alpha,
                  *args,
                  **kwargs)

This is from mmdet/models/losses/focal_loss.py
I wonder if the "label" contains the background class?

**Comment by ZwwWayne** [comment]
You can check the code or see the labels by yourself.
