### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by wytcsuch** [open-mmlab/mmdetection#1742]
Hello，everything is normal in the previous training, but the loss suddenly becomes very large in step 3250, and then the error occurs. What's the problem

2019-12-03 13:36:58,567 - INFO - Epoch [6][3150/3681]	lr: 0.02000, eta: 3:50:55, time: 0.924, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.0431, loss_rpn_bbox: 0.0594, loss_cls: 0.2494, acc: 90.6348, loss_bbox: 0.2668, loss: 0.6186
2019-12-03 13:37:26,314 - INFO - Epoch [6][3200/3681]	lr: 0.02000, eta: 3:50:21, time: 0.555, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.4505, loss_rpn_bbox: 0.1093, loss_cls: 0.2473, acc: 92.7031, loss_bbox: 0.2011, loss: 1.0083
2019-12-03 13:37:43,641 - INFO - Epoch [6][3250/3681]	lr: 0.02000, eta: 3:49:37, time: 0.347, data_time: 0.005, memory: 6147, loss_rpn_cls: 117119.4643, loss_rpn_bbox: 86211.9636, loss_cls: 18325.3354, acc: 83.0372, loss_bbox: 3535.8495, loss: 225192.6129
2019-12-03 13:38:23,517 - INFO - Epoch [6][3300/3681]	lr: 0.02000, eta: 3:49:16, time: 0.798, data_time: 0.005, memory: 6147, loss_rpn_cls: 91894506.7258, loss_rpn_bbox: 23305796.7583, loss_cls: 3989496427.8865, acc: 83.2261, loss_bbox: 13505982514.5904, loss: 17610679897.6990
2019-12-03 13:39:02,348 - INFO - Epoch [6][3350/3681]	lr: 0.02000, eta: 3:48:54, time: 0.777, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.8049, loss_rpn_bbox: 0.1222, loss_cls: 222272.8403, acc: 93.7891, loss_bbox: 280812.6949, loss: 503086.4462
2019-12-03 13:39:27,972 - INFO - Epoch [6][3400/3681]	lr: 0.02000, eta: 3:48:18, time: 0.512, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5977, loss_rpn_bbox: 0.1056, loss_cls: 89.4625, acc: 94.3125, loss_bbox: 639.2675, loss: 729.4332
2019-12-03 13:39:50,872 - INFO - Epoch [6][3450/3681]	lr: 0.02000, eta: 3:47:39, time: 0.458, data_time: 0.005, memory: 6147, loss_rpn_cls: 5375.5316, loss_rpn_bbox: 5233.3437, loss_cls: 0.3641, acc: 92.4902, loss_bbox: 0.0204, loss: 10609.2588
2019-12-03 13:40:15,885 - INFO - Epoch [6][3500/3681]	lr: 0.02000, eta: 3:47:03, time: 0.500, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5581, loss_rpn_bbox: 0.1263, loss_cls: 0.2827, acc: 94.6035, loss_bbox: 0.0101, loss: 0.9772
2019-12-03 13:40:36,492 - INFO - Epoch [6][3550/3681]	lr: 0.02000, eta: 3:46:22, time: 0.412, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5754, loss_rpn_bbox: 0.1105, loss_cls: 0.3166, acc: 93.7832, loss_bbox: 0.0087, loss: 1.0113
2019-12-03 13:41:33,230 - INFO - Epoch [6][3600/3681]	lr: 0.02000, eta: 3:46:18, time: 1.135, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5789, loss_rpn_bbox: 0.1206, loss_cls: 0.3180, acc: 93.5781, loss_bbox: 0.0135, loss: 1.0310
2019-12-03 13:41:54,390 - INFO - Epoch [6][3650/3681]	lr: 0.02000, eta: 3:45:38, time: 0.423, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5287, loss_rpn_bbox: 0.0983, loss_cls: 0.2554, acc: 95.2637, loss_bbox: 0.0082, loss: 0.8906
2019-12-03 13:42:43,852 - INFO - Epoch [7][50/3681]	lr: 0.02000, eta: 3:44:23, time: 0.469, data_time: 0.019, memory: 6147, loss_rpn_cls: 0.5594, loss_rpn_bbox: 0.1067, loss_cls: 0.2959, acc: 94.1758, loss_bbox: 0.0112, loss: 0.9732
2019-12-03 13:43:31,021 - INFO - Epoch [7][100/3681]	lr: 0.02000, eta: 3:44:08, time: 0.943, data_time: 0.005, memory: 6147, loss_rpn_cls: 13454918287.9462, loss_rpn_bbox: 0.1410, loss_cls: 0.3417, acc: 92.7656, loss_bbox: 0.0083, loss: 13454918288.4338
2019-12-03 13:44:10,153 - INFO - Epoch [7][150/3681]	lr: 0.02000, eta: 3:43:46, time: 0.783, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5577, loss_rpn_bbox: 0.1291, loss_cls: 0.3321, acc: 93.1191, loss_bbox: 0.0073, loss: 1.0262
2019-12-03 13:44:34,169 - INFO - Epoch [7][200/3681]	lr: 0.02000, eta: 3:43:09, time: 0.480, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5878, loss_rpn_bbox: 0.1129, loss_cls: 0.3180, acc: 93.7383, loss_bbox: 0.0125, loss: 1.0312
2019-12-03 13:44:58,516 - INFO - Epoch [7][250/3681]	lr: 0.02000, eta: 3:42:33, time: 0.487, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5105, loss_rpn_bbox: 0.0916, loss_cls: 0.2554, acc: 95.2832, loss_bbox: 0.0158, loss: 0.8734
2019-12-03 13:45:27,276 - INFO - Epoch [7][300/3681]	lr: 0.02000, eta: 3:42:00, time: 0.575, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5878, loss_rpn_bbox: 0.1184, loss_cls: 0.3391, acc: 92.9375, loss_bbox: 0.0139, loss: 1.0593
2019-12-03 13:46:03,470 - INFO - Epoch [7][350/3681]	lr: 0.02000, eta: 3:41:35, time: 0.724, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5407, loss_rpn_bbox: 0.1281, loss_cls: 0.2719, acc: 94.6621, loss_bbox: 0.0111, loss: 0.9518
2019-12-03 13:46:45,389 - INFO - Epoch [7][400/3681]	lr: 0.02000, eta: 3:41:15, time: 0.838, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5501, loss_rpn_bbox: 0.1292, loss_cls: 0.2925, acc: 93.9961, loss_bbox: 0.0058, loss: 0.9776
2019-12-03 13:47:11,399 - INFO - Epoch [7][450/3681]	lr: 0.02000, eta: 3:40:40, time: 0.520, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5634, loss_rpn_bbox: 0.1169, loss_cls: 0.3164, acc: 93.5215, loss_bbox: 0.0100, loss: 1.0067
2019-12-03 13:47:44,780 - INFO - Epoch [7][500/3681]	lr: 0.02000, eta: 3:40:12, time: 0.668, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5887, loss_rpn_bbox: 0.1329, loss_cls: 0.3308, acc: 93.0215, loss_bbox: 0.0134, loss: 1.0658
2019-12-03 13:48:16,044 - INFO - Epoch [7][550/3681]	lr: 0.02000, eta: 3:39:43, time: 0.625, data_time: 0.005, memory: 6147, loss_rpn_cls: 0.5723, loss_rpn_bbox: 0.1283, loss_cls: 0.2985, acc: 94.0254, loss_bbox: 0.0053, loss: 1.0043
Traceback (most recent call last):
  File "tools/train.py", line 112, in <module>
    main()
  File "tools/train.py", line 108, in main
    logger=logger)
  File "/home/yantianwang/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/yantianwang/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    self.call_hook('after_train_iter')
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 19, in after_train_iter
    self.clip_grads(runner.model.parameters())
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 13, in clip_grads
    filter(lambda p: p.requires_grad, params), **self.grad_clip)
  File "/home/yantianwang/anaconda2/envs/pytorch/lib/python3.6/site-packages/torch/nn/utils/clip_grad.py", line 33, in clip_grad_norm_
    total_norm += param_norm.item() ** norm_type
RuntimeError: CUDA error: an illegal memory access was encountered
(pytorch) yantianwang@wyt2-computer:~/mmdetection$

**Comment by ZwwWayne** [comment]
Please use the `Error Template` to indicate your modification and configs etc., current information is too less and we are not able to help you.

**Comment by lxtGH** [comment]
@wytcsuch Hi did you find the reason why ?
