### ISSUE TITLE
UnboundLocalError: local variable 'checkpoint' referenced before assignment

### ISSUE THREAD

**Issue by PAUPAUPAUL** [open-mmlab/mmdetection#1751]
Traceback (most recent call last):
  File "tools/train.py", line 110, in <module>
    main()
  File "tools/train.py", line 86, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/workspaces/code/Detection/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/workspaces/code/Detection/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/workspaces/code/Detection/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/workspaces/code/Detection/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 87, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/workspaces/code/Detection/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 95, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/workspaces/code/Detection/mmdetection/mmdet/models/backbones/resnet.py", line 499, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 163, in load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 120, in load_url_dist
    return checkpoint
UnboundLocalError: local variable 'checkpoint' referenced before assignment

**Comment by PAUPAUPAUL** [comment]
I met this issue, after running: UnboundLocalError: local variable 'checkpoint' referenced before assignment. But I have not changed the checkpoint.py.

**Comment by hellock** [comment]
Please follow the `Error report` issue template to provide more information, so that other users or maintainers can help.

**Comment by AmberrrLiu** [comment]
> I met this issue, after running: UnboundLocalError: local variable 'checkpoint' referenced before assignment. But I have not changed the checkpoint.py.

I have similar issue.Do you have any idea now?

**Comment by guotong1988** [comment]
Similar question.

**Comment by AmberrrLiu** [comment]
> Similar question.

I solved this problem by using exactly same file pth as in the instruction.
original checkpoint path is ../configs/solo/ 
I changed it into    configs/solo/   Then, the problem was raised.
Before: I use
python demo/inference_demo.py      #and change the path in demo.py
After:
cd demo
python inference_demo.py  
AND it worked.

**Comment by guotong1988** [comment]
I solve this problem by setting the absolute path to the checkpoint.
