### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by lyd953621450** [open-mmlab/mmdetection#1765]
When I train my own dataset  by: python tools/train.py configs/faster_rcnn_r50_fpn_1x.py --work_dir works
Then, It show the error :`2019-12-06 11:27:45,332 - INFO - Start running, host: dachen@dachen-MRC-WX0, work_dir: /home/dachen/mmdetection/work_dirs/faster_rcnn_r50_fpn_1x
2019-12-06 11:27:45,332 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 110, in <module>
    main()
  File "tools/train.py", line 106, in main
    logger=logger)
  File "/home/dachen/Documents/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/dachen/Documents/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dachen/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dachen/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/dachen/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/dachen/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/dachen/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/dachen/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/dachen/conda/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/dachen/Documents/mmdetection/mmdet/datasets/loader/sampler.py", line 63, in __iter__
    indices = np.concatenate(indices)
ValueError: need at least one array to concatenate
`
Anyone can solve it ?

**Comment by ZwwWayne** [comment]
If you think the bug is caused by the codebase and want to report it here, please use the `Error Template` especially tell us what you do to the code.
Otherwise, you could [google](https://www.google.com/) or [baidu](https://www.baidu.com/), because this bug is normal for `np.concatenate`, for example, thie [link](https://stackoverflow.com/questions/54967688/valueerror-need-at-least-one-array-to-concatenate).

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/210
