### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by liguang190223** [open-mmlab/mmdetection#1772]
I have searched related issues but cannot get the expected help.

**Describe the bug**
KeyError:  'train'

**Reproduction**
1. What command or script did you run?
  $ python3 tools/train.py --config configs/cascade_rcnn_r50_fpn_1x.py

2. What dataset did you use?
VOC2007
**Environment**
 - OS: [e.g., Ubuntu 18.04]
 - GCC [e.g., 5.4.0]
 - PyTorch version [e.g., 1.1.0]
- How you installed PyTorch [conda]
- GPU model [e.g., 2080Ti]

**Error traceback**
2019-12-09 10:05:35,873 - INFO - Start running, host: lee@lee-Z10PA-U8-Series, work_dir: /home/lee/mmdetection/work_dirs/cascade_rcnn_r50_fpn_1x
2019-12-09 10:05:35,873 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 109, in <module>
    main()
  File "tools/train.py", line 105, in main
    logger=logger)
  File "/home/lee/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/lee/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lee/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lee/mmdetection/mmdet/datasets/custom.py", line 128, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/lee/mmdetection/mmdet/datasets/custom.py", line 136, in prepare_train_img
    ann_info = self.get_ann_info(idx)
  File "/home/lee/mmdetection/mmdet/datasets/xml_style.py", line 47, in get_ann_info
    label = self.cat2label[name]
KeyError: 'train'

**Comment by ZwwWayne** [comment]
What does your config look like? This might be the bug of your config for the VOC dataset. You can check the [config for voc](https://github.com/open-mmlab/mmdetection/blob/master/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py).
