### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by jzchenriver** [open-mmlab/mmdetection#1820]
When I trained a model with my own dataset, I met this error. 
My data was originally in the VOC format labeled by labelimg. After encountering this problem, I converted it to the COCO format, but the problem remained unresolved. 
What should I do?

Traceback (most recent call last):
  File "tools/train.py", line 108, in <module>
    main()
  File "tools/train.py", line 104, in main
    logger=logger)
  File "/home/atr5-1207/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/atr5-1207/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/home/atr5-1207/anaconda3/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/home/atr5-1207/mmdetection/mmdet/datasets/loader/sampler.py", line 63, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by hellock** [comment]
#210
