### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'keep_all_stages'

### ISSUE THREAD

**Issue by gbyy422990** [open-mmlab/mmdetection#1823]
error when eval
```terminal width is too small (0), please consider widen the terminal for better progressbar visualization
[          ] 0/10000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 283, in <module>
    main()
  File "tools/test.py", line 242, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 102, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 93, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 342, in simple_test
    if self.test_cfg.keep_all_stages:
  File "/root/miniconda3/lib/python3.6/site-packages/mmcv/utils/config.py", line 27, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'keep_all_stages'```

**Comment by hellock** [comment]
Please update to the latest version.
