### ISSUE TITLE
Error when using Pytorch-1.3

### ISSUE THREAD

**Issue by chongruo** [open-mmlab/mmdetection#1855]
It raises an error (Segmentation fault) when using pytorch-1.3.  Not sure how to fix it.  CUDA version is 10.1

```shell
2019-12-22 14:17:18,847 - INFO - Start running, host: ubuntu@ip-172-31-25-221, work_dir: /home/ubuntu/mmdetection/work_dirs/mask_rcnn_r101_fpn_1x
2019-12-22 14:17:18,847 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 110, in <module>
    main()
  File "tools/train.py", line 106, in main
    logger=logger)
  File "/home/ubuntu/mmdetection/mmdet/apis/train.py", line 65, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ubuntu/mmdetection/mmdet/apis/train.py", line 237, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 267, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/apis/train.py", line 43, in batch_processor
    losses = model(**data)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/base.py", line 141, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/models/detectors/two_stage.py", line 182, in forward_train
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/ubuntu/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/ubuntu/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 276, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/ubuntu/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 92, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
  File "/home/ubuntu/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 55, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/Loops.cuh:102)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fe2362c3687 in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x78d (0x7fe23d32391d in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x53b70c2 (0x7fe23d31d0c2 in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x53b7578 (0x7fe23d31d578 in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x16150db (0x7fe23957b0db in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x44e (0x7fe239575f0e in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1b0c5aa (0x7fe239a725aa in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x35e67bd (0x7fe23b54c7bd in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #8: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0xbb (0x7fe23b21354b in /home/ubuntu/anaconda3/envs/pytorch-1.3/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #9: nms_cuda(at::Tensor, float) + 0x827 (0x7fe16275ab90 in /home/ubuntu/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #10: nms(at::Tensor const&, float) + 0x318 (0x7fe1627496d8 in /home/ubuntu/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x42c9d (0x7fe162758c9d in /home/ubuntu/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x3fa21 (0x7fe162755a21 in /home/ubuntu/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>

Segmentation fault (core dumped)
```

**Environment**

Pytorch is installed vis conda.
> conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

```shell
sys.platform: linux
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.1.2
MMCV: 0.2.15
MMDetection: 1.0rc1+ed9d42a
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0
```

**Comment by hellock** [comment]
You may install the pytorch prebuilt with CUDA 10.0, or upgrade your local CUDA to 10.1.
