### ISSUE TITLE
ImportError: cannot import name 'get_dist_info'

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#1862]
After I used 'python setup.py develop' this afternoon ,this error happened,I tried to re install the mmcv,but it is useless.
error info:
(mm) wrc@wrc:/media/wrc/0EB90E450EB90E45/mmdetection$ python tools/test.py configs/guided_anchoring/ga_faster_r50_caffe_fpn_1x.py ./work_dirs/ga_faster_rcnn_r50_caffe_fpn_multiscaletrain/latest.pth --out pklfile/multi_ga.pkl --eval bbox
Traceback (most recent call last):
  File "tools/test.py", line 13, in <module>
    from mmdet.apis import init_dist
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>
    from mmdet import datasets
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info'

**Comment by hellock** [comment]
Updating to the latest mmdetection can solve the problem.

**Comment by yuyijie1995** [comment]
I already git pull the latest mmdetection but the error still happened during the evaluation .
Traceback (most recent call last):
  File "tools/test.py", line 14, in <module>
    from mmdet.core import coco_eval, results2json, wrap_fp16_model
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>
    from mmdet import datasets
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler
  File "/media/wrc/0EB90E450EB90E45/mmdetection/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info'

**Comment by yuyijie1995** [comment]
I solved it by  python setup.py develop again.

**Comment by zack624** [comment]
I reinstalled mmcv==0.2.15, and changed file: mmdet/datasets/loader/sampler.py, then it worked.
`from mmcv.runner.utils import get_dist_info -->
from mmcv.runner import get_dist_info`

**Comment by kennyadelaide** [comment]
the function named  tensor2imgs and wrap_fp16_model from  the latest version of mmdetection, then how to invoke them?

**Comment by Lisuqiang228** [comment]
same problem,i solved it.     from mmengine.dist import get_dist_info, init_dist

**Comment by Lisuqiang228** [comment]
same problem,i solved it.     from mmengine.dist import get_dist_info, init_dist
