### ISSUE TITLE
error when running Hybrid Task Cascade (HTC)

### ISSUE THREAD

**Issue by alaayadi** [open-mmlab/mmdetection#1881]
I was able to successfully run Mask R-CNN
cascade_mask_rcnn_x101_64x4d is working fine as well
but when trying HTC, I got this error :

> total_epochs = 40
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/htc_r101_fpn_20e'
load_from = None
resume_from = None
workflow = [('train', 1)]
2019-12-27 10:32:24,289 - INFO - load model from: torchvision://resnet101
2019-12-27 10:32:24,728 - WARNING - The model and loaded state dict do not match exactly
unexpected key in source state_dict: fc.weight, fc.bias
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
2019-12-27 10:32:28,653 - INFO - load checkpoint from htc_r101_fpn_20e_20190408-a2e586db.pth
2019-12-27 10:32:29,031 - WARNING - The model and loaded state dict do not match exactly
these keys have mismatched shape:
+--------------------------------+----------------------------+-----------------------------+
| key                            | expected shape             | loaded shape                |
+--------------------------------+----------------------------+-----------------------------+
| bbox_head.0.fc_cls.weight      | torch.Size([4, 1024])      | torch.Size([81, 1024])      |
| bbox_head.0.fc_cls.bias        | torch.Size([4])            | torch.Size([81])            |
| bbox_head.1.fc_cls.weight      | torch.Size([4, 1024])      | torch.Size([81, 1024])      |
| bbox_head.1.fc_cls.bias        | torch.Size([4])            | torch.Size([81])            |
| bbox_head.2.fc_cls.weight      | torch.Size([4, 1024])      | torch.Size([81, 1024])      |
| bbox_head.2.fc_cls.bias        | torch.Size([4])            | torch.Size([81])            |
| mask_head.0.conv_logits.weight | torch.Size([4, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.0.conv_logits.bias   | torch.Size([4])            | torch.Size([81])            |
| mask_head.1.conv_logits.weight | torch.Size([4, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.1.conv_logits.bias   | torch.Size([4])            | torch.Size([81])            |
| mask_head.2.conv_logits.weight | torch.Size([4, 256, 1, 1]) | torch.Size([81, 256, 1, 1]) |
| mask_head.2.conv_logits.bias   | torch.Size([4])            | torch.Size([81])            |
+--------------------------------+----------------------------+-----------------------------+
2019-12-27 10:32:29,032 - INFO - resumed epoch 20, iter 146600
2019-12-27 10:32:29,033 - INFO - Start running, host: aa@aa, work_dir: /home/aa/segmentation/work_dirs/htc_r101_fpn_20e
2019-12-27 10:32:29,033 - INFO - workflow: [('train', 1)], max: 40 epochs
Traceback (most recent call last):
  File "../../mmdetection/tools/train.py", line 124, in <module>
    main()
  File "../../mmdetection/tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 133, in train_detector
    timestamp=timestamp)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 319, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/aai/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/aa/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/aa/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/aa/.local/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aa/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aa/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/datasets/custom.py", line 131, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/datasets/custom.py", line 144, in prepare_train_img
    return self.pipeline(results)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 107, in __call__
    results = self._load_semantic_seg(results)
  File "/home/aa/anaconda3/lib/python3.7/site-packages/mmdet-1.0rc1+16a6f7d-py3.7-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 92, in _load_semantic_seg
    osp.join(results['seg_prefix'], results['ann_info']['seg_map']),
  File "/home/aa/anaconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by hellock** [comment]
Please check your config file to see whether the dataset follows [this](https://github.com/open-mmlab/mmdetection/blob/master/configs/htc/htc_r50_fpn_1x.py#L232-L237).

**Comment by alaayadi** [comment]
Great , Thanks  , I  am missing seg_prefix
Sorry, but what should we include in the seg_prefix ?

**Comment by hellock** [comment]
The prefix path to your semantic segmentation maps.
