### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable, in rpn_head.py

### ISSUE THREAD

**Issue by Helicopt** [open-mmlab/mmdetection#1882]
**Describe the bug**
Error raised:

  File "~/.local/lib/python3.6/site-packages/mmdet-1.0rc1+cd0d37c-py3.6-linux-x86_64.egg/mmdet/models/anchor_heads/rpn_head.py", line 53, in loss
    loss_rpn_cls=losses['loss_cls'], loss_rpn_bbox=losses['loss_bbox'])
TypeError: 'NoneType' object is not subscriptable

traceback:
- cls_reg_targets is None in mmdet/models/anchor_heads/anchor_head.py#L178
- expression “any([labels is None for labels in all_labels])” is True in mmdet/core/anchor/anchor_target.py#L65
- condition "if not inside_flags.any():" satisfied in mmdet/core/anchor/anchor_target.py#L106
- all valid flags positions exceed boundary in mmdet/core/anchor/anchor_target.py#L168

I guess:  all positions/locations are not valid,  or exceed image boundaries. 
So what happens? Is there something wrong with the input data?  Is the input image too small?

The pipelines are as below:

104 train_pipeline = [
105     dict(type='LoadImageFromFile'),
106     dict(type='LoadAnnotations', with_bbox=True),
107     dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
108     dict(type='RandomFlip', flip_ratio=0.5),
109     dict(type='Normalize', **img_norm_cfg),
110     dict(type='Pad', size_divisor=32),
111     dict(type='DefaultFormatBundle'),
112     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
113 ]

**Reproduction**
1. What command or script did you run?
```
I modified the original code for my own purpose, the command is not important. We can assume I run a faster rcnn without FPN but with RPN and BBox Head on ImageNet DET dataset.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

My modification is irrelevant to this Error after my careful consideration, that is why I am here to ask a question.

3. What dataset did you use?

ImageNet DET.

**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.

It is not a environment relevant problem.

2. You may add addition that may be helpful for locating the problem, such as

It is not a environment relevant problem.

**Error traceback**
If applicable, paste the error trackback here.
```
traceback:
- cls_reg_targets is None in mmdet/models/anchor_heads/anchor_head.py#L178
- expression “any([labels is None for labels in all_labels])” is True in mmdet/core/anchor/anchor_target.py#L65
- condition "if not inside_flags.any():" satisfied in mmdet/core/anchor/anchor_target.py#L106
- all valid flags positions exceed boundary in mmdet/core/anchor/anchor_target.py#L168

```

**Comment by hellock** [comment]
RPN does not generate any valid proposals, which is most likely to be caused by improper hyper-parameters so that the model is not trained well. The provided configs are designed for COCO dataset.

**Comment by Helicopt** [comment]
> RPN does not generate any valid proposals, which is most likely to be caused by improper hyper-parameters so that the model is not trained well. The provided configs are designed for COCO dataset.

Sorry, I don't think it is hyper params problem yeilding null rpn proposals. The Error happens before loss function, where rpn scores feature maps are firstly used. It seems that there are problems in anchors generation.

![image](https://user-images.githubusercontent.com/8593583/71517968-9256ee00-2904-11ea-89ed-a970a4b36724.png)

Before loss function, the anchors are not well generated.

**Comment by hellock** [comment]
If `inside_flags` are all False, then there is no anchors inside the image boundary. You may check the image size and anchor sizes. You may set `allowed_border` to -1 to skip the condition, but it may not be a nice solution.

**Comment by Helicopt** [comment]
The anchors size is scale[8] and ratios[0.5, 1.0, 2.0 ], the input image size of the error is (img: 187 1333, pad: 192 1344). Maybe the input size is too small to generate any anchors.

It is better to add assertion with message to warn users about this.

**Comment by hellock** [comment]
Yes agree.

**Comment by CharlesNJ** [comment]
I got the same error _TypeError: 'NoneType' object is not subscriptable_ with different traceback.

`Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 177, in main
    train_detector(
  File "/home/wellchecked/cbn/CBNetV2/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wellchecked/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 371, in __call__
    results = self._load_masks(results)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 323, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 323, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/wellchecked/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 281, in _poly2mask
    elif isinstance(mask_ann['counts'], list):
TypeError: 'NoneType' object is not subscriptable
`

**Comment by CharlesNJ** [comment]
I got the same error with a different traceback. Any idea what's going on here?

`/mmdet/datasets/pipelines/loading.py", line 323, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)`
    
`mmdet/datasets/pipelines/loading.py", line 281, in _poly2mask
    elif isinstance(mask_ann['counts'], list):
TypeError: 'NoneType' object is not subscriptable`
