### ISSUE TITLE
NameError: name 'collect_results_cpu' is not defined

### ISSUE THREAD

**Issue by loveunk** [open-mmlab/mmdetection#1890]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
- It works well if I run tools/test.py with single GPU.
- But error happens when I run it with multiple GPUs.
- The errors are as follow:

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=0,1,2 bash ~/code/****/tools/dist_test.sh ~/code/****/configs/faster_rcnn_x101_32x4d_fpn_1x_hardhat.py ~/model/****/1228/epoch_9.pth 3 --out ~/model/****/1228/result9.pkl
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes
3. What dataset did you use?
VOC (cusomized)

**Environment**

1. Please run `python tools/collect_env.py` to collect necessary environment infomation and paste it here.
```
sys.platform: linux
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.2.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.4
    - Built with CuDNN 7.3.1
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/opt/conda/conda-bld/pytorch_1566789512916/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1566789512916/work=/usr/local/src/conda/pytorch-1.2.0 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1566789512916/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.4.0a0
OpenCV: 4.1.2
MMCV: 0.2.15
MMDetection: 1.0rc1+16a6f7d
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.0

```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1701/1701, 21.6 task/s, elapsed: 79s, ETA:     0sTraceback (most recent call last):
  File "/home/****/code/****/tools/test.py", line 247, in <module>
    main()
  File "/home/****/code/****/tools/test.py", line 210, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir)
  File "/home/****/code/****/tools/test.py", line 80, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
NameError: name 'collect_results_cpu' is not defined
Traceback (most recent call last):
  File "/home/****/code/****/tools/test.py", line 247, in <module>
    main()
  File "/home/****/code/****/tools/test.py", line 210, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir)
  File "/home/****/code/****/tools/test.py", line 80, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
NameError: name 'collect_results_cpu' is not defined
Traceback (most recent call last):
  File "/home/****/code/****/tools/test.py", line 247, in <module>
    main()
  File "/home/****/code/****/tools/test.py", line 210, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir)
  File "/home/****/code/****/tools/test.py", line 80, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
NameError: name 'collect_results_cpu' is not defined
Traceback (most recent call last):
  File "/home/****/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/****/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/****/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/****/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/****/anaconda3/envs/open-mmlab/bin/python', '-u', '/home/****/code/****/tools/test.py', '--local_rank=2', '/home/****/code/****/configs/faster_rcnn_x101_32x4d_fpn_1x_hardhat.py', '/home/****/model/****/1228/epoch_9.pth',
'--launcher', 'pytorch', '--out', '/home/****/model/****/1228/result9.pkl']' returned non-zero exit status 1.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by loveunk** [comment]
fixed! the issue is caused due to code merge error
