### ISSUE TITLE
i hava found e big bug ,there is something  wrong with the framework or the description of official website when i want to evaluate

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#1923]
official website says:
By default we evaluate the model on the validation set after each epoch

but why I donot see results of  evaluate? where is it ? is it in some logs? but i havenot found when 
i have traind .

by the way , i met an error  when I have uesd :python tools/test.py configs/cascade_rcnn_r101_fpn_1x.py  work_dirs/cas101/latest.pth --out=eval/result.pkl --eval bbox

pleaes help me  how to evaluate and is there something wrong with the above "--eval bbox",why it casue error ?  my email is  83656313@qq.com

the error is :
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 282, in <module>
    main()
  File "tools/test.py", line 260, in main
    coco_eval(result_files, eval_types, dataset.coco)
  File "/home/mmdetection/mmdet/core/evaluation/coco_utils.py", line 44, in coco_eval
    cocoEval = COCOeval(coco, coco_dets, iou_type)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by ZwwWayne** [comment]
Hi @xianglei3 
For your first question, you should see the similar output in your terminal during training in the following picture.
![image](https://user-images.githubusercontent.com/40779233/71861787-848a3f80-3132-11ea-9138-fa98d4eb865a.png)
At least you will find this in the log.txt.
![image](https://user-images.githubusercontent.com/40779233/71861837-b4394780-3132-11ea-82db-c8faf8a8f79a.png)

For your second question, please use the `Error Template`.
