### ISSUE TITLE
Import Error: Cannot import name 'get_dist_info' from mmcv.runner.utils

### ISSUE THREAD

**Issue by cristianoKaKa** [open-mmlab/mmdetection#1926]
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,train_detector)
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/core/evaluation/__init__.py", line 5, in <module>
    from .eval_hooks import (CocoDistEvalmAPHook, CocoDistEvalRecallHook,
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/core/evaluation/eval_hooks.py", line 13, in <module>
    from mmdet import datasets
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/datasets/__init__.py", line 6, in <module>
    from .loader import DistributedGroupSampler, GroupSampler, build_dataloader
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/datasets/loader/__init__.py", line 1, in <module>
    from .build_loader import build_dataloader
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/datasets/loader/build_loader.py", line 8, in <module>
    from .sampler import DistributedGroupSampler, DistributedSampler, GroupSampler
  File "/home/hdc/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet/datasets/loader/sampler.py", line 6, in <module>
    from mmcv.runner.utils import get_dist_info
ImportError: cannot import name 'get_dist_info'
##########################################
I have already update mmcv to the latest version(0.2.15), and mmdetection is the latest version too.
Still this error, anyone know why and how to fix? Thanks very much!

**Comment by ZwwWayne** [comment]
https://github.com/open-mmlab/mmdetection/issues/1811
