### ISSUE TITLE
ValueError: runner has no method named "evaluate" to run an epoch 

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#1933]
when i use  workflow = [('evaluate', 1)]
the err:
Traceback (most recent call last):
  File "tools/train.py", line 110, in <module>
    main()
  File "tools/train.py", line 106, in main
    logger=logger)
  File "/home/mmdetection/mmdet/apis/train.py", line 86, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/mmdetection/mmdet/apis/train.py", line 258, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 352, in run
    format(mode))
ValueError: runner has no method named "evaluate" to run an epoch

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
