### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by korabelnikov** [open-mmlab/mmdetection#1956]
I've tried to train with COCO dataset but got 

**Error traceback**
2019-12-31 00:09:23,589 - INFO - Start running, host: user@korabelnikov-pc, work_dir: /home/user/repos/run_models/work_dirs/work_dirs/COCO_ssd_resnext50_fpn_2L32B_A_O2
2019-12-31 00:09:23,589 - INFO - workflow: [('train', 1)], max: 15 epochs
2019-12-31 00:10:00,814 - INFO - Epoch [1][50/23454]	lr: 0.00020, eta: 3 days, 0:44:36, time: 0.744, data_time: 0.011, memory: 6814, loss_cls: 0.1815, loss_bbox: 6.2176, loss: 6.3991
2019-12-31 00:10:25,669 - INFO - Epoch [1][100/23454]	lr: 0.00023, eta: 2 days, 12:38:58, time: 0.497, data_time: 0.006, memory: 6814, loss_cls: 0.1245, loss_bbox: 5.7827, loss: 5.9072
2019-12-31 00:10:52,344 - INFO - Epoch [1][150/23454]	lr: 0.00027, eta: 2 days, 9:47:53, time: 0.533, data_time: 0.006, memory: 6814, loss_cls: 0.1271, loss_bbox: 5.9448, loss: 6.0718
2019-12-31 00:11:15,380 - INFO - Epoch [1][200/23454]	lr: 0.00030, eta: 2 days, 6:35:31, time: 0.461, data_time: 0.006, memory: 6814, loss_cls: 0.0976, loss_bbox: 5.9246, loss: 6.0222
2019-12-31 00:11:42,663 - INFO - Epoch [1][250/23454]	lr: 0.00033, eta: 2 days, 6:19:28, time: 0.546, data_time: 0.006, memory: 6814, loss_cls: 0.1249, loss_bbox: 5.8464, loss: 5.9713
2019-12-31 00:12:04,013 - INFO - Epoch [1][300/23454]	lr: 0.00037, eta: 2 days, 4:12:46, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.1220, loss_bbox: 6.0454, loss: 6.1674
2019-12-31 00:12:25,409 - INFO - Epoch [1][350/23454]	lr: 0.00040, eta: 2 days, 2:42:55, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.1183, loss_bbox: 5.9647, loss: 6.0830
2019-12-31 00:12:46,703 - INFO - Epoch [1][400/23454]	lr: 0.00043, eta: 2 days, 1:33:58, time: 0.426, data_time: 0.006, memory: 6814, loss_cls: 0.1040, loss_bbox: 5.8759, loss: 5.9800
2019-12-31 00:13:09,888 - INFO - Epoch [1][450/23454]	lr: 0.00047, eta: 2 days, 1:04:51, time: 0.464, data_time: 0.006, memory: 6814, loss_cls: 0.1225, loss_bbox: 5.5926, loss: 5.7151
2019-12-31 00:13:31,482 - INFO - Epoch [1][500/23454]	lr: 0.00050, eta: 2 days, 0:22:52, time: 0.432, data_time: 0.006, memory: 6814, loss_cls: 0.1148, loss_bbox: 6.0096, loss: 6.1244
2019-12-31 00:13:52,914 - INFO - Epoch [1][550/23454]	lr: 0.00050, eta: 1 day, 23:46:43, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.1115, loss_bbox: 6.1329, loss: 6.2444
2019-12-31 00:14:14,286 - INFO - Epoch [1][600/23454]	lr: 0.00050, eta: 1 day, 23:15:57, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0938, loss_bbox: 5.9587, loss: 6.0526
2019-12-31 00:14:35,955 - INFO - Epoch [1][650/23454]	lr: 0.00050, eta: 1 day, 22:52:32, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.1049, loss_bbox: 5.7561, loss: 5.8610
2019-12-31 00:14:57,182 - INFO - Epoch [1][700/23454]	lr: 0.00050, eta: 1 day, 22:28:43, time: 0.425, data_time: 0.006, memory: 6814, loss_cls: 0.1262, loss_bbox: 5.4852, loss: 5.6114
2019-12-31 00:15:18,702 - INFO - Epoch [1][750/23454]	lr: 0.00050, eta: 1 day, 22:10:19, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0994, loss_bbox: 5.7783, loss: 5.8777
2019-12-31 00:15:40,112 - INFO - Epoch [1][800/23454]	lr: 0.00050, eta: 1 day, 21:53:22, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.1098, loss_bbox: 5.5480, loss: 5.6578
2019-12-31 00:16:01,445 - INFO - Epoch [1][850/23454]	lr: 0.00050, eta: 1 day, 21:37:50, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0969, loss_bbox: 5.8624, loss: 5.9594
2019-12-31 00:16:23,257 - INFO - Epoch [1][900/23454]	lr: 0.00050, eta: 1 day, 21:27:06, time: 0.436, data_time: 0.006, memory: 6814, loss_cls: 0.1083, loss_bbox: 5.5466, loss: 5.6550
2019-12-31 00:16:44,710 - INFO - Epoch [1][950/23454]	lr: 0.00050, eta: 1 day, 21:15:15, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0885, loss_bbox: 5.8403, loss: 5.9289
2019-12-31 00:17:05,974 - INFO - Epoch [1][1000/23454]	lr: 0.00050, eta: 1 day, 21:03:27, time: 0.425, data_time: 0.006, memory: 6814, loss_cls: 0.1206, loss_bbox: 5.7406, loss: 5.8612
2019-12-31 00:17:27,306 - INFO - Epoch [1][1050/23454]	lr: 0.00050, eta: 1 day, 20:53:07, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.1010, loss_bbox: 5.7785, loss: 5.8794
2019-12-31 00:17:48,549 - INFO - Epoch [1][1100/23454]	lr: 0.00050, eta: 1 day, 20:43:12, time: 0.425, data_time: 0.006, memory: 6814, loss_cls: 0.0927, loss_bbox: 6.0366, loss: 6.1293
2019-12-31 00:18:10,066 - INFO - Epoch [1][1150/23454]	lr: 0.00050, eta: 1 day, 20:35:32, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.1022, loss_bbox: 4.9621, loss: 5.0643
2019-12-31 00:18:31,478 - INFO - Epoch [1][1200/23454]	lr: 0.00050, eta: 1 day, 20:27:57, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0934, loss_bbox: 5.6022, loss: 5.6956
2019-12-31 00:18:54,535 - INFO - Epoch [1][1250/23454]	lr: 0.00050, eta: 1 day, 20:28:38, time: 0.461, data_time: 0.006, memory: 6814, loss_cls: 0.1072, loss_bbox: 5.4426, loss: 5.5499
2019-12-31 00:19:16,095 - INFO - Epoch [1][1300/23454]	lr: 0.00050, eta: 1 day, 20:22:31, time: 0.431, data_time: 0.006, memory: 6814, loss_cls: 0.1060, loss_bbox: 5.6252, loss: 5.7311
2019-12-31 00:19:37,603 - INFO - Epoch [1][1350/23454]	lr: 0.00050, eta: 1 day, 20:16:36, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0966, loss_bbox: 5.3681, loss: 5.4647
2019-12-31 00:19:59,250 - INFO - Epoch [1][1400/23454]	lr: 0.00050, eta: 1 day, 20:11:39, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0987, loss_bbox: 5.6089, loss: 5.7076
2019-12-31 00:20:21,039 - INFO - Epoch [1][1450/23454]	lr: 0.00050, eta: 1 day, 20:07:36, time: 0.436, data_time: 0.006, memory: 6814, loss_cls: 0.0986, loss_bbox: 5.5507, loss: 5.6494
2019-12-31 00:20:42,740 - INFO - Epoch [1][1500/23454]	lr: 0.00050, eta: 1 day, 20:03:26, time: 0.434, data_time: 0.006, memory: 6814, loss_cls: 0.1058, loss_bbox: 5.7321, loss: 5.8379
2019-12-31 00:21:04,166 - INFO - Epoch [1][1550/23454]	lr: 0.00050, eta: 1 day, 19:58:30, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0960, loss_bbox: 5.4672, loss: 5.5632
2019-12-31 00:21:25,558 - INFO - Epoch [1][1600/23454]	lr: 0.00050, eta: 1 day, 19:53:43, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0953, loss_bbox: 5.8306, loss: 5.9258
2019-12-31 00:21:46,885 - INFO - Epoch [1][1650/23454]	lr: 0.00050, eta: 1 day, 19:48:59, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0860, loss_bbox: 5.7611, loss: 5.8471
2019-12-31 00:22:08,762 - INFO - Epoch [1][1700/23454]	lr: 0.00050, eta: 1 day, 19:46:23, time: 0.438, data_time: 0.006, memory: 6814, loss_cls: 0.1100, loss_bbox: 5.5785, loss: 5.6886
2019-12-31 00:22:30,342 - INFO - Epoch [1][1750/23454]	lr: 0.00050, eta: 1 day, 19:42:55, time: 0.432, data_time: 0.006, memory: 6814, loss_cls: 0.1056, loss_bbox: 5.0848, loss: 5.1903
2019-12-31 00:22:51,984 - INFO - Epoch [1][1800/23454]	lr: 0.00050, eta: 1 day, 19:39:50, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0941, loss_bbox: 5.4029, loss: 5.4971
2019-12-31 00:23:13,385 - INFO - Epoch [1][1850/23454]	lr: 0.00050, eta: 1 day, 19:36:08, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0976, loss_bbox: 5.5178, loss: 5.6154
2019-12-31 00:23:35,150 - INFO - Epoch [1][1900/23454]	lr: 0.00050, eta: 1 day, 19:33:44, time: 0.435, data_time: 0.007, memory: 6814, loss_cls: 0.1036, loss_bbox: 5.5894, loss: 5.6929
2019-12-31 00:23:56,475 - INFO - Epoch [1][1950/23454]	lr: 0.00050, eta: 1 day, 19:30:07, time: 0.426, data_time: 0.006, memory: 6814, loss_cls: 0.1038, loss_bbox: 5.4678, loss: 5.5716
2019-12-31 00:24:17,803 - INFO - Epoch [1][2000/23454]	lr: 0.00050, eta: 1 day, 19:26:40, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0952, loss_bbox: 5.4550, loss: 5.5502
2019-12-31 00:24:39,207 - INFO - Epoch [1][2050/23454]	lr: 0.00050, eta: 1 day, 19:23:35, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.1011, loss_bbox: 5.3920, loss: 5.4931
2019-12-31 00:25:00,623 - INFO - Epoch [1][2100/23454]	lr: 0.00050, eta: 1 day, 19:20:41, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0974, loss_bbox: 5.6212, loss: 5.7185
2019-12-31 00:25:22,251 - INFO - Epoch [1][2150/23454]	lr: 0.00050, eta: 1 day, 19:18:27, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0956, loss_bbox: 5.3545, loss: 5.4501
2019-12-31 00:25:43,898 - INFO - Epoch [1][2200/23454]	lr: 0.00050, eta: 1 day, 19:16:22, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0912, loss_bbox: 5.3529, loss: 5.4441
2019-12-31 00:26:05,347 - INFO - Epoch [1][2250/23454]	lr: 0.00050, eta: 1 day, 19:13:51, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0906, loss_bbox: 5.3064, loss: 5.3970
2019-12-31 00:26:26,822 - INFO - Epoch [1][2300/23454]	lr: 0.00050, eta: 1 day, 19:11:29, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.1046, loss_bbox: 5.6220, loss: 5.7267
2019-12-31 00:26:48,617 - INFO - Epoch [1][2350/23454]	lr: 0.00050, eta: 1 day, 19:10:00, time: 0.436, data_time: 0.006, memory: 6814, loss_cls: 0.0898, loss_bbox: 5.6581, loss: 5.7480
2019-12-31 00:27:10,249 - INFO - Epoch [1][2400/23454]	lr: 0.00050, eta: 1 day, 19:08:10, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0789, loss_bbox: 5.5252, loss: 5.6042
2019-12-31 00:27:32,109 - INFO - Epoch [1][2450/23454]	lr: 0.00050, eta: 1 day, 19:06:56, time: 0.437, data_time: 0.006, memory: 6814, loss_cls: 0.0966, loss_bbox: 5.2845, loss: 5.3811
2019-12-31 00:27:53,435 - INFO - Epoch [1][2500/23454]	lr: 0.00050, eta: 1 day, 19:04:30, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0831, loss_bbox: 5.5308, loss: 5.6140
2019-12-31 00:28:15,267 - INFO - Epoch [1][2550/23454]	lr: 0.00050, eta: 1 day, 19:03:18, time: 0.437, data_time: 0.006, memory: 6814, loss_cls: 0.0921, loss_bbox: 5.3269, loss: 5.4189
2019-12-31 00:28:36,819 - INFO - Epoch [1][2600/23454]	lr: 0.00050, eta: 1 day, 19:01:30, time: 0.431, data_time: 0.006, memory: 6814, loss_cls: 0.0997, loss_bbox: 5.4699, loss: 5.5697
2019-12-31 00:28:58,449 - INFO - Epoch [1][2650/23454]	lr: 0.00050, eta: 1 day, 18:59:55, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0956, loss_bbox: 5.3340, loss: 5.4296
2019-12-31 00:29:19,917 - INFO - Epoch [1][2700/23454]	lr: 0.00050, eta: 1 day, 18:58:03, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0949, loss_bbox: 5.5417, loss: 5.6366
2019-12-31 00:29:41,331 - INFO - Epoch [1][2750/23454]	lr: 0.00050, eta: 1 day, 18:56:07, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0972, loss_bbox: 5.4973, loss: 5.5944
2019-12-31 00:30:03,002 - INFO - Epoch [1][2800/23454]	lr: 0.00050, eta: 1 day, 18:54:46, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0967, loss_bbox: 5.2866, loss: 5.3832
2019-12-31 00:30:24,467 - INFO - Epoch [1][2850/23454]	lr: 0.00050, eta: 1 day, 18:53:02, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.1042, loss_bbox: 5.5576, loss: 5.6618
2019-12-31 00:30:46,340 - INFO - Epoch [1][2900/23454]	lr: 0.00050, eta: 1 day, 18:52:10, time: 0.437, data_time: 0.006, memory: 6814, loss_cls: 0.0790, loss_bbox: 5.6036, loss: 5.6826
2019-12-31 00:31:08,276 - INFO - Epoch [1][2950/23454]	lr: 0.00050, eta: 1 day, 18:51:27, time: 0.439, data_time: 0.006, memory: 6814, loss_cls: 0.1002, loss_bbox: 5.2425, loss: 5.3427
2019-12-31 00:31:30,033 - INFO - Epoch [1][3000/23454]	lr: 0.00050, eta: 1 day, 18:50:23, time: 0.435, data_time: 0.006, memory: 6814, loss_cls: 0.0820, loss_bbox: 5.6200, loss: 5.7020
2019-12-31 00:31:51,763 - INFO - Epoch [1][3050/23454]	lr: 0.00050, eta: 1 day, 18:49:18, time: 0.435, data_time: 0.006, memory: 6814, loss_cls: 0.0954, loss_bbox: 5.3579, loss: 5.4533
2019-12-31 00:32:13,255 - INFO - Epoch [1][3100/23454]	lr: 0.00050, eta: 1 day, 18:47:47, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0920, loss_bbox: 5.1064, loss: 5.1984
2019-12-31 00:32:34,953 - INFO - Epoch [1][3150/23454]	lr: 0.00050, eta: 1 day, 18:46:42, time: 0.434, data_time: 0.006, memory: 6814, loss_cls: 0.0905, loss_bbox: 4.9328, loss: 5.0233
2019-12-31 00:32:56,524 - INFO - Epoch [1][3200/23454]	lr: 0.00050, eta: 1 day, 18:45:24, time: 0.431, data_time: 0.006, memory: 6814, loss_cls: 0.0887, loss_bbox: 5.5082, loss: 5.5969
2019-12-31 00:33:18,026 - INFO - Epoch [1][3250/23454]	lr: 0.00050, eta: 1 day, 18:44:00, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0952, loss_bbox: 5.4456, loss: 5.5408
2019-12-31 00:33:39,441 - INFO - Epoch [1][3300/23454]	lr: 0.00050, eta: 1 day, 18:42:29, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0876, loss_bbox: 5.2540, loss: 5.3416
2019-12-31 00:34:00,787 - INFO - Epoch [1][3350/23454]	lr: 0.00050, eta: 1 day, 18:40:53, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.1045, loss_bbox: 5.3024, loss: 5.4069
2019-12-31 00:34:22,604 - INFO - Epoch [1][3400/23454]	lr: 0.00050, eta: 1 day, 18:40:07, time: 0.436, data_time: 0.006, memory: 6814, loss_cls: 0.1003, loss_bbox: 5.2591, loss: 5.3595
2019-12-31 00:34:43,858 - INFO - Epoch [1][3450/23454]	lr: 0.00050, eta: 1 day, 18:38:25, time: 0.425, data_time: 0.006, memory: 6814, loss_cls: 0.0954, loss_bbox: 5.5484, loss: 5.6439
2019-12-31 00:35:05,366 - INFO - Epoch [1][3500/23454]	lr: 0.00050, eta: 1 day, 18:37:11, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.1047, loss_bbox: 5.2274, loss: 5.3321
2019-12-31 00:35:26,883 - INFO - Epoch [1][3550/23454]	lr: 0.00050, eta: 1 day, 18:35:59, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0887, loss_bbox: 5.3598, loss: 5.4485
2019-12-31 00:35:48,336 - INFO - Epoch [1][3600/23454]	lr: 0.00050, eta: 1 day, 18:34:42, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0925, loss_bbox: 5.4496, loss: 5.5421
2019-12-31 00:36:09,877 - INFO - Epoch [1][3650/23454]	lr: 0.00050, eta: 1 day, 18:33:36, time: 0.431, data_time: 0.006, memory: 6814, loss_cls: 0.0876, loss_bbox: 5.2397, loss: 5.3273
2019-12-31 00:36:31,260 - INFO - Epoch [1][3700/23454]	lr: 0.00050, eta: 1 day, 18:32:15, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.1078, loss_bbox: 4.8906, loss: 4.9984
2019-12-31 00:36:52,685 - INFO - Epoch [1][3750/23454]	lr: 0.00050, eta: 1 day, 18:31:00, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0947, loss_bbox: 5.7650, loss: 5.8596
2019-12-31 00:37:14,172 - INFO - Epoch [1][3800/23454]	lr: 0.00050, eta: 1 day, 18:29:52, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0798, loss_bbox: 5.4519, loss: 5.5317
2019-12-31 00:37:35,589 - INFO - Epoch [1][3850/23454]	lr: 0.00050, eta: 1 day, 18:28:39, time: 0.428, data_time: 0.006, memory: 6814, loss_cls: 0.0869, loss_bbox: 5.4921, loss: 5.5790
2019-12-31 00:37:57,229 - INFO - Epoch [1][3900/23454]	lr: 0.00050, eta: 1 day, 18:27:48, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0898, loss_bbox: 5.4224, loss: 5.5122
2019-12-31 00:38:18,889 - INFO - Epoch [1][3950/23454]	lr: 0.00050, eta: 1 day, 18:26:58, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0845, loss_bbox: 5.3786, loss: 5.4631
2019-12-31 00:38:40,325 - INFO - Epoch [1][4000/23454]	lr: 0.00050, eta: 1 day, 18:25:50, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0798, loss_bbox: 5.5536, loss: 5.6335
2019-12-31 00:39:01,949 - INFO - Epoch [1][4050/23454]	lr: 0.00050, eta: 1 day, 18:25:00, time: 0.432, data_time: 0.006, memory: 6814, loss_cls: 0.0873, loss_bbox: 5.2261, loss: 5.3134
2019-12-31 00:39:23,599 - INFO - Epoch [1][4100/23454]	lr: 0.00050, eta: 1 day, 18:24:12, time: 0.433, data_time: 0.006, memory: 6814, loss_cls: 0.0832, loss_bbox: 5.2777, loss: 5.3609
2019-12-31 00:39:45,091 - INFO - Epoch [1][4150/23454]	lr: 0.00050, eta: 1 day, 18:23:11, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0915, loss_bbox: 5.4730, loss: 5.5645
2019-12-31 00:40:06,463 - INFO - Epoch [1][4200/23454]	lr: 0.00050, eta: 1 day, 18:22:02, time: 0.427, data_time: 0.006, memory: 6814, loss_cls: 0.0689, loss_bbox: 5.8046, loss: 5.8735
2019-12-31 00:40:27,931 - INFO - Epoch [1][4250/23454]	lr: 0.00050, eta: 1 day, 18:21:02, time: 0.429, data_time: 0.006, memory: 6814, loss_cls: 0.0973, loss_bbox: 5.7275, loss: 5.8248
2019-12-31 00:40:49,436 - INFO - Epoch [1][4300/23454]	lr: 0.00050, eta: 1 day, 18:20:05, time: 0.430, data_time: 0.006, memory: 6814, loss_cls: 0.0880, loss_bbox: 5.1067, loss: 5.1947
Traceback (most recent call last):
  File "../../mmdetection/tools/train.py", line 108, in <module>
    main()
  File "../../mmdetection/tools/train.py", line 104, in main
    logger=logger)
  File "/home/user/repos/mmdetection1.3/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/user/repos/mmdetection1.3/mmdet/apis/train.py", line 225, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/models/detectors/base.py", line 92, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/models/detectors/single_stage.py", line 56, in forward_train
    x = self.extract_feat(img)
  File "/home/user/repos/mmdetection1.3/mmdet/models/detectors/single_stage.py", line 40, in extract_feat
    x = self.backbone(img)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/models/backbones/resnet.py", line 526, in forward
    x = res_layer(x)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/repos/mmdetection1.3/mmdet/models/backbones/resnet.py", line 264, in forward
    out = _inner_forward(x)
  File "/home/user/repos/mmdetection1.3/mmdet/models/backbones/resnet.py", line 249, in _inner_forward
    out = self.norm3(out)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/user/anaconda3/envs/mmdet2/lib/python3.7/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 7.80 GiB total capacity; 6.38 GiB already allocated; 23.25 MiB free; 602.65 MiB cached)

Process finished with exit code 1

**Comment by hellock** [comment]
Maybe 8G memory is just not enough. `memory` in the log is obtained with `torch.cuda.max_memory_cached()`, which is smaller than the output of `nvidia-smi`. Could you provide more cues?

**Comment by korabelnikov** [comment]
it may be but
how it can be that memory consumption grows in the middle of epoch?

**Comment by hellock** [comment]
During the same run, the memory is mainly affected by two factors: aspect ratio of images and number of gts. It usually reaches the maximum in the middle.
