### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 359: invalid continuation byte

### ISSUE THREAD

**Issue by ToBread** [open-mmlab/mmdetection#1960]
(mmlab) e520@e520-MS-7B18:~/PycharmProjects/ClassDetect/mmdetection$ python tools/train.py configs/cascade_rcnn_r50_fpn_1x.py --gpus 1
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 59, in main
    cfg = Config.fromfile(args.config)
  File "/home/e520/mmdetection/mmcv/mmcv/utils/config.py", line 97, in fromfile
    return Config(cfg_dict, filename=filename)
  File "/home/e520/mmdetection/mmcv/mmcv/utils/config.py", line 123, in __init__
    super(Config, self).__setattr__('_text', f.read())
  File "/home/e520/anaconda3/envs/mmlab/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 359: invalid continuation byte

**Comment by ToBread** [comment]
where's the bug

**Comment by hellock** [comment]
#1959

**Comment by yxy-lol** [comment]
> (mmlab) e520@e520-MS-7B18:~/PycharmProjects/ClassDetect/mmdetection$ python tools/train.py configs/cascade_rcnn_r50_fpn_1x.py --gpus 1
> Traceback (most recent call last):
> File "tools/train.py", line 124, in
> main()
> File "tools/train.py", line 59, in main
> cfg = Config.fromfile(args.config)
> File "/home/e520/mmdetection/mmcv/mmcv/utils/config.py", line 97, in fromfile
> return Config(cfg_dict, filename=filename)
> File "/home/e520/mmdetection/mmcv/mmcv/utils/config.py", line 123, in **init**
> super(Config, self).**setattr**('_text', f.read())
> File "/home/e520/anaconda3/envs/mmlab/lib/python3.7/codecs.py", line 322, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> 
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 359: invalid continuation byte

Did you solve this problem？

**Comment by skyerhxx** [comment]
I met the same problem and solved it. It is because I pasted the command directly copyed from my windows os. After I typed the command manually, it worked successfully.

Hope this can help.

**Comment by 1999luodi** [comment]
i have encountered this problems
Traceback (most recent call last):
  File "D:\luodi\code\python\mmdetection\tools\train.py", line 121, in <module>
    main()
  File "D:\luodi\code\python\mmdetection\tools\train.py", line 110, in main
    runner = Runner.from_cfg(cfg)
  File "D:\program\miniconda\envs\mmd\lib\site-packages\mmengine\runner\runner.py", line 462, in from_cfg
  File "D:\program\miniconda\envs\mmd\lib\site-packages\mmengine\runner\runner.py", line 376, in __init__
  File "D:\program\miniconda\envs\mmd\lib\site-packages\mmengine\runner\runner.py", line 716, in set_randomness
  File "D:\program\miniconda\envs\mmd\lib\site-packages\mmengine\runner\utils.py", line 71, in set_random_seed
    torch.manual_seed(seed)
  File "D:\program\miniconda\envs\mmd\lib\site-packages\torch\random.py", line 40, in manual_seed
    torch.cuda.manual_seed_all(seed)
  File "D:\program\miniconda\envs\mmd\lib\site-packages\torch\cuda\random.py", line 113, in manual_seed_all
    _lazy_call(cb, seed_all=True)
  File "D:\program\miniconda\envs\mmd\lib\site-packages\torch\cuda\__init__.py", line 172, in _lazy_call
    _lazy_seed_tracker.queue_seed_all(callable, traceback.format_stack())
  File "D:\program\miniconda\envs\mmd\lib\traceback.py", line 197, in format_stack
    return format_list(extract_stack(f, limit=limit))
  File "D:\program\miniconda\envs\mmd\lib\traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "D:\program\miniconda\envs\mmd\lib\traceback.py", line 366, in extract
    f.line
  File "D:\program\miniconda\envs\mmd\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "D:\program\miniconda\envs\mmd\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "D:\program\miniconda\envs\mmd\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "D:\program\miniconda\envs\mmd\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "D:\program\miniconda\envs\mmd\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 5851: invalid start byte
Change the encoding of the file to "utf-8" is useless
![image](https://github.com/user-attachments/assets/aa6113af-173e-413f-b505-cf9e47cd14d5)
Has anyone solved it？？
