### ISSUE TITLE
Read timed out.

### ISSUE THREAD

**Issue by yamioo** [open-mmlab/mmdetection#1978]
Hi, when I run "pip install -v -e . or pip install ." ,The following error occurred,do you kmow the reson,Look forward to your reply~  
<<<
Downloading https://files.pythonhosted.org/packages/88/95/90e8c4c31cfc67248bf944ba42029295b77159982f532c5689bcfe4e9108/torch-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (734.6MB)
     |██                              | 47.7MB 17kB/s eta 11:07:26ERROR: Exception:
Traceback (most recent call last):
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sunr/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.  >>>

**Comment by ZwwWayne** [comment]
Please read the error log, the pip does download `torch` package but failed. Try several times or other methods to install `pytorch`.

**Comment by ZwwWayne** [comment]
The issue is closed because the issue is answered and not related to the codebase. Feel free to reopen it if you have any further questions.
