### ISSUE TITLE
RuntimeError: No state_dict found in checkpoint file

### ISSUE THREAD

**Issue by ChutianXu0922** [open-mmlab/mmdetection#1991]
Hello! I got problems when I tried to test a dataset.

I created a folder named checkpoint and downloaded the checkpoint from [MODEL_ZOO.md](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/MODEL_ZOO.md). Then I used the command with docker in order to train it.

`sudo docker run --rm -it -v $(pwd):/$(pwd) -w $(pwd) --name cascademask cascademask python tools/test.py configs/mask_rcnn_r50_fpn_1x.py checkpoint/e2e_mask_rcnn_R_50_FPN_1x.pth --out results.pkl --eval bbox segm`

However, it turned out to be a RuntimeError: No state_dict found in checkpoint file. The whole message is:

loading annotations into memory...
Done (t=0.68s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/test.py", line 282, in <module>
    main()
  File "tools/test.py", line 231, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 177, in load_checkpoint
    'No state_dict found in checkpoint file {}'.format(filename))
RuntimeError: No state_dict found in checkpoint file checkpoint/e2e_mask_rcnn_R_50_FPN_1x.pth

I searched the existing issues as well as the internet, but I cannot solve the problem.
I am very grateful if anyone can help me.

**Comment by ChutianXu0922** [comment]
I found the reason is that I used the checkpoint provided by MaskRCNN rather than that provided in this project, which is not matched. Thank you for your work!
