### ISSUE TITLE
Correct way for single machine multi-gpu training

### ISSUE THREAD

**Issue by xpngzhng** [open-mmlab/mmdetection#1992]
As the [GETTING_STARTED.md#train-with-multiple-gpus](https://github.com/open-mmlab/mmdetection/blob/master/docs/GETTING_STARTED.md#train-with-multiple-gpus) says, we can launch single machine multi-gpu training using [tools/dist_train.sh](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh) and the training goes well.

I have two questions:

- In single machine multi-gpu training, does the argument `gpus` in [tools/train.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py) become useless?

I try command 
`CUDA_VISIBLE_DEVICES="0,1,2,3" PORT="29500" bash tools/dist_train.sh configs/ms_rcnn/ms_rcnn_r50_caffe_fpn_1x.py 4 --validate --gpus 2`
`nvidia-smi` shows 4 gpus are running
I try command
`CUDA_VISIBLE_DEVICES="0,1,2,3" PORT="29500" bash tools/dist_train.sh configs/ms_rcnn/ms_rcnn_r50_caffe_fpn_1x.py 2 --validate --gpus 4`
`nvidia-smi` shows 2 gpus are running

- Is [tools/dist_train.sh](https://github.com/open-mmlab/mmdetection/blob/master/tools/dist_train.sh) the only way for single machine multi-gpu training ?

I try command 
`python3 tools/train.py configs/ms_rcnn/ms_rcnn_r50_caffe_fpn_1x.py --gpus 4`
for multi-gpu training, but encounter error like this
```
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/local/mmdetection/mmdet/apis/train.py", line 133, in train_detector
    timestamp=timestamp)
  File "/local/mmdetection/mmdet/apis/train.py", line 319, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 267, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/local/mmdetection/mmdet/apis/train.py", line 100, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    for k in out))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 62, in <genexpr>
    for k in out))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py", line 67, in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/_functions.py", line 67, in <lambda>
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
IndexError: dimension specified as 0 but tensor has no dimensions
```

**Comment by ZwwWayne** [comment]
1. The option `--gpu` is only applicable to non-distributed training, as you can find the instruction [here](https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L28).
2. The code should support the non-distributed training, this might be a bug to be fixed. You could just use dist_train.sh if you can for now.
