### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by melikovk** [open-mmlab/mmdetection#2015]
I try to install using 

pip install --user -v -e .

**Environment**

When I try to run python tools/collect_env.py I get an error
```
Traceback (most recent call last):
  File "tools/collect_env.py", line 8, in <module>
    import torch
  File "/usr/lib/python3.8/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /usr/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch4cuda4nccl6detail16throw_nccl_errorE12ncclResult_t
```
**Error traceback**
when i run pip install --user -v -e .
I get the following error message

```
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kamran/workspace/mmdetection/setup.py", line 9, in <module>
        import torch
      File "/usr/lib/python3.8/site-packages/torch/__init__.py", line 81, in <module>
        from torch._C import *
    ImportError: /usr/lib/python3.8/site-packages/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch4cuda4nccl6detail16throw_nccl_errorE12ncclResult_t
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
and some additional output in stdout
```
Created temporary directory: /tmp/pip-ephem-wheel-cache-g9grd8_p
Created temporary directory: /tmp/pip-req-tracker-_a8b4enr
Created requirements tracker '/tmp/pip-req-tracker-_a8b4enr'
Created temporary directory: /tmp/pip-install-m6xtqzz7
Obtaining file:///home/kamran/workspace/mmdetection
  Added file:///home/kamran/workspace/mmdetection to build tracker '/tmp/pip-req-tracker-_a8b4enr'
    Running setup.py (path:/home/kamran/workspace/mmdetection/setup.py) egg_info for package from file:///home/kamran/workspace/mmdetection
Cleaning up...
Removed file:///home/kamran/workspace/mmdetection from build tracker '/tmp/pip-req-tracker-_a8b4enr'
Removed build tracker '/tmp/pip-req-tracker-_a8b4enr'
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 381, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 294, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 257, in prepare_editable_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3.8/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/usr/lib/python3.8/site-packages/pip/_internal/operations/generate_metadata.py", line 121, in _generate_metadata_legacy
    call_subprocess(
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Thank you

**Comment by melikovk** [comment]
Sorry for rush posting. This is unrelated to MMDetection, but a problem with my recent pytorch upgrade, since I get same error just trying to import torch.

**Comment by tianwen0110** [comment]
so how you solve this problom? I met a same one
