### ISSUE TITLE
Remove opencv-python as an installation requirement

### ISSUE THREAD

**Issue by prateek-77** [open-mmlab/mmdetection#2033]
I'm working on a system that does not allow **pip install opencv-python**. I am unable to install mmdetection on my system, because opencv-python is a requirement of setup.py file.
I won't be using opencv in my work, so is there any way I can complete the installation without installing opencv-python? (**remove it as a requirement maybe?**)

I tried this: https://github.com/open-mmlab/mmdetection/issues/445#issue-425739212
But it doesn't work.

Error Traceback (after executing **pip install -v -e .**)
```
1 location(s) to search for versions of opencv-python:
* https://pypi.org/simple/opencv-python/
Fetching project page and analyzing links: https://pypi.org/simple/opencv-python/
Getting page https://pypi.org/simple/opencv-python/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/opencv-python/" in the cache
Request header has "max_age" as 0, cache bypassed
https://pypi.org:443 "GET /simple/opencv-python/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: cp27-cp27m-macosx_10_10_intel, cp27-cp27m-macosx_10_10_x86_64, cp27-cp27m-macosx_10_6_intel, cp27-cp27m-macosx_10_9_intel, cp27-cp27m-macosx_10_9_x86_64: https://files.pythonhosted.org/packages/e3/09/6d175ca54a4fd3072b4575e971140ced19a96fffe75828358c72b29c6147/opencv_python-3.1.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#sha256=d316c9660ed5f2625a69425c52d391dedd4df3fef11f2ed50dcce97f3e567827 (from https://pypi.org/simple/opencv-python/)
  Skipping link: none of the wheel's tags match: cp27-cp27m-manylinux1_i686: https://files.pythonhosted.org/packages/42/64/fabb6af7858c346cf946deccbadee9b7fb2bb38d18d1b7de12b87675ce50/opencv_python-3.1.0.0-cp27-cp27m-manylinux1_i686.whl#sha256=4ba17d5ce5c7f3ad39c50ce46c3c6af0bf2d77df6382840310352e0d9dd9be8a (from https://pypi.org/simple/opencv-python/)
.
.
.
Given no hashes to check 0 links for project 'opencv-python': discarding no candidates
ERROR: Could not find a version that satisfies the requirement opencv-python>=3 (from mmcv>=0.2.15->mmdet==1.0rc1+f96e57d) (from versions: none)
Cleaning up...
  Removing source in /tmp/pip-install-8jmtj1ww/mmcv
  Removing source in /tmp/pip-install-8jmtj1ww/terminaltables
Removed build tracker: '/tmp/pip-req-tracker-fs0w87le'
ERROR: No matching distribution found for opencv-python>=3 (from mmcv>=0.2.15->mmdet==1.0rc1+f96e57d)
Exception information:
Traceback (most recent call last):
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/users/student21/.conda/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for opencv-python>=3 (from mmcv>=0.2.15->mmdet==1.0rc1+f96e57d)
```

Thanks!

**Comment by hellock** [comment]
opencv-python is a dependency of MMCV. If you are sure you want to ignore opencv-python, you may comment [these lines](https://github.com/open-mmlab/mmcv/blob/master/setup.py#L36-L39) and install MMCV again.

**Comment by prateek-77** [comment]
Cool, thanks a lot!
