### ISSUE TITLE
AssertionError:assert isinstance(cfg, dict) and 'type' in cfg

### ISSUE THREAD

**Issue by tcexeexe** [open-mmlab/mmdetection#2038]
![image](https://user-images.githubusercontent.com/28287196/73583877-821bcb00-44cf-11ea-9637-ad6a4a5741ac.png)
What caused this error..Is there any solution?

**Comment by tcexeexe** [comment]
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    model_ensemble = get_model(config, model_dir)
  File "main.py", line 6, in get_model
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/detectors/cascade_rcnn.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/builder.py", line 19, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/backbones/resnet.py", line 427, in __init__
    gen_attention_blocks=stage_with_gen_attention[i])
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/backbones/resnet.py", line 284, in make_res_layer
    (0 in gen_attention_blocks) else None))
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/backbones/resnet.py", line 168, in __init__
    bias=False)
  File "/home/tcexeexe/git/mmdetection-master/mmdet/models/utils/conv_module.py", line 33, in build_conv_layer
    assert isinstance(cfg, dict) and 'type' in cfg
AssertionError

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by tcexeexe** [comment]
> Please follow the `Error report` issue template.

OK,but l've solve this problem by add  type='DCN' in config.py

**Comment by lyp19921126** [comment]
I also meet the same problem  is any solution?

**Comment by tcexeexe** [comment]
> I also meet the same problem is any solution?

have you try add " type='DCN'  "?

**Comment by lyp19921126** [comment]
where i add this type? is in the mmcv's config.py?

**Comment by AlaylmYC** [comment]
I also solve this problem by adding type='DCN' in config.py

before:
        dcn=dict(
            modulated=False,
            groups=32,
            deformable_groups=1,
            fallback_on_stride=False),

after:
        dcn=dict(
            #modulated=False,
            #groups=32,
            type='DCN',
            deformable_groups=1,
            fallback_on_stride=False),

**Comment by AlaylmYC** [comment]
> where i add this type? is in the mmcv's config.py?

before:
dcn=dict(
modulated=False,
groups=32,
deformable_groups=1,
fallback_on_stride=False),

after:
dcn=dict(
#modulated=False,
#groups=32,
type='DCN',
deformable_groups=1,
fallback_on_stride=False),

**Comment by lyp19921126** [comment]
OK, thanks I will try.

**Comment by 237014845** [comment]
I loaded the pretraining model of reppoints_moment_x101_dcn_fpn_2x_mt.py to train my dataset. Why can't I train DCN without type= 'DCN' in config, and can't I load DCN part of the pretrained model with type= 'DCN' @hellock
