### ISSUE TITLE
"fp16 = dict(loss_scale=512.)" get error when use several GPU

### ISSUE THREAD

**Issue by TangDL** [open-mmlab/mmdetection#2057]
when I add this code "fp16 = dict(loss_scale=512.)" in config file, and only use one

GPU  to train the model, it runs ok. But when I run the model in serval GPU, it report a error as follow:
"Traceback (most recent call last):
  File "/data2/TDL/paper_fabric/code/mmdetection/tools/train.py", line 112, in <module>
    main()
  File "/data2/TDL/paper_fabric/code/mmdetection/tools/train.py", line 108, in main
    logger=logger)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/core/fp16/decorators.py", line 75, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/models/detectors/base.py", line 117, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 188, in forward_train
    x = self.extract_feat(img)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 116, in extract_feat
    x = self.backbone(img)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/models/backbones/resnet.py", line 524, in forward
    x = self.norm1(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/TDL/paper_fabric/code/mmdetection/mmdet/core/fp16/hooks.py", line 122, in new_forward
    **cast_tensor_type(kwargs, src_type, dst_type))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_batch_norm)

Process finished with exit code 1"
anyone help?

**Comment by ZwwWayne** [comment]
Please use `Error Template`. We cannot do much help here since we have very limited information.
This might because the input of BN and the weights of BN layer are not in the same GPU, please check your code or scripts.

**Comment by milleniums** [comment]
how to resolve this problem?

**Comment by CarryHJR** [comment]
move to mmdet 1.2.0 or mmdet 2.x, mmdet 1.0 has this bug when no-dist multi-gpu training
