### ISSUE TITLE
validate error in dist_train

### ISSUE THREAD

**Issue by breezelj** [open-mmlab/mmdetection#2065]
the validation has an error after training one epoch, but I have no idea how to debug in "mmdet/core/evaluation/eval_hooks.py", the error information show below, could you give some advice about this error., thanks

2020-02-08 10:11:46,927 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2020-02-08 10:12:13,710 - mmdet - INFO - Epoch [1][50/250]	lr: 0.00399, eta: 0:26:19, time: 0.536, data_time: 0.138, memory: 3446, loss_rpn_cls: 0.2191, loss_rpn_bbox: 0.1022, loss_cls: 0.4013, acc: 94.1387, loss_bbox: 0.0813, loss: 0.8039
2020-02-08 10:12:32,293 - mmdet - INFO - Epoch [1][100/250]	lr: 0.00465, eta: 0:21:55, time: 0.371, data_time: 0.003, memory: 3446, loss_rpn_cls: 0.1309, loss_rpn_bbox: 0.0939, loss_cls: 0.2082, acc: 96.6807, loss_bbox: 0.0850, loss: 0.5180
2020-02-08 10:12:51,090 - mmdet - INFO - Epoch [1][150/250]	lr: 0.00532, eta: 0:20:18, time: 0.376, data_time: 0.003, memory: 3446, loss_rpn_cls: 0.1256, loss_rpn_bbox: 0.0649, loss_cls: 0.2035, acc: 96.5742, loss_bbox: 0.0845, loss: 0.4785
2020-02-08 10:13:09,927 - mmdet - INFO - Epoch [1][200/250]	lr: 0.00599, eta: 0:19:21, time: 0.377, data_time: 0.003, memory: 3446, loss_rpn_cls: 0.1214, loss_rpn_bbox: 0.0770, loss_cls: 0.2022, acc: 96.5303, loss_bbox: 0.0874, loss: 0.4881
2020-02-08 10:13:28,755 - mmdet - INFO - Epoch [1][250/250]	lr: 0.00665, eta: 0:18:40, time: 0.377, data_time: 0.003, memory: 3446, loss_rpn_cls: 0.1123, loss_rpn_bbox: 0.0662, loss_cls: 0.1758, acc: 96.8154, loss_bbox: 0.0791, loss: 0.4335
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1000/1000, 54.2 task/s, elapsed: 18s, ETA:     0s

Traceback (most recent call last):
  File "./tools/train.py", line 126, in <module>
    main()
  File "./tools/train.py", line 122, in main
    timestamp=timestamp)
  File "/media/data1/jliang_data/detection/temp/mmdetection/mmdet/apis/train.py", line 103, in train_detector
    timestamp=timestamp)
  File "/media/data1/jliang_data/detection/temp/mmdetection/mmdet/apis/train.py", line 250, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 277, in train
    self.call_hook('after_train_epoch')
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 230, in call_hook
    getattr(hook, fn_name)(self)
  File "/media/data1/jliang_data/detection/temp/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 60, in after_train_epoch
    tmp_results = mmcv.load(tmp_file)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/fileio/io.py", line 40, in load
    obj = handler.load_from_path(file, **kwargs)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/fileio/handlers/pickle_handler.py", line 13, in load_from_path
    filepath, mode='rb', **kwargs)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.15-py3.7-linux-x86_64.egg/mmcv/fileio/handlers/base.py", line 21, in load_from_path
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/data1/jliang_data/detection/temp/mmdetection/work_dirs/faster_rcnn_r50_caffe_c4_1x_selsa/temp_1.pkl'
Traceback (most recent call last):
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/jliang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jliang/miniconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/faster_rcnn_r50_caffe_c4_1x_selsa.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.

**Comment by ZwwWayne** [comment]
Hi @breezelj ,
From the bug error `FileNotFoundError: [Errno 2] No such file or directory: '/media/data1/jliang_data/detection/temp/mmdetection/work_dirs/faster_rcnn_r50_caffe_c4_1x_selsa/temp_1.pkl'`, it seems that the temporary file saved by multiple GPUs for evaluation is missing. You might need to check whether the path is correct or why the file is mising.

**Comment by breezelj** [comment]
@ZwwWayne thanks your reply. but the validation run only when running the dist_train.sh, I can not debug line by line in the  "mmdet/core/evaluation/eval_hooks.py". could you give some ideas to help to dubug it.

**Comment by ZwwWayne** [comment]
Since the model is saved, you can use dist_test.sh to test that checkpoint, i.e., epoch_1.pth,  and see what happens, it should appear the same behavior as the evaluation during training.

**Comment by breezelj** [comment]
sorry for late reply, thanks your advice, I will try it.

**Comment by dreamitpossible1** [comment]
2020-10-15 13:30:12,324 - mmdet - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "D:\tf_train\mmdetection\mmdet\apis\train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\dist_utils.py", line 94, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\hooks\checkpoint.py", line 52, in after_train_epoch
    self.out_dir, save_optimizer=self.save_optimizer, **self.args)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 172, in save_checkpoint
    shutil.copy(filename, dst_file)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\dw\Anaconda3\envs\CentripetalNet\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'epoch_1.pth'
I have encountered the same problem. Have you solved it?@breezelj

**Comment by Mio2020** [comment]
@dreamitpossible1
https://github.com/open-mmlab/mmdetection/issues/2865#issuecomment-636614625

I change the configs/_base_/default_runtime Line 1 to :
`checkpoint_config = dict(interval=1, create_symlink=False)`

And have solved it. Windows 10, mmdetection2.6+
