### ISSUE TITLE
Bug when running voc_eval.py on my own dataset

### ISSUE THREAD

**Issue by wwetnaroh** [open-mmlab/mmdetection#2074]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/gxt/anaconda3/envs/MMDETECTION/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/gxt/anaconda3/envs/MMDETECTION/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/gxt/mmdetection/mmdet/core/evaluation/mean_ap.py", line 203, in tpfp_default
    ious = bbox_overlaps(det_bboxes, gt_bboxes)
  File "/home/gxt/mmdetection/mmdet/core/evaluation/bbox_overlaps.py", line 38, in bbox_overlaps
    area2 = (bboxes2[:, 2] - bboxes2[:, 0] + 1) * (
IndexError: too many indices for array
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/gxt/mmdetection/tools/voc_eval.py", line 48, in <module>
    main()
  File "/home/gxt/mmdetection/tools/voc_eval.py", line 44, in main
    voc_eval(args.result, test_dataset, args.iou_thr, args.nproc)
  File "/home/gxt/mmdetection/tools/voc_eval.py", line 24, in voc_eval
    nproc=nproc)
  File "/home/gxt/mmdetection/mmdet/core/evaluation/mean_ap.py", line 329, in eval_map
    [area_ranges for _ in range(num_imgs)]))
  File "/home/gxt/anaconda3/envs/MMDETECTION/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/gxt/anaconda3/envs/MMDETECTION/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: too many indices for array

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.

**Comment by hellock** [comment]
You may just use the latest version of mmdetection, which removes `tools/voc_eval.py` and provide a unified tool for testing and evaluating all datasets.
