### ISSUE TITLE
Docker Error of MMdetection of earlier version

### ISSUE THREAD

**Issue by SuckChen** [open-mmlab/mmdetection#2095]
Thanks for your error report and we appreciate it a lot.
**my Dockerfile**
```
ARG PYTORCH="1.1.0"
ARG CUDA="10.0"
ARG CUDNN="7.5"
FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender-dev libxext6

# Install mmdetection
RUN conda install cython -y
COPY ./tianchi /tianchi
WORKDIR /tianchi
RUN ls
RUN pip install -e .
CMD ["sh", "run.sh"]
```

**Error traceback**
I used this dockerfile to build a docker successfully when the mmdetection is  not updated.
error happens  at pip install -e .
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tianchi/setup.py", line 171, in <module>
        sources=['src/compiling_info.cpp']),
      File "/tianchi/setup.py", line 101, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile MMDetection!')
    OSError: CUDA is required to compile MMDetection!
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by heartInsert** [comment]
There is  no  doubt  you  are   taking  part in  Tianchi .

**Comment by hellock** [comment]
Should have been fixed.
