### ISSUE TITLE
How to test the model on COCO test-dev set 2017 with single GPU?

### ISSUE THREAD

**Issue by xuanthuyvo** [open-mmlab/mmdetection#2104]
I want to test model on test-dev set, but the code https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py is only for testing on validation set (5000 images):

python tools/test.py configs/mymodel.py checkpoints/mymodel.pth results.pkl --eval bbox

So, I have a question: How to test the model on COCO test-dev set 2017 with single GPU to submit the json file to codalab server?
I'm looking forward from you. Thank you for your great work!

**Comment by ZwwWayne** [comment]
Remove the `--eval bbox`, change the data path to be the test set in the config file, and set the output to be JSON file.

**Comment by xuanthuyvo** [comment]
Thank you for your reply. You mean:
**python tools/test.py data/coco/test2017 checkpoints/mymodel.pth results.json** 
@ZwwWayne: Is the code right or wrong?

**Comment by xuanthuyvo** [comment]
@ZwwWayne I changed the data path to be the test set in the config file, but it's still not working. could you show the information details about it?

**Comment by xuanthuyvo** [comment]
CUDA_VISIBLE_DEVICES=1 python tools/test.py configs/model.py checkpoints/mymodel/epoch_12.pth --out results.pkl
loading annotations into memory...
Done (t=0.33s)
creating index...
index created!
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 282, in <module>
    main()
  File "tools/test.py", line 241, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 24, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/codepro/thuy/mmdetection/mmdet/datasets/custom.py", line 129, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/codepro/thuy/mmdetection/mmdet/datasets/custom.py", line 152, in prepare_test_img
    return self.pipeline(results)
  File "/home/codepro/thuy/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/codepro/thuy/mmdetection/mmdet/datasets/pipelines/loading.py", line 22, in __call__
    img = mmcv.imread(filename)
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/mmcv/image/io.py", line 42, in imread
    'img file does not exist: {}'.format(img_or_path))
  File "/home/codepro/miniconda3/envs/thuy/lib/python3.7/site-packages/mmcv/utils/path.py", line 33, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: data/coco/test2017/000000397133.jpg
