### ISSUE TITLE
Error before training starts - KeyError: 'proposals'

### ISSUE THREAD

**Issue by ahsan44411** [open-mmlab/mmdetection#2121]
I am using a **custom COCO dataset** and the **config file "libra_fast_rcnn_r50_fpn_1x"** with **two classes** tumor and background.
Before the training even starts I get this error and I can not work around this. Kindly help.
**Using colab to run mmdetection.**

Traceback (most recent call last):
  File "/content/mmdetection/tools/train.py", line 143, in <module>
    main()
  File "/content/mmdetection/tools/train.py", line 139, in main
    meta=meta)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 305, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 271, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 132, in __getitem__
    data = self.prepare_train_img(idx)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 145, in prepare_train_img
    return self.pipeline(results)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.0.0+7473533-py3.6-linux-x86_64.egg/mmdet/datasets/pipelines/loading.py", line 126, in __call__
    proposals = results['proposals']
KeyError: 'proposals'

**Comment by OceanPang** [comment]
@ahsan44411 Hi, I just use the latest mmcv and mmdetection to run the model and there is no error occur. Can you try to use the latest code and re-run the config to see what will happend? Please make sure to provide a proposal file to your data loader.

**Comment by wtt848** [comment]
I also encountered the same problem, how to solve it?

**Comment by wtt848** [comment]
I also encountered the same problem, how to solve it?

**Comment by tiberium24** [comment]
> @ahsan44411 Hi, I just use the latest mmcv and mmdetection to run the model and there is no error occurs. Can you try to use the latest code and re-run the config to see what will happen? Please make sure to provide a proposal file to your data loader.

@OceanPang @hellock What is the proposal file you are mentioning? 
I am stuck in the same thing.
