### ISSUE TITLE
RuntimeError: invalid argument 0:

### ISSUE THREAD

**Issue by deloious** [open-mmlab/mmdetection#2141]
When i train   my own dataset ,the error occurred! Can someone help me with the problem? Thanks !!!
The problem is :

Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/apis/train.py", line 305, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 275, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/models/detectors/base.py", line 137, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 231, in forward_train
    feats=[lvl_feat[j][None] for lvl_feat in x])
  File "/cache/user-job-dir/codes/mmdetection/mmdet/core/bbox/samplers/base_sampler.py", line 75, in sample
    assign_result.add_gt_(gt_labels)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/core/bbox/assigners/assign_result.py", line 192, in add_gt_
    self.labels = torch.cat([gt_labels, self.labels])
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 1 and 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62

By the way ,my dataset is like coco dataset. Thanks ,anyway!

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
