### ISSUE TITLE
CUDA error: an illegal memory access was encountered still exists for RoiPool

### ISSUE THREAD

**Issue by liyiwei979621500** [open-mmlab/mmdetection#2145]
**Describe the bug**
CUDA error: an illegal memory access was encountered still exists when using roi pooling

**Reproduction**
```
CUDA_LAUNCH_BLOCKING=1 python tools/train.py configs/da-faster-rcnn/da_faster_rcnn_vgg_citiscape_foggy_citiscape.py
```
with config
```
roi_layer=dict(type='RoIPool', out_size=7),
```

**Error traceback**
```
THCudaCheck FAIL file=mmdet/ops/roi_pool/src/roi_pool_kernel.cu line=155 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/home/lyw/da-faster-rcnn-mmdet/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/home/lyw/da-faster-rcnn-mmdet/mmdet/apis/train.py", line 305, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 282, in train
    self.call_hook('after_train_iter')
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 238, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 18, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 77, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 189, in wrapper
    outputs = fn(ctx, *args)
  File "/home/lyw/da-faster-rcnn-mmdet/mmdet/ops/roi_pool/roi_pool.py", line 45, in backward
    spatial_scale, grad_input)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at mmdet/ops/roi_pool/src/roi_pool_kernel.cu:155
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered (insert_events at /opt/conda/conda-bld/pytorch_1565272271120/work/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f3539924e37 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x12e14 (0x7f3539b5ce14 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x165bf (0x7f3539b605bf in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x74 (0x7f353990ffa4 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x141ece4 (0x7f34d2f6dce4 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x31b3ca0 (0x7f34d4d02ca0 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x3765dc2 (0x7f34d52b4dc2 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f34d52b4e6f in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: <unknown function> + 0x3782a61 (0x7f34d52d1a61 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: c10::TensorImpl::release_resources() + 0x20 (0x7f353990ff50 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #10: <unknown function> + 0x1bb014 (0x7f3539f2d014 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x40142b (0x7f353a17342b in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x401461 (0x7f353a173461 in /home/lyw/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xf0 (0x7f353e5ff830 in /lib/x86_64-linux-gnu/libc.so.6)
```

**Bug fix**
by using roi align 
```
roi_layer=dict(type='RoIAlign', out_size=7),
```
or using the torchvision roi pool
```
roi_layer=dict(type='RoIPool', out_size=7, use_torchvision=True),
```
can avoid this error

**Comment by tankche1** [comment]
Same error. Thanks!

**Comment by xvjiarui** [comment]
Hi @liyiwei979621500 , thanks for pointing out. 
Could you please try [this](https://github.com/xvjiarui/mmdetection/commit/c30e7f2a81ec5741eb64a84b5c83a2980f41cbfe)?

**Comment by liyiwei979621500** [comment]
@xvjiarui Sure, I will try as soon as my gpu is free.

**Comment by liyiwei979621500** [comment]
@xvjiarui Can not reproduce this error.Somehow it just gone.
