### ISSUE TITLE
libpng error: Read Erro  ；AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by deloious** [open-mmlab/mmdetection#2147]
My data is .png pictures,when i train them with mmdetection ,an error occurred!

libpng error: Read Error
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/apis/train.py", line 305, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/anaconda3/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/work/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/cache/user-job-dir/codes/mmdetection/mmdet/datasets/custom.py", line 132, in __getitem__
    data = self.prepare_train_img(idx)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/datasets/custom.py", line 145, in prepare_train_img
    return self.pipeline(results)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/cache/user-job-dir/codes/mmdetection/mmdet/datasets/pipelines/loading.py", line 28, in __call__
    results['img_shape'] = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

Can mmdetection train .png pictures? how to solved it ? thanks!!!!!

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
