### ISSUE TITLE
Can category_id larger than num_classes？

### ISSUE THREAD

**Issue by Xudong-Yan** [open-mmlab/mmdetection#2161]
I want to train a model only detect one category(`num_classes=2`) from coco dataset, such as `category_id = 79`.
So  I removed another category,  and only reserve annotations that `category_id = 79`.
But  I got an error when training:
```
Traceback (most recent call last):
  File "/home/asus/Documents/Xudong/mmdetection/tools/train.py", line 124, in <module>
    main()
  File "/home/asus/Documents/Xudong/mmdetection/tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/apis/train.py", line 133, in train_detector
    timestamp=timestamp)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/apis/train.py", line 319, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/apis/train.py", line 100, in batch_processor
    losses = model(**data)
  File "/home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/models/detectors/base.py", line 138, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 253, in forward_train
    loss_bbox = bbox_head.loss(cls_score, bbox_pred, *bbox_targets)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/asus/Documents/Xudong/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 120, in loss
    if pos_inds.any():
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fed6242fdc5 in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14792 (0x7fed5f481792 in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x50 (0x7fed6241f640 in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x3067fb (0x7fed5fba07fb in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x14019b (0x7fed9144c19b in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x3bfc84 (0x7fed916cbc84 in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3bfcd1 (0x7fed916cbcd1 in /home/asus/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x19dfce (0x560444a1bfce in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #8: <unknown function> + 0x113a6b (0x560444991a6b in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #9: <unknown function> + 0x113bc7 (0x560444991bc7 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #10: <unknown function> + 0x103948 (0x560444981948 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #11: <unknown function> + 0x114267 (0x560444992267 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #12: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #13: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #14: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #15: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #16: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #17: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #18: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #19: <unknown function> + 0x11427d (0x56044499227d in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #20: PyDict_SetItem + 0x502 (0x5604449dd602 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #21: PyDict_SetItemString + 0x4f (0x5604449de0cf in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #22: PyImport_Cleanup + 0x9e (0x560444a1d91e in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #23: Py_FinalizeEx + 0x67 (0x560444a93367 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #24: <unknown function> + 0x227d93 (0x560444aa5d93 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #25: _Py_UnixMain + 0x3c (0x560444aa60bc in /home/asus/anaconda3/envs/open-mmlab/bin/python)
frame #26: __libc_start_main + 0xf0 (0x7feda985d830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #27: <unknown function> + 0x1d0990 (0x560444a4e990 in /home/asus/anaconda3/envs/open-mmlab/bin/python)
```
It looks like something wrong at compute bbox_loss, so I try to convert `category_id` form 79 to 1.
Then the error disappeared. So my question is:
**Whether  `category_id` can't be larger than `num_classes` ?**
Thanks

**Comment by ZwwWayne** [comment]
No, because the `category_id` will be used as labels to train the classifier, if you make the `category_id` larger than the `num_classes`, it will cause the bug during the classification loss calculation.
