### ISSUE TITLE
I used mmdet to train my data, the data type was voc format, the image size was 1920x1080, and the error was reported in the data processing stage

### ISSUE THREAD

**Issue by 237014845** [open-mmlab/mmdetection#2171]
Traceback (most recent call last):
  File "./tools/train.py", line 125, in <module>
    main()
  File "./tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/apis/train.py", line 125, in train_detector
    timestamp=timestamp)
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/apis/train.py", line 272, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/datasets/dataset_wrappers.py", line 52, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/datasets/custom.py", line 131, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/datasets/custom.py", line 144, in prepare_train_img
    return self.pipeline(results)
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/hs/hao/contextnet/ctfpnres/mmdet/datasets/pipelines/transforms.py", line 645, in __call__
    if overlaps.min() < min_iou:
  File "/home/hs/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity

^CTraceback (most recent call last):
  File "/home/hs/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hs/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/hs/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 239, in main
    process.wait()
  File "/home/hs/anaconda3/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/home/hs/anaconda3/lib/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/hs/anaconda3/lib/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

anyone can help me？

**Comment by ZwwWayne** [comment]
Hi @237014845 ,
This might because the bounding box is empty and you might need to filter the images with no GT.

**Comment by ZwwWayne** [comment]
Some similar discussions can be found [here](https://github.com/matterport/Mask_RCNN/issues/47).
