### ISSUE TITLE
Question about the trainning of ssd300_coco.py

### ISSUE THREAD

**Issue by ztyxd** [open-mmlab/mmdetection#2173]
I use the ssd300_coco.py while getting the following problem. But the ssd300_voc.py can work well.

`loading annotations into memory...
Done (t=1.15s)
creating index...
index created!
2020-02-28 22:54:16,206 - INFO - Start running, host: gpuserver@sys, work_dir: /media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/work_dirs/ssd300_hbb_coco
2020-02-28 22:54:16,206 - INFO - workflow: [('train', 1)], max: 24 epochs
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/mmcv/runner/runner.py", line 275, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/models/detectors/base.py", line 175, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/models/detectors/single_stage.py", line 59, in forward_train
    x = self.extract_feat(img)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/models/detectors/single_stage.py", line 40, in extract_feat
    x = self.backbone(img)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/gpuserver/e9a52ecb-e4bc-47ad-8f48-6184e3d580ee/xaserver/zty/AerialDetection-master/mmdet/models/backbones/ssd_vgg.py", line 99, in forward
    x = layer(x)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gpuserver/anaconda3/envs/zty_obb/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
`
Can anyone give me some suggestion about this problem?

**Comment by yhcao6** [comment]
Please use the `Error report` issue template.
