### ISSUE TITLE
train with background bug

### ISSUE THREAD

**Issue by abcxs** [open-mmlab/mmdetection#2192]
There may be a problem when training maskrcnn with backgournd.
[here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L159)
The variable **masks** will be [], and np.stack([]) will raise a error.
![image](https://user-images.githubusercontent.com/13503336/75666858-88a98800-5cb1-11ea-8da8-ab13170573e9.png)

**Comment by ZwwWayne** [comment]
Thanks for your bug report.
Would you like to create a PR to fix that?

**Comment by LiangHann** [comment]
After I update the transform.py file to the fixed one, even though there is no "at least one array to stack", but the following error happens:
Traceback (most recent call last):
  File "./tools/train.py", line 144, in <module>
    main()
  File "./tools/train.py", line 140, in main
    meta=meta)
  File "/home/pichao.wang/mmdetection/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/home/pichao.wang/mmdetection/mmdet/apis/train.py", line 177, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/mmcv/runner/runner.py", line 371, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/mmcv/runner/runner.py", line 275, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/pichao.wang/mmdetection/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pichao.wang/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/pichao.wang/mmdetection/mmdet/models/detectors/base.py", line 137, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/pichao.wang/mmdetection/mmdet/models/detectors/htc.py", line 296, in forward_train
    semantic_feat)
  File "/home/pichao.wang/mmdetection/mmdet/models/detectors/htc.py", line 104, in _mask_forward_train
    mask_pred = mask_head(mask_feats, last_feat, return_feat=False)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pichao.wang/mmdetection/mmdet/models/mask_heads/htc_mask_head.py", line 35, in forward
    x = self.upsample(x)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pichao.wang/anaconda3/envs/htc/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 778, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

How to deal with this problem?

**Comment by LiangHann** [comment]
> There may be a problem when training maskrcnn with backgournd.
> [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L159)
> The variable **masks** will be [], and np.stack([]) will raise a error.
> ![image](https://user-images.githubusercontent.com/13503336/75666858-88a98800-5cb1-11ea-8da8-ab13170573e9.png)

Have you solved this problem?

**Comment by LiangHann** [comment]
> There may be a problem when training maskrcnn with backgournd.
> [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L159)
> The variable **masks** will be [], and np.stack([]) will raise a error.
> ![image](https://user-images.githubusercontent.com/13503336/75666858-88a98800-5cb1-11ea-8da8-ab13170573e9.png)

@abcxs have you solved this problem?

**Comment by abcxs** [comment]
https://github.com/open-mmlab/mmdetection/pull/2289https://github.com/open-mmlab/mmdetection/pull/2289
