### ISSUE TITLE
Question about validate on multi-node multi gpu?

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#2195]
When I train the model on multi node multi gpu, it gives me this error on validation stage :

Traceback (most recent call last):
  File "tools/train.py", line 127, in <module>
    main()
  File "tools/train.py", line 123, in main
    timestamp=timestamp)
  File "/home/work/user-job-dir/mmlab_v1/mmdetection/mmdet/apis/train.py", line 126, in train_detector
    timestamp=timestamp)
  File "/home/work/user-job-dir/mmlab_v1/mmdetection/mmdet/apis/train.py", line 273, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/runner/runner.py", line 277, in train
    self.call_hook('after_train_epoch')
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/runner/runner.py", line 230, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/work/user-job-dir/mmlab_v1/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 60, in after_train_epoch
    tmp_results = mmcv.load(tmp_file)
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/fileio/io.py", line 40, in load
    obj = handler.load_from_path(file, **kwargs)
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/fileio/handlers/pickle_handler.py", line 13, in load_from_path
    filepath, mode='rb', **kwargs)
  File "/home/work/user-job-dir/mmlab_v1/mmcv-0.2.15/mmcv/fileio/handlers/base.py", line 21, in load_from_path
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/cache/model_out/faster_rcnn_r50_fpn_1x/temp_2.pkl'

I only train 1 epoch, and 2 nodes, 2GPUs each.

**Comment by hanjianhua44** [comment]
Seems like my nodes don't share a file system, and that's why it can't find the file.

**Comment by ZwwWayne** [comment]
Hi @hanjianhua44 ,
You can add `--gpu_collect` in the script when you evaluating your model, this will use GPU rather than the file system to collect results.
