### ISSUE TITLE
Testing custom VOC dataset with multiple classes

### ISSUE THREAD

**Issue by maxyakovlevclone** [open-mmlab/mmdetection#2231]
SOS! As I try testing the model after training, I run the following:
!python tools/test.py/content/mmdetection_object_detection_demo/mmdetection/configs/retinanet_r50_fpn_1x.py \  /content/mmdetection_object_detection_demo/mmdetection/./work_dirs/retinanet_r50_fpn_1x/latest.pth \
    --eval mAP

And keep getting : 
Traceback (most recent call last):
  File "tools/test.py", line 175, in <module>
    main()
  File "tools/test.py", line 171, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/content/mmdetection_object_detection_demo/mmdetection/mmdet/datasets/voc.py", line 47, in evaluate
    logger=logger)
  File "/content/mmdetection_object_detection_demo/mmdetection/mmdet/core/evaluation/mean_ap.py", line 385, in eval_map
    mean_ap, eval_results, dataset, area_ranges, logger=logger)
  File "/content/mmdetection_object_detection_demo/mmdetection/mmdet/core/evaluation/mean_ap.py", line 448, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: list index out of range

I did the num_classes = num_labels+1 adjustment, so I'm really puzzled about this one!

Environment:
sys.platform: linux
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.4.0

Could anybody pls explain what I'm doing wrong??

**Comment by maxyakovlevclone** [comment]
Nevermind, resolved!

**Comment by KDcx35** [comment]
hi,i have the same error,how you solved this?

**Comment by Kuuuo** [comment]
i have the same error,how you solved this?
