### ISSUE TITLE
distributed training problem like this , where is the config.seed in api/train.py

### ISSUE THREAD

**Issue by Peterchen111** [open-mmlab/mmdetection#2307]
Traceback (most recent call last):
  File "./tools/train.py", line 142, in <module>
    main()
  File "./tools/train.py", line 138, in main
    meta=meta)
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 129, in _dist_train
    seed=cfg.seed) for ds in dataset
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 129, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/cw/code/mmdetection-master/mmdet/datasets/loader/build_loader.py", line 68, in build_dataloader
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'seed'
Traceback (most recent call last):
  File "./tools/train.py", line 142, in <module>
    main()
  File "./tools/train.py", line 138, in main
    meta=meta)
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 129, in _dist_train
    seed=cfg.seed) for ds in dataset
  File "/home/cw/code/mmdetection-master/mmdet/apis/train.py", line 129, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/cw/code/mmdetection-master/mmdet/datasets/loader/build_loader.py", line 68, in build_dataloader
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'seed'
Traceback (most recent call last):
  File "/home/cw/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cw/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cw/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/cw/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/cw/anaconda3/envs/mmd/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/un/cas_r50/cascade_rcnn_r50_fpn_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by hellock** [comment]
Are you using the latest mmdetection?

**Comment by Peterchen111** [comment]
i use the latest mmd version，how can i solve this problem. i try to annotation the “seed=config.seed”and then it works



发自Peterchen的手机邮箱


------------------ Original ------------------
