### ISSUE TITLE
FP16 error in multi gpu

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#2312]
I run `fp16/mask_rcnn_r50_fpn_fp16_1x.py` and set 2 `gpus` in `tools/train.py`.
The program report error:
```
Traceback (most recent call last):
  File "/home/zgz/github_code/mmdetection/tools/train.py", line 118, in <module>
    main()
  File "/home/zgz/github_code/mmdetection/tools/train.py", line 114, in main
    logger=logger)
  File "/home/zgz/github_code/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/zgz/github_code/mmdetection/mmdet/apis/train.py", line 232, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/python37/lib/python3.7/site-packages/mmcv/runner/runner.py", line 363, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/mmcv/runner/runner.py", line 267, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 163, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/core/fp16/decorators.py", line 75, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/models/detectors/base.py", line 117, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/models/detectors/two_stage.py", line 167, in forward_train
    x = self.extract_feat(img)
  File "/home/zgz/github_code/mmdetection/mmdet/models/detectors/two_stage.py", line 93, in extract_feat
    x = self.backbone(img)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/models/backbones/resnet.py", line 524, in forward
    x = self.norm1(x)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zgz/github_code/mmdetection/mmdet/core/fp16/hooks.py", line 122, in new_forward
    **cast_tensor_type(kwargs, src_type, dst_type))
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/python37/lib/python3.7/site-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_batch_norm)
```

**Comment by as754770178** [comment]
I doubt that `cast_tensor_type` in `mmdet/core/fp16/utils.py`, not only convert the dytpe of tensor, also change the device?

**Comment by xvjiarui** [comment]
Please use [Error Report Template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md)

**Comment by xvjiarui** [comment]
@as754770178 
Btw, please check if your mmcv is updated.

**Comment by as754770178** [comment]
I update `mmcv` and `mmdetection` to latest

**Comment by as754770178** [comment]
I change the code
```
def wrap_fp16_model(model):
    # convert model to fp16
    model.half()
    # patch the normalization layers to make it work in fp32 mode
    # patch_norm_fp32(model) !!!!!!
    # set `fp16_enabled` flag
    for m in model.modules():
        if hasattr(m, 'fp16_enabled'):
            m.fp16_enabled = True
```
The batchnorm not report error
