### ISSUE TITLE
Can I use my own pretrained backbone?

### ISSUE THREAD

**Issue by bnumaomei** [open-mmlab/mmdetection#2327]
**Describe the bug**
I have fine tune a ResNet on my own datasets and I want to use this as my pretrained backbone.

**Reproduction**
I have modified the faster rcnn config file set the pretrained as my model path
    pretrained='/data/xy_data/code/classify/models/4channel/1/model_250.pth',

```
# model settings
model = dict(
    type='FasterRCNN',
    pretrained='/data/xy_data/code/classify/models/4channel/1/model_250.pth',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=dict(
        type='SharedFCBBoxHead',
        num_fcs=2,
        in_channels=256,
        fc_out_channels=1024,
        roi_feat_size=7,
        num_classes=2,
        target_means=[0., 0., 0., 0.],
        target_stds=[0.1, 0.1, 0.2, 0.2],
        reg_class_agnostic=False,
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    rpn_proposal=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0.5,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=512,
            pos_fraction=0.25,
            neg_pos_ub=-1,
            add_gt_as_proposals=True),
        pos_weight=-1,
        debug=False))
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=1000,
        nms_post=1000,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05, nms=dict(type='nms', iou_thr=0.5), max_per_img=100)
    # soft-nms is also supported for rcnn testing
    # e.g., nms=dict(type='soft_nms', iou_thr=0.5, min_score=0.05)
)

```

**Error traceback**
RuntimeError: No state_dict found in checkpoint file /data/xy_data/code/classify/models/4channel/1/model_250.pth
```
Traceback (most recent call last):
  File "tools/train_local.py", line 142, in <module>
    main()
  File "tools/train_local.py", line 115, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/detectors/faster_rcnn.py", line 27, in __init__
    pretrained=pretrained)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/detectors/two_stage.py", line 62, in __init__
    self.init_weights(pretrained=pretrained)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/detectors/two_stage.py", line 70, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/data/xy_data/new_mm/mmdetection-master/mmdet/models/backbones/resnet.py", line 473, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/xy/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv-0.3.1-py3.6-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 193, in load_checkpoint
    'No state_dict found in checkpoint file {}'.format(filename))
RuntimeError: No state_dict found in checkpoint file /data/xy_data/code/classify/models/4channel/1/model_250.pth
```

**Comment by PanJianning** [comment]
Can you load your checkpoint with `torch.load`?

**Comment by bnumaomei** [comment]
@PanJianning  I have tested the classify model , so at that time I have successfully torch.load the checkpoint.

**Comment by PanJianning** [comment]
> @PanJianning I have tested the classify model , so at that time I have successfully torch.load the checkpoint.

You may check this [line](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/checkpoint.py#L192)

**Comment by bnumaomei** [comment]
@PanJianning Thank you very much~ I found that I save the whole model, and alter save model.state_dict(),it worked~!
