### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by feiyangsuo** [open-mmlab/mmdetection#2347]
Error info:
```
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "/home/amax/mmdetection/tools/coco_eval.py", line 30, in <module>
    main()
  File "/home/amax/mmdetection/tools/coco_eval.py", line 26, in main
    coco_eval(args.result, args.types, args.ann, args.max_dets, args.classwise)
  File "/home/amax/mmdetection/mmdet/core/evaluation/coco_utils.py", line 41, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/home/amax/anaconda3/envs/open-mmlab-sfy/lib/python3.7/site-packages/pycocotools-2.0.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 317, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set
```
It happens when I tried to run coco_eval.py. And I'm aware that the error report indicates me the result doesn't fit coco format. **But the result is absolutely and directly generated by mmdetection/tools/test.py.** 
The circumstance is, I used test.py to generate results of a Cascade R-CNN, and used coco_eval.py to evaluate the results, and nothing went wrong before.
This time I trained the same Cascade R-CNN config with another train set of data, the training seems normal, as well as the in-training validating. 
Then I used test.py to generate a result, which is a list of json like:
```
{"image_id": 2973, "bbox": [0.07157446444034576, 291.5343933105469, 0.9284255355596542, 49.182525634765625], "score": 0.013011305592954159, "category_id": 4}
```
When running coco_eval.py, the error mentioned at first happens.

I don't think this format differs from coco's, but as you can see, the width of bbox is less than 1. I visualized the results, noticing that there are always some bbox with 0 width on the border of image.
Is the 0-width bbox resiponsible to the error? However after I filtered the 0-width bbox alway, the same error happens.

**Comment by feiyangsuo** [comment]
Replenish: I'm using the same validation set for in-training validating and later testing. While only testing goes wrong with this error.

**Comment by feiyangsuo** [comment]
Fine. It's just because the wrong path of annotation file in coco_eval.py parameters.
