### ISSUE TITLE
Distributed training error

### ISSUE THREAD

**Issue by Chenney0813** [open-mmlab/mmdetection#236]
I use distributed training to train my cascade_rcnn and everytime it Suddenly interrupted each iteration to 1100，here is the error message：

`2019-01-07 10:49:29,852 - INFO - Epoch [1][1100/10628]	lr: 0.01000, eta: 2 days, 11:10:22, time: 0.989, data_time: 0.005, loss_rpn_cls: 0.0091, loss_rpn_reg: 0.0080, s0.loss_cls: 0.0726, s0.acc: 97.8574, s0.loss_reg: 0.0499, s1.loss_cls: 0.0317, s1.acc: 98.0645, s1.loss_reg: 0.0668, s2.loss_cls: 0.0175, s2.acc: 97.5645, s2.loss_reg: 0.0460, loss: 0.3016
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 96, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 251, in train
    for i, data_batch in enumerate(data_loader):
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
Exception: Traceback (most recent call last):
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 154, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 182, in prepare_train_img
    ann = self.get_ann_info(idx)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/coco.py", line 43, in get_ann_info
    return self._parse_ann_info(ann_info)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/coco.py", line 91, in _parse_ann_info
    gt_masks.append(self.coco.annToMask(ann))
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 431, in annToMask
    rle = self.annToRLE(ann)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 307, in pycocotools._mask.frPyObjects
Exception: input type is not supported.

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fd8b9405710>>
Traceback (most recent call last):
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
`

**Comment by OceanPang** [comment]
I guess the annotations in some images (which appeared at iter 1100)  are incorrect?
