### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. T

### ISSUE THREAD

**Issue by NicholasIrving** [open-mmlab/mmdetection#2377]
While i run dist_train.sh after adding a new component according to the [https://github.com/open-mmlab/mmdetection/blob/master/docs/TECHNICAL_DETAILS.md](url), but it occurred the error

**Reproduction**
1. What command or script did you run?

The command I run: 
`CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=26010 tools/train.py configs/RS-data/Faster-RCNN/train+val/se-r50.py --launcher pytorch --validate`

My environment:
```
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-9.0
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GPU 0,1: TITAN V
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.2
OpenCV: 4.2.0
MMCV: 0.3.1
MMDetection: 1.0+b661d5c
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 9.0
```

Error traceback:

```
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 182, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fdbbca8b813 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x734 (0x7fdc054d0654 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x7bed8a (0x7fdc054bed8a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x210ba4 (0x7fdc04f10ba4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x561b42058114 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x561b42058231 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x52cf (0x561b420bce8f in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #8: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #10: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #13: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #15: <unknown function> + 0x17512a (0x561b4206c12a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #16: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #19: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #22: _PyFunction_FastCallDict + 0x1d5 (0x561b42012805 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #23: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #24: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x6a0 (0x561b420b8260 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0xc30 (0x561b42012030 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #30: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #33: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0xfb (0x561b4205768b in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x416 (0x561b420b7fd6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #38: PyEval_EvalCodeEx + 0x44 (0x561b420125f4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #39: PyEval_EvalCode + 0x1c (0x561b4201261c in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #40: <unknown function> + 0x21c974 (0x561b42113974 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #41: PyRun_FileExFlags + 0xa1 (0x561b4211dcf1 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #42: PyRun_SimpleFileExFlags + 0x1c3 (0x561b4211dee3 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #43: <unknown function> + 0x227f95 (0x561b4211ef95 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #44: _Py_UnixMain + 0x3c (0x561b4211f0bc in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #45: __libc_start_main + 0xe7 (0x7fdc0f0b6b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #46: <unknown function> + 0x1d0990 (0x561b420c7990 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
```

**Comment by xvjiarui** [comment]
May I know what component you added? 
Does the same error occur when you run with 1 process or `non_dist_train`?

**Comment by NicholasIrving** [comment]
i added a SEnet between ROI Align and bbox_head, the same error occurred while running 1 process by `dist_train`, but didn't occur by `non_dist_train`

**Comment by ZwwWayne** [comment]
You can try to set `find_unused_parameters=True` first in your config and see whether the bug still exists.

**Comment by makalsue** [comment]
> You can try to set `find_unused_parameters=True` first in your config and see whether the bug still exists.

Yes，set find_unused_parameters=True in your config file is effective.
