### ISSUE TITLE
Use tensorboardX to visualize the model

### ISSUE THREAD

**Issue by zhaowujie** [open-mmlab/mmdetection#2383]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
```
import torch
from mmdet.apis import init_detector, inference_detector, show_result
from tensorboardX import SummaryWriter
config_file = '../configs/anti-uav/ssd300_voc.py'
checkpoint_file = '../tools/work_dirs/ssd300_voc/latest.pth'

#build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file)
model.eval()
dummy_input = torch.rand(1, 3, 1333, 800).cuda()
with SummaryWriter(log_dir='./tf_log') as w:
    w.add_graph(model, (dummy_input))
#test a single image and show the results
img = '20190925_213001_1_2_00830.jpg'  # or img = mmcv.imread(img), which will only load it once

result = inference_detector(model, img)
show_result(img, result, model.CLASSES)
```

**Environment**
```
CUDA available: True
MMDetection Compiler: GCC 5.4
TorchVision: 0.2.0
PyTorch: 1.2.0
MMDetection: 1.0+3b2ef3a
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.2
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

Python: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
sys.platform: linux
MMDetection CUDA Compiler: 10.0
OpenCV: 4.2.0
MMCV: 0.3.1
NVCC: Cuda compilation tools, release 10.0, V10.0.130
CUDA_HOME: /usr/local/cuda
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
GPU 0: GeForce GTX 1080 Ti
```

**Error traceback**
If applicable, paste the error trackback here.
```
/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/bin/python /media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/demo/demo.py
Traceback (most recent call last):
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/demo/demo.py", line 12, in <module>
    w.add_graph(model, (dummy_input))
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/tensorboardX/writer.py", line 804, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, profile_with_cuda, **kwargs))
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/tensorboardX/pytorch_graph.py", line 324, in graph
    trace = torch.jit.trace(model, args)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 772, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/torch/jit/__init__.py", line 904, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 531, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_meta'

Process finished with exit code 1
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/master/tools/pytorch2onnx.py#L107

**Comment by zhaowujie** [comment]
Thanks a lot !!!
