### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by funfun777** [open-mmlab/mmdetection#239]
when I train my model ,at beginning it shows the error message:
`
rles = maskUtils.frPyObjects(segm, h, w)
File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)
`
I want to know how to solve it ?

**Comment by funfun777** [comment]
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 96, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 251, in train
    for i, data_batch in enumerate(data_loader):
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 154, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 182, in prepare_train_img
    ann = self.get_ann_info(idx)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/coco.py", line 43, in get_ann_info
    return self._parse_ann_info(ann_info)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/coco.py", line 91, in _parse_ann_info
    gt_masks.append(self.coco.annToMask(ann))
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 431, in annToMask
    rle = self.annToRLE(ann)
  File "/media/pengjk/30213d25-fae8-4100-9d8b-9aed2bb5a8df/mmdetection/anaconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools-2.0.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)

**Comment by funfun777** [comment]
I check the annotations and it can be used in  detectron , I don't know what happened

**Comment by tunai** [comment]
Hello, 

Since the algorithm expects a numpy array and you are providing a list, a lot of operations supposed to happen in the workflow are not possible. 
try: 
`import numpy as np`
`bb = np.asarray(bb)`

**Comment by forestriveral** [comment]
Hi @funfun777 have you solved the problem? I encountered this error too today. But I did not get this error until I have changed the datasets to another. Before that it worked without any problems, which makes me very confused now. I checked the annotation files and didn't find anything different with the previous dataset.

**Comment by liugaolian** [comment]
Hi @funfun777 have you solved the problem? I encountered this error too today.If you solve this problem, please enlighten me.Thanks!!!

**Comment by liugaolian** [comment]
> Hi @funfun777 have you solved the problem? I encountered this error too today. But I did not get this error until I have changed the datasets to another. Before that it worked without any problems, which makes me very confused now. I checked the annotation files and didn't find anything different with the previous dataset.
have you solved the problem? I encountered this error too today.If you solve this problem, please enlighten me.Thanks!!!

**Comment by liugaolian** [comment]
I may be caused by incorrect dataset labeling, please refer to:
https://blog.csdn.net/qq_20373723/article/details/88354892
