### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'seed'

### ISSUE THREAD

**Issue by destiny311** [open-mmlab/mmdetection#2393]
Traceback (most recent call last):
  File "tools/train.py", line 127, in <module>
    main()
  File "tools/train.py", line 120, in main
    timestamp=timestamp)
  File "/home/xiangw/anaconda3/lib/python3.6/site-packages/mmdet-1.1.0+1d877f8-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/home/xiangw/anaconda3/lib/python3.6/site-packages/mmdet-1.1.0+1d877f8-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 205, in _non_dist_train
    seed=cfg.seed) for ds in dataset
  File "/home/xiangw/anaconda3/lib/python3.6/site-packages/mmdet-1.1.0+1d877f8-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 205, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/home/xiangw/anaconda3/lib/python3.6/site-packages/mmcv/utils/config.py", line 202, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/xiangw/anaconda3/lib/python3.6/site-packages/mmcv/utils/config.py", line 34, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'seed'

**Comment by ZwwWayne** [comment]
Hi @destiny311,
Which config are you using?
