### ISSUE TITLE
Mask RCNN  ValueError:could not broadcast input array from shape (800,1034) into shape (800,800)

### ISSUE THREAD

**Issue by ycjcy** [open-mmlab/mmdetection#242]
I met the ValueError when training Mask RCNN. The ERROR occured in the function mmcv.impad().
it showed the error like this:

Traceback (most recent call last):
  File "tools/train.py", line 90, in <module>
    main()
  File "tools/train.py", line 86, in main
    logger=logger)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/train.py", line 121, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 251, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 154, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/custom.py", line 216, in prepare_train_img
    scale_factor, flip)
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/transforms.py", line 106, in __call__
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/datasets/transforms.py", line 106, in <listcomp>
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/wenwen/anaconda2/envs/mmdetection/lib/python3.6/site-packages/mmcv/image/transforms/geometry.py", line 186, in impad
    pad[:img.shape[0], :img.shape[1], ...] = img
ValueError: could not broadcast input array from shape (800,1034) into shape (800,800)

If you have do that, please give me some advice. Thanks a lot

**Comment by hellock** [comment]
What dataset are you using? Could you share the config file?

**Comment by wangduyang** [comment]
have you sloved the problem?

**Comment by luxedo** [comment]
I'm having the same issue. 
The config I'm using is similar to `configs/ct/cascade_mask_rcnn_r4_ct_dconv_c3-c5_x101_32x4d_sbn_fpn_1x.py` but I'm using a custom dataset.

**Comment by jy1023408440** [comment]
I'm having the same issue. do you sloved the problem?
ValueError: could not broadcast input array from shape (800,1067) into shape (800,800)

**Comment by Weizhen-Fang** [comment]
I have the same issue when I trained using my own dataset.
ValueError: could not broadcast input array from shape (319,425) into shape (319,416)
How to fix it ?

**Comment by jy1023408440** [comment]
> I'm having the same issue. do you sloved the problem?
> ValueError: could not broadcast input array from shape (800,1067) into shape (800,800)


I have sloved my problem 
https://blog.csdn.net/jy1023408440/article/details/97653602

**Comment by shraddhaamohan** [comment]
Met with a similar error, the model was initially training and then after this log message the same error occurred 

2019-08-25 12:32:05,032 - INFO - Epoch [1][1250/22710]	lr: 0.02000, eta: 2 days, 7:02:14, time: 1.777, data_time: 0.023, memory: 3834, loss_rpn_cls: 0.0886, loss_rpn_bbox: 0.0236, loss_cls: 0.3614, acc: 95.8125, loss_bbox: 0.1004, loss_mask: 0.6289, loss: 1.2029
Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 106, in <module>
    main()
  File "mmdetection/tools/train.py", line 102, in main
    logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 62, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/apis/train.py", line 223, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 174, in __getitem__
    data = self.prepare_train_img(idx)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/datasets/custom.py", line 247, in prepare_train_img
    scale_factor, flip)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/datasets/transforms.py", line 109, in __call__
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/usr/local/lib/python3.6/dist-packages/mmdet-0.6.0+f730b40-py3.6-linux-x86_64.egg/mmdet/datasets/transforms.py", line 109, in <listcomp>
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/usr/local/lib/python3.6/dist-packages/mmcv/image/transforms/geometry.py", line 186, in impad
    pad[:img.shape[0], :img.shape[1], ...] = img
ValueError: could not broadcast input array from shape (800,1067) into shape (800,800)

I have rechecked the json file and I am sure that I have marked the width and height appropriately.
Has anyone found a solution?

**Comment by lntsmn** [comment]
Same problem here, and unfortunately I cannot decipher the solution in the link...
Could anyone who managed provide a short description of the solution?

**Comment by hellock** [comment]
@lntsmn The image width and height in the annotation file are not the same with actual image size (for some reason like wrongly converted json files).
