### ISSUE TITLE
Error after training 6 epoches, died with signals:sigabrt:6

### ISSUE THREAD

**Issue by zhoulukuan** [open-mmlab/mmdetection#2426]
I added some of my own modules to train, but the program terminates when training the 7th epoch, what is the problem?
```
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fa72bfe2441 in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fa72bfe1d7a in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7fa72b58e652 in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7fa72bfd2ce0 in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7fa723924acb in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x1420bb (0x7fa72c56f0bb in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3c30f4 (0x7fa72c7f00f4 in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3c3141 (0x7fa72c7f0141 in /home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x19aa5e (0x55b5f2142a5e in /home/zlk/miniconda3/envs/mm/bin/python)
frame #9: <unknown function> + 0xf1b77 (0x55b5f2099b77 in /home/zlk/miniconda3/envs/mm/bin/python)
frame #10: <unknown function> + 0xf1a07 (0x55b5f2099a07 in /home/zlk/miniconda3/envs/mm/bin/python)
frame #11: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #12: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #13: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #14: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #15: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #16: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #17: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #18: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #19: <unknown function> + 0xf1a1d (0x55b5f2099a1d in /home/zlk/miniconda3/envs/mm/bin/python)
frame #20: PyDict_SetItem + 0x3da (0x55b5f20e063a in /home/zlk/miniconda3/envs/mm/bin/python)
frame #21: PyDict_SetItemString + 0x4f (0x55b5f20e765f in /home/zlk/miniconda3/envs/mm/bin/python)
frame #22: PyImport_Cleanup + 0x99 (0x55b5f214cd89 in /home/zlk/miniconda3/envs/mm/bin/python)
frame #23: Py_FinalizeEx + 0x61 (0x55b5f21b7231 in /home/zlk/miniconda3/envs/mm/bin/python)
frame #24: Py_Main + 0x35e (0x55b5f21c157e in /home/zlk/miniconda3/envs/mm/bin/python)
frame #25: main + 0xee (0x55b5f208b88e in /home/zlk/miniconda3/envs/mm/bin/python)
frame #26: __libc_start_main + 0xe7 (0x7fa7310e6b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #27: <unknown function> + 0x1c3160 (0x55b5f216b160 in /home/zlk/miniconda3/envs/mm/bin/python)

Traceback (most recent call last):
  File "/home/zlk/miniconda3/envs/mm/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zlk/miniconda3/envs/mm/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/zlk/miniconda3/envs/mm/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/zlk/miniconda3/envs/mm/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/new/new.py', '--launcher', 'pytorch']' died with <Signals.SIGABRT: 6>.
```

**Comment by ZwwWayne** [comment]
Please use the `Error Template`.
You can add `CUDA_LAUNCH_BLOCKING=1` when you running the script to capture the real bug that happens in GPU.
