### ISSUE TITLE
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1565272271120/work/torch/lib/c10d/ProcessGroupNCCL.cpp:290, unhandled cuda error

### ISSUE THREAD

**Issue by shengshiH** [open-mmlab/mmdetection#2434]
When I use two GPUs, the program dist_train.sh runs correctly. When I use four, the following error is reported:

  File "/disk/wuzhihao/mmdetection/tools/train.py", line 142, in <module>
    main()
  File "/disk/wuzhihao/mmdetection/tools/train.py", line 115, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/disk/wuzhihao/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/disk/wuzhihao/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/disk/wuzhihao/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 27, in __init__
    pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/two_stage.py", line 62, in __init__
    self.init_weights(pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/two_stage.py", line 70, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/backbones/resnet.py", line 472, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 184, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 153, in _load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
    torch.distributed.barrier()
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1358, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1565272271120/work/torch/lib/c10d/ProcessGroupNCCL.cpp:290, unhandled cuda error
Traceback (most recent call last):
  File "/disk/wuzhihao/mmdetection/tools/train.py", line 142, in <module>
    main()
  File "/disk/wuzhihao/mmdetection/tools/train.py", line 115, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/disk/wuzhihao/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/disk/wuzhihao/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/disk/wuzhihao/mmdetection/mmdet/utils/registry.py", line 79, in build_from_cfg
    return obj_cls(**args)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 27, in __init__
    pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/two_stage.py", line 62, in __init__
    self.init_weights(pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/detectors/two_stage.py", line 70, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/disk/wuzhihao/mmdetection/mmdet/models/backbones/resnet.py", line 472, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 184, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 153, in _load_checkpoint
    checkpoint = load_url_dist(model_urls[model_name])
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 114, in load_url_dist
    torch.distributed.barrier()
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1358, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1565272271120/work/torch/lib/c10d/ProcessGroupNCCL.cpp:290, unhandled cuda error
Traceback (most recent call last):
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/wuzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/wuzhihao/anaconda3/envs/open-mmlab/bin/python', '-u', '/disk/wuzhihao/mmdetection/tools/train.py', '--local_rank=3', '/disk/wuzhihao/mmdetection/faster.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by ZwwWayne** [comment]
Please use the `Error template`.

**Comment by shengshiH** [comment]
> 请使用`Error template`.

Thank you. I have another question now. I trained retinanet_r50_fpn_1x with 4 gpus and 4 imgs/gpu. I didn't change the config and only got:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.345
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.541
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.365
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.194
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.379
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.452

I use anaconda Tsinghua mirror to install the required environment. I don’t know the reason for such decrease in AP, do you know what may be causing it?

**Comment by shengshiH** [comment]
> Please use the `Error template`.

Thank you. I have another question now. I trained retinanet_r50_fpn_1x with 4 gpus and 4 imgs/gpu. I did not modify the rest of the config but only got:
Average Precision (AP) @[ IoU=0.50:0.95 | area= all | maxDets=100 ] = 0.345
Average Precision (AP) @[ IoU=0.50 | area= all | maxDets=100 ] = 0.541
Average Precision (AP) @[ IoU=0.75 | area= all | maxDets=100 ] = 0.365
Average Precision (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.194
Average Precision (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.379
Average Precision (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.452

I use anaconda Tsinghua mirror to install the required environment. I don’t know the reason for such decrease in AP, do you know what may be causing it?

**Comment by ZwwWayne** [comment]
You need to change the learning rate according to your batch size.

**Comment by shengshiH** [comment]
> 你需要根据你的批次大小改变学习速度。

Sorry, I don't understand. Original batch size is 2 * 8 = 16, mine is 4 * 4 = 16. They are the same. Am I wrong?

**Comment by ZwwWayne** [comment]
OK my mistake, what is the version of your codebase?
The reason that we need the users to use the `Error Template`  is that we need enough information to locate the bug.

**Comment by shengshiH** [comment]
> OK my mistake, what is the version of your codebase?
> The reason that we need the users to use the `Error Template` is that we need enough information to locate the bug.

OK I will download the newest version and create a new environment. If I still have such problem, I will use the  Error Template to report. Does workers_per_gpu affect the result?

**Comment by ZwwWayne** [comment]
No, it does not. Thanks for your consideration.
I will close this PR first and you can open a new PR using `Error Template` if you still meet bugs with the newest codebase.

**Comment by YilanWang** [comment]
could you tell me how to solve the original problem? many thanks~
