### ISSUE TITLE
ONNX Checker Error

### ISSUE THREAD

**Issue by marload** [open-mmlab/mmdetection#2451]
I used the `tools/pytorch2onnx.py` to export the Cascade RCN R50 FPN X1 to onnx. However, an error occurs when checking.
How can I fix it?

```
import onnx
model = onnx.load('out.onnx')
onnx.checker.check_model(model)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/testforte-gpu-1/anaconda3/envs/mmdet/lib/python3.7/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'
```

**Comment by Single430** [comment]
Is this problem solved? Looking forward to your reply  @hellock  @marload

**Comment by RunningLeon** [comment]
Pls. try with the latest mmcv and mmdetection.
