### ISSUE TITLE
When I use docker to install mmdetection, it raises exception "No CUDA runtime is found".

### ISSUE THREAD

**Issue by mincwin** [open-mmlab/mmdetection#2487]
I'm using Windows 10, CUDA 10.1, Pytorch 1.1, mmcv 0.4.3 and mmdet 1.1.0+a1c3aa4.
```
PS F:\peoplo_detection\Feature-Selective-Anchor-Free-Module-for-Single-Shot-Object-Detection-master> docker build -t mmdetection docker/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=uie0fi2x2nqgxeiok1ry737fc&shmsize=0&t=mmdetection&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS F:\peoplo_detection\Feature-Selective-Anchor-Free-Module-for-Single-Shot-Object-Detection-master> docker build -t mmdetection docker/
Sending build context to Docker daemon  2.048kB
Step 1/9 : ARG PYTORCH="1.1.0"
Step 2/9 : ARG CUDA="10.0"
Step 3/9 : ARG CUDNN="7.5"
Step 4/9 : FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
 ---> 1be771bff6d1
Step 5/9 : RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender-dev libxext6  && apt-get clean  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 33a5b744d918
Step 6/9 : RUN conda install cython -y && conda clean --all
 ---> Using cache
 ---> 575e510a2616
Step 7/9 : RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
 ---> Using cache
 ---> 69f463a4bec6
Step 8/9 : WORKDIR /mmdetection
 ---> Using cache
 ---> 8029c9531b6a
Step 9/9 : RUN pip install --no-cache-dir -e .
 ---> Running in 54b34e01c7b7
Obtaining file:///mmdetection
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mmdetection/setup.py", line 228, in <module>
        sources=['src/compiling_info.cpp']),
      File "/mmdetection/setup.py", line 97, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile MMDetection!')
    OSError: CUDA is required to compile MMDetection!
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /mmdetection/
The command '/bin/sh -c pip install --no-cache-dir -e .' returned a non-zero code: 1
```

**Comment by hellock** [comment]
#2508
