### ISSUE TITLE
error when python setup.py install

### ISSUE THREAD

**Issue by destinyzs** [open-mmlab/mmdetection#249]
My OS is Ubuntu 14.04, Python is 3.6.2.

When i run `python setup.py install`, error occured:
```
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    long_description=readme(),
  File "setup.py", line 9, in readme
    content = f.read()
  File "/root/anaconda2/envs/mmdetect/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2175: ordinal not in range(128)
```
Don't know why... maybe there is a encoding problem in Ubuntu 14.04 ?
I solve it by changing:
```
def readme():
    with open('README.md') as f:
        content = f.read()
    return content
```
to
```
def readme():
    with open('README.md', 'r', encoding="utf-8") as f:
        content = f.read()
    return content
```
At [here](https://github.com/open-mmlab/mmdetection/blob/master/setup.py#L7-L10).

**Comment by hellock** [comment]
There are some special characters in README.md, and the default encoding depends on the OS, so there is an error on Ubuntu 14.04.

**Comment by destinyzs** [comment]
Thx.
