### ISSUE TITLE
Something wrong when training

### ISSUE THREAD

**Issue by destinyzs** [open-mmlab/mmdetection#250]
When i run CUDA_VISIBLE_DEVICES=X ./tools/dist_train.sh configs/coco/faster_rcnn_r101_fpn_1x.py 1 --validate, error occurs as following:
```
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 65, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/root/anaconda2/envs/mmdetect/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/root/anaconda2/envs/mmdetect/lib/python3.6/site-packages/mmdet-0.5.5+1b9f9b8-py3.6.egg/mmdet/apis/env.py", line 30, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/root/anaconda2/envs/mmdetect/lib/python3.6/site-packages/torch/distributed/__init__.py", line 94, in init_process_group
    group_name, rank)
RuntimeError: public_address was not set in config at /pytorch/torch/lib/THD/process_group/General.cpp:17
```
Any help about this?

**Comment by destinyzs** [comment]
My os is Ubuntu 14.04, Python is 3.6.2, Pytorch is 0.4.1.

**Comment by hellock** [comment]
You just used a single GPU, so there is no need to use distributed training. Just use `python tools/train.py` instead.

**Comment by KiveeDong** [comment]
hi~I've met the same error but I can't solve it for a long time, would you like to share your solution?Thans.
