### ISSUE TITLE
pip install fails on cuda10.2

### ISSUE THREAD

**Issue by RicoMontulet** [open-mmlab/mmdetection#2517]
Thanks for your error report and we appreciate it a lot.

**Checklist**

- [x] I have searched related issues but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**
The pip install fails to build on ubuntu 18.04, cuda10.2 pytorch 1.5 and 1.6-nighty gcc7.5.0

**Reproduction**
1. What command or script did you run?
```
pip install -v -e .
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, fresh pull from github
3. What dataset did you use?
None

**Environment**
```
sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1: TITAN RTX
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.4.4

Ninja version: 1.9.0
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source] Conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
/development/mmdetection$ pip install -v -e .
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-02dlc_4q
Created temporary directory: /tmp/pip-req-tracker-n8rr_3wi
Initialized build tracking at /tmp/pip-req-tracker-n8rr_3wi
Created build tracker: /tmp/pip-req-tracker-n8rr_3wi
Entered build tracker: /tmp/pip-req-tracker-n8rr_3wi
Created temporary directory: /tmp/pip-install-b_bhq7zd
Obtaining file:///data-fast/development/mmdetection
  Added file:///data-fast/development/mmdetection to build tracker '/tmp/pip-req-tracker-n8rr_3wi'
    Running setup.py (path:/data-fast/development/mmdetection/setup.py) egg_info for package from file:///data-fast/development/mmdetection
    Running command python setup.py egg_info
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
  Source in /data-fast/development/mmdetection has version 1.1.0+2452761, which satisfies requirement mmdet==1.1.0+2452761 from file:///data-fast/development/mmdetection
  Removed mmdet==1.1.0+2452761 from file:///data-fast/development/mmdetection from build tracker '/tmp/pip-req-tracker-n8rr_3wi'
Requirement already satisfied: matplotlib in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (3.2.1)
Requirement already satisfied: mmcv>=0.3.1 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (0.4.4)
Requirement already satisfied: numpy in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (1.18.1)
Requirement already satisfied: Pillow<=6.2.2 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (6.2.2)
Requirement already satisfied: six in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (1.14.0)
Requirement already satisfied: terminaltables in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (3.1.0)
Requirement already satisfied: torch>=1.1 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (1.6.0.dev20200422)
Requirement already satisfied: torchvision in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmdet==1.1.0+2452761) (0.7.0a0+70a2e69)
Requirement already satisfied: python-dateutil>=2.1 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from matplotlib->mmdet==1.1.0+2452761) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from matplotlib->mmdet==1.1.0+2452761) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from matplotlib->mmdet==1.1.0+2452761) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from matplotlib->mmdet==1.1.0+2452761) (2.4.7)
Requirement already satisfied: addict in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmcv>=0.3.1->mmdet==1.1.0+2452761) (2.2.1)
Requirement already satisfied: opencv-python>=3 in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmcv>=0.3.1->mmdet==1.1.0+2452761) (4.2.0.34)
Requirement already satisfied: pyyaml in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from mmcv>=0.3.1->mmdet==1.1.0+2452761) (5.3.1)
Requirement already satisfied: future in /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages (from torch>=1.1->mmdet==1.1.0+2452761) (0.18.2)
Installing collected packages: mmdet
  Running setup.py develop for mmdet
    Running command /home/rico/anaconda3/envs/MaskTrackRCNN/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data-fast/development/mmdetection/setup.py'"'"'; __file__='"'"'/data-fast/development/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    writing mmdet.egg-info/PKG-INFO
    writing dependency_links to mmdet.egg-info/dependency_links.txt
    writing requirements to mmdet.egg-info/requires.txt
    writing top-level names to mmdet.egg-info/top_level.txt
    reading manifest file 'mmdet.egg-info/SOURCES.txt'
    writing manifest file 'mmdet.egg-info/SOURCES.txt'
    running build_ext
    building 'mmdet.ops.nms.nms_cuda' extension
    Emitting ninja build file /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/1] c++ -MMD -MF /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /home/rico/anaconda3/envs/MaskTrackRCNN/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/TH -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/THC -I/home/rico/anaconda3/envs/MaskTrackRCNN/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/include/python3.7m -c -c /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp -o /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    FAILED: /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o
    c++ -MMD -MF /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o.d -pthread -B /home/rico/anaconda3/envs/MaskTrackRCNN/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/TH -I/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/THC -I/home/rico/anaconda3/envs/MaskTrackRCNN/include -I/home/rico/anaconda3/envs/MaskTrackRCNN/include/python3.7m -c -c /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp -o /data-fast/development/mmdetection/build/temp.linux-x86_64-3.7/mmdet/ops/nms/src/nms_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp: In function ‘at::Tensor nms(const at::Tensor&, float)’:
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:39: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                                           ^
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:9:3: note: in expansion of macro ‘CHECK_CUDA’
       CHECK_CUDA(dets);
       ^
    In file included from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:11:0,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/ATen/Context.h:4,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/ATen/ATen.h:5,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                     from /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                     from /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:2:
    /home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:267:30: note: declared here
       DeprecatedTypeProperties & type() const {
                                  ^~~~
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: error: ‘AT_CHECK’ was not declared in this scope
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^~~~~~~~
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: suggested alternative: ‘DCHECK’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^
    /data-fast/development/mmdetection/mmdet/ops/nms/src/nms_cuda.cpp:4:23: note: in definition of macro ‘CHECK_CUDA’
     #define CHECK_CUDA(x) AT_CHECK(x.type().is_cuda(), #x, " must be a CUDAtensor ")
                           ^~~~~~~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1421, in _run_ninja_build
        check=True)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data-fast/development/mmdetection/setup.py", line 300, in <module>
        zip_safe=False)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 582, in build_extensions
        build_ext.build_extensions(self)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 425, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1161, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1434, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-n8rr_3wi'
ERROR: Command errored out with exit status 1: /home/rico/anaconda3/envs/MaskTrackRCNN/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data-fast/development/mmdetection/setup.py'"'"'; __file__='"'"'/data-fast/development/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 802, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/rico/anaconda3/envs/MaskTrackRCNN/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/rico/anaconda3/envs/MaskTrackRCNN/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data-fast/development/mmdetection/setup.py'"'"'; __file__='"'"'/data-fast/development/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
Currently it does not support PyTorch 1.5, which will be resolved in a week. #2513

**Comment by rubeea** [comment]
I am facing a similar issue with cuda 10.2 and pytorch 1.6 with torch vision 0.7.0. How to fix this? Kindly help.
