### ISSUE TITLE
double_heads information

### ISSUE THREAD

**Issue by dereyly** [open-mmlab/mmdetection#2530]
Can you give me information about DoubleHeadRCNN
Is it Rethinking Classification and Localization for Object Detection?

**Comment by dereyly** [comment]
And I cant run it
TypeError: forward() missing 1 required positional argument: 'x_reg'

**Comment by bbingy** [comment]
I run into the same problem, and fixed it  after changing the model type to "type='DoubleHeadRCNN'"  in line 3 of the config file.

**Comment by thisisi3** [comment]
Yes it is, the paper (https://arxiv.org/pdf/1906.07155.pdf) has a list of papers of the detectors.

**Comment by hellock** [comment]
Are you using the latest version?

**Comment by xiaozhuka** [comment]
@bbingy DoubleHeadRCNN in model type? 

Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 134, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/senter/huanyun/code/mmdetection_202006/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/senter/huanyun/code/mmdetection_202006/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/senter/miniconda3/envs/mmdetection_v2/lib/python3.7/site-packages/mmcv/utils/registry.py", line 158, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'DoubleHeadRCNN is not in the detector registry'

**Comment by ZwwWayne** [comment]
Fixed after refactoring.
