### ISSUE TITLE
According to the blog operation, the photo error

### ISSUE THREAD

**Issue by 1962975362** [open-mmlab/mmdetection#2586]
/home/user/lyf/PycharmProjects/PyTorch_YOLOv3/venv/bin/python /home/user/lyf/PycharmProjects/PyTorch_YOLOv3/YOLOv3/mmdetection_test.py
/home/user/lyf/mmdetection/mmdet/apis/inference.py:40: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '
Traceback (most recent call last):
  File "/home/user/lyf/PycharmProjects/PyTorch_YOLOv3/YOLOv3/mmdetection_test.py", line 17, in <module>
    for i, result in enumerate(inference_detector(model, imgs)):
  File "/home/user/lyf/mmdetection/mmdet/apis/inference.py", line 82, in inference_detector
    data = test_pipeline(data)
  File "/home/user/lyf/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/user/lyf/mmdetection/mmdet/apis/inference.py", line 56, in __call__
    img = mmcv.imread(results['img'])
  File "/home/user/lyf/.local/lib/python3.5/site-packages/mmcv/image/io.py", line 98, in imread
    raise TypeError('"img" must be a numpy array or a str or '
TypeError: "img" must be a numpy array or a str or a pathlib.Path object

**Comment by ZwwWayne** [comment]
Please check whether the path of your image is valid.
