### ISSUE TITLE
error when install mmdetection using "pip install -v -e ." and "python setup.py develop"

### ISSUE THREAD

**Issue by Lucksong** [open-mmlab/mmdetection#2613]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
The bug appeared in the last step of the installer. 
The output log of `pip install -v -e .` is shown below:
```
Cleaning up...
  Removing source in /tmp/pip-install-dli2l3n7/mmcv
Removed build tracker: '/tmp/pip-req-tracker-mc17lzqv'
ERROR: Command errored out with exit status -9: /mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/lustre/zhangsong/EventSegmentation/mmdetection/setup.py'"'"'; __file__='"'"'/mnt/lustre/zhangsong/EventSegmentation/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 404, in run
    use_user_site=options.use_user_site,
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 71, in install_given_reqs
    **kwargs
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 802, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status -9: /mnt/lustre/zhangsong/anaconda3/envs/open-mmlab/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/lustre/zhangsong/EventSegmentation/mmdetection/setup.py'"'"'; __file__='"'"'/mnt/lustre/zhangsong/EventSegmentation/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```
The output log of  ```python setup.py develop``` is shown below:
```
mmdet/ops/carafe/src/carafe_cuda_kernel.cu(370): error: identifier "__syncwarp" is undefined

mmdet/ops/carafe/src/carafe_cuda_kernel.cu(47): error: identifier "__shfl_down_sync" is undefined
          detected during:
            instantiation of "scalar_t warpReduceSum(scalar_t) [with scalar_t=double]"
(371): here
            instantiation of "void CARAFEBackward_Mask(int, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=double]"
(442): here

mmdet/ops/carafe/src/carafe_cuda_kernel.cu(47): error: identifier "__shfl_down_sync" is undefined
          detected during:
            instantiation of "scalar_t warpReduceSum(scalar_t) [with scalar_t=float]"
(371): here
            instantiation of "void CARAFEBackward_Mask(int, const scalar_t *, const scalar_t *, int, int, int, int, int, int, int, int, int, scalar_t *) [with scalar_t=float]"
(442): here

3 errors detected in the compilation of "/tmp/tmpxft_000271d9_00000000-7_carafe_cuda_kernel.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 2
```

**Reproduction**
1. What command or script did you run?
```
pip install -v -e .
python setup.py develop
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, I didn`t modify anything.
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
I can`t run this script as I have not installed successfully.
My cuda is 9.0, gcc is 5.3.0 and others are shown below:
```
addict          2.2.1
certifi         2020.4.5.1
cffi            1.14.0
cycler          0.10.0
Cython          0.29.17
kiwisolver      1.2.0
matplotlib      3.2.1
mkl-fft         1.0.15
mkl-random      1.1.0
mkl-service     2.3.0
mmcv            0.5.1
numpy           1.18.1
olefile         0.46
opencv-python   4.2.0.34
Pillow          6.2.2
pip             20.0.2
pycocotools     2.0
pycparser       2.20
pyparsing       2.4.7
python-dateutil 2.8.1
PyYAML          5.3.1
setuptools      46.1.3.post20200330
six             1.14.0
terminaltables  3.1.0
torch           1.1.0
torchvision     0.3.0
wheel           0.34.2
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
      ```conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch```
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
It looks that CUDA 8 is used for compiling.
