### ISSUE TITLE
RuntimeError for DCNv1

### ISSUE THREAD

**Issue by hkzhang95** [open-mmlab/mmdetection#2661]
**Describe the bug**
When I was trying to use DCNv1, it reports this error: "RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead."

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=0 ./tools/dist_train.sh configs/dcn/faster_rcnn_r50_fpn_dconv_c3-c5_1x_coco.py 1
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No. It is the original version
3. What dataset did you use?
MS COCO

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.5.1
MMDetection: 2.0.0+2d8bfea
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1
```

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "./tools/train.py", line 159, in <module>
    main()
  File "./tools/train.py", line 155, in main
    meta=meta)
  File "/home/zhkt3/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 289, in train
    self.call_hook('after_train_iter')
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhkt3/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
Traceback (most recent call last):
  File "/home/zhkt3/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhkt3/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/zhkt3/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zhkt3/anaconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/dcn/faster_rcnn_r50_fpn_dconv_c3-c5_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Bug fix**
I also try DCNv2 which is ok.

**Comment by xvjiarui** [comment]
Hi @hkzhang95 
The temporary workaround is to use pytorch 1.4.0. We will fix it soon.

**Comment by shinya7y** [comment]
The error disappeared by fixing `zeros_like` to `zeros`.
https://github.com/open-mmlab/mmdetection/blob/e5921ca860145abdbde64150b38225c20a48ee5c/mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp#L427

**Comment by xvjiarui** [comment]
Hi @shinya7y 
Thanks for your information. I opened a PR #2775  to fix it based on your comment. 
You are very welcome to review it.

**Comment by LaserLV52** [comment]
> The error disappeared by fixing `zeros_like` to `zeros`.
> https://github.com/open-mmlab/mmdetection/blob/e5921ca860145abdbde64150b38225c20a48ee5c/mmdet/ops/dcn/src/cuda/deform_conv_cuda.cpp#L427

I have fix the zeros_like to zeros at the Line 427 in deform_conv_cuda.cpp. But got the same error. Whether I need to recompile the setup.py after I fix the code?
