### ISSUE TITLE
How to train in single machine with multiple gpus？

### ISSUE THREAD

**Issue by 18242360613** [open-mmlab/mmdetection#2662]
I set the -- GPUs to 2, and the training can be carried out normally, but there was an error in the evaluation. The error message is as follows.

[                                                  ] 0/243, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/root/mmdetection/tools/train.py", line 156, in <module>
    main()
  File "/root/mmdetection/tools/train.py", line 152, in main
    meta=meta)
  File "/root/mmdetection/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/root/mmdetection/mmdet/apis/train.py", line 242, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 273, in train
    self.call_hook('after_train_epoch')
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 226, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 28, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/root/mmdetection/mmdet/apis/test.py", line 19, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer

Process finished with exit code 1
so,How to train in single machine with multiple gpus？

**Comment by hellock** [comment]
Please refer to the [documentation](https://mmdetection.readthedocs.io/en/latest/getting_started.html#train-with-multiple-gpus).

**Comment by deepakksingh** [comment]
I'm also facing similar issue.
I was able to train on a single machine with multiple gpus.
The training was successful, but the error occurred at the beginning of validation.
`s_rpn_bbox: 0.0591, loss_cls: 0.2948, acc: 91.5430, loss_bbox: 0.2598, loss_mask: 0.2967, loss_mask_iou: 0.0066, loss: 0.9651
2020-05-14 09:07:05,236 - mmdet - INFO - Epoch [1][14550/14659] lr: 0.02000, eta: 3 days, 19:55:07, time: 2.043, data_time: 0.137, memory: 7585, loss_rpn_cls: 0.0539, loss_rpn_bbox: 0.0656, loss_cls: 0.3184, acc: 90.7178, loss_bbox: 0.2920, loss_mask: 0.3108, loss_mask_iou: 0.0077, loss: 1.0483
2020-05-14 09:08:52,565 - mmdet - INFO - Epoch [1][14600/14659] lr: 0.02000, eta: 3 days, 19:54:17, time: 2.147, data_time: 0.171, memory: 7585, loss_rpn_cls: 0.0545, loss_rpn_bbox: 0.0685, loss_cls: 0.3172, acc: 90.6606, loss_bbox: 0.2967, loss_mask: 0.3121, loss_mask_iou: 0.0067, loss: 1.0556
2020-05-14 09:10:33,736 - mmdet - INFO - Epoch [1][14650/14659] lr: 0.02000, eta: 3 days, 19:52:19, time: 2.023, data_time: 0.137, memory: 7585, loss_rpn_cls: 0.0562, loss_rpn_bbox: 0.0657, loss_cls: 0.3161, acc: 90.7173, loss_bbox: 0.2771, loss_mask: 0.2962, loss_mask_iou: 0.0066, loss: 1.0179
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/dksingh/sandbox/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 292, in train
    self.call_hook('after_train_epoch')
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dksingh/sandbox/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 27, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/dksingh/sandbox/mmdetection/mmdet/apis/test.py", line 48, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
    return self.gather(outputs, self.output_device)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 168, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/dksingh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
TypeError: expected sequence object with len >= 0 or a single integer
`
You can notice that the training completed, and when the validation starts it threw that error.
Kindly let me know where it went wrong.
Training itself took around 6-7 hours.
Thank you
