### ISSUE TITLE
Issues when running codes. ImportError: mmdetection/mmdet/ops/utils/compiling_info.cpython-36m-x86_64-linux-gnu.so: file too short

### ISSUE THREAD

**Issue by Robert-BoMiao** [open-mmlab/mmdetection#2674]
Hi, 

I run the example codes as below and met a bug.
Could you please help me to tackle it?  Does it happended because I use python3.6 instead of python3.7?
Thanks.

/-----code------------------------------------
python tools/test.py configs/mask_rcnn_r50_fpn_1x.py \
    checkpoints/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth \
    --out results.pkl --eval bbox segm
/-----------------------------------------

/-----------------bug log-----------------------
Traceback (most recent call last):
  File "tools/test.py", line 9, in <module>
    from tools.fuse_conv_bn import fuse_module
  File "/home/bomiao/Documents/Projects/mmdetection/tools/fuse_conv_bn.py", line 7, in <module>
    from mmdet.apis import init_detector
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BitmapMasks, PolygonMasks
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmdet.ops.roi_align import roi_align
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/ops/__init__.py", line 15, in <module>
    from .utils import get_compiler_version, get_compiling_cuda_version
  File "/home/bomiao/Documents/Projects/mmdetection/mmdet/ops/utils/__init__.py", line 2, in <module>
    from .compiling_info import get_compiler_version, get_compiling_cuda_version
ImportError: /home/bomiao/Documents/Projects/mmdetection/mmdet/ops/utils/compiling_info.cpython-36m-x86_64-linux-gnu.so: file too short

/---------------------------------------------------------

**Comment by ZwwWayne** [comment]
There probably be an error copying/extracting the libraries
You can first try to remove your builds and `*.so` files in mmdet/ops/*/* and then re-build the repo.
