### ISSUE TITLE
get ValueError: too many values to unpack (expected 2) when training 

### ISSUE THREAD

**Issue by pingnuttakrid** [open-mmlab/mmdetection#2717]
Traceback (most recent call last):
  File "./mmdetection/tools/train.py", line 108, in <module>
    main()
  File "./mmdetection/tools/train.py", line 104, in main
    logger=logger)
  File "/ping/ping/RepPoints/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/ping/ping/RepPoints/mmdetection/mmdet/apis/train.py", line 143, in _dist_train
    for ds in dataset
  File "/ping/ping/RepPoints/mmdetection/mmdet/apis/train.py", line 143, in <listcomp>
    for ds in dataset
  File "/ping/ping/RepPoints/mmdetection/mmdet/datasets/loader/build_loader.py", line 28, in build_dataloader
    world_size, rank)
  File "/ping/ping/RepPoints/mmdetection/mmdet/datasets/loader/sampler.py", line 97, in __init__
    _rank, _num_replicas = get_host_info()
ValueError: too many values to unpack (expected 2) 

get this error when run command for training

**Comment by xvjiarui** [comment]
Hi @pingnuttakrid 
Are you using the latest mmdetection? 
You may use [error template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to report your error.

**Comment by CMobley7** [comment]
@pingnuttakrid , can you include your function call? What arguments are you sending into `tools/train.py` when you run it?
