### ISSUE TITLE
Question about MaskedConv2d.

### ISSUE THREAD

**Issue by AFutureD** [open-mmlab/mmdetection#2726]
In the function `MaskedConv2dFunction`, I don't know the meaning of the first two lines.
Why is the mask would be three dimensions? And why is the value of the feature's first dimension should be 1, not the batch size?

Here are the codes:
``` python
class MaskedConv2dFunction(Function):

    @staticmethod
    def forward(ctx, features, mask, weight, bias, padding=0, stride=1):
        assert mask.dim() == 3 and mask.size(0) == 1  # this line 
        assert features.dim() == 4 and features.size(0) == 1  # And, this line
        ...
```

**Comment by AFutureD** [comment]
Can you provide me some original source of the function?

**Comment by hellock** [comment]
These two lines indicate the same thing: only batch_size=1 is supported.

**Comment by dimimal** [comment]
Hello everyone, I faced the same issue, but surprisingly after my model finished the first training epoch along with the evaluation. In the beginning of the 2nd training epoch I get the following error 

```
Traceback (most recent call last):
  File "tools/train.py", line 183, in <module>
    main()
  File "tools/train.py", line 179, in main
    meta=meta)
  File "/mnt/N1534240/projects/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 89, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/base.py", line 261, in val_step
    losses = self(**data)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 49, in forward_train
    outs = self(x)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 234, in forward
    return multi_apply(self.forward_single, feats)
  File "/mnt/N1534240/projects/mmdetection/mmdet/core/utils/misc.py", line 26, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/ga_rpn_head.py", line 36, in forward_single
    loc_pred) = super(GARPNHead, self).forward_single(x)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 229, in forward_single
    cls_score = self.conv_cls(x, mask)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/ops/masked_conv.py", line 110, in forward
    self.padding)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/ops/masked_conv.py", line 31, in forward
    assert features.dim() == 4 and features.size(0) == 1
AssertionError
```

Any ideas?
