### ISSUE TITLE
for object detection task,how can i training cascade-mask-r-cnn on custom datasets without segentation labels

### ISSUE THREAD

**Issue by kiddliao** [open-mmlab/mmdetection#2749]
您好:
i use configs/cascade_rcnn/cascade_mask_rcnn_x101_64x4d_fpn_20e_coco.py
and i change
_base_ = [
    '../_base_/models/cascade_mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_20e.py', '../_base_/default_runtime.py'
]
to
_base_ = [
    '../_base_/models/cascade_mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_20e.py', '../_base_/default_runtime.py'
]
then raise NoneType Error

i can train on my datasets with configs/cascade_rcnn/cascade_rcnn_x101_64x4d_fpn_20e_coco.py successfully

**Comment by kiddliao** [comment]
this is the error

2020-05-18 14:10:25,910 - root - INFO - load model from: open-mmlab://resnext101_64x4d
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-05-18 14:11:09,116 - mmdet - INFO - Start running, host: bruce@AIloy, work_dir: /data/4T/home/bruce/project/lh/mmdetection-master/xray_dirs
2020-05-18 14:11:09,116 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bruce/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/bruce/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/bruce/.vscode-server/extensions/ms-python.python-2020.5.78807/pythonFiles/lib/python/debugpy/no_wheels/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/usr/local/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bruce/lh/mmdetection-master/tools/train.py", line 160, in <module>
    main()
  File "/home/bruce/lh/mmdetection-master/tools/train.py", line 156, in main
    meta=meta)
  File "/data/4T/home/bruce/project/lh/mmdetection-master/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/bruce/lh/envs/mmlab/lib/python3.6/site-packa

**Comment by kiddliao** [comment]
this is the error
![image](https://user-images.githubusercontent.com/57079702/82187582-34608c80-991f-11ea-9c74-be8569f9b9f9.png)

**Comment by ZwwWayne** [comment]
We cannot you train the mask branch without a mask label, it is supervised learning.
If you want to train cascade mask r-cnn without mask branch, then simply use cascade rcnn should be OK.
