### ISSUE TITLE
when use p100 train meet cuda error

### ISSUE THREAD

**Issue by ranjiewwen** [open-mmlab/mmdetection#2778]
- when i use the code to train, use p100 training willmeet problem below，when use v100 will not meet problem, why? cuda problem ?
> THCudaCheck FAIL file=mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu line=128 error=48 : unrecognized error code
Traceback (most recent call last):
  File "tools/train.py", line 157, in 
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/data/youcaizi/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 282, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/apis/train.py", line 74, in batch_processor
    losses = model(**data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/models/detectors/base.py", line 148, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/models/detectors/single_stage.py", line 90, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/youcaizi/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/models/dense_heads/fcos_head.py", line 185, in loss
    avg_factor=num_pos + num_imgs)  # avoid num_pos is 0
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/youcaizi/mmdetection/mmdet/models/losses/focal_loss.py", line 90, in forward
    avg_factor=avg_factor)
  File "/data/youcaizi/mmdetection/mmdet/models/losses/focal_loss.py", line 37, in sigmoid_focal_loss
    loss = _sigmoid_focal_loss(pred, target, gamma, alpha)
  File "/data/youcaizi/mmdetection/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss.py", line 19, in forward
    gamma, alpha)
RuntimeError: cuda runtime error (48) : unrecognized error code at mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu:128

**Comment by ZwwWayne** [comment]
Please run the `collect_env.py` and post the results.

**Comment by ranjiewwen** [comment]
```
sys.platform: linux
Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 9.0, V9.0.176
GPU 0,1,2,3: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 3.4.3
MMCV: 0.5.1
MMDetection: 2.0.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 9.0
```

**Comment by ZwwWayne** [comment]
It seems that the CUDA compiler is not compatible with the Pytorch you installed. The PyTorch is built by CUDA 10.1, but your cuda version is 9.0.

**Comment by ranjiewwen** [comment]
> It seems that the CUDA compiler is not compatible with the Pytorch you installed. The PyTorch is built by CUDA 10.1, but your cuda version is 9.0.

maybe not, when i use v100,  the env is same: The PyTorch is built by CUDA 10.1, and cuda version is 9.0.

**Comment by ZwwWayne** [comment]
This might because MMDet or PyTorch/torchvision is not built for the correct GPU architecture (compute compatibility).

Try `export TORCH_CUDA_ARCH_LIST=6.0,7.0` , it should makes it compile for both P100s and V100s
