### ISSUE TITLE
PermissionError: 13 when run demo in win10(cpu device)

### ISSUE THREAD

**Issue by ouening** [open-mmlab/mmdetection#2784]
OS: Win10
mmdetection: 2.0
VS: 2017
I successfully installed `mmdetection` in win10 using VS2017, but when I ran the simple demo example I got error as title tell. Detailed info is:
```
webcam_demo.py 46 <module>
main()

webcam_demo.py 28 main
model = init_detector(args.config, args.checkpoint, device=device)

inference.py 28 init_detector
config = mmcv.Config.fromfile(config)

config.py 165 fromfile
cfg_dict, cfg_text = Config._file2dict(filename)

config.py 92 _file2dict
osp.join(temp_config_dir, temp_config_name))

shutil.py 121 copyfile
with open(dst, 'wb') as fdst:

PermissionError:
13
Permission denied
```
I was in administrate mode, but the error still occured. How can I fix it?

**Comment by sciencestarstar** [comment]
同学，请问win10下如何安装2.0版本

**Comment by ouening** [comment]
> 同学，请问win10下如何安装2.0版本

## 环境
- Visual Studio2017
- pytorch1.5
- python3

```
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
```
下面安装Pycocotools，官网教程给出的安装方式是Linux环境的，Windows下要安装下面版本的Pycocotools，
笔者在没有安装此库的情况下仍然可以编译安装mmdetection2.

首先下载程序：
```
git clone https://github.com/cocodataset/cocoapi.git
```
修改文件<cocoapi>/PythonAPI/setup.py第12行(否则会报一个编译错误）：
```
extra_compile_args=['-std=c99'],
```
然后执行安装步骤：
```
cd cocoapi/PythonAPI
python setup.py install
```

最后安装mmdetection2
```
pip install -v -e . # 或者python setup.py develop
```

**Comment by sciencestarstar** [comment]
> > 同学，请问win10下如何安装2.0版本
> 
> ## 环境
> * Visual Studio2017
> * pytorch1.5
> * python3
> 
> ```
> git clone https://github.com/open-mmlab/mmdetection.git
> cd mmdetection
> pip install -r requirements/build.txt
> ```
> 
> 下面安装Pycocotools，官网教程给出的安装方式是Linux环境的，Windows下要安装下面版本的Pycocotools，
> 笔者在没有安装此库的情况下仍然可以编译安装mmdetection2.
> 
> 首先下载程序：
> 
> ```
> git clone https://github.com/cocodataset/cocoapi.git
> ```
> 
> 修改文件/PythonAPI/setup.py第12行(否则会报一个编译错误）：
> 
> ```
> extra_compile_args=['-std=c99'],
> ```
> 
> 然后执行安装步骤：
> 
> ```
> cd cocoapi/PythonAPI
> python setup.py install
> ```
> 
> 最后安装mmdetection2
> 
> ```
> pip install -v -e . # 或者python setup.py develop
> ```

同学  我今天早上试了一下 还是不行  一下是报错信息：
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\mmdetection\mmdet\ops\utils\src\compiling_info.cpp /FoD:\mmdetection\build\temp.win-amd64-3.6\Release\mmdet\ops\utils\src/compiling_info.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/mmdetection/build/temp.win-amd64-3.6/Release/mmdet/ops/utils/src/compiling_info.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\include -IC:\ProgramData\Anaconda3\envs\open-mmlab-v2\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c D:\mmdetection\mmdet\ops\utils\src\compiling_info.cpp /FoD:\mmdetection\build\temp.win-amd64-3.6\Release\mmdet\ops\utils\src/compiling_info.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=compiling_info -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\site-packages\torch\utils\cpp_extension.py", line 1401, in _run_ninja_build
    check=True)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab-v2\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by sciencestarstar** [comment]
我查了一下  好像没有以下这个文件 导致报错的：
FAILED: D:/mmdetection/build/temp.win-amd64-3.6/Release/mmdet/ops/utils/src/compiling_info.obj

**Comment by ankur7721** [comment]
@ouening Is your problem resolved now ?
if yes can you suggest, how ?

**Comment by Lytua** [comment]
我在跑mmfashion的model時也遇到相同問題 python demo/test_predictor.py --input demo/img/attr_pred_demo1.jpg

` File "demo/test_predictor.py", line 57, in <module>
    main()
  File "demo/test_predictor.py", line 37, in main
    cfg = Config.fromfile(args.config)
  File "C:\Anaconda\envs\deepfashion\lib\site-packages\mmcv\utils\config.py", line 166, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "C:\Anaconda\envs\deepfashion\lib\site-packages\mmcv\utils\config.py", line 93, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "C:\Anaconda\envs\deepfashion\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Anaconda\envs\deepfashion\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied:`

**Comment by JinqingZhengTju** [comment]
@ouening 我也遇到了同样的问题，不知您有没有解决了？

**Comment by JinqingZhengTju** [comment]
@sciencestarstar 确实没有你说的这个文件，是因为编译mmdetection有问题，才导致的没有这个文件吗？

**Comment by Lytua** [comment]
@JinqingZhengTju 
我把我的解法寫在這裡，謝謝: 
https://github.com/open-mmlab/mmfashion/issues/60#issuecomment-635622137

**Comment by ouening** [comment]
@Lytua 通过你的方法成功解决了此问题
