### ISSUE TITLE
There was an error when using image_demo.py

### ISSUE THREAD

**Issue by fxlong** [open-mmlab/mmdetection#2813]
)
Traceback (most recent call last):
  File "demo/image_demo.py", line 27, in <module>
    main()
  File "demo/image_demo.py", line 21, in main
    result = inference_detector(model, args.img)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/apis/inference.py", line 84, in inference_detector
    data = test_pipeline(data)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/datasets/pipelines/test_aug.py", line 25, in __call__
    data = self.transforms(_results)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/datasets/pipelines/transforms.py", line 305, in __call__
    self._pad_img(results)
  File "/home/s02/fxl/acm-challenge/mmdetection/mmdet/datasets/pipelines/transforms.py", line 290, in _pad_img
    results['pad_shape'] = padded_img.shape
UnboundLocalError: local variable 'padded_img' referenced before assignment

**Comment by hellock** [comment]
This error should have been fixed in the latest version.

**Comment by fxlong** [comment]
thanks
