### ISSUE TITLE
NameError: name 'data_root_train' is not defined and FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9fod2_s_/tmp5r312299.py'

### ISSUE THREAD

**Issue by yuyijie1995** [open-mmlab/mmdetection#2827]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When I use 'python tools/train.py configs xxx ', this error happened .

Traceback (most recent call last):
  File "tools/train.py", line 151, in <module>
    main()
  File "tools/train.py", line 67, in main
    cfg = Config.fromfile(args.config)
  File "/root/miniconda3/envs/torch/lib/python3.6/site-packages/mmcv-0.5.6-py3.6-linux-x86_64.egg/mmcv/utils/config.py", line 165, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/root/miniconda3/envs/torch/lib/python3.6/site-packages/mmcv-0.5.6-py3.6-linux-x86_64.egg/mmcv/utils/config.py", line 95, in _file2dict
    mod = import_module(temp_module_name)
  File "/root/miniconda3/envs/torch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp9fod2_s_/tmp5r312299.py", line 182, in <module>
NameError: name 'data_root_train' is not defined
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7fc97b7c99b0>>
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/root/miniconda3/envs/torch/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9fod2_s_/tmp5r312299.py'

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/....
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes,I changed some model files. Yes.
3. What dataset did you use?
coco
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
sys.platform: linux
Python: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
CUDA available: False
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.2.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.4.0
OpenCV: 4.2.0
MMCV: 0.5.6
MMDetection: 1.1.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
pip 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
(torch) root@xray-08:/home/my_mm/mmdetection-master# python tools/train.py configs/Fusai/faster_100.py
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-10.1'
Traceback (most recent call last):
  File "tools/train.py", line 151, in <module>
    main()
  File "tools/train.py", line 67, in main
    cfg = Config.fromfile(args.config)
  File "/root/miniconda3/envs/torch/lib/python3.6/site-packages/mmcv-0.5.6-py3.6-linux-x86_64.egg/mmcv/utils/config.py", line 165, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/root/miniconda3/envs/torch/lib/python3.6/site-packages/mmcv-0.5.6-py3.6-linux-x86_64.egg/mmcv/utils/config.py", line 95, in _file2dict
    mod = import_module(temp_module_name)
  File "/root/miniconda3/envs/torch/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp9fod2_s_/tmp5r312299.py", line 182, in <module>
NameError: name 'data_root_train' is not defined
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7fc97b7c99b0>>
Traceback (most recent call last):
  File "/root/miniconda3/envs/torch/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/root/miniconda3/envs/torch/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp9fod2_s_/tmp5r312299.py'
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yuyijie1995** [comment]
‘No CUDA runtime is found ‘ had been solved, but the other problem is still existing.

**Comment by mdv3101** [comment]
Facing similar issue:
`Traceback (most recent call last):
  File "./tools/train.py", line 159, in <module>
    main()
  File "./tools/train.py", line 68, in main
    cfg = Config.fromfile(args.config)
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 165, in fromfile
Traceback (most recent call last):
  File "./tools/train.py", line 159, in <module>
    main()
  File "./tools/train.py", line 68, in main
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    cfg = Config.fromfile(args.config)
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 165, in fromfile
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  [Previous line repeated 1 more time]
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 95, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/madhav3101/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  [Previous line repeated 1 more time]
  File "/home/madhav3101/torch-env/lib/python3.7/site-packages/mmcv/utils/config.py", line 95, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/madhav3101/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp5cx903vu/tmp1pcav906.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpxukit6h4/tmp52a2c6rt.py", line 5, in <module>
TypeError: cannot convert dictionary update sequence element #0 to a sequence
TypeError: cannot convert dictionary update sequence element #0 to a sequence
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x155294354268>
Traceback (most recent call last):
  File "/home/madhav3101/miniconda3/lib/python3.7/tempfile.py", line 448, in __del__
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x14588528c268>
Traceback (most recent call last):
  File "/home/madhav3101/miniconda3/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/madhav3101/miniconda3/lib/python3.7/tempfile.py", line 444, in close
    self.close()
  File "/home/madhav3101/miniconda3/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxukit6h4/tmp52a2c6rt.py'
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5cx903vu/tmp1pcav906.py'
`

**Comment by xvjiarui** [comment]
Hi @yuyijie1995 @mdv3101 
Sorry for the late reply. Could you please provide the config file you used? It seems that the errors occurred during import.

**Comment by mdv3101** [comment]
Hi @xvjiarui ,
Sorry, Now I don't have the configuration file. I re-installed the mmdetection and now it is working fine.

**Comment by yuyijie1995** [comment]
@xvjiarui I solved this problem. I guess it's because the new MMCV is incompatible with my old mmdetection files. I uninstalled the mmcv-0.5.X and downgrade it to 0.2.X and it worked.

**Comment by SinaMohseni** [comment]
I'm getting this error too. should I try downdrading?  


TorchVision: 0.8.2+cu101
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0+6a979e2

sys.platform: linux
Python: 3.7.10 (default, Feb 20 2021, 21:21:24) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0,1,2,3: GeForce GTX TITAN X
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 7.5, V7.5.17
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2


(open-mmlab) ..@lab-devbox:~/.../Swin-Transformer-Object-Detection$ bash test.sh
Traceback (most recent call last):
  File "./tools/test.py", line 224, in <module>
    main()
  File "./tools/test.py", line 118, in main
    cfg = Config.fromfile(args.config)
  File "/home/.../Swin-Transformer-Object-Detection/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 316, in fromfile
    use_predefined_variables)
  File "/home/.../Swin-Transformer-Object-Detection/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 205, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpml1rkzrt/tmpefl37an5.py", line 141, in <module>
NameError: name 'false' is not defined
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7ff9b87e37a0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/tempfile.py", line 587, in __del__
    self.close()
  File "/usr/lib/python3.7/tempfile.py", line 583, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpml1rkzrt/tmpefl37an5.py'
