### ISSUE TITLE
validate - TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

### ISSUE THREAD

**Issue by FantasyJXF** [open-mmlab/mmdetection#2830]
**Describe the bug**
Training model with `validate` would run into error like this:
```
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```
And it's OK if I open the param `--no-validate`.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py  \
    configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py 
```
or
```
python tools/train.py  \
    configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py 
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
> No
3. What dataset did you use?
> coco2017

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```
sys.platform: linux
Python: 3.6.8 (default, Sep 17 2019, 18:22:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: Tesla V100-SXM2-32GB
GCC: gcc (GCC) 5.4.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0+cu100
OpenCV: 4.2.0
MMCV: 0.5.5
MMDetection: 2.0.0+a9bedfb
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0
```
2. You may add addition that may be helpful for locating the problem, such as
> Nothing special here, install pytorch 1.4.0 from official file.

**Error traceback**
If applicable, paste the error trackback here.
```
2020-05-27 17:52:14,255 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=1.20s)
creating index...
index created!
Traceback (most recent call last):
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/ipdb/__main__.py", line 276, in main
    pdb._runscript(mainpyfile)
  File "/usr/local/python3.6.8/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/usr/local/python3.6.8/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/work/JXF/mmdetection/tools/train.py", line 1, in <module>
    import argparse
  File "/home/work/JXF/mmdetection/tools/train.py", line 163, in main
    meta=meta)
  File "/home/work/JXF/mmdetection/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 292, in train
    self.call_hook('after_train_epoch')
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/work/JXF/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 28, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/work/JXF/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/work/JXF/mmdetection/mmdet/datasets/coco.py", line 384, in evaluate
    cocoEval = COCOeval(cocoGt, cocoDt, iou_type)
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/work/.virtualenvs/mmdetection/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by yuyijie1995** [comment]
I met the same error ,have you solved it?

**Comment by ZwwWayne** [comment]
Hi @FantasyJXF @yuyijie1995 ,
For now, you can downgrade the version of numpy to be <= 1.18.0. As long as the version is lower than 1.18.0, the bug should be fixed.

**Comment by FantasyJXF** [comment]
@ZwwWayne `numpy 1.18.0` still runs into error, `numpy 1.17.0` works right.

May be you should modify [this line](https://github.com/open-mmlab/mmdetection/blob/master/requirements/build.txt#L2) like this:
```
numpy<1.18.0
```

**Comment by chAwater** [comment]
Update cocoapi may solve this problem:
`pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'`

**Comment by ZwwWayne** [comment]
To use numpy>=1.18.0 with COCOAPI, we recommend to use https://github.com/open-mmlab/cocoapi. We will maintain and update this fork.

**Comment by FantasyJXF** [comment]
That's very nice. I installed cocoapi with `pip intal pycocotools`.
