### ISSUE TITLE
Error when test image being padded

### ISSUE THREAD

**Issue by kbiyani33** [open-mmlab/mmdetection#2851]
Getting an error as follows while running image_demo.py:
***
Traceback (most recent call last):
  File "image_demo.py", line 11, in <module>
    result = inference_detector(model, img)
  File "/mnt/keshav/mmdetection/mmdet/apis/inference.py", line 84, in inference_detector
    data = test_pipeline(data)
  File "/mnt/keshav/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/mnt/keshav/mmdetection/mmdet/datasets/pipelines/test_aug.py", line 25, in __call__
    data = self.transforms(_results)
  File "/mnt/keshav/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/mnt/keshav/mmdetection/mmdet/datasets/pipelines/transforms.py", line 305, in __call__
    self._pad_img(results)
  File "/mnt/keshav/mmdetection/mmdet/datasets/pipelines/transforms.py", line 290, in _pad_img
    results['pad_shape'] = padded_img.shape
UnboundLocalError: local variable 'padded_img' referenced before assignment
***

CONDA ENVIRONMENT:
Python 3.7.7
CUDA 10.1
Pytorch 1.5.0

One of the solutions to this problem was to update to the latest version.
My mmdet version is 2.0.0, and my MMDetection is at it's latest version since the last updates were made 23 days from today and I started working on mmdet just 10 days back. So I am assuming my version is at the latest version.
CONFIG FILE: GCNET config file mask_rcnn_r101_fpn_gcb_c3-c5_1x_coco.py
My dataset is getting trained on properly without any issues, and box and seem evaluation also seems to be working fine on already resized test images. I would now want to test on raw non resized images for which I added the pad augmentation in the test pipeline. In case there's any information from my side that I am missing please let me know. Thanks.

**Comment by kbiyani33** [comment]
Fixed!!
I was on a docker image, rebuilding the code base again from scratch had worked for me.
