### ISSUE TITLE
No module named numpy 

### ISSUE THREAD

**Issue by Vankeee** [open-mmlab/mmdetection#287]
(mmdetection) ****@ubuntu:~/mmdetection$ sudo ./compile.sh
Building roi align op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building roi pool op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building nms op...
rm -f *.so
echo "Compiling nms kernels..."
Compiling nms kernels...
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import numpy as np
ImportError: No module named numpy
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by Vankeee** [comment]
Does any know what is wrong?
