### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. 

### ISSUE THREAD

**Issue by naturino** [open-mmlab/mmdetection#2883]
**I'm trainning mask-rcnn with coco dataset meet the erro:**

Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 157, in main
    meta=meta)
  File "/dicom/Adam/code/mmdetection/mmdet/apis/train.py", line 176, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 282, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/dicom/Adam/code/mmdetection/mmdet/apis/train.py", line 77, in batch_processor
    losses = model(**data)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 462, in forward
    self.reducer.prepare_for_backward([])

RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

**This is my Environment:**

sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1/
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1: GeForce RTX 2080
GCC: gcc (GCC) 7.3.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture 

**I try to set find_unused_parameters = cfg.get('find_unused_parameters', True), then the error disappeared, but my training process got stuck.**  

**such as:**

2020-06-03 11:29:53,918 - mmdet - INFO - Start running, host: ubuntu@ln-mass, work_dir: /dicom/Adam/code/mmdetection/log/mask_rcnn_r50_fpn_1x
2020-06-03 11:29:53,918 - mmdet - INFO - workflow: [('train', 1)], max: 15 epochs
2020-06-03 11:29:57,301 - mmdet - INFO - Epoch [1][1/53]        lr: 0.00002, eta: 0:43:37, time: 3.296, data_time: 2.563, memory: 3177, loss_rpn_cls: 0.4322, loss_rpn_bbox: 0.0274, loss_cls: 0.2866, acc: 98.8281, loss_bbox: 0.0340, loss_mask: 0.8534, loss: 1.6336
2020-06-03 11:29:57,653 - mmdet - INFO - Epoch [1][2/53]        lr: 0.00012, eta: 0:24:25, time: 0.400, data_time: 0.088, memory: 3456, loss_rpn_cls: 0.0118, loss_rpn_bbox: 0.0035, loss_cls: 0.3228, acc: 98.0957, loss_bbox: 0.0695, loss_mask: 0.7520, loss: 1.1596
2020-06-03 11:29:57,997 - mmdet - INFO - Epoch [1][3/53]        lr: 0.00022, eta: 0:17:46, time: 0.344, data_time: 0.055, memory: 3457, loss_rpn_cls: 0.0452, loss_rpn_bbox: 0.0075, loss_cls: 0.2955, acc: 99.2188, loss_bbox: 0.0237, loss_mask: 0.9116, loss: 1.2836
2020-06-03 11:29:58,332 - mmdet - INFO - Epoch [1][4/53]        lr: 0.00032, eta: 0:14:25, time: 0.335, data_time: 0.040, memory: 3457, loss_rpn_cls: 0.0580, loss_rpn_bbox: 0.0158, loss_cls: 0.3211, acc: 97.9980, loss_bbox: 0.0808, loss_mask: 0.8483, loss: 1.3239
2020-06-03 11:29:58,678 - mmdet - INFO - Epoch [1][5/53]        lr: 0.00042, eta: 0:12:25, time: 0.347, data_time: 0.051, memory: 3457, loss_rpn_cls: 0.0464, loss_rpn_bbox: 0.0083, loss_cls: 0.2969, acc: 97.8027, loss_bbox: 0.0857, loss_mask: 0.9451, loss: 1.3825
2020-06-03 11:29:59,013 - mmdet - INFO - Epoch [1][6/53]        lr: 0.00052, eta: 0:11:04, time: 0.334, data_time: 0.040, memory: 3458, loss_rpn_cls: 0.0614, loss_rpn_bbox: 0.0079, loss_cls: 0.2728, acc: 98.5840, loss_bbox: 0.0533, loss_mask: 0.6696, loss: 1.0650
2020-06-03 11:29:59,348 - mmdet - INFO - Epoch [1][7/53]        lr: 0.00062, eta: 0:10:06, time: 0.336, data_time: 0.052, memory: 3458, loss_rpn_cls: 0.0196, loss_rpn_bbox: 0.0042, loss_cls: 0.2600, acc: 98.8770, loss_bbox: 0.0439, loss_mask: 0.7691, loss: 1.0968
2020-06-03 11:29:59,684 - mmdet - INFO - Epoch [1][8/53]        lr: 0.00072, eta: 0:09:23, time: 0.335, data_time: 0.040, memory: 3458, loss_rpn_cls: 0.0177, loss_rpn_bbox: 0.0068, loss_cls: 0.2538, acc: 97.7539, loss_bbox: 0.0863, loss_mask: 0.8242, loss: 1.1888

**it's getting stuck,If you have method to solve the erro ,pls tell me！Thanks**

**Comment by deepakksingh** [comment]
I'm facing similar issue when training Group Norm based models.
How did you resolve this?
