### ISSUE TITLE
Batch_size ERROR: ValueError: batch_size should be a positive integer value, but got batch_size=0

### ISSUE THREAD

**Issue by zhaowujie** [open-mmlab/mmdetection#2885]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.

**Describe the bug**
I set `--gpus` to `0`  in `./tools/train.py` , and got an error:
```shell
ValueError: batch_size should be a positive integer value, but got batch_size=0
```

**Reproduction**
1. What command or script did you run?
```
cd tools && python train.py --config ../configs/cascade_rcnn_x101_64x4d_fpn_1x_coco.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I use my own dataset， and modified `dataset_type, data_root, img_norm_cfg etc.`
3. What dataset did you use?
dataset like coco
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```shell
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.5.8
MMDetection: 2.0.0+fb9efc2
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection2/tools/train.py", line 166, in <module>
    main()
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection2/tools/train.py", line 162, in main
    meta=meta)
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection2/mmdet/apis/train.py", line 116, in train_detector
    seed=cfg.seed) for ds in dataset
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection2/mmdet/apis/train.py", line 116, in <listcomp>
    seed=cfg.seed) for ds in dataset
  File "/media/hp208/4t/zhaoxingjie/project_graduation/mmdetection2/mmdet/datasets/builder.py", line 125, in build_dataloader
    **kwargs)
  File "/media/hp208/4t/soft/anaconda3/envs/mmdetection2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 219, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/media/hp208/4t/soft/anaconda3/envs/mmdetection2/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 190, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integer value, but got batch_size=0

Process finished with exit code 1
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hellock** [comment]
You may first try it on VOC or COCO. If there is no error, you may check your dataset.

**Comment by zhaowujie** [comment]
But I tried my dataset on MMDetection 1.0, everything is OK.

**Comment by zhaowujie** [comment]
I solved it. Use CUDA10.0 instead 10.1
```
conda install pytorch==1.3.0 cudatoolkit=10.0 torchvision -c pytorch
```
Thanks anyway.
