### ISSUE TITLE
RuntimeError: DataLoader worker (pid 34569) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

### ISSUE THREAD

**Issue by woshildh** [open-mmlab/mmdetection#291]
您好，我在训练mmdetction的时候，每次都是训练600~1000steps之后会报错？数据加载的python进程的内存占比会不断升高，直到报错？我是用的slurm集群训练的。我安装的pytorch版本是0.4.1，用的是pip安装的方式。
``    return self.data_queue.get()
  File "/mnt/lustre/liudonghui/anaconda3/envs/venv_mmdet/lib/python3.6/multiprocessing/queues.py", line 342, in get
    res = self._reader.recv_bytes()
  File "/mnt/lustre/liudonghui/anaconda3/envs/venv_mmdet/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/mnt/lustre/liudonghui/anaconda3/envs/venv_mmdet/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/mnt/lustre/liudonghui/anaconda3/envs/venv_mmdet/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/mnt/lustre/liudonghui/anaconda3/envs/venv_mmdet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 227, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 34569) is killed by signal: Bus error. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

**Comment by hellock** [comment]
Running on clusters managed by slurm is a little different. For users at sensetime, you can send an email to caoyuhang@sensetime.com.

**Comment by lvchigo** [comment]
- hi, when i build docker image, and run it, the error come like : RuntimeError: DataLoader worker (pid 147) is killed by signal: Bus error.

`
Traceback (most recent call last):
  File "/tmp/src/pytorch/image_detect/mmdetection_gcc540//tools/train_douyu.py", line 324, in <module>
    main()
  File "/tmp/src/pytorch/image_detect/mmdetection_gcc540//tools/train_douyu.py", line 320, in main
    logger=logger)
  File "/tmp/src/pytorch/image_detect/mmdetection_gcc540/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/tmp/src/pytorch/image_detect/mmdetection_gcc540/mmdet/apis/train.py", line 222, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 260, in train
    for i, data_batch in enumerate(data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 147) is killed by signal: Bus error.
`
