### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by Hwang64** [open-mmlab/mmdetection#294]
When I train the code, there is an error, I install the mmdetection through the conda, how I solve this issue? Thanks a lot!
{conda is loaded}
2019-01-27 16:08:42,301 - INFO - Distributed training: False
2019-01-27 16:08:43,383 - INFO - load model from: modelzoo://resnet101
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /home/sirius/.torch/models/resnet101-5d3b4d8f.pth
Traceback (most recent call last):
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x2ab63b7a9320>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /models/resnet101-5d3b4d8f.pth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2ab63b7a9320>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 90, in <module>
    main()
  File "tools/train.py", line 77, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/sirius/mmdetection/mmdet/models/builder.py", line 51, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/sirius/mmdetection/mmdet/models/builder.py", line 31, in build
    return _build_module(cfg, registry, default_args)
  File "/home/sirius/mmdetection/mmdet/models/builder.py", line 23, in _build_module
    return obj_type(**args)
  File "/home/sirius/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/sirius/mmdetection/mmdet/models/detectors/two_stage.py", line 50, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/sirius/mmdetection/mmdet/models/detectors/two_stage.py", line 58, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/sirius/mmdetection/mmdet/models/backbones/resnet.py", line 349, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 106, in load_checkpoint
    checkpoint = model_zoo.load_url(model_urls[model_name])
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 65, in load_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 71, in _download_url_to_file
    u = urlopen(url, stream=True)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/sirius/.conda/envs/open-mmlab/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /models/resnet101-5d3b4d8f.pth (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x2ab63b7a9320>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by hellock** [comment]
It's your networking error and cannot download pretrained models from `download.pytorch.org`.

**Comment by Hwang64** [comment]
Thanks a lot and I have solved this issue

**Comment by cuiercuier** [comment]
I have the same problem,can you tell me  how to fix it

**Comment by cuiercuier** [comment]
> Thanks a lot and I have solved this issue

I have the same problem,can you tell me how to fix it
