### ISSUE TITLE
A problem while transfering .pth to .onnx format

### ISSUE THREAD

**Issue by CatbossMr** [open-mmlab/mmdetection#2977]
Hello there, I'm trying to convert .pth format to .onnx, using faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth

After typing the command to convert, I saw this :

```
/home/user/mmdetection/mmdet/core/bbox/transforms.py:161: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.size(0) > 0:
/home/user/mmdetection/mmdet/models/roi_extractors/single_level.py:103: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if inds.any():
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 124, in <module>
    main()
  File "tools/pytorch2onnx.py", line 116, in main
    onnx_model = export_onnx_model(model, (input_data, ), args.passes)
  File "tools/pytorch2onnx.py", line 43, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 352, in forward
    out = self.inner(*trace_inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/user/mmdetection/mmdet/models/detectors/two_stage.py", line 114, in forward_dummy
    x[:self.bbox_roi_extractor.num_inputs], rois)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/user/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/mmdetection/mmdet/models/roi_extractors/single_level.py", line 105, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/user/mmdetection/mmdet/ops/roi_align/roi_align.py", line 77, in forward
    self.spatial_scale, self.sample_num)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 69, in roi_align
    return _RoIAlignFunction.apply(input, rois, output_size, spatial_scale, sampling_ratio)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torchvision/ops/roi_align.py", line 24, in forward
    output_size[0], output_size[1], sampling_ratio)
RuntimeError: rois.device().is_cpu() INTERNAL ASSERT FAILED at /opt/conda/conda-bld/torchvision_1573068346791/work/torchvision/csrc/cpu/ROIAlign_cpu.cpp:386, please report a bug to PyTorch. rois must be a CPU tensor (ROIAlign_forward_cpu at /opt/conda/conda-bld/torchvision_1573068346791/work/torchvision/csrc/cpu/ROIAlign_cpu.cpp:386)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f72140b1687 in /home/user/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: ROIAlign_forward_cpu(at::Tensor const&, at::Tensor const&, float, int, int, int) + 0x277 (0x7f71f8e4bfb3 in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #2: ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int) + 0x92 (0x7f71f8e13059 in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #3: <unknown function> + 0x7713e (0x7f71f8e3a13e in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #4: <unknown function> + 0x73c48 (0x7f71f8e36c48 in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #5: <unknown function> + 0x6ee7d (0x7f71f8e31e7d in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #6: <unknown function> + 0x6f122 (0x7f71f8e32122 in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
frame #7: <unknown function> + 0x5ccb1 (0x7f71f8e1fcb1 in /home/user/anaconda3/lib/python3.7/site-packages/torchvision/_C.so)
<omitting python frames>
frame #12: THPFunction_apply(_object*, _object*) + 0x8d6 (0x7f7244c4b086 in /home/user/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
```

my command is :

```
python tools/pytorch2onnx.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth  --out work_dirs/zxf/output.onnx
```

Could somebody tell me what's going on and how to solve this problem?

thanks !

**Comment by Single430** [comment]
I also encountered the same problem, do you have a solution？ @CatbossMr

**Comment by CatbossMr** [comment]
> I also encountered the same problem, do you have a solution？ @CatbossMr @hellock thx!
> 
> ```
> torch==1.2.0
> torchvision==0.4.0
> onnx==1.6.0
> ```

which mmdetection version are you using?

**Comment by Single430** [comment]
> > I also encountered the same problem, do you have a solution？ @CatbossMr @hellock thx!
> > ```
> > torch==1.2.0
> > torchvision==0.4.0
> > onnx==1.6.0
> > ```
> 
> which mmdetection version are you using?

```
# GENERATED VERSION FILE
# TIME: Wed Feb 12 13:00:43 2020

__version__ = '1.0.0+1d7b0a7'
short_version = '1.0.0'
```

**Comment by CatbossMr** [comment]
> > > I also encountered the same problem, do you have a solution？ @CatbossMr @hellock thx!
> > > ```
> > > torch==1.2.0
> > > torchvision==0.4.0
> > > onnx==1.6.0
> > > ```
> > 
> > 
> > which mmdetection version are you using?
> 
> ```
> # GENERATED VERSION FILE
> # TIME: Wed Feb 12 13:00:43 2020
> 
> __version__ = '1.0.0+1d7b0a7'
> short_version = '1.0.0'
> ```

Your version is too old to transform .pth to .onnx,Maybe you can try installing mmdetection==2.1.0,and then follow the [link](https://blog.csdn.net/qq_21464351/article/details/106731953) to transfrom

**Comment by Single430** [comment]
> > > > I also encountered the same problem, do you have a solution？ @CatbossMr @hellock thx!
> > > > ```
> > > > torch==1.2.0
> > > > torchvision==0.4.0
> > > > onnx==1.6.0
> > > > ```
> > > 
> > > 
> > > which mmdetection version are you using?
> > 
> > 
> > ```
> > # GENERATED VERSION FILE
> > # TIME: Wed Feb 12 13:00:43 2020
> > 
> > __version__ = '1.0.0+1d7b0a7'
> > short_version = '1.0.0'
> > ```
> 
> Your version is too old to transform .pth to .onnx,Maybe you can try installing mmdetection==2.1.0,and then follow the [link](https://blog.csdn.net/qq_21464351/article/details/106731953) to transfrom

Success, thanks!!
