### ISSUE TITLE
about training subset of the existing dataset

### ISSUE THREAD

**Issue by backkon** [open-mmlab/mmdetection#2988]
I want to train subset of the existing dataset, I add only one class in the data dict, when I eval the result, it raise such error:

`Traceback (most recent call last):
  File "/home/backkon/mmdetection/tools/test.py", line 149, in <module>
    main()
  File "/home/backkon/mmdetection/tools/test.py", line 145, in main
    dataset.evaluate(outputs, args.eval, **kwargs)
  File "/home/backkon/mmdetection/mmdet/datasets/coco.py", line 363, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/backkon/mmdetection/mmdet/datasets/coco.py", line 324, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/backkon/mmdetection/mmdet/datasets/coco.py", line 257, in results2json
    json_results = self._det2json(results)
  File "/home/backkon/mmdetection/mmdet/datasets/coco.py", line 195, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

Process finished with exit code 1
`
I found that self.cat_ids only correspond  to the subset, but inference result may be all classes, so how to solve it?

**Comment by backkon** [comment]
i solved it by setting the score_thr to 0.05, thank you!
