### ISSUE TITLE
training error on mmDetection v2

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#2990]
Hi, there,

I installed mmDetection v2 through docker installation last night. I did a try today and saw an error on training. Could you help to take a look and give me some feedback.

Thanks!

Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 136, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/mmdetection/mmdet/datasets/custom.py", line 90, in __init__
    self.pipeline = Compose(pipeline)
  File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
**TypeError: __init__() got an unexpected keyword argument 'std'**
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 136, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/mmdetection/mmdet/datasets/custom.py", line 90, in __init__
    self.pipeline = Compose(pipeline)
  File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
**TypeError: __init__() got an unexpected keyword argument 'std'**
index created!
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 136, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/mmdetection/mmdet/datasets/custom.py", line 90, in __init__
    self.pipeline = Compose(pipeline)
  File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'std'
Traceback (most recent call last):
  File "./tools/train.py", line 161, in <module>
    main()
  File "./tools/train.py", line 136, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/mmdetection/mmdet/datasets/custom.py", line 90, in __init__
    self.pipeline = Compose(pipeline)
  File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 16, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'std'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/faster_rcnn/faster_rcnn_r50_fpn_giou_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by hellock** [comment]
Please follow the `Error report` issue template.

**Comment by shanggdlk** [comment]
Sorry for that, will do.

**Comment by jiameixia1202** [comment]
I also encountered this problem, how did you modify it？
