### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'std' on mmDetection v2

### ISSUE THREAD

**Issue by shanggdlk** [open-mmlab/mmdetection#3000]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.

**Describe the bug**
I installed mmDetection v2 using docker on June 10th. Here's the error when I kick off the training.
Traceback (most recent call last):
File "./tools/train.py", line 161, in
main()
File "./tools/train.py", line 136, in main
datasets = [build_dataset(cfg.data.train)]
File "/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
dataset = build_from_cfg(cfg, DATASETS, default_args)
File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
return obj_cls(**args)
File "/mmdetection/mmdet/datasets/custom.py", line 90, in init
self.pipeline = Compose(pipeline)
File "/mmdetection/mmdet/datasets/pipelines/compose.py", line 16, in init
transform = build_from_cfg(transform, PIPELINES)
File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
return obj_cls(**args)
TypeError: init() got an unexpected keyword argument 'std'

**Reproduction**
1. What command or script did you run?
standard training command.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I trained on my own dataset and tuned the training policies (# of epochs, learning rate etc.)

3. What dataset did you use?

My own dataset.

**Comment by hellock** [comment]
You may paste your config in the description.
