### ISSUE TITLE
ImportError: cannot import name 'nms_cpu' from 'mmdet.ops.nms'

### ISSUE THREAD

**Issue by tricoffee** [open-mmlab/mmdetection#3001]
ImportError: cannot import name 'nms_cpu' from 'mmdet.ops.nms'

**Comment by tricoffee** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/code/DetectoRS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/code/DetectoRS/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/code/DetectoRS/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/code/DetectoRS/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/code/DetectoRS/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/code/DetectoRS/mmdet/ops/__init__.py", line 12, in <module>
    from .nms import nms, soft_nms
  File "/code/DetectoRS/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/code/DetectoRS/mmdet/ops/nms/nms_wrapper.py", line 6, in <module>
    from . import nms_cpu
ImportError: cannot import name 'nms_cpu' from 'mmdet.ops.nms' (/code/DetectoRS/mmdet/ops/nms/__init__.py)

**Comment by hellock** [comment]
Did you install it correctly?

**Comment by tricoffee** [comment]
My computer does not have GPU. I have blocked CUDA code. Maybe my environment is not consistent with the requirements of this repository.

**Comment by hellock** [comment]
The latest code can be built without GPUs. Maybe you were not using the latest one.
