### ISSUE TITLE
ImportError: cannot import name 'LOSSES'

### ISSUE THREAD

**Issue by Harzva** [open-mmlab/mmdetection#3002]
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/root/data/gvision/mmdetection-master/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/root/data/gvision/mmdetection-master/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.models import build_detector
  File "/root/data/gvision/mmdetection-master/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/root/data/gvision/mmdetection-master/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .hrnet import HRNet
  File "/root/data/gvision/mmdetection-master/mmdet/models/backbones/hrnet.py", line 8, in <module>
    from ..builder import BACKBONES
  File "/root/data/gvision/mmdetection-master/mmdet/models/builder.py", line 3, in <module>
    from .losses import BoundedIoULoss,GIoULoss,IoULoss
  File "/root/data/gvision/mmdetection-master/mmdet/models/losses/__init__.py", line 2, in <module>
    from .balanced_l1_loss import BalancedL1Loss, balanced_l1_loss
  File "/root/data/gvision/mmdetection-master/mmdet/models/losses/balanced_l1_loss.py", line 5, in <module>
    from ..builder import LOSSES
ImportError: cannot import name 'LOSSES'

**Comment by ZwwWayne** [comment]
Please use the `error template`.
