### ISSUE TITLE
TypeError: Caught TypeError in DataLoader worker process 0.  TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by socialmen** [open-mmlab/mmdetection#3004]
loading annotations into memory...
Done (t=1.34s)
creating index...
index created!
Traceback (most recent call last):
File "/kaggle/working/mmdetection/tools/train.py", line 142, in
main()
File "/kaggle/working/mmdetection/tools/train.py", line 138, in main
meta=meta)
File "/kaggle/working/mmdetection/mmdet/apis/train.py", line 111, in train_detector
meta=meta)
File "/kaggle/working/mmdetection/mmdet/apis/train.py", line 242, in _non_dist_train
runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 383, in run
epoch_runner(data_loaders[i], **kwargs)
File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/runner.py", line 278, in train
for i, data_batch in enumerate(data_loader):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in next
data = self._next_data()
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
return self._process_data(data)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
data.reraise()
File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
data = fetcher.fetch(index)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/kaggle/working/mmdetection/mmdet/datasets/custom.py", line 132, in getitem
data = self.prepare_train_img(idx)
File "/kaggle/working/mmdetection/mmdet/datasets/custom.py", line 145, in prepare_train_img
return self.pipeline(results)
File "/kaggle/working/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in call
data = t(data)
File "/kaggle/working/mmdetection/mmdet/datasets/pipelines/loading.py", line 149, in call
results = self._load_semantic_seg(results)
File "/kaggle/working/mmdetection/mmdet/datasets/pipelines/loading.py", line 134, in _load_semantic_seg
osp.join(results['seg_prefix'], results['ann_info']['seg_map']),
File "/opt/conda/lib/python3.7/posixpath.py", line 80, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
```
A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZwwWayne** [comment]
According to
```
osp.join(results['seg_prefix'], results['ann_info']['seg_map']),
File "/opt/conda/lib/python3.7/posixpath.py", line 80, in join
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This should because either`results['seg_prefix']` or `results['ann_info']['seg_map']` is None.

**Comment by socialmen** [comment]
@ZwwWayne  Thank you!  I think modify the custom.py may work. Now only one error I have to solve.
![image](https://user-images.githubusercontent.com/38718224/84563875-4a803200-ad91-11ea-8d8c-42a6b3374ec1.png)
