### ISSUE TITLE
Bottle2neck' object has no attribute 'conv2'

### ISSUE THREAD

**Issue by cdzhu** [open-mmlab/mmdetection#3007]
when I choose Res2Net as backbone,and add dcn ,some errors happened.
config.py:
`_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py', '../_base_/datasets/voc0712.py',
    '../_base_/default_runtime.py'
]
model = dict(
    pretrained='open-mmlab://res2net101_v1d_26w_4s',
    backbone=dict(type='Res2Net',depth=101, scales=4, base_width=26,dcn=dict(type='DCN', deformable_groups=1, fallback_on_stride=False),
                 stage_with_dcn=(False, True, True, True)))`
with the config.py,I train successfully,but when test,errors happened.
`Traceback (most recent call last):
  File "/home/cpms/mmdetection/test.py", line 153, in <module>
    main()
  File "/home/cpms/mmdetection/test.py", line 110, in main
    model = build_detector(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
  File "/home/cpms/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/cpms/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/cpms/.conda/envs/mmlab/lib/python3.7/site-packages/mmcv-0.5.9-py3.7-linux-x86_64.egg/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/home/cpms/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 23, in __init__
    pretrained=pretrained)
  File "/home/cpms/mmdetection/mmdet/models/detectors/two_stage.py", line 49, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/cpms/mmdetection/mmdet/models/detectors/two_stage.py", line 61, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/cpms/mmdetection/mmdet/models/backbones/resnet.py", line 592, in init_weights
    m.conv2, 'conv_offset'):
  File "/home/cpms/.conda/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'Bottle2neck' object has no attribute 'conv2'`
thanks very much for fixing the error.

**Comment by xvjiarui** [comment]
Hi @cdzhu 
DCN is not supported in Res2Net as stated [here](https://github.com/open-mmlab/mmdetection/pull/2237#issuecomment-634026279).

**Comment by cdzhu** [comment]
What a pity....Thanks very much @xvjiarui

**Comment by minan19605** [comment]
I have the same issue when I add DCN for res2net.  Now I can test normally after I comment out the below code in init_weights() of resnet.py.  My question is: why when I train the model, it doesn't have this issue?

            if self.dcn is not None:
                for m in self.modules():
                    if isinstance(m, Bottleneck) and hasattr(
                            m.conv2, 'conv_offset'):
                        constant_init(m.conv2.conv_offset, 0)
