### ISSUE TITLE
grad_clip error

### ISSUE THREAD

**Issue by mao-jy** [open-mmlab/mmdetection#3044]
After I added `optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))` to schedule_1x.py, the following error occurs:
`Traceback (most recent call last):
  File "train.py", line 162, in <module>
    main()
  File "train.py", line 158, in main
    meta=meta)
  File "/usr/local/lib/python3.6/dist-packages/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 123, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 44, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 241, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/logger/base.py", line 45, in after_train_iter
    self.log(runner)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/logger/text.py", line 140, in log
    self._dump_log(log_dict, runner)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/hooks/logger/text.py", line 107, in _dump_log
    mmcv.dump(json_log, f, file_format='json')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/fileio/io.py", line 82, in dump
    handler.dump_to_fileobj(obj, file, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/fileio/handlers/json_handler.py", line 13, in dump_to_fileobj
    json.dump(obj, file, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Tensor' is not JSON serializable`

Before I added this 'grad_clip' config, the code can run normally. Can you help me fix this bug?

**Comment by Johnson-Wang** [comment]
I guess your reported error appears in pytorch1.4 or pytorch1.5. We are fixing this bug, please refer to [ this PR](https://github.com/open-mmlab/mmcv/pull/349)

**Comment by mao-jy** [comment]
> I guess your reported error appears in pytorch1.4 or pytorch1.5. We are fixing this bug, please refer to [ this PR](https://github.com/open-mmlab/mmcv/pull/349)

It helps! Thank you so much!
