### ISSUE TITLE
Attempt to use 2 cudas for testing - binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and input b is on cuda:1

### ISSUE THREAD

**Issue by LuizBorgesALS** [open-mmlab/mmdetection#3046]
Hi.

I am trying to use two different CUDAs for my testing. I have the epoch files for both situations, but  one testing works fine and the other does not. 

My code looks like this:

def testImage(path, img, classes, documentType):
    for i, result in enumerate(inference_detector(gpuModels[documentType], imgs)):
        print('testing {} basename {}'.format(imgs[i],os.path.basename(imgs[i])))
        try:
            show_result(imgs[i], result, ['core'], out_file='work_dir/result_{}'.format(os.path.basename(imgs[i])))
            print('Succeeded')
        except:
            print('Failed')
        return(result)

Traceback (most recent call last):
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, i  n error_router
    return original_handler(e)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in   wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exc  eption
    reraise(exc_type, exc_value, tb)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispa  tch_request
    rv = self.handle_user_exception(e)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_restful/__init__.py", line 269, i  n error_router
    return original_handler(e)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in   wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_use  r_exception
    reraise(exc_type, exc_value, tb)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispa  tch_request
    rv = self.dispatch_request()
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_r  equest
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, i  n wrapper
    resp = resource(*args, **kwargs)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, i  n dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/luiz/lhb/training/webAPI.py", line 118, in post
    result = testImage('work_dir/', fileName, model.CLASSES, documentType)
  File "/home/luiz/lhb/training/webAPI.py", line 266, in testImage
    for i, result in enumerate(inference_detector(gpuModels[documentType], imgs)):
  File "/home/skeptomist/mmdetection/mmdet/apis/inference.py", line 99, in _inference_generator
    yield _inference_single(model, img, img_transform, device)
  File "/home/skeptomist/mmdetection/mmdet/apis/inference.py", line 93, in _inference_single
    result = model(return_loss=False, rescale=True, **data)
  File "/home/skeptomist/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493,   in __call__
    result = self.forward(*input, **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/base.py", line 78, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/two_stage.py", line 199, in simple_test
    x, img_meta, self.test_cfg.rpn) if proposals is None else proposals
  File "/home/skeptomist/mmdetection/mmdet/models/detectors/test_mixins.py", line 10, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/skeptomist/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 218, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/skeptomist/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 83, in get_bboxes_single
    self.target_stds, img_shape)
  File "/home/skeptomist/mmdetection/mmdet/core/bbox/transforms.py", line 54, in delta2bbox
    gw = pw * dw.exp()
RuntimeError: binary_op(): expected both inputs to be on same device, but input a is on cuda:0 and input b is on cuda:1

**Comment by yhcao6** [comment]
Could you show me the complete python script and the running command? It is hard to find where the problem is by the given information.
