### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file

### ISSUE THREAD

**Issue by CatbossMr** [open-mmlab/mmdetection#3081]
Hello Sir, recently I updated the mmdetection version to 2.1, I followed the technological process to install it. However, while I start the train.py, I met the following problem:

```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/home/user/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/user/detection/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/user/detection/mmdetection/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/user/detection/mmdetection/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/user/detection/mmdetection/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/user/detection/mmdetection/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/user/detection/mmdetection/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmdet.ops import nms_match
  File "/home/user/detection/mmdetection/mmdet/ops/__init__.py", line 3, in <module>
    from .corner_pool import CornerPool
  File "/home/user/detection/mmdetection/mmdet/ops/corner_pool/__init__.py", line 1, in <module>
    from .corner_pool import CornerPool
  File "/home/user/detection/mmdetection/mmdet/ops/corner_pool/corner_pool.py", line 4, in <module>
    from . import corner_pool_ext
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

```

My CUDA Driver Version = 10.2, CUDA Runtime Version = 10.2, NumDevs = 8, deviceQuery Result is Pass, gcc version = 7.4.0, Nvidia driver = 440.36, mmdetection version =2.1.0,Ubuntu version = 18.04

I have tried deleting `build` and running `sudo python setup.py develop` for many times,but it seems didn't work.  Can you please tell me what's wrong with it and how to fix it properly? I have been perplexed by this problem for several days and really don't know how to deal with it ......

Thanks a lot!!

**Comment by CatbossMr** [comment]
So strange! when I run `train.py` in my conda environment I will meet the problem, when I changed my environment to base and rerun `train.py`, it just worked!!!!!

If someone knows why , please tell me! Thank you so much !

**Comment by weipingmao** [comment]
i meet this prpblem too,have you solveed it?

**Comment by wcw1998** [comment]
i meet this prpblem too,have you solveed it?

**Comment by Coronal-Halo** [comment]
I face the same problem too, have you solved it?
