### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3089]
I have installed mmdetection as per the instructions, ensuring the PyTorch version is inline with the CUDA requirements but I still get a CUDA error when running analysis. I would very much appreciate any guidance.

Many thanks in advance.

**Reproduction**
1. What command or script did you run?
```
tools/train.py train_baseline_config.py
```

**Environment**

```
sys.platform: linux
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
CUDA available: True
CUDA_HOME: /vol/cuda/10.0.130-cudnn7.6.4.38
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1: Tesla T4
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.4.0+cu100
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0+cu100
OpenCV: 4.2.0
MMCV: 0.6.1
MMDetection: 2.1.0+bf9638a
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.0
```

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 161, in <module>
    main()
  File "mmdetection/tools/train.py", line 157, in main
    meta=meta)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/vol/bitbucket/shp2918/_venv/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/vol/bitbucket/shp2918/_venv/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 35, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/apis/train.py", line 74, in batch_processor
    losses = model(**data)
  File "/vol/bitbucket/shp2918/_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/bitbucket/shp2918/_venv/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/vol/bitbucket/shp2918/_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/models/detectors/base.py", line 148, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/models/detectors/two_stage.py", line 149, in forward_train
    proposal_cfg=proposal_cfg)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 37, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 496, in get_bboxes
    scale_factor, cfg, rescale)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 120, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 154, in batched_nms
    torch.cat([bboxes_for_nms, scores[:, None]], -1), **nms_cfg_)
  File "/vol/bitbucket/shp2918/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 53, in nms
    inds = nms_ext.nms(dets_th, iou_thr)
RuntimeError: CUDA error: no kernel image is available for execution on the device (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:103)
```

**Comment by hellock** [comment]
Did you build mmdetection on the same server?

**Comment by sehyungp92** [comment]
I'm not sure if I've 100% understood the question properly but yes, I cloned the git repo, set CUDA_HOME, made sure that torch.cuda.is_available() returned true and installed mmdetection using python setup.py develop.

**Comment by ashwinvaswani** [comment]
@hellock  @sehyungp92 Even I am facing the same error. How did you manage to fix it? 
The output of collect_env.py is as follows:
`sys.platform: linux
Python: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: Tesla V100-SXM2-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.6.1
MMDetection: 2.1.0+264fdf6
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1
`

**Comment by sehyungp92** [comment]
I believe PyTorch needs to be built with GCC 7.5

**Comment by ashwinvaswani** [comment]
@sehyungp92 I'm actually running the default pytorch_p36 env from AWS, how do I fix this issue?

**Comment by sehyungp92** [comment]
I'm not sure unfortunately. Maybe set TORCH_CUDA_ARCH_LIST to include the required compute capability?

**Comment by ashwinvaswani** [comment]
I'm sorry I did not exactly understand. What would I set TORCH_CUDA_ARCH_LIST to? I'm currently running on Tesla V100.
Also, do you mean building mmdetection again with the following code or am I missing something?
```TORCH_CUDA_ARCH_LIST = "XYZ" python setup.py develop```

**Comment by Richie-yan** [comment]
Hi @ashwinvaswani @sehyungp92 I also encountered the same problem: CUDA error: no kernel image is available for execution on the device
My environment is as follows:
```
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: Tesla V100-PCIE-32GB
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
PyTorch: 1.5.0a0+4ff3872
PyTorch compiling details: PyTorch built with:
  - GCC 5.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201307 (a.k.a. OpenMP 4.0)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_70,code=compute_70
  - CuDNN 7.6.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 4.4.0
MMCV: 1.0.5
MMDetection: 2.3.0+b97322e
MMDetection Compiler: GCC 5.3
MMDetection CUDA Compiler: 10.0
```
How can I solve this problem?

**Comment by ashwinvaswani** [comment]
@Richie-yan In my case, the error was due to Pytorch being built on a different version of cuda than the standard one installed on my machine. For some reason I had both cuda 10 and 10.1 installed on my machine and Pytorch was installed with cuda 10.1 but cuda 10 was being used by default. Hope it helps!

**Comment by onepiece010938** [comment]
@ashwinvaswani Hi , I had both cuda 10.1 and 11.1 installed on my machine, how to check which cuda version that Pytorch was used by default? and how to change it?
