### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zhangyu96** [open-mmlab/mmdetection#3113]
I use my own dataset to train, when the first epoch finished, i got the error as follows:
: 0.0005, loss_rpn_bbox: 0.0036, loss_cls: 0.0183, acc: 99.2578, loss_bbox: 0.0498, loss: 0.0723
2020-06-24 00:20:53,044 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 158/158, 9.1 task/s, elapsed: 17s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/d1999/ZY/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/d1999/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/d1999/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
    self.call_hook('after_train_epoch')
  File "/home/d1999/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/d1999/ZY/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 28, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/d1999/ZY/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/d1999/ZY/mmdetection/mmdet/datasets/voc.py", line 47, in evaluate
    logger=logger)
  File "/home/d1999/ZY/mmdetection/mmdet/core/evaluation/mean_ap.py", line 388, in eval_map
    mean_ap, eval_results, dataset, area_ranges, logger=logger)
  File "/home/d1999/ZY/mmdetection/mmdet/core/evaluation/mean_ap.py", line 451, in print_map_summary
    label_names[j], num_gts[i, j], results[j]['num_dets'],
IndexError: list index out of range
Is there an solutions? thanks!

**Comment by azibit** [comment]
How many classes are you using in your dataset?

**Comment by zhangyu96** [comment]
3，do not include background



---Original---

**Comment by fengqian-wei** [comment]
check the config  neck setting :class num

**Comment by zxs123boss** [comment]
this codelab is weird

**Comment by zhaoyang97** [comment]
我也碰到这个问题了，你最后是怎么解决的呢？

**Comment by fengqian-wei** [comment]
你核对下config的neck classnum属性

**Comment by fengqian-wei** [comment]
> 我也碰到这个问题了，你最后是怎么解决的呢？

你核对下config的neck classnum属性

**Comment by zhaoyang97** [comment]
> > 我也碰到这个问题了，你最后是怎么解决的呢？
> 
> 你核对下config的neck classnum属性

好的谢谢！（回复的好快哈哈哈哈

**Comment by sunnyisabaster** [comment]
> > > 我也碰到这个问题了，你最后是怎么解决的呢？
> > 
> > 
> > 你核对下config的neck classnum属性
> 
> 好的谢谢！（回复的好快哈哈哈哈

请问你解决了吗？我改了num classes依然还有这个错误。

**Comment by NiuCY** [comment]
我使用的配置文件是"configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py",该文件中的第五行model = dict(roi_head=dict(bbox_head=dict(num_classes=20))),num_classes这块也要同步改成class的个数.

**Comment by casiahnu** [comment]
> > > > 我也碰到这个问题了，你最后是怎么解决的呢？
> > > 
> > > 
> > > 你核对下config的neck classnum属性
> > 
> > 
> > 好的谢谢！（回复的好快哈哈哈哈
> 
> 请问你解决了吗？我改了num classes依然还有这个错误。

请问您解决了么？我修改好了num_classes，但是仍然报错，我的联系方式是18810220665（电话，微信）
