### ISSUE TITLE
I got unexpected keyword argument 'anchor_scales'

### ISSUE THREAD

**Issue by AlexSG18** [open-mmlab/mmdetection#3150]
<class 'mmdet.models.detectors.faster_rcnn.FasterRCNN'>
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 126, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/alex/mmdetection/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/alex/mmdetection/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/alex/mmdetection/mmcv/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/alex/mmdetection/mmdet/models/detectors/faster_rcnn.py", line 24, in __init__
    pretrained=pretrained)
  File "/home/alex/mmdetection/mmdet/models/detectors/two_stage.py", line 35, in __init__
    self.rpn_head = build_head(rpn_head_)
  File "/home/alex/mmdetection/mmdet/models/builder.py", line 57, in build_head
    return build(cfg, HEADS)
  File "/home/alex/mmdetection/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/alex/mmdetection/mmcv/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/alex/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 22, in __init__
    1, in_channels, background_label=0, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'anchor_scales'

When I run below code

python tools/train.py configs/faster_rcnn_r50_fpn_1x_psylla.py
I get the error, I have upgraded to version 2.1 and tried to change the config 
Any suggestion on how to solve this issue?

**Comment by yhcao6** [comment]
I guess you pass `anchor_scales=xxx` in the `rpn_head` of your config but `RPN head` doesn't have that parameter.
Could you show me your config?

**Comment by AlexSG18** [comment]
here is my config
[config.txt](https://github.com/open-mmlab/mmdetection/files/4850070/config.txt)

**Comment by AlexSG18** [comment]
updated config to the compatible with mmdetection v2.0.0
