### ISSUE TITLE
an issue of val after a epoch.    "scale and scale_factor cannot be both set.") AssertionError: scale and scale_factor cannot be both set.

### ISSUE THREAD

**Issue by tianyuluan** [open-mmlab/mmdetection#3159]
__my command is :__

python tools/test.py configs/cascade_rcnn/cascade_rcnn_r101_fpn_1x_coco.py work_dirs/cascade_rcnn_r101_fpn_1x_coco/latest.pth --out=work_dirs/result.pkl

and the info is:

/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
[                                                  ] 0/1081, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 149, in <module>
    main()
  File "tools/test.py", line 127, in main
    args.show_score_thr)
  File "/home/lty/mmdetection/mmdet/apis/test.py", line 24, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lty/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lty/mmdetection/mmdet/datasets/custom.py", line 185, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/lty/mmdetection/mmdet/datasets/custom.py", line 228, in prepare_test_img
    return self.pipeline(results)
  File "/home/lty/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/lty/mmdetection/mmdet/datasets/pipelines/test_time_aug.py", line 103, in __call__
    data = self.transforms(_results)
  File "/home/lty/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/lty/mmdetection/mmdet/datasets/pipelines/transforms.py", line 262, in __call__
    "scale and scale_factor cannot be both set.")
### **AssertionError: scale and scale_factor cannot be both set.**

can you give me some suggests? thanks !

**Comment by Daniil-Osokin** [comment]
Hi! Looks like something in `master` is not consistent. In the meantime you can checkout and use the latest tag `v.2.1.0`.

**Comment by hellock** [comment]
Thanks for the bug report! It has been fixed in #3162.

**Comment by hust-nj** [comment]
Hello, the same bug again, it seems your fix has been dropped!

> Thanks for the bug report! It has been fixed in #3162.
