### ISSUE TITLE
fovea_align_gn_ms_r50_fpn_4gpu_2x: RuntimeError: view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by QuantScientist** [open-mmlab/mmdetection#3182]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When training fovea (fovea_r50_fpn_4gpu_1x.py) everything works fine, however, the fovea_align_gn_ms_r50_fpn_4gpu_2x configuration results in this error.

**Reproduction**
1. What command or script did you run?
```
./tools/dist_train.sh configs/foveabox/fovea_align_gn_ms_r50_fpn_4gpu_2x.py  1 --validate
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
A COCO compatible data set. 
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

```
sys.platform: linux
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1,2,3: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0a0+8f84ded
PyTorch compiling details: PyTorch built with:
  - GCC 7.4
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.1 Product Build 20180928 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash N/A)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_75,code=compute_75
  - CuDNN 7.6.5
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0
OpenCV: 4.2.0
MMCV: 0.2.16
MMDetection: 1.0.0+d5398a0
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2
```

**Error traceback**

```
loading annotations into memory...
Done (t=1.28s)
creating index...
index created!
loading annotations into memory...
Done (t=0.15s)
creating index...
index created!
2020-07-02 08:46:44,269 - mmdet - INFO - Start running, host: root@b4b9095d2803, work_dir: /root/sharedfolder/production/DeepOncology/DeepOncologyDET/SOLO/work_dirs/fovea_align_gn_ms_r50_fpn_4gpu_2x
2020-07-02 08:46:44,269 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 125, in <module>
    main()
  File "./tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/root/sharedfolder/production/DeepOncology/DeepOncologyDET/SOLO/mmdet/apis/train.py", line 103, in train_detector
    timestamp=timestamp)
  File "/root/sharedfolder/production/DeepOncology/DeepOncologyDET/SOLO/mmdet/apis/train.py", line 250, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 275, in train
    self.call_hook('after_train_iter')
  File "/opt/conda/lib/python3.6/site-packages/mmcv/runner/runner.py", line 231, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/sharedfolder/production/DeepOncology/DeepOncologyDET/SOLO/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/foveabox/fovea_align_gn_ms_r50_fpn_4gpu_2x.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
root@b4b9095d2803:~/sharedfolder/production/DeepOncology/DeepOncologyDET/SOLO# cd ~

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
The command suggests you are using mmdetection of an old version. Could you try the latest one? I can't reproduce your error with the latest version.
