### ISSUE TITLE
Training Error on Google Colab

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#3190]
I am using google colab to train model for table structure recognition. When I execute the command 
`!python tools/train.py {config_fname}`
I got the the following error-

`Traceback (most recent call last):
  File "tools/train.py", line 14, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.2.0+0f33c08-py3.6-linux-x86_64.egg/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.2.0+0f33c08-py3.6-linux-x86_64.egg/mmdet/apis/inference.py", line 13, in <module>
    from mmdet.models import build_detector
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.2.0+0f33c08-py3.6-linux-x86_64.egg/mmdet/models/__init__.py", line 3, in <module>
    from .bbox_heads import *  # noqa: F401,F403
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.2.0+0f33c08-py3.6-linux-x86_64.egg/mmdet/models/bbox_heads/__init__.py", line 3, in <module>
    from .double_bbox_head import DoubleConvFCBBoxHead
  File "/usr/local/lib/python3.6/dist-packages/mmdet-1.2.0+0f33c08-py3.6-linux-x86_64.egg/mmdet/models/bbox_heads/double_bbox_head.py", line 2, in <module>
    from mmcv.cnn.weight_init import normal_init, xavier_init
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'`

I am using **cascade_mask_rcnn_hrnetv2p_w32_20e.py** to train my model and following this link [https://github.com/Tony607/mmdetection_object_detection_demo/blob/master/mmdetection_train_custom_coco_data.ipynb](url)

Can you help me out on this?

**Comment by cpboost** [comment]
i use colab to train cascade_rcnn , successly

**Comment by Atul997** [comment]
> i use colab to train cascade_rcnn , successly

I was also able to run it successfully 2 weeks ago but this time when I am runnning it after changing data files it is not working.

**Comment by njustczr** [comment]
> > i use colab to train cascade_rcnn , successly
> 
> I was also able to run it successfully 2 weeks ago but this time when I am runnning it after changing data files it is not working.

maybe mmcv has updated

**Comment by njustczr** [comment]
> > > i use colab to train cascade_rcnn , successly
> > 
> > 
> > I was also able to run it successfully 2 weeks ago but this time when I am runnning it after changing data files it is not working.
> 
> maybe mmcv has updated

you can pip install mmcv==0.4.3

**Comment by Atul997** [comment]
Thanks. It worked :)

**Comment by yustaub** [comment]
> > > > i use colab to train cascade_rcnn , successly
> > > 
> > > 
> > > I was also able to run it successfully 2 weeks ago but this time when I am runnning it after changing data files it is not working.
> > 
> > 
> > maybe mmcv has updated
> 
> you can pip install mmcv==0.4.3

thks, your answer help me a lot!!!
