### ISSUE TITLE
THE use of robustness_eval.py

### ISSUE THREAD

**Issue by HXH-resonance** [open-mmlab/mmdetection#3256]
when I want to eval  FSAF,a mistake is 
`(open-mmlab-3) xyl@xyl-System-Product-Name:~/mmdetection$ python tools/robustness_eval.py /home/xyl/mmdetection/result/result_100.pkl --dataset coco --metric AP
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "tools/robustness_eval.py", line 250, in <module>
    main()
  File "tools/robustness_eval.py", line 246, in main
    aggregate=args.aggregate)
  File "tools/robustness_eval.py", line 169, in get_results
    aggregate=aggregate)
  File "tools/robustness_eval.py", line 67, in get_coco_style_results
    num_distortions = len(list(eval_output.keys()))
AttributeError: 'list' object has no attribute 'keys'
`

**Comment by ZwwWayne** [comment]
Please use the `Error Template`, or at least provide a way to fully reproduce the bug.
