### ISSUE TITLE
ImportError: cannot import name 'build_from_cfg' from 'mmdet.utils'

### ISSUE THREAD

**Issue by ShidiDaisy** [open-mmlab/mmdetection#3284]
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/ubuntu/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/ubuntu/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.models import build_detector
  File "/home/ubuntu/mmdetection/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/ubuntu/mmdetection/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .detectors_resnet import DetectoRS_ResNet
  File "/home/ubuntu/mmdetection/mmdet/models/backbones/detectors_resnet.py", line 5, in <module>
    from ..builder import BACKBONES
  File "/home/ubuntu/mmdetection/mmdet/models/builder.py", line 3, in <module>
    from mmdet.utils import build_from_cfg
ImportError: cannot import name 'build_from_cfg' from 'mmdet.utils' (/home/ubuntu/mmdetection/mmdet/utils/__init__.py)

I'm using 
PyTorch 1,5, 
TorchVision: 0.6.0a0+35d732a,
Python 3.7, 
CUDA 10.2
OpenCV: 4.2.0
MMCV: 1.0.2
mmdet==2.2.0+bcda9d2
MMDetection Compiler: GCC 7.3

anyone could help me with this issue?

**Comment by ZwwWayne** [comment]
Hi @ShidiDaisy ,
It is weird, mmdet has been removed the API of `build_from_cfg` for a while. You can either update you code or fix this bug by changing `from mmdet.utils import build_from_cfg` to `from mmcv.utils import build_from_cfg`.

**Comment by maxiuw** [comment]
I think (not 100% sure) that now with switch to `mmengine` you should use 'from mmengine.registry import build_from_cfg'
or directily build using object from the registy e.g. 

```
from mmengine.registry import MODELS
cfg = Config.fromfile(args.config)
resnet = MODELS.build(cfg)
```

**Comment by ParisaHTM** [comment]
This works for me:
`from mmcv.utils.registry import build_from_cfg`
