### ISSUE TITLE
ValueError: Target size (torch.Size([0, 28, 28])) must be the same as... when use maskrcnn

### ISSUE THREAD

**Issue by zhaogev5** [open-mmlab/mmdetection#3304]
when i use the latest mmdetection,there are error when I use mask-rcnn and other models that contain mask-rcnn,the Value error as that:
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/ymhj/lyz/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ymhj/lyz/mmdetection/mmdet/models/detectors/base.py", line 236, in train_step
    losses = self(**data)
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 271, in forward_train
    bbox_results['bbox_feats'])
  File "/home/ymhj/lyz/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 198, in _mask_forward_train
    mask_targets, pos_labels)
  File "/home/ymhj/lyz/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 147, in loss
    loss_mask = self.loss_mask(mask_pred, mask_targets, labels)
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/losses/cross_entropy_loss.py", line 199, in forward
    **kwargs)
  File "/home/ymhj/lyz/mmdetection/mmdet/models/losses/cross_entropy_loss.py", line 125, in mask_cross_entropy
    pred_slice, target, weight=class_weight, reduction='mean')[None]
  File "/home/ymhj/anaconda3/envs/lyz/lib/python3.7/site-packages/torch/nn/functional.py", line 2112, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([0, 28, 28])) must be the same as input size (torch.Size([34, 28, 28]))
since the other models like cascade-rcnn and faster-rcnn don't have this question.

**Comment by ZwwWayne** [comment]
It seems that your mask prediction has a different shape from the mask target. For now, we have no information about why it happens. So please use the `error template`.
