### ISSUE TITLE
Test a pre-trained model on a single, custom image

### ISSUE THREAD

**Issue by starkgate** [open-mmlab/mmdetection#3310]
I want to test the pre-trained model of DetectoRS on a single, custom image. I read the doc on how to [create a new dataset](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html), however I'm having trouble reproducing the instructions.

I've modified the required config files to point to the new dataset, and I think it's set up properly:
![Screenshot_2020-07-14_16-47-24](https://user-images.githubusercontent.com/12874678/87440233-0bdcd200-c5f2-11ea-9cb5-ba8fd9d097ea.png)

Here's the error log I get when I run the test:
```
PYTHONPATH=${PWD}:$PYTHONPATH python tools/test.py configs/detectors/test.py checkpoints/detectors_htc_r50_1x_coco-329b1453.pth --show
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 105, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/u42/Documents/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/u42/Documents/anaconda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/u42/Documents/mmdetection/mmdet/datasets/voc.py", line 15, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/u42/Documents/mmdetection/mmdet/datasets/xml_style.py", line 23, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/u42/Documents/mmdetection/mmdet/datasets/custom.py", line 82, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/u42/Documents/mmdetection/mmdet/datasets/xml_style.py", line 43, in load_annotations
    tree = ET.parse(xml_path)
  File "/home/u42/Documents/anaconda/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/home/u42/Documents/anaconda/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Annotations/21491hr.xml'
```

The dataset file:
```
# dataset settings
dataset_type = 'VOCDataset'
data_root = 'data/test/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1000, 600),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'ImageSets/trainval.txt'
            ],
            img_prefix=[data_root],
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/test.txt',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/test.txt',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='mAP')
```

**Comment by starkgate** [comment]
(kinda) fixed it by adding the full path to the annotation as img_prefix. I'm still curious if there's a better way to do this. I also had to comment out an exception that was raised in voc.py:VOCDataset (l. 21), because my dataset doesn't have a year in it's folder name.
```
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/test.txt',
        img_prefix='/home/u42/Documents/mmdetection/data/test/',
        pipeline=test_pipeline))
```

**Comment by xvjiarui** [comment]
Hi @starkgate 
The relative path should work too. 
As for the exception, you may create a new dataset instead of using VOC directly.
