### ISSUE TITLE
Adding VGG Backbone to MaskRCNN

### ISSUE THREAD

**Issue by azibit** [open-mmlab/mmdetection#3311]
Hi Everyone,

I am trying to compare different backbones for the MaskRCNN project I am working on and currently trying the VGG. I was wondering if anyone could work me through.

Steps I have completed so far.

1. Use the VGG class in the mmcv package as my base model. I just copied that class into my code
2. Annotated the VGG class and then updated the import.

Now, I have some issues with the Neck values. I would appreciate any help you can offer

**Comment by azibit** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/content/mmdetection/mmdet/models/detectors/base.py", line 236, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/content/mmdetection/mmdet/models/detectors/two_stage.py", line 142, in forward_train
    x = self.extract_feat(img)
  File "/content/mmdetection/mmdet/models/detectors/two_stage.py", line 84, in extract_feat
    x = self.neck(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/content/mmdetection/mmdet/models/necks/fpn.py", line 172, in forward
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/content/mmdetection/mmdet/models/necks/fpn.py", line 172, in <listcomp>
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/cnn/bricks/conv_module.py", line 185, in forward
    x = self.conv(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 353, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 350, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 256, 1, 1], expected input[2, 64, 544, 400] to have 256 channels, but got 64 channels instead

**Comment by azibit** [comment]
I would keep searching

**Comment by fangxu622** [comment]
hi~Do you solve it,.~~cloud you please provide the reference code. I have the same need.
