### ISSUE TITLE
AssertionError: Caught AssertionError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by lgldl** [open-mmlab/mmdetection#3312]
The error occyred when we train our own data with mmdetection. It shows that the dataload is wrong, I don't how to solve it, can you help me?  the error is as follows:

File "/home/lgl/PycharmProjects/DetectoRS/train_building.py", line 144, in <module>
    main()
  File "/home/lgl/PycharmProjects/DetectoRS/train_building.py", line 140, in main
    meta=meta)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/apis/train.py", line 242, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/custom.py", line 132, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/custom.py", line 145, in prepare_train_img
    return self.pipeline(results)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/pipelines/transforms.py", line 323, in __call__
    self._pad_masks(results)
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/pipelines/transforms.py", line 310, in _pad_masks
    for mask in results[key]
  File "/home/lgl/PycharmProjects/DetectoRS/mmdet/datasets/pipelines/transforms.py", line 310, in <listcomp>
    for mask in results[key]
  File "/home/lgl/anaconda3/envs/DetectoRS/lib/python3.6/site-packages/mmcv/image/geometric.py", line 332, in impad
    assert s >= img_s
AssertionError

**Comment by ZwwWayne** [comment]
It seems that the size to be pad is smaller than the mask's shape, you need to check your data or your code when loading the mask annotation.
