### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by 1786939789** [open-mmlab/mmdetection#3314]
run python tools/train.py

There are four gpus. Each gpu has 11G memory. At the beginning of training, the four gpus were evenly distributed. However, during the training process, some of the gpu memory were increasing slowly , and others were decreasing slowly. Finally, cuda out of memory will appear.

There are error details:
Traceback (most recent call last): 
  File "/usr0/home/zhiqic/anaconda3/envs/mmdetect/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker    
      output = module(*input, **kwargs)
  File "/usr0/home/zhiqic/anaconda3/envs/mmdetect/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__    
      result = self.forward(*input, **kwargs)  
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
      return old_func(*args, **kwargs)  
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/detectors/base.py", line 148, in forward    
      return self.forward_train(img, img_metas, **kwargs)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/detectors/two_stage.py", line 149, in forward_train
      proposal_cfg=proposal_cfg)  
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 33, in forward_train
      losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 50, in loss
      gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
      return old_func(*args, **kwargs)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 393, in loss
      label_channels=label_channels)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 320, in get_targets
      unmap_outputs=unmap_outputs)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/utils/misc.py", line 25, in multi_apply
      return tuple(map(list, zip(*map_results)))
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 197, in _get_targets_single
      None if self.sampling else gt_labels)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/bbox/assigners/max_iou_assigner.py", line 105, in assign
      overlaps = self.iou_calculator(gt_bboxes, bboxes)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 31, in __call__
      return bbox_overlaps(bboxes1, bboxes2, mode, is_aligned)
  File "/usr0/home/zhiqic/lihong/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 129, in bbox_overlaps
      union = area1[:, None] + area2 - overlap
RuntimeError: CUDA out of memory. Tried to allocate 548.00 MiB (GPU 0; 10.76 GiB total capacity; 9.14 GiB already allocated; 548.19 MiB free; 9.42 GiB reserved in total by PyTorch)

**Comment by sandy-0326** [comment]
I have the same question. Have you solved the problem yet?

**Comment by 1786939789** [comment]
> I have the same question. Have you solved the problem yet?

I guess that more than 100 bboxes per images in my own dataset cause cuda out of memory. So now I use resnet-50 instead of resnet-101 as backbone.

**Comment by sandy-0326** [comment]
> > I have the same question. Have you solved the problem yet?
> 
> I guess that more than 100 bboxes per images in my own dataset cause cuda out of memory. So now I use resnet-50 instead of resnet-101 as backbone.

Thank you.

**Comment by ZwwWayne** [comment]
If the number of GT is large in your dataset, please refer to the [doc](https://mmdetection.readthedocs.io/en/latest/api.html#mmdet.core.bbox.MaxIoUAssigner). There is an argument `gpu_assign_thr`, you can set the threshold thus the iou calculation will be conducted on CPU to save the GPU memory.

**Comment by 1786939789** [comment]
> If the number of GT is large in your dataset, please refer to the [doc](https://mmdetection.readthedocs.io/en/latest/api.html#mmdet.core.bbox.MaxIoUAssigner). There is an argument `gpu_assign_thr`, you can set the threshold thus the iou calculation will be conducted on CPU to save the GPU memory.

Thank you.

**Comment by zimenglan-sysu-512** [comment]
how to set this param for different dataset?
