### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

### ISSUE THREAD

**Issue by baibaidedongdong** [open-mmlab/mmdetection#3331]
**when i run     "'python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py \
    checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth \
     --show"**
it exits:　　　
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 105, in main
    dataset = build_dataset(cfg.data.test)
  File "/home/zhaotongdong/goole_download/mmdetection/mmdet/datasets/builder.py", line 63, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 167, in build_from_cfg
    return obj_cls(**args)
  File "/home/zhaotongdong/goole_download/mmdetection/mmdet/datasets/custom.py", line 82, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/zhaotongdong/goole_download/mmdetection/mmdet/datasets/coco.py", line 46, in load_annotations
    self.coco = COCO(ann_file)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0.1-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

**but in my root,it exits this file,why?thank you!**

**Comment by baibaidedongdong** [comment]
then I changed the souce code in "configs/_base_/datasets/coco_detection.py",changed the <data_root = 'data/coco/'>,making it is a absolute path,but it also appear the same problem,as below:`(open-mmlab) zhaotongdong@zhaotongdong-MS-7B89:~/goole_download/mmdetection$ python tools/test.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py  checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --eval mAP
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 204, in fromfile
    use_predefined_variables)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 115, in _file2dict
    check_file_exist(filename)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/zhaotongdong/goole_download/mmdetection/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py" does not exist
`

**Comment by baibaidedongdong** [comment]
then I changed the souce code in "configs/base/datasets/coco_detection.py",changed the <data_root = 'data/coco/'>,making it is a absolute path,but it also appear the same problem,as below:
`Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 204, in fromfile
    use_predefined_variables)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 115, in _file2dict
    check_file_exist(filename)
  File "/home/zhaotongdong/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/zhaotongdong/goole_download/mmdetection/configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py" does not exist
`

**Comment by ZwwWayne** [comment]
Can you show the output of `ls -l data/coco/annotations/instances_val2017.json` at the same directory as where you run `python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth --show`

**Comment by baibaidedongdong** [comment]
＠ZwwWayne　　omg,why it shows  "ls: 无法访问'data/coco/annotations/instances_val2017.json': 没有那个文件或目录"
