### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by darkness605** [open-mmlab/mmdetection#3347]
when I train my model with command "python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py"
 ,at beginning it shows the error message:

Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/ubuntu/qifan/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
<class 'mmdet.core.mask.structures.BitmapMasks'>
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/custom.py", line 187, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/custom.py", line 210, in prepare_train_img
    return self.pipeline(results)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 340, in __call__
    results = self._load_masks(results)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 291, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 291, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 247, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)

I want to know how to solve it ?

**Comment by ZwwWayne** [comment]
It seems that you use customized dataset for training. Please check the format of your instance mask. If it is no in polygon format, you do not need to convert the annotation from polygon to mask.

**Comment by darkness605** [comment]
> It seems that you use customized dataset for training. Please check the format of your instance mask. If it is no in polygon format, you do not need to convert the annotation from polygon to mask.
