### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by darkness605** [open-mmlab/mmdetection#3381]
**Describe the bug**
       when I used customized dataset to train my model with command
 "python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py", at beginning it shows the error message。
my mmdet version is 2.2.1. install follow the official tutorial , [https://github.com/open-mmlab/mmdetection/blob/v2.2.1/docs/install.md](here)

**Reproduction**
1. What command or script did you run?
```
"python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py"
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
i changed the classnum to 10(not contain BG) or 11(both of them worked) in mask_rcnn_r50_fpn.py, and also  changed the CLASSER in coco.py.
,the LoadAnnotations configs is shown in picture.
![image](https://user-images.githubusercontent.com/49859687/88182412-bc864980-cc62-11ea-93e7-c7311eafa9f2.png)
I try to change the "with_mask=False" from False to ture. but it isn't worked. 

3. What dataset did you use?
 mydata set is customized in coco format. As shown below.
```
{
  "info": {
    "description": null,
    "url": null,
    "version": null,
    "year": 2020,
    "contributor": null,
    "date_created": "2020-07-19 11:06:22.162591"
  },
  "licenses": [
    {
      "url": null,
      "id": 0,
      "name": null
    }
  ],
  "images": [
    {
      "license": 0,
      "url": null,
      "file_name": "BMPImages/0010.bmp",
      "height": 768,
      "width": 1024,
      "date_captured": null,
      "id": 0
    }
],
"type": "instances",
  "annotations": [
    {
      "id": 0,
      "image_id": 0,
      "category_id": 3,
      "segmentation": [
        [
          707.4285714285714,
          461.9047619047619,
          719.3333333333334,
          481.74603174603175
        ]
      ],
      "area": 273.0,
      "bbox": [
        707.0,
        461.0,
        13.0,
        21.0
      ],
      "iscrowd": 0
    }
],
 "categories": [
    {
      "supercategory": null,
      "id": 1,
      "name": "break"
    },
    ........
    {
      "supercategory": null,
      "id": 10,
      "name": "tornlab"
    }
  ]
}
```
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/ubuntu/qifan/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 801, in __next__
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/lqfmmdet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/custom.py", line 187, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/custom.py", line 210, in prepare_train_img
    return self.pipeline(results)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 339, in __call__
    results = self._load_masks(results)
  File "/home/ubuntu/qifan/mmdetection/mmdet/datasets/pipelines/loading.py", line 295, in _load_masks
    w)
  File "/home/ubuntu/qifan/mmdetection/mmdet/core/mask/structures.py", line 334, in __init__
    assert isinstance(masks[0][0], np.ndarray)
IndexError: list index out of range
```
what should i do?thanks for help a lot

**Comment by ZwwWayne** [comment]
From the annotation format, it seems that there is no polygon or mask annotation in the JSON. From the error message, it seems that the `masks` is empty.

**Comment by jovenwayfarer** [comment]
> From the annotation format, it seems that there is no polygon or mask annotation in the JSON. From the error message, it seems that the `masks` is empty.

Hi, could explain what do you mean by `masks`? I have the same problem. Thanks!

**Comment by jovenwayfarer** [comment]
@darkness605 HI! Could explain how did you solve the problem?

**Comment by srishilesh** [comment]
> From the annotation format, it seems that there is no polygon or mask annotation in the JSON. From the error message, it seems that the `masks` is empty.

@ZwwWayne Could you explain what you mean by `masks`?

@darkness605 Were you able to solve this? If so, please explain.

**Comment by jamie-ji** [comment]
Were you able to solve this? If so, please explain.

**Comment by nabilragab** [comment]
to train mask-rcnn you should annotate your data using a polygon or mask...
-i saw in another tutorial using bounding box, but it doesn't seem to be the case here.

-CHANGE LABELS :)

**Comment by Chidu2000** [comment]
I am running SRGAN algorithm using my custom dataset to train the model.

I am getting an error,
  File "/home/ubuntu/Downloads/Image processing project/SRGAN_ImProc_code/dataset.py", line 33, in __getitem__
    GT = self.GT_img[i].astype(np.float32)
IndexError: list index out of range

I tried putting a condition (i.e base case)
while pre_epoch < args.pre_train_epoch:
        for i, tr_data in enumerate(loader):
            **if i>= len(loader):     // my modification
                break** 
            
            gt = tr_data['GT'].to(device)
            lr = tr_data['LR'].to(device)

            output, _ = generator(lr)
            loss = l2_loss(gt, output)

            g_optim.zero_grad()
            loss.backward()
            g_optim.step()

        pre_epoch += 1

        if pre_epoch % 2 == 0:
            print(pre_epoch)
            print(loss.item())
            print('=========')
        
        if pre_epoch % 800 ==0:
            torch.save(generator.state_dict(), './model/pre_trained_model_%03d.pt'%pre_epoch)
ode.py such that,

How to fix this error??
