### ISSUE TITLE
Dynamic rcnn SmoothL1Loss  assert beta > 0 AssertionError

### ISSUE THREAD

**Issue by DingShengLin** [open-mmlab/mmdetection#3384]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when i add dynamic component  (DynamicRoiHead, SmoothL1Loss) into my config file , there is a AssertionError:

Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/dsl/my_project/mmdetection_update/mmdet/apis/train.py", line 129, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/two_stage.py", line 165, in forward_train
    **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/roi_heads/dynamic_roi_head.py", line 88, in forward_train
    img_metas)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/roi_heads/dynamic_roi_head.py", line 127, in _bbox_forward_train
    *bbox_targets)
  File "/home/dsl/my_project/mmdetection_update/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 182, in loss
    reduction_override=reduction_override)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/losses/smooth_l1_loss.py", line 93, in forward
    **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/losses/utils.py", line 94, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/losses/smooth_l1_loss.py", line 21, in smooth_l1_loss
    assert beta > 0
AssertionError

can anyone help me ?

**Comment by hellock** [comment]
@implus may help.

**Comment by DingShengLin** [comment]
when i change the beta update manner from  median to mean, I can successfully train the network, but why ??

 #new_beta = min(self.train_cfg.dynamic_rcnn.initial_beta,
  #               np.median(self.beta_history))
new_beta = min(self.train_cfg.dynamic_rcnn.initial_beta,
                    np.mean(self.beta_history))

**Comment by hkzhang95** [comment]
> when i change the beta update manner from median to mean, I can successfully train the network, but why ??
> 
> #new_beta = min(self.train_cfg.dynamic_rcnn.initial_beta,
> #np.median(self.beta_history))
> new_beta = min(self.train_cfg.dynamic_rcnn.initial_beta,
> np.mean(self.beta_history))

Intuitively, there are a lot of 0s in the `self.beta_history`, and if you use `np.median` you will update beta as 0, and the error occurs. When you change `np.median` to `np.mean`, there may exist some non-zero values so the beta will not be 0.

So why are there so many zeros?

Faster R-CNN will append the ground-truth bounding boxes into the batch when training. So if there are **no other positive samples** but ground-truths, `self.beta_history` will record 0 since the regression label is 0. I guess this is the final reason.

**Comment by DingShengLin** [comment]
@hkzhang95 thank you very much , i got it !

**Comment by twmht** [comment]
@DingShengLin 
@ZwwWayne 

so is it ok to change np.median to np.mean?

**Comment by DingShengLin** [comment]
@twmht yes, its ok !

**Comment by ZwwWayne** [comment]
> @DingShengLin
> @ZwwWayne
> 
> so is it ok to change np.median to np.mean?
> 
> or should we just return zero loss if beta is 0?

When beta=0, it should act as L1 loss rather than return zero loss.

**Comment by ywx-hub** [comment]
@hkzhang95 
hi, thanks for your code.
i am reading dynamic_roi_head.py  recently and have a question about the code:

if len(self.iou_history) % update_iter_interval == 0:
            new_iou_thr, new_beta = self.update_hyperparameters()

After updated  beta,how can new_beta transfer to SmoothL1loss？i can't find which code call this new_beta.
Thank  you very much!
