### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by LicharYuan** [open-mmlab/mmdetection#3398]
**Describe the bug**
Hi, I run the demo and encounter CUDA error: invalid device function

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py 
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO
3. What dataset did you use?
COCO

**Environment**
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

The result of python mmdet/utils/collect_env.py. 

```
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
PyTorch: 1.5.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_
70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREA
DPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unu
sed-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-e
rror=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, 
PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=O
FF, 

TorchVision: 0.6.1
OpenCV: 4.3.0
MMCV: 1.0.3
MMDetection: 2.3.0rc0+b05c17e
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.0
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
       I tried to install from conda and pip, and this issue still exists
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/mnt/truenas/scratch/liuchun.yuan/anacodna3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/detectors/two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 574, in get_bboxes
    scale_factor, cfg, rescale)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/ops/nms.py", line 242, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/utils/misc.py", line 262, in new_func
    output = old_func(*args, **kwargs)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/ops/nms.py", line 112, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/mnt/truenas/scratch/liuchun.yuan/projects/mmcv/mmcv/ops/nms.py", line 19, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: invalid device function
[1]    1159 segmentation fault (core dumped)  python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by TeleeMa** [comment]
I have the same problem, I hope there is solution to fix it.

**Comment by hellock** [comment]
https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md#common-issues

**Comment by LicharYuan** [comment]
> https://github.com/open-mmlab/mmdetection/blob/master/docs/install.md#common-issues

I found it is because the version of mmcv is 1.0.3, which makes it incompatible. Now it is ok. Thank you!
