### ISSUE TITLE
NASFPN AssertionError

### ISSUE THREAD

**Issue by DingShengLin** [open-mmlab/mmdetection#3401]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When i add NASFPN structure into my faster_rcnn config file , there is a asstertionerror:
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/dsl/my_project/mmdetection_update/mmdet/apis/train.py", line 129, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/two_stage.py", line 143, in forward_train
    x = self.extract_feat(img)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/detectors/two_stage.py", line 85, in extract_feat
    x = self.neck(x)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/models/necks/nas_fpn.py", line 155, in forward
    p7_tmp = stage['gp_54_7'](p5, p4_2, out_size=p7.shape[-2:])
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dsl/my_project/mmdetection_update/mmdet/ops/merge_cells.py", line 111, in forward
    x1 = self._resize(x1, out_size)
  File "/home/dsl/my_project/mmdetection_update/mmdet/ops/merge_cells.py", line 97, in _resize
    assert x.shape[-2] % size[-2] == 0 and x.shape[-1] % size[-1] == 0
AssertionError

**Reproduction**
1. Did you make any modifications on the code or config? Did you understand what you have modified?
  i change neck from fpn to nasfpn:
    #neck=dict(
        #type='FPN',
        #in_channels=[256, 512, 1024, 2048],
        #out_channels=256,
        #num_outs=5),
    neck=dict(
        type="NASFPN",
        in_channels=[256,512,1024,2048],
        out_channels=256,
        num_outs=5,
        stack_times=7,
        add_extra_convs=True),

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by lh0515** [comment]
I have the same problem.

**Comment by ZwwWayne** [comment]
Faster RCNN's FPN is different from RetinaNet's FPN. You need to check the difference and modify the config accordingly.

**Comment by lh0515** [comment]
I used RetinaNet with NasFpn，it still didn't work. The same problem still exists.

**Comment by ZwwWayne** [comment]
Hi @lh0515 ,
Do you use [this config](https://github.com/open-mmlab/mmdetection/blob/master/configs/nas_fpn/retinanet_r50_nasfpn_crop640_50e_coco.py)? Or you use customized config and meet similar issues? Please raise a new issue using the `reimplementation questions` and describe your bug in detail.

**Comment by jklp2** [comment]
exists.



> I used RetinaNet with NasFpn，it still didn't work. The same problem still exists.

I had the same problem before. I solved it by changing the image size to 512*512.

**Comment by kernel-Peanut** [comment]
when you use nasfpn, size_divisor of Pad should be 128, or image size is a multiple of 128, because nasfpn downsample 128x

**Comment by Neesky** [comment]
> when you use nasfpn, size_divisor of Pad should be 128, or image size is a multiple of 128, because nasfpn downsample 128x

think you!!! you help me a lot.

**Comment by JarvisKevin** [comment]
https://zhuanlan.zhihu.com/p/515073653
