### ISSUE TITLE
No module named 'mmcv.cnn.weight_init'

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mmdetection#3402]
Please tell me the solution, thanks

```
/home/sarim/PycharmProjects/trajectory_prediction/venv/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "/home/sarim/PycharmProjects/trajectory_prediction/obj_det_track.py", line 13, in <module>
    from DetectoRS.mmdet.apis import init_detector, inference_detector
  File "/home/sarim/PycharmProjects/trajectory_prediction/DetectoRS/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/sarim/PycharmProjects/trajectory_prediction/DetectoRS/mmdet/apis/inference.py", line 13, in <module>
    from mmdet.models import build_detector
  File "/home/sarim/PycharmProjects/trajectory_prediction/DetectoRS/mmdet/models/__init__.py", line 3, in <module>
    from .bbox_heads import *  # noqa: F401,F403
  File "/home/sarim/PycharmProjects/trajectory_prediction/DetectoRS/mmdet/models/bbox_heads/__init__.py", line 3, in <module>
    from .double_bbox_head import DoubleConvFCBBoxHead
  File "/home/sarim/PycharmProjects/trajectory_prediction/DetectoRS/mmdet/models/bbox_heads/double_bbox_head.py", line 2, in <module>
    from mmcv.cnn.weight_init import normal_init, xavier_init
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

Process finished with exit code 1
```

**Comment by azibit** [comment]
Try this: pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html

**Comment by hellock** [comment]
The version you used may be too old.

**Comment by dhananjayd232** [comment]
> pip install mmcv-full==latest+torch1.5.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html

still getting same issue as mentioned

**Comment by DanieleFundaro** [comment]
I have the same problem too.

**Comment by kaizhan** [comment]
all you need to do  is 
pip install mmcv==0.4.3

**Comment by Armstrong-lsw** [comment]
> all you need to do is
> pip install mmcv==0.4.3

god like!

**Comment by PrithwishChakraborty** [comment]
even after installing mmcv==0.4.3 getting the same error

**Comment by dav-ell** [comment]
Same. mmcv is on 2.0.0 now, also.

**Comment by KaneiGi** [comment]
change the code 
from `mmcv.cnn.weight_init` 
to `mmcv.cnn`

**Comment by wuchengu** [comment]
Actually pip install mmcv==1.0.2 will fix this. I tried for accidently and succeed.

**Comment by PKUHaoWang** [comment]
from mmengine.model import constant_init

**Comment by maxiuw** [comment]
if you're using `xavier_init` it's in `from mmengine.model import xavier_init` instead :)

**Comment by chengamo** [comment]
This will be vallid. `from mmengine.model import (constant_init, normal_init,
                                        trunc_normal_init)`
