### ISSUE TITLE
NameError: name 'DefaultOptimizerConstructor' is not defined

### ISSUE THREAD

**Issue by sehyungp92** [open-mmlab/mmdetection#3406]
When I try to use the DefaultOptimizerConstructor as per the instructions I get a NameError. Just wanted to check whether this is a version issue or if I've done something very silly. Thanks.

**Reproduction**
1. What command or script did you run?
```
python tools/train.py htc_lr.py
```

**Environment**
MMCV: 0.6.2
MMDetection: 2.1.0+cdaf42b

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 64, in main
    cfg = Config.fromfile(args.config)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py", line 178, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/config.py", line 108, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmplvdmqbp5/tmpadgb4z0p.py", line 291, in <module>
NameError: name 'DefaultOptimizerConstructor' is not defined
```

**Comment by ZwwWayne** [comment]
MMCV 0.6.2 should already contain `DefaultOptimizerConstructor`. You might need to uninstall and re-install mmcv.
