### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by ryan994** [open-mmlab/mmdetection#3439]
Hello, I am trying to install mmdet2 into Windows10, when I run demo, there is an error, I have no clue to fix that.

(mmdet2) D:\Users\ryan.wangr\Downloads\mmdetection-2.0.0>python demo/image_demo.py demo/demo.jpg configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
Traceback (most recent call last):
  File "demo/image_demo.py", line 28, in <module>
    main()
  File "demo/image_demo.py", line 22, in main
    result = inference_detector(model, args.img)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\apis\inference.py", line 101, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\core\fp16\decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\detectors\base.py", line 150, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\detectors\base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\detectors\two_stage.py", line 187, in simple_test
    proposal_list = self.simple_test_rpn(x, img_metas)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\detectors\test_mixins.py", line 29, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*rpn_outs, img_metas)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\core\fp16\decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\dense_heads\anchor_head.py", line 490, in get_bboxes
    scale_factor, cfg, rescale)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\models\dense_heads\rpn_head.py", line 119, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\ops\nms\nms_wrapper.py", line 146, in batched_nms
    torch.cat([bboxes_for_nms, scores[:, None]], -1), **nms_cfg_)
  File "D:\Anaconda3\envs\mmdet2\lib\site-packages\mmdet-2.0.0+unknown-py3.6-win-amd64.egg\mmdet\ops\nms\nms_wrapper.py", line 53, in nms
    inds = nms_ext.nms(dets_th, iou_thr)
RuntimeError: nms is not compiled with GPU support (nms at mmdet\ops\nms\src/nms_ext.cpp:20)
(no backtrace available)

I am using pytorch1.3.1 torchvision0.4.2 cuda10.1

**Comment by hiromesh** [comment]
hi, I have meet the similar problem: RuntimeError: nms is not compiled with GPU support (nms at mmdet\ops\nms\src/nms_ext.cpp:23)
(no backtrace available)
have you solve it?
I am also using pytorch1.3.1 torchvision0.4.2 cuda10.1.

**Comment by del-zhenwu** [comment]
Now we have provided the Windows package for `mmcv`, pls try it with following the docs.
