### ISSUE TITLE
undefined symbol: _ZN3c1019ComplexCUDATensorIdEv

### ISSUE THREAD

**Issue by rajat997** [open-mmlab/mmdetection#3440]
(alpha) rajat@rajat-Lenovo-Legion-Y540-15IRH-PG0:~/Documents/alphapose/AlphaPose$ python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-
3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/
Traceback (most recent call last):
  File "scripts/demo_inference.py", line 14, in <module>
    from alphapose.models import builder
  File "/home/rajat/Documents/alphapose/AlphaPose/alphapose/models/__init__.py", line 1, in <module>
    from .fastpose import FastPose
  File "/home/rajat/Documents/alphapose/AlphaPose/alphapose/models/fastpose.py", line 10, in <module>
    from .layers.SE_Resnet import SEResnet
  File "/home/rajat/Documents/alphapose/AlphaPose/alphapose/models/layers/SE_Resnet.py", line 9, in <module>
    from .dcn import DeformConv, ModulatedDeformConv
  File "/home/rajat/Documents/alphapose/AlphaPose/alphapose/models/layers/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/rajat/Documents/alphapose/AlphaPose/alphapose/models/layers/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: /home/rajat/Documents/alphapose/AlphaPose/alphapose/models/layers/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019ComplexCUDATensorIdEv

alphapose-https://github.com/MVIG-SJTU/AlphaPose

**Comment by bluesky314** [comment]
MMdetection was working yesterday, today I just tried to install mmdetection and running :
`from mmcv.ops import get_compiling_cuda_version, get_compiler_version`
Gives me similar:
`ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
`

**Comment by changqinyao** [comment]
I have same error，have you solve it?

**Comment by changqinyao** [comment]
> I have similar error, MMdetection was working yesterday, today I just tried to install mmdetection and running :
> `from mmcv.ops import get_compiling_cuda_version, get_compiler_version`
> Gives me similar:
> `ImportError: /usr/local/lib/python3.6/dist-packages/mmcv/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv `

I have same error，have you solve it?

**Comment by ZwwWayne** [comment]
Please use the `error template` to report the version of GCC/CUDA/Pytorch/MMCV in your environment
