### ISSUE TITLE
when i use  res2net  backbone    for detectors   ,it shows no conv1  but i can print it in res2net

### ISSUE THREAD

**Issue by yutao007** [open-mmlab/mmdetection#3449]
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/apis/train.py", line 111, in train_detector
    meta=meta)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/apis/train.py", line 242, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/models/detectors/base.py", line 147, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/models/detectors/htc.py", line 207, in forward_train
    x = self.extract_feat(img)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/models/detectors/rfp.py", line 106, in extract_feat
    x_idx = self.rfp_modules[rfp_idx].rfp_forward(img, rfp_feats)
  File "/home/bova/Downloads/DetectoRS_new/mmdet/models/backbones/resnet.py", line 892, in rfp_forward
    x = self.conv1(x)
  File "/home/bova/anaconda3/envs/solo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'Res2Net' object has no attribute 'conv1'

**Comment by yutao007** [comment]
resnet resnext 可以正常运行，但是res2net不行。求大神调bug

**Comment by cpboost** [comment]
需要自己写detectors的代码，

**Comment by yutao007** [comment]
谢谢。我尝试的改res2net，但是自己能力不够，报上面的错误，准备等你们的改进版。

**Comment by shinya7y** [comment]
Recent Res2Net uses deep_stem instead of conv1.
DetectoRS_ResNet in this repository (open-mmlab/mmdetection) looks supporting deep_stem.
https://github.com/open-mmlab/mmdetection/blob/57bbfb7e275250bbf1f72f7242de2901c66b4a1c/mmdet/models/backbones/detectors_resnet.py#L290-L295
