### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by bozihu** [open-mmlab/mmdetection#3470]
Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/root/models/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/root/models/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIAlign, RoIPool
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /root/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

**Comment by sky-fly97** [comment]
I have this problem too, have solved it? Thanks!!

**Comment by hellock** [comment]
Please follow the `Error report` issue template.
