### ISSUE TITLE
lib2to3.pgen2.parse.ParseError

### ISSUE THREAD

**Issue by leopardyao** [open-mmlab/mmdetection#3477]
Hello,
I have installed  latest mmdetection 2.3.0 , and the mmcv-full 1.0.4 + torch 1.4.0 + cuda10.0
below are some related packages in the enviorment:
mmcv-full                 1.0.4                    pypi_0    pypi
mmdet                     2.3.0rc0+40bc19a           dev_0    <develop>
pytorch 1.14.0
yapf 0.30.0
torchvision=0.5.0

1. I created my VOC-format dataset. and slightly modifed config/pascal_VOC/***faster_rcnn***.py, config/_base_/dataset/voc_0712.py and core/evaluation/class_names.py to fit into my dataset

2.  I can run image_demo.py and test.py on my own trained model (the model was trained using mmdet 2.0.0 in my anothe enviroment)

3. HOWEVER, when I train with the new built mmdet 2.3.0, i run into below problems:
python tools/train.py configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc_XXXXX.py

Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (255, 12))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/driver.py", line 104, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/driver.py", line 72, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=20, value='<', context=('', (255, 12))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 96, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 377, in dump
    f.write(self.pretty_text)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 341, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/yapf_api.py", line 147, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
    raise e
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
    ast.parse(code)
  File "/home/usr/anaconda3/envs/open-mmlab/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 255
    voc_classes=<function voc_classes at 0x7f17b888d9e0>

Can someone help me here? looks like sth related to parsing or yapf...format thing
thanks a lot!

**Comment by leopardyao** [comment]
I think somehow I add some "import class_names" lines in the config.py
but the newest version seems can not parse that, 
what coud be a good way to dynamically change bbox_head then instead of a fixed number?

**Comment by hellock** [comment]
What do you mean by "dynamically change bbox_head"?

**Comment by okideal** [comment]
@leopardyao Hi, may I ask have you solved the mentioned problem?

**Comment by dzh1024** [comment]
i also meet this error ,  how do you solve it  ?  thx

**Comment by dzh1024** [comment]
> i also meet this error , how do you solve it ? thx

i’ve solved it ,just not match version ;using  mmcv-full==1.6.0 and mmsegmentation==0.28.0 can run it
