### ISSUE TITLE
cv2.error: OpenCV(4.3.0) /io/opencv/modules/core/src/copy.cpp:1415: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

### ISSUE THREAD

**Issue by MrSupW** [open-mmlab/mmdetection#3482]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

cv2.error: OpenCV(4.3.0) /io/opencv/modules/core/src/copy.cpp:1415: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.py --gpus 1
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
coco数据集
**Environment**

sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce GTX 1650
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.3.0
MMCV: 1.0.5
MMDetection: 2.3.0rc0+unknown
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/mrsupw/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/mrsupw/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mrsupw/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/datasets/custom.py", line 187, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/datasets/custom.py", line 210, in prepare_train_img
    return self.pipeline(results)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/datasets/pipelines/transforms.py", line 427, in __call__
    self._pad_masks(results)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/datasets/pipelines/transforms.py", line 408, in _pad_masks
    results[key] = results[key].pad(pad_shape, pad_val=self.pad_val)
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/core/mask/structures.py", line 234, in pad
    for mask in self.masks
  File "/home/mrsupw/mmdetection/mmdetection-master/mmdet/core/mask/structures.py", line 234, in <listcomp>
    for mask in self.masks
  File "/home/mrsupw/.local/lib/python3.7/site-packages/mmcv/image/geometric.py", line 439, in impad
    value=pad_val)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/core/src/copy.cpp:1415: error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'copyMakeBorder'

```

**Comment by MrSupW** [comment]
Yesterday it went very well, but today it crashed!!
I am really confused...

**Comment by light1003** [comment]
did you change dataset?,I meet this error too.I found some images in my dataset have exif information cause this error.

**Comment by Kingpopen** [comment]
Hello, have you solved this problem, I encountered the same problem when I used my own dataset(coco format) to train the mask-rcnn model.

**Comment by xvjiarui** [comment]
Hi all,
You may try checking if your image is correct (not corrupted).

**Comment by vincentpalma** [comment]
Hi, I had the same problem and it was because some images were taken with a cellphone and the orientation was not taken into account, meaning that the width and height were swapped which caused an error while padding. See https://github.com/open-mmlab/mmdetection/issues/482#issuecomment-482779230

I ended up just removing the problematic images from my dataset. Here is a python script to detect those:
```python
import glob
import mmcv
from PIL import Image
import json
import numpy as np

img_path = "/path/to/your/images/"

print("parsing images...")
images = glob.glob(img_path+"*.jpg")

print("checking images...")
inverted = []
for f in images:
	if str(mmcv.imread(f).shape) != str(np.array(Image.open(f)).shape):
		inverted.append(f)
print(len(inverted),"bad images :",inverted)

```

**Comment by 920666358** [comment]
hello, how do you solve this problem? I meet the same bug T T
