### ISSUE TITLE
RuntimeError: DataLoader worker (pid 12890) is killed by signal: Killed.

### ISSUE THREAD

**Issue by minan19605** [open-mmlab/mmdetection#3495]
**Describe the bug**
I use HTC to train myself dataset. During the training procedure,  the mmdetection will run validation procedure for every epoch.
I found two problems:
1. the validate procedure spend a much longer time than a separate validation procedure.
2. after validation, when starting the next training epoch, the DataLoader procedure was killed. I guess the validation procedure speed to much time and block the training related procedures.

The output as below. you can find the validation procedure spends about 4000s. But when I run python tools/test.py after training procedure finished, it speeds about 1600s.

2020-08-05 11:57:43,994 - mmdet - INFO - Start running, host: zqc@zqc-MS-7885-In valid-entry-length-16-Fixed-up-to-11, work_dir: /home/zqc/zjj/mmdetection/work_d irs/htc/20200804
2020-08-05 11:57:43,995 - mmdet - INFO - workflow: [('train', 1)], max: 200 epoc hs
2020-08-05 12:00:32,952 - mmdet - INFO - Epoch [1][50/175]      lr: 1.978e-03, e ta: 1 day, 8:47:27, time: 3.378, data_time: 2.356, memory: 6405, loss_rpn_cls: 0 .6710, loss_rpn_bbox: 0.2255, s0.loss_cls: 0.3607, s0.acc: 88.1484, s0.loss_bbox : 0.0790, s0.loss_mask: 0.8372, s1.loss_cls: 0.1658, s1.acc: 92.7044, s1.loss_bb ox: 0.0230, s1.loss_mask: 0.5567, s2.loss_cls: 0.0958, s2.acc: 86.9154, s2.loss_ bbox: 0.0030, s2.loss_mask: 0.2721, loss: 3.2898
2020-08-05 12:02:45,747 - mmdet - INFO - Epoch [1][100/175]     lr: 3.976e-03, e ta: 1 day, 5:14:47, time: 2.656, data_time: 1.639, memory: 7010, loss_rpn_cls: 0 .4523, loss_rpn_bbox: 0.1860, s0.loss_cls: 0.3186, s0.acc: 90.4557, s0.loss_bbox : 0.1073, s0.loss_mask: 0.5625, s1.loss_cls: 0.1379, s1.acc: 92.9622, s1.loss_bb ox: 0.0316, s1.loss_mask: 0.2836, s2.loss_cls: 0.0658, s2.acc: 93.9427, s2.loss_ bbox: 0.0048, s2.loss_mask: 0.1456, loss: 2.2961
2020-08-05 12:05:24,857 - mmdet - INFO - Epoch [1][150/175]     lr: 5.974e-03, e ta: 1 day, 5:44:17, time: 3.182, data_time: 2.012, memory: 7469, loss_rpn_cls: 0 .2535, loss_rpn_bbox: 0.1889, s0.loss_cls: 0.4034, s0.acc: 82.9779, s0.loss_bbox : 0.3054, s0.loss_mask: 0.4567, s1.loss_cls: 0.1643, s1.acc: 88.7878, s1.loss_bb ox: 0.1087, s1.loss_mask: 0.2315, s2.loss_cls: 0.0683, s2.acc: 92.1445, s2.loss_ bbox: 0.0178, s2.loss_mask: 0.1191, loss: 2.3176
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 166/166, 0.0 task/s, elapsed: 4000s, ETA:     0s2 020-08-05 13:13:11,545 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.16s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=15.17s).
Accumulating evaluation results...
DONE (t=0.12s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.031
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.131
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.031
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.004
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.036
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.150
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.151
2020-08-05 13:13:27,005 - mmdet - INFO - Evaluating segm...
Loading and preparing results...
DONE (t=0.23s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=16.05s).
Accumulating evaluation results...
DONE (t=0.12s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.036
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.147
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.012
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.037
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.006
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.045
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.144
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.012
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.145
2020-08-05 13:13:43,599 - mmdet - INFO - Epoch [1][175/175]     lr: 6.973e-03, b box_mAP: 0.0310, bbox_mAP_50: 0.1310, bbox_mAP_75: -1.0000, bbox_mAP_s: -1.0000,  bbox_mAP_m: 0.0000, bbox_mAP_l: 0.0310, bbox_mAP_copypaste: 0.031 0.131 -1.000  -1.000 0.000 0.031, segm_mAP: 0.0360, segm_mAP_50: 0.1470, segm_mAP_75: -1.0000,  segm_mAP_s: -1.0000, segm_mAP_m: 0.0120, segm_mAP_l: 0.0370, segm_mAP_copypaste : 0.036 0.147 -1.000 -1.000 0.012 0.037
2020-08-05 13:16:34,992 - mmdet - INFO - Epoch [2][50/175]      lr: 8.971e-03, e ta: 1 day, 3:08:16, time: 3.426, data_time: 2.185, memory: 7659, loss_rpn_cls: 0 .1884, loss_rpn_bbox: 0.1825, s0.loss_cls: 0.4093, s0.acc: 82.0807, s0.loss_bbox : 0.3555, s0.loss_mask: 0.4153, s1.loss_cls: 0.1835, s1.acc: 84.6927, s1.loss_bb ox: 0.1954, s1.loss_mask: 0.2042, s2.loss_cls: 0.0738, s2.acc: 90.2396, s2.loss_ bbox: 0.0402, s2.loss_mask: 0.1053, loss: 2.3534
2020-08-05 13:18:58,674 - mmdet - INFO - Epoch [2][100/175]     lr: 1.097e-02, e ta: 1 day, 3:12:41, time: 2.874, data_time: 1.577, memory: 7659, loss_rpn_cls: 0 .1608, loss_rpn_bbox: 0.1744, s0.loss_cls: 0.3785, s0.acc: 83.1263, s0.loss_bbox : 0.3397, s0.loss_mask: 0.3816, s1.loss_cls: 0.1790, s1.acc: 84.0091, s1.loss_bb ox: 0.2369, s1.loss_mask: 0.1881, s2.loss_cls: 0.0750, s2.acc: 88.3398, s2.loss_ bbox: 0.0631, s2.loss_mask: 0.0967, loss: 2.2736
2020-08-05 13:21:24,955 - mmdet - INFO - Epoch [2][150/175]     lr: 1.297e-02, e ta: 1 day, 3:19:37, time: 2.926, data_time: 1.594, memory: 8201, loss_rpn_cls: 0 .1409, loss_rpn_bbox: 0.1634, s0.loss_cls: 0.3577, s0.acc: 84.3320, s0.loss_bbox : 0.3222, s0.loss_mask: 0.3667, s1.loss_cls: 0.1697, s1.acc: 85.2074, s1.loss_bb ox: 0.2354, s1.loss_mask: 0.1813, s2.loss_cls: 0.0749, s2.acc: 87.8835, s2.loss_ bbox: 0.0715, s2.loss_mask: 0.0915, loss: 2.1751
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 166/166, 0.0 task/s, elapsed: 4048s, ETA:     0s2 020-08-05 14:29:59,653 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.06s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=14.65s).
Accumulating evaluation results...
DONE (t=0.12s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.241
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.558
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.051
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.243
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.019
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.141
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.378
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.049
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.381
2020-08-05 14:30:14,492 - mmdet - INFO - Evaluating segm...
Loading and preparing results...
DONE (t=0.23s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=15.35s).
Accumulating evaluation results...
DONE (t=0.12s).
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.216
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.548
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.050
Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.218
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.018
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.129
Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.315
Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.047
Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.317
2020-08-05 14:30:30,230 - mmdet - INFO - Epoch [2][175/175]     lr: 1.397e-02, b box_mAP: 0.2410, bbox_mAP_50: 0.5580, bbox_mAP_75: -1.0000, bbox_mAP_s: -1.0000,  bbox_mAP_m: 0.0510, bbox_mAP_l: 0.2430, bbox_mAP_copypaste: 0.241 0.558 -1.000  -1.000 0.051 0.243, segm_mAP: 0.2160, segm_mAP_50: 0.5480, segm_mAP_75: -1.0000,  segm_mAP_s: -1.0000, segm_mAP_m: 0.0500, segm_mAP_l: 0.2180, segm_mAP_copypaste : 0.216 0.548 -1.000 -1.000 0.050 0.218
Traceback (most recent call last):
  File "tools/train.py", line 153, in <module>
    main()
  File "tools/train.py", line 149, in main
    meta=meta)
  File "/home/zqc/zjj/mmdetection/mmdet/apis/train.py", line 143, in train_detec tor
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/mmcv/runner/e poch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/mmcv/runner/e poch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/mmcv/parallel /data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/zqc/zjj/mmdetection/mmdet/models/detectors/base.py", line 237, in  train_step
    losses = self(**data)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/torch/nn/modu les/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zqc/zjj/mmdetection/mmdet/core/fp16/decorators.py", line 51, in ne w_func
    return old_func(*args, **kwargs)
  File "/home/zqc/zjj/mmdetection/mmdet/models/detectors/base.py", line 171, in  forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/zqc/zjj/mmdetection/mmdet/models/detectors/two_stage.py", line 164 , in forward_train
    **kwargs)
  File "/home/zqc/zjj/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line  323, in forward_train
    semantic_feat)
  File "/home/zqc/zjj/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line  154, in _mask_forward_train
    mask_pred = mask_head(mask_feats, last_feat, return_feat=False)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/torch/nn/modu les/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zqc/zjj/mmdetection/mmdet/models/roi_heads/mask_heads/htc_mask_hea d.py", line 36, in forward
    x = self.upsample(x)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/torch/nn/modu les/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/torch/nn/modu les/conv.py", line 790, in forward
    output_padding, self.groups, self.dilation)
  File "/home/zqc/anaconda3/envs/wheat/lib/python3.7/site-packages/torch/utils/d ata/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12890) is killed by signal: Killed.

**Reproduction**
1. What command or script did you run?
python tools/train.py configs/my_config/htc_without_semantic_r50_fpn_1x_coco_linux.py --work-dir work_dirs/htc/20200805

A placeholder for the command.
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Change some configuration. I understand what I did.

3. What dataset did you use?
COCO format dataset and it is my dataset. I am using this dataset for more than 6 months and with different models.

**Environment**
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.3.0
MMCV: 1.0.4
MMDetection: 2.3.0rc0+d06b352
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2

**Comment by ZwwWayne** [comment]
The dataloader's work will be killed by the system if the memory runs out. You may set `workers_per_gpu=1` or 0 to reduce the number of workers.

**Comment by minan19605** [comment]
But why the memory runs out?  Now I am using --no-validate parameter for training. That is working fine. But why do validation during the training procedure will have this problem. 
I have 20GB memory, and I watched memory usage by the 'top' command, only about 4-5GB be used.

**Comment by ZwwWayne** [comment]
I do not know the reason, this is usually not caused by the codebase but by the running environment.
