### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by lsabrinax** [open-mmlab/mmdetection#3502]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I test my trained libranet, it will report an  AttributeError: 'list' object has no attribute 'get'
**Reproduction**
1. What command or script did you run?
```
python tools/test.py configs/libra*
```

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "tools/test.py", line 153, in <module>
    main()
  File "tools/test.py", line 91, in main
    if cfg.model.neck.get('rfp_backbone'):
AttributeError: 'list' object has no attribute 'get'
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!
Because the libranet neck config is a list, so it will report error show as title, you can fix it.
```
neck=[
        dict(
            type='FPN',
            in_channels=[256, 512, 1024, 2048],
            out_channels=256,
            num_outs=5),
        dict(
            type='BFP',
            in_channels=256,
            num_levels=5,
            refine_level=2,
            refine_type='non_local')
    ],
```

**Comment by ZwwWayne** [comment]
Hi @lsabrinax ,
Thanks for your bug report, we will fix it ASAP.
