### ISSUE TITLE
run pytorch2onnx.py error to visualize model  sturcture.

### ISSUE THREAD

**Issue by fangxu622** [open-mmlab/mmdetection#3504]
it's better if could use tensorboar to visualize the model architecture.
but it have some bug , #2383   #3239.
So I use the pytorch2onnx ,then visiualize the model sturcture use netron.
some problem occurs whwn convert to onnx.

**Reproduction**
1. What command or script did you run?
```
python tools/pytorch2onnx.py ./configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py ~/Downloads/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
```
**Environment**
ubuntu 18.04 , pytorch 1.5 ,cuda 10.2

**Error traceback**
If applicable, paste the error trackback here.
```
(torch1.5) fangxu@fangxu:/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection$ python tools/pytorch2onnx.py ./configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py ~/Downloads/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/detectors/base.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert samples_per_gpu == 1
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/anchor/anchor_generator.py:255: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_h = int(feat_h)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/anchor/anchor_generator.py:256: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  feat_w = int(feat_w)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/anchor/anchor_generator.py:199: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  xx = x.repeat(len(y))
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/anchor/anchor_generator.py:200: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  yy = y.view(-1, 1).repeat(1, len(x)).view(-1)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/dense_heads/rpn_head.py:119: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rpn_cls_score.size()[-2:] == rpn_bbox_pred.size()[-2:]
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/dense_heads/rpn_head.py:132: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cfg.nms_pre > 0 and scores.shape[0] > cfg.nms_pre:
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:67: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmcv/mmcv/ops/nms.py:82: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 4
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmcv/mmcv/ops/nms.py:83: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(0) == scores.size(0)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/bbox/transforms.py:66: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.size(0) > 0:
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/roi_extractors/single_level_roi_extractor.py:74: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if inds.any():
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmcv/mmcv/ops/roi_align.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert rois.size(1) == 5, 'RoI must be (idx, x1, y1, x2, y2)!'
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/post_processing/bbox_nms.py:31: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] > 4:
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/bbox/transforms.py:106: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] == 0:
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/bbox/transforms.py:110: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bboxes = bboxes.cpu().detach().numpy()
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/core/bbox/transforms.py:111: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  labels = labels.cpu().detach().numpy()
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/test_mixins.py:161: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if det_bboxes.shape[0] == 0:
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:191: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  N = len(mask_pred)
/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/tensor.py:467: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:291: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.isinf(img_x).any():
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:294: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if torch.isinf(img_y).any():
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:233: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  im_mask[(inds, ) + spatial_inds] = masks_chunk
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:236: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cls_segms[labels[i]].append(im_mask[i].cpu().numpy())
/media/fangxu/Segate3T/PHD-Project/linux-3rd/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py:236: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cls_segms[labels[i]].append(im_mask[i].cpu().numpy())
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 166, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 58, in pytorch2onnx
    opset_version=opset_version)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/home/fangxu/anaconda3/envs/torch1.5/lib/python3.6/site-packages/torch/jit/__init__.py", line 351, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type numpy.ndarray
```

**Comment by hellock** [comment]
`pytorch2onnx` does not support two-stage detectors yet, and it has been updated a few days ago.

**Comment by fangxu622** [comment]
Oh, thanks , I was surprised by the speed of the response . Are there other ways to visualize models structure when we use the mmdetction ？

**Comment by xizi** [comment]
you can delete the .numpy()

**Comment by hellock** [comment]
> Oh, thanks , I was surprised by the speed of the response .that's owsome. Are there other ways to visualize models structure when we use the mmdetction ？

Although exporting to ONNX for two-stage detectors has not been supported yet, it should not be hard to achieve it by modifying some codes.

**Comment by moerbenkaola** [comment]
> you can delete the .numpy()
delete .numpy() cause "Exporting the operator new_full to ONNX opset version 11 is not supported". Tensor slice may cause new_full operator....

**Comment by xizi** [comment]
> you can delete the .numpy()
> delete .numpy() cause "Exporting the operator new_full to ONNX opset version 11 is not supported". Tensor slice may cause new_full operator....

onnx not support new_full, you can use new_ones()*scalar instead of new_full

**Comment by qiubai521** [comment]
有老铁解决了么：AttributeError: 'ConvModule' object has no attribute 'norm'

**Comment by ghoshaw** [comment]
> 有老铁解决了么：AttributeError: 'ConvModule' object has no attribute 'norm'

has solution?
