### ISSUE TITLE
ImportError: miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv

### ISSUE THREAD

**Issue by YaoSir323** [open-mmlab/mmdetection#3525]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Something wrong with MMdetection Compiler or Cuda Compiler?

**Reproduction**
1. What command or script did you run?
```
from mmdet.apis import init_detector, inference_detector, show_result
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, i didn't make any modifications.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
Actually, when I tried to run `python mmdet/utils/collect_env.py`, I got the same problems. The traceback is as follows.
```
$ python mmdet/utils/collect_env.py
Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 64, in <module>
    for name, val in collect_env().items():
  File "mmdet/utils/collect_env.py", line 57, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
```

Then I commented out the relative code lines(line57-line59), I got the result. (Compiler version and CUDA Compiler Version are missing here)
```
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0,1,2,3: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 3.4.2
MMCV: 1.0.5
MMDetection: 2.3.0+ae453fa
```

2. How you installed PyTorch [e.g., pip, conda, source]
`conda install -c pytorch pytorch torchvision -y`

**Error traceback**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhongyujiang/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/zhongyujiang/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIAlign, RoIPool
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/zhongyujiang/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceISt7complexIdEEEPKNS_6detail12TypeMetaDataEv
```

Looking forward to reply. Many Thanks!

**Comment by ZwwWayne** [comment]
Please check whether the Pytorch used for compiling your mmcv is the same as the runtime mmcv. For example, you may upgrade your pytorch version after install mmcv-full, in this situation, you need to re-install mmcv-full.

**Comment by biao321** [comment]
Have you solved the problem？It seems that there is no version of mmcv suitable for torch 1.5.0 and cuda10.0?  When you "pip install mmcv-full==1.0.4+torch1.5.0+cu100 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html" , you can not find a suitable source.

**Comment by ZwwWayne** [comment]
> Have you solved the problem？It seems that there is no version of mmcv suitable for torch 1.5.0 and cuda10.0? When you "pip install mmcv-full==1.0.4+torch1.5.0+cu100 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html" , you can not find a suitable source.

In this case you can simply use `pip install mmcv-full==1.0.4`. This is because Pytorch 1.5 does not have pre-built package for CUDA 10.0.

**Comment by prasadh711** [comment]
I am facing the same import error with an undefined symbol when I try to run  `python mmdet/utils/collect_env.py` . 
I am using 
pytorch 1.7 
 cuda 10.2
 mmcv-full 1.3.18
mmdet 2.20.0

Looking forward to your reply, thank you.

**Comment by Neil-untitled** [comment]
@prasadh711 You can try this:
mim uninstall mmcv-full
mim install mmcv-full
to upgrade mmcv to match current pytorch version
