### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ga_rpn_head'.

### ISSUE THREAD

**Issue by lxg15066629402** [open-mmlab/mmdetection#3542]
Traceback (most recent call last):
  File "tools/train.py", line 176, in <module>
    main()
  File "tools/train.py", line 138, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/dicom/Jone/Dection_mass/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/miniconda2/envs/Adam_mmlab2.0/lib/python3.7/site-packages/mmcv-0.5.9-py3.7-linux-x86_64.egg/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'ga_rpn_head'.

**Comment by ZwwWayne** [comment]
What is the version of your mmdetection & mmcv?This seems to be an incompatibility issue.

**Comment by lxg15066629402** [comment]
ok, I check it




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenwei Zhang"<notifications@github.com&gt;; 
发送时间: 2020年8月12日(星期三) 晚上10:07
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 
抄送: "Jone"<it_lxg@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmdetection] TypeError: __init__() got an unexpected keyword argument &#39;ga_rpn_head&#39;. (#3542)





 
What is the version of your mmdetection &amp; mmcv?This seems to be an incompatibility issue.
