### ISSUE TITLE
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other' in call to _th_and

### ISSUE THREAD

**Issue by uniyushu** [open-mmlab/mmdetection#3587]
**Describe the bug**
I meet a problem when I use mmdetection for training.I think it is some wrong with mmdetection core so I didn't try to change the code. Please help me solve this problem.

**Error traceback**
2020-08-20 08:05:19,720 - INFO - workflow: [('train', 1)], max: 240 epochs
/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/functional.py:2494: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 94, in main
    logger=logger)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 63, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 228, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/apis/train.py", line 41, in batch_processor
    losses = model(**data)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/open-mmlab-train/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/detectors/cascade_rcnn.py", line 137, in forward_train
    *rpn_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/anchor_heads/rpn_head.py", line 51, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/models/anchor_heads/anchor_head.py", line 179, in loss
    sampling=self.sampling)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 108, in anchor_target_single
    cfg.allowed_border)
  File "/data/data/ysc_data/project/Pedestron/mmdet/core/anchor/anchor_target.py", line 176, in anchor_inside_flags
    (flat_anchors[:, 2] < img_w + allowed_border) & \
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other' in call to _th_and

**Comment by v-qjqs** [comment]
Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all Tensors here to torch.uint8 or torch.bool manually?

**Comment by uniyushu** [comment]
> Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?

> Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?

Thank you, You are right.I manually convert the tensors and solve the problem.

**Comment by BronyazzZ** [comment]
how did you solve the problem ,can i see your code?

**Comment by liuyibi** [comment]
I also can solve this problem，can i see your code?

> > Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?
> 
> Thank you, You are right.I manually convert the tensors and solve the problem.

I also can solve this problem，can i see your code?

**Comment by liuyibi** [comment]
> > Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?
> 
> Thank you, You are right.I manually convert the tensors and solve the problem.

I also can solve this problem，can i see your code?

**Comment by WuhongYui** [comment]
> > Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?
> 
> Thank you, You are right.I manually convert the tensors and solve the problem.

> I have the same problem as you, could you tell me how did you solve it?

**Comment by WuhongYui** [comment]
> > Hi, I guess this may be caused by PyTorch version? May you convert the dtype of all tensors here to torch.uint8 or torch.bool manually?
> 
> Thank you, You are right.I manually convert the tensors and solve the problem.

I have the same problem as you, could you tell me how did you solve it?
