### ISSUE TITLE
when output .json not .pkl, it seems to has some error. 

### ISSUE THREAD

**Issue by caiduoduo12138** [open-mmlab/mmdetection#3597]
when I do object detection ,I use this command to output the result with json format :（.pkl format can generate correctly） 
./tools/dist_test.sh configs/hrnet/cascade_rcnn_hrnetv2p_w40_20e_coco.py checkpoints/epoch_2.pth 2 --format-only --eval-options "jsonfile_prefix=./res"
But it seems to has some problem,I would be very grateful if you could help me。

Here are some details:
loading annotations into memory...
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Done (t=0.01s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1200/1200, 16.3 task/s, elapsed: 73s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 189, in <module>
    main()
  File "./tools/test.py", line 178, in main
    dataset.format_results(outputs, **kwargs)
  File "/home/cai/mmdetection2.3/mmdet/datasets/underwater.py", line 349, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/cai/mmdetection2.3/mmdet/datasets/underwater.py", line 281, in results2json
    json_results = self._det2json(results)
  File "/home/cai/mmdetection2.3/mmdet/datasets/underwater.py", line 217, in _det2json
    data['category_id'] = self.cat_ids[label]#######
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/cai/anaconda3/envs/mmd2/bin/python', '-u', './tools/test.py', '--local_rank=1', 'configs/hrnet/cascade_rcnn_hrnetv2p_w40_20e_coco.py', 'checkpoints/epoch_2.pth', '--launcher', 'pytorch', '--format-only', '--eval-options', 'jsonfile_prefix=./11']' returned non-zero exit status 1.

**Comment by yhcao6** [comment]
```
File "/home/cai/mmdetection2.3/mmdet/datasets/underwater.py", line 217, in _det2json
data['category_id'] = self.cat_ids[label]#######
```
Can you modify this line with and run again to see the output
```
try:
    data['category_id'] = self.cat_ids[label]
except:
    print(f'len data: {len(data)}, category_id: {category_id}, len(cat_ids): {len(self.cat_ids)}, label: {label}')
    exit()
```

**Comment by wongsinglam** [comment]
Hi, your custom classes are 4 and the num_classes should be 5 (4 + background).

**Comment by caiduoduo12138** [comment]
> Hi, your custom classes are 4 and the num_classes should be 5 (4 + background).

Hi, the version of mmdet I used was 2.+, so the classes should be set without background .

**Comment by wongsinglam** [comment]
> > Hi, your custom classes are 4 and the num_classes should be 5 (4 + background).
> 
> Hi, the version of mmdet I used was 2.+, so the classes should be set without background.

Thank you. I solved my problem when I don't consider the background. I didn't meet the problem when I train a big dataset but it happened when the dataset is small.
