### ISSUE TITLE
How to get polygon format ground-truths when calculating the mask head loss in mask-rcnn.

### ISSUE THREAD

**Issue by zeakey** [open-mmlab/mmdetection#3599]
I want to catch polygon-style mask_targets (instead of masks) when calculating the FCNMaskHead loss:
<https://github.com/open-mmlab/mmdetection/blob/9596b9a4c916ae601f9a8a641c3a0ea47265abec/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py#L138-L149>.

After reading the source code, I simply add `poly2mask=False` to `dict(type='LoadAnnotations', with_bbox=True, with_mask=True, poly2mask=False)` <https://github.com/open-mmlab/mmdetection/blob/9596b9a4c916ae601f9a8a641c3a0ea47265abec/configs/_base_/datasets/cityscapes_instance.py#L7>,
and then start training by
```
python tools/train.py configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py
```

It gives me the error below:
```
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "/media/hdd0/Code/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/media/hdd0/Code/mmdetection/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/hdd0/Code/mmdetection/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/dataset_wrappers.py", line 78, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/custom.py", line 187, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/custom.py", line 210, in prepare_train_img
    return self.pipeline(results)
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/pipelines/loading.py", line 339, in __call__
    results = self._load_masks(results)
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/pipelines/loading.py", line 294, in _load_masks
    [self.process_polygons(polygons) for polygons in gt_masks], h,
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/pipelines/loading.py", line 294, in <listcomp>
    [self.process_polygons(polygons) for polygons in gt_masks], h,
  File "/media/hdd0/Code/mmdetection/mmdet/datasets/pipelines/loading.py", line 271, in process_polygons
    if len(polygon) % 2 == 0 and len(polygon) >= 6:
TypeError: len() of unsized object
```

**Comment by xvjiarui** [comment]
Hi @zeakey 
It has been fixed. You may re-open this issue if there is still a problem.
