### ISSUE TITLE
One Question about adding additional regression head

### ISSUE THREAD

**Issue by Cknex** [open-mmlab/mmdetection#3613]
Hello!
I'd like to add an additional regression head, to estimate the attribute of the detected object.
Currently, I have finished the dataset.py, it will insert an item in the annotation dict.  
I also changed collect keys in the configs.
How can I change the piplines/formating.py?
Do I need to change the ToDataContainer and DefaultFormatBundle?

I think this is a common problem. Is there any tutorials?

**Comment by ZwwWayne** [comment]
You might need to change the DefaultFormatBundle if you have some special keys but you do not need to modify ToDataContainer because you only need to modify some keys.

**Comment by Cknex** [comment]
`    def __call__(self, results):
        if 'img' in results:
            img = results['img']
            if len(img.shape) < 3:
                img = np.expand_dims(img, -1)
            img = np.ascontiguousarray(img.transpose(2, 0, 1))
            results['img'] = DC(to_tensor(img), stack=True)
        for key in ['proposals', 'gt_bboxes', 'gt_bboxes_ignore', 'gt_labels']:
            #print('a')
            if key not in results:
                continue
            results[key] = DC(to_tensor(results[key]))
        if 'gt_masks' in results:
            results['gt_masks'] = DC(results['gt_masks'], cpu_only=True)
        if 'gt_semantic_seg' in results:
            results['gt_semantic_seg'] = DC(
                to_tensor(results['gt_semantic_seg'][None, ...]), stack=True)
        if 'gt_3d_labels' in results:
            results['gt_3d_labels']['vp'] = DC(
                    to_tensor(results['gt_3d_labels']['vp']), stack=True)
            results['gt_3d_labels']['dir'] = DC(
                    to_tensor(results['gt_3d_labels']['dir']), stack=True)
            results['gt_3d_labels']['dim'] = DC(
                    to_tensor(results['gt_3d_labels']['dim']), stack=True)
            results['gt_3d_labels']['center'] = DC(
                    to_tensor(results['gt_3d_labels']['center']), stack=True)
            results['gt_3d_labels']['depth'] = DC(
                    to_tensor(results['gt_3d_labels']['depth']), stack=True)

        return results
`

**Comment by Cknex** [comment]
I modify DefaultFormatBundle into this:

`       def __call__(self, results):
        """Call function to transform and format common fields in results.
        Args:
            results (dict): Result dict contains the data to convert.
        Returns:
            dict: The result dict contains the data that is formatted with \
                default bundle.
        """

        if 'img' in results:
            img = results['img']
            # add default meta keys
            results = self._add_default_meta_keys(results)
            if len(img.shape) < 3:
                img = np.expand_dims(img, -1)
            img = np.ascontiguousarray(img.transpose(2, 0, 1))
            results['img'] = DC(to_tensor(img), stack=True)
        for key in ['proposals', 'gt_bboxes', 'gt_bboxes_ignore', 'gt_labels']:
            if key not in results:
                continue
            results[key] = DC(to_tensor(results[key]))
        if 'gt_masks' in results:
            results['gt_masks'] = DC(results['gt_masks'], cpu_only=True)
        if 'gt_semantic_seg' in results:
            results['gt_semantic_seg'] = DC(
                to_tensor(results['gt_semantic_seg'][None, ...]), stack=True)
        if 'gt_other' in results:
            results['gt_other']['a'] = DC(
                to_tensor(results['gt_other']['a']), stack=True)
        if 'gt_other' in results:
            results['gt_other']['b'] = DC(
                to_tensor(results['gt_other']['b']), stack=True)
        return results

`

But I always get error:

Traceback (most recent call last):
  File "tools/train.py", line 174, in <module>
    main()
  File "tools/train.py", line 170, in main
    meta=meta)
  File "/disk0/code/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 82, in collate
    for key in batch[0]
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 82, in <dictcomp>
    for key in batch[0]
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 82, in collate
    for key in batch[0]
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 82, in <dictcomp>
    for key in batch[0]
  File "/home/celiu/anaconda3/envs/fir/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 41, in collate
    assert ndim > batch[i].pad_dims
AssertionError

Do you have any suggestions?
Thank you very much!

**Comment by xvjiarui** [comment]
What is the dimension of your `gt_other`? 
You may set `stack=False`.

**Comment by Cknex** [comment]
Thanks! I have given up...
