### ISSUE TITLE
ImportError: /home/user/miniconda3/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

### ISSUE THREAD

**Issue by anthony23122** [open-mmlab/mmdetection#3620]
I tried to run the model by using 

`python demo/image_demo.py demo/demo.jpg configs/faster_rcnn_r50_fpn_1x_coco.py     checkpoints/cascade_mask_rcnn_x101_64x4d_fpn_20e_coco_20200512_161033-bdb5126a.pth --device cpu`

But it turned out to show

`Traceback (most recent call last):
  File "demo/image_demo.py", line 3, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result_pyplot
  File "/home/user/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/user/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIAlign, RoIPool
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/user/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/user/miniconda3/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE`

when i type the code below
`python mmdet/utils/collect_env.py`

It shows
`Traceback (most recent call last):
  File "mmdet/utils/collect_env.py", line 64, in <module>
    for name, val in collect_env().items():
  File "mmdet/utils/collect_env.py", line 57, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/user/miniconda3/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 10, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/user/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/user/miniconda3/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE`

I don't know if there is compiling error or something

My set up are like this:
Ubuntu18.04
python 3.7.4
gcc 7.5.0 
pytorch 1.4.0
addict-2.2.1
mvcc-full-1.0.4
yapf-0.30.0
mmdet 2.3.0rc0
cuda10.0
nvidia drive 4.4.0

**Comment by hellock** [comment]
How did you install pytorch and mmcv?

**Comment by ZwwWayne** [comment]
The [trouble shooting doc](https://mmdetection.readthedocs.io/en/latest/trouble_shooting.html#trouble-shooting) may do some help. The bug of the undefined symbol seems to be related to the incompatibility between mmcv and pytorch. For example, the extension is compiled by Pytorch 1.3 but used in Pytorch 1.5. You need to re-compile/re-install mmcv-full in the environment.

**Comment by anthony23122** [comment]
Thank you all. I had solved the problem by reinstalling mmcv and pytorch
