### ISSUE TITLE
Can't Evaluate a Model Trained With Pytorch 1.6 under Pytorch 1.4 env, but the opposite works

### ISSUE THREAD

**Issue by CMobley7** [open-mmlab/mmdetection#3636]
**Describe the bug**
When I train a model under MMDetection 2.3.0 with Pytorch 1.6 and Torchvision 0.7.0 using MMDetection's train.py script, I can't evaluate or run inference on said model if Pytorch and Torchvision are downgraded to 1.4 and 0.5.0 respectively. I don't believe this was an issue when downgrading from Pytorch 1.5 and Torchvision 0.6.1 to Pytorch 1.4 and Torchvision 0.5.0, but I'll recheck this. When I try to run evaluation using MMDetection test.py script, I receive the error below. Is this not possible and if so is there a way to make it possible? I can do the opposite, as in evaluate and perform inference using a model trained under Pytorch 1.4 and Torchvision 0.5.0 under an environment with Pytorch 1.6 and Torchvision 0.7.0. Thanks in advance!
 
```
Traceback (most recent call last):
  File "/podc/src/mmdet/tools/test.py", line 154, in <module>
    main()
  File "/podc/src/mmdet/tools/test.py", line 118, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 224, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 200, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f33dd0c0193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f33e04509eb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f33e0451c04 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c53a6 (0x7f342870a3a6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x7f34282db1c4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallDict + 0x35c (0x566ddc in /usr/bin/python3)
frame #6: /usr/bin/python3() [0x594b71]
frame #7: /usr/bin/python3() [0x54a325]
frame #8: /usr/bin/python3() [0x5517c1]
frame #9: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #10: /usr/bin/python3() [0x50a783]
frame #11: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #12: /usr/bin/python3() [0x507f24]
frame #13: _PyFunction_FastCallDict + 0x2e2 (0x509202 in /usr/bin/python3)
frame #14: /usr/bin/python3() [0x594b01]
frame #15: /usr/bin/python3() [0x54a17f]
frame #16: /usr/bin/python3() [0x5517c1]
frame #17: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x50a783]
frame #19: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #20: /usr/bin/python3() [0x507f24]
frame #21: /usr/bin/python3() [0x509c50]
frame #22: /usr/bin/python3() [0x50a64d]
frame #23: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #24: /usr/bin/python3() [0x507f24]
frame #25: /usr/bin/python3() [0x509c50]
frame #26: /usr/bin/python3() [0x50a64d]
frame #27: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #28: /usr/bin/python3() [0x507f24]
frame #29: /usr/bin/python3() [0x509c50]
frame #30: /usr/bin/python3() [0x50a64d]
frame #31: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #32: /usr/bin/python3() [0x509918]
frame #33: /usr/bin/python3() [0x50a64d]
frame #34: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x507f24]
frame #36: PyEval_EvalCode + 0x23 (0x50b053 in /usr/bin/python3)
frame #37: /usr/bin/python3() [0x634dd2]
frame #38: PyRun_FileExFlags + 0x97 (0x634e87 in /usr/bin/python3)
frame #39: PyRun_SimpleFileExFlags + 0x17f (0x63863f in /usr/bin/python3)
frame #40: Py_Main + 0x591 (0x6391e1 in /usr/bin/python3)
frame #41: main + 0xe0 (0x4b0dc0 in /usr/bin/python3)
frame #42: __libc_start_main + 0xe7 (0x7f34313e2b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #43: _start + 0x2a (0x5b26fa in /usr/bin/python3)

Traceback (most recent call last):
  File "/podc/src/mmdet/tools/test.py", line 154, in <module>
    main()
  File "/podc/src/mmdet/tools/test.py", line 118, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location='cpu')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 224, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/checkpoint.py", line 200, in _load_checkpoint
    checkpoint = torch.load(filename, map_location=map_location)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 527, in load
    with _open_zipfile_reader(f) as opened_zipfile:
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 224, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f6f4172d193 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1f5b (0x7f6f44abd9eb in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::string const&) + 0x64 (0x7f6f44abec04 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x6c53a6 (0x7f6f8cd773a6 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x2961c4 (0x7f6f8c9481c4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #5: _PyCFunction_FastCallDict + 0x35c (0x566ddc in /usr/bin/python3)
frame #6: /usr/bin/python3() [0x594b71]
frame #7: /usr/bin/python3() [0x54a325]
frame #8: /usr/bin/python3() [0x5517c1]
frame #9: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #10: /usr/bin/python3() [0x50a783]
frame #11: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #12: /usr/bin/python3() [0x507f24]
frame #13: _PyFunction_FastCallDict + 0x2e2 (0x509202 in /usr/bin/python3)
frame #14: /usr/bin/python3() [0x594b01]
frame #15: /usr/bin/python3() [0x54a17f]
frame #16: /usr/bin/python3() [0x5517c1]
frame #17: _PyObject_FastCallKeywords + 0x19c (0x5a9eec in /usr/bin/python3)
frame #18: /usr/bin/python3() [0x50a783]
frame #19: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #20: /usr/bin/python3() [0x507f24]
frame #21: /usr/bin/python3() [0x509c50]
frame #22: /usr/bin/python3() [0x50a64d]
frame #23: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #24: /usr/bin/python3() [0x507f24]
frame #25: /usr/bin/python3() [0x509c50]
frame #26: /usr/bin/python3() [0x50a64d]
frame #27: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #28: /usr/bin/python3() [0x507f24]
frame #29: /usr/bin/python3() [0x509c50]
frame #30: /usr/bin/python3() [0x50a64d]
frame #31: _PyEval_EvalFrameDefault + 0x1226 (0x50cfd6 in /usr/bin/python3)
frame #32: /usr/bin/python3() [0x509918]
frame #33: /usr/bin/python3() [0x50a64d]
frame #34: _PyEval_EvalFrameDefault + 0x444 (0x50c1f4 in /usr/bin/python3)
frame #35: /usr/bin/python3() [0x507f24]
frame #36: PyEval_EvalCode + 0x23 (0x50b053 in /usr/bin/python3)
frame #37: /usr/bin/python3() [0x634dd2]
frame #38: PyRun_FileExFlags + 0x97 (0x634e87 in /usr/bin/python3)
frame #39: PyRun_SimpleFileExFlags + 0x17f (0x63863f in /usr/bin/python3)
frame #40: Py_Main + 0x591 (0x6391e1 in /usr/bin/python3)
frame #41: main + 0xe0 (0x4b0dc0 in /usr/bin/python3)
frame #42: __libc_start_main + 0xe7 (0x7f6f95a4fb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #43: _start + 0x2a (0x5b26fa in /usr/bin/python3)

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
```

**Environment**
Included below is the environment I was using to evaluate. It should be the same as the one used to train under but just different versions of PyTorch and Torchvision.
```
sys.platform: linux
Python: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0,1: Tesla P100-PCIE-12GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.4.0
MMCV: 1.0.5
MMDetection: 2.3.0+68d860d
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2
```

**Comment by hellock** [comment]
PyTorch 1.6 switched the `torch.save()` serialization format.
