### ISSUE TITLE
Unable to run inference with array in "inference detector"

### ISSUE THREAD

**Issue by Fryman420** [open-mmlab/mmdetection#3637]
### Problem
3 days ago in mmdet/apis/inference.py, the hardcore loading was removed. 
I was able to run an inference with code like this:

`img = 'test.jpg'`
` img = mmcv.imread(img)`
` result = inference_detector(model, img)`

 Now I am unable to run it like this. `inference_detector()` only works with file-path now.
### See my error:
_Traceback (most recent call last):
  File "process_img.py", line 71, in <module>
    main()
  File "process_img.py", line 63, in main
    result = inference_detector(model, img)
  File "C:\Users\ASUS\mmdetection\mmdet\apis\inference.py", line 95, in inference_detector
    data = test_pipeline(data)
  File "C:\Users\ASUS\mmdetection\mmdet\datasets\pipelines\compose.py", line 40, in __call__
    data = t(data)
  File "C:\Users\ASUS\mmdetection\mmdet\datasets\pipelines\loading.py", line 59, in __call__
    img_bytes = self.file_client.get(filename)
  File "C:\Users\ASUS\Anaconda3\lib\site-packages\mmcv\fileio\file_client.py", line 294, in get
    return self.client.get(filepath)
  File "C:\Users\ASUS\Anaconda3\lib\site-packages\mmcv\fileio\file_client.py", line 185, in get
    with open(filepath, 'rb') as f:
OSError: [Errno 22] Invalid argument: '[[[ 9 51 16]\n  [ 9 51 16]\n  [12 53 19]\n  ...\n  [39 72 47]\n  [40 74 50]\n  [40 74 50]]\n\n [[10 52 17]\n  [10 52 17]\n  [13 54 20]\n  ...\n  [37 71 46]\n  [38 73 49]\n  [38 73 49]]\n\n [[17 56 23]\n  [17 56 23]\n  [18 56 24]\n  ...\n  [29 68 41]\n  [29 70 43]\n  [29 70 43]]\n\n ...\n\n [[41 68 62]\n  [41 68 62]\n  [40 70 63]\n  ...\n  [32 68 49]\n  [27 62 41]\n  [27 62 41]]\n\n [[42 69 64]\n  [42 69 64]\n  [47 77 69]\n  ...\n  [26 62 44]\n  [23 58 38]\n  [23 58 38]]\n\n [[42 70 64]\n  [42 70 64]\n  [48 78 71]\n  ...\n  [24 61 43]\n  [22 57 37]\n  [22 57 37]]]'_

**However, in the API documentation, it is written that this should work with an array.**

**Comment by mcdy143** [comment]
It is a bug introduced by #3611. They will fix it soon.

**Comment by hellock** [comment]
Already fixed in #3634
