### ISSUE TITLE
An issue on re-implementation with COCO2017 dataset

### ISSUE THREAD

**Issue by rose-jinyang** [open-mmlab/mmdetection#3660]
Hello
How are you?
Thanks for contributing this project.
I have searched related issues but cannot get the expected help.
The bug has not been fixed in the latest version.
I cloned the 2.3.0 version of this project and tried to train a model with COCO2017 dataset.
I used the following command.
python tools/train.py configs/detectors/detectors_htc_r50_1x_coco.py
I did not modify your code.
My environment is following.

sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GPU 0,1,2,3: Tesla V100-PCIE-16GB
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60                ,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-genc                ode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -D                USE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -W                extra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-c                ompare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-al                iasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=ol                d-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -                fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON,                 USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OP                ENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.4.0
MMCV: 1.0.5
MMDetection: 2.3.0+
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

I installed Pytorch 1.5.0 with conda command.
The environment variables are following.
![image](https://user-images.githubusercontent.com/47862419/91680737-c9119200-eb7e-11ea-9ce6-4904bf519ba4.png)
![image](https://user-images.githubusercontent.com/47862419/91680745-cf077300-eb7e-11ea-8986-edf20282d521.png)

The PYTHONPATH is empty.
The issue track is following:

Traceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 150, in main
    meta=meta)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 31, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/models/roi_heads/htc_roi_head.py", line 256, in forward_train
    loss_seg = self.semantic_head.loss(semantic_pred, gt_semantic_seg)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/Jin/mmdetection-2.3.0/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py", line 105, in loss
    loss_semantic_seg = self.criterion(mask_pred, labels)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 932, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 2317, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/vishwam/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 2117, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [2, 100, 152, 3]

Please let me know the reason of this issue asap.
Thanks

**Comment by RyanXLi** [comment]
Hi! We have not been able to reproduce your error on the current master. Please update your version and try again, thanks!
