### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by xuaiyishen2012** [open-mmlab/mmdetection#3661]
Traceback (most recent call last):
  File "tools/train.py", line 173, in <module>
    main()
  File "tools/train.py", line 169, in main
    meta=meta)
  File "/root/mmdetection-master/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/anaconda3/envs/python377/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/root/mmdetection-master/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by xvjiarui** [comment]
Hi @xuaiyishen2012 
Which config/cmd did you use?

**Comment by Polaris231** [comment]
hi,i'm facing the same error with you,but i don't know why. and could you tell me how did you solve this?thank you!

**Comment by Quebradawill** [comment]
I met the same error, could anyone help me?

**Comment by kaijieshi7** [comment]
我用自己重弄的json标签文件也遇到了这个问题，后来发现是我的json文件里面width和height没给值，通过_filter_imgs函数之后，vaild_inds输出是空。把这种相关的代码注释就好了。
