### ISSUE TITLE
pytorch2onnx: RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

### ISSUE THREAD

**Issue by ShidiDaisy** [open-mmlab/mmdetection#3662]
Hi,

I'm using the latest pytorch2onnx.py script to convert a faster r-cnn pytorch model that I download from here [https://github.com/open-mmlab/mmdetection/tree/master/configs/pascal_voc](url) to onnx, but I met this error:

```
/home/shidi/Documents/SmartParking/mmdetection/mmdet/core/bbox/transforms.py:110: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bboxes = bboxes.cpu().numpy()
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 170, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 58, in pytorch2onnx
    opset_version=opset_version)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 412, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/models/detectors/base.py", line 150, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/models/detectors/two_stage.py", line 199, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 255, in simple_test
    self.bbox_head.num_classes)
  File "/home/shidi/Documents/SmartParking/mmdetection/mmdet/core/bbox/transforms.py", line 110, in bbox2result
    bboxes = bboxes.cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```

If I have followed the instruction to change "bboxes = bboxes.cpu().numpy()" to "bboxes = bboxes.cpu().detach().numpy()", then I got this error:
```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 170, in <module>
    normalize_cfg=normalize_cfg)
  File "tools/pytorch2onnx.py", line 58, in pytorch2onnx
    opset_version=opset_version)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/shidi/anaconda3/envs/python369/lib/python3.6/site-packages/torch/jit/__init__.py", line 415, in wrapper
    out_vars, _ = _flatten(outs)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type numpy.ndarray
```

Does anyone know how can I solve this issue? Or is there any other way to convert MMDetection trained pytorch model to onnx or caffe?

Thanks.

**Comment by xvjiarui** [comment]
Hi @ShidiDaisy 
ONNX is still an experimental feature. Only RetinaNet is supported for now.

**Comment by Fly-dream12** [comment]
Have you solved this problem? I also encounter this problem when trying to export the model to a onnx file. @ShidiDaisy

**Comment by sumitclearquote** [comment]
Hi @ShidiDaisy @Fly-dream12 . Facing the same issue. Did you solve this?
