### ISSUE TITLE
Freezing the backbone network will report an error

### ISSUE THREAD

**Issue by gjxgjxgjxgjx** [open-mmlab/mmdetection#3667]
I made the following changes in single_stage.py, and the result was an error.

        for v in self.backbone.parameters():
            v.requires_grad = False

        for v in self.bbox_head.parameters():
            v.requires_grad = False

Traceback (most recent call last):
  File "/home/ubuntu/gjx/mmdetection/tools/train.py", line 153, in <module>
    main()
  File "/home/ubuntu/gjx/mmdetection/tools/train.py", line 149, in main
    meta=meta)
  File "/home/ubuntu/gjx/mmdetection/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 43, in train
    self.call_hook('after_train_iter')
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 282, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 21, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/anaconda3/envs/mmdet21/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by xvjiarui** [comment]
Hi @gjxgjxgjxgjx 
In your modification, all parameters will have no grad. So BP can't be complete. You may freeze the backbone only.

**Comment by gjxgjxgjxgjx** [comment]
@xvjiarui What should I do if I only want to train the neck and freeze the backbone and head?

**Comment by yuzhj** [comment]
if you want to train the neck, you cannot freeze the head

**Comment by xvjiarui** [comment]
Hi @gjxgjxgjxgjx 
As @yuzhj said, there is no loss on neck directly. So if you would like to train the neck, you must train the head also.
