### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by kinredon** [open-mmlab/mmdetection#368]
I have using this command:

`./tools/dist_train.sh configs/steel_cascade_rcnn_r101_fpn_1x.py 2`

but it does not run sucessfully and occurs error:

```
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 65, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmdet/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmdet/apis/env.py", line 29, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 65, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmdet/apis/env.py", line 16, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/youedata/dengjinhong/anaconda3/envs/pytorch/lib/python3.6/site-packages/mmdet/apis/env.py", line 29, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
```

**Comment by qpoisson** [comment]
It looks like num_gpus is zero in your case. You may check the return of  torch.cuda.is_available() in python.
