### ISSUE TITLE
'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by jshuzi** [open-mmlab/mmdetection#3698]
while i run the command: python tools/test.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --show, an AttributeError occurred :'list' object has no attribute 'shape', details are shown below:
  File "tools/test.py", line 201, in <module>
    main()
  File "tools/test.py", line 174, in main
    args.show_score_thr)
  File "/home/jshuzi/mmdetection/mmdet/apis/test.py", line 51, in single_gpu_test
    score_thr=show_score_thr)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 303, in show_result
    for i, bbox in enumerate(bbox_result)
  File "/home/jshuzi/mmdetection/mmdet/models/detectors/base.py", line 303, in <listcomp>
    for i, bbox in enumerate(bbox_result)
AttributeError: 'list' object has no attribute 'shape'
i wonder whether i should change the bbox from list to array?

**Comment by baibaidedongdong** [comment]
I meet same question in runing"tools/test.py configs/libra_rcnn/libra_faster_rcnn_r101_fpn_1x_coco.py work_dirs/libra_faster_rcnn_r101_fpn_1x_coco/epoch_12.pth --show "
but I did't meet this question when I test other model ,

**Comment by noslacktome** [comment]
I also encountered this problem. 
I tried both models faster_rcnn and casacade_rcnn at the same time, and both encountered this problem. I tried to change the bbox from list to array, but it reported an error: 
Traceback (most recent call last):
  File "tools/test.py", line 201, in <module>
    main()
  File "tools/test.py", line 174, in main
    args.show_score_thr)
  File "/media/user/1T_DISK/lost+found/lyd/mmdetection-master/mmdet/apis/test.py", line 51, in single_gpu_test
    score_thr=show_score_thr)
  File "/media/user/1T_DISK/lost+found/lyd/mmdetection-master/mmdet/models/detectors/cascade_rcnn.py", line 37, in show_result
    return super(CascadeRCNN, self).show_result(data, result, **kwargs)
  File "/media/user/1T_DISK/lost+found/lyd/mmdetection-master/mmdet/models/detectors/base.py", line 338, in show_result
    out_file=out_file)
  File "/home/user/anaconda3/envs/lydmmdet/lib/python3.7/site-packages/mmcv/visualization/image.py", line 119, in imshow_det_bboxes
    assert bboxes.shape[0] == labels.shape[0]
AssertionError
