### ISSUE TITLE
one class detection error using Retinanet 

### ISSUE THREAD

**Issue by guiyuliu** [open-mmlab/mmdetection#3739]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I generate json file like coco data set which only has one class ， the class name is ‘’obstacle’
I want to train retinanet to detect。It seems It can run  but saving checkpoint at 1 epoch at once and have problem with eval.  

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=4,5,6,7 ./tools/dist_train.sh configs/retinanet/retinanet_r50_fpn_2x_coco.py 4

```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

3. What dataset did you use?

all the same with cocodataset  except the class names
 ```
dataset_type = 'CocoDataset'
data_root = '/ssd/nuscenes/'

class_names = ['obstacle']
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_train.coco.json',
        img_prefix=data_root,
        pipeline=train_pipeline,
        classes=class_names
    ),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_val.coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline,
        classes=class_names
    ),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_val.coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline,
        classes=class_names
    ))
evaluation = dict(interval=1, metric='bbox')
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```

2020-09-11 07:48:10,182 - mmdet - INFO - Start running, host: root@ca651b051d70, work_dir: /home/repo/mmdetection/work_dirs/retinanet_r50_fpn_2x_coco
2020-09-11 07:48:10,183 - mmdet - INFO - workflow: [('train', 1)], max: 18 epochs
index created!
2020-09-11 07:48:24,700 - mmdet - INFO - Saving checkpoint at 1 epochs
completed: 0, elapsed: 0s

Traceback (most recent call last):
  File "./tools/train.py", line 174, in <module>
    main()
  File "./tools/train.py", line 170, in main
    meta=meta)
  File "/home/repo/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 46, in train
    self.call_hook('after_train_epoch')
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 298, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/repo/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 132, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/repo/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 79, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/repo/mmdetection/mmdet/datasets/coco.py", line 416, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/repo/mmdetection/mmdet/datasets/coco.py", line 361, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/repo/mmdetection/mmdet/datasets/coco.py", line 292, in results2json
    if isinstance(results[0], list):
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/anaconda3/envs/nuscenes/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/nuscenes/bin/python', '-u', './tools/train.py', '--local_rank=3', 'configs/retinanet/retinanet_r50_fpn_2x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by RyanXLi** [comment]
Hi! The problem would most likely be in the object category of your custom dataset (i.e. obstacle). You may need to inherit coco.py and also change the config file to modify all the class number and class names. You can refer to this [tutorial](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html) for more information.

**Comment by guiyuliu** [comment]
> Hi! The problem would most likely be in the object category of your custom dataset (i.e. obstacle). You may need to inherit coco.py and also change the config file to modify all the class number and class names. You can refer to this [tutorial](https://mmdetection.readthedocs.io/en/latest/tutorials/new_dataset.html) for more information.

this is my dataset
```
from .coco import CocoDataset
from .builder import DATASETS

@DATASETS.register_module()
class NusDataset(CocoDataset):
    CLASSES = ('obstacle')
```

this is my config file, the class_names has been changed and add it to data dict
```
dataset_type = 'NusDataset'
data_root = '/ssd/nuscenes/'
class_names = ['obstacle'] 
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_train.coco.json',
        img_prefix=data_root,
        pipeline=train_pipeline,
        **classes=class_names**
    ),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_val.coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline,
        **classes=class_names**
    ),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'FRONT_CAM_obstacle_infos_val.coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline,
        classes=class_names
    ))
evaluation = dict(interval=4, metric='bbox')

```

I also changed th num_classes = 1 in retinanet_r50_fpn.py

it still has these problems

**Comment by RyanXLi** [comment]
It seems that your dataset length is recognized as 0. You may need to check your annotation file.

**Comment by guiyuliu** [comment]
> It seems that your dataset length is recognized as 0. You may need to check your annotation file.

thank you very much , it seems that when  you only have one class,  it is no need for  custom classes . it will get the subset.
which in my code class_names = ['obstacle']  should be deleted.
