### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by JiangniHIT** [open-mmlab/mmdetection#3750]
Traceback (most recent call last):
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/models/detectors/reppoints_v2_detector.py", line 35, in forward_train    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/models/dense_heads/reppoints_v2_head.py", line 861, in loss    label_channels=label_channels)
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/models/dense_heads/reppoints_v2_head.py", line 585, in get_targets
    unmap_outputs=unmap_outputs)
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/core/utils/misc.py", line 54, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/models/dense_heads/reppoints_v2_head.py", line 480, in _point_target_single
    assign_result = assigner.assign(proposals, num_level_proposals_inside, gt_bboxes, gt_bboxes_ignore, gt_labels)
  File "/mnt/hdfs-data-5/data/ni.jiang/rep-dev/mmdet/core/bbox/assigners/atss_assigner.py", line 154, in assign
    overlaps_inf[index] = overlaps.t().contiguous().view(-1)[index]
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /tmp/pip-req-build-4baxydiv/c10/cuda/CUDACachingAllocator.cpp:569)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6d (0x7f254bef5e7d in /home/use
frame #1: <unknown function> + 0x21a83 (0x7f254bf2ba83 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f254bee122d in /home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x10b6a9 (0x7f254c0546a9 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x4b1abd (0x7f254c3faabd in /home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x1809da (0x561210d509da in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #7: <unknown function> + 0xfc039 (0x561210ccc039 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #8: <unknown function> + 0xfa938 (0x561210cca938 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #9: <unknown function> + 0xfa938 (0x561210cca938 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #10: <unknown function> + 0xfa348 (0x561210cca348 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #11: <unknown function> + 0xfadd8 (0x561210ccadd8 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #12: <unknown function> + 0xfadec (0x561210ccadec in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #13: <unknown function> + 0xfadec (0x561210ccadec in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #14: <unknown function> + 0xfadec (0x561210ccadec in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #15: <unknown function> + 0xfadec (0x561210ccadec in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #16: <unknown function> + 0xfadec (0x561210ccadec in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #17: <unknown function> + 0x12adc7 (0x561210cfadc7 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #18: PyDict_SetItemString + 0x89 (0x561210d07889 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #19: PyImport_Cleanup + 0x9c (0x561210d7c80c in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #20: Py_FinalizeEx + 0x64 (0x561210df0d04 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #21: <unknown function> + 0x23232e (0x561210e0232e in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #22: _Py_UnixMain + 0x3c (0x561210e0267c in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)
frame #23: __libc_start_main + 0xf5 (0x7f2556056445 in /lib64/libc.so.6)
frame #24: <unknown function> + 0x1d7101 (0x561210da7101 in /home/users/ni.jiang/anaconda3/envs/open-mmlab/bin/python)

Traceback (most recent call last):
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/users/ni.jiang/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)

**Comment by ZwwWayne** [comment]
Duplicate https://github.com/open-mmlab/mmdetection/issues/3742
