### ISSUE TITLE
Assertion error on multi image (batch) testing

### ISSUE THREAD

**Issue by uttaransinha** [open-mmlab/mmdetection#3752]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version. (Using MMDetection 2.4.0)

**Describe the bug**
The following error is displayed when evaluating retinanet on batch-size of 2 per gpu. Works as expected with batch-size 1. 
assert features.dim() == 4 and features.size(0) == 1
AssertionError
File : mmcv/lib/python3.7/site-packages/mmcv/ops/masked_conv.py", line 31, in forward

**Reproduction**
1. What command or script did you run?
```
CUDA_VISIBLE_DEVICES=0,1,2,3 tools/dist_test.sh my_retinanet.py \ epoch_1.pth 4 --eval bbox
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes. I added the following line after line 148 in tools/test.py
samples_per_gpu = 2
3. What dataset did you use?
Custom MSCOCO Dataset.
**Environment**
Python 3.7 with Pytorch 1.4.0 GPU
1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.0b3 (default, Mar 30 2018, 04:35:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: GeForce GTX 1080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0
OpenCV: 4.4.0
MMCV: 1.1.1
MMDetection: 2.4.0+11b1ef8
MMDetection Compiler: GCC 7.3
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
          Using pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
Traceback (most recent call last):
  File "../tools/test.py", line 206, in <module>
    main()
  File "../tools/test.py", line 186, in main
    args.gpu_collect)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/apis/test.py", line 96, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/models/detectors/single_stage.py", line 112, in simple_test
    outs = self.bbox_head(x)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 243, in forward
    return multi_apply(self.forward_single, feats)
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/core/utils/misc.py", line 54, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/uttaran/Small_Object_Detection/mmcv/mmdetection/mmdet/models/dense_heads/ga_retina_head.py", line 107, in forward_single
    cls_score = self.retina_cls(cls_feat, mask)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/mmcv/ops/masked_conv.py", line 110, in forward
    self.padding)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/mmcv/ops/masked_conv.py", line 31, in forward
    assert features.dim() == 4 and features.size(0) == 1
AssertionError
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/uttaran/Small_Object_Detection/mmcv/bin/python', '-u', '../tools/test.py', '--local_rank=3', 'retinanet.py', 'epoch_1.pth', '--launcher', 'pytorch', '--eval', 'bbox']' returned non-zero exit status 1.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
```
  File "/home/uttaran/Small_Object_Detection/mmcv/lib/python3.7/site-packages/mmcv/ops/masked_conv.py", line 31, in forward
    assert features.dim() == 4 and features.size(0) == 1
```
Just as the error suggests, `masked_conv` doesn't support the case when batch size > 1.
