### ISSUE TITLE
No module named 'mmdet.ops.dcn'

### ISSUE THREAD

**Issue by Re-bin** [open-mmlab/mmdetection#3760]
Traceback (most recent call last):
  File "demo_vimeo.py", line 14, in <module>
    import src.layers as layers
  File "/content/drive/My Drive/Colab Notebooks/FeatureFlow/src/layers.py", line 1, in <module>
    import src.model as model
  File "/content/drive/My Drive/Colab Notebooks/FeatureFlow/src/model.py", line 6, in <module>
    from mmdet.ops.dcn.deform_conv import DeformConv, ModulatedDeformConv, _pair, modulated_deform_conv
ModuleNotFoundError: No module named 'mmdet.ops.dcn'

**Comment by bharath-07** [comment]
from mmcv.ops import DeformConv, ModulatedDeformConv, _pair, modulated_deform_conv , should fix the problem. 
Also ensure you are using the latest mmdetection version.
