### ISSUE TITLE
UnboundLocalError: local variable 'pos_inds_temp' referenced before assignment

### ISSUE THREAD

**Issue by wlgcqh** [open-mmlab/mmdetection#3769]
./tools/dist_train.sh configs/paa/paa_r50_fpn_1x_coco.py 2
2020-09-15 17:14:42,327 - mmdet - INFO - Epoch [1][50/7330]	lr: 9.890e-04, eta: 3 days, 18:50:42, time: 3.720, data_time: 2.000, memory: 11812, loss_cls: 0.9872, loss_bbox: 0.6724, loss_iou: 0.3482, loss: 2.0078
^@2020-09-15 17:16:09,193 - mmdet - INFO - Epoch [1][100/7330]	lr: 1.988e-03, eta: 2 days, 18:35:57, time: 1.738, data_time: 0.023, memory: 11813, loss_cls: 0.8489, loss_bbox: 0.6244, loss_iou: 0.3464, loss: 1.8196
^@^@2020-09-15 17:17:37,479 - mmdet - INFO - Epoch [1][150/7330]	lr: 2.987e-03, eta: 2 days, 10:43:03, time: 1.764, data_time: 0.023, memory: 11815, loss_cls: 0.8256, loss_bbox: 0.5487, loss_iou: 0.3417, loss: 1.7161
^@2020-09-15 17:19:06,118 - mmdet - INFO - Epoch [1][200/7330]	lr: 3.986e-03, eta: 2 days, 6:49:09, time: 1.773, data_time: 0.024, memory: 11815, loss_cls: 0.7054, loss_bbox: 0.5139, loss_iou: 0.3378, loss: 1.5571
^@^@2020-09-15 17:20:33,403 - mmdet - INFO - Epoch [1][250/7330]	lr: 4.985e-03, eta: 2 days, 4:20:27, time: 1.747, data_time: 0.025, memory: 11815, loss_cls: 0.6756, loss_bbox: 0.4699, loss_iou: 0.3315, loss: 1.4770
^@2020-09-15 17:22:01,437 - mmdet - INFO - Epoch [1][300/7330]	lr: 5.984e-03, eta: 2 days, 2:44:20, time: 1.761, data_time: 0.023, memory: 11815, loss_cls: 0.6212, loss_bbox: 0.4469, loss_iou: 0.3261, loss: 1.3942
^@^@2020-09-15 17:23:27,824 - mmdet - INFO - Epoch [1][350/7330]	lr: 6.983e-03, eta: 2 days, 1:28:12, time: 1.727, data_time: 0.023, memory: 11815, loss_cls: 0.6295, loss_bbox: 0.4245, loss_iou: 0.3189, loss: 1.3729
^@2020-09-15 17:24:57,139 - mmdet - INFO - Epoch [1][400/7330]	lr: 7.982e-03, eta: 2 days, 0:41:41, time: 1.787, data_time: 0.024, memory: 11816, loss_cls: 0.6668, loss_bbox: 0.4194, loss_iou: 0.3183, loss: 1.4045
Traceback (most recent call last):
  File "./tools/train.py", line 177, in <module>
    main()
  File "./tools/train.py", line 173, in main
    meta=meta)
  File "/home/beiqi.qh/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/beiqi.qh/mmcv/mmcv/runner/epoch_based_runner.py", line 123, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/beiqi.qh/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/home/beiqi.qh/mmcv/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/beiqi.qh/mmdetection/mmdet/models/detectors/base.py", line 234, in train_step
    losses = self(**data)
  File "/home/beiqi.qh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/beiqi.qh/mmdetection/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/beiqi.qh/mmdetection/mmdet/models/detectors/base.py", line 168, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/beiqi.qh/mmdetection/mmdet/models/detectors/single_stage.py", line 94, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/home/beiqi.qh/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/beiqi.qh/mmdetection/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/beiqi.qh/mmdetection/mmdet/models/dense_heads/paa_head.py", line 138, in loss
    anchor_list,
  File "/home/beiqi.qh/mmdetection/mmdet/core/utils/misc.py", line 54, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/beiqi.qh/mmdetection/mmdet/models/dense_heads/paa_head.py", line 321, in paa_reassign
    gmm_assignment, scores, pos_inds_gmm)
  File "/home/beiqi.qh/mmdetection/mmdet/models/dense_heads/paa_head.py", line 366, in gmm_separation_scheme
    return pos_inds_temp, ignore_inds_temp
UnboundLocalError: local variable 'pos_inds_temp' referenced before assignment
Traceback (most recent call last):
  File "/home/beiqi.qh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/beiqi.qh/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/beiqi.qh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/beiqi.qh/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/beiqi.qh/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/paa/paa_r50_fpn_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by ZwwWayne** [comment]
See this [line](https://github.com/open-mmlab/mmdetection/blob/11b1ef830aa7c8c054d8b5346fe0966e643d473c/mmdet/models/dense_heads/paa_head.py#L362) when there is no foreground, `pos_inds_temp` and `ignore_inds_temp` will not be created.

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/3688
