### ISSUE TITLE
Mask Scoring R-CNN - Model crash before commencing training phase

### ISSUE THREAD

**Issue by ecm200** [open-mmlab/mmdetection#3825]
### **The issue**
On running training using different variants of Mask Scoring R-CNN, an error is encountered which causes the training to crash. The traceback is supplied below.

The error has been replicated for backbones: ResNet50, ResNet101, ResNext101 32x4d and ResNeXt 64x4d.

This occurs when using either single or multiple GPUs on a single node, with the same error resulting.

The dataset is a custom COCO type which is detailed in #3796 . Successful training has been achieved using this dataset using different variants of the Mask R-CNN framework with both ResNet and ResNeXt backbones.

The model configuration was a minimally adapted version of the default model specification for Mask Scoring architecture for the COCO dataset. The model configuration dictionary was specified as below, for a ResNeXt101 32x4d Mask Scoring R-CNN).

#### Question

I have been having issues with evaluation metrics of the custom dataset in question, in particular with the segmentation mask metrics calculations using the COCO dataset type evaluation tool. This was reported in #3796 , is there a potential link here with the issue relating to the segmentation mask ground truths?

#### Traceback

``` python
2020-09-22 16:00:33,619 - mmdet - INFO - workflow: [('train', 1), ('val', 1)], max: 30 epochs
Traceback (most recent call last):
  File "MMDetection_Model_Train__003.py", line 242, in <module>
    main()
  File "MMDetection_Model_Train__003.py", line 238, in main
    meta=meta)
  File "/datadrive/drive1/Projects/WillowTree/Repo/advanced_seg/MMDetection_experiments/mmdetection_morphologi_train.py", line 225, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/edmorris/Git/mmcv/mmcv-0.5.1/mmcv/runner/runner.py", line 397, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/edmorris/Git/mmcv/mmcv-0.5.1/mmcv/runner/runner.py", line 296, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/datadrive/drive1/Projects/WillowTree/Repo/advanced_seg/MMDetection_experiments/mmdetection_morphologi_train.py", line 78, in batch_processor
    losses = model(**data)
  File "/anaconda/envs/py37_mmdetection_003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/py37_mmdetection_003/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/anaconda/envs/py37_mmdetection_003/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/detectors/base.py", line 148, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/detectors/two_stage.py", line 158, in forward_train
    **kwargs)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/roi_heads/standard_roi_head.py", line 125, in forward_train
    gt_masks, img_metas)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/roi_heads/mask_scoring_roi_head.py", line 44, in _mask_forward_train
    mask_results['mask_targets'], self.train_cfg)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/roi_heads/mask_heads/maskiou_head.py", line 135, in get_targets
    area_ratios = torch.cat(list(area_ratios))
  File "/home/edmorris/Git/mmdetection_new_backup/mmdet/models/roi_heads/mask_heads/maskiou_head.py", line 168, in _get_area_ratio
    ratio = gt_mask_in_proposal.areas[0] / (
IndexError: index 0 is out of bounds for axis 0 with size 0

```

#### Model Configuration Dictionary

``` python
{'checkpoint_config': {'interval': 1, 'type': 'CheckpointHook'},
 'classes': ['particle'],
 'data': {'imgs_per_gpu': 2,
          'samples_per_gpu': 2,
          'test': {'ann_file': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/annotations/valid_coco_changed_removed.json',
                   'classes': ['particle'],
                   'img_prefix': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/valid/',
                   'pipeline': [{'type': 'LoadMorphologiSynImage'},
                                {'flip': False,
                                 'img_scale': (1296, 972),
                                 'transforms': [{'keep_ratio': True,
                                                 'type': 'Resize'},
                                                {'mean': [123.675,
                                                          116.28,
                                                          103.53],
                                                 'std': [58.395, 57.12, 57.375],
                                                 'to_rgb': True,
                                                 'type': 'Normalize'},
                                                {'keys': ['img'],
                                                 'type': 'ImageToTensor'},
                                                {'keys': ['img'],
                                                 'type': 'Collect'}],
                                 'type': 'MultiScaleFlipAug'}],
                   'type': 'MorphologiDataset'},
          'train': {'ann_file': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/annotations/train_coco_changed_removed.json',
                    'classes': ['particle'],
                    'img_prefix': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/train/',
                    'pipeline': [{'type': 'LoadMorphologiSynImage'},
                                 {'type': 'LoadAnnotations',
                                  'with_bbox': True,
                                  'with_mask': True},
                                 {'img_scale': (1296, 972),
                                  'keep_ratio': True,
                                  'type': 'Resize'},
                                 {'mean': [123.675, 116.28, 103.53],
                                  'std': [58.395, 57.12, 57.375],
                                  'to_rgb': True,
                                  'type': 'Normalize'},
                                 {'type': 'DefaultFormatBundle'},
                                 {'keys': ['img',
                                           'gt_bboxes',
                                           'gt_labels',
                                           'gt_masks'],
                                  'type': 'Collect'}],
                    'type': 'MorphologiDataset'},
          'val': {'ann_file': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/annotations/valid_coco_changed_removed.json',
                  'classes': ['particle'],
                  'img_prefix': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/valid/',
                  'pipeline': [{'type': 'LoadMorphologiSynImage'},
                               {'flip': False,
                                'img_scale': (1296, 972),
                                'transforms': [{'keep_ratio': True,
                                                'type': 'Resize'},
                                               {'mean': [123.675,
                                                         116.28,
                                                         103.53],
                                                'std': [58.395, 57.12, 57.375],
                                                'to_rgb': True,
                                                'type': 'Normalize'},
                                               {'keys': ['img'],
                                                'type': 'ImageToTensor'},
                                               {'keys': ['img'],
                                                'type': 'Collect'}],
                                'type': 'MultiScaleFlipAug'}],
                  'type': 'MorphologiDataset'},
          'workers_per_gpu': 2},
 'data_dir': 'cuboidal_v1p3_images/',
 'data_root': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/cuboidal_v1p3_images/',
 'data_root_dir': '/datadrive/drive0/willow_tree_synthetic/mpdsim/train_test_coco_fmt/',
 'dataset_type': 'MorphologiDataset',
 'dist_params': {'backend': 'nccl'},
 'evaluation': {'interval': 1, 'metric': ['bbox']},
 'gpu_ids': range(0, 1),
 'gpus': 4,
 'img_norm_cfg': {'mean': [123.675, 116.28, 103.53],
                  'std': [58.395, 57.12, 57.375],
                  'to_rgb': True},
 'load_from': None,
 'log_config': {'hooks': [{'type': 'TextLoggerHook'},
                          {'type': 'TensorboardLoggerHook'}],
                'interval': 50},
 'log_level': 'INFO',
 'lr_config': {'policy': 'step',
               'step': [24, 33],
               'warmup': 'linear',
               'warmup_iters': 500,
               'warmup_ratio': 0.001},
 'model': {'backbone': {'base_width': 4,
                        'depth': 101,
                        'frozen_stages': 1,
                        'groups': 32,
                        'norm_cfg': {'requires_grad': True, 'type': 'BN'},
                        'norm_eval': True,
                        'num_stages': 4,
                        'out_indices': (0, 1, 2, 3),
                        'style': 'pytorch',
                        'type': 'ResNeXt'},
           'neck': {'in_channels': [256, 512, 1024, 2048],
                    'num_outs': 5,
                    'out_channels': 256,
                    'type': 'FPN'},
           'pretrained': None,
           'roi_head': {'bbox_head': {'bbox_coder': {'target_means': [0.0,
                                                                      0.0,
                                                                      0.0,
                                                                      0.0],
                                                     'target_stds': [0.1,
                                                                     0.1,
                                                                     0.2,
                                                                     0.2],
                                                     'type': 'DeltaXYWHBBoxCoder'},
                                      'fc_out_channels': 1024,
                                      'in_channels': 256,
                                      'loss_bbox': {'beta': 1.0,
                                                    'loss_weight': 1.0,
                                                    'type': 'SmoothL1Loss'},
                                      'loss_cls': {'loss_weight': 1.0,
                                                   'type': 'CrossEntropyLoss',
                                                   'use_sigmoid': False},
                                      'num_classes': 1,
                                      'reg_class_agnostic': False,
                                      'roi_feat_size': 7,
                                      'type': 'Shared2FCBBoxHead'},
                        'bbox_roi_extractor': {'featmap_strides': [4,
                                                                   8,
                                                                   16,
                                                                   32],
                                               'out_channels': 256,
                                               'roi_layer': {'out_size': 7,
                                                             'sample_num': 0,
                                                             'type': 'RoIAlign'},
                                               'type': 'SingleRoIExtractor'},
                        'mask_head': {'conv_out_channels': 256,
                                      'in_channels': 256,
                                      'loss_mask': {'loss_weight': 1.0,
                                                    'type': 'CrossEntropyLoss',
                                                    'use_mask': True},
                                      'num_classes': 1,
                                      'num_convs': 4,
                                      'type': 'FCNMaskHead'},
                        'mask_iou_head': {'conv_out_channels': 256,
                                          'fc_out_channels': 1024,
                                          'in_channels': 256,
                                          'num_classes': 1,
                                          'num_convs': 4,
                                          'num_fcs': 2,
                                          'roi_feat_size': 14,
                                          'type': 'MaskIoUHead'},
                        'mask_roi_extractor': {'featmap_strides': [4,
                                                                   8,
                                                                   16,
                                                                   32],
                                               'out_channels': 256,
                                               'roi_layer': {'out_size': 14,
                                                             'sample_num': 0,
                                                             'type': 'RoIAlign'},
                                               'type': 'SingleRoIExtractor'},
                        'type': 'MaskScoringRoIHead'},
           'rpn_head': {'anchor_generator': {'ratios': [0.5, 1.0, 2.0],
                                             'scales': [4, 8, 16],
                                             'strides': [4, 8, 16, 32, 64],
                                             'type': 'AnchorGenerator'},
                        'bbox_coder': {'target_means': [0.0, 0.0, 0.0, 0.0],
                                       'target_stds': [1.0, 1.0, 1.0, 1.0],
                                       'type': 'DeltaXYWHBBoxCoder'},
                        'feat_channels': 256,
                        'in_channels': 256,
                        'loss_bbox': {'loss_weight': 1.0, 'type': 'L1Loss'},
                        'loss_cls': {'loss_weight': 1.0,
                                     'type': 'CrossEntropyLoss',
                                     'use_sigmoid': True},
                        'type': 'RPNHead'},
           'type': 'MaskScoringRCNN'},
 'optimizer': {'lr': 0.0025,
               'momentum': 0.9,
               'type': 'SGD',
               'weight_decay': 0.0001},
 'optimizer_config': {'grad_clip': None},
 'resume_from': None,
 'seed': 42,
 'test_cfg': {'rcnn': {'mask_thr_binary': 0.35,
                       'max_per_img': 500,
                       'nms': {'iou_thr': 0.5, 'type': 'nms'},
                       'score_thr': 0.05},
              'rpn': {'max_num': 1000,
                      'min_bbox_size': 0,
                      'nms_across_levels': False,
                      'nms_post': 1000,
                      'nms_pre': 1000,
                      'nms_thr': 0.7}},
 'test_pipeline': [{'type': 'LoadMorphologiSynImage'},
                   {'flip': False,
                    'img_scale': (1296, 972),
                    'transforms': [{'keep_ratio': True, 'type': 'Resize'},
                                   {'mean': [123.675, 116.28, 103.53],
                                    'std': [58.395, 57.12, 57.375],
                                    'to_rgb': True,
                                    'type': 'Normalize'},
                                   {'keys': ['img'], 'type': 'ImageToTensor'},
                                   {'keys': ['img'], 'type': 'Collect'}],
                    'type': 'MultiScaleFlipAug'}],
 'total_epochs': 36,
 'train_cfg': {'rcnn': {'assigner': {'ignore_iof_thr': -1,
                                     'match_low_quality': True,
                                     'min_pos_iou': 0.5,
                                     'neg_iou_thr': 0.5,
                                     'pos_iou_thr': 0.5,
                                     'type': 'MaxIoUAssigner'},
                        'debug': False,
                        'mask_size': 28,
                        'mask_thr_binary': 0.5,
                        'pos_weight': -1,
                        'sampler': {'add_gt_as_proposals': True,
                                    'neg_pos_ub': -1,
                                    'num': 512,
                                    'pos_fraction': 0.25,
                                    'type': 'RandomSampler'}},
               'rpn': {'allowed_border': -1,
                       'assigner': {'ignore_iof_thr': -1,
                                    'match_low_quality': True,
                                    'min_pos_iou': 0.3,
                                    'neg_iou_thr': 0.3,
                                    'pos_iou_thr': 0.7,
                                    'type': 'MaxIoUAssigner'},
                       'debug': False,
                       'pos_weight': -1,
                       'sampler': {'add_gt_as_proposals': False,
                                   'neg_pos_ub': -1,
                                   'num': 256,
                                   'pos_fraction': 0.5,
                                   'type': 'RandomSampler'}},
               'rpn_proposal': {'max_num': 2000,
                                'min_bbox_size': 0,
                                'nms_across_levels': False,
                                'nms_post': 2000,
                                'nms_pre': 4000,
                                'nms_thr': 0.7}},
 'train_pipeline': [{'type': 'LoadMorphologiSynImage'},
                    {'type': 'LoadAnnotations',
                     'with_bbox': True,
                     'with_mask': True},
                    {'img_scale': (1296, 972),
                     'keep_ratio': True,
                     'type': 'Resize'},
                    {'mean': [123.675, 116.28, 103.53],
                     'std': [58.395, 57.12, 57.375],
                     'to_rgb': True,
                     'type': 'Normalize'},
                    {'type': 'DefaultFormatBundle'},
                    {'keys': ['img', 'gt_bboxes', 'gt_labels', 'gt_masks'],
                     'type': 'Collect'}],
 'work_dir': 'advanced_seg/MMDetection_experiments/output/SGD/cuboidal_v1p3_images_4XGPU_DODParsV1_MaskScoringRCNN_ResNeXt101_FPN_23092020_134133',
 'workflow': [('train', 1), ('val', 1)]}
```

### **Reproduction**

The training script is a custom training script heavily based on the COCO tutorial script supplied with package.

#### Training Script Calls
The single node training is called using the following call:
```
python MMDetection_Model_Train_003.py
```

The multi-gpu training is called using the same script with the following call:

```
python -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 MMDetection_Model_Train__003.py --launcher pytorch --gpus 4
```

#### Training Script

``` python
import mmcv
from mmcv import Config, DictAction
from mmcv.runner import init_dist
import torch


from mmdet import __version__
#from mmdet.apis import set_random_seed, train_detector
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.utils import collect_env, get_root_logger

# import __main__ as main
import os
import random
import datetime 
import shutil
import copy
import time
from glob import glob
#from sklearn.model_selection import train_test_split
import albumentations as A
import numpy as np
import argparse

from mmdetection_morphologi_pipelines import LoadMorphologiSynImage
from mmdetection_morphologi_datasets import MorphologiDataset
from mmdetection_morphologi_train import set_random_seed, train_detector
from mmdetection_morphologi_hooks import ValidationCheckpointHook, TensorboardLoggerWithImagesHook
from mmdetection_morphologi_utils import save_pickle

BASE_DIR = '' # 'advanced_seg/MMDetection_experiments' # Base DIR specification for executing in debug mode
TESTING = False

def parse_args():
    parser = argparse.ArgumentParser(description='Train a detector')
    parser.add_argument('--config', help='train config file path', default=os.path.join(BASE_DIR,'configs_morph/mmdetection_morphologi_ms_rcnn_x101_32x4d_fpn_1x.py'))
    parser.add_argument('--work_dir', help='the dir to save logs and models', default=os.path.join(BASE_DIR,'output/SGD'))
    parser.add_argument('--workflow', type=int, help='Workflow type [1] train only, [2] train and validate every epoch', default=2)
    parser.add_argument('--job_name', help='name for output files and dirs', default='cuboidal_v1p3_images_4XGPU_DODParsV1_') #'spherical_v1_cuboidal_square_images_v1p1_combined_500_125_4536_')
    parser.add_argument(
        '--resume-from', help='the checkpoint file to resume from')
    parser.add_argument(
        '--validate',
        action='store_true',
        help='whether to evaluate the checkpoint during training', default=True)
    group_gpus = parser.add_mutually_exclusive_group()
    group_gpus.add_argument(
        '--gpus',
        type=int,
        help='number of gpus to use '
        '(only applicable to non-distributed training)')
    group_gpus.add_argument(
        '--gpu-ids',
        type=int,
        nargs='+',
        help='ids of gpus to use '
        '(only applicable to non-distributed training)')
    parser.add_argument('--seed', type=int, default=42, help='random seed') # Default is usually 42
    parser.add_argument(
        '--deterministic',
        action='store_true',
        help='whether to set deterministic options for CUDNN backend.')
    parser.add_argument(
        '--options', nargs='+', action=DictAction, help='arguments in dict')
    parser.add_argument(
        '--launcher',
        choices=['none', 'pytorch', 'slurm', 'mpi'],
        default='none',
        help='job launcher')
    parser.add_argument('--local_rank', type=int, default=0)
    parser.add_argument(
        '--autoscale-lr',
        action='store_true',
        help='automatically scale lr with the number of gpus',
        default=True) #Added by ECM as this should [always be used
    args = parser.parse_args()
    if 'LOCAL_RANK' not in os.environ:
        os.environ['LOCAL_RANK'] = str(args.local_rank)

    return args

def main():

    args = parse_args()
    
    # Output dir and job details
    if args.job_name[-1] == '_':
        job_name_preamble = args.job_name
    else:
        job_name_preamble = args.job_name + '_'

    #### CONFIG
    ## Get the Base Config
    cfg = Config.fromfile(args.config)


    ## Set up Config
    
    # Get additional keyword arguments for configuration
    if args.options is not None:
        cfg.merge_from_dict(args.options)

    # set cudnn_benchmark
    if cfg.get('cudnn_benchmark', False):
        torch.backends.cudnn.benchmark = True

    # Setup output dir and copy over the exection script, save copy of config and input arguments
    if args.work_dir is not None:
        if TESTING:
            output_base_dir = os.path.join(args.work_dir,'testing')
        else:
            output_base_dir = args.work_dir
    elif cfg.get('work_dir', None) is None:
        if TESTING:
            output_base_dir = os.path.join(args.work_dir,'output/testing')
        else:
            output_base_dir = os.path.join(BASE_DIR,'output')
    cfg.work_dir = os.path.join(output_base_dir,job_name_preamble+cfg.model.type+'_'+cfg.model.backbone.type+str(cfg.model.backbone.depth)+'_'+cfg.model.neck.type+'_'+datetime.datetime.now().strftime('%d%m%Y_%H%M%S'))
    os.makedirs(cfg.work_dir, exist_ok=True)
    # Save this file
    shutil.copyfile(__file__, os.path.join(cfg.work_dir,__file__.split('/')[-1]))
    # Save the input arguments
    args_out_path = os.path.join(cfg.work_dir,'args_in_dict.pkl')
    save_pickle(pkl_object=args.__dict__, fname=args_out_path)
    # Save the config to file
    cfg_out_path = os.path.join(cfg.work_dir,cfg.work_dir.split('/')[-1]+'.cfg')
    cfg_out = open(cfg_out_path, 'w')
    cfg_out.writelines(cfg.text)
    cfg_out.close()
    

    # init the logger before other steps
    timestamp = time.strftime('%Y%m%d_%H%M%S', time.localtime())
    log_file = os.path.join(cfg.work_dir, '{}.log'.format(timestamp))
    logger = get_root_logger(log_file=log_file, log_level=cfg.log_level)
    logger.info('Created output directory: {}'.format(cfg.work_dir))

    logger.info('Command line arguments passed to training script: ')
    for arg_key,arg_value in args.__dict__.items():
        logger.info('{} :: {}'.format(arg_key, arg_value))

    # Resume from previous iteration
    if args.resume_from is not None:
        cfg.resume_from = args.resume_from

    # Update the default number of GPUs if different from config.
    if args.gpu_ids is not None:
        cfg.gpu_ids = args.gpu_ids
    else:
        cfg.gpu_ids = range(1) if args.gpus is None else range(args.gpus)

    # Update the autoscaler with the number of GPUs if changed from default 8 gpus.
    # ECM Modified so it takes into account the actual mini-batch size, which is dependent on the number of gpus and the images per gpu.
    # It now scales with the default mini-batch of 8 gpus and 2 images per gpu (16), and changes in response to changes in both gpus and/or images per gpu.
    if args.autoscale_lr:
        _old_lr = cfg.optimizer['lr']
        # Custom LR modification
        cfg.optimizer['lr'] =cfg.optimizer['lr'] * (len(cfg.gpu_ids) * cfg.data.imgs_per_gpu) / (16)
        # Example LR modification
        #cfg.optimizer['lr'] = cfg.optimizer['lr'] * len(cfg.gpu_ids) / 8
        logger.info('Applying linear Learning Rate correction. LR changed from {} to {}'.format(_old_lr, cfg.optimizer['lr']))

    # init distributed env first, since logger depends on the dist info.
    if args.launcher == 'none':
        logger.info('Distributed environment has not been initialized.')
        distributed = False
    else:
        logger.info('Distributed environment initialised.')
        distributed = True
        init_dist(args.launcher, **cfg.dist_params)

    ## Set workflow overide
    # Just training or validation will be done through the evaluation hook.
    if (args.workflow == 1):# or (args.validate):
        cfg.workflow = [('train', 1)]
        logger.info('Setting workflow to train only {}'.format(cfg.workflow))
    # Run validation through the val() function.
    elif args.workflow == 2:
        cfg.workflow = [('train', 1), ('val', 1)]
        logger.info('Setting workflow to train and validate {}'.format(cfg.workflow))
    # Report if using COCO validation metrics.
    if args.validate:
        logger.info('COCO Validation will be performed after every {} training epoch(s) using metrics {}'.format(cfg.evaluation.interval, cfg.evaluation.metric))

    # init the meta dict to record some important information such as
    # environment info and seed, which will be logged
    meta = dict()
    # log env info
    env_info_dict = collect_env()
    env_info = '\n'.join([('{}: {}'.format(k, v))
                            for k, v in env_info_dict.items()])
    dash_line = '-' * 60 + '\n'
    logger.info('Environment info:\n' + dash_line + env_info + '\n' +
                dash_line)
    meta['env_info'] = env_info

    # log some basic info
    logger.info('Distributed training: {}'.format(distributed))
    logger.info('Config:\n{}'.format(cfg.text))

    # set random seeds
    if args.seed is not None:
        logger.info(f'Set random seed to {args.seed}, '
                    f'deterministic: {args.deterministic}')
        set_random_seed(args.seed, deterministic=args.deterministic)
    cfg.seed = args.seed
    meta['seed'] = args.seed

    save_pickle(pkl_object=cfg._cfg_dict, fname=os.path.join(cfg.work_dir,cfg.work_dir.split('/')[-1]+'_cfg.pkl'))
    
    model = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)

    datasets = [build_dataset(cfg.data.train)] #, build_dataset(cfg.data.val)]

    if len(cfg.workflow) == 2:
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.pipeline
        datasets.append(build_dataset(val_dataset))
    if cfg.checkpoint_config is not None:
        # save mmdet version, config file content and class names in
        # checkpoints as meta data
        cfg.checkpoint_config.meta = dict(
            mmdet_version=__version__,
            config=cfg.text,
            CLASSES=datasets[0].CLASSES)

    # Output configuration dictionary to pickle file
    save_pickle(pkl_object=cfg._cfg_dict, fname=os.path.join(cfg.work_dir,cfg.work_dir.split('/')[-1]+'_cfg.pkl'))

    # add an attribute for visualization convenience
    model.CLASSES = datasets[0].CLASSES
    train_detector(
        model,
        datasets,
        cfg,
        distributed=distributed,
        validate=args.validate,
        timestamp=timestamp,
        meta=meta)

if __name__ == '__main__':

    main()

```

### **Environment**

``` python
sys.platform: linux
Python: 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 15:27:18) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0,1,2,3: Tesla P40
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.5.1
MMDetection: 2.0.0+6603790
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1
```

**Comment by RyanXLi** [comment]
Hi! This seems like a problem with your custom dataset, please ensure your groundtruth mask is in your bbox such that the "gt_mask_in_proposal" in [this line](https://github.com/open-mmlab/mmdetection/blob/413207c54828a2d7c2274f69efce21a07d84a583/mmdet/models/roi_heads/mask_heads/maskiou_head.py#L165) does have an area.

**Comment by RyanXLi** [comment]
This issue is stale and closed.

**Comment by matthost** [comment]
You fix this? Seeing the same issue after converting my config to MMDet 3.x, my coco annotation file does have areas
