### ISSUE TITLE
ssl.SSLCertVerificationError

### ISSUE THREAD

**Issue by yongtaoge** [open-mmlab/mmdetection#3829]
```
2020-09-24 17:05:02,690 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe                                                               
Downloading: "https://openmmlab.oss-accelerate.aliyuncs.com/pretrain/third_party/resnet50_msra-5891d200.pth" to /home/zhengyi/.cache/torch/hub/checkpoints/resn
et50_msra-5891d200.pth                                                                                                                                         
Traceback (most recent call last):                                                                                                                             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 1350, in do_open                                                       
    encode_chunked=req.has_header('Transfer-encoding'))                                                                                                        
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 1277, in request                                                          
    self._send_request(method, url, body, headers, encode_chunked)                                                                                             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 1323, in _send_request                                                    
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                       
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 1272, in endheaders                                                       
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 1032, in _send_output                                                     
    self.send(msg)                                                                                                                                             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 972, in send                                                              
    self.connect()                                                                                                                                             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/http/client.py", line 1447, in connect                                                          
    server_hostname=server_hostname)                                                                                                                           
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/ssl.py", line 423, in wrap_socket                                                               
    session=session                                                                                                                                            
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/ssl.py", line 870, in _create                                                                   
    self.do_handshake()                                                                                                                                        
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/ssl.py", line 1139, in do_handshake                                                             
    self._sslobj.do_handshake()

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)         [0/3228]
                                                                         
During handling of the above exception, another exception occurred:    
                                                                       
Traceback (most recent call last):                                                                                                             
  File "tools/train.py", line 178, in <module>                                                                                                 
    main()                                                                                                                                     
  File "tools/train.py", line 152, in main                                                                                                        
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)                                                                                 
  File "/test/zhengyi/code/mmdetection/mmdet/models/builder.py", line 67, in build_detector                                                       
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))                                                                 
  File "/test/zhengyi/code/mmdetection/mmdet/models/builder.py", line 32, in build                                                                
    return build_from_cfg(cfg, registry, default_args)                                                                                         
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg                 
    return obj_cls(**args)                                                                                                                     
  File "/test/zhengyi/code/mmdetection/mmdet/models/detectors/retinanet.py", line 17, in __init__                                                 
    test_cfg, pretrained)                                                                                                                      
  File "/test/zhengyi/code/mmdetection/mmdet/models/detectors/single_stage.py", line 33, in __init__                                              
    self.init_weights(pretrained=pretrained)                                                                                                   
  File "/test/zhengyi/code/mmdetection/mmdet/models/detectors/single_stage.py", line 43, in init_weights                                          
    self.backbone.init_weights(pretrained=pretrained)                          
  File "/test/zhengyi/code/mmdetection/mmdet/models/backbones/resnet.py", line 600, in init_weights                                                            
    load_checkpoint(self, pretrained, strict=False, logger=logger)             
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint                          
    checkpoint = _load_checkpoint(filename, map_location)                      
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 207, in _load_checkpoint                         
    checkpoint = load_url_dist(model_url)                                      
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 111, in load_url_dist                            
    checkpoint = model_zoo.load_url(url, model_dir=model_dir)                  
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/hub.py", line 481, in load_state_dict_from_url                              
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)                                                                                     
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/hub.py", line 379, in download_url_to_file                                  
    u = urlopen(req)                   
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 222, in urlopen                                                        
    return opener.open(url, data, timeout)                                     
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 525, in open                                                           
    response = self._open(req, data)                                           
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 543, in _open                                                          
    '_open', req)                      
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 503, in _call_chain                                                    
    result = func(*args)               
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 1393, in https_open                                                    
    context=self._context, check_hostname=self._check_hostname)                
  File "/test/zhengyi/envs/miniconda3/envs/mmdet/lib/python3.7/urllib/request.py", line 1352, in do_open                                                       
    raise URLError(err)                
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

**Comment by yongtaoge** [comment]
Hi, When I download the pre-trained model, an SSL error occur. How can I avoid this problem?

**Comment by yongtaoge** [comment]
I can solve the problem by the following line:
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by golikeri** [comment]
> I can solve the problem by the following line:
> 
> ```
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```

Thanks! This worked for me

**Comment by behnamkamrani** [comment]
> I can solve the problem by the following line:
> 
> ```
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```

Add to which file?
