### ISSUE TITLE
KeyError: On training model using cascade_rcnn_hrnetv2p_w32_20e_coco.py 

### ISSUE THREAD

**Issue by Siddhijain16** [open-mmlab/mmdetection#3841]
Hi,
I am using cascade_rcnn_hrnetv2p_w32_20e_coco.py config file to train model on custom data set and got this error. how to fix  it? Please suggest.

[cascade_rcnn_hrnetv2p_w32_20e_coco.zip](https://github.com/open-mmlab/mmdetection/files/5286526/cascade_rcnn_hrnetv2p_w32_20e_coco.zip)

Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 154, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/usr/local/lib/python3.6/dist-packages/mmdet-2.4.0-py3.6.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/usr/local/lib/python3.6/dist-packages/mmdet-2.4.0-py3.6.egg/mmdet/datasets/custom.py", line 85, in _init_
    self.data_infos = self.get_subset_by_classes()
  File "/usr/local/lib/python3.6/dist-packages/mmdet-2.4.0-py3.6.egg/mmdet/datasets/coco.py", line 127, in get_subset_by_classes
    info = self.coco.load_imgs([i])[0]
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 265, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 265, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: 8

![image](https://user-images.githubusercontent.com/46879959/94338779-92f6ef00-0012-11eb-8d82-8ad446ce284e.png)

**Comment by ZwwWayne** [comment]
Hi @Siddhijain16 ,
Could you switch to use this PR https://github.com/open-mmlab/mmdetection/pull/3695  and try again? Some potential bugs are fixed in the PR, so maybe it also fixes yours.

**Comment by ZwwWayne** [comment]
#3695 has been merged into master, so you could also pull master and try now.
