### ISSUE TITLE
how can i train custom coco style dataset in mmdet v2.0?

### ISSUE THREAD

**Issue by YummyWaffle** [open-mmlab/mmdetection#3889]
Take training 'faster rcnn + resnet50 + fpn' as an example.

I modified:
1) configs/_base_/datasets/coco_detection.py  ---  add 'classes = ('tower')'
2) configs/_base_/models/faster_rcnn_r50_fpn.py  ---  edit 'num_classes=2'

then i train the model: python configs/python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py

The error appears:

Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/xjm/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.4.0-py3.7.egg/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by ZwwWayne** [comment]
classes = ('tower') -> classes = ('tower',)
num_classes = 2 -> num_classes = 1

**Comment by YummyWaffle** [comment]
> classes = ('tower') -> classes = ('tower',)
> num_classes = 2 -> num_classes = 1

thank you very much!

**Comment by tingfengwanxiao** [comment]
> > classes = ('tower') -> classes = ('tower',)
> > num_classes = 2 -> num_classes = 1
> 
> thank you very much!

Can you send me a copy of your Jason file? I also have only one category. I want to see if there is an error in Jason file. My email address: 1918139841@qq.com Thank you
