### ISSUE TITLE
How to use GIoU Loss 、 DIoU Loss in Cascade-rcnn?

### ISSUE THREAD

**Issue by wulongjian** [open-mmlab/mmdetection#3914]
Hello, I want train cascade-rcnn with GIoU or DIoU loss to replace  smooth L1 loss, here is my part of config file.
```python
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained=None,
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,  
        out_indices=(0, 1, 2, 3),  
        frozen_stages=1,  
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],  
        out_channels=256,
        num_outs=5),  # 输出的特征层的数量
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8], 
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=1.0)),

    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',  
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,  
            num_classes=5,  
            target_means=[0., 0., 0., 0.],  
            target_stds=[0.1, 0.1, 0.2, 0.2],  
            reg_class_agnostic=True, 
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
           # loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
            loss_bbox=dict(type='GIoULoss', loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=5,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            # loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
            loss_bbox=dict(type='GIoULoss', loss_weight=1.0)),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=5,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            # loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
            loss_bbox=dict(type='GIoULoss', loss_weight=1.0))
    ])
```

I just replace the SmoothL1Loss with GIoULoss in bbox_head, nothing else has changed, but I get the following error

```bash
Traceback (most recent call last):
  File "/home/wlj/urpc2020/underwater-object-detection/tools/train.py", line 125, in <module>
    main()
  File "/home/wlj/urpc2020/underwater-object-detection/tools/train.py", line 121, in main
    timestamp=timestamp)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/apis/train.py", line 133, in train_detector
    timestamp=timestamp)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/apis/train.py", line 319, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/apis/train.py", line 100, in batch_processor
    losses = model(**data)
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/detectors/base.py", line 138, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/detectors/cascade_rcnn.py", line 253, in forward_train
    loss_bbox = bbox_head.loss(cls_score, bbox_pred, *bbox_targets)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/bbox_heads/bbox_head.py", line 133, in loss
    reduction_override=reduction_override)
  File "/home/wlj/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/losses/iou_loss.py", line 325, in forward
    **kwargs)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/losses/utils.py", line 95, in wrapper
    loss = weight_reduce_loss(loss, weight, reduction, avg_factor)
  File "/home/wlj/urpc2020/underwater-object-detection/mmdet/models/losses/utils.py", line 40, in weight_reduce_loss
    loss = loss * weight
RuntimeError: The size of tensor a (31) must match the size of tensor b (4) at non-singleton dimension 1

Process finished with exit code 1
```
Could you give me some advice? Should I change some other configs?

**Comment by ZwwWayne** [comment]
There might still be incompatibilities between the box regression weight and the IoULosses. We will have a check on that. For a quick fix, you may change the dimension of the box regression weights accordingly.

**Comment by wulongjian** [comment]
thanks a lot. Finally I find this is because my mmdetection version is so old, I use `mmcv =0.4.3` and `mmdet = 1.0`, this verion is note complete the GIoU loss, when I use the latest version `mmdet=2.5`, it works well. The key code as followings:
We are in `mmdet/models/losses/iou_loss.py`
```
        if weight is not None and weight.dim() > 1:
            # TODO: remove this in the future
            # reduce the weight of shape (n, 4) to (n,) to match the
            # giou_loss of shape (n,)
            assert weight.shape == pred.shape
            weight = weight.mean(-1)
```
I will colse this issue.
