### ISSUE TITLE
pip install -v -e .

### ISSUE THREAD

**Issue by rouyalxy** [open-mmlab/mmdetection#3925]
Error when pip install -v -e . is running

Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-4wccl1sh
Created temporary directory: /tmp/pip-req-tracker-_t8j_d2f
Initialized build tracking at /tmp/pip-req-tracker-_t8j_d2f
Created build tracker: /tmp/pip-req-tracker-_t8j_d2f
Entered build tracker: /tmp/pip-req-tracker-_t8j_d2f
Created temporary directory: /tmp/pip-install-g_5l0s71
Obtaining file:///home/zxy/mmdetection
  Added file:///home/zxy/mmdetection to build tracker '/tmp/pip-req-tracker-_t8j_d2f'
    Running setup.py (path:/home/zxy/mmdetection/setup.py) egg_info for package from file:///home/zxy/mmdetection
    Created temporary directory: /tmp/pip-pip-egg-info-5gait6w6
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/zxy/mmdetection/setup.py", line 5, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 332, in run
    requirement_set = resolver.resolve(
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 300, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 531, in prepare_editable_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 550, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 525, in _generate_metadata
    return generate_metadata_legacy(
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/home/zxy/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///home/zxy/mmdetection from build tracker '/tmp/pip-req-tracker-_t8j_d2f'
Removed build tracker: '/tmp/pip-req-tracker-_t8j_d2f'

**Comment by ZwwWayne** [comment]
1. From the error message `ModuleNotFoundError: No module named 'torch'`, torch is not correctly installed.
2. Please use the `error template` when creating the issue.

**Comment by rouyalxy** [comment]
>     1. From the error message `ModuleNotFoundError: No module named 'torch'`, torch is not correctly installed.
> 
>     2. Please use the `error template` when creating the issue.

thank you , where the error template

**Comment by ZwwWayne** [comment]
When you create an issue, there are several options to choose from, you can choose the bug item and fill in the place holders.

**Comment by aliencaocao** [comment]
Same issue here, torch is installed and can be imported. Weirdest thing is it was working 3 days ago and i did nothing to my venv. using the 2.x branch

**Comment by LangR7** [comment]
same issue
