### ISSUE TITLE
code no longer runs!

### ISSUE THREAD

**Issue by why228430** [open-mmlab/mmdetection#3959]
2020-10-19 22:05:28,760 - mmdet - INFO - Epoch [1][4350/4502]   lr: 0.00353, eta: 1 day, 1:25:27, time: 0.878, data_time: 0.006, memory: 6930, s0.loss_cls: 0.4002, s0.loss_bbox: 0.5765, sr0.loss_cls: 0.3215, sr0.loss_bbox: 0.4856, sr1.loss_cls: 0.4673, sr1.loss_bbox: 0.4131, loss: 2.6642
2020-10-19 22:06:12,688 - mmdet - INFO - Epoch [1][4400/4502]   lr: 0.00357, eta: 1 day, 1:24:38, time: 0.879, data_time: 0.006, memory: 6930, s0.loss_cls: 0.4703, s0.loss_bbox: 0.5323, sr0.loss_cls: 0.3091, sr0.loss_bbox: 0.4284, sr1.loss_cls: 0.4456, sr1.loss_bbox: 0.3651, loss: 2.5508
2020-10-19 22:06:56,962 - mmdet - INFO - Epoch [1][4450/4502]   lr: 0.00360, eta: 1 day, 1:23:57, time: 0.885, data_time: 0.006, memory: 6930, s0.loss_cls: 0.4628, s0.loss_bbox: 0.5366, sr0.loss_cls: 0.3102, sr0.loss_bbox: 0.4151, sr1.loss_cls: 0.3911, sr1.loss_bbox: 0.3452, loss: 2.4611
2020-10-19 22:07:41,018 - mmdet - INFO - Epoch [1][4500/4502]   lr: 0.00364, eta: 1 day, 1:23:11, time: 0.881, data_time: 0.006, memory: 6930, s0.loss_cls: 0.4717, s0.loss_bbox: 0.5756, sr0.loss_cls: 0.3644, sr0.loss_bbox: 0.4828, sr1.loss_cls: 0.4877, sr1.loss_bbox: 0.4105, loss: 2.7926
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 458/458, 0.5 task/s, elapsed: 952s, ETA:     0s15

The code no longer runs when it runs here！

**Comment by why228430** [comment]
ctrl+c强制退出后打印以下信息

2020-10-21 12:02:55,331 - mmdet - INFO - Epoch [1][800/875]     lr: 0.00098, eta: 7:37:05, time: 1.356, data_time: 0.161, memory: 9041, s0.loss_cls: 0.7353, s0.loss_bbox: 0.9079, sr0.loss_cls: 0.7223, sr0.loss_bbox: 0.8589, sr1.loss_cls: 0.7794, sr1.loss_bbox: 0.9339, loss: 4.9376
2020-10-21 12:04:02,713 - mmdet - INFO - Epoch [1][850/875]     lr: 0.00101, eta: 7:35:46, time: 1.348, data_time: 0.160, memory: 9041, s0.loss_cls: 0.7115, s0.loss_bbox: 0.8552, sr0.loss_cls: 0.7105, sr0.loss_bbox: 0.7884, sr1.loss_cls: 0.7689, sr1.loss_bbox: 0.8546, loss: 4.6892
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 458/458, 0.4 task/s, elapsed: 1084s, ETA:     0s15
^CProcess ForkPoolWorker-1:
Process ForkPoolWorker-4:
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
Traceback (most recent call last):
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
    meta=meta)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/apis/train.py", line 179, in train_detector
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 384, in run
Traceback (most recent call last):
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/queues.py", line 352, in get
    res = self._reader.recv_bytes()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
    epoch_runner(data_loaders[i], **kwargs)
KeyboardInterrupt
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 293, in train
    self.call_hook('after_train_epoch')
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/core/evaluation/eval_hooks.py", line 28, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/datasets/dotav1.py", line 189, in evaluate
    logger=logger)
  File "/home/dl/anaconda3/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/core/evaluation/rmean_ap.py", line 212, in reval_map
    [area_ranges for _ in range(num_imgs)]))
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 651, in get
    self.wait(timeout)
  File "/home/dl/anaconda3/lib/python3.7/multiprocessing/pool.py", line 648, in wait
    self._event.wait(timeout)
  File "/home/dl/anaconda3/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/dl/anaconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by why228430** [comment]
This is my environment!

2020-10-21 13:58:12,888 - mmdet - INFO - Environment info:
sys.platform: linux
Python: 3.7.0 (default, Jun 28 2018, 13:15:42) [GCC 7.2.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.3.1
PyTorch compiling details: PyTorch built with:

GCC 7.3
Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
OpenMP 201511 (a.k.a. OpenMP 4.5)
NNPACK is enabled
CUDA Runtime 10.1
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
CuDNN 7.6.3
Magma 2.5.1
Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
TorchVision: 0.4.2
OpenCV: 4.4.0
MMCV: 0.5.9
MMDetection: 2.1.0+8f3868f
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.2
2020-10-21 13:58:12,888 - mmdet - INFO - Distributed training: False
2020-10-21 13:58:13,710 - mmdet - INFO - Config:
model = dict(
type='R3Det',
pretrained='torchvision://resnet50',
backbone=dict(
type='ResNet',
depth=50,
num_stages=4,
out_indices=(0, 1, 2, 3),
frozen_stages=1,
norm_cfg=dict(type='BN', requires_grad=True),
norm_eval=True,
style='pytorch'),
neck=dict(
type='FPN',
in_channels=[256, 512, 1024, 2048],
out_channels=256,
start_level=1,
add_extra_convs='on_input',
num_outs=5),
bbox_head=dict(
type='RRetinaHead',
num_classes=15,
in_channels=256,
stacked_convs=4,
use_h_gt=True,
feat_channels=256,
anchor_generator=dict(
type='RAnchorGenerator',
octave_base_scale=4,
scales_per_octave=3,
ratios=[1.0, 0.5, 2.0, 0.3333333333333333, 3.0, 0.2, 5.0],
angles=None,
strides=[8, 16, 32, 64, 128]),
bbox_coder=dict(
type='DeltaXYWHABBoxCoder',
target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
loss_cls=dict(
type='FocalLoss',
use_sigmoid=True,
gamma=2.0,
alpha=0.25,
loss_weight=1.0),
loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)),
frm_cfgs=[
dict(in_channels=256, featmap_strides=[8, 16, 32, 64, 128]),
dict(in_channels=256, featmap_strides=[8, 16, 32, 64, 128])
],
num_refine_stages=2,
refine_heads=[
dict(
type='RRetinaRefineHead',
num_classes=15,
in_channels=256,
stacked_convs=4,
feat_channels=256,
anchor_generator=dict(
type='PseudoAnchorGenerator', strides=[8, 16, 32, 64, 128]),
bbox_coder=dict(
type='DeltaXYWHABBoxCoder',
target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
loss_cls=dict(
type='FocalLoss',
use_sigmoid=True,
gamma=2.0,
alpha=0.25,
loss_weight=1.0),
loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)),
dict(
type='RRetinaRefineHead',
num_classes=15,
in_channels=256,
stacked_convs=4,
feat_channels=256,
anchor_generator=dict(
type='PseudoAnchorGenerator', strides=[8, 16, 32, 64, 128]),
bbox_coder=dict(
type='DeltaXYWHABBoxCoder',
target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
loss_cls=dict(
type='FocalLoss',
use_sigmoid=True,
gamma=2.0,
alpha=0.25,
loss_weight=1.0),
loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0))
])
train_cfg = dict(
s0=dict(
assigner=dict(
type='MaxIoUAssigner',
pos_iou_thr=0.5,
neg_iou_thr=0.4,
min_pos_iou=0,
ignore_iof_thr=-1,
iou_calculator=dict(type='RBboxOverlaps2D')),
allowed_border=-1,
pos_weight=-1,
debug=False),
sr=[
dict(
assigner=dict(
type='MaxIoUAssigner',
pos_iou_thr=0.6,
neg_iou_thr=0.5,
min_pos_iou=0,
ignore_iof_thr=-1,
iou_calculator=dict(type='RBboxOverlaps2D')),
allowed_border=-1,
pos_weight=-1,
debug=False),
dict(
assigner=dict(
type='MaxIoUAssigner',
pos_iou_thr=0.7,
neg_iou_thr=0.6,
min_pos_iou=0,
ignore_iof_thr=-1,
iou_calculator=dict(type='RBboxOverlaps2D')),
allowed_border=-1,
pos_weight=-1,
debug=False)
],
stage_loss_weights=[1.0, 1.0])
merge_nms_iou_thr_dict = dict({
'roundabout': 0.1,
'tennis-court': 0.3,
'swimming-pool': 0.1,
'storage-tank': 0.1,
'soccer-ball-field': 0.3,
'small-vehicle': 0.05,
'ship': 0.05,
'plane': 0.3,
'large-vehicle': 0.05,
'helicopter': 0.2,
'harbor': 0.0001,
'ground-track-field': 0.3,
'bridge': 0.0001,
'basketball-court': 0.3,
'baseball-diamond': 0.3
})
merge_cfg = dict(
nms_pre=2000,
score_thr=0.1,
nms=dict(
type='rnms',
iou_thr=dict({
'roundabout': 0.1,
'tennis-court': 0.3,
'swimming-pool': 0.1,
'storage-tank': 0.1,
'soccer-ball-field': 0.3,
'small-vehicle': 0.05,
'ship': 0.05,
'plane': 0.3,
'large-vehicle': 0.05,
'helicopter': 0.2,
'harbor': 0.0001,
'ground-track-field': 0.3,
'bridge': 0.0001,
'basketball-court': 0.3,
'baseball-diamond': 0.3
})),
max_per_img=1000)
test_cfg = dict(
nms_pre=1000,
score_thr=0.1,
nms=dict(type='rnms', iou_thr=0.05),
max_per_img=100,
merge_cfg=dict(
nms_pre=2000,
score_thr=0.1,
nms=dict(
type='rnms',
iou_thr=dict({
'roundabout': 0.1,
'tennis-court': 0.3,
'swimming-pool': 0.1,
'storage-tank': 0.1,
'soccer-ball-field': 0.3,
'small-vehicle': 0.05,
'ship': 0.05,
'plane': 0.3,
'large-vehicle': 0.05,
'helicopter': 0.2,
'harbor': 0.0001,
'ground-track-field': 0.3,
'bridge': 0.0001,
'basketball-court': 0.3,
'baseball-diamond': 0.3
})),
max_per_img=1000))
dataset_type = 'DOTADatasetV1'
data_root = '/media/dl/本地磁盘/DOTA'
trainsplit_ann_folder = '/media/dl/本地磁盘/DOTA/trainsplit/labelTxt'
trainsplit_img_folder = '/media/dl/本地磁盘/DOTA/trainsplit/images'
valsplit_ann_folder = '/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/valsplit/labelTxt'
valsplit_img_folder = '/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/valsplit/images'
val_ann_folder = '/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/val/labelTxt-v1.0/labelTxt'
val_img_folder = '/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/val/images/part1/images'
test_img_folder = '/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/test/images/part1/images'
img_norm_cfg = dict(
mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
dict(type='LoadImageFromFile'),
dict(type='LoadAnnotations', with_bbox=True),
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='DefaultFormatBundle'),
dict(
type='Collect',
keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
]
test_pipeline = [
dict(type='LoadImageFromFile'),
dict(
type='CroppedTilesFlipAug',
tile_scale=(800, 800),
tile_shape=(600, 600),
tile_overlap=(150, 150),
flip=False,
transforms=[
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='ImageToTensor', keys=['img']),
dict(type='Collect', keys=['img'])
])
]
data = dict(
samples_per_gpu=8,
workers_per_gpu=2,
train=[
dict(
type='DOTADatasetV1',
data_root='/media/dl/本地磁盘/DOTA',
ann_file='/media/dl/本地磁盘/DOTA/trainsplit/labelTxt',
img_prefix='/media/dl/本地磁盘/DOTA/trainsplit/images',
pipeline=[
dict(type='LoadImageFromFile'),
dict(type='LoadAnnotations', with_bbox=True),
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='DefaultFormatBundle'),
dict(
type='Collect',
keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
]),
dict(
type='DOTADatasetV1',
data_root='/media/dl/本地磁盘/DOTA',
ann_file=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/valsplit/labelTxt',
img_prefix=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/valsplit/images',
pipeline=[
dict(type='LoadImageFromFile'),
dict(type='LoadAnnotations', with_bbox=True),
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='DefaultFormatBundle'),
dict(
type='Collect',
keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
])
],
val=dict(
type='DOTADatasetV1',
data_root='/media/dl/本地磁盘/DOTA',
ann_file=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/val/labelTxt-v1.0/labelTxt',
difficulty_thresh=1,
img_prefix=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/val/images/part1/images',
pipeline=[
dict(type='LoadImageFromFile'),
dict(
type='CroppedTilesFlipAug',
tile_scale=(800, 800),
tile_shape=(600, 600),
tile_overlap=(150, 150),
flip=False,
transforms=[
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='ImageToTensor', keys=['img']),
dict(type='Collect', keys=['img'])
])
]),
test=dict(
type='DOTADatasetV1',
data_root='/media/dl/本地磁盘/DOTA',
ann_file=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/test/images/part1/images',
difficulty_thresh=1,
img_prefix=
'/media/dl/本地磁盘/r3det-on-mmdetection/data/dota/test/images/part1/images',
pipeline=[
dict(type='LoadImageFromFile'),
dict(
type='CroppedTilesFlipAug',
tile_scale=(800, 800),
tile_shape=(600, 600),
tile_overlap=(150, 150),
flip=False,
transforms=[
dict(type='RResize', img_scale=(800, 800)),
dict(type='RRandomFlip', flip_ratio=0.5),
dict(
type='Normalize',
mean=[123.675, 116.28, 103.53],
std=[58.395, 57.12, 57.375],
to_rgb=True),
dict(type='Pad', size=(800, 800)),
dict(type='ImageToTensor', keys=['img']),
dict(type='Collect', keys=['img'])
])
]))
optimizer = dict(type='SGD', lr=0.004, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=10, norm_type=2))
lr_config = dict(
policy='step',
warmup='linear',
warmup_iters=5000,
warmup_ratio=0.1,
step=[12, 16, 20])
total_epochs = 24
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/r3det_r50_fpn_2x_20200616'
evaluation = dict(interval=1, metric='mAP')
gpu_ids = range(0, 1)

**Comment by v-qjqs** [comment]
Hi @why228430, I guess you are using your own dataset, rather than common dataset like COCO. So you might debug where you got strucked.
