### ISSUE TITLE
Problem on training process

### ISSUE THREAD

**Issue by Hyeonminro** [open-mmlab/mmdetection#3968]
**Describe the bug**
I ran through the training process that described on documentation and I faced this error message

**Reproduction**
1. What command or script did you run?
python tools/train.py configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coil.py 

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I changed the my own data set into COCO data format and than modified my data path(data root) in config file (/config/_base_/model, /config/_base_/data) then run the train.py file
3. What dataset did you use?
my own dataset that labeled with labelme 

**Environment**

sys.platform: linux
Python: 3.7.7 (default, Mar 26 2020, 15:48:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPU 0: Tesla V100-PCIE-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0a0+82fd1c8
OpenCV: 4.2.0
MMCV: 0.5.1
MMDetection: 2.0.0+3c021b1
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.2

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/pirl/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 383, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 278, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pirl/mmdetection/mmdet/datasets/custom.py", line 140, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/pirl/mmdetection/mmdet/datasets/custom.py", line 153, in prepare_train_img
    return self.pipeline(results)
  File "/home/pirl/mmdetection/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/pirl/mmdetection/mmdet/datasets/pipelines/loading.py", line 24, in __call__
    img = mmcv.imread(filename, self.color_type)
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/image/io.py", line 85, in imread
    f'img file does not exist: {img_or_path}')
  File "/home/pirl/anaconda3/envs/segmen/lib/python3.7/site-packages/mmcv-0.5.1-py3.7-linux-x86_64.egg/mmcv/utils/path.py", line 25, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: img file does not exist: data/custom/coil/train/JPEGImages\Cam12 04.jpg

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
Just as the error suggests the img file does not exist, you can check it by running bash command 
`ls data/custom/coil/train/JPEGImages\Cam12 04.jpg`
