### ISSUE TITLE
torchsummary or torchstat 

### ISSUE THREAD

**Issue by casiahnu** [open-mmlab/mmdetection#4028]
When I use torchsummary or torchstat to calculate the parameters, I meet
Traceback (most recent call last):
  File "./tools/train.py", line 167, in <module>
    main()
  File "./tools/train.py", line 137, in main
    stat(model, (3, 256, 256))
  File "/usr/local/lib/python3.6/dist-packages/torchstat/statistics.py", line 71, in stat
    ms.show_report()
  File "/usr/local/lib/python3.6/dist-packages/torchstat/statistics.py", line 64, in show_report
    collected_nodes = self._analyze_model()
  File "/usr/local/lib/python3.6/dist-packages/torchstat/statistics.py", line 57, in _analyze_model
    model_hook = ModelHook(self._model, self._input_size)
  File "/usr/local/lib/python3.6/dist-packages/torchstat/model_hook.py", line 24, in __init__
    self._model(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaozishu/data/mmdetection_550/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'img_metas'

What should I do? Thank you

**Comment by ZwwWayne** [comment]
This is because the model forward requires `img_metas` as input. To get the number of parameters, you can use this [script](https://github.com/open-mmlab/mmdetection/blob/master/tools/get_flops.py).

**Comment by msha096** [comment]
> This is because the model forward requires `img_metas` as input. To get the number of parameters, you can use this [script](https://github.com/open-mmlab/mmdetection/blob/master/tools/get_flops.py).

Hi, the script link is not available now, could you please update the link to the script? Thanks!
