### ISSUE TITLE
cannot install mmcv-full in RTX 3090 environment

### ISSUE THREAD

**Issue by LanceZPF** [open-mmlab/mmdetection#4047]
cannot compile mmcv-full==1.1.1 or the version below 1.1.6

I am using the server that has environment of pytorch1.8.0dev and cudatoolkit11.0.

when I am doing "pip install mmcv-full==1.1.1"
after downloading while compiling
the error comes out:

"raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension"

before it is:
"ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/zpf/anaconda3/envs/lance/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1534, in _run_ninja_build
    env=env)
  File "/home/zpf/anaconda3/envs/lance/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1."

I wonder if it's because the mmcv  does not support cuda11?

by the way, when I am using the latest version of mmcv and mmdet, the installing is fine but other error comes out when I try to train a model:
"ModuleNotFoundError: No module named 'mmcv._ext'"

**Comment by ZwwWayne** [comment]
You can use the newest mmcv from the github [here](https://github.com/open-mmlab/mmcv), which already supports Pytorch 1.7. MMCV-full==1.2.0 will be released soon to support that.

**Comment by caiduoduo12138** [comment]
I use the newest mmcv ,but error still occours .
Does it support 3090?
Here are the details:
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/cai/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/cai/mmdetection/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/cai/mmdetection/mmcv/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/cai/mmdetection/mmcv/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/cai/mmdetection/mmcv/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/cai/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/cai/mmdetection/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/cai/mmdetection/mmcv/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/cai/mmdetection/mmcv/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/cai/mmdetection/mmcv/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/cai/anaconda3/envs/mmd2/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/ssd/ssd300_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by RyanXLi** [comment]
Please check whether [this](https://github.com/open-mmlab/mmdetection/issues/4052#issuecomment-724713919) solves your problem.

**Comment by caiduoduo12138** [comment]
Has the version of MMCV-full and MMDET support the newest  architecture(compute_86) of GPU which called Ampere, I used torch 1.7+cuda11.

**Comment by G-Naughty** [comment]
> Has the version of MMCV-full and MMDET support the newest architecture(compute_86) of GPU which called Ampere, I used torch 1.7+cuda11.

Can you write a blog to teach how to setup mmdetection, Thank you very much

**Comment by G-Naughty** [comment]
I try to run image_demo,but report error
Traceback (most recent call last):
  File "/home/ggm/GGM/mmdetection2/demo/image_demo.py", line 26, in <module>
    main()
  File "/home/ggm/GGM/mmdetection2/demo/image_demo.py", line 20, in main
    result = inference_detector(model, args.img)
  File "/home/ggm/GGM/mmdetection2/mmdet/apis/inference.py", line 119, in inference_detector
    result = model(return_loss=False, rescale=True, **data)[0]
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/detectors/two_stage.py", line 194, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/ggm/GGM/mmdetection2/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/ggm/anaconda3/envs/mmd2/lib/python3.6/site-packages/mmcv/ops/nms.py", line 18, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: nms is not compiled with GPU support

**Comment by LanceZPF** [comment]
> Has the version of MMCV-full and MMDET support the newest architecture(compute_86) of GPU which called Ampere, I used torch 1.7+cuda11.

Could you please share the link of Ampere?
