### ISSUE TITLE
pytorch2onnx--Failing for convert retinanet onnx model to pb model.

### ISSUE THREAD

**Issue by herrickli** [open-mmlab/mmdetection#4060]
Hi~
After successfully convert a pytorch model to onnx model, I want to convert the onnx model to pb model, and I use this repo to convert the model:
```https://github.com/onnx/onnx-tensorflow.git```
And I got this error:
```TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int64, float64] that don't all match.```
It seems somewhere in onnx model has type mismatch. How can I solve this problem, thanks~

Here is the complete error report：
```
: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3591910000 Hz
: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5584a88fde70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "convter.py", line 13, in <module>
    onnx2pb(onnx_input_path, pb_output_path)
  File "convter.py", line 7, in onnx2pb
    tf_exp.export_graph(pb_output_path)  # export the model
  File "projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/backend_rep.py", line 116, in export_graph
    **self.signatures))
  File "anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 959, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 865, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3299, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/backend_tf_module.py:103 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/backend.py:299 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
   /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/handlers/backend/concat.py:27 version_11  *
        return cls._common(node, **kwargs)
  /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/handlers/backend/concat.py:15 _common  *
        return [cls.make_tensor_from_onnx_node(node, inputs=[inputs])]
   /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/handlers/backend_handler.py:120 make_tensor_from_onnx_node  *
        return cls._run_tf_func(tf_func, inputs, attrs)
   /projects/convert_mmd/convertion/onnx-tensorflow/onnx_tf/handlers/backend_handler.py:200 _run_tf_func  *
        return tf_func(**kwargs)
    /anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:180 wrapper  **
        return target(*args, **kwargs)
    /anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:1606 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    /anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py:1189 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    /anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:442 _apply_op_helper
        raise TypeError("%s that don't all match." % prefix)

    TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int64, float64] that don't all match.
```

**Comment by v-qjqs** [comment]
@herrickli, as the error message suggests, may you manually change the dtype of all tensors here to in64 or float64?
