### ISSUE TITLE
Error  when running coco_erroe_analysis.py 

### ISSUE THREAD

**Issue by casiahnu** [open-mmlab/mmdetection#4065]
When I run 
python ./tools/coco_error_analysis.py  ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/20200914_033609.log.json  ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
I got the following error:

root@224e003dc587:/home/gaozishu/data/mmdetection_550# python ./tools/coco_error_analysis.py  ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/20200914_033609.log.json  ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "./tools/coco_error_analysis.py", line 173, in <module>
    main()
  File "./tools/coco_error_analysis.py", line 169, in main
    analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
  File "./tools/coco_error_analysis.py", line 113, in analyze_results
    cocoDt = cocoGt.loadRes(res_file)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 380, in loadRes
    anns = json.load(open(resFile))
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 2222)

What should I do? Thank you!

**Comment by casiahnu** [comment]
When I run test.py. CUDA_VISIBLE_DEVICES=6 python3 ./tools/test.py ./configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py  ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/latest.pth --out ./result/result.pkl --eval bbox

Then I run python3 ./tools/coco_error_analysis.py  ./result/result.pkl     ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco

I get 
 root@224e003dc587:/home/gaozishu/data/mmdetection_550# python3 ./tools/coco_error_analysis.py  ./result/result.pkl     ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loading and preparing results...
Traceback (most recent call last):
  File "./tools/coco_error_analysis.py", line 173, in <module>
    main()
  File "./tools/coco_error_analysis.py", line 169, in main
    analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
  File "./tools/coco_error_analysis.py", line 113, in analyze_results
    cocoDt = cocoGt.loadRes(res_file)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 380, in loadRes
    anns = json.load(open(resFile))
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

In addition, when I run test.py, I will get a .pkl format result. 
When I run coco_error_analysis.py,  I will use the .pkl format result as input  in 'parser.add_argument('result',help='result file (json format) path'). '  But I need a .json format file as input in fact.  How can I get the .json format file? Could you please give me some guidance？ Thank you

**Comment by casiahnu** [comment]
We aim to get PR curve about coco dataset

**Comment by Quebradawill** [comment]
I met the same error

**Comment by astontang** [comment]
how to sovle it?

**Comment by minooei** [comment]
> When I run test.py. CUDA_VISIBLE_DEVICES=6 python3 ./tools/test.py ./configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/latest.pth --out ./result/result.pkl --eval bbox
> 
> Then I run python3 ./tools/coco_error_analysis.py ./result/result.pkl ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
> 
> I get
> root@224e003dc587:/home/gaozishu/data/mmdetection_550# python3 ./tools/coco_error_analysis.py ./result/result.pkl ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
> loading annotations into memory...
> Done (t=0.00s)
> creating index...
> index created!
> Loading and preparing results...
> Traceback (most recent call last):
> File "./tools/coco_error_analysis.py", line 173, in
> main()
> File "./tools/coco_error_analysis.py", line 169, in main
> analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
> File "./tools/coco_error_analysis.py", line 113, in analyze_results
> cocoDt = cocoGt.loadRes(res_file)
> File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 380, in loadRes
> anns = json.load(open(resFile))
> File "/usr/lib/python3.6/json/**init**.py", line 296, in load
> return loads(fp.read(),
> File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
> return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
> 
> In addition, when I run test.py, I will get a .pkl format result.
> When I run coco_error_analysis.py, I will use the .pkl format result as input in 'parser.add_argument('result',help='result file (json format) path'). ' But I need a .json format file as input in fact. How can I get the .json format file? Could you please give me some guidance？ Thank you

you should first get coco format json with format-only option:
python3 ./tools/test.py ./configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/latest.pth --out ./result/result.pkl \
    --format-only \
    --options "jsonfile_prefix=./results"

which gives you "results.bbox.json" file then run:

python3 ./tools/coco_error_analysis.py results.bbox.json ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco --ann /path/to/instances_val2017.json

**Comment by hellock** [comment]
@yhcao6 may add documentation of the tool.

**Comment by zhuhl0913** [comment]
> > When I run test.py. CUDA_VISIBLE_DEVICES=6 python3 ./tools/test.py ./configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/latest.pth --out ./result/result.pkl --eval bbox
> > Then I run python3 ./tools/coco_error_analysis.py ./result/result.pkl ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
> > I get
> > root@224e003dc587:/home/gaozishu/data/mmdetection_550# python3 ./tools/coco_error_analysis.py ./result/result.pkl ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco
> > loading annotations into memory...
> > Done (t=0.00s)
> > creating index...
> > index created!
> > Loading and preparing results...
> > Traceback (most recent call last):
> > File "./tools/coco_error_analysis.py", line 173, in
> > main()
> > File "./tools/coco_error_analysis.py", line 169, in main
> > analyze_results(args.result, args.ann, args.types, out_dir=args.out_dir)
> > File "./tools/coco_error_analysis.py", line 113, in analyze_results
> > cocoDt = cocoGt.loadRes(res_file)
> > File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 380, in loadRes
> > anns = json.load(open(resFile))
> > File "/usr/lib/python3.6/json/**init**.py", line 296, in load
> > return loads(fp.read(),
> > File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
> > return codecs.ascii_decode(input, self.errors)[0]
> > UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
> > In addition, when I run test.py, I will get a .pkl format result.
> > When I run coco_error_analysis.py, I will use the .pkl format result as input in 'parser.add_argument('result',help='result file (json format) path'). ' But I need a .json format file as input in fact. How can I get the .json format file? Could you please give me some guidance？ Thank you
> 
> you should first get coco format json with format-only option: python3 ./tools/test.py ./configs/fcos/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco.py ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco/latest.pth --out ./result/result.pkl --format-only --options "jsonfile_prefix=./results"
> 
> which gives you "results.bbox.json" file then run:
> 
> python3 ./tools/coco_error_analysis.py results.bbox.json ./work_dirs/fcos_r50_caffe_fpn_gn-head_4x4_1x_coco --ann /path/to/instances_val2017.json

Well, for me that way of generating corresponding json file using tools/test.py with the argument following it isn't working. Do anyone has a simpler way to simply convert the pkl. file generated by test.py into coco format json file?

**Comment by acg93-pixel** [comment]
Solved it maybe? I can see that in the latest version of test.py, dumping results.bbox.json isn't supported, and I can't run coco_error_analysis.py without it.
