### ISSUE TITLE
The ''albumentations'' is not available

### ISSUE THREAD

**Issue by tsunehiro-kashiwagi** [open-mmlab/mmdetection#4079]
Thank you for the great repository.

On the subject of the title, The following URL configuration is not working.
https://github.com/open-mmlab/mmdetection/blob/master/configs/albu_example/mask_rcnn_r50_fpn_albu_1x_coco.py

At first I thought it might be a problem on the mmdetection side, but it seems to be due to a code change on the albu side.
https://github.com/albumentations-team/albumentations/releases

Due to minor changes in the albu repository, you get the following error
```
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
```

**Comment by v-qjqs** [comment]
Hi, I guess a solution is to modify the code [here](https://github.com/albumentations-team/albumentations/blob/master/albumentations/core/composition.py#L223) to if data is not None"

**Comment by tsunehiro-kashiwagi** [comment]
@v-qjqs 
Thanks for the reply.
I've confirmed that the cause is due to the alub 5.0 update. I'll try the fix you mentioned.
However, since the environment is currently a docker environment with multiple people building, it's not efficient to fix each time, so I've specified a version lower than 5.0 as a workaround for the time being.
