### ISSUE TITLE
Using the loader in jupyter notebook

### ISSUE THREAD

**Issue by i008** [open-mmlab/mmdetection#410]
First of all thanks to the authors for the great tool.

So in order to learn the package i wanted to do some tests and check the outputs in a jupyter notebook, but for some reason the code i pasted below will work when run from the shell as a seperate file but not in a jupyter cell. I assume this is related to some threads, is there a way around that?
(If run in a jupyter cell it will just hang and nothing will happen)

```python
from mmcv import Config
from mmdet.datasets import get_dataset
from mmdet.datasets.loader import build_dataloader
from mmdet.models import build_detector

cfg = Config.fromfile('configs/retinanet_r101_fpn_1x.py')
ds = get_dataset(cfg.data.train)
model = build_detector(
        cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)

dl =build_dataloader(ds, 1, 1,dist=False)

for a in dl:
    print(a)
    break
```

If you interrupt the kernel in the notebook you will see this:

```
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f3363c9be48>>
Traceback (most recent call last):
  File "/home/i008/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 717, in __del__
    self._shutdown_workers()
  File "/home/i008/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 713, in _shutdown_workers
    w.join()
  File "/home/i008/anaconda3/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/i008/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 57, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/i008/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 35, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt:```

**Comment by i008** [comment]
Ok i forgot to set the num worker to 0:) consider this resolved

**Comment by hyz-xmaster** [comment]
Hi @i008，I saw this post by chance and it helped me a lot. I always have this problem when I try to debug at some points. Can you also explain the meaning of setting works_per_gpu=0 ? Thanks.
