### ISSUE TITLE
Paa Error

### ISSUE THREAD

**Issue by as754770178** [open-mmlab/mmdetection#4164]
I run `paa_r101_fpn_2x_coco` in torch:1.6, mmcv:1.2.0 and mmdet:2.6.0, the code report error:
I try in  torch:1.6, mmcv:1.1.6 and mmdet:2.4.0, the code also report error.
```
/home/zgz/mmdetection-2.6.0/mmdetection-2.6.0/mmdet/models/dense_heads/paa_head.py:485: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  pos_inds.append(pos_mask.nonzero().view(-1))
[W TensorIterator.cpp:924] Warning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (function operator())
[W TensorIterator.cpp:918] Warning: Mixed memory format inputs detected while calling the operator. The operator will output contiguous tensor even if some of the inputs are in channels_last format. (function operator())
2020-11-23 19:22:17,484 - mmdet - INFO - Epoch [1][50/58633]	lr: 9.890e-04, eta: 10 days, 15:56:31, time: 0.655, data_time: 0.054, memory: 5105, loss_cls: 1.5923, loss_bbox: 0.7098, loss_iou: 0.3477, loss: 2.6498
2020-11-23 19:22:49,508 - mmdet - INFO - Epoch [1][100/58633]	lr: 1.988e-03, eta: 10 days, 13:07:58, time: 0.640, data_time: 0.007, memory: 5105, loss_cls: 1.2279, loss_bbox: 0.6568, loss_iou: 0.3483, loss: 2.2330
2020-11-23 19:23:19,759 - mmdet - INFO - Epoch [1][150/58633]	lr: 2.987e-03, eta: 10 days, 7:34:17, time: 0.605, data_time: 0.006, memory: 5105, loss_cls: 1.5554, loss_bbox: 0.7115, loss_iou: 0.3505, loss: 2.6174
Traceback (most recent call last):
  ... ...
  File "/home/zgz/mmdetection-2.6.0/mmdetection-2.6.0/mmdet/models/dense_heads/paa_head.py", line 155, in loss
    anchor_list,
  File "/home/zgz/mmdetection-2.6.0/mmdetection-2.6.0/mmdet/core/utils/misc.py", line 26, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/zgz/mmdetection-2.6.0/mmdetection-2.6.0/mmdet/models/dense_heads/paa_head.py", line 343, in paa_reassign
    gmm.fit(pos_loss_gmm)
  File "/usr/local/python/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 193, in fit
    self.fit_predict(X, y)
  File "/usr/local/python/lib/python3.7/site-packages/sklearn/mixture/_base.py", line 246, in fit_predict
    self._m_step(X, log_resp)
  File "/usr/local/python/lib/python3.7/site-packages/sklearn/mixture/_gaussian_mixture.py", line 679, in _m_step
    self.covariances_, self.covariance_type)
  File "/usr/local/python/lib/python3.7/site-packages/sklearn/mixture/_gaussian_mixture.py", line 333, in _compute_precision_cholesky
    raise ValueError(estimate_precision_error_message)
ValueError: Fitting the mixture model failed because some components have ill-defined empirical covariance (for instance caused by singleton or collapsed samples). Try to decrease the number of components, or increase reg_covar.
```

I don't know which cause the warn `Warning: Mixed memory format inputs detected while calling the operator. The operator will output channels_last tensor even if some of the inputs are not in channels_last format. (function operator())`.

**Comment by xvjiarui** [comment]
Hi @as754770178 
What is your batch size? When the batch size is too small, the model may diverge.

**Comment by as754770178** [comment]
my batchsize is 2. I only have one GPU, so what cause this error? I want to avoid it by myself.

**Comment by xvjiarui** [comment]
Hi @as754770178 
When the batch size is too small, the model may diverge.
You may use the provided checkpoint as pretrain.

**Comment by as754770178** [comment]
I not find the resnext152 pth.
