### ISSUE TITLE
Error when training yolo

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#4186]
Hello. When I was training yolo, errors happened. 
The training procedure doesn't have any problems. In the validation step:

_[                                                  ] 0/298, elapsed: 0s, ETA:/media/hkuit155/Elements/mmdetection/mmdet/models/dense_heads/yolo_head.py:270: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729047590/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  conf_inds = conf_pred.ge(conf_thr).nonzero().flatten()
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    meta=meta)
  File "/media/hkuit155/Elements/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/media/hkuit155/Elements/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 74, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/media/hkuit155/Elements/mmdetection/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/media/hkuit155/Elements/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/media/hkuit155/Elements/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/media/hkuit155/Elements/mmdetection/mmdet/models/detectors/single_stage.py", line 114, in simple_test
    *outs, img_metas, rescale=rescale)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/media/hkuit155/Elements/mmdetection/mmdet/models/dense_heads/yolo_head.py", line 208, in get_bboxes
    cfg, rescale, with_nms)
  File "/media/hkuit155/Elements/mmdetection/mmdet/models/dense_heads/yolo_head.py", line 313, in _get_bboxes_single
    score_factors=multi_lvl_conf_scores)
  File "/media/hkuit155/Elements/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 65, in multiclass_nms
    dets, keep = batched_nms(bboxes, scores, labels, nms_cfg)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/hkuit155/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 18, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)_

**Comment by xvjiarui** [comment]
Hi @CheungBH 
Sorry for the late reply. 
You may use [error report template](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to provide more information.
