### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by abdoelsayed2016** [open-mmlab/mmdetection#4216]
Traceback (most recent call last):
  File "./mmdetection/tools/train.py", line 14, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\apis\inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\core\__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\core\post_processing\__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\core\post_processing\bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\ops\__init__.py", line 2, in <module>
    from .conv import build_conv_layer
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\ops\conv.py", line 4, in <module>
    from .dcn import DeformConvPack, ModulatedDeformConvPack
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "c:\users\a.abdallah\desktop\tabledata-20201201t174421z-001\tabledata\mmdetection\mmdet\ops\dcn\deform_conv.py", line 11, in <module>
    from . import deform_conv_cuda
ImportError: DLL load failed: The specified procedure could not be found.

*mmdetection-version: v1.2.0*
*pytorch: last-version*

**Comment by ZwwWayne** [comment]
This seems to be an environmental issue. Could you follow the steps in [here](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment) to check whether CUDA/Pytorch is installed correctly? Please also follow the `Error Template` to report the issues with more detailed of your environment information if you can.

**Comment by korabelnikov** [comment]
I can confirm, that issue with 
`ImportError: DLL load failed: The specified procedure could not be found.`
exists. I met it earlier, and  I met it now.

short answer:
**setup.py clean -all
pip install -e .**

long story:

I had pytorch 1.2 on my windows machine and mmdetection I worked.
I have pytorch 1.3.1 on my ubuntu machine, and mmdetectoin works.

I needed pytorch 1.3.1 for distiller, so I decided to update my env (moreover I would have save version of torch on both my machines).

I updated pytorch by conda, checked. It works well even on cuda. MMdetection started to fail with abovementioned error.
I've rebuild mmdetection, but error still here.

**Comment by ZwwWayne** [comment]
> I can confirm, that issue with
> `ImportError: DLL load failed: The specified procedure could not be found.`
> exists. I met it earlier, and I met it now.
> 
> short answer:
> **setup.py clean -all pip install -e .**
> 
> long story:
> 
> I had pytorch 1.2 on my windows machine and mmdetection I worked.
> I have pytorch 1.3.1 on my ubuntu machine, and mmdetectoin works.
> 
> I needed pytorch 1.3.1 for distiller, so I decided to update my env (moreover I would have save version of torch on both my machines).
> 
> I updated pytorch by conda, checked. It works well even on cuda. MMdetection started to fail with abovementioned error.
> I've rebuild mmdetection, but error still here.

Hi @korabelnikov ,
So did you fix that? If you fixed it, would you like to create a PR to update our FAQ thus others could solve the problem following your step?

**Comment by korabelnikov** [comment]
hi,
as I understood
`setup.py clean **-all**`
is necessary when you change torch version

it may be wrong conclusion, so let's wait reactions from other users
