### ISSUE TITLE
Albumentation support

### ISSUE THREAD

**Issue by Adblu** [open-mmlab/mmdetection#4220]
Hi. I am using albumentations library however I'm getting an error:
```
Traceback (most recent call last):
  File "/home/user/.conda/envs/project/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/.conda/envs/project/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/project/project/src/models/train_model.py", line 32, in <module>
    train(cfg)
  File "/home/user/project/project/src/utilities/helpers.py", line 47, in train
    train_detector(model, datasets, cfg, distributed=distributed, validate=True)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 191, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 214, in prepare_train_img
    return self.pipeline(results)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/datasets/pipelines/transforms.py", line 512, in __call__
    self._pad_masks(results)
  File "/home/user/.conda/envs/project/lib/python3.7/site-packages/mmdet/datasets/pipelines/transforms.py", line 493, in _pad_masks
    results[key] = results[key].pad(pad_shape, pad_val=self.pad_val)
AttributeError: 'numpy.ndarray' object has no attribute 'pad'
```

To fix it I had to modify file mmdetection/mmdet/datasets/pipelines/transforms.py

from 
```
    def mapper(d, keymap):
        """Dictionary mapper. Renames keys according to keymap provided.

        Args:
            d (dict): old dict
            keymap (dict): {'old_key':'new_key'}
        Returns:
            dict: new dict.
        """

        updated_dict = {}
        for k, v in zip(d.keys(), d.values()):
            new_k = keymap.get(k, k)
            updated_dict[new_k] = d[k]
        return updated_dict

    def __call__(self, results):
        # dict to albumentations format
        results = self.mapper(results, self.keymap_to_albu)
        # TODO: add bbox_fields
        if 'bboxes' in results:
            # to list of boxes
            if isinstance(results['bboxes'], np.ndarray):
                results['bboxes'] = [x for x in results['bboxes']]
            # add pseudo-field for filtration
            if self.filter_lost_elements:
                results['idx_mapper'] = np.arange(len(results['bboxes']))

        # ------------------------------- PART TO BE REPLACED ----------------------
        # TODO: Support mask structure in albu
        if 'masks' in results:
            if isinstance(results['masks'], PolygonMasks):
                raise NotImplementedError(
                    'Albu only supports BitMap masks now')
            ori_masks = results['masks']
            if albumentations.__version__ < '0.5':
                results['masks'] = results['masks'].masks
            else:
                results['masks'] = [mask for mask in results['masks'].masks]
        # -------------------------------------------------------------------------
        results = self.aug(**results)
```
to:
```
def mapper(d, keymap):
        """Dictionary mapper. Renames keys according to keymap provided.


        Args:
            d (dict): old dict
            keymap (dict): {'old_key':'new_key'}
        Returns:
            dict: new dict.
        """


        updated_dict = {}
        for k, v in zip(d.keys(), d.values()):
            new_k = keymap.get(k, k)
            updated_dict[new_k] = d[k]
        return updated_dict


    def __call__(self, results):
        # dict to albumentations format
        results = self.mapper(results, self.keymap_to_albu)
        # TODO: add bbox_fields
        if 'bboxes' in results:
            # to list of boxes
            if isinstance(results['bboxes'], np.ndarray):
                results['bboxes'] = [x for x in results['bboxes']]
            # add pseudo-field for filtration
            if self.filter_lost_elements:
                results['idx_mapper'] = np.arange(len(results['bboxes']))

        # ------------------------------- CHANGE ----------------------

        from mmdet.core.mask.structures import BitmapMasks

        if 'masks' in results and not isinstance(results['masks'], BitmapMasks):
            h, w = results['img_info']['height'], results['img_info']['width']
            results['masks'] = BitmapMasks(results['masks'], h, w)

        # -------------------------------------------------------------------------

        results = self.aug(**results)
```

This is not an elegant solution in fully automated pipeline. 
FYI, notice original remark:
```
# TODO: Support mask structure in albu
```

Has something been done to that manner ?

**Comment by ZwwWayne** [comment]
Please @yhcao6  have a look for that.

**Comment by Adblu** [comment]
@ZwwWayne @yhcao6  Is there any update on the issue ?

**Comment by abdksyed** [comment]
The issue still exists. MMDetection data laoder converts the mask to PolyMask, but this raises an error when the mask is PolyMask.

I tried the above fix mentioned after changing few things like `results['height']` instead of results['image_info']['height'] as` `results` dict doesn't have `image_info` anymore.

After doing all this `BitMask` is giving an Assertion error.
```
AssertionError
mmdet/structures/mask/structures.py", line 261, in __init__
    assert isinstance(masks, (list, np.ndarray))
```
