### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.version'

### ISSUE THREAD

**Issue by WhoseDangerousSmile** [open-mmlab/mmdetection#423]
Traceback (most recent call last):
  File "round1_submit.py", line 3, in <module>
    from mmdet.models import build_detector
  File "/mmdetection/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

my envs:
16.04.1-Ubuntu
pytorch0.4.1-cuda9-cudnn7 
python 3.6

**Comment by OceanPang** [comment]
@WhoseDangerousSmile Please run `python setup.py install` in first, refer to [INSTALL.md](uhttps://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md)

**Comment by Dawning23** [comment]
@hellock 我也遇到了相似的问题,报错内容如下:

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
    from mmdet import __version__
  File "/home/zbh/Projects/mayi_submit/code/mmdetection/mmdet/                                                   __init__.py", line 1, in <module>
    from mmdet import __version__
from mmdet import __version__  File "/home/zbh/Projects/mayi_s                                                   ubmit/code/mmdetection/mmdet/__init__.py", line 1, in <module>

  File "/home/zbh/Projects/mayi_submit/code/mmdetection/mmdet/                                                   __init__.py", line 1, in <module>
    from .version import __version__, short_version
        from .version import __version__, short_versionModuleN                                                   otFoundErrorfrom .version import __version__, short_version
:
No module named 'mmdet.version'ModuleNotFoundError
: ModuleNotFoundErrorNo module named 'mmdet.version':
No module named 'mmdet.version'
Traceback (most recent call last):
  File "/home/zbh/anaconda3/envs/mmdetect/lib/python3.7/runpy.                                                   py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zbh/anaconda3/envs/mmdetect/lib/python3.7/runpy.                                                   py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zbh/anaconda3/envs/mmdetect/lib/python3.7/site-p                                                   ackages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/zbh/anaconda3/envs/mmdetect/lib/python3.7/site-p                                                   ackages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zbh/anaconda3/                                                   envs/mmdetect/bin/python', '-u', './tools/train.py', '--local_rank=2', '../mmdetection_old/configs/fusai_single-scale.py', ' --launcher', 'pytorch']' returned non-zero exit status 1.
```

遇到此问题后,我按照 @OceanPang 的方法删除 `/mmdetection/build/` 文件夹,并且按照[INSTALL.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/INSTALL.md)步骤使用`python setup.py develop`重新安装,依然报相同的错误       
请问有什么解决办法么?

**Comment by luyao777** [comment]
请问你是Pytorch版本是？

**Comment by RiyazAina-DeepML** [comment]
import mmdet working but when i am running train.py its throwing 
  File "tools/train.py", line 12, in <module>
    from mmdet import __version__

**Comment by PanJianning** [comment]
> import mmdet working but when i am running train.py its throwing
> File "tools/train.py", line 12, in
> from mmdet import **version**

If mmdet is **build** successfully, the `mmdet` folder should have file `version.py` .  Also, since you can't import in `tools/train.py`, the reason can be that `mmdet` is missing in python import path (`sys.path`, `PAYTHONPATH`).

**Comment by guotong1988** [comment]
Same question. Thank you.

**Comment by sisse008** [comment]
Did anyone figure this out?

**Comment by SkySailing** [comment]
i solve it by run command like this :
`anaconda3/envs/openmmlab/bin/python3    /mnt/data740G/mmdetection/mmdetection-2.4.0/tools/train.py 
   ../configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py`
