### ISSUE TITLE
Conversion to ONNX

### ISSUE THREAD

**Issue by SebastienLinker** [open-mmlab/mmdetection#4238]
**Describe the bug**
I am trying to convert my models to TensorRT (use TensorRT as a backend interface for ONNX). When I use the `tools/pytorch2onnx.py` script, I foound that the outputted model actually depends on the test image.

**Reproduction**
1. What command or script did you run?
```
tools/pytorch2onnx.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ./checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth --input-img demo/demo.jpg --verify --show
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?

Line 27, update the sample image by a random image, or any thing different from the original one:
```python
test_img = input_img # Use a different image to test
# Use either one of those:
input_config['input_path'] = np.random.randint(0, 255, size=(427, 640, 3), dtype=np.uint8)
input_config['input_path'] = 255 - mmcv.imread(input_img)
```

Then, during model creation or inference, we get an error. I would expect the ONNX model generated to not depend on the test image, but it seems not to be the case. It seems that when processing inference on a new image, the ONNX model fails

3. What dataset did you use?
No dataset

**Environment**

```
sys.platform: linux
Python: 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.1
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMDetection: 2.7.0+04b5dea
```

**Error traceback**

With random image (`np.random.randint`)
```
File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/detectors/base.py", line 182, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/detectors/base.py", line 159, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/detectors/two_stage.py", line 199, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 248, in simple_test
    x, img_metas, proposal_list, self.test_cfg, rescale=rescale)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/roi_heads/test_mixins.py", line 93, in simple_test_bboxes
    cfg=rcnn_test_cfg)
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 223, in get_bboxes
    cfg.max_per_img)
  File "/home/sebastien/Documents/repositories/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 56, in multiclass_nms
    raise RuntimeError('[ONNX Error] Can not record NMS '
RuntimeError: [ONNX Error] Can not record NMS as it has not been executed this time
```

**Error traceback**

With different image (opposite: `255 - mmcv.imread(input_img)`)
```
Traceback (most recent call last):
  File "/home/sebastien/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sebastien/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sebastien/.vscode-server-insiders/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/sebastien/.vscode-server-insiders/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/sebastien/.vscode-server-insiders/extensions/ms-python.python-2020.11.371526539/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/sebastien/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/sebastien/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/sebastien/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sebastien/Documents/repositories/mmdetection/tools/pytorch2onnx.py", line 207, in <module>
    dataset=args.dataset)
  File "/home/sebastien/Documents/repositories/mmdetection/tools/pytorch2onnx.py", line 86, in pytorch2onnx
    {net_feed_input[0]: one_img.detach().numpy()})
  File "/home/sebastien/Documents/repositories/mmdetection/venv37/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1103' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{606,2}, requested shape:{223,2}
```

**Comment by RunningLeon** [comment]
Hi, conversion from Pytorch to ONNX is done by tracing. For detection models with NMS, we strongly suggest you use a real image with objects to do this work. Otherwise,  the exported ONNX model may be incomplete. 
Just as the asserted error suggested: 
> RuntimeError: [ONNX Error] Can not record NMS as it has not been executed this time.

You may use [netron](https://netron.app/) to double-check your ONNX model.

**Comment by SebastienLinker** [comment]
Hi @RunningLeon

Thanks for your work on this part. Let's focus on the 2nd case, i.e. 2 different images.
I've used netron but did not notice anything wrong, design looked similar.
My concern is that, when I want to process inference on the ONNX model (using a different image), then I get a runtime exception. Did you meet this problem?

```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1103' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{606,2}, requested shape:{223,2}
```

**Comment by RunningLeon** [comment]
@SebastienLinker 
This often because some tensors with a dynamic shape were traced as the ones with a constant shape while exporting to ONNX.
Suggest you find the code of defining `Reshape_1103` op in the source code and try to debug a little bit.

**Comment by RunningLeon** [comment]
BTW, it did throws RuntimeError from `Reshape_1103` in Pytorch=1.7.0, while it works fine with Pytorch=1.6.0. Pls. try with Pytorch 1.6.0.

**Comment by xyty-citibank** [comment]
@RunningLeon 
I get into  the same trouble, I wan to know how to do when occur "dynamic shape were traced as the ones with a constant shape while exporting to ONNX" ,thinks!

**Comment by xyty-citibank** [comment]
@RunningLeon ,
Hi,I get into the same trouble, I wan to know how to do when occured "dynamic shape were traced as the ones with a constant shape while exporting to ONNX" ,thanks!

**Comment by SebastienLinker** [comment]
Actually, I also had some troubles with pytorch==1.6.0
Personally, I switched to that repo, but it does not convert to ONNX: https://github.com/grimoire/mmdetection-to-tensorrt

**Comment by RunningLeon** [comment]
> @SebastienLinker
> This often because some tensors with a dynamic shape were traced as the ones with a constant shape while exporting to ONNX.
> Suggest you find the code of defining `Reshape_1103` op in the source code and try to debug a little bit.
@xyty-citibank 
Always starts with netron and then to source code.
If you have any trouble for faster-rcnn to onnx with pytorch=1.6.0, pls. posted here.

**Comment by oreo-lp** [comment]
i have the same problem too, my environment is torch ==1.7
