### ISSUE TITLE
Mask R-CNN ONNX Export at mmdet 2.7.0, how to without failing?

### ISSUE THREAD

**Issue by masotrix** [open-mmlab/mmdetection#4247]
I installed mmdet 2.7.0 and as of the Changelog https://github.com/open-mmlab/mmdetection/blob/master/docs/changelog.md, Mask R-CNN models shold be able to be exported to ONNX format but I have not been able to get predictions from the exported model

For testing the feature I downloaded the pretrained model mask_rcnn_r101_fpn_2x_coco_bbox_mAP-0.408__segm_mAP-0.366_20200505_071027-14b391c7.pth from https://github.com/open-mmlab/mmdetection/tree/master/configs/mask_rcnn, put inside a folder named "checkpoints" inside ~/mmdetection and there I used
`python tools/pytorch2onnx.py configs/mask_rcnn/mask_rcnn_r101_fpn_2x_coco.py checkpoints/mask_rcnn_r101_fpn_2x_coco_bbox_mAP-0.408__segm_mAP-0.366_20200505_071027-14b391c7.pth --input-img demo/demo.jpg --verify --show`

When running it it first says "Successfully exported ONNX model: tmp.onnx" but at the end it fails saying
```
onnxruntime output names: ['boxes', 'labels'],             output shapes: [(62, 5), (62,)]
Traceback (most recent call last):
  File "../mmTools/pytorch2onnx.py", line 193, in <module>
    pytorch2onnx(
  File "../mmTools/pytorch2onnx.py", line 121, in pytorch2onnx
    np.testing.assert_allclose(
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 759, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

(shapes (51, 5), (49, 5) mismatch)
 x: array([[1.158027e+03, 2.130080e+02, 1.205723e+03, 2.563616e+02,
        9.916629e-01],
       [9.157939e+02, 2.070513e+02, 9.928231e+02, 2.445640e+02,...
 y: array([[1.158027e+03, 2.130080e+02, 1.205723e+03, 2.563616e+02,
        9.916627e-01],
       [9.157939e+02, 2.070513e+02, 9.928231e+02, 2.445640e+02,...
```

I thought it could be some minor issue so I went to test the exported model using 
```import onnxruntime as rt, numpy as np, sys
import skimage.transform, skimage.io

testIm='./demo/demo.jpg';
im = skimage.io.imread(testIm);

# Preprocess
im = np.rollaxis(im,2,0);
# COCO pretrained models seem to have 3x800x1216 input dimensions as
# shown by running script given by accepted answer at 
# https://stackoverflow.com/questions/56734576/find-input-shape-from-onnx-file
im = skimage.transform.resize(im/255, (3,800,1216), anti_aliasing=True)
im = im[np.newaxis,:,:,:]
#print(im.shape); sys.exit();
im = im.astype(np.float32);

sess = rt.InferenceSession("tmp.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred = sess.run(None, {input_name: im})[0]

print(pred);
```

Which also fails saying
```
2020-12-07 22:30:05.631629881 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_1222' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{432,2}, requested shape:{470,2}

Traceback (most recent call last):
  File "cocoPredict.py", line 18, in <module>
    pred = sess.run(None, {input_name:im})
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_1222' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{432,2}, requested shape:{470,2}
```

Does this mean that ONNX is still not fully suported for Mask R-CNN or something else should be done while doing the export to ONNX?

**Comment by ZwwWayne** [comment]
Please @RunningLeon have a check.

**Comment by RunningLeon** [comment]
@masotrix Hi,
Pytorch2ONNX of Mask-RCNN in MMCV is not fully supported up to now.
Reasons:
1. `F.grid_sample` cannot be converted right now;
2. Minor differences of `nms` between Pytorch and ONNX Runtime may lead to unmatched results.(as AssertionError says);
2. Sometimes dynamic shapes may be traced as constant shapes and exported to ONNX(as ONNXRuntimeError suggests: `Reshape_1222` were constant shape), which is weird and not fully solved;
