### ISSUE TITLE
Error with train detection

### ISSUE THREAD

**Issue by attashe** [open-mmlab/mmdetection#4254]
When I try train config based on __base__/coco_detection.py my custom dataset, i got this error:

`
2020-12-08 21:06:16,257 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 234, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 168, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 164, in forward_train
    **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 128, in forward_train
    gt_masks, img_metas)
  File "/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 188, in _mask_forward_train
    self.train_cfg)
  File "/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 134, in get_targets
    gt_masks, rcnn_train_cfg)
  File "/mmdetection/mmdet/core/mask/mask_target.py", line 24, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable
`

I checked my annotation json and it seems ok, fields like url and date are empty, but I think it's not a problem.

annotation.json:

`
"images":
....
{'license': 3,
  'file_name': '22968_IMG_0103.jpg',
  'coco_url': '',
  'height': 960,
  'width': 1280,
  'date_captured': '2013-11-14 11:18:45',
  'flickr_url': '',
  'id': 1072055},
 {'license': 3,
  'file_name': '119322_IMG_0159.jpg',
  'coco_url': '',
  'height': 720,
  'width': 1280,
  'date_captured': '2013-11-14 11:18:45',
  'flickr_url': '',
  'id': 1072056}],
"annotations": 
....
{'segmentation': [656.0, 324.0, 948.0, 324.0, 948.0, 512.0, 656.0, 512.0],
  'area': 54896.0,
  'iscrowd': 0,
  'image_id': 1002385,
  'bbox': [656.0, 324.0, 292.0, 188.0],
  'category_id': 11,
  'id': 10087120},
 {'segmentation': [670.0, 496.0, 894.0, 496.0, 894.0, 605.0, 670.0, 605.0],
  'area': 24416.0,
  'iscrowd': 0,
  'image_id': 1004819,
  'bbox': [670.0, 496.0, 224.0, 109.0],
  'category_id': 11,
  'id': 10087121},
....
`

**Comment by attashe** [comment]
I found working config, closing issue

**Comment by tingfengwanxiao** [comment]
hello,I meet the same question,so,how you solve the problems?

**Comment by fangxu622** [comment]
I have the same questions.
Have you solved it?

**Comment by fangxu622** [comment]
just occurs on cascade-rcnn series config file `~and faster rcnn is ok
