### ISSUE TITLE
Cuda error when saving first checkpoint.

### ISSUE THREAD

**Issue by roachsinai** [open-mmlab/mmdetection#4267]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Goes well in first training epoch, but when saving checkpoint get `ETA:Traceback (most recent call last)` saying: `RuntimeError: CUDA error: no kernel image is available for execution on the device (NMSCUDAKernelLauncher at ./mmcv/ops/csrc/pytorch/nms_cuda.cu:50)`

**Error Details**:

```
2020-12-09 17:39:01,532 - mmdet - INFO - load model from: open-mmlab://vgg16_caffe
2020-12-09 17:39:01,594 - mmdet - WARNING - The model and loaded state dict do not match exactly

missing keys in source state_dict: extra.0.weight, extra.0.bias, extra.1.weight, extra.1.bias, extra.2.weight, extra.2.bias, extra.3.weight, extra.3.bias, extra.4.weight, extra.4.bias, extra.5.weight, extra.5.bias, extra.6.weight, extra.6.bias, extra.7.weight, extra.7.bias, l2_norm.weight

2020-12-09 17:39:07,154 - mmdet - INFO - Start running, host: roach@hmanx, work_dir: /home/roach/code/Git/mmdetection/experiment/ssd300_voc
2020-12-09 17:39:07,155 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
2020-12-09 17:44:27,545 - mmdet - INFO - Epoch [1][50/620]      lr: 9.890e-05, eta: 1 day, 2:06:15, time: 6.337, data_time: 0.064, memory: 1582, loss_cls: 8.4968, loss_bbox: 2.9340, loss: 11.4308
2020-12-09 17:49:24,424 - mmdet - INFO - Epoch [1][100/620]     lr: 1.988e-04, eta: 1 day, 1:11:32, time: 5.935, data_time: 0.083, memory: 1582, loss_cls: 4.7074, loss_bbox: 2.8221, loss: 7.5296
2020-12-09 17:54:25,056 - mmdet - INFO - Epoch [1][150/620]     lr: 2.987e-04, eta: 1 day, 0:56:17, time: 6.012, data_time: 0.085, memory: 1582, loss_cls: 4.2257, loss_bbox: 2.6309, loss: 6.8566
2020-12-09 17:59:27,580 - mmdet - INFO - Epoch [1][200/620]     lr: 3.986e-04, eta: 1 day, 0:48:28, time: 6.050, data_time: 0.087, memory: 1582, loss_cls: 3.7011, loss_bbox: 2.5217, loss: 6.2228
2020-12-09 18:04:27,079 - mmdet - INFO - Epoch [1][250/620]     lr: 4.985e-04, eta: 1 day, 0:38:51, time: 5.990, data_time: 0.085, memory: 1582, loss_cls: 3.3513, loss_bbox: 2.4976, loss: 5.8489
2020-12-09 18:09:24,310 - mmdet - INFO - Epoch [1][300/620]     lr: 5.984e-04, eta: 1 day, 0:28:55, time: 5.944, data_time: 0.085, memory: 1582, loss_cls: 3.2767, loss_bbox: 2.3835, loss: 5.6601
2020-12-09 18:14:23,563 - mmdet - INFO - Epoch [1][350/620]     lr: 6.983e-04, eta: 1 day, 0:21:51, time: 5.986, data_time: 0.085, memory: 1582, loss_cls: 3.0469, loss_bbox: 2.3051, loss: 5.3519
2020-12-09 18:19:22,589 - mmdet - INFO - Epoch [1][400/620]     lr: 7.982e-04, eta: 1 day, 0:15:07, time: 5.980, data_time: 0.083, memory: 1582, loss_cls: 2.9813, loss_bbox: 2.2719, loss: 5.2533
2020-12-09 18:24:22,772 - mmdet - INFO - Epoch [1][450/620]     lr: 8.981e-04, eta: 1 day, 0:09:23, time: 6.003, data_time: 0.084, memory: 1582, loss_cls: 2.9933, loss_bbox: 2.1929, loss: 5.1862
2020-12-09 18:29:21,360 - mmdet - INFO - Epoch [1][500/620]     lr: 9.980e-04, eta: 1 day, 0:03:03, time: 5.972, data_time: 0.085, memory: 1582, loss_cls: 3.0064, loss_bbox: 2.0350, loss: 5.0414
2020-12-09 18:34:19,849 - mmdet - INFO - Epoch [1][550/620]     lr: 1.000e-03, eta: 23:56:56, time: 5.970, data_time: 0.084, memory: 1582, loss_cls: 2.9340, loss_bbox: 2.0482, loss: 4.9821
2020-12-09 18:39:18,917 - mmdet - INFO - Epoch [1][600/620]     lr: 1.000e-03, eta: 23:51:13, time: 5.981, data_time: 0.084, memory: 1582, loss_cls: 2.9554, loss_bbox: 1.9417, loss: 4.8972
2020-12-09 18:41:14,140 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/4952, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/home/roach/code/Git/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/roach/code/Git/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 142, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/roach/code/Git/mmdetection/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/roach/code/Git/mmdetection/mmdet/models/detectors/base.py", line 182, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/roach/code/Git/mmdetection/mmdet/models/detectors/base.py", line 159, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/roach/code/Git/mmdetection/mmdet/models/detectors/single_stage.py", line 115, in simple_test
    *outs, img_metas, rescale=rescale)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/roach/code/Git/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/roach/code/Git/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 661, in _get_bboxes_single
    cfg.max_per_img)
  File "/home/roach/code/Git/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 64, in multiclass_nms
    dets, keep = batched_nms(bboxes, scores, labels, nms_cfg)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/ops/nms.py", line 19, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device (NMSCUDAKernelLauncher at ./mmcv/ops/csrc/pytorch/nms_cuda.cu:50)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fe60677a813 in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: NMSCUDAKernelLauncher(at::Tensor, at::Tensor, float, int) + 0x741 (0x7fe5f56b4438 in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #2: nms_cuda(at::Tensor, at::Tensor, float, int) + 0x5b (0x7fe5f5751ecb in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #3: nms(at::Tensor, at::Tensor, float, int) + 0x166 (0x7fe5f5752a86 in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x151146 (0x7fe5f5730146 in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x147d9c (0x7fe5f5726d9c in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so)
frame #6: _PyMethodDef_RawFastCallKeywords + 0x2ec (0x5558633be6fc in /home/roach/.pyenv/versions/nn/bin/python)
frame #7: _PyCFunction_FastCallKeywords + 0x2f (0x5558633be7ef in /home/roach/.pyenv/versions/nn/bin/python)
frame #8: <unknown function> + 0x59c59 (0x5558633a4c59 in /home/roach/.pyenv/versions/nn/bin/python)
frame #9: _PyEval_EvalFrameDefault + 0x2502 (0x5558633a72b2 in /home/roach/.pyenv/versions/nn/bin/python)
frame #10: <unknown function> + 0x587a3 (0x5558633a37a3 in /home/roach/.pyenv/versions/nn/bin/python)
frame #11: _PyFunction_FastCallDict + 0x2f8 (0x5558633be208 in /home/roach/.pyenv/versions/nn/bin/python)
frame #12: THPFunction_apply(_object*, _object*) + 0x936 (0x7fe648af1b86 in /home/roach/.pyenv/versions/nn/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #13: _PyMethodDef_RawFastCallKeywords + 0x329 (0x5558633be739 in /home/roach/.pyenv/versions/nn/bin/python)
frame #14: _PyCFunction_FastCallKeywords + 0x2f (0x5558633be7ef in /home/roach/.pyenv/versions/nn/bin/python)
frame #15: <unknown function> + 0x59c59 (0x5558633a4c59 in /home/roach/.pyenv/versions/nn/bin/python)
frame #16: _PyEval_EvalFrameDefault + 0x58e3 (0x5558633aa693 in /home/roach/.pyenv/versions/nn/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #18: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #19: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #20: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #21: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #22: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #23: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #24: _PyFunction_FastCallKeywords + 0x89 (0x5558633be2a9 in /home/roach/.pyenv/versions/nn/bin/python)
frame #25: <unknown function> + 0x59a35 (0x5558633a4a35 in /home/roach/.pyenv/versions/nn/bin/python)
frame #26: _PyEval_EvalFrameDefault + 0x2713 (0x5558633a74c3 in /home/roach/.pyenv/versions/nn/bin/python)
frame #27: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #28: _PyFunction_FastCallKeywords + 0x89 (0x5558633be2a9 in /home/roach/.pyenv/versions/nn/bin/python)
frame #29: <unknown function> + 0x59a35 (0x5558633a4a35 in /home/roach/.pyenv/versions/nn/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x2713 (0x5558633a74c3 in /home/roach/.pyenv/versions/nn/bin/python)
frame #31: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #32: _PyFunction_FastCallKeywords + 0x89 (0x5558633be2a9 in /home/roach/.pyenv/versions/nn/bin/python)
frame #33: <unknown function> + 0x59a35 (0x5558633a4a35 in /home/roach/.pyenv/versions/nn/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x58e3 (0x5558633aa693 in /home/roach/.pyenv/versions/nn/bin/python)
frame #35: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #36: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #37: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #38: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #39: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #40: _PyObject_Call_Prepend + 0xed (0x5558633c0a6d in /home/roach/.pyenv/versions/nn/bin/python)
frame #41: PyObject_Call + 0x6a (0x5558633bf36a in /home/roach/.pyenv/versions/nn/bin/python)
frame #42: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #43: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #44: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #45: _PyObject_Call_Prepend + 0xed (0x5558633c0a6d in /home/roach/.pyenv/versions/nn/bin/python)
frame #46: PyObject_Call + 0x6a (0x5558633bf36a in /home/roach/.pyenv/versions/nn/bin/python)
frame #47: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #48: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #49: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #50: _PyObject_Call_Prepend + 0xed (0x5558633c0a6d in /home/roach/.pyenv/versions/nn/bin/python)
frame #51: PyObject_Call + 0x6a (0x5558633bf36a in /home/roach/.pyenv/versions/nn/bin/python)
frame #52: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #53: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #54: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #55: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #56: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #57: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #58: _PyObject_Call_Prepend + 0xed (0x5558633c0a6d in /home/roach/.pyenv/versions/nn/bin/python)
frame #59: PyObject_Call + 0x6a (0x5558633bf36a in /home/roach/.pyenv/versions/nn/bin/python)
frame #60: _PyEval_EvalFrameDefault + 0x21ee (0x5558633a6f9e in /home/roach/.pyenv/versions/nn/bin/python)
frame #61: _PyEval_EvalCodeWithName + 0x920 (0x55586346a240 in /home/roach/.pyenv/versions/nn/bin/python)
frame #62: _PyFunction_FastCallDict + 0x13f (0x5558633be04f in /home/roach/.pyenv/versions/nn/bin/python)
frame #63: _PyObject_Call_Prepend + 0xed (0x5558633c0a6d in /home/roach/.pyenv/versions/nn/bin/python)
```

**Reproduction**

1. What command or script did you run?

```
pyg tools/train.py configs/pascal_voc/ssd300_voc0712.py --gpus 1 --work-dir experiment/ssd300_voc
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I use SSD300 to train VOC2007 on my Computer and only train two class. Check the diff:

![image](https://user-images.githubusercontent.com/9500049/101625488-6f124980-3a56-11eb-8f46-4775635bfa35.png)
![image](https://user-images.githubusercontent.com/9500049/101625510-78031b00-3a56-11eb-9f61-bc117f7ff41a.png)

3. What dataset did you use?

VOC2007

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```
(nn) hmanx ~/c/G/mmdetection master » pyg mmdet/utils/collect_env.py
sys.platform: linux
Python: 3.7.4 (default, Apr 19 2020, 18:33:26) [GCC 9.3.0]
CUDA available: True
GPU 0: GeForce GT 740M
CUDA_HOME: /opt/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (GCC) 10.2.0
PyTorch: 1.3.0+cu92
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.4.1+cu92
OpenCV: 4.1.2
MMCV: 1.2.1
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 9.2
MMDetection: 2.7.0+bec3fc1
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

Installed pytorch by: `pip install torch===1.3.0 torchvision===0.4.1 -f https://download.pytorch.org/whl/torch_stable.html -i https://pypi.tuna.tsinghua.edu.cn/simple`

```
(nn) hmanx ~/c/G/m/experiment master » pip list | grep torch                                                                               
torch                1.3.0+cu92
torchvision          0.4.1+cu92
```

Installed mmcv by: `pip install mmcv-full==latest+torch1.3.0+cu92 -f https://download.openmmlab.com/mmcv/dist/index.html`

My GPU is GeForce GT 740M: compute capability 3.0.

---

```
(nn) hmanx ~/c/G/m/experiment master » tree
.
└── ssd300_voc
    ├── 20201209_165039.log
    ├── 20201209_165222.log
    ├── 20201209_165539.log
    ├── 20201209_165550.log
    ├── 20201209_170122.log
    ├── 20201209_170122.log.json
    ├── 20201209_173637.log
    ├── 20201209_173900.log
    ├── 20201209_173900.log.json
    ├── epoch_1.pth
    ├── latest.pth -> epoch_1.pth
    └── ssd300_voc0712.py

1 directory, 12 files
(nn) hmanx ~/c/G/m/experiment master » pwd                           
/home/roach/code/Git/mmdetection/experiment
```

Thanks in advance!

**Comment by ZwwWayne** [comment]
Hi @roachsinai ,
MMCV-Full does not support compute capability 3.0 in CUDA 9.2 due to some incompatibility issues. You may upgrade to use CUDA 10.0.

**Comment by roachsinai** [comment]
@ZwwWayne Thanks for reply!

Just wanna make sure mmcv not support compute capability 3.0? or CUDA9.2?

**Comment by ZwwWayne** [comment]
MMCV does not support compute capability 3.0 for CUDA 9.2, but support 3.0 for other versions, e.g., CUDA 10.0.

**Comment by roachsinai** [comment]
@ZwwWayne Thanks!
