### ISSUE TITLE
PicklingError on Customized Dataset

### ISSUE THREAD

**Issue by bjanfeshan** [open-mmlab/mmdetection#4290]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I am trying to train a mask-rcnn model on a customized dataset, similar to what is explained in the documentation, but I get PicklingError. When I run the code on the same config file with the Balloon dataset it works but, when I replace the json file with mine I get this error.

**Reproduction**

1. What command or script did you run?

```none
python tools/train.py /mmdetection/configs/ssd_coupler/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_coupler.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I modified this config file: mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_coupler.py
3. What dataset did you use?
a custom data set

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True
GPU 0: Quadro P4000
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.1
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 11.1
MMDetection: 2.7.0+fb287b1
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
used conda to install PyTorch

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
```

Here is an example of my json file:

`{
    "images": [
        {
            "id": 1,
            "file_name": "0a3d5a6b-9efd-480d-a851-ced08845d9d5.jpg",
            "width": 2000,
            "height": 1024
        }
    ],
    "annotations": [
        {
            "area": 330720,
            "iscrowd": 0,
            "id": 1,
            "image_id": 1,
            "category_id": 2,
            "segmentation": [
                [
                    681,
                    947,
                    1720,
                    947,
                    1720,
                    630,
                    681,
                    630
                ]
            ],
            "bbox": [
                681,
                630,
                1040,
                318
            ]
        }
    ],
    "categories": [
        {
            "name": "coupler",
            "id": 1
        },
        {
            "name": "truck",
            "id": 2
        }
    ]
}`
**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by yhcao6** [comment]
Can you try to debug with setting `num_gpu=1, samples_per_gpu=1, workers_per_gpu=0` to see if it will hint you which line raises such an error?

**Comment by bjanfeshan** [comment]
where exactly I should change these settings?

**Comment by yhcao6** [comment]
https://github.com/open-mmlab/mmdetection/blob/43b1909221179395ebd36edd24540940274ab9c9/configs/_base_/datasets/coco_detection.py#L31-L32

**Comment by bjanfeshan** [comment]
thanks for the prompt response. where I can set `num_gpu`?
after changing `samples_per_gpu=1`  and `workers_per_gpu=1` in coco_detection.py I got this:
`Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError`

**Comment by yhcao6** [comment]
`workers_per_gpu=0` and debug with this command, default is 1 GPU:
python tools/train.py [your_config]

**Comment by bjanfeshan** [comment]
`2020-12-14 00:29:59,031 - mmdet - INFO - Start running, host: bita@psxi1mzh8, work_dir: /home/bita/mmdetection/work_dirs/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_coupler
2020-12-14 00:29:59,032 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError
Traceback (most recent call last):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numpy.core._exceptions.UFuncTypeError'>: it's not the same object as numpy.core._exceptions.UFuncTypeError`

**Comment by yhcao6** [comment]
python tools/train.py [your_cfg] --cfg-options data.samples_per_gpu=1 data.workers_per_gpu=0

**Comment by bjanfeshan** [comment]
`Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 170, in main
    train_detector(
  File "/home/bita/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bita/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/bita/mmdetection/mmdet/datasets/custom.py", line 192, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/bita/mmdetection/mmdet/datasets/custom.py", line 215, in prepare_train_img
    return self.pipeline(results)
  File "/home/bita/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/bita/mmdetection/mmdet/datasets/pipelines/transforms.py", line 303, in __call__
    self._resize_masks(results)
  File "/home/bita/mmdetection/mmdet/datasets/pipelines/transforms.py", line 249, in _resize_masks
    results[key] = results[key].rescale(results['scale'])
  File "/home/bita/mmdetection/mmdet/core/mask/structures.py", line 547, in rescale
    rescaled_masks = self.resize((new_h, new_w))
  File "/home/bita/mmdetection/mmdet/core/mask/structures.py", line 562, in resize
    p[0::2] *= w_scale
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'`

**Comment by yhcao6** [comment]
Yes, it tells you where the error comes from and you can fix it yourself now.

**Comment by bjanfeshan** [comment]
thanks! it's fixed!
