### ISSUE TITLE
Pytorch2onnx Problem 

### ISSUE THREAD

**Issue by HzzzW** [open-mmlab/mmdetection#4324]
When I am **converting faster_rcnn model to onnx**. An error occurs:

I just run
```none
 python tools/pytorch2onnx.py   configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py  checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
```

**Environment**

sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
GPU 0: GeForce GTX 1080
PyTorch: 1.6.0

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.2.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.6.0+040d5ea

**Results**
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 203, in <module>
    dataset=args.dataset)
  File "tools/pytorch2onnx.py", line 52, in pytorch2onnx
    opset_version=opset_version)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 787, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/utils.py", line 745, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/team613/miniconda3/envs/open-mmlab1126/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 109, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator new_full to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

**so how can i solve it? Looking forward to your help**

**Comment by RunningLeon** [comment]
Please update mmcv to >= 1.2.1, or compile from source. Actually, `new_full` is supported from there.

**Comment by HzzzW** [comment]
@RunningLeon **Thank you very much for your help！**I have updated mmcv to  1.2.2, but another error occurs:
Traceback (most recent call last):
  File "/home/team613/houzhiwen-mmdetection/tools/pytorch2onnx.py", line 142, in <module>
    normalize_cfg=normalize_cfg)
  File "/home/team613/houzhiwen-mmdetection/tools/pytorch2onnx.py", line 43, in pytorch2onnx
    opset_version=opset_version)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/__init__.py", line 412, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/team613/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/team613/mmdetection/mmdet/models/detectors/base.py", line 170, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/team613/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/team613/mmdetection/mmdet/models/detectors/two_stage.py", line 207, in simple_test
    x, proposal_list, img_metas, rescale=rescale)  #for visualization
  File "/home/team613/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 252, in simple_test
    for i in range(len(det_bboxes))
  File "/home/team613/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 252, in <listcomp>
    for i in range(len(det_bboxes))
  File "/home/team613/mmdetection/mmdet/core/bbox/transforms.py", line 114, in bbox2result
    bboxes = bboxes.cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

**I want to know what to do next, thank you!**

**Comment by RunningLeon** [comment]
Please use mmdet=2.7.0. Because `pytorch2onnx` is experimental and may change fast, strongly suggest you always try with the lastest mmcv and mmdet, and build from source.

**Comment by HzzzW** [comment]
@RunningLeon Thank you very much!
