### ISSUE TITLE
pip install mmcv-full

### ISSUE THREAD

**Issue by HzzzW** [open-mmlab/mmdetection#4331]
**When i just run** 

```none
pip install mmcv-full==latest+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html
```
**An error occurs**

ERROR: Exception:
Traceback (most recent call last):
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'mmcv-full'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 321, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 96, in __bool__
    return any(self)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 20, in _deduplicated_by_version
    for candidate in candidates:
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 218, in iter_index_candidates
    version=ican.version,
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 151, in _make_candidate_from_link
    link, template, factory=self, name=name, version=version,
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 295, in __init__
    wheel_version = Version(wheel.version)
  File "/home/team613/miniconda3/envs/mm3d-3/lib/python3.7/site-packages/pip/_vendor/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip._vendor.packaging.version.InvalidVersion: Invalid version: 'latest+torch1.6.0+cu101'

**My conda list**

_libgcc_mutex             0.1                        main    defaults
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
ca-certificates           2020.12.8            h06a4308_0    defaults
certifi                   2020.12.5        py37h06a4308_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cython                    0.29.21                  pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0    defaults
intel-openmp              2020.2                      254    defaults
jpeg                      9b                   h024ee3a_2    defaults
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
lz4-c                     1.9.2                heb0550a_3    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py37he8ac12f_0    defaults
mkl_fft                   1.2.0            py37h23d657b_0    defaults
mkl_random                1.1.1            py37h0573a6f_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.10.2           py37hff7bd54_0    defaults
numpy                     1.19.2           py37h54aff64_0    defaults
numpy-base                1.19.2           py37hfa32c7d_0    defaults
olefile                   0.46                     py37_0    defaults
opencv-python             4.4.0.46                 pypi_0    pypi
openssl                   1.1.1i               h27cfd23_0    defaults
pillow                    8.0.1            py37he98fc37_0    defaults
pip                       20.3.3           py37h06a4308_0    defaults
pytest-runner             5.2                      pypi_0    pypi
python                    3.7.9                h7579374_0    defaults
pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
setuptools                51.0.0           py37h06a4308_2    defaults
six                       1.15.0           py37h06a4308_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
torchvision               0.7.0                py37_cu101    pytorch
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yapf                      0.30.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults

**So how can i solve it ? Looking forward to your help!**

**Comment by xvjiarui** [comment]
Hi @HzzzW 
Please follow **pip >= 20.3** section in this [link](https://github.com/open-mmlab/mmcv#installation).
