### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by xiaowanzizz** [open-mmlab/mmdetection#4335]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Traceback (most recent call last):
  File "demo/image_demo.py", line 26, in <module>
    main()
  File "demo/image_demo.py", line 20, in main
    result = inference_detector(model, args.img)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/apis/inference.py", line 123, in inference_detector
    result = model(return_loss=False, rescale=True, **data)[0]
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/detectors/base.py", line 182, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/detectors/base.py", line 159, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 194, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/dense_heads/rpn_test_mixin.py", line 36, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/dense_heads/anchor_head.py", line 571, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmdet-2.7.0-py3.7.egg/mmdet/models/dense_heads/rpn_head.py", line 167, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 259, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 113, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset)
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/mmcv/ops/nms.py", line 19, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Reproduction**

1. What command or script did you run?

```
python demo/image_demo.py demo/demo.jpg configs/mask_rcnn/mask_rcnn_r50_fpn_2x_coco.py checkpoints/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.pth 

```

**Environment**

Python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 3070
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu110
OpenCV: 4.4.0
MMCV: 1.2.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.7.0+

**Comment by silverbulle** [comment]
I encountered the same problem, I also encountered this problem on 3070，hope to get some help

**Comment by sunbin1993** [comment]
I encountered the same problem on Tesla P100 and CUDA Version is 10.2

**Comment by qjc7777** [comment]
I encountered the same problem, I also encountered this problem on 3080，hope to get some help

**Comment by ZwwWayne** [comment]
This is because of the incompatibility between your environment and torch/CUDA/mmcv. Please check [this FAQ about CUDA environment](https://mmdetection.readthedocs.io/en/latest/faq.html#pytorch-cuda-environment).

**Comment by Swaggyyoung03** [comment]
I think my idea might help you.
I met the same problem and my device was RTX 3080.
I tried to use this command pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html which was copied from https://pytorch.org/get-started/locally/. 
try to reinstall the torch and the problem might been solved.

**Comment by xiaowanzizz** [comment]
@Swaggyyoung03    thank you，This problem seems to be due to the problem of gpu computing power and library support. In pytorch1.7.0, it can also be solved by installing 8.0 computing power mmcv. Now pytorch1.7.1 should solve this problem

**Comment by rojas70** [comment]
@xiaowanzizz can you give more details about mmcv? How is it installed properly?

**Comment by fcakyon** [comment]
@SauBuen what is your gpu and os? If Windows and RTX3XXX refer to this issue: https://github.com/open-mmlab/mmcv/issues/1623
