### ISSUE TITLE
batch_size should be a positive integeral value, but got batch_size=0

### ISSUE THREAD

**Issue by wizholy** [open-mmlab/mmdetection#435]
when train my own dataset, some errors happend.
Traceback (most recent call last):
  File "tools/train.py", line 90, in <module>
    main()
  File "tools/train.py", line 86, in main
    logger=logger)
  File "/home/wizard/anaconda3/envs/pytorch041/lib/python3.6/site-packages/mmdet-0.5.7+unknown-py3.6.egg/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/wizard/anaconda3/envs/pytorch041/lib/python3.6/site-packages/mmdet-0.5.7+unknown-py3.6.egg/mmdet/apis/train.py", line 107, in _non_dist_train
    dist=False)
  File "/home/wizard/anaconda3/envs/pytorch041/lib/python3.6/site-packages/mmdet-0.5.7+unknown-py3.6.egg/mmdet/datasets/loader/build_loader.py", line 42, in build_dataloader
    **kwargs)
  File "/home/wizard/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 487, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/home/wizard/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 128, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integeral value, but got batch_size=0

**Comment by zyx1213271098** [comment]
Have you solved it? I also encountered the same problem.
ValueError: batch_size should be a positive integeral value, but got batch_size=0

**Comment by sloan96** [comment]
do you solve it? Can tell me how to do ?

**Comment by sloan96** [comment]
I solved. --gpus means the number of gpu, I thought it's a specific gpu,--gpu 1 nor 0 works!
Meanwhile,my custom datasets like VOC have no difficult,so I need edit mmdet/datasets/xml_style.py.
