### ISSUE TITLE
NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by QY1994-0919** [open-mmlab/mmdetection#4395]
Traceback (most recent call last):
  File "/home/10102010/qy/Projects_qy/mmd1.1.0/D2Det-master/tools/test.py", line 179, in <module>
    main()
  File "/home/10102010/qy/Projects_qy/mmd1.1.0/D2Det-master/tools/test.py", line 118, in main
    cfg = mmcv.Config.fromfile(args.config)
  File "/home/10102010/qy/packges/mmcv-0.4.4/mmcv/utils/config.py", line 152, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/home/10102010/qy/packges/mmcv-0.4.4/mmcv/utils/config.py", line 91, in _file2dict
    mod = import_module('_tempconfig')
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd1.1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpgf_oho6y/_tempconfig.py", line 2, in <module>
NameError: name 'os' is not defined

**Comment by kellenf** [comment]
something wrong with your config file

**Comment by ZwwWayne** [comment]
The config file seems to use os but os is not imported or declared before.
