### ISSUE TITLE
Bug in the resume option?

### ISSUE THREAD

**Issue by tsunehiro-kashiwagi** [open-mmlab/mmdetection#4423]
When resuming training, the validation process will run and an error will occur.

Currently, when resuming, the --no-validate option is used to restart the training.

```
Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 181, in main
    meta=meta)
  File "mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "mmdetection/mmdet/core/evaluation/eval_hooks.py", line 116, in before_train_epoch
    self.after_train_epoch(runner)
  File "mmdetection/mmdet/core/evaluation/eval_hooks.py", line 150, in after_train_epoch
    last_ckpt = runner.meta['hook_msgs']['last_ckpt']
KeyError: 'last_ckpt'
```

**Comment by ZwwWayne** [comment]
This might be related to the refactoring of Evalhook. Please @xvjiarui  have a look. Also, FYI to @dreamerlin since some related refactoring is ongoing.

**Comment by xvjiarui** [comment]
Hi @tsunehiro-kashiwagi 
Could you please provide your config file for more information? 
Btw, note that, the interval of checkpoint hook should divide eval hook.

**Comment by tsunehiro-kashiwagi** [comment]
There are preparations to be made to provide the entire config file, and I don't know how long it will take to provide it, so I will describe the configuration of the part that I think is relevant to this case first.


`evaluation = dict(interval=1, start=3, metric=['bbox', 'segm'], save_best='segm_mAP')
`
`checkpoint_config = dict(interval=1)
`
`resume_from = /path/to/ckpt.pth
`

`resume_from` of config is specified by `--resume` option in tools/train.py.
