### ISSUE TITLE
RuntimeError: CUDA error: a PTX JIT compilation failed

### ISSUE THREAD

**Issue by Smoothing97** [open-mmlab/mmdetection#447]
I install the mmdetection AND test:

`import mmcv
from mmcv.runner import load_checkpoint
from mmdet.models import build_detector
from mmdet.apis import inference_detector, show_result

cfg = mmcv.Config.fromfile('/home/dassein/mmdetection/configs/faster_rcnn_r50_fpn_1x.py')
cfg.model.pretrained = None

model = build_detector(cfg.model, test_cfg=cfg.test_cfg)
_ = load_checkpoint(model, 'faster_rcnn_r50_fpn_1x_20181010-3d1b3351.pth')

img = mmcv.imread('test.jpg')
result = inference_detector(model, img, cfg)
show_result(img, result)`

Error:
Traceback (most recent call last):                                                 
File "testimg.py", line 15, in                                             
for i, result in enumerate(inference_detector(model, imgs, cfg, device='cuda :0')):                                                                             File "/home/bishe/mmdetection-master/mmdet/apis/inference.py", line 45,  in inference_detector                                                               
model = model.to(device)                                                       
File "/home/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torc h/nn/modules/module.py", line 381, in to                                             
return self._apply(convert)                                                    
File "/home/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torc h/nn/modules/module.py", line 187, in _apply                                         
module._apply(fn)                                                              
File "/home/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torc h/nn/modules/module.py", line 187, in _apply 
module._apply(fn)                                                              
File "/home/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torc h/nn/modules/module.py", line 193, in _apply                                         
param.data = fn(param.data)                                                    
File "/home/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torc h/nn/modules/module.py", line 379, in convert                                        
return t.to(device, dtype if t.is_floating_point() else None, non_blocking)  
RuntimeError: CUDA error: a PTX JIT compilation failed

**SO HOW TO SOLVE:RuntimeError: CUDA error: a PTX JIT compilation failed???**

**my env:
4x GTX1080
anaconda 4.6.7
python 3.6.7
pytorch 1.0.1
mmcv 0.2.5
opencv 3.4.4**

**Comment by Smoothing97** [comment]
done!
cuz there are both cuda9.1 cuda8.0 in my env,check /usr/local is useful：）
