### ISSUE TITLE
I added my own SARDataset in dataset __init__.py, but still reported this error. Ask for your help

### ISSUE THREAD

**Issue by 237014845** [open-mmlab/mmdetection#448]
python train.py  '/home/hs/hs/237014845/HuaWei/mmdetection-master/configs/pascal_voc/ssd300_sar.py'  --work_dir '/home/hs/hs/237014845/HuaWei/mmdetection-master/weights/SAR'  
2019-03-28 21:17:53,092 - INFO - Distributed training: False
2019-03-28 21:17:53,248 - INFO - load model from: open-mmlab://vgg16_caffe
2019-03-28 21:17:53,297 - WARNING - missing keys in source state_dict: extra.6.weight, extra.0.bias, extra.4.bias, extra.4.weight, extra.3.weight, extra.2.weight, extra.3.bias, extra.1.weight, l2_norm.weight, extra.1.bias, extra.2.bias, extra.5.weight, extra.7.bias, extra.6.bias, extra.0.weight, extra.5.bias, extra.7.weight

Traceback (most recent call last):
  File "train.py", line 94, in <module>
    main()
  File "train.py", line 83, in main
    train_dataset = get_dataset(cfg.data.train)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+unknown-py3.6.egg/mmdet/datasets/utils.py", line 80, in get_dataset
    get_dataset(data_cfg['dataset']), data_cfg['times'])
  File "/home/hs/anaconda3/lib/python3.6/site-packages/mmdet-0.6rc0+unknown-py3.6.egg/mmdet/datasets/utils.py", line 110, in get_dataset
    dset = obj_from_dict(data_info, datasets)
  File "/home/hs/anaconda3/lib/python3.6/site-packages/mmcv/runner/utils.py", line 68, in obj_from_dict
    obj_type = getattr(parrent, obj_type)
AttributeError: module 'mmdet.datasets' has no attribute 'SARDataset'

**Comment by OceanPang** [comment]
@237014845 Please refer to the notice in [INSTALL.md](https://github.com/open-mmlab/mmdetection/blob/master/INSTALL.md).
