### ISSUE TITLE
tmp file error.

### ISSUE THREAD

**Issue by YunhaoLee** [open-mmlab/mmdetection#4490]
Hi, I got this error after CTRL+C to exit the test program. After this error occurred, I restarted docker to stop the program that did not completely exit and emptied the tmp folder, but this error still exists regardless of training or testing. I would be very grateful if you can give some suggestions for solutions！

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 89, in main
    cfg = Config.fromfile(args.config)
  File "/mmcv/mmcv/utils/config.py", line 251, in fromfile
    use_predefined_variables)
  File "/mmcv/mmcv/utils/config.py", line 145, in _file2dict
    mod = import_module(temp_module_name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpj7h17tbn/tmp8e5kuzoc.py", line 8, in <module>
NameError: name 'optimizer' is not defined
Exception ignored in: <bound method _TemporaryFileCloser.__del__ of <tempfile._TemporaryFileCloser object at 0x7f50f68c2f98>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/tempfile.py", line 452, in __del__
    self.close()
  File "/opt/conda/lib/python3.6/tempfile.py", line 448, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpj7h17tbn/tmp8e5kuzoc.py'

this is my environment：
sys.platform: linux
Python: 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GPU 0,1: Tesla P100-PCIE-16GB
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - CuDNN 7.6.3
  - Magma 2.5.1
TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: mmcv-full 1.2.5
MMDetection: 2.8.0
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1

**Comment by ZwwWayne** [comment]
This usually means that there are some syntax errors in your config.

**Comment by YunhaoLee** [comment]
> This usually means that there are some syntax errors in your config.

thanks! It worked！
