### ISSUE TITLE
TypeError: list indices must be integers or slices, not torch.device

### ISSUE THREAD

**Issue by leehao178** [open-mmlab/mmdetection#4538]
**Checklist**

yes 1. I have searched related issues but cannot get the expected help.
yes 2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
yes 3. The bug has not been fixed in the latest version.

**Describe the bug**
```
Traceback (most recent call last):
  File "demo/image_demo.py", line 145, in <module>
    main()
  File "demo/image_demo.py", line 131, in main
    result = inference_detector(model, args.img)
  File "/home/user/Lab/mmdetection/mmdet/apis/inference.py", line 121, in inference_detector
    data = scatter(data, [device])[0]
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 44, in scatter
    return scatter_map(inputs)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 34, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 29, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 31, in scatter_map
    out = list(map(list, zip(*map(scatter_map, obj))))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 31, in scatter_map
    out = list(map(list, zip(*map(scatter_map, obj))))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 34, in scatter_map
    out = list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 29, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/scatter_gather.py", line 27, in scatter_map
    return Scatter.forward(target_gpus, obj.data)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 76, in forward
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 76, in <listcomp>
    streams = [_get_stream(device) for device in target_gpus]
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 115, in _get_stream
    if _streams[device] is None:
TypeError: list indices must be integers or slices, not torch.device
```
**Reproduction**

1. What command or script did you run?
```
python demo/image_demo.py demo/00018.jpg configs/fcos/fcos.py work_dirs/fcos/epoch_12.pth
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
Using the new parameter, bbox and label for training are indeed effective, but image_demo.py does not work
```

3. What dataset did you use?
```
my own dataset, and its voc format, but add one more parameter
```
4.
```
File "/home/user/Lab/mmdetection/mmdet/apis/inference.py", line 120, in inference_detector
    data = scatter(data, [device])[0]          #device = cuda:0

File "/home/user/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/_functions.py", line 76, in forward
    streams = [_get_stream(device) for device in target_gpus]           #device = [device(type='cuda', index=0)]

```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMDetection: 2.8.0+7f18184

```

**Error traceback**
If applicable, paste the error trackback here.

**Comment by hhaAndroid** [comment]
@leehao178 Please try the latest version, this bug should have been fixed.

**Comment by leehao178** [comment]
@hhaAndroid 
same error  :(
```
TypeError: list indices must be integers or slices, not torch.device
```

```
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMDetection: 2.8.0+bcb5190
```

**Comment by hhaAndroid** [comment]
@leehao178 Please try this command: 'python demo/image_demo.py demo/demo.jpg configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py download_ckpt_path'.  If it is normal, it means your custom config file has a problem.

**Comment by leehao178** [comment]
@hhaAndroid
same error

**Comment by hhaAndroid** [comment]
I think you have changed the code. Please download or clone mmdet again, and run 
`python demo/image_demo.py demo/demo.jpg configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py download_ckpt_path`

**Comment by rhiver** [comment]
@hhaAndroid 
same problem when try to call inference_detector(model, img), with my own DetectoRS model.

**Comment by rhiver** [comment]
@hhaAndroid 

I found an interesting phenomenon. Maybe it's related to this problem.

In config, when I changed dict(type='ImageToTensor', keys=['img']) of test_pipeline to dict(type='DefaultFormatBundle'), I got same problem, "TypeError: list indices must be integers or slices, not torch.device", for build-in models like detectors_htc_r50_1x_coco-329b1453.pth and htc_x101_64x4d_fpn_dconv_c3-c5_mstrain_400_1400_16x1_20e_coco_20200312-946fd751.pth.
When I changed the config back to dict(type='ImageToTensor', keys=['img']), both of them work in inference_detector(model, img).

But for the DetectoRS model I trained by myself even with the same config as the build-in model, I got the "not torch.device" error.

**Comment by rhiver** [comment]
Finally, I found the cause of the error. It's all because of the dict(type='DefaultFormatBundle'), when I changed dict(type='DefaultFormatBundle') back to dict(type='ImageToTensor', keys=['img']) including the those in test_pipeline, data.val and data.test, it worked.

**Comment by baibaidj** [comment]
I also encountered the similar issue and solved it based on previous discussion and some experimentation. I figured that the problem was originated from the incompatibility between DataContainer and Scatter. The Scatter will work with Tensor though. As the DefaultFormatBundle will warp all image data into DataContainer while ImageToTensor will not, the former one will cause the issue during inference while the latter will not. In short, do not use DataContainer and Scatter together.

**Comment by tkmaker** [comment]
> I also encountered the similar issue and solved it based on previous discussion and some experimentation. I figured that the problem was originated from the incompatibility between DataContainer and Scatter. The Scatter will work with Tensor though. As the DefaultFormatBundle will warp all image data into DataContainer while ImageToTensor will not, the former one will cause the issue during inference while the latter will not. In short, do not use DataContainer and Scatter together.

This is what fixed the issue for me as well. I was using a custom pipeline.
