### ISSUE TITLE
Removing MultiScaleFlipAug or Test-Time Augmentation on Validation returns TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#4578]
I tried changing the following: 
```
val=dict(
        type='CocoDataset',
        img_prefix='./data/val/images/',
        classes=classes,
        ann_file='./data/val.json',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]
    ),
```
**to this in order to remove MultiScaleFlipAug on validation**

```
val=dict(
        type='CocoDataset',
        img_prefix='./data/val/images/',
        classes=classes,
        ann_file='./data/val.json',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(type='Resize', keep_ratio=True),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
    
```

I end up getting the following error:
```
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-02-03 18:06:52,587 - mmdet - INFO - Start running, host: root@3fc35c85b333, work_dir: /content/mmdetection/exps
2021-02-03 18:06:52,587 - mmdet - INFO - workflow: [('train', 1)], max: 10 epochs
2021-02-03 18:06:52.822411: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
[                                                  ] 0/200, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/content/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 142, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/content/mmdetection/mmdet/apis/test.py", line 25, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 191, in __getitem__
    return self.prepare_test_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 234, in prepare_test_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 290, in __call__
    self._random_scale(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 190, in _random_scale
    elif len(self.img_scale) == 1:
TypeError: object of type 'NoneType' has no len()

```

**Comment by sarmientoj24** [comment]
following up for this

**Comment by xvjiarui** [comment]
Hi， we shouldn’t remove it from pipeline. May I know why you would like to remove it?

**Comment by elepherai** [comment]
> Hi， we shouldn’t remove it from pipeline. May I know why you would like to remove it?

To speed up inference time in my case.
