### ISSUE TITLE
error when testing

### ISSUE THREAD

**Issue by BoyuanJiang** [open-mmlab/mmdetection#46]
When I test my trained model using the following command, I get something wrong
```
python tools/test.py configs/mask_rcnn_r50_fpn_1x.py  ./work_dirs/mask_rcnn_r50_fpn_1x/latest.pth --gpus 2 --eval proposal_fast --out results.pkl
```

```
loading annotations into memory...
Done (t=0.27s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 5000/5000, 11.5 task/s, elapsed: 436s, ETA:     0s

writing results to results.pkl
Starting evaluate proposal_fast
Traceback (most recent call last):
  File "tools/test.py", line 114, in <module>
    main()
  File "tools/test.py", line 110, in main
    coco_eval(result_file, eval_types, dataset.coco)
  File "/home/jiangboyuan/mmdetection/mmdet/core/evaluation/coco_utils.py", line 20, in coco_eval
    ar = fast_eval_recall(result_file, coco, np.array(max_dets))
  File "/home/jiangboyuan/mmdetection/mmdet/core/evaluation/coco_utils.py", line 73, in fast_eval_recall
    gt_bboxes, results, max_dets, iou_thrs, print_summary=False)
  File "/home/jiangboyuan/mmdetection/mmdet/core/evaluation/recall.py", line 86, in eval_recalls
    if proposals[i].ndim == 2 and proposals[i].shape[1] == 5:
AttributeError: 'tuple' object has no attribute 'ndim'
```
Any suggestion about how to resolve it?

**Comment by ximitiejiang** [comment]
hello, when I tried the test.py for faster_rcnn with eval_type['proposal_fast'], there is mistake happened as above (yes, it runs good if I choose ['proposal', 'bbox'], but I just want to check the implement of recalls, so i choose 'proposal_fast'), 
is this mistake happened due to my wrong config? 
is there anyway to run on eval type of 'proposal_fast' ?

thanks
