### ISSUE TITLE
train error：struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by xiaoxiongli** [open-mmlab/mmdetection#462]
2019-04-03 12:31:36,869 - INFO - Epoch [1][1600/4948]   lr: 0.02000, eta: 1 day, 1:12:43, time: 1.704, data_time: 0.855, loss_rpn_cls: 0.0640, loss_rpn_reg: 0.0370, s0.loss_cls: 0.2357, s0.acc: 92.2437, s0.loss_reg: 0.1221, s0.loss_mask: 0.2930, s1.loss_cls: 0.1102, s1.acc: 92.6602, s1.loss_reg: 0.1240, s1.loss_mask: 0.1231, s2.loss_cls: 0.0539, s2.acc: 92.6199, s2.loss_reg: 0.0676, s2.loss_mask: 0.0513, loss: 1.2820
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/pytorch1.0_py3.6/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/home/ubuntu/.conda/envs/pytorch1.0_py3.6/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/ubuntu/.conda/envs/pytorch1.0_py3.6/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
**struct.error: 'i' format requires -2147483648 <= number <= 2147483647**

Anyone who met this crash issue During training? 
Please Help...

**Comment by wjp0408** [comment]
I meet the same error but don't know how to fix it...
I think it just occured when using **cascade mask rcnn...**
Have you fixed it? @xiaoxiongli

**Comment by xiaoxiongli** [comment]
@wjp0408 i have no idea about this bug,  yes, i use cascade mask rcnn now, Have you fixed it?

**Comment by wjp0408** [comment]
> @wjp0408 i have no idea about this bug, yes, i use cascade mask rcnn now, Have you fixed it?

I have no idea and Sorry for that... But when I change **images_per_gpu=1** and **works_per_gpu=1**, and change **the training image size is not too large**,  I will not meet this bug again.

**Comment by xiaoxiongli** [comment]
@wjp0408 retinanet have also met this problem, even i change images_per_gpu=1 and works_per_gpu=1

**Comment by xiaoxiongli** [comment]
@tjsongzw @lindahua @ychfan sorry for bother you, have you met this problem? please help...^_^

**Comment by tangsanli5201** [comment]
I meet the same problem. And I think changing imgs_per_gpu=1 and wokers_per_gpu=1 is not a satisfying solution. Could anyone give a better solution?

**Comment by ztyxd** [comment]
Did anyone fix this problem?
Could you give us some suggestion? @hellock

**Comment by hhaAndroid** [comment]
Is there still a problem with the latest version now?

**Comment by hhaAndroid** [comment]
resolve: #2044
