### ISSUE TITLE
Mask-RCNN Guided Anchor - inference error masked_conv

### ISSUE THREAD

**Issue by dimimal** [open-mmlab/mmdetection#4629]
Hello everyone, I faced the same issue, but surprisingly after my model finished the first training epoch along with the evaluation. At the end of evaluation I get this error:

```
Traceback (most recent call last):
  File "tools/train.py", line 183, in <module>
    main()
  File "tools/train.py", line 179, in main
    meta=meta)
  File "/mnt/N1534240/projects/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 89, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/base.py", line 261, in val_step
    losses = self(**data)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/detectors/two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 49, in forward_train
    outs = self(x)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 234, in forward
    return multi_apply(self.forward_single, feats)
  File "/mnt/N1534240/projects/mmdetection/mmdet/core/utils/misc.py", line 26, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/ga_rpn_head.py", line 36, in forward_single
    loc_pred) = super(GARPNHead, self).forward_single(x)
  File "/mnt/N1534240/projects/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 229, in forward_single
    cls_score = self.conv_cls(x, mask)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/ops/masked_conv.py", line 110, in forward
    self.padding)
  File "/mnt/N1534240/.local/share/virtualenvs/mmdetection-fgR1Fdxo/lib64/python3.7/site-packages/mmcv/ops/masked_conv.py", line 31, in forward
    assert features.dim() == 4 and features.size(0) == 1
AssertionError
```
I am using the guidedAnchorHead.
After some debugging inside the class I noticed that I get a different batch size during inference wrt to the mask

```
2021-02-12 12:59:18,002 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
X shape: torch.Size([5, 256, 200, 336])
Mask shape: torch.Size([1, 200, 336])
X shape: torch.Size([5, 256, 200, 336])
Mask shape: torch.Size([1, 200, 336])
X shape: torch.Size([5, 256, 200, 304])
Mask shape: torch.Size([1, 200, 304])
X shape: torch.Size([5, 256, 200, 304])
Mask shape: torch.Size([1, 200, 304])
X shape: torch.Size([5, 256, 200, 304])
Mask shape: torch.Size([1, 200, 304])
X shape: torch.Size([5, 256, 200, 304])
Mask shape: torch.Size([1, 200, 304])
```

Any ideas?

**Comment by dimimal** [comment]
I tried to run this model with single batch size, and it run smoothly, it seems that this function is enabled during inference and it does not support batch size > 1. Is it possible to select different batch size for training and validation respectively?

**Comment by jshilong** [comment]
Sure, you can specific `samples_per_gpu` in `val`  or `test` dict, such as:

```
    val=dict(  # Validation dataset config
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ]),
        samples_per_gpu=2  # Batch size of a single GPU
        ]),
    test=dict(  # Test dataset config, modify the ann_file for test-dev/test submission
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        samples_per_gpu=2  # Batch size of a single GPU used in testing
        ))
```

**Comment by dimimal** [comment]
In Val you have the samples_per_gpu inside the pipeline but in test its outside of the pipeline list. Is that correct?

**Comment by jshilong** [comment]
Sorry, both are outside the pipeline.

**Comment by dimimal** [comment]
It doesn't seem to work: Here is my config part wrt the data pipelines:

```
data = dict(
#     samples_per_gpu=samples_per_gpu,
#     workers_per_gpu=workers_per_gpu,
    train=dict(

        samples_per_gpu=samples_per_gpu,
        workers_per_gpu=workers_per_gpu,
        type=dataset_type,
        classes=classes,
        img_prefix='/mnt/N1534240/projects/voc_parts_dataset/VOCdevkit/VOC2010/JPEGImages/',  # Prefix of image path
        ann_file='/mnt/N1534240/projects/voc_parts_dataset/train_parts_voc.json',

        pipeline=[  # pipeline, this is passed by the train_pipeline created before.
            dict(type='LoadImageFromFile'),
            dict(
                type='LoadAnnotations',
                with_bbox=True,
                with_mask=True,
                poly2mask=False),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=mean_,
                std=std_,
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])]),
    val=dict(
            samples_per_gpu=1,
            workers_per_gpu=1,
        type=dataset_type,
        classes=classes,
        img_prefix='/mnt/N1534240/projects/voc_parts_dataset/VOCdevkit/VOC2010/JPEGImages/',
        ann_file='/mnt/N1534240/projects/voc_parts_dataset/val_parts_voc.json',
#         sampler=dict(  # Config of positive/negative sampler
#                 type='RandomSampler'
#                 pos_fraction=0.4),
        pipeline=[ 
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(
                        type='Normalize',
                        mean=mean_,
                        std=std_,
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])]),
    test=dict(
        samples_per_gpu=1,
        workers_per_gpu=1,
        type=dataset_type,
        classes=classes,
        img_prefix='/mnt/N1534240/projects/voc_parts_dataset/VOCdevkit/VOC2010/JPEGImages/',
        ann_file='/mnt/N1534240/projects/voc_parts_dataset/val_parts_voc.json',
        pipeline=[  # Pipeline is passed by test_pipeline created before
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
#                     dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=mean_,
                        std=std_,
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])]))
```

**Comment by dimimal** [comment]
@jshilong Sorry but this doesn't work, is this feature added in a latest version??

**Comment by ZwwWayne** [comment]
The mask conv seems to only accept batch size=1, but the feature has batch size of 5. You may set breakpoint in the code and check the bug.
