### ISSUE TITLE
yolov3 pytorch2onnx: TypeError: iteration over a 0-d tensor(Occurred when translating upsample_nearest2d)

### ISSUE THREAD

**Issue by RunningLeon** [open-mmlab/mmdetection#4646]
Pytorch2onnx failed for yolov3 with PyTorch==1.6.0, but succeeded with PyTorch==1.7.0 and PyTorch==1.5.0

**Reproduction**

1. What command or script did you run?

```
python tools/deployment/pytorch2onnx.py \
configs/yolo/yolov3_d53_320_273e_coco.py \
checkpoints/yolo/yolov3_d53_320_273e_coco-421362b6.pth \
--mean 0.0 0.0 0.0 \
--std 255.0 255.0 255.0 \
--shape 608 608 \
--verify
```

**Environment**
```
sys.platform: linux
Python: 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1060 6GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 7.1.0-10ubuntu1~16.04.york0) 7.1.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 7.1
MMCV CUDA Compiler: 10.2
MMDetection: 2.9.0+df681d8
```

**Error traceback**
```
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 230, in <module>
    do_simplify=args.simplify)
  File "tools/deployment/pytorch2onnx.py", line 54, in pytorch2onnx
    opset_version=opset_version)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 384, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 241, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 791, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmcv-pt1.6/mmcv/onnx/symbolic.py", line 17, in symbolic_fn
    g, interpolate_mode, args)
  File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmcv-pt1.6/mmcv/onnx/onnx_utils/symbolic_helper.py", line 253, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmcv-pt1.6/mmcv/onnx/onnx_utils/symbolic_helper.py", line 232, in _interpolate_get_scales_if_available
    'fs') != -1 and not _is_none(scales[0])
  File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmcv-pt1.6/mmcv/onnx/onnx_utils/symbolic_helper.py", line 66, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/home/SENSETIME/maningsheng/projects/open-mmlab/mmcv-pt1.6/mmcv/onnx/onnx_utils/symbolic_helper.py", line 43, in _parse_arg
    return [float(v) for v in tval]
  File "/home/SENSETIME/maningsheng/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/tensor.py", line 450, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor 
(Occurred when translating upsample_nearest2d).

```

**Bug fix**
MMCV PR [#815](https://github.com/open-mmlab/mmcv/pull/815) may bring this issue( Work in progress).

**Comment by RunningLeon** [comment]
Closed due to mmcv PR [848](https://github.com/open-mmlab/mmcv/pull/848) is merged.
