### ISSUE TITLE
I tried the Instaboost, and met the error "operands could not be broadcast together with shapes (0,) (4,)"

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection#4657]
There is no negative sample in my custom dataset. It seems that the Instaboost makes the gt nums to zero, the error info is below:

_bbox: 0.0145, loss_cls: 0.0669, acc: 97.9316, loss_bbox: 0.0616, loss: 0.1611
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/home/user/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 5.
Original Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/mmclass/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/mmdetection/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/user/mmdetection/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/home/user/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/user/mmdetection/mmdet/datasets/pipelines/transforms.py", line 312, in __call__
    self._resize_bboxes(results)
  File "/home/user/mmdetection/mmdet/datasets/pipelines/transforms.py", line 237, in _resize_bboxes
    bboxes = results[key] * results['scale_factor']
ValueError: operands could not be broadcast together with shapes (0,) (4,)

**Comment by hhaAndroid** [comment]
hi, @clw5180  no negative sample? it seems to be caused by `Instaboost`. Is there an empty gt in your dataset?
Thank you!

**Comment by clw5180** [comment]
> hi, @clw5180 no negative sample? it seems to be caused by `Instaboost`. Is there an empty gt in your dataset?
> Thank you!

Thanks, I mean all sample have gts, no empty gt in my dataset. I have gt whose width or height equals to 1, maybe the parameter of Instaboost scale=(0.8, 1.2) make the gt's width or height =0, now I change the scale to (1.0, 1.2) and have a try.

**Comment by hhaAndroid** [comment]
> > hi, @clw5180 no negative sample? it seems to be caused by `Instaboost`. Is there an empty gt in your dataset?
> > Thank you!
> 
> Thanks, I mean all samples have gt, no empty gt in my dataset. I have gt whose width or height equals to 1, maybe the parameter of Instaboost scale=(0.8, 1.2) makes the gt's width or height =0, now I change the scale to (1.0, 1.2) and have a try.

OK

**Comment by clw5180** [comment]
> > > hi, @clw5180 no negative sample? it seems to be caused by `Instaboost`. Is there an empty gt in your dataset?
> > > Thank you!
> > 
> > 
> > Thanks, I mean all samples have gt, no empty gt in my dataset. I have gt whose width or height equals to 1, maybe the parameter of Instaboost scale=(0.8, 1.2) makes the gt's width or height =0, now I change the scale to (1.0, 1.2) and have a try.
> 
> OK

The problem still not solved.....

**Comment by hhaAndroid** [comment]
If this error rarely occurs, you can try to modify the code. If Instaboost output does not have gt, skip this augment.

**Comment by 00ffcc** [comment]
the problem also exists when using `Instaboost`

**Comment by 00ffcc** [comment]
lol, I place `dict(type='InstaBoost'),` behind `dict(type='LoadAnnotations', with_bbox=True, with_mask=True),` and now it works, however I remember that some docs say that `dict(type='InstaBoost'),`  should be placed before `dict(type='LoadAnnotations', with_bbox=True, with_mask=True),`,(And I remember the former course some problems indeed)
