### ISSUE TITLE
installation verification fails

### ISSUE THREAD

**Issue by lweingart** [open-mmlab/mmdetection#4662]
Dear Team,

During these last few weeks, I have successfully installed mmpose and mmdetection on two different Nvidia Jetson devices.
On my attempt on a third device, running a script for mmpose fails, telling me that mmdet should be installed.
However, mmdetection is installed, and I can import mmdet in the python interpreter successfully.

The strange thing is that I went through the exact same install process on all devices.

Looking more deeply however, it's `import mmdet.apis` that fails.
I noticed the verification script you provide to verify the mmdetection, and this is what it shows when run:
```
Traceback (most recent call last):
  File "test_jnstall.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/home/jetson/git/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/jetson/git/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/home/jetson/git/mmcv/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/jetson/git/mmcv/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/jetson/git/mmcv/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

mmcv is also installed, but on this device it's version 1.2.7 (when it's 1.2.2 on the other devices where the installation is working fine).

Result of `python3 mmdet/utils/collect_env.py`
```
% python3 mmdet/utils/collect_env.py
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0: Xavier
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, USE_CUDA=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.7
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMDetection: 2.9.0+3d5b103
```

Would you have any idea what could go wrong by chance?
Also, should I reinstall mmcv but version 1.2.2?
In this case, could you give me a pointer on how to uninstall it correctly before re installing it (It was installed from source with `MMCV_WITH_OPS=1 pip install -e .` )?

Thank you very much for your help

**Comment by ZwwWayne** [comment]
It seems that MMCV is not succesfully built. You may try to re-install MMCV, and may try `MMCV_WITH_OPS=1 FORCE_CUDA=1 pip install -e .` in the mmcv.

**Comment by lweingart** [comment]
Hello @ZwwWayne,

I just did what you suggested, but then when I try the script provided to test the mmdet installation, I still get the same error message unfortunately:
```
Traceback (most recent call last):
  File "test_jnstall.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/home/jetson/git/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/jetson/git/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/home/jetson/git/mmcv/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/jetson/git/mmcv/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/jetson/git/mmcv/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

Here is what happend when reinstalling mmcv:
```
# jetson @ jetson-xavier in ~/git/mmcv on git:master o [19:42:17]  $ MMCV_WITH_OPS=1
# jetson @ jetson-xavier in ~/git/mmcv on git:master o [19:42:17]  $ FORCE_CUDA=1
# jetson @ jetson-xavier in ~/git/mmcv on git:master o [19:42:23]  $ pip3 install -e .
Obtaining file:///home/jetson/git/mmcv
Collecting addict (from mmcv==1.2.7)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/6a/00/b08f23b7d7e1e14ce01419a467b583edbb93c6cdb8654e54a9cc579cd61f/addict-2.4.0-py3-none-any.whl
Collecting numpy (from mmcv==1.2.7)
  Cache entry deserialization failed, entry ignored
Collecting Pillow (from mmcv==1.2.7)
  Cache entry deserialization failed, entry ignored
Collecting pyyaml (from mmcv==1.2.7)
  Cache entry deserialization failed, entry ignored
Collecting yapf (from mmcv==1.2.7)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/c1/5d/d84677fe852bc5e091739acda444a9b6700ffc6b11a21b00dd244c8caef0/yapf-0.30.0-py2.py3-none-any.whl
Installing collected packages: addict, numpy, Pillow, pyyaml, yapf, mmcv
  Found existing installation: mmcv 1.2.7
    Uninstalling mmcv-1.2.7:
      Successfully uninstalled mmcv-1.2.7
  Running setup.py develop for mmcv
Successfully installed Pillow-8.1.0 addict-2.4.0 mmcv numpy-1.19.5 pyyaml-5.4.1 yapf-0.30.0
```
and in the python console:
```
# jetson @ jetson-xavier in ~/git/mmdetection on git:master x [19:47:39] C:1 $ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mmcv
>>> print(mmcv.__version__)
1.2.7
>>>
```

`python mmdet/utils/collect_env.py` still yields the same
```
# jetson @ jetson-xavier in ~/git/mmdetection on git:master x [19:56:18]  $ python3 mmdet/utils/collect_env.py
sys.platform: linux
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
CUDA available: True
GPU 0: Xavier
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_53,code=sm_53;-gencode;arch=compute_62,code=sm_62;-gencode;arch=compute_72,code=sm_72
  - CuDNN 8.0
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, USE_CUDA=ON, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=ON, USE_NCCL=0, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.7
MMCV Compiler: n/a
MMCV CUDA Compiler: n/a
MMDetection: 2.9.0+3d5b103
```

It looks to me that mmcv is correctly installed.
I'm at loss for ideas.

**Comment by lweingart** [comment]
Hi again,

I reinstalled mmcv version 1.2.2, and I had this error when running the test script:
```
Traceback (most recent call last):
  File "test_jnstall.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "/home/jetson/git/mmdetection/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.2.2 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.
```

So I installed mmcv 1.2.4 and now I can successfully import mmdet.apis in the python interpreter.
(although the script to test the mmdet installation still fails, the issue comes from somewhere else:
```
Traceback (most recent call last):
  File "test_jnstall.py", line 9, in <module>
    model = init_detector(config_file, checkpoint_file, device=device)
  File "/home/jetson/git/mmdetection/mmdet/apis/inference.py", line 42, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
  File "/home/jetson/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/jetson/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 254, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth is not a checkpoint file
```

It looks to me that the current mmdetection is incompatible with mmcv 1.2.7.

Apart from that, I was able to run a command with mmpose with the mmdet error, but I still end up with a segmentation fault, the same I got as I described here: 
https://github.com/open-mmlab/mmpose/issues/457

Unfortunately, reinstalling everything still brings me to the segmentation fault.

**Comment by ZwwWayne** [comment]
The OSError is because you have not downloaded the checkpoint.

**Comment by SamMohel** [comment]
> Hi again,
> 
> I reinstalled mmcv version 1.2.2, and I had this error when running the test script:
> 
> ```
> Traceback (most recent call last):
>   File "test_jnstall.py", line 1, in <module>
>     from mmdet.apis import init_detector, inference_detector
>   File "/home/jetson/git/mmdetection/mmdet/__init__.py", line 25, in <module>
>     f'MMCV=={mmcv.__version__} is used but incompatible. ' \
> AssertionError: MMCV==1.2.2 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.
> ```
> 
> So I installed mmcv 1.2.4 and now I can successfully import mmdet.apis in the python interpreter.
> (although the script to test the mmdet installation still fails, the issue comes from somewhere else:
> 
> ```
> Traceback (most recent call last):
>   File "test_jnstall.py", line 9, in <module>
>     model = init_detector(config_file, checkpoint_file, device=device)
>   File "/home/jetson/git/mmdetection/mmdet/apis/inference.py", line 42, in init_detector
>     checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
>   File "/home/jetson/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 279, in load_checkpoint
>     checkpoint = _load_checkpoint(filename, map_location)
>   File "/home/jetson/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 254, in _load_checkpoint
>     raise IOError(f'{filename} is not a checkpoint file')
> OSError: checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth is not a checkpoint file
> ```
> 
> It looks to me that the current mmdetection is incompatible with mmcv 1.2.7.
> 
> Apart from that, I was able to run a command with mmpose without the mmdet error, but I still end up with a segmentation fault, the same I got as I described here:
> [open-mmlab/mmpose#457](https://github.com/open-mmlab/mmpose/issues/457)
> 
> Unfortunately, reinstalling everything still brings me to the segmentation fault.

did you solve it ?
