### ISSUE TITLE
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Byte

### ISSUE THREAD

**Issue by lyd959** [open-mmlab/mmdetection#4670]
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2021-02-24 22:39:22,481 - mmdet - INFO - Start running, host: Administrator@WPQ1Q5CTQTX8D0Z, work_dir: F:\pyCode\SOLO\work_dirs\solov2_light_release_r18_fpn_8gpu_3x
2021-02-24 22:39:22,481 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs
E:\Anaconda3\envs\mmdetection\lib\site-packages\torch\nn\functional.py:2479: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Ple
ase specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 121, in main
    timestamp=timestamp)
  File "f:\pycode\solo\mmdet\apis\train.py", line 111, in train_detector
    timestamp=timestamp)
  File "f:\pycode\solo\mmdet\apis\train.py", line 297, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "E:\Anaconda3\envs\mmdetection\lib\site-packages\mmcv-0.2.16-py3.7-win-amd64.egg\mmcv\runner\runner.py", line 364, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "E:\Anaconda3\envs\mmdetection\lib\site-packages\mmcv-0.2.16-py3.7-win-amd64.egg\mmcv\runner\runner.py", line 268, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "f:\pycode\solo\mmdet\apis\train.py", line 78, in batch_processor
    losses = model(**data)
  File "E:\Anaconda3\envs\mmdetection\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\envs\mmdetection\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\Anaconda3\envs\mmdetection\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "f:\pycode\solo\mmdet\core\fp16\decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "f:\pycode\solo\mmdet\models\detectors\base.py", line 142, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "f:\pycode\solo\mmdet\models\detectors\single_stage_ins.py", line 78, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "f:\pycode\solo\mmdet\models\anchor_heads\solov2_head.py", line 200, in loss
    mask_feat_size=mask_feat_size)
  File "f:\pycode\solo\mmdet\core\utils\misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "f:\pycode\solo\mmdet\models\anchor_heads\solov2_head.py", line 314, in solov2_target_single
    center_ws, center_hs = center_of_mass(gt_masks_pt)
  File "f:\pycode\solo\mmdet\models\anchor_heads\solov2_head.py", line 20, in center_of_mass
    m10 = (bitmasks * xs).sum(dim=-1).sum(dim=-1)
RuntimeError: expected device cuda:0 and dtype Float but got device cuda:0 and dtype Byte

**Comment by xvjiarui** [comment]
HI @lyd959 
Please use [error report](https://github.com/open-mmlab/mmdetection/blob/master/.github/ISSUE_TEMPLATE/error-report.md) template to provide more information.
