### ISSUE TITLE
ResNeSt backbone cascade rcnn can not use async_inference_detector, async_simple_test() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by JustinhoCHN** [open-mmlab/mmdetection#4718]
**Describe the bug**
I was trying to use my ResNeSt backbone cascade rcnn model with ```async_inference_detector```, but it raised an error:
```
Traceback (most recent call last):
  File "tools/batch_inference_async.py", line 77, in <module>
    asyncio.run(main())
  File "/home/huzhihao/anaconda3/envs/open-mmlab/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/huzhihao/anaconda3/envs/open-mmlab/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "tools/batch_inference_async.py", line 61, in main
    await async_inference_detector(model, test_img)
  File "/home/huzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.9.0-py3.7.egg/mmdet/apis/inference.py", line 179, in async_inference_detector
    result = await model.aforward_test(rescale=True, **data)
  File "/home/huzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.9.0-py3.7.egg/mmdet/models/detectors/base.py", line 121, in aforward_test
    return await self.async_simple_test(img[0], img_metas[0], **kwargs)
  File "/home/huzhihao/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.9.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 185, in async_simple_test
    x, proposal_list, img_meta, rescale=rescale)
TypeError: async_simple_test() takes 3 positional arguments but 4 were given
```

**BUT !** If I replace the model cfg and weights that ```mmdetection/tests/test_runtime/async_benchmark.py``` supplies, there's no error.

**Reproduction**
codes and models are here: [baiduwangpan](https://pan.baidu.com/s/1rx9i2uik-rMfxOc_weph_A) code: nh11

running command:
```
python tools/batch_inference_async.py workdir/big_model/cascade_rcnn_s101_fpn_syncbn-backbone+head_mstrain-range_1x_coco_fp16.py workdir/big_model/epoch_11.pth --imgs data/random_testset/ --batch_size 8 --device 1
```

mmcv-full: 1.2.7
mmdetection: 2.9.0
pytorch: 1.6.0
cuda: 10.2
cudnn: 7.6.5
os: ubuntu 1804

**Comment by JustinhoCHN** [comment]
I've also tried ```cascade_rcnn_r101_fpn_dconv_c3-c5_1x_coco``` model, it was the same error, maybe the ```async_inference_detector``` didn't work for cascade_rcnn, needed to be fixed.

**Comment by hhaAndroid** [comment]
Thank you for your feedback, currently Cascade R-CNN does not support async inference, but community PR is welcome!
