### ISSUE TITLE
Segmenation fault when using new onnx2tensorrt feature

### ISSUE THREAD

**Issue by Mxbonn** [open-mmlab/mmdetection#4731]
### **Issue**: 
Running the onnx2tensorrt tool gives a segmentation fault.
```
python tools/deployment/onnx2tensorrt.py checkpoints/retinanet_r50_fpn_1x_coco.onnx --trt-file checkpoints/retinanet_r50_fpn_1x_coco.trt --input-img demo/demo.jpg --shape 400 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375
```
results in
```
Segmentation fault (core dumped)
```

### Steps to reproduce:
```
python tools/deployment/pytorch2onnx.py configs/retinanet/retinanet_r50_fpn_1x_coco.py checkpoints/retinanet_r50_fpn_1x_coco.pth --output-file checkpoints/retinanet_r50_fpn_1x_coco.onnx --input-img demo/demo.jpg --shape 400 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375
python tools/deployment/onnx2tensorrt.py checkpoints/retinanet_r50_fpn_1x_coco.onnx --trt-file checkpoints/retinanet_r50_fpn_1x_coco.trt --input-img demo/demo.jpg --shape 400 600 --mean 123.675 116.28 103.53 --std 58.395 57.12 57.375
``` 

### Additional remark/question:

1.  Using the **pytorch2onnx** converter as reported above does produce a .onnx file however usint the pytorch2onnx converter with the **`--verify`** flag gives an additional error:
```
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 218, in <module>
    pytorch2onnx(
  File "tools/deployment/pytorch2onnx.py", line 107, in pytorch2onnx
    sess = rt.InferenceSession(output_file, session_options)
  File "/home/mbonnaer/anaconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/mbonnaer/anaconda3/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 226, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from checkpoints/retinanet_r50_fpn_1x_coco.onnx failed:Fatal error: NonMaxSuppression is not a registered function/op
```
My mmcv version is build from source with the latest version and all custom flags to support onnx. 
I believe this last error can be ignored as this is a custom operation only known within mmcv, is this statement correct or should verify work with nonmaximumsuppression after installing mmcv with the `MMCV_WITH_OPS=1 MMCV_WITH_ORT=1 MMCV_WITH_TRT=1 pip install -e .`?

According to the documentation in mmcv: (https://github.com/open-mmlab/mmcv/blob/master/docs/tensorrt_plugin.md)
Non maximum suppression is WIP (so not yet supported), however many of the models that are listed in (https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md) as supported do use this operation. 

2) Perhaps better suited in a new error report but the same pytorch2onnx hangs when used with the ssd config. As this was also listed as supported im also interested in reproducing this tensorrt model.

**Environment**
Tested on 2 environments:
```
sys.platform: linux
Python: 3.8.2 (default, Mar 26 2020, 15:53:00) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.2
MMDetection: 2.10.0+bec24ea
```
and
```
sys.platform: linux
Python: 3.8.2 (default, Mar 26 2020, 15:53:00) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.2
MMDetection: 2.10.0+bec24ea

```

**Comment by Mxbonn** [comment]
Tagging @RunningLeon as you seem to be the main contributor behind these new features.

**Comment by Mxbonn** [comment]
@RunningLeon thanks! That indeed did the trick, it might be useful to put this somewhere in the documentation.

However regarding my other issue, **SSD** still does not work. When using mmdetection **2.10** it seems to hang in the **`pytorch2onnx`** tool.  And when using mmdet **2.9** to generate the onnx i get the following error when using **`onnx2tensorrt`**:
```
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 172, in <module>
    onnx2tensorrt(
  File "tools/deployment/onnx2tensorrt.py", line 34, in onnx2tensorrt
    trt_engine = onnx2trt(
  File "/home/mxbonn/github.com/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 148, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (importCast): INVALID_NODE: Assertion failed: convertDtype(onnxType, &dtype) && "Unsupported cast!"

```
With what settings did you confirm the that SSD works as is stated in https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/onnx2tensorrt.md?

**Comment by RunningLeon** [comment]
You might need to set `nms_pre` or `deploy_nms_pre` in the `ssd` config when exporting onnx. Otherwise, there would be too much `bboxes` for `nms`.

**Comment by RunningLeon** [comment]
Feel free to reopen it if you still have the issue.
