### ISSUE TITLE
RuntimeError: Exporting the operator argsort to ONNX opset version 11 is not supported. 

### ISSUE THREAD

**Issue by mprzewie** [open-mmlab/mmdetection#4738]
**Describe the bug**

When running ` pytorch2onnx.py` script against a Mask-RCNN model, I get the error about `argsort` operator. Could MMDet code shift to using `sort` operator, as this :

https://github.com/pytorch/pytorch/issues/33412

issue says?

**Reproduction**

1. What command or script did you run?

```none
 python pytorch2onnx.py /my/model/config.py /my/model/weights.pth
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I encountered this error with unmodified mmdet code. Then, I changed all occurences of `.argsort` in mmdet like this:

original:
```
x = y.argsort(...)
```

to:

`_, x = y.sort(...)`

3. What dataset did you use?

Custom dataset in COCO format. This problem is about an already successfully-trained model, which I'd like to convert to ONNX.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```sys.platform: linux
Python: 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.8.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0+cu101
OpenCV: 4.4.0
MMCV: 1.2.5
MMCV Compiler: GCC 7.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.10.0+b9e2af5
```

2. You may add addition that may be helpful for locating the problem, such as

PyTorch installed with pip.

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "pytorch2onnx.py", line 246, in <module>
    cfg_options=args.cfg_options)
  File "pytorch2onnx.py", line 58, in pytorch2onnx
    opset_version=opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 698, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 465, in _model_to_graph
    module=module)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 947, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_registry.py", line 112, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator argsort to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by RunningLeon** [comment]
Hi, MaskRCNN is not fully supported with PyToch2onnx right now. But, as far as I know, `argsort` op is not supported in ONNX. You may have to replace `tensort.sort()` with `tensor.topk()` to workaround.

**Comment by mprzewie** [comment]
Thanks @RunningLeon,  I'll definitely try it! I see that in this comment you listed issues with converting M-RCNN to ONNX:

https://github.com/open-mmlab/mmdetection/issues/4247#issuecomment-740468931

After the recent commits to MMDet, have any of these been solved?

**Comment by RunningLeon** [comment]
Up to now, MASKRCNN is not supported for pytorch2onnx.

**Comment by mprzewie** [comment]
Thank you!
