### ISSUE TITLE
YOLOv3 TensorRT conversion from ONNX fails due to NMS

### ISSUE THREAD

**Issue by azbe** [open-mmlab/mmdetection#4748]
I am trying to replicate the conversion from onnx2tensorrt.md, but it fails. I have not modified any code and have built MMCV with TensorRT support.

The error is as follows:
```
$ python3 tools/deployment/onnx2tensorrt.py yolov3_608.onnx --trt-file yolov3_608.trt --input-img datasets/coco/images/val2017/000000100274.jpg --shape 608 608 --mean 0 0 0 --std 255 255 255

[TensorRT] ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin NonMaxSuppression version 1
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 179, in <module>
    workspace_size=args.workspace_size)
  File "tools/deployment/onnx2tensorrt.py", line 38, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/media/radut/5e5b5db9-505a-4a1f-ae05-c321fcc3f5241/3d-human-pose/od/mmdetection/mmcv_build/mmcv/tensorrt/tensorrt_utils.py", line 52, in onnx2trt
    onnx_model.SerializeToString()), 'parse onnx failed.'
AssertionError: parse onnx failed.
```

I am using PyTorch 1.6.0 and TensorRT 7.2.1

**Comment by RunningLeon** [comment]
Please check this https://github.com/open-mmlab/mmdetection/issues/4731#issuecomment-793821771

**Comment by RunningLeon** [comment]
@azbe Feel free to reopen it if you still have this issue.
