### ISSUE TITLE
RuntimeError: NCCL error unhandled cuda error, NCCL version 2.4.8

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection#4749]
When I want to test my trained model on multi GPU, there are some error happens while test on single gpu it is ok.
# error logs:
CUDA_VISIBLE_DEVICES=5,6,7 PORT=90000 ./tools/dist_test.sh /data3/ywt/tianchi/mm_work_dir/4096_2048/cascade_50_full_body/tc_cascade_rcnn_r50_fpn_1x_coco.py /data3/ywt/tianchi/mm_work_dir/4096_2048/cascade_50_full_body/epoch_12.pth 3 --format-only --options "jsonfile_prefix=./cascade_r50_fullbody4096_2048_softnms_fliptest"
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
./tools/test.py:96: UserWarning: --options is deprecated in favor of --eval-options
  warnings.warn('--options is deprecated in favor of --eval-options')
./tools/test.py:96: UserWarning: --options is deprecated in favor of --eval-options
  warnings.warn('--options is deprecated in favor of --eval-options')
./tools/test.py:96: UserWarning: --options is deprecated in favor of --eval-options
  warnings.warn('--options is deprecated in favor of --eval-options')
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
loading annotations into memory...
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Done (t=0.05s)
creating index...
index created!
Use load_from_local loader
Use load_from_local loader
Use load_from_local loader
Traceback (most recent call last):
  File "./tools/test.py", line 220, in <module>
    main()
  File "./tools/test.py", line 195, in main
    broadcast_buffers=False)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 285, in __init__
    self.broadcast_bucket_size)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 496, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1591914895884/work/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled cuda error, NCCL version 2.4.8
Traceback (most recent call last):
  File "./tools/test.py", line 220, in <module>
    main()
  File "./tools/test.py", line 195, in main
    broadcast_buffers=False)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 285, in __init__
    self.broadcast_bucket_size)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 496, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1591914895884/work/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled cuda error, NCCL version 2.4.8
Traceback (most recent call last):
  File "./tools/test.py", line 220, in <module>
    main()
  File "./tools/test.py", line 195, in main
    broadcast_buffers=False)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 285, in __init__
    self.broadcast_bucket_size)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 496, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1591914895884/work/torch/lib/c10d/ProcessGroupNCCL.cpp:514, unhandled cuda error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/josheh/anaconda3/envs/cuda92/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/josheh/anaconda3/envs/cuda92/bin/python', '-u', './tools/test.py', '--local_rank=2', '/data3/ywt/tianchi/mm_work_dir/4096_2048/cascade_50_full_body/tc_cascade_rcnn_r50_fpn_1x_coco.py', '/data3/ywt/tianchi/mm_work_dir/4096_2048/cascade_50_full_body/epoch_12.pth', '--launcher', 'pytorch', '--format-only', '--options', 'jsonfile_prefix=./cascade_r50_fullbody4096_2048_softnms_fliptest']' returned non-zero exit status 1.
How can I solve this? Very appreciate for your reply!!

**Comment by brightro99** [comment]
I have same error, how to you solved that?

**Comment by Adenialzz** [comment]
why this issue is closed? anyone knows how to solve it?

**Comment by alaa-shubbak** [comment]
Hello , I got similar error as following 

`RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:558, unhandled system error, NCCL version 2.7.8`
