### ISSUE TITLE
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

### ISSUE THREAD

**Issue by Mactarvish** [open-mmlab/mmdetection#4774]
When I was running the example code [https://mmdetection.readthedocs.io/en/latest/2_new_data_model.html#prepare-a-config](url). , I got such error:

        classes=('isolated', 'embedded')))
evaluation = dict(metric=['bbox', 'segm'])
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
classes = ('isolated', 'embedded')
work_dir = './work_dirs/pg'
gpu_ids = range(0, 1)

2021-03-15 17:29:08,338 - mmdet - INFO - load model from: open-mmlab://detectron2/resnet50_caffe
2021-03-15 17:29:08,339 - mmdet - INFO - Use load_from_openmmlab loader
2021-03-15 17:29:08,483 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: conv1.bias

loading annotations into memory...
Done (t=0.76s)
creating index...
index created!
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
2021-03-15 17:29:13,836 - mmdet - INFO - Start running, host: work@169932717a8fw, work_dir: /home/github/mmdetection/work_dirs/pg
2021-03-15 17:29:13,837 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/home/github/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/work/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/github/mmdetection/mmdet/datasets/custom.py", line 193, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/github/mmdetection/mmdet/datasets/custom.py", line 216, in prepare_train_img
    return self.pipeline(results)
  File "/home/github/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/github/mmdetection/mmdet/datasets/pipelines/transforms.py", line 304, in __call__
    self._resize_masks(results)
  File "/home/github/mmdetection/mmdet/datasets/pipelines/transforms.py", line 250, in _resize_masks
    results[key] = results[key].rescale(results['scale'])
  File "/home/github/mmdetection/mmdet/core/mask/structures.py", line 630, in rescale
    rescaled_masks = self.resize((new_h, new_w))
  File "/home/github/mmdetection/mmdet/core/mask/structures.py", line 645, in resize
    p[0::2] *= w_scale
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

How to solve it ? Thanks in advance.

**Comment by hhaAndroid** [comment]
Please check the input mask type. This may be related to your data labeling. example:

```python
from mmdet.core.mask.structures import *  # NOQA

masks = [
    [np.array([0, 0, 10, 0, 10, 10, 0, 10, 0, 0])]
]
self = PolygonMasks(masks, 16, 16)
self.resize((10, 10))
```
The above code will report an `numpy.core._exceptions.UFuncTypeError` error. It should look like this：

```python
masks = [
    [np.array([0, 0, 10, 0, 10, 10, 0, 10, 0, 0], np.float)]
]
# or 
masks = [
    [np.array([0, 0, 10.0, 0, 10, 10, 0, 10, 0, 0])]
]
self = PolygonMasks(masks, 16, 16)
self.resize((10, 10))
```

**Comment by Mactarvish** [comment]
Thanksn very much! Totally solved.

By the way, why does mask must be float instead of int ?

**Comment by hhaAndroid** [comment]
> Thanksn very much! Totally solved.
> 
> By the way, why does mask must be float instead of int ?

I'm not very sure why, but it may be a desire to reduce precision loss due to operations such as resize.
