### ISSUE TITLE
convert mask_rcnn model to tensorrt, there is a wrong "shape mismatch"

### ISSUE THREAD

**Issue by xzsong** [open-mmlab/mmdetection#4817]
Hi, when i conver my mask_rcnn model using mmdet2trt command, there is wrong, here is my command line:

**mmdet2trt experiments/third_party/maskrcnn_inference/configs/mask_rcnn/mask_rcnn_r50_fpn_2x_coco_acid_alkali.py experiments/assets/weights/latest.pth acid_mask_rcnn.trt**

--------------------------------------------------------------------------------------------------------------------------------------
**and come out something like this:**
/root/space/mmdetection/mmdet/models/builder.py:72: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
INFO:mmdet2trt:Model warmup
INFO:mmdet2trt:Converting model
Traceback (most recent call last):
  File "/usr/local/bin/mmdet2trt", line 33, in <module>
    sys.exit(load_entry_point('mmdet2trt', 'console_scripts', 'mmdet2trt')())
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/mmdet2trt.py", line 330, in main
    enable_mask=args.enable_mask)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/mmdet2trt.py", line 147, in mmdet2trt
    int8_calib_algorithm=int8_calib_algorithm)
  File "/root/space/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 513, in torch2trt_dynamic
    outputs = module(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/models/detectors/two_stage.py", line 52, in forward
    result = self.roi_head_wraper(feat, rois, x.shape[2:])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/models/roi_heads/standard_roi_head.py", line 75, in forward
    bbox_results = self._bbox_forward(feat, rois)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/models/roi_heads/standard_roi_head.py", line 44, in _bbox_forward
    x[:len(self.bbox_roi_extractor.featmap_strides)], rois)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/models/roi_heads/roi_extractors/single_level_roi_extractor.py", line 22, in forward
    return self.roi_extractor(feats, rois, roi_scale_factor)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/space/torch2trt_dynamic/torch2trt_dynamic/torch2trt_dynamic.py", line 298, in wrapper
    outputs = method(*args, **kwargs)
  File "/root/space/mmdetection-to-tensorrt/mmdet2trt/models/roi_heads/roi_extractors/pooling_layers/roi_align_extractor.py", line 32, in forward
    roi_feats[inds] = roi_feats_t
RuntimeError: shape mismatch: value tensor of shape [9, 256, 7, 7] cannot be broadcast to indexing result of shape [0, 10, 256, 7, 7]

---------------------------------------------------------------------------------------------------------------------------
**the mask_rcnn_r50_fpn_2x_coco_acid_alkali.py**
_base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_2x.py', '../_base_/default_runtime.py'
]
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=13),
        mask_head=dict(num_classes=13)))

test_pipeline = [
    dict(type='LoadImageFromWebcam'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

dataset_type = 'CocoDataset'
classes = (
    "large_white_reagent_bottle",
    "NaCl_label",
    "small_white_reagent_bottle",
    "dropper",
    "fentai_label",
    "tube",
    "red_tube_liquid",
    "white_tube_liquid",
    "inverted_bottle_cap",
    "bottle_cap",
    "beaker",
    "waste_cup_label",
    "HCl_label",
)
data_root = '/home/dm/dataset/acid_alkali_samples_det/'
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=8,
    train=dict(
        classes=classes,
        ann_file=data_root + 'annotations/train.json',
        img_prefix=data_root + 'train/',
    ),
    val=dict(
        classes=classes,
        ann_file=data_root + 'annotations/val.json',
        img_prefix=data_root + 'val/',
        pipeline=test_pipeline,
    ),
    test=dict(
        classes=classes,
        ann_file=data_root + 'annotations/val.json',
        img_prefix=data_root + 'val/',
        pipeline=test_pipeline,
    ))

test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=10,
        nms_post=10,
        max_num=1000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100,
        mask_thr_binary=0.5))

**Comment by RunningLeon** [comment]
@xzsong Please be noted that mask-rcnn for pytorch->onnx->tensorrt is not supported in mmdetection.

**Comment by xzsong** [comment]
@RunningLeon hi, if i want to convert mask-rcnn model to tensorrt, how can i do this? thank you

**Comment by RunningLeon** [comment]
@xzsong Please try with the latest mmcv on master branch and mmdetection on [onnx branch](https://github.com/open-mmlab/mmdetection/tree/onnx).
