### ISSUE TITLE
RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3

### ISSUE THREAD

**Issue by jewelc92** [open-mmlab/mmdetection#4850]
I change '../_base_/datasets/coco_detection.py' to '../_base_/datasets/voc0712.py' in cornernet_hourglass104_mstest_32x3_210e_coco.py and num_classes,  and command line is python tools/train.py configs/cornernet/cornernet_hourglass104_mstest_32x3_210e_coco.py

Traceback (most recent call last):
  File "tools/train.py", line 193, in <module>
    main()
  File "tools/train.py", line 189, in main
    meta=meta)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/detectors/single_stage.py", line 108, in forward_train
    x = self.extract_feat(img)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/detectors/single_stage.py", line 58, in extract_feat
    x = self.backbone(img)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 191, in forward
    hourglass_feat = single_hourglass(inter_feat)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 74, in forward
    low2 = self.low2(low1)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 74, in forward
    low2 = self.low2(low1)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 74, in forward
    low2 = self.low2(low1)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 74, in forward
    low2 = self.low2(low1)
  File "/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/person/cj/mmdetection-2.10.0/mmdet/models/backbones/hourglass.py", line 77, in forward
    return up1 + up2
RuntimeError: The size of tensor a (13) must match the size of tensor b (14) at non-singleton dimension 3

It seems that the 'train_pipeline' in cornernet_hourglass104_mstest_32x3_210e_coco.py doesn't replace the 'train_pipeline' in voc0712.py

**Comment by jshilong** [comment]
Is there any modification? especially `size_divisor` in `Pad` operation.

**Comment by jewelc92** [comment]
> Is there any modification? especially `size_divisor` in `Pad` operation.

No, as I said, I only change "'../_base_/datasets/coco_detection.py'" to ''../_base_/datasets/voc0712.py' and "num_classes" from 80 to 20。Now, I copy the "train_pipeline" and "test_pipeline" from cornernet_hourglass104_mstest_32x3_210e_coco.py and replace the original in voc0712, it works.

**Comment by lt1103725556** [comment]
> > Is there any modification? especially `size_divisor` in `Pad` operation.
> 
> No, as I said, I only change "'../_base_/datasets/coco_detection.py'" to ''../_base_/datasets/voc0712.py' and "num_classes" from 80 to 20。Now, I copy the "train_pipeline" and "test_pipeline" from cornernet_hourglass104_mstest_32x3_210e_coco.py and replace the original in voc0712, it works.

it works indeed, but I can't understand why it happens. The "train_pipeline" and "test_pipeline" in "voc0712.py" should be replaced by that in cornernet's config file automatically, shouldn't they?
