### ISSUE TITLE
Error on Mask RCNN when change BN to GN

### ISSUE THREAD

**Issue by yc0619** [open-mmlab/mmdetection#4856]
I have changed the 

`model = dict (
                       backbone=dict(
                                                norm_cfg=dict(type='GN', requires_grad=True)))`

By training, it raises error:
`Traceback (most recent call last):
  File "/home/chao/mmcv/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/home/chao/swa_mmdetection/mmdet/models/backbones/resnet.py", line 417, in __init__
    self._make_stem_layer(in_channels, stem_channels)
  File "/home/chao/swa_mmdetection/mmdet/models/backbones/resnet.py", line 567, in _make_stem_layer
    self.norm_cfg, stem_channels, postfix=1)
  File "/home/chao/mmcv/mmcv/cnn/bricks/norm.py", line 112, in build_norm_layer
    assert 'num_groups' in cfg_
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chao/mmcv/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/home/chao/swa_mmdetection/mmdet/models/detectors/mask_rcnn.py", line 24, in __init__
    pretrained=pretrained)
  File "/home/chao/swa_mmdetection/mmdet/models/detectors/two_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/chao/swa_mmdetection/mmdet/models/builder.py", line 39, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/chao/swa_mmdetection/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/chao/mmcv/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: ResNet: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train.py", line 187, in <module>
    main()
  File "./tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/chao/swa_mmdetection/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/chao/swa_mmdetection/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/chao/mmcv/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: MaskRCNN: ResNet: `

Have i did something wrong by the changing?
Thanks for the help.

**Comment by yc0619** [comment]
I have change the pre train model to 
`_base_ = '../mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
conv_cfg = dict(type='ConvWS')
norm_cfg = dict(type='GN', num_groups=32, requires_grad=True)
model = dict(
    pretrained='open-mmlab://jhu/resnet50_gn_ws',
    backbone=dict(conv_cfg=conv_cfg, norm_cfg=norm_cfg),
    neck=dict(conv_cfg=conv_cfg, norm_cfg=norm_cfg),
    roi_head=dict(
        bbox_head=dict(
            type='Shared4Conv1FCBBoxHead',
            conv_out_channels=256,
            conv_cfg=conv_cfg,
            norm_cfg=norm_cfg),
        mask_head=dict(conv_cfg=conv_cfg, norm_cfg=norm_cfg)))
# learning policy
lr_config = dict(step=[16, 22])
runner = dict(type='EpochBasedRunner', max_epochs=24)`

And set the norm_cfg as the code above, it runs perfect. Still would like to ask what means 'ConvWS' and is it necessary to change the num_groups in norm_cfg. My training data is 512*512.

Thanks

**Comment by fengyouliang** [comment]
`num_groups` necessary
`ConvWS` is another conv layer
