### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by BraveDrXuTF** [open-mmlab/mmdetection#4867]
```bash
root@6055f3edc6300f81f11f0153:/data-input/mmdetection# python tools/train.py --no-validate /data-input/mmdetection/configs/cascade_rcnn/cascade_forpandas.py
2021-03-31 16:49:59,077 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.7 (default, Dec 21 2020, 20:10:35) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: '/usr/local/cuda'
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.4
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1+cu110
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.10.0+79c8dd5
------------------------------------------------------------

2021-03-31 16:50:03,947 - mmdet - INFO - Distributed training: False
2021-03-31 16:50:08,834 - mmdet - INFO - Config:
model = dict(
    type='CascadeRCNN',
    pretrained='torchvision://resnet101',
    backbone=dict(
        type='ResNet',
        depth=101,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='CascadeRoIHead',
        num_stages=3,
        stage_loss_weights=[1, 0.5, 0.25],
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=[
            dict(type='Shared2FCBBoxHead', num_classes=4),
            dict(type='Shared2FCBBoxHead', num_classes=4),
            dict(type='Shared2FCBBoxHead', num_classes=4)
        ],
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=4,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=0,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=2000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.5,
                    neg_iou_thr=0.5,
                    min_pos_iou=0.5,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.6,
                    neg_iou_thr=0.6,
                    min_pos_iou=0.6,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False),
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.7,
                    neg_iou_thr=0.7,
                    min_pos_iou=0.7,
                    match_low_quality=False,
                    ignore_iof_thr=-1),
                sampler=dict(
                    type='RandomSampler',
                    num=512,
                    pos_fraction=0.25,
                    neg_pos_ub=-1,
                    add_gt_as_proposals=True),
                mask_size=28,
                pos_weight=-1,
                debug=False)
        ]),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1024, 1024), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=0,
    train=({
        'type':
        'CocoDataset',
        'classes': ('visible body', 'full body', 'head', 'vehicle'),
        'ann_file':
        '/data-user/ann_coco.json',
        'img_prefix':
        '/data-input/PANDA-Toolkit/train_scaled/image_train3_v_2048',
        'pipeline': [{
            'type': 'LoadImageFromFile'
        }, {
            'type': 'LoadAnnotations',
            'with_bbox': True
        }, {
            'type': 'Resize',
            'img_scale': (1024, 1024),
            'keep_ratio': True
        }, {
            'type': 'RandomFlip',
            'flip_ratio': 0.5
        }, {
            'type': 'Normalize',
            'mean': [123.675, 116.28, 103.53],
            'std': [58.395, 57.12, 57.375],
            'to_rgb': True
        }, {
            'type': 'Pad',
            'size_divisor': 32
        }, {
            'type': 'DefaultFormatBundle'
        }, {
            'type': 'Collect',
            'keys': ['img', 'gt_bboxes', 'gt_labels']
        }]
    }, ),
    val=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/instances_val2017.json',
        img_prefix='data/coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    imgs_per_gpu=2)
evaluation = dict(metric=['bbox', 'segm'])
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '/data-user/latest.pth'
resume_from = None
workflow = [('train', 1)]
classes = ('visible body', 'full body', 'head', 'vehicle')
dataset_A_train = ({
    'type':
    'CocoDataset',
    'classes': ('visible body', 'full body', 'head', 'vehicle'),
    'ann_file':
    '/data-user/ann_coco.json',
    'img_prefix':
    '/data-input/PANDA-Toolkit/train_scaled/image_train3_v_2048',
    'pipeline': [{
        'type': 'LoadImageFromFile'
    }, {
        'type': 'LoadAnnotations',
        'with_bbox': True
    }, {
        'type': 'Resize',
        'img_scale': (1024, 1024),
        'keep_ratio': True
    }, {
        'type': 'RandomFlip',
        'flip_ratio': 0.5
    }, {
        'type': 'Normalize',
        'mean': [123.675, 116.28, 103.53],
        'std': [58.395, 57.12, 57.375],
        'to_rgb': True
    }, {
        'type': 'Pad',
        'size_divisor': 32
    }, {
        'type': 'DefaultFormatBundle'
    }, {
        'type': 'Collect',
        'keys': ['img', 'gt_bboxes', 'gt_labels']
    }]
}, )
dataset_B_train = ({
    'type':
    'CocoDataset',
    'classes': ('visible body', 'full body', 'head', 'vehicle'),
    'ann_file':
    '/data-user/anno_coco_05.json',
    'img_prefix':
    '/data-user/train_scaled_05_v/image_train',
    'pipeline': [{
        'type': 'LoadImageFromFile'
    }, {
        'type': 'LoadAnnotations',
        'with_bbox': True
    }, {
        'type': 'Resize',
        'img_scale': (1024, 1024),
        'keep_ratio': True
    }, {
        'type': 'RandomFlip',
        'flip_ratio': 0.5
    }, {
        'type': 'Normalize',
        'mean': [123.675, 116.28, 103.53],
        'std': [58.395, 57.12, 57.375],
        'to_rgb': True
    }, {
        'type': 'Pad',
        'size_divisor': 32
    }, {
        'type': 'DefaultFormatBundle'
    }, {
        'type': 'Collect',
        'keys': ['img', 'gt_bboxes', 'gt_labels']
    }]
}, )
work_dir = './work_dirs/cascade_forpandas'
gpu_ids = range(0, 1)

2021-03-31 16:50:09,940 - mmdet - INFO - load model from: torchvision://resnet101
2021-03-31 16:50:09,940 - mmdet - INFO - Use load_from_torchvision loader
2021-03-31 16:50:10,386 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=7.12s)
creating index...
index created!
2021-03-31 16:50:18,893 - mmdet - WARNING - "imgs_per_gpu" is deprecated in MMDet V2.0. Please use "samples_per_gpu" instead
2021-03-31 16:50:18,893 - mmdet - WARNING - Got "imgs_per_gpu"=2 and "samples_per_gpu"=2, "imgs_per_gpu"=2 is used in this experiments
2021-03-31 16:50:22,871 - mmdet - INFO - load checkpoint from /data-user/latest.pth
2021-03-31 16:50:22,872 - mmdet - INFO - Use load_from_local loader
2021-03-31 16:50:42,941 - mmdet - INFO - Start running, host: root@6055f3edc6300f81f11f0153, work_dir: /data-input/mmdetection/work_dirs/cascade_forpandas
2021-03-31 16:50:42,941 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 176, in main
    train_detector(
  File "/data-input/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/usr/local/lib/python3.8/dist-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/data-input/mmdetection/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/data-input/mmdetection/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data-input/mmdetection/mmdet/models/detectors/two_stage.py", line 161, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "/data-input/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 267, in forward_train
    mask_results = self._mask_forward_train(
  File "/data-input/mmdetection/mmdet/models/roi_heads/cascade_roi_head.py", line 192, in _mask_forward_train
    mask_targets = self.mask_head[stage].get_targets(
  File "/data-input/mmdetection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 133, in get_targets
    mask_targets = mask_target(pos_proposals, pos_assigned_gt_inds,
  File "/data-input/mmdetection/mmdet/core/mask/mask_target.py", line 58, in mask_target
    mask_targets = map(mask_target_single, pos_proposals_list,
TypeError: 'NoneType' object is not iterable
```

**Comment by hhaAndroid** [comment]
Please use the issue template

**Comment by fangxu622** [comment]
I have the same questions.
Have you solved it?

**Comment by TaChao** [comment]
+1  Use custom coco dataset and maskrcnn 。

**Comment by chentiao** [comment]
+1

**Comment by henfy233** [comment]
+1

**Comment by ganesh3** [comment]
+1

**Comment by FelixGrabscheit** [comment]
+1

**Comment by gouthamkallempudi** [comment]
+1

**Comment by sadransh** [comment]
+1

**Comment by auniquesun** [comment]
> 

where is the issue template?

**Comment by shujunyy123** [comment]
> +1

**Comment by AdorableJiang** [comment]
+1

**Comment by AdorableJiang** [comment]
I ran into this problem after modifying the dataset of `configs\cascade_rcnn\cascade_mask_rcnn_r50_fpn_20e_coco.py` to `../_base_/datasets/voc0712.py`. Is there any other config needs to be applied to the new config file as well?

**Comment by tik0** [comment]
In ran into this issue when I tried to apply the [2_new_data_model.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/2_new_data_model.md) example to my own dataset. I found out that some of my `annotation` in the JSON file missed the `segmentation` element with its corresponding data. Therefore, the data loader stored `None` in the dictionary. Everything worked fines after I've pruned the invalid annotations.

**Comment by ryanalexmartin** [comment]
I still have this issue, despite validating that my annotation file has no empty annotations.  For what it's worth, I'm using `3.x` branch.

I think it would be a good idea to add a new tag for issues with `3.x` so they don't get muddled.
