### ISSUE TITLE
Error in converting SlowFast model to onnx using tools/pytorch2onnx.py, looks something link to detection

### ISSUE THREAD

**Issue by arvindchandel** [open-mmlab/mmdetection#4878]
Getting error below while running the  conversion script. Seek help on this.

(open-mmlab) dev2@dev2-Euclid:~/mmaction2$ python tools/pytorch2onnx.py configs/detection/ava/custom_slowfast_arvind.py checkpoint/slowfast_r50_4x16x1_256e_kinetics400_rgb_20200704-bcde7ed7.pth --verify
Use load_from_local loader
The model and loaded state dict do not match exactly

unexpected key in source state_dict: cls_head.fc_cls.weight, cls_head.fc_cls.bias

missing keys in source state_dict: roi_head.bbox_head.fc_cls.weight, roi_head.bbox_head.fc_cls.bias

/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "
/home/dev2/mmdetection/mmdet/core/bbox/transforms.py:70: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.size(0) > 0:
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 236, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 147, in pytorch2onnx
    opset_version=opset_version)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/dev2/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/dev2/mmdetection/mmdet/models/detectors/two_stage.py", line 101, in forward_dummy
    roi_outs = self.roi_head.forward_dummy(x, proposals)
  File "/home/dev2/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 60, in forward_dummy
    bbox_results = self._bbox_forward(x, rois)
TypeError: _bbox_forward() missing 1 required positional argument: 'img_metas'

**Comment by RunningLeon** [comment]
@arvindchandel 
@xvjiarui 
This could be the version mismatch of mmdetecion. Suggest you try with the latest mmdetecion.

**Comment by arvindchandel** [comment]
@RunningLeon @xvjiarui with new mmdetection, error is below

root@arvind:/opt/caml/mmaction2# python3 tools/pytorch2onnx.py ../caml-core/har_predictor/configs/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py ../caml-core/har_predictor/models/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb_20201217-ae225e97.pth         
/opt/caml/mmaction2/mmaction/models/builder.py:79: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model. Details see this PR: https://github.com/open-mmlab/mmaction2/pull/629
  UserWarning)
/opt/caml/mmdetection/mmdet/models/builder.py:52: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Use load_from_local loader
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 169, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 74, in pytorch2onnx
    opset_version=opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward_dummy() got an unexpected keyword argument 'softmax'

**Comment by RunningLeon** [comment]
@hhaAndroid Could you take a look at this issue?

**Comment by junaid340** [comment]
@arvindchandel I'm getting the same error as you! did you find anything helpful to get it fixed?
