### ISSUE TITLE
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by arnyao** [open-mmlab/mmdetection#4947]
Hello·
pytorch 1.4.0
cuda 10.0
python 3.7
dataset coco

This error occurred when I ran the program. Could you please help me to solve this problem

Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, inrun
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in_worker_loop
    data = fetcher.fetch(index)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/custom.py", line 144, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/custom.py", line 157, in prepare_train_img
    return self.pipeline(results)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/transforms.py", line 306, in __call__
    self._pad_masks(results)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/transforms.py", line 298, in _pad_masks
    pad_shape[:2], pad_val=self.pad_val)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/core/mask/structures.py", line 179, in pad
    for mask in self.masks
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/core/mask/structures.py", line 179, in <listcomp>
    for mask in self.masks
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

thanks

**Comment by hhaAndroid** [comment]
Did you modify the code?

**Comment by Chandhana99** [comment]
Hello @arnyao, did this issue got resolved?

Getting the same issue.

Thanks.
