### ISSUE TITLE
maskrcnn ONNX model export error

### ISSUE THREAD

**Issue by KangolHsu** [open-mmlab/mmdetection#4984]
windows10,
torch                  1.7.0+cu110
torchvision            0.8.1+cu110
mmdet                  2.11.0              d:\github\mmdetection\detection\mmdetection-2.11.0

run script:
python tools/deployment/pytorch2onnx.py ./configs/mask_rcnn/mask_rcnn_r50_fpn_2x_coco.py ../checkpoints/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.pth --input-img demo/demo.jpg --test-img demo/demo.jpg --out ../checkpoints_onnx/mask_rcnn_r50_fpn_2x_coco_bbox_mAP-0.392__segm_mAP-0.354_20200505_003907-3e542a40.onnx --opset-version 11 --verify --simplify --show

error logs:
onnxruntime output names: ['boxes', 'labels', 'masks'],             output shapes: [(100, 5), (100,), (100, 1, 800, 1216)]
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 247, in <module>
    cfg_options=args.cfg_options)
  File "tools/deployment/pytorch2onnx.py", line 152, in pytorch2onnx
    atol=1e-05,
  File "C:\Users\Administrator\.conda\envs\torch1.7.0\lib\site-packages\numpy\testing\_private\utils.py", line 1529, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\Administrator\.conda\envs\torch1.7.0\lib\site-packages\numpy\testing\_private\utils.py", line 761, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

(shapes (6, 5), (1, 5) mismatch)
 x: array([[4.829279e+02, 1.940896e+02, 4.984240e+02, 2.122618e+02,
        5.104632e-02],
       [1.187800e+03, 1.940252e+02, 1.205958e+03, 2.122912e+02,...
 y: array([[4.829279e+02, 1.940896e+02, 4.984240e+02, 2.122618e+02,
        5.104659e-02]], dtype=float32)

when I use onnxruntime c++ inference engine to infer demo/demo.jpg,detection results is not the same

**Comment by KangolHsu** [comment]
run script:
python tools/deployment/pytorch2onnx.py ./configs/mask_rcnn/mask_rcnn_r50_caffe_fpn_1x_coco.py ../checkpoints/mask_rcnn_r50_caffe_fpn_1x_coco_bbox_mAP-0.38__segm_mAP-0.344_20200504_231812-0ebd1859.pth --input-img demo/demo.jpg --test-img demo/demo.jpg --out ../checkpoints_onnx/mask_rcnn_r50_caffe_fpn_1x_coco_bbox_mAP-0.38__segm_mAP-0.344_20200504_231812-0ebd1859.onnx --opset-version 11 --verify --simplify --show


error logs:
onnxruntime output names: ['boxes', 'labels', 'masks'],             output shapes: [(100, 5), (100,), (100, 1, 800, 1216)]
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 247, in <module>
    cfg_options=args.cfg_options)
  File "tools/deployment/pytorch2onnx.py", line 152, in pytorch2onnx
    atol=1e-05,
  File "C:\Users\Administrator\.conda\envs\torch1.7.0\lib\site-packages\numpy\testing\_private\utils.py", line 1529, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\Administrator\.conda\envs\torch1.7.0\lib\site-packages\numpy\testing\_private\utils.py", line 761, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

(shapes (18, 5), (0, 5) mismatch)
 x: array([[4.327607e+02, 2.712231e+02, 9.378939e+02, 7.607599e+02,
        2.025224e-02],
       [4.786701e+02, 3.276212e+02, 8.665113e+02, 6.372161e+02,...
 y: array([], shape=(0, 5), dtype=float32)



OUTPUT:
both pytorch result and onnxruntime result are empty.

**Comment by RunningLeon** [comment]
Please check correctness by visualization. Assertation of numetric comparing may fail due to detailed differences of implementation between different frameworks.

**Comment by XianWu-THU** [comment]
I have a same error when exporting a retinanet model from pytorch to onnx.
