### ISSUE TITLE
PAA inference error

### ISSUE THREAD

**Issue by caiduoduo12138** [open-mmlab/mmdetection#4998]
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                                                  ] 0/1000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 220, in <module>
    main()
  File "tools/test.py", line 190, in main
    args.show_score_thr)
  File "/home/cai/mmdetection/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/cai/mmdetection/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/cai/mmdetection/mmdet/models/detectors/base.py", line 167, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/home/cai/mmdetection/mmdet/models/detectors/single_stage.py", line 154, in aug_test
    return [self.bbox_head.aug_test(feats, img_metas, rescale=rescale)]
  File "/home/cai/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 751, in aug_test
    return self.aug_test_bboxes(feats, img_metas, rescale=rescale)
  File "/home/cai/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 73, in aug_test_bboxes
    bbox_outputs = self.get_bboxes(*bbox_inputs)[0]
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 189, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/cai/mmdetection/mmdet/models/dense_heads/atss_head.py", line 373, in get_bboxes
    with_nms)
  File "/home/cai/mmdetection/mmdet/models/dense_heads/paa_head.py", line 536, in _get_bboxes
    assert with_nms, 'PAA only supports "with_nms=True" now'
AssertionError: PAA only supports "with_nms=True" now
I make sure with_nms=True, 
my environment is
mmdet 2.11.0
cuda11.1
torch1.7.1

**Comment by caiduoduo12138** [comment]
I reboot the machine, it works.
...................

**Comment by guanbin1994** [comment]
I also meet this error
