### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by xinzhichao** [open-mmlab/mmdetection#5034]
Hello, when I use my own data set for training, the program can run, but after a period of training, it will suddenly terminate. It may be the 10th epoch or the 1st epoch. What settings do I have? Is it not the right place.　

when i run cascade_rcnn_x101_64x4d_fpn_1x.py

RuntimeError: The size of tensor a (4) must match the size of tensor b (9) at non-singleton dimension 1

**Comment by hhaAndroid** [comment]
Hi, Can you provide complete information? E.g. complete error message

**Comment by xinzhichao** [comment]
> Hi, Can you provide complete information? E.g. complete error message

sorry，
2021-04-21 10:29:48,485 - mmdet - INFO - Epoch [1][200/7417]    lr: 4.584e-04, eta: 1 day, 11:18:11, time: 1.165, data_time: 0.005, memory: 7563, loss_cls: 1.0233, loss_bbox: 0.9092, loss_dfl: 0.4767, loss: 2.4092
2021-04-21 10:30:48,286 - mmdet - INFO - Epoch [1][250/7417]    lr: 5.733e-04, eta: 1 day, 11:36:20, time: 1.196, data_time: 0.006, memory: 7563, loss_cls: 0.8554, loss_bbox: 0.8731, loss_dfl: 0.4612, loss: 2.1897
2021-04-21 10:31:46,308 - mmdet - INFO - Epoch [1][300/7417]    lr: 6.882e-04, eta: 1 day, 11:37:07, time: 1.160, data_time: 0.006, memory: 7563, loss_cls: 0.8586, loss_bbox: 0.8980, loss_dfl: 0.4735, loss: 2.2301
2021-04-21 10:32:42,522 - mmdet - INFO - Epoch [1][350/7417]    lr: 8.030e-04, eta: 1 day, 11:27:52, time: 1.124, data_time: 0.005, memory: 7563, loss_cls: 0.9923, loss_bbox: 0.8502, loss_dfl: 0.4539, loss: 2.2964
2021-04-21 10:33:38,669 - mmdet - INFO - Epoch [1][400/7417]    lr: 9.179e-04, eta: 1 day, 11:20:23, time: 1.123, data_time: 0.005, memory: 7563, loss_cls: 1.7532, loss_bbox: 0.8804, loss_dfl: 0.4672, loss: 3.1008
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/home/xinzhichao/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/xinzhichao/mmdetection/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/xinzhichao/mmdetection/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/xinzhichao/mmdetection/mmdet/models/detectors/single_stage.py", line 95, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/home/xinzhichao/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/xinzhichao/mmdetection/mmdet/models/dense_heads/gfl_head.py", line 362, in loss
    num_total_samples=num_total_samples)
  File "/home/xinzhichao/mmdetection/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/xinzhichao/mmdetection/mmdet/models/dense_heads/gfl_head.py", line 276, in loss_single
    avg_factor=1.0)
  File "/home/xinzhichao/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xinzhichao/mmdetection/mmdet/models/losses/iou_loss.py", line 342, in forward
    return (pred * weight).sum()  # 0
RuntimeError: The size of tensor a (4) must match the size of tensor b (9) at non-singleton dimension 1

**Comment by hhaAndroid** [comment]
O, This problem has been fixed, please use the latest version. you can refer to https://github.com/open-mmlab/mmdetection/pull/4982
