### ISSUE TITLE
AssertionError: aug test does not support inference with batch size 2

### ISSUE THREAD

**Issue by caiduoduo12138** [open-mmlab/mmdetection#5057]
If aug test is applied in dataset config, It seems that batch interence can not be applied. Can you give me some advice, thanks. 
My dataset config:
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=[(1333, 600), (1333, 1000)], multiscale_mode='range', keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='Pad', size_divisor=32),
    dict(type='Albu',
         transforms=albu_train_transforms,
         bbox_params=dict(type='BboxParams',
                          format='pascal_voc',
                          label_fields=['gt_labels'],
                          min_visibility=0.0,
                          filter_lost_elements=True),
         keymap={'img': 'image', 'gt_bboxes': 'bboxes'},
         update_pad_shape=False,
         skip_img_without_anno=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=[(1333, 600), (1333, 800), (1333, 1000)],
        flip=True,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

Error information:
Use load_from_local loader
[                                                  ] 0/1200, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 221, in <module>
    main()
  File "tools/test.py", line 191, in main
    args.show_score_thr)
  File "/home/cai/mmdetection/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cai/anaconda3/envs/mmd2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/cai/mmdetection/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/cai/mmdetection/mmdet/models/detectors/base.py", line 162, in forward_test
    assert imgs[0].size(0) == 1, 'aug test does not support ' \
AssertionError: aug test does not support inference with batch size 2

**Comment by hhaAndroid** [comment]
Yes. aug test does not support inference with batch size >1.
