### ISSUE TITLE
Why am I stuck during dist training and the CPU usage rate is 100%？

### ISSUE THREAD

**Issue by noobying** [open-mmlab/mmdetection#5060]
When I train my custom model on coco, I always get stuck after several iterations, sometimes not, it will appear on different machines. And it always happens when i use the dist train. 
Here is message when I interrupt.
`
^CTraceback (most recent call last):
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/site-packages/torch/distributed/launch.py", line 254, in main
    process.wait()
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/zpf/miniconda3/envs/solotr/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

`

**Comment by noobying** [comment]
It seems like a deadlock problem. But I don't know how to solve it

**Comment by cl886699** [comment]
i got the same problem, sometimes it happened after several dozen steps, sometimes it happend after several epochs.

2021-04-29 01:11:06,095 - mmdet - INFO - Epoch [16][810/1676]   lr: 1.000e-02, eta: 3:48:26, time: 0.958, data_time: 0.007, memory: 8059, loss_cls: 0.5132, loss_bbox: 0.2357, loss_bbox_rf: 0.2942, loss: 1.0430

^CTraceback (most recent call last):
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in main
    process.wait()
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 971, in wait
    return self._wait(timeout=timeout)
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 1601, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/ai/anaconda3/envs/torch/lib/python3.7/subprocess.py", line 1559, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

**Comment by cl886699** [comment]
the GPU usage rate is  also 100%

**Comment by noobying** [comment]
> the GPU usage rate is also 100%

I solved it by modify my model forward code where may cause gradient inconsistent between multi gpus. In my case , I replace the logic block(if while) with matrix form.
This blog may help.[https://www.cnblogs.com/Xiaoyan-Li/p/14451547.html](url)

**Comment by zhmengyu01** [comment]
> It seems like a deadlock problem. But I don't know how to solve it

i meet the same issue when num_fg_imgs = 0 in loss function.
