### ISSUE TITLE
ERROR: Model Complexity of Cascade PRN

### ISSUE THREAD

**Issue by Dinghaoxuan** [open-mmlab/mmdetection#5063]
When I use the tools/analysis_tools/get_flops.py to compute the Flops and # of Parameters of Cascade-RPN-Faster-RCNN and Cascade-RPN, I got an error "NotImplementedError". 

Here is the TraceBack I got:

Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 84, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 74, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/anaconda3/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 104, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/lib/python3.8/site-packages/mmdet-2.11.0-py3.8.egg/mmdet/models/detectors/rpn.py", line 62, in forward_dummy
    rpn_outs = self.rpn_head(x)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 175, in _forward_unimplemented
    raise NotImplementedError

**Comment by jshilong** [comment]
We do not support calculating the flops of cascade

**Comment by jshilong** [comment]
If you really need it, you can implement `forward_dummy` by yourself
