### ISSUE TITLE
UnboundLocalError: local variable 'beta1' referenced before assignment

### ISSUE THREAD

**Issue by CharlesChen24** [open-mmlab/mmdetection#5083]
When I run 'python tools/train.py configs/detr/detr_r50_8x2_150e_coco.py‘，An UnboundLocalError occured. Please help me.

My env:
GCC: gcc (GCC) 6.4.0
PyTorch: 1.8.0+cu111
TorchVision: 0.9.0+cu111
OpenCV: 4.5.1
MMCV: 1.2.4
MMCV Compiler: GCC 6.4
MMCV CUDA Compiler: 11.1
MMDetection: 2.11.0+

Error Information:
Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File ".../mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File ".../lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File ".../lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File ".../lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File ".../lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 34, in after_train_iter
    runner.optimizer.step()
  File ".../lib/python3.7/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File ".../lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File ".../lib/python3.7/site-packages/torch/optim/adamw.py", line 117, in step
    beta1,
UnboundLocalError: local variable 'beta1' referenced before assignment

**Comment by shinya7y** [comment]
It seems a bug of PyTorch 1.8.0.
https://github.com/pytorch/pytorch/issues/55740

**Comment by CharlesChen24** [comment]
Thanks for your reply. Actually, this is indeed an error in pytorch1.8.0. And I have solved this problem successfully by your link.

**Comment by fangxu622** [comment]
> Thanks for your reply. Actually, this is indeed an error in pytorch1.8.0. And I have solved this problem successfully by your link.

are you think it right to just decreases one tab, although it can be run.
