### ISSUE TITLE
Error occur during running

### ISSUE THREAD

**Issue by lr13953301387** [open-mmlab/mmdetection#5154]
I believed I have install all the requirements  but when I trying to runs the following code "from mmdet.apis import inference_detector, init_detector, show_result_pyplot". It raise an error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/senter/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/senter/mmdetection/mmdet/apis/inference.py", line 10, in <module>
    from mmdet.core import get_classes
  File "/home/senter/mmdetection/mmdet/core/__init__.py", line 4, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/senter/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/senter/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/senter/miniconda3/envs/yolo/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

Does anyone know what might cause it and how to fix it?

**Comment by krybkin** [comment]
`pip install numpy==1.20.1` should help

**Comment by lr13953301387** [comment]
> `pip install numpy==1.20.1` should help

Thank you!

**Comment by del-zhenwu** [comment]
I have the problem too, can we add this in `FAQ` or `requirements` @ZwwWayne ?
