### ISSUE TITLE
Error while train resnest Mask R-CNN  model 

### ISSUE THREAD

**Issue by abdoelsayed2016** [open-mmlab/mmdetection#5164]
Traceback (most recent call last):
  File "/content/drive/MyDrive/ColabNotebooks/Table_work/mmdetection/tools/train.py", line 187, in <module>
    main()
  File "/content/drive/MyDrive/ColabNotebooks/Table_work/mmdetection/tools/train.py", line 183, in main
    meta=meta)
  File "/content/drive/My Drive/ColabNotebooks/Table_work/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'

**Comment by hhaAndroid** [comment]
Please use issue template.
