### ISSUE TITLE
AssertionError: contour_expand miss in module _ext

### ISSUE THREAD

**Issue by kwuliang** [open-mmlab/mmdetection#5178]
python ./tools/train.py configs/reppoints/reppoints_moment_r50_fpn_1x_coco.py --work-dir /home/wuliang/work-dir/Reppoints

Traceback (most recent call last):
  File "./tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/wuliang/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/wuliang/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/home/wuliang/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 5, in <module>
    from .contour_expand import contour_expand
  File "/home/wuliang/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/ops/contour_expand.py", line 6, in <module>
    ext_module = ext_loader.load_ext('_ext', ['contour_expand'])
  File "/home/wuliang/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: contour_expand miss in module _ext

**Comment by hhaAndroid** [comment]
This means that mmcv did not compile successfully. It is recommended that you download the pre-compiled version directly from https://github.com/open-mmlab/mmcv.
