### ISSUE TITLE
I got an error when  use the inference code in api with custom data input pipeline

### ISSUE THREAD

**Issue by BboyHanat** [open-mmlab/mmdetection#5200]
**Checklist**
**Describe the bug**
```
TypeError: 'DataContainer' object is not iterable
```
**Reproduction**
inference my detection model with   custom data input pipeline

config-file:
```# dataset settings
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    test=dict(
        pipeline=[
            dict(type='LoadImageFromWebcam'),
            dict(type='Resize', img_scale=(1280, 640), keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'], meta_keys=('filename', 'ori_filename', 'ori_shape',
                                                          'img_shape', 'pad_shape', 'scale_factor',
                                                          'img_norm_cfg'))
        ]
    )
)
```

**Environment**

```sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cpu
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cpu
OpenCV: 4.5.1
MMCV: 1.3.3
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: not available
MMDetection: 2.12.0+6293bf1
```

**Error traceback**

```Traceback (most recent call last):
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanat/anaconda3/envs/cvpy37/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hanat/WorkSpace/code/DefectDetectionMM-flask/app/api_views.py", line 130, in web_object_detection_image_file
    result_image = detect_and_draw_result(net_model, img_nd)
  File "/home/hanat/WorkSpace/code/DefectDetectionMM-flask/app/inference.py", line 89, in detect_and_draw_result
    result = inference_detector(net, image)
  File "/home/hanat/code/mmdetection/mmdet/apis/inference.py", line 134, in inference_detector
    data['img_metas'] = [img_metas.data[0] for img_metas in data['img_metas']]
TypeError: 'DataContainer' object is not iterable

```

**Bug fix**

In mmcv/parallel/collate.py
replace line 80 by
```
key: [collate([d[key]] , samples_per_gpu) for d in batch]
```
It is worked in this code, but don't work with have test time augument config-file

**Comment by EdisionWew** [comment]
hi, I got the error too, but suffered that "It is worked in this code, but don't work with have test time augument config-file". How you deal it?
