### ISSUE TITLE
DeformConv is not implemented on CPU

### ISSUE THREAD

**Issue by Tzeny** [open-mmlab/mmdetection#5208]
**Describe the bug**
I have installed your solution in a docker container running on CPU for inference purposes. When I try to run _inference_detector_ I get the following error: "DeformConv is not implemented on CPU". I used the DetectoRS_ResNet variant.

**Reproduction**

Run inference_detector on the cpu using DetectoRS_ResNet.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```
/usr/local/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
fatal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.10 (default, Apr 10 2021, 16:02:25) [GCC 8.3.0]
CUDA available: False
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.2
MMCV: 1.3.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: not available
MMDetection: 2.12.0+
```

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "./TestPredict.py", line 84, in <module>
    predictions = handler.process_image(f'/test_images/{index}', return_predictions=True)
  File "/TestPredict/TestPredictHandler.py", line 44, in process_image
    result = inference_detector(self.model, image_path)
  File "/TestPredict/mmdetection/mmdet/apis/inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/TestPredict/mmdetection/mmdet/models/detectors/base.py", line 169, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/TestPredict/mmdetection/mmdet/models/detectors/base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/TestPredict/mmdetection/mmdet/models/detectors/two_stage.py", line 170, in simple_test
    x = self.extract_feat(img)
  File "/TestPredict/mmdetection/mmdet/models/detectors/two_stage.py", line 61, in extract_feat
    x = self.backbone(img)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/TestPredict/mmdetection/mmdet/models/backbones/detectors_resnet.py", line 321, in forward
    outs = list(super(DetectoRS_ResNet, self).forward(x))
  File "/TestPredict/mmdetection/mmdet/models/backbones/resnet.py", line 642, in forward
    x = res_layer(x)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/TestPredict/mmdetection/mmdet/models/backbones/resnet.py", line 297, in forward
    out = _inner_forward(x)
  File "/TestPredict/mmdetection/mmdet/models/backbones/resnet.py", line 274, in _inner_forward
    out = self.conv2(out)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/ops/saconv.py", line 104, in forward
    self.dilation, self.groups, 1)
  File "/usr/local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 103, in forward
    im2col_step=cur_im2col_step)
RuntimeError: DeformConv is not implemented on CPU
```

**Comment by hhaAndroid** [comment]
Yes, DeformConv is not implemented on CPU for now

**Comment by Tzeny** [comment]
Are there plans to implement it in the near future?

**Comment by hhaAndroid** [comment]
> Are there plans to implement it in the near future?

Not yet

**Comment by ZwwWayne** [comment]
We do not have plans for DCN on GPU for now.
