### ISSUE TITLE
FileNotFoundError: VOCDataset: [Errno 2] No such file or directory: 'data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'

### ISSUE THREAD

**Issue by wujiaors** [open-mmlab/mmdetection#5236]
I use the vocdataset, and I have got the trainval.txt. But it still shows like this:
unexpected key in source state_dict: fc.weight, fc.bias

/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmcv/cnn/utils/weight_init.py:115: UserWarning: init_cfg without layer key, if you do not define override key either, this init_cfg will do nothing
  'init_cfg without layer key, if you do not define override'
Traceback (most recent call last):
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/voc.py", line 19, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/xml_style.py", line 25, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/custom.py", line 88, in __init__
    self.data_infos = self.load_annotations(self.ann_file)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/xml_style.py", line 40, in load_annotations
    img_ids = mmcv.list_from_file(ann_file)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmcv/fileio/parse.py", line 17, in list_from_file
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 164, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/builder.py", line 64, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/builder.py", line 69, in build_dataset
    dataset = _concat_dataset(cfg, default_args)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/builder.py", line 48, in _concat_dataset
    datasets.append(build_dataset(data_cfg, default_args))
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmdet-2.12.0-py3.6.egg/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/XXXX/anaconda3/envs/new_env/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: VOCDataset: [Errno 2] No such file or directory: 'data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'

**Comment by jshilong** [comment]
Please check the path you run the python, it  should be under `mmdetection`

**Comment by wujiaors** [comment]
> Please check the path you run the python, it should be under `mmdetection`

I am sure the path is under mmdetection. How I should do?

**Comment by ZwwWayne** [comment]
could you type `ls ./data/` and post the output?

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by github-yqc** [comment]
Have you solved this problem yet? I also encountered this problem
