### ISSUE TITLE
How can I write a plugin module.

### ISSUE THREAD

**Issue by herrickli** [open-mmlab/mmdetection#5255]
How can I write a plugin module like ContextBlock, BTW, I couldn't find the import position of ContextBlok in the latest repo. Thanks for kindly reply.

**Comment by ZwwWayne** [comment]
You can implement a module following the doc https://mmdetection.readthedocs.io/en/latest/tutorials/customize_models.html#develop-new-components

**Comment by herrickli** [comment]
@ZwwWayne 
Hi, this is what I did.
I create a dir named plugins under mmdet/models/, and put `myBlock.py` into the dir.
The `mmdet/models/builder.py` has no `PLUGIN_LAYERS` variable, so I add this line `PLUGIN_LAYERS = Registry('plugin_layer')`
In  `myBlock.py`, I add this line `from ..builder import PLUGIN_LAYERS`  and use `@PLUGIN_LAYERS.register_module()` to decorate the MyBlock class.
And I got this error, say the block is not found.
```
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 152, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/builder.py", line 68, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/builder.py", line 33, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/licheng/anaconda3/envs/open-mmlabv2/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/detectors/two_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/builder.py", line 38, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/builder.py", line 33, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/licheng/anaconda3/envs/open-mmlabv2/lib/python3.6/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/backbones/resnet.py", line 443, in __init__
    plugins=stage_plugins)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/backbones/resnet.py", line 518, in make_res_layer
    return ResLayer(**kwargs)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/utils/res_layer.py", line 71, in __init__
    **kwargs))
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/backbones/resnet.py", line 214, in __init__
    planes * self.expansion, self.after_conv3_plugins)
  File "/home/licheng/projects/convert_mmd/mmdetection/mmdet/models/backbones/resnet.py", line 233, in make_block_plugins
    postfix=plugin.pop('postfix', ''))
  File "/home/licheng/anaconda3/envs/open-mmlabv2/lib/python3.6/site-packages/mmcv/cnn/bricks/plugin.py", line 78, in build_plugin_layer
    raise KeyError(f'Unrecognized plugin type {layer_type}')
KeyError: 'Unrecognized plugin type MyBlock'
```
I am wondering where is wrong， thanks for your kindly reply.

**Comment by herrickli** [comment]
Here is `myBlock.py` file likes.
```
import torch
from torch import nn

from ..builder import PLUGIN_LAYERS

@PLUGIN_LAYERS.register_module()
class MyBlock(nn.Module):

    _abbr_ = 'MyBlock'

    def __init__(self):
        pass
       
    def forward(self, x):
        pass
       
```

**Comment by ZwwWayne** [comment]
‘__init__.py’ might not be imported. You can directly use custom_imports in your config to directly import this file without using  '__init__.py', e.g.
```python
custom_imports = dict(
    imports=['mmdet.models.backbones.mobilenet'],
    allow_failed_imports=False)
```

**Comment by herrickli** [comment]
@ZwwWayne Hi,I put
```    
    custom_imports = dict(
            imports=['mmdet.models.plugins.MyAttenBlock'],
            allow_failed_imports=False)
```
into backbone=dict(custom_imports...) of config file, and I got this error
```
TypeError: __init__() got an unexpected keyword argument 'custom_imports'
```
