### ISSUE TITLE
RetinaNet onnx2trt verify failed

### ISSUE THREAD

**Issue by yaoqi-zd** [open-mmlab/mmdetection#5266]
### Describe the bug:
I'm trying to convert retinanet with provided pytorch->onnx->tensorrt tools. I can obtain the onnx file successfully by running:
```
python tools/deployment/pytorch2onnx.py configs/retinanet/retinanet_r50_fpn_1x_coco.py checkpoints/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth --output-file export/retinanet_r50_fpn_1x_coco.onnx --input-img demo/demo.jpg --shape 1200 1200 --dynamic-export --show --verify
```
pytorch and onnx files are verified to output allclose values

when I convert onnx to tensorrt, **I can generate trt file but cannot pass the verification step**:
```
python tools/deployment/onnx2tensorrt.py export/retinanet_r50_fpn_1x_coco.onnx --trt-file export/retinanet_r50_fpn_1x_coco.trt --input-img demo/demo.jpg --shape 1200 1200 --show --verify
```
Here are parts of the output logs:
```
TensorRT output names: ['dets', 'labels'],             output shapes: [(100, 5), (100,)]                              [2/1953]
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 227, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 112, in onnx2tensorrt
    np.testing.assert_allclose(ort_dets, trt_dets, rtol=1e-03, atol=1e-05)
  File "/disk2/yaoqi/anaconda3/envs/mmtraffic/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1529, in asse
rt_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/disk2/yaoqi/anaconda3/envs/mmtraffic/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 842, in asse$
t_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 492 / 500 (98.4%)
Max absolute difference: 1146.3584
Max relative difference: 1027.0259
 x: array([[9.013470e+02, 3.101845e+02, 9.815286e+02, 3.665620e+02,
        8.143559e-01],
       [5.525516e+02, 3.275294e+02, 7.094547e+02, 4.220050e+02,...
 y: array([[5.525516e+02, 3.275294e+02, 7.094547e+02, 4.220050e+02,
        8.101704e-01],
       [4.015326e+02, 4.925861e+02, 8.565710e+02, 1.089324e+03,...
```

### Reproduction
```
# pytorch->onnx
python tools/deployment/pytorch2onnx.py configs/retinanet/retinanet_r50_fpn_1x_coco.py checkpoints/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth --output-file export/retinanet_r50_fpn_1x_coco.onnx --input-img demo/demo.jpg --shape 1200 1200 --dynamic-export --show --verify

# onnx->tensorrt
python tools/deployment/onnx2tensorrt.py export/retinanet_r50_fpn_1x_coco.onnx --trt-file export/retinanet_r50_fpn_1x_coco.trt --input-img demo/demo.jpg --shape 1200 1200 --show --verify
```
I didn't modify any of the codes

### Environment
```
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1: Tesla T4
CUDA_HOME: /disk2/yaoqi/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.2
MMCV: 1.3.5
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.2
MMDetection: 2.12.0+a8c681d
```
onnx=1.7.0, onnxruntime=1.5.1, tensorrt=7.2.1.6

**Comment by RunningLeon** [comment]
@yaoqi-zd The numerical values are different between Pytorch and ONNX, but it does not necessarily mean the  exported ONNX model is problematic. You can compare the drawn results and verify with tools by https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/pytorch2onnx.md#how-to-evaluate-the-exported-models

**Comment by yaoqi-zd** [comment]
@RunningLeon I've run the evaluation tool and find the performance same as stated in doc (36.3 mmap on COCO val2017), thanks for your help!

By the way,  when I switch to TensorRT7.1.3.4,  the evaluation performance of tensorrt file on COCO val 2017 drops to 31.9. Do you have any ideas on this? why TensorRT7.1 and 7.2 differs so much?

**Comment by RunningLeon** [comment]
@yaoqi-zd Sorry, we do not have knowledge of this kind. Maybe you could post this issue on TensorRT's github.
