### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by Atul997** [open-mmlab/mmdetection#5274]
I have converted my model into torch serve format and it is trained on GPU , while inferencing I found that by default `inference.py` uses `cuda` for inferencing. We can specify device while inferencing through normal mmdetection models but in conversion this is not available which gives the error. Below is the error traceback- 
```
2021-06-02 17:27:53,113 [WARN ] W-9004-table_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: table, error: Worker died.
2021-06-02 17:27:53,113 [DEBUG] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-table_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2021-06-02 17:27:53,113 [WARN ] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-table_1.0-stderr
2021-06-02 17:27:53,113 [WARN ] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-table_1.0-stdout
2021-06-02 17:27:53,113 [INFO ] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9004 in 2 seconds.
2021-06-02 17:27:53,132 [INFO ] W-9004-table_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-table_1.0-stderr
2021-06-02 17:27:53,132 [INFO ] W-9004-table_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-table_1.0-stdout
2021-06-02 17:27:55,499 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2021-06-02 17:27:55,499 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - [PID]39202
2021-06-02 17:27:55,500 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:55,500 [DEBUG] W-9000-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:55,500 [INFO ] W-9000-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2021-06-02 17:27:55,500 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:55,500 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2021-06-02 17:27:55,502 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9003
2021-06-02 17:27:55,502 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - [PID]39205
2021-06-02 17:27:55,503 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:55,503 [DEBUG] W-9003-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:55,503 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:55,503 [INFO ] W-9003-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9003
2021-06-02 17:27:55,505 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9003.
2021-06-02 17:27:55,562 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:55,571 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:55,579 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9006
2021-06-02 17:27:55,581 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - [PID]39198
2021-06-02 17:27:55,582 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:55,582 [DEBUG] W-9006-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9006-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:55,582 [INFO ] W-9006-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9006
2021-06-02 17:27:55,582 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:55,583 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9006.
2021-06-02 17:27:55,663 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:55,733 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:55,737 [INFO ] W-9000-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:55,831 [INFO ] W-9006-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:56,126 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9001
2021-06-02 17:27:56,126 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - [PID]39233
2021-06-02 17:27:56,126 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:56,127 [DEBUG] W-9001-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:56,127 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:56,127 [INFO ] W-9001-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9001
2021-06-02 17:27:56,127 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9001.
2021-06-02 17:27:56,149 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9007
2021-06-02 17:27:56,149 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - [PID]39225
2021-06-02 17:27:56,149 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:56,149 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:56,150 [DEBUG] W-9007-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:56,150 [INFO ] W-9007-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9007
2021-06-02 17:27:56,159 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9005
2021-06-02 17:27:56,159 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - [PID]39230
2021-06-02 17:27:56,159 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:56,159 [DEBUG] W-9005-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9005-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:56,160 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:56,160 [INFO ] W-9005-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9005
2021-06-02 17:27:56,161 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9007.
2021-06-02 17:27:56,166 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9005.
2021-06-02 17:27:56,185 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:56,231 [INFO ] W-9001-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:56,239 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:56,247 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:56,262 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9002
2021-06-02 17:27:56,262 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - [PID]39224
2021-06-02 17:27:56,262 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:56,262 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:56,262 [DEBUG] W-9002-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:56,262 [INFO ] W-9002-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9002
2021-06-02 17:27:56,263 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9002.
2021-06-02 17:27:56,264 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9004
2021-06-02 17:27:56,265 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - [PID]39244
2021-06-02 17:27:56,265 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Torch worker started.
2021-06-02 17:27:56,265 [DEBUG] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-table_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2021-06-02 17:27:56,265 [INFO ] W-9004-table_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9004
2021-06-02 17:27:56,265 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Python runtime: 3.8.5
2021-06-02 17:27:56,268 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9004.
2021-06-02 17:27:56,287 [INFO ] W-9005-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:56,293 [INFO ] W-9007-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:56,328 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:56,335 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/Grammar.txt
2021-06-02 17:27:56,381 [INFO ] W-9002-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:27:56,383 [INFO ] W-9004-table_1.0-stdout MODEL_LOG - Generating grammar tables from /usr/lib/python3.8/lib2to3/PatternGrammar.txt
2021-06-02 17:28:01,363 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - No CUDA runtime is found, using CUDA_HOME='/usr'
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Use load_from_local loader
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Backend worker process died.
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 182, in <module>
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     worker.run_server()
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 154, in run_server
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 116, in handle_connection
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 89, in load_model
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size, envelope)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/ts/model_loader.py", line 110, in load
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/tmp/models/4a1d614beb934891bccdbab9eb454537/mmdet_handler.py", line 27, in initialize
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     self.model = init_detector(self.config_file, checkpoint, self.device)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmdet/apis/inference.py", line 42, in init_detector
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 522, in load_checkpoint
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     checkpoint = _load_checkpoint(filename, map_location, logger)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 466, in _load_checkpoint
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 243, in load_checkpoint
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     return checkpoint_loader(filename, map_location)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 260, in load_from_local
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     checkpoint = torch.load(filename, map_location=map_location)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     result = unpickler.load()
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 845, in persistent_load
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     load_tensor(data_type, size, key, _maybe_decode_ascii(location))
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 834, in load_tensor
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     loaded_storages[key] = restore_location(storage, location)
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
2021-06-02 17:28:01,364 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     result = fn(storage, location)
2021-06-02 17:28:01,365 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
2021-06-02 17:28:01,365 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     device = validate_cuda_device(location)
2021-06-02 17:28:01,365 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -   File "/home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
2021-06-02 17:28:01,365 [INFO ] W-9003-table_1.0-stdout MODEL_LOG -     raise RuntimeError('Attempting to deserialize object on a CUDA '
2021-06-02 17:28:01,365 [INFO ] W-9003-table_1.0-stdout MODEL_LOG - RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
2021-06-02 17:28:01,409 [WARN ] W-9003-table_1.0-stderr MODEL_LOG - /home/billion/PycharmProjects/tablecell_inference/venv/lib/python3.8/site-packages/mmdet/models/builder.py:70: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
```

How can I map my model to cpu externally or is it possible during conversion?

**Comment by RangiLyu** [comment]
Change device to 'cpu' when you calling init_detector(self.config_file, checkpoint, self.device) function.

**Comment by Atul997** [comment]
CUDA is used in inference API in by default. I know to pass the `cpu` parameter when inferencing through init_detector function explicitly but after or during conversion in torchserve format I don't have any idea.

**Comment by waddington** [comment]
Any update on this? I also have same issue.

The serving docker image works fine with the `--gpus` flag, but if you omit this like the docs say (https://mmdetection.readthedocs.io/en/latest/useful_tools.html?highlight=TorchServe#run-mmdet-serve) you get the above error.

**Comment by iFlyyyy** [comment]
Same here. This is because the GPU is available on your computer but you want to use the CPU

[        self.map_location = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.device = torch.device(self.map_location + ':' +
                                   str(properties.get('gpu_id')) if torch.cuda.
                                   is_available() else self.map_location)](https://github.com/open-mmlab/mmdetection/blob/6cf9aa1866b745fce8f1da6717fdb833d7c66fab/tools/deployment/mmdet_handler.py#L17-L20)

Change them to 'cpu' before convert model to torchserve
