### ISSUE TITLE
object() takes no parameters

### ISSUE THREAD

**Issue by hankangying** [open-mmlab/mmdetection#5283]
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/hyk/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: object() takes no parameters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/hyk/lib/python3.6/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/userdata/hyk/mmdetection/mmdet/datasets/pipelines/test_time_aug.py", line 58, in __init__
    self.transforms = Compose(transforms)
  File "/userdata/hyk/mmdetection/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/usr/local/anaconda3/envs/hyk/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: DefaultFormatBundle: object() takes no parameters

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/userdata/hyk/mmdetection/1.py", line 12, in <module>
    inference_detector(model, 'demo/demo.jpg')
  File "/userdata/hyk/mmdetection/mmdet/apis/inference.py", line 117, in inference_detector
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "/userdata/hyk/mmdetection/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/usr/local/anaconda3/envs/hyk/lib/python3.6/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MultiScaleFlipAug: DefaultFormatBundle: object() takes no parameters

**Comment by hhaAndroid** [comment]
Hi @hankangying Please use the issue template, otherwise we cannot help locate the issue.

**Comment by RangiLyu** [comment]
Closed due to long time with no response. Feel free to reopen it if you still have problems.
