### ISSUE TITLE
A question about how to custom a model that all the components are implemented in MMDetection rightly when the components have duplicate key

### ISSUE THREAD

**Issue by genres17** [open-mmlab/mmdetection#5308]
### Question
1. I wanna custom a new model that all the components are implemented in MMDetection, but straightly inherits the base configs met the error __KeyError: 'Duplicate key is not allowed among bases__ , for instance, I wanna custom a new model with faster_rcnn_x101_64x4d_fpn+guided_anchor(rpn head)+doubleHead(RoI head)+soft_nms, firstly I don't know what the duplicate key is, so I tried the second question step but __I wonder how to solve this rightly__?

2. As the first question says, I can't find what the duplicate key is, so __I tried to copy the configs from implemented model to solve this, but encountered another error AttributeError: 'ConfigDict' object has no attribute 'assigner'__, I know it means my config lost a key 'assigner', but __I definitely find it in my config and I don't know how to solve this, either__. Is this caused by I omit implemented model base config?

### Question Config( my custom config, faster_rcnn_x101_64x4d_fpn+guided_anchor+doubleHead+soft_nms)
for second question
in configs/my_dateset/faster_rcnn_r50_caffe_fpn_guidedanchor_doublehead_softnms_1x_tools.py 
```
_base_ = ['../faster_rcnn/faster_rcnn_x101_64x4d_fpn_1x_coco.py', ]
classes = ('Grasper', 'Bipolar', 'Hook', 'Scissors',
           'Clipper', 'Irrigator', 'SpecimenBag')

# Modify dataset related settings
dataset_type = 'VOCDataset'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    rpn_head=dict(
        _delete_=True,
        type='GARPNHead',
        in_channels=256,
        feat_channels=256,
        approx_anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=8,
            scales_per_octave=3,
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        square_anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0],
            scales=[8],
            strides=[4, 8, 16, 32, 64]),
        anchor_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.07, 0.07, 0.14, 0.14]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.07, 0.07, 0.11, 0.11]),
        loc_filter_thr=0.01,
        loss_loc=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_shape=dict(type='BoundedIoULoss', beta=0.2, loss_weight=1.0),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
    roi_head=dict(
        type='DoubleHeadRoIHead',
        reg_roi_scale_factor=1.3,
        bbox_head=dict(
            _delete_=True,
            type='DoubleConvFCBBoxHead',
            num_convs=4,
            num_fcs=2,
            in_channels=256,
            conv_out_channels=1024,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=len(classes),
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=2.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=2.0))),
    # model training and testing settings
    train_cfg=dict(
        rpn=dict(
            ga_assigner=dict(
                type='ApproxMaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                ignore_iof_thr=-1),
            ga_sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            center_ratio=0.2,
            ignore_ratio=0.5),
        rpn_proposal=dict(nms_post=1000, max_per_img=300),
        rcnn=dict(
            assigner=dict(pos_iou_thr=0.6, neg_iou_thr=0.6, min_pos_iou=0.6),
            sampler=dict(type='RandomSampler', num=256))),
    test_cfg=dict(
        rpn=dict(nms_post=1000, max_per_img=300), rcnn=dict(score_thr=0.05, nms=dict(type='soft_nms', iou_threshold=0.5),)))
optimizer_config = dict(
    _delete_=True, grad_clip=dict(max_norm=35, norm_type=2))

data_root = 'data/VOCdevkit/'

# We can use the pre-trained Mask RCNN model to obtain higher performance
load_from = 'http://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_x101_64x4d_fpn_1x_coco/faster_rcnn_x101_64x4d_fpn_1x_coco_20200204-833ee192.pth'

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1000, 600), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1000, 600),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=8,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt',
            ],
            img_prefix=[data_root + 'VOC2007/'],
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline
    ),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline
    ))
evaluation = dict(interval=1, metric='mAP')
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
total_epochs = 12
work_dir = './work_dirs/faster_rcnn_r50_caffe_fpn_guidedanchor_doublehead_softnms_1x_tools'


```
### Error Info
```
Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 152, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/detectors/faster_rcnn.py", line 24, in __init__
    pretrained=pretrained)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 35, in __init__
    self.rpn_head = build_head(rpn_head_)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/builder.py", line 57, in build_head
    return build(cfg, HEADS)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/dense_heads/ga_rpn_head.py", line 17, in __init__
    super(GARPNHead, self).__init__(1, in_channels, **kwargs)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet-2.5.0-py3.7.egg/mmdet/models/dense_heads/guided_anchor_head.py", line 176, in __init__
    self.assigner = build_assigner(self.train_cfg.assigner)
  File "/home/lsz1/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 42, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'assigner'
```

**Comment by hhaAndroid** [comment]
Hi @genres17 I found no problem with your configuration, except that you need to modify the following configuration

```python
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=0,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            classes=classes, ####### Note
            type=dataset_type,
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt',
            ],
            img_prefix=[data_root + 'VOC2007/'],
            pipeline=train_pipeline)),
    val=dict(
        classes=classes,  ######## Note
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline
    ),
    test=dict(
        classes=classes,  ####### Note
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline
    ))
```

It can run normally

````python
2021-06-08 13:40:30,640 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
2021-06-08 13:41:11,872 - mmdet - INFO - Epoch [1][50/2484]	lr: 1.978e-03, eta: 6:48:20, time: 0.823, data_time: 0.054, memory: 3067, loss_rpn_cls: 0.1444, loss_rpn_bbox: 0.0396, loss_anchor_shape: 0.0230, loss_anchor_loc: 3.1893, loss_cls: 0.5509, acc: 97.8516, loss_bbox: 0.0302, loss: 3.9776, grad_norm: 28.3747
```

Maybe you need to update the version.

**Comment by genres17** [comment]
> 
> 
> Hi @genres17 I found no problem with your configuration, except that you need to modify the following configuration
> 
> ```python
> data = dict(
>     samples_per_gpu=1,
>     workers_per_gpu=0,
>     train=dict(
>         type='RepeatDataset',
>         times=3,
>         dataset=dict(
>             classes=classes, ####### Note
>             type=dataset_type,
>             ann_file=[
>                 data_root + 'VOC2007/ImageSets/Main/trainval.txt',
>             ],
>             img_prefix=[data_root + 'VOC2007/'],
>             pipeline=train_pipeline)),
>     val=dict(
>         classes=classes,  ######## Note
>         type=dataset_type,
>         ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
>         img_prefix=data_root + 'VOC2007/',
>         pipeline=test_pipeline
>     ),
>     test=dict(
>         classes=classes,  ####### Note
>         type=dataset_type,
>         ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
>         img_prefix=data_root + 'VOC2007/',
>         pipeline=test_pipeline
>     ))
> ```
> 
> It can run normally
> 
> ```python
> 2021-06-08 13:40:30,640 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
> 2021-06-08 13:41:11,872 - mmdet - INFO - Epoch [1][50/2484]	lr: 1.978e-03, eta: 6:48:20, time: 0.823, data_time: 0.054, memory: 3067, loss_rpn_cls: 0.1444, loss_rpn_bbox: 0.0396, loss_anchor_shape: 0.0230, loss_anchor_loc: 3.1893, loss_cls: 0.5509, acc: 97.8516, loss_bbox: 0.0302, loss: 3.9776, grad_norm: 28.3747
> ```
> 
>  Maybe you need to update the version.
> ```

Thanks for your reply! However, I've changed VOC classes in official implemented voc.py before so I ignored this. After I modified this in my configuration it still throws this error. I will try it again after updating my mmdet version.
