### ISSUE TITLE
Mask RCNN trains its own dataset

### ISSUE THREAD

**Issue by Ahappyprogrammer** [open-mmlab/mmdetection#5320]
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 371, in __call__
    results = self._load_masks(results)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 323, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 323, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/userdata/anaconda3/envs/mmenv/lib/python3.7/site-packages/mmdet-2.13.0-py3.7.egg/mmdet/datasets/pipelines/loading.py", line 279, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
TypeError: object of type 'float' has no len()

When I convert my dataset to coco format, I want to execute `python tools / train.py configs / mask_ rcnn/mask_ rcnn_ r50_ fpn_ 1x_ coco.py --gpus 1`, but the error is reported. I don't know whether it is a JSON format error or something

**Comment by RangiLyu** [comment]
It seems that your mask format in the annotation is not correct. COCO uses polygon or RLE format to save masks.

**Comment by Ahappyprogrammer** [comment]
> 注释中的掩码格式似乎不正确。COCO 使用多边形或 RLE 格式来保存蒙版。

Thank you. I'll check the JSON format of my dataset again
