### ISSUE TITLE
ImportError: cannot import name 'results2json'

### ISSUE THREAD

**Issue by sunboyan1024** [open-mmlab/mmdetection#5332]
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from batch_train import BatchTrain
  File "/home/ealiser/pythonProject/DefectNet-master/tools/batch_train.py", line 12, in <module>
    from batch_process import batch_train, batch_test
  File "/home/ealiser/pythonProject/DefectNet-master/tools/batch_process.py", line 12, in <module>
    from defect_test import main as test_main
  File "/home/ealiser/pythonProject/DefectNet-master/tools/defect_test.py", line 20, in <module>
    from mmdet.core import results2json, wrap_fp16_model
ImportError: cannot import name 'results2json'
请问这个方法在哪里，应该从哪里引用？

**Comment by RangiLyu** [comment]
In mmdet/datasets/coco.py. It's a member of CocoDataset.

**Comment by colsona** [comment]
Have you solved this probelm?I meet the same issues with you.
