### ISSUE TITLE
config does not exist

### ISSUE THREAD

**Issue by m-nasiri** [open-mmlab/mmdetection#5336]
Hi,
I'm training my own dataset consisting 5 classes. according to documentation i have prepared dataset in coco format and config file as follows

* n_classes = 5
* my dataset is here ~/mmdetection/dataset/pdd
* my config file is here ~/mmdetection/configs/pdd/cascade_rcnn_r50_fpn_1x_pdd.py
* my pretrained-net is here ~/mmdetection/checkpoints/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth

<br>
<br>

This is my cascade_rcnn_r50_fpn_1x_pdd.py file
``` python
# The new config inherits a base config to highlight the necessary modification
_base_ = 'cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=5),
        mask_head=dict(num_classes=5)))

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('chair','handle','table','button','person')
data = dict(
    train=dict(
        img_prefix='dataset/pdd/train/',
        classes=classes,
        ann_file='dataset/pdd/train/pdd_annotation_coco_train.json'),
    val=dict(
        img_prefix='dataset/pdd/val/',
        classes=classes,
        ann_file='dataset/pdd/val/pdd_annotation_coco_val.json'),
    test=dict(
        img_prefix='dataset/pdd/val/',
        classes=classes,
        ann_file='dataset/pdd/val/pdd_annotation_coco_val.json'))

# We can use the pre-trained Mask RCNN model to obtain higher performance
load_from = 'checkpoints/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth'
```

In orther to train i run
``` python
cd mmdetection
python tools/train.py configs/pdd/cascade_rcnn_r50_fpn_1x_pdd.py
``` 
but i get following errors

``` python
Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 251, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 174, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 124, in _file2dict
    check_file_exist(filename)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/deep/mmdetection/configs/pdd/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py" does not exist
``` 

Why do i get this error!!!?

**Bug fix**
I have changed first line or my config file [cascade_rcnn_r50_fpn_1x_pdd.py] 
from 

``` python
_base_ = 'cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py'
``` 
to

``` python
_base_ = '../cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco.py'
``` 

It works but i get another error!

``` python
Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 251, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 184, in _file2dict
    base_cfg_dict = Config._merge_a_into_b(cfg_dict, base_cfg_dict)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 242, in _merge_a_into_b
    b[k] = Config._merge_a_into_b(v, b[k], allow_list_keys)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 242, in _merge_a_into_b
    b[k] = Config._merge_a_into_b(v, b[k], allow_list_keys)
  File "/home/deep/.virtualenvs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 237, in _merge_a_into_b
    raise TypeError(
TypeError: bbox_head={'num_classes': 5} in child config cannot inherit from base because bbox_head is a dict in the child config but is of type <class 'list'> in base config. You may set `_delete_=True` to ignore the base config
``` 
How can i solve the problem? plz help me

**Comment by RangiLyu** [comment]
In cascade rcnn config, the type of bbox_head is List because it has 3 Shared2FCBBoxHead. You need to change num_classes in all these heads. You can refer to configs/_base_/models/cascade_rcnn_r50_fpn.py to modify your config.

**Comment by m-nasiri** [comment]
> In cascade rcnn config, the type of bbox_head is List because it has 3 Shared2FCBBoxHead. You need to change num_classes in all these heads. You can refer to configs/_base_/models/cascade_rcnn_r50_fpn.py to modify your config.

**Comment by m-nasiri** [comment]
> In cascade rcnn config, the type of bbox_head is List because it has 3 Shared2FCBBoxHead. You need to change num_classes in all these heads. You can refer to configs/_base_/models/cascade_rcnn_r50_fpn.py to modify your config.

I have changed all num_classes=80 in configs/_base_/models/cascade_rcnn_r50_fpn.py to num_classes=5 and modified my configs/pdd/cascade_rcnn_r50_fpn_1x_pdd.py file like following 

``` python
# The new config inherits a base config to highlight the necessary modification
_base_ = [
    '../_base_/models/cascade_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_detection.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('chair','handle','table','button','person')
data = dict(
    train=dict(
        img_prefix='dataset/pdd/train/',
        classes=classes,
        ann_file='dataset/pdd/train/pdd_annotation_coco_train.json'),
    val=dict(
        img_prefix='dataset/pdd/val/',
        classes=classes,
        ann_file='dataset/pdd/val/pdd_annotation_coco_val.json'),
    test=dict(
        img_prefix='dataset/pdd/val/',
        classes=classes,
        ann_file='dataset/pdd/val/pdd_annotation_coco_val.json'))

# We can use the pre-trained Mask RCNN model to obtain higher performance
load_from = 'checkpoints/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth'
```

This works for me, tanx
