### ISSUE TITLE
Using a 1280x720 dataset with YOLACT

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#5362]
Hello, it seems like I cant train YOLACT on a single GPU when using a custom dataset that isn't 550 x 550. I am going through the configs to understand why this may be. Is this an issue you encountered before?

**Comment by hhaAndroid** [comment]
Hi @pcicales What's wrong with you? I set `img_size = 520` to run normally.

**Comment by pcicales** [comment]
Hi @hhaAndroid , I removed that line as I wasnt sure if it was overwriting my training data size configs. Perhaps thats the issue?

**Comment by hhaAndroid** [comment]
> Hi @hhaAndroid , I removed that line as I wasnt sure if it was overwriting my own data size configs. Perhaps thats the issue? I set the image sizes elsewhere in config to reflect my dataset.

uess your configuration is incorrect. If you want to check whether your modification is correct, you can use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/print_config.py script to dump it down.

**Comment by pcicales** [comment]
Here it is @hhaAndroid 

```
# results directory name
run_dir = '6_14_2021_run1'

# model settings
# img_size = 550
model = dict(
    type='YOLACT',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,  # do not freeze stem
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,  # update the statistics of bn
        zero_init_residual=False,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        upsample_cfg=dict(mode='bilinear')),
    bbox_head=dict(
        type='YOLACTHead',
        num_classes=8,
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=3,
            scales_per_octave=1,
            base_sizes=[8, 16, 32, 64, 128],
            ratios=[0.5, 1.0, 2.0],
            strides=[550.0 / x for x in [69, 35, 18, 9, 5]], # originally [550.0 / x for x in [69, 35, 18, 9, 5]]
            centers=[(550 * 0.5 / x, 550 * 0.5 / x) for x in [69, 35, 18, 9, 5]]), # originally [(550 * 0.5 / x, 550 * 0.5 / x) for x in [69, 35, 18, 9, 5]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.1, 0.1, 0.2, 0.2]),
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            reduction='none',
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.5),
        num_head_convs=1,
        num_protos=32,
        use_ohem=True),
    mask_head=dict(
        type='YOLACTProtonet',
        in_channels=256,
        num_protos=32,
        num_classes=8,
        max_masks_to_train=100,
        loss_mask_weight=6.125),
    segm_head=dict(
        type='YOLACTSegmHead',
        num_classes=8,
        in_channels=256,
        loss_segm=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0.,
            ignore_iof_thr=-1,
            gt_max_assign_all=False),
        # smoothl1_beta=1.,
        allowed_border=-1,
        pos_weight=-1,
        neg_pos_ratio=3,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        iou_thr=0.5,
        top_k=200,
        max_per_img=100))

# dataset settings
dataset_type = 'CocoDataset'
data_root = '/red/datasets/bdd100k/'
CLASSES = ('pedestrian', 'rider', 'car', 'truck', 'bus', 'train', 'motorcycle', 'bicycle', )

img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=img_norm_cfg['mean'],
        to_rgb=img_norm_cfg['to_rgb'],
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(1280, 720), keep_ratio=False), # originally keep ratio false
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1280, 720),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=4, #batch
    workers_per_gpu=32, #cpu workers
    train=dict(
        type='CocoDataset',
        ann_file=data_root + 'labels/ins_seg_coco/ins_seg_train_mmdetection.json',
        img_prefix=data_root + 'images/10k/train/',
        pipeline=train_pipeline,
        classes=CLASSES),
    val=dict(
        type='CocoDataset',
        ann_file=data_root + 'labels/ins_seg_coco/ins_seg_val_mmdetection.json',
        img_prefix=data_root + 'images/10k/val/',
        pipeline=test_pipeline,
        classes=CLASSES),
    test=dict(
        type='CocoDataset',
        img_prefix=data_root + 'images/10k/test/',
        pipeline=test_pipeline,
        classes=CLASSES))
evaluation = dict(metric=['bbox', 'segm'])

# optimizer
optimizer = dict(type='SGD', lr=1e-3, momentum=0.9, weight_decay=5e-4)
optimizer_config = dict()
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.1,
    step=[20, 42, 49, 52])
runner = dict(type='EpochBasedRunner', max_epochs=80)

checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
custom_hooks = [dict(type='NumClassCheckHook')]

dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = 'dir' + run_dir
load_from = None
resume_from = None
workflow = [('train', 1), ('val', 1)]
```

**Comment by pcicales** [comment]
I just remembered how the code was using the img_size = 550 line; that wont work for me, as I am working with 720p data. Is it possible for me to run this without changing the aspect ration/resolution of the data? @hhaAndroid

**Comment by pcicales** [comment]
@hhaAndroid Here is the traceback after running dist_train on 1 gpu, keeping all config options the same but with 'img_scale=(1280,720)'. As you can see, it successfully trained for one epoch and saved a model, running one round of val without errors.

```
2021-06-15 11:50:16,802 - mmdet - INFO - Saving checkpoint at 1 epochs
2021-06-15 11:50:17,177 - mmdet - INFO - Exp name: yolact_resnet50_8x1_bdd100k_ins_seg.py
2021-06-15 11:50:17,177 - mmdet - INFO - Epoch(val) [1][1000]   bbox_mAP: 0.0360, bbox_mAP_50: 0.0800, bbox_mAP_75: 0.0280, bbox_mAP_s: 0.0230, bbox_mAP_m: 0.0490, bbox_mAP_l: 0.0940, bbox_mAP_copypaste: 0.036 0.080 0.028 0.023 0.049 0.094, segm_mAP: 0.0250, segm_mAP_50: 0.0550, segm_mAP_75: 0.0220, segm_mAP_s: 0.0080, segm_mAP_m: 0.0390, segm_mAP_l: 0.1050, segm_mAP_copypaste: 0.025 0.055 0.022 0.008 0.039 0.105
/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "/red/pycharm_projects/mmdetection/tools/train.py", line 191, in <module>
    main()
  File "/red/pycharm_projects/mmdetection/tools/train.py", line 187, in main
    meta=meta)
  File "/red/pycharm_projects/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 91, in val_step
    output = self.module.val_step(*inputs[0], **kwargs[0])
  File "/red/workspace/pycharm_projects/mmdetection/mmdet/models/detectors/base.py", line 252, in val_step
    losses = self(**data)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/red/workspace/pycharm_projects/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/red/workspace/pycharm_projects/mmdetection/mmdet/models/detectors/yolact.py", line 80, in forward_train
    sampling_results)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/red/workspace/pycharm_projects/mmdetection/mmdet/models/dense_heads/yolact_head.py", line 714, in forward
    mask_pred = cur_prototypes @ cur_coeff_pred.t()
RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D
Traceback (most recent call last):
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/red/anaconda3/envs/AMB_BDD/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/red/anaconda3/envs/AMB_BDD/bin/python', '-u', 'red/workspace/pycharm_projects/mmdetection/tools/train.py', '--local_rank=0', '/red/results/bdd100k/ins_seg/AmbaNet/YOLACT/yolact_resnet50_8x1_bdd100k_ins_seg.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by pcicales** [comment]
@hhaAndroid after running the code exactly as provided in the repo, I get the same exact error as above, even with the resolution set to 550 x 550

**Comment by hhaAndroid** [comment]
> @hhaAndroid after running the code exactly as provided/instructed in the repo, I get the same exact error as above, even with the resolution set to 550 x 550

That’s really weird, I run with coco is normal.

**Comment by pcicales** [comment]
I will try to look more at this when I have some time, let me know if you have any advice.

**Comment by AgatheMo** [comment]
@pcicales @hhaAndroid have you been able to resolve the issue ? I am facing the same problem. The issue only seems to appear when we set a val step in the workflow in the config file : `workflow = [('train', 1), ('val', 1)]`
When you take a look at the `yolact_head.py` code it seems that  `coeff_pred`'s dimension is reduced during the training step while it isn't in the val step, causing the dimension mismatch in the` mask_pred = cur_prototypes @ cur_coeff_pred.t()` line

```
# Training state
        if self.training:
            coeff_pred_list = []
            for coeff_pred_per_level in coeff_pred:
                coeff_pred_per_level = \
                    coeff_pred_per_level.permute(
                        0, 2, 3, 1).reshape(num_imgs, -1, self.num_protos)
                coeff_pred_list.append(coeff_pred_per_level)
            coeff_pred = torch.cat(coeff_pred_list, dim=1)

        mask_pred_list = []
        for idx in range(num_imgs):
            cur_prototypes = prototypes[idx]
            cur_coeff_pred = coeff_pred[idx]
            cur_bboxes = bboxes[idx]
            cur_img_meta = img_meta[idx]

            # Testing state
            if not self.training:
                bboxes_for_cropping = cur_bboxes
            else:
                cur_sampling_results = sampling_results[idx]
                pos_assigned_gt_inds = \
                    cur_sampling_results.pos_assigned_gt_inds
                bboxes_for_cropping = cur_bboxes[pos_assigned_gt_inds].clone()
                pos_inds = cur_sampling_results.pos_inds
                cur_coeff_pred = cur_coeff_pred[pos_inds]

            # Linearly combine the prototypes with the mask coefficients
            mask_pred = cur_prototypes @ cur_coeff_pred.t()
            mask_pred = torch.sigmoid(mask_pred)
```
Do you know how to solve it ?
