### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [open-mmlab/mmdetection#5391]
Hi, I am following [get_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md) to install [mmdetection](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md#install-mmdetection).

`mim install mmdet` gives the following error. Why? How to resolve it? Thank you.

```
(open-mmlab) zeshan@seecs-2288H-V5:~$ mim install mmdet
installing mmdet from https://github.com/open-mmlab/mmdetection.git.
Traceback (most recent call last):
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 390, in call_command
    subprocess.check_call(cmd)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zeshan/.conda/envs/open-mmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/commands/install.py", line 107, in cli
    is_editable=is_editable)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/commands/install.py", line 203, in install
    is_yes, is_user_dir, is_install_master)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/commands/install.py", line 493, in install_from_github
    call_command(clone_cmd)
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 392, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 364, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/zeshan/.conda/envs/open-mmlab/lib/python3.7/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, FileNotFoundError found
```

**Comment by zeeshanalipanhwar** [comment]
I had not installed `git` in the `conda` environment, installing that resolved the issue.

**Comment by Cassieyy** [comment]
I have run “mim install mmdet” again, and installed successfully!!
