### ISSUE TITLE
When I train on one GPU, everything is normal, but when I use multiple GPUs, the problem appears

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5400]
error as following:
raceback (most recent call last):
  File "./train.py", line 188, in <module>
    main()
  File "./train.py", line 162, in main
    model.init_weights()
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/home/liuguangcan/mmdetection/mmdet/models/backbones/swin_transformer.py", line 696, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 306, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 281, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: None is not a checkpoint file
Traceback (most recent call last):
  File "./train.py", line 188, in <module>
    main()
  File "./train.py", line 162, in main
    model.init_weights()
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/home/liuguangcan/mmdetection/mmdet/models/backbones/swin_transformer.py", line 696, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 306, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 281, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: None is not a checkpoint file
Traceback (most recent call last):
  File "./train.py", line 188, in <module>
    main()
  File "./train.py", line 162, in main
    model.init_weights()
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/home/liuguangcan/mmdetection/mmdet/models/backbones/swin_transformer.py", line 696, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 306, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 281, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: None is not a checkpoint file
Traceback (most recent call last):
  File "./train.py", line 188, in <module>
    main()
  File "./train.py", line 162, in main
    model.init_weights()
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/home/liuguangcan/mmdetection/mmdet/models/backbones/swin_transformer.py", line 696, in init_weights
    load_checkpoint(self, self.pretrained, strict=False, logger=logger)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 306, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/home/liuguangcan/mmdetection/mmcv_custom/checkpoint.py", line 281, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: None is not a checkpoint file
Traceback (most recent call last):
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/liuguangcan/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/liuguangcan/anaconda3/envs/open-mmlab/bin/python', '-u', './train.py', '--local_rank=3', '../configs/test/centernet_swin_140e_voc.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by BIGWangYuDong** [comment]
It seems that your checkpoint file name is wrong: `the error is  (f'{filename} is not a checkpoint file'` 
Please check your checkpoint name while you run the code.

**Comment by Bin-ze** [comment]
If I want to initialize my bacjbone through swin trained on the classification task, is it reasonable for me to set it like this in the configuration file:
model = dict(
    type='CenterNet',
    **pretrained='../checkpoints/checkpoints/swin_base_patch4_window12_384_22k.pth',**
    backbone=dict(
        type='SwinTransformer',
        embed_dim=128,
        depths=[2, 2, 18, 2],
        num_heads=[4, 8, 16, 32],
        window_size=7,
        mlp_ratio=4.,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.3,
        ape=False,
        patch_norm=True,
        out_indices=( 3, ),
        use_checkpoint=False),

**Comment by BIGWangYuDong** [comment]
Hi, I think you should check your `.pth` file path, maybe you can use absolute path first to have a try. This error seems that your path is wrong
