### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by FirasKedidi** [open-mmlab/mmdetection#5407]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. Yes
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. Yes
3. The bug has not been fixed in the latest version.

**Describe the bug**
I am using mmdetection to train a cascade mask rcnn on a costume dataset on colab when testing the model i keep getting this error that list index out of range note that i changed the categories in coco.py and it worked for me before with a different model but now i am getting this error

![image](https://user-images.githubusercontent.com/58661767/122747473-00bf0700-d283-11eb-8744-5cf8db713c8e.png)

**Reproduction**

1. What command or script did you run?
2. 

```none
%%shell
python /content/mmdetection/tools/test.py \
    '/content/mmdetection/configs/news/cascade.py' \
    '/content/dir/latest.pth' \
     --eval segm  \
     --options "classwise=True" \
     --show.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. Yess i did modifications and i understand what i chenged
3. What dataset did you use?
Costum dataset
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. atal: not a git repository (or any of the parent directories): .git
sys.platform: linux
Python: 3.7.10 (default, May  3 2021, 02:48:31) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla K80
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.1+cu101
OpenCV: 4.1.2
MMCV: 1.3.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.13.0+
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
File "/content/mmdetection/tools/test.py", line 237, in <module>
    main()
  File "/content/mmdetection/tools/test.py", line 229, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 400, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 345, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 282, in results2json
    json_results = self._segm2json(results)
  File "/content/mmdetection/mmdet/datasets/coco.py", line 233, in _segm2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-8-02853bc12f6d> in <module>()
----> 1 get_ipython().run_cell_magic('shell', '', 'python /content/mmdetection/tools/test.py \\\n    \'/content/mmdetection/configs/news/cascade.py\' \\\n    \'/content/dir/latest.pth\' \\\n     --eval segm  \\\n     --options "classwise=True" \\\n     --show')

2 frames
/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py in check_returncode(self)
    137     if self.returncode:
    138       raise subprocess.CalledProcessError(
--> 139           returncode=self.returncode, cmd=self.args, output=self.output)
    140 
    141   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'python /content/mmdetection/tools/test.py \
    '/content/mmdetection/configs/news/cascade.py' \
    '/content/dir/latest.pth' \
     --eval segm  \
     --options "classwise=True" \
     --show' returned non-zero exit status 1.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by FirasKedidi** [comment]
This line seems to be wrong 

![image](https://user-images.githubusercontent.com/58661767/122755380-d6724700-d28c-11eb-9978-77e3c018d197.png)

**Comment by FirasKedidi** [comment]
I runned tool/train to create the conf file and then used to test with the trained parameters that i got via train API and it worked

**Comment by FirasKedidi** [comment]
Hello, i tried to test the model locally and the problem appeared again.

**Comment by FirasKedidi** [comment]
In this case the problem was from the  annotation file #5628
