### ISSUE TITLE
RuntimeError: CUDA out of memory.  when train own dataset on config ga_faster_r50_caffe_fpn_1x_coco/ga_faster_r50_fpn_1x_coco

### ISSUE THREAD

**Issue by github-eliviate** [open-mmlab/mmdetection#5425]
1. when i train my own dataset on config ga_faster_r50_caffe_fpn_1x_coco/ga_faster_r50_fpn_1x_coco，error is 'cuda out of memory', then i tried to finetune the batchsize and lr，the same error occurs untill the batchsize is 1; but when the batchsize is 1, the AP on every category is 0 after 12 epochs. 
2. I have modified the num_classes
3. the same dataset is normal on the config ga_retinanet_r50_fpn_1x_coco

the traceback of CUDA out of memory is:
Traceback (most recent call last):
  File "tools/train.py", line 182, in <module>
    main()
  File "tools/train.py", line 178, in main
    meta=meta)
  File "/home/GitHub/mmdetection/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/.local/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/GitHub/mmdetection/mmdet/models/detectors/base.py", line 246, in train_step
    losses = self(**data)
  File "/home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/GitHub/mmdetection/mmdet/models/detectors/base.py", line 180, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/GitHub/mmdetection/mmdet/models/detectors/two_stage.py", line 156, in forward_train
    proposal_cfg=proposal_cfg)
  File "/home/GitHub/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/GitHub/mmdetection/mmdet/models/dense_heads/ga_rpn_head.py", line 55, in loss
    gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/.local/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/GitHub/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 665, in loss
    img_metas)
  File "/home/GitHub/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 586, in ga_shape_targets
    unmap_outputs=unmap_outputs)
  File "/home/GitHub/mmdetection/mmdet/core/utils/misc.py", line 26, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/GitHub/mmdetection/mmdet/models/dense_heads/guided_anchor_head.py", line 512, in _ga_shape_target_single
    gt_bboxes, gt_bboxes_ignore)
  File "/home/GitHub/mmdetection/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 121, in assign
    all_overlaps = self.iou_calculator(approxs, gt_bboxes)
  File "/home/GitHub/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 35, in __call__
    return bbox_overlaps(bboxes1, bboxes2, mode, is_aligned)
  File "/home/GitHub/mmdetection/mmdet/core/bbox/iou_calculators/iou2d_calculator.py", line 140, in bbox_overlaps
    union = area1[..., None] + area2[..., None, :] - overlap
RuntimeError: CUDA out of memory. Tried to allocate 2.21 GiB (GPU 0; 23.65 GiB total capacity; 22.39 GiB already allocated; 257.50 MiB free; 22.50 GiB reserved in total by PyTorch)

**Comment by ElectronicElephant** [comment]
It's clear that, convergence is not easy when batch size is too small.

BTW, it seems that your input resolution is too large. Why not crop or resize images before sending them to the network?

**Comment by alaa-shubbak** [comment]
> It's clear that, convergence is not easy when batch size is too small.
> 
> BTW, it seems that your input resolution is too large. Why not crop or resize images before sending them to the network?

in general , how can i crop images or resize them ? is there any library or document explain this through the mmdectection library ? is there any function do this?

**Comment by ElectronicElephant** [comment]
Hi @alaa-shubbak ,

Yes, you can check https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html . I hope it will help you -:).
