### ISSUE TITLE
YOLACT Classification scores become infinite or NaN

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdetection#5434]
I'm trying to retrain YOLACT from scratch but getting following error:

```
2021-06-23 13:49:06,598 - mmdet - INFO - Epoch [1][12650/39089] lr: 1.000e-03, eta: 5 days, 12:24:36, time: 0.219, data_time: 0.015, memory: 10495, loss_cls: 4.6314, loss_bbox: 3.1098, loss_segm: 1.0940, loss_mask: 4.3273, loss: 13.1626
2021-06-23 13:49:17,510 - mmdet - INFO - Epoch [1][12700/39089] lr: 1.000e-03, eta: 5 days, 12:24:18, time: 0.218, data_time: 0.015, memory: 10495, loss_cls: 12.5155, loss_bbox: 4.6638, loss_segm: 3.2519, loss_mask: 4.8612, loss: 25.2924
Traceback (most recent call last):
  File "/home/deploy/mmdetection/tools/train.py", line 187, in <module>
    main()
  File "/home/deploy/mmdetection/tools/train.py", line 183, in main
    meta=meta)
  File "/home/deploy/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/deploy/mmdetection/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/deploy/mmdetection/mmdet/models/detectors/base.py", line 181, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/deploy/mmdetection/mmdet/models/detectors/yolact.py", line 78, in forward_train
    *bbox_head_loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/deploy/miniconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
    return old_func(*args, **kwargs)
  File "/home/deploy/mmdetection/mmdet/models/dense_heads/yolact_head.py", line 219, in loss
    'classification scores become infinite or NaN!'
AssertionError: classification scores become infinite or NaN!
```

Here is my training config:
```
_base_ = '/home/deploy/mmdetection/configs/_base_/default_runtime.py'

# model settings
model = dict(
    type='YOLACT',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,  # do not freeze stem
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,  # update the statistics of bn
        zero_init_residual=False,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        upsample_cfg=dict(mode='bilinear')),
    bbox_head=dict(
        type='YOLACTHead',
        num_classes=80,
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=3,
            scales_per_octave=1,
            base_sizes=[8, 16, 32, 64, 128],
            ratios=[0.5, 1.0, 2.0],
            strides=[550.0 / x for x in [69, 35, 18, 9, 5]],
            centers=[(550 * 0.5 / x, 550 * 0.5 / x)
                     for x in [69, 35, 18, 9, 5]]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.1, 0.1, 0.2, 0.2]),
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            reduction='none',
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.5),
        num_head_convs=1,
        num_protos=32,
        use_ohem=True),
    mask_head=dict(
        type='YOLACTProtonet',
        in_channels=256,
        num_protos=32,
        num_classes=80,
        max_masks_to_train=100,
        loss_mask_weight=6.125),
    segm_head=dict(
        type='YOLACTSegmHead',
        num_classes=80,
        in_channels=256,
        loss_segm=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0.,
            ignore_iof_thr=-1,
            gt_max_assign_all=False),
        # smoothl1_beta=1.,
        allowed_border=-1,
        pos_weight=-1,
        neg_pos_ratio=3,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        iou_thr=0.5,
        top_k=200,
        max_per_img=100))
# dataset settings
dataset_type = 'CocoDataset'
data_root = '/home/deploy/ved/coco/'
img_norm_cfg = dict(
    mean=[123.68, 116.78, 103.94], std=[58.40, 57.12, 57.38], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=img_norm_cfg['mean'],
        to_rgb=img_norm_cfg['to_rgb'],
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(550, 550), keep_ratio=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(550, 550),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=3,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='SGD', lr=1e-3, momentum=0.9, weight_decay=5e-4)
optimizer_config = dict()
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.1,
    step=[20, 42, 49, 52])
runner = dict(type='EpochBasedRunner', max_epochs=56)
cudnn_benchmark = True
evaluation = dict(metric=['bbox', 'segm'])
load_from = '' #'/home/deploy/ved/sort/potato_l1/yolact/pretrain/yolact_r50_1x8_coco_20200908-f38d58df.pth'
work_dir = '/home/deploy/ved/sort/potato_l1/yolact/checkpoints/'
```

How were you able to get it trained ?

**Comment by RangiLyu** [comment]
You can refer to `Training "Loss goes Nan"` section in FAQ:https://github.com/open-mmlab/mmdetection/blob/master/docs/faq.md

**Comment by anshkumar** [comment]
@RangiLyu I'm using the default config shared in [YOLACT](https://github.com/open-mmlab/mmdetection/blob/master/configs/yolact/README.md).

**Comment by RangiLyu** [comment]
How many GPUs did you use for training? The learning rate in default configs is based on 8 GPUs. You may need to modify the lr if you have different GPU numbers.

**Comment by anshkumar** [comment]
I'm using 1 GPU only. I'm using config for `1x8`, single gpu with batch size of 8.

**Comment by RangiLyu** [comment]
> I'm using 1 GPU only. I'm using config for `1x8`, single gpu with batch size of 8.
But in your config, you set samples_per_gpu=3 which means single gpu with batch size of 3.

**Comment by tarunn2799** [comment]
Hey I'm facing the same issue. What exactly should I modify about the config?

**Comment by kevinlikai1213** [comment]
I have the same problem

**Comment by cozeybozey** [comment]
Using --auto-scale-lr fixed the issue for me

**Comment by ipon1031** [comment]
reduce the lr can solve this problem
