### ISSUE TITLE
KeyError: 'BDDDataset is not in the dataset registry'

### ISSUE THREAD

**Issue by s1mpleee** [open-mmlab/mmdetection#5461]
so I add a bdd.py in /mmdet/datasets folder(which contain a BDDDataset class), and as I train with this dataset config， I got this error below

Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 164, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/adas/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/adas/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'BDDDataset is not in the dataset registry'

what should I do ro registry this config may I ask:(

**Comment by s1mpleee** [comment]
problem fixed with https://github.com/open-mmlab/mmdetection/blob/master/docs/tutorials/customize_dataset.md
