### ISSUE TITLE
Not support pipenv in docker

### ISSUE THREAD

**Issue by dxsooo** [open-mmlab/mmdetection#5513]
Hello,

 I have tried to install mmcv & mmdet in docker, the following is my docker file:
```
FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

RUN pip config set global.trusted-host mirrors.aliyun.com && pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip install pipenv

COPY Pipfile Pipfile
RUN pipenv lock --requirements > requirements.txt && pip install -r requirements.txt
```

And the pipfile referred is following:
```
[[source]]
name = "pypi"
url = "https://mirrors.aliyun.com/pypi/simple/"
verify_ssl = true

[packages]
mmdet = "==2.11.0"
mmcv-full = "*"
```
(I have other packages need but just remove for now)

It locked failed for 
```
Building requirements...
Resolving dependencies...
⠇ Locking..✔ Success! 
#9 286.2 Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠸ Locking..✘ Locking Failed! 
#9 293.1 ERROR:pip.subprocessor:Command errored out with exit status 1:
#9 293.1  command: /root/.local/share/virtualenvs/workspace-dqq3IVyd/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-ncn7uggy/mmpycocotools/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-ncn7uggy/mmpycocotools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-ncn7uggy/mmpycocotools/pip-egg-info
#9 293.1      cwd: /tmp/pip-resolver-ncn7uggy/mmpycocotools/
#9 293.1 Complete output (5 lines):
#9 293.1 Traceback (most recent call last):
#9 293.1   File "<string>", line 1, in <module>
#9 293.1   File "/tmp/pip-resolver-ncn7uggy/mmpycocotools/setup.py", line 1, in <module>
#9 293.1     import numpy as np
#9 293.1 ModuleNotFoundError: No module named 'numpy'
#9 293.1 ----------------------------------------
#9 293.1 Traceback (most recent call last):
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/resolver.py", line 764, in <module>
#9 293.1     main()
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
#9 293.1     dev=parsed.dev)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
#9 293.1     resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
#9 293.1     requirements_dir=requirements_dir,
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/resolver.py", line 692, in resolve
#9 293.1     req_dir=requirements_dir
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/utils.py", line 1403, in resolve_deps
#9 293.1     req_dir=req_dir,
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
#9 293.1     resolver.resolve()
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/utils.py", line 823, in resolve
#9 293.1     results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
#9 293.1     has_changed, best_matches = self._resolve_one_round()
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
#9 293.1     their_constraints.extend(self._iter_dependencies(best_match))
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
#9 293.1     dependencies = self.repository.get_dependencies(ireq)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
#9 293.1     legacy_results = self.get_legacy_dependencies(ireq)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 351, in get_legacy_dependencies
#9 293.1     download_dir, ireq, wheel_cache
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
#9 293.1     results = resolver._resolve_one(reqset, ireq)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
#9 293.1     abstract_dist = self._get_abstract_dist_for(req_to_install)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
#9 293.1     abstract_dist = self.preparer.prepare_linked_requirement(req)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 509, in prepare_linked_requirement
#9 293.1     req, self.req_tracker, self.finder, self.build_isolation,
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
#9 293.1     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
#9 293.1     self.req.prepare_metadata()
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 564, in prepare_metadata
#9 293.1     self.metadata_directory = self._generate_metadata()
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 544, in _generate_metadata
#9 293.1     details=self.name or "from {}".format(self.link)
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/build/metadata_legacy.py", line 118, in generate_metadata
#9 293.1     command_desc='python setup.py egg_info',
#9 293.1   File "/opt/conda/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
#9 293.1     raise InstallationError(exc_msg)
#9 293.1 pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#9 293.1 
------
executor failed running [/bin/sh -c pipenv lock --requirements > requirements.txt && pip install -r requirements.txt]: exit code: 1
```

Seems that mmpycocotools tried to find numpy but pipenv lock designed to not install anything (in fact, there are numpy installed in the base pytorch image). The installation of deps is handled by pip as virtual env is not need in docker.

So there may need some work to make mmdet expose its deps to make pipenv action in a right way?

**Comment by ZwwWayne** [comment]
Thanks for your suggestion. For now, we have a dockerfile that works https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile. For using pipenv, we may do it in the future.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.
