### ISSUE TITLE
Training error with ssd512

### ISSUE THREAD

**Issue by forestriveral** [open-mmlab/mmdetection#552]
When I was going to train ssd512, the following error occurred:

`2019-04-27 14:09:30,855 - INFO - Distributed training: True`
`2019-04-27 14:09:31,023 - INFO - load model from: open-mmlab://vgg16_caffe`
`2019-04-27 14:09:31,079 - WARNING - missing keys in source state_dict: extra.7.bias, extra.7.weight, extra.0.bias, extra.4.weight, l2_norm.weight, extra.1.weight, extra.5.bias, extra.8.weight, extra.3.bias, extra.4.bias, extra.3.weight, extra.5.weight, extra.6.weight, extra.9.bias, extra.9.weight, extra.2.weight, extra.0.weight, extra.8.bias, extra.1.bias, extra.2.bias, extra.6.bias
`
`loading annotations into memory...`
`Done (t=0.02s)`
`creating index...`
`index created!`
`2019-04-27 14:09:34,078 - INFO - Start running, host: forestriveral@HanazawaKana, work_dir: /home/forestriveral/DeepLearning/object-detection/mmdetection/work_dirs/ssd512_coco`
`2019-04-27 14:09:34,078 - INFO - workflow: [('train', 1)], max: 24 epochs`
`THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=405 error=11 : invalid argument`
`Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/apis/train.py", line 114, in _dist_train
    log_config=cfg.log_config, val_dataloader=val_dataloader)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 396, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/runner/runner.py", line 271, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/apis/train.py", line 37, in batch_processor
    losses = model(**data)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/models/detectors/single_stage.py", line 51, in forward_train
    x = self.extract_feat(img)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/models/detectors/single_stage.py", line 40, in extract_feat
    x = self.backbone(img)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/models/backbones/ssd_vgg.py", line 79, in forward
    x = layer(x)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/forestriveral/anaconda3/envs/mmdetection/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)`
`RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:405`

Besides, if set the workflow to `[('train', 1), ('val', 1)]` and add a `build_dataloader` for val to `dataloaders` in the `api/train.py` , an assertionerror like below occurred too:

`File "/home/forestriveral/DeepLearning/object-detection/mmdetection/mmdet/datasets/loader/sampler.py", line 81, in __init__
    assert hasattr(self.dataset, 'flag')`
`AssertionError`

Thanks for any advice!

**Comment by yhcao6** [comment]
Hi, do you use the latest mmcv or latest mmdetection? I just run SSD512-voc successfully

**Comment by ywq502** [comment]
> Hi, do you use the latest mmcv or latest mmdetection? I just run SSD512-voc successfully

hi，i met the same problem on SSD512-voc,could you paste the config.py below
