### ISSUE TITLE
train error on provided coco config

### ISSUE THREAD

**Issue by lzhbrian** [open-mmlab/mmdetection#554]
I am using this config [mask_rcnn_r50_fpn_1x.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/mask_rcnn_r50_fpn_1x.py) to train on coco dataset, and have encountered the following error.

I use the distributed training `bash ./tools/dist_train.sh ./configs/mask_rcnn_r50_fpn_1x.py 8`.

Seems like an Assertion `cur_target >= 0 && cur_target < n_classes` failed. However I have successfully trained epoch 1 and 2, and failed on epoch 3. And I didn't modify the config file provided (except adding the Tensorboard hook).

Any idea how this happened? Thanks in advance.

```
2019-04-28 07:09:48,940 - INFO - Epoch [3][300/7330]    lr: 0.02000, eta: 13:36:04, time: 0.663, data_time: 0.056, memory: 3961, loss_rpn_cls: 0.0421, loss_rpn_reg: 0.0372, loss_cls: 0.2461, acc: 92.0879,
 loss_reg: 0.1274, loss_mask: 0.3005, loss: 0.7533
2019-04-28 07:10:23,415 - INFO - Epoch [3][350/7330]    lr: 0.02000, eta: 13:35:35, time: 0.690, data_time: 0.062, memory: 3961, loss_rpn_cls: 0.0572, loss_rpn_reg: 0.0442, loss_cls: 0.2780, acc: 90.8945,
 loss_reg: 0.1505, loss_mask: 0.2975, loss: 0.8274
2019-04-28 07:10:56,944 - INFO - Epoch [3][400/7330]    lr: 0.02000, eta: 13:35:01, time: 0.671, data_time: 0.037, memory: 3961, loss_rpn_cls: 0.0363, loss_rpn_reg: 0.0319, loss_cls: 0.2266, acc: 92.8848,
 loss_reg: 0.1187, loss_mask: 0.3126, loss: 0.7261
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:78: void ClassNLLCriterion_updateGradInput_no_reduce_kernel(int, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTra
its>, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [70,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/apis/train.py", line 96, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 269, in train
    self.call_hook('after_train_iter')
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: copy_if failed to synchronize: device-side assert triggered
terminate called without an active exception
```

**Comment by lzhbrian** [comment]
I use `resume_from` cfg to resume training, and successfully finishes epoch 3.
but in epoch 4, this error occurs again.

**Comment by hellock** [comment]
Looks weird. You are just using COCO dataset and the config file in the repo without modifications?

**Comment by lzhbrian** [comment]
@hellock  yes.

**Comment by hellock** [comment]
I have only met the error `copy_if failed to synchronize: device-side assert triggered` once, which is caused by the server-side issues.
If you have more than one server, you may try running on others to see if this error is related to the server. You may also try single-gpu or 2-gpu training to see if there is some problems with specific cards.

**Comment by lzhbrian** [comment]
Thanks, I am only using one 8-gpu server.
I will try to find if it’s problem with some specific cards.

**Comment by lzhbrian** [comment]
For the record, 
I am using cuda-10.0 with cudnn-7.4.1, and this is my conda env:
```
# Name                    Version                   Build  Channel
absl-py                   0.7.1                     <pip>
addict                    2.2.0                     <pip>
astor                     0.7.1                     <pip>
attrs                     19.1.0                    <pip>
backcall                  0.1.0                     <pip>
bleach                    3.1.0                     <pip>
ca-certificates           2019.3.9             hecc5488_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2019.3.9                 py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
chardet                   3.0.4                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.7                    <pip>
decorator                 4.4.0                     <pip>
defusedxml                0.6.0                     <pip>
entrypoints               0.3                       <pip>
gast                      0.2.2                     <pip>
grpcio                    1.20.1                    <pip>
h5py                      2.9.0                     <pip>
idna                      2.8                       <pip>
ipykernel                 5.1.0                     <pip>
ipython                   7.5.0                     <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.13.3                    <pip>
Jinja2                    2.10.1                    <pip>
jsonschema                3.0.1                     <pip>
jupyter-client            5.2.4                     <pip>
jupyter-core              4.4.0                     <pip>
Keras-Applications        1.0.7                     <pip>
Keras-Preprocessing       1.0.9                     <pip>
kiwisolver                1.1.0                     <pip>
libffi                    3.2.1             he1b5a44_1006    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
Markdown                  3.1                       <pip>
MarkupSafe                1.1.1                     <pip>
matplotlib                3.0.3                     <pip>
mistune                   0.8.4                     <pip>
mmcv                      0.2.7                     <pip>
mmdet                     0.6.0+unknown             <pip>
mock                      2.0.0                     <pip>
nbconvert                 5.5.0                     <pip>
nbformat                  4.4.0                     <pip>
ncurses                   6.1               hf484d3e_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
notebook                  5.7.8                     <pip>
numpy                     1.16.3                    <pip>
opencv-python             4.1.0.25                  <pip>
openssl                   1.1.1b               h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandocfilters             1.4.2                     <pip>
parso                     0.4.0                     <pip>
pbr                       5.2.0                     <pip>
pexpect                   4.7.0                     <pip>
pickleshare               0.7.5                     <pip>
Pillow                    6.0.0                     <pip>
pip                       19.0.3                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prometheus-client         0.6.0                     <pip>
prompt-toolkit            2.0.9                     <pip>
protobuf                  3.7.1                     <pip>
ptyprocess                0.6.0                     <pip>
pycocotools               2.0.0                     <pip>
Pygments                  2.3.1                     <pip>
pyparsing                 2.4.0                     <pip>
pyrsistent                0.15.1                    <pip>
python                    3.6.7             h381d211_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.0                     <pip>
PyYAML                    5.1                       <pip>
pyzmq                     18.0.1                    <pip>
readline                  7.0               hf8c457e_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.21.0                    <pip>
scipy                     1.2.1                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                41.0.0                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.12.0                    <pip>
sqlite                    3.26.0            h67949de_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tensorboard               1.13.1                    <pip>
tensorboardX              1.6                       <pip>
tensorflow-estimator      1.13.0                    <pip>
tensorflow-gpu            1.13.1                    <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.2                     <pip>
terminaltables            3.1.0                     <pip>
testpath                  0.4.2                     <pip>
tk                        8.6.9             h84994c4_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
torch                     1.0.1.post2               <pip>
torchvision               0.2.2.post3               <pip>
tornado                   6.0.2                     <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.24.2                    <pip>
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
Werkzeug                  0.15.2                    <pip>
wheel                     0.33.1                   py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.4             h14c3975_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zlib                      1.2.11            h14c3975_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
```

**Comment by lzhbrian** [comment]
An update (small fix), the error msg shown is different after I resume the training.

it's showing an __Assertion `linearIndex < size && linearIndex >= -size`__,
which is different from the first one I posted above: __Assertion `cur_target >= 0 && cur_target < n_classes` failed__.

Looks like it's throwing random errors?

```
2019-04-28 14:47:29,417 - INFO - Epoch [4][2250/7330]   lr: 0.02000, eta: 12:17:21, time: 0.667, data_time: 0.046, memory: 3955, loss_rpn_cls: 0.0432, loss_rpn_reg: 0.0391, loss_cls: 0.2548, acc: 91.7402,
 loss_reg: 0.1383, loss_mask: 0.2965, loss: 0.7719
2019-04-28 14:48:02,988 - INFO - Epoch [4][2300/7330]   lr: 0.02000, eta: 12:16:14, time: 0.671, data_time: 0.052, memory: 3955, loss_rpn_cls: 0.0492, loss_rpn_reg: 0.0395, loss_cls: 0.2627, acc: 91.5098,
 loss_reg: 0.1363, loss_mask: 0.2978, loss: 0.7856
2019-04-28 14:48:36,707 - INFO - Epoch [4][2350/7330]   lr: 0.02000, eta: 12:15:14, time: 0.674, data_time: 0.050, memory: 3955, loss_rpn_cls: 0.0489, loss_rpn_reg: 0.0358, loss_cls: 0.3027, acc: 90.8848,
 loss_reg: 0.1422, loss_mask: 0.2790, loss: 0.8087
2019-04-28 14:49:10,487 - INFO - Epoch [4][2400/7330]   lr: 0.02000, eta: 12:14:15, time: 0.675, data_time: 0.049, memory: 3955, loss_rpn_cls: 0.0373, loss_rpn_reg: 0.0350, loss_cls: 0.2827, acc: 91.4766,
 loss_reg: 0.1327, loss_mask: 0.2858, loss: 0.7735
/pytorch/aten/src/THC/THCTensorIndex.cu:383: IndexType indexToOffset(const TensorInfo<T, IndexType> &, long, IndexType) [with Dims = -2, T = float, IndexType = int]: block: [5050,0,0], thread: [218,0,0] A
ssertion `linearIndex < size && linearIndex >= -size` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/apis/train.py", line 96, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 269, in train
    self.call_hook('after_train_iter')
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/mmcv/runner/runner.py", line 229, in call_hook
    getattr(hook, fn_name)(self)
  File "/nvme/linziheng/projects/imat-fashion/mmdetection/mmdet/core/utils/dist_utils.py", line 53, in after_train_iter
    runner.outputs['loss'].backward()
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/nvme/linziheng/anaconda3/envs/open-mmlab/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: copy_if failed to synchronize: device-side assert triggered
terminate called without an active exception
```

**Comment by lzhbrian** [comment]
UPDATE:
I tried training with the first 4 GPUs alone, and the last 4 GPUs alone, the first 4 GPUs works fine, but the last 4 GPUs ran into the above mistakes constantly. Seems like there is some issue with my last 4 GPUs.

However, if I use non-distributed training, no error shows.

**Comment by hellock** [comment]
I have no idea how this occurs. Maybe you can have a check to block only one gpu each time.

**Comment by lzhbrian** [comment]
UPDATE: using non-distributed training also shows the same error.

**Comment by lzhbrian** [comment]
@hellock Do you think this may have something to do with CUDA version?
I am using cuda-10.0 with cudnn-7.4.1, and I saw your MODEL_ZOO is using cuda-9.0 with CUDNN 7.0.4.

**Comment by hellock** [comment]
I am afraid not. I have been working with cuda 10 and cudnn 7.4 for a long time, which is more preferable than cuda 9 and cudnn 7.0.

**Comment by lzhbrian** [comment]
I think this issue is related with my server.
This error are more likely to occur If I run concurrent tasks on the same GPU.

P.S. I am using 8xTitan Xp, NVIDIA Driver 418.43, Ubuntu 16.04
tested on: CUDA 9.0, CUDNN 7.2.1 and CUDA 10.0, CUDNN 7.4.1. Both shown the same error.
