### ISSUE TITLE
ImportError undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [open-mmlab/mmdetection#5547]
I was following this https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md
Then, at the step Verification, when I ran `from mmdet.apis import init_detector, inference_detector` I got the following error:

```
 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mmdet.apis import init_detector, inference_detector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/merge/Harry/instance_seg/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/merge/Harry/instance_seg/mmdetection/mmdet/apis/inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "/home/merge/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/merge/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/merge/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/merge/anaconda3/envs/open-mmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/merge/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```

Here is my conda list environment:
```
 conda list             
# packages in environment at /home/merge/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.5.25            h06a4308_1  
certifi                   2021.5.30        py37h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cudatoolkit               11.1.74              h6bb024c_0    nvidia
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.23                  pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
idna                      2.10                     pypi_0    pypi
importlib-metadata        4.6.1                    pypi_0    pypi
intel-openmp              2021.2.0           h06a4308_610  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.1                h27cfd23_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h2531618_0  
markdown                  3.3.4                    pypi_0    pypi
matplotlib                3.4.2                    pypi_0    pypi
mkl                       2021.2.0           h06a4308_296  
mkl-service               2.3.0            py37h27cfd23_1  
mkl_fft                   1.3.0            py37h42c9631_2  
mkl_random                1.2.1            py37ha9443f7_2  
mmcv-full                 1.3.8                    pypi_0    pypi
mmdet                     2.14.0                    dev_0    <develop>
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nettle                    3.7.3                hbbd107a_1  
ninja                     1.10.2               hff7bd54_1  
numpy                     1.20.2           py37h2d18471_0  
numpy-base                1.20.2           py37hfae3a4d_0  
olefile                   0.46                     py37_0  
opencv-python             4.5.2.54                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openmim                   0.1.2                    pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
ordered-set               4.0.2                    pypi_0    pypi
pandas                    1.3.0                    pypi_0    pypi
pillow                    8.2.0            py37he98fc37_0  
pip                       21.1.3           py37h06a4308_0  
pycocotools               2.0.2                    pypi_0    pypi
pyparsing                 3.0.0b2                  pypi_0    pypi
python                    3.7.10               h12debd9_4  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.9.0           py3.7_cuda11.1_cudnn8.0.5_0    pytorch
pytz                      2021.1                   pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torchaudio                0.9.0                      py37    pytorch
torchvision               0.10.0               py37_cu111    pytorch
typing_extensions         3.10.0.0           pyh06a4308_0  
urllib3                   1.26.6                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zipp                      3.5.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  


```

**Comment by RangiLyu** [comment]
It seems the c++ version which complies mmcv is different from your c++ runtime. Try to add the correct version of libstdc++.so to LD_PRELOAD or LD_LIBRARY_PATH.

**Comment by TrinhDinhPhuc** [comment]
Oh Im not sure it was about libstdc++ or not but after checking the correct version of mmcv-full, now it works. Thanks anyway.

**Comment by jianxin123** [comment]
my gpu is 3070, cuda 11.2 and pytorch 1.9 it seems there is no right version of mmcv-full... can u tell me which version is correct?

**Comment by RangiLyu** [comment]
> my gpu is 3070, cuda 11.2 and pytorch 1.9 it seems there is no right version of mmcv-full... can u tell me which version is correct?

Currently no pre-compiled mmcv-full package, but you can compile it locally.
