### ISSUE TITLE
Meet RuntimeError about bbox datatype when train on retinanet r101 on coco dataset

### ISSUE THREAD

**Issue by hbhflw2000** [open-mmlab/mmdetection#556]
Hello, here is my problem:

2019-04-28 19:11:41,479 - INFO - Start running, host: wei@wei, work_dir: /home/wei/github/mmdetection-master/tools/work_dirs/test
2019-04-28 19:11:41,479 - INFO - workflow: [('train', 1)], max: 2 epochs
Traceback (most recent call last):
  File "/home/wei/github/mmdetection-master/tools/train.py", line 90, in <module>
    main()
  File "/home/wei/github/mmdetection-master/tools/train.py", line 86, in main
    logger=logger)
  File "/home/wei/github/mmdetection-master/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/wei/github/mmdetection-master/mmdet/apis/train.py", line 121, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wei/anaconda3/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 355, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wei/anaconda3/envs/py36/lib/python3.6/site-packages/mmcv/runner/runner.py", line 261, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/wei/github/mmdetection-master/mmdet/apis/train.py", line 37, in batch_processor
    losses = model(**data)
  File "/home/wei/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wei/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wei/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wei/github/mmdetection-master/mmdet/models/detectors/base.py", line 80, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/wei/github/mmdetection-master/mmdet/models/detectors/single_stage.py", line 55, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/wei/github/mmdetection-master/mmdet/models/anchor_heads/anchor_head.py", line 198, in loss
    sampling=sampling)
  File "/home/wei/github/mmdetection-master/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/home/wei/github/mmdetection-master/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/wei/github/mmdetection-master/mmdet/core/anchor/anchor_target.py", line 120, in anchor_target_single
    gt_bboxes_ignore, gt_labels)
  File "/home/wei/github/mmdetection-master/mmdet/core/bbox/assigners/max_iou_assigner.py", line 76, in assign
    overlaps = bbox_overlaps(gt_bboxes, bboxes)
  File "/home/wei/github/mmdetection-master/mmdet/core/bbox/geometry.py", line 49, in bbox_overlaps
    lt = torch.max(bboxes1[:, None, :2], bboxes2[:, :2])  # [rows, cols, 2]
RuntimeError: Expected object of scalar type Float but got scalar type Double for argument #2 'other'

Here is a sample of my annotation file: 

{'id': 2, 'image_id': 0, 'category_id': 5, 'iscrowd': 0, 'segmentation': [], 'area': 11800, 'bbox': [296, 244, 118, 100], 'minAreaRect': [[411, 345], [289, 270], [316, 226], [438, 301]]}

I have no idea where should change, or where I did wrong. Thanks in advance for help!

**Comment by zhaoyue-zephyrus** [comment]
Hi @hbhflw2000 ,

The error indicates that "bboxes1", namely "gt_bboxes" has a type Double. However, a type Float is required (due to the predicted "bboxes").

Please make sure that the "gt_bboxes" that you have is properly converted to a type of float32. For your reference, in [mmdet/datasets/coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L99), we have a gt_bboxes of type np.float32.

**Comment by hbhflw2000** [comment]
> Hi @hbhflw2000 ,
> 
> The error indicates that "bboxes1", namely "gt_bboxes" has a type Double. However, a type Float is required (due to the predicted "bboxes").
> 
> Please make sure that the "gt_bboxes" that you have is properly converted to a type of float32. For your reference, in [mmdet/datasets/coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L99), we have a gt_bboxes of type np.float32.

Thanks very much. I tried to convert the gt_bboxes to float32, and now it works! I really appreciate your help.
