### ISSUE TITLE
OSError: Caught OSError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by chandlerbing65nm** [open-mmlab/mmdetection#5653]
Hi, I'm having this issue when running `!python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py` in google colab:
```
index created!
2021-07-20 04:56:56,971 - mmdet - INFO - Start running, host: root@5526dcebfd7a, work_dir: /content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/work_dirs/faster_rcnn_r50_fpn_1x_coco
2021-07-20 04:56:56,972 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/drive/.shortcut-targets-by-id/1QI1uqs44zWhCK8Zc8WK7JuesHC_QjWqw/MyFPN/mmdet/datasets/pipelines/loading.py", line 59, in __call__
    img_bytes = self.file_client.get(filename)
  File "/usr/local/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 306, in get
    return self.client.get(filepath)
  File "/usr/local/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 184, in get
    with open(filepath, 'rb') as f:
OSError: [Errno 5] Input/output error: 'data/coco/train2017/000000123190.jpg'
```

**Comment by chandlerbing65nm** [comment]
Problem 1: 
`OSError: Caught OSError in DataLoader worker process 0.`
Solution:
Set `worker_per_gpu = 0`

Problem 2: 
`OSError: [Errno 5] Input/output error: 'data/coco/train2017/000000123190.jpg'`
Solution:
Colab cannot access all the coco images at once, what I did was just keep pressing the rerun button until all of the images are seen by colab.

**Comment by Zhangwenyao1** [comment]
> 
If we set work_per_gpu=0; the efficiency of training is very slow,  can you tell me how to improve it, please?
