### ISSUE TITLE
benchmark error

### ISSUE THREAD

**Issue by kike-0304** [open-mmlab/mmdetection#5672]
python tools/analysis_tools/benchmark.py A-my-configs/retinanet/retinanet_r50_fpn_1x_coco.py work_dirs/retinanet_r50/latest.pth --launcher pytorch --fuse-conv-bn

error:
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 142, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 135, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/cc631/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 21, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/cc631/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 32, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/home/cc631/anaconda3/envs/mmd/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

What should I do to get FPS?

**Comment by shinya7y** [comment]
```bash
python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 \
  tools/analysis_tools/benchmark.py \
  configs/retinanet/retinanet_r50_fpn_1x_coco.py \
  work_dirs/retinanet_r50/latest.pth \
  --launcher pytorch \
  --fuse-conv-bn
```

Adding `tools/analysis_tools/benchmark.sh` like `tools/dist_test.sh` will be better.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question

**Comment by ilem777** [comment]
@shinya7y @jshilong Hello, I followed the following command to run benchmark.py.
`python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py work_dirs/faster_rcnn_r50_fpn_1x_coco/epoch_100.pth --launcher pytorch --fuse-conv-bn`
But the following error appears.
```
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 143, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 136, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "f:\pycharmprojects\mmdetection_env\mmcv\mmcv\runner\dist_utils.py", line 34, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\distributed_c10d.py", line 433, in init_process_group
    rendezvous_iterator = rendezvous(
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\mmdetection_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "D:\Anaconda3\envs\mmdetection_env\lib\site-packages\torch\distributed\launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['D:\\Anaconda3\\envs\\mmdetection_env\\python.exe', '-u', 'tools/analysis_tools/benchmark.py', '--local_rank=0', 'configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py', 'work_dirs/faster_rcnn_r50_
fpn_1x_coco/epoch_100.pth', '--launcher', 'pytorch', '--fuse-conv-bn']' returned non-zero exit status 1.
```

My computer system is Win10, graphics card is Quadro P5000, single card, CUDA10.2. How can I fix it please?
