### ISSUE TITLE
error when pip install -e .

### ISSUE THREAD

**Issue by liugl7** [open-mmlab/mmdetection#568]
My OS is Ubuntu 16.04,  Python is 3.6.3.

When i run `pip install -e .` ,  error occured:

> liu_gaoliang@node01:~/mmdetection$ pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/liu_gaoliang/mmdetection
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/http/client.py", line 1239, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
        self.send(msg)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/http/client.py", line 964, in send
        self.connect()
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/ssl_support.py", line 174, in connect
        (self.host, self.port), getattr(self, 'source_address', None)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/socket.py", line 724, in create_connection
        raise err
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
        sock.connect(sa)
    OSError: [Errno 101] Network is unreachable
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 751, in open_url
        return open_with_auth(url, self.opener)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 952, in _socket_timeout
        return func(*args, **kwargs)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 1071, in open_with_auth
        fp = opener(request)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
        response = self._open(req, data)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
        '_open', req)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/ssl_support.py", line 161, in https_open
        lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>    
    During handling of the above exception, another exception occurred:    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/liu_gaoliang/mmdetection/setup.py", line 112, in <module>
        zip_safe=False)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 335, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
        replace_conflicting=replace_conflicting
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1141, in best_match
        return self.obtain(req, installer)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1153, in obtain
        return installer(requirement)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/dist.py", line 522, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 660, in easy_install
        not self.always_copy, self.local_index
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 640, in fetch_distribution
        dist = find(requirement)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 621, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 570, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 809, in _download_url
        return self._attempt_download(url, filename)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 815, in _attempt_download
        headers = self._download_to(url, filename)
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 714, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/home/liu_gaoliang/anaconda3/lib/python3.6/site-packages/setuptools/package_index.py", line 765, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/15/0a/1e73c3a3d3f4f5faf5eacac4e55675c1627b15d84265b80b8fef3f8a3fb5/pytest-runner-4.4.tar.gz#sha256=00ad6cd754ce55b01b868a6d00b77161e4d2006b3918bde882376a0a884d0df4: [Errno 101] Network is unreachable
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/liu_gaoliang/mmdetection/

**Comment by liugl7** [comment]
`pip install pytest-runner` could solve it
