### ISSUE TITLE
MMDetection using COCO dataset

### ISSUE THREAD

**Issue by shabbbb** [open-mmlab/mmdetection#5685]
Sir,
    I got an error while executing the below code :
            train_detector(model, datasets, cfg, distributed=False, validate=True)
   The error is as follows : 
 ----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
                ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 303, in __call__
    self._resize_bboxes(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 237, in _resize_bboxes
    bboxes = results[key] * results['scale_factor']
ValueError: operands could not be broadcast together with shapes (0,) (4,)

**Comment by olegkorshunov** [comment]
I got the same error, who knows how to fix it?
