### ISSUE TITLE
operands could not be broadcast together with shapes (0,) (4,)

### ISSUE THREAD

**Issue by olegkorshunov** [open-mmlab/mmdetection#5688]
Hi guys, I am newbie in mmdetection and I have got an error occurred while training the model
```python
2021-07-24 23:10:00,037 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
/content/mmdetection/mmdet/core/anchor/anchor_generator.py:323: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/content/mmdetection/mmdet/core/anchor/anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
2021-07-24 23:10:07,260 - mmdet - INFO - Epoch [1][10/104]	lr: 2.500e-03, eta: 0:14:19, time: 0.694, data_time: 0.250, memory: 4573, loss_rpn_cls: 0.0050, loss_rpn_bbox: 0.0000, loss_cls: 0.1002, acc: 97.3828, loss_bbox: 0.0005, loss: 0.1057
2021-07-24 23:10:12,118 - mmdet - INFO - Epoch [1][20/104]	lr: 2.500e-03, eta: 0:12:04, time: 0.486, data_time: 0.037, memory: 4573, loss_rpn_cls: 0.0039, loss_rpn_bbox: 0.0000, loss_cls: 0.0040, acc: 99.7168, loss_bbox: 0.0005, loss: 0.0084
2021-07-24 23:10:16,650 - mmdet - INFO - Epoch [1][30/104]	lr: 2.500e-03, eta: 0:11:03, time: 0.455, data_time: 0.037, memory: 4573, loss_rpn_cls: 0.0022, loss_rpn_bbox: 0.0000, loss_cls: 0.0040, acc: 99.7461, loss_bbox: 0.0004, loss: 0.0066
2021-07-24 23:10:21,409 - mmdet - INFO - Epoch [1][40/104]	lr: 2.500e-03, eta: 0:10:36, time: 0.473, data_time: 0.035, memory: 4573, loss_rpn_cls: 0.0001, loss_rpn_bbox: 0.0000, loss_cls: 0.0045, acc: 99.7266, loss_bbox: 0.0004, loss: 0.0049
2021-07-24 23:10:26,186 - mmdet - INFO - Epoch [1][50/104]	lr: 2.500e-03, eta: 0:10:21, time: 0.484, data_time: 0.037, memory: 4573, loss_rpn_cls: 0.0003, loss_rpn_bbox: 0.0000, loss_cls: 0.0053, acc: 99.6777, loss_bbox: 0.0004, loss: 0.0060
2021-07-24 23:10:30,758 - mmdet - INFO - Epoch [1][60/104]	lr: 2.500e-03, eta: 0:10:02, time: 0.453, data_time: 0.031, memory: 4573, loss_rpn_cls: 0.0005, loss_rpn_bbox: 0.0000, loss_cls: 0.0045, acc: 99.7266, loss_bbox: 0.0003, loss: 0.0053
2021-07-24 23:10:35,727 - mmdet - INFO - Epoch [1][70/104]	lr: 2.500e-03, eta: 0:09:55, time: 0.494, data_time: 0.038, memory: 4573, loss_rpn_cls: 0.0006, loss_rpn_bbox: 0.0000, loss_cls: 0.0048, acc: 99.7070, loss_bbox: 0.0002, loss: 0.0056
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-74-34e40fa299ab> in <module>()
      6 # Create work_dir
      7 mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
----> 8 train_detector(model, datasets, cfg, distributed=False, validate=True)

6 frames
/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    423             # have message field
    424             raise self.exc_type(message=msg)
--> 425         raise self.exc_type(msg)
    426 
    427 

ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 303, in __call__
    self._resize_bboxes(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 237, in _resize_bboxes
    bboxes = results[key] * results['scale_factor']
ValueError: operands could not be broadcast together with shapes (0,) (4,)
```
I read that this error can occur when the image is not jpg, I tried to check it with cv2 img.shape and pillow image.shape but there are three channels everywhere
Here my [code](https://colab.research.google.com/drive/1aRo1sxrguTEUZbOz4LnxnEPtvF9T9wYX?usp=sharing)
Here my [dataset](https://drive.google.com/file/d/1k09_XURAqb8F5F9_eP1pcvKmYq3XQooy/view?usp=sharing)

**Comment by shabbbb** [comment]
I got the same error, and I noticed that the dataset that I was trying was processed.

**Comment by ZwwWayne** [comment]
You may first check which image caused this error. For now, MMDet do not support switch image decode backends from cv2 to PIL, so there are indeed some types that are not supported. You may modify the code in MMDetection following those in mmseg https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/loading.py#L35
