### ISSUE TITLE
During how training how do I show BOTH val loss and compute mAP?

### ISSUE THREAD

**Issue by andrewmellinger** [open-mmlab/mmdetection#5694]
I found this issue:

https://github.com/open-mmlab/mmdetection/issues/171

Where it says "For validation there are two options.".  How do I do both at the same time? Can I just give it val and test datasets/dataloaders and have it do both?  

Thanks!

**Comment by hhaAndroid** [comment]
You just need to set `workflow = [('train', 1),('val', 1)]` in the configuration

**Comment by andrewmellinger** [comment]
Thanks for the response!

That's what we thought too. However, when we do this we get some errors "TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'".  This seems to do with the val pipeline doesn't load the annotations, but when we start hacking on the pipelines, we can't seem to find a combination that satisfies both the val_loss and mAP code. The training pipeline uses random_sizes, but the val pipeline has only one size, even though it has MultiScaleFlipAug.  So we seem to get a size issue.

Our model is based on:

https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco.py

We don't change the pipelines we just use a different coco-based data set.  The exact error is:

```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/juneberry/juneberry/trainer.py", line 134, in train_model
    self.train()
  File "/juneberry/juneberry/mmdetection/mmd_trainer.py", line 306, in train
    train_detector(self.model, self.datasets, self.cfg, distributed=self.distributed)
  File "/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 91, in val_step
    output = self.module.val_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 252, in val_step
    losses = self(**data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 881, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'
```

So how can we set up the val pipeline to match the train pipeline without the random size selection and flipping and keep the val pipeline intact for the mAP calculation?

Thanks for any help!

**Comment by hhaAndroid** [comment]
@andrewmellinger Thank you for your feedback, we will confirm it immediately.

**Comment by hhaAndroid** [comment]
@anurag1paul I tested retinanet and found no problems. Can you consider updating to the latest version?

```
2021-08-24 12:55:53,757 - mmdet - INFO - Epoch [1][50/61]       lr: 9.890e-04, eta: 0:02:17, time: 0.201, data_time: 0.044, memory: 1068, loss_cls: 1.1531, loss_bbox: 0.8725, loss: 2.0256
2021-08-24 12:55:55,415 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 120/120, 8.1 task/s, elapsed: 15s, ETA:     0s2021-08-24 12:56:10,653 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
2021-08-24 12:56:10,653 - mmdet - ERROR - The testing results of the whole dataset is empty.
2021-08-24 12:56:10,654 - mmdet - INFO - Exp name: retinanet_r50_fpn_1x_coco.py
2021-08-24 12:56:10,655 - mmdet - INFO - Epoch(val) [1][120]    
2021-08-24 12:56:16,709 - mmdet - INFO - Exp name: retinanet_r50_fpn_1x_coco.py
2021-08-24 12:56:16,709 - mmdet - INFO - Epoch(val) [1][60]     loss_cls: 1.1543, loss_bbox: 0.7726, loss: 1.9269
2021-08-24 12:56:26,903 - mmdet - INFO - Epoch [2][50/61]       lr: 2.208e-03, eta: 0:01:53, time: 0.203, data_time: 0.044, memory: 1068, loss_cls: 1.1514, loss_bbox: 0.8310, loss: 1.9823
2021-08-24 12:56:28,600 - mmdet - INFO - Saving checkpoint at 2 epochs
```

**Comment by David-Biggs** [comment]
> @anurag1paul I tested retinanet and found no problems. Can you consider updating to the latest version?
> 
> ```
> 2021-08-24 12:55:53,757 - mmdet - INFO - Epoch [1][50/61]       lr: 9.890e-04, eta: 0:02:17, time: 0.201, data_time: 0.044, memory: 1068, loss_cls: 1.1531, loss_bbox: 0.8725, loss: 2.0256
> 2021-08-24 12:55:55,415 - mmdet - INFO - Saving checkpoint at 1 epochs
> [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 120/120, 8.1 task/s, elapsed: 15s, ETA:     0s2021-08-24 12:56:10,653 - mmdet - INFO - Evaluating bbox...
> Loading and preparing results...
> 2021-08-24 12:56:10,653 - mmdet - ERROR - The testing results of the whole dataset is empty.
> 2021-08-24 12:56:10,654 - mmdet - INFO - Exp name: retinanet_r50_fpn_1x_coco.py
> 2021-08-24 12:56:10,655 - mmdet - INFO - Epoch(val) [1][120]    
> 2021-08-24 12:56:16,709 - mmdet - INFO - Exp name: retinanet_r50_fpn_1x_coco.py
> 2021-08-24 12:56:16,709 - mmdet - INFO - Epoch(val) [1][60]     loss_cls: 1.1543, loss_bbox: 0.7726, loss: 1.9269
> 2021-08-24 12:56:26,903 - mmdet - INFO - Epoch [2][50/61]       lr: 2.208e-03, eta: 0:01:53, time: 0.203, data_time: 0.044, memory: 1068, loss_cls: 1.1514, loss_bbox: 0.8310, loss: 1.9823
> 2021-08-24 12:56:28,600 - mmdet - INFO - Saving checkpoint at 2 epochs
> ```

Is workflow = [('train', 1), ('val', 1)] the only thing you changed in config? 
I successfully got Epoch(val) but with mAP, I would like loss (as you have it).
