### ISSUE TITLE
Training on multiple nodes(docker container) mounting same storage got “Input/output error” & “RuntimeError: Broken pipe”

### ISSUE THREAD

**Issue by ybbthou8** [open-mmlab/mmdetection#5709]
I have two docker containers mounting same storage and work_dirs is in the storage, there are 4 V100s in each container, mmdet version is 2.14.0 and mmcv-full version is 1.3.8

containers's ip is 10.38.160.70 and 10.38.160.71, I pull the tasks with command:
master(10.38.160.71): python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=0 --master_addr="10.38.160.71" --master_port=29500 tools/train.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py --launcher pytorch
worker(10.38.160.70): python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="10.38.160.71" --master_port=29500 tools/train.py configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py --launcher pytorch
when I run the master command, after ten seconds ,run the worker command, it works, Training on multiple nodes works well.
however, when I run the two commands at the same time, I got these error:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 128, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 524, in dump
    f.write(self.pretty_text)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/fcos/fcos_r50_caffe_fpn_gn-head_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
root@10-38-160-71:/mnt/test/mmlab/mmdetection# Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 162, in main
    model.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 45, in init_weights
    initialize(self, self.init_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 527, in initialize
    _initialize(module, cp_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 432, in _initialize
    func(module)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 416, in __call__
    logger=logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 405, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 286, in load_from_http
    torch.distributed.barrier()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 1710, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 162, in main
    model.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 45, in init_weights
    initialize(self, self.init_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 527, in initialize
    _initialize(module, cp_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 432, in _initialize
    func(module)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 416, in __call__
    logger=logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 405, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 286, in load_from_http
    torch.distributed.barrier()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 1710, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 162, in main
    model.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_module.py", line 45, in init_weights
    initialize(self, self.init_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 527, in initialize
    _initialize(module, cp_cfg)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 432, in _initialize
    func(module)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/cnn/utils/weight_init.py", line 416, in __call__
    logger=logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 405, in load_from_openmmlab
    checkpoint = load_from_http(model_url, map_location=map_location)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/checkpoint.py", line 286, in load_from_http
    torch.distributed.barrier()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 1710, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe

**Comment by AronLin** [comment]
You can open an issue on [MMCV](https://github.com/open-mmlab/mmcv/issues).

**Comment by ybbthou8** [comment]
@AronLin OK
