### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'release'

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#5724]
When I use 'pip install mmcv-full -f http://download.openmmlab.com/mmcv/dist/cu102/torch1.5.0/index.html' to install mmcv, the error below appeared:
```bash
ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hztm5i6k/mmcv-full_5fc671f531b84bd1bea94da43fd8c2fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hztm5i6k/mmcv-full_5fc671f531b84bd1bea94da43fd8c2fe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1_fcef7f
         cwd: /tmp/pip-install-hztm5i6k/mmcv-full_5fc671f531b84bd1bea94da43fd8c2fe/
    Complete output (13 lines):
    which: no hipcc in (/opt/gcc/9.3.0/bin:/opt/hpcx/2.6.0/ompi-icc/2019.update5/bin:/opt/hpcx/2.6.0/clusterkit/bin:/opt/hpcx/2.6.0/ompi-icc/2019.update5/tests/imb:/opt/hpcx/2.6.0/hcoll/bin:/opt/hpcx/2.6.0/ucx/bin:/opt/intel/2019.update5/compilers_and_libraries_2019.5.281/linux/bin/intel64:/opt/intel/2019.update5/debugger_2019/gdb/intel64/bin:/opt/intel/2019.update5/parallel_studio_xe_2019.1.053/bin:/opt/cuda/10.2.89/bin:/opt/anaconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/opt/bin:/home/sist/tqzouustc/.local/bin:/home/sist/tqzouustc/bin)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hztm5i6k/mmcv-full_5fc671f531b84bd1bea94da43fd8c2fe/setup.py", line 320, in <module>
        version=get_version(),
      File "/tmp/pip-install-hztm5i6k/mmcv-full_5fc671f531b84bd1bea94da43fd8c2fe/setup.py", line 37, in get_version
        exec(compile(f.read(), version_file, 'exec'))
      File "mmcv/version.py", line 35, in <module>
        version_info = parse_version_info(__version__)
      File "mmcv/version.py", line 21, in parse_version_info
        assert version.release, f'failed to parse version {version_str}'
    AttributeError: 'Version' object has no attribute 'release'
    No CUDA runtime is found, using CUDA_HOME='/opt/cuda/10.2.89'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Is this a bug of version.py since it has been changed recently?

**Comment by Icecream-blue-sky** [comment]
It's my personal fault.

**Comment by jiarenyf** [comment]
???

**Comment by Wolfgang1998** [comment]
Have you solved this problem？

**Comment by szxwpp** [comment]
pip install --upgrade packaging

upgrade packaging to the latest version
