### ISSUE TITLE
 AttributeError: 'ConfigDict' object has no attribute 'pipeline' at quick run

### ISSUE THREAD

**Issue by YHYeooooong** [open-mmlab/mmdetection#5739]
Hi, Thanks for sharing your nice work!

I am a beginner in MMDetection and have processed quick runs, but I have errors like below when I try to do Result Analysis with my adjusted config file from quick run3.

> AttributeError: 'ConfigDict' object has no attribute 'pipeline'

I used the config file like this for a short practice.
I copied the code of 'Prepare a config' and erase the AutoAugment part in lines 91, 
> dict( type='AutoAugment' .....) 

and adjust the to FPN as same as original ' ../_base_/models/cascade_mask_rcnn_r50_fpn.py' use
> neck=dict(type='AugFPN' ...) 

my command line is the same as this

> CUDA_VISIBLE_DEVICES=1 python tools/train.py \\
>configs/cityscapes/cascade_mask_rcnn_r50_augfpn_autoaug_10e_cityscapes.py --wdir ./work_dir/city_cascade/

> python tools/test.py configs/cityscapes/cascade_mask_rcnn_r50_augfpn_autoaug_10e_cityscapes.py \\
> ./work_dir/city_cascade/latest.pth \\
>--out ./work_dir/city_cascade/test_result/results.pkl --eval bbox segm

>python tools/analysis_tools/analyze_results.py \\
>configs/cityscapes/cascade_mask_rcnn_r50_augfpn_autoaug_10e_cityscapes.py \\
> ./work_dir/city_cascade/test_result/results.pkl \\
>./work_dir/city_cascade/analized_result/

and after the third command, I got an error message like this

>  AttributeError: 'ConfigDict' object has no attribute 'pipeline'

Total code for my config file
```python
_base_ = [
    '../_base_/models/cascade_mask_rcnn_r50_fpn.py',
    '../_base_/datasets/cityscapes_instance.py', '../_base_/default_runtime.py'
]

model = dict(
    # set None to avoid loading ImageNet pretrained backbone,
    # instead here we set `load_from` to load from COCO pretrained detectors.
    backbone=dict(init_cfg=None),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    # replace neck from defaultly `FPN` to our new implemented module `AugFPN`
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                # change the number of classes from defaultly COCO to cityscapes
                num_classes=8,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                # change the number of classes from defaultly COCO to cityscapes
                num_classes=8,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                # change the number of classes from defaultly COCO to cityscapes
                num_classes=8,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ],
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            # change the number of classes from defaultly COCO to cityscapes
            num_classes=8,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))))

# over-write `train_pipeline` for new added `AutoAugment` training setting
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        type='Resize', img_scale=[(224, 224)], keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=3,
    # over-write `pipeline` with new training pipeline setting
    train=dict(dataset=dict(pipeline=train_pipeline)))
# Set optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# Set customized learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8])
runner = dict(type='EpochBasedRunner', max_epochs=5)

# We can use the COCO pretrained Cascade Mask R-CNN R50 model for more stable performance initialization
load_from = 'https://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_mask_rcnn_r50_fpn_1x_coco/cascade_mask_rcnn_r50_fpn_1x_coco_20200203-9d4dcb24.pth'
```

I also checked issues #1533 , #4240 but I can't make it
Are there anythings did I miss? If It is can you where I have to fix it?
Thanks!

**Comment by ZwwWayne** [comment]
You might need to change 
```python
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=3,
    # over-write `pipeline` with new training pipeline setting
    train=dict(dataset=dict(pipeline=train_pipeline)))
```
to 
```
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=3,
    # over-write `pipeline` with new training pipeline setting
    train=dict(
        pipeline=train_pipeline,
        dataset=dict(pipeline=train_pipeline)))
```

**Comment by YHYeooooong** [comment]
Thanks! I will try

**Comment by wwcc1107** [comment]
hi have you solved the problem?i also meet the problem:
Traceback (most recent call last):
  File "./tools/train.py", line 242, in <module>
    main()
  File "./tools/train.py", line 221, in main
    val_dataset.pipeline = cfg.data.train.pipeline
  File "/home/wangchang2/anaconda3/envs/mmdeploy/lib/python3.7/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'pipeline'

**Comment by chainaiquan** [comment]
You can change line 222 in file "train.py" 
`val_dataset.pipeline = cfg.data.train.pipeline`
to
`val_dataset.pipeline = cfg.data.train.dataset.pipeline`

**Comment by serser** [comment]
I had the issue since `ConcatDataset` doesn't have test_pipeline at the first level.

**Comment by gafrancia** [comment]
> I had the issue since `ConcatDataset` doesn't have test_pipeline at the first level.

Hi serser, did you solve this issue? I need help trying to use ConcatDataset. Also, when I tried to perform validation, I got an error "data['category_id'] = self.cat_ids[label] IndexError: list index out of range". I have checked possible solutions, adjusted the index, and put it in sequence like dataset_A classes = ('dog', 'cat'), dataset_B classes = ('horse', 'mice'), ann_A: cat_id: 1 for dog, 2 for cat], ann_B: cat_id: 3 for horse, 4 for mice. Classes were changed at COCO class as well. I would appreciate any help you can give me or anyone.

**Comment by XinyueZ** [comment]
@serser have you solved?
