### ISSUE TITLE
results['img'].shape != results['img_shape'] when use Albu's RandomRotate90  to augment the dataset.

### ISSUE THREAD

**Issue by kingstarcraft** [open-mmlab/mmdetection#5755]
I add dict(type='Albu', transforms=[dict(type='RandomRotate90', p=0.5)]) to pipeline. results['img'].shape != results['img_shape'], when the data rotate 90 or 270. Is it a bug?

**Comment by BIGWangYuDong** [comment]
Hi, I didn't meet this error before, I'll have a try this afternoon.

**Comment by BIGWangYuDong** [comment]
@kingstarcraft Hi, please give me your config file, I have checked randomrotate90 and did not get the error. Did you fix your error?

**Comment by wzr0108** [comment]
have you met this error when using RandomRotate90 
```
Traceback (most recent call last):
  File "./tools/train.py", line 234, in <module>
    main()
  File "./tools/train.py", line 221, in main
    meta=meta)
  File "/disk/sde/qwe/project/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/sde/qwe/project/mmdet/datasets/dataset_wrappers.py", line 437, in __getitem__
    'The training pipeline of the dataset wrapper'
RuntimeError: The training pipeline of the dataset wrapper always return None.Please check the correctness of the dataset and its pipeline.
```
when i remove RandomRotate90 , the training is normal

**Comment by BIGWangYuDong** [comment]
feel free to re-open this issue if you still meet this error
