### ISSUE TITLE
train fail：TypeError: init_weights() missing 1 required positional argument: 'pretrained'

### ISSUE THREAD

**Issue by chensen668** [open-mmlab/mmdetection#5775]
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 162, in main
    model.init_weights()
  File "/home/ubuntu/.conda/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/base_module.py", line 55, in init_weights
    m.init_weights()
TypeError: init_weights() missing 1 required positional argument: 'pretrained'

**Comment by hhaAndroid** [comment]
@chensen668 Please use the latest version of the code and corresponding configuration.

**Comment by chensen668** [comment]
你是说我的config里面有的代码跟mmdet版本不匹配吗

**Comment by chensen668** [comment]
我知道错误原因了，我的mmdet版本是2.12，但是我迁移了2.3的代码去重写config，所以一直报错。但是因为我的CUDA是11.2，所以我用不了2.3版本的mmdet。话说mmdet2.12和mmdet2.3是不是有些代码格式问题，需要重新修改
