### ISSUE TITLE
Error in installing the mmdet

### ISSUE THREAD

**Issue by AslanDevbrat** [open-mmlab/mmdetection#5778]
I am simply trying to install the mmdet using 

```
pip install openmim
mim install mmdet
```

Even though I am running those commands through Administrator I am getting this error`

```
installing mmdet from https://github.com/open-mmlab/mmdetection.git.
Cloning into 'C:\Users\lenovo\AppData\Local\Temp\tmp02_5m7dj\mmdetection'...
remote: Enumerating objects: 20267, done.
remote: Counting objects: 100% (527/527), done.
remote: Compressing objects: 100% (256/256), done.
remote: Total 20267 (delta 319), reused 407 (delta 271), pack-reused 19740
Receiving objects: 100% (20267/20267), 24.11 MiB | 547.00 KiB/s, done.
Resolving deltas: 100% (14078/14078), done.
Note: switching to '2028b0c189d676ce0c7ad31f24f8a68107220855'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (1118/1118), done.
Successfully installed dependencies.
Processing c:\users\lenovo\appdata\local\temp\tmp02_5m7dj\mmdetection
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: matplotlib in c:\users\lenovo\appdata\roaming\python\python37\site-packages (from mmdet==2.14.0) (3.4.2)
Requirement already satisfied: numpy in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from mmdet==2.14.0) (1.20.3)
Requirement already satisfied: six in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from mmdet==2.14.0) (1.16.0)
Requirement already satisfied: terminaltables in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from mmdet==2.14.0) (3.1.0)
Requirement already satisfied: pycocotools-windows in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from mmdet==2.14.0) (2.0.0.2)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from matplotlib->mmdet==2.14.0) (1.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from matplotlib->mmdet==2.14.0) (2.4.7)
Requirement already satisfied: pillow>=6.2.0 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from matplotlib->mmdet==2.14.0) (8.3.1)
Requirement already satisfied: python-dateutil>=2.7 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from matplotlib->mmdet==2.14.0) (2.8.2)
Requirement already satisfied: cycler>=0.10 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from matplotlib->mmdet==2.14.0) (0.10.0)
Requirement already satisfied: setuptools>=18.0 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from pycocotools-windows->mmdet==2.14.0) (52.0.0.post20210125)
Requirement already satisfied: cython>=0.27.3 in e:\python\pythoninstall\envs\open-mmlab\lib\site-packages (from pycocotools-windows->mmdet==2.14.0) (0.29.24)
Building wheels for collected packages: mmdet
  Building wheel for mmdet (setup.py) ... done
  Created wheel for mmdet: filename=mmdet-2.14.0-py3-none-any.whl size=1047496 sha256=6a1b0d7b60bcc1cea493e1bbd25e7965cef1c05d65df463df67562a7021ece78
  Stored in directory: C:\Users\lenovo\AppData\Local\Temp\pip-ephem-wheel-cache-2dgeq7b4\wheels\5a\4b\48\6cbbbb59ae0b527b993841339d1fc41a0f5cbefd892a54ae50
Successfully built mmdet
Installing collected packages: mmdet
Successfully installed mmdet-2.14.0
Traceback (most recent call last):
  File "e:\python\pythoninstall\envs\open-mmlab\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Python\PythonInstall\envs\open-mmlab\Scripts\mim.exe\__main__.py", line 7, in <module>
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\mim\commands\install.py", line 107, in cli
    is_editable=is_editable)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\mim\commands\install.py", line 211, in install
    is_yes, is_user_dir, is_install_master)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\site-packages\mim\commands\install.py", line 540, in install_from_github
    is_user_dir=is_user_dir)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\tempfile.py", line 807, in __exit__
    self.cleanup()
  File "e:\python\pythoninstall\envs\open-mmlab\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "e:\python\pythoninstall\envs\open-mmlab\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\tmp02_5m7dj\\mmdetection\\.git\\objects\\pack\\pack-db3941c3cc1018e1f9fc4cbe022cccfe96163eff.idx'

```

i tried  `pip install --upgrade pip --user` but no result Can you help me?

**Comment by BIGWangYuDong** [comment]
Hi, you can try to install the mmdet in other way, for example, using `pip install mmdet` or install mmdet by git repo. More details please refer to [get_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/get_started.md)
