### ISSUE TITLE
Strange behaviours when training with imgs_per_gpu=3.

### ISSUE THREAD

**Issue by sebgao** [open-mmlab/mmdetection#58]
Hi.

Thank you for the great work. I found there were some strange behaviours when I was trying to train faster R-CNN with imgs_per_gpu=3 (although the number 3 is inappropriate to some extent). One is that in the very beginning training accuracy is above ~95%, which is relatively high compared to ~89% with imgs_per_gpu=2 or 4. And the other is that after validation epoch, an error related to indices happened.

`Loading and preparing results...
Traceback (most recent call last):
  File "./tools/train.py", line 81, in <module>
    main()
  File "./tools/train.py", line 77, in main
    logger=logger)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmdet/apis/train.py", line 92, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 349, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 265, in train
    self.call_hook('after_train_epoch')
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmcv/runner/runner.py", line 222, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmdet/core/evaluation/eval_hooks.py", line 93, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/mmdet/core/evaluation/eval_hooks.py", line 134, in evaluate
    cocoDt = cocoGt.loadRes(tmp_file)
  File "/home/root/miniconda3/envs/mytorch/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range`

**Comment by hellock** [comment]
`imgs_per_gpu=3` is ok, the error is caused by the empty output for all images. Maybe your hyper parameters are not correctly set and the model is not converging.
