### ISSUE TITLE
TypeError: 'DataContainer' object is not subscriptable

### ISSUE THREAD

**Issue by Wolfwjs** [open-mmlab/mmdetection#5806]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Everything is normal during the training phase，but during the testing phase, I can’t run and report an error:
TypeError: 'DataContainer' object is not subscriptable

**Reproduction**

1. What command or script did you run?

```none
sh test_slurm.sh
#!/usr/bin/env bash

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \

srun -p pat \
    --job-name=test \
    --gres=gpu:2 \
    --ntasks=2 \
    --ntasks-per-node=2 \
    --cpus-per-task=5 \
    --kill-on-bad-exit=1 \
    python -u test.py \
    ../configs/condlanenet/tusimple/tusimple_small_test.py \
    /mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/tools/output/small/latest.pth \
    --show \
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

3. What dataset did you use?
Tusimple

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: False
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture appl
ications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_
PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPP
ER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits 
-Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused
-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=de
precated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-styl
e-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math
-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_A
VX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF
, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 0.5.6
MMDetection: 2.0.0+73c2043
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1

```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]   **conda**
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
(openmm) [wangjinsheng@HOST-10-198-32-69 tools]$ sh test_slurm.sh 
[                                                  ] 0/2782, elapsed: 0s, ETA:[                                                  ] 0/2782, elapsed: 0s, ETA:Traceback (most recent call last):
Traceback (most recent call last):
  File "test.py", line 149, in <module>
  File "test.py", line 149, in <module>
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    main()
  File "test.py", line 127, in main
    args.show_score_thr)
  File "/mnt/lustre/wangjinsheng/project/lane-detection/conditional-lane-detection/mmdet/apis/test.py", line 28, in single_gpu_test
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable
    img_tensor = data['img'][0]
TypeError: 'DataContainer' object is not subscriptable

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jshilong** [comment]
There may be problems in `getitem` of your own dataset, you check what `data['img]` is

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
