### ISSUE TITLE
bbox_label dimension incorrect in cascade_roi_head.py simeple test

### ISSUE THREAD

**Issue by collinzrj** [open-mmlab/mmdetection#5817]
**Describe the bug**
I am trying the cascade rcnn network on a test dataset with a single image, after the training begins, the `regress_by_class` method called in `simple_test` of `cascade_roi_head.py` produce an error. 

**Error traceback**
```
2021-08-07 12:48:22,062 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/1, elapsed: 0s
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 177, in main
    train_detector(
  File "c:\users\colli\mmdetection\mmdet\apis\train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\hooks\evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "c:\users\colli\mmdetection\mmdet\core\evaluation\eval_hooks.py", line 17, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "c:\users\colli\mmdetection\mmdet\apis\test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "C:\Users\colli\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\parallel\data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "C:\Users\colli\anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\colli\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\colli\mmdetection\mmdet\models\detectors\base.py", line 173, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "c:\users\colli\mmdetection\mmdet\models\detectors\base.py", line 146, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "c:\users\colli\mmdetection\mmdet\models\detectors\two_stage.py", line 181, in simple_test
    return self.roi_head.simple_test(
  File "c:\users\colli\mmdetection\mmdet\models\roi_heads\cascade_roi_head.py", line 344, in simple_test
    refined_rois = self.bbox_head[i].regress_by_class(
  File "C:\Users\colli\anaconda3\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\colli\mmdetection\mmdet\models\roi_heads\bbox_heads\bbox_head.py", line 471, in regress_by_class
    inds = torch.stack((label, label + 1, label + 2, label + 3), 1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Environment**

```
sys.platform: win32
Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2060 SUPER
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
NVCC: Not Available
GCC: n/a
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.10.0
OpenCV: 4.5.2
MMCV: 1.3.9
MMCV Compiler: MSVC 192729111
MMCV CUDA Compiler: 11.2
MMDetection: 2.15.0+62a1cd3

```

**Bug fix**
https://github.com/open-mmlab/mmdetection/blob/62a1cd3fd6091fc4efa83627631ab4b99a8d005c/mmdet/models/roi_heads/cascade_roi_head.py#L332-L345
https://github.com/open-mmlab/mmdetection/blob/46988b3ac9820bcd8728980f04be98272ee5ea39/mmdet/models/roi_heads/bbox_heads/bbox_head.py#L453-L465
`regress_by_class` expects a shape (n, ), but in the code above, in line 341 bbox_label is produced by slicing the cls_score, so it has been a 1 dimension tensor, but in line 343, it is sliced again, so it seems to be a zero dimension scalar now. I guess this produce the problem, after changing it to 
```
refined_rois = self.bbox_head[i].regress_by_class(rois[j], bbox_label, bbox_pred[j], img_metas[j])
```
The code runs correctly. 
The change in these lines is made in fd5d019ca983b032c35d15cd900b0fa6eec4f988 by @hhaAndroid, can you have a look at it? Am I understanding it correctly?

**Comment by maksimovkonstantin** [comment]
@hhaAndroid can you pls take a look at it?

**Comment by collinzrj** [comment]
Can anyone have a look at this issue?

**Comment by jshilong** [comment]
Sorry for the late response, we involve in another project in last weeks, we will check it asap
