### ISSUE TITLE
ScNet Training Error using training bash file

### ISSUE THREAD

**Issue by sagnik1511** [open-mmlab/mmdetection#5839]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. When working on ScNet, I used the data [VHR-10](https://github.com/chaozhong2010/VHR-10_dataset_coco) and updated the configs as per those.
2. I downloaded the pre-trained model of Scnet family which has the backbone **X-101-64x4d-FPN** and the scheduler was 20e and connected to [this](https://github.com/open-mmlab/mmdetection/tree/master/configs/scnet/scnet_x101_64x4d_fpn_20e_coco.py) config file.
3. Then I hit an error when training it using the bash command which is -
```!bash tools/dist_train.sh configs/scnet/scnet_x101_64x4d_fpn_20e_coco.py 1 --no-validate``` in google colab with Tesla-T4 GPU support.
**Error traceback**
Traceback (most recent call last):

```none
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 378, in __call__
    results = self._load_semantic_seg(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/loading.py", line 352, in _load_semantic_seg
    img_bytes = self.file_client.get(filename)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/fileio/file_client.py", line 306, in get
    return self.client.get(filepath)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/fileio/file_client.py", line 184, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/content/VHR10/dataset/images/193.png'
```
If anybody faced the same error or recovered from an error similar to this , please **help**.

**Comment by hhaAndroid** [comment]
@sagnik1511 Incorrect image path. You need to move or link the data to `mmdetection/data`.

**Comment by sagnik1511** [comment]
Yeah, I've updated the data directory path in the configs that were connected to the selected one, I also have updated the num_classes of the model, Still, it happens. I also tried to set the data inside that specific directory, but that still couldn't help me.

**Comment by hhaAndroid** [comment]
@sagnik1511 O, May have to perform an inspection.
