### ISSUE TITLE
'ConfigDict' object has no attribute 'model'

### ISSUE THREAD

**Issue by NNNNerd** [open-mmlab/mmdetection#5843]
At first I installed mmdet successfully and have run a sample code to inference a demo image. Later I installed mmpose and demo for mmpose worked fine. But when I used mmdet after that, it was not working. Maybe because when I install mmpose I re-installed different version of mmcv or pytorch. 

 Traceback (most recent call last):
  File "demo1.py", line 7, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "/home/zy/mmdetection/mmdet/apis/inference.py", line 37, in init_detector
    config.model.pretrained = None
  File "/home/zy/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 490, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/zy/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 47, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'model'

**Comment by hhaAndroid** [comment]
@NNNNerd Maybe you can confirm the version of MMCV and PyTorch.
