### ISSUE TITLE
Yolact loading pre trained weights fails

### ISSUE THREAD

**Issue by skaldesh** [open-mmlab/mmdetection#5855]
Hi, 
I wanted to fine tune a pre trained YOLACT model with my own custom data.  
I have successfully done so already with a Mask-RCNN.  

When loading the pre trained weights, the `torch.load_state_dict_from_url` raises `RuntimeError('Only one file(not dir) is allowed in the zipfile')`  

Following, my configuration I am using:

My Config printed with `tools/misc/print_config.py`:  
```py
Config:
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = 'https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/yolact/yolact_r50_1x8_coco_20200908-f38d58df.pth'
resume_from = None
workflow = [('train', 1)]
img_size = 550
model = dict(
    type='YOLACT',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=False,
        zero_init_residual=False,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5,
        upsample_cfg=dict(mode='bilinear')),
    bbox_head=dict(
        type='YOLACTHead',
        num_classes=1,
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=3,
            scales_per_octave=1,
            base_sizes=[8, 16, 32, 64, 128],
            ratios=[0.5, 1.0, 2.0],
            strides=[
                7.971014492753623, 15.714285714285714, 30.555555555555557,
                61.111111111111114, 110.0
            ],
            centers=[(3.9855072463768115, 3.9855072463768115),
                     (7.857142857142857, 7.857142857142857),
                     (15.277777777777779, 15.277777777777779),
                     (30.555555555555557, 30.555555555555557), (55.0, 55.0)]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[0.1, 0.1, 0.2, 0.2]),
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            reduction='none',
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.5),
        num_head_convs=1,
        num_protos=32,
        use_ohem=True),
    mask_head=dict(
        type='YOLACTProtonet',
        in_channels=256,
        num_protos=32,
        num_classes=1,
        max_masks_to_train=100,
        loss_mask_weight=6.125),
    segm_head=dict(
        type='YOLACTSegmHead',
        num_classes=1,
        in_channels=256,
        loss_segm=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0.0,
            ignore_iof_thr=-1,
            gt_max_assign_all=False),
        allowed_border=-1,
        pos_weight=-1,
        neg_pos_ratio=3,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        iou_thr=0.5,
        top_k=200,
        max_per_img=100))
dataset_type = 'CocoDataset'
data_root = '/mmdetection/data/dataset/'
img_norm_cfg = dict(
    mean=[123.68, 116.78, 103.94], std=[58.4, 57.12, 57.38], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=[123.68, 116.78, 103.94],
        to_rgb=True,
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(550, 550), keep_ratio=False),
    dict(
        type='Normalize',
        mean=[123.68, 116.78, 103.94],
        std=[58.4, 57.12, 57.38],
        to_rgb=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(550, 550),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.68, 116.78, 103.94],
                std=[58.4, 57.12, 57.38],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        ann_file='data/coco/annotations/instances_train2017.json',
        img_prefix='data/coco/train2017/',
        pipeline=[
            dict(type='LoadImageFromFile', to_float32=True),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
            dict(
                type='PhotoMetricDistortion',
                brightness_delta=32,
                contrast_range=(0.5, 1.5),
                saturation_range=(0.5, 1.5),
                hue_delta=18),
            dict(
                type='Expand',
                mean=[123.68, 116.78, 103.94],
                to_rgb=True,
                ratio_range=(1, 4)),
            dict(
                type='MinIoURandomCrop',
                min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                min_crop_size=0.3),
            dict(type='Resize', img_scale=(550, 550), keep_ratio=False),
            dict(
                type='Normalize',
                mean=[123.68, 116.78, 103.94],
                std=[58.4, 57.12, 57.38],
                to_rgb=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ],
        times=3,
        classes=('Baumstamm', ),
        dataset=dict(
            type='CocoDataset',
            classes=('Baumstamm', ),
            ann_file='/mmdetection/data/dataset/coco.json',
            img_prefix='/mmdetection/data/dataset/',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
                dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
                dict(
                    type='PhotoMetricDistortion',
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                dict(
                    type='Expand',
                    mean=[123.68, 116.78, 103.94],
                    to_rgb=True,
                    ratio_range=(1, 4)),
                dict(
                    type='MinIoURandomCrop',
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
                    min_crop_size=0.3),
                dict(type='Resize', img_scale=(550, 550), keep_ratio=False),
                dict(
                    type='Normalize',
                    mean=[123.68, 116.78, 103.94],
                    std=[58.4, 57.12, 57.38],
                    to_rgb=True),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(type='DefaultFormatBundle'),
                dict(
                    type='Collect',
                    keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
            ])),
    val=dict(
        type='CocoDataset',
        ann_file='/mmdetection/data/dataset/coco.json',
        img_prefix='/mmdetection/data/dataset/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(550, 550),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.68, 116.78, 103.94],
                        std=[58.4, 57.12, 57.38],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('Baumstamm', )),
    test=dict(
        type='CocoDataset',
        ann_file='/mmdetection/data/dataset/coco.json',
        img_prefix='/mmdetection/data/dataset/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(550, 550),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=False),
                    dict(
                        type='Normalize',
                        mean=[123.68, 116.78, 103.94],
                        std=[58.4, 57.12, 57.38],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('Baumstamm', )))
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.1,
    step=[7])
runner = dict(type='EpochBasedRunner', max_epochs=20)
cudnn_benchmark = True
evaluation = dict(metric=['bbox', 'segm'], interval=2)
classes = ('Baumstamm', )
```

The log output:  
```
2021-08-10 15:41:11,330 - mmdet - INFO - load checkpoint from https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/yolact/yolact_r50_1x8_coco_20200908-f38d58df.pth
2021-08-10 15:41:11,330 - mmdet - INFO - Use load_from_http loader
Downloading: "https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/yolact/yolact_r50_1x8_coco_20200908-f38d58df.pth" to /root/.cache/torch/hub/checkpoints/yolact_r50_1x8_coco_20200908-f38d58df.pth
100%|██████████| 135M/135M [00:20<00:00, 6.86MB/s] 
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 169, in train_detector
    runner.load_checkpoint(cfg.load_from)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 345, in load_checkpoint
    revise_keys=revise_keys)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 513, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 451, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 244, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 284, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/opt/conda/lib/python3.7/site-packages/torch/hub.py", line 490, in load_state_dict_from_url
    raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
RuntimeError: Only one file(not dir) is allowed in the zipfile
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
```

The Dockerfile I am using (copied from this repo): 
```docker
ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install MMCV
RUN pip install mmcv-full==1.3.8 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html

# Install MMDetection
RUN conda clean --all
#RUN git clone https://github.com/open-mmlab/mmdetection.git /mmdetection
COPY . /mmdetection
WORKDIR /mmdetection
ENV FORCE_CUDA="1"
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .
```

**Comment by bommap2810** [comment]
My recommendation is that you download .pth file directly then in the line `load_from = <url>` you just need to pass your .pth path.
For example, your downloaded file was stored in /home/Downloads/*.pth then fix it into:
`load_from = '/home/Downloads/*.pth'`

**Comment by skaldesh** [comment]
May I ask why you think that would fix it? From the log output it seems that the download succeeded and the `load_state_from_dict` then fails. I do not see how a manual download could fix this.

**Comment by bommap2810** [comment]
> May I ask why you think that would fix it? From the log output it seems that the download succeeded and the `load_state_from_dict` then fails. I do not see how a manual download could fix this.

I think you should check the checkpoint link, it was a zip file, not .pth file, u can unzip it and see the folder.

**Comment by skaldesh** [comment]
Ah I see. I manually downloaded the checkpoint and unzipped it. It has the following folder structure:  
```
archive
  - 136M data (dir)
  - 56K   data.pkl (file)
  - 4.0K  version (file)
```
Which one would I need to supply to `load_state_from_dict`?

**Comment by skaldesh** [comment]
For me it did not work yet.  
I've included `resume_from = "/mmdetection/data/archive/data.pkl"` in my config, but it failed with another error.  

Could you show me your config?

**Comment by AronLin** [comment]
https://github.com/open-mmlab/mmsegmentation/issues/687
This issue may help you.

**Comment by AronLin** [comment]
The 1.6 release of PyTorch switched `torch.save` to use a new zipfile-based file format. `torch.load` still retains the ability to load files in the old format. If for any reason you want `torch.save` to use the old format, pass the kwarg `_use_new_zipfile_serialization=False`.

This is what the Pytorch documentation says.

**Comment by skaldesh** [comment]
Sorry but this does not fix my issue.  
The Dockerfile of this repo installs pytorch 1.6.0. So why does the `torch.load` fail?  

The error message I got said: `RuntimeError: Only one file(not dir) is allowed in the zipfile`

**Comment by AronLin** [comment]
I see, you should not use `torch.load_state_dict_from_url`, you should use our `mmcv.runner.load_checkpoint`.

**Comment by skaldesh** [comment]
@AronLin Could you please reopen the issue and wait, until I confirm that it is actually resolved? Thank you :) (no offense)
