### ISSUE TITLE
How to do inference using a single image only?

### ISSUE THREAD

**Issue by TrinhDinhPhuc** [open-mmlab/mmdetection#5871]
How to do inference using a single image only?

**Comment by RangiLyu** [comment]
Run demo/image_demo.py

**Comment by TrinhDinhPhuc** [comment]
@RangiLyu  Thank you but i got this weird error:
```

Traceback (most recent call last):
  File "tools/inference_demo.py", line 12, in <module>
    show_result_pyplot(model, img, result)
  File "/home/merge/Harry/instance_seg/ZSI2_cu11_copy/mmdet/apis/inference.py", line 169, in show_result_pyplot
    img, result, class_names, score_thr=score_thr, show=False)
  File "/home/merge/Harry/instance_seg/ZSI2_cu11_copy/mmdet/apis/inference.py", line 117, in show_result
    img = mmcv.imread(img)
  File "/home/merge/anaconda3/envs/zsi_mmdet2.14/lib/python3.7/site-packages/mmcv/image/io.py", line 44, in imread
    raise TypeError('"img" must be a numpy array or a filename')
TypeError: "img" must be a numpy array or a filename
```


My code
```
checkpoint_file = './work_dirs/zsi/baseline_original/65_15/epoch_48.pth'
# checkpoint_file = 'model.pt'
config_file = './configs/zsi/65_15/test/gzsi/zero-shot-mask-rcnn-BARPN-bbox_mask_sync_bg_65_15_decoder_notanh_gzsi.py'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = './data/coco/val2014/COCO_val2014_000000081922.jpg'
result = inference_detector(model, img)
show_result_pyplot(model, img, result)
```
