### ISSUE TITLE
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

### ISSUE THREAD

**Issue by irvtree** [open-mmlab/mmdetection#5885]
**Error traceback**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhanghong/mmdetection/tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/zhanghong/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/zhanghong/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/zhanghong/mmdetection/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/home/zhanghong/mmdetection/mmdet/datasets/cityscapes.py", line 16, in <module>
    from .coco import CocoDataset
  File "/home/zhanghong/mmdetection/mmdet/datasets/coco.py", line 14, in <module>
    from .api_wrappers import COCO, COCOeval
  File "/home/zhanghong/mmdetection/mmdet/datasets/api_wrappers/__init__.py", line 1, in <module>
    from .coco_api import COCO, COCOeval
  File "/home/zhanghong/mmdetection/mmdet/datasets/api_wrappers/coco_api.py", line 6, in <module>
    from pycocotools.coco import COCO as _COCO
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/site-packages/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2500, in <module>
    switch_backend(rcParams["backend"])
  File "/home/zhanghong/anaconda3/envs/openmmlab/lib/python3.7/site-packages/matplotlib/pyplot.py", line 288, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
Which OS are you using?

**Comment by irvtree** [comment]
> Which OS are you using?

in Linux

**Comment by ZwwWayne** [comment]
It seems that you installed OpenCV-headless in your environment. You may try to uninstall it and install opencv.

**Comment by shouwangzhe134** [comment]
I also suffer from this problem when matplotlib==3.4.3.
Changing the version of matplotlib  to 3.2.1 maybe solves this problem.

**Comment by shouwangzhe134** [comment]
I also suffer from this problem when matplotlib==3.4.3.
Try to change the version of matplotlib to 3.2.1.

**Comment by Ken-97** [comment]
> I also suffer from this problem when matplotlib==3.4.3. Try to change the version of matplotlib to 3.2.1.

I tried this method and it worked!

**Comment by Men200** [comment]
> > 我在matplotlib==3.4.3时也遇到了这个问题。尝试将 matplotlib 的版本更改为 3.2.1。
> 
> 我尝试了这种方法，它奏效了！

这个版本太低了，和我的python版本不适配🤦‍

**Comment by thecatcarryingakeyboard** [comment]
> 当 matplotlib==3.4.3 时，我也遇到了这个问题。尝试将 matplotlib 的版本更改为 3.2.1。

failed again
