### ISSUE TITLE
when i finish epoch1 and eval  i meet a error  

### ISSUE THREAD

**Issue by krisandchris** [open-mmlab/mmdetection#5888]
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[196.022, 194.771, 170.893],
    std=[71.407, 60.157, 73.296],
    to_rgb=True)
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=3,
    train=dict(
        type='MosaicMixUpDataset',
        dataset=dict(
            type='CocoDataset',
            ann_file='data/coco/annotations/coco_train.json',
            img_prefix='data/coco/train/',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True)
            ],
            filter_empty_gt=False),
        mosaic_pipeline=[
            dict(
                type='RandomAffineOrPerspective',
                scale=(0.1, 2),
                border=(-320, -320))
        ],
        enable_mosaic=True,
        enable_mixup=True,
        pipeline=[
            dict(type='Resize', keep_ratio=True),
            dict(type='Pad', pad2square=True, pad_val=114.0),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels'],
                meta_keys=('filename', 'ori_shape', 'img_shape',
                           'img_norm_cfg', 'pad_shape', 'scale_factor'))
        ],
        img_scale=(640, 640),
        mixup_scale=(0.8, 1.6)),
    val=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/coco_val.json',
        img_prefix='data/coco/train/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(type='Pad', size=(640, 640), pad_val=114.0),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/coco/annotations/coco_test.json',
        img_prefix='data/coco/test/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(type='Pad', size=(640, 640), pad_val=114.0),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]))

error:
2021-08-14 22:48:54,385 - mmdet - INFO - Epoch(val) [1][400]    bbox_mAP: 0.0520, bbox_mAP_50: 0.0730, bbox_mAP_75: 0.0590, bbox_mAP_s: 0.0150, bbox_mAP_m: 0.0380, bbox_mAP_l: 0.0550, bbox_mAP_copypaste: 0.052 0.073 0.059 0.015 0.038 0.055
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/root/mmdetection_x/mmdet/apis/train.py", line 269, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 64, in val
    for i, data_batch in enumerate(self.data_loader):
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.local/conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/mmdetection_x/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/root/mmdetection_x/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/root/mmdetection_x/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/root/mmdetection_x/mmdet/datasets/pipelines/transforms.py", line 292, in __call__
    self._random_scale(results)
  File "/root/mmdetection_x/mmdet/datasets/pipelines/transforms.py", line 192, in _random_scale
    elif len(self.img_scale) == 1:
TypeError: object of type 'NoneType' has no len()

**Comment by shinya7y** [comment]
> type='MosaicMixUpDataset',

Does `MultiImageMixDataset` in the latest code (after https://github.com/open-mmlab/mmdetection/pull/5848) work?

**Comment by krisandchris** [comment]
> > type='MosaicMixUpDataset',
> 
> Does `MultiImageMixDataset` in the latest code (after #5848) work?

report the same error

**Comment by krisandchris** [comment]
> > type='MosaicMixUpDataset',
> 
> Does `MultiImageMixDataset` in the latest code (after #5848) work?

i think  this issue could relate to my problem
Removing MultiScaleFlipAug or Test-Time Augmentation on Validation returns TypeError: object of type 'NoneType' has no len() #4578
