### ISSUE TITLE
Issue about tools\analysis_tools\get_flops.py

### ISSUE THREAD

**Issue by solauky** [open-mmlab/mmdetection#5891]
When I used the tools/analysis_tools/get_flops.py to compute the Flops and Parameters of YOLACT , I got an error "NotImplementedError".

Traceback (most recent call last):
  File "tools/analysis_tools/get_flops.py", line 81, in <module>
    main()
  File "tools/analysis_tools/get_flops.py", line 71, in main
    flops, params = get_model_complexity_info(model, input_shape)
  File "/home/scsc01/anaconda3/envs/mmlab/lib/python3.8/site-packages/mmcv/cnn/utils/flops_counter.py", line 104, in get_model_complexity_info
    _ = flops_model(batch)
  File "/home/scsc01/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/scsc01/lxx/mmlab/mmdet/models/detectors/yolact.py", line 32, in forward_dummy
    raise NotImplementedError
NotImplementedError
Does the get_flops.py not support the complexity calculation of YOLACT? thank you~~

**Comment by collinzrj** [comment]
In **yolact.py**, `forward_dummy` is not implemented
https://github.com/open-mmlab/mmdetection/blob/6882fa0a220880e6e2e7e0536037f043b9031185/mmdet/models/detectors/yolact.py#L27-L32
But in **get_flops.py**
https://github.com/open-mmlab/mmdetection/blob/6882fa0a220880e6e2e7e0536037f043b9031185/tools/analysis_tools/get_flops.py#L64-L69
I have checked `forward_dummy` of other models, and they are all implemented. I assume that the expected behavior is `forward_dummy` should not be declared in **yolact.py**, so the error information can be easier to understand?

**Comment by ZwwWayne** [comment]
For now we have not supported it. We will support it in the future.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
