### ISSUE TITLE
How to do distributed training with backbone written by myself

### ISSUE THREAD

**Issue by Bin-ze** [open-mmlab/mmdetection#5892]
**My backbone runs normally on a  single card, once the distributed training is carried out, the following error occurs：**

  File "./train.py", line 120, in main                                                                                                                                │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist                                        │
    _init_dist_pytorch(backend, **kwargs)                                                                                                                             │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch                               │
    init_dist(args.launcher, **cfg.dist_params)                                                                                                                       │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist                                        │
        init_dist(args.launcher, **cfg.dist_params)dist.init_process_group(backend=backend, **kwargs)                                                                 │
                                                                                                                                                                      │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group                  │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist                                        │
    _init_dist_pytorch(backend, **kwargs)                                                                                                                             │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch                               │
    _init_dist_pytorch(backend, **kwargs)                                                                                                                             │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 34, in _init_dist_pytorch                               │
    dist.init_process_group(backend=backend, **kwargs)                                                                                                                │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group                  │
    dist.init_process_group(backend=backend, **kwargs)                                                                                                                │
_store_based_barrier(rank, store, timeout)                                                                                                                            │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group                  │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 207, in _store_based_barrier                │
    time.sleep(0.01)                                                                                                                                                  │
KeyboardInterrupt                                                                                                                                                     │
    _store_based_barrier(rank, store, timeout)                                                                                                                        │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 207, in _store_based_barrier                │
    _store_based_barrier(rank, store, timeout)                                                                                                                        │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 207, in _store_based_barrier                │
    time.sleep(0.01)                                                                                                                                                  │
KeyboardInterrupt                                                                                                                                                     │
    time.sleep(0.01)                                                                                                                                                  │
KeyboardInterrupt                                                                                                                                                     │
Traceback (most recent call last):                                                                                                                                    │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                                            │
    "__main__", mod_spec)                                                                                                                                             │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code                                                                       │
    exec(code, run_globals)                                                                                                                                           │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 173, in <module>                                      │
    main()                                                                                                                                                            │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 169, in main                                          │
    run(args)                                                                                                                                                         │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/run.py", line 624, in run                                              │
    )(*cmd_args)                                                                                                                                                      │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 116, in __call__                                │
    return launch_agent(self._config, self._entrypoint, list(args))                                                                                                   │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper      │
    return f(*args, **kwargs)                                                                                                                                         │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 238, in launch_agent                            │
    result = agent.run()                                                                                                                                              │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper                          │
    result = f(*args, **kwargs)                                                                                                                                       │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 700, in run                         │
    result = self._invoke_run(role)                                                                                                                                   │
  File "/home/guozebin/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 828, in _invoke_run                 │
    time.sleep(monitor_interval)                                                                                                                                      │
KeyboardInterrupt      

    **I think it should be the problem of initialization, but I don’t know how to solve it**

**Comment by hhaAndroid** [comment]
@Bin-ze Please make sure that the distributed start command is correct and please use the issue template.
