### ISSUE TITLE
How to get the area of gt_bbox when training?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [open-mmlab/mmdetection#5905]
I need to get the 'area' of gt_bbox when training.  But I find that mmdetection doesn't load area of gt_bbox in loading.py. So I try to    
 load it by myself.  In coco.py, I change the function _parse_ann_info:
```python
gt_areas = []
for i, ann in enumerate(ann_info):
  gt_areas.append(ann['area'])
  gt_areas = np.array(gt_areas, dtype=np.float32)
ann = dict(
            bboxes=gt_bboxes,
            labels=gt_labels,
            bboxes_ignore=gt_bboxes_ignore,
            masks=gt_masks_ann,
            seg_map=seg_map,
            areas=gt_areas
            )
```
Besides, in loading.py, I change the function _load_bboxes:
```python
results['gt_areas'] = ann_info['areas'].copy()
```
Then I get the error:
```python
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/gpfs/home/sist/tqzouustc/code/mmdetection/mmdet/apis/train.py", line 73, in train_detector
    for i, data in enumerate(train_dataloader):
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/sist/tqzouustc/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/home/sist/tqzouustc/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/home/sist/tqzouustc/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/sist/tqzouustc/.local/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [17] at entry 0 and [4] at entry 1
```
What caused the problem? And is there other simple way to achieve my goal?

**Comment by Icecream-blue-sky** [comment]
And in coco_detection.py, I change the train_pipeline:
```python
dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_areas'])
```

**Comment by hhaAndroid** [comment]
@Icecream-blue-sky  gt_areas needs to be packaged by datacontainer, otherwise, it cannot collect.

**Comment by Icecream-blue-sky** [comment]
> @Icecream-blue-sky gt_areas needs to be packaged by datacontainer, otherwise, it cannot collect.

Thanks, I'll try.
