### ISSUE TITLE
AttributeError: 'DeformableDETRHead' object has no attribute 'input_proj'

### ISSUE THREAD

**Issue by HarmitMinhas96** [open-mmlab/mmdetection#5950]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
When trying to export a model trained by this config https://github.com/open-mmlab/mmdetection/blob/master/configs/deformable_detr/deformable_detr_twostage_refine_r50_16x2_50e_coco.py using this script https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py, the following exception is thrown: `AttributeError: 'DeformableDETRHead' object has no attribute 'input_proj'`

**Error traceback**

```Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 308, in <module>
    dynamic_export=args.dynamic_export)
  File "tools/deployment/pytorch2onnx.py", line 78, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/opt/conda/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 168, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "/mmdetection/mmdet/models/detectors/detr.py", line 62, in onnx_export
    outs = self.bbox_head.forward_onnx(x, img_metas)
  File "/mmdetection/mmdet/models/dense_heads/detr_head.py", line 732, in forward_onnx
    return multi_apply(self.forward_single_onnx, feats, img_metas_list)
  File "/mmdetection/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mmdetection/mmdet/models/dense_heads/detr_head.py", line 761, in forward_single_onnx
    x = self.input_proj(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'DeformableDETRHead' object has no attribute 'input_proj'
```

**Bug fix**
The issue seems to be because the `DeformableDETRHead` class overrides the `_init_layers` method of the parent class `DETRHead`, so when calling super().__init__(), self.input_proj isn't defined since the subclass doesn't define it.

**Comment by prosperopapaleo** [comment]
> DeformableDETR does not support onnx export yet.

Hi, is there anything new about the export support? 

thanks in advance.

**Comment by RunningLeon** [comment]
> > DeformableDETR does not support onnx export yet.
> 
> Hi, is there anything new about the export support?
> 
> thanks in advance.

@prosperopapaleo Hi, still no. BTW, this model is too heavy. Wonder why you deploy this model in real production.

**Comment by prosperopapaleo** [comment]
@RangiLyu may I ask if it will be supported in the long run?

> > > DeformableDETR does not support onnx export yet.
> > 
> > 
> > Hi, is there anything new about the export support?
> > thanks in advance.

**Comment by qingwan7** [comment]
@RangiLyu  Please, Can you have a try ?
