### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'nms'

### ISSUE THREAD

**Issue by 7425362** [open-mmlab/mmdetection#5954]
Traceback (most recent call last):
File "", line 1, in
File "E:\users\PyCharm 2021.2\plugins\python\helpers\pydev_pydev_bundle\pydev_umd.py", line 198, in runfile
pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
File "E:\users\PyCharm 2021.2\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "E:/python/adversarial object detection/GPAttack/attack.py", line 337, in
success_attack = specific_attack(model_helpers, img_path, mask, save_image_dir)
File "E:/python/adversarial object detection/GPAttack/attack.py", line 268, in specific_attack
res = loop.run_until_complete(asyncio.gather(*tasks))
File "E:\users\anaconda3\envs\mmdt\lib\asyncio\base_events.py", line 587, in run_until_complete
return future.result()
File "E:/python/adversarial object detection/GPAttack/attack.py", line 228, in get_attack_loss
al, on = await helper.attack_loss(img)
File "E:\python\adversarial object detection\GPAttack\faster_helper.py", line 140, in attack_loss
scores = self.get_detector_cls_sorces(img, self.img_metas)
File "E:\python\adversarial object detection\GPAttack\faster_helper.py", line 125, in get_detector_cls_sorces
proposal_list = self.model.rpn_head.simple_test_rpn(x, img_metas)
File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\dense_test_mixins.py", line 124, in simple_test_rpn
proposal_list = self.get_bboxes(*rpn_outs, img_metas)
File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
return old_func(*args, **kwargs)
File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 130, in get_bboxes
scale_factor, cfg, rescale)
File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmdet\models\dense_heads\rpn_head.py", line 220, in _get_bboxes_single
dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
File "E:\users\anaconda3\envs\mmdt\lib\site-packages\mmcv\utils\config.py", line 48, in getattr
raise ex
AttributeError: 'ConfigDict' object has no attribute 'nms'

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question.

**Comment by neel04** [comment]
@jshilong I have the same problem which occurs only after an epoch in Val/checkpointing. Any ideas how to solve it?

**Comment by jonguo111** [comment]
> Same issue here - can be fixed by installing an older version of mmdet. Seems like something broke when they updated. Could we please get this fixed?

how to install the older version of mmdet?

**Comment by Xielihao** [comment]
> Same issue here - can be fixed by installing an older version of mmdet. Seems like something broke when they updated. Could we please get this fixed?

which version is useful?

**Comment by SYSU-CSP** [comment]
please repalce the config file. For example, I use the mask_rcnn_r50_fpn.py, but it's too higher version to occure this error, I replace a lower version mask_rcnn_r50_fpn.py. Finally problem solved, Hope it helps you, thanks.

**Comment by zyakmd** [comment]
Ensure that the file in your model definition
train_cfg=dict ( rpn_proposal=dict(...) )
and
test_cfg = dict( rpn=dict(...) rpn=dict(...) )
have
nms=dict (type='nms', iou_threshold=..)
which can be find in the source code, like https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/cascade_rcnn_r50_fpn.py , in the penultimate line

**Comment by DaniaALkhadraa** [comment]
I have the same problem. any suggestion?


`File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/apis/inference.py", line 157, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py", line 179, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/dense_heads/dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 102, in get_bboxes
    results = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 185, in _get_bboxes_single
    return self._bbox_post_process(mlvl_scores, mlvl_bbox_preds,
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 231, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "/Users/daniaalkhadraa/miniforge3/envs/pedant-ml/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'nms'`
