### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by Mactarvish** [open-mmlab/mmdetection#5968]
I'm training a Cascade RCNN using mmdet 2.0, but after 3000 iters I got such error:

```
2021-08-30 00:53:10,508 - mmdet - INFO - Epoch [1][3000/4796]   lr: 0.00200, eta: 2 days, 15:57:30, time: 1.914, data_time: 0.529, memory: 29272, loss_rpn_cls: 0.0858, loss_rpn_bbox: 0.0754, s0.loss_cls: 0.6329, s0.acc: 80.7804, s0.loss_bbox: 0.2457, s0.loss_mask: 0.3179, s1.loss_cls: 0.3352, s1.acc: 78.5220, s1.loss_bbox: 0.2506, s1.loss_mask: 0.1529, s2.loss_cls: 0.1677, s2.acc: 80.6841, s2.loss_bbox: 0.1237, s2.loss_mask: 0.0698, loss: 2.4576
2021-08-30 00:54:45,441 - mmdet - INFO - Epoch [1][3050/4796]   lr: 0.00200, eta: 2 days, 15:51:02, time: 1.899, data_time: 0.503, memory: 29272, loss_rpn_cls: 0.0815, loss_rpn_bbox: 0.0734, s0.loss_cls: 0.6333, s0.acc: 80.4203, s0.loss_bbox: 0.2536, s0.loss_mask: 0.3176, s1.loss_cls: 0.3320, s1.acc: 78.2193, s1.loss_bbox: 0.2572, s1.loss_mask: 0.1527, s2.loss_cls: 0.1644, s2.acc: 80.4639, s2.loss_bbox: 0.1287, s2.loss_mask: 0.0699, loss: 2.4644
2021-08-30 00:56:33,999 - mmdet - INFO - Epoch [1][3100/4796]   lr: 0.00200, eta: 2 days, 15:52:56, time: 2.171, data_time: 0.557, memory: 29272, loss_rpn_cls: 0.0851, loss_rpn_bbox: 0.0760, s0.loss_cls: 0.6396, s0.acc: 80.6315, s0.loss_bbox: 0.2481, s0.loss_mask: 0.3193, s1.loss_cls: 0.3345, s1.acc: 78.2621, s1.loss_bbox: 0.2521, s1.loss_mask: 0.1525, s2.loss_cls: 0.1640, s2.acc: 80.5509, s2.loss_bbox: 0.1238, s2.loss_mask: 0.0693, loss: 2.4642
Traceback (most recent call last):
  File "/home/work/.conda/envs/co/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/home/work/.conda/envs/co/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/work/.conda/envs/co/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

How to solve it ?

**Comment by ZwwWayne** [comment]
It seems the code got error when packaging something for multiprocess. Could you follow the issue template to describe the detail environments, running commands, etc?
