### ISSUE TITLE
Issue when training YOLACT with val step in the workflow

### ISSUE THREAD

**Issue by AgatheMo** [open-mmlab/mmdetection#5978]
Hi, I ran into an issue when trying to train YOLACT with a workflow including a val step : `workflow = [('train',1),('val',1)]`
The code works fine when the workflow contains the training step only : `workflow = [('train',1)]`
The issue happens during the first val step, after the first training epoch is executed. 
The error traceback is:
```
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/local/user/yolact_mm/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/local/user/yolact_mm/mmcv-1.3.8/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/localscratch/user/yolact_mm/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/local/user/yolact_mm/mmcv-1.3.8/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/local/user/yolact_mm/mmcv-1.3.8/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/local/user/yolact_mm/mmcv-1.3.8/mmcv/parallel/data_parallel.py", line 89, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/local/user/yolact_mm/mmdetection/mmdet/models/detectors/base.py", line 252, in val_step
    losses = self(**data)
  File "/localscratch/user/yolact_mm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local/user/yolact_mm/mmcv-1.3.8/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/local/user/yolact_mm/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/local/user/yolact_mm/mmdetection/mmdet/models/detectors/yolact.py", line 80, in forward_train
    sampling_results)
  File "/localscratch/user/yolact_mm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/local/user/yolact_mm/mmdetection/mmdet/models/dense_heads/yolact_head.py", line 722, in forward
    mask_pred = cur_prototypes @ cur_coeff_pred.t()
RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D
```
My environment is :
```
sys.platform: linux
Python: 3.7.4 (default, Jul 18 2019, 19:34:02) [GCC 5.4.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-12GB
CUDA_HOME: /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/cudacore/10.1.243
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (20190410 gcc-8-branch revision 270244) 8.3.0
PyTorch: 1.7.1+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.2 Product Build 20190118 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu101
OpenCV: 4.1.2
MMCV: 1.3.8
MMCV Compiler: GCC 8.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0+
```
I think #5362 ran into the same issue.

**Comment by hhaAndroid** [comment]
@AgatheMo Currently it is recommended to use `evalhook` instead of `val workflow`, but I will check the problem.
