### ISSUE TITLE
Yolact Training: bbox_loss becomes NaN or Infinite

### ISSUE THREAD

**Issue by skaldesh** [open-mmlab/mmdetection#5985]
**Describe the bug**
During training of Yolact, a CUDA device-side assert fails, apparently related to the loss of bbox becoming NaN or Infinite

**Reproduction**

1. What command or script did you run?

```none
./tools/dist_train.sh \
                        /mmdetection/data/my_yolact_config.py \
                        2 \
                        --work-dir=/mmdetection/data/weights
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I modified the config to fine-tune the Yolact model. Here is my config:

```python
_base_ = [
    '../configs/yolact/yolact_r50_1x8_coco.py'
]

# 0. general settings
#load_from = "https://openmmlab.oss-cn-hangzhou.aliyuncs.com/mmdetection/v2.0/yolact/yolact_r50_1x8_coco_20200908-f38d58df.pth"

# 1. dataset settings
dataset_type = 'CocoDataset'
classes = ('Baumstamm',)
data_root = '/mmdetection/data/dataset/'
img_norm_cfg = dict(mean=[123.68, 116.78, 103.94], std=[58.40, 57.12, 57.38], to_rgb=True)
img_size = 550

train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(4.0, 4.0)),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=img_norm_cfg['mean'],
        to_rgb=img_norm_cfg['to_rgb'],
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(img_size, img_size), keep_ratio=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(img_size, img_size),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

# Use RepeatDataset to speed up training
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=4,
    train=dict(
        type='RepeatDataset',
        times=3,
        classes=classes,
        dataset=dict(
            type=dataset_type,
            classes=classes,
            ann_file=data_root + 'coco.json',
            img_prefix=data_root,
            pipeline=train_pipeline
        )
    ),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline
    ),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'coco.json',
        img_prefix=data_root,
        pipeline=test_pipeline
    )
)

# 2. model settings

# explicitly over-write all the `num_classes` field from default 80 to your classes.
model = dict(
    bbox_head=dict(
        type='YOLACTHead',
        num_classes=len(classes)
    ),
    mask_head=dict(
        type='YOLACTProtonet',
        num_classes=len(classes)
    ),
    segm_head=dict(
        type='YOLACTSegmHead',
        num_classes=len(classes)
    )
) 

# 3. optimizer
# lr is set for a batch size of 8
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.1,
    step=[7]
)
# the max_epochs and step in lr_config need specifically tuned for the customized dataset
evaluation = dict(interval=2, metric=['bbox', 'segm'])
runner = dict(max_epochs=20)
log_config = dict(interval=100)

```

3. What dataset did you use?
My custom dataset, which I successfully used to train a Mask-RCNN. It has only 2 classes.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

I am using the (unmodified) Docker Container of this repo, so my Pytorch version is 1.6 for example.

**Error traceback**
If applicable, paste the error trackback here.

```none
2021-08-31 07:21:58,662 - mmdet - INFO - Epoch(val) [2][635]    bbox_mAP: 0.4150, bbox_mAP_50: 0.8940, bbox_mAP_75: 0.3120, bbox_mAP_s: 0.1010, bbox_mAP_m: 0.3000, bbox_mAP_l: 0.4220, bbox_mAP_copypaste: 0.415 0.894 0.312 0.101 0.300 0.422, segm_mAP: 0.4740, segm_mAP_50: 0.7880, segm_mAP_75: 0.4730, segm_mAP_s: 0.0060, segm_mAP_m: 0.3620, segm_mAP_l: 0.4840, segm_mAP_copypaste: 0.474 0.788 0.473 0.006 0.362 0.484
/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/mmdetection/mmdet/core/anchor/anchor_generator.py:323: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/mmdetection/mmdet/core/anchor/anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
2021-08-31 07:23:31,001 - mmdet - INFO - Epoch [3][100/161]     lr: 8.578e-03, eta: 0:31:09, time: 0.923, data_time: 0.322, memory: 9324, loss_cls: 1.2368, loss_bbox: 1.3766, loss_segm: 0.0438, loss_mask: 1.6699, loss: 4.3270
2021-08-31 07:24:14,945 - mmdet - INFO - Saving checkpoint at 3 epochs
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [99,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [1,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [2,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [3,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [4,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [5,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [6,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [7,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [8,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [9,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [10,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [11,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [12,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [13,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [14,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [15,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [16,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [17,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [18,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [19,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [20,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [21,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [22,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [23,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [24,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [25,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [26,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [27,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [28,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [29,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [30,0,0] Assertion `input_val >= zero && input_val <= one` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/Loss.cu:106: operator(): block: [101,0,0], thread: [31,0,0] Assertion `input_val >= zero && input_val <= one` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/yolact.py", line 87, in forward_train
    assert torch.isfinite(torch.stack(losses[loss_name]))\
RuntimeError: CUDA error: device-side assert triggered
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
terminate called after throwing an instance of 'c10::Error'
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/yolact.py", line 89, in forward_train
    .format(loss_name)
AssertionError: loss_bbox becomes infinite or NaN!
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f16ace0477d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x7f16ad054d9d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f16acdf0b1d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x53f0ea (0x7f16e66870ea in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x1a311e (0x5595b322e11e in /opt/conda/bin/python)
frame #5: <unknown function> + 0x10e91c (0x5595b319991c in /opt/conda/bin/python)
frame #6: <unknown function> + 0x10ea77 (0x5595b3199a77 in /opt/conda/bin/python)
frame #7: <unknown function> + 0x10ea77 (0x5595b3199a77 in /opt/conda/bin/python)
frame #8: <unknown function> + 0xfdfc8 (0x5595b3188fc8 in /opt/conda/bin/python)
frame #9: <unknown function> + 0x10f147 (0x5595b319a147 in /opt/conda/bin/python)
frame #10: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #11: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #12: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #13: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #14: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #15: <unknown function> + 0x10f15d (0x5595b319a15d in /opt/conda/bin/python)
frame #16: PyDict_SetItem + 0x502 (0x5595b31ef172 in /opt/conda/bin/python)
frame #17: PyDict_SetItemString + 0x4f (0x5595b31efc4f in /opt/conda/bin/python)
frame #18: PyImport_Cleanup + 0xa0 (0x5595b3234760 in /opt/conda/bin/python)
frame #19: Py_FinalizeEx + 0x67 (0x5595b32af817 in /opt/conda/bin/python)
frame #20: <unknown function> + 0x2373d3 (0x5595b32c23d3 in /opt/conda/bin/python)
frame #21: _Py_UnixMain + 0x3c (0x5595b32c26fc in /opt/conda/bin/python)
frame #22: __libc_start_main + 0xe7 (0x7f1708a37b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #23: <unknown function> + 0x1dc3c0 (0x5595b32673c0 in /opt/conda/bin/python)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=1', '/mmdetection/data/my_yolact_config.py', '--launcher', 'pytorch', '--work-dir=/mmdetection/data/weights']' died with <Signals.SIGABRT: 6>.
```

**Comment by hhaAndroid** [comment]
@skaldesh  This means that your class length is 1, but your gt_label is greater than 1.

**Comment by skaldesh** [comment]
Ahh you are right, my bad. Thanks for the help!
