### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn'

### ISSUE THREAD

**Issue by 237014845** [open-mmlab/mmdetection#601]
uge@zhuge-All-Series:~/hs/MobilenetV2-Retina-Pytorch-master/tools$ python train.py  '/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/configs/pascal_voc/shuffle_retina_voc.py'  --work_dir '/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/weights/shuffle_retina/1.0/640'  --seed 1314
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from mmdet.datasets import get_dataset
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformRoIPooling, DeformRoIPoolingPack,
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from .. import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/zhuge/hs/MobilenetV2-Retina-Pytorch-master/mmdet/ops/dcn/__init__.py)

**Comment by 237014845** [comment]
I forgot to run ./compile. Sh.

**Comment by Siggi1988** [comment]
Hallo 237014845 i have the same problem. 
Where i must run ./compile. Sh.?

**Comment by FilipLangr** [comment]
> Hallo 237014845 i have the same problem.
> Where i must run ./compile. Sh.?

Try running `python3 setup.py install` in the project root directory.

**Comment by ash11sh** [comment]
> @ash11sh Where can I get pytorch-0.4.1 version mmdetection?

I mean here two versions of pytorch had different installation setup

**Comment by SamMohel** [comment]
did someone solve it ?
