### ISSUE TITLE
SSD evaluation problem : ZeroDivisionError: division by zero because of indices 0

### ISSUE THREAD

**Issue by Abeni18** [open-mmlab/mmdetection#6024]
Training SSD works fine for the first epoch then when it gets to the evaluation stage it throws an error. I have trained the same dataset successfully on different methods like faster-RCNN. 

These is the error logs :

Traceback (most recent call last):
  File "./test.py", line 238, in <module>
    main()
  File "./test.py", line 211, in main
    args.gpu_collect)
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/apis/test.py", line 96, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/datasets/samplers/distributed_sampler.py", line 35, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 13244) is killed by signal: Terminated.
indices 0

Any help appreciated  👍

**Comment by Abeni18** [comment]
Similar problem with cascadeRCNN

0172, s1.loss_cls: 0.0121, s1.acc: 99.0501, s1.loss_bbox: 0.0278, s2.loss_cls: 0.0078, s2.acc: 98.6437, s2.loss_bbox: 0.0183, loss: 0.1071
2021-09-02 18:03:12,474 - mmdet - INFO - Saving checkpoint at 1 epochs
completed: 0, elapsed: 0sindices 0
Traceback (most recent call last):
  File "./../tools/train.py", line 189, in <module>
    main()
  File "./../tools/train.py", line 185, in main
    meta=meta)
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 237, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/core/evaluation/eval_hooks.py", line 54, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/apis/test.py", line 96, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/abenezerg/mmcv_det/2mmdetection/mmdet/datasets/samplers/distributed_sampler.py", line 35, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/abenezerg/anaconda3/envs/mmcv/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 2047) is killed by signal: Terminated.
indices 0

**Comment by jshilong** [comment]
Please double-check your information. This error should be model agnostic so Faster-RCNN looking well is not reasonable  According to the error message, please check your validation dataset, because len(indices) should be equal to len(dataset), which is zero in your implementaion.

**Comment by jshilong** [comment]
Feel free to reopen the issue if there is any question
