### ISSUE TITLE
Recursion Error upon loading Config file

### ISSUE THREAD

**Issue by neel04** [open-mmlab/mmdetection#6037]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
It seems that I am unable to load the `Config` file for a specific model I want to use - it errors out about missing `/tmp/...py` 

OG bug report at #5949

**Reproduction**

1. What command or script did you run?

Kaggle Reproducer (CPU):-
```py
!mkdir checkpoints
!wget -c https://github.com/CBNetwork/storage/releases/download/v1.0.0/htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth.zip -O ./chkp.zip
!unzip ./chkp.zip -d -o ./checkpoints/
!wget "https://raw.githubusercontent.com/VDIGPKU/CBNetV2/main/configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py" -O ./mmdetection/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py

!cd ./mmdetection; pip install -v -e .

# ---------------------------- [NEW CELL SHOULD BE USED] -----------------------------------
%%writefile ./mmdetection/new_config.py
# The new config inherits a base config to highlight the necessary modification
_base_ = '/kaggle/working/mmdetection/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=3)))

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('a','b', 'c')
data = dict(
    train=dict(
        img_prefix='/kaggle/working/asd.txt',
        classes=classes,
        ann_file='/kaggle/working/train_coco/jsa.json'),
    val=dict(
        img_prefix='/kaggle/working/v_coco/',
        classes=classes,
        ann_file='/kaggle/working/val_coco/labels.json'),
    test=dict(
        img_prefix='/kaggle/working/v_coco/',
        classes=classes,
        ann_file='/kaggle/working/v_coco/labels.json'))

load_from = '/kaggle/working/checkpoints/htc_cbv2_swin_base22k_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.pth'

# optimizer
# lr is set for a batch size of 8
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

# the max_epochs and step in lr_config need specifically tuned for the customized dataset
runner = dict(max_epochs=8)
log_config = dict(interval=100)
# ---------------------------- [NEW CELL SHOULD BE USED] -----------------------------------

# the max_epochs and step in lr_config need specifically tuned for the customized dataset
runner = dict(max_epochs=8)
log_config = dict(interval=100)

!python3 ./mmdetection/tools/train.py  "/kaggle/working/mmdetection/new_config.py" --work-dir='/kaggle/working' --launcher="pytorch"
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? `Just printing args`

```py
Namespace(cfg_options=None, config='./mmdetection/new_config.py', deterministic=True, gpu_ids=None, gpus=1, launcher='pytorch', local_rank=0, no_validate=True, options=None, resume_from=None, seed=42, work_dir='./')
```
`config` is detected, and everything seems ok

I am using this I am using [model](https://github.com/VDIGPKU/CBNetV2/blob/main/configs/cbnet/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_giou_4conv1f_adamw_20e_coco.py) 

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```py
sys.platform: linux
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0]
CUDA available: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.4.0
MMCV: 1.3.12
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: not available
MMDetection: 2.16.0+003f520
```

**Error traceback**
If applicable, paste the error trackback here.

```py
Traceback (most recent call last):
  File "./mmdetection/tools/train.py", line 191, in <module>
    main()
  File "./mmdetection/tools/train.py", line 92, in main
    cfg = Config.fromfile(args.config)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 330, in fromfile
    use_predefined_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  [Previous line repeated 979 more times]
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 872, in get_code
  File "<frozen importlib._bootstrap_external>", line 959, in _cache_bytecode
  File "<frozen importlib._bootstrap_external>", line 984, in set_data
  File "<frozen importlib._bootstrap_external>", line 117, in _write_atomic
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7fcfb72a3320>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw_uy3mwm/tmpgxwqyh2q.py'
```

**Comment by shinya7y** [comment]
> Kaggle Reproducer (CPU):-

> MMCV CUDA Compiler: not available

Is mmcv-full correctly installed for GPU?

**Comment by jshilong** [comment]
Seems there are some problems in your config, you can merge the `_base_` by yourself then you may find the problem

**Comment by shinya7y** [comment]
> !cd ./mmdetection; pip install -v -e .

If this `mmdetection` is `open-mmlab/mmdetection`, there is no code for CBNetV2.
Copying the checkpoint and config is not enough.

> %%writefile ./mmdetection/new_config.py
> _base_ = '/kaggle/working/mmdetection/htc_cbv2_swin_base_patch4_window7_mstrain_400-1400_adamw_20e_coco.py'

It is better to place the config files under `configs/cbnet/` not to break the relative import of `configs/_base_` configs.

> model = dict(
>     roi_head=dict(
>         bbox_head=dict(num_classes=3)))

This change will not work for Cascade R-CNN and HTC.

**Comment by neel04** [comment]
@shinya7y trying to get CPU to work first (at least a single step) before using my GPU quota.

Ahh, so the linked models won't work simply because they aren't yet released by open-mmlab's framework? Then why does the CBNetV2 repo direct us here? :( 
And what do you think is the SOTA for object detection offered here? :hugs: 

Thanks a ton everyone for such a quick response, I really appreciate it!!! :cake:

**Comment by shinya7y** [comment]
Swin Transformer-based detectors achieve SOTA accuracy, but are still impractical for practitioners without high-memory GPUs.
YOLOX is a possible choice because it has SOTA speed/accuracy trade-offs.

I recommend studying the usage of mmdetection with basic methods (e.g., ATSS, Faster R-CNN) before trying recent methods.

**Comment by neel04** [comment]
sure, will keep in mind. Thanks a lot :+1:

**Comment by shinya7y** [comment]
I think supporting TPUs requires tons of work.
Please close this issue.

**Comment by neel04** [comment]
Haha, one of the curses of being based on Pytorch :smiley: Still, great repo and thanks a lot for your time!
