### ISSUE TITLE
MultiImageMixDataset中使用mosaic，混合数据集输入报错

### ISSUE THREAD

**Issue by zhanghang-cv** [open-mmlab/mmdetection#6055]
```
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=2,
    train=dict(
        type='MultiImageMixDataset',
        dataset=[dict(
            type='CocoDataset',
            ann_file = '/root/dataset/terror_train/huawei/coco_anno1.json',
            img_prefix = '/root/dataset/terror_train/huawei/images',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True)
            ],
            filter_empty_gt=False),
            dict(
            type='CocoDataset',
            ann_file = '/root/dataset/terror_train/huawei/coco_anno2.json',
            img_prefix = '/root/dataset/terror_train/huawei/images',
            pipeline=[
                dict(type='LoadImageFromFile', to_float32=True),
                dict(type='LoadAnnotations', with_bbox=True)
            ],
            filter_empty_gt=False)],
        pipeline=[
            dict(type='Mosaic', img_scale=(640, 640), pad_val=114.0),
            dict(
                type='RandomAffine',
                scaling_ratio_range=(0.1, 2),
                border=(-320, -320)),
            dict(
                type='MixUp',
                img_scale=(640, 640),
                ratio_range=(0.8, 1.6),
                pad_val=114.0),
            dict(
                type='PhotoMetricDistortion',
                brightness_delta=32,
                contrast_range=(0.5, 1.5),
                saturation_range=(0.5, 1.5),
                hue_delta=18),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='Resize', keep_ratio=True),
            dict(type='Pad', pad_to_square=True, pad_val=114.0),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        dynamic_scale=(640, 640)),
    val=dict(
        type='CocoDataset',
        ann_file = '/root/dataset/terror_train/huawei/coco_anno1.json',
        img_prefix = '/root/dataset/terror_train/huawei/images',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(type='Pad', size=(640, 640), pad_val=114.0),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file = '/root/dataset/terror_train/huawei/coco_anno1.json',
        img_prefix = '/root/dataset/terror_train/huawei/images',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(type='Pad', size=(640, 640), pad_val=114.0),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
```
MultiImageMixDataset中输入两个数据集，调用mosaic数据数据增强报错
```
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/environment/anaconda3/envs/mmdet2.16/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/environment/anaconda3/envs/mmdet2.16/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/environment/anaconda3/envs/mmdet2.16/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/factory/mmdetection2.16/mmdet2.16/mmdet/datasets/dataset_wrappers.py", line 354, in __getitem__
    indexes = transform.get_indexes(self.dataset)
  File "/root/factory/mmdetection2.16/mmdet2.16/mmdet/datasets/pipelines/transforms.py", line 2254, in get_indexes
    gt_bboxes_i = dataset.get_ann_info(index)['bboxes']
AttributeError: 'ConcatDataset' object has no attribute 'get_ann_info'
```
我看了源码，混合数据集要调用ConcatDataset，但是mosaic中调用get_ann_info函数，但是ConcatDataset没有该函数。
如果只输入一个coco数据集可以正常调用coco数据集中的get_ann_info函数。所以MultiImageMixDataset中使用mosaic不支持混合数据集输入吗？或者怎么在MultiImageMixDataset中使用混合数据集输入。

**Comment by lamia482** [comment]
This is because of the transform: `MixUp`;
This class has a method called `get_indexes`, which will load the ann_info and try to filter index with empty annotations, so disable the check will work for you, 
or comment this transform, 
or implement a `get_ann_info` for `ConcatDataset`

implementation of MixUp.get_indexes in mmdet/datasets/pipelines/transforms.py
```
def get_indexes(self, dataset):
  for i in range(self.max_iters):
  index = random.randint(0, len(dataset))
  gt_bboxes_i = dataset.get_ann_info(index)['bboxes']
  if len(gt_bboxes_i) != 0:
    break
  return index
```
