### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'items'

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection#6061]
When I train RetinaNet, something wrong happened:
```
Traceback (most recent call last):
  File "tools/train.py", line 174, in <module>
    main()
  File "tools/train.py", line 170, in main
    meta=meta)
  File "/mnt/lustre/wangsen1/objectflow2/mmdetection/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/lustre/wangsen1/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/lustre/wangsen1/.local/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/mnt/lustre/wangsen1/.local/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/lustre/wangsen1/objectflow2/mmdetection/mmdet/models/detectors/base.py", line 235, in train_step
    loss, log_vars = self._parse_losses(losses)
  File "/mnt/lustre/wangsen1/objectflow2/mmdetection/mmdet/models/detectors/base.py", line 185, in _parse_losses
    for loss_name, loss_value in losses.items():
AttributeError: 'tuple' object has no attribute 'items'
```
Do you have any suggestions?

**Comment by SagiAbd** [comment]
did you solve it?
