### ISSUE TITLE
RuntimeError: target.max().item<int64_t>() <= (int64_t)

### ISSUE THREAD

**Issue by huimlight** [open-mmlab/mmdetection#6070]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
https://github.com/open-mmlab/mmdetection/issues/5801.  The question was raised earlier.

 RuntimeError: target.max().item<int64_t>() <= (int64_t)num_classes INTERNAL ASSERT FAILED at "/tmp/pip-install-rnu39oc3/mmcv-full_c3244ef0af18442e9c75bebe181bc703/mmcv/ops/csrc/pytorch/cuda/focal_loss_cuda.cu":13, please report a bug to PyTorch. target label should smaller or equal than num classes

**Reproduction**

1. What command or script did you run?
CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=3 python tools/train.py configs/retinanet/retinanet_r50_fpn_1x_coco.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?

no.

3. What dataset did you use?

coco

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080 Ti
CUDA_HOME: /disk1/huim/softwares/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1
OpenCV: 4.5.3
MMCV: 1.3.12
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.16.0+db85fd1

**Error traceback**
Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 185, in main
    meta=meta)
  File "/disk1/huim/projects/mmdetection/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/disk1/huim/projects/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/disk1/huim/projects/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/disk1/huim/projects/mmdetection/mmdet/models/detectors/single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/disk1/huim/projects/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 55, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/disk1/huim/projects/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 490, in loss
    num_total_samples=num_total_samples)
  File "/disk1/huim/projects/mmdetection/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/disk1/huim/projects/mmdetection/mmdet/models/dense_heads/anchor_head.py", line 405, in loss_single
    cls_score, labels, label_weights, avg_factor=num_total_samples)
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/disk1/huim/projects/mmdetection/mmdet/models/losses/focal_loss.py", line 178, in forward
    avg_factor=avg_factor)
  File "/disk1/huim/projects/mmdetection/mmdet/models/losses/focal_loss.py", line 87, in sigmoid_focal_loss
    alpha, None, 'none')
  File "/disk1/huim/softwares/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/focal_loss.py", line 56, in forward
    input, target, weight, output, gamma=ctx.gamma, alpha=ctx.alpha)
RuntimeError: target.max().item<int64_t>() <= (int64_t)num_classes INTERNAL ASSERT FAILED at "/tmp/pip-install-rnu39oc3/mmcv-full_c3244ef0af18442e9c75bebe181bc703/mmcv/ops/csrc/pytorch/cuda/focal_loss_cuda.cu":13, please report a bug to PyTorch. target label should smaller or equal than num classes

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by huimlight** [comment]
Through debugging, I found that the target of the classification would be greater than 81.

**Comment by huimlight** [comment]
![1](https://user-images.githubusercontent.com/88706946/132696140-6812923f-ce0c-4cbe-829b-7259070fe9c6.png)

**Comment by huimlight** [comment]
![2](https://user-images.githubusercontent.com/88706946/132697882-7a311713-8d1a-42fd-9d3e-aabc0abbf576.png)
The length of label weight is inconsistent with that of neg_inds

**Comment by RangiLyu** [comment]
What dataset did you use? COCO?

**Comment by huimlight** [comment]
> What dataset did you use? COCO?

yes，I ues coco dataset

**Comment by RangiLyu** [comment]
We tested recently but cannot reproduce this error. Feel free to reopen the issue if you can provide more detailed information.

**Comment by rlczddl** [comment]
same, how to fixed it?
