### ISSUE TITLE
About HTC training

### ISSUE THREAD

**Issue by xlzhang1992** [open-mmlab/mmdetection#609]
Does stuffthingmaps only have coco_stuff semantic map?  When I add semantic branch, there is an assertionError.

Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/home/amax/mmdetection/mmdet/apis/train.py", line 58, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/amax/mmdetection/mmdet/apis/train.py", line 99, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/runner/runner.py", line 258, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 63, in collate
    for key in batch[0]
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 63, in <dictcomp>
    for key in batch[0]
  File "/home/amax/anaconda3/envs/mmdetection/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 38, in collate
    assert batch[i].dim() == 3

If there is a mistake in my root (data/coco/stuffthingsmaps/...)?

**Comment by hellock** [comment]
Yes it is COCO-stuff annotation maps. You may downloaded the wrong dataset?

**Comment by iFighting** [comment]
I also meet this problem

**Comment by xlzhang1992** [comment]
> I also meet this problem
> I download the dataset from this url, and it's ok now.
> https://github.com/nightrome/cocostuff/blob/master/README.md#downloads
> @xlzhang1992

Thanks
