### ISSUE TITLE
Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by Adblu** [open-mmlab/mmdetection#6101]
I'm trying to run demo example on GPU card. Here is what I'm getting:

```
 UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/app/pycharm/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/app/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/adrian/Documents/CODE/mmdetection/test_on_image.py", line 21, in <module>
    model = init_detector(config, checkpoint, device='cuda:0')
  File "/home/adrian/Documents/CODE/mmdetection/mmdet/apis/inference.py", line 52, in init_detector
    model.to(device)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/adrian/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```
And yes, there is proper cuda installed:

```
python collect_env.py 
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce GTX 1050
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.16.0+3e7d7e4

```
also:

```
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py37h06a4308_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
matplotlib                3.4.3                    pypi_0    pypi
mmcv-full                 1.3.13                   pypi_0    pypi
mmdet                     2.16.0                    dev_0    <develop>
ncurses                   6.2                  he6710b0_1  
numpy                     1.21.2                   pypi_0    pypi
opencv-python             4.5.3.56                 pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0                     pypi_0    pypi
pillow                    8.3.2                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
pycocotools               2.0.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py37h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
terminaltables            3.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.9.0+cu111              pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
typing-extensions         3.10.0.2                 pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zlib                      1.2.11               h7b6447c_3 
```

also 2: 

```
print(torch.cuda.device_count()) -> 1
print(torch.cuda.is_available()) -> True
print(torch.version.cuda) -> 11.1 
```

What is wrong ?

**Comment by AronLin** [comment]
https://github.com/Deep-MI/FastSurfer/issues/39

Does your GPU model support the version of your GPU driver? Maybe you can go to NVIDIA to create an issue.

**Comment by Adblu** [comment]
@AronLin Yes it does. The most recent one available is 470.63.01 from 2021.8.10, however mine is 460.91.03.

**Comment by AronLin** [comment]
We do not know what happend.
I suggest you to create an issue in Pytorch or Nvidia.

**Comment by Adblu** [comment]
Problem solved. It turned out pycharm installed with flatpack dosnt read some variables. 
[link](https://stackoverflow.com/questions/65439154/pytorch-doesnt-work-with-cuda-in-pycharm-intellij)
