### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6141]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I'm trying to train a Mask-RCNN-r50 on a custom dataset of type `COCODataset` with 5 classes. The config file is very simple: the only differences from the base config `mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py`  are the number of classes and the usage of a custom dataset . Even so, the train fails with an `AttributeError`. 
**Reproduction**

Config file:

```python
# base config
_base_ = ['/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py']

# dataset settings
dataset_type = 'COCODataset'
data_root = 'data/coco/'
classes = ('a', 'b', 'c', 'f', 'e')
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='CocoDataset',
        ann_file=
        '/data/xxx/training_files/rotated_data/annotations/train.json',
        img_prefix=
        '/data/xxx/training_files/rotated_data/images/',
        classes=classes),
    val=dict(
        type='CocoDataset',
        ann_file=
        '/data/xxx/training_files/rotated_data/annotations/val.json',
        img_prefix=
        '/data/xxx/training_files/rotated_data/images/',
        classes=classes),
    test=dict(
        type='CocoDataset',
        ann_file=
        '/data/xxx/training_files/rotated_data/annotations/test.json',
        img_prefix=
        '/data/xxx/training_files/rotated_data/images/',
        classes=classes),
)

# model settings
n_classes = len(classes)
model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes)],
    mask_head=dict(num_classes=n_classes)))

work_dir = '/workspace/andrea/test_MMDet/logs/test'

```

1. What command or script did you run?

```bash
python /mmdetection/tools/train.py /workspace/andrea/test_MMDet/test.py
```

2. The only modifications I made to the config files were the use of a custom dataset, and the number of classes, as well as their labels.
3. I used a custom dataset  of type `COCODataset`.

**Environment**

1. The output of `python /mmdetection/mmdet/utils/collect_env.py` is
```bash
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.16.0+HEAD
```

2. You may add addition that may be helpful for locating the problem, such as
    - I didn't have to install PyTorch. I'm running in a Docker container, and the Dockerfile starts with
```bash
ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

```
  
Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

```
echo $PATH
/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo $LD_LIBRARY_PATH
/usr/local/nvidia/lib:/usr/local/nvidia/lib64
echo $PYTHONPATH

```
**Error traceback**

```python
Traceback (most recent call last):
  File "/mmdetection/tools/train.py", line 194, in <module>
    main()
  File "/mmdetection/tools/train.py", line 190, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 149, in forward_train
    **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 105, in forward_train
    img_metas)
  File "/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 134, in _bbox_forward_train
    bbox_results = self._bbox_forward(x, rois)
  File "/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 124, in _bbox_forward
    cls_score, bbox_pred = self.bbox_head(bbox_feats)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py", line 162, in forward
    x = x.flatten(1)
AttributeError: 'tuple' object has no attribute 'flatten'
```

**Bug fix**
I don't know what's causing the issue, but it's interesting to note that at runtime, execution goes through the function `convfc_bbox_head.py` twice. The first time, no error is raised, since `x` is a regular `torch.Tensor`, but the second time `x` is a tuple of 2 tensors, and at this point the code exits with error.

**Comment by AndreaPi** [comment]
Ok, my bad, the `AttributeError` was due to an error in the config file. For `mask_rcnn` on a custom dataset of type `CocoDataset`, **this** is the right way to set the number of classes:

```python
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=n_classes),
        mask_head=dict(num_classes=n_classes)))
```

**Comment by praj441** [comment]
> Ok, my bad, the `AttributeError` was due to an error in the config file. For a `mask_rcnn` model on a custom dataset of type `CocoDataset`, **this** is the right way to set the number of classes:
> 
> ```python
> model = dict(
>     roi_head=dict(
>         bbox_head=dict(num_classes=n_classes),
>         mask_head=dict(num_classes=n_classes)))
> ```

I am getting the same issue. I did set the correct num_classes. Still, getting the same issue.
File "mmdetection/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py", line 169, in forward
    x = x.flatten(1)
AttributeError: 'tuple' object has no attribute 'flatten'
