### ISSUE TITLE
<DATASET_NAME> is not in the dataset registry 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [open-mmlab/mmdetection#6149]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. -> checked with the search button, I found one similar [here](https://github.com/open-mmlab/mmdetection/issues/5800) but no real fix
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I followed the doc about [customize_dataset](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html) and I've created a custom dataset.

First I was forced to clone the repo because I need to store my dataset inside it.

**Is there a way to just install mmdet and add a dataseted to the registry without manually copy & paste the .py file inside it?**

```python

@DATASETS.register_module()
class DarwinDetectionDataset(CustomDataset):

    CLASSES = ("African Grey Parrot", "European Robin", "Nightingale")

    def convert_annotation(self, annotation_path: Path) -> Dict:
        print(annotation_path)
        with annotation_path.open("r") as f:
            data = json.load(f)
            image = data.pop("image")
            annotations = data.pop("annotations")

            targets = []
            for annotation in annotations:
                if "bounding_box" in annotation:
                    bbox = annotation["bounding_box"]
                    h = bbox["h"]
                    w = bbox["w"]
                    x = bbox["x"]
                    y = bbox["y"]
                    x2 = x + w
                    y2 = y + h
                    bbox = np.array([x, y, x2, y2])
                    label = np.array(self.CLASSES.index(annotation["name"].strip()))

                    ann = {"bbox": bbox, "label": label}

                    targets.append(ann)

            return dict(
                filename=image["filename"],
                width=image["width"],
                height=image["height"],
                ann=dict(
                    bboxes=np.stack([v["bbox"] for v in targets]),
                    labels=np.stack([v["label"] for v in targets]),
                ),
            )

    def load_annotations(self, ann_file):
        data_infos = []  # di dizionari

        with open(ann_file, "r") as f:
            annotations = [
                self.convert_annotation(ANNOTATIONS / f"{name.strip()}.json")
                for name in f.readlines()[:1]
            ]
            data_infos.append(annotations)
        pprint(data_infos)
        return data_infos

    def get_ann_info(self, idx):
        return self.data_infos[idx]["ann"]
```
Stored inside `mmdet/datasets/darwin_detection_dataset.py`. 

**Reproduction**

1. What command or script did you run?

`python tools/train -<MY_CONFIG_FILE>`

Error:

```
Traceback (most recent call last):
  File "/home/zuppif/integration-object-detection/mmdetection/train.py", line 189, in <module>
    main()
  File "/home/zuppif/integration-object-detection/mmdetection/train.py", line 165, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zuppif/integration-object-detection/mmdetection/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zuppif/integration-object-detection/.venv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'DarwinDetectionDataset is not in the dataset registry'
```

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

```
sys.platform: linux
Python: 3.9.5 (default, Jun  4 2021, 12:28:51) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29373293_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.1+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu102
OpenCV: 4.5.3
MMCV: 1.3.13
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.2
MMDetection: 2.16.0+fa10539
```
**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "/home/zuppif/integration-object-detection/mmdetection/train.py", line 189, in <module>
    main()
  File "/home/zuppif/integration-object-detection/mmdetection/train.py", line 165, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zuppif/integration-object-detection/mmdetection/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zuppif/integration-object-detection/.venv/lib/python3.9/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'DarwinDetectionDataset is not in the dataset registry'
```

Thanks!

Cheers,

Francesco

**Comment by FrancescoSaverioZuppichini** [comment]
[SOLVED] 

So, install mmdet with `pip` or whatever you like then:
- Create your `custom_dataset.py` following the [doc](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html).
- copy the `tools/train.py` file in your project 

The structure looks like 

```
.
├── config.py
├── custom_dataset.py
├── train.py
```

In `train.py` import your dataset

```python
# train.py
...
from custom_dataset import CustomDataset
...
```
Done! You can now run `train.py` with your custom dataset
