### ISSUE TITLE
Problem while loading yolox-tiny model parameters

### ISSUE THREAD

**Issue by reclusezz** [open-mmlab/mmdetection#6156]
The model and loaded state dict do not match exactly

unexpected key in source state_dict: ema_backbone_stem_conv_conv_weight, ema_backbone_stem_conv_bn_weight, ema_backbone_stem_conv_bn_bias, ema_backbone_stem_conv_bn_running_mean, ema_backbone_stem_conv_bn_running_var, ema_backbone_stem_conv_bn_num_batches_tracked, ema_backbone_stage1_0_conv_weight, ema_backbone_stage1_0_bn_weight, ema_backbone_stage1_0_bn_bias, ema_backbone_stage1_0_bn_running_mean, ema_backbone_stage1_0_bn_running_var, ema_backbone_stage1_0_bn_num_batches_tracked, ema_backbone_stage1_1_main_conv_conv_weight, ema_backbone_stage1_1_main_conv_bn_weight, ema_backbone_stage1_1_main_conv_bn_bias, ema_backbone_stage1_1_main_conv_bn_running_mean, ema_backbone_stage1_1_main_conv_bn_running_var, ema_backbone_stage1_1_main_conv_bn_num_batches_tracked, ema_backbone_stage1_1_short_conv_conv_weight, ema_backbone_stage1_1_short_conv_bn_weight, ema_backbone_stage1_1_short_conv_bn_bias, ema_backbone_stage1_1_short_conv_bn_running_mean, ema_backbone_stage1_1_short_conv_bn_running_var, ... ...

When I load trained yolox-tiny model during testing phase, I meet the problem. How to solve it and do it influence the result?

**Comment by BIGWangYuDong** [comment]
Hi, please use issue templet to give us more details

**Comment by hhaAndroid** [comment]
@reclusezz It does not matter, it is the ema model saved during training, you can ignore it or delete it manually.

**Comment by reclusezz** [comment]
Thx, another question. I replace the loss_obj with FocalLoss. Then I met the error shown as below. Do you have any idea how to solve it?

Traceback (most recent call last):
  File "/mypc/mmdetection-master/tools/train.py", line 190, in <module>
    main()
  File "/mypc/mmdetection-master/tools/train.py", line 186, in main
    meta=meta)
  File "/mypc/mmdetection-master/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/distributed.py", line 53, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mypc/mmdetection-master/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/mypc/mmdetection-master/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mypc/mmdetection-master/mmdet/models/detectors/single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/mypc/mmdetection-master/mmdet/models/dense_heads/base_dense_head.py", line 55, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/mypc/mmdetection-master/mmdet/models/dense_heads/yolox_head.py", line 392, in loss
    obj_targets) / num_total_samples
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mypc/mmdetection-master/mmdet/models/losses/focal_loss.py", line 178, in forward
    avg_factor=avg_factor)
  File "/mypc/mmdetection-master/mmdet/models/losses/focal_loss.py", line 87, in sigmoid_focal_loss
    alpha, None, 'none')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/ops/focal_loss.py", line 36, in forward
    assert isinstance(target, (torch.LongTensor, torch.cuda.LongTensor))
AssertionError

**Comment by reclusezz** [comment]
Also I found that if I replace the loss_obj with CIoULoss, the loss_obj  will be abnormal while training.

2021-09-24 09:33:31,595 - mmdet - INFO - Epoch [1][50/1802]     lr: 1.925e-06, eta: 1 day, 15:28:00, time: 6.586, data_time: 4.374, memory: 5520, loss_cls: 1.1192, loss_bbox: 0.0030, loss_obj: 10.1863, loss: 11.3086
2021-09-24 09:36:58,477 - mmdet - INFO - Epoch [1][100/1802]    lr: 7.699e-06, eta: 1 day, 8:03:24, time: 4.138, data_time: 0.341, memory: 5521, loss_cls: 1.1134, loss_bbox: 0.0031, loss_obj: 10.0663, loss: 11.1828

**Comment by hhaAndroid** [comment]
@reclusezz It may be that focal loss is not robust enough and needs to be improved.

**Comment by hhaAndroid** [comment]
@reclusezz loss_obj represents the objectness branch loss, theoretically you should not use CIoULoss.

**Comment by Monkey-D-Luffy-star** [comment]
@hhaAndroid  what is ema model? I meet the same issue.

**Comment by Caius-Lu** [comment]
> @hhaAndroid what is ema model? I meet the same issue during testing phase.

I also meet this problem.
