### ISSUE TITLE
When I executed test.py, this error occurred. Can you help me with this?

### ISSUE THREAD

**Issue by Kobeee0614** [open-mmlab/mmdetection#618]
When I executed test.py, this error occurred. Can you help me with this?
![2019-05-10 10-15-14屏幕截图](https://user-images.githubusercontent.com/23253981/57498020-ad8cd300-730c-11e9-96ee-34657c4ddd63.png)

**Comment by Kobeee0614** [comment]
`Traceback (most recent call last):
  File "tools/test.py", line 117, in <module>
    main()
  File "tools/test.py", line 106, in main
    coco_eval(result_file, eval_types, dataset.coco)
  File "/home/jason/notebook/mmdetection/mmdet/core/evaluation/coco_utils.py", line 31, in coco_eval
    cocoEval = COCOeval(coco, coco_dets, iou_type)
  File "/home/jason/anaconda3/envs/pytorch10/lib/python3.7/site-packages/pycocotools-2.0.0-py3.7-linux-x86_64.egg/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/jason/anaconda3/envs/pytorch10/lib/python3.7/site-packages/pycocotools-2.0.0-py3.7-linux-x86_64.egg/pycocotools/cocoeval.py", line 531, in __init__
    raise Exception('iouType not supported')
Exception: iouType not supported
`

**Comment by Charcy-yang** [comment]
我也遇到了同样的问题，请问怎么解决的？
