### ISSUE TITLE
Test pipeline

### ISSUE THREAD

**Issue by ushakovegor** [open-mmlab/mmdetection#6206]
Hello,
I try make my own test pipeline. I use this:
`train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]`
But i have this this error:
`Traceback (most recent call last):
  File "./tools/train.py", line 251, in <module>
    main()
  File "./tools/train.py", line 144, in main
    cfg.test_pipeline[1]['transforms'][4] = {'type': 'DefaultFormatBundle'}
  File "/home/ushakov/.pyenv/versions/histo_env/lib/python3.8/site-packages/mmcv/utils/config.py", line 35, in __missing__
    raise KeyError(name)
KeyError: 'transforms'
Traceback (most recent call last):
  File "./tools/train.py", line 251, in <module>
    main()
  File "./tools/train.py", line 144, in main
    cfg.test_pipeline[1]['transforms'][4] = {'type': 'DefaultFormatBundle'}
  File "/home/ushakov/.pyenv/versions/histo_env/lib/python3.8/site-packages/mmcv/utils/config.py", line 35, in __missing__
    raise KeyError(name)
KeyError: 'transforms'
Killing subprocess 10855
Killing subprocess 10856
Traceback (most recent call last):
  File "/home/ushakov/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ushakov/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ushakov/.pyenv/versions/histo_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ushakov/.pyenv/versions/histo_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ushakov/.pyenv/versions/histo_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ushakov/.pyenv/versions/histo_env/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/fcos/fcos_x101_64x4d_fpn_gn-head_mstrain_640-800_2x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.`

Can i solve this issue in config?

**Comment by AndreaPi** [comment]
Hi, it's a bit complicated to read your code without proper formatting, but it looks like you defined your own _train_ pipeline, not the test pipeline, since you used the `train_pipeline` keyword:

```
train_pipeline = [ dict(type='LoadImageFromFile'), dict(type='LoadAnnotations', with_bbox=True), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']), ]
```

What would you like to customize, the train pipeline or the test pipeline? Disclaimer: I'm not one of the developers.

**Comment by ushakovegor** [comment]
> Hi, it's a bit complicated to read your code without proper formatting, but it looks like you defined your own _train_ pipeline, not the test pipeline, since you used the `train_pipeline` keyword:
> 
> ```
> train_pipeline = [ 
>         dict(type='LoadImageFromFile'), 
>         dict(type='LoadAnnotations', with_bbox=True), 
>         dict(type='Normalize', **img_norm_cfg), 
>         dict(type='Pad', size_divisor=32), 
>         dict(type='DefaultFormatBundle'), 
>         dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
> ]
> ```
> 
> What would you like to customize, the train pipeline or the test pipeline? Disclaimer: I'm not one of the developers.

Sorry about my formatting. I forgot to change its name. I try to change the test pipeline.

**Comment by ushakovegor** [comment]
> 

> > Hi, it's a bit complicated to read your code without proper formatting, but it looks like you defined your own _train_ pipeline, not the test pipeline, since you used the `train_pipeline` keyword:
> > ```
> > train_pipeline = [ 
> >         dict(type='LoadImageFromFile'), 
> >         dict(type='LoadAnnotations', with_bbox=True), 
> >         dict(type='Normalize', **img_norm_cfg), 
> >         dict(type='Pad', size_divisor=32), 
> >         dict(type='DefaultFormatBundle'), 
> >         dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What would you like to customize, the train pipeline or the test pipeline? Disclaimer: I'm not one of the developers.
> 
> Sorry about my formatting. I forgot to change its name. I try to customize the test pipeline.

**Comment by AndreaPi** [comment]
Ok, so, assuming that you defined `img_norm_cfg` correctly before in the config file, I'd try to do this:

```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='MultiScaleFlipAug',
        img_scale=image_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='Normalize',**img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
```

I'd also suggest that you include your whole config file, to get better support.

**Comment by ushakovegor** [comment]
> Ok, so, assuming that you defined `img_norm_cfg` correctly before in the config file, I'd try to do this:
> 
> ```
> test_pipeline = [
>     dict(type='LoadImageFromFile'),
>     dict(type='MultiScaleFlipAug',
>         img_scale=image_scale,
>         flip=False,
>         transforms=[
>             dict(type='Resize', keep_ratio=True),
>             dict(type='Normalize',**img_norm_cfg),
>             dict(type='Pad', size_divisor=32),
>             dict(type='DefaultFormatBundle'),
>             dict(type='Collect', keys=['img'])
>         ])
> ]
> ```
> 
> I'd also suggest that you post your whole config file here, to get better support.

My config
```
_base_ = './fcos_r50_caffe_fpn_gn-head_1x_coco.py'
model = dict(
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://resnext101_64x4d')))
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
albu_train_transforms = [
    dict(
        type='RandomRotate90',
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        p=0.3),
    dict(
        type='ShiftScaleRotate',
        scale_limit=0.3,
        p=0.5),
    dict(
        type='Flip',
        p=0.5),
    dict(
        type='GaussNoise',
        p=0.3),
    dict(
        type='Blur',
        blur_limit=3,
        p=0.1),
    dict(
        type='Sharpen',
        alpha=(0.15, 0.25),
        p=0.5),
     dict(
        type='HueSaturationValue',
        p=0.3)
    
]

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Pad', size_divisor=32),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='RandomFlip', flip_ratio=0.0),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels'])
]


test_pipeline = [ 
        dict(type='LoadImageFromFile'), 
        dict(type='LoadAnnotations', with_bbox=True), 
        dict(type='Normalize', **img_norm_cfg), 
        dict(type='Pad', size_divisor=32), 
        dict(type='DefaultFormatBundle'), 
        dict(type='Collect', keys=['img']),
]

data = dict(
    samples_per_gpu=15,
    workers_per_gpu=2,
    train=dict(pipeline=train_pipeline),
    val=dict(pipeline=test_pipeline),
    test=dict(pipeline=test_pipeline))
# optimizer
optimizer = dict(
    lr=0.01, paramwise_cfg=dict(bias_lr_mult=2., bias_decay_mult=0.))
optimizer_config = dict(
    _delete_=True, grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(step=[16, 22])
runner = dict(type='EpochBasedRunner', max_epochs=40)
```

Your test config is working. But i do not understand, why i can not use my version pipeline?

**Comment by AndreaPi** [comment]
I _think_ you can't because train data augmentation and test data augmentation are two very different things: one is a regularization on the weights, the other one is a sort of ensembling method. If you want to do test data aug correctly in MMDet, I think you need to use `MultiScaleFlipAug`. See also the doc on pipelines:

https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html#test-time-augmentation

But again, I'm not a developer, so I may be wrong.
