### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmo5dhu0b/tmpysztf6e9.py'

### ISSUE THREAD

**Issue by zkungithub** [open-mmlab/mmdetection#6221]
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 68, in main
    cfg = Config.fromfile(args.config)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 165, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 95, in _file2dict
    mod = import_module(temp_module_name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpmo5dhu0b/tmpysztf6e9.py", line 3
    model = dict(`
                 ^
SyntaxError: invalid syntax
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f78e349d4d0>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmo5dhu0b/tmpysztf6e9.py'

在mmdetection训练faster-RNN 和ssd的时候出现了问题，但是一开始训练ssd的时候是可以训练的，过几天之后出的这个问题

**Comment by neel04** [comment]
In my experience, just run the snippet again - for some reason it fixes it 🤷

**Comment by wujiaors** [comment]
> Traceback (most recent call last): File "tools/train.py", line 161, in main() File "tools/train.py", line 68, in main cfg = Config.fromfile(args.config) File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 165, in fromfile cfg_dict, cfg_text = Config._file2dict(filename) File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 125, in _file2dict _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f)) File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 95, in _file2dict mod = import_module(temp_module_name) File "/opt/conda/lib/python3.7/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1006, in _gcd_import File "", line 983, in _find_and_load File "", line 967, in _find_and_load_unlocked File "", line 677, in _load_unlocked File "", line 724, in exec_module File "", line 860, in get_code File "", line 791, in source_to_code File "", line 219, in _call_with_frames_removed File "/tmp/tmpmo5dhu0b/tmpysztf6e9.py", line 3 model = dict(` ^ SyntaxError: invalid syntax Exception ignored in: <function _TemporaryFileCloser.**del** at 0x7f78e349d4d0> Traceback (most recent call last): File "/opt/conda/lib/python3.7/tempfile.py", line 448, in **del** self.close() File "/opt/conda/lib/python3.7/tempfile.py", line 444, in close unlink(self.name) FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpmo5dhu0b/tmpysztf6e9.py'
> 
> 在mmdetection训练faster-RNN 和ssd的时候出现了问题，但是一开始训练ssd的时候是可以训练的，过几天之后出的这个问题

请问最后怎么解决的呀

**Comment by mingmingbo** [comment]
是啊，怎么解决的呢

**Comment by ron4u1998** [comment]
did u solve this error?

**Comment by kevinlikai1213** [comment]
请问怎么解决的呢
