### ISSUE TITLE
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by neosis** [open-mmlab/mmdetection#6223]
Hi

I am trying to train - cascade_mask_rcnn_hrnetv2p_w32_20e_coco with custom dataset using tools/train.py.

`python ../mmdetection/tools/train.py ./model/cascade_mask_rcnn_hrnetv2p_w32_20e_coco.py`

I am getting following error -

```
Traceback (most recent call last):
  File "../mmdetection/tools/train.py", line 189, in <module>
    main()
  File "../mmdetection/tools/train.py", line 185, in main
    meta=meta)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 127, in forward_train
    x = self.extract_feat(img)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 67, in extract_feat
    x = self.backbone(img)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/mmdet/models/backbones/hrnet.py", line 547, in forward
    x = self.conv1(x)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/neosis/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

Will you be able help or provide some pointers on what could be amiss?

Best
Ashutosh

**Comment by neosis** [comment]
Solved by using to_float32
