### ISSUE TITLE
 TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by CharlesNJ** [open-mmlab/mmdetection#6231]
**Describe the bug**
While training the model I am facing this error, not sure where am I going wrong. 

**Reproduction**

1. What command or script did you run?

```
!python tools/train.py  'configs/truck/cascade_mask_rcnn_swin_small_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_truck.py' 
```

Using the pre-trained model as a checkpoint for transfer learning.

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I modified the code for custom object detection for the custom dataset. Using a custom dataset with modifications made in the config/swin/xxx file and changed the path in the _ base _ variable in the config file downloaded from the repository.

3. What dataset did you use?
custom dataset with a json file annotations

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
I don't think it is env problem, I have no issues running a pre-trained model by itself.

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

I have modified the files that were mentioned in the config files like num_classes and adding data variables with paths, enabling optimizer_config and in models/cascade_xxx.py.

**Error traceback**

```
File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 177, in main
    train_detector(
  File "/home/w/cbn/CBNetV2/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/w/cbn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/w/cbn/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/w/cbn/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/w/cbn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/w/cbn/CBNetV2/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 371, in __call__
    results = self._load_masks(results)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 323, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 323, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "/home/w/cbn/CBNetV2/mmdet/datasets/pipelines/loading.py", line 281, in _poly2mask
    elif isinstance(mask_ann['counts'], list):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by neel04** [comment]
that seems to be a problem with your dataset - double-check the type. How many classes are you classifying? are you sure the format is correct?

**Comment by AndreaPi** [comment]
I agree - sounds like an error in the number and/or naming of classes. This happened to me quite often when I began to use MMDetection. If you share your config file, we could help more. BTW, I'm curious - are you using a model where the backbone network is Swin-S and the head is Cascade Mask R-CNN? I cannot find anything like that here - the closest one (but it's Mask R-CNN, not Cascade) is this

https://github.com/open-mmlab/mmdetection/blob/master/configs/swin/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco.py

**Comment by CharlesNJ** [comment]
I looked into the json file, but I don't see a discrepancy in the format. Does it matter which annotation comes first?
`iscrowd` is in the middle on the annotations whereas COCO format is at the last. I am assuming this is not a biggie!

```
_base_ = [
    '../_base_/models/cascade_mask_rcnn_swin_fpn.py',
    #'../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py', '../_base_/datasets/coco_detection.py'
]


dataset_type = 'COCODataset'
classes = ('person', 'car', 'truck',)
data = dict(
    train=dict(
        img_prefix='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/train/',
        classes=classes,
        ann_file='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/train/oil_truck_tr.json'),
    val=dict(
        img_prefix='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/val/',
        classes=classes,
        ann_file='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/val/oil_truck_val.json'),
    test=dict(
        img_prefix='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/test/',
        classes=classes,
        ann_file='/home/wellchecked/Pictures/ImageAssistant_Batch_Image_Downloader/training DS/oil tanker/test/oil_truck_test.json'))

# We can use the pre-trained Mask RCNN model to obtain higher performance
load_from = '/home/wellchecked/cbn/CBNetV2/cascade_mask_rcnn_cbv2_swin_small_patch4_window7_mstrain_400-1400_adamw_3x_oiltanker.pth'


model = dict(
    backbone=dict(
        embed_dim=96,
        depths=[2, 2, 18, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        ape=False,
        drop_path_rate=0.2,
        patch_norm=True,
        use_checkpoint=False
    ),
    neck=dict(in_channels=[96, 192, 384, 768]),
    roi_head=dict(
        bbox_head=[
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=3,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=False,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=3,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=False,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0)),
            dict(
                type='ConvFCBBoxHead',
                num_shared_convs=4,
                num_shared_fcs=1,
                in_channels=256,
                conv_out_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=3,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0., 0., 0., 0.],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=False,
                reg_decoded_bbox=True,
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
                loss_bbox=dict(type='GIoULoss', loss_weight=10.0))
        ],
        mask_head=dict(num_classes=3)
        
        ))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

# augmentation strategy originates from DETR / Sparse RCNN
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='AutoAugment',
         policies=[
             [
                 dict(type='Resize',
                      img_scale=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                                 (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                                 (736, 1333), (768, 1333), (800, 1333)],
                      multiscale_mode='value',
                      keep_ratio=True)
             ],
             [
                 dict(type='Resize',
                      img_scale=[(400, 1333), (500, 1333), (600, 1333)],
                      multiscale_mode='value',
                      keep_ratio=True),
                 dict(type='RandomCrop',
                      crop_type='absolute_range',
                      crop_size=(384, 600),
                      allow_negative_crop=True),
                 dict(type='Resize',
                      img_scale=[(480, 1333), (512, 1333), (544, 1333),
                                 (576, 1333), (608, 1333), (640, 1333),
                                 (672, 1333), (704, 1333), (736, 1333),
                                 (768, 1333), (800, 1333)],
                      multiscale_mode='value',
                      override=True,
                      keep_ratio=True)
             ]
         ]),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]


data = dict(train=dict(pipeline=train_pipeline))

optimizer = dict(_delete_=True, type='AdamW', lr=0.0001, betas=(0.9, 0.999), weight_decay=0.05,
                 paramwise_cfg=dict(custom_keys={'absolute_pos_embed': dict(decay_mult=0.),
                                                 'relative_position_bias_table': dict(decay_mult=0.),
                                                 'norm': dict(decay_mult=0.)}))
lr_config = dict(step=[27, 33])
runner = dict(type='EpochBasedRunnerAmp', max_epochs=36)

# do not use mmdet version fp16
fp16 = None

optimizer_config = dict(
    type="DistOptimizerHook",
    update_interval=1,
    grad_clip=None,
    coalesce=True,
    bucket_size_mb=-1,
    use_fp16=True,
)

```

**Comment by CharlesNJ** [comment]
I think I got the problem, mask is set to true while I don't have mask segmentation in the annotations file. Thank you! That solved the problem, even though it raised other issues, hoping that it is not related to this! Thank you, sending the config file helped me see it!

**Comment by neel04** [comment]
@CharlesNJ If you might manage to get Cascade RCNN with Swin transformer working and training well, would you be so kind as to send me the final config so that I can see why my stuff is erroring out?

I think I didn't include `_base_` but that itself errors out on addition, so I ditched it

**Comment by CharlesNJ** [comment]
Lol, how are you connecting the files then? 
For sure! I am still running into errors!! I will update here if I get a breakthrough!

**Comment by neel04** [comment]
> Lol, how are you connecting the files then?
I have no idea lol - it just seems to does automatically (I guess)

**Comment by CharlesNJ** [comment]
@neel04 what's happening with your training?

**Comment by neel04** [comment]
Not very stable and extremely spiky - with severe overfitting. It seems that whatever I try, I can't fine-tune for some reason :(

**Comment by CharlesNJ** [comment]
@neel04 Oh no! Are you training from scratch or are you using a pre-trained model?

**Comment by neel04** [comment]
*trying* to use pre-trained models, get a lot of warnings that half of the layers don't match and spiky training. 
Are you trying to fine-tune too?

**Comment by CharlesNJ** [comment]
Yeah, I am trying to use the pre-trained model too, same with me. I removed masks in the DS that's one of the reasons for many of my errors.

**Comment by neel04** [comment]
yeah, it seems the models can't be loaded properly? seems more like a problem with Swin + cascade_RCNN than `mmdetection`

**Comment by neel04** [comment]
how's your config currently? I think I am doing things wrong by ignoring stuff like `_base_` 🤔

**Comment by CharlesNJ** [comment]
I haven't made any changes except for changing the classes, num_classes, and the paths of the data.

**Comment by cyysc1998** [comment]
![image](https://user-images.githubusercontent.com/35159700/196024532-df1e7ea0-fcb9-4b41-8ff2-54bd88cd7e2e.png)
Maybe you should set with_mask=False. That works for me!
