### ISSUE TITLE
GFL导出onnx时遇到错误

### ISSUE THREAD

**Issue by FDInSky** [open-mmlab/mmdetection#6244]
Traceback (most recent call last):
  File "./tools/onnx_mmdet.py", line 334, in <module>
    pytorch2onnx(
  File "./tools/onnx_mmdet.py", line 89, in pytorch2onnx
    torch.onnx.export(
  File "/home/xiaolong.sun/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/xiaolong.sun/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/xiaolong.sun/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 694, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/xiaolong.sun/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 502, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: number of dims don't match in permute

**Comment by ZwwWayne** [comment]
Please @RunningLeon take a look. You can also refer to the documentation https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html

**Comment by ZwwWayne** [comment]
As [MMDeploy](https://github.com/open-mmlab/mmdeploy) supported YOLOX export. MMDet will no longer maintain the feature of model export. Please use MMDeploy and create an issue if you still have questions about that.

**Comment by changzhonghan** [comment]
mmdet.models.dense_heads.gfl_head.Integral

    self.register_buffer('project',
                         torch.linspace(0, self.reg_max, self.reg_max + 1,
                                        dtype=torch.float32).view(1, self.reg_max + 1))
