### ISSUE TITLE
ImportError: cannot import name 'replace_ImageToTensor' from 'mmdet.datasets' 

### ISSUE THREAD

**Issue by Tesla2678** [open-mmlab/mmdetection#6260]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

The training stage (Training VOC2007 dataset with faster_rcnn_x101_64x4d_fpn_1x_coco.) is successful.
Errors happened while testing the model by "tools/analysis_tools/analyze_results.py"

**Reproduction**

1. What command or script did you run?

`python analyze_results.py /home/xudongsong0302/PycharmProjects/mmDetection_Reader/mmdetection/Data_test_delibrate_practice/configs/faster_rcnn/faster_rcnn_x101_64x4d_fpn_1x_coco.py /home/xudongsong0302/PycharmProjects/mmDetection_Reader/mmdetection/Data_test_delibrate_practice/work_dirs/faster_rcnn_x101_64x4d_fpn_1x_coco/result.pkl /home/xudongsong0302/PycharmProjects/mmDetection_Reader/mmdetection/Data_test_delibrate_practice/work_dirs/faster_rcnn_x101_64x4d_fpn_1x_coco/test_result_analyse --topk 50 --show-score-thr 0.2`

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, Yes

3. What dataset did you use?
VOC2007

**Environment**
1. 
```
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2: NVIDIA Quadro P5000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.3
MMCV: 1.3.9
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.16.0+d53fbbc
```
2.
PyTorch installed by pip,
MMCV installed by pip,
MMDetection downloaded by git, 

**Error traceback**

```
Traceback (most recent call last):
  File "/home/xudongsong0302/Downloads/mmdetection/tools/analysis_tools/analyze_results.py", line 11, in <module>
    from mmdet.datasets import build_dataset, get_loading_pipeline
  File "/home/xudongsong0302/Downloads/mmdetection/mmdet/datasets/__init__.py", line 14, in <module>
    from .utils import NumClassCheckHook, get_loading_pipeline,replace_ImageToTensor,DeliberatePracticeHook
  File "/home/xudongsong0302/Downloads/mmdetection/mmdet/datasets/utils.py", line 8, in <module>
    from mmdet.apis.test import multi_gpu_test,single_gpu_test
  File "/home/xudongsong0302/Downloads/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/xudongsong0302/Downloads/mmdetection/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.datasets import replace_ImageToTensor
ImportError: cannot import name 'replace_ImageToTensor' from 'mmdet.datasets' (/home/xudongsong0302/Downloads/mmdetection/mmdet/datasets/__init__.py)
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tesla2678** [comment]
> @Tesla2678 Please pip install mmdetection after git download.

Hello hhaAndroid, Thank you very much, It works after pip install mmdetection.
