### ISSUE TITLE
when train my new model, optimizer error

### ISSUE THREAD

**Issue by Riser6** [open-mmlab/mmdetection#6298]
when change the backbone of yolox to a new module, the error occur

Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 185, in main
    meta=meta)
  File "/data/wd/mmdetection/mmdet/apis/train.py", line 89, in train_detector
    optimizer = build_optimizer(model, cfg.optimizer)
  File "/data/wd/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/optimizer/builder.py", line 43, in build_optimizer
    optimizer = optim_constructor(model)
  File "/data/wd/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/optimizer/default_constructor.py", line 249, in __call__
    return build_from_cfg(optimizer_cfg, OPTIMIZERS)
  File "/data/wd/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: SGD: some parameters appear in more than one parameter group

I'd appreciate it if you could help me!

**Comment by Riser6** [comment]
[configs.zip](https://github.com/open-mmlab/mmdetection/files/7358617/configs.zip)
the config file

**Comment by Riser6** [comment]
No problem replacing them with other backbone
