### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6301]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I'm trying to train htc_r50 without a semantic head, but I get` "index out of bounds"` errors and then a core dump.

**Reproduction**

1. What command or script did you run?

```python
python /mmdetection/tools/train.py configs/test.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

I change the number of classes (5 instead of 80), the mean and standard deviation of the images as well as their size, and the learning rate, since I have a batch size of 4. None of these modifications could be the cause of the error since I use exactly the same values for my Cascade Mask R-CNN r50 and r101 models, which both train perfectly on my custom dataset. Here is the modified config file:

```python
# base config
_base_ = '/mmdetection/configs/htc/htc_without_semantic_r50_fpn_1x_coco.py'
# classes
classes = ('a', 'b', 'c',
            'd', 'e')
n_classes = len(classes)
model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes),
            dict(
                type='Shared2FCBBoxHead',
                num_classes=n_classes)
        ],
        mask_head=[
            dict(
                type='HTCMaskHead',
                num_classes=n_classes),
            dict(
                type='HTCMaskHead',
                num_classes=n_classes),
            dict(
                type='HTCMaskHead',
                num_classes=n_classes)
        ])
)
# channel normalization
img_norm_cfg = dict(
    mean=[107.79, 115.57, 117.07], std=[48.47, 54.44, 56.12], to_rgb=False)
# image scale for resizing
image_scale = (1920, 1440)
# pipelines setting
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=image_scale, keep_ratio=True),
    dict(type='Pad', size_divisor=32),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'],
        meta_keys=('filename', 'ori_shape', 'img_shape', 'img_norm_cfg',
                   'pad_shape', 'scale_factor'))
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='MultiScaleFlipAug',
        img_scale=image_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='Normalize',**img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
# dataset settings
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=2,
    train=dict(
        type='CocoDataset',
        ann_file=<..>,
        img_prefix=<..>,
        pipeline=train_pipeline,
        classes=classes),
    val=dict(
        type='CocoDataset',
        ann_file=<..>,
        img_prefix=<..>,
        pipeline=test_pipeline,
        classes=classes),
    test=dict(
        type='CocoDataset',
        ann_file=<..>,
        img_prefix=<..>,
        pipeline=test_pipeline,
        classes=classes),
)

evaluation = dict(metric=['bbox', 'segm'], save_best='bbox_mAP')
# optimizer settings
# correct learning rate for training with a batch size of 2, e.g., 1 GPU, 2 img/GPU
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
lr_config = dict(  
    policy='step',
    warmup=None,  
    step=[100,130]) 

# workflow and workdir settings
runner = dict(type='EpochBasedRunner', max_epochs=160)
checkpoint_config = dict(interval=-1) 
workflow = [('train', 1), ('val', 1)] # this prints both train & val loss for each epoch
#load_from = 'logs/cascade_mask_rcnn_r101_fpn_150e_random_split/latest.pth'
work_dir = 'logs/<...>'
##To Save only last weight and tensorboard log
log_config = dict(
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
```

3. What dataset did you use?

A custom dataset of type `COCODataset`. The dataset is read correctly by MMDetection.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.17.0+3bc614d
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

I don't have to install PyTorch because I'm running it in a Docker container based on

https://github.com/open-mmlab/mmdetection/blob/master/docker/Dockerfile

with some modifications related to my environment. 

```bash
> echo $PATH
/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> echo $LD_LIBRARY_PATH
/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> echo $PYTHONPATH

```

**Error traceback**
The error traceback is 

```python
Traceback (most recent call last):
  File "/mmdetection/tools/train.py", line 194, in <module>
    main()
  File "/mmdetection/tools/train.py", line 190, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/htc_roi_head.py", line 299, in forward_train
    bbox_results['bbox_pred'], pos_is_gts, img_metas)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 447, in refine_bboxes
    img_meta_)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 184, in new_func
    return old_func(*args, **kwargs)
  File "/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 490, in regress_by_class
    rois, bbox_pred, max_shape=max_shape)
  File "/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 93, in decode
    self.add_ctr_clamp, self.ctr_clamp)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/parrots_jit.py", line 21, in wrapper_inner
    return func(*args, **kargs)
  File "/mmdetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py", line 206, in delta2bbox
    means = deltas.new_tensor(means).view(1,
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1595629403081/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f69ae75277d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xb5d (0x7f69ae9a2d9d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f69ae73eb1d in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x53f0ea (0x7f69e7fd50ea in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: __libc_start_main + 0xe7 (0x7f6a0af7eb97 in /lib/x86_64-linux-gnu/libc.so.6)

./run_experiment.sh: line 1:  1220 Aborted                 (core dumped) python /mmdetection/tools/train.py configs/test.py
```

However, before Python errors out, I get hundreds of lines like these ones, which seem to indicate an array out of bounds error:

```python
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [5,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1595629403081/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:86: operator(): block: [5,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
.
.
```

For the sake of completeness, I attached the full stdout and stderr as a zip file.
[stdout_stderr.txt.zip](https://github.com/open-mmlab/mmdetection/files/7360930/stdout_stderr.txt.zip)

**Comment by AndreaPi** [comment]
Apparently, the cause is that MMCV `merge_a_into_b` method is not very smart, and when the variable to be modified is a list of `dicts`, such as the `bbox_head` of a cascade model, it just replaces it rather than descending into it, like it does when the variable is a `dict`:

https://github.com/open-mmlab/mmcv/blob/e22740b1d6953d75a0acecce4455d23800b1f018/mmcv/utils/config.py#L324

The (ugly) solution is to copy _all_ the `bbox_head` parameters in the config file, even if you really need to modify only
`num_classes`:

 https://github.com/open-mmlab/mmdetection/issues/6340
