### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by sxy1122** [open-mmlab/mmdetection#6307]
![image](https://user-images.githubusercontent.com/77336413/137716488-57ee0c72-cee0-491e-9f37-4c214e1753f5.png)

I would like to ask what caused this? I can't find a solution。
Then there is another problem. After training 1epoch, the verification is broken now. How can I make the trained epoch verify and get the map。

**Comment by jshilong** [comment]
Please use CUDA_LAUNCH_BLOCKING=1 python /mmdetection/tools/train.py configs/test.py to localize the error more precisely,
Usually, this error indicates there is indexes out of boundary

**Comment by Sakura-ldx** [comment]
> Please run
> 
> ```
> CUDA_LAUNCH_BLOCKING=1 python /mmdetection/tools/train.py configs/test.py`
> ```
> 
> and update the error message

I meet this issue in another projecct. This is the Traceback.
Traceback (most recent call last):
  File "/home/ssd/priv/workspace/hyperstyle/scripts/train.py", line 32, in <module>
    main()
  File "/home/ssd/priv/workspace/hyperstyle/scripts/train.py", line 20, in main
    coach.train()
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../training/coach_hyperstyle.py", line 137, in train
    x, y, y_hat, loss_dict, id_logs, w_inversion = self.perform_forward_on_batch(batch, train=True)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../training/coach_hyperstyle.py", line 105, in perform_forward_on_batch
    y_hat, latent, weights_deltas, codes, w_inversion = self.net.forward(x,
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/hyperstyle.py", line 72, in forward
    y_hat, codes = self.__get_initial_inversion(x, resize=True)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/hyperstyle.py", line 155, in __get_initial_inversion
    return self.__get_w_inversion(x, resize)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/hyperstyle.py", line 165, in __get_w_inversion
    y_hat, _ = self.decoder([codes],
  File "/home/ssd/priv/miniconda3/envs/hyperstyle_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/stylegan2/model.py", line 532, in forward
    skip = self.to_rgb1(out, latent[:, 1], weights_delta=weights_deltas[1])
  File "/home/ssd/priv/miniconda3/envs/hyperstyle_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/stylegan2/model.py", line 356, in forward
    out = self.conv(input, style, weights_delta)
  File "/home/ssd/priv/miniconda3/envs/hyperstyle_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/stylegan2/model.py", line 237, in forward
    style = self.modulation(style).view(batch, 1, in_channel, 1, 1)
  File "/home/ssd/priv/miniconda3/envs/hyperstyle_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ssd/priv/workspace/hyperstyle/scripts/../models/stylegan2/model.py", line 154, in forward
    print((weight * self.scale).device)
weight is a Tensor in the cuda: 1 device, self.scale is a float, but the error happened when they multiply. Do you have any solution?
