### ISSUE TITLE
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by Chandhana99** [open-mmlab/mmdetection#6320]
Getting this issue, please help me solve this.

Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 151, in <module>
    main()
  File "mmdetection/tools/train.py", line 147, in main
    meta=meta)
  File "/content/mmdetection/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 132, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 145, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 24, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 323, in __call__
    self._pad_masks(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 310, in _pad_masks
    for mask in results[key]
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 310, in <listcomp>
    for mask in results[key]
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

**Comment by AronLin** [comment]
1. It seems that the version of mmdet is too old, I can not find this line.
2. Please use the issue template to show more information. We cannot locate the problem with the little information.
