### ISSUE TITLE
How to ues the   'benchmark_inference_fps.py' in the   ' .dev_scripts' ?

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdetection#6333]
Hello! Could you please tell me how to use  **''benchmark_inference_fps.py'** ?
I use it by the code: **'python .dev_scripts/benchmark_inference-fps.py configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py work_dirs/yolo_mydata/latest.pth'**
But it occur the error:   **' NotImplementedError: Only supports distributed mode'**
Could you please **show me an example**? I use this to get the inference speed(fps).
Thank you!

**Comment by RangiLyu** [comment]
This script is for developers, you can use tools/analysis_tools/benchmark.py to get FPS.
And you need to run the script with a distributed launcher.
Try to run
```
python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py YOUR_CFG YOUR_MODEL --launcher pytorch```

**Comment by lijoe123** [comment]
Thank you !!!!    I GOT  IT!
![11](https://user-images.githubusercontent.com/86214036/138224471-6cce044f-4bfd-437b-8404-08ea19ab43a2.JPG)
But i dont understand which is  **'inference time '**? '**fps' or 'times per image'**

**Comment by joeyslv** [comment]
> FPS means frames per second, and its value is 49.4 images per second. Inference time per image is 20.3 milliseconds.
```
(swin-t) E:\Object-Detection\Github\radar-detection>python -m torch.distributed.launch --nproc_per_node=1 --master_port=29500 tools/analysis_tools/benchmark.py checkpoints/tood/radar_tood_tri/radar_tood.py checkpoints/tood/radar_tood_tri/epoch_31.pth --launcher pytorch 
NOTE: Redirects are currently not supported in Windows or MacOs.
D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : tools/analysis_tools/benchmark.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: C:\Users\joeyslv\AppData\Local\Temp\torchelastic_r5tsilen\none_uwu6jww7
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python.exe
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\elastic\utils\store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: C:\Users\joeyslv\AppData\Local\Temp\torchelastic_r5tsilen\none_uwu6jww7\attempt_0\0\error.json
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 187, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 179, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 531, in init_process_group
    timeout=timeout)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 625, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 29940) of binary: D:\App\anaconda\envs\swin-t\python.exe
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: C:\Users\joeyslv\AppData\Local\Temp\torchelastic_r5tsilen\none_uwu6jww7\attempt_1\0\error.json
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 187, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 179, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 531, in init_process_group
    timeout=timeout)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 625, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 30364) of binary: D:\App\anaconda\envs\swin-t\python.exe
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 2/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: C:\Users\joeyslv\AppData\Local\Temp\torchelastic_r5tsilen\none_uwu6jww7\attempt_2\0\error.json
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 187, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 179, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 531, in init_process_group
    timeout=timeout)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 625, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21344) of binary: D:\App\anaconda\envs\swin-t\python.exe
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 1/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=3
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: C:\Users\joeyslv\AppData\Local\Temp\torchelastic_r5tsilen\none_uwu6jww7\attempt_3\0\error.json
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 187, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 179, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 531, in init_process_group
    timeout=timeout)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\distributed_c10d.py", line 625, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6740) of binary: D:\App\anaconda\envs\swin-t\python.exe
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\elastic\utils\store.py:71: FutureWarning: This is an experimental API and will be changed in future.    
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:Done waiting for other agents. Elapsed: 0.0 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "6740", "role": "default", "hostname": "yukkier", "state": "FAILED", "total_run_time": 20, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python.exe\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [1]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "yukkier", "state": "SUCCEEDED", "total_run_time": 20, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python.exe\"}", "agent_restarts": 3}}
D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py:354: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 6740 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "D:\App\anaconda\envs\swin-t\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\App\anaconda\envs\swin-t\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\launch.py", line 173, in <module>
    main()
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\launch.py", line 169, in main
    run(args)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\run.py", line 624, in run
    )(*cmd_args)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\launcher\api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\torch\distributed\launcher\api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
********************************************
  tools/analysis_tools/benchmark.py FAILED
============================================
Root Cause:
[0]:
  time: 2022-04-17_21:10:29
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 6740)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
============================================
Other Failures:
  <NO_OTHER_FAILURES>
********************************************
```
when i run the benchmark.py, this occured ,Could you please help me ?

**Comment by alaa-shubbak** [comment]
@joeyslv  are you running soft-teacher model with this script above ?

**Comment by alaa-shubbak** [comment]
I am little bit confused , I used this instruction for my models. three of them from same basic structure.
It works correctly with one model and failed with the other two 
it gave me such error massage
`RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:558, unhandled system error, NCCL version 2.7.8`

notice that , my dataset is not huge , for the test part it is only 88 images. 

shall i update or reinstall the NCCL version ?
