### ISSUE TITLE
ERROR: Command errored out with exit status 1，import io, os, sys, setuptools, tokenize; sys.argv[0]

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#6411]
安装的时候 报错
Error during installation

```
pip install -v -e .

Installing collected packages: six, python-dateutil, kiwisolver, cycler, matplotlib, terminaltables, pycocotools-windows, mmdet
  Running setup.py develop for mmdet
    Running command 'E:\anaconda3\envs\mmdetection\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\mmdetection\\setup.py'"'"'; __file__='"'"'F:\\mmdetection\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "F:\mmdetection\setup.py", line 182, in <module>
        add_mim_extension()
      File "F:\mmdetection\setup.py", line 169, in add_mim_extension
        os.symlink(src_relpath, tar_path)
    OSError: symbolic link privilege not held
ERROR: Command errored out with exit status 1: 'E:\anaconda3\envs\mmdetection\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'F:\\mmdetection\\setup.py'"'"'; __file__='"'"'F:\\mmdetection\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.


python setup.py develop

Traceback (most recent call last):
  File "setup.py", line 182, in <module>
    add_mim_extension()
  File "setup.py", line 169, in add_mim_extension
    os.symlink(src_relpath, tar_path)
OSError: symbolic link privilege not held

```
```

------------------- ------------ --------
win11

addict              2.4.0
certifi             2021.10.8
cycler              0.11.0
Cython              0.29.24
kiwisolver          1.3.2
matplotlib          3.4.3
mmcv                1.3.16       f:\mmcv
mmcv-full           1.3.16       f:\mmcv
numpy               1.21.3
opencv-python       4.5.4.58
packaging           21.2
Pillow              8.4.0
pip                 21.2.4
pycocotools-windows 2.0.0.2
pyparsing           2.4.7
python-dateutil     2.8.2
PyYAML              6.0
regex               2021.10.23
setuptools          58.0.4
six                 1.16.0
terminaltables      3.1.0
torch               1.10.0+cu113
torchaudio          0.10.0+cu113
torchvision         0.11.1+cu113
typing-extensions   3.10.0.2
wheel               0.37.0
wincertstore        0.2
yapf                0.31.0
```

**Comment by mengmeng0320** [comment]
I also encountered similar problems. Have you solved them？

**Comment by tijanidevit** [comment]
Uninstall and re-install your Python
