### ISSUE TITLE
KeyError: 'MMSyncBN is already registered in norm layer'

### ISSUE THREAD

**Issue by wantaoliu** [open-mmlab/mmdetection#6419]
**Environment**

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.3
MMCV: 1.3.11
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0+2295154

**Error traceback**
Traceback (most recent call last):
  File "/home/lwt/Project/mmdetection2/detectRS.py", line 4, in <module>
    from apis.inference import result_pyplot
  File "/home/lwt/Project/mmdetection2/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/lwt/Project/mmdetection2/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/lwt/Project/mmdetection2/mmdet/datasets/__init__.py", line 12, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/home/lwt/Project/mmdetection2/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "/home/lwt/Project/mmdetection2/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/lwt/Project/mmdetection2/mmdet/models/backbones/__init__.py", line 1, in <module>
    from .darknet import Darknet
  File "/home/lwt/Project/mmdetection2/mmdet/models/backbones/darknet.py", line 10, in <module>
    from ..builder import BACKBONES
  File "/home/lwt/Project/mmdetection2/mmdet/models/builder.py", line 6, in <module>
    from cv_core import build_from_cfg
  File "/home/lwt/Project/mmdetection2/mmdet/cv_core/__init__.py", line 15, in <module>
    from .ops import *
  File "/home/lwt/Project/mmdetection2/mmdet/cv_core/ops/__init__.py", line 21, in <module>
    from .sync_bn import SyncBatchNorm
  File "/home/lwt/Project/mmdetection2/mmdet/cv_core/ops/sync_bn.py", line 110, in <module>
    class SyncBatchNorm(Module):
  File "/home/lwt/Project/mmdetection2/mmdet/cv_core/utils/registry.py", line 122, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/lwt/Project/mmdetection2/mmdet/cv_core/utils/registry.py", line 58, in _register_module
    raise KeyError(f'{module_name} is already registered '
KeyError: 'MMSyncBN is already registered in norm layer'
```none
```
Last time,the Program is ok but don't run again now
Please help me if you know

**Comment by jshilong** [comment]
The version of mmcv and your mmdet is not compatible

**Comment by wantaoliu** [comment]
Thanks very much!

**Comment by DenghuiXiao** [comment]
how to solve it
