### ISSUE TITLE
Training detectorRS backbone in MMClassification

### ISSUE THREAD

**Issue by joihn** [open-mmlab/mmdetection#6422]
I'm using a custom dataset quite diffirent from ImageNet.
I want to pretrain my detectoRS backbone on a classification task, for this I'm using [MMclassification](https://github.com/open-mmlab/mmclassification).

I've successfully imported detectorRS backbone and neck (respectively `DetectoRS_ResNet` and `RFP`) into MMclassification.
For the head I'm using `LinearClsHead` from MMclassification.

### Problem

I have a bug during the head stage:
 ```
File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1672, in linear
    if input.dim() == 2 and bias is not None:
AttributeError: 'list' object has no attribute 'dim'
```
I think it's because the format outputeds by the RFP neck (MMdetection format ? ) is different from the expected input format  of the `LinearClsHead` (MMClassification fformat ?)
Any tipps ? 
### CFG and Logs below
cfg: 
```
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='DetectoRS_ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        conv_cfg=dict(type='ConvAWS'),
        sac=dict(type='SAC', use_deform=True),
        stage_with_sac=(False, True, True, True),
        output_img=True),
    neck=dict(
        type='RFP',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5,
        rfp_steps=2,
        aspp_out_channels=64,
        aspp_dilations=(1, 3, 6, 1),
        rfp_backbone=dict(
            rfp_inplanes=256,
            type='DetectoRS_ResNet',
            depth=50,
            num_stages=4,
            out_indices=(0, 1, 2, 3),
            frozen_stages=1,
            norm_cfg=dict(type='BN', requires_grad=True),
            norm_eval=True,
            conv_cfg=dict(type='ConvAWS'),
            sac=dict(type='SAC', use_deform=True),
            stage_with_sac=(False, True, True, True),
            style='pytorch')),
    head=dict(
        type='LinearClsHead',
        num_classes=2,
        in_channels=256,
        loss=dict(
            type='CrossEntropyLoss', class_weight=[3.243, 1], loss_weight=1.0),
        topk=(1, )))





RES_FACTOR = '0.5'
dataset_type = 'plant_data'
home_path = 'REMOVED_FOR_PRIVACY'
img_norm_cfg = dict(
    mean=[37.8847, 48.0685, 31.3074],
    std=[10.8716, 10.8456, 10.8808],
    to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=(768, 768), scale=(0.95, 1)),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='RandomFlip', flip_prob=0.5, direction='vertical'),
    dict(type='ColorJitter', brightness=0.2, contrast=0.2, saturation=0.2),
    dict(
        type='Normalize',
        mean=[37.8847, 48.0685, 31.3074],
        std=[10.8716, 10.8456, 10.8808],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(768, 1024)),
    dict(
        type='Normalize',
        mean=[37.8847, 48.0685, 31.3074],
        std=[10.8716, 10.8456, 10.8808],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
classes = (['bg', 'plant'], )
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=4,
    train=dict(
        type='plant_data',
        data_prefix='REMOVED_FOR_PRIVACY',
        ann_file=
        'REMOVED_FOR_PRIVACY',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='RandomResizedCrop', size=(768, 768), scale=(0.95, 1)),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(type='RandomFlip', flip_prob=0.5, direction='vertical'),
            dict(
                type='ColorJitter',
                brightness=0.2,
                contrast=0.2,
                saturation=0.2),
            dict(
                type='Normalize',
                mean=[37.8847, 48.0685, 31.3074],
                std=[10.8716, 10.8456, 10.8808],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ],
        classes=(['bg', 'plant'], )),
    val=dict(
        type='plant_data',
        data_prefix='REMOVED_FOR_PRIVACY',
        ann_file=
        'REMOVED_FOR_PRIVACY',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(768, 1024)),
            dict(
                type='Normalize',
                mean=[37.8847, 48.0685, 31.3074],
                std=[10.8716, 10.8456, 10.8808],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        classes=(['bg', 'plant'], )),
    test=dict(
        type='plant_data',
        data_prefix='REMOVED_FOR_PRIVACY',
        ann_file=
        'REMOVED_FOR_PRIVACY',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(768, 1024)),
            dict(
                type='Normalize',
                mean=[37.8847, 48.0685, 31.3074],
                std=[10.8716, 10.8456, 10.8808],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        classes=(['bg', 'plant'], )))
evaluation = dict(interval=8, metric='accuracy')
checkpoint_config = dict(interval=8)


wnb_username = 'REMOVED_FOR_PRIVACY'
wnb_project_name = 'classification'
model_name = 'temp'
resume_wandb = False
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(
            type='WandbLoggerHook',
            init_kwargs=dict(
                project='classification', name='temp', entity='REMOVED_FOR_PRIVACY'))
    ])
custom_hooks = [dict(type='Wandb_conf_hook', priority='VERY_LOW')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[120, 240, 360])
runner = dict(type='EpochBasedRunner', max_epochs=800)

work_dir = 'output/detectors'
gpu_ids = range(0, 1)
```

Logs:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-13b9d8b85e5b>", line 1, in <module>
    runfile('tools/train.py', args=['configs/detectors/rumex_detectors.py', '--work-dir', 'output/detectors'], wdir='/home/dockeruser/Documents/code/mmclassification')
  File "/home/dockeruser/.local/share/JetBrains/IntelliJIdea2021.2/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/dockeruser/.local/share/JetBrains/IntelliJIdea2021.2/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 177, in main
    meta=meta)
  File "/home/dockeruser/Documents/code/mmclassification/mmcls/apis/train.py", line 170, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/dockeruser/Documents/code/mmclassification/mmcls/models/classifiers/base.py", line 146, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/dockeruser/Documents/code/mmclassification/mmcls/models/classifiers/base.py", line 90, in forward
    return self.forward_train(img, **kwargs)
  File "/home/dockeruser/Documents/code/mmclassification/mmcls/models/classifiers/image.py", line 110, in forward_train
    loss = self.head.forward_train(x, gt_label)
  File "/home/dockeruser/Documents/code/mmclassification/mmcls/models/heads/linear_head.py", line 52, in forward_train
    cls_score = self.fc(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1672, in linear
    if input.dim() == 2 and bias is not None:
AttributeError: 'list' object has no attribute 'dim'
```

**Comment by jshilong** [comment]
The input is a list instead of a Tensor，please check your modification

**Comment by joihn** [comment]
Well, I didn't modify anything yet.
By default, the detection head is a cascade roi head, which takes a list as input. [ref here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/cascade_roi_head.py#L201)
`x (list[Tensor]): list of multi-level img features.`

Now I'm trying to find a **classsification** head which would take the same kind of input.

**Comment by joihn** [comment]
closing this because I realized it's not directly related to MMdetection
