### ISSUE TITLE
RuntimeError: CUDA error: out of memory when training  HTC without semantic head on a 32 Gb GPU

### ISSUE THREAD

**Issue by AndreaPi** [open-mmlab/mmdetection#6427]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I try to train an HTC model on a custom COCODataset (the `balloon` dataset), on a 32 Gb V100 GPU. The training errors out with `RuntimeError: CUDA error: out of memory `.
**Reproduction**

1. I used the following script to train the model:

```python
CUDA_LAUNCH_BLOCKING=1 python /mmdetection/tools/train.py configs/test_htc_without_semantic_head.py
```

2. I modified the number of classes in the config file, since the `balloon` dataset has only one class. I also changed the batch size, reducing it down to 1, in an attempt to solve the memory issues.
3. I used the `balloon` dataset. I can upload the dataset as a zip file if needed.
4. Here is the actual config file:

```python
# base config
_base_ = ['/mmdetection/configs/htc/htc_without_semantic_r50_fpn_1x_coco.py']

#### dataset-related parameters: edit accordingly when changing dataset
# classes
classes = ('balloon',)
n_classes = len(classes)
model = dict(
    backbone=dict(
        depth=101,
        init_cfg=dict(type='Pretrained',
                      checkpoint='torchvision://resnet101')),
    roi_head=dict(
            bbox_head=[
                dict(
                    type='Shared2FCBBoxHead',
                    in_channels=256,
                    fc_out_channels=1024,
                    roi_feat_size=7,
                    num_classes=n_classes,
                    bbox_coder=dict(
                        type='DeltaXYWHBBoxCoder',
                        target_means=[0., 0., 0., 0.],
                        target_stds=[0.1, 0.1, 0.2, 0.2]),
                    reg_class_agnostic=True,
                    loss_cls=dict(
                        type='CrossEntropyLoss',
                        use_sigmoid=False,
                        loss_weight=1.0),
                    loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                                loss_weight=1.0)),
                dict(
                    type='Shared2FCBBoxHead',
                    in_channels=256,
                    fc_out_channels=1024,
                    roi_feat_size=7,
                    num_classes=n_classes,
                    bbox_coder=dict(
                        type='DeltaXYWHBBoxCoder',
                        target_means=[0., 0., 0., 0.],
                        target_stds=[0.05, 0.05, 0.1, 0.1]),
                    reg_class_agnostic=True,
                    loss_cls=dict(
                        type='CrossEntropyLoss',
                        use_sigmoid=False,
                        loss_weight=1.0),
                    loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                                loss_weight=1.0)),
                dict(
                    type='Shared2FCBBoxHead',
                    in_channels=256,
                    fc_out_channels=1024,
                    roi_feat_size=7,
                    num_classes=n_classes,
                    bbox_coder=dict(
                        type='DeltaXYWHBBoxCoder',
                        target_means=[0., 0., 0., 0.],
                        target_stds=[0.033, 0.033, 0.067, 0.067]),
                    reg_class_agnostic=True,
                    loss_cls=dict(
                        type='CrossEntropyLoss',
                        use_sigmoid=False,
                        loss_weight=1.0),
                    loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
            ],
            mask_head=[
                dict(
                    type='HTCMaskHead',
                    with_conv_res=False,
                    num_convs=4,
                    in_channels=256,
                    conv_out_channels=256,
                    num_classes=n_classes,
                    loss_mask=dict(
                        type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
                dict(
                    type='HTCMaskHead',
                    num_convs=4,
                    in_channels=256,
                    conv_out_channels=256,
                    num_classes=n_classes,
                    loss_mask=dict(
                        type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
                dict(
                    type='HTCMaskHead',
                    num_convs=4,
                    in_channels=256,
                    conv_out_channels=256,
                    num_classes=n_classes,
                    loss_mask=dict(
                        type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))
            ]),
)
########################################################################### 
# dataset settings
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/train.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
    val=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/validation.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
    test=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/validation.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
)

evaluation = dict(metric=['bbox', 'segm'], save_best='bbox_mAP')
# optimizer settings
optimizer = dict(type='SGD', lr=0.00125)
lr_config = dict(  
    step=[9, 16]) 
# workflow and workdir settings
runner = dict(type='EpochBasedRunner', max_epochs=20)
checkpoint_config = dict(interval=-1) 
workflow = [('train', 1), ('val', 1)] 
work_dir = 'logs/test_htc_without_semantic_head'
## logger settings
log_config = dict(
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.5.4-dev
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.18.0+3bc614d
```

2. 
  - I didn't need to install PyTorch because I use a Docker image with PyTorch
  - environment variables that may be related:
  ```bash
  root@89a7349daa69:/# echo $PATH                                         
  /opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  root@89a7349daa69:/# echo $LD_LIBRARY_PATH
  /usr/local/nvidia/lib:/usr/local/nvidia/lib64
  root@89a7349daa69:/workspace/andrea/instance_segmentation_for_combustor_defects# echo $PYTHONPATH
  
  ```
 
**Error traceback**
If applicable, paste the error trackback here.

```python
Traceback (most recent call last):
  File "/mmdetection/tools/train.py", line 194, in <module>
    main()
  File "/mmdetection/tools/train.py", line 190, in main
    meta=meta)
  File "/mmdetection/mmdet/apis/train.py", line 89, in train_detector
    model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 458, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
```

Can you help me? Thanks!

**Comment by hhaAndroid** [comment]
@AndreaPi 32GB CUDA memory is enough, you can check if there are other programs occupying the  CUDA memory.

**Comment by AndreaPi** [comment]
@hhaAndroid thanks for your answer, but the issue is due to some bugs in the current implementation of the HTC model in MMDetectio, and not to other programs occupying the CUDA memory. Here's the proof:

1) results of `nvidia-smi` concerning my GPU
```
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   31C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
2) results from `torch`:

```python
import torch

print('Is CUDA available?', torch.cuda.is_available())
print('How many GPUs?',torch.cuda.device_count())
print('What''s the device name?', torch.cuda.get_device_name(0))

print('Memory Usage:')
print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
print('Cached:   ', round(torch.cuda.memory_reserved(0)/1024**3,1), 'GB')
```

Output:

```
Is CUDA available? True
How many GPUs? 1
Whats the device name? Tesla V100-SXM2-32GB
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
```

Also, this other config file, which is very similar to my other one (same dataset), but uses Cascade Mask R-CNN in place of HTC, works perfectly fine:

```python
# base config
_base_ = ['/mmdetection/configs/cascade_rcnn/cascade_mask_rcnn_r101_fpn_20e_coco.py']

#### dataset-related parameters: edit accordingly when changing dataset
# classes
classes = ('balloon',)
n_classes = len(classes)
model = dict(
    roi_head=dict(
        bbox_head=[
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=n_classes,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.1, 0.1, 0.2, 0.2]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=n_classes,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.05, 0.05, 0.1, 0.1]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0,
                               loss_weight=1.0)),
            dict(
                type='Shared2FCBBoxHead',
                in_channels=256,
                fc_out_channels=1024,
                roi_feat_size=7,
                num_classes=n_classes,
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[0.033, 0.033, 0.067, 0.067]),
                reg_class_agnostic=True,
                loss_cls=dict(
                    type='CrossEntropyLoss',
                    use_sigmoid=False,
                    loss_weight=1.0),
                loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0))
        ],
        mask_head=dict(
            type='FCNMaskHead',
            num_classes=n_classes)
    )
)

########################################################################### 
# dataset settings
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/train.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
    val=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/validation.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
    test=dict(
        type='CocoDataset',
        ann_file=
        '/data/balloon/annotations/validation.json',
        img_prefix=
        '/data/balloon/images/',
        classes=classes),
)

evaluation = dict(metric=['bbox', 'segm'], save_best='bbox_mAP')
# optimizer settings
optimizer = dict(type='SGD', lr=0.00125)
lr_config = dict(  
    step=[9, 16]) 
# workflow and workdir settings
runner = dict(type='EpochBasedRunner', max_epochs=20)
checkpoint_config = dict(interval=-1) 
workflow = [('train', 1), ('val', 1)] 
work_dir = 'logs/test_htc_without_semantic_head'
## logger settings
log_config = dict(
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
```

**Comment by hhaAndroid** [comment]
@AndreaPi I have successfully trained the htc_r50 model on v100, but there is no problem. The r101 model consumes a lot of memory, and the OOM problem is more difficult to determine.

**Comment by AndreaPi** [comment]
I'm using `htc_without_semantic` instead of `htc`, but you're right: if I switch to a ResNet-50 backbone instead of a ResNet-101 one, the OOM error goes away. I'm surprised that with ResNet-101, a single V100 with 32 Gb is not enough, but apparently this is how it is. Thanks

**Comment by jaideep11061982** [comment]
@AndreaPi are you able to run ..
when I add keys gt_semantic
i get a key error ..
when i remove it , i get an error 
```
/kaggle/working/mmdetection/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py in loss(self, mask_pred, labels)
    101     @force_fp32(apply_to=('mask_pred', ))
    102     def loss(self, mask_pred, labels):
--> 103         labels = labels.squeeze(1).long()
    104         loss_semantic_seg = self.criterion(mask_pred, labels)
    105         loss_semantic_seg *= self.loss_weight

AttributeError: 'NoneType' object has no attribute 'squeeze'
```
 
In order to use HTC with semantic head what is needed in annoations..

**Comment by AndreaPi** [comment]
> @AndreaPi are you able to run .. when I add keys gt_semantic i get a key error .. when i remove it , i get an error
> 
> ```
> /kaggle/working/mmdetection/mmdet/models/roi_heads/mask_heads/fused_semantic_head.py in loss(self, mask_pred, labels)
>     101     @force_fp32(apply_to=('mask_pred', ))
>     102     def loss(self, mask_pred, labels):
> --> 103         labels = labels.squeeze(1).long()
>     104         loss_semantic_seg = self.criterion(mask_pred, labels)
>     105         loss_semantic_seg *= self.loss_weight
> 
> AttributeError: 'NoneType' object has no attribute 'squeeze'
> ```
> 
> In order to use HTC with semantic head what is needed in annoations..

I used HTC **without** semantic head. If you're using HTC **with** semantic head, I can't help.
