### ISSUE TITLE
RuntimeError: No rendezvous handler for env:// on Windows

### ISSUE THREAD

**Issue by PPeanutButter** [open-mmlab/mmdetection#6436]
**Describe the bug**
run dist_train.py on windows, mmdet v2.17.0

**Reproduction**

1. What command or script did you run?

```none
python -m torch.distributed.launch --nproc_per_node=2 --master_port=29501 train.py ../configs/panrunqiu/pan_r50_f
pn.py --launcher pytorch
```

**Environment**

train.py just works fine

**Error traceback**
```none
(openmmlab) D:\Research\mmdetection\tools>python -m torch.distributed.launch --nproc_per_node=2 --master_port=29501 train.py ../configs/panrunqiu/pan_r50_f
pn.py --launcher pytorch
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable f
or optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 121, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    main()
  File "train.py", line 121, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\dist_utils.py", line 32, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "D:\Anaconda\envs\openmmlab\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\openmmlab\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "D:\Anaconda\envs\openmmlab\lib\site-packages\torch\distributed\launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Anaconda\\envs\\openmmlab\\python.exe', '-u', 'train.py', '--local_rank=1', '../configs/panrunqiu/pan_r50_fpn
.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

```

**Comment by RangiLyu** [comment]
What is your pytorch version? This error is because your env does not support distributed training.

**Comment by PPeanutButter** [comment]
pytorch 1.7.1 with py3.7_cuda110_cudnn8_0 from official site

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年11月4日 11:18
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [open-mmlab/mmdetection] RuntimeError: No rendezvous handler for env:// on Windows (Issue #6436)


What is your pytorch version? This error is because your env does not support distributed training.

―

**Comment by RangiLyu** [comment]
It is highly possible that your distributed environment is not set correctly. Please check.
