### ISSUE TITLE
SSD512 VOC Training AssertionError

### ISSUE THREAD

**Issue by Leejunyee** [open-mmlab/mmdetection#6438]
i just use the model config to train ssd512, it happens this AssertionError, the config file didn't change ,i don't know how to deal with this error.
Traceback (most recent call last):
  File "tools/train.py", line 207, in <module>
    main()
  File "tools/train.py", line 203, in main
    meta=meta)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\apis\train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 129, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)#核心代码
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 31, in run_iter
    **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\parallel\data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\models\detectors\base.py", line 238, in train_step
    losses = self(**data)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\models\detectors\single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\base_dense_head.py", line 55, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "D:\Professtion\Anaconda\envs\openmmlab\lib\site-packages\mmdet\models\dense_heads\ssd_head.py", line 288, in loss
    assert len(featmap_sizes) == self.anchor_generator.num_levels
AssertionError

**Comment by RangiLyu** [comment]
Need to check whether your model config is correct. Please refer to this https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/ssd300.py
We refactored SSD 4 months ago. Please make sure your configs and codes are all upgraded to the latest version.

**Comment by Leejunyee** [comment]
> Need to check whether your model config is correct. Please refer to this https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/models/ssd300.py We refactored SSD 4 months ago. Please make sure your configs and codes are all upgraded to the latest version.

I found that the config is consistent with the MMdetection' Github Project. I ask for help in the community, be told that the config of SSD512_VOC should be similar the SSD512_COCO, i just the revise the 'model' item, replace the original with SSD512_COCO, just for the 'model=dict(xxxxx)' only . And finally, it works. get done this bug, run successfuuly!
