### ISSUE TITLE
Error in saving best checkpoint

### ISSUE THREAD

**Issue by sarmientoj24** [open-mmlab/mmdetection#6451]
Received this error when enabling `save_best='bbox_mAP'` in evaluation config.

Error:
```
Traceback (most recent call last):
  File "tools/train.py", line 208, in <module>
    main()
  File "tools/train.py", line 203, in main
    meta=meta,
  File "/home/james_sarmiento/pave/semi_supervised_pavement_detector/ssod/apis/train.py", line 207, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/james_sarmiento/anaconda3/envs/pave/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/james_sarmiento/anaconda3/envs/pave/lib/python3.6/site-packages/mmcv/runner/iter_based_runner.py", line 66, in train
    self.call_hook('after_train_iter')
  File "/home/james_sarmiento/anaconda3/envs/pave/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/james_sarmiento/pave/semi_supervised_pavement_detector/ssod/utils/hooks/submodules_evaluation.py", line 37, in after_train_iter
    self._do_evaluate(runner)
  File "/home/james_sarmiento/pave/semi_supervised_pavement_detector/ssod/utils/hooks/submodules_evaluation.py", line 100, in _do_evaluate
    self._save_ckpt(runner, best_score)
  File "/home/james_sarmiento/anaconda3/envs/pave/lib/python3.6/site-packages/mmcv/runner/hooks/evaluation.py", line 296, in _save_ckpt
    runner.work_dir, best_ckpt_name, create_symlink=False)
TypeError: save_checkpoint() takes 2 positional arguments but 3 were given
```

Any way to save best checkpoint?

**Comment by hhaAndroid** [comment]
@sarmientoj24 Please use the issue template
