### ISSUE TITLE
〇〇LrUpdaterHook: __init__() got an unexpected keyword argument 'step'

### ISSUE THREAD

**Issue by abebe9849** [open-mmlab/mmdetection#6456]
When I followed this [config](https://github.com/ZFTurbo/2nd-place-solution-for-VinBigData-Chest-X-ray-Abnormalities-Detection/blob/master/part_ivan/configs/train/cascade_rcnn_r50_rfp_1x_xray_stage1_fold0.py), I found below error.
```
Traceback (most recent call last):
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/runner/hooks/lr_updater.py", line 264, in __init__
    super(CosineAnnealingLrUpdaterHook, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'step'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u094724e/vinbig/src/mmdetection/tools/train.py", line 189, in <module>
    main()
  File "/home/u094724e/vinbig/src/mmdetection/tools/train.py", line 178, in main
    train_detector(
  File "/home/u094724e/vinbig/src/mmdetection/mmdet/apis/train.py", line 129, in train_detector
    runner.register_training_hooks(cfg.lr_config, optimizer_config,
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 538, in register_training_hooks
    self.register_lr_hook(lr_config)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 417, in register_lr_hook
    hook = mmcv.build_from_cfg(lr_config, HOOKS)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CosineAnnealingLrUpdaterHook: __init__() got an unexpected keyword argument 'step'
```
When I changed to "lr_config = dict(policy='poly', power=0.9, min_lr=1e-4, by_epoch=False)", 

"TypeError: PolyLrUpdaterHook: __init__() got an unexpected keyword argument 'step' "was happened.

mmdet.__version__=='2.18.0',mmcv.__version__='1.3.16'

I would be grateful if anyone could help me if I could understand the cause.

**Comment by hhaAndroid** [comment]
@abebe9849 
```python
lr_config = dict( _delete_=True, policy='poly', power=0.9, min_lr=1e-4, by_epoch=False)
```

**Comment by abebe9849** [comment]
thanks!! it works!!
