### ISSUE TITLE
 No module named 'mmdet.models.dense_heads.rpn_test_mixin'

### ISSUE THREAD

**Issue by Xbox-9527** [open-mmlab/mmdetection#6458]
Just like the title,when I run this " python demo/image_demo.py".

I got the error report, as follows:

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
TorchVision: 0.6.0+cu101
OpenCV: 4.5.4-dev
MMCV: 1.3.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.18.0+

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
   from source

**Error traceback**
Traceback (most recent call last):
  File "demo/image_demo.py", line 5, in <module>
    from mmdet.apis import (async_inference_detector, inference_detector,
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/datasets/__init__.py", line 12, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/datasets/utils.py", line 9, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead, RPNHead_involution
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/dense_heads/__init__.py", line 24, in <module>
    from .rpn_head_involution import RPNHead_involution
  File "/home/YJJ/CodeReuse/mmdetection-master/mmdet/models/dense_heads/rpn_head_involution.py", line 13, in <module>
    from .rpn_test_mixin import RPNTestMixin
ModuleNotFoundError: No module named 'mmdet.models.dense_heads.rpn_test_mixin'

**Comment by Xbox-9527** [comment]
I commented out them in the every init.py ,so I can use it now.
Maybe there lacks some files
