### ISSUE TITLE
Unsupported type <class 'set'> of classes

### ISSUE THREAD

**Issue by XIANYUNYEHE-DEL** [open-mmlab/mmdetection#6459]
**Describe the bug**

Hi ,  dear editor
I write the cfg to implement model based on your official video, but there is something wrong whit the dataloader read my dataset
**Reproduction**

1. What command or script did you run?
`python   tools/test.py  configs/luna16/mask_rcnn_swin-t-p4-w7_fpn_1x_coco_luna16.py`
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I changed the classes, roi_head in order to match my custom dataset.
3. What dataset did you use?
Custom Coco Dataset.
4. Specific configuration `filemask_rcnn_swin-t-p4-w7_fpn_1x_coco_luna16.py` code
```
_base_ = 'mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py'

model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=1),
        mask_head=dict(num_classes=1)),
        backbone = dict(
            init_cfg=dict(
                type='Pretrained',
                checkpoint='checkpoints/swin_tiny_patch4_window7_224.pth'
            )
        )
)

dataset_type = 'CocoDataset'
classes = ('nodule',)
data = dict(
    train=dict(
        img_prefix='/data5/zhw/luna16/coco/train/',
        classes=classes,
        ann_file='/data5/zhw/luna16/coco/annotations/train_luna16.json'),
    val=dict(
        img_prefix='/data5/zhw/luna16/coco/val/',
        classes=classes,
        ann_file='/data5/zhw/luna16/coco/annotations/val_luna16.json'),
    test=dict(
        img_prefix='/data5/zhw/luna16/coco/val/',
        classes=classes,
        ann_file='/data5/zhw/luna16/coco/annotations/val_luna16.json'))

load_from = 'checkpoints/swin_tiny_patch4_window7_224.pth'
pretrained = 'checkpoints/swin_tiny_patch4_window7_224.pth'
```

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: False
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.5.4-dev
MMCV: 1.3.16
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.17.0+

```

**Error traceback**
If applicable, paste the error trackback here.
```
 Traceback (most recent call last):
  File "/home/zhw/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/zhw/code/tmp/pycharm_project_597/mmdet/datasets/custom.py", line 74, in __init__
    self.CLASSES = self.get_classes(classes)
  File "/home/zhw/code/tmp/pycharm_project_597/mmdet/datasets/custom.py", line 261, in get_classes
    raise ValueError(f'Unsupported type {type(classes)} of classes.')
ValueError: Unsupported type <class 'set'> of classes.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 166, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zhw/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 78, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zhw/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: CocoDataset: Unsupported type <class 'set'> of classes.
```

**Comment by hhaAndroid** [comment]
@XIANYUNYEHE-DEL Please use the issue template to help us troubleshoot the cause.

**Comment by XIANYUNYEHE-DEL** [comment]
> @XIANYUNYEHE-DEL Please use the issue template to help us troubleshoot the cause.

Ok, I have modified my issue format and found the problem in my annotation file.
