### ISSUE TITLE
RepPointsDetector: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by abebe9849** [open-mmlab/mmdetection#6463]
When I used this config's [model setting](https://github.com/yujiariyasu/siim_covid19_detection/blob/main/ian-siim/mmdetection/configs/swin/swin_rsna002.py) ,
```

Traceback (most recent call last):
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/u094724e/vinbig/src/mmdetection/mmdet/models/detectors/reppoints_detector.py", line 22, in __init__
    super(RepPointsDetector,
  File "/home/u094724e/vinbig/src/mmdetection/mmdet/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/u094724e/vinbig/src/mmdetection/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u094724e/vinbig/src/mmdetection/tools/train.py", line 189, in <module>
    main()
  File "/home/u094724e/vinbig/src/mmdetection/tools/train.py", line 159, in main
    model = build_detector(
  File "/home/u094724e/vinbig/src/mmdetection/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/u094724e/anaconda3/envs/vinbig/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: RepPointsDetector: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'
```

was happened. I tried adding _delete_ = True, but it didn't work.

mmdet.version=='2.18.0',mmcv.version='1.3.16'

I would be grateful if anyone could help me if I could understand the cause.

**Comment by abebe9849** [comment]
I was able to train correctly when using the official swin configuration. Thank you.
