### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Si-VVON** [open-mmlab/mmdetection#6465]
I need you guys' help!!!!!

**command**
python  tools/train.py /data/siwon/mmdetection/configs/_base_/resvggnew /mask_1x_r50.py

**error**
Traceback (most recent call last):
  File "/data/siwon/mmdetection/tools/train.py", line 189, in <module>
    main()
  File "/data/siwon/mmdetection/tools/train.py", line 185, in main
    meta=meta)
  File "/home/siwon/.conda/envs/mm/lib/python3.7/site-packages/mmdet/apis/train.py", line 100, in train_detector
    assert cfg.total_epochs == cfg.runner.max_epochs
AssertionError

**Environment**
python = 3.7 pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 mmcv-full==1.3.5
in centos 8

**Comment by hhaAndroid** [comment]
@Si-VVON This shows that there is an error in the config, please check the configuration.
