### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by vincent507cpu** [open-mmlab/mmdetection#6466]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
- After training one epoch, the following error raised. I checked data, found that `self.cat_ids` is `[]`. I checked the official `pycocotools` on the same dataset, which can return categories.
```
from pycocotools.coco import COCO
coco = COCO('/work/zhaiwj/mmdetection/data/coco/annotations/instances_train2017.json')
cats = ['motorbike', 'aeroplane', 'dog', 'diningtable', 'chair', 'car', 'person', 'train', 'bus', 'bottle', 'horse', 'bird', 'tvmonitor', 'cat', 'boat', 'bicycle', 'pottedplant', 'sofa', 'cow', 'sheep']
cat_ids = coco.getCatIds(cats)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
- update:
I checked `COCO` class in `mmdet` package, it can also return cats.
```
from mmdet.datasets.api_wrappers import COCO

coco = COCO('/work/zhaiwj/mmdetection/data/coco/annotations/instances_train2017.json')
coco.get_cat_ids()

# loading annotations into memory...
# Done (t=0.14s)
# creating index...
# index created!
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```
**Reproduction**

1. What command or script did you run?

```none
python tools/train.py configs/faster_rcnn/my_faster_rcnn_config.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
```
# my_faster_rcnn_config.py
_base_ = './faster_rcnn_r50_fpn_1x_coco.py'

model = dict(
    roi_head = dict(
        bbox_head = dict(
            num_classes=20
        )
    )
)
classes = (
    'motorbike', 'aeroplane', 'dog', 'diningtable', 'chair', 'car', 
    'person', 'train', 'bus', 'bottle', 'horse', 'bird', 'tvmonitor', 
    'cat', 'boat', 'bicycle', 'pottedplant', 'sofa', 'cow', 'sheep'
)
data_root = '/work/zhaiwj/mmdetection/data/coco/'
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    train=dict(
        img_prefix=data_root + 'train2017/',
        classes=classes,
        ann_file=data_root + 'annotations/instances_train2017.json'),
    val=dict(
        img_prefix=data_root + 'val2017/',
        classes=classes,
        ann_file=data_root + 'annotations/instances_val2017.json'),
    test=dict(
        img_prefix=data_root + 'val2017/',
        classes=classes,
        ann_file=data_root + 'annotations/instances_val2017.json'))

runner = dict(type='EpochBasedRunner', max_epochs=12)

optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0001)
```
3. What dataset did you use?
official VOC dataset using [this script](https://github.com/vincent507cpu/object_detection/blob/main/generate_dataset.py) to change format

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.9.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1
OpenCV: 4.5.4-dev
MMCV: 1.3.16
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.18.0+9874180
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]: conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
--------------------------
--------------------------
cat_ids: [] # modify source code to show variable
--------------------------
--------------------------
Traceback (most recent call last):
  File "tools/train.py", line 204, in <module>
    main()
  File "tools/train.py", line 193, in main
    train_detector(
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/apis/train.py", line 177, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 20, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 359, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 420, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 365, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 297, in results2json
    json_results = self._det2json(results)
  File "/home/zhaiwj/miniconda3/envs/cv/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 234, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@vincent507cpu The configuration file looks correct. You can use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py script to visualize first, so it is easy to debug

**Comment by vincent507cpu** [comment]
@hhaAndroid Thank you for the help. This script returned
```loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
[                                                  ] 0/5717, elapsed: 0s, ETA:
[                                ] 1/5717, 0.5 task/s, elapsed: 2s, ETA: 12529s
[                                ] 2/5717, 0.5 task/s, elapsed: 4s, ETA: 12571s
...
```
is it what I should expect?

**Comment by hhaAndroid** [comment]
@vincent507cpu OK
