### ISSUE TITLE
TypeError: CocoDataset: string indices must be integers

### ISSUE THREAD

**Issue by jiangxinufo** [open-mmlab/mmdetection#6468]
unexpected key in source state_dict: fc.weight, fc.bias

E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py:154: UserWarning: CustomDataset does not support filtering empty gt images.
  warnings.warn(
Traceback (most recent call last):
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmcv-1.3.1\mmcv\utils\registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py", line 96, in __init__
    valid_inds = self._filter_imgs()
  File "E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py", line 158, in _filter_imgs
    if min(img_info['width'], img_info['height']) >= min_size:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/mmdetection/week2_mmdet/Week2_mmdet/mmdetection-2.11.0/tools/train.py", line 187, in <module>
    main()
  File "E:/mmdetection/week2_mmdet/Week2_mmdet/mmdetection-2.11.0/tools/train.py", line 163, in main
    datasets = [build_dataset(cfg.data.train)]
  File "E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\mmdet\datasets\builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmcv-1.3.1\mmcv\utils\registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset: string indices must be integers

**Comment by jiangxinufo** [comment]
def _filter_imgs(self, min_size=32):
        """Filter images too small."""
        if self.filter_empty_gt:
            warnings.warn(
                'CustomDataset does not support filtering empty gt images.')
        valid_inds = []
        for i, img_info in enumerate(self.data_infos):
            if min(img_info['width'], img_info['height']) >= min_size: //img_info有错误
                valid_inds.append(i)
        return valid_inds

**Comment by jiangxinufo** [comment]
`def _filter_imgs(self, min_size=32):
    """Filter images too small."""
    if self.filter_empty_gt:
        warnings.warn(
            'CustomDataset does not support filtering empty gt images.')
    valid_inds = []
    for i, img_info in enumerate(self.data_infos):
        if min(img_info['width'], img_info['height']) >= min_size: //img_info有错误
            valid_inds.append(i)
    return valid_inds`

**Comment by jiangxinufo** [comment]
2021-11-10 13:33:03,259 - mmdet - INFO - Distributed training: False
2021-11-10 13:33:04,464 - mmdet - INFO - Config:
model = dict(
    type='MaskRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=2,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=2,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.4),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.4),
            max_per_img=100,
            mask_thr_binary=0.5)))
dataset_type = 'CocoDataset'
data_root = 'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(500, 300), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(500, 300),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    train=dict(
        type='CocoDataset',
        ann_file=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/annotations/instances_train2017.json',
        img_prefix=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/train2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(type='Resize', img_scale=(500, 300), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ]),
    val=dict(
        type='CocoDataset',
        ann_file=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/annotations/instances_val2017.json',
        img_prefix=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(500, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/annotations/instances_val2017.json',
        img_prefix=
        'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\tools\data\coco/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(500, 300),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(metric=['bbox', 'segm'])
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[20, 25])
runner = dict(type='EpochBasedRunner', max_epochs=30)
checkpoint_config = dict(interval=4)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = 'E:\mmdetection\week2_mmdet\Week2_mmdet\mmdetection-2.11.0\weights\mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth'
resume_from = None
workflow = [('train', 1)]
work_dir = 'train_grain_128'
gpu_ids = range(0, 1)

2021-11-10 13:33:04,862 - mmdet - INFO - load model from: torchvision://resnet50
2021-11-10 13:33:04,863 - mmdet - INFO - Use load_from_torchvision loader
2021-11-10 13:33:05,231 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py:155: UserWarning: CustomDataset does not support filtering empty gt images.
  'CustomDataset does not support filtering empty gt images.')
Traceback (most recent call last):
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmcv-1.3.1\mmcv\utils\registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py", line 96, in __init__
    valid_inds = self._filter_imgs()
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmdet\datasets\custom.py", line 158, in _filter_imgs
    if min(img_info['width'], img_info['height']) >= min_size:
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 163, in main
    datasets = [build_dataset(cfg.data.train)]
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmdet\datasets\builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "e:\mmdetection\week2_mmdet\week2_mmdet\mmdetection-2.11.0\mmcv-1.3.1\mmcv\utils\registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset: string indices must be integers

**Comment by hhaAndroid** [comment]
@jiangxinufo Please check if your label is correct.

**Comment by alaa-shubbak** [comment]
I have the same error , and i checked my dataset annotation 
here is a part of them:

<img width="522" alt="222733248-c4dd3b47-90a0-465d-a5c0-cdc9f4e643fe" src="https://user-images.githubusercontent.com/10245810/222968971-0bf80198-1e1d-4e9b-b22d-b6fa8a0ae0d7.png">


![222539386-df1931cf-fd4e-4752-9c33-c299983f71f4](https://user-images.githubusercontent.com/10245810/222968976-9708c80e-408d-4364-b7f6-d803aef89c9e.png)

I don't know where is the error /mistake in them. can you please help.

**Comment by alaa-shubbak** [comment]
any help on this please !
i have a look on dataset of animals/fly. 

I found the annotation there is has more info in category part as bellow:
![fly_ann](https://user-images.githubusercontent.com/10245810/222977526-98b67f04-8cfc-4dd0-9ad3-6cc0e483da20.jpg)

I try it also and the error still present.
