### ISSUE TITLE
Test Mask R-CNN on Cityscapes test with 1 GPU

### ISSUE THREAD

**Issue by leo-hao** [open-mmlab/mmdetection#6477]
Hello, when I learn the docs_zh-CN, and reimpliment the example in 1_exist_data_model.md,  I was stumped by a problem.
First, because I can only use one GPU, I successfully run the following command Test Mask R-CNN on COCO test-dev with 1Gpu
```
python tools/test.py  \
configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py  \
checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth \
--format-only \
--options "jsonfile_prefix=./mask_rcnn_test-dev_results"
```

However, when I run bellowing command to Test Mask R-CNN on COCO test-dev with 1Gpu
```
python tools/test.py \
configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py\
checkpoints/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth \
--format-only \
--options "txtfile_prefix=./mask_rcnn_cityscapes_test_results"
```
Then failed.

**Describe the issue**

```
(liuhaommlab) cv428@428:/home/data/liuhao/code/mmdetection-master$ python tools/test.py configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py checkpoints/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth --format-only --options "txtfile_prefix=./mask_rcnn_cityscapes_test_results"
tools/test.py:116: UserWarning: --options is deprecated in favor of --eval-options
  warnings.warn('--options is deprecated in favor of --eval-options')
loading annotations into memory...
Done (t=0.26s)
creating index...
index created!
/home/data/liuhao/code/mmdetection-master/mmdet/core/anchor/builder.py:17: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader
[                                                  ] 0/1525, elapsed: 0s, ETA:/home/data/liuhao/code/mmdetection-master/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/data/liuhao/code/mmdetection-master/mmdet/core/anchor/anchor_generator.py:361: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  '``single_level_grid_anchors`` would be deprecated soon. '
[                                                  ] 8/1525, 3.7 task/s, elapsed: 2s, ETA:   405sTraceback (most recent call last):
  File "tools/test.py", line 252, in <module>
    main()
  File "tools/test.py", line 218, in main
    args.show_score_thr)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/apis/test.py", line 28, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/detectors/two_stage.py", line 184, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/roi_heads/standard_roi_head.py", line 266, in simple_test
    x, img_metas, det_bboxes, det_labels, rescale=rescale)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/roi_heads/test_mixins.py", line 277, in simple_test_mask
    rescale)
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 298, in get_seg_masks
    skip_empty=device.type == 'cpu')
  File "/home/data/liuhao/code/mmdetection-master/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 407, in _do_paste_mask
    masks.to(dtype=torch.float32), grid, align_corners=False)
  File "/home/cv428/anaconda3/envs/liuhaommlab/lib/python3.6/site-packages/torch/nn/functional.py", line 3391, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: CUDA out of memory. Tried to allocate 416.00 MiB (GPU 0; 9.78 GiB total capacity; 1.10 GiB already allocated; 43.56 MiB free; 1.28 GiB reserved in total by PyTorch)
```

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. What config dir you run?

```none
python tools/test.py configs/cityscapes/mask_rcnn_r50_fpn_1x_cityscapes.py checkpoints/mask_rcnn_r50_fpn_1x_cityscapes_20201211_133733-d2858245.pth --format-only --options "txtfile_prefix=./mask_rcnn_cityscapes_test_results"
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
first, in tools/test.py, I added "os.environ['CUDA_VISIBLE_DEVICES'] = '1' "
In 'mmdetection-master/configs/_base_/datasets/cityscapes_instance.py'
I try to modify the test_pipeline img_scale=(2048, 1024) to (256,128)
But it gives the same error.

4. What dataset did you use?
cityscapes 

**Environment**
(liuhaommlab) cv428@428:/home/data/liuhao/code/mmdetection-master$ python mmdet/utils/collect_env.py
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.6.13 | packaged by conda-forge | (default, Sep 23 2021, 07:56:31) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2: GeForce RTX 3080
CUDA_HOME: /usr/local/cuda-11.0
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu110
OpenCV: 4.5.1
MMCV: 1.3.16
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.17.0+

```
(base) cv428@428:~$ nvidia-smi
Wed Nov 10 19:37:27 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3080    Off  | 00000000:04:00.0 Off |                  N/A |
| 69%   60C    P2   288W / 370W |   7307MiB / 10018MiB |     86%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3080    Off  | 00000000:09:00.0 Off |                  N/A |
|  0%   24C    P8    23W / 370W |      8MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3080    Off  | 00000000:82:00.0 Off |                  N/A |
| 66%   54C    P2   177W / 340W |   6663MiB / 10018MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1459      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A   2997726      C   python                           7299MiB |
|    1   N/A  N/A      1459      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      1459      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A   2031107      C   python                           6655MiB |
+-----------------------------------------------------------------------------+

```
I don't know where to modify the code to make  it run successfully...
Looking forward to your answer！

**Comment by AronLin** [comment]
Maybe the code is right but your Memory of GPU is too small.

**Comment by mailoc123** [comment]
Can you show me how to download checkpoints folder.?

Thank you so much.

**Comment by leo-hao** [comment]
go to mmdetection/docs/model_zoo.md；you can select the backbone what you want ,;

**Comment by leo-hao** [comment]
> Can you show me how to download checkpoints folder.?
> 
> Thank you so much.
go to mmdetection/docs/model_zoo.md；you can select the backbone what you want ,;
