### ISSUE TITLE
yolox publish AttributeError: 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by yulinhuyang** [open-mmlab/mmdetection#6485]
I train yolox s model.and I try to del ema weight use publish model. when I use  

        torch.save(checkpoint, out_file, _use_new_zipfile_serialization=False)

A error happens, can you help me about the error.

 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 374, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 436, in _legacy_save
    pickle_module.dump(MAGIC_NUMBER, f, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/model_convert/publish_model.py", line 47, in <module>
    main()
  File "tools/model_convert/publish_model.py", line 43, in main
    process_checkpoint(args.in_file)
  File "tools/model_convert/publish_model.py", line 32, in process_checkpoint
    torch.save(checkpoint, out_file, _use_new_zipfile_serialization=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 374, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 225, in __exit__
    self.file_like.flush()
AttributeError: 'NoneType' object has no attribute 'flush'

**Comment by hhaAndroid** [comment]
@yulinhuyang Please make sure the output path exists.
