### ISSUE TITLE
yolox转onnx出现问题：AttributeError: 'YOLOXHead' object has no attribute 'bbox_coder'

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmdetection#6487]
/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py:407: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cfg.get('nms_pre', -1), device=device, dtype=torch.long)
/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py:427: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/core/export/onnx_helper.py:63: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k <= 0 or size <= 0:
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 357, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 112, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/utils.py", line 459, in _model_to_graph
    _retain_param_name)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/utils.py", line 422, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/jit/_trace.py", line 1160, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1039, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 169, in onnx_export
    *outs, img_metas, with_nms=with_nms)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 483, in onnx_export
    bboxes = self.bbox_coder.decode(
  File "/disk/conda/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'YOLOXHead' object has no attribute 'bbox_coder'

**Comment by hhaAndroid** [comment]
@betterhalfwzm Sorry. We have not yet supported YOLOX export ONNX, but community PR is welcome.

**Comment by aeoleader** [comment]
For anyone who encounters this issue, a temporary workaround is to modify code on line 168 in detectors/single_stage.py.
```python
def onnx_export(...):
    ...
    # line 168 in detectors/single_stage.py
    try:
        det_bboxes, det_labels = self.bbox_head.onnx_export(
                *outs, img_metas, with_nms=with_nms)
    except:
        det_bboxes, det_labels = self.bbox_head.get_bboxes(*outs, img_metas)
    ...
```

**Comment by jinfagang** [comment]
A better way is to written a customized YOLOXHeadPatch and injected into config file, then you can implement onnx_eport method without changing any mmdet code.

now, it can be easily convert to onnx for YOLOX. and you can tweaking any output format for customization export, for instance, exporting for ONNXRuntime inject nms op.

![image](https://user-images.githubusercontent.com/21303438/153186505-0cd5cb1c-7c04-474a-80ce-5154adf887b7.png)

**Comment by VJoer** [comment]
> constants

Hello, Can you post your complete the steps and code? Thank u very much

**Comment by VJoer** [comment]
> A better way is to written a customized YOLOXHeadPatch and injected into config file, then you can implement onnx_eport method without changing any mmdet code.
> 
> now, it can be easily convert to onnx for YOLOX. and you can tweaking any output format for customization export, for instance, exporting for ONNXRuntime inject nms op.
> 
> ![image](https://user-images.githubusercontent.com/21303438/153186505-0cd5cb1c-7c04-474a-80ce-5154adf887b7.png)

Hello, Can you post your complete the steps and code? Thank u very much

**Comment by jinfagang** [comment]
using mmdeploy

**Comment by maisonhai3** [comment]
> For anyone who encounters this issue, a temporary workaround is to modify code on line 168 in detectors/single_stage.py.
> 
> ```python
> def onnx_export(...):
>     ...
>     # line 168 in detectors/single_stage.py
>     try:
>         det_bboxes, det_labels = self.bbox_head.onnx_export(
>                 *outs, img_metas, with_nms=with_nms)
>     except:
>         det_bboxes, det_labels = self.bbox_head.get_bboxes(*outs, img_metas)
>     ...
> ```

```
It almost works, we need to add `[0]` after get returns from `.get_bboxes()`.
        try:
            det_bboxes, det_labels = self.bbox_head.onnx_export(
                *outs, img_metas, with_nms=with_nms)
        except:
            (det_bboxes, det_labels) = self.bbox_head.get_bboxes(
                *outs, img_metas)[0]
```
