### ISSUE TITLE
Problem with augmentation with cascade rcnn

### ISSUE THREAD

**Issue by ridasalam** [open-mmlab/mmdetection#650]
**I get this error:**

Traceback (most recent call last):
  File "/home/rs/VR/External_Repos/mmdetection/tools/supervisely_train.py", line 106, in <module>
    main()
  File "/home/rs/VR/External_Repos/mmdetection/tools/supervisely_train.py", line 102, in main
    logger=logger)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/apis/train.py", line 124, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/runner/runner.py", line 357, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/runner/runner.py", line 259, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/repeat_dataset.py", line 16, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/supervisely_custom.py", line 145, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/supervisely_custom.py", line 218, in prepare_train_img
    scale_factor, flip)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/transforms.py", line 106, in __call__
    for mask in masks
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/transforms.py", line 106, in <listcomp>
    for mask in masks
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/image/transforms/resize.py", line 101, in imrescale
    type(scale)))
TypeError: Scale must be a number or tuple of int, but got <class 'numpy.ndarray'>

**My config file is:**
```python
# model settings
model = dict(
    type='CascadeRCNN',
    num_stages=3,
    pretrained='modelzoo://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_scales=[8],
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[4, 8, 16, 32, 64],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        use_sigmoid_cls=True),
    bbox_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=7, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=81,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=81,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.05, 0.05, 0.1, 0.1],
            reg_class_agnostic=True),
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=81,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.033, 0.033, 0.067, 0.067],
            reg_class_agnostic=True)
    ],
    mask_roi_extractor=dict(
        type='SingleRoIExtractor',
        roi_layer=dict(type='RoIAlign', out_size=14, sample_num=2),
        out_channels=256,
        featmap_strides=[4, 8, 16, 32]),
    mask_head=dict(
        type='FCNMaskHead',
        num_convs=4,
        in_channels=256,
        conv_out_channels=256,
        num_classes=81))
# model training and testing settings
train_cfg = dict(
    rpn=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.7,
            neg_iou_thr=0.3,
            min_pos_iou=0.3,
            ignore_iof_thr=-1),
        sampler=dict(
            type='RandomSampler',
            num=256,
            pos_fraction=0.5,
            neg_pos_ub=-1,
            add_gt_as_proposals=False),
        allowed_border=0,
        pos_weight=-1,
        smoothl1_beta=1 / 9.0,
        debug=False),
    rcnn=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.6,
                min_pos_iou=0.6,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.7,
                min_pos_iou=0.7,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1, 0.5, 0.25])
test_cfg = dict(
    rpn=dict(
        nms_across_levels=False,
        nms_pre=2000,
        nms_post=2000,
        max_num=2000,
        nms_thr=0.7,
        min_bbox_size=0),
    rcnn=dict(
        score_thr=0.05,
        nms=dict(type='nms', iou_thr=0.5),
        max_per_img=100,
        mask_thr_binary=0.5),
    keep_all_stages=False)
# dataset settings
dataset_type = 'myDatasetCustom'
data_root = '/home/rs/VR/External_Repos/mmdetection/data/my/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            ann_file=data_root + 'annotations/annotations_train_val.json',
            img_prefix=data_root + 'all_images_train_val/',
            img_scale=(1333, 800),
            img_norm_cfg=img_norm_cfg,
            size_divisor=32,
            flip_ratio=0.5,
            with_mask=True,
            with_crowd=True,
            with_label=True,
            extra_aug=dict(
                photo_metric_distortion=dict(
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                expand=dict(
                    mean=img_norm_cfg['mean'],
                    to_rgb=img_norm_cfg['to_rgb'],
                    ratio_range=(1, 4)),
                random_crop=dict(
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9), min_crop_size=0.3)),
            resize_keep_ratio=False)),
    val=dict(
        type=dataset_type,
        ann_file=data_root +  'annotations/annotations_val.json',
        img_prefix=data_root + 'val/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root +  'annotations/annotations_val.json',
        img_prefix=data_root + 'val/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_label=False,
        test_mode=True))
# optimizer
optimizer = dict(type='SGD', lr=0.0025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[8, 11])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=5,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 50
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = '/media/hdd/work_dirs/cascade_mask_rcnn_r50_fpn_1x_trial2'
load_from = '/home/rs/VR/External_Repos/mmdetection/checkpoints/cascade_mask_rcnn_r50_fpn_1x_20181123-88b170c9.pth'
resume_from = None # '/media/hdd/work_dirs/cascade_mask_rcnn_r50_fpn_1x/latest.pth'
workflow = [('train', 1)]
```

I tried to add augmentation to the config file.

**Comment by ridasalam** [comment]
**If i set resize_keep_ratio to True, i get the following:**


Traceback (most recent call last):
  File "/home/rs/VR/External_Repos/mmdetection/tools/supervisely_train.py", line 106, in <module>
    main()
  File "/home/rs/VR/External_Repos/mmdetection/tools/supervisely_train.py", line 102, in main
    logger=logger)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/apis/train.py", line 124, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/runner/runner.py", line 357, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/runner/runner.py", line 259, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/repeat_dataset.py", line 16, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/supervisely_custom.py", line 145, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/supervisely_custom.py", line 218, in prepare_train_img
    scale_factor, flip)
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/transforms.py", line 111, in __call__
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/rs/VR/External_Repos/mmdetection/mmdet/datasets/transforms.py", line 111, in <listcomp>
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/rs/anaconda3/envs/mmdet/lib/python3.7/site-packages/mmcv-0.2.7-py3.7.egg/mmcv/image/transforms/geometry.py", line 186, in impad
    assert shape[i] >= img.shape[i]
AssertionError

**Comment by ridasalam** [comment]
I think I know why. The random crop inside extra augmentation does not also crop the mask.

**Comment by liugl7** [comment]
> I think I know why. The random crop inside extra augmentation does not also crop the mask.

Excuse me，How did you solve this problem?
I use it in cascade-rcnn **without mask branch**, and I got the same error as you

**Comment by ridasalam** [comment]
I provide the mask as input to the extra aug def and I crop it. (Like it is done for the image here)

https://github.com/open-mmlab/mmdetection/blob/1cbc88e3f528fa27489b9d68595b47ddb5cb1f34/mmdet/datasets/extra_aug.py#L138

**Comment by anhtranhoang** [comment]
> I provide the mask as input to the extra aug def and I crop it. (Like it is done for the image here)
> 
> https://github.com/open-mmlab/mmdetection/blob/1cbc88e3f528fa27489b9d68595b47ddb5cb1f34/mmdet/datasets/extra_aug.py#L138

can you give me the code in your file extra_aug.py  , i have the same problem ! tks

**Comment by hellock** [comment]
This issue is outdated and the latest version should be ok.
