### ISSUE TITLE
Mismatch for num_classes and Cityscapes for custom classes

### ISSUE THREAD

**Issue by vakker** [open-mmlab/mmdetection#6532]
**Checklist**

1. [x] I have searched related issues but cannot get the expected help.
2. [x] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. [x] The bug has not been fixed in the latest version.

**Describe the bug**

When using custom number of classes with the Cityscapes dataset it raises:
```
AssertionError: The `num_classes` (1) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 8) in RepeatDataset
```

Seems to be the same as #4862 and #6334.
This should work based on the `configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person.py` example.

**Reproduction**

The `config.py`:
```python
_base_ = "cityscapes/faster_rcnn_r50_fpn_1x_cityscapes.py"

model = dict(roi_head=dict(bbox_head=dict(num_classes=1)))
classes = ('person', )
data = dict(
    train=dict(classes=classes),
    val=dict(classes=classes),
    test=dict(classes=classes))
```

1. What command or script did you run?

```none
python tools/train.py configs/config.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? -> see above
3. What dataset did you use? -> standard Cityscapes

**Environment**

```
sys.platform: linux
Python: 3.8.12 (default, Nov 17 2021, 08:17:37) [GCC 9.3.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.5.r11.5/compiler.30411180_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.5.4-dev
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.18.1+c76ab0e
```

**Bug fix**

Changing in `CityscapesDataset` the classes definition to `CLASSES = ('person',)` makes it work.

I don't know if this is actually a bug or intended behaviour, but based on the [example](https://mmdetection.readthedocs.io/en/v2.18.0/2_new_data_model.html) it should work without any modifications, and it's also unclear what the `classes=classes` bit does in the config for the dataset.

**Comment by hhaAndroid** [comment]
@vakker If you are not sure whether the modification is correct, you can use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/print_config.py script to print all the information

**Comment by vakker** [comment]
@hhaAndroid thanks, but the config is correct (it's actually the same modification that's [here](https://mmdetection.readthedocs.io/en/v2.18.0/2_new_data_model.html) and [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_caffe_fpn_mstrain_1x_coco-person.py)). The problem is with the dataset class, and not with the config.

**Comment by RangiLyu** [comment]
> @vakker If you are not sure whether the modification is correct, you can use the https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/print_config.py script to print all the information

Is this a potential bug of NumClassCheckHook? @jshilong Please take a look.

**Comment by vakker** [comment]
@RangiLyu @jshilong thanks for looking into this. 
Also, it's relevant, but might be a separate issue, is that if I provide a class that's not in the original Cityscapes dataset (e.g. balloon in the [example](https://mmdetection.readthedocs.io/en/v2.18.0/2_new_data_model.html)) but it's in my dataset, then it raises another error (even if I change the `CLASSES` in `CityscapesDataset`):
```
after_run:                                                                                                                                                                                                         (VERY_LOW    ) TextLoggerHook                                                                                                                                                                                      
 --------------------                                                                                                                                                                                              2021-11-18 11:00:57,049 - mmdet - INFO - workflow: [('train', 1)], max: 8 epochs                                                                                                                                   
2021-11-18 11:00:57,049 - mmdet - INFO - Checkpoints will be saved to /home/vince/workspace/work_dirs/mask_rcnn_r50_fpn_1x_test by HardDiskBackend.                                                 
Traceback (most recent call last):                                                                                                                                                                                 
  File "tools/train.py", line 189, in <module>                                                                                                                                                                         main()                                                                                                                                                                                                         
  File "tools/train.py", line 178, in main                                                                                                                                                                             train_detector(                                                                                                                                                                                                
  File "/home/vince/workspace/mmdetection/mmdet/apis/train.py", line 211, in train_detector                                                                                                                   runner.run(data_loaders, cfg.workflow)                                                                                                                                                                         
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run                                                                                            epoch_runner(data_loaders[i], **kwargs)                                                                                                                                                                        
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train                                                                                           for i, data_batch in enumerate(self.data_loader):                                                                                                                                                              
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__                                                                                          return self._get_iterator()                                                                                                                                                                                    
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator                                                                                 
    return _MultiProcessingDataLoaderIter(self)                                                                                                                                                                    
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 944, in __init__
    self._reset(loader, first_iter=True)
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 975, in _reset
    self._try_put_index()
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1209, in _try_put_index
    index = self._next_index()
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 512, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/vince/.pyenv/versions/p1/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 229, in __iter__
    for idx in self.sampler:
  File "/home/vince/workspace/mmdetection/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by jshilong** [comment]
You need to set group in your dataset, you can add it refering to 
https://github.com/open-mmlab/mmdetection/blob/a7a16afbf2a4bdb4d023094da73d325cb864838b/mmdet/datasets/custom.py#L103

**Comment by vakker** [comment]
@jshilong thanks for the suggestion, but I'm not using a custom dataset. Following the official tutorial ([here](https://mmdetection.readthedocs.io/en/v2.18.0/2_new_data_model.html)) reproduces the same error. It's unclear where `set_group_flag` comes into the picture.

Could you confirm that you can reproduce the same error and suggest a full working solution?

**Comment by vakker** [comment]
@jshilong @hhaAndroid could you confirm that the issue can be reproduced on your end as well? I'm happy to investigate this further, but it's unclear if this is a broader issue or there's just something wrong with my workflow. 
In any case either the tutorial is missing crucial information or there's a bug in how the dataset is handled with custom classes.

**Comment by vakker** [comment]
@jshilong @hhaAndroid do you have any update on this issue?
