### ISSUE TITLE
Error when training on custom dataset: TypeError: can't pickle module objects

### ISSUE THREAD

**Issue by qiaomu-miao** [open-mmlab/mmdetection#6550]
I am training yolov3 on a custom dataset, I modified the config file based on yolov3_d53_mstrain-416_273e_coco.py. The error message is as follow:
`Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/site-packages/mmcv/utils/config.py", line 332, in fromfile
    use_predefined_variables)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/site-packages/mmcv/utils/config.py", line 262, in _file2dict
    base_cfg_dict)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/site-packages/mmcv/utils/config.py", line 149, in _substitute_base_vars
    cfg = copy.deepcopy(cfg)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/qiaomu/anaconda3/envs/cuda10/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects`

I am running in an environment of python 3.7, torch=1.7.0, cuda 10.1. 

Does anyone have any clue about how to fix this? Thanks!

**Comment by hhaAndroid** [comment]
@qiaomu-miao Can you post your config?

**Comment by 24spiders** [comment]
I also have this issue

**Comment by qiaomu-miao** [comment]
> 
Sorry for the late reply. The config is as follow:
```python
import os
_base_ = "../yolo/yolov3_d53_mstrain-416_273e_coco.py"
model = dict(
    roi_head=dict(
        bbox_head=dict(num_classes=1),
       ))
data_dir = '/nfs/bigbrain/qiaomu/datasets/hollywood-heads'
dataset_type = 'COCODataset'
classes = ('head',)
data = dict(
    train=dict(
        img_prefix=data_dir,
        classes=classes,
        ann_file=os.path.join(data_dir, 'trainval.json'),
    val=dict(
        img_prefix=data_dir,
        classes=classes,
        ann_file=os.path.join(data_dir, 'test.json'))
    )
)
load_from = "/nfs/bigbrain/qiaomu/ckpts/mmdet/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth"
```

**Comment by alexarsenault** [comment]
I am also getting this error with a very similar config

**Comment by Bruce-Si** [comment]
Same error, is there any progress?

**Comment by alexarsenault** [comment]
I was able to get it to work by using an absolute path, but never figured out why the relative path failed

**Comment by Jackqu** [comment]
any progress?

**Comment by TAICHIKF** [comment]
Don't import any modules, like os, mmcv.
