### ISSUE TITLE
Cannot pickle object 'dataset_register.....' with worker_per_gpu=2.

### ISSUE THREAD

**Issue by ZhangHanbo** [open-mmlab/mmdetection#6577]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
Cannot pickle object 'dataset_register.....'

**Reproduction**
One can reproduce this error by setting the worker_per_gpu to 2.

Maybe helpful for bug shooting:
I have two envs of mmdetection in anaconda.
One uses torch 1.10.0 while another with torch 1.6.0.
All other configurations are the same, including the cuda version, python version, etc.
My code runs smoothly with worker_per_gpu > 2 and torch == 1.6.0, while when transferring to torch 1.10.0, there will be a multiprocessing bug:
Cannot pickle object 'dataset_register.....'

**Comment by AronLin** [comment]
Can you provide the error trace of this bug?
And what version of `mmdet` do you use?
We haven't tried to adapt torch1.10 yet, so if possible, please use Pytorch <=1.9.

**Comment by ZhangHanbo** [comment]
> Can you provide the error trace of this bug?
> And what version of `mmdet` do you use?
> We haven't tried to adapt torch1.10 yet, so if possible, please use Pytorch <=1.9.

Environment

OS: Ubuntu 18.04
Python version: Python 3.7.10
PyTorch version: 1.10.0
CUDA/cuDNN version: 10.2
GCC version: 6.5.0
Any other relevant information:
Additional context

Traceback (most recent call last):
File "./scripts/vmrn/train.py", line 189, in 
main()
File "./scripts/vmrn/train.py", line 185, in main
meta=meta)
File "/home/hanbo/ws/vmrn_mmdet/invigorate/apis/train.py", line 211, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
for i, data_batch in enumerate(self.data_loader):
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in iter
return self._get_iterator()
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 918, in init
w.start()
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/process.py", line 112, in start
self._popen = self._Popen(self)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in init
super().init(process_obj)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_fork.py", line 20, in init
self._launch(process_obj)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/home/hanbo/anaconda3/envs/open-mmlab/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Dataset.register_datapipe_as_function..class_function'

**Comment by ZhangHanbo** [comment]
> Can you provide the error trace of this bug?
> And what version of `mmdet` do you use?
> We haven't tried to adapt torch1.10 yet, so if possible, please use Pytorch <=1.9.

and my model version:

mmdet                     2.18.0                    dev_0    <develop>

**Comment by AronLin** [comment]
Sorry for the late reply.
This is a question about python multithreading, you can set num_workers=0.
Or go to `StackOverflow` to check this question.
