### ISSUE TITLE
Converting Grid RCNN model to ONNX

### ISSUE THREAD

**Issue by Rishit-dagli** [open-mmlab/mmdetection#6582]
While trying to convert a Grid RCNN model I trained with mmdetection, it seems I am not able to convert it to ONNX:

```
Traceback (most recent call last):
  File "mmdetection/tools/deployment/pytorch2onnx.py", line 345, in <module>
    skip_postprocess=args.skip_postprocess)
  File "mmdetection/tools/deployment/pytorch2onnx.py", line 100, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 132, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/detectors/base.py", line 169, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/detectors/two_stage.py", line 204, in onnx_export
    return self.roi_head.onnx_export(x, proposals, img_metas)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/roi_heads/standard_roi_head.py", line 299, in onnx_export
    x, img_metas, proposals, self.test_cfg, rescale=rescale)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/roi_heads/standard_roi_head.py", line 392, in bbox_onnx_export
    bbox_pred = bbox_pred.reshape(batch_size, num_proposals_per_img,
AttributeError: 'NoneType' object has no attribute 'reshape'
```

Is converting a Grid RCNN model not supported yet or is there any workaround for this?

**Comment by AronLin** [comment]
Yes, Grid RCNN ONNX is not supported now.

**Comment by Rishit-dagli** [comment]
@AronLin Ah got it, thanks for the info. Could this issue be converted to a feature request?

**Comment by AronLin** [comment]
We currently do not have this plan, but if you have time to complete it, we welcome PR and appreciate it.
