### ISSUE TITLE
I am a researcher at Microsoft. When I use mmaction for training, I will prompt errors related to distributed training. I sincerely look forward to your reply. Thank you very much

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#6588]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
the log is :
File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25385) of binary: /home/kny/anaconda3/envs/mmd/bin/python
Traceback (most recent call last):
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>

**Reproduction**

1. What command or script did you run?
bash  run.sh .
`python train.py

2. Did you make any modifications on the code or config? Did you understand what you have modified?
 no
3. What dataset did you use?'
 coco

**Environment**
pytorch 1.10   nvidia 3090  cuda 113

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - pip 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    python 3.7
**Error traceback**
If applicable, paste the error trackback here.
I am a researcher at Microsoft. When I use mmaction for training, I will prompt errors related to distributed training. I sincerely look forward to your reply. Thank you very much

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
Can you upload the full error message?

**Comment by xianglei3** [comment]
> 

hi the full erros  message is 
2021-11-25 17:23:57,289 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
2021-11-25 17:23:57,289 - mmdet - INFO - Checkpoints will be saved to /home/kny/code/cell/swin by HardDiskBackend.
Traceback (most recent call last):
  File "/home/kny/code/cell/./tools/train.py", line 189, in <module>
    main()
  File "/home/kny/code/cell/./tools/train.py", line 178, in main
    train_detector(
  File "/home/kny/code/cell/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/kny/code/cell/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/kny/code/cell/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/kny/code/cell/mmdet/models/detectors/two_stage.py", line 249, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/home/kny/code/cell/mmdet/models/dense_heads/base_dense_head.py", line 49, in forward_train
    outs = self(x)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kny/code/cell/mmdet/models/dense_heads/anchor_head.py", line 139, in forward
    return multi_apply(self.forward_single, feats)
  File "/home/kny/code/cell/mmdet/core/utils/misc.py", line 29, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/kny/code/cell/mmdet/models/dense_heads/rpn_head.py", line 39, in forward_single
    x = self.rpn_conv(x)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 31691) of binary: /home/kny/anaconda3/envs/xl/bin/python
Traceback (most recent call last):
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kny/anaconda3/envs/xl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2021-11-25_17:24:24
  host      : kny-ai
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 31691)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by RangiLyu** [comment]
Are you using apex to accelerate training?

**Comment by xianglei3** [comment]
> 

yes,

**Comment by sjtuytc** [comment]
I met the same issue.

**Comment by Younger330** [comment]
I have the same issue and I am sure it is not caused by apex
`
Traceback (most recent call last):
  File "/home/aaa/disk1/mmdetection-2.19.0/tools/train.py", line 192, in <module>
    main()
  File "/home/aaa/disk1/mmdetection-2.19.0/tools/train.py", line 181, in main
    train_detector(
  File "/home/aaa/disk1/CalibratedTeacher-main/src/apis/train.py", line 191, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/aaa/disk1/mmcv-1.4.5/mmcv/runner/iter_based_runner.py", line 116, in run
    self.call_hook('before_run')
  File "/home/aaa/disk1/mmcv-1.4.5/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/aaa/disk1/CalibratedTeacher-main/src/utils/hooks/mean_teacher.py", line 30, in before_run
    assert hasattr(model, "teacher")
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3208990) of binary: /home/aaa/anaconda3/envs/calibrate_teacher1/bin/python
Traceback (most recent call last):
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/aaa/anaconda3/envs/calibrate_teacher1/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/aaa/disk1/mmdetection-2.19.0/tools/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-28_14:12:59
  host      : aaa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3208990)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`
