### ISSUE TITLE
About RoIPooling

### ISSUE THREAD

**Issue by 842430478** [open-mmlab/mmdetection#659]
Could you help me correct this bug?
When I switch the type of roi_layer to "RoIPool", I encounter the following error.

THCudaCheck FAIL file=src/roi_pool_kernel.cu line=154 error=77 : an illegal memory access was encountered

**Comment by 842430478** [comment]
THCudaCheck FAIL file=src/roi_pool_kernel.cu line=154 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/ming/pytorch_test/weakly_supervised/mmdetection-master/tools/train.py", line 99, in <module>
    main()
  File "/home/ming/pytorch_test/weakly_supervised/mmdetection-master/tools/train.py", line 95, in main
    logger=logger)
  File "/home/ming/pytorch_test/weakly_supervised/mmdetection-master/mmdet/apis/train.py", line 69, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/ming/pytorch_test/weakly_supervised/mmdetection-master/mmdet/apis/train.py", line 166, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmcv/runner/runner.py", line 355, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmcv/runner/runner.py", line 268, in train
    self.call_hook('after_train_iter')
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmcv/runner/runner.py", line 228, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmcv/runner/hooks/optimizer.py", line 17, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/ming/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/ming/pytorch_test/weakly_supervised/mmdetection-master/mmdet/ops/roi_pool/functions/roi_pool.py", line 50, in backward
    spatial_scale, grad_input)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at src/roi_pool_kernel.cu:154
