### ISSUE TITLE
Add a notice about thread unsafety of 'mmdet.apis.init_detector'

### ISSUE THREAD

**Issue by AerysNan** [open-mmlab/mmdetection#6601]
**Describe the feature**

Add a notice in the document and tutorial, warning users that `mmdet.apis.init_dectector` is not thread-safe.

**Motivation**

Hello, I am a newbie to `mmdetection`. Thanks a lot for this wonderful framework.

Recently I encountered a problem when trying to call `mmdet.apis.init_detector` in multiple threads simultaneously. Displayed below is the error log:

```python
Traceback (most recent call last):
  File "src/cmd/worker/worker.py", line 31, in AddModel
    self.model_dict[request.source] = init_detector(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/mmdet/apis/inference.py", line 32, in init_detector
    config = mmcv.Config.fromfile(config)
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 331, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/usr/local/lib/python3.8/dist-packages/mmcv/utils/config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tmp6wm66ta3'
```

After some inspection into this error, I found the root cause is the code block below in `mmcv.Config._file2dict` when trying to load the configuration file into memory:

```python
temp_module_name = osp.splitext(temp_config_name)[0]
sys.path.insert(0, temp_config_dir)
Config._validate_py_syntax(filename)
mod = import_module(temp_module_name)
sys.path.pop(0)
```

Here `sys.path` is simply a Python list without any thread-safe guarantee. So if this block is called concurrently, the import path inserted by one thread might be poped by another, which leads to a `ModuleNotFoundError`.

What I am working on is an online scenario where a single inference worker handles multiple incoming streams concurrently, and these streams enter and exit dynamically. So I think this scenario is quite common and worth considering.

A simple walkaround is to load the configuration file with `mmcv.Config.fromfile` with mutex, and call `init_detector` using a `dict` instead of a `string`. This actually demands users handle thread safety by themselves. I am not sure whether it is a good idea. Or is it better to be directly fixed inside `mmcv`?

In any case, I personally think it is necessary to mention thread unsafety of 'mmdet.apis.init_detector' (or `mmcv.Config.fromfile`, more essentially) in the manual or tutorial, so others will not spend quite some time on this issue again : )

Thanks a lot for your kind assistance.

**Related resources**

Not applicable.

**Additional context**

Not applicable.

**Comment by heyitsguay** [comment]
Thank you for pointing this out! Ran into the same issue
