### ISSUE TITLE
Bugs when assigning "attn_mask" for DetrTransformerDecoderLayer

### ISSUE THREAD

**Issue by Sharpiless** [open-mmlab/mmdetection#6620]
input_embed torch.Size([4, 501, 256]), e.g. (Batch-size, num_seq, embedding_dim)

when running:
```python
            input_embed = input_embed.transpose(0, 1)
            num_seq = input_embed.shape[0]
            attn_mask = torch.triu(torch.ones((num_seq, num_seq)), diagonal=1).bool(). \
                to(input_embed.device)
            out_dec = self.decoder(
                query=input_embed,
                key=memory,
                value=memory,
                key_pos=pos_embed,
                key_padding_mask=mask,
                attn_mask=attn_mask)[-1]
```

get:

```bash
Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 174, in main
    train_detector(
  File "/home/guowx/mmdetection-master/mmdet/apis/train.py", line 211, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/guowx/mmdetection-master/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/guowx/mmdetection-master/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/guowx/mmdetection-master/mmdet/models/detectors/single_stage.py", line 83, in forward_train
    losses = self.bbox_head.forward_train(x, img_metas, gt_bboxes,
  File "/home/guowx/mmdetection-master/mmdet/models/dense_heads/pix2seq_head.py", line 592, in forward_train
    outs = self(x, img_metas, targets)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guowx/mmdetection-master/mmdet/models/dense_heads/pix2seq_head.py", line 231, in forward
    return multi_apply(self.forward_single, feats, img_metas_list, targets_list)
  File "/home/guowx/mmdetection-master/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/guowx/mmdetection-master/mmdet/models/dense_heads/pix2seq_head.py", line 267, in forward_single
    outs_dec, _ = self.transformer(x, input_seq, masks,
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guowx/mmdetection-master/mmdet/models/utils/transformer.py", line 1230, in forward
    out_dec = self.decoder(
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guowx/mmdetection-master/mmdet/models/utils/transformer.py", line 528, in forward
    query = layer(query, *args, **kwargs)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/guowx/anaconda3/envs/torch107/lib/python3.8/site-packages/mmcv/cnn/bricks/transformer.py", line 474, in forward
    query = self.attentions[attn_index](
TypeError: MultiheadAttention object got multiple values for keyword argument 'attn_mask'
```

**Comment by Sharpiless** [comment]
Is there a problem with the way I assign the value of the mask?

**Comment by Sharpiless** [comment]
There is "attn_mask" key in "**kwargs" at code "mmcv/cnn/briks/transformer" line 483 when assigning "attn_mask". But line 481 also gives multiple values for  "attn_mask".

**Comment by jshilong** [comment]
> There is "attn_mask" key in "**kwargs" at code "mmcv/cnn/briks/transformer" line 483 when assigning "attn_mask". But line 481 also gives multiple values for "attn_mask". Comment out this sentence to solve this problem: "attn_mask=attn_masks[attn_index]". But I'm not sure if it will lead to other problems.

Please change to
```
            out_dec = self.decoder(
                query=input_embed,
                key=memory,
                value=memory,
                key_pos=pos_embed,
                key_padding_mask=mask,
                attn_masks=attn_mask)[-1]
```
