### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by ZdsAlpha** [open-mmlab/mmdetection#6645]
**Describe the bug**
I am trying to deploy model using bentoml. It doesn't give me full access to run terminal commands in conda env to setup using mim. I tried installing using pip.

**Reproduction**

Here is my setup_sh which likely runs outside conda env:
```
#!/bin/bash
set -e

apt-get --allow-releaseinfo-change update
apt-get -y install libgl1 libglib2.0-0 libsm6 libxrender1 libxext6

pip install bentoml easyocr torch torchvision boto3 docker rich

pip install -U pip --no-cache-dir
apt-get -y clean

export MMCV_WITH_OPS=1
export FORCE_CUDA=1

echo "export MMCV_WITH_OPS=1\n" >> ~/.bashrc
echo "export FORCE_CUDA=1\n" >> ~/.bashrc

source ~/.bashrc
```
I tried to export MMCV_WITH_OPS and FORCE_CUDA beause `mmdet.utils.collect_env()` gives me 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a'.

Here is my `requirements.txt`
```
-f https://download.pytorch.org/whl/cu113/torch_stable.html
torch==1.10.0+cu113
torchvision==0.11.1+cu113
opencv-python-headless
-f https://download.openmmlab.com/mmcv/dist/cu113/1.10.0/index.html
mmcv-full
mmdet
gevent
numpy
bentoml
easyocr
```

**Environment**

Using docker with image `bentoml/model-server:latest-py37-gpu`, Python 3.7

Output of `mmdet.utils.collect_env()`:

```
{'sys.platform': 'linux', 'Python': '3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]', 'CUDA available': True, 'GPU 0': 'Tesla T4', 'CUDA_HOME': '/usr/local/cuda', 'NVCC': '', 'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0', 'PyTorch': '1.10.0+cu113', 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.3\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86\n  - CuDNN 8.2\n  - Magma 2.5.2\n  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n', 'TorchVision': '0.11.1+cu113', 'OpenCV': '4.5.4', 'MMCV': '1.3.18', 'MMCV Compiler': 'n/a', 'MMCV CUDA Compiler': 'n/a', 'MMDetection': '2.19.0+'}
```

**Error traceback**

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/server/gunicorn_server.py", line 125, in load
    bento_service = load_from_dir(self.bento_service_bundle_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/saved_bundle/loader.py", line 110, in wrapper
    return func(bundle_path, *args)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/saved_bundle/loader.py", line 272, in load_from_dir
    return svc_cls()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/__init__.py", line 490, in __init__
    self._config_artifacts()
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/__init__.py", line 559, in _config_artifacts
    self.artifacts.load_all(artifacts_path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 280, in load_all
    artifact.load(path)
  File "/opt/conda/lib/python3.7/site-packages/bentoml/service/artifacts/__init__.py", line 175, in wrapped_load
    ret = original(*args, **kwargs)
  File "./MLUI/service.py", line 34, in load
    from mmdet.apis import init_detector
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/opt/conda/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/opt/conda/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Comment by BIGWangYuDong** [comment]
It is suggested to check whether you have installed CUDA successfully.

**Comment by ZdsAlpha** [comment]
> It is suggested to check whether you have installed CUDA successfully.

How can I do that? I have initialized tensor in GPU in pytorch before initializing mmcv. It works. So what is causing problem.

**Comment by AronLin** [comment]
> > It is suggested to check whether you have installed CUDA successfully.
> 
> How can I do that? I have initialized tensor in GPU in pytorch before initializing mmcv. It works. So what is causing problem.
1. Please check whether torch.cuda.is_available() is True.
2. If true, try to uninstall mmcv-full and re-install it.
3. If it still does not work, please create an issue in mmcv, they are professional.

**Comment by mathur01** [comment]
I tried all possible way explained in this thread. Still i am getting same error. Here are specs i am working on:
OS: Windows 10
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.49       Driver Version: 496.49       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+

Torch-1.11.0+cu115
torch.cuda.is_available()) - True
Torchvision -  0.12.0+cu115
mmdet.__version__ - 2.22.0

`ModuleNotFoundError: No module named 'mmcv._ext'`
