### ISSUE TITLE
在fpn中使用upsample_cfg=dict(mode='nearest'，scale_factor=2)时，转onnx报错

### ISSUE THREAD

**Issue by geoffzhang** [open-mmlab/mmdetection#6647]
**在fpn中使用upsample_cfg=dict(mode='nearest'，scale_factor=2)时，转onnx报错，去掉scale_factor正常**
错误信息如下：
Traceback (most recent call last):
  File "tools/scrfd2onnx.py", line 197, in <module>
    pytorch2onnx(
  File "tools/scrfd2onnx.py", line 85, in pytorch2onnx
    torch.onnx.export(
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 632, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/torch/onnx/utils.py", line 934, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/mmcv/onnx/symbolic.py", line 16, in symbolic_fn
    scales, align_corners = sym_help._get_interpolate_attributes(
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 254, in _get_interpolate_attributes
    scales = _interpolate_get_scales_if_available(g, scales)
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 229, in _interpolate_get_scales_if_available
    available_scales = _maybe_get_const(scales[0], 'f') != -1 and not _is_none(
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 64, in _maybe_get_const
    return _parse_arg(value, desc)
  File "/home/geoff/venv_python/mmdet_py3.8/lib/python3.8/site-packages/mmcv/onnx/onnx_utils/symbolic_helper.py", line 33, in _parse_arg
    return float(tval)
ValueError: only one element tensors can be converted to Python scalars

使用版本为2.7

**Comment by AronLin** [comment]
Perhaps it is related to the python version, our deployment process is developed under python3
