### ISSUE TITLE
I am a researcher of Microsoft Research institute. I made the following mistake when USING the Albu data enhancement module. I sincerely look forward to your reply

### ISSUE THREAD

**Issue by xianglei3** [open-mmlab/mmdetection#6666]
Thanks for your error report and we appreciate it a lot.

the error is  
bbox_params must be specified for bbox transformations

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?
2. train_pipeline = [
    dict(type='LoadImageFromFile',to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    
    dict(type="Albu", transforms=[
        dict(type="CLAHE", clip_limit=4.0, tile_grid_size=(8, 8), p=0.5),
        dict(type="ChannelShuffle", p=0.5),
        dict(type="RGBShift", r_shift_limit=20, g_shift_limit=20, b_shift_limit=20, p=0.5),
        dict(type="RandomBrightnessContrast", brightness_limit=0.2, contrast_limit=0.2, p=0.5),
        dict(type="HueSaturationValue", hue_shift_limit=20, sat_shift_limit=30, val_shift_limit=20, p=0.5),
        dict(type="OneOf", transforms=[
            dict(type="GaussianBlur", blur_limit=(3, 7), sigma_limit=0, p=0.5),
            dict(type="MedianBlur", blur_limit=7, p=0.5),
            dict(type="MotionBlur", p=0.5)], p=0.5)
    ]),

 
    

    

```none
A placeholder for the command.
```
 bash run.sh 
2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?
coco
**Environment**
ubuntu

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
2021-12-02 16:08:00,939 - mmdet - INFO - Checkpoints will be saved to /home/kny/code/cell/model/dzx by HardDiskBackend.
Traceback (most recent call last):
  File "./tools/train.py", line 190, in <module>
    main()
  File "./tools/train.py", line 186, in main
    meta=meta)
  File "/home/kny/code/cell/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kny/code/cell/mmdet/datasets/custom.py", line 194, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/kny/code/cell/mmdet/datasets/custom.py", line 217, in prepare_train_img
    return self.pipeline(results)
  File "/home/kny/code/cell/mmdet/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/home/kny/code/cell/mmdet/datasets/pipelines/transforms.py", line 1441, in __call__
    results = self.aug(**results)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/albumentations/core/composition.py", line 195, in __call__
    self._check_args(**data)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/albumentations/core/composition.py", line 277, in _check_args
    raise ValueError("bbox_params must be specified for bbox transformations")
ValueError: bbox_params must be specified for bbox transformations

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 100426) of binary: /home/kny/anaconda3/envs/mmd/bin/python
Traceback (most recent call last):
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kny/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
It seems that you are using the internal version of mmdet in MS, most of the augmentations are not in the OpenMMLab version. Please ask the maintainer in your department.
