### ISSUE TITLE
AttributeError: VOCDataset: 'FileClient' object has no attribute 'get_local_path'

### ISSUE THREAD

**Issue by wyh196646** [open-mmlab/mmdetection#6683]
I running the project on my own pc,but the error shows

2021-12-04 17:23:05,450 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2021-12-04 17:23:05,476 - mmdet - INFO - initialize Shared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
Traceback (most recent call last):
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/voc.py", line 20, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/xml_style.py", line 34, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py", line 91, in __init__
    with self.file_client.get_local_path(self.ann_file) as local_path:
AttributeError: 'FileClient' object has no attribute 'get_local_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 161, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 69, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 79, in build_dataset
    dataset = _concat_dataset(cfg, default_args)
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 53, in _concat_dataset
    datasets.append(build_dataset(data_cfg, default_args))
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AttributeError: VOCDataset: 'FileClient' object has no attribute 'get_local_path'

**Comment by wyh196646** [comment]
I check the '/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py' file ,and search the 'get_local_path' in the  project but not not found,Is there a problem with the version I installed,how do I slove it?

**Comment by BIGWangYuDong** [comment]
need update mmcv version to the latest one

**Comment by lad-kun** [comment]
> I check the '/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/custom.py' file ,and search the 'get_local_path' in the project but not not found,Is there a problem with the version I installed,how do I slove it?
I have also encountered this problem. Have you solved this problem?

**Comment by wyh196646** [comment]
> 

I just reinstall the mmcv and mmdetection,and read the official docs to change my config file,then it works
