### ISSUE TITLE
assign_score_withk_forward miss in module _ext

### ISSUE THREAD

**Issue by wyh196646** [open-mmlab/mmdetection#6703]
The new error 
``
(open-mmlab) wangyh21@d01:~/assignment/mmtest/mmdetection$ python tools/train.py ./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_voc.py
Traceback (most recent call last):
  File "tools/train.py", line 16, in <module>
    from mmdet.apis import init_random_seed, set_random_seed, train_detector
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/inference.py", line 7, in <module>
    from mmcv.ops import RoIPool
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/ops/assign_score_withk.py", line 6, in <module>
    '_ext', ['assign_score_withk_forward', 'assign_score_withk_backward'])
  File "/home/wangyh21/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 15, in load_ext
    assert hasattr(ext, fun), f'{fun} miss in module {name}'
AssertionError: assign_score_withk_forward miss in module _ext

**Comment by Tom-Hardy-3D-Vision-Workshop** [comment]
Do you solve this problem?

**Comment by ZouRuia** [comment]
I also miss this problem,is it a version problem? Do you solve it?

**Comment by ZouRuia** [comment]
cuda 11.2,torch 1.7.1+cu110

**Comment by ZouRuia** [comment]
I reinstall mmcv-full solve this problem.
mmcv-full          1.4.0
mmdet              2.19.0
torch              1.7.1+cu110
torchvision        0.8.2+cu110

**Comment by wyh196646** [comment]
> I reinstall mmcv-full solve this problem. mmcv-full 1.4.0 mmdet 2.19.0 torch 1.7.1+cu110 torchvision 0.8.2+cu110
really thanks！I will try it

**Comment by SandeepMenonKodiak** [comment]
I am getting this error and reinstalling is not working
This is my trace
```
Traceback (most recent call last):
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/vehicle/source/offboard/ml/third_party/bevfusion/tools/test_dataloader.py", line 11, in <module>
    from mmdet.core import DistEvalHook
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmdet/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/execroot/vehicle/bazel-out/main_compute-opt/bin/source/offboard/ml/third_party/bevfusion/test_dataloader.runfiles/offboard_python_analysis_mmcv/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/s.menon/.cache/bazel/_bazel_s.menon/45be10fcfdc1ffc6fc5ee66d3fa7c88a/external/python3_8_x86_64-unknown-linux-gnu/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

Any mmdet.core import is failing with this error.
I am using python 3.8 and cuda 11.7. Installing using a requirements file
```
mmcv == 1.4.0
mmcv-full == 1.4.0
mmdet == 2.20.0
```
