### ISSUE TITLE
AttributeError: 'ECAlayer' object has no attribute 'init_weights'

### ISSUE THREAD

**Issue by hyyun0408** [open-mmlab/mmdetection#6836]
I am trying to add some modules into other people's model, which doesn't exist in the mmdet model right now, however, when  I ran the new model after adding attention module, the system always remind me this error.
AttributeError: 'ECAlayer' object has no attribute 'init_weights'
I find some similar issues in guthub, and the solution is to update mmcv, but since the model I used is based on an old version(mmcv 0.5.9), if I update it to the latest one, then the whole net seems can't run any longer. So What else can I do to debug it, or updating is the only way?

> Traceback (most recent call last):
  File "../tools/train.py", line 161, in <module>
    main()
  File "../tools/train.py", line 133, in main
    model = build_detector(
  File "/home/bnu208/r3det-on-mmdetection-master/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/bnu208/r3det-on-mmdetection-master/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/bnu208/anaconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
  File "/home/bnu208/r3det-on-mmdetection-master/mmdet/models/detectors/r3det.py", line 49, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/bnu208/r3det-on-mmdetection-master/mmdet/models/detectors/r3det.py", line 57, in init_weights
    m.init_weights()
  File "/home/bnu208/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ECAlayer' object has no attribute 'init_weights'

**Comment by hyyun0408** [comment]
the version are mmcv 0.5.9 and the mmdet is 2.1.0,very old ...
btw, the attention module I used doesn't in mmdet, either.
