### ISSUE TITLE
I want to see val loss on tensorboard but face with error TypeError: loss() missing 1 required positional argument: 'img_metas'

### ISSUE THREAD

**Issue by liang532** [open-mmlab/mmdetection#6851]
In config file , workflow = [('train', 1)] , I change it to workflow = [('train', 1),('val',1)],hope to see val loss on tensorboard , but after one train epoch , val epoch begin , get error:TypeError: loss() missing 1 required positional argument: 'img_metas'.

Detail:
2021-12-21 12:11:29,428 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
2021-12-21 12:11:29,430 - mmdet - ERROR - The testing results of the whole dataset is empty.
2021-12-21 12:11:29,448 - mmdet - INFO - Exp name: small_val_loss.py
2021-12-21 12:11:29,449 - mmdet - INFO - Epoch(val) [1][1534]	
/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/utils/registry.py:252: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 185, in main
    meta=meta)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/apis/train.py", line 177, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/parallel/distributed.py", line 94, in val_step
    output = self.module.val_step(*inputs[0], **kwargs[0])
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/base.py", line 253, in val_step
    losses = self(**data)
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 326, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
TypeError: loss() missing 1 required positional argument: 'img_metas'
Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 185, in main
    meta=meta)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/apis/train.py", line 177, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/parallel/distributed.py", line 94, in val_step
    output = self.module.val_step(*inputs[0], **kwargs[0])
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/base.py", line 253, in val_step
    losses = self(**data)
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/detectors/single_stage.py", line 84, in forward_train
    gt_labels, gt_bboxes_ignore)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 326, in forward_train
    losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/data/E/personal/liang/Traffic_Sign_Detection/mmcv/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
TypeError: loss() missing 1 required positional argument: 'img_metas'
Traceback (most recent call last):
  File "/opt/conda/envs/mmdetection/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/mmdetection/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/opt/conda/envs/mmdetection/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/mmdetection/bin/python', '-u', './tools/train.py', '--local_rank=1', 'work_dirs/from_resnet/vfnet_xiangguan/vfnet_1x/small_val_loss.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by hhaAndroid** [comment]
@liang532 Please use the issue template.

**Comment by dnth** [comment]
@liang532 did you solve the issue? I face this problem with VFNet but not other single stage models. Happens to all versions after `mmdet==2.17.0`

**Comment by dnth** [comment]
I find that the forward_single fucntion returns three value `cls_score, bbox_pred, bbox_pred_refine` during training and returns only two values `cls_score, bbox_pred_refine` when it is not in training.

Could this be the cause of this problem?

https://github.com/open-mmlab/mmdetection/blob/a64303186aa79811a050942f1bdab430a6a7f7af/mmdet/models/dense_heads/vfnet_head.py#L307

**Comment by dnth** [comment]
@BIGWangYuDong other than the fix proposed https://github.com/open-mmlab/mmdetection/pull/7173, is there any other way we can solve this bug?

**Comment by FraCamp** [comment]
So is this still open? was found some solution to this? Is there a way to produce validation loss during training on vfnet?
