### ISSUE TITLE
Dataset load error when training with VOC-style dataset

### ISSUE THREAD

**Issue by truemanluo** [open-mmlab/mmdetection#6876]
When I trained on a VOC format dataset， a weird error occurred.
Error message:
```bash
Traceback (most recent call last):
  File "/media/luoqiuhong/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/voc.py", line 26, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/xml_style.py", line 34, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/custom.py", line 92, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/xml_style.py", line 54, in load_annotations
    tree = ET.parse(xml_path)
  File "/media/luoqiuhong/anaconda3/envs/openmmlab/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/media/luoqiuhong/anaconda3/envs/openmmlab/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: junk after document element: line 27, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 161, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/builder.py", line 69, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/builder.py", line 79, in build_dataset
    dataset = _concat_dataset(cfg, default_args)
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/builder.py", line 53, in _concat_dataset
    datasets.append(build_dataset(data_cfg, default_args))
  File "/media/luoqiuhong/mmdetection/mmdet/datasets/builder.py", line 81, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/media/luoqiuhong/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
xml.etree.ElementTree.ParseError: VOCDataset: junk after document element: line 27, column 0
```
It's weird because If I modify the `ann_file` of `data.train` in `configs/_base_/datasets/voc0712.py` to `test.txt`(of course it's wrong doing this), the code can run.
I've done serval steps to train this VOC-style dataset:
1. change my config to `mmdetection/configs/faster_rcnn/ip102_config.py`:
```python
_base_ = [
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/voc0712.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

model = dict(
    roi_head=dict(
        bbox_head=dict(
            num_classes=102,
        )
    ),
)
optimizer = dict(type='SGD', lr=0.02/8, momentum=0.9, weight_decay=0.0001)

lr_config = dict(
    policy='step',
    warmup=None,
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11]
)
seed = 0
gpu_ids = range(1)

work_dir = 'ip102_work_dir/faster-rcnn_r50_fpn_1x'
load_from = 'checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth'
```

2.  comment the `VOC2012` part in `configs/_base_/datasets/voc0712.py`:
```python
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=3,
        dataset=dict(
            type=dataset_type,
            # ann_file=[
            #     data_root + 'VOC2007/ImageSets/Main/trainval.txt',
            #     data_root + 'VOC2012/ImageSets/Main/trainval.txt'
            # ],
            # img_prefix=[data_root + 'VOC2007/', data_root + 'VOC2012/'],
            ann_file=[
                data_root + 'VOC2007/ImageSets/Main/trainval.txt'
            ],
            img_prefix=[data_root + 'VOC2007/'],
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='mAP')

```
3. modified the classes name in `mmdet/core/evaluation/class_names.py`
```python
def voc_classes():
    return [str(i) for i in range(102)]
```
4. modified the `mmdet/datasets/voc.py`
```python
@DATASETS.register_module()
class VOCDataset(XMLDataset):
    CLASSES = tuple([str(i) for i in range(102)])
    pass
```
5. I also checked if this error caused by `ET`, but the `.xml` can be parsed properly.
```python
import xml.etree.ElementTree as ET

tree = ET.parse('../../data/VOCdevkit/VOC2007/Annotations/IP000000378.xml')

root = tree.getroot()

for child in root:
    print(child.tag, child.attrib)

```
6. I've wrote scripts to check if `xmls` in `trainval.txt` matched image names in `JEPGImages`, and yes. 

My `data` folder like this:
```bash
mmdetecion/data/VOCdevkit
└── VOC2007
    ├── Annotations
    ├── Annotations.tar
    ├── ImageSets
     |       |
     |       ----Main
     |                   |
     |                   trainval.txt
     |                   test.txt
    ├── JPEGImages
    └── JPEGImages.tar
4 directories, 2 files
```

Could you tell me anywhere I did the wrong way? Thanks.

**Comment by truemanluo** [comment]
Sorry my bad. Something goes wrong with the annotations.

**Comment by Luxiangxianghy** [comment]
> Sorry my bad. Something goes wrong with the annotations.
Sorry my bad. Something goes wrong with the annotations.

**Comment by Luxiangxianghy** [comment]
> Sorry my bad. Something goes wrong with the annotations.

Can you tell me what went wrong?
