### ISSUE TITLE
What are the specific reasons for this situation? How should I solve it

### ISSUE THREAD

**Issue by sxy1122** [open-mmlab/mmdetection#6970]
Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/utils/config.py", line 332, in fromfile
    use_predefined_variables)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/utils/config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmpnhb0vjpp/tmp1monw1y2.py", line 37, in <module>
AttributeError: 'dict' object has no attribute 'load_state_dict'
Traceback (most recent call last):
  File "./tools/train.py", line 189, in <module>
    main()
  File "./tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/utils/config.py", line 332, in fromfile
    use_predefined_variables)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/utils/config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/tmp8zpdq401/tmpkmce66ka.py", line 37, in <module>
AttributeError: 'dict' object has no attribute 'load_state_dict'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f0236d218c0>
Traceback (most recent call last):
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnhb0vjpp/tmp1monw1y2.py'
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f72e81c58c0>
Traceback (most recent call last):
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp8zpdq401/tmpkmce66ka.py'
Traceback (most recent call last):
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/zxqgy/anaconda3/envs/mm/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)

**Comment by RangiLyu** [comment]
Please follow the issue template to provide more information.
