### ISSUE TITLE
TypeError: object of type 'float' has no len()

### ISSUE THREAD

**Issue by sunnyisabaster** [open-mmlab/mmdetection#7004]
Hello there, 

I'm using mask rcnn in mmdection. Today i met a problem:

```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\torch\utils\data\_utils\worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "F:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\anaconda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\anaconda\lib\site-packages\mmdet\datasets\custom.py", line 216, in __getitem__
    data = self.prepare_train_img(idx)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\custom.py", line 239, in prepare_train_img
    return self.pipeline(results)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 41, in __call__
    data = t(data)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\pipelines\loading.py", line 377, in __call__
    results = self._load_masks(results)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\pipelines\loading.py", line 329, in _load_masks
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\pipelines\loading.py", line 329, in <listcomp>
    [self._poly2mask(mask, h, w) for mask in gt_masks], h, w)
  File "F:\anaconda\lib\site-packages\mmdet\datasets\pipelines\loading.py", line 285, in _poly2mask
    rles = maskUtils.frPyObjects(mask_ann, img_h, img_w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: object of type 'float' has no len()
```

My annotation dic likes below, which generated by code:

```
{'bboxes': array([[191.54916, 223.7229 , 316.355  , 313.51614]], dtype=float32),
 'labels': array([0]), 'bboxes_ignore': array([], shape=(0, 4), dtype=float32), 
'labels_ignore': array([], dtype=int32), 
'area': 11206.721937273685,
 'masks': [[283.0022692889561, 224.94402420574886, 284.99924357034797, 224.3741805345436, 287.00126071608673, 224.22289460413512, 288.99823499747856, 224.50025214321732, 290.2589510842158, 224.9994957135653, 291.0002521432173, 225.35249621785172, 293.00226928895614, 226.97629853756933, 293.02244074634393, 227.00151285930409, 294.63615733736765, 228.99848714069591, 294.9992435703479, 229.45738779626825, 296.1893595562279, 231.00050428643468, 297.00126071608673, 231.97377710539584, 297.7879475542108, 232.99747856782653, 298.99823499747856, 234.65658093797273, 299.2453353504791, 234.9994957135653, 300.5211800302572, 237.00151285930409, 301.0002521432174, 237.71255673222387, 301.83232476046396, 238.99848714069591, 303.0022692889561, 240.79878971255673, 303.1283408976298, 241.0005042864347, 304.2125567322239, 242.9974785678265, 304.99924357034797, 244.4145234493192, 305.32198688855266, 244.99949571356527, 306.5121028744327, 247.00151285930409, 307.00126071608673, 247.67725668179523, 307.86359051941497, 248.9984871406959, 308.9982349974785, 250.63741805345433, 309.23524962178516, 251.00050428643468, 310.39006555723654, 253.00252143217344, 311.0002521432173, 254.0665658093797, 311.4894099848714, 254.9994957135653, 312.3971255673222, 257.00151285930406, 313.00226928895614, 258.4589006555724, 313.2241553202219, 258.9984871406959, 313.9150277357539, 261.0005042864347, 314.58068582955116, 263.00252143217347, 314.99924357034797, 264.0968229954614, 315.3169440242058, 264.9994957135653, 315.95234493192135, 267.00151285930406, 316.4667170953101, 268.9984871406959, 316.8550176500252, 271.0005042864347, 316.76424609178014, 273.0025214321734, 316.2246596066566, 274.9994957135653, 315.47327281896116, 277.00151285930406, 314.99924357034797, 278.3832576903681, 314.7824004034291, 278.99848714069594, 314.3487140695915, 281.00050428643465, 313.87972768532524, 283.00252143217347, 313.0930408472012, 284.9994957135653, 313.00226928895614, 285.1457387796268, 311.83232476046396, 287.0015128593041, 311.0002521432173, 288.2521432173474, 310.5110943015633, 288.9984871406959, 309.26550680786687, 291.0005042864347, 308.9982349974785, 291.3736762481089, 307.7980332829047, 293.00252143217347, 307.00126071608673, 293.9152798789712, 306.01790216843165, 294.9994957135653, 304.99924357034797, 296.0837115481594, 304.11674230963183, 297.00151285930406, 303.0022692889561, 298.1613716591024, 302.21053958648514, 298.9984871406959, 301.0002521432174, 300.31467473524964, 300.3245083207262, 301.0005042864347, 298.99823499747856, 302.30156328794754, 298.25693393847706, 303.0025214321734, 297.00126071608673, 304.1119515885023, 295.9573877962683, 304.9994957135653, 294.9992435703479, 305.79626828038323, 293.4157841654059, 307.00151285930406, 293.00226928895614, 307.304084720121, 291.0002521432173, 308.49924357034797, 290.0622793746848, 308.99848714069594, 288.99823499747856, 309.5582450832072, 287.00126071608673, 310.4508320726172, 285.42788703983865, 311.00050428643465, 284.99924357034797, 311.1467473524962, 283.0022692889561, 311.5249621785174, 281.0002521432173, 311.6712052445789, 278.99823499747856, 311.70146243066057, 277.00126071608673, 311.7367624810893, 274.9992435703479, 311.767019667171, 273.00226928895614, 311.79727685325264, 271.0002521432174, 311.8275340393343, 268.99823499747856, 311.857791225416, 267.00126071608673, 311.92334846192637, 264.99924357034797, 312.01412002017145, 263.00226928895614, 312.2208774583964, 261.0002521432173, 312.654563792234, 259.95133635905194, 313.00252143217347, 258.99823499747856, 313.31013615733735, 257.00126071608673, 313.8093797276853, 254.99924357034797, 314.0161371659102, 253.00226928895611, 313.8900655572365, 251.00025214321735, 313.46646495209274, 249.47226424609175, 313.00252143217347, 248.99823499747856, 312.846192637418, 247.00126071608673, 312.3166918809884, 244.99924357034794, 312.0292486132123, 243.00226928895611, 311.87291981845686, 241.00025214321735, 311.79727685325264, 238.99823499747856, 311.74684820978314, 237.00126071608673, 311.70146243066057, 234.99924357034794, 311.6712052445789, 233.00226928895611, 311.6712052445789, 231.00025214321732, 311.64094805849726, 228.99823499747856, 311.6207766011094, 227.00126071608676, 311.5804336863338, 224.99924357034794, 311.4291477559253, 223.0728693898134, 311.00050428643465, 223.00226928895611, 310.98537569339385, 221.00025214321735, 310.1986888552697, 218.9982349974786, 309.0539586485123, 218.92763489662127, 308.99848714069594, 217.00126071608673, 307.51084215834595, 216.38603126575896, 307.00151285930406, 214.99924357034797, 305.89208270297524, 213.77382753403933, 304.9994957135653, 213.00226928895611, 304.4548663640948, 211.00025214321735, 303.2647503782148, 210.59682299546142, 303.0025214321734, 208.99823499747856, 301.96369137670195, 207.59127584467979, 301.0005042864347, 207.00126071608673, 300.571860816944, 204.99924357034794, 299.0590015128593, 204.9336863338376, 298.9984871406959, 203.00226928895611, 297.10741301059, 202.90141200201714, 297.00151285930406, 201.35325264750378, 294.9994957135653, 201.00025214321732, 294.5254664649521, 199.91099344427636, 293.00252143217347, 198.99823499747856, 291.6207766011094, 198.5897629853757, 291.0005042864347, 197.46520423600603, 288.9984871406959, 197.00126071608673, 288.13111447302066, 196.40620272314675, 287.0015128593041, 195.4228441754917, 284.9994957135653, 194.99924357034794, 284.1674230963187, 194.4092284417549, 283.00252143217347, 193.49142713061016, 281.00050428643465, 193.00226928895614, 279.7397881996974, 192.71482602118004, 278.99848714069594, 192.220625315179, 277.00151285930406, 192.04916792738274, 274.9994957135653, 192.09455370650528, 273.0025214321734, 192.34669692385276, 271.0005042864347, 192.82072617246595, 268.9984871406959, 193.00226928895614, 268.4488149268784, 193.46621280887544, 267.00151285930406, 194.07639939485628, 264.9994957135653, 194.6361573373676, 263.00252143217347, 194.99924357034794, 261.7871911245588, 195.24634392334846, 261.0005042864347, 195.81114473020676, 258.9984871406959, 196.34064548663642, 257.00151285930406, 197.00126071608673, 255.2163388804841, 197.08698940998485, 254.9994957135653, 198.1359051941503, 253.00252143217344, 198.99823499747856, 251.58547655068077, 199.36636409480585, 251.00050428643468, 200.59682299546142, 248.9984871406959, 201.00025214321732, 248.393343419062, 201.92813918305598, 247.00151285930409, 203.00226928895611, 245.43822491174984, 203.30484114977307, 244.99949571356527, 204.61598587997983, 242.9974785678265, 204.99924357034794, 242.48814926878467, 206.10867372667673, 241.0005042864347, 207.00126071608673, 239.91124558749368, 207.74760463943517, 238.99848714069591, 208.99823499747856, 237.35955622793745, 209.27559253656077, 237.00151285930409, 210.72793746848208, 234.9994957135653, 211.00025214321735, 234.6515380736258, 212.3416540595058, 232.99747856782653, 213.00226928895611, 232.27130610186586, 214.24281391830561, 231.00050428643468, 214.99924357034797, 230.28946041351486, 216.63313161875945, 228.99848714069591, 217.00126071608673, 228.72617246596064, 218.9982349974786, 227.5915279878971, 220.5211800302572, 227.00151285930409, 221.00025214321735, 226.81492687846696, 223.00226928895611, 226.50226928895611, 224.99924357034794, 226.65355521936456, 226.23474533535048, 227.00151285930409, 227.00126071608676, 227.21835602622286, 228.99823499747856, 227.8688855269793, 231.00025214321732, 228.5143721633888, 232.52824004034292, 228.99848714069591, 233.00226928895611, 229.1497730711044, 234.99924357034794, 229.67423096318709, 237.00126071608673, 230.03227433182047, 238.99823499747856, 230.36006051437215, 241.00025214321735, 230.75844679778115, 241.93822491174987, 231.00050428643468, 243.00226928895611, 231.27281896116995, 244.99924357034794, 231.7014624306606, 247.00126071608673, 231.9687342410489, 248.99823499747856, 232.16036308623296, 251.00025214321735, 232.39233484619263, 253.00226928895611, 232.7604639435199, 254.24785678265255, 232.99747856782653, 254.99924357034797, 233.14876449823498, 257.00126071608673, 233.33535047907208, 258.99823499747856, 233.17397881996973, 259.845436207766, 232.99747856782653, 261.0002521432173, 232.7604639435199, 263.00226928895614, 232.35703479576398, 264.99924357034797, 231.95360564800805, 267.00126071608673, 231.45940494200704, 268.3830055471508, 231.00050428643468, 268.99823499747856, 230.7836611195159, 271.0002521432174, 230.08270297528995, 273.00226928895614, 229.36157337367624, 273.8746848209783, 228.99848714069591, 274.9992435703479, 228.5345436207766, 277.00126071608673, 227.7327281896117, 278.6401916288452, 227.00151285930409, 278.99823499747856, 226.83509833585475, 281.0002521432173, 225.92233988905696, 282.88124054462935, 224.9994957135653]],
 'iscrowd': 0}
```

So, does anyone know how to solve it? Thanks a lot!

**Comment by sunnyisabaster** [comment]
@AronLin Sorry bro, this problem annoyed me for a couple of days...do u have any ideas?

**Comment by sunnyisabaster** [comment]
Does anyone know?
