### ISSUE TITLE
pth to onnx:ImportError: cannot import name 'roi_align_cuda'

### ISSUE THREAD

**Issue by xd-Nanan** [open-mmlab/mmdetection#7021]
When I convert the EfficientPS panoramic segmentation model to the onnx model, the following errors occur during inference:
It shows that each python file in ops cannot call the interface provided by its C++ file，This model is modified based on mmdet1.1.0 version. Now the calling method in the new version of mmcv has changed. I don't know how to import the module in the way of "from . import roi_align_cuda".

1.python3 mmdet/ops/roi_align/roi_align.py
Traceback (most recent call last):
  File "mmdet/ops/roi_align/roi_align.py", line 6, in <module>
    from . import roi_align_cuda
ImportError: cannot import name 'roi_align_cuda'

2.
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 351, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 104, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/__init__.py", line 276, i export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in exort
    use_external_data_format=use_external_data_format)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 707, in _xport
    dynamic_axes=dynamic_axes)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 465, in _odel_to_graph
    use_new_jit_passes)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 426, in _reate_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/onnx/utils.py", line 386, in _race_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/jit/_trace.py", line 1139, in get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 88, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/jit/_trace.py", line 130, in frward
    self._force_outplace,
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/jit/_trace.py", line 116, in wapper
    outs.append(self.inner(*trace_inputs))
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 88, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 86, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/models/efficientps/base.py", line 149, in forward
    return self.forward_test(img, img_metas, eval, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/models/efficientps/base.py", line 130, in forward_test
    return self.simple_test(imgs[0], img_metas[0], eval=eval, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/models/efficientps/efficientPS.py", line 250, in simple_tes
    img_metas, proposal_list, self.test_cfg.rcnn, rescale=rescale)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/models/efficientps/efficientPS.py", line 304, in simple_tes_bboxes
    x[:len(self.bbox_roi_extractor.featmap_strides)], rois)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 88, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 86, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/models/roi_extractors/single_level.py", line 106, in forwar
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 88, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/inspur/zxnan/myEnv/efficient_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 86, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/ops/roi_align/roi_align.py", line 145, in forward
    self.sample_num, self.aligned)
  File "/home/inspur/zxnan/EfficientPS-2.20.0/mmdet/ops/roi_align/roi_align.py", line 43, in forward
    raise NotImplementedError
NotImplementedError

**Comment by RangiLyu** [comment]
It seems the EfficientPS project uses MMDetection v1.x. Make sure you compiled all of the OPs.
