### ISSUE TITLE
Log file doesn't contain loss_cls

### ISSUE THREAD

**Issue by vakker** [open-mmlab/mmdetection#7040]
**Checklist**

- [x] I have searched related issues but cannot get the expected help.
- [x] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the latest version.

**Describe the bug**

I'm training a model and when I use `tools/analysis_tools/analyze_logs.py` as described in the [documentation](https://mmdetection.readthedocs.io/en/v2.18.0/useful_tools.html#log-analysis) I'm getting:
```
$ python tools/analysis_tools/analyze_logs.py plot_curve ./work_dirs/model/20220119_094759.log.json --keys loss_cls
plot curve of ./work_dirs/model/20220119_094759.log.json, metric is loss_cls
Traceback (most recent call last):
  File "/home/user/workspace/mmdet/tools/analysis_tools/analyze_logs.py", line 180, in <module>
    main()
  File "/home/user/workspace/mmdet/tools/analysis_tools/analyze_logs.py", line 176, in main
    eval(args.task)(log_dicts, args)
  File "/home/user/workspace/mmdet/tools/analysis_tools/analyze_logs.py", line 54, in plot_curve
    raise KeyError(
KeyError: './work_dirs/model/20220119_094759.log.json does not contain metric loss_cls'
```

Do I need to do anything in particular to include the `loss_cls` in the logs?

**Reproduction**

I'm running a training on a small dataset with:
```
log_config = dict(interval=5)
checkpoint_config = dict(interval=5)
runner = dict(type='EpochBasedRunner', max_epochs=10)
```
It produces the checkpoints and the log file has the following:
```
{"mode": "val", "epoch": 1, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 2, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 3, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 4, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 5, "iter": 2, "lr": 0.0, "bbox_mAP": 0.16, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.168, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.16, "bbox_mAP_copypaste": "0.160 0.252 0.168 -1.000 -1.000 0.160", "segm_mAP": 0.151, "segm_mAP_50": 0.168, "segm_mAP_75": 0.168, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.151, "segm_mAP_copypaste": "0.151 0.168 0.168 -1.000 -1.000 0.151"}
{"mode": "val", "epoch": 6, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 7, "iter": 2, "lr": 0.0, "bbox_mAP": 0.126, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.126, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.126, "bbox_mAP_copypaste": "0.126 0.252 0.126 -1.000 -1.000 0.126", "segm_mAP": 0.114, "segm_mAP_50": 0.126, "segm_mAP_75": 0.126, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.114, "segm_mAP_copypaste": "0.114 0.126 0.126 -1.000 -1.000 0.114"}
{"mode": "val", "epoch": 8, "iter": 2, "lr": 0.0, "bbox_mAP": 0.11, "bbox_mAP_50": 0.252, "bbox_mAP_75": 0.101, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.11, "bbox_mAP_copypaste": "0.110 0.252 0.101 -1.000 -1.000 0.110", "segm_mAP": 0.091, "segm_mAP_50": 0.101, "segm_mAP_75": 0.101, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.091, "segm_mAP_copypaste": "0.091 0.101 0.101 -1.000 -1.000 0.091"}
{"mode": "val", "epoch": 9, "iter": 2, "lr": 0.0, "bbox_mAP": 0.097, "bbox_mAP_50": 0.126, "bbox_mAP_75": 0.101, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.097, "bbox_mAP_copypaste": "0.097 0.126 0.101 -1.000 -1.000 0.097", "segm_mAP": 0.091, "segm_mAP_50": 0.101, "segm_mAP_75": 0.101, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.091, "segm_mAP_copypaste": "0.091 0.101 0.101 -1.000 -1.000 0.091"}
{"mode": "val", "epoch": 10, "iter": 2, "lr": 0.0, "bbox_mAP": 0.098, "bbox_mAP_50": 0.126, "bbox_mAP_75": 0.101, "bbox_mAP_s": -1.0, "bbox_mAP_m": -1.0, "bbox_mAP_l": 0.098, "bbox_mAP_copypaste": "0.098 0.126 0.101 -1.000 -1.000 0.098", "segm_mAP": 0.091, "segm_mAP_50": 0.101, "segm_mAP_75": 0.101, "segm_mAP_s": -1.0, "segm_mAP_m": -1.0, "segm_mAP_l": 0.091, "segm_mAP_copypaste": "0.091 0.101 0.101 -1.000 -1.000 0.091"}
```

**Environment**

```
sys.platform: linux
Python: 3.8.12 (default, Nov 17 2021, 08:17:37) [GCC 9.3.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.5.r11.5/compiler.30411180_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.5.4-dev
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.18.1+a7a16af
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by jbwang1997** [comment]
It seems the number of iterations in one epoch is less than the `interval` of logging. So, there is no training information printing in the log file. 
You can try to reduce the `interval` and ensure it is less than iterations of one epoch.

**Comment by vakker** [comment]
That works, thanks. 
So the `interval` is related to the SGD iterations, and not a full epoch, right?

**Comment by jbwang1997** [comment]
The `iterval` in the `log_config` means after how many iterations to print once information. The `iterval` in the `checkpoint_config` means after how many epochs to save once checkpoint.

**Comment by vakker** [comment]
Thanks for the clarification. Then one more question: is there a way to checkpoint during an epoch, or it can only be done after a whole epoch?

**Comment by jbwang1997** [comment]
It also can save checkpoints by iterations. You can refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py#L11 for details.

**Comment by vakker** [comment]
That's great, thanks for the clarification!

**Comment by keepgoing365** [comment]
我遇到了相同的问题，在configs/XXX/XXX.py配置文件中加上这行
log_config = dict(interval=5, hooks=[dict(type='TextLoggerHook')]) ###default50
将保存log 间隔epoch从50降为5生效了
