### ISSUE TITLE
DETR: Why the AP is still zero?

### ISSUE THREAD

**Issue by preminstrel** [open-mmlab/mmdetection#7065]
I use DETR to be my model. However, by the time consumed, the mAP is still zero! How can I fix it? Thanks for your time!
@env Google Colab Pro, Tesla P100 x 1
```bash
2022-01-23 09:34:04,450 - mmdet - INFO - Epoch [30][1700/1914]	lr: 1.000e-04, eta: 1 day, 0:53:57, time: 0.310, data_time: 0.007, memory: 2682, loss_cls: 0.6340, loss_bbox: 0.7269, loss_iou: 0.9467, d0.loss_cls: 0.6340, d0.loss_bbox: 0.7455, d0.loss_iou: 0.9307, d1.loss_cls: 0.6149, d1.loss_bbox: 0.7628, d1.loss_iou: 0.9419, d2.loss_cls: 0.6299, d2.loss_bbox: 0.7469, d2.loss_iou: 0.9007, d3.loss_cls: 0.6271, d3.loss_bbox: 0.7629, d3.loss_iou: 0.9817, d4.loss_cls: 0.6057, d4.loss_bbox: 0.7296, d4.loss_iou: 0.9133, loss: 13.8352, grad_norm: 122.4885
2022-01-23 09:34:19,980 - mmdet - INFO - Epoch [30][1750/1914]	lr: 1.000e-04, eta: 1 day, 0:53:21, time: 0.311, data_time: 0.007, memory: 2682, loss_cls: 0.8577, loss_bbox: 0.9509, loss_iou: 1.0904, d0.loss_cls: 0.8779, d0.loss_bbox: 0.9118, d0.loss_iou: 1.0630, d1.loss_cls: 0.8663, d1.loss_bbox: 0.9445, d1.loss_iou: 1.0946, d2.loss_cls: 0.8329, d2.loss_bbox: 0.9296, d2.loss_iou: 1.0548, d3.loss_cls: 0.8339, d3.loss_bbox: 0.8931, d3.loss_iou: 1.0901, d4.loss_cls: 0.8285, d4.loss_bbox: 0.9316, d4.loss_iou: 1.1168, loss: 17.1683, grad_norm: 111.5039
2022-01-23 09:34:35,550 - mmdet - INFO - Epoch [30][1800/1914]	lr: 1.000e-04, eta: 1 day, 0:52:48, time: 0.311, data_time: 0.007, memory: 2682, loss_cls: 0.6407, loss_bbox: 0.7397, loss_iou: 0.8846, d0.loss_cls: 0.6558, d0.loss_bbox: 0.7460, d0.loss_iou: 0.8977, d1.loss_cls: 0.6353, d1.loss_bbox: 0.7861, d1.loss_iou: 0.9433, d2.loss_cls: 0.6239, d2.loss_bbox: 0.7578, d2.loss_iou: 0.9046, d3.loss_cls: 0.6196, d3.loss_bbox: 0.7555, d3.loss_iou: 0.9204, d4.loss_cls: 0.6080, d4.loss_bbox: 0.8734, d4.loss_iou: 0.9794, loss: 13.9719, grad_norm: 111.2883
2022-01-23 09:34:51,085 - mmdet - INFO - Epoch [30][1850/1914]	lr: 1.000e-04, eta: 1 day, 0:52:14, time: 0.311, data_time: 0.007, memory: 2682, loss_cls: 0.6424, loss_bbox: 0.7029, loss_iou: 0.8696, d0.loss_cls: 0.6646, d0.loss_bbox: 0.7212, d0.loss_iou: 0.9079, d1.loss_cls: 0.6477, d1.loss_bbox: 0.7490, d1.loss_iou: 0.9256, d2.loss_cls: 0.6392, d2.loss_bbox: 0.6808, d2.loss_iou: 0.8410, d3.loss_cls: 0.6441, d3.loss_bbox: 0.7481, d3.loss_iou: 0.9541, d4.loss_cls: 0.6445, d4.loss_bbox: 0.7538, d4.loss_iou: 0.8992, loss: 13.6358, grad_norm: 104.3842
2022-01-23 09:35:06,607 - mmdet - INFO - Epoch [30][1900/1914]	lr: 1.000e-04, eta: 1 day, 0:51:39, time: 0.310, data_time: 0.006, memory: 2682, loss_cls: 0.6657, loss_bbox: 0.8133, loss_iou: 0.9617, d0.loss_cls: 0.6715, d0.loss_bbox: 0.6973, d0.loss_iou: 0.9084, d1.loss_cls: 0.6466, d1.loss_bbox: 0.6913, d1.loss_iou: 0.9413, d2.loss_cls: 0.6491, d2.loss_bbox: 0.6960, d2.loss_iou: 0.9029, d3.loss_cls: 0.6462, d3.loss_bbox: 0.8051, d3.loss_iou: 0.9619, d4.loss_cls: 0.6788, d4.loss_bbox: 0.7287, d4.loss_iou: 0.9151, loss: 13.9811, grad_norm: 110.2449
2022-01-23 09:35:10,988 - mmdet - INFO - Saving checkpoint at 3 epochs
[>>] 425/425, 15.0 task/s, elapsed: 28s, ETA:     0s2022-01-23 09:35:52,119 - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.16s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=1.02s).
Accumulating evaluation results...
DONE (t=1.00s).
2022-01-23 09:35:54,548 - mmdet - INFO - 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
```

**Comment by shinya7y** [comment]
DETR takes a very long time to converge.
Longer training might improve AP, considering `Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.002`.

Practically, it is better to use other methods (e.g., Deformable DETR) or pre-trained weights by `load_from = 'https://download.openmmlab.com/mmdetection/v2.0/detr/detr_r50_8x2_150e_coco/detr_r50_8x2_150e_coco_20201130_194835-2c4b8974.pth'`

**Comment by preminstrel** [comment]
@shinya7y Thanks for your time! I will take your useful advice. By the way, there maybe something wrong with Deformable DETR when using. I have tried `mmcv 1.4.3` and `mmcv 1.4.2`, resulting the same error below, called `RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`. How can I fix it now?

```bash
2022-01-23 09:34:39,343 - mmdet - INFO - workflow: [('train', 1)], max: 50 epochs
2022-01-23 09:34:39,344 - mmdet - INFO - Checkpoints will be saved to /content/gdrive/MyDrive/mmdetection/work_dirs/deformable_detr_r50_16x2_50e by HardDiskBackend.
/usr/local/lib/python3.7/dist-packages/mmdet/models/utils/positional_encoding.py:81: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature**(2 * (dim_t // 2) / self.num_feats)
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 192, in main
    meta=meta)
  File "/usr/local/lib/python3.7/dist-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

**Comment by shinya7y** [comment]
Please discuss in # 7017.

**Comment by preminstrel** [comment]
Ok, thanks!

**Comment by sibet-lb** [comment]
What is the meaning of "8x2" in the config name? This naming is different from other models' config naming but there is no explanation, which makes me confused. I look forward to your reply!

**Comment by preminstrel** [comment]
> What is the meaning of "8x2" in the config name? This naming is different from other models' config naming but there is no explanation, which makes me confused. I look forward to your reply!

@sibet-lb Hello, I guess that the 8 means `num_heads=8` and the 2 means `worker_per_gpu=2, samples_per_gpu=2`. Do you think so?

**Comment by shinya7y** [comment]
> `[gpu x batch_per_gpu]`: GPUs and samples per GPU, `8x2` is used by default.

https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/config.md#config-name-style
