### ISSUE TITLE
images2coco.py can't work well on win10.

### ISSUE THREAD

**Issue by cg1937** [open-mmlab/mmdetection#7103]
file location: tools\dataset_converters\images2coco.py
problem description: In win10, I want to get coco style annotation json file for my image dataset. and I try all kinds of input method to use it, but all failed. This is output:
```
(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py configs\cow\test\images 1 test.json png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: png

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py configs\cow\test\images 1 test.json 'png'
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: 'png'

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py configs\cow\test\images 1 test.json
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100/100, 90.3 task/s, elapsed: 1s, ETA:     0s
Traceback (most recent call last):
  File "tools\dataset_converters\images2coco.py", line 101, in <module>
    main()
  File "tools\dataset_converters\images2coco.py", line 89, in main
    classes = mmcv.list_from_file(args.classes)
  File "D:\Ancoda\envs\mmdet\lib\site-packages\mmcv\fileio\parse.py", line 44, in list_from_file
    with StringIO(file_client.get_text(filename, encoding)) as f:
  File "D:\Ancoda\envs\mmdet\lib\site-packages\mmcv\fileio\file_client.py", line 1006, in get_text
    return self.client.get_text(filepath, encoding)
  File "D:\Ancoda\envs\mmdet\lib\site-packages\mmcv\fileio\file_client.py", line 535, in get_text
    with open(filepath, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '1'

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images classes 1 out test.json -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: 1 out test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images  1 test.json -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py ^ img_path configs\cow\test\images ^ 1 ^ test.json ^  -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py ^ img_path configs\cow\test\images ^ 1 ^ out test.json ^  -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: out test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py ^ img_path configs\cow\test\images ^ 1 ^ annotation.json ^  -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: annotation.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images  cow annotation.json  -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: annotation.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images  cow test.json  -e png-e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images configs\cow\class.txt test.json -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: test.json

(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py img_path configs\cow\test\images\ configs\cow\class.txt test.json -e png
usage: images2coco.py [-h] [-e EXCLUDE_EXTENSIONS [EXCLUDE_EXTENSIONS ...]]
                      img_path classes out
images2coco.py: error: unrecognized arguments: test.json
```
and then I change images2coco.py 12,14,16 lines like this:
```
    parser.add_argument('--img_path', help='The root path of images')
    parser.add_argument(
        '--classes', type=str, help='The text file name of storage class list')
    parser.add_argument(
        '--out',
        type=str,
        help='The output annotation json file name, The save dir is in the '
        'same directory as img_path')
```
It can work, but there is a bug already in this file. if I use "-e 
 png" , it will output this problem:
```
(mmdet) E:\mmdetection>python tools\dataset_converters\images2coco.py --img_path configs\cow\test\images\ --classes configs\cow\class.txt --out test.json -e png
[                                                  ] 0/100, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools\dataset_converters\images2coco.py", line 101, in <module>
    main()
  File "tools\dataset_converters\images2coco.py", line 86, in main
    img_infos = collect_image_infos(args.img_path, args.exclude_extensions)
  File "tools\dataset_converters\images2coco.py", line 37, in collect_image_infos
    and not image_path.lower().endswith(exclude_extensions)):
TypeError: endswith first arg must be str or a tuple of str, not list
```
It seems parser use arg.exclude_extensions as a list, endswith function can't receive this type of arg. Maybe it can be changed in 38 line like this:
`and not image_path.lower().endswith(tuple(exclude_extensions))):`
The description of this part in the doc is too blurred. I think the description of this part can be more detailed.
And I have a suggestion that if the classes are small (I only have one class "cow"), this option can receive a list not a file.
Thank you for solving this problem!

**Comment by RangiLyu** [comment]
Thanks for your report. The doc of this script needs to be polished. If you have some suggestions, it would be really appreciated if you can create a PR.
