### ISSUE TITLE
Error Occurs when running train.py with the "image" field of json file (val2017.json) set empty

### ISSUE THREAD

**Issue by HiiiXinyiii** [open-mmlab/mmdetection#7105]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

+ It's not a critical bug but more like an improvement. 
+ The bug occurs when the "image" field of the json file named val2017.json is empty. So when validating after each train epoch, the index subscript will be out of range. 
+ It's advisable to assert this potential error when an empty dataloader is set or before it's used. Or the alternative plan is not to skip validating if the dataloader is empty.

**Reproduction**

1. The json file(modified from val2017.json) that I used. 

```json
    "licenses": [
        ...
    ],
    "images": [],
    "annotations": [
    {
        ...
    }
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

- I didn't modified the code and the config. I just extract a smaller dataset from the original coco dataset, including modifying the json file and extracting the pictures corresponding to the json file.

3. What dataset did you use?

+ COCO dataset which is modifed by me as said above

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```
sys.platform: linux
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1660 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.5.5
MMCV: 1.4.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.20.0+ff9bc39

```

**Error traceback**

```python
Traceback (most recent call last):
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/tools/train.py", line 196, in <module>
    main()
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/tools/train.py", line 185, in main
    train_detector(
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/PJLAB/chenxinyi/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 128, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/PJLAB/chenxinyi/anaconda3/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 55, in train
    self.call_hook('after_train_epoch')
  File "/home/PJLAB/chenxinyi/anaconda3/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/PJLAB/chenxinyi/anaconda3/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/mmdet/core/evaluation/eval_hooks.py", line 59, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/PJLAB/chenxinyi/anaconda3/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/mmdet/datasets/coco.py", line 416, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/mmdet/datasets/coco.py", line 361, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/PJLAB/chenxinyi/XinyiWorkspace/mmdetection/mmdet/datasets/coco.py", line 292, in results2json
    if isinstance(results[0], list):
IndexError: list index out of range
```

**Bug fix**

- The fixed code is from mmdetection/core/evaluation/eval_hooks.py

```python
    def _do_evaluate(self, runner):
        """perform evaluation and save ckpt."""
        if not self._should_evaluate(runner):
            return

        from mmdet.apis import single_gpu_test
        assert len(self.dataloader) != 0, "empty dataloader, which may be due to the \"image\" field of json file"
        results = single_gpu_test(runner.model, self.dataloader, show=False)

        runner.log_buffer.output['eval_iter_num'] = len(self.dataloader)
        key_score = self.evaluate(runner, results)
        if self.save_best:
            self._save_ckpt(runner, key_score)
```

- I added one assert sentence to notify the user that the dataloader is empty which could lead to an error later, since the model can not fetch any images from it. It can help the user to better find the potential error in advance.

- I put it here because the later validation operation is all based on the image data in the dataloader, and they all require it to contain some data in default, otherwise it will lead to error, which may not be easy for the user to understand how it happens quickly.

**Comment by hhaAndroid** [comment]
@Xinyi-Adv I'm more curious why the validation set is an empty image? If you don't want to do validation, consider just training.

**Comment by Xinyi-Adv** [comment]
It could be an accidental mistake made by the user. As an open source project, it could be more user-friendly to announce the user the possible reasons of the errors when it occurs.

**Comment by hhaAndroid** [comment]
@Xinyi-Adv Yes. This modification is best placed in the dataset.

**Comment by Xinyi-Adv** [comment]
ohhh Thank you. I have posted a new PR refering to your advice #7129
