### ISSUE TITLE
fatal: unable to access 'https://github.com/open-mmlab/mmdetection.git/': Could not resolve host: github.com: mim install mmdet fails to install mmdet

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mmdetection#7109]
I run `mim install mmdet` and get the following result

```
installing mmdet from https://github.com/open-mmlab/mmdetection.git.
Cloning into '/tmp/tmpb63s46qj/mmdetection'...
fatal: unable to access 'https://github.com/open-mmlab/mmdetection.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 418, in call_command
    subprocess.check_call(cmd)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/open-mmlab/mmdetection.git', '-b', 'v2.20.0', '/tmp/tmpb63s46qj/mmdetection']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/muhammadmehdi/anaconda3/envs/memex/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 107, in cli
    is_editable=is_editable)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 206, in install
    is_yes, is_user_dir, is_install_master)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 534, in install_from_github
    call_command(clone_cmd)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 420, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 392, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, CalledProcessError found
```

**Comment by jbwang1997** [comment]
It seems some issues with your internet connection, please check the internet or try several times.

**Comment by sarimmehdi** [comment]
@jbwang1997 it's still not working but git and pip seem to work fine. I am not behind a firewall but even when I am, git and pip work fine but not mim

**Comment by hhaAndroid** [comment]
@zhouzaida

**Comment by BIGWangYuDong** [comment]
Please make free to create a new issue if you still meet this problem
