### ISSUE TITLE
errors when i implement IouLoss in cascade_rcnn_hrnetv2p_w32_20e.py

### ISSUE THREAD

**Issue by jihuaxu** [open-mmlab/mmdetection#712]
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 91, in main
    logger=logger)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 171, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 180, in refine_bboxes
    img_meta_)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 202, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 91, in main
    main()
  File "./tools/train.py", line 91, in main
    logger=logger)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    logger=logger)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 171, in _dist_train
    _dist_train(model, dataset, cfg, validate=validate)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 171, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 262, in train
    epoch_runner(data_loaders[i], **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    self.model, data_batch, train_mode=True, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    losses = model(**data)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    return self.module(*inputs[0], **kwargs[0])
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
    return self.forward_train(img, img_meta, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 180, in refine_bboxes
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 180, in refine_bboxes
    img_meta_)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 202, in regress_by_class
    img_meta_)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 202, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 91, in main
    logger=logger)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 171, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 236, in forward_train
    rois, roi_labels, bbox_pred, pos_is_gts, img_meta)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 180, in refine_bboxes
    img_meta_)
  File "/cluster/home/it_stu21/main/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 202, in regress_by_class
    assert rois.size(1) == 4 or rois.size(1) == 5
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Traceback (most recent call last):
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/cluster/home/it_stu21/.conda/envs/mm/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/cluster/home/it_stu21/.conda/envs/mm/bin/python', '-u', './tools/train.py', '--local_rank=0', 'Transportation_cfg_new/cascade_rcnn_hrnetv2p_w40_transportation3.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by chituma110** [comment]
how did you implement the IouLoss? @jihuaxu

**Comment by jihuaxu** [comment]
> 
> 
> how did you implement the IouLoss? @jihuaxu
cfg file setting is like this:
bbox_head=[
        dict(
            type='SharedFCBBoxHead',
            num_fcs=2,
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=21,
            target_means=[0., 0., 0., 0.],
            target_stds=[0.1, 0.1, 0.2, 0.2],
            reg_class_agnostic=True,
            loss_cls=dict(
                type='CrossEntropyLoss',
                use_sigmoid=False,
                loss_weight=1.0),
            loss_bbox=dict(
                type='IoULoss',
                beta=1.0,
                loss_weight=1.0)),

**Comment by garrettmsft7** [comment]
Was this ever fixed?

**Comment by hellock** [comment]
#1436
