### ISSUE TITLE
How to train fast_rcnn model?

### ISSUE THREAD

**Issue by Soodep** [open-mmlab/mmdetection#7120]
For Faster RCNN I can easily  use the config/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py and train by making some changes to the voc0712.py file ( provide the path to ann_file) as I have the annotation and JPEG images but how do I train the Fast RCNN model? When I use the same method for Fast RCNN it gives me error saying:

Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 192, in main
    meta=meta)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmdet-2.20.0-py3.7.egg/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmdet-2.20.0-py3.7.egg/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmdet-2.20.0-py3.7.egg/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmdet-2.20.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/home/UNT/sd0570/anaconda3/envs/newmmdet/lib/python3.7/site-packages/mmdet-2.20.0-py3.7.egg/mmdet/models/roi_heads/standard_roi_head.py", line 91, in forward_train
    proposal_list[i], gt_bboxes[i], gt_bboxes_ignore[i],
TypeError: 'NoneType' object is not subscriptable

Am I missing somethig? 
Your help is highly appreciated.

**Comment by ZwwWayne** [comment]
You should first extract region proposals. Therefore, you should first train an RPN, use the RPN to extract the region proposals of the dataset, set the path of proposals in your Fast RCNN config, then train the model.

**Comment by Soodep** [comment]
How to train on RPN?

**Comment by Soodep** [comment]
ok after I train the RPN how can I extract the region proposals?

**Comment by zytx121** [comment]
Refer to #7549
