### ISSUE TITLE
When yolox_s_8x8_300e_coco.py is executed in v2.20.0, assert 'mix_results' in results is displayed at the 2nd epochs.

### ISSUE THREAD

**Issue by Keiku** [open-mmlab/mmdetection#7135]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

When `yolox_s_8x8_300e_coco.py` is executed in v2.20.0, `assert 'mix_results' in results` is displayed at the 2nd epochs. This has not happened in v2.18.0.

**Reproduction**

1. What command or script did you run?

```none
python tools/train.py configs/yolox/yolox_s_8x8_300e_coco.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

The contents of config have not changed.

3. What dataset did you use?

I am using a self-made dataset called tiny_coco sampled from the COCO dataset for verification. Almost unchanged COCO dataset.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.

```
⋊> ~/c/t/mmdetection-2.20.0 on main ⨯ python mmdet/utils/collect_env.py      17:50:07
sys.platform: linux
Python: 3.8.6 (default, Feb  8 2022, 15:06:25) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0: TITAN X (Pascal)
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.10.2+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.3+cu102
OpenCV: 4.5.5
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.20.0+03cd63e
⋊> ~/c/t/mmdetection-2.20.0 on main ⨯ 
```

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
2022-02-10 17:38:52,223 - mmdet - INFO - Epoch [1][600/626]     lr: 3.675e-04, eta: 13:19:52, time: 0.264, data_time: 0.010, memory: 7146, loss_cls: 2.5010, loss_bbox: 3.8971, loss_obj: 5.3728, loss: 11.7709
Traceback (most recent call last):
  File "tools/train.py", line 196, in <module>
    main()
  File "tools/train.py", line 185, in main
    train_detector(
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 64, in val
    for i, data_batch in enumerate(self.data_loader):
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 216, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 239, in prepare_train_img
    return self.pipeline(results)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/datasets/pipelines/transforms.py", line 2022, in __call__
    results = self._mosaic_transform(results)
  File "/home/keiichi_kuroyanagi/.pyenv/versions/3.8.6-tiny-coco-benchmark/lib/python3.8/site-packages/mmdet/datasets/pipelines/transforms.py", line 2048, in _mosaic_transform
    assert 'mix_results' in results
AssertionError

⋊> ~/c/t/mmdetection-2.20.0 on main ⨯ 
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@Keiku Whether you have made code modifications, you need to pay attention to the corresponding configuration files and code versions.

**Comment by Keiku** [comment]
@hhaAndroid It seems that there is no problem if `workflow = [('train', 1)]`. Is this the expected behavior?

```
diff --git a/mmdetection-2.20.0/configs/_base_/default_runtime.py b/mmdetection-2.20.0/configs/_base_/default_runtime.py
index 5fec22b..32f552c 100644
--- a/mmdetection-2.20.0/configs/_base_/default_runtime.py
+++ b/mmdetection-2.20.0/configs/_base_/default_runtime.py
@@ -13,4 +13,5 @@ dist_params = dict(backend='nccl')
 log_level = 'INFO'
 load_from = None
 resume_from = None
-workflow = [('train', 1), ('val', 1)]
+workflow = [('train', 1)]
⋊> ~/c/t/mmdetection-2.20.0 on main ⨯ 
```

**Comment by heartInsert** [comment]
I think maybe  you have  changed   the  train dataset  to  'mulitiImageDataset'  in  config , but you  didn't  change the  val  datatset to 'mulitiImageDataset' . When  you  write  workflow = [('train', 1), ('val', 1)] , Apparently  that   the  mmdetection  will report  this  asserterror ' assert 'mix_results' in results'  in  val .

**Comment by JiaLiangShen** [comment]
I have the same issue last week. One solution may work for you, @Keiku , you can change the parameter 'filter_empty_gt=True' in config to 'filter_empty_gt=False'. It works for me.

**Comment by Weizhongjin** [comment]
I also have the same issue when i  write `workflow = [('train', 1), ('val', 1)]`. I find the reason maybe at  [tool/train.py.](https://github.com/open-mmlab/mmdetection/blob/6b87ac22b8d9dea8cc28b9ce84909e6c311e6268/tools/train.py#L186-L189)
` ``python
   if len(cfg.workflow) == 2:
        val_dataset = copy.deepcopy(cfg.data.val)
        val_dataset.pipeline = cfg.data.train.pipeline
        datasets.append(build_dataset(val_dataset))
```
we can find that, the pipeline of val_dataset changes to pipeline of train_dataset.
But the type of val_dataset didn't change. 
All such problem exists because mmdetection have two kind of evalution system: 1. workflow 2. EvalHook

**Comment by momoko31** [comment]
> I think maybe you have changed the train dataset to 'mulitiImageDataset' in config , but you didn't change the val datatset to 'mulitiImageDataset' . When you write workflow = [('train', 1), ('val', 1)] , Apparently that the mmdetection will report this asserterror ' assert 'mix_results' in results' in val .

Agree it , I met the same problem , after deleting the parameter about validation in workflow, it solved. I guess that is because it does't add "type='MultiImageMixDataset'" to val dataset in config.

**Comment by Audrey528** [comment]
How do you guys solved the problem?
