### ISSUE TITLE
INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)

### ISSUE THREAD

**Issue by jamiechoi1995** [open-mmlab/mmdetection#7137]
I try to convert a faster rcnn model to trt, 
I can successfully convert it to onnx, but when I convert onnx to trt, I got the following error:

```python
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt.py", line 254, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt.py", line 45, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/workspace/mmcv-1.3.17/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node 147 (parseGraph): INVALID_GRAPH: Assertion failed: ctx->tensors().count(inputName)
```

my script:
```shell
ONNX_BACKEND=MMCVTensorRT python tools/deployment/pytorch2onnx.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py ../../faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

python tools/deployment/onnx2tensorrt.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py tmp.onnx --shape 800 1216
```

my environment:
python=3.6.9
pytorch=1.7.0
onnxruntime=1.8.1

**Comment by VJoer** [comment]
How is this problem solved?

**Comment by jamiechoi1995** [comment]
> How is this problem solved?

I forgot, it seems that mmcv should be compiled with TRT support. However, the use of mmdeploy is now encouraged.

**Comment by VJoer** [comment]
> > How is this problem solved?
> 
> I forgot, it seems that mmcv should be compiled with TRT support. However, the use of mmdeploy is now encouraged.

well, thank u
