### ISSUE TITLE
Error with onnx

### ISSUE THREAD

**Issue by agnJason** [open-mmlab/mmdetection#7145]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
while torch2onnx in swin-transformer(config: swin-s), error: RuntimeError: the derivative for 'indices' is not implemented

**Reproduction**

1. What command or script did you run?

```none
python tools/deployment/pytorch2onnx.py configs/swin/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco.py mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco_20210903_104808-b92c91f1.pth
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**
‘’‘
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
NVCC: Not Available
GCC: n/a
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 191627039
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191125 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 200203
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_7
5,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4  (built against CUDA 10.1)
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS  /GR  /w /EHa /bigobj -openmp -DNDEBUG -DUSE_FBGEMM, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=
OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.6.0
OpenCV: 4.5.5
MMCV: 1.4.4
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 10.2
MMDetection: 2.21.0+9894980
’‘’

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 345, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 100, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\onnx\utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\jit\__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\jit\__init__.py", line 361, in forward
    self._force_outplace,
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\jit\__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\detectors\base.py", line 169, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\detectors\two_stage.py", line 204, in onnx_export
    return self.roi_head.onnx_export(x, proposals, img_metas)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\roi_heads\standard_roi_head.py", line 299, in onnx_export
    x, img_metas, proposals, self.test_cfg, rescale=rescale)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\roi_heads\standard_roi_head.py", line 395, in bbox_onnx_export
    rois, cls_score, bbox_pred, img_shapes, cfg=rcnn_test_cfg)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\roi_heads\bbox_heads\bbox_head.py", line 586, in onnx_export
    labels=labels)
  File "C:\ProgramData\Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\core\export\onnx_helper.py", line 172, in add_dummy_nms_for_onnx
    mask[pos_inds, :] += 1
RuntimeError: the derivative for 'indices' is not implemented

```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by agnJason** [comment]
fix mmdet\core\export\onnx_helper.py
`mask[pos_inds.detach(), :] += 1`
works well

**Comment by chhluo** [comment]
What version of onnx are you using?

**Comment by RunningLeon** [comment]
> fix mmdet\core\export\onnx_helper.py, line 172 `mask[pos_inds.detach(), :] += 1` works well

@agnJason Hi, thanks for the info. Actually, we did not test with `swin-transformer` backbone yet. Glad to know it works. For deployment, we have [mmdeploy](https://github.com/open-mmlab/mmdeploy). You could have a try if possible.
