### ISSUE TITLE
yolact Out of memory during training

### ISSUE THREAD

**Issue by Masterzhuior** [open-mmlab/mmdetection#7148]
When using yolact for training, when an epoch ends, it will be **OOM** in the Val phase.

My environment is:

- Python  3.7.11
- CUDA  11.3
- CUDNN  8200
- numpy  1.21.2
- pycocotools  2.0.4 
- pytorch   1.10.1

The GPU is 3090 (24G Vram)

I just modified the `num_classes` in file `yolact_r50_1x8_coco.py`

then I started training `python tools/train.py configs/yolact/yolact_r50_1x8_coco.py` by using my dataset. 

My dataset：
- https://resources.mpi-inf.mpg.de/d2/orekondy/redactions/, The format of annotations has been changed to CoCo.

But when an epoch ends, it will be out of memory in the Val phase.

```
2022-02-13 14:38:01,355 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 26/1611, 0.6 task/s, elapsed: 43s, ETA:  2636sTraceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main()
  File "tools/train.py", line 191, in main
    meta=meta)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmdet/apis/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmdet/apis/test.py", line 28, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 50, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/zjj/anaconda3/envs/image/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zjj/anaconda3/envs/image/lib/pyth
```

**Comment by hhaAndroid** [comment]
@Masterzhuior It is possible that other programs occupy the GPU memory.

**Comment by Masterzhuior** [comment]
> 

No, I'm sure no other program is occupying the GPU memory.

**Comment by Masterzhuior** [comment]
> @Masterzhuior It is possible that other programs occupy the GPU memory.

No, I'm sure no other program is occupying the GPU memory.

**Comment by ZwwWayne** [comment]
The program fails during inference time. It might because the images are too big, you may try to resize them to a smaller size.

**Comment by Masterzhuior** [comment]
> The program fails during inference time. It might because the images are too big, you may try to resize them to a smaller size.

```
img_size = 550 
```
I tried to modify this parameter(550 to 400) in the model , but it still hasn't been solved.

**Comment by mikaizhu** [comment]
@ZwwWayne hi, how to resize image?

**Comment by ZwwWayne** [comment]
Modify the Resize module in the pipeline and make the image scale smaller.
