### ISSUE TITLE
Error while running mmdetection/tools/analysis_tools/analyze_results.py

### ISSUE THREAD

**Issue by vidushi27** [open-mmlab/mmdetection#7192]
File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/mmdetection/tools/analysis_tools/analyze_results.py", line 199, in <module>
    main()
  File "/content/mmdetection/tools/analysis_tools/analyze_results.py", line 182, in main
    cfg = Config.fromfile(args.config)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 334, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@vidushi27 This means your configuration file is wrong, especially `custom_imports`
