### ISSUE TITLE
ERROR: assert hasattr(dataset, 'flag')

### ISSUE THREAD

**Issue by jwwangchn** [open-mmlab/mmdetection#72]
I used the command 
> python tools/test.py configs/mask_rcnn_r50_fpn_1x.py weights/mask_rcnn_r50_fpn_1x_20181010-069fa190.pth --gpus 1 --out result.pkl 

to test the pretrained model. But I meet one error.  The output is

> loading annotations into memory...
Done (t=0.61s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/test.py", line 114, in <module>
    main()
  File "tools/test.py", line 84, in main
    shuffle=False)
  File "/home/jwwangchn/anaconda2/lib/python2.7/site-packages/mmdet/datasets/loader/build_loader.py", line 28, in build_dataloader
    sampler = GroupSampler(dataset, imgs_per_gpu)
  File "/home/jwwangchn/anaconda2/lib/python2.7/site-packages/mmdet/datasets/loader/sampler.py", line 14, in __init__
    assert hasattr(dataset, 'flag')
AssertionError

I have installed `mmcv 0.2.0` by source. I want to know how to solve this problem.

**Comment by hellock** [comment]
Thanks for your reports. This bug have been fixed in #73.
