### ISSUE TITLE
[YOLOX] TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

### ISSUE THREAD

**Issue by gitgitgithut** [open-mmlab/mmdetection#7209]
Hi there, I was trying to using yolox to run on my custom voc dataset and encountered the following error. Any help would be appreciated:

```
/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py:222: UserWarning: runner.meta is None. Creating an empty one.
  warnings.warn('runner.meta is None. Creating an empty one.')
Traceback (most recent call last):
  File "/mnt/d/Workspace/Python/mmdet/trainers/train_yolox.py", line 47, in <module>
    train_detector(model, train_dataset, cfg, distributed=False, validate=True)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 80, in collate
    return {
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 81, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 85, in collate
    return default_collate(batch)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>
```

The following is the content of my config file:
```
_base_ = ['../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py']

img_scale = (640, 640)
seed = 42
gpu_ids = [0]
work_dir = './'

custom_imports = dict(
    imports=['data.customDataset'], allow_failed_imports=False)

# model settings
model = dict(
    type='YOLOX',
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=1, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    # In order to align the source code, the threshold of the val phase is
    # 0.01, and the threshold of the test phase is 0.001.
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

# dataset settings
data_root = r"/mnt/d/Workspace/Python/dataset_public/welding seams/VOC2012/"
dataset_type = 'myVOCDataset'

train_pipeline = [
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/Main/train.txt',
        img_prefix=data_root,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline)



test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=1,
    workers_per_gpu=1,
    # persistent_workers=True,
    classes=['seam'],
    
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/Main/test.txt',
        img_prefix=data_root,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'ImageSets/Main/test.txt',
        img_prefix=data_root,
        pipeline=test_pipeline))

# optimizer
# default 8 gpu
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=5e-4,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))
optimizer_config = dict(grad_clip=None)

max_epochs = 300
num_last_epochs = 15
resume_from = None
interval = 10

# learning policy
lr_config = dict(
    _delete_=True,
    policy='YOLOX',
    warmup='exp',
    by_epoch=False,
    warmup_by_epoch=True,
    warmup_ratio=1,
    warmup_iters=5,  # 5 epoch
    num_last_epochs=num_last_epochs,
    min_lr_ratio=0.05)

runner = dict(type='EpochBasedRunner', max_epochs=max_epochs)

custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=num_last_epochs,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=num_last_epochs,
        interval=interval,
        priority=48),
    dict(
        type='ExpMomentumEMAHook',
        resume_from=resume_from,
        momentum=0.0001,
        priority=49)
]
checkpoint_config = dict(interval=interval, max_keep_ckpts=1)
load_from = "checkpoints/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth"
evaluation = dict(
    save_best='auto',
    # The evaluation interval is 'interval' when running epoch is
    # less than ‘max_epochs - num_last_epochs’.
    # The evaluation interval is 1 when running epoch is greater than
    # or equal to ‘max_epochs - num_last_epochs’.
    interval=interval,
    dynamic_intervals=[(max_epochs - num_last_epochs, 1)],
    metric='mAP')
log_config = dict(interval=50)
```

**Comment by hhaAndroid** [comment]
@gitgitgithut It may be that the configuration file is incorrect, resulting in no output data. Please use https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py to check.

**Comment by gitgitgithut** [comment]
> @gitgitgithut It may be that the configuration file is incorrect, resulting in no output data. Please use https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py to check.

Thank you for your reply. I ran browse_dataset.py and found some output images from the pipeline are blank. I will investigate if my custom VOCDataset implementation is responsible for this.

**Comment by gitgitgithut** [comment]
> @gitgitgithut It may be that the configuration file is incorrect, resulting in no output data. Please use https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py to check.



> > @gitgitgithut It may be that the configuration file is incorrect, resulting in no output data. Please use https://github.com/open-mmlab/mmdetection/blob/master/tools/misc/browse_dataset.py to check.
> 
> Thank you for your reply. I ran browse_dataset.py and found some output images from the pipeline are blank. I will investigate if my custom VOCDataset implementation is responsible for this, since my pipelines are exactly the same as the one in official yolox_s config file

Hi @hhaAndroid ,  I just found out that the aforementioned blank output images are due to my unresponsive pop out window.s  The correct images actually show up if I simply hover my cursor onto the window.  Therefore I think my pipelines and dataset have no issues.

However, I failed to mention an important detail: when I train my model with this config file, I encountered an error due to the infinite recursion:
```
File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 78, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 78, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 78, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded in comparison
```
I also tried to run YOLOX on the official Pascal VOC dataset and this issue persisted.

Then I did some searches online and found #https://github.com/open-mmlab/mmcv/issues/1387, and made some modifications to [mmcv.parallel.collate.py](https://github.com/open-mmlab/mmcv/blob/master/mmcv/parallel/collate.py) at line 74 according to #https://github.com/open-mmlab/mmcv/pull/1445, which eventually led me to the error I mentioned in my first post. 

Would you please try to reproduce this error on your device with the official Pascal VOC dataset?
