### ISSUE TITLE
AssertionError: The `num_classes` (80) in UniFormer of MMDistributedDataParallel does not matches the length of `CLASSES` 54) in CocoDataset

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmdetection#7220]
`Traceback (most recent call last):
  File "./tools/train.py", line 187, in <module>
    main()
  File "./tools/train.py", line 183, in main
    meta=meta)
  File "/home/lbc/UniFormer/object_detection/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/lbc/UniFormer/object_detection/mmdet/datasets/utils.py", line 150, in before_train_epoch
    self._check_head(runner)
  File "/home/lbc/UniFormer/object_detection/mmdet/datasets/utils.py", line 137, in _check_head
    (f'The `num_classes` ({module.num_classes}) in '
AssertionError: The `num_classes` (80) in UniFormer of MMDistributedDataParallel does not matches the length of `CLASSES` 54) in CocoDataset
`

**Comment by ZwwWayne** [comment]
Could you use the issue template to provide more information? 
It seems that your config is wrong.

**Comment by Williamlizl** [comment]
> Could you use the issue template to provide more information? It seems that your config is wrong.

I use the model: https://github.com/Sense-X/UniFormer

**Comment by hhaAndroid** [comment]
@Williamlizl Please check the `num_class` attribute in the configuration file.
