### ISSUE TITLE
python3.7 测试的时候加载数据报错 TypeError: can't pickle dict_keys objects

### ISSUE THREAD

**Issue by Light--** [open-mmlab/mmdetection#7243]
```
Traceback (most recent call last):
  File "tools/test.py", line 246, in <module>
    main()
  File "tools/test.py", line 223, in main
    args.gpu_collect)
  File "/home/xxx/lib/python3.7/site-packages/mmdet/apis/test.py", line 100, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/xxx/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 360, in __iter__
    return self._get_iterator()
  File "/home/xxx/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 306, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/xxx/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 919, in __init__
    w.start()
  File "/home/xxx/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/xxx/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/xxx/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/xxx/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/xxx/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/xxx/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/xxx/lib/python3.7/multiprocessing/reduction.py", line 61, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle dict_keys objects
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 82601) of binary: /home/xxx/bin/python
Traceback (most recent call last):
  File "/home/xxx/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xxx/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxx/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-24_14:57:48
  host      : k8s-deploy-xxx
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 82601)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================


```

**Comment by ZwwWayne** [comment]
Hi @Light-- ，
Could you follow the `issue template` to provide more details about the failure? For now, we are not able to help given limited information.
