### ISSUE TITLE
Training with customized dataset - Balloon example 

### ISSUE THREAD

**Issue by jankrans** [open-mmlab/mmdetection#7275]
When following this tutorial to train the balloon dataset I get the following error:
`(mmlab) C:\Users\jkranzen\mmdetection>python tools/train.py configs/balloon/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_balloon.py`
> Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1353, in _path_importer_cache
KeyError: 'C:\\Users\\jkranzen\\AppData\\Local\\Temp\\tmpiaav39sd'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "C:\Users\jkranzen\mmdetection\tools\train.py", line 209, in <module>
    main()
  File "C:\Users\jkranzen\mmdetection\tools\train.py", line 100, in main
    cfg = Config.fromfile(args.config)
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\site-packages\mmcv\utils\config.py", line 334, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\site-packages\mmcv\utils\config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\site-packages\mmcv\utils\config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\site-packages\mmcv\utils\config.py", line 248, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  [Previous line repeated 980 more times]
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\site-packages\mmcv\utils\config.py", line 206, in _file2dict
    mod = import_module(temp_module_name)
  File "C:\Users\jkranzen\Miniconda3\envs\mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1383, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1355, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1331, in _path_hooks
  File "<frozen importlib._bootstrap_external>", line 1599, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 163, in _path_isdir
  File "<frozen importlib._bootstrap_external>", line 148, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 142, in _path_stat
RecursionError: maximum recursion depth exceeded while calling a Python object

**Additional info**
I followed the tutorial step by step, converted the json-file successfully to a coco-json. It also seems to recognize the correct files at the correct directories...

**Environment**
I followed this thread to install everything on Windows: https://github.com/open-mmlab/mmcv/issues/1623
Python 3.9.7
CUDA 11.3 (Nvidea Geforce MX130)
TorchVision: 0.11.1
MMCV: 1.4.2
MMDetection: 2.20.0->2.22.0

**Comment by jankrans** [comment]
Wrong pathfile in config path to _base_ caused the problem. Closing the issue.

**Comment by leonlee723** [comment]
I have the same issue, how to resolve it? Thanks
