### ISSUE TITLE
'NoneType' object has no attribute 'sample_all'

### ISSUE THREAD

**Issue by sxs505** [open-mmlab/mmdetection#7280]
Traceback (most recent call last):
  File "tools/train.py", line 245, in <module>
    main()
  File "tools/train.py", line 241, in main
    meta=meta)
  File "/data/.conda/envs/mmdetection3d/mmdet3d/apis/train.py", line 71, in train_model
    meta=meta)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 178, in __getitem__
    return self.dataset[idx % self._ori_len]
  File "/data/.conda/envs/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 361, in __getitem__
    data = self.prepare_train_data(idx)
  File "/data/.conda/envs/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 155, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/home/aidrive1/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/data/.conda/envs/mmdetection3d/mmdet3d/datasets/pipelines/transforms_3d.py", line 329, in __call__
    sampled_dict = self.db_sampler.sample_all(
AttributeError: 'NoneType' object has no attribute 'sample_all'

**Comment by hhaAndroid** [comment]
@sxs505 Please go to mmdet3d to create an issue.
