### ISSUE TITLE
pytorch2onnx gives "RuntimeError: expected scalar type Long but found Float" with DETR model

### ISSUE THREAD

**Issue by mdcaio** [open-mmlab/mmdetection#7285]
Hi,

I'm following https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html#list-of-supported-models-exportable-to-onnx in order to export a trained DETR model to onnx format. I run:
`python /path/to/mmdetection/tools/deployment/pytorch2onnx.py /path/to/detr_r50_8x2_150e_coco_4_classes.py /path/to/checkpoint.pth --input-img /path/to/my_img.png --output-file /path/to/epoch_6.onnx`

According to the tutorial, DETR should be supported by pytorch2onnx.py, but it doesn't actually work. After a very long TraceBack, it gives this error:
```
Traceback (most recent call last):
  File "<some_path>/mmdetection/tools/deployment/pytorch2onnx.py", line 333, in <module>
    pytorch2onnx(
  File "<some_path>/mmdetection/tools/deployment/pytorch2onnx.py", line 89, in pytorch2onnx
    torch.onnx.export(
  File "<some_path>/miniconda3/envs/<my-env>/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "<some_path>/miniconda3/envs/<my-env>/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "<some_path>/miniconda3/envs/<my-env>/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "<some_path>/miniconda3/envs/<my-env>/lib/python3.8/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: expected scalar type Long but found Float
```
Note that the only difference between the standard config file and the one I'm using is in the number of output classes (4 instead of 80). With this config, the model trained well and works well at inference.

Any ideas?

Many thanks in advance.

**Comment by mdcaio** [comment]
it actually works with PyTorch 1.10. Doesn't work with PyTorch 1.9. Maybe it should be written somewhere?

**Comment by Zalways** [comment]
> it actually works with PyTorch 1.10. Doesn't work with PyTorch 1.9. Maybe it should be written somewhere?

i met the same problem with you, in pytorch1.9(cuda 11.1) :
params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: expected scalar type Long but found Float;
but when i change pytorch 1.10(cuda 11.3),it shows another error:
Traceback (most recent call last):
  File "deploy/export_model00.py", line 227, in <module>
    exported_model = export_tracing(torch_model, sample_inputs)
  File "deploy/export_model00.py", line 132, in export_tracing
    torch.onnx.export(traceable_model, image, f, input_names=['input'], output_names=['output'], opset_version=11,dynamic_axes={'input':[1,2],'output':[1,2]})
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool, 

do you encountered this problem? @mdcaio  looking forward to your reply
