### ISSUE TITLE
There are still bugs in the scripts used to run validation in train.py

### ISSUE THREAD

**Issue by pcicales** [open-mmlab/mmdetection#7314]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Training scripts do not use the val pipeline when building the validation dataset, throwing the forward_train() missing 2 required positional arguments: 'gt_boxes' and 'gt_labels' error. 

**Reproduction**

1. What command or script did you run?
```
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector
from mmcv import Config
import mmcv
import os.path as osp

cfg = Config.fromfile('<config>')

# Build dataset
datasets = [build_dataset(cfg.data.train), build_dataset(cfg.data.val)]

# Build the detector
model = build_detector(
    cfg.model,
    train_cfg=cfg.get('train_cfg'),
    test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?

Default mask rcnn settings on a custom dataset that I have used many times with this repo.

5. What dataset did you use?

nuimage

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
3. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    conda
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**

```
2022-03-03 01:51:24,996 - mmdet - INFO - Epoch(val) [1][16445] bbox_mAP: 0.0580, bbox_mAP_50: 0.1260, bbox_mAP_75: 0.0460, bbox_mAP_s: 0.0360, bbox_mAP_m: 0.0670, bbox_mAP_l: 0.0820, bbox_mAP_copypaste: 0.058 0.126 0.046 0.036 0.067 0.082, segm_mAP: 0.0490, segm_mAP_50: 0.1080, segm_mAP_75: 0.0390, segm_mAP_s: 0.0200, segm_mAP_m: 0.0590, segm_mAP_l: 0.0880, segm_mAP_copypaste: 0.049 0.108 0.039 0.020 0.059 0.088
Traceback (most recent call last):
  File "/workspace/pycharm_projects/mmdetection/train_debugging.py", line 23, in <module>
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "/workspace/pycharm_projects/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 97, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/workspace/pycharm_projects/mmdetection/mmdet/models/detectors/base.py", line 263, in val_step
    losses = self(**data)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/workspace/pycharm_projects/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes' and 'gt_labels'

Process finished with exit code 1
```

**Bug fix**
You need to properly set the validation pipeline in train. Currently, in line 188 of train.py, you set the val dataset pipeline following:

```
val_dataset.pipeline = cfg.data.train.pipeline
```

This was discussed in #5990, where the user there changed this line to use the val pipeline. However, @hhaAndroid said the following:

@jiangnanwuyanzu The above approach (changing line 188 to `val_dataset.pipeline = cfg.data.val.pipeline`) is correct because the val pipeline does not have GT. At the same time, we do not recommend using val workflow but evalhook.

It is not clear what is meant by this - the training script does not appear to do this automatically, which is why I believe this is a bug.
 
Interestingly, this error is thrown AFTER the script successfully produces my validation set classwise results... so it is a very confusing issue. I do not want to change the scripts in your repo, especially since it seems that this is somehow intended behavior.. but it seems like line 188 should be changed since the evalhook is causing training to crash after 1 validation round.

**Comment by jbwang1997** [comment]
Hi @pcicales. The results of the validation are produced by `evalhook`. The crashing is brought by [val workflow](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L256) which also needs ground truths to get losses. If you only need validation results, `datasets = build_dataset(cfg.data.train)` is enough.

**Comment by pcicales** [comment]
The following code:

```
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import train_detector
from mmcv import Config
import mmcv
import os.path as osp

cfg = Config.fromfile('config')

# Build dataset
datasets = [build_dataset(cfg.data.train)]

# Build the detector
model = build_detector(
    cfg.model,
    train_cfg=cfg.get('train_cfg'),
    test_cfg=cfg.get('test_cfg'))
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES

# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```

yields the following error:


```
loading annotations into memory...
Done (t=6.43s)
creating index...
index created!
Traceback (most recent call last):
  File "/workspace/pycharm_projects/mmdetection/train_single_gpu.py", line 23, in <module>
    train_detector(model, datasets, cfg, distributed=False, validate=True)
  File "/workspace/pycharm_projects/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/anaconda3/envs/openmmlab_03012022/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 85, in run
    assert len(data_loaders) == len(workflow)
AssertionError

Process finished with exit code 1
```

The correct syntax is not intuitive. What is the issue with these commands? They are from the documentation... @jbwang1997

**Comment by jbwang1997** [comment]
Thanks for your suggestion. We will continue to improve related documents.
For your question, the val workflow actually has the same logic as the train workflow. The difference between them is they execute different hook functions. For example, the train workflow calls `before_train_iter` and `before_train_iter` functions while the val workflow calls `before_val_iter` and `before_val_iter` functions. It is worth noting that the `return_loss` is still True in the val workflow thus the model needs the same input as the train workflow. That's why we need to set `val_dataset.pipeline = cfg.data.val.pipeline`. You can refer to details at [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/epoch_based_runner.py#L40-L70).

The evaluation function is implemented in EvalHook and called in train workflow. As referring to [EvalHook](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/evaluation.py), the `_do_evaluate` function is called in `after_train_iter`. That's why you can successfully get evaluation results once and then meet the val workflow error.

**Comment by pcicales** [comment]
@jbwang1997 thank you, I think I am beginning to understand. Thank you very much for your help, looking forward to using this repo again :)

**Comment by gitgitgithut** [comment]
> Hi @pcicales. The results of the validation are produced by `evalhook`. The crashing is brought by [val workflow](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L256) which also needs ground truths to get losses. If you only need validation results, `datasets = build_dataset(cfg.data.train)` is enough.

Hi @jbwang1997 , then how do we enable validation losses calculation without using workflow?
From what I am understanding, the `_do_evaluation()` in `EvalHook` calls `single_gpu_test()` to perform validations, which does not calculate the loss at all since the argument `return_loss` is set to false:
```
def single_gpu_test(model,
                    data_loader,
                    show=False,
                    out_dir=None,
                    show_score_thr=0.3):
    model.eval()
    results = []
    dataset = data_loader.dataset
    PALETTE = getattr(dataset, 'PALETTE', None)
    prog_bar = mmcv.ProgressBar(len(dataset))
    for i, data in enumerate(data_loader):
        with torch.no_grad():
            result = model(return_loss=False, rescale=True, **data)
```
Therefore I set `return_loss` to value `True`, and also modified `val_pipeline` in my config file (I am using YOLOX) so that it loads the gts, which should enable loss calculations:
```
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ])
]
```
However, the dataloader simply threw an exception at me:
```
Exception has occurred: KeyError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 216, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 259, in prepare_test_img
    return self.pipeline(results)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/loading.py", line 389, in __call__
    results = self._load_bboxes(results)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/loading.py", line 251, in _load_bboxes
    ann_info = results['ann_info']
KeyError: 'ann_info'
```
Even if I set my `val_pipeline=train_pipeline` (which is exactly what `tools/train.py` does when using 'workflow = [('train', 1),('val',1)]') the validation dataloader still refused to work:
```
Exception has occurred: AssertionError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 216, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 259, in prepare_test_img
    return self.pipeline(results)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/transforms.py", line 2022, in __call__
    results = self._mosaic_transform(results)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/transforms.py", line 2048, in _mosaic_transform
    assert 'mix_results' in results
AssertionError
```
This is the exact same assertion error as the one when using 'workflow = [('train', 1),('val',1)]'. Would you please kindly explain me what is going on here? And is there any workaround for this?

**Comment by jbwang1997** [comment]
@gitgitgithut In your case, I suggest you use the val workflow. You can try to write a custom hook to restore each iteration loss in `after_val_iter` and then analyze them in `after_val_epoch`. It's much easier.

**Comment by gitgitgithut** [comment]
> @gitgitgithut In your case, I suggest you use the val workflow. You can try to write a custom hook to restore each iteration loss in `after_val_iter` and then analyze them in `after_val_epoch`. It's much easier.

@jbwang1997 Thank you for your suggestion.  
Would you please also provide me some insights into the  `KeyError: 'ann_info'` thew by dataloader?

**Comment by jbwang1997** [comment]
This is because the `test_mode` of val dataset is True in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L183.

**Comment by gitgitgithut** [comment]
> This is because the `test_mode` of val dataset is True in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/apis/train.py#L183.

Thank you  @jbwang1997, this really helps me understand how hook works in mmdet.
Following your suggestion, I implemented the `before_val_epoch()` and `after_val_epoch()` in `eval_hook`. However, after setting `test_mode` to `False` for my validation dataset, I got the following error during validation:
```
/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180487213/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-03-11 15:07:33,866 - mmdet - INFO - Epoch [1][1/2] lr: 2.500e-03, eta: 25 days, 19:13:15, time: 3721.528, data_time: 3719.171, memory: 1035, loss_cls: 1.7388, loss_bbox: 4.0778, loss_obj: 12.1705, loss: 17.9871, grad_norm: 275.3524
2022-03-11 15:07:34,321 - mmdet - INFO - Exp name: yolox_s_8x8_300e_voc0712.py
2022-03-11 15:07:34,322 - mmdet - INFO - Epoch [1][2/2] lr: 1.000e-02, eta: 12 days, 21:07:50, time: 0.448, data_time: 0.055, memory: 1105, loss_cls: 1.4485, loss_bbox: 3.6382, loss_obj: 7.3110, loss: 12.3977, grad_norm: 238.6587
2022-03-11 15:07:34,378 - mmdet - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/Workspace/Python/mmdet/tools/mytrain.py", line 212, in <module>
    main()
  File "/mnt/d/Workspace/Python/mmdet/tools/mytrain.py", line 201, in main
    train_detector(
  File "/mnt/d/Workspace/Python/mmdet/hooks/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 67, in val
    self.run_iter(data_batch, train_mode=False)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    outputs = self.model.val_step(data_batch, self.optimizer, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 97, in val_step
    return self.module.val_step(*inputs[0], **kwargs[0])
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 263, in val_step
    losses = self(**data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/models/detectors/yolox.py", line 93, in forward_train
    losses = super(YOLOX, self).forward_train(img, img_metas, gt_bboxes,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/models/detectors/single_stage.py", line 81, in forward_train
    super(SingleStageDetector, self).forward_train(img, img_metas)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 80, in forward_train
    img_meta['batch_input_shape'] = batch_input_shape
TypeError: list indices must be integers or slices, not str
```
This was thrown by my validation dataloader at https://github.com/open-mmlab/mmcv/blob/c4b02566cfeb42185041c34ec36f09ad7a5b8589/mmcv/runner/epoch_based_runner.py#L64.

It seems that during training, `img_metas` is of type `List[Dict]`, while during validation it is of type `List[List[Dict]]`, which leads to this type Error..... 

Is there anything else I should modify? The following is my config code (note that I now use `test_dataset` for `eval_hook` validation, and use `val_dataset` for workflow validation):
``` 
_base_ = ['../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py']

img_scale = (640, 640)


custom_imports = dict(
    imports=['data.customDataset'], allow_failed_imports=False)

# model settings
model = dict(
    type='YOLOX',
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    # backbone=dict(type="MobileNetV2")
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=1, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    # In order to align the source code, the threshold of the val phase is
    # 0.01, and the threshold of the test phase is 0.001.
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

# dataset settings
data_root = '/home/vok5/welding_seams/VOC2012'
dataset_type = 'myVOCDataset'

train_pipeline = [
    dict(type='Mosaic', img_scale=img_scale, pad_val=114.0),
    dict(
        type='RandomAffine',
        scaling_ratio_range=(0.1, 2),
        border=(-img_scale[0] // 2, -img_scale[1] // 2)),
    dict(
        type='MixUp',
        img_scale=img_scale,
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    # According to the official implementation, multi-scale
    # training is not considered here but in the
    # 'mmdet/models/detectors/yolox.py'.
    dict(type='Resize', img_scale=img_scale, keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        # If the image is three-channel, the pad value needs
        # to be set separately for each channel.
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]

train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type=dataset_type,
        ann_file=data_root + '/ImageSets/Main/temp.txt',
        img_prefix=data_root,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False,
    ),
    pipeline=train_pipeline)

val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ])
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=img_scale,
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    persistent_workers=True,
    train=train_dataset,
    val=dict(
        type=dataset_type,
        ann_file=data_root + '/ImageSets/Main/test.txt',
        img_prefix=data_root,
        pipeline=val_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + '/ImageSets/Main/test.txt',
        img_prefix=data_root,
        pipeline=test_pipeline))

# optimizer
# default 8 gpu
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=5e-4,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0., bias_decay_mult=0.))
optimizer_config = dict(_delete_=True, grad_clip=dict(max_norm=35, norm_type=2))

max_epochs = 300
num_last_epochs = 15
resume_from = None
interval = 1

# learning policy
lr_config = dict(
    _delete_=True,
    policy='YOLOX',
    warmup='exp',
    by_epoch=False,
    warmup_by_epoch=True,
    warmup_ratio=1,
    warmup_iters=1,  # 5 epoch
    num_last_epochs=num_last_epochs,
    min_lr_ratio=0.05)

runner = dict(type='EpochBasedRunner', max_epochs=max_epochs)

custom_hooks = [
    dict(
        type='YOLOXModeSwitchHook',
        num_last_epochs=num_last_epochs,
        priority=48),
    dict(
        type='SyncNormHook',
        num_last_epochs=num_last_epochs,
        interval=interval,
        priority=48),
    dict(
        type='ExpMomentumEMAHook',
        resume_from=resume_from,
        momentum=0.0001,
        priority=49)
]
checkpoint_config = dict(interval=interval, max_keep_ckpts=1)
load_from = 'checkpoints/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth'
evaluation = dict(
    save_best='auto',
    # The evaluation interval is 'interval' when running epoch is
    # less than ‘max_epochs - num_last_epochs’.
    # The evaluation interval is 1 when running epoch is greater than
    # or equal to ‘max_epochs - num_last_epochs’.
    interval=interval,
    dynamic_intervals=[(max_epochs - num_last_epochs, 1)],
    metric='mAP')
log_config = dict(interval=interval,
                  hooks=[dict(type='TextLoggerHook'),
                         dict(type='TensorboardLoggerHook')]
                  )
workflow = [('train', 1),('val', 1)]

```

**Comment by jbwang1997** [comment]
`MultiScaleFlipAug` is prepared for the test. You can directly use train_pipeline in val dataset.

**Comment by gitgitgithut** [comment]
> `MultiScaleFlipAug` is prepared for the test. You can directly use train_pipeline in val dataset.

Thank you for your suggestion. After I set my `val_pipeline=train_pipeline`, I again got the `assert 'mix_up'` error. I think this is because that my `val_dataset` is not a `MultiImageMixDataset`? 

I also tried to simply disable `MultiScaleFlipAug` in my `val_pipeline`, which looks like this now:
``` 
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
```
But during validation I instead got this key error:
``` 
2022-03-12 10:51:31,009 - mmdet - INFO - Epoch [1][2/2] lr: 1.000e-02, eta: 0:43:54, time: 1.398, data_time: 1.065, memory: 1107, loss_cls: 0.2665, loss_bbox: 4.8563, loss_obj: 11.5434, loss: 16.6662, grad_norm: 460.8017
2022-03-12 10:51:31,059 - mmdet - INFO - Saving checkpoint at 1 epochs
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/vok5/.vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/d/Workspace/Python/mmdet/tools/mytrain.py", line 212, in <module>
    main()
  File "/mnt/d/Workspace/Python/mmdet/tools/mytrain.py", line 201, in main
    train_detector(
  File "/mnt/d/Workspace/Python/mmdet/hooks/train.py", line 209, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 64, in val
    for i, data_batch in enumerate(self.data_loader):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/custom.py", line 241, in prepare_train_img
    return self.pipeline(results)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/vok5/miniconda3/envs/mmlab/lib/python3.9/site-packages/mmdet/datasets/pipelines/formatting.py", line 343, in __call__
    img_meta[key] = results[key]
KeyError: 'flip'
```
This is interesting..... I have already disabled `MultiScaleFlipAug` but it still looks for flipping augmentation....

**Comment by jiangnanwuyanzu** [comment]
您好Dear,您的邮件我已收到，感谢您的来信，我会尽快给您回复。Thank you for your email and I have got that.I will respond soon.       顺颂时祺！                                                      Best wishes

**Comment by LaniakeaYanzu** [comment]
您好Dear,您的邮件我已收到，感谢您的来信，我会尽快给您回复。Thank you for your email and I have got that.I will respond soon.       顺颂时祺！                                                      Best wishes

**Comment by not-hermione** [comment]
> It is worth noting that the `return_loss` is Still True in the val workflow thus the model needs the same input as the train workflow. That's why we need to set `val_dataset.pipeline = cfg.data.val.pipeline`

Is the above reason for the following bug?
Suppose I set to train for 1 epoch. I find while setting workflow=[('train',1),('val',1)], there is a train epoch followed by a val epoch and an additional train epoch after that, which doesn't get recorded in the log file also.
