### ISSUE TITLE
Error while installing fatal error: utils/spconv/spconv/geometry.h: No such file or directory

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdetection#7410]
I'm doing a fresh installation of mmdetection. The steps I used are as follows:

```
conda create -n openmmlab python=3.7 -y
conda activate openmmlab
conda install pytorch torchvision -c pytorch
pip install openmim
mim install mmdet
```

but it is giving me following error:
```
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    ./mmcv/ops/csrc/pytorch/cpu/sparse_indice.cpp:16:42: fatal error: utils/spconv/spconv/geometry.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/deploy/miniconda3/envs/openmmlab/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n7iqd541/mmcv-full_3916fd9986d4412fb2fff0268f620a30/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n7iqd541/mmcv-full_3916fd9986d4412fb2fff0268f620a30/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2mwbht6p/install-record.txt --single-version-externally-managed --compile --install-headers /home/deploy/miniconda3/envs/openmmlab/include/python3.7m/mmcv-full Check the logs for full command output.
Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 418, in call_command
    subprocess.check_call(cmd)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'pip', '--default-timeout', '45', 'install', 'mmcv-full==1.4.6', '-f', 'https://download.openmmlab.com/mmcv/dist/cu113/torch1.11.0/index.html']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 107, in cli
    is_editable=is_editable)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 206, in install
    is_yes, is_user_dir, is_install_master)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 541, in install_from_github
    is_user_dir=is_user_dir)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 460, in install_from_repo
    install_dependencies(dependencies, timeout, is_yes, is_user_dir)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 381, in install_dependencies
    is_user_dir=is_user_dir)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 212, in install
    is_user_dir)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/install.py", line 574, in install_from_wheel
    call_command(install_cmd)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 420, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/utils/utils.py", line 392, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, CalledProcessError found
```

**Comment by Tacha-S** [comment]
I had the same problem, but downgraded to pytorch==1.10.0 and it worked.

**Comment by anshkumar** [comment]
pytorch==1.10.0 is working fine.
