### ISSUE TITLE
ImportError: cannot import name 'download_url_to_file' from 'torch.hub'

### ISSUE THREAD

**Issue by sxy1122** [open-mmlab/mmdetection#7417]
After I configured the environment and prepared to run the code, the following problems occurred. I don't know where the problem is

Traceback (most recent call last):
  File "./tools/train.py", line 8, in <module>
    import mmcv
  File "/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/utils/__init__.py", line 40, in <module>
    from .hub import load_url
  File "/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/utils/hub.py", line 19, in <module>
    from torch.hub import HASH_REGEX, _get_torch_home, download_url_to_file
ImportError: cannot import name 'download_url_to_file' from 'torch.hub' (/home/fuwuqi/test/anaconda3/envs/mm2/lib/python3.7/site-packages/torch/hub.py)
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

**Comment by BIGWangYuDong** [comment]
> No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

Please check whether you have successfully installed CUDA in your environment. Seems this is a CUDA error.

**Comment by sxy1122** [comment]
> > No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
> 
> Please check whether you have successfully installed CUDA in your environment. Seems this is a CUDA error.

I dealt with this problem, but there are still problems

ImportError: cannot import name 'download_url_to_file' from 'torch.hub

**Comment by dingddx** [comment]
I have the same problem.

**Comment by jbwang1997** [comment]
The version of pytorch may be too low. Before 1.2.0 there is no `download_url_to_file` in torch.hub. Please upgrade pytorch.

**Comment by jbwang1997** [comment]
This pr will be closed. Feel free to repoen this pr if you have any questions.
