### ISSUE TITLE
ubunut20.04安装报错

### ISSUE THREAD

**Issue by aiwenzhu** [open-mmlab/mmdetection#7418]
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-q9gvk_ly/mmcv-full_7aa35194dee441b2bf1af874ee187013/setup.py", line 389, in <module>
          ext_modules=get_extensions(),
        File "/tmp/pip-install-q9gvk_ly/mmcv-full_7aa35194dee441b2bf1af874ee187013/setup.py", line 308, in get_extensions
          ext_ops = extension(
        File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
          if (not os.path.exists(_join_cuda_home(lib_dir)) and
        File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by aiwenzhu** [comment]
> English-please

An error occurs when installing mmcv-full in Ubuntu20.04，the error is:

python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/tmp/pip-install-q9gvk_ly/mmcv-full_7aa35194dee441b2bf1af874ee187013/setup.py", line 389, in
ext_modules=get_extensions(),
File "/tmp/pip-install-q9gvk_ly/mmcv-full_7aa35194dee441b2bf1af874ee187013/setup.py", line 308, in get_extensions
ext_ops = extension(
File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 867, in CUDAExtension
library_dirs += library_paths(cuda=True)
File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 975, in library_paths
if (not os.path.exists(_join_cuda_home(lib_dir)) and
File "/home/xl/anaconda3/envs/torch/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1982, in _join_cuda_home
raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jbwang1997** [comment]
Please check your CUDA installation. If your CUDA is not installed at the default path, you need to add your custom CUDA path in the CUDA_HOME environment variable
