### ISSUE TITLE
TypeError: SwinTransformer: __init__() got an unexpected keyword argument '_delete_'

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdetection#7443]
I was trying to train retinanet_swin-t-p4-w7_fpn_1x_coco with the following config:
```
classes = ['neck', 'rotten', 'sprouting', "tip", 'without_skin']
pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa
model = dict(
    type='RetinaNet',
    backbone=dict(
        _delete_=True,
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(1, 2, 3),
        # Please only add indices that would be used
        # in FPN, otherwise some parameter will not be used
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)),
    neck=dict(in_channels=[192, 384, 768], start_level=0, num_outs=5),
    bbox_head=dict(
        type='RetinaHead',
        num_classes=len(classes),
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[0.5, 1.0, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.5),
        max_per_img=100))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True, poly2mask=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Resize', img_scale=(750, 750), keep_ratio=True),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(750, 750),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize',**img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
       type='MultiScaleFlipAug',
       img_scale=(750, 750),
       flip=False,
       transforms=[
           dict(type='Resize', keep_ratio=True),
           dict(type='RandomFlip', flip_ratio=0.0),
           dict(type='Normalize', **img_norm_cfg),
           dict(type='DefaultFormatBundle'),
           dict(type='Collect', keys=['img']),
       ])
   ]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='CocoDataset',
        img_prefix='/home/deploy/ved/sort/onion_l2/data/train/images/',
        ann_file='/home/deploy/ved/sort/onion_l2/data/train/onion_train.json',
        classes=classes,
        pipeline=train_pipeline,
        ),
    val=dict(
        type='CocoDataset',
        img_prefix='/home/deploy/ved/sort/onion_l2/data/val/images/',
        ann_file='/home/deploy/ved/sort/onion_l2/data/val/onion_val.json',
        classes=classes,
        pipeline=val_pipeline),
    test=dict(
        samples_per_gpu=1,  # Batch size of a single GPU used in testing
        type='CocoDataset',
        classes=classes,
        pipeline=test_pipeline)
    )
evaluation = dict(interval=1, metric='bbox')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[16, 22])
runner = dict(type='EpochBasedRunner', max_epochs=24)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
```

but it's giving me followig error:
```
Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument '_delete_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/retinanet.py", line 19, in __init__
    test_cfg, pretrained, init_cfg)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SwinTransformer: __init__() got an unexpected keyword argument '_delete_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 209, in <module>
    main()
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 182, in main
    test_cfg=cfg.get('test_cfg'))
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: RetinaNet: SwinTransformer: __init__() got an unexpected keyword argument '_delete_'
Traceback (most recent call last):
  File "/home/deploy/miniconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/train.py", line 107, in cli
    other_args=other_args)
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mim/commands/train.py", line 256, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/deploy/miniconda3/envs/openmmlab/lib/python3.7/site-packages/mmdet/.mim/tools/train.py', 'retinanet_r50_fpn_2x_coco.py', '--gpus', '1', '--launcher', 'none', '--work-dir', 'mmdet']' returned non-zero exit status 1.
```

**Comment by RangiLyu** [comment]
If your config does not inherit a config, do not add `_delete_`.
