### ISSUE TITLE
Custom register_module fails

### ISSUE THREAD

**Issue by vakker** [open-mmlab/mmdetection#7447]
**Checklist**

1. [x] I have searched related issues but cannot get the expected help.
2. [x] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. [x] The bug has not been fixed in the latest version.

**Describe the bug**
Importing elements from `dataset` fails with `KeyError: 'NumClassCheckHook is already registered in hook'`.

**Reproduction**
Run in the command line:
```sh
python -c "from mmdetection.mmdet.datasets.builder import DATASETS"
```

Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/workspace/mmdetection/mmdet/datasets/__init__.py", line 13, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "/home/user/workspace/mmdetection/mmdet/datasets/utils.py", line 118, in <module>
    class NumClassCheckHook(Hook):
  File "/home/user/.pyenv/versions/proj/lib/python3.9/site-packages/mmcv/utils/registry.py", line 312, in _register
    self._register_module(
  File "/home/user/.pyenv/versions/proj/lib/python3.9/site-packages/mmcv/utils/registry.py", line 246, in _register_module
    raise KeyError(f'{name} is already registered '
KeyError: 'NumClassCheckHook is already registered in hook'
```

Might be related to #6419, and other similar issues, but I'm using the latest versions of MMCV and MMDet, that matches the requirements.

**Environment**

```
sys.platform: linux
Python: 3.9.7 (default, Nov 19 2021, 11:53:21) [GCC 9.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1650 with Max-Q Design
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.5.r11.5/compiler.30411180_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.5.5
MMCV: 1.4.6
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.22.0+28d8791
```

**Bug fix**
When you import anything from `dataset`, then everything gets reimported in `__init__.py`, so all the `register_module` wrappers are called again. The same issue happens with any other parts of the code, e.g.:
```sh
python -c "import mmdetection.mmdet.models"
```
Error:
```
...
KeyError: 'NormedConv2d is already registered in conv layer'
```

**Comment by RangiLyu** [comment]
Did you modify any code?

**Comment by RangiLyu** [comment]
Why use `from mmdetection.mmdet.datasets.builder import DATASETS`? the package name is mmdet and you should use  `from mmdet.datasets.builder import DATASETS`.

**Comment by vakker** [comment]
Ah, that's right. I was having `mmdetection` as a git submodule within my own project (to have access to `tools` and `configs`) and that caused this confusion.
