### ISSUE TITLE
When I was doing inference, I used init_detector to report this error : TypeError: CascadeRCNN: ResNet: __init__() got an unexpected keyword argument 'init_cfg' 

### ISSUE THREAD

**Issue by 1wang11lijian1** [open-mmlab/mmdetection#7476]
C:\Users\12481\.conda\envs\mmd\python.exe C:/Users/12481/Desktop/win/WIN/pre_mult.py
Traceback (most recent call last):
  File "C:\Users\12481\.conda\envs\mmd\lib\site-packages\mmcv\utils\registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\12481\.conda\envs\mmd\lib\site-packages\mmcv\utils\registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\detectors\cascade_rcnn.py", line 25, in __init__
    pretrained=pretrained)
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\detectors\two_stage.py", line 26, in __init__
    self.backbone = build_backbone(backbone)
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\builder.py", line 39, in build_backbone
    return build(cfg, BACKBONES)
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\12481\.conda\envs\mmd\lib\site-packages\mmcv\utils\registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: ResNet: __init__() got an unexpected keyword argument 'init_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/12481/Desktop/win/WIN/pre_mult.py", line 17, in <module>
    model = init_detector(config_file, checkpoint_file, device='cuda:0')
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\apis\inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "c:\users\12481\week2_mmdet\mmdetection-2.11.0\mmdet\models\builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\12481\.conda\envs\mmd\lib\site-packages\mmcv\utils\registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CascadeRCNN: ResNet: __init__() got an unexpected keyword argument 'init_cfg'

Process finished with exit code 1

**Comment by Czm369** [comment]
Maybe you can refer to https://github.com/open-mmlab/mmdetection/issues/5734
Do not set init_cfg and pretrained at the same time in your config.
