### ISSUE TITLE
Encountering PermissionError when training YOLOX on custom dataset 

### ISSUE THREAD

**Issue by Tim-Hung** [open-mmlab/mmdetection#7506]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
  When training YOLOX on custom dataset using 2 GPU, it meets PermissionError in the training process(halfway).

  The total interation steps is 50000, and the bug jumps in 8300 iteration steps.

  Changing model to Faster R-CNN and keeping everything the same works fine.

  Below is something I've changed the code:
  I was using IterBasedRunner to train YOLOX so I have to re-design some hook used in YOLOX. So I import custom hook in 
  tools/train_yolox.py. And the custom hook with YOLOX works fine on COCO dataset with same reproduction result.
    
  I think this problem is not related to custom dataset because changing model works fine.

**Reproduction**

1. What command or script did you run?

```none
python -m torch.distributed.launch --nproc_per_node=2 --master_port=29500 tools/train_yolox.py configs/railway/yolox_rail_front_2gpu.py --launcher pytorch
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
  Yes. as described in bug part.

3. What dataset did you use?
  custom dataset.

**Environment**
```
------------------------------------------------------------
sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
GPU 0,1: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.5.r11.5/compiler.30411180_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.4
MMCV: 1.4.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.21.0+97064fb
------------------------------------------------------------
```

**Error traceback**

Part of the error trackback :

```
2022-03-22 19:16:46,888 - mmdet.ssod - INFO - Iter [8300/50000] lr: 9.430e-03, eta: 2 days, 2:33:19, time: 4.646, data_time: 2.544, memory: 24329, loss_cls: 0.6112, loss_bbox: 1.8945, loss_obj: 1.0213, loss: 3.5270
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.conda/envs/MMD/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/user/.conda/envs/MMD/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/user/.conda/envs/MMD/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/user/.conda/envs/MMD/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/user/.conda/envs/MMD/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/user/.conda/envs/MMD/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/user/.conda/envs/MMD/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/SoftTeacher/tools/train_yolox.py", line 9, in <module>
    import mmcv
  File "/home/user/.local/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/user/.local/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/user/.local/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/user/.local/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 22, in <module>
    import torch
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/__init__.py", line 721, in <module>
    import torch.utils.data
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/utils/data/__init__.py", line 38, in <module>
    from torch.utils.data.dataloader_experimental import DataLoader2
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/utils/data/dataloader_experimental.py", line 11, in <module>
    from torch.utils.data.datapipes.iter import IterableWrapper
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/utils/data/datapipes/__init__.py", line 1, in <module>
    from . import iter
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/utils/data/datapipes/iter/__init__.py", line 1, in <module>
    from torch.utils.data.datapipes.iter.callable import (
  File "/home/user/.conda/envs/MMD/lib/python3.8/site-packages/torch/utils/data/datapipes/iter/callable.py", line 6, in <module>
    import dill
  File "/home/user/.local/lib/python3.8/site-packages/dill/__init__.py", line 25, in <module>
    from ._dill import dump, dumps, load, loads, dump_session, load_session, \
  File "/home/user/.local/lib/python3.8/site-packages/dill/_dill.py", line 211, in <module>
    BufferedRandomType = get_file_type('r+b', buffering=-1)
  File "/home/user/.local/lib/python3.8/site-packages/dill/_dill.py", line 204, in get_file_type
    f = open(os.devnull, *args, **kwargs)
PermissionError: [Errno 1] Operation not permitted: '/dev/null'
[E ProcessGroupNCCL.cpp:587] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807433 milliseconds befo
re timing out.
[E ProcessGroupNCCL.cpp:341] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on co
rrupted/incomplete data. To avoid this inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1807433 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 22712 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 22713) of binary: /home/user/.conda/envs/MMD/bin/python
```

**Config File**

```
optimizer = dict(
    type='SGD',
    lr=0.01,
    momentum=0.9,
    weight_decay=0.0005,
    nesterov=True,
    paramwise_cfg=dict(norm_decay_mult=0.0, bias_decay_mult=0.0))
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='IterYOLOX',
    warmup='exp',
    by_epoch=False,
    warmup_by_epoch=False,
    warmup_ratio=1,
    warmup_iters=2000,
    num_last_iters=8000,
    min_lr_ratio=0.05)
runner = dict(type='IterBasedRunner', max_iters=50000)
checkpoint_config = dict(interval=4000, by_epoch=False, max_keep_ckpts=1)
log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(
            type='WandbLoggerHook',
            init_kwargs=dict(
                entity='tim32338519',
                project='Railway_Front',
                name='yolox_rail_front_2gpu',
                config=dict(
                    work_dirs='./work_dirs/yolox_rail_front_2gpu',
                    total_step=50000)),
            by_epoch=False)
    ])
custom_hooks = [
    dict(type='IterYOLOXModeSwitchHook', num_last_iters=8000, priority=48),
    dict(
        type='IterSyncNormHook',
        num_last_iters=8000,
        interval=2000,
        priority=48),
    dict(
        type='ExpMomentumEMAHook',
        resume_from=None,
        momentum=0.0001,
        priority=49)
]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
img_scale = (640, 640)
model = dict(
    type='YOLOX',
    input_size=(640, 640),
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=10, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))
train_pipeline = [
    dict(type='Mosaic', img_scale=(640, 640), pad_val=114.0),
    dict(
        type='RandomAffine', scaling_ratio_range=(0.1, 2),
        border=(-320, -320)),
    dict(
        type='MixUp',
        img_scale=(640, 640),
        ratio_range=(0.8, 1.6),
        pad_val=114.0),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Resize', img_scale=(640, 640), keep_ratio=True),
    dict(
        type='Pad',
        pad_to_square=True,
        pad_val=dict(img=(114.0, 114.0, 114.0))),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(640, 640),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
classes = ('eclip_x', 'eclip_xx', 'railspike_x', 'railspike_xx', 'rail_x',
           'rail_xx', 'slab_track_eclip_x', 'slab_track_eclip_xx',
           'others_break', 'eclip_is_covered')
dataset_type = 'CocoDataset'
train_dataset = dict(
    type='MultiImageMixDataset',
    dataset=dict(
        type='CocoDataset',
        classes=('eclip_x', 'eclip_xx', 'railspike_x', 'railspike_xx',
                 'rail_x', 'rail_xx', 'slab_track_eclip_x',
                 'slab_track_eclip_xx', 'others_break', 'eclip_is_covered'),
        ann_file='data/railway/annotations/front_train.json',
        img_prefix='data/railway/front/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True)
        ],
        filter_empty_gt=False),
    pipeline=[
        dict(type='Mosaic', img_scale=(640, 640), pad_val=114.0),
        dict(
            type='RandomAffine',
            scaling_ratio_range=(0.1, 2),
            border=(-320, -320)),
        dict(
            type='MixUp',
            img_scale=(640, 640),
            ratio_range=(0.8, 1.6),
            pad_val=114.0),
        dict(type='YOLOXHSVRandomAug'),
        dict(type='RandomFlip', flip_ratio=0.5),
        dict(type='Resize', img_scale=(640, 640), keep_ratio=True),
        dict(
            type='Pad',
            pad_to_square=True,
            pad_val=dict(img=(114.0, 114.0, 114.0))),
        dict(
            type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
        dict(type='DefaultFormatBundle'),
        dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
    ])
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=4,
    persistent_workers=True,
    train=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type='CocoDataset',
            classes=('eclip_x', 'eclip_xx', 'railspike_x', 'railspike_xx',
                     'rail_x', 'rail_xx', 'slab_track_eclip_x',
                     'slab_track_eclip_xx', 'others_break',
                     'eclip_is_covered'),
            ann_file='data/railway/annotations/front_train.json',
            img_prefix='data/railway/front/',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True)
            ],
            filter_empty_gt=False),
        pipeline=[
            dict(type='Mosaic', img_scale=(640, 640), pad_val=114.0),
            dict(
                type='RandomAffine',
                scaling_ratio_range=(0.1, 2),
                border=(-320, -320)),
            dict(
                type='MixUp',
                img_scale=(640, 640),
                ratio_range=(0.8, 1.6),
                pad_val=114.0),
            dict(type='YOLOXHSVRandomAug'),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(type='Resize', img_scale=(640, 640), keep_ratio=True),
            dict(
                type='Pad',
                pad_to_square=True,
                pad_val=dict(img=(114.0, 114.0, 114.0))),
            dict(
                type='FilterAnnotations',
                min_gt_bbox_wh=(1, 1),
                keep_empty=False),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ]),
    val=dict(
        type='CocoDataset',
        classes=('eclip_x', 'eclip_xx', 'railspike_x', 'railspike_xx',
                 'rail_x', 'rail_xx', 'slab_track_eclip_x',
                 'slab_track_eclip_xx', 'others_break', 'eclip_is_covered'),
        ann_file='data/railway/annotations/front_test.json',
        img_prefix='data/railway/front/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Pad',
                        pad_to_square=True,
                        pad_val=dict(img=(114.0, 114.0, 114.0))),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        classes=('eclip_x', 'eclip_xx', 'railspike_x', 'railspike_xx',
                 'rail_x', 'rail_xx', 'slab_track_eclip_x',
                 'slab_track_eclip_xx', 'others_break', 'eclip_is_covered'),
        ann_file='data/railway/annotations/front_test.json',
        img_prefix='data/railway/front/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(640, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Pad',
                        pad_to_square=True,
                        pad_val=dict(img=(114.0, 114.0, 114.0))),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
num_last_iters = 8000
evaluation = dict(save_best='auto', interval=4000, metric=['bbox'])
work_dir = './work_dirs/yolox_rail_front_2gpu'
cfg_name = 'yolox_rail_front_2gpu'
gpu_ids = range(0, 2)

```

**Comment by jbwang1997** [comment]
It's weird. Does this error always raise when you run the code?

**Comment by Tim-Hung** [comment]
@jbwang1997 Thanks for your response!

I run this code twice and the error is raised at different iteration steps. 

I restart the computer and re-run this code now to see what will happen.

**Comment by Tim-Hung** [comment]
The run has finished without any error. There is no other question. Thanks!
