### ISSUE TITLE
Is not a  checkpoint file error when using one_stage detection models

### ISSUE THREAD

**Issue by Money-HY** [open-mmlab/mmdetection#7511]
**Describe the bug**
When I was training one_stage detection models such as retinanet or yolof with swin as backbone , I always get "is not a checkpoint file" error but at the same time, when I use the same .pth file in configs for mask_rcnn or other multi_stage detection models, this error disappears. I have followed the docs to change the out_indices=(0, 1, 2, 3) to out_indices=(1, 2, 3) in these one_stage detection models and I wonder if this caused the error.

**Environment**
ys.platform: linux
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
PyTorch: 1.8.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2
OpenCV: 4.5.1
MMCV: 1.4.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.22.0+HEAD

**Error traceback**
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 209, in <module>
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 209, in <module>
        main()main()

  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 183, in main
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 183, in main
        model.init_weights()model.init_weights()

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 209, in <module>
    main()
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 183, in main
    model.init_weights()
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 209, in <module>
    main()
  File "/fs0/home/sx1904098/qhy/mmdetection-master/tools/train.py", line 183, in main
    model.init_weights()
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
      File "/fs0/home/sx1904098/qhy/mmdetection-master/mmdet/models/backbones/swin.py", line 690, in init_weights
    m.init_weights()    m.init_weights()
m.init_weights()
  File "/fs0/home/sx1904098/qhy/mmdetection-master/mmdet/models/backbones/swin.py", line 690, in init_weights

  File "/fs0/home/sx1904098/qhy/mmdetection-master/mmdet/models/backbones/swin.py", line 690, in init_weights
  File "/fs0/home/sx1904098/qhy/mmdetection-master/mmdet/models/backbones/swin.py", line 690, in init_weights
    ckpt = _load_checkpoint(
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
ckpt = _load_checkpoint(    
ckpt = _load_checkpoint(      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint

ckpt = _load_checkpoint(  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
        return CheckpointLoader.load_checkpoint(filename, map_location, logger)    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
    return checkpoint_loader(filename, map_location)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
    OSError    return checkpoint_loader(filename, map_location): return checkpoint_loader(filename, map_location)
../pretrained/swin/swin_tiny_patch4_window7_224 is not a checkpoint file
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/checkpoint.py", line 265, in load_from_local
raise IOError(f'{filename} is not a checkpoint file')
OSError: ../pretrained/swin/swin_tiny_patch4_window7_224 is not a checkpoint file
    raise IOError(f'{filename} is not a checkpoint file')    
raise IOError(f'{filename} is not a checkpoint file')
OSErrorOSError: : ../pretrained/swin/swin_tiny_patch4_window7_224 is not a checkpoint file../pretrained/swin/swin_tiny_patch4_window7_224 is not a checkpoint file

Traceback (most recent call last):
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/fs0/software/anaconda/3-2020.07/envs/sx1904098/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/qhyuse/yolof_swin_c5_8x8_1x_coco.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by jbwang1997** [comment]
I see the pretrain model is `../pretrained/swin/swin_tiny_patch4_window7_224`. The model needs to end with .pth and exists. You can first check the path of retained model.

**Comment by Money-HY** [comment]
> I see the pretrained model is `../pretrained/swin/swin_tiny_patch4_window7_224`. The model needs to end with .pth and exists. You can first check the path of pretained model.

Actually the .pth is not the problem because i use the very same path and file name in other two_stage detection modules but it will not cause the error.  That is why i think that it is related to the module.
