### ISSUE TITLE
AttributeErrorAttributeError: : 'RepeatDataset' object has no attribute 'update_skip_type_keys''RepeatDataset' object has no attribute 'update_skip_type_keys'

### ISSUE THREAD

**Issue by hjfdsssdg** [open-mmlab/mmdetection#7513]
2022-03-23 19:55:12,056 - mmdet - INFO - Epoch [281][50/150]	lr: 2.533e-04, eta: 0:20:59, time: 0.458, data_time: 0.056, memory: 4778, loss_cls: 0.1916, loss_bbox: 0.4818, loss_obj: 0.09
2022-03-23 19:55:33,073 - mmdet - INFO - Epoch [281][100/150]	lr: 2.528e-04, eta: 0:20:37, time: 0.420, data_time: 0.011, memory: 4778, loss_cls: 0.1781, loss_bbox: 0.4376, loss_obj: 0.08
2022-03-23 19:55:47,920 - mmdet - INFO - Exp name: yolox_s_8x8_300e_coco.py
2022-03-23 19:55:47,921 - mmdet - INFO - Epoch [281][150/150]	lr: 2.524e-04, eta: 0:20:16, time: 0.297, data_time: 0.011, memory: 4778, loss_cls: 0.2032, loss_bbox: 0.5285, loss_obj: 0.11
2022-03-23 19:56:09,370 - mmdet - INFO - Epoch [282][50/150]	lr: 2.520e-04, eta: 0:19:54, time: 0.427, data_time: 0.059, memory: 4778, loss_cls: 0.1845, loss_bbox: 0.4580, loss_obj: 0.09
2022-03-23 19:56:29,615 - mmdet - INFO - Epoch [282][100/150]	lr: 2.517e-04, eta: 0:19:33, time: 0.405, data_time: 0.011, memory: 4778, loss_cls: 0.1995, loss_bbox: 0.5067, loss_obj: 0.09
2022-03-23 19:56:46,582 - mmdet - INFO - Exp name: yolox_s_8x8_300e_coco.py
2022-03-23 19:56:46,582 - mmdet - INFO - Epoch [282][150/150]	lr: 2.513e-04, eta: 0:19:11, time: 0.339, data_time: 0.010, memory: 4778, loss_cls: 0.2021, loss_bbox: 0.5204, loss_obj: 0.10
2022-03-23 19:57:13,228 - mmdet - INFO - Epoch [283][50/150]	lr: 2.511e-04, eta: 0:18:50, time: 0.531, data_time: 0.057, memory: 4778, loss_cls: 0.1852, loss_bbox: 0.4597, loss_obj: 0.08
2022-03-23 19:57:35,046 - mmdet - INFO - Epoch [283][100/150]	lr: 2.508e-04, eta: 0:18:29, time: 0.436, data_time: 0.009, memory: 4778, loss_cls: 0.1949, loss_bbox: 0.4928, loss_obj: 0.09
2022-03-23 19:57:56,457 - mmdet - INFO - Exp name: yolox_s_8x8_300e_coco.py
2022-03-23 19:57:56,457 - mmdet - INFO - Epoch [283][150/150]	lr: 2.506e-04, eta: 0:18:08, time: 0.428, data_time: 0.009, memory: 4778, loss_cls: 0.1934, loss_bbox: 0.4838, loss_obj: 0.09
2022-03-23 19:58:15,608 - mmdet - INFO - Epoch [284][50/150]	lr: 2.504e-04, eta: 0:17:46, time: 0.381, data_time: 0.057, memory: 4778, loss_cls: 0.1965, loss_bbox: 0.5007, loss_obj: 0.10
2022-03-23 19:58:33,411 - mmdet - INFO - Epoch [284][100/150]	lr: 2.503e-04, eta: 0:17:25, time: 0.356, data_time: 0.009, memory: 4778, loss_cls: 0.1937, loss_bbox: 0.4894, loss_obj: 0.10
2022-03-23 19:58:54,690 - mmdet - INFO - Exp name: yolox_s_8x8_300e_coco.py
2022-03-23 19:58:54,691 - mmdet - INFO - Epoch [284][150/150]	lr: 2.501e-04, eta: 0:17:03, time: 0.426, data_time: 0.009, memory: 4778, loss_cls: 0.1932, loss_bbox: 0.4881, loss_obj: 0.09
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    meta=meta)
  File "/home/ldy/mmdetection-2.22.0/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ldy/mmdetection-2.22.0/mmdet/core/hook/yolox_mode_switch_hook.py", line 40, in before_train_epoch
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    meta=meta)
  File "/home/ldy/mmdetection-2.22.0/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ldy/mmdetection-2.22.0/mmdet/core/hook/yolox_mode_switch_hook.py", line 40, in before_train_epoch
2022-03-23 19:58:54,772 - mmdet - INFO - No mosaic and mixup aug now!
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    meta=meta)
  File "/home/ldy/mmdetection-2.22.0/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ldy/mmdetection-2.22.0/mmdet/core/hook/yolox_mode_switch_hook.py", line 40, in before_train_epoch
Traceback (most recent call last):
  File "tools/train.py", line 209, in <module>
    main()
  File "tools/train.py", line 205, in main
    meta=meta)
  File "/home/ldy/mmdetection-2.22.0/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/home/fang/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ldy/mmdetection-2.22.0/mmdet/core/hook/yolox_mode_switch_hook.py", line 40, in before_train_epoch
        train_loader.dataset.update_skip_type_keys(self.skip_type_keys)train_loader.dataset.update_skip_type_keys(self.skip_type_keys)

AttributeErrorAttributeError: : 'RepeatDataset' object has no attribute 'update_skip_type_keys''RepeatDataset' object has no attribute 'update_skip_type_keys'

**Comment by hjfdsssdg** [comment]
train YOLOX ，the last 15 epochs run error

**Comment by jbwang1997** [comment]
Have you used the `MultiImageMixDataset`.  `update_skip_type_keys` is implemented in `MultiImageMixDataset`.
