### ISSUE TITLE
Invalid configuration argument at src/masked_conv2d_kernel.cu:70

### ISSUE THREAD

**Issue by randf102** [open-mmlab/mmdetection#753]
Hi, I want to use `ga_faster_r50_caffe_fpn_1x.py` to test my dataset. 
But it outputs this error message.

```
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>           ] 289/365, 8.3 task/s, elapsed: 35s, ETA:     9s
THCudaCheck FAIL file=src/masked_conv2d_kernel.cu line=70 error=9 : invalid configuration argument
Traceback (most recent call last):
  File "tools/test.py", line 192, in <module>
    main()
  File "tools/test.py", line 162, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_test(img, img_meta , **kwargs)
  File "/mmdetection/mmdet/models/detectors/base.py", line 78, in forward_test
    return self.simple_test(imgs[0], img_metas[0] , **kwargs)
  File "/mmdetection/mmdet/models/detectors/two_stage.py", line 199, in simple_test
    x, img_meta, self.test_cfg.rpn) if proposals is None else proposals
  File "/mmdetection/mmdet/models/detectors/test_mixins.py", line 9, in simple_test_rpn
    rpn_outs = self.rpn_head(x)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/models/anchor_heads/guided_anchor_head.py", line 228, in forward
    return multi_apply(self.forward_single, feats)
  File "/mmdetection/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/mmdetection/mmdet/models/anchor_heads/ga_rpn_head.py", line 37, in forward_single
    loc_pred) = super(GARPNHead, self).forward_single(x)
  File "/mmdetection/mmdet/models/anchor_heads/guided_anchor_head.py", line 219, in forward_single
    cls_score = self.conv_cls(x, mask)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mmdetection/mmdet/ops/masked_conv/modules/masked_conv.py", line 30, in forward
    self.padding)
  File "/mmdetection/mmdet/ops/masked_conv/functions/masked_conv.py", line 40, in forward
    data_col)
RuntimeError: cuda runtime error (9) : invalid configuration argument at src/masked_conv2d_kernel.cu:70

```

I have used the same dataset to test on `faster_rcnn_r50_fpn_1x.py` and `faster_rcnn_r50_caffe_c4_1x.py`. And it works well. So I think the dataset's format is correct.

And before the error message is output, images can be detected well. 
I have no idea how to fix it. Could anyone help me, please?

My dataset is from a video, and every input image has the same size.

Thank you!

**Comment by 1349949** [comment]
I got the same problem!

**Comment by notfox** [comment]
yes,i got the same error as upper

**Comment by IcebergKnight** [comment]
yes,i got the same error as upper

**Comment by myownskyW7** [comment]
This bug will appear when mask is all zero. I will fix it soon.

**Comment by randf102** [comment]
Thank you for your help! It can work after updating!
