### ISSUE TITLE
AssertionError: aug test does not support inference with batch size 3

### ISSUE THREAD

**Issue by sxy1122** [open-mmlab/mmdetection#7568]
I want to get new data and its annotation file through the existing test results, but there is a problem and I don't know how to solve it.

Traceback (most recent call last):
   File "Det-Tools/build_dataset/VisDrone2COCO.py", line 165, in main
    first_results = inference_detector(detector, img)
  File "/home/test/PythonProject/mmdet/apis/inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/home/test/anaconda3/envs/mm2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/test/anaconda3/envs/mm2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/test/PythonProject/mmdet/models/detectors/base.py", line 173, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/test/PythonProject/mmdet/models/detectors/base.py", line 148, in forward_test
    assert imgs[0].size(0) == 1, 'aug test does not support ' \
AssertionError: aug test does not support inference with batch size 3

**Comment by hhaAndroid** [comment]
@sxy1122 Yes, test aug does not support batch.

**Comment by sxy1122** [comment]
> 
So how should I deal with this problem?

**Comment by hhaAndroid** [comment]
@sxy1122 You can use bs=1 when testing.
