### ISSUE TITLE
pytorch2onnx: RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead

### ISSUE THREAD

**Issue by cumthxy** [open-mmlab/mmdetection#7613]
hi i get the error. 
i use mmdetection 2.11.0 and the model is my self.

how to solve it

**Comment by chhluo** [comment]
Please provide your env information, the code you ran and the traceback such that I can know where did the problem come from?

**Comment by cumthxy** [comment]
> Please provide your env information, the code you ran and the traceback such that I can know where did the problem come from?
the environment 
python=3.6
mmcv-full                                     1.4.0
mmdet                                         2.11.0
and the pytorch2onnx.py script is also mmdet 2.11.0 script。

the erros like that:
`Traceback (most recent call last):
  File "pytorch2onnx.py", line 245, in <module>
    cfg_options=args.cfg_options)
  File "pytorch2onnx.py", line 58, in pytorch2onnx
    opset_version=opset_version)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 361, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/data/new_mmdet/mmdetection/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/data/new_mmdet/mmdetection/mmdet/models/detectors/base.py", line 160, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/data/DAVAR-Lab-OCR/davarocr/davar_table/models/detectors/lgpma.py", line 166, in simple_test
    global_seg_results = self.global_seg_head.get_seg_masks(global_seg_pred, img_metas, (h_img, w_img))
  File "/home/data/DAVAR-Lab-OCR/davarocr/davar_table/models/seg_heads/gpma_mask_head.py", line 224, in get_seg_masks
    mask_pred = mask_pred.sigmoid().cpu().numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.`

**Comment by chhluo** [comment]
Please try `mask_pred.sigmoid().cpu().numpy()` -> `mask_pred.sigmoid().cpu().detach().numpy()`
