### ISSUE TITLE
How to change yolov3 backbone to swin transformer?

### ISSUE THREAD

**Issue by ouening** [open-mmlab/mmdetection#7617]
I followed the configuration in `configs/swin/` to replace the backbone in yolov3 with swin transformer, but failed in training. The config is:
```
_base_ = '../_base_/default_runtime.py'
# model settings
pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa
model = dict(
    type='YOLOV3',
    # backbone=dict(
    #     type='Darknet',
    #     depth=53,
    #     out_indices=(3, 4, 5),
    #     init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://darknet53')),
    # neck=dict(
    #     type='YOLOV3Neck',
    #     num_scales=3,
    #     in_channels=[1024, 512, 256],
    #     out_channels=[512, 256, 128]),
    backbone=dict(
        # _delete_=True,
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(1,2,3),
        # out_indices=(3,2,1),
        # Please only add indices that would be used
        # in FPN, otherwise some parameter will not be used
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)),
    # neck=dict(in_channels=[192, 384, 768], start_level=0, num_outs=5),
    neck=dict(
        type='YOLOV3Neck',
        num_scales=3,
        in_channels=[192, 384, 768],
        out_channels=[512, 256, 128]),
    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=4,
        in_channels=[512, 256, 128],
        out_channels=[1024, 512, 256],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(116, 90), (156, 198), (373, 326)],
                        [(30, 61), (62, 45), (59, 119)],
                        [(10, 13), (16, 30), (33, 23)]],
            strides=[32, 16, 8]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[32, 16, 8],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),
        loss_wh=dict(type='MSELoss', loss_weight=2.0, reduction='sum')),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='GridAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0)),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.45),
        max_per_img=100))
# dataset settings
dataset_type = 'CocoDataset'
data_root = "D:/Deep/CocoFormatData/"
classes = ('a','b','c','d')
```

Some error occured when training:
```
Traceback (most recent call last):
  File "E:\DeepLearning\mmdetection\tools\train.py", line 220, in <module>
    main()
  File "E:\DeepLearning\mmdetection\tools\train.py", line 209, in main
    train_detector(
  File "e:\deeplearning\mmdetection\mmdet\apis\train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "e:\deeplearning\mmdetection\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "e:\deeplearning\mmdetection\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "e:\deeplearning\mmdetection\mmdet\models\detectors\single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "e:\deeplearning\mmdetection\mmdet\models\detectors\single_stage.py", line 45, in extract_feat
    x = self.neck(x)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\deeplearning\mmdetection\mmdet\models\necks\yolo_neck.py", line 137, in forward
    out = detect(tmp)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "e:\deeplearning\mmdetection\mmdet\models\necks\yolo_neck.py", line 56, in forward
    tmp = self.conv1(x)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\mmcv\cnn\bricks\conv_module.py", line 201, in forward
    x = self.conv(x)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Applications\WPy64-3980\python-3.9.8.amd64\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [256, 1024, 1, 1], expected input[2, 448, 68, 76] to have 1024 channels, but got 448 channels instead 
```
I have also tried to change the parameter `in_channels` in `neck` configuration, but failed too. Could someone provide useful instructions? Appreciate it.

**Comment by Tianyu100** [comment]
Do you solve it? I meet same problems,too.

**Comment by ouening** [comment]
No, failed in some tries

**Comment by ouening** [comment]
I solved it by using `mmcls.SwinTransformer`:
```python
_base_ = '../_base_/default_runtime.py'

# please install mmcls>=0.20.0
# import mmcls.models to trigger register_module in mmcls
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)

# model settings
model = dict(
    type='YOLOV3',
    
    # backbone=dict(
    #     type='Darknet',
    #     depth=53,
    #     out_indices=(3, 4, 5),
    #     init_cfg=dict(type='Pretrained', checkpoint='open-mmlab://darknet53')),
    # neck=dict(
    #     type='YOLOV3Neck',
    #     num_scales=3,
    #     in_channels=[1024, 512, 256],
    #     out_channels=[512, 256, 128]),

    #============== MobileNetV3 ================
    # backbone=dict(
    #     type='mmcls.MobileNetV3',
    #     arch='small',
    #     out_indices=(3, 8, 11),
    #     init_cfg=dict(type='Pretrained', checkpoint='https://download.openmmlab.com/mmclassification/v0/mobilenet_v3/convert/mobilenet_v3_small-8427ecf0.pth',prefix='backbone.')),
    # neck=dict(
    #     type='YOLOV3Neck',
    #     num_scales=3,
    #     in_channels=[96, 48, 24],  # 顺序是反的
    #     out_channels=[512, 256, 128]),
    #==============  end  ===============

    #============== SwinTransformer ================
    backbone=dict(
        type='mmcls.SwinTransformer',
        arch='tiny',
        out_indices=(0,1,2),  # 192,384,768
        init_cfg=dict(type='Pretrained', checkpoint='https://download.openmmlab.com/mmclassification/v0/swin-transformer/swin_tiny_224_b16x64_300e_imagenet_20210616_090925-66df6be6.pth',prefix='backbone.')),
    neck=dict(
        type='YOLOV3Neck',
        num_scales=3,
        in_channels=[768,384,192],  # 顺序是反的
        out_channels=[512, 256, 128]),
    #==============  end  ===============

    bbox_head=dict(
        type='YOLOV3Head',
        num_classes=2,
        in_channels=[512, 256, 128],
        out_channels=[1024, 512, 256],
        anchor_generator=dict(
            type='YOLOAnchorGenerator',
            base_sizes=[[(116, 90), (156, 198), (373, 326)],
                        [(30, 61), (62, 45), (59, 119)],
                        [(10, 13), (16, 30), (33, 23)]],
            strides=[32, 16, 8]),
        bbox_coder=dict(type='YOLOBBoxCoder'),
        featmap_strides=[32, 16, 8],
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_conf=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=1.0,
            reduction='sum'),
        loss_xy=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            loss_weight=2.0,
            reduction='sum'),
        loss_wh=dict(type='MSELoss', loss_weight=2.0, reduction='sum')),
    # training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='GridAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.5,
            min_pos_iou=0)),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        conf_thr=0.005,
        nms=dict(type='nms', iou_threshold=0.45),
        max_per_img=100))
```

However the results seems not good compare to the original one. Maybe some other configurations should be adjusted.

**Comment by hruday-tej** [comment]
Hi @ouening could we please connect with me, I am working on the same problem statement of replacing YOLO Backbone with Swin transformer.
