### ISSUE TITLE
TensorRT deploy error

### ISSUE THREAD

**Issue by zhaowujin** [open-mmlab/mmdetection#7657]
Thanks for your error report and we appreciate it a lot.

**Environment**

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 5.4.0
PyTorch: 1.5.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0
OpenCV: 4.5.5
MMCV: 1.3.13
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.2
MMDetection: 2.11.0+b7077d5
onnx                   1.7.0
onnx-graphsurgeon      0.2.6
onnx-simplifier        0.3.7
onnxoptimizer          0.2.6
onnxruntime            1.8.1

PyTorch by pip

**Error traceback**
[TensorRT] VERBOSE: ModelImporter.cpp:125: Equal_370 [Equal] inputs: [706 -> (-1, -1)], [707 -> ()], 
Traceback (most recent call last):
  File "tools/deployment/onnx2tensorrt_ori.py", line 255, in <module>
    verbose=args.verbose)
  File "tools/deployment/onnx2tensorrt_ori.py", line 46, in onnx2tensorrt
    max_workspace_size=max_workspace_size)
  File "/usr/local/app/sumeru_coa/ft_local/OCR_Universal/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 63, in onnx2trt
    raise RuntimeError(f'parse onnx failed:\n{error_msgs}')
RuntimeError: parse onnx failed:
In node -1 (elementwiseHelper): UNSUPPORTED_NODE: Assertion failed: elementwiseCheck(inputs, binary_op)

It seem like "elementwiseCheck" not supported by tensorrt. Any method can avoid this problem?

**Comment by RangiLyu** [comment]
The model deployment script in MMDetection is deprecated. Please try to use MMDeploy https://github.com/open-mmlab/mmdeploy

**Comment by zhaowujin** [comment]
> The model deployment script in MMDetection is deprecated. Please try to use MMDeploy https://github.com/open-mmlab/mmdeploy

https://github.com/open-mmlab/mmdetection/tree/master/tools/deployment，this tool not recommend？

**Comment by tehkillerbee** [comment]
@zhaowujin 
"Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future."

https://github.com/open-mmlab/mmdetection/pull/7242

**Comment by zhaowujin** [comment]
> 

ok! I try to export by mmdeploy.

**Comment by zhaowujin** [comment]
> @zhaowujin "Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future."
> 
> #7242

ok! I try to export by mmdeploy.

**Comment by zhaowujin** [comment]
> @zhaowujin "Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future."
> 
> #7242
seem like MMDeploy can not support Centos system?

**Comment by zhaowujin** [comment]
> @zhaowujin "Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future."
> 
> #7242

Seem like MMDeploy can not support centos?
