### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by zuyx** [open-mmlab/mmdetection#7664]
When I run the command python train.py with correct config, the error  presented  below ocurred, please tell me how to fix this, thanks!
```

Traceback (most recent call last):
  File "/home/ren/zyx/mmdet/tools/train.py", line 16, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/__init__.py", line 5, in <module>
    from .hook import *  # noqa: F401, F403
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/hook/__init__.py", line 4, in <module>
    from .sync_norm_hook import SyncNormHook
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/hook/sync_norm_hook.py", line 8, in <module>
    from ..utils.dist_utils import all_reduce_dict
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/utils/__init__.py", line 4, in <module>
    from .misc import flip_tensor, mask2ndarray, multi_apply, unmap
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/utils/misc.py", line 8, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/mask/__init__.py", line 3, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ren/.local/lib/python3.9/site-packages/mmdet-2.16.0-py3.9.egg/mmdet/core/mask/structures.py", line 7, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ren/.local/lib/python3.9/site-packages/pycocotools-2.0.4-py3.9-linux-x86_64.egg/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

I install the erviroment by runing commands in mmdetection folder below:
```
conda install pytorch
pip install mmcv-full==1.3.8 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html
pip install numpy
pip install scipy
pip install sklearn
pip install future tensorboard
pip install -r requirements/build.txt
python setup.py install --user
```

And the installed enviroment is listed below.
```
**Environment**
Python: 3.9.12 (main, Apr  5 2022, 06:56:58) [GCC 7.5.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3070
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.1
OpenCV: 4.5.5
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.16.0+
```

**Comment by BIGWangYuDong** [comment]
A pycocotools error or a numpy error. Try to re-install numpy and pycocotools

**Comment by zuyx** [comment]
Thanks! It work.
