### ISSUE TITLE
  KeyError: 'ann_info'

### ISSUE THREAD

**Issue by Zhengym-hub** [open-mmlab/mmdetection#7680]
Hello, I trained faster_rcnn with myself dataset, but it only run one epoch, when validated, the KeyError occurred. 
I have checked the dataset, there is no problem. I exchanged the training set and validation set, only one epoch can be run and after train, the KeyError occurred. So, I suspect there is a problem with the validation code。
I found similar questions in issues, but their solution doesn't work for me.

**The error:**
 Saving checkpoint at 1 epochs
[                                                  ] 0/363, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 307, in <module>
    main()
  File "tools/train.py", line 296, in main
    train_detector(
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 56, in _do_evaluate
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/apis/test.py", line 27, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 216, in __getitem__
    return self.prepare_test_img(idx)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 259, in prepare_test_img
    return self.pipeline(results)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/pipelines/loading.py", line 389, in __call__
    results = self._load_bboxes(results)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/pipelines/loading.py", line 251, in _load_bboxes
    ann_info = results['ann_info']
KeyError: 'ann_info'

And the second question is why the error file comes from site-packages instead of my file folder?
Thanks!

**Comment by chhluo** [comment]
Please check your config for val dataset.

**Comment by Zhengym-hub** [comment]
> Please check your config for val dataset.

The val_pipeline is similar to the train_pipeline
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]

val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/val.json',
        img_prefix=data_root + 'val/',
        classes=classes,
        pipeline=val_pipeline)

**Comment by chhluo** [comment]
val_pipeline should be 
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
```

**Comment by ssli23** [comment]
> > Please check your config for val dataset.
> 
> The val_pipeline is similar to the train_pipeline val_pipeline = [ dict(type='LoadImageFromFile'), dict(type='LoadAnnotations', with_bbox=True), dict(type='Resize', img_scale=(1333, 800), keep_ratio=True), dict(type='RandomFlip', flip_ratio=0.5), dict(type='Normalize', **img_norm_cfg), dict(type='Pad', size_divisor=32), dict(type='DefaultFormatBundle'), dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']), ]
> 
> val=dict( type=dataset_type, ann_file=data_root + 'annotations/val.json', img_prefix=data_root + 'val/', classes=classes, pipeline=val_pipeline)

Have you solved it? I need you help

**Comment by SuFIND** [comment]
> dict(type='ImageToTensor', keys=['img']),

If you are in the **/path/to/MMDetection mmdet/datasets** to define data sets inherited class "**CocoDataset**" or "**CustomDataset**", You need to override the **prepare_test_img** method to add ann_info to result.

**Comment by zou-yiqi** [comment]
> > dict(type='ImageToTensor', keys=['img']),
> 
> If you are in the **/path/to/MMDetection mmdet/datasets** to define data sets inherited class "**CocoDataset**" or "**CustomDataset**", You need to override the **prepare_test_img** method to add ann_info to result.

How do you modify **_prepare_test_img_** function? I tried to change the **_prepare_test_img_** function in **_custom.py_** same as **_prepare_train_img_**, but it didn't work. Thank you for answering.

**Comment by dynamic721** [comment]
> > > dict(type='ImageToTensor', keys=['img']),
> > 
> > 
> > If you are in the **/path/to/MMDetection mmdet/datasets** to define data sets inherited class "**CocoDataset**" or "**CustomDataset**", You need to override the **prepare_test_img** method to add ann_info to result.
> 
> How do you modify **_prepare_test_img_** function? I tried to change the **_prepare_test_img_** function in **_custom.py_** same as **_prepare_train_img_**, but it didn't work. Thank you for answering.

How do you solve in the end?Thx
