### ISSUE TITLE
NotImplementedError: Built-in validation is not implemented yet in not-distributed training. Use distributed training or test.py and *eval.py scripts instead.

### ISSUE THREAD

**Issue by youzi260** [open-mmlab/mmdetection#7726]
I did not find this error in the document. How can I solve it? Thank you very much

/home/wanghan/anaconda3/envs/zxx/bin/python3.7 /home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/tools/train.py --validate
2022-04-15 11:53:37,772 - INFO - Distributed training: False
2022-04-15 11:53:38,134 - INFO - load model from: /home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/resnet101.pyth
2022-04-15 11:53:40,051 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=7.10s)
creating index...
index created!
total training samples 62300 ....
Traceback (most recent call last):
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/tools/train.py", line 122, in <module>
    main()
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/tools/train.py", line 118, in main
    eval_only=args.eval_only)
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/apis/train.py", line 66, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate, eval_only=eval_only)
  File "/home/wanghan/ZTT-video/zero_shot_detection-master/mmdetection/mmdet/apis/train.py", line 204, in _non_dist_train
    raise NotImplementedError('Built-in validation is not implemented '
NotImplementedError: Built-in validation is not implemented yet in not-distributed training. Use distributed training or test.py and *eval.py scripts instead.

Process finished with exit code 1

**Comment by BIGWangYuDong** [comment]
what code did you use? what code did you change?

**Comment by youzi260** [comment]
I used this code, but he didn't change the whole structure of MMDetection

https://github.com/nasir6/zero_shot_detection

**Comment by youzi260** [comment]
mmdetection：1.0.rc0+1c9afec+
pytorch:1.4
cuda:10.1
I ran MMDetectionin these environments.

**Comment by BIGWangYuDong** [comment]
Seems that you use mmdet v1.x to run the code. 
Firstly, please check whether your mmcv version is matched with your mmdet version. 
Also. it is suggested to update your mmdet version.
