### ISSUE TITLE
在pascal voc格式的数据集上运行test.py，test集没有真值标记而报错

### ISSUE THREAD

**Issue by 13717630148** [open-mmlab/mmdetection#7775]
命令行输入如下：
python tools/test.py     configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc.py     checkpoints/faster_rcnn_r50_fpn_1x_voc0712_20200624-c9895d40.pth     --eval mAP --out result.pkl

报错如下：
Traceback (most recent call last):
  File "/data4/user/.local/lib/python3.6/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/data4/user/.local/lib/python3.6/site-packages/mmdet/datasets/voc.py", line 26, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/data4/user/.local/lib/python3.6/site-packages/mmdet/datasets/xml_style.py", line 34, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/data4/user/.local/lib/python3.6/site-packages/mmdet/datasets/custom.py", line 95, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/data4/user/.local/lib/python3.6/site-packages/mmdet/datasets/xml_style.py", line 54, in load_annotations
    tree = ET.parse(xml_path)
  File "/usr/local/anaconda3/envs/torch-1.6-py3/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/local/anaconda3/envs/torch-1.6-py3/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/VOCdevkit/VOC2012/Annotations/006382.xml'

因为006382属于test集，所以没有xml。但我现在需要获取test集的inference结果并保存到pkl里，那该怎么做？

**Comment by RangiLyu** [comment]
delete `--eval mAP` command
