### ISSUE TITLE
Error in testing ONNX Mask RCNN model

### ISSUE THREAD

**Issue by hontiky** [open-mmlab/mmdetection#7782]
**Describe the bug**
I have an error during testing ONNX model, which was created with `tools\deployment\pytorch2onnx.py` from Mask RCNN checkpoint and config file

1. What command or script did you run?

I try to run function `get_ort_model_output` from `mmdetection.tests.test_onnx.utils`

**Error traceback**
```
2022-04-21 17:04:04.933358103 [W:onnxruntime:, graph.cc:1237 Graph] Initializer 3823 appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
......(there are many same errors).....
2022-04-21 17:04:04.936612495 [W:onnxruntime:, graph.cc:1237 Graph] Initializer rpn_head.rpn_reg.weight appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
Traceback (most recent call last):
  File "project-path/tmp.py", line 30, in <module>
    get_ort_model_output([img])
  File "project-path/tests/test_onnx/utils.py", line 106, in get_ort_model_output
    sess = ort.InferenceSession(onnx_io, session_options)
  File "project-path/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "project-path/venv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from tmp.onnx failed:Fatal error: grid_sampler is not a registered function/op
```

**Comment by RangiLyu** [comment]
The scripts in tools\deployment are deprecated. Please use MMDeploy instead. https://github.com/open-mmlab/mmdeploy

**Comment by hontiky** [comment]
@Rangil, thank you!
