### ISSUE TITLE
When I set find_unused_paramters=True, the val mAP results are all 0. While without find_unused_paramters=True, I got RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. 

### ISSUE THREAD

**Issue by SheffieldCao** [open-mmlab/mmdetection#7803]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
I try to build a mask-rcnn model with my own ` backbone ` and ` neck `. The meta-arch of my model is modified from the `_base_/models/mask_rcnn_r50_fpn.py`. 
But during training, I got **RuntimeError(Expected to have finished reduction in the prior iteration before starting a new one. )**. 
```shell
~ - mmdet - INFO - workflow: [('train', 1)], max: 55 epochs
~ - mmdet - INFO - Checkpoints will be saved to path by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 209, in main
    train_detector(
  File "~/mmdet/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "~/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "~/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "~/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "~/miniconda3/envs/mm/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 42, in train_step
    and self.reducer._rebuild_buckets()):
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```
I try to find the exact break point. I find that the training loop was broke just after the first `run_iter` in `train` of **EpochBasedRunner**. The losses returned by `run_iter` was normal.
```python
class EpochBasedRunner(BaseRunner):
...
    def train(self, data_loader, **kwargs):
        self.model.train()
        self.mode = 'train'
        self.data_loader = data_loader
        self._max_iters = self._max_epochs * len(self.data_loader)
        self.call_hook('before_train_epoch')
        time.sleep(2)  # Prevent possible deadlock during epoch transition
        for i, data_batch in enumerate(self.data_loader):
            self._inner_iter = i
            self.call_hook('before_train_iter')
            self.run_iter(data_batch, train_mode=True, **kwargs)
            self.call_hook('after_train_iter')
            self._iter += 1

        self.call_hook('after_train_epoch')
        self._epoch += 1
```
I have seen several issues with the similiar problem,  while the other issues with the same **RuntimeError** have more error info as follows. (for example in #2377)
```shell
Traceback (most recent call last):
  File "tools/train.py", line 142, in <module>
    main()
  File "tools/train.py", line 138, in main
    meta=meta)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 102, in train_detector
    meta=meta)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 182, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/fitlab/NiCk/mmdetection/mmdet/apis/train.py", line 75, in batch_processor
    losses = model(**data)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 459, in forward
    self.reducer.prepare_for_backward([])
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:518)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fdbbca8b813 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x734 (0x7fdc054d0654 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x7bed8a (0x7fdc054bed8a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x210ba4 (0x7fdc04f10ba4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x561b42058114 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x561b42058231 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x52cf (0x561b420bce8f in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #8: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #10: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #13: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #15: <unknown function> + 0x17512a (0x561b4206c12a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #16: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #19: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #22: _PyFunction_FastCallDict + 0x1d5 (0x561b42012805 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #23: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #24: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x6a0 (0x561b420b8260 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0xc30 (0x561b42012030 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #30: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #33: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0xfb (0x561b4205768b in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x416 (0x561b420b7fd6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #38: PyEval_EvalCodeEx + 0x44 (0x561b420125f4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #39: PyEval_EvalCode + 0x1c (0x561b4201261c in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #40: <unknown function> + 0x21c974 (0x561b42113974 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #41: PyRun_FileExFlags + 0xa1 (0x561b4211dcf1 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #42: PyRun_SimpleFileExFlags + 0x1c3 (0x561b4211dee3 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #43: <unknown function> + 0x227f95 (0x561b4211ef95 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #44: _Py_UnixMain + 0x3c (0x561b4211f0bc in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #45: __libc_start_main + 0xe7 (0x7fdc0f0b6b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #46: <unknown function> + 0x1d0990 (0x561b420c7990 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fdbbca8b813 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::prepare_for_backward(std::vector<torch::autograd::Variable, std::allocator<torch::autograd::Variable> > const&) + 0x734 (0x7fdc054d0654 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x7bed8a (0x7fdc054bed8a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x210ba4 (0x7fdc04f10ba4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: _PyMethodDef_RawFastCallKeywords + 0x264 (0x561b42058114 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #5: _PyCFunction_FastCallKeywords + 0x21 (0x561b42058231 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #6: _PyEval_EvalFrameDefault + 0x52cf (0x561b420bce8f in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #7: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #8: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #9: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #10: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #11: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #12: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #13: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #14: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #15: <unknown function> + 0x17512a (0x561b4206c12a in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #16: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #19: _PyFunction_FastCallDict + 0x400 (0x561b42012a30 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #22: _PyFunction_FastCallDict + 0x1d5 (0x561b42012805 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #23: _PyObject_Call_Prepend + 0x63 (0x561b4202d943 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #24: PyObject_Call + 0x6e (0x561b42020b9e in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x1e35 (0x561b420b99f5 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #26: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #27: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #28: _PyEval_EvalFrameDefault + 0x6a0 (0x561b420b8260 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0xc30 (0x561b42012030 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #30: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #31: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #32: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #33: _PyFunction_FastCallKeywords + 0x387 (0x561b42057917 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x14e6 (0x561b420b90a6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #35: _PyFunction_FastCallKeywords + 0xfb (0x561b4205768b in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #36: _PyEval_EvalFrameDefault + 0x416 (0x561b420b7fd6 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #37: _PyEval_EvalCodeWithName + 0x2f9 (0x561b420116f9 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #38: PyEval_EvalCodeEx + 0x44 (0x561b420125f4 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #39: PyEval_EvalCode + 0x1c (0x561b4201261c in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #40: <unknown function> + 0x21c974 (0x561b42113974 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #41: PyRun_FileExFlags + 0xa1 (0x561b4211dcf1 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #42: PyRun_SimpleFileExFlags + 0x1c3 (0x561b4211dee3 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #43: <unknown function> + 0x227f95 (0x561b4211ef95 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #44: _Py_UnixMain + 0x3c (0x561b4211f0bc in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
frame #45: __libc_start_main + 0xe7 (0x7fdc0f0b6b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #46: <unknown function> + 0x1d0990 (0x561b420c7990 in /home/fitlab/NiCk/anaconda3/envs/nick_rs/bin/python)
```
There is **ONLY** one issue (#2883) that is almost the same as this issue. While unfortunately, this issue has not received a valid answer and was closed.

I try to follow #2377 to set find_unused_paramters=True, the training and evaluating process were normal. But I got the val results as follows.
```shell
~ - mmdet - INFO - Evaluating bbox...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.48s).
Accumulating evaluation results...
DONE (t=0.09s).
~ - mmdet - INFO - 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000

~ - mmdet - INFO - Evaluating segm...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *segm*
DONE (t=0.32s).
Accumulating evaluation results...
DONE (t=0.09s).
2022-04-24 00:02:21,774 - mmdet - INFO - 
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.000

~ - mmdet - INFO - Exp name: mask_rcnn_gpwin8_sfp_ws_gn_cs.py
~ - mmdet - INFO - Epoch(val) [1][84]     bbox_mAP: 0.0000, bbox_mAP_50: 0.0000, bbox_mAP_75: -1.0000, bbox_mAP_s: 0.0000, bbox_mAP_m: 0.0000, bbox_mAP_l: 0.0000, bbox_mAP_copypaste: 0.000 0.000 -1.000 0.000 0.000 0.000, segm_mAP: 0.0000, segm_mAP_50: 0.0000, segm_mAP_75: -1.0000, segm_mAP_s: 0.0000, segm_mAP_m: 0.0000, segm_mAP_l: 0.0000, segm_mAP_copypaste: 0.000 0.000 -1.000 0.000 0.000 0.000
```
Could you please give me some ideas about the causes of such error and how to deal with it. Thx!

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by chhluo** [comment]
The problem may be caused by you modificaition to backbone and neck. Would you mind provide your code and your entire config file here?

**Comment by chhluo** [comment]
The mask_rcnn_r50_fpn_1x_coco.py is okay for running. I think this error maybe caused by your own backbone and neck.

**Comment by wenyuqing** [comment]
> Sorry for the late response. 😅. Actually I have solved my problem. Indeed it is related to my backbone and neck. The current training and evaluation are normal. I checked the whole backbone and neck, and made several changes, later I will attach more details about the exact bug after I finished my current experiments.

Hi, I made some modifications to my custom backbone and stuck into similar problem. Could you please share your solution？
