### ISSUE TITLE
data['category_id'] = self.cat_ids[label] IndexError: list index out of range

### ISSUE THREAD

**Issue by Zhengym-hub** [open-mmlab/mmdetection#7804]
Hello, I run mask-rcnn on my data, but there is a problem after run 1 train epoch: 
 -------------------- 
2022-04-24 09:44:32,733 - mmdet - INFO - workflow: [('train', 1), ('val', 1)], max: 50 epochs
2022-04-24 09:44:32,733 - mmdet - INFO - Checkpoints will be saved to /media/Data/zhengym/Segmentation/FaT/workdir by HardDiskBackend.
2022-04-24 09:44:37,897 - mmdet - INFO - Epoch [1][50/215]	lr: 9.890e-06, eta: 0:18:24, time: 0.103, data_time: 0.044, memory: 693, loss_rpn_cls: 0.5157, loss_rpn_bbox: 0.2202, loss_cls: 1.0874, acc: 69.2617, loss_bbox: 0.0288, loss_mask: 0.7952, loss: 2.6473
2022-04-24 09:44:40,254 - mmdet - INFO - Epoch [1][100/215]	lr: 1.988e-05, eta: 0:13:20, time: 0.047, data_time: 0.004, memory: 693, loss_rpn_cls: 0.4081, loss_rpn_bbox: 0.1511, loss_cls: 0.6434, acc: 99.7500, loss_bbox: 0.0098, loss_mask: 0.4907, loss: 1.7031
2022-04-24 09:44:43,008 - mmdet - INFO - Epoch [1][150/215]	lr: 2.987e-05, eta: 0:12:05, time: 0.055, data_time: 0.004, memory: 693, loss_rpn_cls: 0.4266, loss_rpn_bbox: 0.1525, loss_cls: 0.6892, acc: 99.7695, loss_bbox: 0.0083, loss_mask: 0.5052, loss: 1.7818
2022-04-24 09:44:45,404 - mmdet - INFO - Epoch [1][200/215]	lr: 3.986e-05, eta: 0:11:08, time: 0.048, data_time: 0.004, memory: 693, loss_rpn_cls: 0.3736, loss_rpn_bbox: 0.1265, loss_cls: 0.6487, acc: 99.7773, loss_bbox: 0.0077, loss_mask: 0.4442, loss: 1.6006
2022-04-24 09:44:46,060 - mmdet - INFO - Saving checkpoint at 1 epochs
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 215/215, 14.9 task/s, elapsed: 14s, ETA:     0s0
Traceback (most recent call last):
  File "tools/train.py", line 212, in <module>
    main()
  File "tools/train.py", line 201, in main
    train_detector(
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 58, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 361, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 643, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 385, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 322, in results2json
    json_results = self._segm2json(results)
  File "/home/zhengym/.conda/envs/205_mmdetection/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 273, in _segm2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

------------------------------------------------------------------------------------------------------------------------------
**The config I used:**
# dataset settings
dataset_type = 'CocoDataset'
data_root = '/media/Data/zhengym/Segmentation/FaT/'
# data_root = 'data/coco/'

classes = ('Fibroma', 'Tumor')

img_norm_cfg = dict(
    mean=[0, 0, 0], std=[1, 1, 1], to_rgb=True)
    # mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(256, 256), keep_ratio=True),
    # dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        # img_scale=(1333, 800),
        img_scale=(600, 400),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=0,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'mask_annotations/val.json',
        img_prefix=data_root + 'val/',
        classes=classes,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'mask_annotations/val.json',
        img_prefix=data_root + 'val/',
        classes=classes,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'mask_annotations/test.json',
        img_prefix=data_root + 'test/',
        classes=classes,
        pipeline=test_pipeline))
evaluation = dict(metric=['bbox', 'segm'])

I've been debugging for two days, but I haven't made any progress.
Thank you!

**Comment by ZwwWayne** [comment]
Seems that you did not change the num_classes in your head, which is bigger than the number of classes in your dataset.

**Comment by gkgo** [comment]
Hello，I have encountered the same problem, but the num_classes in my head is fine. How can I solve it?

**Comment by gkgo** [comment]
And I've run five epoch before the error occurs.
![image](https://user-images.githubusercontent.com/91817417/165074501-c9f36858-565f-43a8-b257-8bf55437a82b.png)
![image](https://user-images.githubusercontent.com/91817417/165074539-aa6ea910-e49b-455d-9a76-46fe6caba2e3.png)

**Comment by L-xiaolu** [comment]
Did you solve this problem please?

**Comment by ztfmars** [comment]
> Did you solve this problem please?

一个原因是 你在configs中的num_classes与数据中类别数目不相符，或者跟num_classes相关的参数有一些没有改正，例如 有一些loss_weight 是根据不同类别数目而设置的（但是你没改）。

另一个原因是，你使用coco数据集，但是官方默认是coco是80个类别，所以需要稍微更改一下在做evaluation的时候，获取CLASSES的方式。由原来的coco的CLASSES, 变成从dataset获取类别。

在mmdet/dataset/coco.py， line 635 , 修改如下：

    ## ------> origin
    # self.cat_ids = coco_gt.get_cat_ids(cat_names=self.CLASSES)
    ## ------> after : use dataset classes instead of coco classes
    self.cat_ids = coco_gt.get_cat_ids()

ref:
https://blog.csdn.net/weixin_42237113/article/details/125566366?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125566366%22%2C%22source%22%3A%22weixin_42237113%22%7D&ctrtid=v4ROR

**Comment by kuangxiaoye** [comment]
> > Did you solve this problem please?
> 
> 一个原因是 你在configs中的num_classes与数据中类别数目不相符，或者跟num_classes相关的参数有一些没有改正，例如 有一些loss_weight 是根据不同类别数目而设置的（但是你没改）。
> 
> 另一个原因是，你使用coco数据集，但是官方默认是coco是80个类别，所以需要稍微更改一下在做evaluation的时候，获取CLASSES的方式。由原来的coco的CLASSES, 变成从dataset获取类别。
> 
> 在mmdet/dataset/coco.py， line 635 , 修改如下：
> 
> ```
> ## ------> origin
> # self.cat_ids = coco_gt.get_cat_ids(cat_names=self.CLASSES)
> ## ------> after : use dataset classes instead of coco classes
> self.cat_ids = coco_gt.get_cat_ids()
> ```
> 
> ref: https://blog.csdn.net/weixin_42237113/article/details/125566366?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125566366%22%2C%22source%22%3A%22weixin_42237113%22%7D&ctrtid=v4ROR

If you use tools/trains  line35  need change  that too

**Comment by Z-mingyu** [comment]
> > Did you solve this problem please?
> 
> 一个原因是 你在configs中的num_classes与数据中类别数目不相符，或者跟num_classes相关的参数有一些没有改正，例如 有一些loss_weight 是根据不同类别数目而设置的（但是你没改）。
> 
> 另一个原因是，你使用coco数据集，但是官方默认是coco是80个类别，所以需要稍微更改一下在做evaluation的时候，获取CLASSES的方式。由原来的coco的CLASSES, 变成从dataset获取类别。
> 
> 在mmdet/dataset/coco.py， line 635 , 修改如下：
> 
> ```
> ## ------> origin
> # self.cat_ids = coco_gt.get_cat_ids(cat_names=self.CLASSES)
> ## ------> after : use dataset classes instead of coco classes
> self.cat_ids = coco_gt.get_cat_ids()
> ```
> 
> ref: https://blog.csdn.net/weixin_42237113/article/details/125566366?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22125566366%22%2C%22source%22%3A%22weixin_42237113%22%7D&ctrtid=v4ROR

有点令人匪夷所思，为什么cat_names=self.dataset_meta['classes']获取的是coco原来的80类的classes,去掉之后确实好了
