### ISSUE TITLE
ETOODHead is not in the models registry, how to register module without using custom_import

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#7821]
I want to create a new head, in script named `etood_head.py` placed in models/dense_heads
```
@HEADS.register_module()
class ETOODHead(ATSSHead):
"""
code
"""
```

then import it in` __init__.py` in models/dense_heads
```
...
from .etood_head import ETOODHead
__all__ = [
    'AnchorFreeHead', 'AnchorHead', 'GuidedAnchorHead', 'FeatureAdaption',
    'RPNHead', 'GARPNHead', 'RetinaHead', 'RetinaSepBNHead', 'GARetinaHead',
    'SSDHead', 'FCOSHead', 'RepPointsHead', 'FoveaHead',
    'FreeAnchorRetinaHead', 'ATSSHead', 'FSAFHead', 'NASFCOSHead',
    'PISARetinaHead', 'PISASSDHead', 'GFLHead', 'CornerHead', 'YOLACTHead',
    'YOLACTSegmHead', 'YOLACTProtonet', 'YOLOV3Head', 'PAAHead',
    'SABLRetinaHead', 'CentripetalHead', 'VFNetHead', 'StageCascadeRPNHead',
    'CascadeRPNHead', 'EmbeddingRPNHead', 'LDHead', 'CascadeRPNHead',
    'AutoAssignHead', 'DETRHead', 'YOLOFHead', 'DeformableDETRHead',
    'SOLOHead', 'DecoupledSOLOHead', 'CenterNetHead', 'YOLOXHead',
    'DecoupledSOLOLightHead', 'LADHead', 'TOODHead', 'MaskFormerHead',
    'Mask2FormerHead', 'ETOODHead'
]
```
then I create config file named `etood_r50_fpn_1x_coco.py` in configs/tood
```
model = dict(
    type='TOOD',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5),
    bbox_head=dict(
        type='ETOODHead',
        num_classes=80,
        in_channels=[256, 256, 256],
        stacked_convs=1,
        feat_channels=256,
        anchor_type='anchor_free',
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0],
            octave_base_scale=8,
            scales_per_octave=1,
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[0.1, 0.1, 0.2, 0.2]),
        initial_loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            activated=True,  # use probability instead of logit as input
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_cls=dict(
            type='QualityFocalLoss',
            use_sigmoid=True,
            activated=True,  # use probability instead of logit as input
            beta=2.0,
            loss_weight=1.0),
        loss_bbox=dict(type='GIoULoss', loss_weight=2.0)),
    train_cfg=dict(
        initial_epoch=4,
        initial_assigner=dict(type='ATSSAssigner', topk=9),
        assigner=dict(type='TaskAlignedAssigner', topk=13),
        alpha=1,
        beta=6,
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.6),
        max_per_img=100))
```

Run `python3 tools/train.py configs/tood/etood_r50_fpn_1x_coco.py`
Stack trace: 
```
Traceback (most recent call last):
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmdet/models/detectors/tood.py", line 19, in __init__
    super(TOOD, self).__init__(backbone, neck, bbox_head, train_cfg,
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmdet/models/detectors/single_stage.py", line 37, in __init__
    self.bbox_head = build_head(bbox_head)
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmdet/models/builder.py", line 40, in build_head
    return HEADS.build(cfg)
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/jovyan/anaconda3/envs/yolox/lib/python3.9/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'ETOODHead is not in the models registry'
```

**Comment by iumyx2612** [comment]
Digging the issues in here, finally understand.
I installed mmdet using mim
```
pip install openmim
mim install mmdet
```
so it's installed inside my virtual environment, not inside my working directory. Had to reinstalled inside working directory using
```
cd mmdetection
pip install -r requirements/build.txt
pip install -v -e .  # or "python setup.py develop"
```
