### ISSUE TITLE
mask_size change causes size mismatch error

### ISSUE THREAD

**Issue by optimaltaskin** [open-mmlab/mmdetection#7849]
Hi,

I'm trying to change mask_size parameter from 7 (which is default) to 14 or 28 hoping to get more precise mask results. My config file is as below:
```

_base_ = '../point_rend/point_rend_r50_caffe_fpn_mstrain_3x_coco_downloaded.py'
model = dict(
    roi_head=dict(
        bbox_roi_extractor=dict(
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),),
        bbox_head=dict(
            roi_feat_size=14,
            num_classes=1,
        ),
        mask_head=dict(
            num_classes=1,
        ),
        point_head=dict(
            num_classes=1,
        ),
    ),
    train_cfg=dict(
        rcnn=dict(
            mask_size=14,
        ),
    ),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=100,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=10,
            mask_thr_binary=0.5,
            subdivision_steps=5,
            subdivision_num_points=784,
            scale_factor=2)),
)
dataset_type = 'COCODataset'
classes = ('card',)
log_config = dict(interval=4)
checkpoint_config = dict(interval=128)
runner = dict(type='EpochBasedRunner', max_epochs=128)

optimizer = dict(type='AdamW', lr=0.00001, weight_decay=0.000005)
optimizer_config = dict(grad_clip=None)

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        img_prefix='data/base_set/training/',
        classes=classes,
        ann_file='data/base_set/training/training_labels.json'),
    test=dict(
        img_prefix='data/base_set/testing/',
        classes=classes,
        ann_file='data/base_set/testing/testing_labels.json'),
    val=dict(
        img_prefix='data/base_set/testing/',
        classes=classes,
        ann_file='data/base_set/testing/testing_labels.json'),
    # val=dict(
    #     img_prefix='data/base_set/validation/',
    #     classes=classes,
    #     ann_file='data/base_set/validation/val_labels.json'),
)

load_from = 'checkpoints/point_rend_r50_caffe_fpn_mstrain_3x_coco-e0ebb6b7.pth'

```

When I run under this configuration I get the following error about size mismatch:
```
Traceback (most recent call last):
  File "/home/patroclos/PycharmProjects/mmdet/tools/train.py", line 209, in <module>
    main()
  File "/home/patroclos/PycharmProjects/mmdet/tools/train.py", line 198, in main
    train_detector(
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/apis/train.py", line 210, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/detectors/two_stage.py", line 147, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 111, in forward_train
    mask_results = self._mask_forward_train(x, sampling_results,
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/roi_heads/point_rend_roi_head.py", line 34, in _mask_forward_train
    mask_results = super()._mask_forward_train(x, sampling_results,
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/roi_heads/standard_roi_head.py", line 175, in _mask_forward_train
    loss_mask = self.mask_head.loss(mask_results['mask_pred'],
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 177, in loss
    loss_mask = self.loss_mask(mask_pred, mask_targets, labels)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/losses/cross_entropy_loss.py", line 246, in forward
    loss_cls = self.loss_weight * self.cls_criterion(
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/mmdet/models/losses/cross_entropy_loss.py", line 164, in mask_cross_entropy
    return F.binary_cross_entropy_with_logits(
  File "/home/patroclos/PycharmProjects/.venvs/mmdet/lib/python3.9/site-packages/torch/nn/functional.py", line 2980, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([25, 14, 14])) must be the same as input size (torch.Size([25, 7, 7]))
```

I have tried to find which parameter I need to change to avoid this size mismatch error but couldn't find any. Checked tutorial below as well: 
https://github.com/open-mmlab/mmdetection/blob/master/docs/en/tutorials/config.md

but still no chance. Can anyone help me about how I can increase mask_size parameter? Thanks in advance.

**Comment by jbwang1997** [comment]
Since you change the `mask_size=14` in train_cfg, the shape of mask_target is 25X14X14 but the shape of prediction is still 25X7X7. You can try to increase the output size of `mask_roi_extractor` or reduce the `downsample_factor` in `CoarseMaskHead`.
