### ISSUE TITLE
RuntimeError: nms_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection#7874]
Hello. An error occurs to me

Traceback (most recent call last):
  File "tools/train.py", line 213, in <module>
    main()
  File "tools/train.py", line 209, in main
    meta=meta)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/detectors/two_stage.py", line 162, in forward_train
    **kwargs)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 340, in forward_train
    *outs, img_metas=img_metas, cfg=proposal_cfg)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 105, in get_bboxes
    **kwargs)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 187, in _get_bboxes_single
    img_shape)
  File "/media/hdd1t/baoheng/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 231, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 326, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 173, in nms
    score_threshold, max_num)
  File "/home/baoheng/.conda/envs/openmmlab/lib/python3.7/site-packages/mmcv/ops/nms.py", line 27, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: nms_impl: implementation for device cuda:0 not found.

**Comment by BIGWangYuDong** [comment]
Similar: https://github.com/open-mmlab/mmdetection/issues/6765 and https://github.com/open-mmlab/mmdetection/issues/7788

**Comment by CheungBH** [comment]
> Similar: #6765 and #7788

Yes I know. I noticed these issues before. But there is no response in the 6765, and the response in 7788 is provided by the user which doesn't solve my problem.
Are there any official ideas?

**Comment by BIGWangYuDong** [comment]
You can try to re-install a new environment and install mmcv-full by source code

**Comment by CheungBH** [comment]
> You can try to re-install a new environment and install mmcv-full by source code

Are there any docs about this step?

**Comment by CheungBH** [comment]
> You can try to re-install a new environment and install mmcv-full by source code

Hello. I tried, but it failed again. Are there anything supported in my environment?

**Comment by MireniamuYuki** [comment]
I solved this by re-install a new environment by following the steps [https://github.com/open-mmlab/mmdetection/blob/master/docs/zh_cn/get_started.md](url)

**Comment by CheungBH** [comment]
> I solved this by re-install a new environment by following the steps [https://github.com/open-mmlab/mmdetection/blob/master/docs/zh_cn/get_started.md](url)

I think it is not useful for me, since my current environment is installed using this tutorial..

**Comment by CheungBH** [comment]
> I solved this by re-install a new environment by following the steps [https://github.com/open-mmlab/mmdetection/blob/master/docs/zh_cn/get_started.md](url)

Oh thanks I just find that I installed a wrong version before. I modified it and it worked!

**Comment by shring56** [comment]
> > I solved this by re-install a new environment by following the steps [https://github.com/open-mmlab/mmdetection/blob/master/docs/zh_cn/get_started.md](url)
> 
> Oh thanks I just find that I installed a wrong version before. I modified it and it worked!

Hello, Which version did you install by mistake?

**Comment by adam-matic** [comment]
For me, the error disappeared after making a new environement with python 3.11 (I tried first with python 3.8 and 3.9)
Using windows, cuda 11.6
