### ISSUE TITLE
pip install -v -e .[tests] error occur 

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#7886]
Ubuntu 20.04
cuda 11.1
Nvdia 3060

how to run pytest ?

```
(mmdet_pytest) elaine@elaine-System-Product-Name:/project/mmlab_template/mmdetection$ pip install -v -e .[tests]
Using pip 22.0.4 from /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/pip (python 3.9)
Obtaining file:///project/mmlab_template/mmdetection
  Running command python setup.py egg_info
  /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/torch/package/_mock_zipreader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448255797/work/torch/csrc/utils/tensor_numpy.cpp:67.)
    _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
  running egg_info
  creating /tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info
  writing /tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'mmdet/VERSION'
  warning: no files found matching 'mmdet/.mim/demo/*/*'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-t_sk5tvr/mmdet.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Collecting matplotlib
  Using cached matplotlib-3.5.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
Collecting numpy
  Using cached numpy-1.22.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting pycocotools
  Using cached pycocotools-2.0.4-cp39-cp39-linux_x86_64.whl
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting terminaltables
  Using cached terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Collecting asynctest
  Using cached asynctest-0.13.0-py3-none-any.whl (26 kB)
Collecting codecov
  Using cached codecov-2.1.12-py2.py3-none-any.whl (16 kB)
Collecting flake8
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
Collecting interrogate
  Using cached interrogate-1.5.0-py3-none-any.whl (45 kB)
Collecting isort==4.3.21
  Using cached isort-4.3.21-py2.py3-none-any.whl (42 kB)
Collecting kwarray
  Using cached kwarray-0.6.0-py3-none-any.whl (78 kB)
Collecting mmtrack
  Using cached mmtrack-0.13.0-py3-none-any.whl (377 kB)
Collecting onnx==1.7.0
  Using cached onnx-1.7.0.tar.gz (5.5 MB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting protobuf
    Using cached protobuf-3.20.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
  Installing collected packages: wheel, setuptools, protobuf
  Successfully installed protobuf-3.20.1 setuptools-62.1.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  fatal: not a git repository (or any of the parent directories): .git
  /tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting pytest-runner
    Using cached pytest_runner-6.0.0-py3-none-any.whl (7.2 kB)
  Installing collected packages: pytest-runner
  Successfully installed pytest-runner-6.0.0
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  fatal: not a git repository (or any of the parent directories): .git
  /tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  running dist_info
  creating /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info
  writing /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/entry_points.txt
  writing requirements to /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-2f7fw13u/onnx.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-2f7fw13u/onnx-1.7.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Collecting onnxruntime>=1.8.0
  Using cached onnxruntime-1.11.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
Collecting pytest
  Using cached pytest-7.1.2-py3-none-any.whl (297 kB)
Collecting ubelt
  Using cached ubelt-1.0.1-py3-none-any.whl (151 kB)
Collecting xdoctest>=0.10.0
  Using cached xdoctest-1.0.0-py3-none-any.whl (117 kB)
Collecting yapf
  Using cached yapf-0.32.0-py2.py3-none-any.whl (190 kB)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages (from onnx==1.7.0->mmdet==2.23.0) (4.1.1)
Collecting protobuf
  Using cached protobuf-3.20.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting flatbuffers
  Using cached flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting requests>=2.7.9
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting coverage
  Using cached coverage-6.3.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (210 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting pycodestyle<2.9.0,>=2.8.0
  Using cached pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
Collecting pyflakes<2.5.0,>=2.4.0
  Using cached pyflakes-2.4.0-py2.py3-none-any.whl (69 kB)
Collecting tabulate
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting attrs
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting py
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting click>=7.1
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting scipy
  Using cached scipy-1.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.2-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Requirement already satisfied: pillow>=6.2.0 in /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages (from matplotlib->mmdet==2.23.0) (9.0.1)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.8-py3-none-any.whl (98 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting lap
  Using cached lap-0.4.0-cp39-cp39-linux_x86_64.whl
Collecting motmetrics
  Using cached motmetrics-1.2.5-py3-none-any.whl (161 kB)
Collecting dotty-dict
  Using cached dotty_dict-1.3.0-py3-none-any.whl
Collecting opencv-python
  Using cached opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.5 MB)
Collecting pandas<=1.3.5
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting pycocotools
  Using cached pycocotools-2.0.2-cp39-cp39-linux_x86_64.whl
Collecting scipy
  Using cached scipy-1.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.8 MB)
Collecting mmcls>=0.16.0
  Using cached mmcls-0.22.1-py2.py3-none-any.whl (548 kB)
Collecting seaborn
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting attributee==0.1.5
  Using cached attributee-0.1.5-py3-none-any.whl
Requirement already satisfied: setuptools>=18.0 in /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages (from pycocotools->mmdet==2.23.0) (61.2.0)
Collecting cython>=0.27.3
  Using cached Cython-0.29.28-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting tomli>=1.0.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting ordered-set
  Using cached ordered_set-4.1.0-py3-none-any.whl (7.6 kB)
Collecting pytz>=2017.3
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages (from requests>=2.7.9->codecov->mmdet==2.23.0) (2021.10.8)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting setuptools-scm
  Using cached setuptools_scm-6.4.2-py3-none-any.whl (37 kB)
Collecting xmltodict>=0.12.0
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Building wheels for collected packages: onnx
  Running command Building wheel for onnx (pyproject.toml)
  fatal: not a git repository (or any of the parent directories): .git
  /tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py:757: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 9.4.0
  -- The CXX compiler identification is GNU 9.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  Generated: /tmp/pip-install-c5mrjf7p/onnx_6ab6c6654a704f339c0cc65f25c67384/.setuptools-cmake-build/onnx/onnx-ml.proto
  CMake Error at CMakeLists.txt:256 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:287 (relative_protobuf_generate_cpp)


  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-c5mrjf7p/onnx_6ab6c6654a704f339c0cc65f25c67384/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 321, in <module>
      setuptools.setup(
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 136, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 217, in run
      self.run_command('cmake_build')
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-6oi5k57l/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 203, in run
      subprocess.check_call(cmake_args)
    File "/home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/elaine/miniconda3/envs/mmdet_pytest/include/python3.9', '-DPYTHON_EXECUTABLE=/home/elaine/miniconda3/envs/mmdet_pytest/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-39-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-c5mrjf7p/onnx_6ab6c6654a704f339c0cc65f25c67384']' returned non-zero exit status 1.
  error: subprocess-exited-with-error
  
  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/elaine/miniconda3/envs/mmdet_pytest/bin/python /home/elaine/miniconda3/envs/mmdet_pytest/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpgd137518
  cwd: /tmp/pip-install-c5mrjf7p/onnx_6ab6c6654a704f339c0cc65f25c67384
  Building wheel for onnx (pyproject.toml) ... error
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

```

**Comment by vansin** [comment]
I have solve the problem by using follow cmd
```shell
sudo apt-get install protobuf-compiler libprotoc-dev
```
