### ISSUE TITLE
Mask RCNN C4 cause import error

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#7887]
Hi @ZwwWayne @yhcao6 @hhaAndroid 

Please check [this issue](https://github.com/open-mmlab/mmselfsup/issues/301), the error info is:
```
+ CFG=configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py
+ PRETRAIN=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth
+ GPUS=8
+ PY_ARGS='--work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k'
++ echo configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco
++ sed -e s/configs/work_dirs/g
++ echo work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth
++ rev
++ cut -d/ -f 1
++ rev
+ WORK_DIR=work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth
++ dirname tools/benchmarks/mmdetection/mim_dist_train_c4.sh
+ PYTHONPATH=tools/benchmarks/mmdetection/..::/opt/tiger/arnold_toolbox
+ mim train mmdet configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py --launcher pytorch -G 8 --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k
Using port 24497 for synchronization.
Training command is python -m torch.distributed.launch --nproc_per_node=8 --master_port=24497 /home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py --launcher pytorch --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth --cfg-options model.backbone.init_cfg.type=Pretrained model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth model.roi_head.shared_head.init_cfg.type=Pretrained model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth --work-dir work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k.
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  FutureWarning,
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
torch.distributed: socket accepted connection from 127.0.0.1:47610
torch.distributed: socket accepted connection from 127.0.0.1:47612
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tools.benchmarks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 237, in <module>
    main()
  File "/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py", line 110, in main
    cfg = Config.fromfile(args.config)
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/config.py", line 340, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/tiger/.local/lib/python3.7/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 965536 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 965532) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 261, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

Traceback (most recent call last):
  File "/home/tiger/.local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/train.py", line 107, in cli
    other_args=other_args)
  File "/home/tiger/.local/lib/python3.7/site-packages/mim/commands/train.py", line 256, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'torch.distributed.launch', '--nproc_per_node=8', '--master_port=24497', '/home/tiger/.local/lib/python3.7/site-packages/mmdet/.mim/tools/train.py', 'configs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco.py', '--launcher', 'pytorch', '--work-dir', 'work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/final_model.pth', '--cfg-options', 'model.backbone.init_cfg.type=Pretrained', 'model.backbone.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth', 'model.roi_head.shared_head.init_cfg.type=Pretrained', 'model.roi_head.shared_head.init_cfg.checkpoint=work_dirs/mmselfsup/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k/final_model.pth', '--work-dir', 'work_dirs/benchmarks/mmdetection/coco/mask_rcnn_r50_c4_mstrain_1x_coco/pixpro/pixpro_resnet50_8xb128-coslr-100e_in1k']' returned non-zero exit status 1.
```

This import error is caused by `tools.benchmarks.mmdetection.res_layer_extra_norm` in [this line](https://github.com/open-mmlab/mmcv/blob/9f5a03dc2ca3731b2c1b18f90f826fcb9eb51ccf/mmcv/utils/misc.py#L80)

```
    for imp in imports:
        if not isinstance(imp, str):
            raise TypeError(
                f'{imp} is of type {type(imp)} and cannot be imported.')
        try:
            imported_tmp = import_module(imp)
        except ImportError:
            if allow_failed_imports:
                warnings.warn(f'{imp} failed to import and is ignored.',
                              UserWarning)
                imported_tmp = None
            else:
                print(imp)   # the output is `tools.benchmarks.mmdetection.res_layer_extra_norm`
                raise ImportError
        imported.append(imported_tmp)
```
```

**Comment by jbwang1997** [comment]
Thanks for your error report. 

This error is because Detectron2 installs its `tools` as a python package to your environment. Consequently, `import_module` finds `tools.benchmarks` in Detectron2's `tools` instead of mmselfsup's `tools`.

**Comment by mitming** [comment]
> Thanks for your error report.
> 
> This error is because Detectron2 installs its `tools` as a python package to your environment. Consequently, `import_module` finds `tools.benchmarks` in Detectron2's `tools` instead of mmselfsup's `tools`.

How can I fix this error?

**Comment by jbwang1997** [comment]
You can uninstall the `tools`. Make sure there is no module named `tools` in your environment.

**Comment by mitming** [comment]
> You can uninstall the `tools`. Make sure there is no module named `tools` in your environment.

Could you please explain the `tools.` ? Did you mean I should run `pip list` or `conda list` and remove all packages start with `tools.` ? However, I cannot find any packages meet this...

**Comment by mitming** [comment]
We can fix it by uninstalling the detectron2 in current enviroment.
