### ISSUE TITLE
GCNNet with x101 backbone is not work

### ISSUE THREAD

**Issue by zhengye1995** [open-mmlab/mmdetection#791]
I use gcb in x101 backbone，but get this error:
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 73, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/detectors/cascade_rcnn.py", line 36, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 36, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/backbones/resnext.py", line 191, in __init__
    super(ResNeXt, self).__init__(**kwargs)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/backbones/resnet.py", line 447, in __init__
    gen_attention_blocks=stage_with_gen_attention[i])
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/backbones/resnet.py", line 317, in make_res_layer
    (0 in gen_attention_blocks) else None))
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/backbones/resnext.py", line 19, in __init__
    super(Bottleneck, self).__init__(*args, **kwargs)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/models/backbones/resnet.py", line 205, in __init__
    self.context_block = ContextBlock(inplanes=gcb_inplanes, **gcb)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/mmdet-0.6.0+unknown-py3.6.egg/mmdet/ops/gcb/context_block.py", line 40, in __init__
    nn.Conv2d(self.inplanes, self.planes, kernel_size=1),
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 327, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 45, in __init__
    self.reset_parameters()
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 48, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/init.py", line 323, in kaiming_uniform_
    fan = _calculate_correct_fan(tensor, mode)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/init.py", line 292, in _calculate_correct_fan
    fan_in, fan_out = _calculate_fan_in_and_fan_out(tensor)
  File "/home/zhengye/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/nn/init.py", line 222, in _calculate_fan_in_and_fan_out
    receptive_field_size = tensor[0][0].numel()
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by GYxiaOH** [comment]
i meet the same problem. Do you know what's wrong?

**Comment by zhengye1995** [comment]
you should update your backbone file，because the orfer of parameters is changed to compliance with specificatinos. See pull  #780

**Comment by hellock** [comment]
Thanks for reporting! Will fix soon.

**Comment by GYxiaOH** [comment]
@zhengye1995 

i don't know what's your mean? your mean is my hyper parameter have some wrong? but when i run r4,it is ok, i only change gcb 1/4 to 1/16, the problem will appear
