### ISSUE TITLE
Testing two-stage detectors with imgs_per_gpu=2 on COCODataset produces errors

### ISSUE THREAD

**Issue by zacurr** [open-mmlab/mmdetection#795]
I changed imgs_per_gpu=2 here when testing cascade Mask R-CNN.
https://github.com/open-mmlab/mmdetection/blob/master/tools/test.py#L153

and comment out two lines.
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L74

but, it produced the following errors.
Because the images have different aspect ratios, size of tensors were not matched.
In training, however, it never happens. (when cfg.data.imgs_per_gpu is set to 2 or 3)

How should I fix test.py to deal with different shapes of images?
and How train.py handle this problem without errors?

and the possible bug introduced by this commit can only happen when imgs_per_gpu >=2 
https://github.com/open-mmlab/mmdetection/commit/f18561b57802ae158634765ef1a85c9972bc6af8

so I think the previous results that I obtained with previous aug_rpn is not changed. 
because of the following two lines.
https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/base.py#L74

Am I right?

[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/home/etri/Desktop/workspace_zacurr/mmdetection_190426/tools/test.py", line 198, in <module>
    main()
  File "/home/etri/Desktop/workspace_zacurr/mmdetection_190426/tools/test.py", line 168, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "/home/etri/Desktop/workspace_zacurr/mmdetection_190426/tools/test.py", line 23, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 551, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 572, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/mmcv-0.2.7-py3.6.egg/mmcv/parallel/collate.py", line 63, in collate
    for key in batch[0]
  File "/opt/conda/lib/python3.6/site-packages/mmcv-0.2.7-py3.6.egg/mmcv/parallel/collate.py", line 63, in <dictcomp>
    for key in batch[0]
  File "/opt/conda/lib/python3.6/site-packages/mmcv-0.2.7-py3.6.egg/mmcv/parallel/collate.py", line 59, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/mmcv-0.2.7-py3.6.egg/mmcv/parallel/collate.py", line 59, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/opt/conda/lib/python3.6/site-packages/mmcv-0.2.7-py3.6.egg/mmcv/parallel/collate.py", line 66, in collate
    return default_collate(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 43, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 608 and 640 in dimension 3 at ../aten/src/TH/generic/THTensor.cpp:726

**Comment by hellock** [comment]
Testing with larger batch size than 1 is not officially supported now. We will still investigate it according to your findings.

**Comment by zacurr** [comment]
I should correct my assumption.
I found the bug fix affect the results even when imgs_per_gpu=1
https://github.com/open-mmlab/mmdetection/commit/f18561b57802ae158634765ef1a85c9972bc6af8

Before bug fixed, it collect ROIs from a single scale and discard ROIs from other scales and their flips.

**Comment by ll490187880** [comment]
> Testing with larger batch size than 1 is not officially supported now. We will still investigate it according to your findings.

When will the larger batch size for testing supported? The imgs_per_gpu=1 in testing process is quite slow for some larger models.

**Comment by joeythegod** [comment]
imgs_per_gpu=1 is really slow, hope there is a solution.

**Comment by serser** [comment]
How about now? Is it resolved?
