### ISSUE TITLE
Get training time and inference time

### ISSUE THREAD

**Issue by edehino** [open-mmlab/mmdetection#7966]
Hi, I'd like to get the training time and the inference time. I can simply add the code but I don't know where to put it. Hope you can help me with this. Thanks!

**Comment by RangiLyu** [comment]
You can find the training time in the training log.
And you need to use tools/analysis_tools/benchmark.py to get the inference time.

**Comment by 654140593** [comment]
Dear mmdetection team,

When I tried to use benchmark.py for inference time, I got an error message like this
python tools/analysis_tools/benchmark.py  configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py   checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth  --log-interval 50 --fuse-conv-bn
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 195, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 185, in main
    raise NotImplementedError('Only supports distributed mode')
NotImplementedError: Only supports distributed mode

Can you please help me with this issue?

Best wishes
Neil

**Comment by alaa-shubbak** [comment]
i am also interested to know how to use function `tools/analysis_tools/benchmark.py` to get the inference time and the fps 
please help

**Comment by moon6666** [comment]
i am also interested to know how to use function tools/analysis_tools/benchmark.py to get the inference time and the fps
please help!
