### ISSUE TITLE
Mask2Former input shape inference error

### ISSUE THREAD

**Issue by caiobarrosv** [open-mmlab/mmdetection#7979]
I cannot perform any inference by using the pre-trained weights of the Mask2Former.
The network is loaded correctly, but I cannot perform inferences.

Model and config files:
config_file = Mask2Former\Mask2Former\mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.py
checkpoint_file = Mask2Former\mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.pth
device = 'cuda:0'

Script used:
```python
from mmdet.apis import init_detector, inference_detector
model = init_detector(config_file, checkpoint_file, device=device)
inference_detector(model, img)
```

When I run inference_detector() I get the following error:

```bash
load checkpoint from local path: C:\Users\engca\OneDrive\MAPZER\Repo\mapzer_cnns\pytorch\CNN Weights\pre_trained\Mask2Former\mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.pthImage shape: (1080, 1920, 3)
Traceback (most recent call last):
  File "c:\Users\engca\OneDrive\MAPZER\Repo\mapzer_cnns\pytorch\Networks\Papnotic_segmentation\Mask2Former\Mask2Former_openMMLAB.py", line 28, in <module>
    inference_detector(model, img)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\apis\inference.py", line 151, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\detectors\maskformer.py", line 130, in simple_test
    feats = self.extract_feat(imgs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\detectors\single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\backbones\swin.py", line 746, in forward
    x, hw_shape = self.patch_embed(x)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\users\engca\onedrive\mapzer\repo\mmdetection\mmdet\models\utils\transformer.py", line 252, in forward
    x = self.projection(x)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\engca\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [96, 3, 4, 4], expected input[1, 768, 1344, 4] to have 3 channels, but got 768 channels instead
```

Any thoughts on this issue?
Has it anything to do with image resolution?

Thank you in advance :)

**Comment by BIGWangYuDong** [comment]
What code did you use? What confit file did You use?
