### ISSUE TITLE
import custom model error

### ISSUE THREAD

**Issue by GF1447571253** [open-mmlab/mmdetection#7983]
I run tools/train.py on my machine and got a KeyError!
2022-05-14 15:19:32,105 - mmdet - INFO - Set random seed to 640356377, deterministic: False
Traceback (most recent call last):
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/models/detectors/yolox.py", line 58, in __init__
    super(YOLOX, self).__init__(backbone, neck, bbox_head, train_cfg,
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'ConvNeXt is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 207, in main
    model = build_detector(
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmdet/models/builder.py", line 58, in build_detector
    return DETECTORS.build(
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "YOLOX: 'ConvNeXt is not in the models registry'"

However, i run it on pycharm with ssh interpreter, and the code works

**Comment by chhluo** [comment]
ConvNeXt is not support yet, #7281

**Comment by GF1447571253** [comment]
Sorry, i think i didn’t describe my question clearly, all I want to ask is , i run the code with pycharm by ssh liking my server ,no error occur, but run the code in server shell got a error.
For more information,I would like describing my question again in Chinese.
我在pycharm上通过ssh远程连接服务器，然后在pycharm上运行代码，没有报错。但是在服务器的终端上运行代码就报错？
convnext我已经实现并通过加入到mmdet/models/backbones/__init__.py里面了，也通过custom_imports加入到配置文件中了

Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: Cedric Luo ***@***.***&gt;
Date: Sat,May 14,2022 7:09 PM
To: open-mmlab/mmdetection ***@***.***&gt;
Cc: GF1447571253 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmdetection] import custom model error (Issue #7983)





 
ConvNeXt is not support yet, #7281

**Comment by chhluo** [comment]
Please check whether convnext exists on the sever and whether you use the expected the conda or pip environment.

**Comment by GF1447571253** [comment]
yes, I'm sure that i have check convnext on mmdetection/mmdet/models/backbones/ folders and conda envs is same whether pycharm or shell. 
![image](https://user-images.githubusercontent.com/23076399/168463067-b03e9b9b-c0d0-457e-80e0-d3e6c2c4a787.png)
and i have tried to add the code below
# custom_imports = dict(
#     imports=[
#         'mmdet.models.backbones._csp_darknet.py'
#     ],
#     allow_failed_imports=False)
and it turns out
(mmdet) sdxx@sdxx-Precision-5820-Tower:~/hgf/mmdetection$ python tools/train.py 
Traceback (most recent call last):
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'convnext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 110, in main
    cfg = Config.fromfile(args.config)
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/config.py", line 337, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/sdxx/hgf/anaconda3/envs/mmdet/lib/python3.8/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError
it seems strange!

**Comment by chhluo** [comment]
In the picture, the path is `mmdet.models.backbones.csp_darknet.py`, not `mmdet.models.backbones._csp_darknet.py`

**Comment by GF1447571253** [comment]
yes,  i just want to show you convnext existing, _csp_darknet.py is in the bottom.

**Comment by chhluo** [comment]
Please reinstall mmdet by `pip install -v -e .` in directory `mmdetection`.

**Comment by chhluo** [comment]
Please paste your config file and your env infomation when running in terminal. By the way, ConvNext is supported in mmclassification https://github.com/open-mmlab/mmclassification/tree/master/configs/convnext, you can directly used in mmdet

**Comment by GF1447571253** [comment]
yes,  i did
![image](https://user-images.githubusercontent.com/23076399/169192081-2541a8b2-7e1b-44b0-aca5-8a535c04aa41.png)
![image](https://user-images.githubusercontent.com/23076399/169192102-02637a59-13cb-4efc-99e1-7380e00dc586.png)

**Comment by chhluo** [comment]
It's strange that running is okay in pycharm which connected to the remote server, but failed in terminal. Running  is okay in pycharm verifyed that your modifcation is correct. So is there any special setting in pycharm?

**Comment by GF1447571253** [comment]
I downloaded the mmdetection in my laptop and remote server respectively，and then I added a ssh interpreter.
![image](https://user-images.githubusercontent.com/23076399/169684019-6e51984d-2299-4862-873f-43f92c2ba059.png)
![image](https://user-images.githubusercontent.com/23076399/169684042-8762e52d-4a60-418f-ae02-e444c822cbf4.png)
and I'm not done anything special in pycharm and all the modfication i've done in pycharm can be seen in the remote server(inlcuding new a python file, modify the code and so on)

**Comment by PandaHead2077** [comment]
hi, did you solve this problem? I met the same problem.

**Comment by GF1447571253** [comment]
no



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ Original ------------------
From: cc ***@***.***&gt;
Date: Mon,Jun 13,2022 10:14 AM
To: open-mmlab/mmdetection ***@***.***&gt;
Cc: GF1447571253 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [open-mmlab/mmdetection] import custom model error (Issue #7983)





 
hi, did you solve this problem? I met the same problem.

**Comment by Clichong** [comment]
I designed a network structure name "SpinMLP" and configured it according to the documentation, but he got the same error：KeyError: 'SpinMLP is not in the models registry'
![image](https://user-images.githubusercontent.com/55774787/189477959-dc3d5a01-06a8-4cb7-8305-d5c7b37b3cb0.png)
