### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by Y-M-Y** [open-mmlab/mmdetection#7991]
I encountered the following error when I trained FCOS with pvtv2_b2 as a backbone on my own dataset.
```text
Traceback (most recent call last):
  File "tools/train.py", line 220, in <module>
    main()
  File "tools/train.py", line 216, in main
    meta=meta)
  File "/home/yangmoyi/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1603729047590/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f54cd7b38b2 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f54cda05982 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f54cd79eb7d in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x811159 (0x7f5510a81159 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x252f083 (0x7f551279f083 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x29640a2 (0x7f5512bd40a2 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f5512bd414f in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x4818d9 (0x7f551798a8d9 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: c10::TensorImpl::release_resources() + 0x20 (0x7f54cd79eb50 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x5fbb7a (0x7f5517b04b7a in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x5fbc26 (0x7f5517b04c26 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #25: __libc_start_main + 0xf3 (0x7f55492390b3 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

```

The training process worked well when the FCOS backbone is pvtv2_b1 and pvtv2_b3. Therefore I think my own dataset is generally good and GPU is enough.

It's wired, the config of FCOS_pvtv2_b2 is almost the same as FCOS_pvtv2_b3. The differences are:
1. the num of layers
2. pretrained model

pvtv2_b2 is like
```python
backbone=dict(
        type='PyramidVisionTransformerV2',
        embed_dims=64,
        num_layers=[3, 4, 6, 3],
        init_cfg=dict(
            checkpoint=
            'https://github.com/whai362/PVT/releases/download/v2/pvt_v2_b2.pth'
        ))
```
pvtv2_b3 is like
```python
backbone=dict(
        type='PyramidVisionTransformerV2',
        embed_dims=64,
        num_layers=[3, 4, 18, 3],
        init_cfg=dict(
            checkpoint=
            'https://github.com/whai362/PVT/releases/download/v2/pvt_v2_b3.pth'
        ))
```

PS: Maybe my own dataset is not good enough? :)

Here's my
[fcos_pvt_b2_fpn_2x_coco_wd67.zip](https://github.com/open-mmlab/mmdetection/files/8695277/fcos_pvt_b2_fpn_2x_coco_wd67.zip)
 config of FCOS_pvtv2_b2.

**Comment by ZwwWayne** [comment]
Please set CUDA_LAUNCH_BLOCKING=1 in you code to see which line cause this error. For now, it is hard to tell the reason that causes this issue.

**Comment by Y-M-Y** [comment]
@ZwwWayne 
Here's the new error report after adding CUDA_LAUNCH_BLOCKING=1 in training command. Thanks for your hint!
```
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1603729047590/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f31ef12a8b2 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7f31ef37c982 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f31ef115b7d in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x811159 (0x7f32323f8159 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x252f083 (0x7f3234116083 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x29640a2 (0x7f323454b0a2 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f323454b14f in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x4818d9 (0x7f32393018d9 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: c10::TensorImpl::release_resources() + 0x20 (0x7f31ef115b50 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x5fbb7a (0x7f323947bb7a in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x5fbc26 (0x7f323947bc26 in /home/yangmoyi/anaconda3/envs/mmdet223/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #25: __libc_start_main + 0xf3 (0x7f326abb00b3 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```
