### ISSUE TITLE
[Question] Error when converting yolact to ONNX

### ISSUE THREAD

**Issue by gggaugau** [open-mmlab/mmdetection#7995]
Hello. May I ask if converting yolact to ONNX/TRT is currently available? I tried to convert using tools/deployment/pytorch2onnx.py but it seems to be errors. 
Please help me, thanks a lot in advance.
```
python tools/deployment/pytorch2onnx.py configs/yolact/yolact_r50_1x8_coco.py /home/gggggg/projects/yolact_weights/r50_1x8_coco/2104.pth --output-file test.onnx --input-img /home/gggggg/projects/test.jpg
mmdetection/tools/deployment/pytorch2onnx.py:299: UserWarning: Arguments like `--mean`, `--std`, `--dataset` would be         parsed directly from config file and are deprecated and         will be removed in future releases.
  warnings.warn('Arguments like `--mean`, `--std`, `--dataset` would be \
/home/gggggg/miniconda3/lib/python3.9/site-packages/mmcv/onnx/symbolic.py:481: UserWarning: DeprecationWarning: This function will be deprecated in future. Welcome to use the unified model deployment toolbox MMDeploy: https://github.com/open-mmlab/mmdeploy
  warnings.warn(msg)
load checkpoint from local path: /home/gggggg/projects/yolact_weights/r50_1x8_coco/2104.pth
[W NNPACK.cpp:51] Could not initialize NNPACK! Reason: Unsupported hardware.
/home/gggggg/mmdetection/./mmdet/models/dense_heads/base_dense_head.py:415: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  nms_pre_tensor = torch.tensor(
/home/gggggg/mmdetection/./mmdet/models/dense_heads/base_dense_head.py:436: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/gggggg/mmdetection/./mmdet/core/export/onnx_helper.py:63: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k <= 0 or size <= 0:
/home/gggggg/mmdetection/./mmdet/models/dense_heads/base_dense_head.py:457: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre > 0:
Traceback (most recent call last):
  File "/home/gggggg/mmdetection/tools/deployment/pytorch2onnx.py", line 335, in <module>
    pytorch2onnx(
  File "/home/gggggg/mmdetection/tools/deployment/pytorch2onnx.py", line 91, in pytorch2onnx
    torch.onnx.export(
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 499, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 440, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/onnx/utils.py", line 391, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/gggggg/mmdetection/./mmdet/models/detectors/base.py", line 169, in forward
    return self.onnx_export(img[0], img_metas[0])
  File "/home/gggggg/mmdetection/./mmdet/models/detectors/single_stage.py", line 168, in onnx_export
    det_bboxes, det_labels = self.bbox_head.onnx_export(
  File "/home/gggggg/miniconda3/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
  File "/home/gggggg/mmdetection/./mmdet/models/dense_heads/base_dense_head.py", line 460, in onnx_export
    nms_pre_score = (nms_pre_score * score_factors[..., None])
RuntimeError: The size of tensor a (45600) must match the size of tensor b (1459200) at non-singleton dimension 1
```

**Comment by Czm369** [comment]
You can try
https://github.com/open-mmlab/mmdeploy
