### ISSUE TITLE
Errors occurring when training the swin transformer

### ISSUE THREAD

**Issue by qingfengtommy** [open-mmlab/mmdetection#8001]
Hello sir!
I used the swin transformer to train a custom dataset in **coco** format. 

My current **working environment** is :
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0
TorchVision: 0.7.0
OpenCV: 4.5.5
MMCV: 1.3.17
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMDetection: 2.11.0+461e003

I encountered **following errors**:

_**Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/swin/mmdet/datasets/pipelines/auto_augment.py", line 98, in __init__
    'Each specific augmentation must be a dict with key' \
AssertionError: Each specific augmentation must be a dict with key "type".

During handling of the above exception, another exception occurred:

**_Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/swin/mmdet/datasets/custom.py", line 104, in __init__
    self.pipeline = Compose(pipeline)
  File "/swin/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: AutoAugment: Each specific augmentation must be a dict with key "type"._**

**_During handling of the above exception, another exception occurred:_**

**_Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "/tools/train.py", line 163, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/swin/mmdet/datasets/builder.py", line 71, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/anaconda3/lib/python3.7/site-packages/mmcv/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: CocoDataset: AutoAugment: Each specific augmentation must be a dict with key "type"_**

Could you please give me any advice? 
Thanks!

**Comment by hhaAndroid** [comment]
@qingfengtommy This is because your AutoAugment configuration is wrong. Some augs do not have a type field, please confirm it

**Comment by qingfengtommy** [comment]
That's really helpful. Thank you sir!
