### ISSUE TITLE
After adding albu, an error occurs: AttributeError: 'list' object has no attribute 'rescale'

### ISSUE THREAD

**Issue by hailyxu** [open-mmlab/mmdetection#8020]
I choosed albumentations to do data aug when I use QuestInst to tackle instance segmentation task , here is my corresponding config setting:

```python
    dict(
        type='Albu',
        transforms=[
            dict(
                type='RandomBrightnessContrast',
                brightness_limit=[-0.6, 0.6],
                contrast_limit=[-0.4, 0.4],
                p=0.7),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=0.2
            ),
            dict(
                type='GaussianBlur',
                blur_limit=(3, 7),
                sigma_limit=0,
                p=0.7
            )
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=["gt_labels"],
        )),
```

I think I got everything right, but an error occurs:
```bash
Original Traceback (most recent call last):
  File "/home/chiebot-cv/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/chiebot-cv/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chiebot-cv/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/custom.py", line 241, in prepare_train_img
    return self.pipeline(results)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/auto_augment.py", line 106, in __call__
    return transform(results)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/transforms.py", line 313, in __call__
    self._resize_masks(results)
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/transforms.py", line 259, in _resize_masks
    results[key] = results[key].rescale(results['scale'])
AttributeError: 'list' object has no attribute 'rescale'
```

I think this is because in:
```python
    def _resize_masks(self, results):
        """Resize masks with ``results['scale']``"""
        for key in results.get('mask_fields', []):
            if results[key] is None:
                continue
            if self.keep_ratio:
                results[key] = results[key].rescale(results['scale'])
            else:
                results[key] = results[key].resize(results['img_shape'][:2])

``` 
`results['gt_masks']` is a list with an ndarray in it. So it can't call rescale()

What should I do?

btw: If I don't use albu, there would be no error.

**Comment by RangiLyu** [comment]
The type of gt_masks should be one of the mask structures defined in mmdet/core/mask/structures.py.

And did you set the key mapping correctly like this?

```
    dict(
        type='Albu',
        ...
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
```

**Comment by hailyxu** [comment]
> The type of gt_masks should be one of the mask structures defined in mmdet/core/mask/structures.py.
> 
> And did you set the key mapping correctly like this?
> 
> ```
>     dict(
>         type='Albu',
>         ...
>         keymap={
>             'img': 'image',
>             'gt_masks': 'masks',
>             'gt_bboxes': 'bboxes'
>         },
>         update_pad_shape=False,
>         skip_img_without_anno=True),
> ```


Oh sorry, I didn't. But after I add key mapping like this:
```python
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=["gt_labels"],
        ),
        keymap={
            'img': 'image',
            'gt_masks': 'masks',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
```
Still the same error eccors:
```bash
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/mmdet/datasets/pipelines/transforms.py", line 260, in _resize_masks
    results[key] = results[key].rescale(results['scale'])
AttributeError: 'list' object has no attribute 'rescale'
```
I tried to debug this part:
```python
    def _resize_masks(self, results):
        """Resize masks with ``results['scale']``"""
        for key in results.get('mask_fields', []):
            if results[key] is None:
                continue
            if self.keep_ratio:
                results[key] = results[key].rescale(results['scale'])
            else:
                results[key] = results[key].resize(results['img_shape'][:2])
```
the key is:
```bash
key: gt_masks
```
the result[key]:
```bash
results[key]: [array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)]
type(results[key]): <class 'list'>
```

I'm so confused now, even doubt whether my coco-format .json file is correct or not.. But if I don't add albu, everything would be alright, I have checked that.

**Comment by hailyxu** [comment]
Nevermind, you guys can close the issue, I did albu offline.
