### ISSUE TITLE
NotImplementedError: You must implement the backward function for custom autograd.Function.

### ISSUE THREAD

**Issue by champagne-yellow** [open-mmlab/mmdetection#8027]
I added a mask branch to the objection detection network and reported an error during training:

Traceback (most recent call last):
  File "/home/champagne/file/Mask-CornerNet/V1/tools/train.py", line 193, in <module>
    main()
  File "/home/champagne/file/Mask-CornerNet/V1/tools/train.py", line 189, in main
    validate=(not args.no_validate), timestamp=timestamp, meta=meta)
  File "/home/champagne/file/Mask-CornerNet/V1/mmdet/apis/train.py", line 207, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 201, in backward
    raise NotImplementedError("You must implement the backward function for custom"
NotImplementedError: You must implement the backward function for custom autograd.Function.

Process finished with exit code 1

It seems to be an error in the back propagation process, but how to find the wrong code?

**Comment by ZwwWayne** [comment]
It seems that customized operators is added and got issues during BP. You may check the code added and see if there is any custom operators that inherits autograd.Function but only implements forward. The code should look like the code in mmcv.ops.

**Comment by champagne-yellow** [comment]
@ZwwWayne 
Hi ZwwWayne, thank you very much, but I still haven't solved this problem. Let me tell you how my network is implemented.
I added a fcn_mask_head branch to the CornerNet. The boxes generated by the CornerNet are used as proposals for segmentation. (The overall idea is like Centripetalnet, but the code of the instance of Centripetalnet, an open source of MMdetection, seems incomplete, which makes it unusable.) 
I changed the box_head of the CornerNet to roi_head. The roi_head contains the box_head and the mask_head. When I remove the mask_head, the network can be trained normally, but when the mask_head is added, an error(NotImplementedError: You must implement the backward function for custom autograd.Function.) is reported.
I can't find the code about BP. What should I do?

**Comment by champagne-yellow** [comment]
@ZwwWayne 
I also added the cross-entropy loss function to calculate the loss of the mask. When the cross-entropy loss function is removed, it can be trained, but an error will be reported after adding it.

**Comment by ZwwWayne** [comment]
There might be some issues when you use roi_head to replace the bbox_head. And the no grad fuction problem may caused by ROIAlign.

**Comment by champagne-yellow** [comment]
@ZwwWayne 
Thank you very much, I have solved this problem.
The proposal generated by bbox_head needs to be detached, otherwise it will enter the subsequent calculation graph.
