### ISSUE TITLE
WandbLoggerHook doesn't log validation loss

### ISSUE THREAD

**Issue by MABatin** [open-mmlab/mmdetection#8034]
I was trying to use wandblogger with some of my runs but unlike tensorboardlogger it doesn't log val losses or accuracy. 
I edited my config file to add
workflow = [('train', 1), ('val', 1)]

What might be the issue here?

**Comment by ayulockin** [comment]
Can you give this dedicated logger a try #7459 and see if it is able to log your validation metrics? It's still a PR though.

**Comment by hhaAndroid** [comment]
Closed due to no reply for more than 8 days.

**Comment by MABatin** [comment]
> Can you give this dedicated logger a try #7459 and see if it is able to log your validation metrics? It's still a PR though.

Hi @ayulockin I have tried to use your dedicated logger after it was merged. But when trying to run with MMDetWandbHook logger I get this error

```none
Traceback (most recent call last):
  File "D:\Leon\SpikeDetection\Wheat\tools\train.py", line 237, in <module>
    main()
  File "D:\Leon\SpikeDetection\Wheat\tools\train.py", line 226, in main
    train_detector(
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\apis\train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 108, in run
    self.call_hook('before_run')
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\dist_utils.py", line 129, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\core\hook\wandblogger_hook.py", line 142, in before_run
    self.wandb.save(src_cfg_path, base_path=runner.work_dir)
  File "C:\Users\leonh\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1579, in save
    return self._save(glob_str, base_path, policy)
  File "C:\Users\leonh\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1633, in _save
    os.symlink(abs_path, wandb_path)
OSError: [WinError 1314] A required privilege is not held by the client: 'D:\\Leon\\SpikeDetection\\Wheat\\work_dirs\\retinanet\\retinanet_r50_bifpn_2x_coco.py' -> 'Wheat/work_dirs/retinanet/wandb\\run-20220617_154947-11j6i2bq\\files\\
retinanet_r50_bifpn_2x_coco.py'
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
```

I don't know what is causing this issue and your help would be much appreciated.

**Comment by ayulockin** [comment]
The error is happening in this line inside `MMDetWandbHook` - `self.wandb.save(src_cfg_path, base_path=runner.work_dir)`. This line is simply trying to write the config file to the work_dir. In your case the config file  at `D:\\Leon\\SpikeDetection\\Wheat\\work_dirs\\retinanet\\retinanet_r50_bifpn_2x_coco.py` is to be written to `Wheat/work_dirs/retinanet/wandb\\run-20220617_154947-11j6i2bq\\files\\
retinanet_r50_bifpn_2x_coco.py`. 

The OSError is stating that you don't have the required permission to do so. Having said this, I would like to know if you are using your own system or a public windows system (college, library, etc.)? Plus I would check on my end if `wandb.save` fails on a windows system (it should but will check anyway).

**Comment by ayulockin** [comment]
Hey @MABatin, having looked closely this seemed to be a reported [issue](https://github.com/wandb/client/issues/1370). 

On what version of W&B are you? 

To quickly fix this you can run your code with administrator privileges. Or you can follow the suggestion in the issue linked above. I will get confirmation on my end if this is something we have fixed.

**Comment by MABatin** [comment]
@ayulockin Thank you for your quick response. I am using my own system with Windows 10 and wandb version 0.12.16. Running the code with administrator privileges seem to solve the OSError but now the following error is occuring.
```none
Traceback (most recent call last):
  File "D:\Leon\SpikeDetection\Wheat\tools\train.py", line 237, in <module>
    main()
  File "D:\Leon\SpikeDetection\Wheat\tools\train.py", line 226, in main
    train_detector(
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\apis\train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 108, in run
    self.call_hook('before_run')
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmcv\runner\dist_utils.py", line 129, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\core\hook\wandblogger_hook.py", line 200, in before_run
    self._add_ground_truth(runner)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\core\hook\wandblogger_hook.py", line 379, in _add_ground_truth
    wandb_masks = self._get_wandb_masks(
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\core\hook\wandblogger_hook.py", line 535, in _get_wandb_masks
    mask = polygon_to_bitmap(mask, height, width)
  File "C:\Users\leonh\anaconda3\lib\site-packages\mmdet\core\mask\structures.py", line 1069, in polygon_to_bitmap
    rles = maskUtils.frPyObjects(polygons, height, width)
  File "pycocotools\_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range
```
From what I understand, this might be because the logger is trying to get mask information when there is none (my dataset indeed has no mask annotations). But this shouldn't be the case and what might be the fix for this?
