### ISSUE TITLE
ImportError: cannot import name 'eval_map' from partially initialized module 'mmdet.core' (most likely due to a circular import) (D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\__init__.py)

### ISSUE THREAD

**Issue by Runner9** [open-mmlab/mmdetection#8042]
I'm having this problem when running the train.py, has anyone encountered this error?
```python
Traceback (most recent call last):
  File "E:/mmdetection-master/tools/train.py", line 20, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\apis\inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\bbox\__init__.py", line 2, in <module>
    from .assigners import (AssignResult, BaseAssigner, CenterRegionAssigner,
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\bbox\assigners\__init__.py", line 2, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\bbox\assigners\approx_max_iou_assigner.py", line 6, in <module>
    from .max_iou_assigner import MaxIoUAssigner
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\bbox\assigners\max_iou_assigner.py", line 6, in <module>
    from .assign_result import AssignResult
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\bbox\assigners\assign_result.py", line 4, in <module>
    from mmdet.utils import util_mixins
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\utils\__init__.py", line 6, in <module>
    from .det_cam_visualizer import (DetAblationLayer, DetBoxScoreTarget,
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\utils\det_cam_visualizer.py", line 26, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\datasets\__init__.py", line 3, in <module>
    from .cityscapes import CityscapesDataset
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\datasets\cityscapes.py", line 17, in <module>
    from .coco import CocoDataset
  File "D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\datasets\coco.py", line 16, in <module>
    from mmdet.core import eval_recalls
ImportError: cannot import name 'eval_recalls' from partially initialized module 'mmdet.core' (most likely due to a circular import) (D:\Anaconda3\envs\my_mmdet\lib\site-packages\mmdet\core\__init__.py)
```

Here is the source code of mmdet,
```python
from mmdet.core import eval_recalls
```

Although it will run after changing "import" to the following,
```python
from mmdet.core.evaluation.recall import eval_recalls
```
But there are still many imports that need to be changed, except for "eval_recalls".

And I think this should not be a circular call problem? Is there a conflict between what is installed? Or is it something else?
The other day it was running fine, but today it suddenly stopped working.
Platform：Windows 10，Pycharm
mmcv：1.4.6
mmdet：2.22.0

**Comment by hhaAndroid** [comment]
@Runner9 where did you change it?

**Comment by Runner9** [comment]
@hhaAndroid 
I didn't change anything, or maybe I accidentally changed something when I changed the network but it wasn't noticed.
But then I upgraded both mmcv and mmdet to the latest version and it was back to normal.
Is it possible that there is a conflict with other environments in anaconda? Or maybe I changed some code by mistake?

**Comment by hhaAndroid** [comment]
@Runner9 Maybe something changed, but you didn't find it.

**Comment by zhouxuexiao** [comment]
@guazat Hello, did you ultimately resolve it by updating mmcv and mmdet? Are there any other solutions?I am currently facing the same issue as you.

**Comment by LvRuH** [comment]
Perhaps there were no modifications made to the relevant __ init__. py
