### ISSUE TITLE
KeyError: "CurvelanesDatasetClass: 'albumentation is not in the pipeline registry'"

### ISSUE THREAD

**Issue by Ehangiun** [open-mmlab/mmdetection#8043]
I define the format of the dataset and register the database. why does this dataset report an error

Traceback (most recent call last):
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 213, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/vcar/lane/mmdetection/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/vcar/miniconda3/envs/lane/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CurvelanesDatasetClass: 'albumentation is not in the pipeline registry'"

**Comment by jbwang1997** [comment]
Do you add a pipeline named `albumentation` in `train_piplines`? MMDetection provides `albu` pipeline to support albumentation. Please check if the pipeline name is correct.

**Comment by Ehangiun** [comment]
Okay, I see what the problem is,thank
