### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by champagne-yellow** [open-mmlab/mmdetection#8047]
I added a mask branch to the objection detection network and reported an error during training:

Traceback (most recent call last):
File "/home/champagne/file/Mask-CornerNet/V1/tools/train.py", line 193, in
main()
File "/home/champagne/file/Mask-CornerNet/V1/tools/train.py", line 189, in main
validate=(not args.no_validate), timestamp=timestamp, meta=meta)
File "/home/champagne/file/Mask-CornerNet/V1/mmdet/apis/train.py", line 207, in train_detector
runner.run(data_loaders, cfg.workflow)
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
epoch_runner(data_loaders[i], **kwargs)
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
self.call_hook('after_train_iter')
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
getattr(hook, fn_name)(self)
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
runner.outputs['loss'].backward()
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/init.py", line 132, in backward
allow_unreachable=True) # allow_unreachable flag
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 89, in apply
return self._forward_cls.backward(self, *args) # type: ignore
File "/home/champagne/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/autograd/function.py", line 201, in backward
raise NotImplementedError("You must implement the backward function for custom"
NotImplementedError: You must implement the backward function for custom autograd.Function.

Process finished with exit code 1

It seems to be an error in the back propagation process, but how to find the wrong code?

**Comment by jbwang1997** [comment]
This bug is because some operation in your model hadn't realized the backward function. Could you follow the issue template to provide more information?

**Comment by jbwang1997** [comment]
This issue will be closed due to inactivity. Feel free to reopen it if you have any questions.
