### ISSUE TITLE
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8074]
```shell
python tools/train.py configs/efficientnet/retinanet_effb3_fpn_crop896_8x4_1x_coco.py
```

```shell
Traceback (most recent call last):
  File "/project/mmlab_template/tools/train.py", line 209, in <module>
    main()
  File "/project/mmlab_template/tools/train.py", line 191, in main
    train_detector(
  File "/project/mmlab_template/mmdetection/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/project/mmlab_template/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/project/mmlab_template/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/project/mmlab_template/mmdetection/mmdet/models/detectors/single_stage.py", line 82, in forward_train
    x = self.extract_feat(img)
  File "/project/mmlab_template/mmdetection/mmdet/models/detectors/single_stage.py", line 43, in extract_feat
    x = self.backbone(img)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/project/mmlab_template/mmdetection/mmdet/models/backbones/efficientnet.py", line 398, in forward
    x = layer(x)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/mmcv/cnn/bricks/conv_module.py", line 203, in forward
    x = self.norm(x)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 731, in forward
    world_size = torch.distributed.get_world_size(process_group)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 748, in get_world_size
    return _get_group_size(group)
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 274, in _get_group_size
    default_pg = _get_default_group()
  File "/home/elaine/miniconda3/envs/cvmart/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 358, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

During handling of the above exception, another exception occurred:
```

**Comment by chhluo** [comment]
This is caused by `norm_cfg=dict(type='SyncBN', requires_grad=True, eps=1e-3, momentum=0.01),` in backbone part when training with single gpu. Replacing `SyncBN` with `BN` can solve the problem when training with single gpu.

**Comment by vansin** [comment]
thanks
