### ISSUE TITLE
## **I checked and this is predictive, but why can't it generate a thermal map?**

### ISSUE THREAD

**Issue by BigHeadShang** [open-mmlab/mmdetection#8085]
## **I checked and this is predictive, but why can't it generate a thermal map?**
load checkpoint from local path: /content/gdrive/MyDrive/mmdetection/bighead-mask_rcnn/mask_rcnn_r101_fpn_mstrain-poly_3x_coco_20210524_200244-5675c317.pth
/content/gdrive/MyDrive/mmdetection1/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
  File "demo/vis_cam.py", line 238, in <module>
    main()
  File "demo/vis_cam.py", line 219, in main
    eigen_smooth=args.eigen_smooth)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/utils/det_cam_visualizer.py", line 327, in __call__
    return self.cam(img, targets, aug_smooth, eigen_smooth)[0, :]
  File "/usr/local/lib/python3.7/dist-packages/pytorch_grad_cam/base_cam.py", line 185, in __call__
    targets, eigen_smooth)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_grad_cam/base_cam.py", line 74, in forward
    outputs = self.activations_and_grads(input_tensor)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_grad_cam/activations_and_gradients.py", line 42, in __call__
    return self.model(x)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/utils/det_cam_visualizer.py", line 176, in __call__
    loss = self.detector(return_loss=True, **self.input_data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/models/detectors/two_stage.py", line 150, in forward_train
    **kwargs)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/models/roi_heads/standard_roi_head.py", line 113, in forward_train
    gt_masks, img_metas)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/models/roi_heads/standard_roi_head.py", line 173, in _mask_forward_train
    self.train_cfg)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 144, in get_targets
    gt_masks, rcnn_train_cfg)
  File "/content/gdrive/MyDrive/mmdetection1/mmdet/core/mask/mask_target.py", line 60, in mask_target
    pos_assigned_gt_inds_list, gt_masks_list, cfg_list)
TypeError: 'NoneType' object is not iterable

_Originally posted by @BigHeadShang in https://github.com/open-mmlab/mmdetection/issues/7987#issuecomment-1140676877_

**Comment by BigHeadShang** [comment]
import os
os.chdir('/content/gdrive/MyDrive/mmdetection1')
!python demo/vis_cam.py /content/gdrive/MyDrive/mmdetection/data/coco2/val2017/13.jpg /content/gdrive/MyDrive/mmdetection/bighead-mask_rcnn/mask_rcnn_r101_fpn_2x_coco.py /content/gdrive/MyDrive/mmrazor/student.pth 
### this is origin code

**Comment by Czm369** [comment]
Visual heatmaps are not yet supported.

**Comment by zhangzhengbin96** [comment]
请问你解决这个问题了吗，我现在遇到跟你同样的问题
