### ISSUE TITLE
Same config, works well on training/test, but fails in analyze_results

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mmdetection#8095]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Same config, works well on training/test, but fails in analyze_results

**Reproduction**

1. What command or script did you run?

```bash
file_client_args = dict(backend='disk')
load_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(xxxx, xxxx), keep_ratio=True),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(0.01, 0.01)),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Pad', size_divisor=32)
]
train_pipeline = [
    dict(type='CopyPaste', max_num_pasted=100),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(xxxx, xxxx),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='MultiImageMixDataset',
        dataset=dict(
            type='CocoDataset',
            ann_file='data/train.json',
            img_prefix='data/train',
            pipeline=[
                dict(
                    type='LoadImageFromFile',
                    file_client_args=dict(backend='disk')),
                dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
                dict(type='Resize', img_scale=(1920, 1080), keep_ratio=True),
                dict(type='FilterAnnotations', min_gt_bbox_wh=(0.01, 0.01)),
                dict(type='RandomFlip', flip_ratio=0.5),
                dict(type='Pad', size_divisor=32)
            ]),
        pipeline=[
            dict(type='CopyPaste', max_num_pasted=100),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ]),
    val=dict(
        type='CocoDataset',
        ann_file='data/val.json',
        img_prefix='data/val',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(xxxx, xxxx),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        ann_file='data/val.json',
        img_prefix='data/val',
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(xxxx, xxxx),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I change the coco datasets into my own

3. What dataset did you use?
My own datasets with standard coco format.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
Traceback (most recent call last):
  File "tools/analysis_tools/analyze_results.py", line 210, in <module>
    main()
  File "tools/analysis_tools/analyze_results.py", line 199, in main
    cfg.data.test.pipeline = get_loading_pipeline(cfg.data.train.pipeline)
  File "/home/tiger/.local/lib/python3.7/site-packages/mmdet/datasets/utils.py", line 112, in get_loading_pipeline
    'The data pipeline in your config file must include ' \
AssertionError: The data pipeline in your config file must include loading image and annotations related pipeline.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by hhaAndroid** [comment]
@mitming This bug has been fixed in https://github.com/open-mmlab/mmdetection/pull/7922, please update the code

**Comment by mitming** [comment]
> @mitming This bug has been fixed in #7922, please update the code

Thanks a lot
