### ISSUE TITLE
SSD512: TypeError: __init__() got an unexpected keyword argument 'momentum'

### ISSUE THREAD

**Issue by JeanD1983** [open-mmlab/mmdetection#8123]
**Describe the bug**
I trained a SSD512 network with `python tools/train.py configs/ssd/BrickSim_SSD512.py ` 
this error did not appear.  

When running it distributed it pops up.
`bash ./tools/dist_train.sh configs/Brick_CNNs/SSD_Strict.py 8`

Error:
`Traceback (most recent call last):
  File "/mnt/fourth/students/debinski/mmdetection/./tools/train.py", line 209, in <module>
    main()
  File "/mnt/fourth/students/debinski/mmdetection/./tools/train.py", line 198, in main
    train_detector(
  File "/mnt/fourth/students/debinski/mmdetection/mmdet/apis/train.py", line 126, in train_detector
    optimizer = build_optimizer(model, cfg.optimizer)
  File "/mnt/fourth/students/debinski/.conda/envs/mmdetection/lib/python3.9/site-packages/mmcv/runner/optimizer/builder.py", line 43, in build_optimizer
    optimizer = optim_constructor(model)
  File "/mnt/fourth/students/debinski/.conda/envs/mmdetection/lib/python3.9/site-packages/mmcv/runner/optimizer/default_constructor.py", line 243, in __call__
    return build_from_cfg(optimizer_cfg, OPTIMIZERS)
  File "/mnt/fourth/students/debinski/.conda/envs/mmdetection/lib/python3.9/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: AdamW: __init__() got an unexpected keyword argument 'momentum'`

4. What dataset did you use?

My config file using my own created dataset:
`_base_ = "/mnt/fourth/students/debinski/mmdetection/configs/ssd/ssd300_coco.py"
input_size = 512
model = dict(
    neck=dict(
        out_channels=(512, 1024, 512, 256, 256, 256, 256),
        level_strides=(2, 2, 2, 2, 1),
        level_paddings=(1, 1, 1, 1, 1),
        last_kernel_size=4),
    bbox_head=dict(
        num_classes = 222, 
        in_channels=(512, 1024, 512, 256, 256, 256, 256),
        anchor_generator=dict(
            type='SSDAnchorGenerator',
            scale_major=False,
            input_size=input_size,
            basesize_ratio_range=(0.1, 0.9),
            strides=[8, 16, 32, 64, 128, 256, 512],
            ratios=[[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]])))
# learning policy
runner = dict(type='EpochBasedRunner', max_epochs=24)
evaluation = dict(interval=1, save_best="bbox_mAP", metric=["bbox"])
# checkpoint settings
checkpoint_config = dict(interval=1, max_keep_ckpts=5)

# load or resume from pretrained model
load_from = "checkpoints/ssd512_coco_20210803_022849-0a47a1ca.pth"
# dataset settings
dataset_type = 'CocoDataset'
data_root = "/mnt/third/jean/"
classes = ("11055","11090","11211","11212","11458","11477","13269uv","14716","14719","15068","15535",
    "15535uv","15573","15712","17457","18626","18677","22385","2357","23950","2412",
    "2412v2","2420","24299","24307","24309","2431","2444","24445","2540","2555","26047","26169","2653",
    "2654v2","26603","26604","2723","2730","28192","2871","2877","2878","29084p2","29085",
    "29120","2920","2921","2922","30000","3001","3002","3003","30031","3004","3005","3007","3008","3009","3010","30162","30165",
    "3020","3021","3022","3023","3024","3028","3029","3030","3031","3032","3033","3034","3035","30350","30357","3036","30374","30377",
    "3039","3040","30414","30552","3065","3066","3068","3069","3070","31593","3176","32028",
    "32064","32084","32123","32187","32270","32293","32324","33078","33909","3460","3622","3623",
    "3626v2uv","3626v3","3633","3659","3666","3679","3680","3701","3704","3706","3710",
    "3743","3747","3794","3794v2","3795","3819v2","3820v2","3832","3839v2","3937",
    "3956","4070","4073","4083","4085v2","41092","4150","4162","41677","41740","4175","4185",
    "42506","4275","42918","43719","44237","44728","4477","44860","44861","4510","45677",
    "4593","4599v2","47905","48336","4865v1","48729","50950","51739","52501","53451","54200","5505","55053",
    "55423","55423p2","57878","60474","60478","60479","60485","60675","60676","60897","6091",
    "6111","6112","61252","61409","61678","6179","6191","6212","6231","62360uv","62462","6266","63864","63965",
    "6541","65458","6558","6587","6632","6636","71075","73092","7627","76270","76279","76292",
    "7638","85544","85557","85558","85861","85984","87079","87079UV","87087","87994",
    "90258","90540","92280","92339","92946","93094","93273","93274","95820","98138",
    "98368","99021","99206","99780")

img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[1, 1, 1], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile', to_float32=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PhotoMetricDistortion',
        brightness_delta=32,
        contrast_range=(0.5, 1.5),
        saturation_range=(0.5, 1.5),
        hue_delta=18),
    dict(
        type='Expand',
        mean=img_norm_cfg['mean'],
        to_rgb=img_norm_cfg['to_rgb'],
        ratio_range=(1, 4)),
    dict(
        type='MinIoURandomCrop',
        min_ious=(0.1, 0.3, 0.5, 0.7, 0.9),
        min_crop_size=0.3),
    dict(type='Resize', img_scale=(512, 512), keep_ratio=False),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=False),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=44,
    workers_per_gpu=16,
    train=dict(
        _delete_=True,
        type='RepeatDataset',
        times=5,
        dataset=dict(
            type=dataset_type,
            classes = classes,
            ann_file=data_root + 'dataset/annotations/train_2.json',
            img_prefix=data_root + 'dataset/',
            pipeline=train_pipeline)),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'dataset/annotations/val_2.json',
        img_prefix=data_root + "dataset/",
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'dataset/annotations/test_2.json',
        img_prefix=data_root + "dataset/",
        pipeline=test_pipeline))
# optimizer
optimizer = dict(type='AdamW', lr=2e-3, momentum=0.9, 
  weight_decay=5e-4)
optimizer_config = dict(_delete_=True)
custom_hooks = [
    dict(type='NumClassCheckHook'),
    dict(type='CheckInvalidLossHook', interval=50, priority='VERY_LOW')
]

work_dir = '/mnt/third/jean/work_dir/SSD512'
`

**Comment by JeanD1983** [comment]
GOT IT! Commented out the `optimizer = dict(type='AdamW', lr=2e-3, momentum=0.9,
weight_decay=5e-4)` and changed SGD to AdamW in the base file of ssd30_coco.py.
