### ISSUE TITLE
solov2 error: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 136, 328]

### ISSUE THREAD

**Issue by star379814385** [open-mmlab/mmdetection#8159]
a error in solov2.head.py line733
keep_inds may be [] after mask_matrix_nms, mask_preds.shape[0] may be 0, which can not be used in F.interpolate.

Traceback (most recent call last):
  File "D:/project/0_PanopticSeg/mmdetection-2.25.0/custom_tools/scripts/vis_from_mmdet_infer.py", line 50, in <module>
    result = inference_detector(model, img)
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\apis\inference.py", line 151, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "D:\winPrpgram\anaconda3\envs\mmdet38\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\winPrpgram\anaconda3\envs\mmdet38\lib\site-packages\mmcv\runner\fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\models\detectors\single_stage_instance_seg.py", line 175, in simple_test
    results_list = self.mask_head.simple_test(
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\models\dense_heads\base_mask_head.py", line 107, in simple_test
    results_list = self.get_results(
  File "D:\winPrpgram\anaconda3\envs\mmdet38\lib\site-packages\mmcv\runner\fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\mmdet\models\dense_heads\solov2_head.py", line 622, in get_results
    result = self._get_results_single(
  File "D:\project\0_PanopticSeg\mmdetection-2.25.0\custom_modules\qiti_solov2_head.py", line 126, in _get_results_single
    mask_preds = F.interpolate(
  File "D:\winPrpgram\anaconda3\envs\mmdet38\lib\site-packages\torch\nn\functional.py", line 3919, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 136, 328]

**Comment by BIGWangYuDong** [comment]
Thanks for your report, we will have a check and fix ASAP

**Comment by BIGWangYuDong** [comment]
@star379814385 if the mask_pred.shape[0] = 0, we will return an empty_results, 
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#L708-L713

So more details need be reported, what code did you change?

**Comment by zhanggefan** [comment]
It might be a bug. The code can still reach line 733 with empty mask when `test_cfg.filter_thr` is set to be sufficiently high, which triggers the error. 
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#L722-L733
The solution is to add another protection branch to bypass the mask upsampling code when `keep_inds` is empty.
