### ISSUE TITLE
Why do you host the model zoo on AWS

### ISSUE THREAD

**Issue by andeyeluguo** [open-mmlab/mmdetection#816]
Downloading models from AWS is slow to me, could you provide a mirror on the cloud storage of Baidu or Tencent?

**Comment by hellock** [comment]
Please use English for issues.

1. BaiduYun or Tencent Cloud are too slow for us
2. They do not provide direct links.

We also provide a mirror on Aliyun, please refer to the [MODEL ZOO](https://github.com/open-mmlab/mmdetection/blob/master/MODEL_ZOO.md#mirror-sites). However, it is sometimes very slow to upload the models, so some recent models are still not synchronized.

**Comment by suranliunian** [comment]
~/mmdetection$ python tools/train.py configs/cascade_rcnn_x101_32x4d_fpn_1x.py --validate
2019-07-25 10:13:28,296 - INFO - Distributed training: False
2019-07-25 10:13:30,073 - INFO - load model from: open-mmlab://resnext101_32x4d
Downloading: "https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d-a5af3160.pth" to /home/yaping/.cache/torch/checkpoints/resnext101_32x4d-a5af3160.pth
Traceback (most recent call last):
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 76, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/yaping/mmdetection/mmdet/models/builder.py", line 43, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/yaping/mmdetection/mmdet/models/builder.py", line 15, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/yaping/mmdetection/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
  File "/home/yaping/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 86, in __init__
    self.init_weights(pretrained=pretrained)
  File "/home/yaping/mmdetection/mmdet/models/detectors/cascade_rcnn.py", line 94, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/home/yaping/mmdetection/mmdet/models/backbones/resnet.py", line 484, in init_weights
    load_checkpoint(self, pretrained, strict=False, logger=logger)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 140, in load_checkpoint
    checkpoint = load_url_dist(open_mmlab_model_urls[model_name])
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 99, in load_url_dist
    checkpoint = model_zoo.load_url(url)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/hub.py", line 433, in load_state_dict_from_url
    _download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/site-packages/torch/hub.py", line 349, in _download_url_to_file
    u = urlopen(url)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

sad!

**Comment by xxllp** [comment]
bad

**Comment by nwf5d** [comment]
model zoo on BaiduYun：
链接：https://pan.baidu.com/s/1k72QpgXPDEx92Gdyjs6PjA 
提取码：etub

**Comment by guotong1988** [comment]
@nwf5d 
Thank you.
Why not ALL of them?
