### ISSUE TITLE
facing index out of range during training on custom classes coco dataset

### ISSUE THREAD

**Issue by AhmadIbtehaj** [open-mmlab/mmdetection#8160]
2022-06-09 18:43:38,315 - mmdet - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/5000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/apis/train.py", line 185, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/core/evaluation/eval_hooks.py", line 276, in after_train_epoch
    gpu_collect=self.gpu_collect)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/apis/test.py", line 97, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ibtehaj/anaconda3/envs/lab2/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/detectors/base.py", line 160, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/detectors/two_stage.py", line 204, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/roi_heads/standard_roi_head.py", line 267, in simple_test
    x, img_metas, det_bboxes, det_labels, rescale=rescale)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/roi_heads/test_mixins.py", line 319, in simple_test_mask
    ori_shapes[i], scale_factors[i], rescale)
  File "/home/ibtehaj/Documents/ibtehaj/vision/Swin-Transformer-Object-Detection/mmdet/models/roi_heads/mask_heads/fcn_mask_head.py", line 302, in get_seg_masks
    cls_segms[labels[i]].append(im_mask[i].detach().cpu().numpy())
IndexError: list index out of range

**Comment by RangiLyu** [comment]
You need to change num_classes to the number of classes in your dataset.
