### ISSUE TITLE
ValueError: cannot reshape array of size 65010176 into shape (1088,800)

### ISSUE THREAD

**Issue by David-Biggs** [open-mmlab/mmdetection#8167]
Hi there, thanks for this amazing platform.

I am training models on my custom COCO dataset. I had success in both object detection and instance segmentation until I updated my validation dataset. Now I get the errors below when I train an instance seg. models. When I train an object detection model it all works. 

`ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdetection/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdetection/mmdet/datasets/custom.py", line 241, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/content/mmdetection/mmdetection/mmdet/datasets/pipelines/transforms.py", line 665, in __call__
    self._pad_masks(results)
  File "/content/mmdetection/mmdetection/mmdet/datasets/pipelines/transforms.py", line 645, in _pad_masks
    results[key] = results[key].pad(pad_shape, pad_val=pad_val)
  File "/content/mmdetection/mmdetection/mmdet/core/mask/structures.py", line 312, in pad
    return BitmapMasks(padded_masks, *out_shape)
  File "/content/mmdetection/mmdetection/mmdet/core/mask/structures.py", line 235, in __init__
    self.masks = np.stack(masks).reshape(-1, height, width)
ValueError: cannot reshape array of size 65010176 into shape (1088,800)`

Here is a screenshot of where the error is being raised in `structures.py` :

![image](https://user-images.githubusercontent.com/64862726/173038260-3276985d-cc02-4d95-b85f-c7276f6401ea.png)

I found a similar issue #4926. But I think they are unrelated. 

I have checked my dataset in FiftyOne and it seems to be all fine. Here is my validation annotation file. It is originally a .json but I converted it so I could include it here. 
[validation_2022.txt](https://github.com/open-mmlab/mmdetection/files/8877707/validation_2022.txt)

Many thanks,
David

**Comment by BIGWangYuDong** [comment]
you can check the shape of `masks` and `np.stack(masks)` when you meet the error.

**Comment by David-Biggs** [comment]
Hi @BIGWangYuDong ,

Thanks for your responce. 

I managed to find the source of the error. In my custom dataset, one of the image annotations was 'corrupt'. I manually removed each image from the .json file individually, along which its corresponding annotations, to find out which image was causing the problem.

Many thanks

**Comment by alexjiao-chrono** [comment]
@David-Biggs Believe I'm running into a similar error as you. Do you mind sharing how the annotation was "corrupt"?

**Comment by gauravjio** [comment]
@David-Biggs ,

please let me know how did you identified corrupted image annotation, if you have a script please let me know.

**Comment by David-Biggs** [comment]
@alexjiao-chrono 
@gauravjio 

From what I can remember, the 'corrupt' annotations had empty segmentation lists. In the JSON file, a segmentation list for a corrupt image looked like this: ` "segmentation": [[]] `, containing no coordinates. I removed all images with empty annotation lists and it seemed to work.

I hope this helps.
