### ISSUE TITLE
About abs_pos_embed in swin

### ISSUE THREAD

**Issue by Money-HY** [open-mmlab/mmdetection#8187]
When I use Swin as a backbone for my model, I try to use the use_abs_pos_embed in config file but get an error. How to solve this problem.

Detailed information:
sys.platform: linux
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
PyTorch: 1.8.2
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMRotate: 0.3.0+HEAD
------------------------------------------------------------

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
2022-06-15 10:57:41,178 - mmrotate - INFO - Distributed training: True
2022-06-15 10:57:41,601 - mmrotate - INFO - Config:
dataset_type = 'DOTADataset'
data_root = '../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(1024, 1024)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='oc'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1024, 1024),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='DOTADataset',
        ann_file='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/trainval/annfiles/',
        img_prefix='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/trainval/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize', img_scale=(1024, 1024)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='oc'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        version='oc'),
    val=dict(
        type='DOTADataset',
        ann_file='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/val/annfiles/',
        img_prefix='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/val/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='oc'),
    test=dict(
        type='DOTADataset',
        ann_file='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/test/images/',
        img_prefix='../Dataset/DOTA/DOTA1.0/split_ss_dota1_0/test/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1024, 1024),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='oc'))
evaluation = dict(interval=12, metric='mAP')
optimizer = dict(
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys=dict(
            absolute_pos_embed=dict(decay_mult=0.0),
            relative_position_bias_table=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0))))
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=12)
checkpoint_config = dict(interval=12)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
pretrained = '../pretrained/swin/swin_tiny.pth'
angle_version = 'oc'
model = dict(
    type='R3Det',
    backbone=dict(
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.2,
        patch_norm=True,
        use_abs_pos_embed=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(
            type='Pretrained', checkpoint='../pretrained/swin/swin_tiny.pth')),
    neck=dict(
        type='FPN',
        in_channels=[96, 192, 384, 768],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5),
    bbox_head=dict(
        type='RotatedRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        anchor_generator=dict(
            type='RotatedAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHAOBBoxCoder',
            angle_range='oc',
            norm_factor=None,
            edge_swap=False,
            proj_xy=False,
            target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)),
    frm_cfgs=[dict(in_channels=256, featmap_strides=[8, 16, 32, 64, 128])],
    num_refine_stages=1,
    refine_heads=[
        dict(
            type='RotatedRetinaRefineHead',
            num_classes=15,
            in_channels=256,
            stacked_convs=4,
            feat_channels=256,
            assign_by_circumhbbox=None,
            anchor_generator=dict(
                type='PseudoAnchorGenerator', strides=[8, 16, 32, 64, 128]),
            bbox_coder=dict(
                type='DeltaXYWHAOBBoxCoder',
                angle_range='oc',
                norm_factor=None,
                edge_swap=False,
                proj_xy=False,
                target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
                target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0))
    ],
    train_cfg=dict(
        s0=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.4,
                min_pos_iou=0,
                ignore_iof_thr=-1,
                iou_calculator=dict(type='RBboxOverlaps2D')),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        sr=[
            dict(
                assigner=dict(
                    type='MaxIoUAssigner',
                    pos_iou_thr=0.6,
                    neg_iou_thr=0.5,
                    min_pos_iou=0,
                    ignore_iof_thr=-1,
                    iou_calculator=dict(type='RBboxOverlaps2D')),
                allowed_border=-1,
                pos_weight=-1,
                debug=False)
        ],
        stage_loss_weights=[1.0]),
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))
find_unused_parameters = True
work_dir = './work_dirs/r3det_swin_abs_fpn_1x_dota_oc'
auto_resume = False
gpu_ids = range(0, 4)

2022-06-15 10:57:41,604 - mmrotate - INFO - Set random seed to 0, deterministic: False
2022-06-15 10:57:42,102 - mmdet - INFO - load checkpoint from local path: ../pretrained/swin/swin_tiny.pth
2022-06-15 10:57:43,727 - mmrotate - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-06-15 10:57:43,760 - mmrotate - INFO - initialize RotatedRetinaHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'retina_cls', 'std': 0.01, 'bias_prob': 0.01}}
2022-06-15 10:57:43,824 - mmrotate - INFO - initialize RotatedRetinaRefineHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'retina_cls', 'std': 0.01, 'bias_prob': 0.01}}
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
2022-06-15 10:58:16,067 - mmrotate - INFO - Start running, host: sx1904098@gpu03, work_dir: /fs0/home/sx1904098/qhy/mmrotate-main/work_dirs/r3det_swin_abs_fpn_1x_dota_oc
2022-06-15 10:58:16,068 - mmrotate - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) DistSamplerSeedHook                
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(NORMAL      ) DistSamplerSeedHook                
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-06-15 10:58:16,068 - mmrotate - INFO - workflow: [('train', 1)], max: 12 epochs
2022-06-15 10:58:16,069 - mmrotate - INFO - Checkpoints will be saved to /fs0/home/sx1904098/qhy/mmrotate-main/work_dirs/r3det_swin_abs_fpn_1x_dota_oc by HardDiskBackend.
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 192, in <module>
    main()
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 181, in main
    train_detector(
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/apis/train.py", line 141, in train_detector
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 192, in <module>
    main()
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 181, in main
    train_detector(
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/apis/train.py", line 141, in train_detector
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 192, in <module>
Traceback (most recent call last):
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 192, in <module>
    main()
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 181, in main
    train_detector(
      File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/apis/train.py", line 141, in train_detector
main()
  File "/fs0/home/sx1904098/qhy/mmrotate-main/tools/train.py", line 181, in main
    train_detector(
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
runner.run(data_loaders, cfg.workflow)
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
runner.run(data_loaders, cfg.workflow)
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
runner.run(data_loaders, cfg.workflow)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
        epoch_runner(data_loaders[i], **kwargs)    epoch_runner(data_loaders[i], **kwargs)
    epoch_runner(data_loaders[i], **kwargs)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train

epoch_runner(data_loaders[i], **kwargs)  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)    
self.run_iter(data_batch, train_mode=True, **kwargs)      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter

self.run_iter(data_batch, train_mode=True, **kwargs)      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter

self.run_iter(data_batch, train_mode=True, **kwargs)  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 59, in train_step
    outputs = self.model.train_step(data_batch, self.optimizer,
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 59, in train_step
outputs = self.model.train_step(data_batch, self.optimizer,    
outputs = self.model.train_step(data_batch, self.optimizer,  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 59, in train_step

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 59, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 248, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])    output = self.module.train_step(*inputs[0], **kwargs[0])
output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 248, in train_step

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 248, in train_step
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 248, in train_step
        losses = self(**data)    losses = self(**data)    
losses = self(**data)
losses = self(**data)  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
result = self.forward(*input, **kwargs)
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
result = self.forward(*input, **kwargs)    
result = self.forward(*input, **kwargs)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
            return old_func(*args, **kwargs)    return old_func(*args, **kwargs)return old_func(*args, **kwargs)
return old_func(*args, **kwargs)

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 172, in forward

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 172, in forward
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 172, in forward
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)        
    return self.forward_train(img, img_metas, **kwargs)return self.forward_train(img, img_metas, **kwargs)  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 83, in forward_train
return self.forward_train(img, img_metas, **kwargs)

  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 83, in forward_train
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 83, in forward_train
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 83, in forward_train
    x = self.extract_feat(img)    
x = self.extract_feat(img)  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 54, in extract_feat

      File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 54, in extract_feat
    x = self.extract_feat(img)x = self.extract_feat(img)

  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 54, in extract_feat
  File "/fs0/home/sx1904098/qhy/mmrotate-main/mmrotate/models/detectors/r3det.py", line 54, in extract_feat
        x = self.backbone(img)x = self.backbone(img)

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
        x = self.backbone(img)x = self.backbone(img)

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
        result = self.forward(*input, **kwargs)result = self.forward(*input, **kwargs)

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/backbones/swin.py", line 749, in forward
      File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/backbones/swin.py", line 749, in forward
    result = self.forward(*input, **kwargs)result = self.forward(*input, **kwargs)

  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/backbones/swin.py", line 749, in forward
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/mmdet-2.24.0-py3.9.egg/mmdet/models/backbones/swin.py", line 749, in forward
    x = x + self.absolute_pos_embed
        x = x + self.absolute_pos_embedRuntimeError    x = x + self.absolute_pos_embed
: x = x + self.absolute_pos_embed
The size of tensor a (65536) must match the size of tensor b (3136) at non-singleton dimension 1
RuntimeError
RuntimeError: RuntimeError: The size of tensor a (65536) must match the size of tensor b (3136) at non-singleton dimension 1: The size of tensor a (65536) must match the size of tensor b (3136) at non-singleton dimension 1
The size of tensor a (65536) must match the size of tensor b (3136) at non-singleton dimension 1

Traceback (most recent call last):
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/fs0/software/anaconda/3-2020.07/envs/sx1904098/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/fs0/software/anaconda/3-2020.07/envs/sx1904098/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/qhyuse/r3det_swin_abs_fpn_1x_dota_oc.py', '--seed', '0', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by jbwang1997** [comment]
It's a bug. The pr is in progress. https://github.com/open-mmlab/mmdetection/pull/8127
