### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by funny000** [open-mmlab/mmdetection#8193]
when i use mmdet model to train a segmemgent dataset, I have the problem.
and look for the problem in the internet, but not solve it.
so ask the problem in the github,
can you help me?

```
the follow error information:
===================================================
Traceback (most recent call last):
  File "train.py", line 419, in <module>
    train(trainlog)
  File "train.py", line 222, in train
    tout, lout = net(img)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "train.py", line 86, in forward
    out = self.head(out0)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/train/models/head/uper_head.py", line 101, in forward
    laterals.append(self.psp_forward(inputs))
  File "/train/models/head/uper_head.py", line 84, in psp_forward
    psp_outs.extend(self.psp_modules(x))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/train/models/head/psp_head.py", line 52, in forward
    ppm_out = ppm(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/train/models/losses/utils.py", line 144, in forward
    out = self.conv(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)
===================================================
```

**Comment by jbwang1997** [comment]
Maybe this issue can help you. https://github.com/open-mmlab/mmdetection/issues/7231
