### ISSUE TITLE
meet an error when convert TOOD pth to onnx

### ISSUE THREAD

**Issue by Liuhongmiao** [open-mmlab/mmdetection#8201]
when I run pytorch2onnx.py to convert TOOD model with deformable conv layer.

the environment is:
```
2022-06-16 11:18:47,704 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.5 (default, Mar  4 2021, 15:06:06) [GCC 9.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2060
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu110
OpenCV: 4.1.2
MMCV: 1.4.3
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.23.0+2c16184

```

The error I got is like this:
```
tools/deployment/pytorch2onnx.py:299: UserWarning: Arguments like `--mean`, `--std`, `--dataset` would be         parsed directly from config file and are deprecated and         will be removed in future releases.
  will be removed in future releases.')
load checkpoint from local path: output_models/XHM/tood_daAtten_XHM3.0_withNormal_epoch_120.pth
2022-06-16 11:00:04,858 - root - INFO - ModulatedDeformConvPack backbone.layer2.0.conv2 is upgraded to version 2.
2022-06-16 11:00:04,860 - root - INFO - ModulatedDeformConvPack backbone.layer2.1.conv2 is upgraded to version 2.
2022-06-16 11:00:04,862 - root - INFO - ModulatedDeformConvPack backbone.layer2.2.conv2 is upgraded to version 2.
2022-06-16 11:00:04,863 - root - INFO - ModulatedDeformConvPack backbone.layer2.3.conv2 is upgraded to version 2.
2022-06-16 11:00:04,864 - root - INFO - ModulatedDeformConvPack backbone.layer3.0.conv2 is upgraded to version 2.
2022-06-16 11:00:04,866 - root - INFO - ModulatedDeformConvPack backbone.layer3.1.conv2 is upgraded to version 2.
2022-06-16 11:00:04,868 - root - INFO - ModulatedDeformConvPack backbone.layer3.2.conv2 is upgraded to version 2.
2022-06-16 11:00:04,870 - root - INFO - ModulatedDeformConvPack backbone.layer3.3.conv2 is upgraded to version 2.
2022-06-16 11:00:04,871 - root - INFO - ModulatedDeformConvPack backbone.layer3.4.conv2 is upgraded to version 2.
2022-06-16 11:00:04,873 - root - INFO - ModulatedDeformConvPack backbone.layer3.5.conv2 is upgraded to version 2.
2022-06-16 11:00:04,875 - root - INFO - ModulatedDeformConvPack backbone.layer3.6.conv2 is upgraded to version 2.
2022-06-16 11:00:04,876 - root - INFO - ModulatedDeformConvPack backbone.layer3.7.conv2 is upgraded to version 2.
2022-06-16 11:00:04,878 - root - INFO - ModulatedDeformConvPack backbone.layer3.8.conv2 is upgraded to version 2.
2022-06-16 11:00:04,880 - root - INFO - ModulatedDeformConvPack backbone.layer3.9.conv2 is upgraded to version 2.
2022-06-16 11:00:04,881 - root - INFO - ModulatedDeformConvPack backbone.layer3.10.conv2 is upgraded to version 2.
2022-06-16 11:00:04,884 - root - INFO - ModulatedDeformConvPack backbone.layer3.11.conv2 is upgraded to version 2.
2022-06-16 11:00:04,886 - root - INFO - ModulatedDeformConvPack backbone.layer3.12.conv2 is upgraded to version 2.
2022-06-16 11:00:04,889 - root - INFO - ModulatedDeformConvPack backbone.layer3.13.conv2 is upgraded to version 2.
2022-06-16 11:00:04,891 - root - INFO - ModulatedDeformConvPack backbone.layer3.14.conv2 is upgraded to version 2.
2022-06-16 11:00:04,892 - root - INFO - ModulatedDeformConvPack backbone.layer3.15.conv2 is upgraded to version 2.
2022-06-16 11:00:04,894 - root - INFO - ModulatedDeformConvPack backbone.layer3.16.conv2 is upgraded to version 2.
2022-06-16 11:00:04,896 - root - INFO - ModulatedDeformConvPack backbone.layer3.17.conv2 is upgraded to version 2.
2022-06-16 11:00:04,898 - root - INFO - ModulatedDeformConvPack backbone.layer3.18.conv2 is upgraded to version 2.
2022-06-16 11:00:04,899 - root - INFO - ModulatedDeformConvPack backbone.layer3.19.conv2 is upgraded to version 2.
2022-06-16 11:00:04,901 - root - INFO - ModulatedDeformConvPack backbone.layer3.20.conv2 is upgraded to version 2.
2022-06-16 11:00:04,903 - root - INFO - ModulatedDeformConvPack backbone.layer3.21.conv2 is upgraded to version 2.
2022-06-16 11:00:04,906 - root - INFO - ModulatedDeformConvPack backbone.layer3.22.conv2 is upgraded to version 2.
2022-06-16 11:00:04,909 - root - INFO - ModulatedDeformConvPack backbone.layer4.0.conv2 is upgraded to version 2.
2022-06-16 11:00:04,914 - root - INFO - ModulatedDeformConvPack backbone.layer4.1.conv2 is upgraded to version 2.
2022-06-16 11:00:04,917 - root - INFO - ModulatedDeformConvPack backbone.layer4.2.conv2 is upgraded to version 2.
2022-06-16 11:00:04,928 - root - INFO - ModulatedDeformConvPack bbox_head.inter_convs.0.conv is upgraded to version 2.
2022-06-16 11:00:04,930 - root - INFO - ModulatedDeformConvPack bbox_head.inter_convs.1.conv is upgraded to version 2.
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/modulated_deform_conv.py:147: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not all(map(lambda s: s > 0, output_size)):
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/modulated_deform_conv.py:93: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  with_bias=ctx.with_bias)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/tood_head.py:233: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  anchor = torch.cat([anchor for _ in range(b)])
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py:182: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not all(map(lambda s: s > 0, output_size)):
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py:89: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cur_im2col_step = min(ctx.im2col_step, input.size(0))
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py:91: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  ) == 0, 'batch size must be divisible by im2col_step'
/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py:109: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  im2col_step=cur_im2col_step)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/base_dense_head.py:416: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cfg.get('nms_pre', -1), device=device, dtype=torch.long)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/base_dense_head.py:436: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:63: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if k <= 0 or size <= 0:
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/base_dense_head.py:457: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre > 0:
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/base_dense_head.py:472: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  _, topk_inds = max_scores.topk(nms_pre)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:90: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(0) == bboxes.size(0)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/bbox/coder/delta_xywh_bbox_coder.py:92: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert pred_bboxes.size(1) == bboxes.size(1)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:119: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  iou_threshold = torch.tensor([iou_threshold], dtype=torch.float32)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:120: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  score_threshold = torch.tensor([score_threshold], dtype=torch.float32)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:124: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  nms_pre = torch.tensor(pre_top_k, device=scores.device, dtype=torch.long)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:148: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  batch_inds = torch.randint(batch_size, (num_fake_det, 1))
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:149: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cls_inds = torch.randint(num_class, (num_fake_det, 1))
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:150: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  box_inds = torch.randint(num_box, (num_fake_det, 1))
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:181: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  after_top_k, device=scores.device, dtype=torch.long)
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:184: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_after > 0:
/home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/core/export/onnx_helper.py:185: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  _, topk_inds = scores.topk(nms_after)
Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 345, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 100, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 421, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 268, in _run_symbolic_method
    return utils._run_symbolic_method(*args, **kwargs)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 723, in _run_symbolic_method
    return symbolic_fn(*args)
  File "/home/liuhm/.local/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 47, in symbolic
    im2col_step_i=im2col_step)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 829, in _graph_op
    n = g.insertNode(_newNode(g, opname, outputs, *args, **kwargs))
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 782, in _newNode
    _add_attribute(n, k, v, aten=aten)
  File "/home/liuhm/.local/lib/python3.7/site-packages/torch/onnx/utils.py", line 760, in _add_attribute
    return getattr(node, kind + "_")(name, value)
TypeError: i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

Invoked with: %4714 : Tensor = mmcv::MMCVDeformConv2d[bias=0](%4674, %4697, %4713)
, 'deform_groups', 4704 defined in (%4704 : Long(device=cpu) = onnx::Gather[axis=0](%4701, %4703) # /home/liuhm/workspace/CODING_project/YFZX_AIResearch_MMDetection/mmdet/models/dense_heads/tood_head.py:283:0
) (occurred when translating DeformConv2dFunction)
```

Any help is appreciated!

**Comment by RangiLyu** [comment]
TOOD currently does not support converting to ONNX. And the pytorch2onnx.py has been deprecated. Please use MMDeploy instead. https://github.com/open-mmlab/mmdeploy

**Comment by Liuhongmiao** [comment]
> TOOD currently does not support converting to ONNX. And the pytorch2onnx.py has been deprecated. Please use MMDeploy instead. https://github.com/open-mmlab/mmdeploy

Ok! I have noticed the MMDeploy. And I'm trying to work with it. Maybe add tood_head.py can help support TOOD. I'm not sure. Would you please give some more information. Thank you! @RangiLyu

**Comment by Liuhongmiao** [comment]
Thank you. I will add tood and debug it.
