### ISSUE TITLE
Getting something wrong when training config file `/root/mmdetection/configs/convnext/mask_rcnn_convnext-t_p4_w7_fpn_fp16_ms-crop_3x_coco.py`

### ISSUE THREAD

**Issue by Atlantisming** [open-mmlab/mmdetection#8202]
Hi, I tried to replace the backbone of detr to convnext, And I got some mistake when I training the config file.

**Describe the bug**
So I back to training the demo config file `/root/mmdetection/configs/convnext/mask_rcnn_convnext-t_p4_w7_fpn_fp16_ms-crop_3x_coco.py`
but got the same wrong.
```
Traceback (most recent call last):
  File "mmdetection/tools/train.py", line 242, in <module>
    main()
  File "mmdetection/tools/train.py", line 238, in main
    meta=meta)
  File "/root/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/.local/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 41, in train
    self.model.train()
  File "/root/.local/conda/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1277, in train
    module.train(mode)
  File "/root/.local/conda/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1277, in train
    module.train(mode)
  File "/root/.local/lib/python3.7/site-packages/mmcls/models/backbones/convnext.py", line 333, in train
    if mode and self.norm_eval:             
  File "/root/.local/conda/envs/openmmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'ConvNeXt' object has no attribute 'norm_eval'
```
This config file can run the test.py but get mistake when running train.py
**Reproduction**

1. What command or script did you run?
I run this command `python mmdetection/tools/train.py mmdetection/configs/convnext/mask_rcnn_convnext-t_p4_w7_fpn_fp16_ms-crop_3x_coco.py`

```
python mmdetection/tools/train.py mmdetection/configs/convnext/mask_rcnn_convnext-t_p4_w7_fpn_fp16_ms-crop_3x_coco.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I didn't make any modification in the config file. Here's the config file
```
_base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

# please install mmcls>=0.22.0
# import mmcls.models to trigger register_module in mmcls
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)
checkpoint_file = 'mmdetection/checkpoints/mask_rcnn_convnext-t_p4_w7_fpn_fp16_ms-crop_3x_coco_20220426_154953-050731f4.pth'  # noqa

model = dict(
    backbone=dict(
        _delete_=True,
        type='mmcls.ConvNeXt',
        arch='tiny',
        out_indices=[0, 1, 2, 3],
        drop_path_rate=0.4,
        layer_scale_init_value=1.0,
        gap_before_final_norm=False,
        init_cfg=dict(
            type='Pretrained', checkpoint=checkpoint_file,
            prefix='backbone.')),
    neck=dict(in_channels=[96, 192, 384, 768]))

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

# augmentation strategy originates from DETR / Sparse RCNN
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='AutoAugment',
        policies=[[
            dict(
                type='Resize',
                img_scale=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                           (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                           (736, 1333), (768, 1333), (800, 1333)],
                multiscale_mode='value',
                keep_ratio=True)
        ],
                  [
                      dict(
                          type='Resize',
                          img_scale=[(400, 1333), (500, 1333), (600, 1333)],
                          multiscale_mode='value',
                          keep_ratio=True),
                      dict(
                          type='RandomCrop',
                          crop_type='absolute_range',
                          crop_size=(384, 600),
                          allow_negative_crop=True),
                      dict(
                          type='Resize',
                          img_scale=[(480, 1333), (512, 1333), (544, 1333),
                                     (576, 1333), (608, 1333), (640, 1333),
                                     (672, 1333), (704, 1333), (736, 1333),
                                     (768, 1333), (800, 1333)],
                          multiscale_mode='value',
                          override=True,
                          keep_ratio=True)
                  ]]),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks']),
]
data = dict(train=dict(pipeline=train_pipeline), persistent_workers=True)

optimizer = dict(
    _delete_=True,
    constructor='LearningRateDecayOptimizerConstructor',
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg={
        'decay_rate': 0.95,
        'decay_type': 'layer_wise',
        'num_layers': 6
    })

lr_config = dict(warmup_iters=1000, step=[27, 33])
runner = dict(max_epochs=36)

# you need to set mode='dynamic' if you are using pytorch<=1.5.0
fp16 = dict(loss_scale=dict(init_scale=512))
```
3. What dataset did you use?
I used the coco2017 datasets
**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla V100S-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.1
OpenCV: 4.6.0
MMCV: 1.5.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.25.0+
```
Thanks!
**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
What's your mmclassification's version? Please make the version of mmcls >= 0.22.0

**Comment by Atlantisming** [comment]
> What's your mmclassification's version? Please make the version of mmcls >= 0.22.0
Thanks!
Sorry for late reply.
I checked the mmcls.__version__ is
```
>>> import mmcls
>>> print(mmcls.__version__)
0.23.1
```

But still have this problem
```
torch.nn.modules.module.ModuleAttributeError: 'ConvNeXt' object has no attribute 'norm_eval'
```
I will try to reinstall the mmcls and reply later

**Comment by Atlantisming** [comment]
> What's your mmclassification's version? Please make the version of mmcls >= 0.22.0

So I reinstall the mmcls as followed:
```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/, https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///root/mmclassification
Requirement already satisfied: matplotlib in /root/.local/lib/python3.7/site-packages (from mmcls==0.23.1) (3.5.2)
Requirement already satisfied: numpy in /root/.local/lib/python3.7/site-packages (from mmcls==0.23.1) (1.21.6)
Requirement already satisfied: packaging in /root/.local/lib/python3.7/site-packages (from mmcls==0.23.1) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /root/.local/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in /root/.local/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (4.33.3)
Requirement already satisfied: pyparsing>=2.2.1 in /root/.local/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (3.0.9)
Requirement already satisfied: cycler>=0.10 in /root/.local/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /root/.local/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (1.4.2)
Requirement already satisfied: pillow>=6.2.0 in /root/.local/conda/envs/openmmlab/lib/python3.7/site-packages (from matplotlib->mmcls==0.23.1) (9.0.1)
Requirement already satisfied: typing-extensions in /root/.local/conda/envs/openmmlab/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->mmcls==0.23.1) (4.1.1)
Requirement already satisfied: six>=1.5 in /root/.local/conda/envs/openmmlab/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib->mmcls==0.23.1) (1.16.0)
Installing collected packages: mmcls
  Attempting uninstall: mmcls
    Found existing installation: mmcls 0.23.1
    Uninstalling mmcls-0.23.1:
      Successfully uninstalled mmcls-0.23.1
  Running setup.py develop for mmcls
Successfully installed mmcls
```

and didn't meet the error.
Thanks.
