### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by PakizaArhamsoft** [open-mmlab/mmdetection#8204]
EOFError                                  Traceback (most recent call last)
/tmp/ipykernel_60391/991485170.py in <module>
----> 1 train_detector(model, datasets[0], cfg, distributed=False, validate=True)

~/Machine Learning/MMCV/mmdetection/mmdet/apis/train.py in train_detector(model, dataset, cfg, distributed, validate, timestamp, meta)
    241         runner.resume(cfg.resume_from)
    242     elif cfg.load_from:
--> 243         runner.load_checkpoint(cfg.load_from)
    244     runner.run(data_loaders, cfg.workflow)

~/.local/lib/python3.8/site-packages/mmcv/runner/base_runner.py in load_checkpoint(self, filename, map_location, strict, revise_keys)
    337                         strict=False,
    338                         revise_keys=[(r'^module.', '')]):
--> 339         return load_checkpoint(
    340             self.model,
    341             filename,

~/.local/lib/python3.8/site-packages/mmcv/runner/checkpoint.py in load_checkpoint(model, filename, map_location, strict, logger, revise_keys)
    615         dict or OrderedDict: The loaded checkpoint.
    616     """
--> 617     checkpoint = _load_checkpoint(filename, map_location, logger)
    618     # OrderedDict is a subclass of dict
    619     if not isinstance(checkpoint, dict):

~/.local/lib/python3.8/site-packages/mmcv/runner/checkpoint.py in _load_checkpoint(filename, map_location, logger)
    550            information, which depends on the checkpoint.
    551     """
--> 552     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
    553 
    554 
~/.local/lib/python3.8/site-packages/mmcv/runner/checkpoint.py in load_checkpoint(cls, filename, map_location, logger)
    297         mmcv.print_log(
    298             f'load checkpoint from {class_name[10:]} path: {filename}', logger)
--> 299         return checkpoint_loader(filename, map_location)
    300 
    301 

~/.local/lib/python3.8/site-packages/mmcv/runner/checkpoint.py in load_from_local(filename, map_location)
    316     if not osp.isfile(filename):
    317         raise FileNotFoundError(f'{filename} can not be found.')
--> 318     checkpoint = torch.load(filename, map_location=map_location)
    319     return checkpoint
    320 

~/.local/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    593                     return torch.jit.load(opened_file)
    594                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 595         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    596 
    597 

~/.local/lib/python3.8/site-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    762             "functionality.")
    763 
--> 764     magic_number = pickle_module.load(f, **pickle_load_args)
    765     if magic_number != MAGIC_NUMBER:
    766         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input

**Comment by Lewis-Lu** [comment]
Is there any updates on this issue ?

Traceback (most recent call last):
  File "./tools/test.py", line 5, in <module>
    import mmcv
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 3, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/mmcv/utils/config.py", line 17, in <module>
    from yapf.yapflib.yapf_api import FormatCode
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf/__init__.py", line 41, in <module>
    from yapf.yapflib import yapf_api
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf/yapflib/yapf_api.py", line 39, in <module>
    from yapf.pyparser import pyparser
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf/pyparser/pyparser.py", line 44, in <module>
    from yapf.yapflib import format_token
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf/yapflib/format_token.py", line 23, in <module>
    from yapf.pytree import pytree_utils
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf/pytree/pytree_utils.py", line 30, in <module>
    from yapf_third_party._ylib2to3 import pygram
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pygram.py", line 29, in <module>
    python_grammar = driver.load_grammar(_GRAMMAR_FILE)
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/driver.py", line 252, in load_grammar
    g.load(gp)
  File "/data_ssd/hlu/miniconda3/envs/uniad/lib/python3.8/site-packages/yapf_third_party/_ylib2to3/pgen2/grammar.py", line 95, in load
    d = pickle.load(f)
EOFError: Ran out of input
