### ISSUE TITLE
delta2bbox index out of  bound

### ISSUE THREAD

**Issue by soon-yau** [open-mmlab/mmdetection#821]
Got "index out of bounds" error 
in line
```
def delta2bbox(rois,
               deltas,
               means=[0, 0, 0, 0],
               stds=[1, 1, 1, 1],
               max_shape=None,
               wh_ratio_clip=16 / 1000):
    means = deltas.new_tensor(means).repeat(1, deltas.size(1) // 4)
```
called from
```
            proposals = delta2bbox(anchors, rpn_bbox_pred, self.target_means,
                                   self.target_stds, img_shape)
```

I suspect that rpn_bbox_pred's size is wrong. I use custome dataset, so it might be something wrong with my data, any idea how to debug?

```
/opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::operator()(int)->auto: block: [11,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "./tools/train.py", line 98, in <module>
    main()
  File "./tools/train.py", line 94, in main
    logger=logger)
  File "/home/ubuntu/github/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/ubuntu/github/mmdetection/mmdet/apis/train.py", line 171, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mmcv-0.2.8-py3.6.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mmcv-0.2.8-py3.6.egg/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/github/mmdetection/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)   
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/mmcv-0.2.8-py3.6.egg/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/github/mmdetection/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/ubuntu/github/mmdetection/mmdet/models/detectors/two_stage.py", line 114, in forward_train
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/ubuntu/github/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 218, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/ubuntu/github/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 83, in get_bboxes_single
    self.target_stds, img_shape)
  File "/home/ubuntu/github/mmdetection/mmdet/core/bbox/transforms.py", line 40, in delta2bbox
    means = deltas.new_tensor(means).repeat(1, deltas.size(1) // 4)
RuntimeError: CUDA error: device-side assert triggered

```

**Comment by gittigxuy** [comment]
Same problem,have you solve it?

**Comment by 651juan** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by xunhen** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by JSchapke** [comment]
This might be due to exploding gradients. Try lowering the learning rate.

**Comment by qianjinhao** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by qianjinhao** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by PanJianning** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by sunpeng1996** [comment]
I'm having the same issue! Does anyone have a solution?

**Comment by xmyqsh** [comment]
try:
    means = deltas.new_tensor(means).repeat(1, deltas.size(1) // 4)
except:
    print(deltas.size(1), deltas.size(1) // 4)
    assert 0

**Comment by hellock** [comment]
@651juan Hi, we plan to upload packages to pypi, could you transfer the ownership of [mmdet](https://pypi.org/project/mmdet/) to the user `openmmlab`?
