### ISSUE TITLE
Data Registration

### ISSUE THREAD

**Issue by ZahraAnam** [open-mmlab/mmdetection#8211]
Dear MMDetection Team,
First I really appreciate your work of bringing everything at one place and helping the community.

My question might be very simple, but is it possible to explain the process of adding Custom Data a little more??
Specially how can it be registered coz I face xxxDataset not in registry and I haven't found anything well descriptive.
will be great help.

**Comment by BIGWangYuDong** [comment]
you need to add your own Dataset in /datasets/__init__.py, also you cannot install by pip install mmdet, you should install from the source code.

**Comment by ZahraAnam** [comment]
I have a confusion that do I need to build/install again after adding my
dataset??

**Comment by ZahraAnam** [comment]
Now I get the following error: 
Traceback (most recent call last):
  File "/home/anam_zahra/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'times'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 218, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/anam_zahra/Codes/mmdetection/mmdet/datasets/builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/anam_zahra/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset: __init__() got an unexpected keyword argument 'times'

**Comment by ZahraAnam** [comment]
I have customized data as per this example https://mmdetection.readthedocs.io/en/latest/tutorials/customize_dataset.html
And created .txt files
I have added MyDataset.py in mmdet/datasets as well as init.py 
Also added data and classes in mmdet/evaluation init.py and class_names.py
