### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by alejopaullier96** [open-mmlab/mmdetection#8212]
I followed the steps from [get_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md).

When executing the command:
```
mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .
```
I got the following error :
```
/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/opt/anaconda3/envs/openmmlab/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 44, in cli
    download(package, configs, dest_root)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/download.py", line 75, in download
    model_info = get_model_info(
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 170, in get_model_info
    dataframe = convert2df(metadata)
  File "/opt/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mim/commands/search.py", line 396, in convert2df
    for key, value in name2collection[collection_name].items():
KeyError: 'Cascade Mask R-CNN'
```

I am running it on a MacBook Pro with an M1 chip.

**Comment by BIGWangYuDong** [comment]
I did not meet this error in Ubuntu 1604.

**Comment by BIGWangYuDong** [comment]
What mim version did you use?

**Comment by cfwen** [comment]
I have same error when I follow the installation steps on https://mmdetection.readthedocs.io/en/stable/get_started.html

I am using WSL2, Ubuntu 20.04, mim version 0.1.6

**Comment by alejopaullier96** [comment]
The problem has been solved [here](https://github.com/open-mmlab/mmdetection/issues/8122#issuecomment-1158658158)
