### ISSUE TITLE
Failed to train SOLOV2 model

### ISSUE THREAD

**Issue by dygcjlu** [open-mmlab/mmdetection#8221]
1 I train solov2 with the following command:
python tools/train.py  /home/xxd/open-mmlab/mmdetection/configs/solov2/solov2_r50_fpn_1x_coco.py

  2 and then the  the process was terminated with the following error information:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 128, 200, 272]], which is output 0 of ReluBackward0, is at version 3; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

 3 i add torch.autograd.set_detect_anomaly(True) in train.py.

 4 i get the following information. it seems that the Relu should be set to False in self.convs_all_levels[0] module. but actually, Relu already been set to False "inplace=False"

any help would be appreciated

**environment:**
cuda 11.3.1
pytorch 1.10.1
torchvision 0.11.2
mmcv-full 1.5.2
mmdet 2.25.0

**error information:**

[W python_anomaly_mode.cpp:104] Warning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "tools/train.py", line 244, in <module>
    main()
  File "tools/train.py", line 233, in main
    train_detector(
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/detectors/single_stage_instance_seg.py", line 127, in forward_train
    mask_loss = self.mask_head.forward_train(
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/dense_heads/base_mask_head.py", line 56, in forward_train
    outs = self(x)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/dense_heads/solov2_head.py", line 253, in forward
    mask_feats = self.mask_feature_head(feats)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/models/dense_heads/solov2_head.py", line 136, in forward
    feature_add_all_level = self.convs_all_levels[0](inputs[0])
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 205, in forward
    x = self.activate(x)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/functional.py", line 1299, in relu
    result = torch.relu(input)
 (function _print_stack)
Traceback (most recent call last):
  File "tools/train.py", line 244, in <module>
    main()
  File "tools/train.py", line 233, in main
    train_detector(
  File "/home/xxd/dyg/open-mmlab/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 52, in train
    self.call_hook('after_train_iter')
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/xxd/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 128, 200, 304]], which is output 0 of ReluBackward0, is at version 3; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by Czm369** [comment]
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#L144
Welcome to fix the bug, we will review asap
`feature_add_all_level = feature_add_all_level + self.convs_all_levels[i](input_p)`

**Comment by BIGWangYuDong** [comment]
Have you changed any codes? I haven't met this problem before

**Comment by dygcjlu** [comment]
> Have you changed any codes? I haven't met this problem before

I didn't change any code. 
i fixed the bug according to @Czm369 's suggestion.

**Comment by dygcjlu** [comment]
> https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/solov2_head.py#L144
> 
> Welcome to fix the bug, we will review asap
> `feature_add_all_level = feature_add_all_level + self.convs_all_levels[i](input_p)`

Thanks

**Comment by BIGWangYuDong** [comment]
We'll fix this error in the next version. Thanks for your report

**Comment by BIGWangYuDong** [comment]
Fixed in mmdet v2.25.1
