### ISSUE TITLE
Lack of 'Cascade Mask R-CNN' in collections of Metadata for mmdet-2.25.0

### ISSUE THREAD

**Issue by Paul-LiPu** [open-mmlab/mmdetection#8227]
Version: openmim-0.1.6, mmcv-full-1.5.3, mmdet-2.25.0

This error popped out when I verified the installation of mmdet. And there is no such error when I downgrade to  mmdet-2.24.0. 

`$ mim download mmdet --config yolov3_mobilenetv2_320_300e_coco --dest .`
Traceback (most recent call last):
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/bin/mim", line 8, in <module>
sys.exit(cli())
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/click/core.py", line 610, in invoke
return callback(*args, **kwargs)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/mim/commands/download.py", line 44, in cli
download(package, configs, dest_root)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/mim/commands/download.py", line 75, in download
model_info = get_model_info(
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/mim/commands/search.py", line 170, in get_model_info
dataframe = convert2df(metadata)
File "/home/users/pli/anaconda3/envs/py38_pt110_mm/lib/python3.8/site-packages/mim/commands/search.py", line 396, in convert2df
for key, value in name2collection[collection_name].items():
KeyError: 'Cascade Mask R-CNN'

**Comment by Mr-brillianter** [comment]
Unluckily, i don't have this file in Ubuntu 18.04 
I have "locate" and checked .

**Comment by Mr-brillianter** [comment]
hard to believe it's a 2 years old bug.

**Comment by BIGWangYuDong** [comment]
Fixed in mmdet2.25.1
