### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by QueenW1998** [open-mmlab/mmdetection#8238]
Traceback (most recent call last):
  File "E:\Anaconda\envs\whmmdet\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "H:\WH\MM\mmdetection-master\mmdet\datasets\custom.py", line 121, in __init__
    valid_inds = self._filter_imgs()
  File "H:\WH\MM\mmdetection-master\mmdet\datasets\coco.py", line 139, in _filter_imgs
    if min(img_info['width'], img_info['height']) >= min_size:    #min_size
TypeError: '>=' not supported between instances of 'str' and 'int'

**Comment by jbwang1997** [comment]
Seems the img_info['width'] and img_info['height'] are str type. Please check if the json file is correct.
