### ISSUE TITLE
This error occurs when using Albu RandomRotate90 in train_pipeline

### ISSUE THREAD

**Issue by wzr0108** [open-mmlab/mmdetection#8250]
```
Traceback (most recent call last):
  File "./tools/train.py", line 234, in <module>
    main()
  File "./tools/train.py", line 221, in main
    meta=meta)
  File "/disk/sde/qwe/project/mmdet/apis/train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/sdb/qwe/.conda/envs/qwe_env2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk/sde/qwe/project/mmdet/datasets/dataset_wrappers.py", line 437, in __getitem__
    'The training pipeline of the dataset wrapper'
RuntimeError: The training pipeline of the dataset wrapper always return None.Please check the correctness of the dataset and its pipeline.
```

the train pipeline is as follows
```
train_pipeline = [
    dict(
        type='Resize',
        img_scale=[(1000, 400), (1000, 800)],
        multiscale_mode='range',
        keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Albu',
        transforms=[
            dict(type='RandomRotate90', p=0.5),
        ],
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_area=1,
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(img='image', gt_bboxes='bboxes'),
        update_pad_shape=True,
        skip_img_without_anno=True),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='FilterAnnotations', min_gt_bbox_wh=(1, 1), keep_empty=False),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
```
when i remove Albu, the training is normal

**Comment by Bruce-Si** [comment]
I met the same error, any progress?

**Comment by wzr0108** [comment]
> I met the same error, any progress?

I just switched the order of data augmentation

**Comment by wzr0108** [comment]
> I met the same error, any progress?
···
dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            format='pascal_voc',
            label_fields=['gt_labels'],
            min_area=1,
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap=dict(img='image', gt_bboxes='bboxes'),
        update_pad_shape=True,
        skip_img_without_anno=False),
···
it works for me

**Comment by Bruce-Si** [comment]
Thank you! Though my dataset is coco, I set the config as yours, it works.

**Comment by clw5180** [comment]
skip_img_without_anno=False means the negative sample(img without gt bbox) will be keeped, otherwise it will return None and cause bug in next pipeline
