### ISSUE TITLE
Errors in inference

### ISSUE THREAD

**Issue by austin1900** [open-mmlab/mmdetection#8269]
I have added a new branch in head, but I met the following error when inferring and the model cannot be inferred.

**Describe the bug**
Traceback (most recent call last):
  File "./tools/train.py", line 242, in <module>
    main()
  File "./tools/train.py", line 238, in main
    meta=meta)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/core/evaluation/eval_hooks.py", line 130, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/apis/test.py", line 109, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/models/detectors/single_stage.py", line 106, in simple_test
    feat, img_metas, rescale=rescale)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/models/dense_heads/base_dense_head.py", line 360, in simple_test
    return self.simple_test_bboxes(feats, img_metas, rescale=rescale)
  File "/data/zhouzz1/mmdetection_2.25/mmdet/models/dense_heads/dense_test_mixins.py", line 38, in simple_test_bboxes
    *outs, img_metas=img_metas, rescale=rescale)
  File "/home/zhouzz1/anaconda3/envs/mm/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 197, in new_func
    return old_func(*args, **kwargs)
TypeError: get_bboxes() got multiple values for argument 'img_metas'

How can I solve this problem? Thanks

**Comment by Czm369** [comment]
You can check `img_metas`
https://github.com/open-mmlab/mmdetection/blob/ca11860f4f3c3ca2ce8340e2686eeaec05b29111/mmdet/models/dense_heads/dense_test_mixins.py#L17

**Comment by austin1900** [comment]
thanks

**Comment by shuangkouyizu** [comment]
I have met the same problem，please tell me how to solve it？ Thank you a lot！
