### ISSUE TITLE
Saving checkpoint error

### ISSUE THREAD

**Issue by boynextdoor7** [open-mmlab/mmdetection#8276]
2022-06-28 19:03:10,324 - mmdet - INFO - Saving checkpoint at 1 epochs
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/train.py", line 186, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/core/evaluation/eval_hooks.py", line 53, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/test.py", line 95, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/datasets/samplers/distributed_sampler.py", line 32, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/train.py", line 186, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/core/evaluation/eval_hooks.py", line 53, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/test.py", line 95, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/datasets/samplers/distributed_sampler.py", line 32, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 80063) is killed by signal: Terminated. 
completed: 0, elapsed: 0sTraceback (most recent call last):
  File "./tools/train.py", line 188, in <module>
    main()
  File "./tools/train.py", line 184, in main
    meta=meta)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/train.py", line 186, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 220, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/core/evaluation/eval_hooks.py", line 53, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/apis/test.py", line 95, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/home/ccf_disk/zlq/CBNetV2/mmdet/datasets/samplers/distributed_sampler.py", line 32, in __iter__
    math.ceil(self.total_size / len(indices)))[:self.total_size]
ZeroDivisionError: division by zero
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 80105) is killed by signal: Terminated. 
Traceback (most recent call last):
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ccf_disk/zlq/anaconda3/envs/new_mmd/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ccf_disk/zlq/anaconda3/envs/new_mmd/bin/python', '-u', './tools/train.py', '--local_rank=2', 'configs/swin/cascade_rcnn_swin_tiny.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by hhaAndroid** [comment]
@boynextdoor7 `math.ceil(self.total_size / len(indices)))[:self.total_size]  ZeroDivisionError: division by zero `.  This means that the data processing is wrong, please check the dataset.
