### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 34: illegal multibyte sequence

### ISSUE THREAD

**Issue by zhjr2019** [open-mmlab/mmdetection#8291]
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" D:/zhjrProjects/source/OpenMMLab/MMDetection/tools/train.py ../configs/balloon/mask_rcnn_r50_caffe_fpn_mstrain-poly_1x_balloon.py
Traceback (most recent call last):
  File "D:\zhjrProjects\source\OpenMMLab\MMDetection\tools\train.py", line 242, in <module>
    main()
  File "D:\zhjrProjects\source\OpenMMLab\MMDetection\tools\train.py", line 114, in main
    cfg = replace_cfg_vals(cfg)
  File "D:\zhjrProjects\source\OpenMMLab\MMDetection\mmdet\utils\replace_cfg_vals.py", line 64, in replace_cfg_vals
    updated_cfg = Config(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\mmcv\utils\config.py", line 405, in __init__
    text = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 34: illegal multibyte sequence

Process finished with exit code 1

**Comment by zhjr2019** [comment]
按照官网设置：https://mmdetection.readthedocs.io/zh_CN/latest/2_new_data_model.html
IDE：PyCharm
另外指出一个官网配置文件问题：
![image](https://user-images.githubusercontent.com/44044519/176992066-9eb5fed5-b4f2-4b7c-a3f5-71d0e9965ffd.png)

**Comment by chhluo** [comment]
Re-new the config file with encoding='utf-8' may help you.

**Comment by wrywst** [comment]
i have the same problem,

**Comment by lavender37** [comment]
change the config.py in line 405 with specifying the encoding UTF-8 may help you
``` 
        if cfg_text:
            text = cfg_text
        elif filename:
            with open(filename, encoding='UTF-8') as f:
                text = f.read()
        else:
            text = ''
```
