### ISSUE TITLE
Mask RCNN swin transformer to TensorRT KeyError: 'onnx::NonMaxSuppression_12575'

### ISSUE THREAD

**Issue by anshkumar** [open-mmlab/mmdetection#8299]
I was trying to convert Swin-T Mask R-CNN but getting following error:

```
Traceback (most recent call last):
  File "/home/sort/mmdetection/tools/deployment/onnx2tensorrt.py", line 247, in <module>
    onnx2tensorrt(
  File "/home/sort/mmdetection/tools/deployment/onnx2tensorrt.py", line 40, in onnx2tensorrt
    trt_engine = onnx2trt(
  File "/home/sort/ved/mmcv/mmcv/tensorrt/tensorrt_utils.py", line 71, in onnx2trt
    onnx_model = preprocess_onnx(onnx_model)
  File "/home/sort/ved/mmcv/mmcv/tensorrt/preprocess.py", line 102, in preprocess_onnx
    mark_nodes_to_remove(node_inputs[2])
  File "/home/sort/ved/mmcv/mmcv/tensorrt/preprocess.py", line 59, in mark_nodes_to_remove
    node = node_dict[name]
KeyError: 'onnx::NonMaxSuppression_12575'
``` 

Here, are the steps I followed:
1) mmcv compile with TRT and ONNX:
```
export TENSORRT_DIR=/home/sort/ved/TensorRT-7.2.3.4
export ONNXRUNTIME_DIR=/home/sort/ved/onnxruntime-linux-x64-gpu-1.11.1
export LD_LIBRARY_PATH=/home/sort/ved/onnxruntime-linux-x64-gpu-1.11.1/lib:/home/sort/ved/TensorRT-7.2.3.4/lib:/usr/local/cuda/lib64


git clone https://github.com/open-mmlab/mmcv.git

cd mmcv ## to MMCV root directory
MMCV_WITH_OPS=1 MMCV_WITH_ORT=1 MMCV_WITH_TRT=1 pip install -e .
```
2) To ONNX:
```
python /home/sort/mmdetection/tools/deployment/pytorch2onnx.py \
    /home/sort/ved/sort/onion_l2/mask_rcnn_swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py \
    /home/sort/ved/sort/onion_l2/mask_rcnn_swin/epoch_5.pth \
    --output-file mask_rcnn_swin_e5.onnx \
    --input-img /home/sort/ved/sort/onion_l2/data/val/images/1000.jpg \
    --test-img /home/sort/ved/sort/onion_l2/data/val/images/0.jpg \
    --shape 750 750 \
    --show \
    --dynamic-export 
```

3) To TRT:
```
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/home/sort/ved/TensorRT-7.2.3.4/lib:/home/sort/ved/TensorRT-8.4.1.5/lib

python -m pip install colored polygraphy --extra-index-url https://pypi.ngc.nvidia.com
polygraphy surgeon sanitize --fold-constants mask_rcnn_swin_e5.onnx -o mask_rcnn_swin_e5_folded.onnx


python /home/sort/mmdetection/tools/deployment/onnx2tensorrt.py \
    /home/sort/ved/sort/onion_l2/mask_rcnn_swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py \
    mask_rcnn_swin_e5_folded.onnx \
    --trt-file mask_rcnn_swin_e5.trt \
    --input-img /home/sort/ved/sort/onion_l2/data/val/images/0.jpg \
    --shape 750 750 \
    --show
```

I'm using both `TensorRT-7.2.3.4` and `TensorRT-8.4.1.5`, otherwise I was getting errors like:
```
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
```

**Comment by Czm369** [comment]
Maybe you can try MMDeploy
https://github.com/open-mmlab/mmdeploy

**Comment by anshkumar** [comment]
Getting following error:
```
Process Process-3:
Traceback (most recent call last):
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sort/miniconda3/envs/openmmlab/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sort/mmdeploy/mmdeploy/apis/core/pipeline_manager.py", line 107, in __call__
    ret = func(*args, **kwargs)
  File "/home/sort/mmdeploy/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line 79, in onnx2tensorrt
    from_onnx(
  File "/home/sort/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 113, in from_onnx
    raise RuntimeError(f'Failed to parse onnx, {error_msgs}')
RuntimeError: Failed to parse onnx, In node 2160 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

2022-07-05 13:55:26,152 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed. exit.
```

I'm using following command:
```
python ./tools/deploy.py \
    'configs/mmdet/_base_/base_tensorrt-fp16_static-1050x1050.py' \
    '/home/sort/ved/sort/onion_l2/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py' \
    '/home/sort/ved/sort/onion_l2/mask_rcnn_swin/epoch_5.pth' \
    '/home/sort/ved/sort/onion_l2/data/val/images/10000000000001.0.jpg' \
    --test-img '/home/sort/ved/sort/onion_l2/data/val/images/1000000000012.0.jpg' \
    --work-dir '/home/sort/ved/sort/onion_l2/mmdeploy_out/' \
    --log-level DEBUG\
    --show \
    --device cuda:1
```

In file `configs/mmdet/_base_/base_tensorrt-fp16_static-1050x1050.py` I'm using 1056x1056 as dimensions.
