### ISSUE TITLE
AvoidCUDAOOM usage

### ISSUE THREAD

**Issue by Hari7696** [open-mmlab/mmdetection#8302]
Hi Team,

I am training a faster RCNN model and tried to use the AvoidCUDAOOM  in the following way

```
    from mmdet.utils import AvoidOOM
    from mmdet.apis import train_detector
    from mmdet.models import build_detector
    from mmdet.datasets import build_dataset
    AvoidCUDAOOM = AvoidOOM()
    cfg, _ = load_config(data_folder)
    datasets = [build_dataset(cfg.data.train)]
    model = build_detector(cfg.model, train_cfg=cfg.get("train_cfg"), test_cfg=cfg.get("train_cfg"))
    AvoidCUDAOOM.retry_if_cuda_oom(train_detector)(model, datasets, cfg, validate=True)
```

The code working fine without the OOM. But when I Use the OOM, it's throwing the following error. Can you please let me know if I am doing something wrong?

```
Traceback (most recent call last):
  File "basicHighResolution.py", line 150, in <module>
    output = AvoidCUDAOOM.retry_if_cuda_oom(train_detector)(model, datasets, cfg, validate=True)
  File "/mmdetection/mmdet/utils/memory.py", line 160, in wrapped
    raise ValueError('There is no tensor in the inputs, cannot get dtype and device')

```

**Comment by abhijeet-gorai** [comment]
I am also facing the same issue. I am using it in the following way - 
```
from mmdet.utils import AvoidCUDAOOM
AvoidCUDAOOM.retry_if_cuda_oom(train_detector)(model, datasets, cfg, validate=True)
```

**Comment by ZwwWayne** [comment]
AvoidCUDAOOM only works with functions that take tensors as input.

**Comment by ZwwWayne** [comment]
Seems that AvoidCUDAOOM is not in our doc, we should update it.
