### ISSUE TITLE
Issue while installing MMCV and MMDET

### ISSUE THREAD

**Issue by IAMShashankk** [open-mmlab/mmdetection#8316]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
Not able to set up the environment for mmdetection.  I installed all the prerequisite libraries.
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
`pip install tqdm`
`pip install torchpack`
`pip install mmcv-full==1.4 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`
`pip install mmdet==2.22.0`

**Reproduction**

1. What command or script did you run?

```
Running setup.py after installing all the above packages, results in an error.
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
No

5. What dataset did you use?
I am using nuscenes but before that, I am not able to build the environment to run create_Data.py

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
```
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0
Libc version: glibc-2.9

Python version: 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 23:13:11)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-120-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.0.167
GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB
Nvidia driver version: 510.73.08
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] crumpets-torch==3.0.0a5+cuda110
[pip] msgpack-numpy==0.4.8
[pip] numpy==1.18.1
[pip] pytorch-ignite==0.4.1
[pip] pytorch-transformers==1.1.0
[pip] torch==1.9.0+cu111
[pip] torch-geometric==1.6.0
[pip] torchaudio==0.9.0
[pip] torchpack==0.3.1
[pip] torchtext==0.6.0
[pip] torchvision==0.10.0+cu111
[conda] crumpets-torch            3.0.0a5+cuda110          pypi_0    pypi
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.18.1           py36h94c655d_0  
[conda] numpy-base                1.18.1           py36h2f8d375_1  
[conda] pytorch-ignite            0.4.1                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-geometric           1.6.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchpack                 0.3.1                    pypi_0    pypi
[conda] torchtext                 0.6.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```
3. You may add addition that may be helpful for locating the problem, such as
 Already mentioned above.

**Error traceback**
If applicable, paste the error trackback here.

```
*********************************calling setup.py*********************************
running develop
running egg_info
creating mmdet3d.egg-info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
building 'mmdet3d.ops.spconv.sparse_conv_ext' extension
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv
creating /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src
Emitting ninja build file /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/7] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o 
/usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/reordering_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/reordering_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[2/7] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o 
/usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/maxpool_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/maxpool_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[3/7] /usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/indice_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
FAILED: /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o 
/usr/local/cuda/bin/nvcc  -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/indice_cuda.cu -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/indice_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -w -std=c++14 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_86,code=sm_86 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[4/7] c++ -MMD -MF /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/reordering.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/reordering.cc -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/reordering.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[5/7] c++ -MMD -MF /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/maxpool.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/maxpool.cc -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/maxpool.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[6/7] c++ -MMD -MF /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/indice.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/indice.cc -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/indice.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[7/7] c++ -MMD -MF /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/all.o.d -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/include -I/opt/conda/lib/python3.6/site-packages/torch/include -I/opt/conda/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.6/site-packages/torch/include/TH -I/opt/conda/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.6m -c -c /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/mmdet3d/ops/spconv/src/all.cc -o /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/bevfusion/build/temp.linux-x86_64-3.6/mmdet3d/ops/spconv/src/all.o -w -std=c++14 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=sparse_conv_ext -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 161, in <module>
    zip_safe=False,
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/opt/conda/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by IAMShashankk** [comment]
I tried building MMC and MMDet from source using following commands:
```
git clone https://github.com/open-mmlab/mmcv.git
cd mmcv
pip install -r requirements/optional.txt
MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e .
git clone --branch v2.20.0 https://github.com/open-mmlab/mmdetection.git
cd /netscratch/mishra/Thesis_Fusion/BEVFusion/BEVFusion_Baseline/mmdetection
pip install -r requirements/build.txt
pip install -v -e .
```
still, the same error while running setup.py.
@ZwwWayne any inputs on this.

**Comment by ZwwWayne** [comment]
It seems to be the cause of CUDA operators in mmdet3d. We have not test it in the high version.

**Comment by Markson-Young** [comment]
I also encountered this problem, my PyTorch version is 1.9.0+cu111 too!!!
I look forward to your reply to my questions as soon as possible. Thanks!

Log as follows:

ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1666, in _run_ninja_build
    subprocess.run(
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    setup(
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 682, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\Python\Anaconda\anaconda3\envs\mmlab\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
