### ISSUE TITLE
simply hard to install

### ISSUE THREAD

**Issue by twangnh** [open-mmlab/mmdetection#8335]

**Comment by chhluo** [comment]
What's the problem did you meet when install the MMDetection?

**Comment by twangnh** [comment]
I encountered CUDA error which I have no clue at all:
```
Traceback (most recent call last):
  File "./tools/train.py", line 153, in <module>
    main()
  File "./tools/train.py", line 142, in main
    train_detector(
  File "/home/wangtao/prj/eqlv2/mmdet/apis/train.py", line 143, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 51, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/wangtao/prj/eqlv2/mmdet/models/detectors/base.py", line 237, in train_step                                                                                                                                                                     [0/1903]
    losses = self(**data)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangtao/prj/eqlv2/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/wangtao/prj/eqlv2/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/wangtao/prj/eqlv2/mmdet/models/detectors/two_stage.py", line 165, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/home/wangtao/prj/eqlv2/mmdet/models/dense_heads/base_dense_head.py", line 58, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/wangtao/prj/eqlv2/mmdet/core/fp16/decorators.py", line 131, in new_func
    return old_func(*args, **kwargs)
  File "/home/wangtao/prj/eqlv2/mmdet/models/dense_heads/anchor_head.py", line 572, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/home/wangtao/prj/eqlv2/mmdet/models/dense_heads/rpn_head.py", line 176, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, nms_cfg)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/misc.py", line 310, in new_func
    output = old_func(*args, **kwargs)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: initialization error
Traceback (most recent call last):
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/wangtao/anaconda3_2/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/wangtao/anaconda3_2/envs/openmmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', './configs/end2end/eql_r50_8x2_1x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by chhluo** [comment]
MMCV is installed inproperly. 

Please install it by `pip install mmcv-full==1.5.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10/index.html`
replace the `cu113` and `torch1.10` according to your requirement.

**Comment by twangnh** [comment]
it works, thanks, could you add this to the installation page? it takes so long for me, but did not find this simple solution

**Comment by chhluo** [comment]
It's in the [get_started.nd](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md)

How did you install MMDetection?

**Comment by twangnh** [comment]
I followed the provided instruction to install MMDetection, it works without errors. However, it installed the newest torch, which results in gpu cannot be find problem, I thus tried installing lower version torch as
`pip install torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
Then I met the problem

**Comment by chhluo** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/blob/v2.24.1/docs/en/get_started.md

**Comment by twangnh** [comment]
thks!
