### ISSUE TITLE
train mask2former self data(coco) show erro after tarin one epochs in eval

### ISSUE THREAD

**Issue by 827346462** [open-mmlab/mmdetection#8414]
my env:
mmcv-full 1.5.0
mmdet 2.25
pytorct 1.10-cu11.3

我训练mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.py . 使用标准的coco2017数据集，标签10个
我修改了config中的数据集路径以及标签个数如下，以及修改了coco.py 以及coco_panoptic.py 对应的数据
num_things_classes = 10
num_stuff_classes = 0
num_classes = 10

其中panoptic_head panoptic_fusion_head中的num_things_classes=80我没有进行修改
panoptic_head=dict(
        type='Mask2FormerHead',
        in_channels=[96, 192, 384, 768],
        strides=[4, 8, 16, 32],
        feat_channels=256,
        out_channels=256,
        num_things_classes=80,
        num_stuff_classes=0,
        num_queries=100,
        num_transformer_feat_level=3,
        pixel_decoder=dict(
            type='MSDeformAttnPixelDecoder',
            num_outs=3,
            norm_cfg=dict(type='GN', num_groups=32),
            act_cfg=dict(type='ReLU'),
            encoder=dict(
                type='DetrTransformerEncoder',
                num_layers=6,
                transformerlayers=dict(
                    type='BaseTransformerLayer',
                    attn_cfgs=dict(
                        type='MultiScaleDeformableAttention',
                        embed_dims=256,
                        num_heads=8,
                        num_levels=3,
                        num_points=4,
                        im2col_step=64,
                        dropout=0.0,
                        batch_first=False,
                        norm_cfg=None,
                        init_cfg=None),
                    ffn_cfgs=dict(
                        type='FFN',
                        embed_dims=256,
                        feedforward_channels=1024,
                        num_fcs=2,
                        ffn_drop=0.0,
                        act_cfg=dict(type='ReLU', inplace=True)),
                    operation_order=('self_attn', 'norm', 'ffn', 'norm')),
                init_cfg=None),
            positional_encoding=dict(
                type='SinePositionalEncoding', num_feats=128, normalize=True),
            init_cfg=None),
        enforce_decoder_input_project=False,
        positional_encoding=dict(
            type='SinePositionalEncoding', num_feats=128, normalize=True),
        transformer_decoder=dict(
            type='DetrTransformerDecoder',
            return_intermediate=True,
            num_layers=9,
            transformerlayers=dict(
                type='DetrTransformerDecoderLayer',
                attn_cfgs=dict(
                    type='MultiheadAttention',
                    embed_dims=256,
                    num_heads=8,
                    attn_drop=0.0,
                    proj_drop=0.0,
                    dropout_layer=None,
                    batch_first=False),
                ffn_cfgs=dict(
                    embed_dims=256,
                    feedforward_channels=2048,
                    num_fcs=2,
                    act_cfg=dict(type='ReLU', inplace=True),
                    ffn_drop=0.0,
                    dropout_layer=None,
                    add_identity=True),
                feedforward_channels=2048,
                operation_order=('cross_attn', 'norm', 'self_attn', 'norm',
                                 'ffn', 'norm')),
            init_cfg=None),
        loss_cls=dict(
            type='CrossEntropyLoss',
            use_sigmoid=False,
            loss_weight=2.0,
            reduction='mean',
            class_weight=[
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1
            ]),
        loss_mask=dict(
            type='CrossEntropyLoss',
            use_sigmoid=True,
            reduction='mean',
            loss_weight=5.0),
        loss_dice=dict(
            type='DiceLoss',
            use_sigmoid=True,
            activate=True,
            reduction='mean',
            naive_dice=True,
            eps=1.0,
            loss_weight=5.0)),
    panoptic_fusion_head=dict(
        type='MaskFormerFusionHead',
        num_things_classes=80,
        num_stuff_classes=0,
        loss_panoptic=None,
        init_cfg=None),

在训练一个epoch后进行评估时会出现labels 溢出，不知道这是什么原因？是我数据设置的错吗？以下是错误信息。请解答我的疑问，十分感谢

[                                                  ] 0/252, elapsed: 0s, ETA:/data/mmdetection-master/mmdet/models/seg_heads/panoptic_fusion_heads/maskformer_fusion_head.py:144: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  query_indices = top_indices // self.num_classes
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 252/252, 5.1 task/s, elapsed: 49s, ETA:     0s80
0
80###这是我将coco.py的 函数 _segm2json 的 len(det)的长度进行输出看到的结果
80
80
Traceback (most recent call last):
  File "./tools/train.py", line 246, in <module>
    main()
  File "./tools/train.py", line 235, in main
    train_detector(
  File "/data/mmdetection-master/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 262, in after_train_iter
    self._do_evaluate(runner)
  File "/data/mmdetection-master/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 363, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/data/mmdetection-master/mmdet/datasets/coco.py", line 631, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/data/mmdetection-master/mmdet/datasets/coco.py", line 373, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/data/mmdetection-master/mmdet/datasets/coco.py", line 310, in results2json
    json_results = self._segm2json(results)
  File "/data/mmdetection-master/mmdet/datasets/coco.py", line 261, in _segm2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range

**Comment by ZwwWayne** [comment]
This is usually caused by unmatched number of classes in the head and dataset. In config, we can see that `num_things_classes=80`, is still 80.

**Comment by 827346462** [comment]
> 这通常是由头部和数据集中不匹配的类数量引起的。在配置中，我们可以看到 ，仍然是 80。`num_things_classes=80`

i try chang panoptic_head panoptic_fusion_head is "num_things_classes = 10",but get erro:
Traceback (most recent call last):
  File "./tools/train.py", line 246, in <module>
    main()
  File "./tools/train.py", line 235, in main
    train_detector(
  File "/data/mmdetection-master/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/mmdetection-master/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
    return old_func(*args, **kwargs)
  File "/data/mmdetection-master/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/mmdetection-master/mmdet/models/detectors/maskformer.py", line 104, in forward_train
    losses = self.panoptic_head.forward_train(x, img_metas, gt_bboxes,
  File "/data/mmdetection-master/mmdet/models/dense_heads/maskformer_head.py", line 521, in forward_train
    losses = self.loss(all_cls_scores, all_mask_preds, gt_labels, gt_masks,
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 198, in new_func
    return old_func(*args, **kwargs)
  File "/data/mmdetection-master/mmdet/models/dense_heads/maskformer_head.py", line 303, in loss
    losses_cls, losses_mask, losses_dice = multi_apply(
  File "/data/mmdetection-master/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/data/mmdetection-master/mmdet/models/dense_heads/mask2former_head.py", line 263, in loss_single
    loss_cls = self.loss_cls(
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mmdetection-master/mmdet/models/losses/cross_entropy_loss.py", line 291, in forward
    loss_cls = self.loss_weight * self.cls_criterion(
  File "/data/mmdetection-master/mmdet/models/losses/cross_entropy_loss.py", line 42, in cross_entropy
    loss = F.cross_entropy(
  File "/home/sevnce/anaconda3/envs/mm/lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: weight tensor should be defined either for all 11 classes or no classes but got weight tensor of shape: [81]

**Comment by PeterVennerstrom** [comment]
`class_weight=[
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1
])`

This probably originated in an inherited config.  It should be redefined for your # classes.

`loss_cls=dict(class_weight=[1.0] * num_classes + [0.1]))`

**Comment by 827346462** [comment]
> 

thanks.I sucess train
