### ISSUE TITLE
TypeError: build_model_from_cfg() got multiple values for argument 'registry'

### ISSUE THREAD

**Issue by X-ray0214** [open-mmlab/mmdetection#8477]
Traceback (most recent call last):
  File "/home1/ugv/autodriving/BEVFusion-main/demo/pcd_demo.py", line 28, in <module>
    main()
  File "/home1/ugv/autodriving/BEVFusion-main/demo/pcd_demo.py", line 20, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/apis/inference.py", line 51, in init_detector
    model = build_detector(config.model, train_cfg=None, test_cfg=config.get('test_cfg'))
  File "/home1/ugv/autodriving/BEVFusion-main/mmdet3d/models/builder.py", line 48, in build_detector
    return DETECTORS.build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mnt/EXOS_AUTO/JIANG_FOLDER/anoconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
TypeError: build_model_from_cfg() got multiple values for argument 'registry'

**Comment by jbwang1997** [comment]
Could you provide the config and the mmdetection version you used?

**Comment by X-ray0214** [comment]
> Could you provide the config and the mmdetection version you used?

The mmdetection version is 2.25.0 and the config I used is "second---------hv_second_secfpn_6x8_80e_kitti-3d-car.py" . I also tried other configs(such as pointpillars and mvxnet), but the same error occurs.

**Comment by jbwang1997** [comment]
Seems you used mmdet3d, I consider the version of your mmdet3d is too low. Please follow the [tutorial](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/faq.md) to install the right version of mmdet3d. Or your can downgrade your mmdet.

**Comment by X-ray0214** [comment]
> 

Hello!You are right!Thanks a lot!
