### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (0,) (4,)

### ISSUE THREAD

**Issue by Vo-Linh** [open-mmlab/mmdetection#8511]
When I tried train model YOLOv3, I got `ValueError: operands could not be broadcast together with shapes (0,) (4,)`

My code 

```
# Build dataset
datasets = [build_dataset(cfg.data.train)]
# Build the detector
model = build_detector(cfg.model)
# Add an attribute for visualization convenience
model.CLASSES = datasets[0].CLASSES
# Create work_dir
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
train_detector(model, datasets, cfg, distributed=False, validate=True)
```
Result form datasets
<img width="635" alt="image" src="https://user-images.githubusercontent.com/79654917/183230561-1db25a70-e46b-47cb-a545-3b99b36196e6.png">

**Comment by chhluo** [comment]
Please provide the traceback information.

**Comment by Vo-Linh** [comment]
Can you help me?
```
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/mmdetection/mmdet/datasets/custom.py", line 218, in __getitem__
    data = self.prepare_train_img(idx)
  File "/content/mmdetection/mmdet/datasets/custom.py", line 241, in prepare_train_img
    return self.pipeline(results)
  File "/content/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/content/mmdetection/mmdet/datasets/pipelines/transforms.py", line 1118, in __call__
    (left, top), 2).astype(results[key].dtype)
ValueError: operands could not be broadcast together with shapes (0,) (4,)
```

**Comment by chhluo** [comment]
@Vo-Linh Which config file did you use? And did you make any modification to code and config?

**Comment by Vo-Linh** [comment]
You can check my config
```
fg = Config.fromfile('mmdetection/configs/yolo/yolov3_d53_320_273e_coco.py')

# Modify dataset type and path.
cfg.dataset_type = 'myDateset'
cfg.data_root = '/data_root/'
cfg.data.test.type = 'myDateset'
cfg.data.test.data_root = '/data_root/'
cfg.data.test.ann_file = '/content/data_root/dataset/ImageSets/test.txt'
cfg.data.test.img_prefix = '/content/data_root/dataset/JPEGImages'
cfg.data.train.type = 'myDateset'
cfg.data.train.data_root = '/data_root/'
cfg.data.train.ann_file = '/content/data_root/dataset/ImageSets/train.txt'
cfg.data.train.img_prefix = '/content/data_root/dataset/JPEGImages'
cfg.data.val.type = 'myDateset'
cfg.data.val.data_root = '/data_root/'
cfg.data.val.ann_file = '/content/data_root/dataset/ImageSets/valid.txt'
cfg.data.val.img_prefix = '/content/data_root/dataset/JPEGImages' 
# Batch size (samples per GPU).
cfg.data.samples_per_gpu = 16
# Modify number of classes as per the model head.
cfg.model.bbox_head.num_classes = 7
# Comment/Uncomment this to training from scratch/fine-tune according to the 
# model checkpoint path. 
cfg.load_from = 'checkpoints/yolov3_d53_320_273e_coco-421362b6.pth'
# The original learning rate (LR) is set for 8-GPU training.
# We divide it by 8 since we only use one GPU.
cfg.optimizer.lr = 0.008 / 8
cfg.lr_config.warmup = None
cfg.log_config.interval = 5
# The output directory for training. As per the model name.
cfg.work_dir = 'outputs/yolov3_d53_320_273e_coco'
# Evaluation Metric.
cfg.evaluation.metric = 'mAP'
# Evaluation times.
cfg.evaluation.interval = 1
# Checkpoint storage interval.
cfg.checkpoint_config.interval = 15
# Set random seed for reproducible results.
cfg.seed = 0
set_random_seed(0, deterministic=False)
cfg.gpu_ids = range(1)
cfg.device = 'cuda'
cfg.runner.max_epochs = 100
# We can also use tensorboard to log the training process
cfg.log_config.hooks = [
    dict(type='TextLoggerHook'),
    dict(type='TensorboardLoggerHook')]

```

**Comment by chhluo** [comment]
The error is from here, https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/pipelines/transforms.py#L1117
gt_bboxes.shape or gt_bboxes_ignore.shape is (0, ) wihch means that there is no annotation in the current image. So please check that whether there exists a image which  has no annotation.

When there is no annotation in the image, the shape of `gt_bboxes` or `gt_bboxes_ignore` should be (0, 4) instead of (0, ), refer to https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/datasets/coco.py#L185
