### ISSUE TITLE
''TypeError: 'DataContainer' object is not subscriptable'''

### ISSUE THREAD

**Issue by jimuIee** [open-mmlab/mmdetection#8550]
when i run the
''CUDA_VISIBLE_DEVICE=7 GPUS=1 ./test_sonar.sh''
it will show:
''TypeError: 'DataContainer' object is not subscriptable'''

loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                                                  ] 0/600, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/test.py", line 378, in <module>
    main()
  File "./tools/test.py", line 361, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "./tools/test.py", line 65, in multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/lzk/mydata/anaconda3/envs/mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/base.py", line 139, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/base.py", line 124, in forward_test
    return self.aug_test(imgs, img_metas, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/cascade_rcnn.py", line 417, in aug_test
    proposal_list = self.aug_test_rpn(
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/test_mixins.py", line 41, in aug_test_rpn
    proposal_list = self.simple_test_rpn(x, img_meta, rpn_test_cfg)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/detectors/test_mixins.py", line 34, in simple_test_rpn
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/home/lzk/Uodac_sonar/mmdet/models/anchor_heads/anchor_head.py", line 272, in get_bboxes
    img_shape = img_metas[img_id]['img_shape']
TypeError: 'DataContainer' object is not subscriptable！！！！！！！！！！！！！
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3728270) of binary: /home/lzk/mydata/anaconda3/envs/mmlab/bin/python

i saw the same problem has been solved but that issue not reply how to solve this.....

**Comment by BIGWangYuDong** [comment]
please use the issue template

**Comment by BIGWangYuDong** [comment]
continue https://github.com/open-mmlab/mmdetection/issues/8551
