### ISSUE TITLE
Configs other than .py fail because of tuples

### ISSUE THREAD

**Issue by awarebayes** [open-mmlab/mmdetection#8554]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**

Config expects img_scale to be a tuple. json/yaml/Config.dump do not support tuples.

```python
Traceback (most recent call last):
  File "/home/misha/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/misha/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet/datasets/pipelines/transforms.py", line 92, in __init__
    assert mmcv.is_list_of(self.img_scale, tuple)
AssertionError
```

**Reproduction**

1. What command or script did you run?

I want to connect mmdet to clearml. To do that I use the following code:
```python
import json
import subprocess
import sys

from clearml import Task
import shutil

from mmcv import Config
from mmdet.utils import replace_cfg_vals

from src.util.misc import go_to_root_dir

go_to_root_dir()

# task = Task.init(
#     project_name="VAS-MLOPS",
#     task_name="detector/yolox_mmdet/step1_learn",
#     task_type=Task.TaskTypes.training,
# )

cfg_src = "src/nn/detector/mmdet/learning/config/our_yolox.py"
cfg_dst = "github_repos/mmdetection/configs/yolox/our_yolox.py"
cfg_dst_json = "github_repos/mmdetection/configs/yolox/our_yolox.json"

shutil.copyfile(cfg_src, cfg_dst)
cfg = Config.fromfile(cfg_dst)

cfg = replace_cfg_vals(cfg)
cfg_dict = cfg.to_dict()
# cfg_dict = task.connect(cfg_dict)

cfg_overriden = Config.fromstring(json.dumps(cfg_dict), file_format=".json")
cfg_overriden.img_scale = tuple(cfg_overriden.img_scale)
cfg_overriden.dump(cfg_dst_json)

args = [
    "python",
    "github_repos/mmdetection/tools/train.py",
    cfg_dst_json,
]
subprocess.Popen(args, stdout=sys.stdout, stderr=sys.stderr).communicate()
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by awarebayes** [comment]
If you are lookig for a solution I've come up with this monstrosity to dump the config:

```python
def dump_dict_to_openmm_config(overriden_dict, save_path):
    img_scale = tuple(overriden_dict["img_scale"])

    def override_lambda(some_dict, key, value_lambda):
        if isinstance(some_dict, dict):
            for k, v in some_dict.items():
                if k == key:
                    some_dict[k] = value_lambda(some_dict[k])
                elif isinstance(v, dict):
                    some_dict[k] = override_lambda(some_dict[k], key, value_lambda)
                elif isinstance(v, list):
                    some_dict[k] = [override_lambda(x, key, value_lambda) for x in some_dict[k]]
        return some_dict

    def override(some_dict, key, value):
        return override_lambda(some_dict, key, lambda x: value)

    overriden_dict = override(overriden_dict, key="img_scale", value=img_scale)
    overriden_dict = override(overriden_dict, key="dynamic_intervals", value=[(285, 1)])
    overriden_dict = override(overriden_dict, key="workflow", value=[tuple(i) for i in overriden_dict["workflow"]])

    def override_pad_val(pad_val):
        if not isinstance(pad_val, dict):
            return pad_val
        if isinstance(pad_val['img'], list):
            pad_val['img'] = tuple(pad_val['img'])
        return pad_val

    overriden_dict = override_lambda(overriden_dict, key="pad_val", value_lambda=override_pad_val)

    with open(save_path, "w") as f:
        for key, val in overriden_dict.items():
            fmtstr = lambda s: s if not isinstance(s, str) else f'"{s}"'
            f.write(f"{key} = {fmtstr(val)}\n")
```
