### ISSUE TITLE
mmdet库配置'file_client_args': {'backend': 'http'}后仍不能处理http链接输入

### ISSUE THREAD

**Issue by TPL-egg-HIT** [open-mmlab/mmdetection#8570]
感谢mmlab的工作～
我使用mmcls和mmdet训练了几个模型。现在想部署模型，模型的输入为http链接格式
查看文档后，我在mmcls库中修改了test_pipe_line中的         file_client_args=dict( backend='http',)), 后续模型的输入改为http链接，可以使用。
但是我在使用mmdet库部署的时候，修改了相同的cfg配置，运行报错，如下：
![image](https://user-images.githubusercontent.com/41310923/184845414-da23bdf4-fbb6-4bc9-a1f3-d2010849bd75.png)

打印出来的cfg文件如下：
'test_pipeline': [{'type': 'LoadImageFromFile', 'file_client_args': {'backend': 'http'}}, 
我跟进了代码，发现backend调用了disk，没有使用http。
麻烦帮忙看一下，谢谢～

**Comment by TPL-egg-HIT** [comment]
这几天我又看了下代码，发现是config文件读取的问题。infer中的config和我自己的config内容不一致导致，不一致如下：
1. img_norm_cfg，不一致
2. LoadImageFromFile，不一致
但是文件路径等配置还是跟我的配置一致，所以config文件是有一些默认的使用方式嘛？我尝试了很多还未解决。麻烦帮忙看下，谢谢～
@hhaAndroid 
**************************************************************************************************************
运行代码如下：
**************************************************************************************************************
from mmdet.apis import init_detector, inference_detector
import mmcv
import requests as req
from PIL import Image
from io import BytesIO
from mmdet.datasets import replace_ImageToTensor
from mmdet.datasets.pipelines import Compose
from mmdet.models import build_detector

# 指定模型的配置文件和 checkpoint 文件路径
config_file = '../configs/tmp/zhang_faster_rcnn_r50_fpn_1x_coco_2_url.py'
checkpoint_file = '../checkpoints/epoch_12.pth'

# 根据配置文件和 checkpoint 文件构建模型
model = init_detector(config_file, checkpoint_file, device='cpu')

cfg = model.cfg
img = 'http/xxxxxxxxxx'

print('='*50, '111')
test_pipeline = Compose(cfg.data.test.pipeline)
print(cfg.data.train)
print(cfg.data.test.pipeline)
print(test_pipeline)
print('='*50, '222')

result = inference_detector(model, img)


**************************************************************************************************************
打印的信息如下：
**************************************************************************************************************
$python test_sim.py 
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
load checkpoint from local path: ../checkpoints/epoch_12.pth
================================================== 111
{'type': 'RepeatDataset', 'times': 1, 'dataset': {'type': 'CocoDataset', 'ann_file': 'data/red_zhang_2/train/annotations/train.json', 'img_prefix': 'data/red_zhang_2/train/images', 'pipeline': [{'type': 'LoadImageFromFile'}, {'type': 'LoadAnnotations', 'with_bbox': True}, {'type': 'Resize', 'img_scale': [(1333, 640), (1333, 800)], 'multiscale_mode': 'range', 'keep_ratio': True}, {'type': 'RandomFlip', 'flip_ratio': 0.5}, {'type': 'Normalize', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'to_rgb': True}, {'type': 'Pad', 'size_divisor': 32}, {'type': 'DefaultFormatBundle'}, {'type': 'Collect', 'keys': ['img', 'gt_bboxes', 'gt_labels']}], 'classes': ('title_seal', 'comp_seal')}}
[{'type': 'LoadImageFromFile'}, {'type': 'MultiScaleFlipAug', 'img_scale': (1333, 800), 'flip': False, 'transforms': [{'type': 'Resize', 'keep_ratio': True}, {'type': 'RandomFlip'}, {'type': 'Normalize', 'mean': [123.675, 116.28, 103.53], 'std': [58.395, 57.12, 57.375], 'to_rgb': True}, {'type': 'Pad', 'size_divisor': 32}, {'type': 'ImageToTensor', 'keys': ['img']}, {'type': 'Collect', 'keys': ['img']}]}]
Compose(
    LoadImageFromFile(to_float32=False, color_type='color', channel_order='bgr', file_client_args={'backend': 'disk'})
    MultiScaleFlipAug(transforms=Compose(
        Resize(img_scale=None, multiscale_mode=range, ratio_range=None, keep_ratio=True, bbox_clip_border=True)
        RandomFlip(flip_ratio=None)
        Normalize(mean=[123.675 116.28  103.53 ], std=[58.395 57.12  57.375], to_rgb=True)
        Pad(size=None, size_divisor=32, pad_to_square=False, pad_val={'img': 0, 'masks': 0, 'seg': 255})
        ImageToTensor(keys=['img'])
        Collect(keys=['img'], meta_keys=('filename', 'ori_filename', 'ori_shape', 'img_shape', 'pad_shape', 'scale_factor', 'flip', 'flip_direction', 'img_norm_cfg'))
    ), img_scale=[(1333, 800)], flip=False, flip_direction=['horizontal'])
)
================================================== 222
/root/miniconda3/lib/python3.6/site-packages/mmdet/datasets/utils.py:70: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  'data pipeline in your config file.', UserWarning)
Traceback (most recent call last):
  File "test_sim.py", line 60, in <module>
    result = inference_detector(model, img)
  File "/root/miniconda3/lib/python3.6/site-packages/mmdet/apis/inference.py", line 133, in inference_detector
    data = test_pipeline(data)
  File "/root/miniconda3/lib/python3.6/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/root/miniconda3/lib/python3.6/site-packages/mmdet/datasets/pipelines/loading.py", line 67, in __call__
    img_bytes = self.file_client.get(filename)
  File "/root/miniconda3/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 993, in get
    return self.client.get(filepath)
  File "/root/miniconda3/lib/python3.6/site-packages/mmcv/fileio/file_client.py", line 518, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'http://xxxxxx'

**************************************************************************************************************
自己的config文件如下：
**************************************************************************************************************

# 新的配置来自基础的配置以更好地说明需要修改的地方
_base_ = [
    '../common/mstrain_3x_coco.py', '../_base_/models/faster_rcnn_r50_fpn.py'
]



# 2. 模型设置
# 将所有的 `num_classes` 默认值修改为1（原来为80）
model = dict(
    rpn_head=dict(
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.25, 0.5, 1.0, 2.0, 4.0],),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        reg_decoded_bbox=True,      # 使用GIoUI时注意添加
        # loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        loss_bbox=dict(type='GIoULoss', loss_weight=5.0)),
    roi_head=dict(
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            num_classes=2,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            reg_decoded_bbox=True,     # 使用GIoUI时注意添加
            loss_bbox=dict(type='GIoULoss', loss_weight=5.0))),
            # loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
 
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            # nms=dict(type='nms', iou_threshold=0.5),
            nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05),
            max_per_img=100)
        # soft-nms is also supported for rcnn testing
        # e.g., nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05)
    )
)


# 1. 数据集设定
dataset_type = 'CocoDataset'
classes = ('title_seal', 'comp_seal')
# mean = tensor([0.7693, 0.7630, 0.7582]),
# std = tensor([0.2606, 0.2671, 0.2742])
img_norm_cfg = dict(
    mean=[196.17, 194.56, 193.34], std=[66.3, 68.085, 69.92], to_rgb=True)

albu_train_transforms = [
    dict(
        type='HorizontalFlip',
        p=0.5),
    dict(
        type='VerticalFlip',
        p=0.5),

    dict(
        type='ShiftScaleRotate',
        shift_limit=0.0625,
        scale_limit=0.0,
        rotate_limit=180,
        interpolation=1,
        p=0.5),
    dict(
        type='RandomBrightnessContrast',
        brightness_limit=[0.1, 0.3],
        contrast_limit=[0.1, 0.3],
        p=0.2),
    dict(
        type='OneOf',
        transforms=[
            dict(
                type='RGBShift',
                r_shift_limit=10,
                g_shift_limit=10,
                b_shift_limit=10,
                p=1.0),
            dict(
                type='HueSaturationValue',
                hue_shift_limit=20,
                sat_shift_limit=30,
                val_shift_limit=20,
                p=1.0)
        ],
        p=0.1),
    # dict(type='JpegCompression', quality_lower=85, quality_upper=95, p=0.2),

    dict(type='ChannelShuffle', p=0.1),
    dict(
        type='OneOf',
        transforms=[
            dict(type='Blur', blur_limit=3, p=1.0),
            dict(type='MedianBlur', blur_limit=3, p=1.0)
        ],
        p=0.1),
]

# In mstrain 3x config, img_scale=[(1333, 640), (1333, 800)],
# multiscale_mode='range'
train_pipeline = [
    dict(type='LoadImageFromFile',        
        file_client_args=dict(
            backend='http')),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='Resize',
        img_scale=[(1333, 640), (1333, 800)],
        multiscale_mode='range',
        keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(
        type='Albu',
        transforms=albu_train_transforms,
        bbox_params=dict(
            type='BboxParams',
            # format='pascal_voc',
            # label_fields=['gt_labels'],
            format='coco',
            label_fields=['category_id'],
            min_visibility=0.0,
            filter_lost_elements=True),
        keymap={
            'img': 'image',
            'gt_bboxes': 'bboxes'
        },
        update_pad_shape=False,
        skip_img_without_anno=True),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile',
        file_client_args=dict(
            backend='http')),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=1,
        dataset=dict(
            type=dataset_type,
            classes=classes,
            ann_file='data/red_zhang_2/train/annotations/train.json',
            img_prefix='data/red_zhang_2/train/images')),
    val=dict(
        type=dataset_type,
        # 将类别名字添加至 `classes` 字段中
        classes=classes,
        ann_file='data/red_zhang_2/test/annotations/test.json',
        img_prefix='data/red_zhang_2/test/images'),
    test=dict(
        type=dataset_type,
        # 将类别名字添加至 `classes` 字段中
        classes=classes,
        ann_file='data/red_zhang_2/test/annotations/test.json',
        img_prefix='data/red_zhang_2/test/images'))



# load_from = 'checkpoints/faster_rcnn_r50_fpn_mstrain_3x_coco_20210524_110822-e10bd31c.pth'


# 优化器
# batch size 为 8 时的 lr 配置
optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# 学习策略
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[7])
# lr_config 中的 max_epochs 和 step 需要针对自定义数据集进行专门调整
runner = dict(max_epochs=12)
log_config = dict(interval=100)
