### ISSUE TITLE
using dish_train.sh raise subprocess.CalledProcessError多卡训练报错，单卡训练没出现异常

### ISSUE THREAD

**Issue by dkw-wkd** [open-mmlab/mmdetection#8657]
runner = dict(type='EpochBasedRunner', max_epochs=24)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=True, base_batch_size=16)
work_dir = './out/faster_rcnn_r101_fpn_2x_object365'
auto_resume = False
gpu_ids = range(0, 4)

2022-08-29 05:53:33,263 - mmdet - INFO - Set random seed to 0, deterministic: False
2022-08-29 05:53:34,031 - mmdet - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet101'}
2022-08-29 05:53:34,031 - mmcv - INFO - load model from: torchvision://resnet101
2022-08-29 05:53:34,031 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet101
2022-08-29 05:53:37,636 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2022-08-29 05:53:37,677 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-08-29 05:53:37,697 - mmdet - INFO - initialize RPNHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01}
2022-08-29 05:53:37,702 - mmdet - INFO - initialize Shared2FCBBoxHead with init_cfg [{'type': 'Normal', 'std': 0.01, 'override': {'name': 'fc_cls'}}, {'type': 'Normal', 'std': 0.001, 'override': {'name': 'fc_reg'}}, {'type': 'Xavier', 'distribution': 'uniform', 'override': [{'name': 'shared_fcs'}, {'name': 'cls_fcs'}, {'name': 'reg_fcs'}]}]
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Killing subprocess 49397
Killing subprocess 49398
Killing subprocess 49399
Killing subprocess 49400
Traceback (most recent call last):
  File "/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/sensebee2/dinghaojie/anaconda3/envs/openmmdetection/bin/python', '-u', './tools/train.py', '--local_rank=3', './train_dirs/faster_rcnn_r101_fpn_2x_object365/faster_rcnn_r101_fpn_2x_object365.py', '--seed', '0', '--launcher', 'pytorch']' died with <Signals.SIGKILL: 9>.

**Comment by dkw-wkd** [comment]
单gpu训练的时候未出现异常，但是多gpu训练时报错了
