### ISSUE TITLE
assert hasattr(value, 'numel') and value.numel() == 1

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmdetection#8664]
```shell

---------------iou_thr: 0.95---------------
08/30 02:37:24 - mmengine - INFO - 
+-------+-----+------+--------+-------+
| class | gts | dets | recall | ap    |
+-------+-----+------+--------+-------+
| table | 449 | 3880 | 0.004  | 0.000 |
+-------+-----+------+--------+-------+
| mAP   |     |      |        | 0.000 |
+-------+-----+------+--------+-------+
Traceback (most recent call last):
  File "/home/elaine/miniconda3/envs/mmdet-yolo/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/elaine/miniconda3/envs/mmdet-yolo/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/elaine/.vscode/extensions/ms-python.python-2022.12.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "tools/train.py", line 120, in <module>
    main()
  File "tools/train.py", line 116, in main
    runner.train()
  File "/project/openmmlab2/mmengine/mmengine/runner/runner.py", line 1631, in train
    model = self.train_loop.run()  # type: ignore
  File "/project/openmmlab2/mmengine/mmengine/runner/loops.py", line 94, in run
    self.runner.val_loop.run()
  File "/project/openmmlab2/mmengine/mmengine/runner/loops.py", line 347, in run
    self.runner.call_hook('after_val_epoch', metrics=metrics)
  File "/project/openmmlab2/mmengine/mmengine/runner/runner.py", line 1693, in call_hook
    getattr(hook, fn_name)(self, **kwargs)
  File "/project/openmmlab2/mmengine/mmengine/hooks/runtime_info_hook.py", line 115, in after_val_epoch
    runner.message_hub.update_scalar(f'val/{key}', value)
  File "/project/openmmlab2/mmengine/mmengine/logging/message_hub.py", line 139, in update_scalar
    checked_value = self._get_valid_value(value)
  File "/project/openmmlab2/mmengine/mmengine/logging/message_hub.py", line 338, in _get_valid_value
    assert hasattr(value, 'numel') and value.numel() == 1
AssertionError
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb:                                                                                
wandb: 
wandb: Run history:
wandb:           acc █▇▁▆▆█
wandb:     data_time ▂█▁▁▁▁
wandb:         epoch ▁▁▁▁▁▁
wandb:          loss █▂▃▂▁▁
wandb:     loss_bbox ▁▇█▅▅▄
wandb:      loss_cls █▂▄▂▁▁
wandb: loss_rpn_bbox █▃██▁▂
wandb:  loss_rpn_cls █▁▁▁▁▁
wandb:            lr ▁▂▄▅▇█
wandb:          time ▁█▁▁▃▁
wandb: 
wandb: Run summary:
wandb:           acc 98.24219
wandb:     data_time 0.0028
wandb:         epoch 1
wandb:          loss 0.1954
wandb:     loss_bbox 0.06718
wandb:      loss_cls 0.07565
wandb: loss_rpn_bbox 0.03021
wandb:  loss_rpn_cls 0.02236
wandb:            lr 0.01199
wandb:          time 0.33906
wandb: 
wandb: Synced true-totem-21: http://localhost:8080/vansin/mmdetection-tools/runs/2gczk992
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./work_dirs/faster-rcnn_r50_fpn_1x_coco/20220830_023329/vis_data/wandb/run-20220830_023351-2gczk992/logs

```

**Comment by vansin** [comment]
solve this problem by converting the eval_results from np.float64 to float
