### ISSUE TITLE
Question about pad_shape

### ISSUE THREAD

**Issue by my-hello-world** [open-mmlab/mmdetection#868]
I use coco datasets with instances_minival2014.json  but I got error as following:
```
2019-06-25 15:40:49,333 - INFO - Epoch [1][1100/2476]	lr: 0.00250, eta: 18:47:20, time: 2.419, data_time: 0.036, memory: 4873, loss_rpn_cls: 0.1301, loss_rpn_bbox: 0.0608, s0.loss_cls: 0.5617, s0.acc: 90.4805, s0.loss_bbox: 0.1975, s0.loss_mask: 0.5710, s1.loss_cls: 0.2107, s1.acc: 92.9980, s1.loss_bbox: 0.1178, s1.loss_mask: 0.2874, s2.loss_cls: 0.0675, s2.acc: 95.9551, s2.loss_bbox: 0.0301, s2.loss_mask: 0.1507, loss: 2.3854
Traceback (most recent call last):
  File "/media/data/helloworld_/mmdetection/tools/train2.py", line 100, in <module>
    main()
  File "/media/data/helloworld_/mmdetection/tools/train2.py", line 96, in main
    logger=logger)
  File "/media/data/helloworld_/mmdetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/media/data/helloworld_/mmdetection/mmdet/apis/train.py", line 202, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 258, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/data/helloworld_/mmdetection/mmdet/datasets/custom.py", line 169, in __getitem__
    data = self.prepare_train_img(idx)
  File "/media/data/helloworld_/mmdetection/mmdet/datasets/custom.py", line 240, in prepare_train_img
    scale_factor, flip)
  File "/media/data/helloworld_/mmdetection/mmdet/datasets/transforms.py", line 109, in __call__
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/media/data/helloworld_/mmdetection/mmdet/datasets/transforms.py", line 109, in <listcomp>
    mmcv.impad(mask, pad_shape[:2], pad_val=0) for mask in masks
  File "/home/hello/.conda/envs/torch1.1/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/image/transforms/geometry.py", line 183, in impad
    **assert shape[i] >= img.shape[i]
AssertionError**

```
I just made the following changes：
```
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_minival2014.json',
        img_prefix=data_root + 'val2014/',
        # (long_edge, short_edge) or [(long1, short1), (long2, short2), ...]
        img_scale=(1333, 800),#
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0.5,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    val=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_minival2014.json',
        img_prefix=data_root + 'val2014/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=True,
        with_crowd=True,
        with_label=True),
    test=dict(
        type=dataset_type,
        ann_file=data_root + 'annotations/instances_minival2014.json',
        img_prefix=data_root + 'val2014/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True))
```

**Comment by hellock** [comment]
#482
