### ISSUE TITLE
UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.   'data pipeline in your config file.', UserWarning)

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8706]
I understand that this is an error message

Will not affect

But I don't want to see and solve this prompt

**Comment by vansin** [comment]
please try to replace ImageToTensor with DefaultFormatBundle in  config files~

**Comment by monkeycc** [comment]
`dict(type='ImageToTensor', keys=['img']),`
replace 
dict(type='DefaultFormatBundle', keys=['img']),

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\test_time_aug.py", line 60, in __init__
    self.transforms = Compose(transforms)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2.py", line 22, in <module>
    result = inference_detector(model, img)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\apis\inference.py", line 121, in inference_detector
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MultiScaleFlipAug: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'
```

**Comment by monkeycc** [comment]
`dict(type='ImageToTensor', keys=['img']),`
replace 
`dict(type='DefaultFormatBundle', keys=['img']),
`
```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\test_time_aug.py", line 60, in __init__
    self.transforms = Compose(transforms)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2.py", line 22, in <module>
    result = inference_detector(model, img)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\apis\inference.py", line 121, in inference_detector
    test_pipeline = Compose(cfg.data.test.pipeline)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 23, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "D:\Anaconda3\envs\MM\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MultiScaleFlipAug: DefaultFormatBundle: __init__() got an unexpected keyword argument 'keys'
```

**Comment by vansin** [comment]
sorry, I can't solve this problem, and I will send this issue to mmdet core developer

**Comment by vansin** [comment]
please provide the log after you run the train.py

**Comment by monkeycc** [comment]
[mask_rcnn_r50_fpn_1x_coco.zip](https://github.com/open-mmlab/mmdetection/files/9474622/mask_rcnn_r50_fpn_1x_coco.zip)

**Comment by vansin** [comment]
> [mask_rcnn_r50_fpn_1x_coco.zip](https://github.com/open-mmlab/mmdetection/files/9474622/mask_rcnn_r50_fpn_1x_coco.zip)

Thanks ,I will run this conig

```python
model = dict(
    type='MaskRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=13,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=14, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        mask_head=dict(
            type='FCNMaskHead',
            num_convs=4,
            in_channels=256,
            conv_out_channels=256,
            num_classes=13,
            loss_mask=dict(
                type='CrossEntropyLoss', use_mask=True, loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            mask_size=28,
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100,
            mask_thr_binary=0.5)))
dataset_type = 'CocoDataset'
data_root = 'E:/MM/Biaozhu_OK_cocoCOCO/'
classes = ('TouXiongJia', 'FuJie_Xiao', 'FuJie', 'WeiJie', 'TouJian', 'WeiBa',
           'YanSE', 'TouXiongJia2', 'FuJie_Xiao2', 'FuJie2', 'WeiJie2',
           'WeiBa2', 'TouJian2')
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='CocoDataset',
        classes=('TouXiongJia', 'FuJie_Xiao', 'FuJie', 'WeiJie', 'TouJian',
                 'WeiBa', 'YanSE', 'TouXiongJia2', 'FuJie_Xiao2', 'FuJie2',
                 'WeiJie2', 'WeiBa2', 'TouJian2'),
        ann_file=
        'E:/MM/Biaozhu_OK_cocoCOCO/annotations/instances_train2017.json',
        img_prefix='E:/MM/Biaozhu_OK_cocoCOCO/train2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(
                type='Collect',
                keys=['img', 'gt_bboxes', 'gt_labels', 'gt_masks'])
        ]),
    val=dict(
        type='CocoDataset',
        classes=('TouXiongJia', 'FuJie_Xiao', 'FuJie', 'WeiJie', 'TouJian',
                 'WeiBa', 'YanSE', 'TouXiongJia2', 'FuJie_Xiao2', 'FuJie2',
                 'WeiJie2', 'WeiBa2', 'TouJian2'),
        ann_file=
        'E:/MM/Biaozhu_OK_cocoCOCO/annotations/instances_val2017.json',
        img_prefix='E:/MM/Biaozhu_OK_cocoCOCO/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='CocoDataset',
        classes=('TouXiongJia', 'FuJie_Xiao', 'FuJie', 'WeiJie', 'TouJian',
                 'WeiBa', 'YanSE', 'TouXiongJia2', 'FuJie_Xiao2', 'FuJie2',
                 'WeiJie2', 'WeiBa2', 'TouJian2'),
        ann_file=
        'E:/MM/Biaozhu_OK_cocoCOCO/annotations/instances_val2017.json',
        img_prefix='E:/MM/Biaozhu_OK_cocoCOCO/val2017/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
evaluation = dict(metric=['bbox', 'segm'])
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=24)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 2)]
opencv_num_threads = 0
mp_start_method = 'fork'
auto_scale_lr = dict(enable=False, base_batch_size=16)
work_dir = './work_dirs\mask_rcnn_r50_fpn_1x_coco'
auto_resume = False
gpu_ids = [0]
```

**Comment by BIGWangYuDong** [comment]
the DefaultFormatBundle do not need to set keys . you can refer to the code as :https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/configs/_base_/datasets/coco_detection.py#L13 

More DefaultFormatBundle  codes you can refer to  https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/datasets/pipelines/formatting.py#L191-L198
