### ISSUE TITLE
TypeError: CocoDataset2: load_annotations() missing 1 required positional argument: 'ann_file'

### ISSUE THREAD

**Issue by marouaneamz** [open-mmlab/mmdetection#8712]
# Scenario 
my algorithm it's a bit too complicated because i'm trying to merge mmdet and mmcls , i don't understand why we confuse between the load_annotatios in customdataset and  load_annotatios in CocoDataset2

my idea is to use coco.py from mmdet in place of imagent from mmcls with custom and datsets from mmcls

# Actaual : 

here is the beginning of my code I have a problem from the beginning with the arguments
```
from mmdet.core import eval_recalls
from mmdet.datasets.api_wrappers import COCO, COCOeval
from mmcls.datasets.builder import DATASETS
from mmcls.datasets.custom import CustomDataset


@DATASETS.register_module()
class CocoDataset2(CustomDataset):

    CLASSES = [
        "advert",
        "box_start_horse",
        "end_carriage",
        "end_horse"
        "group_heat_carriage",
        "group_heat_horse",
        "heat_carriage",
        "heat_horse",
        "interview",
        "orthogonal_start_carriage",
        "orthogonal_start_horse",
        "paddock",
        "presenters",
        "race_carriage",
        "race_horse",
        "slide",
        "truck_start_carriage",
        "walking_horse",
        "winnerslide"

    ]
    def __init__(self,ann_file = None, **kwargs):
        self.img_cache_prefix = kwargs.pop('img_cache_prefix')
        super(CocoDataset2,self).__init__(**{'data_prefix': self.img_cache_prefix, **kwargs})
        print(self.ann_file)

    def load_annotations(self, ann_file):
        """Load annotation from COCO style annotation file.
        Args:
            ann_file (str): Path of annotation file.
        Returns:
            list[dict]: Annotation info from COCO api....
        """
```

### ERROR : 
```
Traceback (most recent call last):
  File "/home/marouane/dev/mdl-py-classification/model/mobile/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "../../datasets/coco.py", line 49, in __init__
    super(CocoDataset2,self).__init__(**{'data_prefix': self.img_cache_prefix, **kwargs})
  File "/home/marouane/dev/mmclassification/mmcls/datasets/custom.py", line 170, in __init__
    test_mode=test_mode)
  File "/home/marouane/dev/mmclassification/mmcls/datasets/base_dataset.py", line 51, in __init__

    self.data_infos = self.load_annotations()
TypeError: load_annotations() missing 1 required positional argument: 'ann_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mobilenet.py", line 80, in <module>
    datasets = [build_dataset(cfg.data.train)]
  File "/home/marouane/dev/mmclassification/mmcls/datasets/builder.py", line 55, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/marouane/dev/mdl-py-classification/model/mobile/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: CocoDataset2: load_annotations() missing 1 required positional argument: 'ann_file
```

**Comment by BIGWangYuDong** [comment]
according to codes: https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/datasets/custom.py#L59-L70
you should set ann_file, try to use `super().__init__(ann_file=ann_file, **xxxx)

**Comment by marouaneamz** [comment]
> according to codes:
> 
> https://github.com/open-mmlab/mmdetection/blob/df28da98926bc410e16bed1e9fc7d425d9a89495/mmdet/datasets/custom.py#L59-L70
> 
> 
> you should set ann_file, try to use `super().__init__(ann_file=ann_file, **xxxx)` in your dataset

I think I have a confusion with [load_annotation in basedasets](https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/mmcls/datasets/base_dataset.py#L51) and [load_annotations in coco.py](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L62)

**Comment by BIGWangYuDong** [comment]
MMClassification and MMDetection have different settings in OpenMMLab 1.0. So you can try to use MMDet 3.x and MMCls 1.x, because the loading logic is unified.
