### ISSUE TITLE
 The `num_classes` (80) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 1) in CocoDataset

### ISSUE THREAD

**Issue by monkeycc** [open-mmlab/mmdetection#8734]
`python tools/train.py configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py`
```
classes = ("CP",)
num_classes=1
```

```

2022-09-04 22:10:33,384 - mmdet - INFO - workflow: [('train', 2)], max: 24 epochs
2022-09-04 22:10:33,384 - mmdet - INFO - Checkpoints will be saved to E:\MM\mmdetection\work_dirs\faster_rcnn_r50_fpn_1x_coco by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 242, in <module>
    main()
  File "tools/train.py", line 238, in main
    meta=meta)
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmdet\apis\train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 47, in train
    self.call_hook('before_train_epoch')
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmdet\datasets\utils.py", line 158, in before_train_epoch
    self._check_head(runner)
  File "D:\anaconda308\envs\open-mmlab\lib\site-packages\mmdet\datasets\utils.py", line 145, in _check_head
    (f'The `num_classes` ({module.num_classes}) in '
AssertionError: The `num_classes` (80) in Shared2FCBBoxHead of MMDataParallel does not matches the length of `CLASSES` 1) in CocoDataset
```

````
# `../_base_/models/faster_rcnn_r50_fpn.py`
# model settings
model = dict(
    type='FastRCNN',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=1,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0., 0., 0., 0.],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
    # model training and testing settings
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))

```

```
#  '../_base_/datasets/coco_detection.py',
# dataset settings
dataset_type = 'CocoDataset'
data_root = 'E:/MM/coco/'

# 
# classes = ['CP']
classes = ("CP",)
# 
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/instances_train2017.json',
        img_prefix=data_root + 'train2017/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/instances_val2017.json',
        img_prefix=data_root + 'val2017/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations/instances_test2017.json',
        img_prefix=data_root + 'test2017/',
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='bbox')

```

**Comment by BIGWangYuDong** [comment]
The config file is normal. Please check whether you have used the correct config file during training.

**Comment by BIGWangYuDong** [comment]
You can check whether your num_classes = 1 in your log file

**Comment by Wanghy118** [comment]
Hi, have you solved this problem？ Can you teach me?
