### ISSUE TITLE
Multi GPU training problem

### ISSUE THREAD

**Issue by vadik6666** [open-mmlab/mmdetection#878]
After running `CUDA_VISIBLE_DEVICES=0,1,2,3 ./tools/dist_train.sh configs/wider/retinanet_r50_fpn_1x_wider.py 1`
- imgs_per_gpu=2
- working inside docker container
- using proxy
```
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 61, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/other/study/mmdetection-wider/mmdet/apis/env.py", line 17, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/apis/env.py", line 31, in _init_dist_pytorch
    dist.init_process_group(backend=backend, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/wider/retinanet_r50_fpn_1x_wider.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```
How can I fix it?

**Comment by ferranrigual** [comment]
Just today I also found this message:
"RuntimeError: Address already in use"

And what I did is kill all the python3 processes in my docker container using:
ps -efa | grep python3 | cut -d" " -f7 | xargs kill -9

**Comment by vadik6666** [comment]
@ferranrigual did it fix the problem?

**Comment by ferranrigual** [comment]
Yes

**Comment by vadik6666** [comment]
Now 4-gpu training seems to work for while. But at some iteration fails:
```
2019-06-27 08:28:20,685 - INFO - Epoch [1][233/3221]    lr: 0.00488, eta: 10:26:40, time: 0.459, data_time: 0.009, memory: 9847, loss_cls: 0.9253, loss_bbox: 0.4023, loss: 1.3276
2019-06-27 08:28:21,119 - INFO - Epoch [1][234/3221]    lr: 0.00489, eta: 10:26:22, time: 0.433, data_time: 0.009, memory: 9847, loss_cls: 0.7693, loss_bbox: 0.4059, loss: 1.1752
2019-06-27 08:28:21,557 - INFO - Epoch [1][235/3221]    lr: 0.00489, eta: 10:26:05, time: 0.437, data_time: 0.011, memory: 9847, loss_cls: 0.9918, loss_bbox: 0.3871, loss: 1.3789
Traceback (most recent call last):
  File "./tools/train.py", line 95, in <module>
    main()
  File "./tools/train.py", line 91, in main
    logger=logger)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 59, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 171, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
 File "/root/miniconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/parallel/distributed.py", line 50, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/models/detectors/single_stage.py", line 55, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/other/study/mmdetection-wider/mmdet/models/anchor_heads/anchor_head.py", line 177, in loss
    sampling=self.sampling)
  File "/home/other/study/mmdetection-wider/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/home/other/study/mmdetection-wider/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/other/study/mmdetection-wider/mmdet/core/anchor/anchor_target.py", line 120, in anchor_target_single
    gt_bboxes_ignore, gt_labels)
  File "/home/other/study/mmdetection-wider/mmdet/core/bbox/assigners/max_iou_assigner.py", line 76, in assign
    overlaps = bbox_overlaps(gt_bboxes, bboxes)
  File "/home/other/study/mmdetection-wider/mmdet/core/bbox/geometry.py", line 51, in bbox_overlaps
    wh = (rb - lt + 1).clamp(min=0)  # [rows, cols, 2]
RuntimeError: CUDA out of memory. Tried to allocate 2.96 GiB (GPU 2; 10.92 GiB total capacity; 8.71 GiB already allocated; 1.38 GiB free; 225.64 MiB cached)

```

**Comment by vadik6666** [comment]
With ssd300 config it works - 7 epochs are already trained.
But with retinanet_r50_fpn_1x, and faster_rcnn_r50_fpn_1x_voc0712 configs training fails after some amount of iterations.

**Comment by hellock** [comment]
If you have confirmed that there is only one process running, the reason may just be insufficient memory. You can reduce the batch size.

**Comment by vadik6666** [comment]
@hellock , when I trained it with multiple gpues no other experiments were launched.
As I understood imgs_per_gpu=2 is a default for 11Gb gpu.
The gpu-memory consuming for this retina-config looks strange a little bit. It consumes more and more memory with each iteration, and that is why at some iteration it failes with cuda OOM. I didn't see such behavior with pytorch training before. And I'm not sure decreasing the batch size to 1 can help, because it will fail not at e.g. 100 iteration, but at 1000 iteration

**Comment by hellock** [comment]
Duplicated with #879.

**Comment by ujsyehao** [comment]
your GPU may be used.

**Comment by vadik6666** [comment]
@hellock Hi! How can I train two models in multi-gpu mode on a single node inside one docker-container to avoid `RuntimeError: Address already in use` ? Or I should run multi-gpu experiments inside separate docker-containers?
