### ISSUE TITLE
single gpu retina training problem

### ISSUE THREAD

**Issue by vadik6666** [open-mmlab/mmdetection#879]
I am trying to run `CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/wider/retinanet_r50_fpn_1x_wider.py`
- imgs_per_gpu=2
- 11Gb total gpu memory
- working inside docker container
- using proxy

and got error **at some** iteration:

```
2019-06-26 13:28:45,743 - INFO - Epoch [1][2104/12880]  lr: 0.01000, eta: 1 day, 6:05:06, time: 0.335, data_time: 0.008, memory: 9847, loss_cls: 0.8375, loss_bbox: 0.5142, loss: 1.3517                                            [12/1944]
2019-06-26 13:28:46,084 - INFO - Epoch [1][2105/12880]  lr: 0.01000, eta: 1 day, 6:05:04, time: 0.341, data_time: 0.008, memory: 9847, loss_cls: 0.8220, loss_bbox: 0.8251, loss: 1.6471
2019-06-26 13:28:46,424 - INFO - Epoch [1][2106/12880]  lr: 0.01000, eta: 1 day, 6:05:02, time: 0.340, data_time: 0.008, memory: 9847, loss_cls: 0.7455, loss_bbox: 0.4926, loss: 1.2380
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 262, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/apis/train.py", line 39, in batch_processor
    losses = model(**data)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/models/detectors/base.py", line 84, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/other/study/mmdetection-wider/mmdet/models/detectors/single_stage.py", line 55, in forward_train
    *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/home/other/study/mmdetection-wider/mmdet/models/anchor_heads/anchor_head.py", line 177, in loss
    sampling=self.sampling)
  File "/home/other/study/mmdetection-wider/mmdet/core/anchor/anchor_target.py", line 63, in anchor_target
    unmap_outputs=unmap_outputs)
  File "/home/other/study/mmdetection-wider/mmdet/core/utils/misc.py", line 24, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/home/other/study/mmdetection-wider/mmdet/core/anchor/anchor_target.py", line 120, in anchor_target_single
    gt_bboxes_ignore, gt_labels)
  File "/home/other/study/mmdetection-wider/mmdet/core/bbox/assigners/max_iou_assigner.py", line 76, in assign
    overlaps = bbox_overlaps(gt_bboxes, bboxes)
  File "/home/other/study/mmdetection-wider/mmdet/core/bbox/geometry.py", line 59, in bbox_overlaps
    ious = overlap / (area1[:, None] + area2 - overlap)
RuntimeError: CUDA out of memory. Tried to allocate 882.00 MiB (GPU 0; 10.92 GiB total capacity; 9.67 GiB already allocated; 447.50 MiB free; 200.14 MiB cached)
```
why is it so? This gpu was free all the time from any other procesess.

**Comment by hellock** [comment]
What is your `configs/wider/retinanet_r50_fpn_1x_wider.py`?

**Comment by vadik6666** [comment]
```
# model settings
model = dict(
    type='RetinaNet',
    pretrained='modelzoo://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs=True,
        num_outs=5),
    bbox_head=dict(
        type='RetinaHead',
        num_classes=2,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        octave_base_scale=4,
        scales_per_octave=3,
        anchor_ratios=[0.5, 1.0, 2.0],
        anchor_strides=[8, 16, 32, 64, 128],
        target_means=[.0, .0, .0, .0],
        target_stds=[1.0, 1.0, 1.0, 1.0],
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)))
cudnn_benchmark = True
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.4,
        min_pos_iou=0,
        ignore_iof_thr=-1),
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
test_cfg = dict(
    nms_pre=1000,
    min_bbox_size=0,
    score_thr=0.05,
    nms=dict(type='nms', iou_thr=0.5),
    max_per_img=100)
# model training and testing settings
# dataset settings
dataset_type = 'WIDERDataset'
data_root = 'data/WIDER/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
# img_norm_cfg = dict(
#     mean=[123.675, 116.28, 103.53], std=[1., 1., 1.], to_rgb=True)
data = dict(
    imgs_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='RepeatDataset',
        times=2,
        dataset=dict(
            type=dataset_type,
            ann_file=[
                data_root + 'train.txt',
            ],
            img_prefix=[data_root + 'WIDER_train/'],
            img_scale=(1333, 800),
            img_norm_cfg=img_norm_cfg,
            size_divisor=32,
            flip_ratio=0.5,
            with_mask=False,
            with_crowd=False,
            with_label=True,
            test_mode=False,
            extra_aug=dict(
                photo_metric_distortion=dict(
                    brightness_delta=32,
                    contrast_range=(0.5, 1.5),
                    saturation_range=(0.5, 1.5),
                    hue_delta=18),
                expand=dict(
                    mean=img_norm_cfg['mean'],
                    to_rgb=img_norm_cfg['to_rgb'],
                    ratio_range=(1, 4)),
                random_crop=dict(
                    min_ious=(0.1, 0.3, 0.5, 0.7, 0.9), min_crop_size=0.3)),
            resize_keep_ratio=False)
        ),
    val=dict(
        type=dataset_type,
        ann_file=data_root + '/val.txt',
        img_prefix=data_root + 'WIDER_val/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=True,
        resize_keep_ratio=False),
    test=dict(
        type=dataset_type,
        ann_file=data_root + '/val.txt',
        img_prefix=data_root + 'WIDER_val/',
        img_scale=(1333, 800),
        img_norm_cfg=img_norm_cfg,
        size_divisor=32,
        flip_ratio=0,
        with_mask=False,
        with_label=False,
        test_mode=True,
        resize_keep_ratio=False))
# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=1e-4)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=1.0 / 3,
    step=[16, 20])
checkpoint_config = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 24
# device_ids = range(8)
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/retinanet_r50_fpn_1x_wider'
load_from = None
resume_from = None
workflow = [('train', 1)]


```

**Comment by hellock** [comment]
There may be too many gt bboxes in an image in WIDER FACE, so that you can encounter the OOM issue. Refer to #188 and #583 for solutions.

**Comment by wangYAyuYAxin** [comment]
I wonder to know the map of the model(retinanet_r50_fpn_1x.py) with the voc dataset, and the machine is 1080tiGPU
