### ISSUE TITLE
RuntimeError: cannot perform reduction function kthvalue on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by grwal** [open-mmlab/mmdetection#8851]
After first epoch's 375th log interval, I got this error.
I saw several issues with RuntimeError:cannot perform~~ sentences, but nothing with kthvalue.
I've tried to find where is the operation part which the error mentioning requires 'an identity', but I can't find or even understand the kthvalue is.

Following is my error code

2022-09-21 16:44:21,820 - mmdet - INFO - Epoch [1][25/615]	lr: 4.815e-03, eta: 17:22:44, time: 1.018, data_time: 0.562, memory: 3782, loss_rpn_cls: 0.0418, loss_rpn_bbox: 0.0091, loss_cls: 0.5189, acc: 80.4062, loss_bbox: 0.1758, loss: 0.7456
2022-09-21 16:44:32,298 - mmdet - INFO - Epoch [1][50/615]	lr: 9.810e-03, eta: 12:16:38, time: 0.421, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0201, loss_rpn_bbox: 0.0104, loss_cls: 0.2845, acc: 90.6367, loss_bbox: 0.2034, loss: 0.5185
2022-09-21 16:44:42,997 - mmdet - INFO - Epoch [1][75/615]	lr: 1.481e-02, eta: 10:36:11, time: 0.426, data_time: 0.010, memory: 3782, loss_rpn_cls: 0.0182, loss_rpn_bbox: 0.0105, loss_cls: 0.3182, acc: 89.6758, loss_bbox: 0.1908, loss: 0.5376
2022-09-21 16:44:53,771 - mmdet - INFO - Epoch [1][100/615]	lr: 1.980e-02, eta: 9:47:07, time: 0.431, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0293, loss_rpn_bbox: 0.0102, loss_cls: 0.2734, acc: 91.6953, loss_bbox: 0.1290, loss: 0.4419
2022-09-21 16:45:04,188 - mmdet - INFO - Epoch [1][125/615]	lr: 2.000e-02, eta: 9:14:58, time: 0.418, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0182, loss_rpn_bbox: 0.0081, loss_cls: 0.4470, acc: 85.3711, loss_bbox: 0.4447, loss: 0.9180
2022-09-21 16:45:14,542 - mmdet - INFO - Epoch [1][150/615]	lr: 2.000e-02, eta: 8:52:52, time: 0.414, data_time: 0.011, memory: 3782, loss_rpn_cls: 0.0222, loss_rpn_bbox: 0.0113, loss_cls: 0.4452, acc: 86.8633, loss_bbox: 0.4314, loss: 0.9102
2022-09-21 16:45:25,066 - mmdet - INFO - Epoch [1][175/615]	lr: 2.000e-02, eta: 8:38:02, time: 0.421, data_time: 0.011, memory: 3782, loss_rpn_cls: 0.0330, loss_rpn_bbox: 0.0129, loss_cls: 0.4893, acc: 86.5547, loss_bbox: 0.4532, loss: 0.9883
2022-09-21 16:45:35,560 - mmdet - INFO - Epoch [1][200/615]	lr: 2.000e-02, eta: 8:26:29, time: 0.418, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0277, loss_rpn_bbox: 0.0117, loss_cls: 0.3739, acc: 90.3047, loss_bbox: 0.3466, loss: 0.7600
2022-09-21 16:45:46,006 - mmdet - INFO - Epoch [1][225/615]	lr: 2.000e-02, eta: 8:17:32, time: 0.419, data_time: 0.013, memory: 3782, loss_rpn_cls: 0.0238, loss_rpn_bbox: 0.0100, loss_cls: 0.4849, acc: 83.7969, loss_bbox: 0.5372, loss: 1.0559
2022-09-21 16:45:56,663 - mmdet - INFO - Epoch [1][250/615]	lr: 2.000e-02, eta: 8:11:10, time: 0.427, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0219, loss_rpn_bbox: 0.0119, loss_cls: 0.4514, acc: 83.8867, loss_bbox: 0.4647, loss: 0.9498
2022-09-21 16:46:07,248 - mmdet - INFO - Epoch [1][275/615]	lr: 2.000e-02, eta: 8:05:34, time: 0.423, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0252, loss_rpn_bbox: 0.0099, loss_cls: 0.4421, acc: 86.3750, loss_bbox: 0.4326, loss: 0.9099
2022-09-21 16:46:17,882 - mmdet - INFO - Epoch [1][300/615]	lr: 2.000e-02, eta: 8:01:08, time: 0.426, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0294, loss_rpn_bbox: 0.0119, loss_cls: 0.4095, acc: 87.7891, loss_bbox: 0.3627, loss: 0.8135
2022-09-21 16:46:28,303 - mmdet - INFO - Epoch [1][325/615]	lr: 2.000e-02, eta: 7:56:38, time: 0.417, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0143, loss_rpn_bbox: 0.0076, loss_cls: 0.4073, acc: 86.5547, loss_bbox: 0.4018, loss: 0.8309
2022-09-21 16:46:38,868 - mmdet - INFO - Epoch [1][350/615]	lr: 2.000e-02, eta: 7:53:09, time: 0.422, data_time: 0.011, memory: 3782, loss_rpn_cls: 0.0214, loss_rpn_bbox: 0.0110, loss_cls: 0.4407, acc: 85.3281, loss_bbox: 0.4119, loss: 0.8850
2022-09-21 16:46:49,499 - mmdet - INFO - Epoch [1][375/615]	lr: 2.000e-02, eta: 7:50:16, time: 0.425, data_time: 0.012, memory: 3782, loss_rpn_cls: 0.0182, loss_rpn_bbox: 0.0086, loss_cls: 0.4224, acc: 85.1367, loss_bbox: 0.3869, loss: 0.8361
Traceback (most recent call last):
  File "C:/Users/bong06/Desktop/Baseline/Train/train.py", line 97, in <module>
    run()
  File "C:/Users/bong06/Desktop/Baseline/Train/train.py", line 94, in run
    train_detector(model, datasets[0], cfg, distributed=False, validate=True)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\apis\train.py", line 208, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\parallel\data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\detectors\base.py", line 248, in train_step
    losses = self(**data)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\detectors\base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\detectors\two_stage.py", line 147, in forward_train
    roi_losses = self.roi_head.forward_train(x, img_metas, proposal_list,
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\roi_heads\dynamic_roi_head.py", line 90, in forward_train
    bbox_results = self._bbox_forward_train(x, sampling_results,
  File "C:\Users\bong06\anaconda3\envs\open-mmlab\lib\site-packages\mmdet\models\roi_heads\dynamic_roi_head.py", line 125, in _bbox_forward_train
    cur_target = torch.kthvalue(cur_target, beta_topk)[0].item()
**RuntimeError: cannot perform reduction function kthvalue on tensor with no elements because the operation does not have an identity**

Is there anyone who met this error or able to deal with this? So appreciate in advance

**Comment by jbwang1997** [comment]
Could you provide more information, like your environment, following the issue template?

**Comment by grwal** [comment]
> Could you provide more information, like your environment, following the issue template?

After that I tried to follow the error route, and printed img_metas. And then I found from specific annotation ids are not sequential. I think this is the problem, so I will try to make a new coco dataset for that! Thank you for your favor
