### ISSUE TITLE
hi，question about  train  cascade_mask_rcnn_r101_fpn_1x.py

### ISSUE THREAD

**Issue by nuist-xinyu** [open-mmlab/mmdetection#888]
loading annotations into memory...
Done (t=0.79s)
creating index...
index created!
2019-06-28 10:10:26,047 - INFO - Start running, host: xinyu@xinyu-MS-7B89, work_dir: /home/xinyu/mmdetection/work_dirs/cascade_mask_rcnn_r101_fpn_1x
2019-06-28 10:10:26,047 - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    main()
  File "train.py", line 94, in main
    logger=logger)
  File "/home/xinyu/mmdetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/xinyu/mmdetection/mmdet/apis/train.py", line 197, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 356, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 258, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
Exception: Traceback (most recent call last):
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xinyu/mmdetection/mmdet/datasets/custom.py", line 169, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/xinyu/mmdetection/mmdet/datasets/custom.py", line 197, in prepare_train_img
    ann = self.get_ann_info(idx)
  File "/home/xinyu/mmdetection/mmdet/datasets/coco.py", line 29, in get_ann_info
    return self._parse_ann_info(ann_info, self.with_mask)
  File "/home/xinyu/mmdetection/mmdet/datasets/coco.py", line 75, in _parse_ann_info
    gt_masks.append(self.coco.annToMask(ann))
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 431, in annToMask
    rle = self.annToRLE(ann)
  File "/home/xinyu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 307, in pycocotools._mask.frPyObjects
Exception: input type is not supported.

**Comment by hellock** [comment]
Did you train with COCO dataset or some custom dataset? It seems there are some issues with the annotation.

**Comment by nuist-xinyu** [comment]
> Did you train with COCO dataset or some custom dataset? It seems there are some issues with the annotation.
hello，author  thank you reply me
I think  no problem with my annotation.Because I am running very well under the faster rcnn

**Comment by hellock** [comment]
Faster R-CNN is irrelevant to the mask annotations.

**Comment by nuist-xinyu** [comment]
> Faster R-CNN is irrelevant to the mask annotations.

Oh, hahahahahaha.
That's it, thank you.

**Comment by wzr0108** [comment]
i mei the same problem, have you solved it?
