### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by iumyx2612** [open-mmlab/mmdetection#8885]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

First time ran into this bug, I was using mmdet normally until today. I just train any model with pretrain initialize 
```
2022-09-26 22:26:58,399 - mmdet - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2022-09-26 22:26:58,399 - mmcv - INFO - load model from: torchvision://resnet50
2022-09-26 22:26:58,400 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
Traceback (most recent call last):
  File "E:/Work work/Python/Work/Practice/Object Detection/detection/tools/train.py", line 242, in <module>
    main()
  File "E:/Work work/Python/Work/Practice/Object Detection/detection/tools/train.py", line 216, in main
    model.init_weights()
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\base_module.py", line 116, in init_weights
    m.init_weights()
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\base_module.py", line 105, in init_weights
    initialize(self, self.init_cfg)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 613, in initialize
    _initialize(module, cp_cfg)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 517, in _initialize
    func(module)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\cnn\utils\weight_init.py", line 489, in __call__
    load_checkpoint(
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\checkpoint.py", line 542, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\checkpoint.py", line 481, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\checkpoint.py", line 251, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\checkpoint.py", line 391, in load_from_torchvision
    model_urls = get_torchvision_models()
  File "E:\Anaconda\envs\openmmlab\lib\site-packages\mmcv\runner\checkpoint.py", line 113, in get_torchvision_models
    _zoo = import_module(f'torchvision.models.{name}')
  File "E:\Anaconda\envs\openmmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'torchvision.models.detection.mmdet'

Process finished with exit code 1
```

### Environment

sys.platform: win32
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
NVCC: Not Available
GCC: n/a
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=
compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_W
INDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSY
MBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCE
PTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0
OpenCV: 4.5.5
MMCV: 1.4.7
MMCV Compiler: MSVC 192930140
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.1+2a011dc

### Additional information

I reinstall torchvision, reinstall mmdet but the bug still happens. I was using mmdet normally before

**Comment by iumyx2612** [comment]
Nvm I fixed it, I changed the root folder name to detection instead of mmdetection, which cause the import error
