### ISSUE TITLE
An error : <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by peiyingxin** [open-mmlab/mmdetection#8916]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

apper an error when running with DDP  suddenly. 
In this environment, running other python files are all ok, this error appear at specific epoch specific step. It very confused me.

### Environment

fatal: unsafe repository ('/work/mmdetection' is owned by someone else)
To add an exception for this directory, call:
    git config --global --add safe.directory /work/mmdetection
sys.platform: linux
Python: 3.8.5 (default, Sep  4 2020, 07:30:14) [GCC 7.3.0]
CUDA available: True    
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda          
NVCC: Cuda compilation tools, release 11.0, V11.0.221
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;
arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;ar
ch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2
OpenCV: 4.6.0
MMCV: 1.6.1
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.25.0+

**Comment by peiyingxin** [comment]
This is training logs, before it's all ok. It appear at specific epoch specific step.

2022-09-30 08:48:44,528 - mmdet - INFO - Epoch [13][250/7330]   lr: 1.000e-04, eta: 1 day, 1:49:05, time: 0.511, data_time: 0.026, memory: 12984,
loss_rpn_cls: 0.0325, loss_rpn_bbox: 0.0390, loss_cls: 0.1931, acc: 93.1592, loss_bbox: 0.2324, loss_mask: 0.2375, loss: 0.7345
2022-09-30 08:49:10,145 - mmdet - INFO - Epoch [13][300/7330]   lr: 1.000e-04, eta: 1 day, 1:40:39, time: 0.513, data_time: 0.026, memory: 12984,
loss_rpn_cls: 0.0326, loss_rpn_bbox: 0.0400, loss_cls: 0.1931, acc: 93.1221, loss_bbox: 0.2344, loss_mask: 0.2319, loss: 0.7320
2022-09-30 08:49:35,657 - mmdet - INFO - Epoch [13][350/7330]   lr: 1.000e-04, eta: 1 day, 1:33:17, time: 0.510, data_time: 0.026, memory: 12984,
loss_rpn_cls: 0.0283, loss_rpn_bbox: 0.0389, loss_cls: 0.1920, acc: 93.3005, loss_bbox: 0.2284, loss_mask: 0.2306, loss: 0.7183
2022-09-30 08:50:00,766 - mmdet - INFO - Epoch [13][400/7330]   lr: 1.000e-04, eta: 1 day, 1:24:57, time: 0.502, data_time: 0.024, memory: 12984,
loss_rpn_cls: 0.0294, loss_rpn_bbox: 0.0378, loss_cls: 0.1908, acc: 93.2974, loss_bbox: 0.2214, loss_mask: 0.2239, loss: 0.7033
2022-09-30 08:50:26,165 - mmdet - INFO - Epoch [13][450/7330]   lr: 1.000e-04, eta: 1 day, 1:20:09, time: 0.508, data_time: 0.025, memory: 13458,
loss_rpn_cls: 0.0303, loss_rpn_bbox: 0.0395, loss_cls: 0.1963, acc: 93.0486, loss_bbox: 0.2309, loss_mask: 0.2276, loss: 0.7245
Traceback (most recent call last):                                                                                                                  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                          return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>                                                    main()                                                                                                                                          File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main                                                        raise subprocess.CalledProcessError(returncode=process.returncode,                                                                            subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'tools/train.py', '--local_rank=7', 'configs/swin/mask_rcnn_swin-b-p4-w7_fpn_fp16_ms-crop-3x_coco.py', '--seed', '0', '--launcher', 'pytorch', '--auto-resume']' died with <Signals.SIGSEGV: 11>.

**Comment by BIGWangYuDong** [comment]
Maybe you can try to upgrade your torch version to 1.8.1 or higher.

**Comment by peiyingxin** [comment]
Yeah, when I update higher torch version, this problem solved.
