### ISSUE TITLE
LOCAL_RANK wrong for mpirun

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmdetection#8940]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

Using `torchrun` works fine to train for me, but after attempting to speed up training with `mpirun` command:

`mpirun -np 4 --allow-run-as-root python /opt/ml/code/mmdetection/tools/train.py /opt/ml/code/mmdetection/configs/yolox/yolox_s_8xb8-300e_coco.py --launcher mpi`

I get RuntimeError's on 3/4 processes, ex:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)`
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument weight in method wrapper__cudnn_convolution)`
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument weight in method wrapper__cudnn_convolution)`

### Environment

v3.0.0rc1

### Additional information
I think this is due to https://github.com/open-mmlab/mmdetection/blob/master/tools/train.py#L95
If I replace this line with:
`os.environ['LOCAL_RANK'] = str(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])`
The error goes away and training begins successfully

------

Traceback:
```
gsb2fnng0z-algo-1-6pcq6 | Traceback (most recent call last):
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 120, in <module>
gsb2fnng0z-algo-1-6pcq6 | main()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 116, in main
gsb2fnng0z-algo-1-6pcq6 | runner.train()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
gsb2fnng0z-algo-1-6pcq6 | model = self.train_loop.run()  # type: ignore
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
gsb2fnng0z-algo-1-6pcq6 | self.run_epoch()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 104, in run_epoch
gsb2fnng0z-algo-1-6pcq6 | self.run_iter(idx, data_batch)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 120, in run_iter
gsb2fnng0z-algo-1-6pcq6 | outputs = self.runner.model.train_step(
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
gsb2fnng0z-algo-1-6pcq6 | losses = self._run_forward(data, mode='loss')
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 162, in _run_forward
gsb2fnng0z-algo-1-6pcq6 | results = self(**data, mode=mode)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
gsb2fnng0z-algo-1-6pcq6 | output = self._run_ddp_forward(*inputs, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
gsb2fnng0z-algo-1-6pcq6 | return module_to_run(*inputs[0], **kwargs[0])
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 91, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.loss(inputs, data_samples)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss
gsb2fnng0z-algo-1-6pcq6 | x = self.extract_feat(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 143, in extract_feat
gsb2fnng0z-algo-1-6pcq6 | x = self.backbone(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 281, in forward
gsb2fnng0z-algo-1-6pcq6 | x = layer(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 64, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 207, in forward
gsb2fnng0z-algo-1-6pcq6 | x = self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
gsb2fnng0z-algo-1-6pcq6 | return self._conv_forward(input, self.weight, self.bias)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
gsb2fnng0z-algo-1-6pcq6 | return F.conv2d(input, weight, bias, self.stride,
gsb2fnng0z-algo-1-6pcq6 | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 | /opt/conda/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
gsb2fnng0z-algo-1-6pcq6 | return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
gsb2fnng0z-algo-1-6pcq6 | Traceback (most recent call last):
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 120, in <module>
gsb2fnng0z-algo-1-6pcq6 | main()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 116, in main
gsb2fnng0z-algo-1-6pcq6 | runner.train()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
gsb2fnng0z-algo-1-6pcq6 | model = self.train_loop.run()  # type: ignore
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
gsb2fnng0z-algo-1-6pcq6 | self.run_epoch()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 104, in run_epoch
gsb2fnng0z-algo-1-6pcq6 | self.run_iter(idx, data_batch)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 120, in run_iter
gsb2fnng0z-algo-1-6pcq6 | outputs = self.runner.model.train_step(
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
gsb2fnng0z-algo-1-6pcq6 | losses = self._run_forward(data, mode='loss')
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 162, in _run_forward
gsb2fnng0z-algo-1-6pcq6 | results = self(**data, mode=mode)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
gsb2fnng0z-algo-1-6pcq6 | output = self._run_ddp_forward(*inputs, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
gsb2fnng0z-algo-1-6pcq6 | return module_to_run(*inputs[0], **kwargs[0])
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 91, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.loss(inputs, data_samples)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss
gsb2fnng0z-algo-1-6pcq6 | x = self.extract_feat(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 143, in extract_feat
gsb2fnng0z-algo-1-6pcq6 | x = self.backbone(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 281, in forward
gsb2fnng0z-algo-1-6pcq6 | x = layer(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 64, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 207, in forward
gsb2fnng0z-algo-1-6pcq6 | x = self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
gsb2fnng0z-algo-1-6pcq6 | return self._conv_forward(input, self.weight, self.bias)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
gsb2fnng0z-algo-1-6pcq6 | return F.conv2d(input, weight, bias, self.stride,
gsb2fnng0z-algo-1-6pcq6 | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 | Traceback (most recent call last):
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 120, in <module>
gsb2fnng0z-algo-1-6pcq6 | main()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/ml/code/mmdetection/tools/train.py", line 116, in main
gsb2fnng0z-algo-1-6pcq6 | runner.train()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
gsb2fnng0z-algo-1-6pcq6 | model = self.train_loop.run()  # type: ignore
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
gsb2fnng0z-algo-1-6pcq6 | self.run_epoch()
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 104, in run_epoch
gsb2fnng0z-algo-1-6pcq6 | self.run_iter(idx, data_batch)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 120, in run_iter
gsb2fnng0z-algo-1-6pcq6 | outputs = self.runner.model.train_step(
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
gsb2fnng0z-algo-1-6pcq6 | losses = self._run_forward(data, mode='loss')
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 162, in _run_forward
gsb2fnng0z-algo-1-6pcq6 | results = self(**data, mode=mode)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
gsb2fnng0z-algo-1-6pcq6 | output = self._run_ddp_forward(*inputs, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
gsb2fnng0z-algo-1-6pcq6 | return module_to_run(*inputs[0], **kwargs[0])
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 91, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.loss(inputs, data_samples)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss
gsb2fnng0z-algo-1-6pcq6 | x = self.extract_feat(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 143, in extract_feat
gsb2fnng0z-algo-1-6pcq6 | x = self.backbone(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 281, in forward
gsb2fnng0z-algo-1-6pcq6 | x = layer(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 64, in forward
gsb2fnng0z-algo-1-6pcq6 | return self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 207, in forward
gsb2fnng0z-algo-1-6pcq6 | x = self.conv(x)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 | return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
gsb2fnng0z-algo-1-6pcq6 | return self._conv_forward(input, self.weight, self.bias)
gsb2fnng0z-algo-1-6pcq6 | File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
gsb2fnng0z-algo-1-6pcq6 | return F.conv2d(input, weight, bias, self.stride,
gsb2fnng0z-algo-1-6pcq6 | RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 | --------------------------------------------------------------------------
gsb2fnng0z-algo-1-6pcq6 | Primary job  terminated normally, but 1 process returned
gsb2fnng0z-algo-1-6pcq6 | a non-zero exit code. Per user-direction, the job has been aborted.
gsb2fnng0z-algo-1-6pcq6 | --------------------------------------------------------------------------
gsb2fnng0z-algo-1-6pcq6 | --------------------------------------------------------------------------
gsb2fnng0z-algo-1-6pcq6 | mpirun.real detected that one or more processes exited with non-zero status, thus causing
gsb2fnng0z-algo-1-6pcq6 | the job to be terminated. The first process to do so was:
gsb2fnng0z-algo-1-6pcq6 | 
gsb2fnng0z-algo-1-6pcq6 | Process name: [[8472,1],2]
gsb2fnng0z-algo-1-6pcq6 | Exit code:    1
gsb2fnng0z-algo-1-6pcq6 | --------------------------------------------------------------------------
gsb2fnng0z-algo-1-6pcq6 | Traceback (most recent call last):
gsb2fnng0z-algo-1-6pcq6 |   File "mmdetection_train.py", line 307, in <module>
gsb2fnng0z-algo-1-6pcq6 | raise subprocess.CalledProcessError(returncode=process.returncode, cmd=joint_cmd)
gsb2fnng0z-algo-1-6pcq6 | subprocess.CalledProcessError
gsb2fnng0z-algo-1-6pcq6 | : Command '['mpirun', '-np', '4', '--allow-run-as-root', 'python', '/opt/ml/code/mmdetection/tools/train.py', '/opt/ml/code/updated_config.py', '--launcher', 'mpi', '--work-dir', '/opt/ml/checkpoints']' returned non-zero exit status 1.
gsb2fnng0z-algo-1-6pcq6 | 2022-10-04 23:27:56,718 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
gsb2fnng0z-algo-1-6pcq6 | 2022-10-04 23:27:56,718 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
gsb2fnng0z-algo-1-6pcq6 | 2022-10-04 23:27:56,719 sagemaker-training-toolkit ERROR    Reporting training FAILURE
gsb2fnng0z-algo-1-6pcq6 | 2022-10-04 23:27:56,719 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
gsb2fnng0z-algo-1-6pcq6 | ExitCode 1
gsb2fnng0z-algo-1-6pcq6 | ErrorMessage "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:2! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 |  /opt/conda/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
gsb2fnng0z-algo-1-6pcq6 |  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
gsb2fnng0z-algo-1-6pcq6 |  Traceback (most recent call last)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/ml/code/mmdetection/tools/train.py", line 120, in <module>
gsb2fnng0z-algo-1-6pcq6 |  main()
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/ml/code/mmdetection/tools/train.py", line 116, in main
gsb2fnng0z-algo-1-6pcq6 |  runner.train()
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
gsb2fnng0z-algo-1-6pcq6 |  model = self.train_loop.run()  # type: ignore
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
gsb2fnng0z-algo-1-6pcq6 |  self.run_epoch()
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 104, in run_epoch
gsb2fnng0z-algo-1-6pcq6 |  self.run_iter(idx, data_batch)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/runner/loops.py", line 120, in run_iter
gsb2fnng0z-algo-1-6pcq6 |  outputs = self.runner.model.train_step(
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 120, in train_step
gsb2fnng0z-algo-1-6pcq6 |  losses = self._run_forward(data, mode='loss')
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 162, in _run_forward
gsb2fnng0z-algo-1-6pcq6 |  results = self(**data, mode=mode)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
gsb2fnng0z-algo-1-6pcq6 |  return forward_call(*input, **kwargs)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
gsb2fnng0z-algo-1-6pcq6 |  output = self._run_ddp_forward(*inputs, **kwargs)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
gsb2fnng0z-algo-1-6pcq6 |  return module_to_run(*inputs[0], **kwargs[0])
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/base.py", line 91, in forward
gsb2fnng0z-algo-1-6pcq6 |  return self.loss(inputs, data_samples)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 77, in loss
gsb2fnng0z-algo-1-6pcq6 |  x = self.extract_feat(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/detectors/single_stage.py", line 143, in extract_feat
gsb2fnng0z-algo-1-6pcq6 |  x = self.backbone(batch_inputs)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 281, in forward
gsb2fnng0z-algo-1-6pcq6 |  x = layer(x)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/csp_darknet.py", line 64, in forward
gsb2fnng0z-algo-1-6pcq6 |  return self.conv(x)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py", line 207, in forward
gsb2fnng0z-algo-1-6pcq6 |  x = self.conv(x)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
gsb2fnng0z-algo-1-6pcq6 |  return self._conv_forward(input, self.weight, self.bias)
gsb2fnng0z-algo-1-6pcq6 |  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
gsb2fnng0z-algo-1-6pcq6 |  return F.conv2d(input, weight, bias, self.stride,
gsb2fnng0z-algo-1-6pcq6 |  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 |  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking argument for argument weight in method wrapper__cudnn_convolution)
gsb2fnng0z-algo-1-6pcq6 |  --------------------------------------------------------------------------
gsb2fnng0z-algo-1-6pcq6 |  Primary job  terminated normally, but 1 process returned
gsb2fnng0z-algo-1-6pcq6 |  a non-zero exit code. Per user-direction, the job has been aborted.
gsb2fnng0z-algo-1-6pcq6 |  mpirun.real detected that one or more processes exited with non-zero status, thus causing
gsb2fnng0z-algo-1-6pcq6 |  the job to be terminated. The first process to do so was
gsb2fnng0z-algo-1-6pcq6 |  
gsb2fnng0z-algo-1-6pcq6 |  Process name: [[8472,1],2]
gsb2fnng0z-algo-1-6pcq6 |  Exit code:    1"
```

**Comment by austinmw** [comment]
Actually seems to be fine when I use mmengine _init_dist_mpi

**Comment by miquel-espinosa** [comment]
@austinmw I am also encountering the same issue.
I can also confirm that when I use `os.environ['LOCAL_RANK'] = str(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])` , the problem goes away, and I can train.
What solution did you end up using? Can you develop more on using **mmengine _init_dist_mpi**? 
Thanks,
