### ISSUE TITLE
compile.sh: ImportError: No module named torch.utils.cpp_extension

### ISSUE THREAD

**Issue by stiv-yakovenko** [open-mmlab/mmdetection#897]
I have successfully installed miniconda and pytorch:
```
../miniconda3/bin/conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
```
but when I run ./compile.sh from mmdetection folder, I get these compile errors:

```
Building roi align op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building roi pool op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building nms op...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
Building dcn...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building sigmoid focal loss op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
Building masked conv op...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ImportError: No module named torch.utils.cpp_extension
```

**Comment by hellock** [comment]
You may check the pytorch version, which should be 1.1 or higher.

**Comment by stiv-yakovenko** [comment]
Solved. The root cause was that $PYTHON variable was pointing to python, not python3. On miniconda python has version 2.7

export PYTHON=/home/xrdp/miniconda3/bin/python3

**Comment by Pamyuu** [comment]
> Solved. The root cause was that $PYTHON variable was pointing to python, not python3. On miniconda python has version 2.7
> 
> export PYTHON=/home/xrdp/miniconda3/bin/python3

how to export?

**Comment by Pamyuu** [comment]
Hi, i checked the python and found that pointing to python3,  but still got the same error
how to solve it? thanks
```
$ python3
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by engrmz** [comment]
> Solved. The root cause was that $PYTHON variable was pointing to python, not python3. On miniconda python has version 2.7
> 
> export PYTHON=/home/xrdp/miniconda3/bin/python3

This solves my problem, thanks :+1:
