### ISSUE TITLE
softteacher in 3.x error because can‘t send empty gt

### ISSUE THREAD

**Issue by zhaogev5** [open-mmlab/mmdetection#9121]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmdetection/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmdetection).

### 🐞 Describe the bug

I use your soft teacher code，but when in my own dataset，it doesn't work
I think the reason is when using coco pretrain it work but when in a new dataset,if there is no GT,may have the bug below.
Traceback (most recent call last):
  File "./tools/train.py", line 120, in <module>
    main()
  File "./tools/train.py", line 116, in main
    runner.train()
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 259, in run
    data_batch = next(self.dataloader_iterator)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 156, in __next__
    data = next(self._iterator)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/dataset_wrapper.py", line 131, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 408, in __getitem__
    data = self.prepare_data(idx)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 789, in prepare_data
    return self.pipeline(data_info)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/datasets/transforms/wrappers.py", line 119, in transform
    branch_results = pipeline(copy.deepcopy(results))
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 87, in transform
    results = t(results)  # type: ignore
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/datasets/transforms/wrappers.py", line 161, in transform
    results = t(results)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/datasets/transforms/augment_wrappers.py", line 257, in transform
    results = self.transforms[idx](results)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 87, in transform
    results = t(results)  # type: ignore
  File "/home/ymhj/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/transforms/base.py", line 11, in __call__
    return self.transform(results)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/structures/bbox/box_type.py", line 277, in wrapper
    _results = func(self, results, *args, **kwargs)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/datasets/transforms/geometric.py", line 179, in transform
    self._transform_bboxes(results, mag)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/datasets/transforms/geometric.py", line 138, in _transform_bboxes
    results['gt_bboxes'].project_(self.homography_matrix)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/structures/bbox/horizontal_boxes.py", line 203, in project_
    self.tensor = self.corner2hbox(corners)
  File "/media/ymhj/新加卷/lyz/2021_down/bishe/mmd_3/mmdetection/mmdet/structures/bbox/horizontal_boxes.py", line 233, in corner2hbox
    min_xy = corners.min(dim=-2)[0]
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

### Environment

python3.8
torch1.10
mmcv mmegine
mmdet>3.0.0

**Comment by ZwwWayne** [comment]
Thanks for your bug report. It can be fixed by adding the skipping the operation when the box is empty, like the following line
above https://github.com/open-mmlab/mmdetection/blob/dev-3.x/mmdet/structures/bbox/horizontal_boxes.py#L230 
```python
        if corners.numel() == 0:
            return corners.new_zeros((0, 4))
        min_xy = corners.min(dim=-2)[0]
        ....
```

You might also need to update the `corner2bbox` if you still meet the bug by the following code above https://github.com/open-mmlab/mmdetection/blob/dev-3.x/mmdet/structures/bbox/transforms.py#L315
```python
    if corners.numel() == 0:
        return corners.new_zeros((0, 4))

```

**Comment by ZwwWayne** [comment]
If the modification helps you, would you like to create a PR to fix that?

**Comment by Czm369** [comment]
python3.9
torch1.9.0
It works fine in this environment.
![image](https://user-images.githubusercontent.com/40661020/197906837-f01f0f3a-428d-47ef-8bfd-2837f1aca00d.png)
