### ISSUE TITLE
keyword argument 'normalize' missing in some config files

### ISSUE THREAD

**Issue by Liu0329** [open-mmlab/mmdetection#915]
By
`python3 tools/train.py configs/mask_rcnn_r50_c4_1x.py`
I got
```
Traceback (most recent call last):
  File "tools/train.py", line 99, in <module>
    main()
  File "tools/train.py", line 76, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/code/mmdetection/mmdet/models/builder.py", line 60, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/code/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/code/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
  File "/home/code/mmdetection/mmdet/models/detectors/mask_rcnn.py", line 31, in __init__
    pretrained=pretrained)
  File "/home/code/mmdetection/mmdet/models/detectors/two_stage.py", line 30, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/home/code/mmdetection/mmdet/models/builder.py", line 36, in build_backbone
    return build(cfg, BACKBONES)
  File "/home/code/mmdetection/mmdet/models/builder.py", line 32, in build
    return _build_module(cfg, registry, default_args)
  File "/home/code/mmdetection/mmdet/models/builder.py", line 24, in _build_module
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'normalize'
```
It seems that normalize is missing ?
![image](https://user-images.githubusercontent.com/8122099/60491285-0492a100-9cdb-11e9-9b08-ecb22e5cb011.png)

**Comment by hellock** [comment]
You are not using the latest version.

**Comment by Liu0329** [comment]
Oh, but I cannot find mask_rcnn_r50_c4_1x.py in the latest version. I trained the 'caffe' version, but it works bad on my own dataset. And why is the line `# pretrained='open-mmlab://resnet50_caffe', `commented ?

**Comment by Liu0329** [comment]
Keys inconsistent in state_dict using the resnet50_caffe model. If commented that line, is the model trained from scratch ?

**Comment by hellock** [comment]
Thanks for reporting! This line should be uncommented.

**Comment by Liu0329** [comment]
But uncommenting that line would result in state_dict inconsistency. Is that expected ?

**Comment by Liu0329** [comment]
@hellock 
Using configs/mask_rcnn_r50_caffe_c4_2.py with `pretrained='open-mmlab://resnet50_caffe',`
cause huge keys inconsistency.
![image](https://user-images.githubusercontent.com/8122099/60636715-2eb6a100-9e4a-11e9-8a3b-43fd451e391b.png)

**Comment by hellock** [comment]
This is an outdated issue.
