### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by 666xiaohei666** [open-mmlab/mmdetection#916]
Traceback (most recent call last):
  File "tools/train.py", line 113, in <module>
    main()
  File "tools/train.py", line 109, in main
    logger=logger)
  File "/data2/yanmengkai/mmdetection/mmdet/apis/train.py", line 59, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/data2/yanmengkai/mmdetection/mmdet/apis/train.py", line 118, in _non_dist_train
    runner.resume(cfg.resume_from)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.8-py3.7.egg/mmcv/runner/runner.py", line 308, in resume
    self._epoch = checkpoint['meta']['epoch']
TypeError: list indices must be integers or slices, not str

**Comment by hellock** [comment]
Please use the "Error report" issue template.

**Comment by Hi-Alvin** [comment]
Hi, I got the same problem as yours. Did you got the solution? 
Thaks for your reply.
