### ISSUE TITLE
[Bug] collect_env.py fails due to circular import

### ISSUE THREAD

**Issue by franchesoni** [open-mmlab/mmdetection#9194]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

From `pip freeze`:
```
addict==2.4.0
certifi==2022.9.24
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
commonmark==0.9.1
contourpy==1.0.6
cycler==0.11.0
fonttools==4.38.0
idna==3.4
kiwisolver==1.4.4
Markdown==3.4.1
matplotlib==3.6.1
mmcv==2.0.0rc2
-e git+https://github.com/open-mmlab/mmdetection.git@3221ecf33885bcf185e1ea63ac72a861403d81b0#egg=mmdet
mmengine==0.2.0
model-index==0.1.11
numpy==1.23.4
opencv-python==4.6.0.66
openmim==0.3.2
ordered-set==4.1.0
packaging==21.3
pandas==1.5.1
Pillow==9.3.0
pycocotools==2.0.5
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.5
PyYAML==6.0
requests==2.28.1
rich==12.6.0
six==1.16.0
tabulate==0.9.0
termcolor==2.1.0
terminaltables==3.1.10
torch==1.13.0+cpu
torchvision==0.14.0+cpu
typing_extensions==4.4.0
urllib3==1.26.12
yapf==0.32.0
```

### Reproduces the problem - code sample

```bash
python mmdet/utils/collect_env.py
```

### Reproduces the problem - command or script

```bash
python mmdet/utils/collect_env.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "/home/franchesoni/mine/creations/phd/projects/current/iadet/mmdetection/mmdet/utils/collect_env.py", line 2, in <module>
    from mmengine.utils import get_git_hash
  File "/home/franchesoni/mine/creations/phd/projects/current/iadet/env_iadet/lib/python3.10/site-packages/mmengine/__init__.py", line 3, in <module>
    from .config import *
  File "/home/franchesoni/mine/creations/phd/projects/current/iadet/env_iadet/lib/python3.10/site-packages/mmengine/config/__init__.py", line 2, in <module>
    from .config import Config, ConfigDict, DictAction
  File "/home/franchesoni/mine/creations/phd/projects/current/iadet/env_iadet/lib/python3.10/site-packages/mmengine/config/config.py", line 15, in <module>
    from typing import Any, Optional, Sequence, Tuple, Union
  File "/home/franchesoni/mine/creations/phd/projects/current/iadet/mmdetection/mmdet/utils/typing.py", line 3, in <module>
    from typing import List, Optional, Sequence, Tuple, Union
ImportError: cannot import name 'List' from partially initialized module 'typing' (most likely due to a circular import) (/home/franchesoni/mine/creations/phd/projects/current/iadet/mmdetection/mmdet/utils/typing.py)
```

### Additional information

The expected result is the information of the environment, not an error.

Although this might be my fault, I followed a pretty standard installation:

```
python -m venv env_iadet
source env_iadet/bin/activate
pip install --upgrade pip
pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc1"
git clone https://github.com/open-mmlab/mmdetection.git -b 3.x
cd mmdetection
pip install -v -e .
```

**Comment by zytx121** [comment]
resolved in #9265
