### ISSUE TITLE
failure with dyhead swin onnx model to tensorrt engine with FP16 using mmdeploy

### ISSUE THREAD

**Issue by vedrusss** [open-mmlab/mmdetection#9196]
### Discussed in https://github.com/open-mmlab/mmdetection/discussions/9139

<div type='discussions-op-text'>

<sup>Originally posted by **vedrusss** October 25, 2022</sup>
Hi!
I'm trying to convert dyhead swin based model from onnx to tensorrt engine in fp16 mode using mmdeploy converter:
`python tools/onnx2tensorrt.py  configs/mmdet/detection/detection_tensorrt-fp16_static-1280x1920.py detection_tensorrt_static-1280x1920/fp16/end2end.onnx detection_tensorrt_static-1280x1920/fp16/end2end`

and running in following error:

-------------- The current device memory allocations dump as below --------------
[0]:34359738368 :HybridGlobWriter in reserveRegion: at optimizer/common/globWriter.cpp: 246 idx: 28 time: 0.000158613
[0x302000000]:11324620800 :HybridGlobWriter in reserveRegion: at optimizer/common/globWriter.cpp: 224 idx: 23 time: 0.00316042
[0x7f83c0000000]:29493600 :DeviceActivationSize in reserveNetworkTensorMemory: at optimizer/common/tactic/optimizer.cpp: 4603 idx: 8 time: 0.000331153
[10/24/2022-18:37:08] [TRT] [W] Requested amount of GPU memory (34359738368 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[10/24/2022-18:37:08] [TRT] [W] Skipping tactic 4 due to insuficient memory on requested size of 34359738368 detected for tactic 31.
Try decreasing the workspace size with IBuilderConfig::setMaxWorkspaceSize().
[10/24/2022-18:37:08] [TRT] [E] 2: [pointWiseBuilder.cpp::splitVectorizedHub::277] Error Code 2: Internal Error (Assertion !never(a.z >= 0) failed. )
Traceback (most recent call last):
  File "tools/onnx2tensorrt.py", line 73, in <module>
    main()
  File "tools/onnx2tensorrt.py", line 58, in main
    from_onnx(
  File "/root/workspace/mmdeploy/mmdeploy/backend/tensorrt/utils.py", line 225, in from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine

The actual **available GPU memory onto my device is 16Gb** and it does **support FP16**.
I'm **able to obtain the tensorrt** engine for the same model in **FP32** mode and cannot find out the reason why FP16 doesn't work.
Are there any nuances with using mmdeploy and mmdetection models for obtaining FP16 engines?
</div>

**Comment by Czm369** [comment]
Maybe you can raise an issue in MMDeploy, MMdetection has deprecated onnx.

**Comment by ZwwWayne** [comment]
DyHead is not officially supported for ONNX export.
