### ISSUE TITLE
Bus error. Insufficient shared memory?

### ISSUE THREAD

**Issue by FishLikeApple** [open-mmlab/mmdetection#929]
**Describe the bug**
When workers_per_gpu>0 in the config file, the error will arise. I searched for some keywords of the error, only the way to set workers_per_gpu to 0 can work, I know it means to make data preparation and training serial, which was time-consuming.

**Reproduction**
1. What command or script did you run?
```
"""a piece of code, dcn_best.py is a config file"""
config_file = 'dcn_best.py'
output_path = "/cos_person/275/1745/object_detection/output/"

#train
os.system('python '+mmdetection_path+'tools/train.py '+main_path+'code/'+config_file+' --gpus 1 --work_dir '+output_path)
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I changed some part for suitability for another dataset.
I commented out SyncBN (#norm_cfg=norm_cfg), because it designed for distributed training and I only had access to one GPU (P40) (please let me know if I can use SyncBN on a single GPU for a better result).
3. What dataset did you use?
a small part of Open Images 

**Environment**
 - OS: [linux-x86_64]
 - PyTorch version [3.5]
- How you installed PyTorch [pip]
- GPU model [P40]
(the environment was on cloud and was't set by me, I will be to find more accurate information if you need)

**Error traceback**
```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
�Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3958) is killed by signal: Bus error. 
```

**Bug fix**
The memory was 15G with 2 CPUs. Insufficient shared memory? I'm not sure.  

And thanks for your great work, I can already see improvement after some training, probably I will continuously use mmdetection for tasks with high accuracy requirements.

**Comment by FishLikeApple** [comment]
I'm sorry, PyTorch is lastest due to that it's upgraded each time the environment starts.

**Comment by FishLikeApple** [comment]
Is there anyone who can give any suggestion? Any suggestion will be great. Thank you.

**Comment by FishLikeApple** [comment]
Ok, I think I have some clue, it seems that I misunderstood the framework.

**Comment by FishLikeApple** [comment]
If I set workers_per_gpu>0, Pytorch will create a new worker on GPU, so the insufficient memory is of GPU I guess.
But still, I have some work to do to use multiple CPUs for preprocessing.

**Comment by John-Yao** [comment]
you can try to use multi-dataset which are small parts of total dataset.
The mmcv.runner support multi-dataloaders. But the mmdetection don't support it. There are some files to be modify:
1)mmdet/apis/train.py : 
make multi-dataloader by build_dataloader in dist_train or no_dist train function.
2)mmdet/datasets/utils.py: 
modify the func 'get_dataset' to return multi-dataset instead of Concatdataset
3) config file:
modify as below:
workflow = [('train', 1)] 
ann_file=[data_root + 'jsons/train.json'],
->
workflow = [('train', 1),('train', 1),('train', 1),('train', 1)]
ann_file=[data_root + 'jsons/train.json.part0',data_root + 'jsons/train.json.part1',data_root + 'jsons/train.json.part2',data_root + 'jsons/train.json.part3']
Also the step and total epoch , interval of evaluation should be multipied by the num of trainsets

**Comment by FishLikeApple** [comment]
> 
> 
> you can try to use multi-dataset which are small parts of total dataset.
> The mmcv.runner support multi-dataloaders. But the mmdetection don't support it. There are some files to be modify:
> 1)mmdet/apis/train.py :
> make multi-dataloader by build_dataloader in dist_train or no_dist train function.
> 2)mmdet/datasets/utils.py:
> modify the func 'get_dataset' to return multi-dataset instead of Concatdataset
> 3) config file:
> modify as below:
> workflow = [('train', 1)]
> ann_file=[data_root + 'jsons/train.json'],
> ->
> workflow = [('train', 1),('train', 1),('train', 1),('train', 1)]
> ann_file=[data_root + 'jsons/train.json.part0',data_root + 'jsons/train.json.part1',data_root + 'jsons/train.json.part2',data_root + 'jsons/train.json.part3']
> Also the step and total epoch , interval of evaluation should be multipied by the num of trainsets

Thanks, now I'm considering using group normalization, with which I can use smaller batches to train, so it's OK to use multiple workers in GPU.

**Comment by FishLikeApple** [comment]
I have found some thing time-consuming, the log below is my training log.

2019-07-21 16:20:05,759 - INFO - Epoch [1][5231/30000]	lr: 0.02000, eta: 4 days, 8:18:01, time: 2.013, data_time: 1.655, memory: 2677, loss_rpn_cls: 0.2121, loss_rpn_bbox: 0.0146, s0.loss_cls: 0.0523, s0.acc: 99.8047, s0.loss_bbox: 0.0000, s1.loss_cls: 0.0187, s1.acc: 99.8047, s1.loss_bbox: 0.0000, s2.loss_cls: 0.0094, s2.acc: 99.8047, s2.loss_bbox: 0.0000, loss: 0.3071
2019-07-21 16:20:07,772 - INFO - Epoch [1][5232/30000]	lr: 0.02000, eta: 4 days, 8:19:04, time: 2.013, data_time: 1.595, memory: 2677, loss_rpn_cls: 0.4542, loss_rpn_bbox: 0.0583, s0.loss_cls: 0.4526, s0.acc: 94.1406, s0.loss_bbox: 0.0909, s1.loss_cls: 0.1520, s1.acc: 96.4844, s1.loss_bbox: 0.0344, s2.loss_cls: 0.0644, s2.acc: 97.4609, s2.loss_bbox: 0.0067, loss: 1.3134
2019-07-21 16:20:09,537 - INFO - Epoch [1][5233/30000]	lr: 0.02000, eta: 4 days, 8:19:51, time: 1.764, data_time: 1.417, memory: 2677, loss_rpn_cls: 0.5243, loss_rpn_bbox: 0.1209, s0.loss_cls: 0.3645, s0.acc: 94.1406, s0.loss_bbox: 0.1174, s1.loss_cls: 0.0937, s1.acc: 97.2656, s1.loss_bbox: 0.0134, s2.loss_cls: 0.0489, s2.acc: 97.4609, s2.loss_bbox: 0.0060, loss: 1.2892
2019-07-21 16:20:11,213 - INFO - Epoch [1][5234/30000]	lr: 0.02000, eta: 4 days, 8:20:32, time: 1.677, data_time: 1.298, memory: 2677, loss_rpn_cls: 0.2924, loss_rpn_bbox: 0.0663, s0.loss_cls: 0.0605, s0.acc: 99.8047, s0.loss_bbox: 0.0001, s1.loss_cls: 0.0230, s1.acc: 99.8047, s1.loss_bbox: 0.0000, s2.loss_cls: 0.0102, s2.acc: 99.8047, s2.loss_bbox: 0.0000, loss: 0.4525
2019-07-21 16:20:12,707 - INFO - Epoch [1][5235/30000]	lr: 0.02000, eta: 4 days, 8:21:00, time: 1.493, data_time: 1.127, memory: 2677, loss_rpn_cls: 0.3955, loss_rpn_bbox: 0.1449, s0.loss_cls: 0.0590, s0.acc: 99.8047, s0.loss_bbox: 0.0001, s1.loss_cls: 0.0227, s1.acc: 99.8047, s1.loss_bbox: 0.0000, s2.loss_cls: 0.0102, s2.acc: 99.8047, s2.loss_bbox: 0.0000, loss: 0.6324
2019-07-21 16:20:13,987 - INFO - Epoch [1][5236/30000]	lr: 0.02000, eta: 4 days, 8:21:14, time: 1.281, data_time: 0.945, memory: 2677, loss_rpn_cls: 0.3093, loss_rpn_bbox: 0.0630, s0.loss_cls: 0.0985, s0.acc: 99.0234, s0.loss_bbox: 0.0083, s1.loss_cls: 0.0344, s1.acc: 99.4141, s1.loss_bbox: 0.0012, s2.loss_cls: 0.0191, s2.acc: 99.4141, s2.loss_bbox: 0.0011, loss: 0.5350

One can see that data_time is a lot of time, it occupied a large part of time of each batch. Is data_time  the time used to process data (get training images)? Thinks for all suggestions.

**Comment by Pattorio** [comment]
Never set worker_per_gpu=0, or you will spend LOOOONG time for training.

Did you use docker? When you run docker, add `--shm-size="8g"` or any size you need but more than 64M.

**Comment by FishLikeApple** [comment]
> 
> 
> Never set worker_per_gpu=0, or you will spend LOOOONG time for training.
> 
> Did you use docker? When you run docker, add `--shm-size="8g"` or any size you need but more than 64M.

Thanks, I'm using a cloud plaform which provides a virtual Linux machine. Now I'm using batch size 1 with GN (it's good to know that mmdetection has supported GN). I think technically GN doesn't depend on batch size.
