### ISSUE TITLE
use python tools / test.py error?

### ISSUE THREAD

**Issue by yghcats** [open-mmlab/mmdetection#93]
What is the following question?

Traceback (most recent call last):
  File "tools/test2.py", line 3, in <module>
    from mmdet.models import build_detector
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/models/__init__.py", line 1, in <module>
    from .detectors import (BaseDetector, TwoStageDetector, RPN, FastRCNN,
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/models/detectors/__init__.py", line 1, in <module>
    from .base import BaseDetector
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/models/detectors/base.py", line 8, in <module>
    from mmdet.core import tensor2imgs, get_classes
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops import nms
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/ops/__init__.py", line 1, in <module>
    from .nms import nms, soft_nms
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from .gpu_nms import gpu_nms
ImportError: /usr/local/lib/python3.5/dist-packages/mmdet-0.5.2+3f5df4f-py3.5.egg/mmdet/ops/nms/gpu_nms.so: undefined symbol: _Py_ZeroStruct

**Comment by hellock** [comment]
May be related to #48

**Comment by yghcats** [comment]
Thanks. It has been settled.

**Comment by ujsyehao** [comment]
@yghcats How do you solve it?
