### ISSUE TITLE
AssertionError: loss log variables are different across GPUs!

### ISSUE THREAD

**Issue by vampireacen** [open-mmlab/mmdetection#9340]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.9.13 (main, Oct 13 2022, 21:15:33) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7,8,9: GeForce RTX 3090
CUDA_HOME: :/usr/local/cuda-11.1:/usr/local/cuda-11.1
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.0+cu111
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.25.3+5c0b57f

### Reproduces the problem - code sample

```python
def _parse_losses(self, losses):
        """Parse the raw outputs (losses) of the network.

        Args:
            losses (dict): Raw output of the network, which usually contain
                losses and other necessary information.

        Returns:
            tuple[Tensor, dict]: (loss, log_vars), loss is the loss tensor \
                which may be a weighted sum of all losses, log_vars contains \
                all the variables to be sent to the logger.
        """
        log_vars = OrderedDict()
        for loss_name, loss_value in losses.items():
            if isinstance(loss_value, torch.Tensor):
                log_vars[loss_name] = loss_value.mean()
            elif isinstance(loss_value, list):
                log_vars[loss_name] = sum(_loss.mean() for _loss in loss_value)
            else:
                raise TypeError(
                    f'{loss_name} is not a tensor or list of tensors')

        loss = sum(_value for _key, _value in log_vars.items()
                   if 'loss' in _key)

        # If the loss_vars has different length, GPUs will wait infinitely
        if dist.is_available() and dist.is_initialized():
            log_var_length = torch.tensor(len(log_vars), device=loss.device)
            dist.all_reduce(log_var_length)
            message = (f'rank {dist.get_rank()}' +
                       f' len(log_vars): {len(log_vars)}' + ' keys: ' +
                       ','.join(log_vars.keys()))
            assert log_var_length == len(log_vars) * dist.get_world_size(), \
                'loss log variables are different across GPUs!\n' + message

        log_vars['loss'] = loss
        for loss_name, loss_value in log_vars.items():
            # reduce loss when distributed training
            if dist.is_available() and dist.is_initialized():
                loss_value = loss_value.data.clone()
                dist.all_reduce(loss_value.div_(dist.get_world_size()))
            log_vars[loss_name] = loss_value.item()

        return loss, log_vars
```

### Reproduces the problem - command or script

```shell
CUDA_VISIBLE_DEVICES=9,8,7,6,5,4,3,2 python -m torch.distributed.launch --nproc_per_node=8 tools/train.py configs/Mymodel/Mymodel.py --work-dir work_dirs/neg_sample_test --gpus 8 --launcher pytorch
```
The same error occurs with 2 GPUs

### Reproduces the problem - error message

```
2022-11-16 16:19:14,217 - mmdet - INFO - Set random seed to 577150438, deterministic: False
/home/ubuntu/data/mmdetection/mmdet/models/builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
/home/ubuntu/data/mmdetection/mmdet/models/builder.py:51: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  warnings.warn(
2022-11-16 16:19:14,907 - mmdet - INFO - load checkpoint from http path: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth
2022-11-16 16:19:15,175 - mmdet - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-11-16 16:19:17,285 - mmdet - INFO - Automatic scaling of learning rate (LR) has been disabled.
2022-11-16 16:19:18,136 - mmdet - INFO - load checkpoint from local path: /home/ubuntu/data/mmdetection/work_dirs/pretrain_test/latest.pth
2022-11-16 16:19:18,554 - mmdet - WARNING - The model and loaded state dict do not match exactly

size mismatch for bbox_head.fc_cls.weight: copying a param with shape torch.Size([20, 256]) from checkpoint, the shape in current model is torch.Size([21, 256]).
size mismatch for bbox_head.fc_cls.bias: copying a param with shape torch.Size([20]) from checkpoint, the shape in current model is torch.Size([21]).
size mismatch for bbox_head.pattern.weight: copying a param with shape torch.Size([3, 256]) from checkpoint, the shape in current model is torch.Size([1, 256]).
2022-11-16 16:19:18,556 - mmdet - INFO - Start running, host: ubuntu@chenf1, work_dir: /home/ubuntu/data/mmdetection/work_dirs/pt_test
2022-11-16 16:19:18,558 - mmdet - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) NumClassCheckHook                  
(NORMAL      ) DistSamplerSeedHook                
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) DistEvalHook                       
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(NORMAL      ) NumClassCheckHook                  
(NORMAL      ) DistSamplerSeedHook                
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2022-11-16 16:19:18,559 - mmdet - INFO - workflow: [('train', 1)], max: 500 epochs
2022-11-16 16:19:18,559 - mmdet - INFO - Checkpoints will be saved to /home/ubuntu/data/mmdetection/work_dirs/pt_test by HardDiskBackend.
/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/ubuntu/data/mmdetection/mmdet/models/utils/anchorformer_transformer.py:89: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_feats)
/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:523: UserWarning: position encoding of key ismissing in MultiheadAttention.
  warnings.warn(f'position encoding of key is'
/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/ubuntu/data/mmdetection/mmdet/models/utils/anchorformer_transformer.py:89: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_feats)
/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:523: UserWarning: position encoding of key ismissing in MultiheadAttention.
  warnings.warn(f'position encoding of key is'
Backend TkAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3433, in <module>
    main()
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 3426, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2502, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2509, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "./tools/train.py", line 244, in <module>
    main()
  File "./tools/train.py", line 233, in main
    train_detector(
  File "/home/ubuntu/data/mmdetection/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 31, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ubuntu/data/mmdetection/mmdet/models/detectors/base.py", line 249, in train_step
    loss, log_vars = self._parse_losses(losses)
  File "/home/ubuntu/data/mmdetection/mmdet/models/detectors/base.py", line 208, in _parse_losses
    assert log_var_length == len(log_vars) * dist.get_world_size(), \
AssertionError: loss log variables are different across GPUs!
rank 0 len(log_vars): 18 keys: l0.d0.loss_cls,l0.d0.loss_bbox,l0.d0.loss_iou,l0.d1.loss_cls,l0.d1.loss_bbox,l0.d1.loss_iou,l1.d0.loss_cls,l1.d0.loss_bbox,l1.d0.loss_iou,l1.d1.loss_cls,l1.d1.loss_bbox,l1.d1.loss_iou,l2.d0.loss_cls,l2.d0.loss_bbox,l2.d0.loss_iou,l2.d1.loss_cls,l2.d1.loss_bbox,l2.d1.loss_iou
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 869706 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 869705) of binary: /home/ubuntu/anaconda3/envs/mmdet/bin/python
```

### Additional information

The parameter value of **log_var_length** 18 should become 18 * GPUS after **dist.all_reduce(log_var_length)** （mentioned in the above code sample）, but now it is a very large value such as 550855770130, I don’t know what caused it.

I tried zero loss but the same error occurs, and single GPU works fine.

**Comment by BIGWangYuDong** [comment]
Sorry for the late reply, kindly ping @HAOCHENYE have a look

**Comment by HAOCHENYE** [comment]
You can try to print out the log_vars on each rank to find out the difference between them: https://github.com/open-mmlab/mmdetection/blob/3b72b12fe9b14de906d1363982b9fba05e7d47c1/mmdet/models/detectors/base.py#L203

**Comment by BIGWangYuDong** [comment]
Feel free to re-open this issue if you still meet this problem

**Comment by wjn922** [comment]
Hi @vampireacen, did you solve the problem? I have the same error. I have checked every gpu has the same length of log_var_length, while it returns a huge number after dist.all_reduce().

**Comment by yimeng436** [comment]
> Hi @vampireacen, did you solve the problem? I have the same error. I have checked every gpu has the same log_var_length, while it returns a huge number after dist.all_reduce().

Did you solve the problem? I had the same problem you had

**Comment by yimeng436** [comment]
> Hi @vampireacen, did you solve the problem? I have the same error. I have checked every gpu has the same log_var_length, while it returns a huge number after dist.all_reduce().

I have the same problem as you, and it will become a very large number. Have you solved it now

**Comment by JackyChan97** [comment]
> > Hi @vampireacen, did you solve the problem? I have the same error. I have checked every gpu has the same log_var_length, while it returns a huge number after dist.all_reduce().
> 
> I have the same problem as you, and it will become a very large number. Have you solved it now

I got the same problem, did you solved it now?

**Comment by aarwitz** [comment]
> /home/ubuntu/anaconda3/envs/mmdet/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:523: UserWarning: position encoding of key ismissing in MultiheadAttention.
  warnings.warn(f'position encoding of key is'
  
  
I am getting this warning as well. Anyone fix it or know whether it is relevant?

**Comment by feimadada** [comment]
> > > Hi @vampireacen, did you solve the problem? I have the same error. I have checked every gpu has the same log_var_length, while it returns a huge number after dist.all_reduce().
> > 
> > 
> > I have the same problem as you, and it will become a very large number. Have you solved it now
> 
> I got the same problem, did you solved it now?

I got the same problem, did you solved it now?

**Comment by nonecode404** [comment]
我出现了同样的问题。先描述下：使用partial数据去训练，做法是算loss时将batch中不需要的去除。但是如果有每个batch全部去除后就会导致了该问题。上述的问题，在单GPU上都不会报错，多卡就会报错。
第一个解决方案：只给需要去除的batch赋一个标志位0，loss依然计算不过在最后对该batch的loss*0。（可以解决一部分问题）
第二个方案：自己写的代码bug，当时有一个单batch里loss计算用了reduce_mean这类操作。

**Comment by tengjn** [comment]
remove **reduce_mean related code** in loss computing works for me

![Image](https://github.com/user-attachments/assets/e64b5103-5f4e-4c5b-a0ae-6d36b20b9d33)
