### ISSUE TITLE
[Bug] cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:3689: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

### ISSUE THREAD

**Issue by mylittlebuds** [open-mmlab/mmdetection#9349]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

2022-11-18 18:42:35,272 - mmdeploy - INFO - **********Environmental information**********
fatal: not a git repository (or any of the parent directories): .git
2022-11-18 18:42:36,758 - mmdeploy - INFO - sys.platform: linux
2022-11-18 18:42:36,758 - mmdeploy - INFO - Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
2022-11-18 18:42:36,758 - mmdeploy - INFO - CUDA available: True
2022-11-18 18:42:36,758 - mmdeploy - INFO - GPU 0,1: NVIDIA GeForce RTX 3080 Ti
2022-11-18 18:42:36,758 - mmdeploy - INFO - CUDA_HOME: /usr/local/cuda
2022-11-18 18:42:36,758 - mmdeploy - INFO - NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
2022-11-18 18:42:36,758 - mmdeploy - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
2022-11-18 18:42:36,758 - mmdeploy - INFO - PyTorch: 1.10.2+cu113
2022-11-18 18:42:36,758 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

2022-11-18 18:42:36,758 - mmdeploy - INFO - TorchVision: 0.11.3+cu113
2022-11-18 18:42:36,758 - mmdeploy - INFO - OpenCV: 4.6.0
2022-11-18 18:42:36,758 - mmdeploy - INFO - MMCV: 1.3.18
2022-11-18 18:42:36,758 - mmdeploy - INFO - MMCV Compiler: GCC 7.3
2022-11-18 18:42:36,758 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-18 18:42:36,758 - mmdeploy - INFO - MMDeploy: 0.9.0+
2022-11-18 18:42:36,758 - mmdeploy - INFO - 

2022-11-18 18:42:36,758 - mmdeploy - INFO - **********Backend information**********
2022-11-18 18:42:37,399 - mmdeploy - INFO - onnxruntime: 1.8.1  ops_is_avaliable : True
2022-11-18 18:42:37,426 - mmdeploy - INFO - tensorrt: 8.4.3.1   ops_is_avaliable : False
2022-11-18 18:42:37,440 - mmdeploy - INFO - ncnn: 1.0.20221027  ops_is_avaliable : True

### Reproduces the problem - code sample

cls_modelpath = r'/home/ubuntu/PycharmProjects/mmpose-master/work_dirs/25gesture/good/best_True_13_26_v2_0.8011.pth'   
pose_config = '/home/ubuntu/PycharmProjects/mmpose-master/configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/litehrnet_18_coco_256x192.py'
pose_checkpoint = '/home/ubuntu/PycharmProjects/mmpose-master/work_dirs/litehrnet_18_coco_256x192/epoch_1980.pth'
det_config = '/home/ubuntu/PycharmProjects/mmpose-master/demo/mmdetection_cfg/yolox_s_8x8_300e_coco.py'
det_checkpoint = '/home/ubuntu/PycharmProjects/mdforpretrain/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth'

def image_process(image_path):
    mean = np.array([[[0, 0, 0]]])  # 训练的时候用来mean和std
    std = np.array([[[256, 256, 256]]])
    image = cv2.imread(image_path)
    # print('shape of original pic:',np.shape(image))
    height, width = image.shape[0], image.shape[1]
    width_new = 640
    height_new = 480
    if width / height <= width_new / height_new:# 按照w比例缩放
        img_new0 = cv2.resize(image, (width_new, int(height * width_new / width)))
    else:# 按照h比例缩放
        img_new0 = cv2.resize(image, (int(width * height_new / height), height_new))
    img_new=img_new0[:480,200:840,:]
    print('shape of original img:',np.shape(img_new))
    # img_new = cv2.cvtColor(img_new, cv2.COLOR_BGR2RGB)
    cv2.imshow('', img_new)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    # image = img.astype(np.float32) / 255.0
    image = (img_new - mean) / std
    image = image.transpose((2, 0, 1))
    image = image[np.newaxis, :, :, :]

    image = np.array(image, dtype=np.float32)
    # print('len of image.flatten():',len(image.flatten()))
    # print('max:',max(image.flatten()))
    # print('min:',min(image.flatten()))

    return image

cls_model = GSModel()
cls_model.load_state_dict(torch.load(cls_modelpath))
cls_model.eval()

# initialize pose model
pose_model = init_pose_model(pose_config, pose_checkpoint)
# print('type of pose_model:', type(self.pose_model))
# print('model:', '\r\n', pose_model)
# initialize detector
det_model = init_detector(det_config, det_checkpoint)
mage_path = '/home/ubuntu/temp/Camera_70/Camera_70/IMG_20220913_082912.jpg'
img=image_process(mage_path)
print('img:',img)

# inference detection
mmdet_results = inference_detector(det_model, img)

then raise error as below error message:

### Reproduces the problem - command or script

(openmm37clone) ubuntu@AiotServer02:~/PycharmProjects/mmpose-master$ python ./tools/inferencetemp_26performance.py

### Reproduces the problem - error message

load checkpoint from local path: /home/ubuntu/PycharmProjects/mmpose-master/work_dirs/litehrnet_18_coco_256x192/epoch_1980.pth
load checkpoint from local path: /home/ubuntu/PycharmProjects/mdforpretrain/yolox_s_8x8_300e_coco_20211121_095711-4592a793.pth
shape of original img: (480, 640, 3)
img: [[[[0.5        0.50390625 0.51171875 ... 0.59375    0.59375
    0.5625    ]
   [0.51171875 0.51171875 0.51171875 ... 0.60546875 0.6015625
    0.5546875 ]
   [0.53125    0.5234375  0.51953125 ... 0.63671875 0.64453125
    0.625     ]
   ...
   [0.74609375 0.75       0.75       ... 0.734375   0.54296875
    0.23828125]
   [0.74609375 0.74609375 0.7421875  ... 0.625      0.72265625
    0.67578125]
   [0.74609375 0.7421875  0.73828125 ... 0.6171875  0.61328125
    0.6796875 ]]

  [[0.57421875 0.578125   0.5859375  ... 0.74609375 0.75390625
    0.71875   ]
   [0.5859375  0.5859375  0.5859375  ... 0.75390625 0.75
    0.69921875]
   [0.59765625 0.58984375 0.5859375  ... 0.76171875 0.765625
    0.74609375]
   ...
   [0.765625   0.76953125 0.76953125 ... 0.83203125 0.6328125
    0.3046875 ]
   [0.765625   0.765625   0.76171875 ... 0.7578125  0.84765625
    0.78515625]
   [0.765625   0.76171875 0.7578125  ... 0.7734375  0.76953125
    0.8203125 ]]

  [[0.60546875 0.609375   0.6171875  ... 0.83203125 0.83984375
    0.84375   ]
   [0.6171875  0.6171875  0.6171875  ... 0.84375    0.84375
    0.80859375]
   [0.6328125  0.625      0.62109375 ... 0.859375   0.859375
    0.83984375]
   ...
   [0.77734375 0.78125    0.78125    ... 0.84765625 0.640625
    0.28515625]
   [0.77734375 0.77734375 0.7734375  ... 0.76953125 0.8515625
    0.74609375]
   [0.77734375 0.7734375  0.76953125 ... 0.78125    0.76171875
    0.76953125]]]]
Traceback (most recent call last):
  File "/home/ubuntu/PycharmProjects/mmpose-master/tools/inferencetemp_26performance.py", line 126, in <module>
    mmdet_results = inference_detector(det_model, img)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/apis/inference.py", line 133, in inference_detector
    data = test_pipeline(data)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/datasets/pipelines/test_time_aug.py", line 107, in __call__
    data = self.transforms(_results)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/datasets/pipelines/transforms.py", line 316, in __call__
    self._resize_img(results)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmdet/datasets/pipelines/transforms.py", line 224, in _resize_img
    backend=self.backend)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmcv/image/geometric.py", line 245, in imrescale
    img, new_size, interpolation=interpolation, backend=backend)
  File "/home/ubuntu/anaconda3/envs/openmm37clone/lib/python3.7/site-packages/mmcv/image/geometric.py", line 89, in imresize
    img, size, dst=out, interpolation=cv2_interp_codes[interpolation])
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/resize.cpp:3689: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

### Additional information

please check why raise a such error, and how to input image to  inference_detector() directly not by path?
thanks so much.

**Comment by BIGWangYuDong** [comment]
Dose not get your problem due to the report is confused. And What code did you changed is necessary.

Right now, It is suggested to check the parameters that you fed into resize. it dose not match with the cv2.resize type
