### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by dky233** [open-mmlab/mmdetection#9385]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

torch1.12.0
mmcv2.0
mmdet3.0
mmengine'0.3.1

### Reproduces the problem - code sample

AttributeError: 'pfullmem' object has no attribute 'pss'

### Reproduces the problem - command or script

python tools/analysis_tools/benchmark.py 

### Reproduces the problem - error message

AttributeError: 'pfullmem' object has no attribute 'pss'

### Additional information

Mmdet3. x uses benchmark.py Test fps reports an error AttributeError: 'pfullmem' object has no attribute 'pss'

**Comment by dky233** [comment]
The complete error report is as follows：
11/25 21:06:13 - mmengine - INFO - before build: 
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark.py", line 134, in <module>
    main()
  File "tools/analysis_tools/benchmark.py", line 129, in main
    benchmark = eval(f'{args.task}_benchmark')(args, cfg, distributed, logger)
  File "tools/analysis_tools/benchmark.py", line 85, in dataloader_benchmark
    benchmark = DataLoaderBenchmark(
  File "c:\ptoject\xwj\mmdetection-3.x\mmdet\utils\benchmark.py", line 319, in __init__
    print_process_memory(self._process, self.logger)
  File "c:\ptoject\xwj\mmdetection-3.x\mmdet\utils\benchmark.py", line 54, in print_process_memory
    pss_mem = gb_round(memory_full_info.pss)
AttributeError: 'pfullmem' object has no attribute 'pss'

**Comment by ZwwWayne** [comment]
Hi @dky233 ,
Which device are you using. Do you use mac OS or windows?

**Comment by dky233** [comment]
@ZwwWaune
windows

**Comment by dky233** [comment]
@ZwwWaune
windows

**Comment by dky233** [comment]
@ZwwWaune
windows

**Comment by dky233** [comment]
@ZwwWayne windows

**Comment by ZwwWayne** [comment]
Then it seems that this is caused by the different OS. We will find a way to fix it. Thank you

**Comment by 19990101lrk** [comment]
Is this bug solved? I have the same problem

**Comment by okt7760** [comment]
Is this bug solved? I have the same problem

**Comment by 19990101lrk** [comment]
> Is this bug solved? I have the same problem

You may be using a windows OS, trying to use a Linux OS may solve the problem.

**Comment by sheismoon** [comment]
have a way to solve this ?

**Comment by ZE0201** [comment]
Has it been resolved, please? I'm having the same problem.

**Comment by wozaiAHPUhenxiangni** [comment]
我看了一下，这是psutil.Process.memory_full_info()在Linux端的定义
```
 def memory_full_info(
                self,
                # Gets Private_Clean, Private_Dirty, Private_Hugetlb.
                _private_re=re.compile(br"\nPrivate.*:\s+(\d+)"),
                _pss_re=re.compile(br"\nPss\:\s+(\d+)"),
                _swap_re=re.compile(br"\nSwap\:\s+(\d+)")):
            basic_mem = self.memory_info()
            # Note: using 3 regexes is faster than reading the file
            # line by line.
            # XXX: on Python 3 the 2 regexes are 30% slower than on
            # Python 2 though. Figure out why.
            #
            # You might be tempted to calculate USS by subtracting
            # the "shared" value from the "resident" value in
            # /proc/<pid>/statm. But at least on Linux, statm's "shared"
            # value actually counts pages backed by files, which has
            # little to do with whether the pages are actually shared.
            # /proc/self/smaps on the other hand appears to give us the
            # correct information.
            smaps_data = self._read_smaps_file()
            # Note: smaps file can be empty for certain processes.
            # The code below will not crash though and will result to 0.
            uss = sum(map(int, _private_re.findall(smaps_data))) * 1024
            pss = sum(map(int, _pss_re.findall(smaps_data))) * 1024
            swap = sum(map(int, _swap_re.findall(smaps_data))) * 1024
            return pfullmem(*basic_mem + (uss, pss, swap))
```
中间加入了 pss 属性，而在Windows的定义中
```
    def memory_full_info(self):
        basic_mem = self.memory_info()
        uss = cext.proc_memory_uss(self.pid)
        uss *= getpagesize()
        return pfullmem(*basic_mem + (uss, ))
```
并不包含pss属性，这可能是问题产生的主要原因
