### ISSUE TITLE
Unable to import module 'app': No module named '_tkinter'", "errorType": "Runtime.ImportModuleError"

### ISSUE THREAD

**Issue by ganesh3** [open-mmlab/mmdetection#9403]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

FROM public.ecr.aws/lambda/python:3.8
RUN yum -y update
RUN yum -y install gcc
RUN yum install -y gcc-c++
RUN yum install -y git
RUN yum install -y which
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt \
    && pip install -e git+https://github.com/ganesh3/icevision.git@master#egg=icevision[inference] --upgrade -q
COPY model_dir ./model_dir
COPY /app/app.py   ./
CMD ["app.handler"] 

### Reproduces the problem - code sample

Deploying a model dependent on MMDetection to docker container which will get deployed to AWS lambda which is basically created using headless python packages.

DockerFile

```base
FROM public.ecr.aws/lambda/python:3.8
RUN yum -y update
RUN yum -y install gcc
RUN yum install -y gcc-c++
RUN yum install -y git
RUN yum install -y which
COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt \
    && pip install -e git+https://github.com/ganesh3/icevision.git@master#egg=icevision[inference] --upgrade -q
COPY model_dir ./model_dir
COPY /app/app.py   ./
CMD ["app.handler"] 
```

requirements.txt

```base
--find-links  https://download.pytorch.org/whl/torch_stable.html
torch==1.10.0+cpu 
torchvision==0.11.1+cpu
--find-links  https://download.openmmlab.com/mmcv/dist/cpu/torch1.10.0/index.html
mmcv-full==1.3.17
mmdet==2.17.0
numpy
Pillow
tk
```

```base
# app.py used in the early stages of the project just to test if I was able to import the icevision library
import sys
import os
print("Executing install for fonts")
os.system('mkdir -p /root/.icevision/fonts/')
os.system('curl -LJO https://raw.githubusercontent.com/airctic/storage/master/SpaceGrotesk-Medium.ttf')
os.system('cp SpaceGrotesk-Medium.ttf /root/.icevision/fonts/')
os.system('yum install -y tkinter tcl-devel tk-devel')
os.system('yum search tkinter')
os.system('yum install -y python3-tkinter.x86_64')
print("Before tkinter import")
import tkinter
print("After tkinter import")
import icevision
def handler(event, context): 
    return 'Hello from AWS Lambda using Python ' + sys.version + ' and IceVision ' + icevision.__version__ + '!'

```

### Reproduces the problem - command or script

Create the docker container using the code above
.

```base
The structure is as below:

Code folder:
------->Dockerfile
-------> requirements.txt
-------> app
---------------------------> app.py
------->model
---------------------------> model.pth
```

### Reproduces the problem - error message

```base
[Unable to import module 'app': No module named '_tkinter'", "errorType": "Runtime.ImportModuleError"]
```

I logged into the docker container using and got the following error:

```base
docker exec -it <container_name> sh
```

ERROR:

```base
>>> import icevision
Traceback (most recent call last):


File "<stdin>", line 1, in <module>
  File "/var/task/src/icevision/icevision/__init__.py", line 3, in <module>
    from icevision import parsers
  File "/var/task/src/icevision/icevision/parsers/__init__.py", line 1, in <module>
    from icevision.parsers.parser import *
  File "/var/task/src/icevision/icevision/parsers/parser.py", line 7, in <module>
    from icevision.data import *
  File "/var/task/src/icevision/icevision/data/__init__.py", line 5, in <module>
    from icevision.data.convert_records_to_coco_style import *
  File "/var/task/src/icevision/icevision/data/convert_records_to_coco_style.py", line 17, in <module>
    from icevision.models.inference import *
  File "/var/task/src/icevision/icevision/models/__init__.py", line 15, in <module>
    from icevision.models import mmdet
  File "/var/task/src/icevision/icevision/models/mmdet/__init__.py", line 2, in <module>
    from icevision.models.mmdet.models import *
  File "/var/task/src/icevision/icevision/models/mmdet/models/__init__.py", line 18, in <module>
    from icevision.models.mmdet.models import mask_rcnn
  File "/var/task/src/icevision/icevision/models/mmdet/models/mask_rcnn/__init__.py", line 2, in <module>
    from icevision.models.mmdet.common.mask.two_stage import *
  File "/var/task/src/icevision/icevision/models/mmdet/common/mask/two_stage/__init__.py", line 2, in <module>
    from icevision.models.mmdet.common.mask.two_stage.model import *
  File "/var/task/src/icevision/icevision/models/mmdet/common/mask/two_stage/model.py", line 3, in <module>
    from turtle import back
  File "/var/lang/lib/python3.8/turtle.py", line 107, in <module>
    import tkinter as TK
  File "/var/lang/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

Can this error be resolved as turtle is not relevant for AWS lambda as there is no display required?

### Additional information

The turtle package is not required for AWS Lambda and should be commented for deploying. Removing it will solve the problem of tkinter.

**Comment by ganesh3** [comment]
not relevant to the package
