### ISSUE TITLE
C3D fine-tuning "assert self.size <= img_h and self.size <= img_w" [Bug] 

### ISSUE THREAD

**Issue by suzana-rita** [open-mmlab/mmdetection#9526]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

I created the environment like this:
`conda create -n open-mmlab cudatoolkit=11.3 -c conda-forge -y`
conda activate open-mmlab
conda install python=3.8 pytorch=1.10 torchvision -c pytorch -y`

Using this environment, I could run my code with I3D using your framework. However, I cannot run the same code with some modifications for the C3D archtecture due to the assertion error:
`assert self.size <= img_h and self.size <= img_w`

### Reproduces the problem - code sample

This is the `customized_c3d_sports1m_16x1x1_45e_ucf101_rgb.py` used as the config file for the C3D NN.
```
_base_ = '../../_base_/models/c3d_sports1m_pretrained.py'

model = dict(
    cls_head=dict(
        type='I3DHead',
        num_classes=10,
        in_channels=4096,
        spatial_type=None,
        dropout_ratio=0.5,
        init_std=0.01))


img_norm_cfg = dict(mean=[104, 117, 128], std=[1, 1, 1], to_bgr=False)
train_pipeline = [
    dict(type='SampleFrames', clip_len=16, frame_interval=1, num_clips=1),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(128, 171)),
    dict(type='RandomCrop', size=112),
    dict(type='Flip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
val_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=16,
        frame_interval=1,
        num_clips=1,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(128, 171)),
    dict(type='CenterCrop', crop_size=112),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]
test_pipeline = [
    dict(
        type='SampleFrames',
        clip_len=16,
        frame_interval=1,
        num_clips=10,
        test_mode=True),
    dict(type='RawFrameDecode'),
    dict(type='Resize', scale=(128, 171)),
    dict(type='CenterCrop', crop_size=112),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='FormatShape', input_format='NCTHW'),
    dict(type='Collect', keys=['imgs', 'label'], meta_keys=[]),
    dict(type='ToTensor', keys=['imgs', 'label'])
]


dataset_type = 'MyDataset'
data_root = ''
data_root_val = ''
ann_file_train = '../../dataset_crossvalidation_relative_path/train_data_fold_001.txt'
ann_file_val = '../../dataset_crossvalidation_relative_path/test_data_fold_001.txt'
ann_file_test = '../../dataset_crossvalidation_relative_path/test_data_fold_001.txt'

data = dict(
    videos_per_gpu=10,
    workers_per_gpu=2,
    test_dataloader=dict(videos_per_gpu=1),
    dataset_A_train = dict(
        type='MyDataset',
        data_prefix=data_root,
        ann_file=ann_file_train,
        pipeline=train_pipeline),
    dataset_A_val = dict(
        type='MyDataset',
        data_prefix=data_root_val,
        ann_file=ann_file_test,
        pipeline=test_pipeline),
    dataset_A_test = dict(
        type='MyDataset',
        data_prefix=data_root_val,
        ann_file=ann_file_test,
        pipeline=test_pipeline
        ))

optimizer = dict(
    type='SGD', lr=0.001, momentum=0.9,
    weight_decay=0.0005)  # this lr is used for 8 gpus
optimizer_config = dict(grad_clip=dict(max_norm=40, norm_type=2))

lr_config = dict(policy='step', step=[20, 40])
total_epochs = 20

checkpoint_config = dict(interval=10)
evaluation = dict(
    interval=5, metrics=['top_k_accuracy', 'mean_class_accuracy'])
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
    ])

dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = './work_dirs/c3d_sports1m_16x1x1_45e_ucfsports_rgb/'
load_from = 'https://download.openmmlab.com/mmaction/recognition/c3d/c3d_sports1m_16x1x1_45e_ucf101_rgb/c3d_sports1m_16x1x1_45e_ucf101_rgb_20201021-26655025.pth'
resume_from = None
workflow = [('train', 1)]
gpu_ids = range(1)
```

### Reproduces the problem - command or script

`python tools/fine_tune_c3d.py configs/recognition/c3d/customized_c3d_sports1m_16x1x1_45e_ucf101_rgb.py`

### Reproduces the problem - error message

```
main()
  File "tools/fine_tune_c3d.py", line 386, in main
    new_model = train_model(
  File "/home/mmaction2/mmaction/apis/train.py", line 232, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs, **runner_kwargs)
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mmaction2/mmaction/datasets/base.py", line 289, in __getitem__
    return self.prepare_train_frames(idx)
  File "/home/mmaction2/mmaction/datasets/my_dataset.py", line 46, in prepare_train_frames
    return self.pipeline(results)
  File "/home/mmaction2/mmaction/datasets/pipelines/compose.py", line 50, in __call__
    data = t(data)
  File "/home/mmaction2/mmaction/datasets/pipelines/augmentations.py", line 633, in __call__
    assert self.size <= img_h and self.size <= img_w
AssertionError
```

**Comment by suzana-rita** [comment]
Sorry, I don't know why but I report it in the wrong repository. It was supposed to be on mmaction2 not here. I will repost it there!
