### ISSUE TITLE
[Bug] 'ConfigDict' object has no attribute 'workers_per_gpu'

### ISSUE THREAD

**Issue by emelypi** [open-mmlab/mmdetection#9632]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: win32
Python: 3.9.15 (main, Nov 24 2022, 14:39:17) [MSC v.1916 64 bit (AMD64)]
CUDA available: False
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30136 for x64
GCC: n/a
PyTorch: 1.13.1+cpu
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1+cpu
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: MSVC 192829924
MMCV CUDA Compiler: not available
MMDetection: 2.27.0+

### Reproduces the problem - code sample

I didn't change the code at all.

### Reproduces the problem - command or script

python tools\train.py yolov3_d53_mstrain-608_273e_coco.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/rpierau/Code/mmdetection/tools/train.py", line 247, in <module>
    main()
  File "C:/Users/rpierau/Code/mmdetection/tools/train.py", line 236, in main
    train_detector(
  File "C:\Users\rpierau\Code\mmdetection\mmdet\apis\train.py", line 247, in train_detector
    workers_per_gpu=cfg.data.workers_per_gpu,
  File "C:\Users\rpierau\Code\mmdetection\openmmlab\lib\site-packages\mmcv\utils\config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'workers_per_gpu'

### Additional information

I just tried to run a Yolo model with the config file provided by you. I didn't change anything.

**Comment by ZwwWayne** [comment]
Seems like a bug, we will fix it ASAP.
