### ISSUE TITLE
[Bug] Error when performing inference using centernet

### ISSUE THREAD

**Issue by xuqingyu26** [open-mmlab/mmdetection#9732]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

TorchVision: 0.14.1+cu117
OpenCV: 4.7.0
MMCV: 1.7.1
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.7
MMDetection: 2.26.0+

### Reproduces the problem - code sample

python demo/image_demo.py demo/demo.jpg /home/user/PycharmProjects/Detection_Project/mmdetection/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py /home/user/PycharmProjects/Detection_Project/mmdetection/checkpoints/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth --device cpu --out-file result_center.jpg

### Reproduces the problem - command or script

python demo/image_demo.py demo/demo.jpg /home/user/PycharmProjects/Detection_Project/mmdetection/configs/centernet/centernet_resnet18_dcnv2_140e_coco.py /home/user/PycharmProjects/Detection_Project/mmdetection/checkpoints/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth --device cpu --out-file result_center.jpg

### Reproduces the problem - error message

load checkpoint from local path: /home/user/PycharmProjects/Detection_Project/mmdetection/checkpoints/centernet_resnet18_dcnv2_140e_coco_20210702_155131-c8cd631f.pth
/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/datasets/utils.py:66: UserWarning: "ImageToTensor" pipeline is replaced by "DefaultFormatBundle" for batch inference. It is recommended to manually replace it in the test data pipeline in your config file.
  warnings.warn(
Traceback (most recent call last):
  File "demo/image_demo.py", line 68, in <module>
    main(args)
  File "demo/image_demo.py", line 36, in main
    result = inference_detector(model, args.img)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/apis/inference.py", line 157, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/detectors/base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/detectors/base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/detectors/single_stage.py", line 102, in simple_test
    results_list = self.bbox_head.simple_test(
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 360, in simple_test
    return self.simple_test_bboxes(feats, img_metas, rescale=rescale)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/dense_heads/dense_test_mixins.py", line 37, in simple_test_bboxes
    results_list = self.get_bboxes(
  File "/home/user/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 208, in new_func
    return old_func(*args, **kwargs)
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/dense_heads/centernet_head.py", line 288, in get_bboxes
    self._get_bboxes_single(
  File "/home/user/PycharmProjects/Detection_Project/mmdetection/mmdet/models/dense_heads/centernet_head.py", line 338, in _get_bboxes_single
    batch_border = det_bboxes.new_tensor(img_meta['border'])[...,
KeyError: 'border'

**Comment by unbelivable** [comment]
You can try to comment that part of the code and write 'batch_ border=0’like that 


#################################################################
# batch_border = det_bboxes.new_tensor(img_meta['border'])[...,
#                                                          [2, 0, 2, 0]]
        batch_border=0
#################################################################


I solved it this way, but I don't know if there will be other problems
