### ISSUE TITLE
[Bug] when i try to modify L1Loss to GIOU.It saids: Expected 4-dimensional input for 4-dimensional weight [96, 3, 4, 4], but got 5-dimensional input of size [1, 16, 3, 608, 608] instead

### ISSUE THREAD

**Issue by Rogers98** [open-mmlab/mmdetection#9765]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.7.16 (default, Jan 17 2023, 22:20:44) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.6.r11.6/compiler.30794723_0
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2
OpenCV: 4.7.0
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.28.1+c14dd6c

### Reproduces the problem - code sample

here is my config code. I want to modify L1Loss to GIOU/CIOULoss. As shown in line 88 and 
```python

1. model = dict(
2.     type='FasterRCNN',
3.     backbone=dict(
4.         type='SwinTransformer',
5.         embed_dims=96,
6.         depths=[2, 2, 6, 2],
7.         num_heads=[3, 6, 12, 24],
8.         window_size=7,
9.         mlp_ratio=4,
10.         qkv_bias=True,
11.         qk_scale=None,
12.         drop_rate=0.0,
13.         attn_drop_rate=0.0,
14.         drop_path_rate=0.2,
15.         patch_norm=True,
16.         out_indices=(0, 1, 2, 3),
17.         with_cp=False,
18.         convert_weights=True,
19.         init_cfg=dict(
20.             type='Pretrained',
21.             checkpoint=
22.             'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'
23.         )),
24.     neck=dict(
25.         type='FPN',
26.         in_channels=[96, 192, 384, 768],
27.         out_channels=256,
28.         num_outs=5),
29.     rpn_head=dict(
30.         type='RPNHead',
31.         in_channels=256,
32.         feat_channels=256,
33.         anchor_generator=dict(
34.             type='AnchorGenerator',
35.             scales=[8],
36.             ratios=[0.5, 1.0, 2.0],
37.             strides=[4, 8, 16, 32, 64]),
38.         bbox_coder=dict(
39.             type='DeltaXYWHBBoxCoder',
40.             target_means=[0.0, 0.0, 0.0, 0.0],
41.             target_stds=[1.0, 1.0, 1.0, 1.0]),
42.         loss_cls=dict(
43.             type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
44.         loss_bbox=dict(
45.             type='SmoothL1Loss', loss_weight=1.0, beta=0.1111111111111111)),
46.     roi_head=dict(
47.         type='CascadeRoIHead',
48.         bbox_roi_extractor=dict(
49.             type='SingleRoIExtractor',
50.             roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
51.             out_channels=256,
52.             featmap_strides=[4, 8, 16, 32]),
53.         bbox_head=[
54.             dict(
55.                 type='Shared2FCBBoxHead',
56.                 in_channels=256,
57.                 fc_out_channels=1024,
58.                 roi_feat_size=7,
59.                 num_classes=10,
60.                 bbox_coder=dict(
61.                     type='DeltaXYWHBBoxCoder',
62.                     target_means=[0.0, 0.0, 0.0, 0.0],
63.                     target_stds=[0.1, 0.1, 0.2, 0.2]),
64.                 reg_class_agnostic=False,
65.                 loss_cls=dict(
66.                     type='CrossEntropyLoss',
67.                     use_sigmoid=False,
68.                     loss_weight=1.0),
69.                 # I want to modify SmoothL1Loss to GIoULoss here
70.                 # loss_bbox=dict(type='L1Loss', loss_weight=1.0)
71.                 loss_bbox=dict(type='GIoULoss', loss_weight=10.0),
72.                 reg_decoded_bbox=True),
73.             dict(
74.                 type='Shared2FCBBoxHead',
75.                 in_channels=256,
76.                 fc_out_channels=1024,
77.                 roi_feat_size=7,
78.                 num_classes=10,
79.                 bbox_coder=dict(
80.                     type='DeltaXYWHBBoxCoder',
81.                     target_means=[0.0, 0.0, 0.0, 0.0],
82.                     target_stds=[0.1, 0.1, 0.2, 0.2]),
83.                 reg_class_agnostic=False,
84.                 loss_cls=dict(
85.                     type='CrossEntropyLoss',
86.                     use_sigmoid=False,
87.                     loss_weight=1.0),
88.                 # I want to modify SmoothL1Loss to GIoULoss here
89.                 # loss_bbox=dict(type='L1Loss', loss_weight=1.0)
90.                 loss_bbox=dict(type='GIoULoss', loss_weight=10.0),
91.                 reg_decoded_bbox=True)
92.         ],
93.         num_stages=2,
94.         stage_loss_weights=[1, 0.8]),
95.     train_cfg=dict(
96.         rpn=dict(
97.             assigner=dict(
98.                 type='MaxIoUAssigner',
99.                 pos_iou_thr=0.7,
100.                 neg_iou_thr=0.3,
101.                 min_pos_iou=0.3,
102.                 match_low_quality=True,
103.                 ignore_iof_thr=-1),
104.             sampler=dict(
105.                 type='RandomSampler',
106.                 num=256,
107.                 pos_fraction=0.5,
108.                 neg_pos_ub=-1,
109.                 add_gt_as_proposals=False),
110.             allowed_border=-1,
111.             pos_weight=-1,
112.             debug=False),
113.         rpn_proposal=dict(
114.             nms_pre=2000,
115.             max_per_img=2000,
116.             nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05),
117.             min_bbox_size=0),
118.         rcnn=[
119.             dict(
120.                 assigner=dict(
121.                     type='MaxIoUAssigner',
122.                     pos_iou_thr=0.5,
123.                     neg_iou_thr=0.5,
124.                     min_pos_iou=0.4,
125.                     match_low_quality=True,
126.                     ignore_iof_thr=-1),
127.                 sampler=dict(
128.                     type='RandomSampler',
129.                     num=512,
130.                     pos_fraction=0.25,
131.                     neg_pos_ub=-1,
132.                     add_gt_as_proposals=True),
133.                 pos_weight=-1,
134.                 debug=False),
135.             dict(
136.                 assigner=dict(
137.                     type='MaxIoUAssigner',
138.                     pos_iou_thr=0.6,
139.                     neg_iou_thr=0.6,
140.                     min_pos_iou=0.6,
141.                     match_low_quality=False,
142.                     ignore_iof_thr=-1),
143.                 sampler=dict(
144.                     type='RandomSampler',
145.                     num=512,
146.                     pos_fraction=0.25,
147.                     neg_pos_ub=-1,
148.                     add_gt_as_proposals=True),
149.                 pos_weight=-1,
150.                 debug=False)
151.         ]),
152.     test_cfg=dict(
153.         rpn=dict(
154.             nms_pre=1000,
155.             max_per_img=1000,
156.             nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05),
157.             min_bbox_size=0),
158.         rcnn=dict(
159.             score_thr=0.05,
160.             nms=dict(type='soft_nms', iou_threshold=0.5, min_score=0.05),
161.             max_per_img=100)))
162. dataset_type = 'CocoDataset'
163. data_root = '/home/ljs/dataset/visdrone/'
164. img_norm_cfg = dict(
165.     mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
166. train_pipeline = [
167.     dict(type='Resize', img_scale=(600, 600), keep_ratio=False),
168.     dict(type='RandomFlip', flip_ratio=0.5),
169.     dict(
170.         type='Normalize',
171.         mean=[123.675, 116.28, 103.53],
172.         std=[58.395, 57.12, 57.375],
173.         to_rgb=True),
174.     dict(type='Pad', size_divisor=32),
175.     dict(type='DefaultFormatBundle'),
176.     dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
177. ]
178. test_pipeline = [
179.     dict(type='LoadImageFromFile'),
180.     dict(
181.         type='MultiScaleFlipAug',
182.         img_scale=(600, 600),
183.         flip=False,
184.         transforms=[
185.             dict(type='Resize', keep_ratio=False),
186.             dict(type='RandomFlip'),
187.             dict(
188.                 type='Normalize',
189.                 mean=[123.675, 116.28, 103.53],
190.                 std=[58.395, 57.12, 57.375],
191.                 to_rgb=True),
192.             dict(type='Pad', size_divisor=32),
193.             dict(type='ImageToTensor', keys=['img']),
194.             dict(type='Collect', keys=['img'])
195.         ])
196. ]
197. data = dict(
198.     samples_per_gpu=16,
199.     workers_per_gpu=8,
200.     train=dict(
201.         type='MultiImageMixDataset',
202.         pipeline=[
203.             dict(type='Resize', img_scale=(600, 600), keep_ratio=False),
204.             dict(type='RandomFlip', flip_ratio=0.5),
205.             dict(
206.                 type='Normalize',
207.                 mean=[123.675, 116.28, 103.53],
208.                 std=[58.395, 57.12, 57.375],
209.                 to_rgb=True),
210.             dict(type='Pad', size_divisor=32),
211.             dict(type='DefaultFormatBundle'),
212.             dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
213.         ],
214.         dataset=dict(
215.             type='ClassBalancedDataset',
216.             oversample_thr=0.001,
217.             dataset=dict(
218.                 type='CocoDataset',
219.                 ann_file='/home/ljs/dataset/visdrone/annotations/train.json',
220.                 img_prefix='/home/ljs/dataset/visdrone/train/',
221.                 pipeline=[
222.                     dict(type='LoadImageFromFile'),
223.                     dict(type='LoadAnnotations', with_bbox=True)
224.                 ],
225.                 filter_empty_gt=False))),
226.     val=dict(
227.         type='CocoDataset',
228.         ann_file='/home/ljs/dataset/visdrone/annotations/val.json',
229.         img_prefix='/home/ljs/dataset/visdrone/val/',
230.         pipeline=[
231.             dict(type='LoadImageFromFile'),
232.             dict(
233.                 type='MultiScaleFlipAug',
234.                 img_scale=(600, 600),
235.                 flip=False,
236.                 transforms=[
237.                     dict(type='Resize', keep_ratio=False),
238.                     dict(type='RandomFlip'),
239.                     dict(
240.                         type='Normalize',
241.                         mean=[123.675, 116.28, 103.53],
242.                         std=[58.395, 57.12, 57.375],
243.                         to_rgb=True),
244.                     dict(type='Pad', size_divisor=32),
245.                     dict(type='ImageToTensor', keys=['img']),
246.                     dict(type='Collect', keys=['img'])
247.                 ])
248.         ]),
249.     test=dict(
250.         type='CocoDataset',
251.         ann_file='/home/ljs/dataset/visdrone/annotations/val.json',
252.         img_prefix='/home/ljs/dataset/visdrone/val/',
253.         pipeline=[
254.             dict(type='LoadImageFromFile'),
255.             dict(
256.                 type='MultiScaleFlipAug',
257.                 img_scale=(600, 600),
258.                 flip=False,
259.                 transforms=[
260.                     dict(type='Resize', keep_ratio=False),
261.                     dict(type='RandomFlip'),
262.                     dict(
263.                         type='Normalize',
264.                         mean=[123.675, 116.28, 103.53],
265.                         std=[58.395, 57.12, 57.375],
266.                         to_rgb=True),
267.                     dict(type='Pad', size_divisor=32),
268.                     dict(type='ImageToTensor', keys=['img']),
269.                     dict(type='Collect', keys=['img'])
270.                 ])
271.         ]))
272. evaluation = dict(interval=1, metric='bbox')
273. optimizer = dict(
274.     type='AdamW',
275.     lr=0.0001,
276.     betas=(0.9, 0.999),
277.     weight_decay=0.05,
278.     paramwise_cfg=dict(
279.         custom_keys=dict(
280.             absolute_pos_embed=dict(decay_mult=0.0),
281.             relative_position_bias_table=dict(decay_mult=0.0),
282.             norm=dict(decay_mult=0.0))))
283. optimizer_config = dict(grad_clip=None)
284. lr_config = dict(
285.     policy='step',
286.     warmup='linear',
287.     warmup_iters=1000,
288.     warmup_ratio=0.001,
289.     step=[75, 95])
290. runner = dict(type='EpochBasedRunner', max_epochs=100)
291. checkpoint_config = dict(interval=2)
292. log_config = dict(
293.     interval=50,
294.     hooks=[dict(type='TextLoggerHook'),
295.            dict(type='TensorboardLoggerHook')])
296. custom_hooks = [dict(type='NumClassCheckHook')]
297. dist_params = dict(backend='nccl')
298. log_level = 'INFO'
299. load_from = None
300. resume_from = None
301. workflow = [('train', 1)]
302. opencv_num_threads = 0
303. mp_start_method = 'fork'
304. auto_scale_lr = dict(enable=False, base_batch_size=16)
305. img_scale = (600, 600)
306. load_pipeline = [
307.     dict(type='LoadImageFromFile'),
308.     dict(type='LoadAnnotations', with_bbox=True),
309.     dict(
310.         type='Resize',
311.         img_scale=(600, 600),
312.         ratio_range=(1.0, 1.25),
313.         multiscale_mode='range',
314.         keep_ratio=False),
315.     dict(type='FilterAnnotations', min_gt_bbox_wh=(0.01, 0.01)),
316.     dict(type='RandomFlip', flip_ratio=0.5),
317.     dict(type='Pad', size_divisor=32)
318. ]
319. pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'

```

### Reproduces the problem - command or script

```python
python tools/train.py myOwnConfig.py
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/train.py", line 247, in <module>
    main()
  File "tools/train.py", line 243, in main
    meta=meta)
  File "/home/ljs/workspace/mmdetection/mmdet/apis/train.py", line 246, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 60, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/ljs/workspace/mmdetection/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/ljs/workspace/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/ljs/workspace/mmdetection/mmdet/models/detectors/two_stage.py", line 127, in forward_train
    x = self.extract_feat(img)
  File "/home/ljs/workspace/mmdetection/mmdet/models/detectors/two_stage.py", line 67, in extract_feat
    x = self.backbone(img)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljs/workspace/mmdetection/mmdet/models/backbones/swin.py", line 745, in forward
    x, hw_shape = self.patch_embed(x)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljs/workspace/mmdetection/mmdet/models/utils/transformer.py", line 252, in forward
    x = self.projection(x)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ljs/anaconda3/envs/mmdet_vis/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [96, 3, 4, 4], but got 5-dimensional input of size [1, 16, 3, 608, 608] instead

```

### Additional information

1. In this configuration file, I modified the backbone network ResNet to Swin, adding cascade structure cascade. Modifying the previous configuration file can be trained normally. When I try to modify L1Loss to GIOU, I get the above error.
2. I tried feeding the network using a random matrix, but his output was correct
3. Much appreciated for your help

**Comment by ZwwWayne** [comment]
You need to further modify `reg_decoded_bbox=True`. See https://github.com/open-mmlab/mmdetection/blob/master/configs/faster_rcnn/faster_rcnn_r50_fpn_giou_1x_coco.py#L5
