### ISSUE TITLE
[Reimplementation] A bug during I run image_demo.py in semi-supervised object detection

### ISSUE THREAD

**Issue by zys010219** [open-mmlab/mmdetection#9782]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I have trained a soft_teacher model in semi-supervised object detection with configs/soft_techer/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.1-coco.py
training and testing are both good, but when I run image_demo.py with the checkpoints file, an error occurred:

$ python demo/image_demo.py demo/demo.jpg configs/soft_teacher/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.1-coco.py work_dirs/soft-teacher_faster-rcnn_r50-caffe_fpn_180k_semi-0.1-coco/iter_90000.pth --device cpu --out-file result1.jpg
Traceback (most recent call last):
  File "/mistgpu/miniconda/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 51, in __getattr__
    value = super().__getattr__(name)
  File "/mistgpu/miniconda/envs/openmmlab/lib/python3.8/site-packages/addict/addict.py", line 67, in __getattr__
    return self.__getitem__(item)
  File "/mistgpu/miniconda/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 47, in __missing__
    raise KeyError(name)
KeyError: 'backbone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/image_demo.py", line 98, in <module>
    main(args)
  File "demo/image_demo.py", line 42, in main
    model = init_detector(
  File "/home/mist/mmdetection-3.x/mmdet/apis/inference.py", line 55, in init_detector
    elif 'init_cfg' in config.model.backbone:
  File "/mistgpu/miniconda/envs/openmmlab/lib/python3.8/site-packages/mmengine/config/config.py", line 53, in __getattr__
    raise AttributeError(f"'{self.__class__.__name__}' object has no "
AttributeError: 'ConfigDict' object has no attribute 'backbone'

How can I fix it? I need your help, thanks!

### Environment

sys.platform: linux
Python: 3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: Tesla V100-SXM2-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.13.0+cu116
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.4
    - Built with CuDNN 8.3.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.0+cu116
OpenCV: 4.7.0
MMEngine: 0.5.0
MMDetection: 3.0.0rc5+

**Comment by southeastboss** [comment]
I also meet this problem. Perhaps, the cfg of semi-supervised object detection is different. When I use the python tools/analysis_tools/analyze_results.py it raies another bug: AttributeError: 'ConfigDict' object has no attribute 'dataset'

**Comment by zys010219** [comment]
I compared cfg of semi-supervised od and other cfg, it seems that the 'backbone' is in the dict 'model' in other cfg but the 'backbone' is defined in the 'detector' in our ssl cfg. I don't know if it is the problem. Perhaps we need to contact the administrator to ask if semi-supervised learning does not support use tools?

**Comment by ZwwWayne** [comment]
This is a bug. Some functionalities are not fully compatible with Semi-supervised object detection.
For your case, you need to modify the code to check config.model.student.backbone if backbone is not in the key of config.model

**Comment by zys010219** [comment]
> @zys010219 Have you fixed the error yet? I hope to receive your response.

Unfortunately, not yet. Perhaps you can ask workers of mmdetection for some help.
