### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Mumaping** [open-mmlab/mmdetection#985]
`Traceback (most recent call last):
  File "tools/train.py", line 98, in <module>
    main()
  File "tools/train.py", line 78, in main
    train_dataset = build_dataset(cfg.data.train)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/builder.py", line 32, in build_dataset
    dataset = RepeatDataset(build_dataset(cfg['dataset']), cfg['times'])
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/builder.py", line 34, in build_dataset
    dataset = _concat_dataset(cfg)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/builder.py", line 25, in _concat_dataset
    datasets.append(build_dataset(data_cfg))
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/builder.py", line 36, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS)
  File "/home/yangli/jiyuan/mmdetection/mmdet/utils/registry.py", line 74, in build_from_cfg
    return obj_type(**args)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/voc.py", line 14, in __init__
    super(VOCDataset, self).__init__(**kwargs)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/xml_style.py", line 15, in __init__
    super(XMLDataset, self).__init__(**kwargs)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/custom.py", line 63, in __init__
    self.img_infos = self.load_annotations(ann_file)
  File "/home/yangli/jiyuan/mmdetection/mmdet/datasets/xml_style.py", line 29, in load_annotations
    width = int(size.find('width').text)
AttributeError: 'NoneType' object has no attribute 'find'

`
在跑VOC数据集时出现如下错误，排错失败了。希望大神指点一下。数据集是自己的数据集。

**Comment by hellock** [comment]
Please use the `Error report` issue template, and use English or English&Chinese.

**Comment by milleniums** [comment]
所以怎么解决的？

**Comment by philipwelia** [comment]
> Please use the Error report issue template, and use English or English&Chinese.

I had the same problem when I trained with my own dataset :

-  AttributeError: 'NoneType' object has no attribute 'find'

This error happened in **xml_style.py**, so I guess there was something wrong with my data., but I dont know how to fix it.

 I have made my dataset step by step according to online tutorial
