### ISSUE TITLE
lost the computing occluded mask recall

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmdetection#9871]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

my env list：
mmcv-full              1.7.1     
mmdet                  2.28.2    
branch             master

the document in offline evaluation :
first i use：
```
python /opt/mmdetection/tools/test.py /opt/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py /opt/mmdetection/checkpoints/mask_rcnn_r50_fpn_1x_coco_20200205-d4b0c5d6.pth --out results.pkl
```
then i use ：
```
python /opt/mmdetection/tools/analysis_tools/coco_occluded_separated_recall.py results.pkl --out ./work-dir/occluded_separated_recall.json

/opt/mmcv/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
processing detection results...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 120/120, 4350.0 task/s, elapsed: 0s, ETA:     0s
computing occluded mask recall...
[                                                  ] 0/5550, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/opt/mmdetection/tools/analysis_tools/coco_occluded_separated_recall.py", line 44, in <module>
    main()
  File "/opt/mmdetection/tools/analysis_tools/coco_occluded_separated_recall.py", line 37, in main
    metric_res = dataset.evaluate(results)
  File "/opt/mmdetection/mmdet/datasets/coco_occluded.py", line 88, in evaluate
    iou_thr)
  File "/opt/mmdetection/mmdet/datasets/coco_occluded.py", line 134, in evaluate_occluded_separated
    is_occ=True)
  File "/opt/mmdetection/mmdet/datasets/coco_occluded.py", line 191, in compute_recall
    assert cur_img_name in result_dict.keys()
AssertionError
```

**Comment by BIGWangYuDong** [comment]
seems the image is not in the result dict. what code did you change? did you use the coco dataset or your own dataset?

**Comment by pekopoke** [comment]
> 

i used the coco dataset and didn't change my code of branch master

**Comment by BIGWangYuDong** [comment]
kindly ping @RangiLyu have a look

**Comment by BIGWangYuDong** [comment]
You may debug your code, and print `result_dict.keys()` and `cur_img_name` and give us the results
