### ISSUE TITLE
KeyError: 'DINO is not in the model registry. Please check whether the value of `DINO` is correct or it was registered as expected.

### ISSUE THREAD

**Issue by hailyxu** [open-mmlab/mmdetection#9881]
I tried DINO in the 3.x branch, but got this error:
```bash
Traceback (most recent call last):
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 124, in <module>
    main()
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/runner/runner.py", line 401, in __init__
    self.model = self.build_model(model)
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/runner/runner.py", line 794, in build_model
    model = MODELS.build(model)
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/registry/registry.py", line 421, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 240, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/chiebot-cv/anaconda3/envs/mmengine/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DINO is not in the model registry. Please check whether the value of `DINO` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/tutorials/config.html#import-custom-python-modules'
```
which is very confusing, because I just switched to 3.x branch and did not change anything.

I used the following commands to create 3.x conda env:
```bash
conda install pytorch torchvision cudatoolkit=11.3 -c pytorch
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0rc1"
git checkout 3.x
pip install -v -e .
```
And here is the version of some packages:
```bash
mmcv                      2.0.0rc4                 pypi_0    pypi
mmdet                     3.0.0rc6                  dev_0    <develop>
mmengine                  0.6.0                    pypi_0    pypi

pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
```
Anyone knows what's wrong with it? Many thx.

**Comment by hailyxu** [comment]
I tried the config file `ssd300_voc0712.py`, and have a similar error.
This is the sysetm environment and config file :
```bash
03/06 16:12:16 - mmengine - INFO - 
------------------------------------------------------------
System environment:
    sys.platform: linux
    Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) [GCC 10.3.0]
    CUDA available: True
    numpy_random_seed: 1368201644
    GPU 0,1,2,3: NVIDIA GeForce RTX 3090
    CUDA_HOME: /usr/local/cuda
    NVCC: Cuda compilation tools, release 11.2, V11.2.142
    GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    PyTorch: 1.12.1
    PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

    TorchVision: 0.13.1
    OpenCV: 4.6.0
    MMEngine: 0.6.0

Runtime environment:
    cudnn_benchmark: False
    mp_cfg: {'mp_start_method': 'fork', 'opencv_num_threads': 0}
    dist_cfg: {'backend': 'nccl'}
    seed: None
    Distributed launcher: none
    Distributed training: False
    GPU number: 1
------------------------------------------------------------

03/06 16:12:19 - mmengine - INFO - Config:
dataset_type = 'ChiebotXMLDataset'
data_root = ''
file_client_args = dict(backend='disk')
train_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RandomFlip', prob=0.5),
    dict(
        type='RandomChoice',
        transforms=[[{
            'type':
            'RandomChoiceResize',
            'scales': [(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                       (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                       (736, 1333), (768, 1333), (800, 1333)],
            'keep_ratio':
            True
        }],
                    [{
                        'type': 'RandomChoiceResize',
                        'scales': [(400, 4200), (500, 4200), (600, 4200)],
                        'keep_ratio': True
                    }, {
                        'type': 'RandomCrop',
                        'crop_type': 'absolute_range',
                        'crop_size': (384, 600),
                        'allow_negative_crop': True
                    }, {
                        'type':
                        'RandomChoiceResize',
                        'scales': [(480, 1333), (512, 1333), (544, 1333),
                                   (576, 1333), (608, 1333), (640, 1333),
                                   (672, 1333), (704, 1333), (736, 1333),
                                   (768, 1333), (800, 1333)],
                        'keep_ratio':
                        True
                    }]]),
    dict(type='PackDetInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile', file_client_args=dict(backend='disk')),
    dict(type='Resize', scale=(1333, 800), keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor'))
]
train_dataloader = dict(
    batch_size=2,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type='ChiebotXMLDataset',
        data_root='',
        ann_file=
        '/home/chiebot-cv/disk/disk1/xuxin_workspace/data/比赛添加数据/sly_bjbmyw3/data_tmp_train.txt',
        data_prefix='',
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RandomFlip', prob=0.5),
            dict(
                type='RandomChoice',
                transforms=[[{
                    'type':
                    'RandomChoiceResize',
                    'scales': [(480, 1333), (512, 1333), (544, 1333),
                               (576, 1333), (608, 1333), (640, 1333),
                               (672, 1333), (704, 1333), (736, 1333),
                               (768, 1333), (800, 1333)],
                    'keep_ratio':
                    True
                }],
                            [{
                                'type': 'RandomChoiceResize',
                                'scales': [(400, 4200), (500, 4200),
                                           (600, 4200)],
                                'keep_ratio': True
                            }, {
                                'type': 'RandomCrop',
                                'crop_type': 'absolute_range',
                                'crop_size': (384, 600),
                                'allow_negative_crop': True
                            }, {
                                'type':
                                'RandomChoiceResize',
                                'scales':
                                [(480, 1333), (512, 1333), (544, 1333),
                                 (576, 1333), (608, 1333), (640, 1333),
                                 (672, 1333), (704, 1333), (736, 1333),
                                 (768, 1333), (800, 1333)],
                                'keep_ratio':
                                True
                            }]]),
            dict(type='PackDetInputs')
        ]))
val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ChiebotXMLDataset',
        data_root='',
        ann_file=
        '/home/chiebot-cv/disk/disk1/xuxin_workspace/data/比赛添加数据/sly_bjbmyw3/data_tmp_val.txt',
        data_prefix='',
        test_mode=True,
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='Resize', scale=(1333, 800), keep_ratio=True),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                type='PackDetInputs',
                meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                           'scale_factor'))
        ]))
test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type='ChiebotXMLDataset',
        data_root='',
        ann_file=
        '/home/chiebot-cv/disk/disk1/xuxin_workspace/data/比赛添加数据/sly_bjbmyw3/data_tmp_val.txt',
        data_prefix='',
        test_mode=True,
        pipeline=[
            dict(
                type='LoadImageFromFile',
                file_client_args=dict(backend='disk')),
            dict(type='Resize', scale=(1333, 800), keep_ratio=True),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                type='PackDetInputs',
                meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                           'scale_factor'))
        ]))
val_evaluator = dict(
    type='CocoMetric',
    ann_file='data/coco/annotations/instances_val2017.json',
    metric='bbox',
    format_only=False)
test_evaluator = dict(
    type='CocoMetric',
    ann_file='data/coco/annotations/instances_val2017.json',
    metric='bbox',
    format_only=False)
default_scope = 'mmdet'
default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='DetVisualizationHook'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend')]
visualizer = dict(
    type='DetLocalVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    name='visualizer')
log_processor = dict(type='LogProcessor', window_size=50, by_epoch=True)
log_level = 'INFO'
load_from = None
resume = False
model = dict(
    type='DeformableDETR',
    num_queries=300,
    num_feature_levels=4,
    with_box_refine=True,
    as_two_stage=True,
    data_preprocessor=dict(
        type='DetDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        bgr_to_rgb=True,
        pad_size_divisor=1),
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='ChannelMapper',
        in_channels=[512, 1024, 2048],
        kernel_size=1,
        out_channels=256,
        act_cfg=None,
        norm_cfg=dict(type='GN', num_groups=32),
        num_outs=4),
    encoder=dict(
        num_layers=6,
        layer_cfg=dict(
            self_attn_cfg=dict(embed_dims=256, batch_first=True),
            ffn_cfg=dict(
                embed_dims=256, feedforward_channels=1024, ffn_drop=0.1))),
    decoder=dict(
        num_layers=6,
        return_intermediate=True,
        layer_cfg=dict(
            self_attn_cfg=dict(
                embed_dims=256, num_heads=8, dropout=0.1, batch_first=True),
            cross_attn_cfg=dict(embed_dims=256, batch_first=True),
            ffn_cfg=dict(
                embed_dims=256, feedforward_channels=1024, ffn_drop=0.1)),
        post_norm_cfg=None),
    positional_encoding=dict(num_feats=128, normalize=True, offset=-0.5),
    bbox_head=dict(
        type='DeformableDETRHead',
        num_classes=80,
        sync_cls_avg_factor=True,
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=2.0),
        loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        loss_iou=dict(type='GIoULoss', loss_weight=2.0)),
    train_cfg=dict(
        assigner=dict(
            type='HungarianAssigner',
            match_costs=[
                dict(type='FocalLossCost', weight=2.0),
                dict(type='BBoxL1Cost', weight=5.0, box_format='xywh'),
                dict(type='IoUCost', iou_mode='giou', weight=2.0)
            ])),
    test_cfg=dict(max_per_img=100))
optim_wrapper = dict(
    type='OptimWrapper',
    optimizer=dict(type='AdamW', lr=0.0002, weight_decay=0.0001),
    clip_grad=dict(max_norm=0.1, norm_type=2),
    paramwise_cfg=dict(
        custom_keys=dict(
            backbone=dict(lr_mult=0.1),
            sampling_offsets=dict(lr_mult=0.1),
            reference_points=dict(lr_mult=0.1))))
max_epochs = 50
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=50, val_interval=1)
val_cfg = dict(type='ValLoop')
test_cfg = dict(type='TestLoop')
param_scheduler = [
    dict(
        type='MultiStepLR',
        begin=0,
        end=50,
        by_epoch=True,
        milestones=[40],
        gamma=0.1)
]
auto_scale_lr = dict(base_batch_size=32)
launcher = 'none'
work_dir = './work_dirs/deformable-detr-refine-twostage_r50_16xb2-50e_coco'
```
This is the error:
```bash
03/06 16:13:21 - mmengine - WARNING - Failed to import mmdet.visualization, please check the location of the registry visualizer is correct.
Traceback (most recent call last):
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 124, in <module>
    main()
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_v3/lib/python3.9/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/home/chiebot-cv/anaconda3/envs/mmdet_v3/lib/python3.9/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_v3/lib/python3.9/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_v3/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_v3/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
```

**Comment by k1dDing** [comment]
I have a similar error too,after train.py.
03/08 20:11:52 - mmengine - WARNING - Failed to import mmdet.visualization, please check the location of the registry visualizer is correct.
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 113, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by hailyxu** [comment]
> I have a similar error too,after train.py. 03/08 20:11:52 - mmengine - WARNING - Failed to import mmdet.visualization, please check the location of the registry visualizer is correct. Traceback (most recent call last): File "tools/train.py", line 124, in main() File "tools/train.py", line 113, in main runner = Runner.from_cfg(cfg) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg runner = cls( File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in **init** self.visualizer = self.build_visualizer(visualizer) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer return VISUALIZERS.build(visualizer) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg raise KeyError( KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

Did you solve this problem? I created a new conda env, and this error just disappeared. Then I write a new dataset, and a similar registry error occured.

**Comment by hailyxu** [comment]
I unexpectedly solved this problem by creating a new environment, and then I writed a new dataset, but a new similar error occured.

1. The dataset code is as follows:

```python
from .xml_style import XMLDataset
from mmdet.registry import DATASETS
    
@DATASETS.register_module()
class ChiebotXmlDataset(XMLDataset):
    pass
```

2. The `__init__.py` is as follows:
```python
# Copyright (c) OpenMMLab. All rights reserved.
from .base_det_dataset import BaseDetDataset
from .cityscapes import CityscapesDataset
from .coco import CocoDataset
from .coco_panoptic import CocoPanopticDataset
from .crowdhuman import CrowdHumanDataset
from .dataset_wrappers import MultiImageMixDataset
from .deepfashion import DeepFashionDataset
from .lvis import LVISDataset, LVISV1Dataset, LVISV05Dataset
from .objects365 import Objects365V1Dataset, Objects365V2Dataset
from .openimages import OpenImagesChallengeDataset, OpenImagesDataset
from .samplers import (AspectRatioBatchSampler, ClassAwareSampler,
                       GroupMultiSourceSampler, MultiSourceSampler)
from .utils import get_loading_pipeline
from .voc import VOCDataset
from .wider_face import WIDERFaceDataset
from .xml_style import XMLDataset
from .chiebot_xml import ChiebotXmlDataset

__all__ = [
    'XMLDataset', 'CocoDataset', 'DeepFashionDataset', 'VOCDataset',
    'CityscapesDataset', 'LVISDataset', 'LVISV05Dataset', 'LVISV1Dataset',
    'WIDERFaceDataset', 'get_loading_pipeline', 'CocoPanopticDataset',
    'MultiImageMixDataset', 'OpenImagesDataset', 'OpenImagesChallengeDataset',
    'AspectRatioBatchSampler', 'ClassAwareSampler', 'MultiSourceSampler',
    'GroupMultiSourceSampler', 'BaseDetDataset', 'CrowdHumanDataset',
    'Objects365V1Dataset', 'Objects365V2Dataset', 'ChiebotXmlDataset'
]
```

3. The error is as follows:
```bash
 -------------------- 
Traceback (most recent call last):
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/runner/loops.py", line 43, in __init__
    super().__init__(runner, dataloader)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1333, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'ChiebotXmlDataset is not in the dataset registry. Please check whether the value of `ChiebotXmlDataset` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 124, in <module>
    main()
  File "/home/chiebot-cv/project/mmdet222/Orignal_mmdet/tools/train.py", line 120, in main
    runner.train()
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1656, in train
    self._train_loop = self.build_train_loop(
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1448, in build_train_loop
    loop = LOOPS.build(
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/chiebot-cv/anaconda3/envs/mmdet_test/lib/python3.9/site-packages/mmengine/registry/build_functions.py", line 135, in build_from_cfg
    raise type(e)(
KeyError: "class `EpochBasedTrainLoop` in mmengine/runner/loops.py: 'ChiebotXmlDataset is not in the dataset registry. Please check whether the value of `ChiebotXmlDataset` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"
```

Does anyone know what's wrong with it? Thanks a lot for your reply.

**Comment by k1dDing** [comment]
> > I have a similar error too,after train.py. 03/08 20:11:52 - mmengine - WARNING - Failed to import mmdet.visualization, please check the location of the registry visualizer is correct. Traceback (most recent call last): File "tools/train.py", line 124, in main() File "tools/train.py", line 113, in main runner = Runner.from_cfg(cfg) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg runner = cls( File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in **init** self.visualizer = self.build_visualizer(visualizer) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer return VISUALIZERS.build(visualizer) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build return self.build_func(cfg, *args, **kwargs, registry=self) File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg raise KeyError( KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'
> I recreate a new env too ,and this issue disappeared. I write a new coco format dataset training normally.
> Did you solve this problem? I created a new conda env, and this error just disappeared. Then I write a new dataset, and a similar registry error occured.

I recreate a new env too ,and this issue disappeared. I write a new coco format dataset training normally.

**Comment by fearless-pilgrim** [comment]
I fix this problem by adding:

sys.path.append("path to your dino folders")
import dinov2.eval.segmentation.models
