### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by k1dDing** [open-mmlab/mmdetection#9914]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

3.x branch https://github.com/open-mmlab/mmdetection/tree/3.x

### Environment

System environment:
    sys.platform: linux
    Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
    CUDA available: True
    numpy_random_seed: 460692009
    GPU 0: GeForce RTX 2080
    CUDA_HOME: /usr/local/cuda-10.2
    NVCC: Cuda compilation tools, release 10.2, V10.2.8
    GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    PyTorch: 1.9.0
    PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

    TorchVision: 0.10.0
    OpenCV: 4.7.0
    MMEngine: 0.6.0

### Reproduces the problem - code sample

 python tools/train.py configs/rtmdet/rtmdet_l_8xb32-300e_coco.py 

### Reproduces the problem - command or script

 python tools/train.py configs/rtmdet/rtmdet_l_8xb32-300e_coco.py 

### Reproduces the problem - error message

mmengine - WARNING - Failed to import mmdet.visualization, please check the location of the registry visualizer is correct.

Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main()
  File "tools/train.py", line 114, in main
    runner = Runner.from_cfg(cfg)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 431, in from_cfg
    runner = cls(
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 385, in __init__
    self.visualizer = self.build_visualizer(visualizer)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 767, in build_visualizer
    return VISUALIZERS.build(visualizer)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/ding/.conda/envs/mm3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'DetLocalVisualizer is not in the visualizer registry. Please check whether the value of `DetLocalVisualizer` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by parakh08** [comment]
I am also facing the same issue.

**Comment by k1dDing** [comment]
I recreate the same environment ,then this issue is solved fortunately.

**Comment by k1dDing** [comment]
> I am also facing the same issue.

I recreate the same environment ,then this issue is solved fortunately.

**Comment by parakh08** [comment]
> > I am also facing the same issue.
> 
> I recreate the same environment ,then this issue is solved fortunately.

That actually helped, thanks a lot!

**Comment by GeorgePearse** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/47161914/229379760-316f8bec-e8bd-47f4-9317-e9ed9bb921c5.png">

**Comment by fat-921** [comment]
配置上需要加上`default_scope = 'mmdet'`,不然就会报这个错

**Comment by chenluxin-git** [comment]
> 配置上需要加上`default_scope = 'mmdet'`，不然就会报这个错

May I ask which file was added in

**Comment by GeorgePearse** [comment]
@chenluxin-git  this goes at the root level of the config, 

e.g. could be:
```python
cfg.default_scope = 'mmdet'
```

**Comment by EnzoWuu** [comment]
> 配置上需要加上`default_scope = 'mmdet'`,不然就会报这个错

thanks, it works!
