### ISSUE TITLE
Cannot run train.py since meets bugs. 

### ISSUE THREAD

**Issue by zhuwano1** [open-mmlab/mmdetection#9961]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

Traceback (most recent call last):
  File "D:\artificial_diskD_gp\artificial_itelligence\mmdetection-master_new\mmdetection-master\mmdet\utils\collect_env.py", line 2, in <module>
    from mmcv.utils import collect_env as collect_base_env
ImportError: cannot import name 'collect_env' from 'mmcv.utils' (unknown location)

### Reproduces the problem - code sample

in pycharm, just give this deformable detr config file to train.py.

### Reproduces the problem - command or script

same code as newest version. train.py

### Reproduces the problem - error message

if I run: pip install mmcv-full==1.7.1 （while not install mmcv，lots of people say should do this）
AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc0, <2.1.0.

if i uninstall mmcv-full and   pip install mmcv==2.0.0rc1
Traceback (most recent call last):
  File "D:\artificial_diskD_gp\artificial_itelligence\mmdetection-master_new\mmdetection-master\tools\train.py", line 12, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (unknown location)

How can I do to solve this problem? which pkg and version should I install? my torch version is 1.13.1 and cuda version is Cuda11.7? Also, which mmdet version  I should install? 

### Additional information

who can help me

**Comment by RangiLyu** [comment]
What is the mmdetection version you are using? mmdet 3.x requires mmcv>=2.0.0rc0. But if you are using mmdetection 2.x, which is the master branch as you mentioned in this issue, mmcv-full==1.7.1 is correct.

**Comment by aaronlsmiles** [comment]
> ### Prerequisite
> * [x]  I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
> * [x]  I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
> * [x]  The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).
> 
> ### Task
> I'm using the official example scripts/configs for the officially supported tasks/models/datasets.
> 
> ### Branch
> master branch https://github.com/open-mmlab/mmdetection
> 
> ### Environment
> Traceback (most recent call last): File "D:\artificial_diskD_gp\artificial_itelligence\mmdetection-master_new\mmdetection-master\mmdet\utils\collect_env.py", line 2, in from mmcv.utils import collect_env as collect_base_env ImportError: cannot import name 'collect_env' from 'mmcv.utils' (unknown location)
> 
> ### Reproduces the problem - code sample
> in pycharm, just give this deformable detr config file to train.py.
> 
> ### Reproduces the problem - command or script
> same code as newest version. train.py
> 
> ### Reproduces the problem - error message
> if I run: pip install mmcv-full==1.7.1 （while not install mmcv，lots of people say should do this） AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=2.0.0rc0, <2.1.0.
> 
> if i uninstall mmcv-full and pip install mmcv==2.0.0rc1 Traceback (most recent call last): File "D:\artificial_diskD_gp\artificial_itelligence\mmdetection-master_new\mmdetection-master\tools\train.py", line 12, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (unknown location)
> 
> How can I do to solve this problem? which pkg and version should I install? my torch version is 1.13.1 and cuda version is Cuda11.7? Also, which mmdet version I should install?
> 
> ### Additional information
> who can help me

How did you solve this? I am facing similar error.

**Comment by hotelbread** [comment]
Me either... 

i faced this error message

Traceback (most recent call last):
  File "tools/train.py", line 12, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (unknown location)

and I used these version.
mmcv-full==1.7.1
mmdet==2.26.0
mmengine==0.7.3

please help me...

**Comment by QingfanHou** [comment]
I solved the problem through the following steps, hope it can help you.
pip install openmim
mim install mmcv-full==1.5.1
mim install mmdet == 2.24.1
You can replace the version number you need.

**Comment by GenMoat** [comment]
Make sure you don't have mmcv and mmcv-full installed at the same time (uninstall mmcv, just leave mmcv-full), and follow the comment from @QingfanHou . This works for me.
