### ISSUE TITLE
[Bug] mim install mmdet

### ISSUE THREAD

**Issue by ZitengXue** [open-mmlab/mmdetection#9995]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

python3.9

### Reproduces the problem - code sample

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rxd88cxj/mmcv-full_671a87edfa0a481c85ed9289e3261c9d/setup.py", line 20, in <module>
          from torch.utils.cpp_extension import BuildExtension
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

### Reproduces the problem - command or script

mim install mmdet

### Reproduces the problem - error message

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rxd88cxj/mmcv-full_671a87edfa0a481c85ed9289e3261c9d/setup.py", line 20, in <module>
          from torch.utils.cpp_extension import BuildExtension
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/xzt/miniconda3/envs/mmdet/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by LZX-178** [comment]
Instead of using the ssh server, run commands directly on the server

**Comment by MrPeterJin** [comment]
I also encountered this problem. Please fix this bug.

**Comment by ERGOWHO** [comment]
I have the same problem! it works well previously not sure why.

**Comment by jistiak** [comment]
I had the same issue. This hack solved the problem for me. But same as him, I don't know why it works-

https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/130#issuecomment-1628591076
